project:
  type: book
  output-dir: docs

book:
  title: "聖書の学び"
  author: "鈴木寛（Hiroshi Suzuki）"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - aboutmark.qmd
    - markdq.qmd
    - markdq-old.qmd
    - lukedq-old.qmd
    - matthewdq-old.qmd
    - johndq-old.qmd
    - summary.qmd
    - tables.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    pdf-engine: xelatex
    documentclass: bxjsreport #scrreprt
    classoption: xelatex, ja=standard
    number-sections: true
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{longtable}

editor: visual

