# 使徒言行録（2008-2011） {#actsdq-old}

質問票（8章以降のみ）：ディスカッション・クエスチョン（[PDF](https://icu-hsuzuki.github.io/science/bible/bs/acts2008.pdf)）

## 使徒言行録を学んで行くにあたって {#aboutacts .unnumbered}

使徒言行録（使徒行伝, Acts）は、パウロの伝道旅行に伴って行った医者ルカ（コロサイ4:14）によると言われている。４福音書の一つルカによる福音書の著者で四福音書の中では、唯一の異邦人（非ユダヤ人）。２世紀の伝承では、シリアのアンティオケの生まれだと言われている。ルカについては、上記の箇所以外聖書には2度現れる。ピレモン２４, II テモテ４：１１。

-   テキストから何が分かるかを中心に学びましょう。

-   著者が何を伝えたいと思っているかを中心に学びましょう。

## 使徒言行録 第1章

### 使徒言行録 Acts 1:1--11

-   ルカの福音書と書との働きとは、ルカが初期の教会の出来事を記録してその 1, 2 巻として書いたものです。良書尾序言（ルカ1:1--4, 使徒1:1--5）を読みましょう。a. この報道の資料の出所と記述の目的をルカはどのように述べていますか。b. この二つの文書の受取人について、どんなことがわかりますか。

-   

    a.  1:1-11 の情報しかないとしたら、イエスについてどんなこｔがわかりますか、あげてみましょう。b. ルカはイエスの復活の真実性をどのように強調していますか。

-   

    a.  復活したイエスは、弟子になにを命じますか（4節）b. イエスはこの命令にどんな約束を加えますか。c. この箇所とマルコ1:6--8, ルカ24:49 を比べてみましょう。

### 使徒言行録 Acts 1:12--36

## 使徒言行録 第2章

### 使徒言行録 Acts 2:1-13

-   

    a.  ペンテコステの日に起きたことを順を追ってあげていきましょう。b. \`\`ような'' （2, 3 節）ということばは、聖霊の来臨について何を湿していますか。c. そのことは、弟子たちにまずどんな結果となって現れますか。（4節）

-   

    a.  どんな人々が集まっていますか。b. 傍観者たちはなぜ驚くのですか。c. 聴衆はどんな内容の話を聞いていますか。d.それぞれどんな反応を示しますか。e. 今日、人は神の力と栄光の証明を見ると、どんな反応をしますか、なぜですか。

-   

    a.  ペンテコステの日にそこに居合わせて人々の出身地を地図（40, 41ページ）で探してみましょう。b. このことはキリストの教えの広まりに、どんな影響をするでしょうか。

### 使徒言行録 Act 2:14-21

-   

    a.  ペテロは目前で起きた出来事をどう説明していますか

### 使徒言行録 Act 2:22-36

### 使徒言行録 Act 2:37-47

## 使徒言行録 第3章

### 使徒言行録 Act 3:1-10

### 使徒言行録 Act 3:11-26

## 使徒言行録 第4章

### 使徒言行録 Act 4:1-22

### 使徒言行録 Act 4:23-31

### 使徒言行録 Act 4:32-47

## 使徒言行録 第5章

### 使徒言行録 Act 5:1-11

### 使徒言行録 Act 5:12-26

### 使徒言行録 Act 5:27-42

## 使徒言行録 第6章

### 使徒言行録 Act 6:1-7

### 使徒言行録 Act 6:8-15

## 使徒言行録 第7章

### 使徒言行録 Act 7:1-53

### 使徒言行録 Act 7:54-60

## 使徒言行録 第8章

### 使徒言行録 Acts 8:1--25

-   ステファノの事件をきっかけに起こった大迫害によってどのようなことが起こりましたか。What happened by the persecution following Stephen's martyrdom?

-   なぜ散らされていった人たちはみことばをのべつたえるのでしょうか。Why did those who scattered preached the word wherever they went?

-   シモンについてどのようなことがわかりますか。What can you tell about Simon in verse 9?

-   ペテロとヨハネは何のためにサマリヤに来たのでしょうか。Why did Peter and John come to Samaria?

-   シモンは何をほしかったのでしょうか。What do you think Simon wanted to have?

-   シモンの何が神の前に正しくないのでしょうか。What is not right in Simon before God?

### 使徒言行録 Acts 8:26-40

-   ピリポが遣わされたのはどのような人ですか。Who was Philip sent to?

-   ピリポはどうしますか。How did Philip approach him?

-   なぜこの人は、バプテスマを受けたいと思ったのでしょう。Why did he want to be baptized?

-   なぜ主の霊はピリポをさらっていったのでしょうか。Why did the Sprit of the Lord took Philip away?

## 使徒言行録（使徒行伝, Acts）　第9章

### 使徒言行録 Acts 9:1--19

-   これまでにサウロについてわかっていることを復習しましょう。Review what is known about Saul. (7:58-8:3)

-   なぜサウロは教会をこれまで激しく迫害するのでしょうか。Why does Saul try to destroy the church?

-   サウロはダマスコ途上でどのような経験をしますか。What does Saul experience on the way to Damascus?

-   アナニヤはどのような働きをしますか。What does Ananias do to Saul?

-   サウロの回心にとって鍵となったことはどのようなことでしょうか。What are the keys to Saul's conversion?

### 使徒言行録 Acts 9:20--31

-   v19b--25 の記述からダマスコにおけるその後のサウロについてどんなことがわかりますか。What can you find about Saul in Damascus after his conversion?

-   サウロのメッセージの中心は何ですか。What is the message of Saul there?

-   サウロはエルサレムでどのような事を経験しますか。What does Saul experience in Jerusalem?

-   v31 の教会についての記述から何がわかりますか。What can you tell about Church described in v31?

### 使徒言行録 Acts 9:32--43

-   リダ（ルダ）でペテロはどのような人をどのようにいやしますか。Who and how does Peter heal in Lydda?

-   タビタについてどんなことがわかりますか。What can you tell about Tabitha?

-   二つの記事からどのようなことがわかりますか。What do you learn from these?

## 使徒言行録（使徒行伝, Acts）　第10章

### 使徒言行録 Acts 10:1--23

-   コルネリウスについてどんなことがわかりますか。What can you find about Cornelius?

-   コルネリウスはどのような信仰を持っていたと思いますか。How do you describe Cornelius' faith?

-   ペテロは心中で何と戦っていますか。What is Peter fighting against in his heart?

-   神はどのように働いておられますか。How is God working here?

### 使徒言行録 Acts 10: 23--33

-   ペテロには、結局どうしますか、また、だれが同行しますか。What does Peter do? Who accompany Peter?

-   コルネリオはどのようにしてペテロたちを迎えますか。How does Cornelius welcome Peter?

-   彼らの出会いは、特別に準備されたことだと知ることは、ふたりにとってどんな意味がありますか。What does it mean to Peter and Cornelius that God is working behind?

### 使徒言行録 Acts 10:34--48

-   ペテロにが強調していることはどんなことですか。What is the main points of Peter's message?

-   人はどのようにして罪のゆるしをうけるのですか。How can a man receive forgiveness of sins?

-   「異邦人にも」ということはなぜそれほど重要なのでしょうか。Why is it important that the Holy Sprit is poured out 'even on the Gentiles'?

## 使徒言行録（使徒行伝, Acts）　第11章

### 使徒言行録 Acts 11:1--18

-   異邦人が神の言葉を受け入れたと聞いたときの使徒や兄弟たちの反応はどのようなものでしたか。How did the apostles and the brothers react when they heard that Gentiles had received the word of God.

-   なぜ素直に喜ぶことができないのでしょうか。Why did they fail to accept the news with joy?

-   ペテロは非難に対してどのように説明していますか。How did Peter explain it to them?

-   結果はどのようなものだったでしょう。What was the outcome?

### 使徒言行録 Acts 11:19--30

-   この時点まで福音が広まっていった過程を段階ごとに確認してみましょう。Review how the gospel prevailed up until this time step by step.

-   エルサレム教会はなぜ、バルナバをアンテオキアに派遣したのでしょうか。Why did the the church at Jerusalem send Barnabas to Antioch?

-   バルナバはアンテオキアでどのような働きをしますか。What did Barnabas do in Antioch?

-   バルナバはなぜパウロをアンテオキアに連れて行くのでしょうか。Why did Barnabas brought Saul to Antioch?

-   クラウディウス帝の時に起こった飢饉についてどのようなことが記されていますか。What is recorded about the famine during the reign of Claudius?

### バルナバとサウロ - Barnabas and Saul\\\\ Acts 11:25, 26, 30

1.  Acts 4:36-37

2.  Acts 7:58-8:3

3.  Acts 9:1-30

#### 使徒12章以後のバルナバ - Barnabas after Acts 12

Acts 12:25, 13:1-4, 7, 9, 14, 42, 50, 14:1, 12, 14, 20, 15:2, 12, 22, 25-26, 35-40, 1Cor 9:6, Gal 2:1, 9, 13, Col 4:10[^actsdq-old-1]

[^actsdq-old-1]: Acts 使徒言行録, 1 Cor コリント人への第一の手紙, Gal ガラテヤ人への手紙, Col コロサイ人への手紙

## 使徒言行録（使徒行伝, Acts）　第12章

### 使徒言行録 Acts 12:1--19

-   これまでの迫害について復習してみましょう。Review the persecutions against the disciples. (Acts 4:1--31, 5:17--32, 6:8--15, 7:54--60, 8:1--3)

-   ヘロデが弟子たちを迫害した理由は何だったでしょうか。What is the reason Hedod persecuted the disciples?

-   ペテロはいつ、どのようにして救い出されますか。When and how was Peter rescued?

-   ペテロがマリヤの家に着いたとき、人々はなにをしていますか。What were the disciples doing when Peter visited the house of Mary?

-   なぜこれほどまでに驚いているのでしょうか。Why were they surprised so much?

-   奇跡的なペテロの救出の結果、さらにどんなことが起こりますか。What followed after the Peter's miraculous rescue? (v18, 19)

### 使徒言行録 Acts 12:20--25

-   ヘロデはなぜ主の使いに打たれたのでしょう。Why was Herod struck by the angel of the Lord?

-   この章の最後にどのようなことが記されていますか。What is recorded at the closing of this chapter? (v24, 25)

## 使徒言行録（使徒行伝, Acts）　第13章

### 使徒言行録 Acts 13:1--3

-   アンティオキアの教会はどのような教会で、どのような人たちがいますか。List the members of the church at Antioch.

-   バルナバとサウロはどのようにして宣教旅行に出発しますか。How do Barnabas and Saul start their mission trip?

### 使徒言行録 Acts 13:4-12

-   彼らは第一回伝道旅行を、どこから始めますか。何か理由が考えられますか。Which city do they visit first? Why?

-   なぜ、最初にはユダヤ人の会堂を訪ねるのでしょうか。またそこにはどのような人がいますか。Why do they visit the synagogue first? Who do they meet there?

-   パフォスではどのようなことが起こりますか。What happens in Paphos?

-   サウロはエルマがしていることをどのように咎めていますか。How does Saul accuse Elymas?

-   その結果どうなりますか。What is the outcome?

### 使徒言行録 Acts 13:13-43

-   v13 のヨハネはどのような人ですか。なぜ、エルサレムに帰ってしまうのでしょう。Who is John in v13? Why do you think he returns to Jerusalem?

-   パウロの説教の中で、歴史の中で神はどのようなことをして下さったと語っていますか。How does Paul describe God's action in history?

-   バプテスマのヨハネのしたことは、どんなことだと言っていますか。What is Paul's claim on John the Baptist?

-   パウロは、ダビデとイエスについてどのようなことを言っていますか。What does Paul say about David and Jesus?

-   パウロの説教の要点は何でしょうか。What is the point of Paul's message?

-   パウロの説教の結果、どのようなことが起こりますか。What is the outcome of Paul's message?

-   ユダヤ人はどんな反応をしますか。なぜですか。What is the Jews' response? Why?

-   異邦人は、どんな反応をしますか。What is the gentile's response?

-   アンティオケアでの宣教の結果はどうでしたか。あなたはどう評価しますか。How do you assess the result of the ministry in Antioch?

## 使徒言行録 Acts 第14章

### 使徒言行録 Acts 14:1--7

-   イコニオンでのことをまとめてみましょう。

Summarize what happened in Iconium.

-   なぜこのような激しい分裂が起こるのでしょうか。

Why were the people of the city divided?

### 使徒言行録 Acts 14:8--20

-   生まれつき足いひとがいやされたことについてどう記されていますか。

What is recorded about the healing of a crippled man from birth?

-   リストラの人々はパウロの行ったことを見てどのように反応しますか。

How did the people of Lystra react to what Paul did?

-   これに対して、パウロはどのようなメッセージを語っていますか。

How did Paul respond to them?

-   アンティオキアとイコニオンから来たユダヤ人たちはどのような事をしますか。

What did the Jews from Antioch and Iconium did?

### 使徒言行録 Acts 14:21--28

-   二人がどのような道をとおり、何をしながらアンティオキアまで戻っていきましたか。

What did Paul and Barnabus do on their way back to Antioch?

-   二人はアンティオキアでどのような報告をしましたか。

What was the report of the two in Antioch?

## 使徒言行録（使徒行伝, Acts）　第15章

### 使徒言行録 Acts 15:1--5

-   アンテオケ教会ではどのような問題が持ち上がりますか。What is the problem at the church of Antioch?

-   どのような提案が為されますか。What was proposed to solve the problem?

-   3節のフェニキアとサマリヤアの兄弟たちと 5節のファリサイ派から信仰に入った人たちの反応からどのような事がわかりますか。What can you tell from the reactions of the brothers in Phenicia and Samaria in v3 and those of the believers belonged to the Pharisees in v5 ?

### 使徒言行録 Acts 15:6--21

-   エルサレムでの会議にはどのような人たちが出席していますか。Who attend the counsil in Jerusalem?

-   ペテロの発言の要点をまとめてみましょう。Summarize the points Peter presented.

-   「主の恵みによって救われる」とはどういう事でしょうか。What does it mean to be saved through the grace of our Lord?

-   パウロとバルナバはどのような役割を果たしていますか。What is the role of Paul and Barnabus at the meeting.

-   ヤコブの発言の要点をまとめてみましょう。Summarize the points James presented?

-   三つの規則を異邦人に求めていますが、それはどのような目的があったと思いますか。What is the reason the gentiles should observe the three regulations.

### 使徒言行録 Acts 15:22--35

-   会議の結果を書面にし、かつユダとシラスも派遣することにしますが、それはなぜでしょうか。Why do they send Jude and Silas with the document agreed at the meeting?

-   手紙からはどのようなことがわかりますか。What can you tell from the document?

-   この手紙はアンテオケの人々にどのように迎えられますか。How does the church in Antioch receive the message.

### 使徒言行録 Acts 15:36--41

-   パウロはどのような提案をしますか。What does Paul propose to Barnabas?

-   パウロとバルナバの意見が食い違うのは何が原因ですか。Why cannot they agree?

-   結局どうすることになりますか。What do they choose to do?

## 使徒言行録（使徒行伝, Acts）　第16章

### 使徒言行録 Acts 16:1--5

-   ルステラでは以前どのような事がありましたか。What had happened in Lystra? (14:8-23)

-   テモテはどのような人ですか。What can you tell about Timothy?

-   一方でエルサレムでの決定を伝えながら、なぜテモテに割礼を受けさすのでしょうか。Why do you think Paul circumcised Timothy?

### 使徒言行録 Acts 16:6--15

-   パウロたちはどのような経緯でマケドニアに向かうことにしますか。How did Paul decide to leave for Macedonia?

-   ピリピはどんな町ですか。What can you tell about the city Philippi?

-   ルデヤの回心についてどんなことがわかりますか。How do you describe Lydia's Conversion?

### 使徒言行録 Acts 16:16--34

-   女奴隷はどのようにして変えられますか。そしてそのことでどんな事件がおきますか。How was a slave girl changed?

-   牢獄でどのようなことがおきますか。What had happened in the prison?

-   看守は何をおそれ、そしてどんな救いを得ますか。What was the jailer afraid of and what did he receive for his salvation?

### 使徒言行録 Acts 16:35--40

-   なぜパウロは長官たちが謝罪することを要求したのでしょうか。Why did Paul demanded the magistrates to apologize?

-   ルデヤと女奴隷と看守に神はどのように働いていますか。How God was working for Lydia, the slave girl and the jailer?

## 使徒言行録（使徒行伝, Acts）　第17章

### 使徒言行録 Acts 17:1--9

-   テサロニケでの働きとピリピでの働きとを比べてみましょう。違いは何ですか。What are the differences of Paul's ministry in Thessalonica and in Philippi?

-   パウロはどのようなメッセージを伝えますか。What is Paul's message?

-   結果としてどのようなことが起こりますか。What are the consequences?

-   何が原因で何を理由として訴えますか。訴えた人たちが大切にしていたものは何でしょうか。Why and by what reason, the people sue Jason and others? What do they want to protect?

### 使徒言行録 Acts 17:10--15

-   ベレアはテサロニケとはどんな点で違っていますか。What is different in Berea compared with Thessalonica?

-   テサロニケのユダヤ人たちがベレヤにも押しかけてくるのはなぜでしょうか。Why the Jews in Thessalonica run after Paul to Berea?

### 使徒言行録 Acts 17:16--34

-   パウロはアテネでどのような人たちに話しかけていますか。Who does Paul talk to in Athens?

-   パウロからどんな話しを聞きたかったのでしょうか。What do they want to hear from Paul?

-   パウロのアテネでのメッセージ (v22-31) について気づいたことを挙げてみましょう。List what you notice in Paul's message in Athens.

-   パウロは神についてどのようなことを述べていますか。What does Paul tell about God?

-   パウロはアテネの人たちに、どうすることを求めていますか。What does Paul urge those who hear the message to do?

-   結果はどうでしたか。What was the outcome?

## 使徒言行録（使徒行伝, Acts）　第18章

### 使徒言行録 Acts 18:1--11

-   アクラとプリスキラはどのような人たちですか。Who and what are Aquila and Priscilla?

-   パウロはコリントでどのような活動をしていますか。What is Paul doing in Corinth?

-   パウロの 6節の言葉をあなたはどう受け取りますか。What do you think about Paul's words in verse 6?

-   パウロにどのような激励を受けますか。How is Paul encouraged?

### 使徒言行録 Acts 18:12--22

-   パウロは誰にどのような理由で訴えられていますか。Who accuses Paul to the proconsul, and by what reason?

-   どうなりますか。What is the result?

-   パウロはコリントを発ってどこへ向かいますか。Where does Paul go after Corinth?

### 使徒言行録 Acts 18:23--28

-   アポロについてどんなことがわかりますか。What can you tell about Apollos?

-   プリスキラとアクラそして、弟子達はアポロにどのように接しますか。How do Priscilla, Aquila and other disciples treat Apollos?

-   アポロのその後についてどんなことがわかりますか。What can you tell about Apollos after he leaves Ephesus?

## 使徒言行録（使徒行伝, Acts）　第19章

### 使徒言行録 Acts 19:1--20

-   パウロはエペソでどのような弟子達と会いますか。What kind of disciples does Paul meet in Ephesus?

-   パウロはバプテスマのヨハネの働きについてどのように述べていますか。How does Paul explain the ministry of John the Baptist?

-   この弟子達にどのような変化が起きますか。What happens to the disciples when Paul places his hands on them?

-   vs 8--10 からパウロの活動について何がわかりますか。What can you tell about the activities of Paul in Ephesus?

-   魔術を行っていた人々にどのようなことが起きますか。What happens to those who are practicing sorcery?

-   魔術の本を焼くことはこの人たちにとってどのような意味があったのでしょうか。Why do they burn their scrolls?

### 使徒言行録 Acts 19:21--41

-   パウロはどのような計画をたて、そのためにどんな事をしますか。(vs 21--22) What does Paul plan to do and what preparation does he do?

-   どのような騒動が起きますか。その理由は何ですか。What disturbance about the Way arises and what is the reason?

-   なぜそれほどまでに群衆は腹を立てたのでしょうか。Why do the multitude become so furious?

-   アレキサンデルはどんな役割を持って群衆に話そうとしたと思いますか。What is the role of Alexander and what do you think he tries to communicate?

-   役人はどのようにして群衆を解散させますか。How does the officer dismiss the multitude?

## 使徒言行録（使徒行伝, Acts）　第20章

### 使徒言行録 Acts 20:1--12

-   エペソからトロアスまでのパウロの旅行の跡をたどりましょう。(Trace the route of Paul's journey from Ephesus to Troas.)

-   この時代のキリスト者に必要だった励ましの言葉はどのようなものだったと思いますか。(What encouragements do young Christisna need that time?) (v1, 2)

-   トロアスでは、何曜日に、何を目的として集まっていますか。(What day of the week and for what purpose do they get together in Troas?)

-   トロアスからの出発の日の前夜どのような事が起こりますか。(What happens on the day before Paul set out to Syria?)

### 使徒言行録 Acts 20:13--38

-   パウロの旅程をたどってみましょう。パウロはどんな理由で旅路を急ぐのですか。(Trace the route of Paul's journey. Why is Paul in a hurry?)

-   8-35節のパウロのメッセージは、誰に対して、どのような状況で、何を伝えるために、なされたのでしょうか。(What is the purpose, the background and the main listener of the Paul's message in 18-35?)

-   以下のことについてまとめてみましょう。(Summarize the following.)

1.  パウロのエペソでの活動について。(Paul's activities in Ephesus.) (v18-21)

2.  パウロの態度と目的。(Paul's manner and aim.) (19, 20, 26, 27, 33-35)

3.  パウロのメッセージ。(Paul's message.) (21, 24, 25, 27)

4.  パウロの伝道の方法。(Paul's methods of evangelism.) (20, 21, 25, 34, 35)

5.  パウロの直面した困難。(Faced difficulties.) (19)

-   パウロが大切にした究極の目的は何だったのでしょうか。(What is the goal of Paul's life?)

-   パウロは自分の将来にどんなことを予見していますか。(What does Paul foresee in his future?)

-   パウロはエペソ教会の将来にどのようなことを予見していますか。What does Paul foresee in the future of the church in Ephesus?)

-   パウロは、どのような訓戒を与えていますか。(What is Paul's advise?)

-   32節の「神（主）とその恵みの言葉に委ねる。」とはどのような意味でしょうか。(What does 'Now I commit you to God and to the word of his grace" mean?)

## 使徒言行録（使徒行伝, Acts）　第21章

### 使徒言行録 Acts 21: 1--16

-   パウロのエルサレムまでの旅程をたどってみましょう。(Trace the route of Paul's journey to Jerusalem.)

-   ティルス（ツロ）とカイサリアではどのようなことがありましたか。(What happened to Paul and his company in Tyre and Caesarea?)

-   クリスチャンたちはなにを心配し、どんなことをパウロに願っていますか。(What are the Christians concern and what do they plead with Paul?)

-   パウロはクリスチャンたちに止められても、なぜエルサレムに行こうとするのでしょうか。(Whay is Paul determined to go up to Jerusalem?)

### 使徒言行録 Acts 21: 17--26

-   エルサレムでパウロはまずどんなことをしますか。(What does Paul do first in Jerusalem?)

-   長老たちはなにを心配し、どんな提案をしますか。(What do the elders worry about and give as a proposal to Paul?)

-   パウロはどう応答しますか。(What is Paul's response?)

-   ここで問題になっていることと15章で問題にされたことを比較してみましょう。(Compare the problems here and those in Chapter 15.)

### 使徒言行録 Acts 21: 27--36

-   パウロが千人隊長に逮捕されるまでのことをまとめてみましょう。(Summarize what has happened by the time Paul was arrested.)

-   なぜ民衆はパウロを殺そうとまでするのでしょうか。(Why do the people try to kill Paul?)

-   千人隊長はこの問題をどのように扱おうとしますか。(How does the commander of the Roman troops handle the problem?)

### 使徒言行録 Acts 21: 37--40

-   パウロはなぜ民衆に話すことが許されたのでしょうか。(Why is Paul able to talk to the people?)

## 使徒言行録（使徒行伝, Acts）　第22章

### 使徒言行録 Acts 22: 1--21

-   パウロはどんな状況で話し始めますか。(Review the background information when Paul starts talking before the people.)

-   告発の理由は何ですか。パウロはなぜそれに対する弁明とは違うことを話すのでしょうか。(What is Paul accused of? Why Paul does not defend on the accusation directly?)

-   なぜ民衆はパウロの話に耳を傾けるのでしょうか。(Why are the people listening to Paul quietly?)

-   パウロは何について話していますか。(What is Paul's message about?)

-   パウロはなにを伝えようとしているのでしょうか。(What does Paul want to communicate?)

-   パウロは22節以降も話し続けるとするとどんなことを話したと思いますか。(What would Paul say if he could continue after verse 22?)

### 使徒言行録 Acts 22: 22--30

-   群衆はなぜこの時点で声をはりあげて生かしておくべきではないとまで言うのでしょうか。(Why does the people uproar at this moment saying ''Rid the earth of him! He's not fit to live!'')

-   千人隊長はどのように対応し、またそれに対してパウロはどうしますか。(How does the commander of the Roman troops treat the case?)

-   翌日千人隊長はどのようにしますか。(How does he do on the next day?)

## 使徒言行録（使徒行伝, Acts）　第23章

### 使徒言行録 Acts 23: 1--11

-   ここではパウロはどのような場所でどのような人を相手に話していますか。(Where and to whom is Paul speaking to?)

-   パウロの第一声に対して大祭司はどのような行動をとりますか。それはなぜでしょうか。(How does high priest reacted to Paul's first words? Why?)

-   議会は何が理由で分裂してしまいますか。(Why the people split into two parties?)

-   パウロの議会でなぜこのように行動したのでしょうか。(Why do you think Paul acted like this there?)

-   神はパウロに何をつたえ何を保証しましたか。(What is the message of God? What was guaranteed?)

### 使徒言行録 Acts 23: 12--22

-   パウロに対してどんな陰謀が起きますか。(What is plotted against Paul?)

-   パウロはどのようにしてこの陰謀から救い出されますか。(How is Paul rescued from the plot?)

### 使徒言行録 Acts 23: 23--31

-   千人隊長はどのようにしてパウロを護送しますか。(How does the commander of the Roman troops transport Paul?)

-   総督フェリクスへの手紙からどのようなことがわかりますか。(What can you tell by a letter to Governor Felix?)

-   総督フェリクスはどのように対処しますか。(How does Felix treat Paul?)

### 使徒言行録 Acts 24:1--21

-   いつ誰がどのようなメンバーでパウロを訴えますか。(When and who come down to sue Paul?)

-   どのように何を訴えていますか。(What are the contents of their accusation?)

-   パウロは何について反論しますか、(On what account does Paul defend himself?)

-   パウロは何については認めていますか。(On what account does Paul admit?)

-   パウロはここで何を伝えようとしているのでしょうか。(What does Paul relate in his defense?)

### 使徒言行録 Acts 24:22--27

-   フェリクスはどのような対応をしますか。(What is the decision of Felix at this court?)

-   フェリクスのパウロに関する扱いからどのような事がわかりますか。(What can you tell about Felix by his treatment of Paul?)

-   フェリクスは何を求め、パウロは何を求めていたでしょうか。(What are the desires of Felix and Paul?)

## 使徒言行録（使徒行伝, Acts）　第25章

### 使徒言行録 Acts 25:1--12

-   祭司長達はどのような機会になにをフェストゥスに願いますか。(When and what do the chief priest and elders request Festus?)

-   フェストゥスについてどんなことがわかりますか。(What can you tell about Festus?)

-   ユダヤ人の裁判での訴えの様子からどんなことがわかりますか。(What can you tell from the Jews at the court?)

-   パウロはフェストゥスの前でどのような主旨の弁明をしますか。(How does Paul defend himself in front of Festus?)

-   なぜパウロは皇帝に上訴するのでしょうか。(Why does Paul appeal to Caesar?)

-   フェストゥスはどのような判決を下しますか。それは何故でしょう。(What is the judgement of Festus?)

### 使徒言行録 Acts 25:13--27

-   なぜパウロはアグリッパとベルニケの前で話しをする事になりますか。この聴聞会の目的は何でしょうか。(Why does Paul talk to Agrippa and Bernice? What is the purpose of this hearing?)

-   フェストゥスはパウロをどう見ていますか。(What is the view of Festus about Paul?)

## 使徒言行録（使徒行伝, Acts）　第26章

### 使徒言行録 Acts 26:1--11

-   何が目的で聴聞がなされますか。聴衆はどのような人たちですか。(What is the purpose of this hearing? Who are the audience?) (25:23-27)

-   アグリッパはどのような言葉でパウロの弁明をうながし、パウロはアグリッパにどのように話し始めますか。(How does Agrippa open the hearing and how does Paul respond to it?)

-   パウロは何のための裁判を受けていると言ってしますか。(How does Paul testify about the reason of this trial?) (6,7)

-   パウロは8節でどのような挑戦を聴衆に与えていますか。(How does Paul challenge the audience in verse 8?)

-   パウロは 9-11節でどんなことを証言していますか。(What does Paul testify in vs. 9-11?)

### 使徒言行録 Acts 26:12--23

-   パウロの回心についてどのようなことが強調されていますか。9章、22章と比較してみましょう。(How does Paul describe his conversion? Compare with the description in Chapters 9 and 22.)

-   パウロを遣わす目的はなんだと言っていますか。(What is the mission given to Paul?)

-   パウロはイエスのことばにどのように応えたと言っていますか。(How does Paul respond to Jesus' calling?)

-   パウロは旧約聖書（預言者たちやモーセ）がどのような事を預言していると言っていますか。(How does Paul describe what the prophets and Moses said would happen?)

### 使徒言行録 Acts 26:24--32

-   フェストはどんな反応をしますか。なぜですか。(How does Festus respond to Paul? Why?)

-   パウロはフェストゥスとアグリッパにどのように語りかけていますか。(How does Paul talk to Festus and Agrippa?)

-   アグリッパはどう応答し、パウロはそれに対してどう言いますか。(How does Agrippa respond to Paul, and Paul to Agrippa?)

-   王、総督、ベルニケは、どのように結論しますか。(What is the conclusion of Agrippa, Bernice and Festus?)

## 使徒言行録（使徒行伝, Acts）　第27章

### 使徒言行録 Acts 27:1--20

-   旅程を確認してみましょう。(Check the route of Paul's voyage.)

-   パウロはどのような提案をしていますか。(What is Paul's proposal?)

-   暴風雨とそれに対する対処についてまとめてみましょう。(Review about the storm and how the people react to it?)

### 使徒言行録 Acts 27:21--38

-   パウロはどのような状況でどんな提案をしますか。(When and what does Paul propose?)

### 使徒言行録 Acts 27:39--44

-   どんなことがおき、どのようにして助かりますか。(What does happen? How are they saved?)

-   なぜ助かったのでしょうか。(Why do they reach the island safely?)

## 使徒言行録（使徒行伝, Acts）　第28章

### 使徒言行録 Acts 28:1--10

-   マルタではどのような事件が起きましたか。(What happens in Martha?)

-   パウロはマルタでどのようなことをし、どのような結果を引き起こしましたか。(What does Paul do in Martha and what is the result?)

### 使徒言行録 Acts 28:11--16

-   パウロはローマについたときどんな気持ちだったと思いますか。(What is the meaning of Paul's arrival in Rome?)

-   ローマのユダヤ人たちは、パウロをどのように迎えますか。(How does Jews in Rome welcome Paul?)

\[DQ\] なぜユダヤ人たちは、このように囚人パウロを迎えたのでしょうか。

### 使徒言行録 Acts 28:17--31

-   パウロはどんな目的で重だったユダヤ人たちを集めますか。(What is the purpose of Paul to invite the Jews?)

-   ユダヤ人たちはどのように対応しますか。(What is the response of the Jews?)

-   パウロのメッセージの中心は何ですか。(What is the center of Paul's message?)

-   パウロはイザヤ書からの引用をどのように使っていますか。(Why does Paul quote from Isaiah?)

-   最後はどのように結ばれていますか。(What is recorded at the end of this book?)
