# 福音書が伝えるイエス

四つの福音書を読みながら、イエスはどのような方なのか考えていきたい。以下は、あくまでも、わたしが読み取ったイエス像であり、一般的にキリスト教会で理解されているものとは、異なることを断っておく。

## マルコによる福音書から

## **マルコによる福音書について**

**聖書箇所：**1:1 神の子イエス・キリストの福音のはじめ。 

### 洗礼者ヨハネ、悔い改めの洗礼を宣べ伝える

**聖書箇所：**[マルコによる福音書1章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_1-8.pdf)

### イエス、洗礼を受ける

**聖書箇所：**[マルコによる福音書1章9-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_9-11.pdf)

### **試みを受ける**

**聖書箇所：**[マルコによる福音書1章12-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_12-13.pdf)

### **ガリラヤで宣教を始める**

**聖書箇所：**[マルコによる福音書1章14-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_14-15.pdf)

### **四人の漁師を弟子にする**

**聖書箇所：**[マルコによる福音書1章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_16-20.pdf)

### **汚れた霊に取りつかれた男を癒やす**

**聖書箇所：**[マルコによる福音書1章21-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_21-28.pdf)

### **多くの病人を癒やす**

**聖書箇所：**[マルコによる福音書1章29-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_29-34.pdf)

### **巡回して宣教する**

**聖書箇所：**[マルコによる福音書1章35-39節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_35-39.pdf)

### **規定の病を患っている人を清める**

**聖書箇所：**[マルコによる福音書1章40-45節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_40-45.pdf)

### 体の麻痺した人を癒やす

**聖書箇所：**[マルコによる福音書2章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_1-12.pdf)

### レビを弟子にする

**聖書箇所：**[マルコによる福音書2章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_13-17.pdf)

### 断食についての問答

**聖書箇所：**[マルコによる福音書2章18-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_18-22.pdf)

### **安息日に麦の穂を摘む**

**聖書箇所：**[マルコによる福音書2章23-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_23-28.pdf)

### **手の萎えた人を癒やす**

**聖書箇所：**[マルコによる福音書3章1-6節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_1-6.pdf)

### **湖の岸辺の群衆**

**聖書箇所：**[マルコによる福音書3章7-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_7-12.pdf)

### **十二人を選ぶ**

**聖書箇所：**[マルコによる福音書3章13-19節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_13-19.pdf)

### **ベルゼブル論争**

**聖書箇所：**[マルコによる福音書3章20-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_20-30.pdf)

### **イエスの母、きょうだい**

**聖書箇所：**[マルコによる福音書3章31-35節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_31-35.pdf)

### **「種を蒔く人」のたとえ**

**聖書箇所：**[マルコによる福音書4章1-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_1-9.pdf)

### **たとえを用いて話す理由**

**聖書箇所：**[マルコによる福音書4章10-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_10-12.pdf)

### **「種を蒔く人」のたとえの説明**

**聖書箇所：**[マルコによる福音書3章13-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_13-20.pdf)

### **「灯」と「秤」のたとえ**

**聖書箇所：**[マルコによる福音書4章21-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_21-25.pdf)

### **「成長する種」「からし種」たとえを用いて語る**

**聖書箇所：**[マルコによる福音書4章26-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_26-34.pdf)

### **「成長する種」のたとえ**

**聖書箇所：**[マルコによる福音書4章26-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_26-29.pdf)

### **「からし種」のたとえ**

**聖書箇所：**[マルコによる福音書4章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_30-32.pdf)

### **たとえを用いて語る**

**聖書箇所：**[マルコによる福音書4章33-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_33-34.pdf)

### **突風を静める**

**聖書箇所：**[マルコによる福音書4章35-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_35-41.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす**

**聖書箇所：**[マルコによる福音書5章1-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_1-20.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす（１）**

**聖書箇所：**[マルコによる福音書5章1-10節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_1-10.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす（２）**

**聖書箇所：**[マルコによる福音書5章11-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_11-20.pdf)

### **ヤイロの娘とイエスの服に触れる女**

**聖書箇所：**

### **ヤイロの娘とイエスの服に触れる女（１）**

**聖書箇所：**[マルコによる福音書5章25-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_25-34.pdf)

### **ヤイロの娘とイエスの服に触れる女（２）**

**聖書箇所：**[マルコによる福音書5章21-24, 35-43節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_21-24_35-43.pdf)

### **ナザレで受け入れられない**

**聖書箇所：**[マルコによる福音書6章1-6節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_1-6.pdf)

### **十二人を派遣する**

**聖書箇所：**[マルコによる福音書6章7-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_7-13.pdf)

### **洗礼者ヨハネ、殺される**

**聖書箇所：**[マルコによる福音書6章14-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_14-29.pdf)

### **五千人に食べ物を与える**

**聖書箇所：**[マルコによる福音書6章30-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_30-44.pdf)

-   五千人の給食とはどのようなものだったのだろうか

### **五千人に食べ物を与える（１）**

**聖書箇所：**[マルコによる福音書6章30-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_30-34.pdf)

### **五千人に食べ物を与える（２）**

**聖書箇所：**[マルコによる福音書6章35-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_35-44.pdf)

### **湖の上を歩く**

**聖書箇所：**[マルコによる福音書6章45-52節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_45-52.pdf)

### **ゲネサレトで病人を癒やす**

**聖書箇所：**[マルコによる福音書6章53-56節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_53-56.pdf)

### **昔の人の言い伝え**

**聖書箇所：**

### **昔の人の言い伝え（1）**

**聖書箇所：**[マルコによる福音書7章1-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_1-13.pdf)

### **昔の人の言い伝え（2）**

**聖書箇所：**[マルコによる福音書7章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_14-23.pdf)

### **シリア・フェニキアの女の信仰**

**聖書箇所：**[マルコによる福音書7章24-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_24-30.pdf)

### **耳が聞こえず舌の回らない人を癒やす**

**聖書箇所：**[マルコによる福音書7章31-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_31-37.pdf)

### **四千人に食べ物を与える**

**聖書箇所：**[マルコによる福音書8章1-10節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_1-10.pdf)

### **人々はしるしを欲しがる**

**聖書箇所：**[マルコによる福音書8章11-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_11-13.pdf)

### **ファリサイ派の人々とヘロデのパン種**

**聖書箇所：**[マルコによる福音書8章14-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_14-21.pdf)

### **ベトサイダで盲人を癒やす**

**聖書箇所：**[マルコによる福音書8章22-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_22-26.pdf)

### **ペトロ、イエスがメシアであると告白する**

**聖書箇所：**[マルコによる福音書8章27-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_27-30.pdf)

### **イエス、死と復活を予告する**

**聖書箇所：**[マルコによる福音書8章31-38節, 9章1節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_31-38_9_1.pdf)

### **イエスの姿が変わる**

**聖書箇所：**[マルコによる福音書9章2-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_2-13.pdf)

### **汚れた霊に取りつかれた子を癒やす**

**聖書箇所：**[マルコによる福音書9章14-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_14-29.pdf)

### **再び自分の死と復活を予告する**

**聖書箇所：**[マルコによる福音書9章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32.pdf)/[マルコによる福音書9章30-32節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32_extra.pdf)

### **いちばん偉い者**

**聖書箇所：**[マルコによる福音書9章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_33-37.pdf)

### **逆らわない者は味方**

**聖書箇所：**[マルコによる福音書9章38-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41.pdf)/[マルコによる福音書9章38-41節 福音書対照表（ルカ参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41_extra.pdf)

### **罪への誘惑**

**聖書箇所：**[マルコによる福音書9章42-50節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_42-50.pdf)

### **離婚について教える**

**聖書箇所：**[マルコによる福音書10章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_1-12.pdf)

### **子どもを祝福する**

**聖書箇所：**[マルコによる福音書10章13-16節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_13-16.pdf)

### **金持ちの男**

**聖書箇所：**[マルコによる福音書10章17-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-31.pdf)

### **金持ちの男（1）**

**聖書箇所：**[マルコによる福音書10章17-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-22.pdf)

### **金持ちの男（2）**

**聖書箇所：**[マルコによる福音書10章23-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_23-31.pdf)

### **イエス、三度自分の死と復活を予告する**

**聖書箇所：**[マルコによる福音書10章32-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34.pdf)/[マルコによる福音書10章32-34節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34_extra.pdf)

### **ヤコブとヨハネの願い**

**聖書箇所：**[マルコによる福音書10章35-45節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_35-45.pdf)

### **盲人バルティマイを癒やす**

**聖書箇所：**[マルコによる福音書10章46-52節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_46-52.pdf)

### **エルサレムに迎えられる**

**聖書箇所：**[マルコによる福音書11章1-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_1-11.pdf)

-   マルコ、マタイ、ルカでは、このときが公生涯において、最初にエルサレムに来たときとして描かれているが、ヨハネでは、逆に、エルサレムや、その周辺、ユダヤなどでの活動についてたくさん書かれている。

-   エルサレム入城の書き方が、マルコ、マタイ、ルカ、ヨハネそれぞれに異なる。実際、エルサレム入城は、イエスにとってどのようなものだったのだろう。

### **神殿から商人を追い出す**

**聖書箇所：**[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

[マルコによる福音書11章15-19節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_15-19.pdf)

マルコ、マタイ、ルカでは、宮きよめと言われる記事は、イエスのエルサレム入城のすぐ後に書かれているが、ヨハネでは、イエスの活動の最初に書かれている。

### いちじくを呪う

[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

マルコ11:12-14 と 20-26 に分かれて書かれており、その間に、宮きよめ（11:15-19）の記事が挟まっている。マタイでは、宮きよめを先におき、そのあとに、まとめて（21:18-22）記しているが、記述内容的にも、マルコがもとであると思われる。このあと、イエスは、宮で、何日も教え続けることもあり、宮きよめのあとのこととしては、あまり辻褄があわないように、感じる。そこで、個人的には、この地域、ベタニヤなど、エルサレム近郊の信仰者を守るため、共観福音書、とくに、そのもととなっていると思われる、マルコによる福音書には、通常受難週とよばれる、最後の週の活動以外、ユダヤやエルサレムでのイエスの活動を書かないしわ寄せが背景にり、宮きよめの直前に連動させて、いちじくを呪う（あとで、ペテロが「あなたが呪ったいちじく」と言っている）記事が、ここに置かれているのではないかと思う。

しかし、エルサレム入城の翌日ではないかもしれないが、実際に、このようなこともあったのかもしれない。すなわち、イエスが空腹のゆえに、不機嫌になり、それがゆえに、宮きよめのような、乱暴なこともしてしまったのかもしれない。「いちじくの季節でなかったからである。」（13）というマタイにはない一文や、「弟子たちはこれを聞いていた。」（14）という、冷静にながめている弟子たちの記述は、それを表現しているのかもしれないと思う。イエスは、「食をむさぼる者、大酒を飲む者（マタイ11:18,19、ルカ7:33,34）」だとも言われており、聖人君主にあるまじきこととして、このできごとを、なぞが秘められているなどと、特別な解釈をしないほうが良いと思う。同時に、そうであっても、不機嫌ではおわらずに、かならず、たいせつなことを教えてくださるのが、ペテロをはじめとする、弟子たちにとっての、イエスだったのだろう。

祈りについて、または、願いの実現については、簡単に、語れるものではない。ここでは、最初に、「神を信じなさい」（22）とはじめ、「よく聞いておくがよい。」（23a）という重要なことを語るときの、慣用句ではじめ、まずは、神に信頼することから、「だれでもこの山に、動き出して、海の中にはいれと言い、その言ったことは必ず成ると、心に疑わないで信じるなら、そのとおりに成るであろう。」（23b）と続ける。おそらく、眼の前に、オリーブ山（「この山」）があり、死海（「海」）が見えているかどうかは別として、その光景も想像できる場所だったのだろう。つづけて「そこで、あなたがたに言うが、なんでも祈り求めることは、すでにかなえられたと信じなさい。そうすれば、そのとおりになるであろう。」（24）というが、このことばが、独り歩きすると、危険も伴う。神様への信頼、そして、神様が何を望まれるかが理解できていなければ、利己的に、祈りを使ってしまう可能性もあるからである。ここで、「また立って祈るとき、だれかに対して、何か恨み事があるならば、ゆるしてやりなさい。そうすれば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださるであろう。」（25）と日常に引き戻すように、ゆるしについて語っている。ここでは、恨み事とあるので、それはなにかと考えてしまうが、「だれかに対して何らかのわだかまり (anything you have against someone)」ぐらいの意味で、それを、許容（προσεύχομαι）しなさいとしているように見える。つづけて「あなたがたのあやまち（παράπτωμα）」（25）とあるものも、英語では、trespasses とも訳されている。それが、神様のご性質なのだろう。常に、小さな過誤も、ゆるしてくださっているということなのだろう。

（2024.9.26）

### 権威についての問答

[マルコによる福音書11章27-33節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_27-33.pdf)

「イエスが宮の内を歩いておられると、祭司長、律法学者、長老たちが、みもとにきて言った、『何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか』。」（マルコ11:27b,28）から始まっている。祭司長、律法学者、長老たちは、最高議会（サンヘドリン）の構成メンバー、主だった人たちという意味だろう。ギリシャ語では、みな、複数男性の定冠詞が3つともについており、みな、複数いたのだろう。

実は、使徒行伝4章7節で弟子たちも、同じように問われている。「あなたがたは、いったい、なんの権威、また、だれの名によって、このことをしたのか」。このときも、大祭司の一族も集まっているので、まさに、最高議会の中心メンバーがイエスの前に現れたのだろう。イエスを殺そうとする企てについては、何回かすでに書かれているが、指導者たちが問うているということでも、重要な場面である。

気になるのは「何の権威」「これらの事」「誰が権威を授けたか」だろう。まず最初に、「これらの事」「そうする権威」である。マルコの記述によると、エルサレムでのことはこのときのことしか書かれていないので、はっきりしない。「これらの事」が、宮きよめ（マルコ11章15-19節）を指すのであれば、もうすこし具体的に問うだろう。すると、マタイ21:23b で「その教えておられる所にきて」とあり、ルカ20:1 では「イエスが宮で人々に教え、福音を宣べておられると」とあるので、宮で教えることを指すととるのが良いように思う。マルコでは、直接的には書かれていないが「宮の内を歩いておられると」とあり、回廊（柱：スコラで支えられている）を歩きながら教えるのが、エルサレムでも通常のことであったようなので、「教えていること」について言っていると取るのが自然だろう。マタイ21:14では、宮きよめの際に「そのとき宮の庭で、盲人や足なえがみもとにきたので、彼らをおいやしになった。」とも書かれているので、そのような噂を聞いたことも背景にあったのかもしれない。実際、ヨハネによる福音書を見ると、癒やしもふくめ、多くのわざをエルサレムおよびその周辺でされていることが分かる。

何の権威によって教えているのか、誰が宮で教える権威を授けたのか、と理解すれば、非常に自然である。そのように書かれていないのは、癒やしのような力ある業や、福音の宣教など、さまざまなことを排除しないように「これらのこと」とまとめられているのかもしれない。一義的に教えることであれば、宮で教えることに関しては、祭司長たち、教える内容については、律法学者たちが、権威を授ける人たちであったのだろう。宮きよめもふくめた全体的な秩序を考えると、長老たちを含めた、最高議会のもとにある事項となる。

しかし、イエスは、直接的には答えず「一つだけ尋ねよう。それに答えてほしい。そうしたら、何の権威によって、わたしがこれらの事をするのか、あなたがたに言おう。ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」（29b,30）と逆に問い返す。これは、議論の技術などではなく、本質を突いた問いだったと思う。おそらく、この人たちのなかにも、ヨハネの「罪のゆるしを得させる悔改めのバプテスマ」（マルコ1:4）は天から、すなわち、神様の喜ばれることと、認めざるをえないと考えていた人もいただろう。ルカが記すように、ヨハネが祭司の子であるなら、ヨハネをよく知っている人もいたことだろう。同時に「人々が皆、ヨハネを預言者だとほんとうに思っていた」（32b）ということは、ヨハネのバプテスマが天からのものではないとし、地に引き下ろすことは、自分たちの人々に対する宗教的優位性も失いかねないとうことにもなる。

ヨハネ福音書記者またはその付近には、祭司長の知人（ヨハネ18:15）も居たようであるし、実際、ヨハネ福音書では次のように証言している。「しかし、役人たちの中にも、イエスを信じた者が多かったが、パリサイ人をはばかって、告白はしなかった。会堂から追い出されるのを恐れていたのである。彼らは神のほまれよりも、人のほまれを好んだからである。」（ヨハネ12:42,43）心の分裂が表現されている。真理だと思っても、それを受け入れられない。信じても告白できない。さらに、行動にまでは移せない。共観福音書には、かろうじてアリマタヤのヨセフのことが記されているが（マルコ15:43、マタイ27:57、ルカ23:51、ヨハネ19:38）微妙な心の内を持っていた人たちも多かったのだろう。すくなくとも、祭司長、律法学者、長老たちと出てきたら、これは敵対する「悪者」などと考えないほうがよい。わたしたちと同じような人たちだったのではないだろうか。

おそらく、この人たちは「自分たちは、神の御心、真理を知っている。少なくとも、群衆（一般の人々）とは比較にならない知識をもっている。」と考え、「真理を探求するのではなく、自分たちが持っている知識に頼って判断しようとし」さらに、「自分たちの優越によって人々の間で築いてきた『ひとのほまれ』を手放せない。」面はあるのだろう。しかし、わたしたちに、このような態度がないとは言えないように思う。

求められているのは、自分の弱さを知り、悔い改めによって救いをもとめる生き方。神の御心をつねにもとめて、自分の信じることがほんとうに、神様のみ心なのかを問いつづける生き方だろうか。ここで、はからずも、このひとたちは「わかりません」と答えているが、それは、たいせつな出発点であるようにも思う。宿題をもらったと感じた人も居たかもしれない。まさに『わたしの家（宮）は、祈の家ととなえらるべきである』。自分の心が、神様のみこころと同期しているかを問う場所なのだろう。わたしたちも、悔い改めて、自らを低くし、御心を求めて生きるものでありたい。そして、この人たちの中にも、そのような悔い改めを経験したひとがいることを期待する。

（2024.10.3）

### **「ぶどう園の農夫」のたとえ**

[マルコによる福音書12章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_1-12.pdf)

彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。(マルコ12:12)

と最後にある。まず「彼ら」は誰であろうか。1節にも「そこでイエスは譬で彼らに語り出された」と彼らが登場するので、それより前、すなわち、権威についての問答で、質問する、祭司長、律法学者、長老たち、これらは、サンヘドリン（最高会議）のメンバーを代表しているが、民の指導者たちをさすと考えてよいだろう。すると、このたとえは、11章27-33節とつながっていると考えるのが良さそうである。

マタイでは、「二人息子」のたとえ（マタイ 21:28-32）が挿入されているが、それを除くと、マタイも、ルカも、権威についての問答のあとに置かれている。注意を要するのは、ルカでは、「そこでイエスは次の譬を民衆に語り出された」（ルカ20:9）と始まっており、他にもひとが居たことが想定されている。ただ、そのルカも最後は「このとき、律法学者たちや祭司長たちはイエスに手をかけようと思ったが、民衆を恐れた。いまの譬が自分たちに当てて語られたのだと、悟ったからである。」（ルカ20:19）となっているので、やはり主としてはたとえが語られた対象は、民の指導者たちと考えてよいだろう。追加しておくと、マタイで挿入されているたとえの最後にも「よく聞きなさい。取税人や遊女は、あなたがたより先に神の国にはいる。32 というのは、ヨハネがあなたがたのところにきて、義の道を説いたのに、あなたがたは彼を信じなかった。ところが、取税人や遊女は彼を信じた。あなたがたはそれを見たのに、あとになっても、心をいれ変えて彼を信じようとしなかった。」（マタイ21:31b,32）とあり、この前の権威についての問答でのイエスの相手である民の指導者が「あなたがた」に対応している。

そうすると、たとえのなかの、ぶどう園の主人は、神様、農夫は、民の指導者たちと理解するのが自然だろう。では、ぶどう園はどうだろうか。おそらく、民の指導者たちが、世話をすべきだった、イスラエルの民を意味するのだろう。しもべたちは、預言者など、神様からの使いで、明確ではないが、バプテスマのヨハネも含まれているように思われる。主人の愛子は、イエスであろう。民の指導者たちは、すでに、宮きよめのときにも、どうかしてイエスを殺そうと計っているが（マルコ 11:18）、その人たちに対して、神の愛子である、イエスが殺されることを語っていることになる。同時に、「あなたがたは、この聖書の句を読んだことがないのか。『家造りらの捨てた石が／隅のかしら石になった。これは主がなされたことで、／わたしたちの目には不思議に見える』」。（マルコ12:10,11）とも語られており、殺されるという事実以上のことが語られている。そのことも含めて、イエスが「これらのことをする権威」（マルコ11:28）に対する、応答以上のものが語られていることになる。

疑問に思うのは、なぜ、民の指導者は、主のしもべを受け入れず、打ちたたき、殺してしまうのか。そして、主は、なぜ、愛子ならうやまってくれると考えたのか。そして、神様が受け取ろうとしていた実は何なのだろうかということである。一つ一つ考えてみよう。

神様は、ぶどう酒が欲しかったのだろうか。おそらく、なにかにたとえられているのだろう。ぶどう園から得られるもの。民から得られるものである。それは、神様が喜ばれること。神様が受けるべき栄光だろうか。それは、神様が望まれること、神様が望まれることをもとめ、神様のみ心に生きることだろうか。それこそが、神様が栄光を受けることだろう。そのことのために、民の指導者は立てられているにもかかわらず、神様の栄光のためではなく、自分たちの栄光のため、自分たちのためになることを求めたということだろうか。それを、神様がうけるべきものを、自分たちのものとするということだろうか。もう少し、適切な表現があるかもしれない。

この民の指導者たちは、民が主に仕えるために立てられた人たちであったはずである。神様は、このひとたちが、神様のためと言っているなら、愛子をうやまってくれることは当然と思ったということだろうか。実際は、そうではない。なんと悲しいことだろうか。しかし、おそらく、それは、様々なところに存在することなのだろう。現代的には、一人ひとりが、神様に従うことがたいせつで、指導者の責任ではないという観方もあるかもしれない。しかし、指導者として立てられるものはおり、互いに愛し合うにしても、神様が喜ばれることのために、互いに助け合うこともまた、当然だろう。責任というより、それを喜びとできるかということだろうか。

民の指導者は、そしてわたしたちは、どうして、そのようにできないのだろうか。それこそじっくり考えるべきことである。

（2024.10.10）

### **皇帝への税金**

聖書箇所：[マルコによる福音書12章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_13-17.pdf)

イエスの言葉じりを捕らえようとして、「カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。（14b）と問うてきたひとたちに、「デナリを持ってきて見せなさい」（15b）と答え、彼らがデナリをもってくると、「これは、だれの肖像、だれの記号か」。（16b）と問い、「カイザルのです」（16c）との答えに対して「カイザルのものはカイザルに、神のものは神に返しなさい」。（17a）と命じる。彼らはイエスに驚嘆した。（17b）と終わっているが、なんとも痛快である。しかし、それで良いのだろうか。

まず、我々が理解しておかなければならないのは、聖書に明確に書かれてはいないが、熱心なユダヤ教徒、とくにファリサイ人は、税金を納めることは、ローマに従属することで、自由を失い、アブラハムの子としての尊厳が失われる危機的な状態だと考えていたのではないかと言うことである。ルカ20:20bに「イエスを総督の支配と権威に引き渡す」ことが目的であったとも書かれている。マルコでは、単に「言葉じりを捕らえようとした」とあるだけだが、すでに、イエスを捕らえ（12:12b）殺そうと考えていたことが「祭司長、律法学者たちはこれを聞いて、どうかしてイエスを殺そうと計った。」（11:18）と、宮きよめの箇所の最後に書かれている。このあとの経緯からも推察できるように、おそらく、死刑の権限は、サンヘドリンにはない。すると、ルカが書いているように、総督に殺してもらうことが合法的に、かつ自分たちの手を汚さず、民衆からの批判の矢面にも立たずにできる最良のこととなる。それには、ここで議論されている、問いは重要で、これもルカが後の裁判の場でのこととして書いているように「わたしたちは、この人が国民を惑わし、貢をカイザルに納めることを禁じ、また自分こそ王なるキリストだと、となえているところを目撃しました」。（ルカ23:2）という言質（げんち：あとで証拠となるような約束の言葉。ことばじち。）をとることを目指したのだろうと想像できる。

我々にとって理解しにくいのは、政治的に、ローマに支配されており、レギオン（大隊）などの存在を見れば、熱心党のテロ的なものではこの状態を覆せず、ヘロデ大王の死後、アケラオの支配から直轄地となったように、その支配が強化されることを見ているひとたちにとっては、税金を納める程度は仕方がないと思うのではないかということである。しかし、貨幣に書かれた、自ら DIV 神とする、ローマ皇帝、最高神祇官と名乗る、政教一致と思われる支配状況の中で、税金を自分たちの貨幣ではなく、支配者の貨幣に支配され、それによって税をも納めることは、我慢ならないことだったのかもしれない。一般的にみると、ローマ帝国は、支配体制も盤石で、制度などもしっかりしていたような印象を受け、当時としては、ある程度、永続可能にみえるが、ユダヤ人にとってはそうではなかったのだろう。ヨハネ8:33の「わたしたちはアブラハムの子孫であって、人の奴隷になったことなどは、一度もない。どうして、あなたがたに自由を得させるであろうと、言われるのか」。は印象的である。これだけで、十分な理解が得られたとは思わないが。

税金についてイエスはどのように考えていたのだろうか。イエスの「デナリを持ってきて見せなさい」（15b）という、実物教育にまず驚かされる。実際に、デナリには、神的存在、または神との仲介者としての皇帝のイメージが描かれ、言葉が添えられている。それを確認し「これは、だれの肖像、だれの記号か」（16b）と問い、ことばじりを得ようとする人に答えさせる。「カイザルのです」（21a）そのあとで「それでは、カイザルのものはカイザルに、神のものは神に返しなさい」。（21b）と答えるのである。神のものにも、神の肖像、神の記号が記されているのか。象徴的には、「神は自分のかたちに人を創造された。すなわち、神のかたちに創造し、男と女とに創造された。」（創世記1:27）も、ひとつの回答なのかもしれない。しかし「はじめに神は天と地とを創造された。」（創世記1:1）と信じるなら、すべてのものが神の創造物なのだろう。すると、すべてが神のものとなる。しかし、すると、神のものの中に、カイザルのものがあるのか、それがどのような関係にあるのかが問題になる。とても難しい問題も生じるように思う。実物教育とともに、この質問は、イエスのことばじりを捕らえようとしていた人たちは、それ以上、なにも言えなかったかもしれないとは思うが、イエスが伝えたかったこと、または問いたかったことは何なのだろう。おそらく、最初の問い「カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。（14b）に戻るなら、「神様のものは神様にお返しすべきでしょうか。お返ししなければならないでしょうか。」となるように思われる。そして、これは、「すべてのものが神様のものであるなら、神様のものを神様にお返しするにはどのようにしたら良いのでしょうか。という問いにもつながる。」このことを、イエスは考えてもらいたかったのだろうか。神様にお返しすることは、おそらく、神殿税などではなく、神様のみこころを行うこと（マルコ3:35）なのだろうか。

国または統治者と信仰の問題、政治・経済と宗教だろうか、神様のもとでの自由も関係するだろうか、これらについての、現代的意味を考えたいが、イエスのことばは、これらに関係はしていても、明確には何も伝えていないように思う。あくまでも、問いかけなのだろうか。問いかけは、質問者にとっては、驚き（17b）であり、真剣にこのことばについて考えようとしたひとも居たかもしれないが、わたしたちにとってはどうなのだろうか。困難な問題が目の前にあるときに、神様の視点で見てみることが促されているのかもしれないとは思う。自分の置かれた状況や、その他の障壁に困難や苦しみや理不尽さの原因を求めるのではなく、神様がなにを求めておられるか、わたしたちが、どのような応答をすべきかは、問われているように思う。神のものが、神様のしるしが付いているものに囲まれているならば。

（2024.10.17）

### **復活についての問答**

**聖書箇所：**[マルコによる福音書12章18-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_18-27.pdf)

23 復活のとき、彼らが皆よみがえった場合、この女はだれの妻なのでしょうか。七人とも彼女を妻にしたのですが」。と、サドカイ派の人たちが問うた時、イエスは、24b「あなたがたがそんな思い違いをしているのは、聖書も神の力も知らないからではないか。25 彼らが死人の中からよみがえるときには、めとったり、とついだりすることはない。彼らは天にいる御使のようなものである。と答え、さらに、26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている」。と教えている。

神様による復活は、御使のような存在としてよみがえることをいっているのであって、この世での規定などとは、無関係、次元がことなるものであるとまずは述べている部分は、ある程度理解できるように思う。しかし、サドカイ派ということで、モーセ五書のだれでも知っている出エジプト記３章６節からの引用の解釈には驚かされる。確かに、モーセに、『わたしはアブラハムの神、イサクの神、ヤコブの神である』と現在形で語っているのだから、アブラハム、イサク、ヤコブの神であるということは、今も続いているということを意味するように思う。しかし、アブラハム、イサク、ヤコブも何らかの意味で、神と共に生きていることと、復活とは同一のことなのだろうか。それは、正直良くわからない。

もう少し問いを拡大してみると、「死んだひとが生き返ること、イエスの復活、一般の（イエス以外の）ひとの死後の（最後の日の）復活、神との関係において生き続けること、それぞれの関係と、それぞれの意味についてはどう考えたらよいのだろうか。」少し整理しないといけない。まず、エリヤ（列王記上17:17-24）や、エリシャ（列王記下4:18-37）が、死んだひとを生き返らせたり、イエスが、ヤイロの娘（マルコ5:35-43、マタイ 9:23-26、ルカ 8:49-56）、ナインでのやもめの息子（ルカ7:11-17）、ラザロ（ヨハネ11:38-53）を生き返らす記事は、死から生き返るまで、あまりときを経ていないので、他の三種類のこととは、別のものと分類してもよいように思う。むろん、これらが、神様が肉体の死にも介入しうることを示していることは確かなのだろうが。また、マタイ27:53の記事（そしてイエスの復活ののち、墓から出てきて、聖なる都にはいり、多くの人に現れた。）については、検証が難しいので、これも、別のものと分類することにしよう。

すると、大きく分けると、イエスの復活と、一般の人の死後の復活と、ここでイエスが述べている、神と共に生きることに分類できるように思う。どれも難しい。イエスの復活はと、一般の人の死後の復活は、別の機会に扱うこととし、今回のテキストの中心部分を占めると思われる、神と共に生きることについては、ここで考えておきたい。テキストは最初にも引用したように、次のようになっている。

> 26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている

永遠の方との交わりは、一瞬のこと、わたしたちが肉体的に生きていることではなく、時を超えたものだと伝えているのだろう。すごいこと、素晴らしいことである。

> イエスは彼女に言われた、「わたしはよみがえりであり、命である。わたしを信じる者は、たとい死んでも生きる。26 また、生きていて、わたしを信じる者は、いつまでも死なない。あなたはこれを信じるか」。（ヨハネ11:25-26 ）

ヨハネによる福音書の言葉も、通じる部分があるように思われる。ヨハネによる福音書の言葉を使うと、永遠の命だろうか。イエスを通して、神様との交わりの中に生きることだろうか。そのように、抽象化・普遍化してよいのか、不安は残る。

わたしが、現在書けるのはこのぐらいだが、最後に、この箇所の並行箇所におけるルカによる福音書の言葉を引用しておく。

> 34 イエスは彼らに言われた、「この世の子らは、めとったり、とついだりするが、35 かの世にはいって死人からの復活にあずかるにふさわしい者たちは、めとったり、とついだりすることはない。36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。
>
> 38 神は死んだ者の神ではなく、生きている者の神である。人はみな神に生きるものだからである」。

前半における「かの世にはいって死人からの復活にあずかるにふさわしい者たち」では、復活にあずかることを、それにふさわしい者たちに限定している。「御使い」が「天使（福音書ではここのみ）」に変えられ、さらに、「また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ない」と論理的に、死なないことに結びつけられている。

後半では、「人はみな神に生きるものだから」と、解釈が入っている。パウロの解釈が入っているかどうかまでは、検証できないが、マルコのような素朴な記述ではなく、一歩、踏み込んだものになっていることはたしかである。ルカの解釈である。

まったくの私見でかつ確信・確証もないが、マルコが書かれた時点では、パウロの書簡（少なくとも主要なもの）は、すべえて書かれ、ある程度流布されていた可能性もあると思うが、マルコ著者の周辺、または、マルコの情報源では、復活についての理解が一定しておらず、深められていなかったのかもしれない。そのような背景のもとで生み出されたことも、勘案して読まないといけないのかもしれない。

（2024.10.24）

### **最も重要な戒め**

**聖書箇所：**[マルコによる福音書12章28-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_28-34.pdf)

神殿での議論において、「イエスが巧みに答えられたのを認めて」（28b）律法学者が、「すべてのいましめの中で、どれが第一のものですか」（28c）とイエスに問い、イエスが「第一のいましめはこれである、『イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。 心をつくし、精神をつくし、思いをつくし、力をつくして、主なるあなたの神を愛せよ』。第二はこれである、『自分を愛するようにあなたの隣り人を愛せよ』。これより大事ないましめは、ほかにない」。（29-31）答える。律法学者は「先生、仰せのとおりです、『神はひとりであって、そのほかに神はない』と言われたのは、ほんとうです。また『心をつくし、知恵をつくし、力をつくして神を愛し、また自分を愛するように隣り人を愛する』ということは、すべての燔祭や犠牲よりも、はるかに大事なことです」（32b,33）と応じたのにたいして、イエスは「あなたは神の国から遠くない」（34b）と応じた箇所である。

マタイに対照箇所があり、ルカの善いサマリア人のたとえの直前にある律法学者との問答も、内容的に非常に似ているが、すくなくとも、マタイ、ルカとも、イエスを試そうとして問うたとあり、マルコに書かれている動機、およびそのあとの、律法学者の応じ方とは異なるので、まずは、マルコのテキストに集中して考えてみたい。

まず、この律法学者は、「イエスが巧みに答えられたのを認めて、イエスに質問した」とあるので、マルコは、このひとを好意的に描いている。最後に、このひとが、イエスのことばに応答したあとにも、「イエスは、彼が適切な答をしたのを見て言われた」とあるので、イエスとこの律法学者のやりとりを、マルコが好意的に書いていることは確かだろう。マタイは、このあとの23章で、律法学者、パリサイ人に対して非常に厳しい言葉を延々とイエスが語った様子を描いているので、この律法学者に対しても好意的には書けなかったのかもしれない。

さて、この律法学者の質問は、「すべてのいましめの中で、どれが第一のものですか」である。これに対して、イエスは、「第一のいましめはこれである」、「第二はこれである」として旧約聖書のことばを引用し、最後に「これより大事ないましめは、ほかにない。」と語っている。「第一のもの」という質問に、第一、第二と答えているので、これらは、一つのもの、または、深く関係しているものと捉えることができるように思う。

旧約聖書にも、また、他の同時代の文書（十二族長の遺言など）からも、旧約聖書にあるたくさんのいましめを数えたり、別のことばで、まとめたり、特別に重要なことばを抽出したりというこころみがされていたようである。その中心にあったのが、「聞け（シェマ）」ではじまる、イエスが最初にあげている、申命記６章４・５節であろう。

> イスラエルよ聞け。われわれの神、主は唯一の主である。 あなたは心をつくし、精神をつくし、力をつくして、あなたの神、主を愛さなければならない。

イエスは、さらに、レビ記19章18節からの引用も用いている。引用は一部であるが、全体は以下のようなものである。

> あなたはあだを返してはならない。あなたの民の人々に恨みをいだいてはならない。あなた自身のようにあなたの隣人を愛さなければならない。わたしは主である。

この二つを結びつけて、「主（または神）を愛し、隣人を愛する」という表現は、上に挙げた『十二族長の遺言』にもあり、特に新しいことではないようである。

しかし、いくつか気になることがある。イエスのこたえは、

> 「第一のいましめはこれである、『イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。心をつくし、精神をつくし、思いをつくし、力をつくして、主なるあなたの神を愛せよ』。第二はこれである、『自分を愛するようにあなたの隣り人を愛せよ』。これより大事ないましめは、ほかにない」。

まず、「イスラエルよ聞け。われわれの神、主は唯一の主である。 」の部分は、マタイにもルカにも欠けている。また、さらに、小さいことではあるが、申命記にはない、「思いをつくし（with all thy mind）」が、イエスのことばには、入っていることである。

ひとつめについては、あとで考えることにして、思いをつくしは、あとで、この律法学者が復唱している場面では、「知恵をつくし」となっており、英語では、"with all the understanding" であり、すべてをもって、または全身全霊をもってと言う意味のものが、このように表現されているだけで、大きな違いはないかもしれない。しかし、やはり、英語の "mind" から、知的、または理性的な面も含めているということを表現しているのかもしれない。しっかり、イエスが語ったことも考えてみよう。

実は、わたしは、この箇所は、何回か学んでいるが、この二つのいましめをつぎのようにまとめることにしている。

> 「たいせつなひと（かた）をたいせつにすることは、たいせつなひと（かた）のたいせつなひとをたいせつにすること。」が、神様を愛し、隣人を愛すること。神様を愛することは、かみさまがたいせつなことをたいせつにすること。そして、それは、御心をおこなうとも表現でき、それは、このように表現できるのではないかと思うからである。

レビ記では明らかに、隣人は、同胞、「あなたの民の人々」である。しかし、神様が愛される人びととすれば、それほど、限定されるわけではないし、さらに、「主なるわたしたちの神は、ただひとりの主である。」と宣言すれば、全世界のひとを含みうることになるからである。

きょうだい、隣人、すべてのひとは、そう単純に一括りにはならないが、それこそが、知的、または、理性的な面もふくめて、神様を理解し、神様が愛しておられるひとが広がっていき、さらには、自分への神様の愛の大きさ広さも広がっていくことではないだろうか。

最後にイエスが、「あなたは神の国から遠くない」。と語る時、これは、ほとんど満点と、ポジティブなことを表現しているのか、ちょっと足りないということも含んでいるのかどちらかを考えてみよう。もう少し、表現を変えると、なにをもって、イエスが、この律法学者が、適切な答をしたと見たのだろうか。もし、少し足りないとすると、それは、何なのだろうかということである。

個人的には、適切な答えをしたと見たのは、弟子たちではないだろうかと思う。弟子に比較して、適切な旧約聖書（サムエル記上15:22、ホセア6:6）も踏まえて答えていることがあるように思う。同時に、「それから後は、イエスにあえて問う者はなかった。」とあるが、ここからは、弟子たちとの話が書かれていることを考えると、イエスに従っていくこと、イエスとともに生きることによってしか、自分の十字架を負ってイエスに従っていかなければ学べないことがあることを言っているのではないだろうか。弟子たちは、自分たちと比較して、この人はすごいと思ったかもしれないが、弟子たちには、学ぶ機会がつねに与えられていたのかもしれない。

### **ダビデの子についての問答**

**聖書箇所：**[マルコによる福音書12章35-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_35-37.pdf)

最も重要な戒めの最後は「それから後は、イエスにあえて問う者はなかった。」（12:34b）で終わっており、様々な人達との議論、問答は終わり、この箇所では、イエスから「律法学者たちは、どうしてキリストをダビデの子だと言うのか。」と問うところから始まっている。

マルコによる福音書は「神の子イエス・キリストの福音のはじめ。」（1:1）から始まるが、イエスがキリストであることについては、ペテロの告白（8:29）以外は、9章41節に「だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。」とある以外は、書かれていない。イエスがキリストであること、どのようなキリストであるかは全体で証言しているが、イエスが、自ら宣言するようなことは書かれていない。そんなマルコで、キリストとは、どのような方かについてこの箇所は、語っている。その意味からも、ここでキリストとうときは、直接的には、イエスのことを指しているのではなく、「イエス・キリストがダビデの子か」と問うているのではなく、最初の問いは、当時待望されていた「来たるべき神の油注がれたもの（キリスト）はダビデの子だと言えるのか」という問いであることを確認しておく必要がある。

ダビデについては、サムエル記上16章から記述が始まり、サムエル記下の全体、そして、先祖と共に眠って、ダビデの町に葬られるまで、イスラエルを40年治めた王である（列王記2章10,11節）また、ナタン預言と呼ばれている、サムエル記下7:8-17では「あなたの家と王国はわたしの前に長く保つであろう。あなたの位は長く堅うせられる」（7:16）ことが書かれているだけではなく、「わたしは彼らの上にひとりの牧者を立てる。すなわちわがしもべダビデである。彼は彼らを養う。彼は彼らを養い、彼らの牧者となる。主なるわたしは彼らの神となり、わがしもべダビデは彼らのうちにあって君となる。主なるわたしはこれを言う。」（エゼキエル34:23,24）など、明確とは言えないにしても、ダビデのような神のしもべが、治めるようになるとの預言が旧約聖書にいくつか見られる。（イザヤ9:6,7、11:1,2、詩篇89:20-24）律法学者たちは、この先を、いろいろと議論していたようだ。そのことを踏まえたイエスの問いかけである。

イエスは引き続き次のように語っている。

> 36 ダビデ自身が聖霊に感じて言った、／『主はわが主に仰せになった、／あなたの敵をあなたの足もとに置くときまでは、／わたしの右に座していなさい』。37a このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。

この詩篇は、一般的に、ダビデの詩で、かつ、メシア（キリスト）に関する詩篇だと考えられており、ここで、主は、主なる神、わが主は、メシア、「わが」と読んでいるわたしは、ダビデをさすという理解のもとで、イエスは、「ダビデ自身がキリストを（わが）主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」と言っているのである。

整理すると三つの問いが考えられる。

A. イエスは、キリストはダビデの子だということを否定しているのか。

B. イエスは、自分がダビデの子であることを否定しているのか。

C. キリストは、ダビデの子を超える存在であるということか。

一つ一つ考えていくことにする。A は、少なくとも、表面的には、そのとおりであるように思われる。B については、イエスがキリストであり、かつ、A がその通りなら、論理的帰結として、キリストであるイエスは、ダビデの子ではないとなるが、上にも述べたように、ここでも、イエスは、ここでいうキリストであるかどうかについては、明確にしておらず、否定も肯定もしていないととるのが穏当であろう。最後に、C については、キリストとダビデの関係が明確に示されているわけではないが、ダビデのような、または、ダビデに従属する子分のようなものではないと言っているという意味で、ダビデの子を超える存在であると言っていると解釈してよいだろう。ただ、だから、神の子だと断言するのは、神の子について明確にしなければならいこともあり、すこし、行き過ぎであるように思われる。

簡単に言うと、来たるべきキリストは、ダビデが主と呼ぶようなもので、ダビデの子といわれるようなものではないと言っているのだろう。ダビデの子は、文字通りの息子ではないので、どのように定義するか考える必要があるが。

実は、マルコでは、ダビデの子ということばも非常に注意して使われているように見え、実際にイエスをダビデの子であると、呼ぶのは、エリコでの盲人（10:47,48）だけである。マタイでは、各所でイエスに対してダビデの子と言っていることとは、対照的である。（マタイ1:1（系図）、12:23（ベルゼブル論争）、15:22（カナンの女）、21:9（エルサレム入城））ルカでも、降誕物語からは、ダビデの子孫であることが語られるが、ヨハネ7:42「キリストは、ダビデの子孫から、またダビデのいたベツレヘムの村から出ると、聖書に書いてあるではないか」と言った。」や、系図の議論に関する注意（テモテ前書1:4、テトス3:9）を考え、聖霊による処女降誕などの話を考えると、血筋として、ダビデの子孫かどうかは、あまり重要ではないとしたほうがよいように思う。そのいみで、ダビデの子かという問いも、血筋について無関係と理解したほうが良いだろう。

マルコは最後「37b 大ぜいの群衆は、喜んでイエスに耳を傾けていた。」で終わっている。問答は前段で終了し、群衆は、イエスの話に非常に良い印象をもっていたことが書かれているのだろう。問答における驚かされる応答とともに、このような議論においても、イエスの聖書の一歩深い理解を通して語られており、非常に興味深い。

### **律法学者を非難する**

**聖書箇所：**[マルコによる福音書12章38-40節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_38-40.pdf)

大ぜいの人々に、「律法学者に気をつけなさい」とイエスは教えている。律法学者に対して、非難しているのではなく、教えの一部として語られていることがたいせつなのだろう。すなわち、ここから、どのような学びを得るかということである。単に、「長い衣を着て歩くこと」や「広場であいさつされること」や「会堂の上席、宴会の上座を好」むことや、「やもめたちの家を食い倒」すことや、「見えのために長い祈」をしなければ良いのだろうか。もし、そうであれば、そのようなものを避けるように教えるべきである。

マルコの律法学者非難は簡素で短く、マタイは非常に長く、ルカは異なる形にまとめてあるようだがそれは何を意味するのだろうか。調べてみると、マルコでは、イエスがパリサイということばを出す箇所は、マルコ 8:15 そのとき、イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。だけのように思われる。イエスの受難告知でも、律法学者としている。ユダヤ人が多い地域で、対抗上、イエスの律法学者批判が拡大しているのかもしれないが、マルコでは、教えに集中しているとして、理解すべきだろう。

しかし、マルコの最初から見てみると、まず、イエスの教えに関して「人々は、その教に驚いた。律法学者たちのようにではなく、権威ある者のように、教えられたからである。」（マルコ1:22）からはじまり、律法学者やパリサイ人が絡む記事が非常に多いことに気付かされる。ということは、やはり、「律法学者に気をつけなさい」という教えを通して、イエスの真意を受け取らなければならない。

律法学者の対極はおそらくイエスであり、イエスに従うことが、律法学者に注意することなのだろう。すでに、最も大切な戒めとした目的が、神様を愛すること、隣人を愛することからズレてしまっていることを指摘しているのではないだろうか。それを示すには、この短い箇所で十分なのかもしれない。同時に、それは、キリスト者にも同じ危険があることを示してもいるだろう。神様を愛そうとしてはじめたことが、そこから離れてしまう。隣人を愛そうとしてはじめたことが、そこから離れてしまう。離してしまうものは何なのだろうか。おそらく、それが、自分中心視点、利得をもとめることなど、最初の目的とは離れたことが入り込んでしまっていることなのだろう。それを偽善というのかもしれない。自ら気づくことは難しいのかもしれないが、イエスは、それに気づくように促しているように見える。

### **やもめの献金**

**聖書箇所：**[マルコによる福音書12章41-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_41-44.pdf)

イエスが、賽銭箱に向かって座り、様子を見ていると、多くの金持ちがたくさん賽銭箱に投げ入れているのに対し、一人の貧しいやもめがレプタ二枚を捧げたのをみて、弟子たちに、「よく聞きなさい。あの貧しいやもめは、さいせん箱に投げ入れている人たちの中で、だれよりもたくさん入れたのだ。みんなの者はありあまる中から投げ入れたが、あの婦人はその乏しい中から、あらゆる持ち物、その生活費全部を入れたからである」と教えた箇所である。

マルコと、ルカは、ほぼ同じ構成で、やもめの献金を、ダビデの子についての問答、律法学者を非難する箇所のあと、神殿の崩壊を予告するの前においている。教える相手について、マルコでは、途中で「弟子たちを呼び寄せて」語られるが、ルカでは、その記述はなく、その前の律法学者を非難する箇所の冒頭の、「民衆が皆聞いているとき、イエスは弟子たちにいわれた。」（20:15）から続いているように思われる。内容を見ると他にもマルコとルカの違いがある。マルコには「さいせん箱にむかってすわり Καὶ καθίσας κατέναντι (over against) τοῦ γαζοφυλακίου」とあるがその部分はルカにはない。そのあとも「多くの金持ち　πολλοὶ πλούσιοι」「ひとりの貧しいやもめ μία χήρα πτωχὴ」とマルコではなっているが、ルカでは「金持ちたち」「ある貧しいやもめ」となっている。短い箇所ではあるが全体として、ルカには、マルコの現場を切り取ったような表現が欠け、話し、または教えとしてまとめられているように見える。マタイでは、ダビデの子についての問答のあとは、律法学者とファリサイ派の人々を非難する箇所が殆ど一章続き、最後にルカでは別の箇所に含まれ、マルコにはない、エルサレムのために嘆く記事（マタイ23:37-38, ルカ13:34-35）があり、このやもめの献金についての記事はない。すなわち、律法学者やファリサイ派の人々は批判し、エルサレムが中心であることについては批判的でも、やもめの献金に対して最大の評価をする記事は入れられなかった背景があるのかもしれないと考えられる。ユダヤ人キリスト者の指導的な立場の人達が著書だったことと関係しているのだろうか。

貧しいやもめはなにかの象徴だろうか。やもめのようになれと言っているのだろうか。それとも、そうではないひとを非難しているのだろうか。おそらくそう単純ではないだろうが、少数者（minority）として描かれ、多数者（majority）には、「多くの金持ち」だけでなく、「ありあまる中から投げ入れた」「みんなの者」が含まれ、さらに、弟子たち、クリスチャンにも呼びかけられているのだろう。それ故に、マタイはこの箇所を加えず、律法学者やパリサイ人への批判・呪いでとめておいたのか。そう考えると、キリスト者自身として、心配になり、恐ろしくもなる。現代のキリスト者はどう読むだろうか。しかし、同時に、この貧しいやもめのようになりなさいと言っているのかと言う問いは、深く考えないと行けないと思う。同時に、ザアカイが財産の半分捧げて、イエスに「きょう、救がこの家にきた。」と言われたように、全財産を捧げるのが良いと考えるのもおそらく、適切ではない。

律法学者を非難する前段では、律法学者が律法の真意をそれを守ることによって神様の御心を行い、人々に教えることから離れて、またはそれて、違った方向にいってしまったことが問題であったように思われる。このやもめの献金の箇所でも、献金や寄付の本来の意味からそれてしまっていることが指摘されているのかもしれない。では、献金のとは寄付の目的は何なのだろうか。それをまず考えなければならない。「神様の恵みと憐れみに対する感謝の応答として神様の業に捧げ物と奉仕によって加えさせていただくこと」だろうか。すなわち、神様との関係の営みの中に、捧げ物があるはずである。しかし、それが、自分の義を見せびらかすことになってしまっているのか。それを指摘しているのが、マタイ6章2節の「だから、施しをする時には、偽善者たちが人にほめられるため会堂や町の中でするように、自分の前でラッパを吹きならすな。よく言っておくが、彼らはその報いを受けてしまっている。」かもしれない。

しかし、この箇所では、同時に、強烈な対比がある。イエスの「だれよりもたくさん入れた」という根拠が、「みんなの者はありあまる中から投げ入れたが、あの婦人はその乏しい中から、あらゆる持ち物、その生活費全部を入れたからである」となっている点である。律法を徹底するとういマタイの山上の垂訓の背景とは異なり、もっと直接的に、神様の視点を教えているように見える。すなわち、神様がどう見ておられるかをイエス様の視点から教えているのだろう。

では、イエスの目から見て（神様の秤で）やはりたくさんいれることがよいのかという問いが生じるが、それも少し違うように思う。では、結局、何を教えているのだろう。神様の視点を解き明かすだけでよいのだろうか。このやもめに「安心して行きなさい。あなたの信仰があなたを救った。」（マルコ5:34,10:52）と言えるだろうか。神さまに委ねることで良いのだろうか。正直、このやもめの明日がきになってしまう。さらに、このやもめが、もし、その前の律法学者を非難する箇所にあるような、律法学者に家を食い倒された（マルコ12:40）やもめだったら、放って置いて良いのだろうか。どう考えたら良いのだろうか。

この答えはわたしはわからない。しかし、おそらく、それは、正しい答えをイエスに教えてもらうのではなく、わたしたち一人ひとりが、神様の御心を行うことによって、神様とともに働くことに加えさせていただくことに、委ねられているのだろう。Savior Complex （わたしが助けなければいけないという強い感情）はどうしたら良いのだろうか。わからないことは、多い。

### **神殿の崩壊を予告する**

**聖書箇所：**[マルコによる福音書13章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2.pdf)/[マルコによる福音書13章1-2, 3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2_3-13.pdf)

神殿の壮麗さに注意を促した弟子のひとりに対して、「あなたは、これらの大きな建物をながめているのか。その石一つでもくずされないままで、他の石の上に残ることもなくなるであろう」。とイエスが答えている箇所で、この次の段落に続く。

柱はすべて金箔で覆われ、それ以外の部分も大きな大理石で作られていたため、白く輝いていたと、ヨセフスが描いている神殿であるが、AD66年からのユダヤの反乱に対し、AD70年に、ローマのテトス将軍によって補給路を断つことで、エルサレム内が飢饉となり、ユダヤは敗北。ローマ軍が金箔を剥がし取るために、丁寧に石柱を「その石一つでもくずされないままで、他の石の上に残ることもなくなる」かたちで、神殿を破壊したと言われている。

その意味で、ここに書かれているイエスのことばは、40年も前に、そのことを預言したものだと言われ、また学者たちは、あまりにも記述が正確で、それが、おそらく、AD70よりもあとに書かれた、マタイやルカにも全く同じ記述で書かれていることから、マルコが書かれたのも、AD70年代ではないかとも言われている。

神殿破壊のことは、ヨハネ2:19 にも、イエスが、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。と語ったと書かれており、このことは、マタイ27:40でも「神殿を打ちこわして三日のうちに建てる者よ。もし神の子なら、自分を救え。そして十字架からおりてこい」。と、イエスを非難する言葉として書かれているので、こちらの方は、確実にイエスの言葉であろうと思われる。無論、それだからと言って、13章2節をイエスが言わなかったことにはならない。

しかし、この言葉は、基本的には、やもめの献金に関する記事に引き続き、物質的な壮麗さに目を奪われている、「弟子の一人」に対して、物質的な壮麗さは失われることを告げたものだとも取ることができる。その意味でも、預言の成就にこだわらない方がよいように思われる。

実際、このあとに続く会話でも、「いつ、そんなことが起るのでしょうか。」との問いからはじまるが、イエスは、AD70 年のことにとらわれず、主の日や、終わりの時などについて、考えている弟子たちに、たいせつなことを教えようとしておられる。人間の興味としては、世の終わりや、預言の成就に心が囚われてしまうことは、仕方がないが、イエスのメッセージはそこには、ないと思われる。

### **終末の徴**

**聖書箇所：**[マルコによる福音書13章3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_3-13.pdf)/[マルコによる福音書13章1-2, 3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2_3-13.pdf)

神殿のことに関するイエスの言葉を受けて、ペテロ、ヤコブ、ヨハネ、アンデレが、ひそかに 「わたしたちにお話しください。いつ、そんなことが起るのでしょうか。またそんなことがことごとく成就するような場合には、どんな前兆がありますか」。と尋ね、それに対して、イエスが応答している箇所である。

四人の中心的な弟子たちが「ひそかに」「わたしたちにお話しください」とイエスに尋ねる描写はとても、リアルで、弟子たちが、われわれと同じ地平に立っていることを感じさせ、親近感を感じる。しかし、おそらく、そのような問いにも、イエスは、注意すべき点、神様の御心をと伝えているのだろう。

にせのイエスに惑わされるな。戦争や自然災害や飢饉は起こっても、それで終わりではないこと。福音のために証言を求められる。そして、家族などすべての人に憎まれる。と書かれ、それぞれについて、注意点を語っている。一つ一つ実際にこのあと起こったことなのだろう。

個人的には、愛をたいせつにするにもかかわらず、すべての人に憎まれるようになるという箇所がとても衝撃的である。どう向き合えば良いのだろうか。さらに、「福音はまずすべての民に宣べ伝えられねばならない。」とも書かれている。これはどう理解すれば良いのだろうか。考えたい。

### **大きな苦難を予告する**

**聖書箇所：**[マルコによる福音書13章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_14-23.pdf)/[マルコによる福音書13章14-23, 24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_13-23_24-27.pdf)

「荒らす憎むべきものが、立ってはならぬ所に立つのを見たならば（読者よ、悟れ）、そのとき、ユダヤにいる人々は山へ逃げよ。」（14）と始まるこの箇所は、まず、二重の意味があることを理解しなければいけないのだろう。すなわち、直接的には、神殿破壊がされる、ユダヤ戦役（AD66-70）のときのことであり、そして、そこで終わらない、将来のことについて語られている二重の構造である。実際、「荒らす憎むべきもの」は一義的には、ユダヤ教を冒涜し棄教させるために、神殿におぞましいものをもちこんだシリアのアンティオコスによるギリシャ化が想定されている。しかし、それは、イエスの時代にすでに終わっていることでもある。マルコが書かれた時代がユダヤ戦役の前か後かは不明だが、いずれにしても、それこそがこの箇所の預言ではないのだろう。もし、その預言のために書かれたのであれば、その時をもって、意味を失う。実際、「山へ逃げよ」と語られ、ユダヤにいた、その教えゆえに、キリスト者の多くは、山に逃げ、ローマによって滅ぼされなかったことも伝えられている。さらに、ここには「ユダヤにいる人」と限定的にも語られており、キリスト者は、すでに、広い範囲に広がっていたことも想定されている。つまり、ローマによるエルサレムの破壊、神殿崩壊は、ここで語られていることと重なると言えども、それが終わりではないことも確かである。それを理解して、読まなければならない。

イエスが伝えたかったことは、この前の部分（13節まで）で尽きているようにも見えるが、同時に、そこで言われていることが、そのあとの時代に起こったことに照らして、理解しようとしているとも考えられる。いずれにしても、難しい箇所である。

### **人の子が来る**

**聖書箇所：**[マルコによる福音書13章24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_24-27.pdf)/[マルコによる福音書13章14-23, 24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_13-23_24-27.pdf)

また、イエスの再臨、世の終わりといわれるものが、来ないとは言っていない。まさに、「24 その日には、この患難の後、日は暗くなり、月はその光を放つことをやめ、25 星は空から落ち、天体は揺り動かされるであろう。26 そのとき、大いなる力と栄光とをもって、人の子が雲に乗って来るのを、人々は見るであろう。」である。このことに注意を向けなければいけない。

ただし、旧約聖書の預言、そして、ダニエル書からの引用などが中心で、正直、イエスがこのような再臨の現象のことを弟子たちに伝えていたかは、よくわからない。しかし、それは、再臨がないということではない。ヨハネによる福音書などにも、イエスが戻ってくることは繰り返し述べられている。ただ、世の終わり、再臨などについて、イエスが何を私達に伝えたかったのかは、正直よくわからない。おそらく、弟子たちが知りたかったことに、かき消され、もともとのイエスのメッセージを読み取るのが難しくなっているのかもしれない。わたしたちは、主に従って、どう生きるかよりも、そのときがいつで、どのような前兆があるかのほうに、興味が行ってしまうように思う。それは、おそらく、イエスがわたしたちに伝えたかったこととは異なるのだろう。

### **いちじくの木の教え**

**聖書箇所：**[マルコによる福音書13章28-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32.pdf)/[マルコによる福音書13章28-32, 33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

いちじくは、パレスチナでは、非常に一般的な植物であり、果実でもある。すぐ思い出すのは、創世記3:7 「すると、ふたりの目が開け、自分たちの裸であることがわかったので、いちじくの葉をつづり合わせて、腰に巻いた。」や、民数記13:23 「ついに彼らはエシコルの谷に行って、そこで一ふさのぶどうの枝を切り取り、これを棒をもって、ふたりでかつぎ、また、ざくろといちじくをも取った。」がある。

マルコとマタイでは「そのように、これらの事が起るのを見たならば、人の子が戸口まで近づいていると知りなさい。」としているが、ルカでは、「神の国が近いのだとさとりなさい。」としている。しかし、「30 よく聞いておきなさい。これらの事が、ことごとく起るまでは、この時代は滅びることがない。」は、三つの福音書とも共通している。マルコと、マタイには「その日、その時は、だれも知らない。天にいる御使たちも、また子も知らない、ただ父だけが知っておられる。」があるが、ルカにはそれはない。しかし、「天地は滅びるであろう。しかしわたしの言葉は滅びることがない。」は、三つの福音書とも共通である。

終わりの時は、子も知らないと言っている。そうであれば、わたしたちが、いつかを議論することは、おそらく、無意味なこと、すべきことではないのだろう。それよりも、すべきことがある。

### **目を覚ましていなさい**

**聖書箇所：**[マルコによる福音書13章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_33-37.pdf)/[マルコによる福音書13章28-32, 33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

「目を覚ましていなさい」の部分は、マルコと、マタイのみで、ルカには欠けている。マルコでは、「気をつけて、目をさましていなさい。」が強調され二度繰り返されているが、マタイでは、「ノアの時」のことの描写や、「盗賊」に対する備えなどを加えて、より具体的になっている。ルカでは、並行箇所は、ないが、関連する段落が続いている。

ここのメッセージは、単純で「気をつけて、目をさましていなさい。」である。おそらく、日常的に、気をつけ、目を覚ましていなければいけないのだろう。

### **イエスを殺す計略**

**聖書箇所：**[マルコによる福音書14章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2.pdf)/[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)/[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

「過越と除酵との祭の二日前に、祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。」とあり、さらに、彼らは、「祭の間はいけない。民衆が騒ぎを起すかも知れない」と言っていた。とある箇所である。過越の日（金曜日）にイエスが十字架にかかることを考えると、水曜日だろうか。

このように計画したにもかかわらず、実際には、祭りの間に十字架に架かることも興味深い。このあとの女の人が香油を注ぐ記事は、ヨハネによる福音書によると、過越祭の六日前とあり、順序は編集されているのかもしれない。

マルコでは、実際に、なぜ、祭司長たちや律法学者たちが、イエスを殺そうと思ったかは、あまり明らかではない。ヨハネによる福音書によると、11:48 に、ラザロの復活の後に、「もしこのままにしておけば、みんなが彼を信じるようになるだろう。そのうえ、ローマ人がやってきて、わたしたちの土地も人民も奪ってしまうであろう」。とあり、この最後に書かれていることが起こることを、民のリーダたちは恐れていたことがわかる。他にも理由は、あったのだろうか。

### **ベタニアで香油を注がれる**

**聖書箇所：**[マルコによる福音書14章3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_3-9.pdf)/[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

ヨハネでは、過越祭の六日前となっており、マルコは、エルサレム入場を先に置き、ラザロの復活を描いていないので、イエスに対して、民の指導者たちの行動、この女の行為と、イスカリオテのユダのことを並べることで、イエスの周辺の人たちを描くことにしているのだろう。おそらく、実際には、ヨハネのように、過越祭の六日前に起こったことなのだろう。

マルコは、ベタニヤの、マルタ、マリヤ、ラザロのことを書かず、ここでも、重い皮膚病のシモンの家とだけ書いている。この人については、マルタ、マリヤ、ラザロと近い関係のひとと思われるが不明である。いずれにしても、リチャード・ボウカムが言っているように、マルコが書かれた時点では、マルタ、マリヤなどが生きており、エルサレムの近くで危険が及ぶことを避け、この女の名前の書かず、この家族と、イエスの近しい関係を伏せていたと考えるのが妥当であると思う。

さて、「ひとりの女が、非常に高価で純粋なナルドの香油が入れてある石膏のつぼを持ってきて、それをこわし、香油をイエスの頭に注ぎかけた。」（3b）と始まる。これが異常な行為であることは、このあとの、人々の反応からも、確かである。そのことを強調するためにも、マルコでは、一般的に人々と書いているのかもしれない。マタイでは、弟子たちとし、ヨハネでは、このあとの「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」（12:5）との発言を、イスカリオテのユダに記すことで、弟子たちなど、周囲にいるひとから、批判を遠ざけている。周囲の人は、多かれ少なかれ、驚いたのではないだろうか。

核は、まず、この行為をした女のひとを、人々が咎めたことに対し、イエスが庇（かば）ったことである。まず「するままにさせておきなさい。なぜ女を困らせるのか。わたしによい事をしてくれたのだ。」（6b）と言っている。まずは、この女の人を守っている表現である。ここにあるよい事の「よい」はカロスが使われており、NIV では beautiful thing と訳しているように、アガトス（倫理的善）とはことなり、美しい行為というような意味である。ある意味では、主観でもある。

そして、次には、「貧しい人たちはいつもあなたがたと一緒にいるから、したいときにはいつでも、よい事をしてやれる。しかし、わたしはあなたがたといつも一緒にいるわけではない。 この女はできる限りの事をしたのだ。すなわち、わたしのからだに油を注いで、あらかじめ葬りの用意をしてくれたのである。」（7,8）なにか、イエス自身を特別な存在としているように思われるが、裏に秘められた、たいせつなことを伝えようとしているのだろう。

ひとは、銅貨2枚捧げたやもめはたいしたことをしないと評価し、高額なものを捧げたこの女にたいしては勿体ないことをするとする。しかし、イエスが示す神の視点は、もうすこし広いのだろう。絶対的な価値観を示すのではなく、そうではない見方もあるよと示しているように見える。

ヨハネにあるように、これが、マルタの兄弟マリアだとすると、少し違った見方もできるように思う。マリヤは、ヨハネ11章からこの箇所に続く箇所と、ルカ10章38-42節に登場するが、マルタは、さまざまなことを語っているが、マリヤは「主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう」（11:32）と言っているだけで、かつこのことばは、マルタが11章21節で言ったのとまったく同じことばである。マリヤは常に座っており、給仕している、マルタとの対比が描かれている。障害者とは言えないかもしれないが、対人行動に関する強い特性をもった女性であったと思われる。そう考えると、そのような女性をイエスが庇ったことが書かれているととることもできる。

さて、マリヤはどのように考えて香油を注いだのだろう。石膏の壺をこわしたことから、すべてを捧げようとしたことがわかる。この直前には、兄弟ラザロの復活のことが書かれているから、そのことへの感謝を表現したともとれないことはないが、おそらく、それにとどまらない、マリヤの思いが詰まっていたのだろう。コミュニケーション、または、対人行動特性があるからこそ、他の人は受け取れなかったメッセージを、イエスからしっかり受け取っていたのかもしれない。具体的に、葬りの準備まで考えていなかったとしても、この女性が与えられ、受け取ったこと、「できる限りの事」「美しい行為」をしたのだろう。そして、それをイエスは、最大の賛辞をもって受け取られた。

イエス様の中の主なる神様は、そのような方なのだろう。ある行為を、値踏みして、こちらの方が良いとして、その行為を咎められるような形ではないのだろう。

### **ユダ、裏切りを企てる**

**聖書箇所：**[マルコによる福音書14章10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_10-11.pdf)/[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

文脈としては、マルコ14章1,2節からつながっている。民衆のイエスに対する人気が高まっていくかなで、そのことを危険視した、祭司長たち、律法学者たちが、イエスをどうにかして、捕え、殺そうと考えた時に、イエスの引き渡しに応じたのがイスカリオテのユダだとされる。

しかし、マルコでの記述は、非常に限られている。マルコで、イスカリオテのユダが登場するのは、十二弟子を選んだ箇所（3:13-19）、今回の箇所と、イエスがゲッセマネで捕縛される箇所（14:43-50）のみである。しかし、マタイでは、最後の晩餐のときにも、イスカリオテのユダだけ別に取り扱っており（マタイ26:25）、また、マタイと、ルカ由来の使徒行伝では、イスカリオテの死についても書いている。（マタイ27:3-10、使徒1:18-19）

後から書かれたとされるヨハネではかなり詳しい。まずは、十二弟子以外がイエスを離れていくことが書かれているヨハネ6章の最後（6:70,71）に、「イエスは彼らに答えられた、『あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である』。これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。」と書かれ、さらに、ベタニアでマリアが香油を注ぐ箇所で、「弟子のひとりで、イエスを裏切ろうとしていたイスカリオテのユダが言った、「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」。彼がこう言ったのは、貧しい人たちに対する思いやりがあったからではなく、自分が盗人であり、財布を預かっていて、その中身をごまかしていたからであった。」（12:4-6）とある。また、最後の晩餐においては、次のように書かれている。

> 21 イエスがこれらのことを言われた後、その心が騒ぎ、おごそかに言われた、「よくよくあなたがたに言っておく。あなたがたのうちのひとりが、わたしを裏切ろうとしている」。22 弟子たちはだれのことを言われたのか察しかねて、互に顔を見合わせた。23 弟子たちのひとりで、イエスの愛しておられた者が、み胸に近く席についていた。24 そこで、シモン・ペテロは彼に合図をして言った、「だれのことをおっしゃったのか、知らせてくれ」。25 その弟子はそのままイエスの胸によりかかって、「主よ、だれのことですか」と尋ねると、26 イエスは答えられた、「わたしが一きれの食物をひたして与える者が、それである」。そして、一きれの食物をひたしてとり上げ、シモンの子イスカリオテのユダにお与えになった。27 この一きれの食物を受けるやいなや、サタンがユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。28 席を共にしていた者のうち、なぜユダにこう言われたのか、わかっていた者はひとりもなかった。29 ある人々は、ユダが金入れをあずかっていたので、イエスが彼に、「祭のために必要なものを買え」と言われたか、あるいは、貧しい者に何か施させようとされたのだと思っていた。30 ユダは一きれの食物を受けると、すぐに出て行った。時は夜であった。

27節には「この一きれの食物を受けるやいなや、サタンがユダにはいった。」とある。ルカでは22:3 に 「そのとき、十二弟子のひとりで、イスカリオテと呼ばれていたユダに、サタンがはいった。」とある。

まず、これらの違いをどう理解するかという問題が生じる。ひとつの考え方は、しばらくは、イスカリオテのユダが、裏切ったところまではわからなかったということである。時が経つにつれて、明確になって行ったということかもしれない。しかし、マルコにおいても、ユダがイエスの捕縛の際に手引きをしたことは明らかなので、ユダが裏切った背景、いつから裏切ろうとしていたかなどが、ペテロなど、ほかの十二弟子に明らかではなかったと言うことなのかもしれない。四福音書とも、ペテロがイエスを否んだ記事がかかれていることもあり、また、他の弟子たちは、かなり勇敢なことを言っていたものもいたが（ヨハネ11:16）、イエスの捕縛のときに、イエスを捨てて逃げ去ったこともあり、ユダを問いただすこともなかったのかもしれない。

福音書より先に書かれたとされている、コリント前書15:4,5には、「4 そして葬られたこと、聖書に書いてあるとおり、三日目によみがえったこと、5 ケパに現れ、次に、十二人に現れたことである。」とあり、イスカリオテのユダを区別していない。キリスト教会で、イスカリオテのユダ以外の弟子たちが、神聖化されていく過程で、だんだんとこのあたりが、差別化されていったのかもしれない。

では、イスカリオテのユダは、本当に、何が理由で、イエスを裏切ったのだろうか。イスカリオテのユダの死について描いている、マタイの記述をみると、イエスが死刑の判決を受けたことは、イスカリオテのユダの本意ではなかったように取れる。すると、窮地に陥れることで、熱心党のように、イエスが特別な力を発揮して、世の中を変えるという期待を持っていたという説も登場するが、明確にはわからない。ヨハネが書くように、貪欲から、お金を誤魔化していたというところに、帰結するのも、すこし短絡なように見える。それがわからない程度に、早く、イスカリオテのユダは死んでいったのかもしれない。

### **過越の食事をする**

**聖書箇所：**[マルコによる福音書14章12-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_12-21.pdf)

イエスを捕らえ殺す計画があり、イスカリオテのユダが、イエスを機会を捕らえて、引き渡す約束を祭司長にしたことが書かれた後という場面設定になっている。すなわち、読者は、誰が、イエスを裏切ったかを知っているという設定である。

まず、過越の食事の場所の準備のために、二人の弟子が遣わされる。「市内に行くと、水がめを持っている男に出会うであろう。その人について行きなさい。」イエスの指示についても、注意深く語られている。このあとも、その人に聞くのではなく、その人が入っていく家の主人に聞くことになっている。「するとその主人は、席を整えて用意された二階の広間を見せてくれるから、そこにわたしたちのために用意をしなさい」。とあり、準備をしにはいくが、席を整えて用意されたとあるので、何人の会食かも、すでに伝えてあったように見える。「弟子たちは出かけて市内に行って見ると、イエスが言われたとおりであったので、過越の食事の用意をした。」をイエスの予言的な力が顕れたと取ることも可能であるが、マタイには「かねて話してある人の所に行って」（26:18）とあるので、当時の人は、おそらく、それよりも、マタイの同じ節にある「わたしの時が近づいた」ことに焦点があると理解しただろう。

夕方となり、除酵祭の一日目に入り、過越の食事をするときに、十二弟子と一緒にそこに行き、席につかれたとある。十二弟子と、イエスだけが席に着いていたと考えることも可能だが、過越の食事は、エルサレムに上ったそして、そこにいる皆でするものであるだろうから、おそらく、他にも、気心が知れた人たちがいたのではないだろうか。この家の人たちや、イエスについてきた、女性たちである。（マルコ15:40,41）そのような場でのできごとであることを、考えておく必要がある。

まず、イエスは、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」と一同に告げている。（マルコ14:18b）まず、注意すべきは、「裏切った」とは言われていない。聖書の書かれていない、さまざまな情報があったのかも知れない。しかし、イエスにとって、十二弟子のひとりが裏切ろうとしていることは明らかだったのだろう。不思議なことである。ただ、ヨハネ6章66-71節などをみると、十二弟子は、多くの弟子たちが離れて行っても、着いてきた人たちであると同時に、離れていく可能性も十分あったのではないだろうか。その意味でも、イエスがこれまでも、何回も弟子たちに伝えてきた（マルコでは３回）捕らえられ、殺される時が近づいている今、一人一人に、自分の心を吟味させようとしたのかも知れない。このあとには、主の晩餐の記事があり、ペテロの離反の予告が続いている。主の晩餐について最初の書かれたと思われる、コリント第一の手紙11:23-29を引用する。

> 23 わたしは、主から受けたことを、また、あなたがたに伝えたのである。すなわち、主イエスは、渡される夜、パンをとり、24 感謝してこれをさき、そして言われた、「これはあなたがたのための、わたしのからだである。わたしを記念するため、このように行いなさい」。25 食事ののち、杯をも同じようにして言われた、「この杯は、わたしの血による新しい契約である。飲むたびに、わたしの記念として、このように行いなさい」。26 だから、あなたがたは、このパンを食し、この杯を飲むごとに、それによって、主がこられる時に至るまで、主の死を告げ知らせるのである。27 だから、ふさわしくないままでパンを食し主の杯を飲む者は、主のからだと血とを犯すのである。28 だれでもまず自分を吟味し、それからパンを食べ杯を飲むべきである。29 主のからだをわきまえないで飲み食いする者は、その飲み食いによって自分にさばきを招くからである。

このあとのイエスのことばは、解釈が別れるところだろう。

> 20 イエスは言われた、「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者が、それである。21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。

ここで、十二弟子の中の一人であることが明確になっている。21節は、どう理解したら良いのだろうか。今回、読んで、単純に、「自分について書いてあるとおりに」または、定められたとおりに、または、わたしが、あなたがたに何度も伝えてきた通りにぐらいのいみだろうか、実は「書いてある」とあるが、旧約聖書からの引用だとすることは難しいように思う。（イザヤ書52:13-53:12のようなしもべの姿はイエスの中に明確にあったと思われる。）そして、後半である。定められた通りであったとしても、そこに関与し、裏切ることとなるものは、やはり、とても、悲しいことで。そのようにして、多くの苦しみを負うことは、堪えられないことで、そのひとの人生は、ほんとうに悲しいものだという嘆きの表現ではないだろうかと思った。そして、そのようなことを考えているものがあれば、ここで、悔い改め、違う生き方をしてほしいということではないだろうか。すると、他の弟子にも繋がる、メッセージである。「だれでもまず自分を吟味し」て、主の晩餐に預かるべきである。

人は、どうしても、最初に使わされた二人の弟子はだれなのかと考える。ルカでは、この二人は、ペテロとヨハネだとしている。（ルカ22:8）イスカリオテのユダではないことは、確かだろうが、この二人かどうか、また否定する根拠もない。ただ、ルカ文書とされる、使徒行伝では、3章、4章、8章に、ペテロとヨハネという記述があり、十二弟子の中で中心となったひとたちとして度々登場するので、ここでもそうしたのかも知れない。

また「弟子たちは心配して、ひとりびとり『まさか、わたしではないでしょう』と言い出した。」とあり、そして、当然、イエスは、イスカリオテのユダが裏切ることを知っていたことも前提として、このとき、ユダが「まさか、わたしではないでしょう」と答えていたら、イエスは、どうしただろうかと考えるのも自然である。マタイ26:25 には「イエスを裏切ったユダが答えて言った、『先生、まさか、わたしではないでしょう』。イエスは言われた、『いや、あなただ』。」と書かれている。この最後は、直訳は、「それはあなたの言ったことです」なので、肯定の意味に使われることもあるようだが（マルコ15:2 「ピラトはイエスに尋ねた、『あなたがユダヤ人の王であるか』。イエスは、『そのとおりである』とお答えになった。」も同種の言葉）、塚本虎二訳のように「いや、そうかもしれない」ぐらいの方が、余韻があるように思われる。明確に「いや、あなただ」と答えたとした時に、他の弟子たちが、反応しなかったとは考えにくい。

ヨハネの書き方も、マタイに近いが、席順も暗示するかのように書かれている。イエスが寝そべり、その右に、「イエスの愛しておられた者」がみ胸に近く席についていて、ペテロがイエスに聞くように促す。すると、イエスは「『わたしが一きれの食物をひたして与える者が、それである』。そして、一きれの食物をひたしてとり上げ、シモンの子イスカリオテのユダにお与えになった。この一きれの食物を受けるやいなや、サタンがユダにはいった。」としていある。しかし、このあと、弟子たちが、イスカリオテのユダが裏切ろうとしていたことを認識しなかったことをみると、これも、どの程度正確なのか、後付けのように感じる。また、この「イエスの愛しておられた者」が誰なのかも、議論になる。ゼベタイの子、ヤコブの兄弟ヨハネとする説も有力だが、のちに長老ヨハネとされる人物だとする説もある。すると十二弟子以外のものが近くにいたこととなる。ヨハネは、かなり早い時期から、すべてお見通しといった記述がある。それは、後からの信仰告白だったように思われる。

> ヨハネ2:23 過越の祭の間、イエスがエルサレムに滞在しておられたとき、多くの人々は、その行われたしるしを見て、イエスの名を信じた。24 しかしイエスご自身は、彼らに自分をお任せにならなかった。それは、すべての人を知っておられ、25 また人についてあかしする者を、必要とされなかったからである。それは、ご自身人の心の中にあることを知っておられたからである。
>
> ヨハネ6:60-71 60 弟子たちのうちの多くの者は、これを聞いて言った、「これは、ひどい言葉だ。だれがそんなことを聞いておられようか」。61 しかしイエスは、弟子たちがそのことでつぶやいているのを見破って、彼らに言われた、「このことがあなたがたのつまずきになるのか。62 それでは、もし人の子が前にいた所に上るのを見たら、どうなるのか。63 人を生かすものは霊であって、肉はなんの役にも立たない。わたしがあなたがたに話した言葉は霊であり、また命である。64 しかし、あなたがたの中には信じない者がいる」。イエスは、初めから、だれが信じないか、また、だれが彼を裏切るかを知っておられたのである。65 そしてイエスは言われた、「それだから、父が与えて下さった者でなければ、わたしに来ることはできないと、言ったのである」。66 それ以来、多くの弟子たちは去っていって、もはやイエスと行動を共にしなかった。67 そこでイエスは十二弟子に言われた、「あなたがたも去ろうとするのか」。68 シモン・ペテロが答えた、「主よ、わたしたちは、だれのところに行きましょう。永遠の命の言をもっているのはあなたです。69 わたしたちは、あなたが神の聖者であることを信じ、また知っています」。70 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である」。71 これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。

### **主の晩餐**

**聖書箇所：**[マルコによる福音書14章22-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_22-25.pdf)/[マルコによる福音書14章22-25節 福音書対照表（参照付き（２））](https://icu-hsuzuki.github.io/science/bible/docs/mark14_22-25_extra2.pdf)

最後の晩餐でのクライマックスと言われる場面で、キリスト教会において、聖餐式の起源となった箇所である。聖餐式について最初に書かれたのは、コリント人への第一の手紙11章23-28節の記事のようだが、マルコによるものの方が単純で、こちらが伝承としては、古いものなのかとも思わされる。マタイは、マルコを土台にして、少し詳しく説明しているように見える。パンにおいてはマルコでは単に「取れ」であるのに対し、マタイでは「取って食べよ」、杯に関しては、マルコでは、単純に「これは、多くの人のために流すわたしの契約の血である。」としているが、マタイでは「罪のゆるしを得させるようにと」という目的が加わっている。なお、ルカは、「新しい契約」ということばも使われており、パウロとの関係の近さからか、コリント人への第一の手紙の記述に似ているように思われる。

マルコは、これまでに、イエス自身が、受難と死、復活について三度（マルコ8:31、9:31、10:34）語っており、ぶどう園の農夫のたとえ（マルコ12:1-12）でも、子が殺されることが言われている。しかし、死の意味については、語られていなかった。「あがない」についても、マルコ10:45 に一度「人の子がきたのも、仕えられるためではなく、仕えるためであり、また多くの人のあがないとして、自分の命を与えるためである。」と書かれているが、死の意味が語られているとまでは言えないだろう。そのいみでも、受難と死の意味について語られたのは、マルコでは、この箇所が最初だと思われる。

まず、「一同が食事をしているとき、イエスはパンを取り、祝福してこれをさき、弟子たちに与えて言われた、『取れ、これはわたしのからだである』。」とあり、裂かれたパンをイエスの体としているので、イエスのからだ、イエスの裂かれたからだを食すことにより、イエスの犠牲を受け入れ、イエスとの霊的な交わりに入ることを意味するのだろうが、祝福してこれをさきとあり、これは、自然な行為であり、ここから、イエスの裂かれたからだを想起するのは、後付けのようにも感じる。種入れぬパンは、罪のないことを意味しているとされているが、そこまで確実かどうかは不明である。

杯については「また杯を取り、感謝して彼らに与えられると、一同はその杯から飲んだ。イエスはまた言われた、『これは、多くの人のために流すわたしの契約の血である。』」と言っている。「契約」とくことばが使われたことの重さはあるだろう。また、過越祭の食事の時であり、出エジプト24:3-8の契約が意識されていることは確かだろうが、これが、マタイのように「罪の赦し」とまで明確に言えるかどうかは、これだけではわからないように思う。

原始的な形で、過越の祭の食事におけるこのパンと、杯のことが記録されたことにはとても重要な意味を持っていると思うが、世世に続く、キリスト教の中心的なサクラメントである聖餐式の起源としては、寂しいと感じてしまう。

ここからは、まったく個人的な解釈だが、マルコを読んでいると、弟子たちは、イエスの死に、向き合えていないように思われる。そのなかで、十二弟子の中に裏切ろうとしているものがいると言われて動揺し、このあとにも、ペテロの離反予告の記事が続くことを考えると、自分たちのラビの死という、不吉さの中で、それ以外のことは、残らなかったのではないだろうか。かろうじて、通常の、過越祭の食事とは異なる、この場面を覚えていたのかもしれない。そこから、贖罪論を確立した、パウロを通して、イエスの死の意味が、弟子たちの間でも深められ、しばらくたって書かれたのが、ヨハネの福音書の記述なのだろう。

パウロはイエスの地上での活動について述べない。しかし、ここでは、歴史的な事項として、「わたしは、主から受けたことを、また、あなたがたに伝えたのである。すなわち、主イエスは、渡される夜、パンをとり」と始めていることは、非常に珍しい例であり、注目に値すると思う。このことは、弟子たちから聞いて、それをもとにしていると考えて良いだろう。

ヨハネでは、6章ですでに、贖罪について語られている。その意味で、最後の晩餐のとき、イスカリオテのユダの裏切りと、ペテロの離反について書く間に、聖餐式の起源となることを書かなくてもよかったのかもしれない。おそらく、当時は、人肉食（カニバリズム（英語: cannibalism））をしているとの批判があったこともあり、古い戒めによる古い契約と対比して、新しい戒めとして、ヨハネが大切なものとしてうけとった、互いに愛し合いなさいのメッセージを入れたように思われる。この戒めのところからは、ユダが排除されているように見えるが、それについては、さらに一考がひつようなように思われる。

「なぜ、パンとぶどう酒を配餐し、イエスの死について語る前に、弟子の裏切りのことを語ったのだろうか。」イエスの死の意味をどう考えるかが、イエスに従っていくことの鍵となっているからだろうか。同時に、イエスに従うことなしには、この戒めを理解できないのかもしれない。

最後の晩餐の記事は、イエスが、どうしても、このときを持ちたかったことが伝わってくるたいせつな時であるが、マルコでの記事はあまり長くない。このときに、十二弟子には、すべて受け取ることはできなかったのかもしれない。そして、そのような中で、最後の週の伝承が確立していったのかもしれない。しかし、この最後の晩餐の重要さを振り返り、ここに、多くのイエスのメッセージを詰め込み、13章から17章に含めたヨハネに感謝したい。むろん、時間がたつなかで、紡ぎ合わせた真理であり、イエスが語ったそのままかどうかは不明だが。

### **ペトロの離反を予告する**

**聖書箇所：**[マルコによる福音書14章26-31 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_26-31.pdf)

エルサレムでの過越祭の晩餐のあと、賛美を歌い、オリブ山にかけて行った時にイエスが「あなたがたは皆、わたしにつまずくであろう。」さらに「しかしわたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」と言うのに対して、ペテロが「たとい、みんなの者がつまずいても、わたしはつまずきません」と言い返し、それにイエスが「あなたによく言っておく。きょう、今夜、にわとりが二度鳴く前に、そう言うあなたが、三度わたしを知らないと言うだろう」という箇所である。このあと、ペテロも、みんなのものも同じように「たといあなたと一緒に死なねばならなくなっても、あなたを知らないなどとは、決して申しません」と言ったと記録されている。

晩餐の最初の方で「あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」（18）と言い、弟子たちはひとりびとり「まさか、わたしではないでしょう」という。さらに、裏切るのは、十二人の中のひとりであることを告げ、「たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。」（21）と伝え、そのあとに、パンを「これはわたしのからだである」とわたし、一同は杯から飲み「これは、多くの人のために流すわたしの契約の血である。」と告げることが描かれている。

ペテロについては、マルコ14:66-72（マタイ 26:69-75、ルカ 22:56-62、ヨハネ 18:15-18; 25-27）に、イエスを知らないと言う記事が記録されている。概要としては、四つの福音書ともに描かれている。とても、重要なこととして伝えているのだろう。また、マルコ14:50 には「弟子たちは皆イエスを見捨てて逃げ去った。」とあり、イエスにつまずくをどう理解するかにもよるが、他のでしたちも、イエスに最後まで従い通すことができなかったことが記録されている。

一方、イエスが伝えたふたつめの「わたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」については、マルコ16:7に「今から弟子たちとペテロとの所へ行って、こう伝えなさい。イエスはあなたがたより先にガリラヤへ行かれる。かねて、あなたがたに言われたとおり、そこでお会いできるであろう、と」。描かれているが、実際に、よみがえってからのことは、最も古い写本には、残されていない。しかし、現存のものからは、マルコと、マタイでは、ガリラヤで、復活のイエスが弟子たちと会うことが描かれているが、ルカおよび使徒行伝1:3,4では、昇天まで、エルサレムに留まっているらしいことが描かれ、ヨハネでは、20章までは、エルサレムで弟子たちに現れたことが描かれ、付録のような21章でガリラヤでのことが描かれている。また、ヨハネでは、この対応箇所でも、「主よ、どこへおいでになるのですか」。とペテロが問うところからはじめており、行く場所は、父のみもと（ヨハネ14:28）であることが想定されているようだ。

他の福音書との比較を追加しておくと、マタイは、マルコと非常に似ている。かろうじてことなるのは、マルコでは「にわとりが二度鳴く前に」とある「二度」を削除、ペテロが「力をこめて」言った部分の「力をこめて」が削除されていることのみである。ルカでは、全員に語られたと思われる、「あなたがたは皆、わたしにつまずくであろう。」から始まる部分はなく、また、「しかしわたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」も書かれていない。また、ルカには「22:31 シモン、シモン、見よ、サタンはあなたがたを麦のようにふるいにかけることを願って許された。32 しかし、わたしはあなたの信仰がなくならないように、あなたのために祈った。それで、あなたが立ち直ったときには、兄弟たちを力づけてやりなさい」。が付け加えられている。また、ペテロのことばに「主よ、わたしは獄にでも、また死に至るまでも、あなたとご一緒に行く覚悟です」（33）と、修正が加えられている。ヨハネでは「たしかに人の子は、自分について書いてあるとおりに去って行く。」(マルコ14:21)に呼応するように、または、ヨハネの新しい戒めのひとつ前にある、「子たちよ、わたしはまだしばらく、あなたがたと一緒にいる。あなたがたはわたしを捜すだろうが、すでにユダヤ人たちに言ったとおり、今あなたがたにも言う、『あなたがたはわたしの行く所に来ることはできない』。」（ヨハネ13:33）に関連づけるように、「主よ、なぜ、今あなたについて行くことができないのですか。あなたのためには、命も捨てます」。（ヨハネ13:37）と言っている。

弟子たちは、イエスの死の意味や、復活後のことについては、考えられないようすが、特に、マルコ（マタイも同様）からはみて取れる。さらに、ペテロも、おそらく他の弟子たちも、たとえ他の弟子はつまづいても、自分はつまづかないとも言っている。このような硬い覚悟の中、どうして、イエスを見捨てて逃げ去るのか、イエスを知らないと言うのかについては、対応する箇所で学ぶとして、イエスがどのような思いであったかについて考えてみたい。

イエスは、弟子たちは、つまづいても、信仰（どのようなものかは不明だが）イエスのもとにもどってくることを確信していたのだろうか。それは、イエスが神の子だから、超自然的な力でそれを予知したのだろうかと考える。それは、わからなかったのではないだろうか。ただ、どうなるにしても、神様に信頼していたと言うことではないだろうか。もしかすると、誰が裏切るか、それがイスカリオテのユダなのかも、はっきりとは知らなかったのではないかと思う。ただ、あきらかに、ルカでは、ペテロが、立ち直ることをイエスは知っている。また、ヨハネでも、「あなたはわたしの行くところに、今はついて来ることはできない。しかし、あとになってから、ついて来ることになろう」と書かれていることからも、ペテロが信仰を持ち続けることが想定されている。

最後に、イスカリオテのユダと弟子たちとの比較も考えてみたい。ほんとうに、イスカリオテのユダは、救いようがなく、他の弟子たちは、信仰が弱いとはいえ、問題がなかったのだろうか。すくなくとも、マルコには、それは、描かれていなようにもう思う。それは、イエスも知らず、神様に委ねられていたのではないだろうか。むろん、後からかかれた他の福音書では、そうはなっていないが。

### **ゲッセマネで祈る**

**聖書箇所：**[マルコによる福音書14章32-42 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_32-42.pdf)

イエスの祈りが書かれているだけでなく、弟子たちに、イエスの祈りとともにいてほしいという気持ちが、表現されている箇所に見える。

まず、最初に、弟子たちには、「わたしが祈っている間、ここにすわっていなさい」と言い、ペテロ、ヤコブ、ヨハネを一緒に連れて行き、「恐れおののき、また悩みはじめて」との表現のあと、三人には 「わたしは悲しみのあまり死ぬほどである。ここに待っていて、目をさましていなさい」。と伝えている。イエスは、神様のみこころを自分のものとするために、祈っている間、弟子たちにも、一緒に共にいてほしいと、願っている。さらに、中心的な弟子、ヤイロの娘を生き返らせた時（マルコ5:37）も、山上での変貌の時（9:2）も、一緒に連れて行った三人である。アンデレを加えると、最初の弟子たちとマルコが伝える四人になるが、この四人は（13:3）で、神殿が崩壊するような、世の終わりについて、ともに尋ねている箇所にも登場する。アンデレは、ヨハネによる福音書には、単独でも登場しているが、直接関係ないので省略。

アンデレを加えた四人が、終末について13章の最初（13:3）に問うている箇所の最後（13:33-37）が、「目をさましていないさい」となっている。弟子たちは、おそらく、この世の終わりについて考えていただろうが、まさに、イエスと共に、目をさましていなければならない、もっともたいせつなときに差し掛かっていることには、気づけなかったのだろう。イエスは、このときにも、一般的な世の終わりではなく、自らにとってたいせつなだけでなく、神様のみこころの成就に関して、とても、たいせつな十字架の時のことをも思って、このことばを伝えていたのかもしれない。

イエスは「少し進んで行き、地にひれ伏し、もしできることなら、この時を過ぎ去らせてくださるようにと祈りつづけ、そして言われた、 『アバ、父よ、あなたには、できないことはありません。どうか、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころのままになさってください』」と書かれている。

ルカでは「石を投げてとどくほど離れたところ」（ルカ22:41）と書いているが、おそらく、それほどの距離ではなく、イエスの祈りも聞こえる、平伏して祈るイエスの苦しみも見てとることができる程度の距離だったろう。寝ていたのに、だれが、これらの言葉を聞き取ったのかという疑問は、一般的に繰り返されてきたようだが、ある時間経過のなかで、考えれば、祈りを聞き取ったことと、眠ってしまったことは両立すると理解することも自然である。「この時を過ぎ去らせてください」と「この杯をわたしから取りのけてください」は、同じような内容だと考えて良いのだろう。ヤコブとヨハネが「栄光をお受けになるとき、ひとりをあなたの右に、ひとりを左にすわるようにしてください」。（10:37）と願った時にも、「あなたがたは、わたしが飲む杯を飲み、わたしが受けるバプテスマを受けるであろう。」（10:39）と言っている。この杯なのだろう。そして、晩餐のときに「多くの人のために流すわたしの契約の血」（13:24）と、ともに一つの杯から飲んだときのものともつながっているのだろう。この時、この杯は、そして、イエスを「恐れおののき、また悩みはじめ」させ、「悲しみのあまり死ぬほど」であるとイエスが語る苦しみはどのようなものなのだろうか。

ひとの痛み、苦しみ、そして、喜びや、本当にたいせつなものは、なかなか他人にはわからない、そして、自分でも、はっきりしないことがあるのかもしれないと考えているので、上に書いたように、イエス理解は、不可能だとは思っているが、とても、大切なことだとも考えているので、通常言われていることも復習しながら、考えてみたいと思う。視点としては、弟子たちはどのようなものを伝えようとしているのか、わたしは、どのようなものとして受け取るのか、そして、背後にある、イエスの苦しみはどのようなものであったのかと言うことである。

ChatGPT に、一般的に考えられている見解について聞くと、説明を加えて、以下の項目が挙げられている。

マルコ14:33-34の「恐れおののき、死ぬほどの悲しみ」には、複数の要素が絡んでいると考えられます。

1.  十字架の肉体的苦しみ（伝統的解釈）

2.  全人類の罪を背負う霊的苦しみ（神の裁きを受ける）

3.  サタンの誘惑と霊的戦い

4.  弟子たちの裏切りと孤独

5.  人類の救いへの愛と悲しみ

6.  神の御心への従順の葛藤

「肉体的苦しみ」については、個人的には違うように思う。単に、このあと、弟子たちを含む、さまざまな殉教者たちが、イエスの十字架に匹敵するまたはそれ以上の苦痛の中でも、立派に信仰を証したとの比較ではなく、「死ぬのほど悲しみ」とそれを表現することは、考えられないからである。

「全人類の罪を背負う霊的苦しみ」が表現されていると、学生時代は考えていた。イエスは神の子で、父なる神様と霊も心も一致するような存在であったものが、罪を負い、汚れたものとなり、神から呪われた存在となることは、罪人なる人間には、理解できない苦しみである。これは「そして三時に、イエスは大声で、『エロイ、エロイ、ラマ、サバクタニ』と叫ばれた。それは『わが神、わが神、どうしてわたしをお見捨てになったのですか』という意味である。」（15:34）から受ける印象には近いかもしれない。しかし、それは、マルコが描いている、「わたしに従ってきなさい」（2:14, 15, 8:34, 10:21, 参照 10:52, 15:41）と、全知・全能な神とはことなる、真の人間として生きる、イエスの苦しみとは、必ずしも一致していないように現在は、考えている。

「サタンの誘惑と霊的戦い」ルカ4:13に「悪魔はあらゆる試みをしつくして、一時イエスを離れた。」とあるのを受けて、ここでもサタンの誘惑のもとでの、霊的な戦いがあったとする考え方である。イエスの葛藤が描かれていることは確かで、最終的に、このような「文学的表現」をとることも可能かもしれないが、現実的な痛みや苦しみを、抽象的、現実社会の中で理解しづらいもの、または、物語化してしまうことに対する抵抗を感じる。

「弟子たちの裏切りと孤独」今回、マルコを十二弟子の失敗談として読んでいると「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」（14:18）と言われた時にも「まさか、わたしではないでしょう」としか言えず、「あなたがたは皆、わたしにつまずくであろう。」（14:27）と言われても、「たとい、みんなの者がつまずいても、わたしはつまずきません」。（14:29）や「たといあなたと一緒に死なねばならなくなっても、あなたを知らないなどとは、決して申しません」。とペテロは言い切り、「みんなの者もまた、同じようなことを言った」（14:31）にも関わらず、結局、イエスを捨てて逃げ去り（14:50）、大祭司の庭にまで入って行ったペテロも結局、イエスを知らないと否むことになり、ここでも、眠ってしまうでしたち、あとになってから、イエスの「誘惑に陥らないように、目をさまして祈っていなさい。」（14:38）も、以前に、「目をさましていなさい」も思い出したかもしれないが、最後の晩餐以降、失敗の記憶しかない弟子たちにとっては、この「弟子たちの裏切りと孤独」を思うことは自然だったかもしれない。しかし、本当に、弟子たちはそれを伝えようとしたのか、イエスにとっての苦しみがここに由来しているのかは、疑問である。

弟子たちが離れて行ったことは、ヨハネ6章の後半に詳しく書かれており、ヤコブとヨハネが「栄光をお受けになるとき、ひとりをあなたの右に、ひとりを左にすわるようにしてください」（10:37）と願った時のやりとりなど、さまざまに、弟子たちのダメさ加減が緩和されることなく、直接的に伝えられている（マタイ、そして特にルカでは緩和された表現が用いられている）のが、マルコだとすると、ここで伝えられていることは、それを超えるもののように見える。同時に、孤独の中で、イエスが葛藤しなければならなかったこと、そして、弟子たちに互いに支え合って欲しいと願っていたことは、ヨハネ17章の、弟子たちのために祈るイエスなどからも、みて取れることであろう。自分がいなくなったあとのことについて、伝えようとしていたことは十分にあると思う。

「人類の救いへの愛と悲しみ」は、イエスが人間の罪の深さと、神の愛のあまりの大きな乖離に苦しまれたことだろうか。イエスにとっての神様は、いろいろな形で伝えられてはいるが、十分受け取れていないと思う。しかし、十二弟子、ほかの弟子たち、群衆とよばれる、一般の人たち、律法学者、パリサイ人、祭司長など、民の指導者の無理解を考えると、あまりに、むずかしいことを前にしつつ、自分が死んでいくことに関して、葛藤がなかったと言うほうが不自然だろう。しかし、これこそが、現代につづく、最大の課題であり、簡単にことばで表現できることでもない。個人的には、この問題にどう対応するかは、イエスも、そして、もしかすると、神様もまだ完全な答えをお持ちではないのではないかと思う。しかし、ここで、自分の十字架上での死、それは、「多くの人のために流すわたしの契約の血」（14:24）を流すことであったとしても「多くの人のあがないとして、自分の命を与えるため」（10:45）であっても、おそらく、完全解決だとは、イエスは考えていたなかったのではないだろうかと思う。

「神の御心への従順の葛藤」イエスの祈り「アバ、父よ、あなたには、できないことはありません。どうか、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころのままになさってください」（36）を考えると、これが一番しっくりくるように思われる。すなわち、一つ前の「人類の救いへの愛と悲しみ」を思いつつ、神の御心は、ここで十字架へと向かう道にあるように思う。まだ、すべきことがあるのではないか、弟子たちに教えるべきことがあるのではないかと考える中、神の明確な計画を十分理解できずに、ゆだねていくその葛藤である。イエスであっても、神のみこころを十分は理解できていないという謙虚さゆえの、思いではないだろうか。そして、御心を探究しつつも、もしかすると、御心を自分が完全には受け取っていないのかもしれないという思いも背後にはあったのかもしれない。一方で、神の愛は、一人一人を愛される神は、理解を超えている。他方、あまりに、人間的に、イエスを理解し過ぎであろうか。

同様の対話は、「人にはできないが、神にはできる。神はなんでもできるからである」。ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。（10:25-28）にも現れている。ここでは、ペテロは、このように答えることによって、自分のなすべきことはしていると言っているようである。しかし、御心を知ることは、そこにとどまることではないのだろう。

最後に、他の福音書の記述について記す。マタイは、マルコに似ているが、説明が加えられている。たとえば、「恐れおののき、また悩みはじめて」は、マタイでは「悲しみを催しまた悩みはじめられた」。と書かれている。また、マルコではペテロにだけ語られている部分が、マタイでは、「あなたがたは」とされ、「また離れて行って同じ言葉で祈られた。」（39）とあるところは、マタイでは「また二度目に行って、祈って言われた、『わが父よ、この杯を飲むほかに道がないのでしたら、どうか、みこころが行われますように』。」（26:42）とより詳しく説明している。ルカは短いが、マルコ、マタイにはない、特別な表現が加えられている。弟子たちに最初から、「誘惑に陥らないように祈りなさい」と伝え、どのぐらい離れたかについては「ご自分は、石を投げてとどくほど離れたところへ退き、ひざまずいて、祈って言われた」としている。祈りの場面でも「そのとき、御使が天からあらわれてイエスを力づけた。イエスは苦しみもだえて、ますます切に祈られた。そして、その汗が血のしたたりのように地に落ちた。」（43,44）が追加されている。最後も「祈を終えて立ちあがり、弟子たちのところへ行かれると、彼らが悲しみのはて寝入っているのをごらんになって 言われた、『なぜ眠っているのか。誘惑に陥らないように、起きて祈っていなさい』。」（22:45,46）と閉じている。ヨハネは、ゲッセマネでの祈りは書かれていないが、17章全体が、イエスの祈りとして書かれているように見える。ヨハネは別途学ぶ必要があるだろう。

### **裏切られ、逮捕される**

**聖書箇所：**[マルコによる福音書14章43-50 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50.pdf)/[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)（2頁）/ [マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52s.pdf)（1頁）

イエスが祭司長、律法学者、長老たちから送られた群衆に捕縛される場面である。そしてすぐ、イエスがまだ話しておられるうちに（43a）とあるので、ゲッセマネでの祈りからの続きで、場所は、エルサレムから近く、ルカによると「いつものように」（ルカ22:39）「いつもの場所」（ルカ22:40）と繰り返されているので、ユダも含めてよく知っている場所だったのだろう。ここで、ユダは「わたしの接吻する者が、その人だ。その人をつかまえて、まちがいなく引っぱって行け」（44b）とあらかじめ「合図しておいた」ように、イエスに近寄り「先生」と言って（繰り返し）接吻した。そして、人々はイエスに手をかけて捕まえたとある。このあとに、「イエスのそばに立っていた者のひとりが、剣を抜いて大祭司の僕に切りかかり、その片耳を切り落した。」（47）とあり、それ以上なにも書かずに、イエスの言葉「あなたがたは強盗にむかうように、剣や棒を持ってわたしを捕えにきたのか。わたしは毎日あなたがたと一緒に宮にいて教えていたのに、わたしをつかまえはしなかった。しかし聖書の言葉は成就されねばならない」（48,49）が書かれ、最後に「弟子たちは皆イエスを見捨てて逃げ去った。」（50）ことが書かれている。

まず、接吻による裏切りは、どのような意味があるのだろうか。45節の「彼は来るとすぐ、イエスに近寄り、『先生』と言って接吻した。」 の接吻は καταφιλέω が用いられており、44節の、友愛または友愛の表現としての接吻を表す φιλέω と比較すると、「κατα- (kata-)」という接頭辞は「徹底的に」「繰り返し」「心から」というニュアンスを加えるため、この語は「何度も熱心に接吻した」「愛情を込めて接吻した」という意味合いになる。単なる、挨拶の接吻とは違っている。この言葉は、他に、ルカ7:38、45、ルカ15:20、および、使徒20:37 のみで使われており、やはり、特別な言葉である。少し前まで会っていたことを考えると、全くの、偽善の表現なのだろうか。それとも、別れの挨拶、本当は愛していることの表現、何かを期待する動作なのだろうか。ユダが、なぜ裏切ったかとともに、興味深い問いである。

次には「大祭司の僕に切りかかり、その片耳を切り落した」ことである。ヨハネを見ると、これは、シモン・ペテロで、切られたのは、マルコスと名前が記されている。おそらく、そうなのだろう。マタイ、ルカとも、イエスがそれを止めること、さらに、ルカには、その耳を癒やされたことが書かれている。おそらく、批判される可能性のある内容について、批判されないようにしている可能性も排除できない。マルコの記述では、なにも書かれていないことが、不思議に感じるので、その説明が、他の福音書に書かれているように見える。

次には、イエスの言葉である。内容的には三つのことが言われている。自分は、強盗ではないこと。宮でも一緒にいたのに、捕まえなかった。そして、聖書は成就されなければならないである。

まずは、わたしが何が何者かは、理解してほしいと言うことだろうか。二つ目は、基本的には、イエスの話に聞き入っていた群衆が怖かったのだろう。そして、聖書の成就は、どの箇所なのかは、明確ではない。しかし、イエスは、イザヤ53などから、傷を負うことを、覚悟していたのだろうが、それが、この人たちと共有されていたかは不明である。

最後は、弟子たちが逃げていった箇所である。なぜ、逃げていったのか。よくわからない。ヨハネからは、イエスが、さらせたことが書かれている。弟子たちの弱さだろうか。なにをしたら良いのかわからなかったのではないだろうか。

以下、福音書の差異について記す。マタイは、マルコに近いが、大祭司の僕に切りかかった場面でのイエスの言葉を記している。「52b あなたの剣をもとの所におさめなさい。剣をとる者はみな、剣で滅びる。53 それとも、わたしが父に願って、天の使たちを十二軍団以上も、今つかわしていただくことができないと、あなたは思うのか。」（マタイ26:52b,53）ルカには、ユダが接吻をしようとして近づいてきた時、「ユダ、あなたは接吻をもって人の子を裏切るのか」（22:48）とあり、さらに、耳を切り落とした時「51 イエスはこれに対して言われた、「それだけでやめなさい」。そして、その僕の耳に手を触れて、おいやしになった。」（22:51）と癒した記事が書かれている。また最後に、「だが、今はあなたがたの時、また、やみの支配の時である」（22:53b）が付け加わっている。ヨハネは、イエスの積極的な姿勢が描かれており、「4 しかしイエスは、自分の身に起ろうとすることをことごとく承知しておられ、進み出て彼らに言われた、「だれを捜しているのか」。5 彼らは「ナザレのイエスを」と答えた。イエスは彼らに言われた、「わたしが、それである」。イエスを裏切ったユダも、彼らと一緒に立っていた。」（ヨハネ18:4,5）とあり、ユダの近づき方も変化している。このあとにも、6 イエスが彼らに「わたしが、それである」と言われたとき、彼らはうしろに引きさがって地に倒れた。7 そこでまた彼らに、「だれを捜しているのか」とお尋ねになると、彼らは「ナザレのイエスを」と言った。8 イエスは答えられた、「わたしがそれであると、言ったではないか。わたしを捜しているのなら、この人たちを去らせてもらいたい」。9 それは、「あなたが与えて下さった人たちの中のひとりも、わたしは失わなかった」とイエスの言われた言葉が、成就するためである。とあり、弟子たちを逃すことがまず書かれ、このあとに、切りつけたのは、ペテロであると証言し、切りつけられたのは、マルコスだとしている。（ヨハネ18:10）

付録として、ユダについて私見を書いておく。マタイと、ルカ文書である使徒行伝に、ユダの自殺について書かれている。（マタイ26:14-16, 25, 47-56, 27:3-10、使徒1:18,19 ）自殺については、マルコと、ヨハネには書かれていない。また、マタイとルカ文書を比較すると、その記述はかなり異なる。さらに、1コリント15:5 には「ケパに現れ、次に、十二人に現れたことである。」とあり、ユダについては、言及していない。

裏切ったことは、四つの福音書で証言しており、間違いないだろう。しかし、死など、その後については、不明なのではないだろうか。一定の期間のあとには、いくつかの伝承が共有されていただろうが。

ユダの人生は「たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」（14:21）と表現される人生だったのではないだろうか。

どうであろうか。

### **一人の若者、逃げる**

**聖書箇所：**[マルコによる福音書14章51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_51-52.pdf)/[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)

「ときに、ある若者が身に亜麻布をまとって、イエスのあとについて行ったが、人々が彼をつかまえようとしたので、その亜麻布を捨てて、裸で逃げて行った。」とあり、この文章は、他の福音書には含まれていない。

以下は推測でしかないが、ユダが、どの時点で他の弟子たちと別れたかが共観福音書では不明である。また、ゲッセマネに行ったのが、十二弟子とイエスだけなのかも不明である。ヨハネによると、イスカリオテのユダは、晩餐の途中で、イエスに促されてその場を去ったことが書かれており（ヨハネ13:21-30）「ユダは一きれの食物を受けると、すぐに出て行った。時は夜であった。」（ヨハネ13:30）これは、信頼できるとすると、このときに、大祭司のもとに、イエスたちの居場所とともに、引き渡すことを、知らせに行ったと思われる。もともと、晩餐の場所は、秘密にしていたと思われるので、この時点で、ユダを外に出したと言うことは、イエスは、ユダの裏切りに確信があり、予定の行動として、このようにしたと言うことになる。弟子たちが、あとから、理解したことなのかもしれない。

すると、おそらく、「祭司長、律法学者、長老たちから送られた群衆」がユダとともに向かったのは、この晩餐の場だったろう。しかし、そこには、すでに、イエスと弟子たちはいなかった。次に可能性のある、「いつもの場所」（ルカ22:40）である、ゲッセマネの園に向かったのだろう。

亜麻布はエジプトなどで生産され、高価であり、主に裕福な人々が寝巻きや下着、または埋葬用の布として使用されるとされているので（ChatGPT）晩餐をした家の若者の可能性が高く、マルコにしか書かれていないことから、これがマルコであり、晩餐の場所は、「ペテロはこうとわかってから、マルコと呼ばれているヨハネの母マリヤの家に行った。その家には大ぜいの人が集まって祈っていた。」（使徒12:12）だったのかもしれない。

これは、あくまでも推測で、確証はない。

### **最高法院で裁判を受ける**

**聖書箇所：**[マルコによる福音書14章53-65節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_53-65.pdf)

最高法院での裁判について、このあと「夜が明けるとすぐ、祭司長たちは長老、律法学者たち、および全議会と協議をこらした末、イエスを縛って引き出し、ピラトに渡した。」（マルコ15:1）とあるように、夜明け後の公式と思われる、全議会での協議について記しているが、基本的に、この箇所が主たる議論として、記されている。

イエスは、マルコでは、自分が神の子キリストだとは、明確には伝えていなかったように見えるが、ここでは、大祭司の「あなたは、ほむべき者の子、キリストであるか」との問いに、「わたしがそれである。あなたがたは人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」と肯定的に答えている。それを「けがし言」（64）として、「死に当るものと断定した」（65）となっている。イエスは、どのように決意し、意図してこのように答えたのだろうか。

裁判については、四つの福音書には、いろいろと描かれており、すべてを挙げると、前大祭司アンナス（AD6-15）の家（ヨハネ18:12-14,19-24）、それに、マルコでこの箇所で扱われているカヤパ（AD18-36）とサンヘドリン議員の前での裁き（マルコ14:53-65, マタイ26:57-68, ルカ22:54,63-65）がつづき、上にも書いた、サンヘドリンの公式法廷（マルコ15:1, マタイ27:1, ルカ22:66-71）、総督ピラトのもとでの裁判（マルコ15:1-5, マタイ27:2,11-14, ルカ23:1-5, ヨハネ18:28-38）、途中で、ガリラヤ領主ヘロデ・アンティパス（ルカ23:6-12）に送られたことが、ルカだけに書かれており、最後に、総督ピラトでの裁き（マルコ15:6-15, マタイ27:15-26, ルカ23:13-25, ヨハネ18:39-19:16）で、死刑の決断が下される。どれを正式な裁判とするかは、困難だが、マルコは、大祭司（カヤパ）と、議会のメンバーでの審問と、ピラトのもとでの、死刑の決定についてのみ、記している。

最初に、「イエスを死刑にするために、イエスに不利な証拠を見つけようとしたが、得られなかった。多くの者がイエスに対して偽証を立てたが、その証言が合わなかったからである。」（55,56）とあるが、それに続いて、「わたしたちはこの人が『わたしは手で造ったこの神殿を打ちこわし、三日の後に手で造られない別の神殿を建てるのだ』と言うのを聞きました」（58）と証言の一例が載っている。おそらく、神殿に関することは、イエスは、何回か述べているのだろう。マルコでは、「あなたは、これらの大きな建物をながめているのか。その石一つでもくずされないままで、他の石の上に残ることもなくなるであろう」（13:1）だけであるが、ヨハネ2:13-22 には、宮清めの項で、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」（19）が書かれ、「イエスは自分のからだである神殿のことを言われたのである。それで、イエスが死人の中からよみがえったとき、弟子たちはイエスがこう言われたことを思い出して、聖書とイエスのこの言葉とを信じた。」（21,22）とある。しかし、この記述からも、イエスが明確な意図をもって、伝えたかどうかは分かりにくい。少なくとも、その場にいた、弟子以外には、理解されなかったであろう。神殿の崩壊預と合わせると、神殿での礼拝を絶対視していた、祭司長をリーダーとする宗教人には、理解し難いことだったろう。しかし、この発言が、資材に死罪に結びついたわけではない。

このあとに、「イエスは黙っていて、何もお答えにならなかった。」（61）ことを受けての、大祭司の問いとして、「あなたは、ほむべき者の子、キリストであるか」と、その応答、「わたしがそれである。あなたがたは人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」が記されている。最後の部分は、「わたしがあなたのもろもろの敵を／あなたの足台とするまで、わたしの右に座せよ」（詩篇110:1） と

イエスが、（ほむべき者）神の子であることや、キリストであることを、群衆の前などでは、明確にしなかったのは、おそらくこれら共通理解はなく、または、少なくとも、イエスの理解と、人々の理解との相違もあり、ひとによってイメージを独り歩きさせたくなかったのだろう。それが伝えなかった理由なのだろう。「わたしはまた夜の幻のうちに見ていると、／見よ、人の子のような者が、／天の雲に乗ってきて、／日の老いたる者のもとに来ると、／その前に導かれた。」（ダニエル7:13）からの引用とされるが、最後の日についての預言であろうか、本当にそのような引用をされたか、正直よくわからない。

しかし、ここでは、そのような揺れがあっても、明確に肯定している。ここでは、ἐγώ εἰμι (I am) として、マタイのように、それは、あなたの言ったことというような、多少曖昧な部分を含む表現をさけている。理由は、正確には、わからないが、最後に、マルコのテーマ（1:1）でもある、神の子キリストであることを明確にしたのだろう。

これまで、マルコでは、上に挙げた、1:1 以外には、悪霊が神の子といっている、マルコ3:11, 5:17 以外で、神の子との宣言または告白が登場するのは、イエスの死の場面で、イエスにむかって立っていた百卒長は、このようにして息をひきとられたのを見て言った、「まことに、この人は神の子であった」。（15:39）だけである。それだけ、注意していることは確認しておきたい。

このあと、ある者はイエスにつばきをかけ、目隠しをし、こぶしでたたいて、「言いあててみよ」と言いはじめた。また下役どもはイエスを引きとって、手のひらでたたいた。（65）が記されている。イエスの受難預言の三回目、「また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」（10:34）を思い出させられる。

最後に他の福音書との差異について記す。まず、「ペテロ、イエスを知らないという」をどこに入れるかで、福音書ごとに記述の順序に関して差異がある。また、ヨハネでは、まずは、この時の大祭司カヤパのしゅうとのアンナスのところに、まず行ったことが書かれている。「わたしたちはこの人が『わたしは手で造ったこの神殿を打ちこわし、三日の後に手で造られない別の神殿を建てるのだ』と言うのを聞きました」（58）の部分が、マタイでは、「この人は、わたしは神の宮を打ちこわし、三日の後に建てることができる、と言いました」（61）とあり、ルカと、ヨハネでは省略されている。マタイには、大祭司が「何も答えないのか。これらの人々があなたに対して不利な証言を申し立てているが、どうなのか」（62）と言った記述が挿入されている。「あなたは、ほむべき者の子、キリストであるか」（61）と聞く部分は、マタイでは、「あなたは神の子キリストなのかどうか、生ける神に誓ってわれわれに答えよ」（63）ルカは「あなたがキリストなら、そう言ってもらいたい」（67）これに対するイエスの応答「わたしがそれである。あなたがたは人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」（62）は、マタイでは、「あなたの言うとおりである。しかし、わたしは言っておく。あなたがたは、間もなく、人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」（64）ルカは「わたしが言っても、あなたがたは信じないだろう。68 また、わたしがたずねても、答えないだろう。しかし、人の子は今からのち、全能の神の右に座するであろう」。（68,69）だがそのあとに、彼らは言った、「では、あなたは神の子なのか」。イエスは言われた、「あなたがたの言うとおりである」が続いている。これに対してヨハネは、 大祭司はイエスに、弟子たちのことやイエスの教のことを尋ねた。イエスは答えられた、「わたしはこの世に対して公然と語ってきた。すべてのユダヤ人が集まる会堂や宮で、いつも教えていた。何事も隠れて語ったことはない。 なぜ、わたしに尋ねるのか。わたしが彼らに語ったことは、それを聞いた人々に尋ねるがよい。わたしの言ったことは、彼らが知っているのだから」（18:19-21）とだけ書いており、かなり印象が異なる。

### **ペトロ、イエスを知らないと言う**

**聖書箇所：**[マルコによる福音書14章66-72節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_66-72.pdf)/[マルコによる福音書14章26-31, 66-72節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_26-31_66-72.pdf)

「あなたがたは皆、わた しにつまずくであろう。」（マルコ14:26）とイエスが言うのに対し、「たとい、みんなの者がつまずい ても、わたしはつまずきません」。（29）とペテロは答え、さらに、「あなたによく言っておく。きょう、今夜、にわと りが二度鳴く前に、そう言うあなたが、三度わたしを知らないと言うだ ろう」。（30）と言われて、力を込めて「たといあなたと一緒に死なねばなら なくなっても、あなたを知らないなどとは、決して申しません」。（31）と答えたペテロの末路が書かれている箇所である。

イエスが審問されている、大祭司の館の中庭で焚き火にあたっているペテロに、大祭司の女中が彼をみつめ、「あなたもあ のナザレ人イエスと一緒だった」（67）と言う、これを否定して「わたしは知らない。あなたの言 うことがなんの事か、わからない」（68）といい、庭口の方に出ていくと、先の女中が、そこにいた人たちに「この人はあの仲間のひとりです」（69）と言い出す。再び、ペテロは、それを打ち消す。すると、今度は、そばに立っている人々が「確かにあなたは彼らの仲間だ。あなたもガリラヤ人だから」。（70）と言うのに対し、「あなたがたの話しているその人のことは何も知らない」と言い張って、激しく誓いはじめた。（71）とあり、するとすぐ、にわとりが二度目に鳴いた。ペテロは、「にわとりが二 度鳴く前に、三度わたしを知らないと言うであろう」と言われたイエスの言葉を思い出し、そして思いかえして泣きつづけた。（72）と書かれている、非常に印象的な箇所である。

イエスは、晩餐の場面で、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」（18）といい、弟子たちはひとりびとり「まさか、わたしではないでしょう」と言い出した。とあるが、ペテロの発言をみると、ペテロは、このようには、言わなかったのではないかと想像する。確信をもって、自分は、躓かないといい、死ぬことも厭わないといい、イエス捕縛の場面でも、ヨハネによると、剣をふるって、切りつけたのは、ペテロのようである。それだけの勇気をしめし、弟子たちは、みな逃げてしまったようだが、大祭司の中庭までついていったペテロが、なぜ、簡単に、イエスを否認するのだろうか。これが、まず、第一の問いである。そして、イエスの言葉を思い出し、そして思いかえして泣きつづけた。ペテロが、立ち直ったのは、なぜだろうかというのが、二番目の問いである。マルコには、このいずれにも明確には、答えていないように思われる。マルコは、ペテロが語った、または、ペテロ由来のものが多いと考えられていることからすると、ペテロの失敗談、自分は、そんな弱い人間なのだということを、告白して終わっているだけなのかもしれない。

一つ目の問いに対して、ゲッセマネで寝てしまったのが問題と答えるのでは、まったく不十分だろう。では、なぜなのだろうか。ルカは、「シモン、シモン、見よ、サタンはあなたがたを麦のようにふるいにか けることを願って許された。」（22:31）として、サタンの働きとする。子にに続けて、「しかし、わたしはあなたの信仰がなくならないように、あなたのため に祈った。それで、あなたが立ち直ったときには、兄弟たちを力づけて やりなさい」（22:32）ともイエスはつたえ、さらに、中庭で鶏が鳴くと「主は振りむいてペテロを見つめられた。」（22:61）とある。これが、二つ目の問いの答えなのかもしれない。

マタイでは、マルコとほとんど同じ構成で描いているので、一つ目の問いに対しても、二つ目の問いに対しても、明確な答えは語られていない。イエスの最後の晩餐の直前に置かれているメッセージが、マタイ25章の三つの譬え話であることを考えると、あるかたが語っておられたように、ペテロや、弟子たちが、この三つ目の譬えで語られている「これらの最も小さいもの」は、自分のこと、自分たちのことと気づかされたことを証しているのかもしれない。すると、最初の例えで語られる愚かな乙女や、一タラントを地に埋めて、主人に怒られる僕は、これらの最も小さいもの、ペテロ、または、弟子たちと認識させられたのかもしれない。ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。（マルコ10:28、マタイ19:27、ルカ18:28）などと言っていたことも、恥ずかしくなっただろう。これらは、最初の問いにも、二番目の問いにも答えることにはなっていない。おそらく、このあとを読まないとわからないと言うことだろう。「これは、多くの人のために流すわたしの契約の血である。」（14:24）には、ヒントがあるかもしれない。十字架上での死である。

ヨハネはどうだろうか。一つ目の問いに対しても、二つ目の問いに対しても答えは書かれていない。しかし、復活証言は、ヨハネには、たくさん含まれ、ペテロは新たな証明を与えられているので（ヨハネ21章）、二つ目の問いの答えは、復活の主との出会いとしているのかもしれない。

しかし、マルコにもどってここだけでわかることを考えてみよう。三回否むことについて丁寧に書かれている。最初は、女中、そして、次には、女中がそこにいた人たちに語るシーン、そして、最後は、そこにいた人たちが、ガリラヤ人であるという、ひとつの根拠をもって、集団知としている場面で、なんと、「あなたがたの話しているその人のことは何も知らない」と言い張って、激しく誓いはじめた。（71）とある。これは、ἀναθεματίζω (1. to devote to destruction, 2. to declare one's self liable to the severest divine penalties) と強い言葉が使われており、つまり、もし、これが嘘なら、自分は神に呪われても良いと言う意味である。そこまで、言わせたのはなぜなのだろうか。世の終わりなら、気をつけて目を覚ましている、しかし、イエスが、恐れおののき、また悩みはじめて「わたしは悲しみのあまり死ぬほどである。ここに待っていて、目をさましていなさい」。（33,34）と言われたときには、目を覚ましていることができず、女中から言われたり、女中に、そこにいた人たちに、言われたり、そこにいた人たちに言われたようなときには、適切に対応できないと言うことなのかもしれない。裁判で、お前は、イエスの弟子かと言われたら、証言できたのかもしれない。寒いなかで、火にあたっていたときには、準備ができていなかったのかもしれない。日常的にイエスを主だとは告白していないと言うことなのだろう。考えさせられる。

福音書の差異について、いかに記録する。マルコとマタイは似ているが、マタイでは、強化されている点がいくつかある。マルコでは、二回目も同じ女中（先の女中）とあるが、マタイでは、「ほかの女中」としている。これは、二人または三人の証言がたいせつであることと関係しているのかもしれない。一方、マルコでは「にわとりが二度目に鳴いた」と書かれているが、マタイでは「するとすぐ鶏が鳴いた。」としている。最後は、マルコでは「イエスの言葉を思い出し、そして思いかえして泣きつづけた。」となっているが、その最後の部分は、「外に出て激しく泣いた。」としている。ルカは、多少、マタイに近いように思われる。ただし、マルコでが単に「そう言って入口の方に出て行くと」とあるところが「約一時間たってから」が挿入され、さらに、「主は振りむいてペテロを見つめられた。そのときペテロは、『きょう、鶏が鳴く前に、三度わたしを知らないと言うであろう』と言われた主のお言葉を思い出した。」が挿入されている。ヨハネは情報が多い。まず、なぜ、ペテロが中庭に入れたかについての説明があり、さらに、女中は、門番であったことも書かれている。火についても、炭火とあり、そこにいる人の説明もかかれている。また、二回目と三回目の間には、大祭司アンナスの尋問が挿入されている。

### **ピラトから尋問される**

**聖書箇所：**[マルコによる福音書15章1-5節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_1-5.pdf)

大祭司邸での、審議のあと、ペテロの否認の記事が挿入されたあと、「夜が明けると（すぐ）」祭司長たちは長老、律法学者たち、および全議会と協議をこらした末、イエスを縛って引き出し、ピラトに渡したと始まる。深夜の審議がいつまで続いたかは不明で、また、この朝の協議内容もまったく不明だが、「あなたは、ほむべき者の子、キリストであるか」に肯定的にイエスが応じ、この汚しごとは、死に値するとして、律法のもとで、自らの責任のもと、石打ちの刑にすることは、回避した、または、ヨハネが「わたしたちには、人を死刑にする権限がありません」。（ヨハネ18:32）と書いているように、禁じられていたために、さけ、総督ピラトのもとに送っている。ピラトは、「あなたがユダヤ人の王であるか」と問い、イエスが肯定する。このあと、祭司長たちは、イエスのことをいろいろと訴えた。とあるが、イエスは沈黙を守る。ところまでが書かれている。

ピラトは、ローマ帝国のユダヤ属州の総督（26-36）で、通常は、カイサリア（Caesarea Maritima）に駐在していたようで、1961年に発見された碑文も残っているとのことである。過越祭の時などは、エルサレム神殿の北西角に位置している、アントニア要塞に滞在していたとのことである。ピラトは「ちょうどその時、ある人々がきて、ピラトがガリラヤ人たちの血を流し、それを彼らの犠牲の血に混ぜたことを、イエスに知らせた。」（ルカ13:1）との記録があり、また、ヨセフスなどに、「エルサレムにローマ皇帝ティベリウスの肖像入り軍旗を持ち込んだことでユダヤ人の反発を招いたが、最終的に撤回を余儀なくされた。」「エルサレム神殿の資金を用いて水道を建設し、市民の抗議を武力で鎮圧した。」の記録もあり、残虐と言われ、不人気のようだが、情報が少ないようにも思われる。福音書から受ける印象とは、少し異なる。福音書が書かれた時代背景から、ローマに責任を負わす書き方はできなかったのではないだろうか。

ピラトはすぐ「あなたがユダヤ人の王であるか」と問うている。これは、訴状の内容だと取るのが自然あだろうが、ユダヤ人の群衆を扇動していると表現しても、このようになるかもしれない。しかし、この「ユダヤ人の王」が、マルコ15:26 にあるイエスの罪状書きに書かれていたことからも、重要である。

これに対して、イエスは、「そのとおりである」とお答えになった。イエスはどのように考えておられたのだろうか。マルコでは、表現が明確ではないが、エルサレムの入城記事で「ホサナ、／主の御名によってきたる者に、祝福あれ。今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」（11:9,10）は、マタイでも、ルカでも、そしてヨハネでも、明確に「王」ということばが用いられているように、そのような群衆の声を許容しているとはいえる。

正直、イエスの心うちは、よくわからない。ヨハネには、イエスの胸の内を再現するような記述がある。「わたしの国はこの世のものではない。もしわたしの国がこの世のものであれば、わたしに従っている者たちは、わたしをユダヤ人に渡さないように戦ったであろう。しかし事実、わたしの国はこの世のものではない」。（ヨハネ18:36）さらに、「あなたの言うとおり、わたしは王である。わたしは真理についてあかしをするために生れ、また、そのためにこの世にきたのである。だれでも真理につく者は、わたしの声に耳を傾ける」（ヨハネ18:37）とこたえ、ピラトの「真理とは何か」（ヨハネ18:38）で終わっている。この世のものではなく、かつ、父なる神様についてあかしをするのがイエスが証してきたということなのだろう。正当であるように見えるが、どうだろうか。

最後に、イエスの沈黙について考えてみたい。イエスは、ピラトや、眼前にいる、ひとたちをどうみていたのだろうか。神様の御心、自分の使命を考えていたのだろうか。正直よくわからない。

他の福音書との差異について記す。マタイは、マルコに非常に近い。1節に「イエスを殺そうとして」と目的を追加。マルコでは、4節で、ピラトに「何も答えないのか。見よ、あなたに対してあんなにまで次々に訴えているではないか」と言わせているが、3節の「そこで祭司長たちは、イエスのことをいろいろと訴えた。」は、マタイでは、削除し、「あんなにまで次々に、あなたに不利な証言を立てているのが、あなたには聞えないのか」としている。細かなことだが、マルコではピラトとだけ書かれているが、マタイでは、総督ピラトとし、そのあとの総督としている。マルコは、ピラトが総督であることは、だれでも知っていると想定しているのだろう。それだけ証言としては古いと思われる。ルカでは、訴えた内容として、「わたしたちは、この人が国民を惑わし、貢をカイザルに納めることを禁じ、また自分こそ王なるキリストだと、となえているところを目撃しました」（2）としている。また、ピラトに、「わたしはこの人になんの罪もみとめない」と言わせ、これに対して、「彼は、ガリラヤからはじめてこの所まで、ユダヤ全国にわたって教え、民衆を煽動しているのです」とピラトの厳しい判決を誘導しているように見える。ヨハネには、もっと情報が多い。まず、ピラトのところを、官邸とよび、「けがれを受けないで過越の食事ができるように、官邸にはいらなかった。」としている。過越の食事は、この晩に食べると想定している。さらに、死刑を要求していることを、「わたしたちには、人を死刑にする権限がありません」と主張し、律法で裁く内容とは区別しているように見える。さらに、「あなたは、ユダヤ人の王であるか」の問いについても、最後には、「それでは、あなたは王なのだな」。イエスは答えられた、「あなたの言うとおり、わたしは王である。」としているが、その前に、「わたしの国はこの世のものではない。もしわたしの国がこの世のものであれば、わたしに従っている者たちは、わたしをユダヤ人に渡さないように戦ったであろう。しかし事実、わたしの国はこの世のものではない」。を付け加え、さらに、ユダヤ人の王であることを肯定した後にも、わたしは真理についてあかしをするために生れ、また、そのためにこの世にきたのである。だれでも真理につく者は、わたしの声に耳を傾ける」と付け加え、ピラトに「真理とは何か」と問わせ、さらに「わたしには、この人になんの罪も見いだせない。」と言わせている。いずれにしても、かなり詳細になっている。

### **死刑の判決を受ける**

**聖書箇所：**[マルコによる福音書15章6-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_6-15.pdf)

総督ピラトのもとでイエスの十字架刑が決定される。マルコでは、前段（15:1-5）において、ピラトの「あなたがユダヤ人の王であるか」（2）との問いに対して、イエスは「そのとおりである」（2）と答え、そのあとは、なにも答えていない。今回の箇所では、祭りのたびに恩赦があったことが書かれ（6）暴動を起こし人殺しをして繋がれていた暴徒バラバがいたことが書かれ（7）群衆が、恩赦を要求する（8）ところから始めている。ピラトはこれに対して「おまえたちはユダヤ人の王をゆるしてもらいたいのか」（9）と応じ、さらに、「それは、祭司長たちがイエスを引きわたしたのは、ねたみのためであることが、ピラトにわかっていたからである。」（10）と書いている。これに対して、祭司長たちは、バラバの方をゆるしてもらうように、「群衆を扇動した」(11)とある。つまり、イエスの恩赦に進む可能性があったことを示唆しているように見える。しかし、「それでは、おまえたちがユダヤ人の王と呼んでいるあの人は、どうしたらよいか」（12）と問うと、彼ら（おそらく群衆）は「十字架につけよ」（13）と叫び、ピラトが「あの人は、いったい、どんな悪事をしたのか」（14）と言っても、どうにもならず、「それで、ピラトは群衆を満足させようと思って、バラバをゆるしてやり、イエスをむち打ったのち、十字架につけるために引きわたした。」（15）となっている。

以下、

-   ピラトはなぜイエスを十字架につける決断をしたのだろうか。

-   イエスが十字架刑に至ったのは、誰の何が責任なのだろうか。

-   それぞれの福音書がたいせつなこととして伝えているのはどのようなことなのだろうか。

についても考えてみたいと思う。

福音書によって強調点は異なるが、ヨセフス（ユダヤ古代史）によると、ピラトは就任時に、皇帝の肖像が書かれた旗をエルサレムに持ち込もうとして、強い反対を受け、カイザリアにも強い嘆願があったり、神殿に納められた金を使って、水道工事をしようとして、これも、暴動に発展し、多くを殺したとの記録もある。最終的には、サマリヤからの上訴によって、職を追われたようである。ヨセフスの記述をそのまま信じて良いかどうかはわからないが、直轄地シリアの提督ではなく、ユダヤ・サマリヤの総督であるピラトは、上訴をある程度避けるために、たみの声を聞く必要もあり、強く訴える、大祭司たちに煽動された、群衆の前では、自分の思いで決断することはできなかったのだろう。死罪にあたるような罪はないということを、ピラトに言わせているのは、ローマ帝国の中で活動するキリスト教徒である著者の護教的側面が入っていることを排除することはできないだろうが、ユダヤ人社会において、祭司長や、長老たちのリーダーシップが失われることを避けようとする動きが、背景にあることは、おそらく、否定できないであろう。

しかし、ここで、イエスが十字架刑に至ったのは、誰の何が責任かに、集中してしまうのは、おそらく、不十分なのだろう。背後に、神がおられること、そして、人間の様々な罪があることも見とらなければいけないだろう。マルコでは「煽動」ということばがあるように、もしかすると、イエスを赦してほしいと願っている民も、群衆の中にはいたのかもしれないが、その声がかき消される、または、大声とならなかったところには、弱さがあったのかもしれないし、罪がないものが、十字架刑で死刑になることへの、抗議は、強くはならなかったのだろう。祭司長や、長老たち、さらには、群衆も、神が愛されるイエスの死、神の子の死かもしれないということろには、行き着けなかった悲しい現実がある。イエスがなぜ、十字架刑で死ななければならなかったかは、この後も含めて、考えるべき問いなのだろう。

最後に、他の福音書の記述について、考えてみる。マタイと、ルカは、基本史料は、マルコ、または、マルコとおなじのようであるが、多少異なる点がある。

マタイでは、恩赦についての背景説明の後「おまえたちは、だれをゆるしてほしいのか。バラバか、それとも、キリストといわれるイエスか」（マタイ27:17b）と、バラバかイエスのどちらかが恩赦を受けるという単純化が行われている。特徴的なこととしては、ピラトの妻のことば「あの義人には関係しないでください。わたしはきょう夢で、あの人のためにさんざん苦しみましたから」（マタイ27:19）が挿入されている。また、「ピラトは手のつけようがなく、かえって暴動になりそうなのを見て、水を取り、群衆の前で手を洗って言った、『この人の血について、わたしには責任がない。おまえたちが自分で始末をするがよい」。すると、民衆全体が答えて言った、「その血の責任は、われわれとわれわれの子孫の上にかかってもよい』。」（マタイ27:24,25）と、責任の所在に関するやりとりが記録されている。

ルカでは、すこし枠組みに変化があり「『おまえたちは、この人を民衆を惑わすものとしてわたしのところに連れてきたので、おまえたちの面前でしらべたが、訴え出ているような罪は、この人に少しもみとめられなかった。ヘロデもまたみとめなかった。現に彼はイエスをわれわれに送りかえしてきた。この人はなんら死に当るようなことはしていないのである。だから、彼をむち打ってから、ゆるしてやることにしよう』。」（ルカ23:14-16）と、祭司長たちと役人と民衆を呼び出して告げるところから始めている。さらに、「ピラトはイエスをゆるしてやりたいと思って、もう一度かれらに呼びかけた。」（ルカ23:20）「ピラトは三度目に彼らにむかって言った、『では、この人は、いったい、どんな悪事をしたのか。彼には死に当る罪は全くみとめられなかった。だから、むち打ってから彼をゆるしてやることにしよう』。」（ルカ23:22）とまで書いている。しかしピラトに詰め寄る（ルカ23:23b）強行な彼らに押し切られて、彼らの願い通りにしたと書かれている。

ヨハネでは、まず、恩赦の枠組みが説明され、次に、「1 そこでピラトは、イエスを捕え、むちで打たせた。2 兵卒たちは、いばらで冠をあんで、イエスの頭にかぶらせ、紫の上着を着せ、3 それから、その前に進み出て、「ユダヤ人の王、ばんざい」と言った。そして平手でイエスを打ちつづけた。」（ヨハネ19:1-3）と始めている。共観福音書では、鞭打ったり侮辱を与えるのは、判決後である。このあとに「見よ、わたしはこの人をあなたがたの前に引き出すが、それはこの人になんの罪も見いだせないことを、あなたがたに知ってもらうためである」。（ヨハネ19:4b）と言った後「見よ、この人だ」（ヨハネ19:5b）というあたりは印象的である。さらに「あなたがたが、この人を引き取って十字架につけるがよい。わたしは、彼にはなんの罪も見いだせない」（ヨハネ19:6）とピラトが言った後に、ユダヤ人たちが、「わたしたちには律法があります。その律法によれば、彼は自分を神の子としたのだから、死罪に当る者です」といい、これに対して、ピラトはさらに「あなたは、もともと、どこからきたのか」（ヨハネ19:9）と問い、「何も答えないのか。わたしには、あなたを許す権威があり、また十字架につける権威があることを、知らないのか」に対して、イエスが「あなたは、上から賜わるのでなければ、わたしに対してなんの権威もない。だから、わたしをあなたに引き渡した者の罪は、もっと大きい」（11b）といい、さらに、赦そうとするピラトにたいして、「もしこの人を許したなら、あなたはカイザルの味方ではありません。自分を王とするものはすべて、カイザルにそむく者です」。（ヨハネ19:12b）「わたしたちには、カイザル以外に王はありません」（15b）の声を聞き、ユダヤ人に引き渡すことを決めたことが記録されている。ユダヤ人たちも貶められ、なんとも残念な結末である。

マルコでは、明確とは言えないが、基本的には、暴動を起こし殺人をしたバラバが赦され、ピラトはなんら罪を認めることができなかったイエスが十字架刑にされることが書かれている。特に、ルカや、ヨハネでは、罪がないことが強調されているが、マタイと、ヨハネでは、責任についても述べられている。形式的には、ユダヤ人の責任としているが、枠組みは、死刑の権限を持っている、ピラトが総督である、ローマ帝国政府であることも揺るがない事実であるが、ヨハネには、そのような権威も、神のもとにあることが述べられ、人々が、神の権威か、人の権威のどちらに従うかが問われている関係になっている。

### **兵士から侮辱される**

**聖書箇所：**[マルコによる福音書15章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_16-20.pdf)

### **十字架につけられる**

**聖書箇所：**[マルコによる福音書15章21-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_21-32.pdf)

### **イエスの死**

**聖書箇所：**[マルコによる福音書15章33-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_33-41.pdf)

### **墓に葬られる**

**聖書箇所：**[マルコによる福音書15章42-47節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_42-47.pdf)

### **復活する**

**聖書箇所：**[マルコによる福音書16章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_1-8.pdf)

### **（結び一）マグダラのマリアに現れる**

**聖書箇所：**

### **二人の弟子に現れる**

**聖書箇所：**

### **弟子たちを派遣する**

**聖書箇所：**

### **天に上げられる**

**聖書箇所：**
