# 聖書を一緒に読みませんか {#preface .unnumbered}

表題の名称で、案内を送り、我が家で開いている、聖書を読み、疑問をあげて考え、語り合い、分かち合い、聴く会のページです。

過去の会の情報などは、[ホームページ](https://icu-hsuzuki.github.io/science/index-j.html#seishonokai)をご覧ください。

また、通読の会も主催しており、全体として、一緒に聖書を読むことをできればと願っています。

## 共に学ぶ

いろいろな理由から、聖書を読んでみたいと思う方がおられると思います。また、聖書について知りたいので、だれか教えてくださる方はおられませんか。という場合もあるかもしれません。興味のあるかたは、教会に行かれることをお勧めします。しかし、どこの教会に行ったらよいかわからないとか、ちょっと行ってみたけれど、やはりよくわからない。興味はあるが、同時に、疑問もあり、なかなか満足がいく説明が、教会では聞くことができない。他のひとはどう考えているのかにも、興味を持つし、聖書に書いてあることが全部本当だと信じているのかにも興味がある。さまざまかなと思います。

わたしは、皆さんの質問に、答えることはできません。わたしもよくわからないことが山ほどあるからです。というより、わかっていると思っていることも少しはありますが、それは、ほんの少しだとも思っています。他の言い方をすると、大切なこともあまりよくわかっていないということです。

わたしは、毎日、そして、繰り返し繰り返し聖書を読んでいますが、毎回新しい発見があります。皆さんのお家で、ドアを開けてみるごとに新しい発見がある、という人はおられないと思います。ときどき、変化もふくめて、発見があるかもしれませんが、大体は、家のことはわかっています。しかし、外国などに旅をすると、さまざまなあたらいことに出会います。それは、ほとんど知らないからですよね。わたしは、上に書いたように、聖書を読むたびに、新しい発見があるので、謙虚に言っているのではなく、ほんとうに、聖書を理解できていないと感じています。

しかし、聖書は、なかなか大きな書物で、かつ、長い歴史の中で、何人もの人によって書かれています。書いた人たちの住んだ世界は、現代のわたしが住む世界とはとても違っているでしょうから、理解するのが、簡単でないのは、当たり前かもしれません。

ここでは、聖書全体を通して読むことと、イエスのことについて書いてある、福音書を読むことに中心を置いています。基本的には、イエスのことを知りたいからです。なかなか、興味深い方ですよ。

一人で本などを参考にしながら、読めば良いのではないでしょうか。たしかに、それでも、ある程度は、聖書を理解できると思います。ただ、それは、その本を書いた人が理解した聖書を知ることになります。私が上に書いたように、もし、それぞれの人が理解できていることが、ほんの少しだけなら、一人だけの話を聞いても理解できませんよね。そして、何よりも、自分が疑問に思っていることについて知ることは難しいと思います。

聖書の著者が多様で、いろいろな時代にまたがっているのですから、いろいろな人の話を、理解した部分を聞くこと、さらに、疑問を知ることは、素晴らしいことなのではないかと思います。それを通して、聖書を知ると共に、その人をも少し知ることができるかもしれません。

わたしは、聖書を橋渡しとして、聖書を書いた人と対話がしたいですし、同時に、一緒に読むことによって、その人とも対話をしながら、そに人もほんの少しでも、理解できないかなと考えています。一緒に生きているのですから。そして、共に生きるために。

聖書を読む理由はさまざまだと思いますが、わたしが最も大切だと思っているのは、互いに愛し合うようになることです。イエスが語っていることも、さまざまな表現があるかもしれませんが、互いに愛し合うことにつながっているのではないかと、今は、考えているからでもあります。

聖書を一緒に読むことによって、分裂ではなく、他者の読み方を理解しようとすることによって、互いに愛し合うことを学んでいければと願っています。

## 本書の目的

最後に、なぜこのようなものを書こうと思ったかを簡単に書いていこうと思います。聖書研究会などの名前で、何人かが集まって、聖書を一緒に読んでいくことは、ある程度一般的だと思います。ある時代までは、皆が字を読めたわけではありませんから、誰かの話を聞くことしかできなかったかもしれませんし、聖書自体もそれほど、簡単に手に入るものではなかったと思います。そのような中では、教会に行って、牧師など、先生の話を聞くことが主だったと思います。

現代では、聖書も簡単に手に入りますし、最近では、ネット上で自由に読むことも可能です。その意味で、ハードルは低くなったのですが、最初に書いたように、聖書は大きな書物で読むのはあまり簡単ではない。福音書などに限っても、一人で読んで理解できるというのは、あまり、一般的ではないと思います。

この書では、そのような場合のお手伝いをすることと、集まって一緒に聖書を読む場合の資料を提供することを目的として書いています。準備はそれなりに大変です。問いを考えるというのは、とてもよいことですが、適切な問いを考えるのは、簡単ではありません。まずは、文脈を理解しないといけませんし、他の聖書の箇所から、背景などが多少わかる場合には、その情報もあると助けになることがよくあります。できるだけ、一つの意見や、考えかたにならないように、特に、分断を避けるように、注意して、皆さんが、考えていく助けになればと思い、書いています。

ある程度長い期間に、わたしが司会をして共に聖書を読んだ学びが背後にありますが、むろん、これがよいというわけではありません。準備をする時の、ヒント、助けとなれば、幸いです。

問いだけではなく、わたしが調べたノートもあります。少しずつ、追記していくことができればと願っています。

## 管理人について

鈴木寛（Suzuki, Hiroshi）が、現在は、管理人を務めています。聖書の研究が専門ではありませんが、これまでも、グループで聖書を読む機会を持ってきました。少しでも、理解したいということが、基本的な動機です。聖書の読み方、読む目的も人によってさまざまだと思います。書かれていることに、ご意見、ご批判があるかたもおられるかもしれませんね。何かの機会に、お話を伺えれば幸いです。ホームページに、電子メールアドレスも公開しています。メールをいただければ幸いです。

わたしは、大学で数学を教えていましたが、2019年3月に退職。現在は、数学や、データサイエンスの勉強をつづけ、それ以外に、何箇所かで、ボランティアをしています。

聖書を読む会は、在職中、2003年4月から2018年12月まで、学内住宅の我が家で、学期中、毎週木曜日の夜に持っていました。退職後、2020年1月に再開しましたが、コロナウイルス感染症の流行もあり、中断、2023年4月再開に漕ぎ着けました。

大学で開いていたときと同じようにはできないと思いますが、そこでたいせつにしていたことは何なのかを振り返りながら、この会を続けて行くことができればと願っています。

この会以外にも、聖書通読の会も、2011年から電子メールを利用して、続けています。その情報もホームページにありますので、ご興味のある方はご覧ください。

## 電子ブックについて

Quarto Book という形式で書いています。

-   [Quarto](https://quarto.org): An open-source scientific and technical publishing system

-   [HTML](https://icu-hsuzuki.github.io/biblestudy/): Web browser で読むことができます。

-   [PDF](https://icu-hsuzuki.github.io/biblestudy/聖書の学び.pdf)：全く同じように表示されているわけではありませんが、ネットに繋げなくても読むことができたり、印刷したい方のために作成しています。

-   このサイトのソースファイル：GitHub を利用しています。

    -   [レポジトリー](https://github.com/icu-hsuzuki/biblestudy)
