# はじめに {#introduction}

聖書を少しずつ読んでいきます。専門的に、研究するわけではありませんが、皆さんの声に、耳を傾けて、ていねいに読んでいくことができればと願っています。

## 聖書の会と聖書通読の会

わたしは、聖書の会と、聖書通読の会を主催しています。

聖書通読の会は、文字通り、聖書を通読する会で、2011年から始め、一日二章ずつ読んでいます。このペースですと、２年間で旧約聖書を1回と、新約聖書を2回読む計画で、毎週日曜日の朝にその週に読む箇所についての簡単な説明と、その週に読む各章ごとのわたしがつけている聖書通読ノートをメールで配信しています。また、参加者が送ってくださった感想に、わたしの簡単な応答を加えて、日曜日の夜に送っています。最近は登録者70名程度で推移しています。

通読は、まずは、読み通してみましょうということですから、皆さんが興味を持って通読を続けられるような支援を考えて、メールを書いていますが、感想を送ってくださるのは少数の方で、残念ながら、ほとんど、一方通行になってしまっています。

聖書は66巻（旧約39巻・新約27巻）、1189章（旧約929章・新約260章）あり、内容も多様です。時代的にも、伝承も含めれば、おそらく、今から4000年ぐらい前のものも含まれるかもしれません。短く見積もっても 3000年前（厳密に現在の形になったのはもっと後でしょうが）から、1900年前ぐらいの間に書かれたものですので、理解しながら読むのは難しいですが、違った時代を、神様を求めながら、生きた人たちから、話を聞くことができるという豊かな経験を得ることができると思い、わたしは、読んでいます。語り合うところまではいけませんが、考えさせられることは、とても多いと感じています。

聖書の会では、逆に、とても短く箇所を区切って、読んでいます。問いを、準備して、ディスカッション・スタイルで、考えながら読んでいます。問いなどの内容は、この電子ブックに含まれていますので、ご覧になってくだされば幸いです。

新約聖書、特に、福音書を中心に読んでいます。個人的に、イエスについて学びたいからというのが、大きな理由ですが、聖書には四つの福音書が含まれており、違った視点から、イエスについて学ぶことができるという面でも、とても、良い題材だと考えています。

毎回、とても多くの学びがあります。わたしの人生を考えても、この聖書の会での、皆さんとの時が、最も充実した、幸せな時であり、わたしが日々生きていく上で、豊かな糧を与えてくれている者だと思っています。

この書に書かれていることは、備忘録のようなものですが、ほんの少しでも、より多くの方に、その素晴らしさを味わっていただければと考え、書き始めています。

## 著者について

聖書の著者は？と聞くと「神様」と答えるキリスト者の方が多いかもしれませんが、それは、思考停止に導く面もありますから、わたしは、実際に書き記した人間に目を向けることにしています。

聖書の中には、パウロの手紙のように、著者が明確に書かれている場合もありますが、書かれていない場合がほとんどです。また、著者が明確に書かれている場合も、最近の研究では、そうでもないのではないかとされています。パウロの手紙も、ローマ人への手紙、ガラテヤ人への手紙、コリント人への手紙一、二、テサロニケ人への手紙一、ピレモンへの手紙は、パウロが書いただろうが、他は不明とされる場合もあります。それには、いろいろな根拠もありますが、わたしは、その議論は避けて、パウロの手紙についても、パウロ由来の手紙と呼ぶことにしています。

ここで学ぶ、福音書は、マタイによる福音書、マルコによる福音書、ルカによる福音書、ヨハネによる福音書と、四つありますが、「による」の部分は、「由来の」という意味にとって読んでいると言うことです。曖昧ですけれど。

簡単に書くと、由来する部分があることと、厳密な意味で、それぞれの人が書いたそのままではないかもしれないという意味です。由来はあまりにも曖昧で、四つの福音書によって、どのように由来しているか、程度も様々でしょうが、それを明確にしないと、内容を深く読むことができないとは考えていないからでもあります。

しかし、四つの福音書を読んでいくには、やはりある程度「由来」の中身を知ることはたいせつだとは考えています。そこで、すこしだけ、個人的な見方を書いておきます。お断りしておくのは、このような理解のもとで読み、他の読み方は許容しないという意味ではありませんが、程度の差こそあれ、マタイ、マルコ、ルカ、ヨハネと、このような関係性はあるだろうということです。そして、そのような理解は、助けになるだろうとも考えていると言うことです。

### マルコによる福音書

聖書に登場するヨハネ・マルコとよばれ、使徒行伝によると、バルナバのいとこで、パウロとバルナバと一緒に伝道旅行に出るが、途中で帰ってしまったと書かれているマルコです。（使徒12:12, 12:25, 15:37, 15:39, コロサイ4:10, 2テモテ4:11, ピレモン24, 1ペテロ5:13）

伝承によると、ペテロの通訳だったとされ、ローマにも行ったようですが、使徒行伝によると、お母さんはマリアで、エルサレムに家があったようで、イエスの弟子たちの集会にも使われていたようです。おそらくマルコはイエスが活動していた頃は、幼なかったと思われます。

マルコが書いたかどうかには疑問も上がっているようですが、ペトロからの情報が多い、マルコ由来と考えるのは、内容からして妥当であると思います。由来の意味は、実際に書き記したのは、他の人かもしれないことを許容する表現です。いろいろな人が一緒に聖書を読み、語り合うことがたいせつだと考えているからです。

表現は簡潔ですが、その分、豊かな表現とはなっていないように見えます。個人的にたいせつだと考えているのは、上にも書いたように、自分は直接は知らないが、ペトロからの情報、ペトロの視点からの話で覚えていることを書き記したと言うことです。

ここからは、ますます、不確定ですが、パウロの書簡（一般的には福音書より先に書かれたと考えられています）と、共観福音書（マタイ・マルコ・ルカ）はとても異なる印象を受けます。たとえば、イエスの死が贖罪のための死であったことは、まったく強調されていません。最も古い写本では、復活の部分も空の墓の記述で終わっていて、詳細は書かれていません。パウロの書簡で大切にされている、贖罪と復活はほとんどないのです。１箇所の例外は10章45節だけだと思います。パウロは、自分にならうものとなるように勧め、イエスの教えや行動についてはほとんど書きません。それではいけない、または、不十分との考えからも、この福音書が書かれたのではないかと考えています。

キリスト教会の歴史の中でも、人間イエスをたいせつにする人たち、福音書をたいせつにするひとたち、パウロが書いたことを中心とした教義をたいせつにする人たちがいますが、それが、分裂するのではなく、いまも、一つのキリスト教会を形成していることも、みのがしてはいけない大切なことではないかなと思います。

### マタイによる福音書

マタイはイエスの12弟子の一人で収税人として描かれているマタイだとされています。しかし、福音書の流れば、マルコによる福音書を踏襲しているように見えます。マルコは、イエスの直接の弟子ではありませんから、このことは不思議です。

伝承によると、マタイは「語録（ロギア）」と呼ばれる、イエスの説教集をヘブル後で記録していたとされています。基本的には、のちに、それを含める形で、マルコによる福音書の流れに沿って、書いていったと思われますが、人数や、地名などが、マルコやルカと違っている箇所があり、マタイからかどうかは特定できませんが、別の情報もあって、書かれたものと思われます。

正確にはわかりませんが、これも、マタイ由来で、マタイと交流のあった人たちが編集したとして良いのではないかと思います。ただ、マルコに含まれていない部分がすべて、マタイ由来かは不明です。

### ルカによる福音書

ルカは使徒行伝に登場し、パウロ由来の手紙にも何度か現れ、医者ルカとされているひとだと考えられています。文体などからも、ルカによる福音書と使徒行伝は、同じ人が書いたものと思われますが、使徒行伝には「わたしたち」という表現が、一定の箇所に書かれており、そのときは、ルカも同行していたのではないかと考えられています。それをそのままは受け入れない学者もいるようですが、ある部分、ルカが、パウロと一緒に行動したことは、かなり可能性が高いように思います。

さらに、エルサレムなど、パレスチナに行ったことも非常に可能性が高いでしょう。すでに、死んでいた方も多いと思いますが、イエスの弟子や、イエスに仕えた女性たち、さらに、それらの人たちから直接話を聞いたこともあったと思われます。

しかし、ルカによる福音書が書かれたのは、イエスが十字架にかかってから、40年以上経っていると思われるので、ルカが書いたことをすべて事実と考えるのは、適切ではないかもしれません。ルカが受け取ったことは確かでしょうが、証言として受け取ると、それを受け取ったように書くことも必要になります。そのことも、注意して、読んでいくべきでしょう。

わたしが、ルカによる福音書を大切だと思っているのは、ルカがギリシャ人で、美しいギリシャ語で書かれていること、医者で、病気などについての記述が詳細であること、物語や喩えの記述が豊かで、文学的にも高いなどもありますが、パウロに近い人物として、イエスの生涯を書いたと言う点がとても大きいように思います。

パウロの説いた神学と、イエスの地上での活動を同じ視点から描いていることは、とても貴重なことだと思います。

### ヨハネによる福音書

イエスの十二弟子の一人のゼベダイ子ヨハネ由来だとされています。ヨハネは、いくつかの文書から、一世紀の終わり頃まで生きていたことがわかります。明確ではありませんが、ヨハネによる福音書には、ヨハネと思われる人物が何回か登場します。

ヨハネによる福音書は、20章で一旦終了するような書き方がされていますから、21章は、ヨハネの死後に付け加えたのではないかと思われます。20章までも、ヨハネの生存中に書かれたかどうかは不明ですが、ヨハネが語っていたことを書いたことは、確実性が高いのではないかと思われます。

このような理解のもとで読むと、ヨハネは、イエスの活動の最初から一緒にいたと思われます。ペテロよりも早かった可能性もあります。マルコには含まれていないものがたくさん書かれており、その意味でも、貴重です。このことは、マルコの記述を修正するという面もあったのかもしれませんが、マルコに書かれていない大切なことを書く面が大きかったのではないかと思われます。

ヨハネの視点は、マルコ、すなわち、ペテロの視点とは、違うということも大切なことだと思います。同じ場所に、同じ時にいたにもかかわらず、違う視点から書かれている。新しい事実というより、この違った視点ということは、たいせつにしてよいと思います。

最後に、わたしがもっとも大切だと考えているのは、パウロの神学とイエスの語ったことが、違和感なくひとつに書かれていることかなと思います。ある時点では、一方を支持し、他方を支持しないひとたちもいたかもしれませんが、ヨハネによる福音書が書かれ、読まれることで、少しずつ、そのような見方は減っていったのではないかと思います。

### 福音書の著者についてのまとめ

簡単に、わたしの見方を書いてきましたが、それは、わたし個人の見方であることをお断りしておかなければなりませんが、同時に、聖書の会で、数節ずつ、約16年間、マルコによる福音書、ルカによる福音書、使徒行伝、マタイによる福音書、ヨハネによる福音書を学びながら考えたことでもあります。

それは、知識的な面もあると同時に、違った考え方、見方をする人とも、一緒に聖書を読んでいきたいという心からの願いから書いた面もあります。

今回、みなさんと共に、もう一度、福音書を読みながら、一緒に考えていくことができれと願っています。

最後にわたしが最も好きな聖書のことばを書いておきます。

> わたしは、新しいいましめをあなたがたに与える、互に愛し合いなさい。わたしがあなたがたを愛したように、あなたがたも互に愛し合いなさい。 互に愛し合うならば、それによって、あなたがたがわたしの弟子であることを、すべての者が認めるであろう」。（ヨハネによる福音書13章34章・35節）
