# ヨハネ（2015-2018） {#johndq-old .unnumbered}

## ヨハネ 第1章

### ヨハネによる福音書 John 1:1-5

-   21章20 - 24節 から著者についてどんなことがわかりますか。What can you say about the author from 21:20 - 24?

-   20章31節には、この書の目的は何だと書いてありますか。What does it say about the purpose of this book in 20:31?

-   ヨハネによる福音書はどのようにはじまりますか。How does Gospel according to John begin?

-   「言（ことば）」について（5節までに）書かれていることを列挙してみましょう。List what is written about the Word (in verses 1 - 5).

-   「言」とは誰のことでしょうか。Who is the Word?

-   「初め」とはいつのことでしょうか。When is 'the beginning'?

-   「神と共にある」とはどういうことでしょうか。What does 'with God' mean?

-   「ことばは神であった」とはどういうことでしょうか。What does 'the Word was God' mean?

-   「ことばによって成った」とはどういうことでしょうか。What does 'through the Word all things were made' mean?

-   「光」について書かれていることを列挙してみましょう。List what is written about the light.

### ヨハネによる福音書 John 1:6-18

-   6節から9節で、ヨハネはどのような人だと言っていますか。What is said about John in verses 6 - 9?

-   バプテスマのヨハネとはどのような人でしょうか。聖書の他の箇所から見てみましょう。What is written about John the Baptist?

-   10節から14節には言についてどのように書かれていますか。What does it say about the Word in verses 10 - 14?

-   「神の子となる資格」とはどのようなものでしょうか。'What is the right' to become children of God?

-   「ことばが肉となる」とはどのようなことを表現しているのでしょうか。What does 'the Word became flesh' means?

-   神のひとり子としての栄光をみたとは、どのような意味でしょうか。What does it mean to see the glory of the Son of God?

-   「わたしたち」はどのようなことを経験したと言っていますか。What did 'we' experience?

-   15節から18節で、イエス・キリストについて何を伝えようとしていますか。What do these verses tell about Jesus Christ in verses 15 - 18?

-   どの節が印象に残りましたか。Which verse is impressive to you?

### ヨハネによる福音書 John 1:19-28

-   どのような人たちが、どこで、ヨハネに質問しますか。Who ask John questions?　Where?

-   どのような質問をしますか。What is their question?

-   ヨハネはどのように答えますか。What is John's answer?

-   メシア、エリヤ、あの預言者とはそれぞれどのような人たちですか。Who are Messaiah, Elijah, and the Prophet?

-   この人たちは何を知りたいのでしょうか。そしてそれは何故でしょうか。What do they truly want to know, and why?

-   ヨハネは結局自分をどのような者だと証言していますか。ヨハネは何を伝えたいのでしょう。Who does John claim is he? What does he want to tell the people?

-   ファリサイ派の人たちとはどのような人たちですか。Who are the Pharisees?

-   洗礼についての質問は何を聞いているのでしょうか。What is the question about baptism?

-   ヨハネはどのように答えますか。What is John's answer?

-   今日の箇所で、ヨハネはどのように「自分が光ではないこと」を証言し「光について」証ししていますか。How does John testify in vs 19-28 that he himself is not the light and he comes only as a witness to the light? (Cf. 1:8)

-   他の福音書の記述と比較して見ましょう。Compare these verses in John with other gospels.

### ヨハネによる福音書 John 1:29 - 34

-   いつのことが記されていますか。When is it?

-   他の福音書の記述を見てみましょう。Read other gospels.

-   ヨハネは、イエスについてどのように証言していますか。What does John testify about Jesus?

-   ヨハネはどのような意味で「神の小羊」と呼んだのでしょうか。Why does John call Jesus the Lamb of God?

-   15節と30節はどのような関係になっていますか。What is the relation between verse 15 and verse 30?

-   31 節では、ヨハネはどのように言っていますか。What does John tell in verse 31?

-   ヨハネはイエスがそれまで証言していた方だとどうしてわかったのですか。How does John tell that Jesus is the one he testifies?

-   聖霊によって洗礼を授けるとはどのような意味でしょうか。What does baptizing with the Holy Sprit mean?

-   なぜヨハネは「神の子」であると証ししているのでしょうか。Why does John testify that he is the Son of God, or God's Chosen One?

-   この箇所から、ヨハネについて、そしてイエスについてどんなことが分かりますか。What can you tell from these verses about John and Jesus?

### ヨハネによる福音書 John 1:35 - 42

-   いつ、どのような状況で、ヨハネはイエスに対して「見よ、神の小羊だ」と言いますか。When and under what circumstances John tell "Look, the Lamb of God!" about Jesus?

-   弟子たちはどうしますか。なぜでしょうか。What do they do, and why?

-   イエスはどうしますか。What does Jesus do?

-   弟子たちと、イエスの対話からどのようなことがわかりますか。What can you tell from the conversation of Jesus and the disciples of John?

-   あなたは、イエスに「あなたは何を求めているのか」と聞かれたら、どのように答えますか。If you are asked what you want, what is your response?

-   アンデレはどのような人ですか。Who is Adrew?

-   アンデレは、シモンに何と言っていますか。What does Andrew tell Simon?

-   アンデレは、それからどうしますか。What does Andrew do after telling this to Simon?

-   イエスは、なぜシモンに別の名前をつけたのでしょうか。Why does Jesus give Simon a new name?

### ヨハネによる福音書 John 1:43-51

-   いつ、どのようなときに、イエスはフィリポと出会いどうしますか。When and what occasion does Jesus meet Phillip? What does he do to Phillip?

-   フィリポについてどんなことがわかりますか。What do you tell about Phillip?

-   フィリポはナタナエルにイエスをどのように紹介していますか。How does Phillip introduce Jesus to Nathanael?

-   ナタナエルの47節の応答からどのようなことがわかりますか。そしてピリポはどうしますか。What can you tell from Nathaniel's response in verse 47? What does Phillip do are a response?

-   47-49 でイエスはどのようにナタナエルに話しかけ、ナタナエルはどのように告白するに至りますか。In verses 47-49, how does Jesus talk to Nathnael and how does he confess as his response?

-   ナタナエルはなぜこのように告白したのでしょうか。Why does Nathanael confess like this?

-   イエスは、50 節でどのようにナタナエルに言っていますか。What does Jesus tell Nathanael in verse 50?

-   51節はどのような光景を伝えているのでしょうか。What does Jesus tell in verse 51?

## ヨハネ 第2章

### ヨハネによる福音書 John 2:1-12

-   いつ、どこで、何がありましたか。そこには、どのような人がいますか。What happens? When and where? Who are there?

-   どのような問題がおきますか。What happens there?

-   イエスはどのように答えますか。What is Jesus' response?

-   イエスの母はイエスの応答を聞いてどうしますか。What does Jesus' mother do as her response?

-   イエスはどのように命じ、どのようなことが起きますか。What does Jesus do, and what happens?

-   「最初のしるし」とはどのような意味でしょうか。What does the first of the signs mean?

-   弟子たちにとってこれはどのような経験でしたか。What kind of experience this is to Jesus' disciples?

-   なにを伝えようとしているのでしょうか。What is the message of this story? What is the sign.

-   12節にはどのようなことが書かれていますか。What is recorded in verse 12?

### ヨハネによる福音書 John 2:13-25

-   いつ、どこで、このことが起こりますか。When does it happen and where?

-   イエスはどのような状況で何をしますか。What does Jesus do?

-   他の福音書の記述と比較してみましょう。Compare with other gospels.

-   16節のイエスのことばから、どのようなことがわかりますか。What do you tell from the words of Jesus in verse 16?

-   「あなたの家を思う熱意がわたしを食い尽くす」とはどのような意味ですか。What does 'Zeal for your house will consume me' mean?

-   ユダヤ人たちは、どうしますか。What is the response of the Jews? (v18)

-   イエスはそれにどのように答えますか。What is Jesus' response? (v19)

-   弟子たちは、イエスの言葉をどのように理解しますか。What is the disciples' interpretation of Jesus' words?

-   イエスはなぜこのような行為をしたのでしょうか。Why does Jesus do this?

-   イエスの過越祭での活動をどのように記述していますか。What does Jesus do during this Passover? What is the result? (v23)

-   イエスはそれに対してどうしたと書いてありますか。What does Jesus do?

-   その理由はどのように説明されていますか。Why doesn't Jesus entrust himself to the people?

-   なぜ信じた人たちを信用せずご自身をおまかせにならなかったか、自分の言葉で説明してみましょう。Explain the reason by your own words.

## ヨハネ 第3章

### ヨハネによる福音書 John 3:1-15

-   ニコデモはどのようなひとですか。Who is Nicodemus?

-   ニコデモはいつイエスのもとにきて、どのように告白しますか。When does Nicodemus come to Jesus and what does he tell Jesus?

-   イエスはまずなにを伝えますか。What does Jesus say first? (v.3)

-   ニコデモはこれにどのように応答しますか。What is the response of Nicodemus? (v.4)

-   イエスは、新たに生まれるということを、どのように説明していますか。How does Jesus interpret 'born again'? (vs. 5-8)

-   風のたとえは、なにを伝えようとしているのでしょうか。What does Jesus tell by the wind? (v.8)

-   ニコデモは、何を理解し、何を理解できなかったのでしょうか。What does Nicodemus understand and what does not? (v.9)

-   イスラエルの教師であるニコデモと、イエスの違いは何だと言っていますか。What is the difference between Nicodemus, Israel's teacher and Jesus?

-   何が「地上のこと」で、何が「天上のこと」なのでしょうか。What are earthly things and what are heavenly things?

-   14, 15 節で、イエスはどのようなことをニコデモに伝えていますか。What does Jesus tell Nicodemus in verses 14 and 15?

-   イエスのニコデモとの対話から、どのようなことがわかりますか。What do you tell from the dialogue between Jesus and Nicodemus?

### ヨハネによる福音書 John 3:16-21

-   1節から13節においてイエスはニコデモにどのようなことを語っていますか。What does Jesus tell Nicodemus in verses 1 to 13?

-   14, 15 節で、イエスはどのようなことをニコデモに伝えていますか。What does Jesus tell Nicodemus in verses 14 and 15?

-   15節で言われている永遠の命とはどのようなものでしょうか。What is eternal life in verse 15?

-   16節からわかることをリストしてみましょう。List up what you can tell from verse 16?

-   「神は、世を愛された」とはどのような意味でしょうか。What does 'God so loved the world' mean?

-   独り子を信じるとはどのような意味でしょうか。What is to believe in God's one and only Son?

-   なぜ、神は無条件に永遠のいのちを与えないのでしょうか。Why doesn't God give eternal life without condition?

-   神が御子を遣わした目的は何だと言っていますか。What is the purpose of God to send his Son into the world?

-   どのような人が裁かれるのだと言っていますか。Who will be condemned?

-   光の方に来るとは、何を意味していますか。What is to come into the light?

-   ニコデモは、どのようなメッセージを受け取ったでしょうか。What did Nicodemus learn from Jesus?

### ヨハネによる福音書 John 3:22-30

-   イエスとその弟子たち、ヨハネは、それぞれどこで何をしていますか。What are Jesus and his disciples and John the baptist doing? Where are they?

-   どのようなことから、議論が持ち上がりますか。When does this conversation start?

-   この人たちが、26節のように言ったのは何故だと思いますか。What is the reason they told John the words in verse 26?

-   ヨハネはどのように答えますか。What was John's response?

-   「天から与えられなければ、人は何も受けることができない。」とはどのような意味でしょうか。What does ''A person can receive only what is given them from heaven.'' mean?

-   質問をした人たちの役目は、何だと言っていますか。What is the role of the people around John?

-   ヨハネは、自分自身について、どのように証言していますか。What does John testify about himself?

-   なぜ、衰えないといけないでしょうか。Why must he less?

-   このようなヨハネの姿勢はその後にどのように影響したと思いますか。What do you think is the effect of his attitude?

### ヨハネによる福音書 John 3:31-36

-   「上から来られる方」とか「地から出る者」とは誰かを指し示しているのでしょうか。Who are 'The one who comes from above' and 'the one who is from the earth'?

-   ここでは、遣わされた方について、他にどのようなことが証言されていますか。What else is testified here about whom God has sent?

-   永遠の命について、何が語らえていますか。What is told about eternal life?

## ヨハネ 第4章

### ヨハネによる福音書 John 4:1-15

-   イエスたちは、なぜユダヤを去りますか。Why do Jesus and his disciples leave Judea?

-   イエスたちは、なぜ、サマリヤの町に行きますか。Why do they visit a town of Samaria?

-   いつ、どのような状況でイエスは、サマリアの女性と出会いますか。How does Jesus meet a Samaritan woman? What time is it?

-   イエスはどのように女性に話しかけ、それに女性はどのように応じますか。How does the conversation start? What is the reply of the woman?

-   イエスの10節のことばの意図は何なのでしょうか。What does Jesus intend to communicate by the words in verse 10?

-   「生きた水」とは何でしょうか。この女性はどのように理解していますか。What is the living water? How does this woman understand the word?

-   イエスが与える水はどのようなものだと言っていますか。What is the water Jesus gives?

-   女性はどう応じますか。What does she reply?

### ヨハネによる福音書 John 4:16-26

-   1節から15節をふり返ってみましょう。どのような変化がありますか。Review verses 1 - 15. Any changes?

-   イエスは16節でどのように尋ねていますか。What does Jesus ask this woman?

-   女性の応答に対しイエスはどのように言いますか。As she replies, what does Jesus tell her?

-   女性はなぜ、礼拝する場所についての話しを始めるのでしょうか。Why does she change the topic to the place to worship?

-   イエスはどのように答えますか。How does Jesus reply her?

-   礼拝について、イエスがもっとも大切な事として伝えようとしているのはどんなことでしょうか。What is the key in the message of Jesus about worshiping God?

-   女性はどのように答えますか。What does the woman reply?

-   イエスはどう応じますか。What does Jesus answer her?

-   女性は何を理解したでしょうか。What does she understand?

### ヨハネによる福音書 John 4:27-42

-   1節から26節をふり返ってみましょう。この出会いは、女性と、イエスにとってどのようなものだったのでしょうか。Review verses 1 - 26. What does this meeting mean to the woman and Jesus?

-   帰ってきた弟子たちは、何に驚きますか。When the disciples came back, why are they surprised?

-   女性はどうしますか。What does women do?

-   弟子たちが食事を勧めると、イエスはどのように答えますか。それはなぜでしょう。When his disciples urge Jesus to eat, how does Jesus respond? Why is it?

-   イエスの食べ物とは何ですか。What is Jesus' food?

-   イエスは弟子たちに何を教えますか。What does Jesus teach his disciples?

-   サマリア人たちは、どのような反応をしますか。What is Samaritan's response?

-   なぜこれほど素直に信じるのでしょうか。Why do many of the Samaritans believe?

-   42節でサマリアの人たちはどのように言っていますか。What do the Samaritans say in verse 42?

-   シカルでの人々との出会いから、どのようなことを学びましたか。What do you learn from the story at Sycal in Samaria?

### ヨハネによる福音書 John 4:43-56

-   イエスはどこからどこへ向かわれましたか。それは、どのような場所ですか。Where did Jesus move from and to?

-   ガリラヤの人は、イエスをどのように迎えますか。それは、なぜでしょう。Do the Galileans welcome Jesus? Why is it?

-   カナのイエスのもとにどのような人が頼み事を持ってきますか。Who comes to Jesus in Cana?

-   イエスはどのように応答しますか。How does Jesus reply to this man?

-   この人はどう答えますか。How does he respond?

-   イエスはどうしますか。そして役人はどうしますか。How does Jesus respond to this man? What does this man do?

-   この人は、何を信じたのでしょうか。What does this man believe?

-   どうなりますか。What happens?

-   ヨハネはこのことをどのようにまとめていますか。How does the writer close this paragraph?

## ヨハネ 第5章

### ヨハネによる福音書 John 5:1-18

-   この出来事はどこで起きますか。Where does it happen?

-   池の周りの回廊には、どのような人がちがいますか。Who are there around the pool called Bethesda?

-   イエスはどのような人にどのように声をかけますか。Whom does Jesus talk to?

-   この人は、どのように答えますか。What is his reply?

-   イエスはこの人にどのように命じますか。What does Jesus tell this person?

-   この人はどうなりますか。What happens to this person?

-   ユダヤ人たちは、この人になんと言いますか。What do the Jews tell this person?

-   この人は、どのように答えますか。What does this person say?

-   この人と再会したイエスは、この人にどのようなことを告げますか。What does Jesus tell this person when he meets him again?

-   ユダヤ人はイエスにどのように対し、それに、イエスはどのように答えますか。What is the Jews response? What does Jesus tell them?

-   ユダヤ人たちがイエスを殺そうとまでする理由は何ですか。Why do the Jews try to kill Jesus?

-   あなたはこの話から何を学びましたか。What do you learn from this story?

### ヨハネによる福音書 John 5:19-30

-   17節-18節で、イエスは安息日に働く理由についてどのように答え、ユダヤ人たちはどのようにそれを受け取りますか。How does Jesus tell the reason why he works on Sabbath, and how do the Jews take it? (verses 17, 18)

-   19節でイエスは子がすることと、父がすることの関係についてどのように述べていますか。What does Jesus tell about what the Son does and what his Father does? (verse 19)

-   イエスはなぜそのようにできるのですか。Why can Jesus do so?

-   聞いている人たちは何に、どのようなことに驚くと言っていますか。What will they be amazed?

-   21, 22節では、イエスはどのようなことをすると言っていますか。What will Jesus do? (verses 21 and 22)

-   それによってどのようになると 23節では言っていますか。What would be the outcome of this? (verse 23)

-   24節はどのような意味でしょうか。What does verse 24 mean?

-   25節の「死んだ者が神の子の声を聞く」とはどのような意味でしょうか。What does 'the dead will hear the voice' mean? (verse 25)

-   イエスが命を与えることができるのは、なぜだと言っていますか。Why can Jesus give life? (verse 26)

-   さばきについてどのように言っていますか。What does Jesus say about judgement?

### ヨハネによる福音書 John 5:31-38

-   19節から30節を読んで、イエスの証言についてまとめてみましょう。What does Jesus testify in verses 19 to 30.

-   31節でイエスは何について語っていますか。What does Jesus tell in verse 31?

-   32節の「わたしについて証しをなさる方」とは誰のことでしょうか。Who is the one that testifies about Jesus in verse 32.

-   ヨハネはどのような証しをしましたか。What is John's testimony about Jesus?

-   ヨハネの証しはだれのためのどのような証しだと言っていますか。For whom John's testimony is given? How does Jesus describe John's work?

-   36節の「ヨハネの証しにまさる証し」とは何ですか。What is the testimony weightier than that of John?

-   なぜ、イエスの行っている業がイエスを遣わした方のことを証言することになるのですか。Why does the works Jesus is doing testify that God sent him?

-   イエスを遣わしたかたの証言について、イエスはどのように言っていますか。What does Jesus tell about the testimony of the one who sent him?

-   わたしたちが、自分の正しさを証明するにはどうしたらよいのでしょうか。How can we testify the validity of ourself?

### ヨハネによる福音書 John 5:39-47

-   31節から38節からイエスはどのように証言しているか復習してみましょう。Review what does Jesus say in verses 31 to 38.

-   聖書の証しについてイエスはどのように言っていますか。What does Jesus tell about the testimony of the Scripture?

-   聖書がイエスについて証ししているとはどのような意味でしょうか。What does ''the Scriptures testify Jesus'' mean?

-   命を得るためにイエスのもとに来ない理由は何だと言っていますか。What is the reason why they refuse come to Jesus to have life?\

-   訴えるのは、モーセだと言っていますが、それはなぜですか。Why does Moses accuse those who refuse to come to Jesus?

-   ユダヤ人たちが、神について証しをすると信じているものは、何ですか。イエスはそれについてどのように言っているのでしょう。What do you think the Jews believe to testify God? What does Jesus tell about ti?

-   どうすればイエスが神から来たことがわかるのでしょうか。How can we tell Jesus if from God?

-   聖書とは何なのでしょうか。What is the Bible?

## ヨハネ 第6章

### ヨハネによる福音書 John 6:1-15 (Part I)

-   いつ、イエスは、どこからどこへ移動しますか。When and where did Jesus go?

-   他の福音書は背景についてどのように記していますか。What do other gospels say?

-   群衆は何を求めてイエスの後を追いかけたのでしょうか。Why did the crowds follow Jesus?

-   この時の状況を、ヨハネは 3-5節にどのように描いていますか。How does John describe the scene in verses 3 - 5?

-   イエスはフィリポにどのように声をかけますか。How did Jesus say to Philip?

-   フィリポは何と答えますか。What was Philip's answer?

-   このとき、誰がどのような情報をもたらしますか。Who brought extra information? What is it?

-   この少年は、とてもたくさんパンと魚をもっていたのでしょうか。Did this boy have many loaves of bread and many fish?

-   イエスはどうしますか。What did Jesus do?

-   どうなったと書かれていますか。What were the results?

-   人々は、これをどのように受け止め、どのような行動に出たと書かれていますか。What did the crowds take this and what did they do? (verses 14, 15)

-   イエスはどうしますか。What did Jesus do?

### ヨハネによる福音書 John 6:1-15 (Part II)

-   もういちど、最初から確認してみましょう。Let us review the story from the beginning.

-   五つのパンと二匹の魚の出来事がどのように扱われているか6章の中からリストしてみましょう。How is this incidence treated in John 6?

-   人々は、最初イエスのもとに来たとき（6章のはじめ）何を求めていたのでしょうか。What did the people seek when they came to Jesus in the beginning of John 6?

-   五つのパンと二匹の魚で五千人が満腹した後、人々は、何を求めていますか。What did the people seek after they were fed by five loaves of bread and two fish?

-   イエスは、何を人々に求めていますか。What does Jesus want of the people?

-   何が起こったのでしょうか。What actually happened?

-   この記事を通して福音書記者はそれぞれ何を伝えようとしているのでしょうか。What do the gospel writers want to communicate to us?

### ヨハネによる福音書 John 6:16 - 21

-   弟子たちはどのような状況で舟にのりますか。Describe the disciples when they got into a boat.

-   他の福音書にはどのように書かれていますか。What can you find from other gospels?

-   弟子たちが、イエスと一緒にいることといないことは、どのような差があったのでしょうか。What makes a difference if the disciples were there with Jesus?

-   舟に乗った弟子たちにはどのようなことが起こりますか。そしてイエスはどうしますか。What happened to the disciples on the boat?　What did Jesus do?

-   イエスをみて弟子たちはどのような反応をしますか。What were the responses of the disciples when they saw Jesus?

-   イエスはなんと声をかけますか。What did Jesus say to his disciples?

-   マタイによる福音書にはどのようなことが記されていますか。What is written in Mathew? %(Matt 14:28)

-   ヨハネはこの話しをどのように締めくくっていますか。How does John close this paragraph?

-   ヨハネは、この出来事を通してなにを伝えているのでしょうか。What does John tell us using this story?

### ヨハネによる福音書 John 6:22-40

-   群衆、イエス、その弟子たちは、それぞれどこにいますか。Where are the crowds, Jesus and his disciples?

-   群衆は、なぜイエスを探しているのでしょうか。Why do the crowds seek Jesus?

-   イエスは、群衆にどのように語っていますか。What does Jesus tell the crowds? (verses 26, 27)

-   「いつまでもなくならないで、永遠の命に至る食べ物のために働きなさい。」とはどのような意味でしょうか。What does ''to work for food that endures to eternal life'' mean?

-   群衆はどのような質問をし、イエスはどのように答えていますか。What do the crowds ask Jesus? How does Jesus respond? (verses 28, 29)

-   これに対して、群衆は何を求めていますか。What do the crowds request? (verses 30, 31)

-   これに対してイエスはどのように答えますか。How does Jesus respond to them? (verses 32, 33)

-   群衆はイエスの答えをどのように理解していますか。How do the crowds understand Jesus' message?

-   イエスが命のパンであるとはどのような意味なのでしょうか。What does ''Jesus is the bread of life'' mean?

-   イエスにとっての神の使命とは何なのでしょうか。What is Jesus' misson?

-   永遠の命を得ることと、終わりの日に復活することはどのような関係にあるのでしょうか。What is the relation between to have eternal life and to be risen up at the last day?

### ヨハネによる福音書 John 6:41-59

-   この会話は、いつどのような時に、どのような人の間でなされたものですか。Who are talking? When and where are they talking?

-   ユダヤ人たちは、イエスのことでどのようにつぶやきますか。それはなぜですか。Why and how do the Jews grumble about Jesus?

-   イエスの答えをまとめてみましょう。Summarize what Jesus responded. (verses 43 - 51)

-   イエスが命のパンであるとは、どのようなことを意味しているのでしょうか。What does it mean that ''Jesus is the bread of life"?

-   「わたしが与えるパン」は、「命のパン」や、「生きたパン」と同じでしょうか。Is the bread Jesus will give us same as the bread of life or the living bread?

-   ユダヤ人たちは、どのような議論を始めますか。What do the Jews argue sharply?

-   イエスは、生きたパンをたべることについてさらにどのようにユダヤ人たちに伝えますか。What does Jesus tell the Jews about eating the living bread?

-   イエスの肉を食べ、その血を飲むとは、なにを言っているのでしょうか。What does 'eating Jesus' flesh and drinking his blood mean?

-   先祖が食べたマナと、生きたパンは、何が共通点で、なにが異なるのでしょうか。Compare the manna the ancestors ate and the bread of life.

-   イエスが、そして、聖書記者が伝えたかったことはどのようなことなのでしょうか。What does Jesus and/or John want to communicate?

### ヨハネによる福音書 John 6:60-71

-   これまでのイエスのメッセージを復習してみましょう。Review the message of Jesus.

-   弟子たちは、何をひどいといっているのでしょうか。Which teaching is it the disciples cannot accept?

-   これに対してイエスはどのように答えますか。How does Jesus respond?

-   イエスが語ったことばは霊であり、命であるとはどのような意味でしょうか。What does ''The words I have spoken to you are full of the Spirit and life'' mean?

-   イエスは、64節・65節で信じない者について、どのようなことを告げますか。What does Jesus say about those who do not believe?

-   弟子たちの多くがイエスを離れ去りますが、それはなぜでしょう。Why do many of Jesus' disciples turn back?

-   イエスの問いに、ペトロはどのように答えますか。How does Peter respond to Jesus?

-   残った十二弟子と、去って行った弟子たちでは、なにが違っていたのでしょうか。What are the differences between the twelve disciples and those who do not follow?

-   イエスは、ここでどのように十二弟子に言いますか。What does Jesus say to the twelve disciples?

-   イエスは、悪魔を選んだのでしょうか。Does Jesus choose a devil?

-   イエスを求めて従ってきた人を、イエスは追い返しているようにも見えますが、それはなぜでしょうか。イエスは何を望んでいるのでしょうか。Jesus seems not to accept followers. Why is it? What does he want us?

## ヨハネ 第7章

### ヨハネによる福音書 John 7:1-13

-   イエスはどこにいますか。それは何故ですか。Where is Jesus and why?

-   いつのできごとですか。When is it?

-   イエスの兄弟たちは、イエスにどのように進言しますか。それは、何故ですか。What do Jesus' brothers suggest Jesus and why?

-   イエスはこれに対して、どのように答えますか。How does Jesus respond to them? (verses 6 - 8)

-   「時」とは何でしょうか。わたしたちにもそのような「時」があるのでしょうか。What is 'my time'? Is there a special time for us?

-   イエスは7節は何を伝えているのでしょうか。What does Jesus tell in verse 7?

-   イエスは結局どのように行動しますか。それは何故でしょう。What does Jesus do after all, and why?

-   ユダヤ人は、どのようにイエスを見ていますか。What do Jews think of Jesus?

-   なぜ人々は、公然と語れないのでしょうか。Why do the people whisper and would not say publicly?

-   この章には、どのような人たちの、イエスに対する評価が書かれていますか。Make a list of groups of people in this chapter, and their assessment of Jesus.

### ヨハネによる福音書 John 7:14-24

-   イエスはどこにいて何をしていますか。それはどのような時ですか。Where is Jesus, what is he doing and when is it?

-   ユダヤ人たちは、何に驚いていますか。What are the Jews amazed at?

-   イエスは16節から18節で自分の教えについてどのようなことを述べていますか。What does Jesus tell about his teacihng in verses 16 to 18?

-   イエスは、なぜ自分が教えていることが神の教えであることがわかるのでしょうか。How does Jesus know that his teaching is from God?

-   「自分の栄光を求める」・「神の栄光を求める」は、それぞれどのようなことでしょうか。What is to gain personal glory, and to seek the glory of God?

-   イエスは、19節で、この人たちをどのように批判していますか。How does Jesus criticize the people in verse 19?

-   群衆はどのように、答えていますか。 What is their response?

-   イエスはこれに対して、どのように教えていますか。What does Jesus teach them as a response?

-   24節の「うわべだけで裁くのをやめ、正しい裁きをしなさい。」は何を教えているのでしょうか。What does ''Stop judging by mere appearances, but instead judge correctly.'' in verse 24 mean?

### ヨハネによる福音書 John 7:25-36

-   イエスはどこにいますか。イエスの周囲にはどのような人たちがいますか。Where is Jesus? Who else are there?

-   エルサレムの人々の間ではイエスについてどのような議論をしていますか。What do the people of Jerusalem ask about Jesus?

-   イエスはこれに対して、どのように語っていますか。What does Jesus respond to the them?

-   人々はどうしますか。そしてどうなりますか。What do the people do? What happens?

-   31節では、どのようなひとがどのような事を言っていますか。What do people say about Jesus in verse 31?

-   祭司長たちとファリサイ派の人々はどうしますか。What do the chief priests and the Pharisees do?

-   イエスは、33節・34節でどのように言っていますか。このことから何がわかりますか。In verses 33 and 34, what does Jesus say? What can you tell from his message?

-   ユダヤ人たちは、イエスの言葉についてどのような議論をしていますか。What do the Jews talk about Jesus' words?

-   本当に見つけることができないのでしょうか。Is it impossible to find Jesus?

### ヨハネによる福音書 John 7:37-39

-   イエスはどこにいますか。また、どのような時ですか。Where is Jesus? When is it?

-   イエスは、この祭りの間、どのようなことを教え、どのようなことを語っていますか。During this festival, what does Jesus teach and tell.

-   イエスは大声で何を言いますか。What does Jesus say in a loud voice?

-   渇いている人とはどのような人たちでしょうか。Who do you think is thirsty?

-   イエスのもとで何が得られるのでしょうか。What do we get if we come to Jesus?

-   生きた水が川となって流れ出るとはどのような意味でしょうか。What does ''rivers of living water will flow from within them'' mean?

-   39節はどのようなことを言っていますか。What does verse 29 tell?

-   霊とは何でしょうか。What is the Sprit?

### ヨハネによる福音書 John 7:40-52

-   この場には、どのような人たちがいますか。 Who are there with Jesus?

-   37 節, 38 節のイエスのことばを復習してみましょう。 Review Jesus' words in verses from 37 to 38.

-   群衆はどのような反応をしますか。 What was the responses of the crowds?

-   メシヤの出身地について、どのようなことが議論されていますか。 What is argued among the crowds about the birth of the Messaiah?

-   イエス自身は、自分はどこから来たと言っていますか。 What does Jesus say about where he is from?

-   人々の判断の根拠は何ですか。何に信頼している のでしょうか。 What is the basis of their belief? What do they trust?

-   なぜ、イエスに手をかける者はなかったのでしょうか。 Why don't they arrest Jesus?

-   祭司長たちやファリサイ人たちの問いに、下役たちはどのように答えますか。 How do the temple guards respond to the chief priests and the Phar- isees?

-   ファリサイ派のひとたちはどういいますか。その 根拠は何ですか。 What do the Pharisees say to them? What are their bases?

-   このとき、だれがどのような発言をしますか。 Who gives a comment? What is it?

-   ニコデモは、このとき、どう考えていたのでしょうか。 What does Nicodemus believe at this moment?

## ヨハネ 第8章

### ヨハネによる福音書 John 7:53-8:11

-   人々とイエスはそれぞれどこへ行きますか。Where do the people go? Where does Jesus go?

-   イエスは、いつ、どこで何をしていますか。Where is Jesus? When is it? What is he doing?

-   どのようなことが起こりますか。What happens?

-   女性についてどのようなことがわかりますか。What can you tell about this woman?

-   女性をつれてきた本当の目的はなんですか。What is the real purpose to bring this woman to Jesus?

-   イエスは、どのように応じますか。How does Jesus respond?

-   イエスはなんと言いますか。What does Jesus say?

-   人々はどうします。What happens to the people?

-   イエスはどうしますか。What does Jesus do?

-   女性はどのようなメッセージを受け取ったでしょうか。What does this woman understand?

-   イエスは、なにを伝えていますか。What does Jesus tell?

### ヨハネによる福音書 John 8:12-20

-   イエスはどこにいますか。これは、いつのことでしょうか。Where is Jesus? When is it?

-   12節で「再び（また）」と言っていますが、これまでに、イエスは、自分について、どんなことを言っていましたか。Verse 12 says 'again'. What has Jesus claimed about himself?

-   「イエスが世の光である」とはどのような意味でしょうか。What does ''Jesus is the light of the world'' mean?

-   「イエスに従う」とは、「命の光を持つ」とはどのような意味でしょうか。What do 'to follow Jesus' and 'to have the light of the life' mean?

-   ファリサイ派の人たちはどのように反論しますか。How do the Pharisees criticize Jesus?

-   イエスはこれにどのように答えていますか。How does Jesus respond to it?

-   「どこから来たのか、そしてどこへ行くのか、知っている」とは何を意味しているのでしょうか。What does ''I know where I came from and where I am going'' mean?

-   「肉に従って裁く」とは何を言っているのでしょうか。What does 'You judge by human standards' mean?

-   なぜイエスは誰をも裁かないのでしょうか。Why does not Jesus judge anyone?

-   イエスの裁きが真実であることの根拠はなんですか。Why is Jesus' decision true?

-   ファリサイ派の人たちはどのように答えていますか。How do the Pharisees respond?

-   時が来ていないとはどのような意味でしょうか。What does 'Jesus' hour had not yet come' mean?

### ヨハネによる福音書 John 8:21-30

-   イエスはどこでだれに対して話していますか。そこには、どのようなひとがいるでしょうか。Whom does Jesus talk? Where are they? Who are there?

-   イエスは自分の行き先について、聞いている人たちについてどのように言っていますか。What does Jesus say about his and their destiny?

-   人々はイエスの言葉をどのように理解しますか。How do the people respond to Jesus' claim?

-   イエスは 23節、24節で何と言っていますか。What does Jesus say in verses 23 and 24?

-   25節の人々の質問からどのようなことがわかりますか。What can you tell from the question of the people in verse 25?

-   イエスはこれに対して、どのように答えていますか。How does Jesus reply to their question?

-   人々はなぜ悟ることができないのでしょうか。　Why don't the people understand?

-   イエスは、引き続き、何を伝えていますか。What does Jesus say in verses 28 and 29?

-   24節、28節にある、「『わたしはある』ということ」何を意味しているのでしょうか。What does 'I am he' in verses 24 and 28 mean?

-   イエスは何を伝えようとしているのでしょうか。What does Jesus tell the people?

### ヨハネによる福音書 John 8:30 - 38

-   イエスはどこで誰に対して話していますか。そこにはどんな人たちがいるでしょうか。Whom does Jesus talk? Where are they? Who are there?

-   イエスの言葉にとどまるとはどのような意味でしょうか。What does it mean to 'hold to Jesus' teaching'?

-   「真理が自由にする」とはどのような意味でしょうか。What does 'the truth will set you free' mean?

-   「真理」をほかの言葉で言うとどうなりますか。What is Truth in other words?

-   「自由」をほかの言葉でいうどうなりますか。What is Freedom in other words?

-   「自由になる」と聞いて、ユダヤ人たちは、どのような反応を示しますか。What is the response of the Jews when they hear the words 'to be free'?

-   イエスはこれにまず 34節でどのように答えますか。How does Jesus respond to them first?

-   なぜ、罪を犯す者は罪の奴隷なのでしょうか。Why is anyone who sins a slave to sin?

-   35節36節の奴隷と子の違いはなにを伝えているのでしょうか。What is the difference between the son and the slave explained in verses 35 and 36?

-   37節38節は何を言っているのでしょうか。What does Jesus tell in verses 37 and 38?

### ヨハネによる福音書 John 8:39 - 47

-   31節からの箇所を復習してみましょう。どのようなことで議論していますか。Review a paragraph starting from verse 31. What is the topic the Jews are arguing with Jesus?

-   ユダヤ人たちはなにを主張していますか。What do the Jews claim? - verse 39.

-   イエスは、どのように言われますか。How does Jesus respond? - verses 39b, 40, 41a

-   ユダヤ人たちは、次になにを主張しますか。What do the Jews claim next? - verse 41

-   ユダヤ人たちの父が神であるとの主張に対して、イエスはどのように反論していますか。How does Jesus argue on the Jews' claim that their Father is God?　 - verses s42 - 45

-   イエスは、ユダヤ人たちが、わからない理由は何だと言っていますか。Why is the language of Jesus not clear to the Jews?

-   なぜ、ユダヤ人たちは、イエスの言葉を聞くことができないのですか。Why are the Jews unable to hear what Jesus say?

-   イエスは、神の子と、悪魔の子をどのように区別していますか。How does Jesus distinguish the children of God and those of the Devil?

-   イエスは真理と偽りについてどのように言っていますか。What does Jesus say about the truth and the lies?

-   イエスは、人々に 46 節でどのように、訴えていますか。How does Jesus challenge the Jews in verse 46?

-   イエスは、なにを伝えようとしているのでしょうか。What does Jesus tell the Jews?

### ヨハネによる福音書 John 8:48 - 59

-   31節からの箇所を復習してみましょう。どのようなことで議論していますか。Review a paragraph starting from verse 31. What is the topic the Jews are arguing with Jesus?

-   ユダヤ人たちは、何と言ってイエスを非難しますか。その根拠は何ですか。What do the Jews say against Jesus? Why is it?

-   イエスはこれに何と答えますか。What is Jesus' response? (verses 49, 50)

-   「わたしの言葉を守るなら、その人は決して死ぬ（死をみる）ことがない。」とは、どのようなことを言っているのでしょうか。What does Jesus mean by saying ''whoever obeys my word will never see death''?

-   ユダヤ人たちはどのように、反論しますか。How do the Jews question Jesus? (verses 52, 53)

-   イエスはこれにどのように答えますか。How does Jesus reply to this?

-   56節はどのような意味なのでしょうか。What does verse 56 mean?

-   ユダヤ人は、これにどのように、反応しますか。How do the Jews respond to the word of Jesus in verse 56?

-   イエスは、どのように宣言しますか。What does Jesus claim? (verse 58)

-   どうなりますか。What happens?

-   イエスはなにを伝えようとし、ユダヤ人たちは、なにが受け入れられなかったのでしょうか。What does Jesus tell the Jews and what is the Jesus unable to accept?

## ヨハネ 第9章

### ヨハネによる福音書 John 9:1-12

-   どのような状況で、弟子たちはイエスに質問しますか。When do the disciples ask Jesus a question?

-   弟子たちは、どんな質問をしますか。What is the question?

-   当時の人たちは、どのように考えていたのでしょうか。What do you think the Jews were thinking about?

-   このような問題を、現代のひとはどのように考えているでしょうか。What do the people in modern world think about?

-   イエスはどう答えますか。What is Jesus' answer?

-   イエスはつづけてどのように言われますか。What does Jesus add to it? (verses 4, 5)

-   イエスは、この盲人のひとにどうしますか。どうなりますか。What does Jesus do to this person? What happens?

-   人々はどのような反応をしますか。そして、この人はどのように答えますか。What was the responses of the people? How does this person respond?

-   この人は何を知り、何を知りませんか。What does this person know? What does he not know?

-   「神の業がこの人に現れる」とは、このひとが癒やされると言うことなのでしょうか。Is the healing of this person ''the works of God being displayed''?

-   イエスは、このひとに、そして、人々に、弟子たちに、何を望んでいたのでしょうか。What is the message of Jesus to this person, the people and his disciples?

### ヨハネによる福音書 John 9:13-34

-   9章1節から12節を復習しましょう。Review from verse 1 to 12.

-   盲人だった人は、どこに連れて行かれますか。なぜでしょう。Where is the man who had been blind brought?

-   どのような議論がおこりますか。What do they argue about?

-   盲人だった人は、イエスとどのような人だと考えていますか。Who does the man who had been blind think Jesus is?

-   ユダヤ人たちは、どうして信じられないのでしょうか。Why are the Jews unable to believe?

-   両親には、どのようなことを確かめますか。両親はどのように答えますか。What do they ask his parents? What do the parents respond?

-   この人はどうなりますか。What happens to this person?

-   ユダヤ人たちは、何を知り、何を知らないと言っていますか。What do the Jews claim to know and what do not?

-   盲人だった人はどんな証言をしていますか。What is his testimony?

-   この人はどうなりますか。What happens to Jesus?

-   この人には、どのような変化がみられますか。What is changed in this person?

### ヨハネによる福音書 John 9:35-46

-   9章1節から34節を復習しましょう。Review from verse 1 to 34.

-   どのようにイエスは盲人だった人に出会いますか。How does Jesus meet the man who was blind.

-   イエスはまずどのように聞きますか。What is the first question of Jesus?

-   なんと答えますか。What is his response? (verse 36)

-   イエスは、どのように答えますか。What is Jesus' reply? (verse 37)

-   この人は、どのように応答しますか。What is his reply? (verse 38)

-   イエスは、何と言われますか。What does Jesus tell?

-   イエスの裁きとはどのようなものなのでしょうか。What is Jesus' judgement?

-   ファリサイ派のひとたちは、どのように言いますか。What do the Pharisees say?

-   イエスの41節の言葉は、何を伝えていますか。What is Jesus' message in verse 41?

-   盲人だった人は、見えるようになったのでしょうか。命を得たのでしょうか。Can the man who was blind see? Does he have eternal life?

## ヨハネ 第10章

### ヨハネによる福音書 John 10:1-10

-   イエスは誰に対して話していますか。To whom is Jesus telling this?

-   1節から18節の間でイエスは自分を何に譬えていますか。In the parables from verse 1 to 18, what is Jesus compared to?

-   羊の門とはどのようなものだと言っていますか。What is the function of the gate of the sheep?

-   羊飼いとはどのような者だと言っていますか。How is the shepherd of the sheep described?

-   羊の門と羊飼い以外にどのようなものや人たちが登場しますか。What are the other casts besides the gate and the shepherd in this parable?

-   たとえの中のものや人は何に譬えられているのでしょうか。What are these casts compared to?

-   6節に彼らは何のことかわからなかったとありますが、伝えようとしたことは何だったのでしょうか。What is the message Jesus told 'them'? %6節にファリサイ派の人々に話されたとありますが、それはどのようなメッセージなのでしょうか。What is the message Jesus told the Pharisees? (verse 6)

-   イエスが羊の門であるとは、どのような意味でしょうか。What does 'Jesus is the gate for the sheep' mean?

-   「わたしより前に来た者」とはどのような人のことでしょうか。Who are those came before Jesus in verse 8?

-   羊についてはどのようなことが言われていますか。What is said about the sheep?

-   イエスが来た目的は何ですか。What is the purpose of Jesus's coming?

### ヨハネによる福音書 John 10:11-21

-   1節から10節を復習してみましょう。誰に対して話していますか。イエスは自分を何にたとえていますか。Review verses 1 to 10. Whom is Jesus talking this parable. What is Jesus compared himself to?

-   イエスは11節で自分を何にたとえていますか。What is Jesus compared himself to in verse 11?

-   雇い人との違いをどのように言っていますか。What is the difference with the hired hand?

-   良い羊飼いについて他にどのようなことを言っていますか。What is said about the good shepherd?

-   「この囲いに入っていないほかの羊」とは何を意味しているのでしょうか。What does 'other sheep that are not of this sheep pen' mean?

-   「命を捨てる」とは何を意味しているのでしょうか。What does it mean for Jesus to lay down his life?

-   「父から受けた掟」とはどのような意味でしょうか。What does 'the command Jesus received from His Father' mean?

-   イエスが伝えたかったことは、何なのでしょうか。What is the message of Jesus?

-   この話を聞いた人たちにはどのようなことが起こりますか。What happen to those who hear this message?

-   この人たちを分けたのは何ですか。What divides the people in two groups?

### ヨハネによる福音書 John 10:22-30

-   10章1節から21節のできごとを復習してみましょう。どのようなことが分かりますか。Review John 10:1-21. What can you tell?

-   いつ、どこでのできごとだと書かれていますか。When and where does this happen?

-   ユダヤ人たちは、イエスにどのように迫りますか。How do the Jews challenge Jesus?

-   イエスは、どのように答えていますか。How does Jesus respond to them?

-   イエスの業は何を証ししているのでしょうか。What does Jesus' work testify?

-   イエスの羊かどうかは、どのようにして分かると言っていますか。How can they tell whether or not they are Jesus' sheep?

-   イエスの羊はどうなると言っていますか。What does Jesus say about his sheep?

-   29節で偉大なものと言っているのは、何なのでしょうか。What is greater than all in verse 29? %イエスの父がイエスに下さったものとは、何なのでしょうか。What are those his Father gave Jesus?

-   「わたしと父とは一つである」とはどのような意味なのでしょうか。What does it mean to say ''I and the Father are one".

-   ユダヤ人たちは、これを聞いてどうしますか。What do the Jews do?

### ヨハネによる福音書 John 10:(28-) 31-42

-   イエスは、いつ、どのような場所で、どのような人と話していますか。When and where is Jesus talking? Who are there?

-   ユダヤ人たちは、イエスの話を聞いてどうしますか。What do the Jews do when they hear Jesus say?

-   石打にしようとしたユダヤ人たちに、イエスはどのように言っていますか。What does Jesus say when the Jews picked up stones to stone him?

-   ユダヤ人たちは何と答えますか。What do the Jews reply?

-   34節のイエスの言葉はどのような意味でしょうか。What does Jesus mean by his quote?

-   「父の業」はどのようなことを意味しているのでしょうか。What does the works of the Father mean?

-   ユダヤ人たちはどうしますか。What do the Jews do?

-   そしてどうなりますか。And what happens?

-   イエスは、それから、どこへ向かいますか。Where does Jesus go?

-   そこでは、人々はどのように証言しますか。What do the people there testify?

## ヨハネ 第11章

### ヨハネによる福音書 John 11:1 - 16

-   ラザロについては、どのように紹介されていますか。What can you tell about Lazarus?

-   姉妹たちはイエスに病気のことをどのように伝えますか。What do Mary and Martha tell Jesus about their brother?

-   この知らせを聞いて、イエスはどのように応答しますか。What does Jesus say when he received the message?

-   なぜなお二日間同じところに滞在したのでしょうか。Why does Jesus stayed where he was two more days?

-   ユダヤに行くことはなにを意味していたのでしょうか。What does it mean for Jesus and his disciples to go to Judea?

-   9, 10節のイエスの言葉は何を伝えているのでしょうか。What does Jesus mean by his words in verses 9 and 10?

-   それからイエスはどのように弟子たちに告げますか。(11節) What does Jesus tell his disciples then? (verse 11)

-   弟子たちはどのように反応しますか。How do his disciples respond?

-   イエスは、どのように、弟子たちに答えますか。（14,15節）How does Jesus respond to his disciples? (verses 14, 15)

-   トマスはどのように応答しますか。How does Thomas respond?

### ヨハネによる福音書 John 11:17 - 32

-   1節から16節を復習してみましょう。Review verses from 1 to 16.

-   イエスが到着したとき、ラザロはどのような状態でしたか。What did Jesus find out about Lazarus as he arrived?

-   ベタニアはどこにあると書かれていますか。Where is Bethany?

-   マルタとマリアのところには、どのようなひとたちがいますか。Who are there with Martha and Mary?

-   だれがイエスを迎えに来ますか。Who came out to meet Jesus?

-   マルタはイエスに会うとどのように言いますか。What does Matha tell Jesus when they meet? (vs 21, 22)

-   イエスはどのように答えますか。How does Jesus reply to Martha? (v23)

-   マルタはどのように答えますか。How does Martha reply? (v24)

-   25, 26 節のイエスの言葉は、何を伝えているのでしょうか。What does Jesus mean by his words in verses 25 and 26?

-   マルタはこれにどのように応答しますか。How does Martha reply? (v27)

-   マリアはどのように、イエスを迎えますか。How does Maria meet Jesus?

### ヨハネによる福音書 John 11:33 - 44

-   17節から32節を復習しましょう。Review the verses from 17 to 32.

-   どのような人たちがいますか。Who are there?

-   イエスは皆の様子を見てどうしますか。What does Jesus do? (verses 33-35)

-   あなたは、イエスはなぜ、心に憤りを覚え、興奮したのだと思いますか。Why do you think was Jesus deeply moved in spirit and troubled?

-   イエスはなぜ涙を流されたのでしょうか。Why did Jesus weep?

-   ユダヤ人たちは、どのように考えますか。What do the Jews see this? (verses 36, 37)

-   イエスが石を取りのけるように命じると、マルタはどのように言い、それに対して、イエスはどのように言いますか。When Jesus said ''Take away the stone'', what did Martha say? What was Jesus' reply? (verses 39, 40)

-   イエスはどのように祈りますか。How did Jesus pray then?

-   それからイエスはどのように行動し、どうなりますか。What did Jesus do next, and what happened?

-   この出来事は、何を伝えているのでしょうか。What is the message of this story?

### ヨハネによる福音書 John 11:45-57

-   イエスのなさったことを復習してみましょう。Review what Jesus had done in Bethany. (verses 17-44)

-   イエスのなさったことを目撃したユダヤ人は、どうしましたか。What did the Jews who had seen what Jesus did do?

-   ファリサイ派の人々に告げた目的は何でしょうか。Why did some Jews go to the Pharisees to tell what Jesus had done?

-   祭司長たちとファリサイ派の人々は状況をどのように見ていますか。What is the assessment of the situation by the chief priests and the Pharisees?

-   カイアファはどのような発言をしますか。What did Caiaphas say?

-   51, 52 節はどのような意味でしょうか。What do verses 51 and 52 mean?

-   どのような結論を出しましたか。What was their decision?

-   これに対して、イエスはどうしますか。How dioes Jesus respond to this?

-   過越の祭についてどのような事が書かれていますか。What is written about the Jewish Passover?

-   イエスがなさったことと、祭司長たちや、ファリサイ派の人たちの行動にについてあなたはどう思いますか。What is your thoughts on what Jesus had done and what the high priests and the Pharisees had done?

## ヨハネ 第12章

### ヨハネによる福音書 John 12:1 - 11

-   いつ、どこで、どのようなことが起きますか。また、そこには、どのような人たちがいますか。What does it happen? When and where is it? Who are there? (verses 1 - 3)

-   他の福音書の記事と比較してみましょう。Compare this with the story in other gospels?

-   マリアの行為はどのように記述されていますか。How is Maria's action described?

-   マリアはなぜ油を注いだのでしょうか。Why does this woman pours very expensive perfume on Jesus's head?

-   マリアの行為に対して、だれがどのようなことを言いますか。Who say what against Maria?

-   他の人たちはどのように考えていたでしょうか。What do you think other people around them want to say?

-   イエスはなんと言われますか。What does Jesus tell them?

-   わたしたちには、どのような価値判断が必要なのでしょうか。What is your assessment?

-   何が目的で、多くのユダヤ人が訪ねてきますか。For what purpose do many Jews come and visit them?

-   祭司長たちはどうしますか。それななぜですか。What do the high priest do? What is the reason?

### ヨハネによる福音書 John 12:12 - 19

-   いつ、どこで、どのようなことが起きますか。また、そこには、どのような人たちがいますか。What does it happen? When and where is it? Who are there? (verses 12 - 14)

-   イエスを取り巻く状況について確認しましょう。Review the situation of Jesus? (11:45-57)

-   群衆はどのように、イエスを迎えますか。How do the crowd welcome Jesus?

-   イエスは、なぜ、ろばの子に乗って、エルサレムに入城したのでしょうか。Why does Jesus enter Jerusalem on a donkey's colt?

-   他の福音書の記事と比較してみましょう。Compare this with the story in other gospels. (Mt 21:1-11, Mk 11:1-11, Lk 19:28-44)

-   弟子たちが、あとから気づいたのはどのようなことでしょうか。What do the disciples understand later?

-   群衆の動機についてどのように書かれていますか。What is written about the motivation of the crowd?

-   ファリサイ派の人々は、どのように反応しますか。How do the Pharisees respond?

-   ヨハネは、どんなことを伝えているのでしょうか。What does John tell us by this story?

### ヨハネによる福音書 John 12:20-36

-   だれが、いつ、どのようにして、イエスに面会を求めますか。Who come to meet Jesus? When is it? How do they request?

-   この人たちは、なぜイエスに会いたいのでしょうか。Why do they want to meet Jesus?

-   イエスはどのように答えますか。How does Jesus respond? (verses 23-26)

-   「人の子が栄光を受ける時が来た」とは何をさしているのでしょうか。What does ''The hour has come for the Son of Man to be glorified'' mean?

-   24節、25節は、どのようなことを伝えていると思いますか。What does the message in verses 24 and 25 communicate?

-   26節はなにを伝えていますか。What does verse 26 mean?

-   イエスの27節の言葉はなにを意味しているのでしょうか。What does Jesus' words in verse 27 mean?

-   このとき、どのようなことが起こりますか。What happens then?

-   イエスは、31節から32節でどのようなことを言っていますか。What does Jesus tell in verses 31 and 32?

-   人々はどのような疑問を呈しますか。How do the people respond?

-   イエスはどのように、忠告しますか。What does Jesus tell the people?

### ヨハネによる福音書 John 12:36b-50

-   イエスは、どうしますか。What does Jesus do?

-   誰から身を隠したのでしょうか。それは、いつまででしょうか。From whom does Jesus hide himself? Until when?

-   イエスを信じなかったということをどのようにヨハネは記していますか。What is written about unbelief of them?

-   最初のイザヤの預言はどのようなことについて言っていますか。What does the first prophesy of Isaiah tell?

-   二つ目のイザヤの預言はどのようなことについて言っていますか。What does the second prophesy of Isaiah tell?

-   「イザヤがイエスの栄光を見た」とはどのようなことを指しているのでしょうか。What does 'Isaiah saw Jesus' glory' mean?

-   イエスを信じた議員については、どのように書かれていますか。What is written about the leaders who believed?

-   イエスは、どこで、誰に対して、叫んでいますか。Where does Jesus cry out? To whom is he telling verses 44 to 50?

-   44節から50節までイエスが言っていることをまとめてみましょう。Summarize what Jesus tells in verses 44 to 50.

-   イエスの遣わされた目的は何でしょうか。What is the purpose sending Jesus?

## ヨハネ 第13章

### ヨハネによる福音書 John 13:1-11

-   12章にはどのような事が書かれていましたか。Review chapter 12.

-   12章から13章への大きな変化は何ですか。What changed from chapter 12 to chapter 13?

-   いつのことですか。イエスは、このときをどのようなときだと認識していますか。When is it? How does Jesus recognize the moment?

-   イスカリオテのシモンの子ユダについては、どのようなことが書かれていますか。What is written about Judas, the son of Simon Iscariot?

-   イエスはどのような行動をしますか。What does Jesus do? (verses 4, 5)

-   3節のことばは、イエスの行為とどのように関係しているのでしょうか。How does the verse 3 relate to Jesus' action?

-   ペテロはどのような質問をし、イエスはどのように答えますか。What does Peter ask Jesus? How does Jesus respond?

-   このあと、ペトロとイエスは、どのような会話をしますか。What does Peter argue with Jesus? (verses 8-10)

-   イエスのことば「もしわたしがあなたを洗わないなら、あなたはわたしと何のかかわりもないことになる」はどのような意味でしょうか。What does Jesus mean by saying, ''Unless I wash you, you have no part with me.''

-   11節にはどのようなことが記されていますか。What is recorded in verse 11?

### ヨハネによる福音書 John 13:12-20

-   1節から11節を復習しましょう。Review verses from one to eleven.

-   席に着くとまずイエスは何と問いかけますか。What does Jesus ask his disciples when he returns to his place? (verse 12)

-   イエスは弟子たちにとってどのような存在だと言っていますか。What is Jesus to his disciples? (verse 13)

-   「互いに足を洗い合わなければならない」と義務のように言われていますが、根拠は何ですか。What is the reason why the disciples should wash one another's feet?

-   「足を洗う」とは何を意味しているのでしょうか。What does 'wash one another's feet' mean?

-   「模範」とはどのような「模範」なのでしょうか。What kind of example Jesus showed to them?

-   「僕は主人にまさらず、遣わされた者は遣わした者にまさりはしない。」は何を伝えようとしているのでしょうか。What does 'no servant is greater than his master, nor is a messenger greater than the one who sent him' mean?

-   なぜ急に『わたしのパンを食べている者が、わたしに逆らった』を引用するのでしょうか。Why does Jesus quote 'He who shared my bread has turned against me.' suddenly?

-   19 節は何を言っているのでしょうか。What does verse 19 say?

-   イエスは足を洗うことを通して何を伝えたかったのでしょうか。What does Jesus want his disciples to understand?

### ヨハネによる福音書 John 13:21-30

-   13章1節から20節を復習しましょう。Review verses from 13:1 - 20.

-   イエスは21節でどのように言っていますか。What does Jesus say in verse 21?

-   弟子たちは、どのように反応しますか。How does his disciples respond?

-   シモン・ペトロはどうしますか。What does Simon Peter do?

-   イエスはどうしますか。How does Jesus respond?

-   「ユダがパン切れを受け取ると、サタンが彼の中に入った。」は何を伝えようとしているのでしょうか。What does ''As soon as Judas took the bread, Satan entered into him.'' mean?

-   「しようとしていることを、今すぐ、しなさい」は、何を意味しているのでしょうか。What does ''What you are about to do, do quickly.'' mean?

-   他の弟子たちは、このことを、どのように理解しますか。How do other disciples understand what Jesus said to Judas?

-   ユダはどうしますか。What does Judas do?

-   21節から30節で福音書記者はなにを伝えているのでしょうか。What does the writer of the gospel tell us by verses from 21 to 30?

### ヨハネによる福音書 John 13:31-38

-   「ユダが出て行くと」とありますが、ユダは何をしに出て行ったのでしょうか。What does Judas do after he goes out?

-   「人の子」と「神」について栄光を受ける、または与えることが書かれていますが、これらはどのような関係なのでしょうか。What is the relation between ''the Son of Man is glorified and God is glorified in him''?

-   イエスが去って行くことを、弟子たちにどのように伝えていますか。How does Jesus tell his disciples about his leaving them?

-   イエスは、ここでどのような掟を与えていますか。What commandment does Jesus give his disciples?

-   「互いに愛し合う」ことと「自分自身のように、隣人を愛すること」は同じでしょうか。Is there a difference between ''to love one another'' and ''to love your neighbor as yourself''?

-   「互いに愛し合う」ことと「イエスの弟子である」ことはなぜ関係しているのでしょうか。Why are 'to love one another'' and ''to be Jesus' disciple'' related? (verse 34)

-   ペトロは、どのような質問をイエスにしていますか。イエスはどう答えられますか。What does Peter ask Jesus? How does Jesus respond?

-   37 節のペトロの質問から、ペトロのどのような疑問と心情が想像されますか。What can you tell about Peter from his words in verse 37?

-   イエスは、ペトロに何を伝えていますか。What does Jesus tell Peter as his response?

-   イエスが、ペトロや弟子たちに求めたことは、何だったのでしょうか。What does Jesus want his diciples to do?

## ヨハネ 第14章

### ヨハネによる福音書 John 14:1-11

-   13章から背景を復習しましょう。Review the background from Chapter 13.

-   どのような状況に対して「心を騒がせるな。」と言っているのでしょうか。Why does Jesus say ''Do not let your hearts be troubled?'' What is the background?

-   「神を信じなさい。そして、わたしをも信じなさい。」とはどのような意味でしょうか。What does ''You believe in God; believe also in me'' mean? (verse 1)

-   イエスは「場所を用意しに行く」と言っていますが、それは、どのような場所なのでしょうか。What does Jesus mean by 'preparing a place'? (verses 2, 3)

-   イエスが「場所を用意しに行く」目的は何ですか。Why is Jesus going to prepare a place? (verse 3)

-   イエスは「わたしがどこへ行くのか、その道をあなたがたは知っている。」と言っていますが、これに対して、トマスは、どのように質問しますか。When Jesus tell his disciples ''You know the way to the place where I am going'', what does Thomas ask Jesus? (verses 4, 5)

-   イエスは「わたしがどこへ行くのか、その道をあなたがたは知っている。」と言っていますが、これに対して、トマスは、どのように質問しますか。When Jesus tells his disciples ''You know the way to the place where I am going'', what does Thomas ask Jesus? (verses 4, 5)

-   イエスは、どのように答えますか。How does Jesus reply Thomas? (verses 6, 7)

-   フィリポはどのような質問をしますか。What does Philip ask Jesus? (verse 8)

-   イエスは、どのように、答えますか。What is Jesus' answer? (verses 9 - 11)

-   「わたしが父の内におり、父がわたしの内におられることを信じる」とは、どのようなことでしょうか。What does Jesus mean by saying ''Believe that I am in the Father, and that the Father is in me''? (verses 10, 11)

### ヨハネによる福音書 John 14:12-21

-   14章1節から11節を復習しましょう。Review verses from 1 to 11 in John 14.

-   12節でイエスはどのような宣言をしていますか。What does Jesus tell his disciples in verse 12?

-   「イエスが行う業を行い、もっと大きな業を行うようになる」とはどのようなことを言っているのでしょうか。What do 'they will do the works I have been doing' and 'even greater things than these' mean?

-   イエスの名によって願うことはかなえられるとありますが、何でもかなえられるのでしょうか。Can we simply believe that 'Jesus will do whatever you ask in his name'? (verses 13, 14)

-   「わたしを愛しているならば、わたしの掟を守る。」は前後とどのように関係しているのでしょうか。How should we understand 'If you love me, keep my commands' in the context? (verse 15)

-   イエスは「別の弁護者（助け主）」を遣わしてくださるようにお願いしてくださるとありますが、この「弁護者（助け主）」について分かることをあげてみましょう。Jesus will ask the Father that he would give the disciples another advocate (helper). What can you tell about this advocate (helper)? (verses 16 and 17)

-   イエスは戻ってくると言っていますが、いつのことを言っているのでしょうか。Jesus tell his disciples ''you will see me''. When will it be?　(verses 18 and 19)

-   「わたしが生きているので、あなたがたも生きることになる。」とは何を伝えているのでしょうか。What does ''Because I live, you also will live.'' mean?

-   「かの日に」どのようなことが分かると言っていますか。What do Jesus' disciples realize on 'that day'? (verse 20)

-   「イエスを愛する人」はどのような人だと言っていますか。Who is the one who loves Jesus? (verse 21)

### ヨハネによる福音書 John 14:22-31

-   1節から21節を復習しましょう。Review verses from 1 to 21.

-   弟子の一人からどのような質問が出されますか。What does a disciple ask Jesus?

-   イエスはこの質問にどのように答えていますか。What is Jesus' answer?

-   「父とわたしとはその人のところに行き、一緒に住む。」とはどのようなことを言っているのでしょうか。What does 'we will come to them and make our home with them' mean?

-   「弁護者（助け手）」について書いてありますが、新たにどのようなことが書かれていますか。What is new about 'the advocate'?

-   イエスはさらに、何を残し、与えると言ってますか。What does Jesus leave and give his disciples?

-   イエスは、28節、29節で何を伝えていますか。What does Jesus tell his disciples?

-   「世の支配者が来る」とは何のことを言っているのでしょうか。What does 'the prince of this world is coming' mean?

-   最後にイエスはどのようなことを告げていますか。What does Jesus tell his disciples at the end?

-   このあと、どのようなことが書かれていますか。What is written after this?

## ヨハネ 第15章

### ヨハネによる福音書 John 15:1-11

-   いつ、どこで、だれに、話していますか。When, where and whom does Jesus tell this message?

-   「わたしはまことのぶどうの木」でイエスは何を伝えているのでしょうか。What does Jesus tell us by ''I am the true vine'' ?

-   農夫としての父の仕事はどのようなものですか。What does Father do as the gardener?

-   イエスの言葉によって、清くなっているとは、どういうことでしょうか。What does ''you are already clean by the word of Jesus" mean?

-   「イエスとつながっている」は何を意味していますか。What does ''Remain in Jesus" mean?

-   イエスから離れては「何も」できないのでしょうか。Cannot we do anything apart from Jesus?

-   「わたしにつながっていない」ひととはどのような人ですか。Who are those who do not remain in Jesus?

-   「つながり続けている」ひとについては、どのようなことが書かれていますか。What is written about those who reman in Jesus?

-   イエスの愛にとどまることは、どのようなことだとイエスは言っていますか。How does Jesus tell about ''to remain in Jesus' love''?

-   イエスはこれらのことを話した目的は何だと言っていますか。What is the reason Jesus tells this message to his disciples?

### ヨハネによる福音書 John 15:12-17

-   15章1節から11節を復習しましょう。Review verses from 1 to 11.

-   イエスの掟とはどのようなものですか。What is Jesus' command?

-   イエスの掟をまもることは、1節から11節のどのようなことと関係していますか。Which words in verses 1 to 11 are related to observe Jesus' command?

-   「友のために自分の命を捨てること」は何を意味しているのでしょうか。What does 'to lay down one's life for one's friends' mean?

-   イエスの友とはどのような人ですか。Who are Jesus' friends? (verses 14, 15)

-   「あなたがたがわたしを選んだのではない。わたしがあなたがたを選んだ。」とは何を伝えているのでしょうか。What does Jesus tell by 'You did not choose me, but I chose you'?

-   イエスは弟子たちを選んだ、任命した理由をどのように語っていますか。What is the reason Jesus appoints his disciples?

-   「実」とは何なのでしょうか。What is the fruit?

-   「わたしの名によって父に願うものは何でも与えられるように」とはどのようなことを言っていますか。What does 'whatever you ask in my name the Father will give you' mean?

-   なぜもう一度「互いに愛し合いなさい。」と繰り返しているのでしょうか。Why does Jesus repeat his command 'Love each other'?

### ヨハネによる福音書 John 15:18-27

-   15章1節から17節を復習しましょう。Review verses from 1 to 17.

-   世に憎まれたら、何を覚えなさいと行っていますか。What should his disciples keep in mind if the world hates them?

-   なぜ、世は憎むのですか。Why does the world hate Jesus' disciples?

-   「世に属していない」とはどのような意味でしょうか。What does 'they do not belong to the world' mean?

-   『僕は主人にまさりはしない』とはここではどのような意味ですか。What does 'A servant is not greater than his master.' mean in this context?

-   人々が「これらのこと（21節）」をする理由をどのように述べていますか。Why do the people treat Jesus' disciples 'this way'? (verse 21)

-   イエスはこの人たちについてどのように述べていますか。What does Jesus tell about these people? (verses 22-24)

-   25 節はどのような意味ですか。What does verse 25 mean?

-   「弁護者（助け主）」について新たにどのようなことが言われていますか。What does Jesus tell about the Advocate here?

-   最後にイエスは弟子たちについてどのようなことを述べていますか。What does Jesus tell about his disciples in verse 27?

## ヨハネ 第16章

### ヨハネによる福音書 John 16:1-15

-   「これらのことを話した」とありますが、それはどのようなことですか。What does it mean by 'all this' in verse 1?

-   躓（つまず）かせないためとありますが、躓くとはどのようなことでしょうか。What does falling away mean?

-   迫害するものが、自分は神に奉仕していると考える理由は何だと言っていますか。What does Jesus say about the reason they think they are offering a service to God, when anyone who kills the disciples?

-   4節に「思い出させるため」とありますが、何を思い出させるためなのでしょうか。What do the disciples remember when their time comes? (verse 4)

-   一緒にいるときと、いないときはどう違うのでしょうか。What is the difference whether Jesus is with them or not?

-   弟子たちはなぜ悲しいのでしょうか。Why are the disciples filled with grief?

-   イエスはなぜ去っていることが良いことだと言っていますか。Why is it good for them that Jesus is going away?

-   弁護者（助け手）が来ると、どのようなことが明らかにされますか。What does the Advocate prove them?

-   なぜ、弟子たちは、今は理解できないのでしょうか。Why don't the disciples understand?

-   弁護者（助け手）はどこからきて、誰から受けたことを、弟子たちに告げるのですか。Where does the Advocate, helper, come? From whom does it receive messages?

### ヨハネによる福音書 John 16:16-24

-   イエスはどのような話の中で16節のことばを語りますか。What was Jesus talking about when he said the message in verse 16?

-   弟子たちは、どのような疑問を持ちますか。What are the questions of his disciples?

-   「イエスは、彼らが尋ねたがっているのを知って」とありますが、なぜ弟子たちは、尋ねなかったのでしょうか。Why don't the disciples ask when 'Jesus saw that they wanted to ask him about this'?

-   20節前半の「あなたがたは泣いて悲嘆に暮れるが、世は喜ぶ。」は何を伝えているのでしょうか。What does 'you will weep and mourn while the world rejoices' in the first half of verse 20 mean?

-   20節後半の「あなたがたは悲しむが、その悲しみは喜びに変わる。」ことを21節ではどのような状態だと説明していますか。How does verse 21 explain 'You will grieve, but your grief will turn to joy' in the latter half of verse 20?

-   22節では「あなたがたは悲しむが、その悲しみは喜びに変わる。」ことをどのように説明していますか。How does verse 22 eplain 'You will grieve, but your grief will turn to joy'?

-   「その喜びをあなたがたから奪い去る者はいない。」とは何を伝えているのでしょうか。What does 'no one will take away your joy' mean?

-   「何も尋ねなくなること」「父に願うことは、父がお与えになること」と喜びはどのように関係しているのでしょうか。How does the joy relate to 'no longer ask me anything' or 'my Father will give you whatever you ask in my name'?

-   イエスが伝えている「あなたがたは喜びで満たされる」とは、どのようなことなのでしょうか。What does Jesus mean by 'your joy will be complete'?

-   弟子たちの疑問は、解けたのでしょうか。Were the questions of the disciples resolved?

### ヨハネによる福音書 John 16:25-33

-   イエスはこれまで何を伝え、弟子たちはどんな疑問を持っていましたか。What does Jesus tell his disciples? What are the questions of them?

-   「たとえを用いて話してきた」と言ってますが、それは、どんなことを伝えているのでしょうか。What does Jesus mean by 'speaking figuratively'?

-   「イエスの名によって願う」とはどのようなことを意味していますか。What does 'asking in Jesus' name' mean?

-   なぜ「イエスの名によって」願うことになると言っているのですか。Why do the disciples ask in Jesus' name?

-   イエスは、28節でどのようなことを伝えていますか。What does Jesus say in verse 28?

-   弟子たちは、なんと応答しますか。What do his disciples respond? (verses 29, 30)

-   「あなたが何でもご存じで、だれもお尋ねする必要のないこと」とはどのようなことを言っているのでしょうか。What do his disciples mean by saying 'you know all things and that you do not even need to have anyone ask you questions' ?

-   31 節のイエスのことばから、あなたは、何を受け取りますか。What can you tell by Jesus' words in verse 31?

-   32節の「あなた方が散らされて自分の家に帰ってしまう」ことは、具体的にどのようなことを意味しているのでしょうか。What does the time 'you will be scattered, each to your own home' actually mean?

-   イエスは、最後のことばで、弟子たちにどのようなメッセージを送っているのでしょうか。What is the last message of Jesus to his disciples in verse 33?

## ヨハネ 第17章

### ヨハネによる福音書 John 17:1-8

-   「イエスはこれらのことを話してから」（v1）とありますが、いつ、どのような場で、だれに対して、どんなことを話しましたか。 We read in verse 1, 'After Jesus said this'. When, where, to whom and what did Jesus tell?

-   イエスは「時が来ました」と言っていますが、それはどのような時なのでしょうか。What does 'the hour has come' mean?

-   「栄光を現す」とか「栄光を与える」とは何を言っているのでしょうか。What does 'glorify your son' or 'glorify you' mean?

-   2節に「すべての人を支配する権能」とありますが、このことと「永遠の命を与える」ことはどのような関係にあるのでしょうか。What is the relation between 'the authority over all people' and 'to give eternal life' in verse 2?

-   3節に「永遠の命」の定義がありますが「命」が「知ること」とはどういうことでしょうか。In verse 3, eternal life is defined 'to know'. What does it mean?

-   4節に「業を成し遂げた」とありますが、どのような業を成し遂げたのでしょうか。What is the work Jesus is finishing \[or has accomplished\] on earth? (verse 4)

-   「世界が造られる前に持っていた栄光を与えてください」とはどういうことでしょうか。What does Jesus ask for Father in verse 5? 'The glory Jesus had with Father before the world began?'

-   「世から選び出してわたしに与えてくださった人々」とは誰のことですか。Who are 'those who Father gave Jesus out of the world'?

-   この人たちは、どのようなことを知り、どのようなことを信じていますか。What do these people know and what do they believe?

-   イエスが父から受けるといっている栄光と、このひとたちが、御言葉を守り、イエスについて、イエスを遣わした方について知っていることは、関係しているのでしょうか。Is the glory Jesus receives related to these people written in verses 6 to 8?%Does the glory Jesus receives from Father have something to do with these people?

### ヨハネによる福音書 John 17:9-19

-   1節から8節を復習しましょう。9節の「彼ら」「わたし」「あなた」とはそれぞれ誰のことですか。Review verses from 1 to 8. Who are 'them', 'I' and 'you' in verse 9.

-   「彼ら」はだれに属する存在だと言っていますか。To whom do 'they' belong to?

-   「彼らによって栄光を受けた」とありますが、それはどういうことでしょうか。What does it mean that 'glory has come to me through them'?

-   彼らが一つになるとは何を意味しているのでしょうか。What does 'they may be one' mean?

-   彼らを守ったと言っていますが、誰から守ったのでしょうか。From whom Jesus protected them?

-   イエスの喜びが満ちあふれるとは何を言っているのでしょうか。What does it mean that the full measure of my joy within them?

-   彼らと世とはどのような関係ですか。What is the relationship between 'them" and 'the world'?

-   「聖なるものとする」「世に遣わす」はそれぞれ何を意味していますか。What does 'sanctify' and 'send' mean in verses 17 and 18?

-   19節は何を意味しているのでしょうか。What does verse 19 mean?

-   イエスが、彼らについて、願っていることは、何ですか。What does Jesus pray for them?

### ヨハネによる福音書 John 17:20-26

-   イエスはこんどはだれのためにお願いしていますか。For whom does Jesus pray?

-   「一つにしてください」とはどのような意味で「ひとつ」なのでしょうか。What does it mean that 'they may be one'?

-   なぜ、世は、神様がイエスを遣わしたことを信じるようになるのですか。Why do the world believe that Father sent Jesus?

-   「あなたがくださった栄光」とは何ですか。What is the glory that Father gave Jesus?

-   23節は何を言っていますか。21節の繰り返しですか。What does verse 23 mean? Is it same as the verse 21?

-   24節ではこんどはイエスは何を祈っていますか。What does Jesus pray for them in verse 24?

-   25節の「この人々」はだれのことですか。Who are 'they' in verse 25?

-   26節の「御名を彼ら知らせました」とはどのような意味ですか。What does 'I have made you known to them' mean in verse 26?

-   イエスが祈っているのはどのようなことですか。What does Jesus pray for them?

-   あなたは、17章のイエスの祈りから、なにを学びましたか。What do you learn from Jesus' prayer in Chapter 17?

## ヨハネ 第18章

### ヨハネによる福音書 John 18:1-11

-   イエスと弟子たちは、どこから、どこへ向かいますか。その場所については、どのようなことが分かりますか。Where do Jesus and his disciples go? What do you know about the place they go to?

-   どのような人たちがどのようにして現れますか。どのようなことが分かりますか。Who appear? What do you tell from verse 3?

-   他の福音書の記述と比較してみましょう。Compare with the descriptions in other Gospels?

-   イエスはどのようにこの人たちを迎えますか。（4節）How does Jesus respond when they come? (verse 4)

-   4節から6節のイエスと彼らの会話のあとどのようなことが起こりますか。What happens after the conversation between Jesus and them in verses four to six?

-   イエスはここでどのような要求をしますか。（8節）What does Jesus request them? (v.9)

-   9節からヨハネは何を伝えようとしているのでしょうか。What does John tell us in verse 9?

-   このとき、シモン・ペトロはどうしますか。What does Peter do then?

-   イエスは、ペトロにどのように言いますか。What does Jesus tell Peter?

-   ヨハネが、他の福音書の記述を知っているとすると、ここで何を伝えようとしているのでしょうか。Suppose John knows other Gospels. What does John tell us in this story?

### ヨハネによる福音書 John 18:12 - 27 (1)

-   イエスが捕らえられる時の状況を復習しましょう。Review how Jesus is arrested.

-   誰のところへ連れて行かれますか。Where do they bring Jesus?

-   誰がついて行きますか。Who follow the arrested Jesus?

-   イエスの裁判はだれのもとで行われますか。（18,19章）Who questions Jesus in the court? (Chapters 18 and 19)

-   他の福音書では裁判をどのように書いていますか。What do other Gospels tell us about the trial of Jesus?

-   大祭司はイエスに何を尋問しますか。What does the high priest ask Jesus?

-   イエスはどのように答えますか。How does Jesus respond him?

-   なぜイエスはこのように答えるのでしょうか。Why does Jesus respond in this way?

-   どのようなことが起きますか。（22,23節）How do the people respond? (verse 22, 23)

-   イエスは誰の元に送られますか。To whom do they send Jesus?

### ヨハネによる福音書 John 18:12 - 27 (2)

-   背景となっている、イエスが捕らえられたあとの箇所を確認しましょう。Review the background after the arrest of Jesus. （vs. 12-14, 19-24）

-   ペトロの離反の予告の箇所を復習しましょう。Review what Jesus said about Peter's denial. (13:36-38)

-   ペトロはどのようにして門の中に入りますか。How does Peter enter the gate?

-   だれがペトロになんと聞きますか。Who ask Peter and what?

-   ペトロはなんと答えますか。How does Peter respond?

-   このあとペトロはどうしますか。What does Peter do after his first denial?

-   他の福音書と比較してみましょう。Compare with other Gospels.

-   今度は、だれがペトロに聞き、ペトロはどのように答えますか。Who ask Peter and how does he respond?

-   三度目に、だれがどのように証言し、それにペトロはどのように答えますか。Who testify then and what? How does Peter respond?

-   この箇所を通してヨハネは何を伝えているのでしょうか。What does John tell us from this story?

### ヨハネによる福音書 John 18:28-40

-   人々はイエスをどこから、誰の元へ連れて行きますか。Where do the Jewish leaders take Jesus?

-   人々と、ピラトとの間には、どのような会話がありますか。What do the Jewish leaders and Pilate discuss?

-   なぜ、自分たちで死刑にしないのですか。Why do they not execute Jesus?

-   ピラトはイエスにどのような質問をしますか。（33節）What does Pilate ask Jesus?

-   イエスはどのように応答しますか。（34節）How does Jesus respond?

-   このあと（35-38節）、ピラトと、イエスの間には、どのような会話がありますか。What do they talk after this? (vs 35-38)

-   39, 40節を見てみましょう。人々の望んでいることは何なのでしょうか。What do these people want? (verses 39, 40)

-   ピラトはどう考え、判断しているでしょうか。そして、何を望んでいるのでしょうか。What does Pilate think of Jesus? What does he want?

-   イエスは、ピラトに何を伝えていますか。What does Jesus tell Pilate?

-   ヨハネは、何を伝えようとしているのでしょうか。What does John tell us?

## ヨハネ 第19章

### ヨハネによる福音書 John 19:1-16

-   総督ピラトの官邸での様子を復習しましょう。Review Jesus at the palace of the Roman governor Pilate in 18:28-40.

-   ピラトはイエスをどうしますか。What does Pilate do to Jesus? (verses 1 - 3)

-   他の福音書ではどのように書かれていますか。How do the other gospels describe the scene?

-   ピラトは、なぜイエスをユダヤ人の前に引き出すのでしょうか。Why does Pilate bring Jesus in front of the Jews?

-   ピラトは「神の子と自称した」と聞いてどうしますか。When the Jews say that Jesus claims to be the Son of God, what does Pilate do?

-   イエスはピラトの権限についてどのように言っていますか。What does Jesus talk about the power of Pilate.

-   ピラトはなぜ釈放しようとしたのでしょうか。Why does Pilate try to release Jesus?

-   これに対してユダヤ人たちはどうしますか。What do the Jews respond to it?

-   ピラトはどのような判決をくだしますか。What verdict does Pilate give Jesus?

-   ヨハネは、十字架刑の判決を通して、何を伝えているのでしょうか。What does John tell us through this verdict?

### ヨハネによる福音書 John 19:17 - 24

-   16節までのいきさつを確認しましょう。Review 19:1-16.

-   刑場までのことはどのように書かれていますか。What does John describe Jesus on the way to Golgotha?

-   他の福音書の記述を確認しましょう。Compare John with the other Gospels.

-   イエスはどのようにして十字架につけられますか。How do they crucify Jesus? (vs17-19)

-   罪状書にはどのように書かれていますか。What is written on the sign?

-   罪状書の文言に関してユダヤ人たちとピラトのどのようなことが記録されていますか。What do the Jews request and how does Pilate respond to it?

-   イエスの衣服はどのようにされますか。How do they do with Jesus' garments?

-   衣服のことはどのような聖書の言葉の実現だとしていますか。Which verse of the Bible is fulfilled by the incident on Jesus' garments?

-   ヨハネは、この箇所を通して何を伝えているのでしょうか。What does John tell us?

### ヨハネによる福音書 John 19:25-30

-   17節から24節を復習しましょう。Review 19:17-24.

-   イエスの十字架のそばには、どのような人たちがいますか。Who are there near the cross of Jesus?

-   他の福音書の記述を確認しましょう。Compare John with the other Gospels.

-   四人の女性たちはどのような人たちですか。What do you tell about these four women?

-   イエスは弟子にどのように伝えますか。What does Jesus tell his disciple?

-   28節に「成し遂げられた」とありますが、何のことを言っているのでしょうか。What had been finished? (v. 28)

-「渇く」と言われますが、何に渇いているのでしょうか。What is Jesus thirsty for?

-   人々はどうしますか。What do they do to Jesus? (v29)

-   イエスの最後をヨハネはどのように描いていますか。How does John describe Jesus' last?

-   ヨハネは十字架でのイエスの死について何を伝えているのでしょうか。What does John tell us about Jesus' death on the cross?

### ヨハネによる福音書 John 19:31-37

-   17節から30節までを復習しましょう。Reivew 19:17-30.

-   イエスが十字架にかけられた日はどのような日でしたか。What can you tell about the day Jesus is crucified?

-   ユダヤ人たちは何をピラトに願いますか。それはなぜですか。What do the Jews ask Pilate? Why?

-   兵士たちはどうしますか。What do the soldiers do to them?

-   そのときのイエスの状態についてはどのようなことが分かりますか。What do you tell about Jesus' body?

-   イエスの死因は何だったのでしょうか。What is the cause of death of Jesus?

-   35節には証言者についてどのように書かれていますか。What can you read about the one testifies it in verse 35?

-   骨が砕かれないことはどのような意味を持っているのでしょうか。What is the significance of ''Not one of his bones will be broken''?

-   37節はどのような意味でしょうか。What does the verse 37 mean?

-   ヨハネはイエスの死についてなにを伝えているのでしょうか。What does John tell us about the death of Jesus?

### ヨハネによる福音書 John 19:38 - 42

-   19章17節から37節を復習しましょう。Review 19:17 - 37.

-   まずだれがイエスの遺体を取り降ろすことを願い出ますか。Who asked Pilate for the body of Jesus?

-   なぜ、この人が、ピラトに願い出ることができたのでしょうか。Why could he dare to ask Pilate?

-   ヨハネはなぜわざわざこの人にとって不名誉なことを書いたのでしょうか。Why did John introduce this person in this way?

-   他に、だれがイエスの遺体の引き取り、埋葬に加わりますか。Who else joined to take Jesus' body and bury it?

-   埋葬についてわかることをあげてみましょう。How did they bury Jesus' body?

-   他の福音書にはどのように書かれていますか。Compare with other gospels.\\marginpar{Mt 27:57-61, Mk 15:42-47, Lk 23:50-56

-   ヨハネは、何を伝えているのでしょうか。What does John tell us about Jesus' burial?

## ヨハネ 第20章

### ヨハネによる福音書 John 20:1-10

-   イエスの埋葬について復習しましょう。Review the burial of Jesus' body. (John 19:38-42)

-   いつ、誰が、どこへ行き、何を発見しますか。Who went to the tomb? When was it? What was the discovery?

-   マグダラのマリアはどのような人ですか。Who is Mary Magdalene?

-   この人は、誰に、どのように報告しますか。Who did she tell?

-   報告を聞いたひとたちはどうしますか。What did they do when they heard the news?

-   墓の中はどのような状態でしたか。Describe the place where Jesus' body was laid.

-   8節に「もう一人の弟子も見て信じた」とありますが、何を信じたのでしょうか。What did he see and believe? (verse 8)

-   9節は何を伝えているのでしょうか。What does verse 9 tell?

-   他の福音書と比較してみましょう。Compare with other gospels.

-   ヨハネは何を伝えているのでしょうか。What does John tell us from this?

### ヨハネによる福音書 John 20:11-18

-   1節から10節を復習しましょう。Review verses 1 to 10.

-   マリアはどこで、何をしていて、何を発見しますか。Where is Mary? What is she doing? What does she find?

-   天使たちは、マリアにどのように話しかけますか。マリアはどのように答えますか。What do the angels ask Mary? How does she answer?

-   なぜ気づかなかったのでしょう。Why didn't she recognize Jesus? (verse 14)

-   イエスは何と語りかけ、マリアはどのように応答しますか。How does Jesus talk to Mary? How does Mary respond to him? (verses 15, 16)

-   イエスはマリアにどのようなことを伝えますか。What does Jesus tell Mary? (verse 17)

-   なぜ、イエスは「すがりついてはいけません。」とマリアに命じるのでしょうか。Why does Jesus tell Mary 'Do not cling to me'?

-   マリアに託した伝言は何を伝えているのでしょうか。What is Jesus' message entrusted to Mary?

-   それから、マリアはどうしますか。What does Mary do?

-   ヨハネはこの場面から何を伝えているのでしょうか。What does John tell us from this scene?

### ヨハネによる福音書 John 20:19-23

-   1節から18節を復習しましょう。Review verses 1 to 18.

-   イエスは、いつ、弟子たちに現れますか。When does Jesus appear to his disciples?

-   弟子たちは、なぜ、ユダヤ人を恐れているのですか。Why do they fear the Jews?

-   イエスは、どのように、現れますか。How does Jesus appear to his disciples?

-   イエスはなぜ、手と、わき腹を見せるのでしょう。弟子たちは、どのような反応をしますか。Why does Jesus show his hands and side. How do they respond?

-   イエスは、まず、何を、弟子たちに告げますか。What does Jesus tell his disciples first?

-   父なる神がイエスを遣わした目的は何ですか。What is the purpose Father sent Jesus?

-   イエスは、次に、どのように、何を告げますか。What does Jesus tell his disciples next?

-   弟子たちは罪を裁く権威が与えられたと言うことでしょうか。Do they receive authority to judge sins?

-   ヨハネは、この箇所で、何を証言しているのでしょうか。What does John testify through this scene?

### ヨハネによる福音書 John 20:24 - 29

-   19節から23節を復習しましょう。どんなことがありましたか。Review verses from 19 to 23. What happened?

-   弟子たちは、どのように、トマスに告げ、トマスは、どのように応えますか。What do the disciples tell Thomas? How does he respond?

-   トマスはどのような人ですか。What do you know about Thomas?

-   いつ、どのような時に、イエスはどのように、現れますか。When and how does Jesus appear to his disciples?

-   イエスはトマスにどのように言いますか。What does Jesus tell Thomas?

-   トマスはどう応答しますか。How does Thomas respond?

-   イエスは、さらに、どのように伝えますか。What does Jesus further tell Thomas?

-   ヨハネは何を伝えようとしているのでしょうか。What does John tell the reader?

### ヨハネによる福音書 John 20:30 - 31

-   21章を読んでみましょう。20章までと書き方に変化がありますか。Read Chapter 21. Any differences with Chapters 1 - 20 in writing?

-   21章は付録でしょうか。Is Chapter 21 an appendix?

-   なぜ「この書物には書いてない」などということを書いたのでしょう。Why does John write that Jesus performed many other signs?

-   「しるし」とは何でしょうか。What are signs?

-   なぜ、すべて書かないのでしょうか。Why he does not write everything?

-   この書が書かれた目的は何ですか。What is the purpose of this book?

-   「イエスは神の子メシアであると信じる」とはどのようなことでしょうか。

-   「いのちを受ける」とは、どのようなこととして、ヨハネは伝えているのでしょうか。

-   本書の目的は達成されていますか。Is the purpose of this book achieved?

## ヨハネ 第21章

### ヨハネによる福音書 John 21:1 - 14

-   20章には、どのようなことが記録されていますか。What is written in Chapter 20?

-   いつ、どこで、なにが起こりますか。What happened? Where and When?

-   だれが、その場にいますか。Who are there?

-   彼らは、なぜ、漁に行くのでしょう。Why do they go fishing?

-   イエスはどのように彼らに現れ、どのように話しかけますか。How does Jesus appear himself to his disciples? What does he talk to them?

-   ペトロは「主だ」と聞くと、どうしますか。それは、なぜでしょう。When Peter heard ''It is the Lord'' how does he respond?

-   他の弟子たちは、どうしますか。What do other disciples do?

-   イエスは、どのような指示を弟子たちにあたえますか。What does Jesus tell his disciples?

-   何が伝えられているのでしょうか。What does the writer want to tell us?

-   この部分があとから加えられたとしたら、それは、なぜでしょうか。Why do you think this story becomes a part of the gospel?

### ヨハネによる福音書 John 21:15-19

-   1節から14節を復習しましょう。どのような時にイエスはシモン・ペトロに話しかけますか。Review verses 1 - 14. When does Jesus talk to Simon Peter?

-   ヨハネによる福音書には\\marginpar{1;40-42, 6:66-69, 13:6-11, 24, 36-38, 18:10, 11, 15-18, 25-27, 20:1-10, 21:2, 3, 7, 11、ペトロについてどのように書かれていましたか。What is written about Peter in John?

-   まずイエスはどのようにシモン・ペトロに言い、ペトロはどのように答えますか。What does Jesus talk to Simon Peter and how does he respond?

-   イエスは二度目、三度目にペトロに話しますが、イエスの言葉に何か変化がありますか。Jesus talks to Peter two more times. Any changes?

-   ペトロの答えに何か変化がありますか。Any changes in Peter's response?

-   ペトロの否認とは関係していますか。関係しているとすると、それはどのようなことでしょうか。Is it related to Peter's denial?　If so, how?

-   このあと、イエスは、ペトロに何を告げますか。What does Jesus tell Peter next?

-   イエスがペトロに伝えたかったことは何でしょうか。What does Jesus want to tell Peter?

%- ペトロだけへのメッセージでしょうか。Is this a special message to Peter?

-   この記事が伝えていることは、何ですか。What is the message?

### ヨハネによる福音書 John 21:20-25

-   21章の最初から復習しましょう。Review Chapter 21:1-19.

-   ペトロは、だれが、どのようにしていることを発見しますか。What does Peter see?

-   ペトロは、何と、イエスに質問しますか。それは、なぜでしょう。What does Peter ask Jesus? Why?

-   ペトロは「イエスが愛された弟子」についてどう考えていたのでしょうか。What do you think is the disciple Jesus loved to Peter?

-   イエスはどのように答えますか。What is Jesus' response?

-   イエスが伝えたかったことはなんですか。What does Jesus want to tell Peter?

-   23節からどのようなことがわかりますか。What does verse 23 tell us?

-   著者についてどのように書かれていますか。Who is the author of this gospel?

-   ヨハネによる福音書は、最後、どのようなメッセージで終わっていますか。What is the ending message of the gospel?

-   「イエスの愛しておられた弟子」の使命は何だったのでしょうか。What is the mission of the disciple whom Jesus loved?

### ヨハネによる福音書 John 1:1 - 18

-   21章20 - 25節 には著者についてどのように書かれていますか。What do you tell about the author from 21:20 - 25?

-   20章30, 31節には、この書の目的についてどのように書かれていますか。What do you tell about the the purpose of this book in 20:30,31?

-   ヨハネによる福音書に登場する主要人物をあげてみましょう。List main figures in John's gospel.

-   ヨハネによる福音書はどのようにはじまりますか。How does John's gospel begin?

-   「言（ことば）」についてどのように書かれていますか。List what is written about the Word.

-   「言葉」と「命」と「光」についてどのように書かれていますか。List what is written about the word, the life and the light.

-   ヨハネの役割は何ですか。What is the roll of John?

-   「わたしたち」は何を証言していますか。What do 'we' testify?

-   冒頭部分は何を伝えているのでしょうか。What is the message of 'the beginning'?

-   この福音書からあなたは何を学びましたか。What did you learn from John's gospel?
