# ルカ（2005-2008） {#lukedq-ole}

質問票：ディスカッション・クエスチョン（[PDF](https://icu-hsuzuki.github.io/science/bible/bs/luke2005.pdf)）

## ルカによる福音書を学んで行くにあたって {.unnumbered}

ルカによる福音書は、パウロの伝道旅行に伴って行った医者ルカ（コロサイ4:14）によると言われている。４福音書の著者の中で唯一の異邦人（非ユダヤ人）。２世紀の伝承では、シリアのアンティオケの生まれだと言われている。ルカについては、上記の箇所以外聖書には2度現れる。ピレモン２４, II テモテ４：１１

-   テキストから何が分かるかを中心に学びましょう。

共観福音書 (synoptic)[^lukedq-old-1] の他の箇所は時に応じて参考にしていきましょう。

[^lukedq-old-1]: マタイ、ルカ、ルカの三つの福音書のこと。この三巻は同じできごとについて扱っている部分（並行記事）が多く、「共通の観点を持つ福音書」としてこう呼ばれます。

-   著者が何を伝えたいと思っているかを中心に学びましょう。

## ルカによる福音書　第1章

### 1節 - 4節

1.  ルカはこの福音書に書かれている情報をどのように調べていますか。

2.  どのような目的でこの書は書かれていますか。

### 5節 - 25節

1.  時代を特定するどのような情報が書かれていますか。

2.  5-13 節に書かれていることから、ゼカリヤとエリザベツについてどんなことがわかりますか。あげてみましょう。

3.  生まれる子供についてどのような予告をしていますか。

4.  ゼカリヤはどのように考えどのように応答しますか。

5.  なぜ信じることが難しいのでしょうか。

### 26節 - 38節

1.  マリヤはどのような人物ですか。

2.  マリヤは御使いが彼女に現れたことをごく自然に受け止めていますが、何故だと思いますか。

3.  ガブリエルは何を告げ、それにマリヤはどのような反応を示していますか。

4.  マリヤに生まれる子に対してどんな事がわかりますか。

5.  なぜマリヤがこのような重要なことのために選ばれたと思いますか。

6.  マリヤはこの知らせをどのように受け止めようとしますか。

7.  処女であるマリヤの胎に宿る実は、どのようにして宿る胎児だと言われていますか。このことから、マリヤから生まれたイエスがどのような方であることがわかりますか。

8.  マリヤはこの知らせをどう受け入れますか。このような彼女の信仰について、あなたは、どのように思いますか。

### 39節 - 56節

1.  エリザベツはどのようにマリヤを祝福しますか。

2.  マリヤは￥どう応答しますか。気づいたことをあげてみましょう。

### 57節 - 80節

1.  ザカリヤとエリザベツの子にヨハネと名をつけた経緯を考えてみましょう。

2.  ガブリエルの告知とザカリヤの預言からヨハネについてどのようなことがわかりますか。

## ルカによる福音書　第2章

### 1節 - 7節

1.  マリヤとヨセフはどこへ向かい、マリヤはどこで出産しますか。

### 8節 - 20節

1.  御使いは、羊飼に、どのようなことを告げますか。

2.  羊飼は、どのような行動をしますか。

3.  なぜ羊飼に告げられたのでしょうか。

### 21節 - 39節

1.  8日が過ぎてから、マリヤとヨセフはどうしますか。

2.  シメオンはどのような人ですか。

3.  シメオンはイエスについてどのようなことを預言しますか。

4.  アンナはどのような人で何をしますか。

### 40節 - 52節

1.  イエスの成長のようすはどのように描かれていますか。（v.40, v.52)

2.  イエスが12歳のときのエルサレム上京のとき、何が起きますか。

3.  両親はそれにどのように応答しますか。

### 2章まとめ

1.  この章に描かれている、イエスの誕生と成長からあなたはどのようなことを感じ、思いますか。普通の人間の誕生と成長と変わらないこと、異なることをあげて考えてみましょう。

2.  「心に留め」という表現が 19節と51節にありますが、マリヤはこれらのできごとからどのようなことを考えていたでしょうか。

## ルカによる福音書　第3章

### 1節 - 14節

1.  ヨハネの宣教開始の時期をルカはどのように記していますか。

2.  預言者イザヤの言葉から考えると、ヨハネの役割はどのようなものでしょうか。

3.  ヨハネはどのような警告を群衆に与えますか。その目的は何でしょうか。

4.  ヨハネのメッセージからすると神が望んでおられることはどういうことでしょうか。

5.  どのような人たちがヨハネのメッセージに応答し、ヨハネはその人たちにどのような勧めをしますか。

6.  あなたには、ヨハネはどのようなことを勧めると思いますか。

### 15節 - 22節

1.  ヨハネの宣教は、民衆の間にどのような問いを引き起こさせ、それに、ヨハネはどのように答えますか。ヨハネの答えによると「あとから来る方」とヨハネは何が違うのでしょうか。

2.  ヨハネは投獄されますが、それは、どのような理由によりますか。

3.  イエスもバプテスマを受けますが、そのとき、どのようなことが起こりますか。

### 23節 - 38節

1.  なぜ、系図が挿入され、それも誕生のときではなく、ここに納められているのでしょうか。

## ルカによる福音書　第4章

### 1節 - 13節

1.  イエスは悪魔（サタン）の試みを受けたとありますが、どのような誘惑だったでしょうか。

2.  これら一つ一つは、悪魔ができることなのでしょうか。イエスができることなのでしょうか。

3.  なぜイエスは試みを受けたのでしょう。その必要性と意味について考えてみましょう。

### 14節 - 30節

1.  御霊の力に満ちあふれて（帯びて）とは、どういう状態を言っているのでしょうか。

2.  イザヤ書 (61:1-2)を朗読しますが、ここでの「わたし」はどのような人でどのようなことをしますか。

3.  あなたが想像する「主のめぐみの年」とはどのような年でしょう。

4.  イエスは、自分の説教を聞いた人に対して、どのように対応しますか。

5.  なぜイエスの説教を聞いた人たちは感嘆から憤りへと変わったのでしょう。

### 31節 - 37節

1.  カペナウムの会堂で、汚れた悪霊につかれた人にどんなことが起こりますか。

2.  32, 36節に「驚き」が書かれていますが、どのような驚きでしょうか。現代に場所を変えてみるとそれはどのような驚きだと表現できますか。

### 38節 - 39節

1.  シモンのしゅうとをいやすのに「熱がひくように命じて」いますが、それはどういうことを表現しているのでしょう。

### 40節 - 41節

1.  悪霊はイエスが「神の子」「キリスト（メシヤ）」だと知っていたと書いてありますが、この証言は何を意味するのでしょう。

### 42節 - 44節

1.  イエスと共にいることを願う群衆からどんなことがわかりますか。

2.  「他の町々にも」とはどういうことでしょうか。

## ルカによる福音書　第5章

### 1節 - 11節

1.  1〜7節を読んで、気づいたことをあげてみましょう。

2.  なぜシモンは8節のような言葉を発したのだと思いますか。5節の時と変化がありますか。

3.  10節の言葉でイエスは何を伝えようとしているのでしょうか。また、4人はそれをどのように受けとったと思いますか。

### 12節 - 16節

1.  らい病（重い皮膚病）の人はどのようにして、どのような言葉でイエスに願いましたか。

2.  イエスはこの人にどのように対応しますか。

3.  イエスはいやされた人にどのように命じていますか。それはなぜだと思いますか。

4.  16節には、イエスが集まってきた群衆からはなれて、さびしいところに退いて祈っていたとありますが、それは何故でしょうか。

### 17節 - 26節

1.  パリサイ人や律法学者は何のために来ていると思いますか。

2.  そこでどんなことが起こりますか。

3.  罪はゆるされたというのと、起きて歩けというのとどちらが簡単なのでしょうか。（23節）

4.  そこにいた人にとって26節にある「驚くべきこと」は何だったのでしょう。

### 27節 - 32節

1.  レビはどのような人ですか。またイエスの招きに対してどうしますか。

2.  レビがイエスのためにしたことは何ですか。

3.  現代においてあなたがレビのように招かれたらあなたはどうしますか。イエスは何を望んでいるでしょうか。

4.  31, 32節の言葉で、イエスは何を私たちに語っているのでしょうか。あなたの隣人は健康な人ですか、病気の人ですか。

### 33節 - 39節

1.  断食についてイエスはどのように答えていますか。

2.  新しいぶどう酒は新しい皮袋に入れるとはここでは何を意味しているのでしょうか。

## ルカによる福音書　第6章

### 1節 - 5節

1.  弟子たちは、どこで、なにをしましたか。

2.  パリサイ人は、なぜ弟子たちをとがめたのでしょう。

3.  それに対してイエスは何と答えていますか。

### 6節 - 11節

1.  この事件はどこで起きますか。イエスのまわりには、どんな人たちがいますか。

2.  8節のイエスの言葉は、イエスのどのような心をあらわしていますか。

3.  パリサイ人は、どうしてイエスに対して分別を失うほど怒っているのでしょう。

### 12節 - 16節

1.  イエスが選んだ12人は、どのような人たちでしたか。

2.  イエスは、どのようにして彼らを選びましたか。

### 17節 - 19節

1.  山からおりたイエスを、どんな人たちが 待っていましたか。

2.  彼らの目的は何ですか。

### 20節 - 26節

1.  イエスは、どんな人が幸いだと言っていますか。

2.  どんな人が、哀れ（不幸）だと言っていますか。

### 27節 - 36節

1.  イエスは人々にどのような勧めをしてますか。

2.  イエスの勧めのように生きるとどうなると言っていますか。

### 37節 - 42節

1.  イエスはどんな２つのことを戒めていますか。また、どんな２つのことをするように教えていますか。（37, 38節）

2.  そうすると、どんなことがおきると言っていますか。

3.  イエスは39〜42節のたとえ話では、指導者（批判者）のどんな３つの例をあげていますか。それは、どんなことを教えていると思いますか

### 43節 - 45節

1.  木と実、心の倉、人の口のたとえから、人と人から出てくる感化について、どんなことがわかりますか。

### 46節 - 49節

1.  また、家と土台のたとえから、私たちは何をもとめられていると思いますか。

## ルカによる福音書　第7章

### 1節 - 10節

1.  百人隊長は、どのような人だと思いますか。（社会的、人間的、宗教的に）

2.  百人隊長は、どのような問題をもっていますか。そして、それをどのように解決しようとしていますか。

3.  百人隊長は，イエスに対して、何を信じていたと思いますか。

4.  イエスはこの百人隊長の何を賞賛したのでしょうか。

### 11節-17節

1.  イエスの一行は、どこで、だれと出会いますか。（12節）

2.  この母親の心の内は、どのようなものだったでしょうか。

3.  イエスは、この母親をどのよう思われたでしょうか。また、この母親に対してどうされますか。

4.  あなたは、このようなイエスをどう思いますか。

### 18節 - 35節

1.  バプテスマのヨハネはどのような人ですか。(3:19-20)

2.  イエスはどのようなことから判断するように言っていますか。

3.  神の国で最も小さい者でも、バプテスマのヨハネより偉大だとはどういうことでしょうか。

4.  31節からのたとえからイエスは何を言おうとしているのでしょうか。

### 36節 - 50節

1.  どこで何が起こりますか。

2.  イエスを招いたファリサイ派の人はどのように思ったでしょう。

3.  イエスは、誰に向かってどのようなたとえを話しますか。

4.  あなたは 47節のイエスの言葉をどう思いますか。

5.  50節でイエスは「あなたの信仰があなたを救った」と言っていますが、この女の信仰とはどのようなものですか。

## ルカによる福音書　第8章

### 1節 - 3節

1.  イエスと共に宣教の旅をしていた人たちにはどのような人たちがいますか。

### 4節 - 18節

1.  種がまかれた４種類の土地について書かれていますが、これらの土地の特徴、そしてその種がどうなったかについてまとめてみましょう。どうしてそのような結果になったのでしょうか。

2.  この種はみことばだと書かれていますが、みことばに対するそれぞれの土地・聞き手の受け入れ方についてまとめてみましょう。

3.  道ばた：

4.  岩の上（石地）：

5.  いばらの中：

6.  良い地：

7.  この種まきのたとえを通してイエスは何を教えようとしておられるのでしょうか。

8.  「ともし火」のたとえで、「ともし火」「燭台」「秘められたもの」とは何でしょうか。イエスは何を教えようとしておられるのでしょうか。

9.  11節からのたとえの解き明かしは弟子達向けに語られたようですが、なぜ、群衆にはたとえで語られ、弟子達には解き明かしをされるのでしょうか。

### 19節 - 21節

1.  イエスはなぜ 21節のような応答をされたのでしょうか。（マルコ 3:21 参照）

### 22節 - 25節

1.  この出来事の起こった状況について分かることをあげてみましょう。

2.  弟子達は何に「恐れ驚いた」のでしょう。

### 26節 - 39節

1.  悪霊に取りつかれている人は、どのような状態でしたか。

2.  この人（悪霊？）は、イエスに対してどのような反応を示していますか。

3.  イエスは、どうされましたか。

4.  町の人たちは何を心配し、何を恐れたのでしょうか。

5.  イエスはなぜこの人についてくることを許されなかった（39節）のでしょうか。

### 40節 - 56節

1.  ヤイロはどのような人で、どんな問題をかかえていますか。

2.  43節の女性は、どのような問題をかかえていますか。

3.  この女性は、どのように行動し、それに対して、イエスはどうされましたか。

4.  イエスの求めにこの女性はどのようにし、それに対して、イエスは、彼女に何と言われていますか。

5.  ヤイロの家から知らせが来たとき、イエスはヤイロに対してどのような言葉をかけていますか。（50節）ヤイロの心の内も考えてみましょう。

6.  ヤイロの家ではどのようなことがおきますか。

## ルカによる福音書　第9章

### 1節 - 6節

1.  この箇所から以下の事柄についてまとめてみましょう。

    1.  授けられたもの

    2.  遣わされた目的

    3.  持って行くもの

    4.  とどまるところ

    5.  すべき抗議

    6.  実際に行ったこと

2.  神の国を宣べ伝えることと、病人をいやすことにはどのような関係があるのでしょうか。

### 7節 - 9節

1.  ヘロデは何に戸惑っていた（口語：あわて惑っていた、新改訳：ひどく当惑していた）のでしょうか。

### 10節 - 17節

1.  このことはどのようなときに起こりますか (v10, 11)。

2.  何が起こったのか順を追ってまとめてみましょう。

3.  このことを通してイエスは何を教えようとされているのでしょうか。

### 18節 - 27節

1.  どのようなときに、このことは起こりますか。

2.  イエスはどのような二つの問いを弟子達にしていますか。

3.  ２１節で言われている「このこと」とは何でしょうか。また、何故誰にも話さないように命じたのでしょうか。

4.  どのようなことが起こると弟子達に告げていますか。(v. 22)

5.  ２３節から２７節では何を言っているのでしょうか。

### 28節 - 36節

1.  どのようなときに、このことが起こりますか。

2.  モーセ・エリヤ・イエスは、何について語り合っていたと言っていますか。

3.  ペテロは何を考えて、この様に提案したのでしょうか。

4.  ペテロの提案のあと何がおこりますか。

### 37節 - 43節

1.  山を下りるとどのようなことが起こっていますか。

2.  イエスは何について嘆いていますか。

3.  人々はなぜ神の偉大さに心を打たれたのでしょうか。

### 44節 - 48節

1.  ２回目の告白ではどのように言っていますか。

2.  これに対する弟子達の反応はどうでしたか。

3.  弟子達の関心事は何でしたか。

4.  「この子供を受け入れる」とは、どういうことでしょうか。そしてそれがなぜイエスを受け入れること、さらに、イエスを遣わされた方を受け入れることになるのでしょうか。

5.  最も小さいものが最も偉い（大きい）ものとはどういうことでしょうか。

### 49節 - 56節

1.  ここでイエスは何を教えているのでしょうか。

2.  なぜサマリア人はイエスを歓迎しなかったのでしょう。

3.  弟子達の派遣のときと、何が違うのでしょうか。

### 57節 - 62節

1.  ここで弟子としての覚悟として、イエスはどのようなことを言っていますか。

## ルカによる福音書　第10章

### 1節 - 24節

1.  イエスは72人\\footnote{ある写本では 70人、新改訳では 70を派遣しますが、その目的は何でしょうか。

2.  イエスはどのような指示を与えていますか。

3.  9章1--6節の記事と比べてみましょう。

4.  13節から16節に書かれている怒りをどう受け止めれば良いでしょうか。

5.  なぜ、悪霊が服従することを喜んではいけないのでしょうか。

6.  イエスはどのように祈っていますか。

7.  23節の「あなた方の見ているもの」とは何でしょうか。

### 25節 - 37節

1.  律法の専門家はどのような質問をしますか。

2.  イエスは彼の質問にどう返答しましたか。

3.  彼は、律法によると、どのような答えを自分の質問に対して持っていましたか。

4.  イエスはそれになんと答えましたか。

5.  律法の専門家はイエスの答えを聞いてどう思ったでしょうか。

6.  強盗に襲われた「ある人」は道ばたでどんな様子で倒れていたと思いますか。想像してみましょう。

7.  祭司とレビ人はそれぞれどうしますか。

8.  サマリヤ人は、どうしたと書いてありますか。

9.  たとえを話したあと、イエスはこの人になんと命じていますか。

10. あなたは、イエスと律法の専門家とのやりとりから、永遠の命と隣人を愛することについて、どんなことを学びましたか。

### 38節 - 42節

1.  マルタは何を願い、イエスはそれにどのように答えていますか。

2.  「必要なことはただ一つだけ」それは何なのでしょうか。

## ルカによる福音書　第11章

### 1節 - 13節

1.  どのような事を契機としてイエスは弟子たちに祈りについて教えることになりましたか。

2.  祈りの内容をまとめてみましょう。

3.  5節からのたとえから、祈りについてどのようなことが言われていますか。

4.  9節から13節では祈りについてどのようなことが教えられていますか。

### 14節 - 32節

1.  悪霊を追い出すイエスを見ていた群衆は、イエスに対してどんな反応をしていますか。（vs 14-16)

2.  イエスはそのような反応に何と答えていますか。

3.  イエスはしるしについてどのように言っていますか。

### 33節 - 36節

1.  「あかり」と「光」のたとえから、イエスは私たちに何を教えていますか。

### 37節 - 54節

1.  イエスはパリサイ人にどんな注意をしていますか。（vs 37-44）

2.  律法の専門家にはどんな注意をしていますか。（vs 45-52）

## ルカによる福音書　第12章

### 1節 - 12 節

1.  どのような状況で誰に対してイエスは語っていますか。(Describe the background and the audience.)

2.  4節から 12節でイエスはどのような事を言っていますか。(What did Jesus try to communicate in vs 4 -12?)

### 13節 - 34節

1.  群衆の中の一人はどんな理由でイエスのところに来ましたか。(What was the problem the man in vs 13 has?)

2.  なぜイエスは人々にたとえを話そうとされたのですか。(Why did Jesus tell a parable to people?)

3.  たとえの中で、金持ちが考えていたことは何ですか。(What did the rich in the parable plan?)

4.  なぜどん欲を警戒するのですか。(Why do we need to be on our guard against every kind of greed?)

5.  神はなぜ、この金持ちに「愚か者」と言われたのですか。(Why God said to the rich \`You fool!.')

6.  金持ちの最後はどうでしたか。(What was planned to the rich?)

7.  「神の前に富む」とは、具体的にどういうことですか。(What do you think is to be rich toward God?)

8.  最初にイエスに相談に来た人にイエスは何を言いたかったのでしょうか。(What did Jesus want to tell the person who came in vs 13?)

9.  22〜34節で、イエスが私たちにやめるようにすすめていることは何ですか。(What does Jesus tell us not to do in vs 22 - 34?)

10. イエスが私たちにするように求めていることは何ですか。(What does Jesus tell us to do?)

### 35節 - 53節

1.  聴衆がしもべにたとえられているようですが、しもべのつとめは何でしょうか。(What are the responsibilities of a servant (or a slave)?)

2.  どのようなしもべが幸いだと言っていますか[^lukedq-old-2]。(What sort of servants are blessed?)

3.  管理人は、何によって評価されますか[^lukedq-old-3]。(What do you think is the key characteristic of a steward (or a slave) described in vs 42-48.)

4.  イエスがもたらす分裂とはどのようなものでしょうか。(Why and how does Jesus bring division on earth?)

[^lukedq-old-2]: Why are faithfulness to Christ and readiness for his coming so important?

[^lukedq-old-3]: Why are those who know the will of God through his Word held more responsible?

### 54節 - 59節

1.  今の時を見分けるとはどういう事でしょうか[^lukedq-old-4]。(What does \`analyzing this present time' mean in vs 56?)

2.  57節から 59節のたとえでは、イエスはどのようなことを勧めているのでしょうか[^lukedq-old-5]。(What is the point about the court case in vs 57-59? What warning is implied?)

[^lukedq-old-4]: How would they we live differently if they we had spiritual discernment?

[^lukedq-old-5]: Why does Jesus want men to realize the need for settling their spiritual accounts with him by responding to him now?

## ルカによる福音書　第13章

### 1節 - 9節

1.  どのようなことがイエスに報告されていますか。報告した人たちの考えはどのようなものだったと考えられますか。(What is reported to Jesus? What question from them is implied?)

2.  イエスは、それにどのように答えていますか。(How does Jesus answer?)

3.  旧約聖書ではユダヤ人の国はイチジクの木にたとえられています。このたとえからどのような警告が与えられていると思いますか。ユダヤ人はどうすべきでしょうか。そのようにしないとどうなるでしょうか。(Using Old Testament imagery of the fig tree as a picture of the Jewish nation, what warning does Jesus give the nation in this parable? What should they do? What will happen if they don't?)

### 10節 - 17節

1.  会堂でどのような事がおきましたか。会堂長は何に対して（なぜ）腹をたてどのような行動をしましたか。(Describe this incident on the sabbath in the synagogue. Why the synagogue leader became indignant?)

2.  イエスは会堂長（たち）の偽善をどのように指摘していますか。(How does Jesus show that the attitude of the synagogue ruler is hypocritical and selfish?)

### 18節 - 21節

1.  ここでの二つのたとえは神の国についてどのようなことを教えていますか。(What do the two illustrations teach about the kingdom of God?)

### 22節 - 30節

1.  「救われる人が少ないのか」という質問にイエスはどのように答えていますか。(How does Jesus answer the question about the number of the saved?)

2.  イエスはどのような人に対しては救いのドアが閉じられると言っていますか。(How Jesus describes those who are shut out?)

### 31節 - 35節

1.  ヘロデが殺そうとしている」という警告にイエスはどのように応答していますか。(How does Jesus respond to the warning that Herod intends to kill him?)

2.  この箇所からイエスについて、これからのイエスの進む道についてどのような事が分かりますか。(What do we learn about Jesus from these verses?)

## ルカによる福音書　第14章

### 1節 - 6節

1.  食事の場でどんなことがおきましたか。なぜ律法の専門家たちやファリサイ派の人たちはイエスに答えることができなかったのでしょうか。(Describe the incident that occurs at the dinner. Why are the lawyers unable to respond to Jesus.)

### 7節 - 14節

1.  イエスは招待を受けた人についてどのようなことを指摘していますか。イエスがいいたかったことはどのようなことでしょうか。(What does Jesus observe about the people at the party? What is the point of the parable he tells them?)

2.  イエスは招待する側の人にどのようなことを助言していますか。裕福な人ではなく、貧しい人や障害を持っている人を招くようにと勧めている理由は何ですか。(What does Jesus address to the host of the party? What reason does he give for inviting the needy instead of the rich?)

### 15節 - 24節

1.  神の国で宴会の席に着く人の幸いについていった人にイエスはどのようなたとえを語っていますか。(What does Jesus say in this parable to the one who says the blessings of those who dine in the kingdom of God?

2.  たとえの中の人はどんなことをより大切にしていますか。私たちは優先順位をどのように決めるべきでしょうか。(How are the priorities of the people in the parable expressed? What are our priorities and how should we decide?)

### 25節 - 33節

1.  弟子の条件としてイエスはどのようなことをあげていますか。(What does it cost to follow Jesus?)

2.  塔を建てる人のたとえと戦争に臨む王のたとえを通してイエスはどのようなことを教えようとしているのでしょうか。(What does Jesus teach using two illustrations from building construction and from warfare?)

### 34節 - 35節

1.  「塩気」を失うとはどういうことでしょうか。この箇所を通してイエスは何を教えているのでしょうか。(Why is something that looks like salt but is not salt of no worth?)

## ルカによる福音書　第15章

### 1節 - 10節

1.  どのような人たちが何についてイエスに不平を言っていますか。それは何故でしょう。

2.  イエスはたとえでこれにどのように答えていますか。

3.  前のたとえとの相違点を考えてみましょう。

### 11節 - 32節

1.  このたとえはどのような背景で語られていますか。

2.  弟が家を出た理由はなんだったと想像しますか。

3.  弟は遠い国でどのようなことをしていましたか。

4.  「我に返った」とはどういうことだと思いますか。また、その前後の弟の変化について書いて下さい。

5.  なぜ弟は18節で「天に対して罪を犯し、父の前に罪を犯した。」と言ったのでしょうか。

6.  父は帰って来た弟をどのようにして迎えますか。またその様子がよく現れているところを全部列挙して下さい。

7.  父が家を出て帰ってきた弟をそのように迎えたのはなぜだと思いますか。

8.  弟は、天と父の前で罪を犯したことを自覚したとき、どのようにしましたか。

9.  兄は、弟が帰ってきたことを知ったとき、どのようなことをしましたか。

10. あなたは、このたとえでからどのようなことを新たに学びましたか。

11. このたとえをとおして、イエスは、パリサイ人や、私たちになにを語りかけているのでしょうか。

## ルカによる福音書　第16章

### 1節 - 18節

1.  この箇所はだれに対して語られていますか。

2.  この管理人のしたことをまとめてみましょう。

3.  「この世の子ら」、「光の子ら」とは、誰のことでしょうか。

4.  イエスはこのたとえで何を教えようとしていますか。

5.  イエスはパリサイ人にどんな警告をしていますか。

### 19節 - 31節

1.  金持ちとラザロのこの世での生活を比べ、分かることをあげてみましょう。

2.  死んだ後の金持ちとラザロについてどんなことがわかりますか。

3.  不正な管理人のたとえと、金持ちとラザロのたとえには、どんな共通点が有ると思いますか。

## ルカによる福音書　第17章

### 1節 - 10節

1.  つまづきをもたらす者、罪を犯した兄弟への対し方、赦しについてイエスは、どのように教えていますか。（1〜4節）

2.  イエスの教えている信仰とは、どのようなものですか。（5, 6節）

3.  主人としもべのたとえから、仕える者はどのような心構えでいるべきだと言われていますか。（7〜9節）

### 11節 - 19節

1.  重い皮膚病を患っている人たちはどのようにしてイエスに訴えますか。

2.  重い皮膚病を癒された10人のうち，なぜ，この人は戻って来たのでしょう。

### 20節 - 37節

1.  「神の国はいつ来るのか」というパリサイ人の質問に、イエスは神の国についてどのように教えていますか。

2.  「人の子の日」とはどのような日で、どんなことが起こると言っていますか。

3.  その時、私たちはどうすべきだとイエスは言っていますか。

## ルカによる福音書　第18章

### 1節 - 8節

1.  このたとえを通してイエスは誰のためにどのような事を教えていますか。

2.  この裁判官はどのような人だと思いますか。やもめはどんな立場にありますか

3.  イエスによると、神は私たちに何を約束してくださっていますか。

### 9節 - 14節

1.  イエスは10節以下の話を誰に向かってしていますか。

2.  パリサイ人と取税人の祈りの違いを見てみましょう。

パリサイ人はどのような祈りをしましたか？

1.  取税人はなぜ、遠くに離れて立って祈ったのですか。

2.  パリサイ人と取税人の祈りは違っていました。あなたはこの二人の祈りで、どこが最も違うところだと思いましたか？

### 15節 - 17節

1.  幼子の性格や特質から，子どものように神の国を受け入れるとは、どうすることでしょうか。(What does Jesus mean by receiving the kingdom of God like a little child?)

### 18節 - 30節

1.  イエスとの対話からこの役人はどのような人だと思いますか。(What can you tell about this ruler?)

2.  イエスはこの人の問題にどう答えていますか。(What is Jesus' response?)

3.  イエスはどんな約束をくださっていますか。（29, 30節）(What is the promise given by Jesus in vs 29-30?)

### 31節 - 34節

1.  以前にもイエスは死と復活を予告しています。それらと比べてみましょう。(Compare these verses with Lk 9:21, 22 or other verses.)

### 35節 - 43節

1.  この盲人は、イエスのことを何と呼んでいますか。(How does the blind man call Jesus?)

2.  この盲人は、イエスに何を期待していましたか。(What does the blind man expect from Jesus?)

3.  この章に登場した人たちからあなたはどのような事を学びましたか。(What have you leaned from those introduced in this chapter?)

## ルカによる福音書　第19章

### 1節 - 10節

1.  ザアカイは、どのような人ですか。なぜ、イエスを見たいと思ったのでしょう。(Describe who Zacchaeus is. Why did he want to see Jesus?)

2.  イエスはザアカイにどんな言葉をかけていますか。（5節）

イエスの呼びかけにザアカイはどうしますか。(How did Jesus approach Zacchaeus? How did Zacchaeus respond?)

1.  イエスの言った「救い」とはどのような事だと思いますか？ (What is the salvation Jesus claimed in verse 9?)

### 11節 - 27節

1.  イエスがこのたとえを話したのには、どんな目的がありましたか。(What are the reasons Jesus has for telling this parable?)

2.  たとえの中にどんな人たちが登場していますか。(List up the people in the parable.)

3.  このたとえでイエスはどのようなことを教えていますか。(What does Jesus teach people by this parable?)

4.  私たちにとって、「ミナ（ムナ）」とは何でしょうか。

### 28節 - 44節

1.  ベテパゲとベタニアに近づかれたとき、イエスは弟子たちに何を命じていますか。(What does Jesus ask disciple to prepare for his entry into the city?)

2.  旧約聖書のゼカリヤ書9章9節を読んでみましょう。イエスはご自身をどういう人物として、人々に紹介しようとしていますか。(Read Zachariah 9:9. What is Jesus presenting himself as being?)

3.  イエスを取り巻く人々は、どんな反応をしていますか。(What are the responses of the people around Jesus?)

4.  イエスはなぜ、都を見て泣くのでしょう。（41節〜42節）(Why does Jesus weep for Jerusalem?)

### 45節 - 48節

1.  神殿でイエスはどのような事をしましたか。そしてそれはなぜでしょう。(What does Jesus do at the temple? Why?)

## ルカによる福音書　第20章

### 1節 - 8節

1.  神殿の境内で教えているとき、イエスはどのような人たちからどのような質問を受けますか。(What challenge is put to Jesus as he teaches in the temple? Who challenged him?)

2.  イエスはどのように答えますか、そしてどうなりましたか。(What does Jesus' question about their estimate of John's ministry put them into dilemma?)

### 9節 - 19節

1.  このたとえでイエスはどのようなことを主張していますか。(What does Jesus claim about himself in this parable?)

2.  旧約聖書からの引用は何を示していますか。(What truth does Jesus show them about himself from the Old Testament?)

### 20節 - 26節

1.  律法学者たちはどのような罠を仕掛けていますか。(Into what political trap is their first question (verse 22) intended to snare Jesus?)

2.  イエスはどのように答えますか。イエスの答えはどのように受け取ったらよいでしょうか。(How dies Jesus confound them by his answer? What do you think about Jesus' answer?)

### 27節 - 40節

1.  だれがどのような質問をしますか。(Who challenges Jesus and how?)

2.  イエスはこれにどう答えられますか。(How does Jesus answer it?)

### 41節 - 44節

1.  イエスはどのような質問をしていますか。どのような人にむけた質問でしょうか。(What and to whom does Jesus ask a question?)

### 45節 - 47節

1.  イエスは律法学者をどのように非難していますか。ぞれぞれどのような事を指摘しているのか考えてみましょう。(How is Jesus criticizing the scribes?)

2.  なぜこのような人たちが人一倍厳しい裁きを受けるのでしょう。(Why is it dangerous to be responsible for \`\`turning people off" spiritually?)

## ルカによる福音書　第21章

### 1節 - 4節

1.  イエスは金持ちたちの献金とまずしいやもめの献金をどのように比較していますか。(How does Jesus compare the gifts of the rich with the gift of the poor widow?)

### 5節 - 6節

1.  どのような状況でイエスは神殿の崩壊について告げますか。(Under what circumstances does Jesus tell about the destruction of the temple?)

### 7節 - 19節

1.  聴衆たちは何について知りたいと思い、イエスはそれにどのように答えますか。(What do the hearers want to know and how does Jesus answer?)

2.  イエスはどのようなことがおこると言っていますか。また、聴衆はどのようなことに注意するように言われていますか。(What danger must Jesus' followers avoid? What would happen in those days?)

3.  迫害のときはどのような機会になると言ってますか。またどのような約束を与えていますか。(What opportunity comes with persecution? What does Jesus give his persecuted followers?)

### 20節 - 24節

1.  どのようなことがおこると言われていますか。(Describe the events fortold in this paragraph.)

2.  それはいつまでだと言っていますか。(How long will Jerusalem be in Gentile hands?)

### 25節 - 28節

1.  どのようなことがおき、それは人々にどのような影響を及ぼすと言っていますか。(What things will begin to happen? What effect will these events have on people?)

2.  イエスはどのようなことをすすめていますか。(What causes for rejoicing do verses 27, 28?)

### 29節 - 33節

1.  どのようなことが必要だと言っていますか。(What does Jesus emphasize the need for watchfulness?)

### 34節 - 38節

1.  どのようなとき、私たちの心は鈍くなりますか。(How do our hearts become weghed down?)

2.  どのように準備したらよいでしょうか。(How should we prepare for that day?)

3.  イエスはどのようなパターンで日々を過ごしていますか。(What pattern does Jesus follow during the week after his triunphal entrance into Jerusalem?)

## ルカによる福音書　第22章

### 1節 - 13節

1.  過越祭はユダヤ人達にとってどのような意味を持っていたでしょうか（出エジプト記 12:1-39 ）。(What does the Passover feast mean to Jews? (Read Ex. 12:1-39))

2.  ユダはどのような事を約束しますか。(What arrangement is made between the Jewish readers and Judas?)

3.  なぜイエスは過越の食事をする場所を弟子達にも知らせなかったのでしょうか。(What reason do you see for Jesus' secrecy about the place where he will have the Passover supper?)

### 14節 - 23節

1.  食事の席でイエスが弟子達に告げたことをまとめてみましょう。(What does Jesus reveal to his disciples at the supper?)

2.  裏切るものがいるとのイエスの言葉に弟子達はどのように反応しますか。(How and to what do disciples react?)

### 24節 - 34節

1.  弟子達が望んでいたことはどのような事だったでしょうか。(What is the disciples' concern?)

2.  イエスはここで弟子達にどのような事を教えていますか。(What does Jesus teach on the greatness?)

3.  イエスはシモンにどのような事を告げますか。それに対してシモンはどのように答えていますか。(What is foretold about Peter and what is his reaction?)

### 35節 - 38節

1.  どのような変化が弟子達の生活に起こると告げていますか。(What drastic change is about to come into the disciples' lives?)

### 39節 - 46節

1.  イエスは弟子達に祈りの前と後でどのような事を告げていますか。(What does Jesus tell his disciples before and after he prays?)

2.  イエスはどのように祈っていますか。(What is Jesus' prayer?)

### 47節 - 53節

1.  ここで起こったことをあげてみましょう。(Describe the events in this paragraph.)

2.  イエスは、ここでユダ、弟子達、民のリーダー達にどのようなことを伝えていますか。(What does Jesus tell each of Judas, his disciples and the leaders of the Jews through this incident?)

### 54節 - 62節

1.  ペトロはなぜイエスを知らないと言ってしまうのでしょうか。(Why do you think Peter disowns Jesus?)

### 63節 - 71節

1.  見張りをしていた人たちにとってイエスはどのような存在なのでしょう。(Who is Jesus for those who watched him?)

2.  イエスは最高法院でどのような証言をしていますか。(What claims does Jesus make at the assembly of elders?)

## ルカによる福音書　第23章

### 1節 - 5節

1.  人々は、イエスのどのような罪をピラトに訴えていますか。(What accusations does the Jewish council make against Jesus before Pilate?)

### 6節 - 12節

1.  なぜ、ピラトはイエスをヘロデに送ったのだと思いますか。(Why do you think Pilate sends Jesus to Herod?)

2.  ヘロデは何を期待していましたか。イエスはどのように応じますか。(What is Herod's attitude, how does Jesus respond and why is Herod frustrated?)

### 13節 - 25節

1.  ピラトが結論を出すまでの経過を追ってみましょう。(Trace the decisions Pilate makes, and the reasons for his decision (see v. 4, 14, 16, 22).)

2.  人々はなぜイエスを十字架に付けることを要求したのでしょうか。(Why do people want Jesus to be crusified?)

### 26節 - 43節

1.  イエスは婦人たちに何を伝えているのでしょうか。(What is Jesus' message to women of Jerusalem?)

2.  v34 のイエスの祈りからあなたはどのようなメッセージを受け取りますか。(What message do you receive in Jesus' prayer in v34?)

3.  イエスと一緒に十字架にかけられた犯罪人に対し、イエスはどのように答えていますか。(How does Jesus respond to the criminal?)

### 44節 - 49節

1.  イエスの死にあたり、どのような特別なことがおきますか。そして人々はどのように反応しますか。(What unusual events does Luke record in verse 44-45 at Jesus' death? How do people respond?)

### 50節 - 56節

1.  ヨセフからどのようなことを学びますか。(What do you learn about Joseph?)

2.  なぜ婦人達はすぐに、イエスの体に香油などを塗ることができなかったのでしょう。(Why can the women do nothing immediately about Jesus' body?)

## ルカによる福音書　第24章

### 1節 - 12節

1.  婦人達はどのような気持ちで、どのような事を考えて、何をしに墓に行きましたか。(What emotions, thought and intention do you imagine the women have as they go to the tomb?)

2.  婦人達は、そこで何を見、どのようなことを経験しますか。(What do the women experience there?)

3.  婦人達の報告に対する弟子達の反応から考えると、弟子達はこのとき、どのような状態でどのような事を考えていたでしょうか。(What report do the women make to the other disciples and how is it received? What does this indicate about the expectation of the eleven and the rest?)

### 13節 - 35節

1.  二人の弟子達はどんなことを話していましたか。このときの様子を思い描いて見ましょう。(What are the two discussing on their way to Emmaus? What do you think would be included in their conversation?)

2.  イエスはなぜ旧約聖書から説明されたのでしょうか。またどのようなことを説明しましたか。(Why would Jesus want to interpret to them the Old Testament prophecies about himself before they recognize him? What is the scope of his teaching?)

3.  二人はどのようにして、イエスであると分かりましたか。(Why do you think they recognized Jesus when they were at the table?)

4.  なぜ二人はエルサレムに戻ったのでしょうか。(Why do they return to Jerusalem?)

### 36節 - 49節

1.  イエスは驚いている弟子達にどのように語りかけていますか。(What does Jesus understand about his troubled disciples? How does he ally their fears and questions?)

2.  ルカはイエスの復活がどのようなものであったと記述しているのでしょうか。(What does this section indicate about the kind of resurrection Luke reports?)

3.  イエスは、ここで弟子達にどのような事を教えていますか。まとめてみましょう。(List things Jesus teaches.)

### 50節 - 53節

1.  イエスの昇天についてまとめてみましょう。(Describe Jesus' departure and the disciples' reaction to it.)
