# 聖書の会\@万座温泉 {#manza}

## 過去の会について

ホームページを参照してください。\[[リンク](https://icu-hsuzuki.github.io/science/bible/biblestudy2003.html#manza)\]

## 第七回

### 概要

日程：2023年11月3日〜11月5日

参加人数：12人（予定）

### スケジュール

11/3 バス 8:50 新宿駅西口都庁横大型バス専用駐車場集合、9:00 出発

```         
昼食：ドライブイン

ホテル到着：15:00 頃着（以前より遅くなりました。チェックインが15:00になりました）連休で渋滞の可能性あり

（軽井沢からは、ホテル到着 16:00頃）

夕食：ホテルバイキング

聖書の会 第一：「汚れた霊が戻ってくる」（マタイ12:43-45、ルカ11:24-26）
```

11/4 朝食：ホテルバイキング

```         
聖書の会 第二：「愚かな金持ち」のたとえ（ルカ12:13-21）

昼食

自由時間：交流のとき

（お一人、ホテル到着 15:00頃）

夕食：ホテルバイキング

聖書の会 第三：「思い煩うな」（マタイ6:25-34、ルカ12:22-32）
```

11/5 朝食：ホテルバイキング

```         
（軽井沢行きバス：11:00）

聖書の会 第四：「ぶどう園の労働者」のたとえ（マタイ 20:1-16）

昼食：万座温泉日進舘レストランなど

ホテル出発：15:00 

新宿駅西口：19:30 頃着予定、解散（連休であるため遅くなる可能性もあります）
```

### 大雑把なキリスト教年表

確定は困難ですが、目安として書いておきます。

-   BC6-BC4 イエスの誕生

-   AD30-33 イエスの十字架上での死（復活、昇天）

-   AD50年代 パウロ書簡（テサロニケの信徒への手紙一、ガラテヤの信徒への手紙、コリントの信徒への手紙一・二、ローマの信徒への手紙、ピレモンへの手紙、ピリピの信徒への手紙、他にもパウロ由来の手紙あり）

-   AD70前後 マルコによる福音書（ペテロの通訳のマルコ由来）

-   AD70エルサレム陥落（AD66〜AD70（7ヶ月の包囲後陥落）〜AD74）

-   AD80前後 ルカによる福音書（パウロの同行者の医者ルカ由来）、マタイによる福音書（マタイ由来の文書を中心に編纂）

-   AD90年代 ヨハネによる福音書（ヨハネ由来、21章はヨハネの死後）

### 聖書の会（１）汚れた霊が戻ってくる

#### ルカ11章24-26節

> 24 汚れた霊が人から出ると、休み場を求めて水の無い所を歩きまわるが、見つからないので、出てきた元の家に帰ろうと言って、25 帰って見ると、その家はそうじがしてある上、飾りつけがしてあった。26 そこでまた出て行って、自分以上に悪い他の七つの霊を引き連れてきて中にはいり、そこに住み込む。そうすると、その人の後の状態は初めよりももっと悪くなるのである」。

#### マタイ12章43-45節

> 43 汚れた霊が人から出ると、休み場を求めて水の無い所を歩きまわるが、見つからない。44 そこで、出てきた元の家に帰ろうと言って帰って見ると、その家はあいていて、そうじがしてある上、飾りつけがしてあった。45 そこでまた出て行って、自分以上に悪い他の七つの霊を一緒に引き連れてきて中にはいり、そこに住み込む。そうすると、その人ののちの状態は初めよりももっと悪くなるのである。よこしまな今の時代も、このようになるであろう」。 

[ルカによる福音書11章24-26節福音書対照表](https://icu-hsuzuki.github.io/science/bible/extra/manza2023/Lk11_24-26.pdf)

#### **問い**

1.  汚れた霊とはどのような存在で、どこで、何を目的として活動する（と考えられていた）のでしょうか。（ルカ11:24,マタイ12:43）

2.  元の家がそうじがしてあって、飾り付けがしてあったとは、どのような状態を言っているのでしょうか。（ルカ11:25,マタイ12:44）

3.  なぜ、その人の後の状態が初めよりもっと悪くなったのでしょうか。（ルカ11:26,マタイ12:45）

4.  マタイでは、いまの時代について何を伝えていますか。（マタイ12:45）

5.  ベルゼブル論争（マルコ3:20-30、マタイ12:22-32、ルカ11:14-23）と関係しているとすると、それは、どのようなことですか。

6.  イエスは、このたとえで、なにを教えているのでしょうか。

#### **参照**

-   ルカ11:20-22 しかし、わたしが神の指によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。21 強い人が十分に武装して自分の邸宅を守っている限り、その持ち物は安全である。22 しかし、もっと強い者が襲ってきて彼に打ち勝てば、その頼みにしていた武具を奪って、その分捕品を分けるのである。23 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。（ここに続く）

-   マタイ12:28 しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。29 まただれでも、まず強い人を縛りあげなければ、どうして、その人の家に押し入って家財を奪い取ることができようか。縛ってから、はじめてその家を掠奪することができる。30 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。

-   イエスの悪霊追放・いやし・ゆるし

    -   マルコ9:25 イエスは群衆が駆け寄って来るのをごらんになって、けがれた霊をしかって言われた、「言うことも聞くこともさせない霊よ、わたしがおまえに命じる。この子から出て行け。二度と、はいって来るな」。

    -   マルコ5:34 イエスはその女に言われた、「娘よ、あなたの信仰があなたを救ったのです。安心して行きなさい。すっかりなおって、達者でいなさい」。

    -   ヨハネ5:14 そののち、イエスは宮でその人に出会ったので、彼に言われた、「ごらん、あなたはよくなった。もう罪を犯してはいけない。何かもっと悪いことが、あなたの身に起るかも知れないから」。

    -   ヨハネ8:11 女は言った、「主よ、だれもございません」。イエスは言われた、「わたしもあなたを罰しない。お帰りなさい。今後はもう罪を犯さないように」。〕

-   聖霊（神様の心）

    -   1コリント2:10-12 そして、それを神は、御霊によってわたしたちに啓示して下さったのである。御霊はすべてのものをきわめ、神の深みまでもきわめるのだからである。11 いったい、人間の思いは、その内にある人間の霊以外に、だれが知っていようか。それと同じように神の思いも、神の御霊以外には、知るものはない。12 ところが、わたしたちが受けたのは、この世の霊ではなく、神からの霊である。それによって、神から賜わった恵みを悟るためである。 

#### **記録**

-   日時：2023年11月3日午後8時半〜10時半

-   出席 9名

#### **問いについて**

1.  汚れた霊について：その活動目的と、活動場所。

    -   神の支配（神の国、御心がなること）に逆らい、人々に害を与えたり、病気を引き起こしたりする存在。

    -   活動場所：人および人々の中。または、ひとと神との間。

2.  元の家がきれいになっているとは。

    -   （聖霊によって生きる）神との関係がなく、いつでも、神の支配に逆らうことができる状態。

    -   \[DQ\] 空っぽで、なににも、囚われていないほうが良いのではないでしょうか。

        -   神の支配に逆らう悪霊ではなく、神の霊で満たされることが大切だと示唆されている？

        -   空っぽがよいということは、自分がすべてを判断できるとすることと同じ。おそらくそれは不可能なのだろう。

3.  なぜ、悪くなったのか。

    -   満たされていない。

    -   何か、しっかりした、信仰や、汚れた霊に立ち向かうものを持たなければいけないということでしょうか。

    -   \[DQ\] どうしていなければいけなかったのでしょうか。

4.  マタイ：いまの時代について？

    -   マタイでは、ベルゼブル論争に続いて、「実によって木を知る」と「人々はしるしを欲しがる」のあとに置かれている。

    -   イエスが、来たのに、悔い改めない。ニネベの人たち、南の女王が糾弾するときとなる。

5.  ベルゼブル論争との関係

    -   ルカ11:20-22: 20 しかし、わたしが神の指によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。21 強い人が十分に武装して自分の邸宅を守っている限り、その持ち物は安全である。22 しかし、もっと強い者が襲ってきて彼に打ち勝てば、その頼みにしていた武具を奪って、その分捕品を分けるのである。

    -   マタイ12:28: しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。29 まただれでも、まず強い人を縛りあげなければ、どうして、その人の家に押し入って家財を奪い取ることができようか。縛ってから、はじめてその家を掠奪することができる。

6.  なにを教えているのか。

    -   汚れた霊が出ていったかどうかが問題ではなく、聖霊に満たされ、神様の国を求め続けることがたいせつ。

#### **メモ**

-   ルカもマタイもどちらも、ベルゼブル論争のあとに置かれている。大雑把にいうと、ルカは、その直後に、この「汚れた霊が戻ってくる」が置かれ「真の幸い」の短い記事を挟んで「人々はしるしを欲しがる」記事が続く。マタイでは、ベルゼブル論争のあと、実によって木を知る記事が挟まれ、そのあとに、「人々はしるしを欲しがる」そして「汚れた霊が戻ってくる」となっている。つながりとしては自然に見えるマルコ3章には、「汚れた霊が戻ってくる」記事も、「人々はしるしを欲しがる」記事もなく、単純に、ベルゼブル論争のあとに、その背景にある、3章20節を受ける形で、「イエスの母、きょうだい」の記事が続いている。マタイには、同様に、「汚れた霊が戻ってくる」の直後に、「イエスの母、きょうだい」の記事が続くことから、本来の伝承は、おそらく、ペテロによって語られていた、マルコの繋がりであり、ベルゼブル論争を受けて、関連する記事が挿入されたものと思われる。ベルゼブル論争のあとに、「人々はしるしを欲しがる」と、「汚れた霊が戻ってくる」が挿入されるのは、ベルゼブル論争の性格から、自然であるように見える。

-   悪霊を追い出すだけではなく、「天の父が、求める人たちに、どうして聖霊をくださらないことがありましょう。」（ルカ11:13）に続く、新たなあゆみが整えられなければいけないことを述べているのかもしれない。「しかし、わたしが神の指によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。」（ルカ11:20）「しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。 」（マタイ12:28）

-   このあとは、ルカでは、「しかしイエスは言われた、『いや、めぐまれているのは、むしろ、神の言を聞いてそれを守る人たちである』。」（ルカ11:28）マタイでは、「そして、弟子たちの方に手をさし伸べて言われた、『ごらんなさい。ここにわたしの母、わたしの兄弟がいる。天にいますわたしの父のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである』。」（マタイ12:49,50）

-   現代では、おそらく、どんな宗教にもとらわれない、自分をしっかりと持つことが、推奨されるのだろう。それで本当に良いのだろうか。同時に、なにかに頼ることは、悪霊が入り込む隙をつくる。神の霊に満たされていればたしかによいが、それが神の霊であるかはどのように判断すれば良いのだろうか。それは「実によってわかる」ことなのかも知れない。むろん、すぐには、判断できないかも知れない。交わりを持ち続けながら、検証もすることだろうか。丁寧に、学んでいきたい。

### 聖書の会（２）「愚かな金持ち」のたとえ

#### ルカ12章13-21節

> 13 群衆の中のひとりがイエスに言った、「先生、わたしの兄弟に、遺産を分けてくれるようにおっしゃってください」。14 彼に言われた、「人よ、だれがわたしをあなたがたの裁判人または分配人に立てたのか」。15 それから人々にむかって言われた、「あらゆる貪欲に対してよくよく警戒しなさい。たといたくさんの物を持っていても、人のいのちは、持ち物にはよらないのである」。16 そこで一つの譬を語られた、「ある金持の畑が豊作であった。17 そこで彼は心の中で、『どうしようか、わたしの作物をしまっておく所がないのだが』と思いめぐらして 18 言った、『こうしよう。わたしの倉を取りこわし、もっと大きいのを建てて、そこに穀物や食糧を全部しまい込もう。19 そして自分の魂に言おう。たましいよ、おまえには長年分の食糧がたくさんたくわえてある。さあ安心せよ、食え、飲め、楽しめ』。20 すると神が彼に言われた、『愚かな者よ、あなたの魂は今夜のうちにも取り去られるであろう。そしたら、あなたが用意した物は、だれのものになるのか』。21 自分のために宝を積んで神に対して富まない者は、これと同じである」。

[ルカによる福音書12章13-21節](https://icu-hsuzuki.github.io/science/bible/extra/manza2023/Lk12_13-21.pdf)

#### **問い**

1.  群衆の中のひとりのどのような依頼から始まりますか。（13）

2.  イエスはどのように答えていますか。（14,15）

3.  たとえの中で、金持ちは、どのように、考えていますか。（16-19）

4.  神はなぜ、この金持ちに「愚か者よ」と言われたのですか。（20）

5.  「あらゆる貪欲に対してよくよく警戒しなさい」とはどういう意味でしょうか。（15）

6.  「神に対して富む」とは、具体的にどういうことですか。（21）

7.  最初にイエスに相談に来た人や群衆にイエスは何を伝えたかったのでしょうか。

#### **参照**

-   シラ書（集会の書）11:18-19 用心と節約によって金持ちになる人がいる。／しかし、そういう者の受ける報いはこうだ。19「もう安心して休める。／これで、自分の財産で食べていけるぞ」と言っても／それがいつまで続くのか、知る由もなく／財産を他人に残して、死んでいくのだ。

-   愚か者：生活上神がいないかのようにふるまう実際的無神論

    -   ヨブ2:10 しかしヨブは彼女に言った、「あなたの語ることは愚かな女の語るのと同じだ。われわれは神から幸をうけるのだから、災をも、うけるべきではないか」。すべてこの事においてヨブはそのくちびるをもって罪を犯さなかった。

    -   詩篇14:2 愚かな者は心のうちに「神はない」と言う。彼らは腐れはて、憎むべき事をなし、／善を行う者はない。

    -   サムエル記下25:25 わが君よ、どうぞ、このよこしまな人ナバルのことを気にかけないでください。あの人はその名のとおりです。名はナバルで、愚か者です。あなたのはしためであるわたしは、わが君なるあなたがつかわされた若者たちを見なかったのです。

    -   黙示録3:17 あなたは、自分は富んでいる。豊かになった、なんの不自由もないと言っているが、実は、あなた自身がみじめな者、あわれむべき者、貧しい者、目の見えない者、裸な者であることに気がついていない。

    -   アモス4:12 「それゆえイスラエルよ、／わたしはこのようにあなたに行う。わたしはこれを行うゆえ、／イスラエルよ、あなたの神に会う備えをせよ」。

    -   コリント下8:9 あなたがたは、わたしたちの主イエス・キリストの恵みを知っている。すなわち、主は富んでおられたのに、あなたがたのために貧しくなられた。それは、あなたがたが、彼の貧しさによって富む者になるためである。

    -   ヤコブ2:5 愛する兄弟たちよ。よく聞きなさい。神は、この世の貧しい人たちを選んで信仰に富ませ、神を愛する者たちに約束された御国の相続者とされたではないか。

-   人よ、だれがわたしをあなたがたの裁判人または分配人に立てたのか

    -   出エジプト記2:14 彼は言った、「だれがあなたを立てて、われわれのつかさ、また裁判人としたのですか。エジプトびとを殺したように、あなたはわたしを殺そうと思うのですか」。モーセは恐れた。そしてあの事がきっと知れたのだと思った。

    -   使徒7:27 すると、仲間をいじめていた者が、モーセを突き飛ばして言った、『だれが、君をわれわれの支配者や裁判人にしたのか。

    -   使徒7:35 こうして、『だれが、君を支配者や裁判人にしたのか』と言って排斥されたこのモーセを、神は、柴の中で彼に現れた御使の手によって、支配者、解放者として、おつかわしになったのである。 

    -   参考：使徒18:15 これは諸君の言葉や名称や律法に関する問題なのだから、諸君みずから始末するがよかろう。わたし（アカヤの総督ガリオ）はそんな事の裁判人にはなりたくない」。 

-   裁く

    -   ローマ2:1-3 だから、ああ、すべて人をさばく者よ。あなたには弁解の余地がない。あなたは、他人をさばくことによって、自分自身を罪に定めている。さばくあなたも、同じことを行っているからである。2 わたしたちは、神のさばきが、このような事を行う者どもの上に正しく下ることを、知っている。3 ああ、このような事を行う者どもをさばきながら、しかも自ら同じことを行う人よ。あなたは、神のさばきをのがれうると思うのか。

-   死ぬ時は

    -   詩篇49:17-19 彼が死ぬときは何ひとつ携え行くことができず、／その栄えも彼に従って下って行くことは／ないからである。 18 たとい彼が生きながらえる間、自分を幸福と思っても、／またみずから幸な時に、人々から称賛されても、19 彼はついにおのれの先祖の仲間に連なる。彼らは絶えて光を見ることがない。

-   喜び裁き：伝道の書 11:9 若い者よ、あなたの若い時に楽しめ。あなたの若い日にあなたの心を喜ばせよ。あなたの心の道に歩み、あなたの目の見るところに歩め。ただし、そのすべての事のために、神はあなたをさばかれることを知れ。

-   富んでいる者よ：ヤコブ5:1-5 富んでいる人たちよ。よく聞きなさい。あなたがたは、自分の身に降りかかろうとしているわざわいを思って、泣き叫ぶがよい。2 あなたがたの富は朽ち果て、着物はむしばまれ、3 金銀はさびている。そして、そのさびの毒は、あなたがたの罪を責め、あなたがたの肉を火のように食いつくすであろう。あなたがたは、終りの時にいるのに、なお宝をたくわえている。4 見よ、あなたがたが労働者たちに畑の刈入れをさせながら、支払わずにいる賃銀が、叫んでいる。そして、刈入れをした人たちの叫び声が、すでに万軍の主の耳に達している。5 あなたがたは、地上でおごり暮し、快楽にふけり、「ほふらるる日」のために、おのが心を肥やしている。

-   誰に富むか

    -   詩篇39:7 主よ、今わたしは何を待ち望みましょう。わたしの望みはあなたにあります。

    -   箴言27:1 あすのことを誇ってはならない、／一日のうちに何がおこるかを／知ることができないからだ。

    -   エレミヤ17:11 しゃこが自分が産んだのではない卵を抱くように、／不正な財産を得る者がある。その人は一生の半ばにそれから離れて、／その終りには愚かな者となる。 

    -   シラ書11:19 「もう安心して休める。／これで、自分の財産で食べていけるぞ」と言っても／それがいつまで続くのか、知る由もなく／財産を他人に残して、死んでいくのだ。

    -   コリント前書15:32 もし、わたしが人間の考えによってエペソで獣と戦ったとすれば、それはなんの役に立つのか。もし死人がよみがえらないのなら、「わたしたちは飲み食いしようではないか。あすもわからぬいのちなのだ」。 

-   愚かさ

    -   ヨブ20:22 （ナアマびとゾパル、悪しき人について）その力の満ちている時、彼は窮境に陥り、／悩みの手がことごとく彼の上に臨むであろう。 

    -   ハバクク2:9 わざわいなるかな、／災の手を免れるために高い所に巣を構えようと、／おのが家のために不義の利を取る者よ。

    -   ルカ12:33 自分の持ち物を売って、施しなさい。自分のために古びることのない財布をつくり、盗人も近寄らず、虫も食い破らない天に、尽きることのない宝をたくわえなさい。

-   神に富む

    -   ルカ12:33 自分の持ち物を売って、施しなさい。自分のために古びることのない財布をつくり、盗人も近寄らず、虫も食い破らない天に、尽きることのない宝をたくわえなさい。

    -   マタイ6:20 むしろ自分のため、虫も食わず、さびもつかず、また、盗人らが押し入って盗み出すこともない天に、宝をたくわえなさい。

    -   テモテ前書6:18,19 また、良い行いをし、良いわざに富み、惜しみなく施し、人に分け与えることを喜び、19 こうして、真のいのちを得るために、未来に備えてよい土台を自分のために築き上げるように、命じなさい。

    -   ヤコブ2:5 愛する兄弟たちよ。よく聞きなさい。神は、この世の貧しい人たちを選んで信仰に富ませ、神を愛する者たちに約束された御国の相続者とされたではないか。

    -   黙示録3:17 あなたは、自分は富んでいる。豊かになった、なんの不自由もないと言っているが、実は、あなた自身がみじめな者、あわれむべき者、貧しい者、目の見えない者、裸な者であることに気がついていない。

#### **記録**

-   日時：2023年11月4日午前9時半〜11時半

-   出席 9名

#### **問いについて**

1.  群衆の中のひとりの依頼（13）

    -   「先生、わたしの兄弟に、遺産を分けてくれるようにおっしゃってください」。

    -   \[DQ\] なぜ、このような依頼を、この人はイエスにしたのでしょうか。

2.  イエスの応答（14,15）

    -   14 彼に言われた、「人よ、だれがわたしをあなたがたの裁判人または分配人に立てたのか」。15 それから人々にむかって言われた、「あらゆる貪欲に対してよくよく警戒しなさい。たといたくさんの物を持っていても、人のいのちは、持ち物にはよらないのである」。

    -   \[DQ\] なぜ、イエスは、直接的な応答を拒んだのでしょうか。

    -   \[DQ\] ここでイエスが、たいせつなこととして伝えているのは何でしょうか。

3.  金持ちの考え（16-19）

    -   16 そこで一つの譬を語られた、「ある金持の畑が豊作であった。17 そこで彼は心の中で、『どうしようか、わたしの作物をしまっておく所がないのだが』と思いめぐらして 18 言った、『こうしよう。わたしの倉を取りこわし、もっと大きいのを建てて、そこに穀物や食糧を全部しまい込もう。19 そして自分の魂に言おう。たましいよ、おまえには長年分の食糧がたくさんたくわえてある。さあ安心せよ、食え、飲め、楽しめ』。

    -   \[DQ\] 何か、違和感を感じることはありますか。何が問題なのでしょう。

    -   \[DQ\] あなたなら、このようなとき、どうしますか。特別収入？　宝くじ？

    -   \[DQ\] 将来に備えることは、立派なことではないでしょうか。

4.  愚か者？（20）

    -   20 すると神が彼に言われた、『愚かな者よ、あなたの魂は今夜のうちにも取り去られるであろう。そしたら、あなたが用意した物は、だれのものになるのか』。

    -   \[DQ\] いのち（健康）にも気を遣えば、それで良いでしょうか。

    -   \[DQ\] 魂がとられとは、どのような事を言っているのでしょうか。

5.  あらゆる貪欲に警戒しなさい（15）

    -   15 それから人々にむかって言われた、「あらゆる貪欲に対してよくよく警戒しなさい。たといたくさんの物を持っていても、人のいのちは、持ち物にはよらないのである」。

    -   貪欲：次々と欲を出し満足しないこと。

    -   \[DQ\] あなたは、どんなことに、貪欲になりますか。

    -   \[DQ\] 「いのち（神様・イエス様との交わり？ ヨハネ17:3）」のことに貪欲になるのは良いのでしょうか。

6.  「神の対して富む」とは、具体的にどういうことですか。（21）

    -   21 自分のために宝を積んで神に対して富まない者は、これと同じである」。

    -   \[DQ\] 神か、富、どちらも独占欲が強い。一方しか選べないということでしょうか。

    -   \[DQ\] たくさん、献金しなさいということでしょうか。

7.  最初にイエスに相談に来た人や群衆にイエスは何を伝えたかったのでしょうか。

    -   いのちに関すること、神に対して富むことに、心を配るように。

    -   \[DQ\] 遺産分与については、結局どうすれば良いのでしょうか。

#### **メモ**

-   構造：簡潔な教え（14,15）、たとえ（16-21）、積極的な勧告（22-34）

    -   起点：13 群衆の中のひとりがイエスに言った、「先生、わたしの兄弟に、遺産を分けてくれるようにおっしゃってください」。14 彼に言われた、「人よ、だれがわたしをあなたがたの裁判人または分配人に立てたのか」。

    -   譬え：17 そこで彼は心の中で、『どうしようか、**わたしの**作物をしまっておく所がないのだが』と思いめぐらして 18 言った、『こうしよう。**わたしの**倉を取りこわし、もっと大きいのを建てて、そこに穀物や食糧を全部しまい込もう。19 そして**自分の**魂に言おう。たましいよ、**おまえには**長年分の食糧がたくさんたくわえてある。さあ安心せよ、食え、飲め、楽しめ』

-   メッセージは、質問してきた人にだけ答えているわけではない。「15 それから人々にむかって言われた」

-   何が愚かなのか。

-   一般の人には「貪欲」を避けることがテーマである。最初の人の兄弟は、たしかに、貪欲なのだろう。しかし、その悪をあげつらうことは、自分もそれを望んでいること、貪欲であることを承認していることでもあるのだろう。貪欲な人に引き込まれる。プロスペクト理論が言うように、得をするより、損をしないことを選択する傾向が人間にはあり、それが貪欲の実態なのかもしれない。すなわち、他者との関わりの中で、合理性すらない選択をし続ける。イエスが言っているのは、そのようなものに、引っ張られては行けないということなのだろう。感想にもあったが、貪欲は、伝染すると表現できるかも知れない。

    -   プロスペクト理論（Prospect Theory）は、認知心理学者であるダニエル・カーネマンとアモス・トヴェルスキーによって提案された行動経済学の理論です。プロスペクト理論は、人々がリスクを評価し、意思決定を行う際の心理的特性を説明するために開発されました。

        プロスペクト理論は、伝統的な経済理論である期待効用理論に対して、人々の意思決定が合理的ではなく、主観的な評価に基づいて行われることを主張します。以下に、プロスペクト理論の主な概念を説明します。

        1.  個別の価値関数: プロスペクト理論では、利得や損失を評価する際に、人々は個別の価値関数を持っているとされます。価値関数は、利得や損失に対する主観的な価値を表現し、それに基づいて選択を行います。一般的に、損失に対する感受性は利得に対する感受性よりも大きいとされます。

        2.  損失回避の傾向: プロスペクト理論によれば、人々は損失を回避する傾向があります。同じ金額の利得と損失を比較した場合、損失を避けることを優先する傾向があります。これは、「損失回避のプレミアム」と呼ばれる現象です。

        3.  参照点の重要性: プロスペクト理論では、意思決定において参照点が重要な役割を果たすとされます。参照点は、人々が選択肢の利得や損失を評価する際の基準となります。参照点に対する利得や損失がどれだけあるかによって、人々の評価や意思決定が変化することがあります。

        プロスペクト理論は、経済学や金融学、マーケティングなどの分野で広く応用されています。この理論は、人々の意思決定における心理的要素やバイアスを考慮することで、より現実的なモデルを提供します。

### 聖書の会（３）思い煩うな

ルカによる福音書を中心として、マタイによる福音書を参考にして、学びましょう。

#### ルカ12章22-34節

> 22 それから弟子たちに言われた、「それだから、あなたがたに言っておく。何を食べようかと、命のことで思いわずらい、何を着ようかとからだのことで思いわずらうな。23 命は食物にまさり、からだは着物にまさっている。24 からすのことを考えて見よ。まくことも、刈ることもせず、また、納屋もなく倉もない。それだのに、神は彼らを養っていて下さる。あなたがたは鳥よりも、はるかにすぐれているではないか。25 あなたがたのうち、だれが思いわずらったからとて、自分の寿命をわずかでも延ばすことができようか。26 そんな小さな事さえできないのに、どうしてほかのことを思いわずらうのか。27 野の花のことを考えて見るがよい。紡ぎもせず、織りもしない。しかし、あなたがたに言うが、栄華をきわめた時のソロモンでさえ、この花の一つほどにも着飾ってはいなかった。28 きょうは野にあって、あすは炉に投げ入れられる草でさえ、神はこのように装って下さるのなら、あなたがたに、それ以上よくしてくださらないはずがあろうか。ああ、信仰の薄い者たちよ。29 あなたがたも、何を食べ、何を飲もうかと、あくせくするな、また気を使うな。30 これらのものは皆、この世の異邦人が切に求めているものである。あなたがたの父は、これらのものがあなたがたに必要であることを、ご存じである。31 ただ、御国を求めなさい。そうすれば、これらのものは添えて与えられるであろう。32 恐れるな、小さい群れよ。御国を下さることは、あなたがたの父のみこころなのである。33 自分の持ち物を売って、施しなさい。自分のために古びることのない財布をつくり、盗人も近寄らず、虫も食い破らない天に、尽きることのない宝をたくわえなさい。34 あなたがたの宝のある所には、心もあるからである。 

#### マタイ6章19-34節

> 19 あなたがたは自分のために、虫が食い、さびがつき、また、盗人らが押し入って盗み出すような地上に、宝をたくわえてはならない。20 むしろ自分のため、虫も食わず、さびもつかず、また、盗人らが押し入って盗み出すこともない天に、宝をたくわえなさい。21 あなたの宝のある所には、心もあるからである。22 目はからだのあかりである。だから、あなたの目が澄んでおれば、全身も明るいだろう。23 しかし、あなたの目が悪ければ、全身も暗いだろう。だから、もしあなたの内なる光が暗ければ、その暗さは、どんなであろう。24 だれも、ふたりの主人に兼ね仕えることはできない。一方を憎んで他方を愛し、あるいは、一方に親しんで他方をうとんじるからである。あなたがたは、神と富とに兼ね仕えることはできない。25 それだから、あなたがたに言っておく。何を食べようか、何を飲もうかと、自分の命のことで思いわずらい、何を着ようかと自分のからだのことで思いわずらうな。命は食物にまさり、からだは着物にまさるではないか。26 空の鳥を見るがよい。まくことも、刈ることもせず、倉に取りいれることもしない。それだのに、あなたがたの天の父は彼らを養っていて下さる。あなたがたは彼らよりも、はるかにすぐれた者ではないか。27 あなたがたのうち、だれが思いわずらったからとて、自分の寿命をわずかでも延ばすことができようか。28 また、なぜ、着物のことで思いわずらうのか。野の花がどうして育っているか、考えて見るがよい。働きもせず、紡ぎもしない。29 しかし、あなたがたに言うが、栄華をきわめた時のソロモンでさえ、この花の一つほどにも着飾ってはいなかった。30 きょうは生えていて、あすは炉に投げ入れられる野の草でさえ、神はこのように装って下さるのなら、あなたがたに、それ以上よくしてくださらないはずがあろうか。ああ、信仰の薄い者たちよ。31 だから、何を食べようか、何を飲もうか、あるいは何を着ようかと言って思いわずらうな。32 これらのものはみな、異邦人が切に求めているものである。あなたがたの天の父は、これらのものが、ことごとくあなたがたに必要であることをご存じである。33 まず神の国と神の義とを求めなさい。そうすれば、これらのものは、すべて添えて与えられるであろう。34 だから、あすのことを思いわずらうな。あすのことは、あす自身が思いわずらうであろう。一日の苦労は、その日一日だけで十分である。

[ルカによる福音書12章22-34節福音書対照表](https://icu-hsuzuki.github.io/science/bible/extra/manza2023/Lk12_22-34.pdf)

#### **問い**

1.  ルカでは「愚かな金持ち」のたとえと、この箇所は、それぞれ、誰に向けて、語られていますか。

2.  「思い煩うな」と言われていますが、思い煩いとは、どのようなことでしょうか。あなたは、どのようなことに思い煩いますか。

3.  なぜ思い煩わなくて良いのでしょうか。なぜ思い煩ってはいけないのでしょうか。その理由を挙げてみましょう。

4.  御国を求める（マタイ：神の国と神の義をと求める）とはどのようなことでしょうか。（ルカ12:31, マタイ6:33）

5.  天に宝をたくわえるとはどういう事でしょうか。（ルカ12:33, マタイ6:20）

6.  マタイでは、ルカに加えてどのようなことが教えられていますか。

#### **参照**

-   思い煩うな（μὴ μεριμνᾶτετῇ[^manza-1] ψυχῇ ὑμῶν）色々な部分に分裂する。ヘブル語でも「撹乱される、心配する」シングル・ハートでいなさい。distracted.
    -   ルカ10:41 主は答えて言われた、「マルタよ、マルタよ、あなたは多くのことに心を配って思いわずらっている。
    -   マタイ10:19 彼らがあなたがたを引き渡したとき、何をどう言おうかと心配しないがよい。言うべきことは、その時に授けられるからである。
    -   ピリピ4:6 何事も思い煩ってはならない。ただ、事ごとに、感謝をもって祈と願いとをささげ、あなたがたの求めるところを神に申し上げるがよい。
-   主の養い：
    -   ヨブ38:41 からすの子が神に向かって呼ばわり、／食物がなくて、さまようとき、／からすにえさを与える者はだれか。
    -   詩篇147:8,9 主は雲をもって天をおおい、地のために雨を備え、／もろもろの山に草をはえさせ、9 食物を獣に与え、／また鳴く小がらすに与えられる。 
-   寿命を伸ばす：
    -   詩篇39:6 まことに人は影のように、さまよいます。まことに彼らはむなしい事のために／騒ぎまわるのです。彼は積みたくわえるけれども、／だれがそれを収めるかを知りません。 
-   テモテ前書6:17-19 この世で富んでいる者たちに、命じなさい。高慢にならず、たよりにならない富に望みをおかず、むしろ、わたしたちにすべての物を豊かに備えて楽しませて下さる神に、のぞみをおくように、18 また、良い行いをし、良いわざに富み、惜しみなく施し、人に分け与えることを喜び、19 こうして、真のいのちを得るために、未来に備えてよい土台を自分のために築き上げるように、命じなさい。
-   ルカ16:9 またあなたがたに言うが、不正の富を用いてでも、自分のために友だちをつくるがよい。そうすれば、富が無くなった場合、あなたがたを永遠のすまいに迎えてくれるであろう。
-   「あなたの目が澄んでおれば（ὁ ὀφθαλμός σου ἁπλοῦς[^manza-2]）」は、単一、単純、シングル・アイ「あなたの目が悪ければ（ὁ ὀφθαλμός σου πονηρὸς[^manza-3]）」雑念や口実から、可哀想な人を可哀想でないかのように見過ごし、物惜しみをする目
-   テモテ前書6:9,10 富むことを願い求める者は、誘惑と、わなとに陥り、また、人を滅びと破壊とに沈ませる、無分別な恐ろしいさまざまの情欲に陷るのである。10 銭を愛することは、すべての悪の根である。ある人々は欲ばって金銭を求めたため、信仰から迷い出て、多くの苦痛をもって自分自身を刺しとおした。
-   詩篇37:25 わたしは、むかし年若かった時も、年老いた今も、／正しい人が捨てられ、あるいはその子孫が／食物を請いあるくのを見たことがない。 
-   詩篇68:19 日々にわれらの荷を負われる主はほむべきかな。神はわれらの救である。〔セラ 
-   詩篇31:15 わたしの時はあなたのみ手にあります。わたしをわたしの敵の手と、／わたしを責め立てる者から救い出してください。 
-   詩篇95:7 主はわれらの神であり、／われらはその牧の民、そのみ手の羊である。どうか、あなたがたは、／きょう、そのみ声を聞くように。 
-   コロサイ3:1,2 このように、あなたがたはキリストと共によみがえらされたのだから、上にあるものを求めなさい。そこではキリストが神の右に座しておられるのである。2 あなたがたは上にあるものを思うべきであって、地上のものに心を引かれてはならない。

[^manza-1]: μεριμνάω: i) to be anxious - to be troubled with cares, ii) to care for, look out for (a thing) - to seek to promote one's interests, caring or providing for. STRONGS: to be drawn in different directions, distraction

[^manza-2]: ἁπλοῦς: i) simple, single, ii) whole, iii) good fulfilling its office, sound - of the eye

[^manza-3]: πονηρός: i) full of labours, annoyances, hardships, ii) bad, of a bad nature or condition

#### **記録**

-   日時：2023年11月4日午後7時半〜9時半

-   出席 11名

#### **問いについて**

1.  「愚かな金持ち」のたとえと、この箇所は、誰に向けて。

    -   「それだから」（22）と繋がっているようである。

    -   「愚かな金持ち」のたとえは、群衆の中の質問をしたひとりと、「人々」（13,15）、この箇所は、弟子たち。（22）

    -   \[DQ\] マタイではどうでしょうか。

        -   マタイ5:1 イエスはこの群衆を見て、山に登り、座につかれると、弟子たちがみもとに近寄ってきた。

        -   マタイ7:28,29 イエスがこれらの言を語り終えられると、群衆はその教にひどく驚いた。29 それは律法学者たちのようにではなく、権威ある者のように、教えられたからである。

2.  思い煩いとは？ どのようなことに思い煩うか。

    -   「何を食べようか」と、命のことで思いわずらい、「何を着ようか」とからだのことで思いわずらうな。

    -   「命は食物にまさり、からだは着物にまさっている。」大切なことをなおざりにする？

3.  なぜ思い煩わなくて良いか。なぜ思い煩ってはいけないか。

    -   24 からすのことを考えて見よ。まくことも、刈ることもせず、また、納屋もなく倉もない。それだのに、神は彼らを養っていて下さる。あなたがたは鳥よりも、はるかにすぐれているではないか。25 あなたがたのうち、だれが思いわずらったからとて、自分の寿命をわずかでも延ばすことができようか。26 そんな小さな事さえできないのに、どうしてほかのことを思いわずらうのか。27 野の花のことを考えて見るがよい。紡ぎもせず、織りもしない。しかし、あなたがたに言うが、栄華をきわめた時のソロモンでさえ、この花の一つほどにも着飾ってはいなかった。28 きょうは野にあって、あすは炉に投げ入れられる草でさえ、神はこのように装って下さるのなら、あなたがたに、それ以上よくしてくださらないはずがあろうか。ああ、信仰の薄い者たちよ。29 あなたがたも、何を食べ、何を飲もうかと、あくせくするな、また気を使うな。30 これらのものは皆、この世の異邦人が切に求めているものである。あなたがたの父は、これらのものがあなたがたに必要であることを、ご存じである。

    -   神が養っていてくださる。異邦人が求めていること。父は、必要をご存知。

    -   \[DQ\] 異邦人が求めていることとは、どのような意味で言っているのでしょうか。

    -   自分の寿命を延ばすことができない。

    -   \[DQ\] 天の父がわたしたちに必要なものをすべて知っているということは、あなたの生き方にどう影響しますか。

    -   \[DQ\] なりゆきに（自然に）まかせて何もしなくて良いということでしょうか。

4.  御国を求める（マタイ：神の国と神の義をと求める）とは。

    -   父が望まれることを求める。自分にたいして、地の人々に対して。

5.  天に宝をたくわえるとは。

    -   \[DQ\] 教会にたくさん、献金しなさいということでしょうか。

    -   \[DQ\] 神様のことばかり考えていなさいということでしょうか。

    -   かみさまがたいせつにされること、かみさまにとってたいせつな人々をたいせつにすることについて、考えること。行動すること。

    -   \[DQ\] 宝とは何でしょうか。

6.  マタイでは、ルカに加えて。

    -   マタイ6章19〜24節で、自分の宝を蓄えることについてどんなことを教えていますか。

        -   宝と金銭や富との違いは？「宝のあるところに心もあると言えるようなもの？」

        -   苦しい体験、病気、才能？

        -   虫がつかないように、丁寧に管理すれば良いのでしょうか。

    -   神と富とに仕えるとはどういうことでしょうか。

    -   どちらも、独裁君主だということでしょうか。

    -   神の国と神の義をと求めるとはどのようなことでしょうか。

#### **メモ**

-   マタイ6:1 「自分の義を、見られるために人の前で行わないように、注意しなさい。もし、そうしないと、天にいますあなたがたの父から報いを受けることがないであろう。」から始まり、施し（1-4）、祈り＋主の祈り（5-15）、断食（16-18）とあり、次にここに含まれる「天に宝を積みなさい」（19-21、ルカ12:33-34）「目は体の灯」（22-23、ルカ11:34-36）「神と富」（24、ルカ16:13）「思い煩うな」（25-34、ルカ12:22-32）と続く。

-   思い煩う（ルカ12:22,25,29, マタイ6:25,27,28,31,34,34）

-   神の養いに信頼し（23,24）、自己の無力を悟り（25,26）、父なる神の愛にすがって（27-30）

    -   なにはともあれ神の国を求める。

    -   施しをする。

-   ルカでは、弟子たちに語っているが、マタイの場合がそうであるように、周囲に、人々も居るのかも知れない。「貪欲」から「思い煩い」になっている。弟子たちが、神の御心を学ぶためには、または、イエスに従っていくためには、まさに、こころが分裂していてはいけないのだろう。同時に、自然から、学ぶことも教えている。聖書のことばだけではなく、あらゆるものから、学ぶこともできるのだろう。神様はさまざまな方法で、様々なものを通して、教えられる。フローレンス・ナイチンゲールの「神の考えを知るには、統計学を学ばなければいけません。そこに、神の目的を図る物差しがあるからです。」（'To understand God's thoughts we must study statistics, for these are the measure of his purpose. ' ）も、世界から、神の御心、目的を知る、一つの道を教えているのだろう。

### 聖書の会（４）「ぶどう園の労働者」のたとえ

#### マタイ 20章1-16節

> 1 天国は、ある家の主人が、自分のぶどう園に労働者を雇うために、夜が明けると同時に、出かけて行くようなものである。2 彼は労働者たちと、一日一デナリの約束をして、彼らをぶどう園に送った。3 それから九時ごろに出て行って、他の人々が市場で何もせずに立っているのを見た。4 そして、その人たちに言った、『あなたがたも、ぶどう園に行きなさい。相当な賃銀を払うから』。5 そこで、彼らは出かけて行った。主人はまた、十二時ごろと三時ごろとに出て行って、同じようにした。6 五時ごろまた出て行くと、まだ立っている人々を見たので、彼らに言った、『なぜ、何もしないで、一日中ここに立っていたのか』。7 彼らが『だれもわたしたちを雇ってくれませんから』と答えたので、その人々に言った、『あなたがたも、ぶどう園に行きなさい』。8 さて、夕方になって、ぶどう園の主人は管理人に言った、『労働者たちを呼びなさい。そして、最後にきた人々からはじめて順々に最初にきた人々にわたるように、賃銀を払ってやりなさい』。9 そこで、五時ごろに雇われた人々がきて、それぞれ一デナリずつもらった。10 ところが、最初の人々がきて、もっと多くもらえるだろうと思っていたのに、彼らも一デナリずつもらっただけであった。11 もらったとき、家の主人にむかって不平をもらして 12 言った、『この最後の者たちは一時間しか働かなかったのに、あなたは一日じゅう、労苦と暑さを辛抱したわたしたちと同じ扱いをなさいました』。13 そこで彼はそのひとりに答えて言った、『友よ、わたしはあなたに対して不正をしてはいない。あなたはわたしと一デナリの約束をしたではないか。14 自分の賃銀をもらって行きなさい。わたしは、この最後の者にもあなたと同様に払ってやりたいのだ。15 自分の物を自分がしたいようにするのは、当りまえではないか。それともわたしが気前よくしているので、ねたましく思うのか』。16 このように、あとの者は先になり、先の者はあとになるであろう」。

[マタイによる福音書20章1-16節福音書対照表](https://icu-hsuzuki.github.io/science/bible/extra/manza2023/Mt20_1-16.pdf)

#### **問い**

1.  この主人は、どんな目的のために何をしますか。（1,2）

2.  主人は、夜明け、九時、十二時、三時と五時ごろに、どのようなひとと、どのような約束をして、雇いますか。（3-7）

3.  主人はどのように、給与を払いますか。（8-10）

4.  最初に雇われた人たちはなぜ不平を言うのでしょう。（11）

5.  主人は、どのように応答していますか。（13-15）

6.  「このように、あとの者は先になり、先の者はあとになるであろう」は、そして、このたとえは、何を教えているのでしょうか。（16, 参照：マタイ19:27-30）

#### **参照**

-   冒頭は原語では、'Ὁμοία　γάρ ἐστιν　ἡ βασιλεία　τῶν οὐρανῶν　ἀνθρώπῳ οἰκοδεσπότῃ　ὅστιςἐξῆλθεν ἅμα πρωῒ μισθώσασθαι ἐργάτας εἰς τὸν ἀμπελῶνα αὐτοῦ' (NKJV For the kingdom of heaven is like a landowner who went out early in the morning to hire laborers for his vineyard.) とあり、前段 マタイ19:27-30 の例示になっている。

    -   参照：19:30 30 しかし、多くの先の者はあとになり、あとの者は先になるであろう。29:16 このように、あとの者は先になり、先の者はあとになるであろう」。

        -   同様の構造：マタイ7:16・7:20、24:42・25:13

-   マタイ19:27-30 そのとき、ペテロがイエスに答えて言った、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従いました。ついては、何がいただけるでしょうか」。28 イエスは彼らに言われた、「よく聞いておくがよい。世が改まって、人の子がその栄光の座につく時には、わたしに従ってきたあなたがたもまた、十二の位に座してイスラエルの十二の部族をさばくであろう。29 おおよそ、わたしの名のために、家、兄弟、姉妹、父、母、子、もしくは畑を捨てた者は、その幾倍もを受け、また永遠の生命を受けつぐであろう。30 しかし、多くの先の者はあとになり、あとの者は先になるであろう。（ここに続く）（誰が救われることができるのか（マタイ19:16-26））

-   1 自分のぶどう園に労働者を雇うために、夜が明けると同時に、出かけて行くようなものである。

    -   パレスチナでは身近な、雨期をすぐあとに控えた、忙しい、一刻を争うぶどうの収穫期を思わせる。

-   1デナリ：当時の労働者の一日の平均賃金だが、生活にはギリギリ

    -   資料によると 1デナリで、小さな10〜12切れのパン、3〜4デナリで、12L の小麦、15キロの小麦パンを焼ける。30デナリで、奴隷の衣服、100デナリで 牛1頭。（資料によって異なる）

-   ユダヤの労働時間は、朝の6時から夕方の6時までの12時間。

-   律法では、賃金は、その日のうちに支払うよう定められていた。

-   ルカ 23:42,43 そして言った、「イエスよ、あなたが御国の権威をもっておいでになる時には、わたしを思い出してください」。43 イエスは言われた、「よく言っておくが、あなたはきょう、わたしと一緒にパラダイスにいるであろう」。

-   コリント前書15:8-10 そして最後に、いわば、月足らずに生れたようなわたしにも、現れたのである。9 実際わたしは、神の教会を迫害したのであるから、使徒たちの中でいちばん小さい者であって、使徒と呼ばれる値うちのない者である。10 しかし、神の恵みによって、わたしは今日あるを得ているのである。そして、わたしに賜わった神の恵みはむだにならず、むしろ、わたしは彼らの中のだれよりも多く働いてきた。しかしそれは、わたし自身ではなく、わたしと共にあった神の恵みである。

-   ピリピ3:12-15 わたしがすでにそれを得たとか、すでに完全な者になっているとか言うのではなく、ただ捕えようとして追い求めているのである。そうするのは、キリスト・イエスによって捕えられているからである。13 兄弟たちよ。わたしはすでに捕えたとは思っていない。ただこの一事を努めている。すなわち、後のものを忘れ、前のものに向かってからだを伸ばしつつ、14 目標を目ざして走り、キリスト・イエスにおいて上に召して下さる神の賞与を得ようと努めているのである。15 だから、わたしたちの中で全き人たちは、そのように考えるべきである。しかし、あなたがたが違った考えを持っているなら、神はそのことも示して下さるであろう。

-   バークレイ：神が与えるのは賃金ではなくて贈り物であり、報酬ではなくて恩寵である。

#### **記録**

-   日時：2023年11月5日午前8時15分〜10時半

-   出席 11名

#### **問いについて**

1.  主人は何のために何をするか。

    -   1 天国は、ある家の主人が、自分のぶどう園に労働者を雇うために、夜が明けると同時に、出かけて行くようなものである。2 彼は労働者たちと、一日一デナリの約束をして、彼らをぶどう園に送った。

    -   \[DQ\] ぶどう園に送るとは、どのようなことを意味しているのでしょうか。

    -   \[DQ\] 働かせること？ 主人は、何も労働しないのでしょうか。

2.  夜明け、九時、十二時、三時と五時ごろに、誰と、どのような約束で、雇うか。

    -   3 それから九時ごろに出て行って、他の人々が市場で何もせずに立っているのを見た。4 そして、その人たちに言った、『あなたがたも、ぶどう園に行きなさい。相当な賃銀を払うから』。5 そこで、彼らは出かけて行った。主人はまた、十二時ごろと三時ごろとに出て行って、同じようにした。6 五時ごろまた出て行くと、まだ立っている人々を見たので、彼らに言った、『なぜ、何もしないで、一日中ここに立っていたのか』。7 彼らが『だれもわたしたちを雇ってくれませんから』と答えたので、その人々に言った、『あなたがたも、ぶどう園に行きなさい』。

        -   夜明け（と同時）：労働者たちと、一日一デナリの約束をして、彼らをぶどう園に送った。

        -   九時：他の人々が市場で何もせずに立っているのを見た。『あなたがたも、ぶどう園に行きなさい。相当な賃銀を払うから』。（一デナリとは言っていない）

        -   十二時：同じようにした

        -   三時：同じようにした

        -   五時：まだ立っている人々を見たので、彼らに言った、『なぜ、何もしないで、一日中ここに立っていたのか』。彼らが『だれもわたしたちを雇ってくれませんから』と答えたので、その人々に言った、『あなたがたも、ぶどう園に行きなさい』。

    -   朝早くから雇ってもらうように、市場に立っていた人がいる一方、九時、十二時、三時、五時のひとたちは、そこまでの努力をしていないように見える。背後に何があるかはわからない。五時の人々に「一日中、立っていたのか」と聞いているので、出会いが無かったのかも知れない。他にも雇う人はいたかも知れず、根こそぎ雇うことはしていないのかも知れない。

    -   この管理人は、足繁く、市場に労働者を雇いに行っている。人手が足りないからだろうか。資本を湯水のように使って、貪欲に、仕事を進ませるためだろうか。おそらく、そうではない。天国のたとえなので、天国に向かい入れよう、永遠の生命を与えたいというのが、この管理人の本来の目的なのだろう。

3.  給与の払い方

    -   8 さて、夕方になって、ぶどう園の主人は管理人に言った、『労働者たちを呼びなさい。そして、最後にきた人々からはじめて順々に最初にきた人々にわたるように、賃銀を払ってやりなさい』。9 そこで、五時ごろに雇われた人々がきて、それぞれ一デナリずつもらった。10 ところが、最初の人々がきて、もっと多くもらえるだろうと思っていたのに、彼らも一デナリずつもらっただけであった。

    -   \[DQ\] なぜ、最後にきた人々から払うように命じたのでしょうか。演出的効果を上げるためだろうか。おそらくそうではない。仕事にありつけてよかったね。一日の報酬を上げるよ。

    -   \[DQ\] それぞれの人達はどう思ったでしょうか。

4.  最初に雇われた人たちの不平

    -   11 もらったとき、家の主人にむかって不平をもらして 12 言った、『この最後の者たちは一時間しか働かなかったのに、あなたは一日じゅう、労苦と暑さを辛抱したわたしたちと同じ扱いをなさいました』。

    -   ある観点からの公平さを考えると、この人たちの言い分は正しい。何が違うのだろうか。大切にする観点？他者理解？

    -   放蕩息子のたとえの兄（ルカ15:11-32）

    -   ずっと、サボっていたかも知れない。そうであってもだろうか。

5.  主人の応答

    -   13 そこで彼はそのひとりに答えて言った、『友よ、わたしはあなたに対して不正をしてはいない。あなたはわたしと一デナリの約束をしたではないか。14 自分の賃銀をもらって行きなさい。わたしは、この最後の者にもあなたと同様に払ってやりたいのだ。15 自分の物を自分がしたいようにするのは、当りまえではないか。それともわたしが気前よくしているので、ねたましく思うのか』。

    -   不正は含まれていないことをまずは、主張している。

    -   ここでは、主人が Generous（気前がよい）ことに視点を当てているが、その「恵みのみ」なのだろうか。

    -   \[DQ\] 主人は、なぜ、そうしたかったのだろうか。妬みを起こさせるため？ ではないだろう。大切にしたかったことは。神の性質とは。

6.  何を教えているか。（参照：マタイ19:27-30）

    -   「このように、あとの者は先になり、先の者はあとになるであろう」（16）

    -   直接的には、先の者は、最後に一デナリもらい、喜べず、不平をいうということで、主人のこころを受け取れない。後のものは、一日分の、給与をもらい、喜ぶ。

    -   直接的には弟子たちに。それとも、一般の人向けに。それとも普遍的な真理。

    -   ひとには、簡単には見えない、社会的不公正の中で、ひとは生きている。御心をもとめること、御心を行うことは、それほど簡単ではない。

#### **メモ**

-   背景

    -   金持ちの青年（19:16-30, マルコ10:17-31, ルカ18:18-30）の最後の部分に、ペテロが「そのとき、ペテロがイエスに答えて言った、『ごらんなさい、わたしたちはいっさいを捨てて、あなたに従いました。ついては、何がいただけるでしょうか』。」（19:27）と問い、「38 イエスは彼らに言われた、『よく聞いておくがよい。世が改まって、人の子がその栄光の座につく時には、わたしに従ってきたあなたがたもまた、十二の位に座してイスラエルの十二の部族をさばくであろう。29 おおよそ、わたしの名のために、家、兄弟、姉妹、父、母、子、もしくは畑を捨てた者は、その幾倍もを受け、また永遠の生命を受けつぐであろう。30 しかし、多くの先の者はあとになり、あとの者は先になるであろう。』」（19:28-30）に続いている。

        -   イエスの率直な答えと、普遍化と、注意すべきこととして、たとえが配置されている。

        -   そう考えると、一デナリは、永遠の生命を意味しているようである。直接的には結びつかないかも知れない。

        -   十二弟子を持ち上げておいて、最後に「しかし、多くの先の者はあとになり、あとの者は先になるであろう。」とする。なかなか、注意深い言説である。

        -   29節までは、マルコにも、ルカにも含まれるが、30節は、マルコのみ。マルコでは、このあと、三度自分の死と復活を予告するが続き、そのあとに、ヤコブとヨハネの願いが、続いている。ルカでは、やはり、三度自分の死と復活を予告するが続き、エリコの近くで盲人を癒やす記事を経て、ザアカイの記事に至る。

    -   場面設定：天国に関するたとえ。

    -   登場人物：ある家の主人（1）、ぶどう園で働く労働者（6時、9時、12時、3時、5時）、管理人（8）

-   19:27 「そのとき、ペテロがイエスに答えて言った、『ごらんなさい、わたしたちはいっさいを捨てて、あなたに従いました。ついては、何がいただけるでしょうか』。」に対して、神の国の様子を描き出すことで、柔らかく否定しているように見える。

-   神の国の平等・公平と恵みの関係について考えさせられる。

-   どのひとも、一日、１デナリは必要である。一人ひとりが大切。どんな理由であっても、一デナリ受け取ることは感謝。しかし、その基準は、公平さや、平等さでは、表現できないものだろう。

-   問題点は見えても、解決方法、完全な公平さは、わからないもの。神の国では、基本的な、正しさは確保されるものの、なぜまでは、表現できないかも知れない。わからない部分があることを、覚えなさいということだろうか。

-   背景（19:16-30）に戻って、考えるべき。（マルコで学ぶ予定）

-   天国の法則に目が開かれることは、世界が広くなることでもあると思う。
