# マルコによる福音書の学び {#markdq}

2023年4月に再開した、聖書の会の記録です。マルコによる福音書を学ぶとしていますが、特徴として、他の福音書に並行箇所があるときには、その箇所も比較して読み、考え、共に、問いについて語りあう、形式で進めています。聖書の引用は、口語訳を主としています。厳密に理解しているわけではありませんが、多少、著作権にも配慮してと言うことです。ただ、口語訳には、表題がついていませんから、現在わたしが使っている聖書協会共同訳の表題を並べて、並行箇所にあるものを参照しています。ヨハネによる福音書は、通常並行箇所としては、出てきませんが、背景を知るためには、重要な証言が得られることもあるので、あわせて読むことにしています。なお、マルコを中心とした並行箇所については、資料の[マルコによる福音書表題](https://icu-hsuzuki.github.io/biblestudy/tables.html#mark-titles)に表にしてまとめてあります。

下には、基本的に、聖書箇所、問い（ディスカッション・クエスチョン）、参照箇所、日にちと、出席者（対面）・参加者（遠隔）人数の記録、メモ（個人的感想を含む）を書いていきます。

一般的に知られていることや、原語についてコメントすることもありますが、寄り道で、皆で考えながら読んでいくという中心から、あまり外れてほしくないので、それは、[共観福音書](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html)に書くようにしていきます。自分でも問いを持ちながら、読んでいっていただければ幸いです。

これをお読みのみなさんの学びの一助となることを願っています。

## マルコによる福音書について

> 1:1 神の子イエス・キリストの福音のはじめ。 

### 問い

1.  どのようなことばで始まりますか。

    -   気づいたことを挙げてみましょう。

2.  他の福音書とくらべるとどんなことがわかりますか。

    -   [マルコによる福音書の表題](https://icu-hsuzuki.github.io/science/bible/docs/mark.pdf)

    -   なぜ、マルコはこのように始めているのでしょうか。

3.  [パピアス](aboutmark.qmd#papius)はどのようなことを証言していますか。

4.  パウロの手紙との違いについてどんなことに気付きますか。

    -   ローマ人への手紙以降はたくさんのパウロの手紙が収められていますが、パウロとはどのような人ですか。

    -   パウロの手紙について知っていることを挙げてみましょう。

5.  「福音のはじめ」でどのようなことを伝えたかったのでしょうか。

    -   「福音のはじめ」からはどのようなことをイメージしますか。

    -   あなたなら、誰かについて伝えようとする時どのようなことをたいせつにしますか。

### 参照

-   Ἀρχὴ τοῦ εὐαγγελίου Ἰησοῦ Χριστοῦ \[υἱοῦ θεοῦ\].

    -   [Deutsche Bible Gesellschaft](https://www.academic-bible.com/en/online-bibles/novum-testamentum-graece-na-28/read-the-bible-text/bibel/text/lesen/stelle/51/10001/19999/ch/418f354347a79b322324823db62504dc/)

    -   [Blue Letter Bible](https://www.blueletterbible.org/nkjv/mar/1/1/s_958001)

-   聖書の中の（ヨハネ）マルコ：使徒12:12, 12:25, 15:37, 15:39, コロサイ4:10, 2テモテ4:11, ピレモン24, 1ペテロ5:13

### 記録

-   日時：2023年4月20日午後7時半〜9時半

-   出席（対面）7名、参加（遠隔）6名

### 問いについて

### メモ

-   「はじめ Ἀρχὴ」は、原点という意味もあるが、どこをはじめとするか、福音のはじめでなにを語ろうとしているのか考えた。

-   創世記やヨハネによる福音書の「はじめに」も、想起させる。

-   マタイやルカのように誕生からはじめてはいない。マタイ、ルカ、それぞれの特徴があり、マタイは十二弟子であるが、説教は独自資料だが、話はほとんどマルコを踏襲している。地名や人数など、細かいところで、いくつかマルコとは違うことを書いている。

-   ヨハネと共観福音書では、ゲッセマネで捉えられるところの表現が異なっており、ヨハネでは、イエスが弟子たちを逃したという記述、マルコなどでは弟子たちが逃げたという記述になっている。ペトロとヨハネの受け取り方の違いが、現れているのかもしれない。

-   パピアスも読みながら、教父の一人がつたえたマルコによる福音書について確認した。

-   著者について、[著者などについて](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#mark-author-ai)の AI の答えも見ながら、いろいろな説があることも確認した。以下、マルコ由来として、マルコが書いたとの書き方をするが、そのように断定しているわけではないことを断っておく。

-   パウロ書簡との違い、焦点の合わせ方の違いとともに、マルコ（この書）がつたえる、福音のはじめの原点の取り方が、福音書の特徴でもある。

-   使徒行伝によると、パウロとマルコは、ある時を境に一緒に行動しなくなっている。パウロ由来の手紙とされる著者について議論がある手紙のなかでは、マルコが、パウロと一緒にいることを証言するものもある。

-   マルコでは贖罪については、10章45節「人の子がきたのも、仕えられるためではなく、仕えるためであり、また多くの人のあがないとして、自分の命を与えるためである」ぐらいしか書かれていない。

-   パウロ書簡が伝えるキリスト・イエスと、マルコの伝えるイエス・キリストの違いとともに、それがキリスト教会の分裂にはなっていないこと、福音書の違いもたいせつなものとして味わえると良い。

-   私なら、何をたいせつにして、伝えるだろうか。少しずつ読みながら、考えていきたい。

## 1:1-8 洗礼者ヨハネ、悔い改めの洗礼を宣べ伝える

> 1:1 神の子イエス・キリストの福音のはじめ。 2 預言者イザヤの書に、／「見よ、わたしは使をあなたの先につかわし、／あなたの道を整えさせるであろう。3 荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と書いてあるように、4 バプテスマのヨハネが荒野に現れて、罪のゆるしを得させる悔改めのバプテスマを宣べ伝えていた。 5 そこで、ユダヤ全土とエルサレムの全住民とが、彼のもとにぞくぞくと出て行って、自分の罪を告白し、ヨルダン川でヨハネからバプテスマを受けた。 6 このヨハネは、らくだの毛ごろもを身にまとい、腰に皮の帯をしめ、いなごと野蜜とを食物としていた。7 彼は宣べ伝えて言った、「わたしよりも力のあるかたが、あとからおいでになる。わたしはかがんで、そのくつのひもを解く値うちもない。 8 わたしは水でバプテスマを授けたが、このかたは、聖霊によってバプテスマをお授けになるであろう」。

### マタイ3:1-12

> 3:1 そのころ、バプテスマのヨハネが現れ、ユダヤの荒野で教を宣べて言った、 2 「悔い改めよ、天国は近づいた」。3 預言者イザヤによって、「荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と言われたのは、この人のことである。 4 このヨハネは、らくだの毛ごろもを着物にし、腰に皮の帯をしめ、いなごと野蜜とを食物としていた。 5 すると、エルサレムとユダヤ全土とヨルダン附近一帯の人々が、ぞくぞくとヨハネのところに出てきて、6 自分の罪を告白し、ヨルダン川でヨハネからバプテスマを受けた。7 ヨハネは、パリサイ人やサドカイ人が大ぜいバプテスマを受けようとしてきたのを見て、彼らに言った、「まむしの子らよ、迫ってきている神の怒りから、おまえたちはのがれられると、だれが教えたのか。 8 だから、悔改めにふさわしい実を結べ。9 自分たちの父にはアブラハムがあるなどと、心の中で思ってもみるな。おまえたちに言っておく、神はこれらの石ころからでも、アブラハムの子を起すことができるのだ。 10 斧がすでに木の根もとに置かれている。だから、良い実を結ばない木はことごとく切られて、火の中に投げ込まれるのだ。11 わたしは悔改めのために、水でおまえたちにバプテスマを授けている。しかし、わたしのあとから来る人はわたしよりも力のあるかたで、わたしはそのくつをぬがせてあげる値うちもない。このかたは、聖霊と火とによっておまえたちにバプテスマをお授けになるであろう。 12 また、箕を手に持って、打ち場の麦をふるい分け、麦は倉に納め、からは消えない火で焼き捨てるであろう」。

### ルカ3:1-9

> 3:1 皇帝テベリオ在位[^markdq-1]の第十五年、ポンテオ・ピラトがユダヤの総督[^markdq-2]、ヘロデがガリラヤの領主、その兄弟ピリポがイツリヤ・テラコニテ地方の領主、ルサニヤがアビレネの領主、 2 アンナスとカヤパとが大祭司であったとき、神の言が荒野でザカリヤの子ヨハネに臨んだ。3 彼はヨルダンのほとりの全地方に行って、罪のゆるしを得させる悔改めのバプテスマを宣べ伝えた。4 それは、預言者イザヤの言葉の書に書いてあるとおりである。すなわち／「荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』。5 すべての谷は埋められ、／すべての山と丘とは、平らにされ、／曲ったところはまっすぐに、／わるい道はならされ、 6 人はみな神の救を見るであろう」。 7 さて、ヨハネは、彼からバプテスマを受けようとして出てきた群衆にむかって言った、「まむしの子らよ、迫ってきている神の怒りから、のがれられると、おまえたちにだれが教えたのか。 8 だから、悔改めにふさわしい実を結べ。自分たちの父にはアブラハムがあるなどと、心の中で思ってもみるな。おまえたちに言っておく。神はこれらの石ころからでも、アブラハムの子を起すことができるのだ。9 斧がすでに木の根もとに置かれている。だから、良い実を結ばない木はことごとく切られて、火の中に投げ込まれるのだ」。 

[^markdq-1]: Tiberius Julius Caesar Augustus: 17 September 14 -- 16 March 37 (Wikipedia)

[^markdq-2]: Pontius Pilate: In office 26AD-36AD

### ヨハネ1:19-28

> 1:19 さて、ユダヤ人たちが、エルサレムから祭司たちやレビ人たちをヨハネのもとにつかわして、「あなたはどなたですか」と問わせたが、その時ヨハネが立てたあかしは、こうであった。 20 すなわち、彼は告白して否まず、「わたしはキリストではない」と告白した。21 そこで、彼らは問うた、「それでは、どなたなのですか、あなたはエリヤですか」。彼は「いや、そうではない」と言った。「では、あの預言者ですか」。彼は「いいえ」と答えた。22 そこで、彼らは言った、「あなたはどなたですか。わたしたちをつかわした人々に、答えを持って行けるようにしていただきたい。あなた自身をだれだと考えるのですか」。 23 彼は言った、「わたしは、預言者イザヤが言ったように、『主の道をまっすぐにせよと荒野で呼ばわる者の声』である」。 24 つかわされた人たちは、パリサイ人であった。 25 彼らはヨハネに問うて言った、「では、あなたがキリストでもエリヤでもまたあの預言者でもないのなら、なぜバプテスマを授けるのですか」。26 ヨハネは彼らに答えて言った、「わたしは水でバプテスマを授けるが、あなたがたの知らないかたが、あなたがたの中に立っておられる。27 それがわたしのあとにおいでになる方であって、わたしはその人のくつのひもを解く値うちもない」。28 これらのことは、ヨハネがバプテスマを授けていたヨルダンの向こうのベタニヤであったのである。

[マルコによる福音書1章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_1-8.pdf)

### 問い

1.  2,3 節の引用では「使（つかい）」について何と預言していますか。

    -   \[参照\] マラキ3:1　見よ、わたしはわが使者をつかわす。彼はわたしの前に道を備える。またあなたがたが求める所の主は、たちまちその宮に来る。見よ、あなたがたの喜ぶ契約の使者が来ると、万軍の主が言われる。

    -   \[参照\] イザヤ40:3　呼ばわる者の声がする、／「荒野に主の道を備え、／さばくに、われわれの神のために、／大路をまっすぐにせよ。

    -   なぜ「荒野」なのでしょうか。

2.  ヨハネはどのような人ですか。どのような活動をしますか。

    -   バプテスマのヨハネは、「使」の旧約聖書の預言をどのように成し遂げていますか。

    -   ヨハネの働きは、メシヤを迎えるために人々の心をどのように整えるのでしょうか。悔い改めることは、救い主を迎えるのにどう整えるのでしょうか。やがて来る方とどのような違いがありますか。

3.  他の福音書などの記述と比較して気づいたことを挙げてみましょう。

    -   バプテスマのヨハネについてほかに知っていることはありますか。

4.  「福音のはじめ」として、旧約聖書から引用し、バプテスマのヨハネの活動について書いていますが、なぜ、旧約聖書との関係から、始めたのでしょうか。

5.  主の道を整える・備えるとは、どのようなことで、主の道が整っているとは、どのような状態なのでしょうか。現代は、世界は、そしてあなたへの主の道は整っていますか。

### 参照

-   聖書の中のバプテスマのヨハネ

    -   \[参照\] ルカ1:5-25[^markdq-3]、1:57-80[^markdq-4]、マルコ6:14-29[^markdq-5]（マタイ14:1-12、ルカ9:7-9）、マルコ8:27-30[^markdq-6]（マタイ16:13-20、ルカ9:18-21）、マルコ11:27-33[^markdq-7]（マタイ21:23-27、ルカ20:1-8）、マタイ11:2-19[^markdq-8]（ルカ7:18-35）、マタイ17:10-13[^markdq-9]、ヨハネ1:29-51

    -   \[参照\] 使徒1:5, 22、10:37、11:16、13:24、18:24-27[^markdq-10]、19:1-5[^markdq-11]

[^markdq-3]: 洗礼者ヨハネの誕生、予告される

[^markdq-4]: 洗礼者ヨハネの誕生, 1:80 幼な子は成長し、その霊も強くなり、そしてイスラエルに現れる日まで、荒野にいた。

[^markdq-5]: 洗礼者ヨハネ殺される

[^markdq-6]: ペトロ、イエスがメシアであると告白する

[^markdq-7]: 権威についての問答

[^markdq-8]: 洗礼者ヨハネとイエス

[^markdq-9]: 13 そのとき、弟子たちは、イエスがバプテスマのヨハネのことを言われたのだと悟った。 

[^markdq-10]: 25この人は主の道に通じており、また、霊に燃えてイエスのことを詳しく語ったり教えたりしていたが、ただヨハネのバプテスマしか知っていなかった。 

[^markdq-11]: 4b 「ヨハネは悔改めのバプテスマを授けたが、それによって、自分のあとに来るかた、すなわち、イエスを信じるように、人々に勧めたのである」。 

> **1** Ἀρχὴ τοῦ εὐαγγελίου Ἰησοῦ Χριστοῦ \[υἱοῦ θεοῦ\].
>
> **2** Καθὼς γέγραπται ἐν τῷ Ἠσαΐᾳ τῷ προφήτῃ· \
> *ἰδοὺ ἀποστέλλω τὸν ἄγγελόν μου πρὸ προσώπου σου,* 
>
> *ὃς κατασκευάσει τὴν ὁδόν* σου·
>
> **3** *φωνὴ βοῶντος ἐν τῇ ἐρήμῳ·* \
> *ἑτοιμάσατε*[^markdq-12] *τὴν ὁδὸν κυρίου,* \
> *εὐθείας ποιεῖτε τὰς τρίβους* αὐτοῦ,
>
> **4** ἐγένετο Ἰωάννης \[ὁ\] βαπτίζων ἐν τῇ ἐρήμῳ καὶ κηρύσσων βάπτισμα μετανοίας[^markdq-13] εἰς ἄφεσιν[^markdq-14] ἁμαρτιῶν[^markdq-15].
>
> **5** καὶ ἐξεπορεύετο πρὸς αὐτὸν πᾶσα ἡ Ἰουδαία χώρα καὶ οἱ Ἱεροσολυμῖται πάντες, καὶ ἐβαπτίζοντο ὑπ' αὐτοῦ ἐν τῷ Ἰορδάνῃ ποταμῷ ἐξομολογούμενοι τὰς ἁμαρτίας αὐτῶν.
>
> **6** καὶ ἦν ὁ Ἰωάννης ἐνδεδυμένος τρίχας καμήλου καὶ ζώνην δερματίνην περὶ τὴν ὀσφὺν αὐτοῦ καὶ ἐσθίων ἀκρίδας καὶ μέλι ἄγριον.
>
> **7** Καὶ ἐκήρυσσεν[^markdq-16] λέγων· ἔρχεται ὁ ἰσχυρότερός μου ὀπίσω μου, οὗ οὐκ εἰμὶ ἱκανὸς κύψας λῦσαι τὸν ἱμάντα τῶν ὑποδημάτων αὐτοῦ.
>
> **8** ἐγὼ ἐβάπτισα ὑμᾶς ὕδατι, αὐτὸς δὲ βαπτίσει ὑμᾶς ἐν πνεύματι ἁγίῳ.

[^markdq-12]: ἑτοιμάζω: to make ready, prepare

[^markdq-13]: μετάνοια: a change of mind, as it appears to one who repents, of a purpose he has formed or of something he has done

[^markdq-14]: ἄφεσις: i) release from bondage or imprisonment, ii) forgiveness or pardon, of sins (letting them go as if they had never been committed), remission of the penalty

[^markdq-15]: ἁμαρτία: i) to be without a share in, ii) to miss the mark, iii) to err, be mistaken, iv) to miss or wander from the path of uprightness and honour, to do or go wrong, v) to wander from the law of God, violate God's law, sin. \[Strong\] In Greek writings, 1st, an error of the understanding, 2nd, a bad action, evil deed.

[^markdq-16]: κηρύσσω: i) to be a herald, to officiate as a herald, ii) to publish, proclaim openly: something which has been done

### 記録

-   日時：2023年4月27日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）8名

### 問いについて

### メモ

-   マルコ1:2 の預言はイザヤではなく、マラキ。これは、マタイ、ルカでは修正され、マルコ1:3 の部分だけをイザヤとしている。内部でも修正が議論されたのだろう。ただ、マタイ17:11-13 には、エリヤが先に来るとのことが語られている。マラキの預言が旧約聖書最大の預言者と言われるエリヤがまず来ることと理解されていたのだろう。そして、そのことは、ヨハネ1:21にも反映されており、こちらでは、バプテスマのヨハネは、自分がエリヤであることを否定している。また、荒野で呼ばわる者の声と証言しているのは、バプテスマのヨハネ自身であることもわかる。

-   バプテスマのヨハネについては、使徒の記録（18章、19章）にもあるように、一般によく知られており、ルカの記述によれば、祭司ザカリヤとエリザベトの子、マリヤとも親戚関係と書かれている。ヨハネが祭司の子であったことは、おそらく、よく知られていた事実だと思われるので、そのような人が幼少から、荒野におり（ルカ1:80）それから、語り始めたところを見ると、民にも大きな影響を与える存在であったことがわかる。出自に関しては、イエスとはかなりことなる。

-   ユダヤ全土と、エルサレムの全住民が彼のもとに集まってきていることは、ヨハネの知名度もあったろうが、霊的渇望、社会状況・政治状況からも問題を抱えていた人が多かったのだろう。ただ、マタイ（対象はパリサイ人はサドカイ人）やルカ（一般の人たち・限定なし）への厳しい言葉を見ると、我も我もと集まる中に、悔い改めという自らを省みる部分が欠落していたひとたちも多かったのだろう。それが、救いと裁きという厳しさに現れている。

-   「わたしはかがんで、そのくつのひもを解く値打ちもない（奴隷の仕事）」（7）と証言することによって、「あなたの道」（2）のやがてきてるべき方との大きな差を表現している。

-   「神はこれらの石ころからでも、アブラハムの子を起こすことができる」（マタイ3:9, ルカ3:8）は、アブラハムの子であることを誇りと思っていて、異邦人を心の中で差別していた人には、かなり厳しく聞こえただろう。

-   主の道を整えるが何を意味するかは難しい。一般論ではなく、一人ひとりがその語り掛けを聞くものなのだろうか。現代でも、同じように、主の道が整っているとは言えないが、主の道が整っている人に、主のことばが撒かれると、成長して、何倍にもなるのかもしれない。判定条件があるわけではないだろう。

## 1:9-11 イエス、洗礼を受ける

> 1:9 そのころ、イエスはガリラヤのナザレから出てきて、ヨルダン川で、ヨハネからバプテスマをお受けになった。10 そして、水の中から上がられるとすぐ、天が裂けて、聖霊がはとのように自分に下って来るのを、ごらんになった。 11 すると天から声があった、「あなたはわたしの愛する子、わたしの心にかなう者である」。

### マタイ3:13-17

> 3:13 そのときイエスは、ガリラヤを出てヨルダン川に現れ、ヨハネのところにきて、バプテスマを受けようとされた。14 ところがヨハネは、それを思いとどまらせようとして言った、「わたしこそあなたからバプテスマを受けるはずですのに、あなたがわたしのところにおいでになるのですか」。 15 しかし、イエスは答えて言われた、「今は受けさせてもらいたい。このように、すべての正しいことを成就するのは、われわれにふさわしいことである」。そこでヨハネはイエスの言われるとおりにした。16 イエスはバプテスマを受けるとすぐ、水から上がられた。すると、見よ、天が開け、神の御霊がはとのように自分の上に下ってくるのを、ごらんになった。 17 また天から声があって言った、「これはわたしの愛する子、わたしの心にかなう者である」。

### ルカ3:21-22

> 3:21 さて、民衆がみなバプテスマを受けたとき、イエスもバプテスマを受けて祈っておられると、天が開けて、22 聖霊がはとのような姿をとってイエスの上に下り、そして天から声がした、「あなたはわたしの愛する子、わたしの心にかなう者である」。 

### \[ヨハネ1:29-34\]

> 1:29 その翌日、ヨハネはイエスが自分の方にこられるのを見て言った、「見よ、世の罪を取り除く神の小羊。30 『わたしのあとに来るかたは、わたしよりもすぐれたかたである。わたしよりも先におられたからである』とわたしが言ったのは、この人のことである。 31 わたしはこのかたを知らなかった。しかし、このかたがイスラエルに現れてくださるそのことのために、わたしはきて、水でバプテスマを授けているのである」。 32 ヨハネはまたあかしをして言った、「わたしは、御霊がはとのように天から下って、彼の上にとどまるのを見た。 33 わたしはこの人を知らなかった。しかし、水でバプテスマを授けるようにと、わたしをおつかわしになったそのかたが、わたしに言われた、『ある人の上に、御霊が下ってとどまるのを見たら、その人こそは、御霊によってバプテスマを授けるかたである』。 34 わたしはそれを見たので、このかたこそ神の子であると、あかしをしたのである」。

[マルコによる福音書1章9-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_9-11.pdf)

### 問い

1.  地図で場所（ガリラヤ、ナザレ、ヨルダン川、エルサレム）を確認しましょう。

    -   \[参照\] [キリスト時代のパレスチナ](https://upload.wikimedia.org/wikipedia/commons/1/1f/JBS1956-B_map11.png) (Wikimedia: 聖書地図 (JBS1956))

    -   \[参照\] [John the Baptist](https://www.seektheoldpaths.com/Maps/106.jpg) (Halman Bible Atlas 106)

2.  イエスがバプテスマ（洗礼）を受けたことはどのように描かれていますか。

    -   マルコ、マタイ、ルカの共観福音書を比較して読んでみましょう。

    -   どんなことが共通に書かれていますか。

    -   それぞれどのような特徴と違いがありますか。

3.  10節11節はどのような状況を描いているのでしょうか。

4.  天からの声は何を意味しているのでしょうか。

    -   \[参照\] 11「あなたはわたしの愛する子、わたしの心にかなう者である」

5.  ヨハネ1:29-34 からは、どのようなことがわかりますか。

    -   四福音書で、聖霊が降るのを見たのは、そして天からの声を聞いたのは誰だと記されています。

6.  このできごとによって、なにを伝えようとしているのでしょうか。

    -   あなたは、どのように受け取りますか。

### 参照

#### 愛する子

-   マルコ9:7 すると、雲がわき起って彼らをおおった。そして、その雲の中から声があった、「これはわたしの**愛する子**である。これに聞け」。 

-   マタイ17:5 彼がまだ話し終えないうちに、たちまち、輝く雲が彼らをおおい、そして雲の中から声がした、「これはわたしの愛する子、わたしの心にかなう者である。これに聞け」。

-   2ペテロ1:17 イエスは父なる神からほまれと栄光とをお受けになったが、その時、おごそかな栄光の中から次のようなみ声がかかったのである、「これはわたしの愛する子、わたしの心にかなう者である」。

#### 神の子

-   マルコ1:1 神の子イエス・キリストの福音のはじめ。

-   マルコ3:11 また、けがれた霊どもはイエスを見るごとに、みまえにひれ伏し、叫んで、「あなたこそ**神の子**です」と言った。

-   マルコ5:7 大声で叫んで言った、「いと高き**神の子**イエスよ、あなたはわたしとなんの係わりがあるのです。神に誓ってお願いします。どうぞ、わたしを苦しめないでください」。 

-   マルコ15:39 イエスにむかって立っていた百卒長は、このようにして息をひきとられたのを見て言った、「まことに、この人は神の子であった」。

-   マタイ4:3, 6, 5:9, 8:29, 14:33, 16:16, 26:63, 27:40,43,54

-   ルカ1:35, 4:3, 9, 41, 8:28, 20:36, 22:70

-   ヨハネ1:12, 34, 49, 5:25, 28, 10:36, 11:4, 52, 19:7, 20:31

-   使徒8:37, 9:20, 17:29

-   その他多数

#### バプテスマ

-   マルコ10:38 イエスは言われた、「あなたがたは自分が何を求めているのか、わかっていない。あなたがたは、わたしが飲む杯を飲み、わたしが受ける**バプテスマ**を受けることができるか」。 39 彼らは「できます」と答えた。するとイエスは言われた、「あなたがたは、わたしが飲む杯を飲み、わたしが受ける**バプテスマ**を受けるであろう。 

-   マルコ11:30 ヨハネの**バプテスマ**は天からであったか、人からであったか、答えなさい」。 

-   マルコ16:16 信じて**バプテスマ**を受ける者は救われる。しかし、不信仰の者は罪に定められる。 

-   マタイ28:19 それゆえに、あなたがたは行って、すべての国民を弟子として、父と子と聖霊との名によって、彼らに**バプテスマ**を施し、

-   ヨハネ3:22 こののち、イエスは弟子たちとユダヤの地に行き、彼らと一緒にそこに滞在して、**バプテスマ**を授けておられた。 23 ヨハネもサリムに近いアイノンで、**バプテスマ**を授けていた。そこには水がたくさんあったからである。人々がぞくぞくとやってきて**バプテスマ**を受けていた。 

-   ヨハネ3:26 そこで彼らはヨハネのところにきて言った、「先生、ごらん下さい。ヨルダンの向こうであなたと一緒にいたことがあり、そして、あなたがあかしをしておられたあのかたが、**バプテスマ**を授けており、皆の者が、そのかたのところへ出かけています」。 

-   ヨハネ4:1 イエスが、ヨハネよりも多く弟子をつくり、また**バプテスマ**を授けておられるということを、パリサイ人たちが聞き、それを主が知られたとき、2 （しかし、イエスみずからが、**バプテスマ**をお授けになったのではなく、その弟子たちであった）

-   ヨハネ4:11 さて、イエスはまたヨルダンの向こう岸、すなわち、ヨハネが初めに**バプテスマ**を授けていた所に行き、そこに滞在しておられた。

-   使徒1:5 すなわち、ヨハネは水で**バプテスマ**を授けたが、あなたがたは間もなく聖霊によって、**バプテスマ**を授けられるであろう」。 

-   使徒2:38 すると、ペテロが答えた、「悔い改めなさい。そして、あなたがたひとりびとりが罪のゆるしを得るために、イエス・キリストの名によって、**バプテスマ**を受けなさい。そうすれば、あなたがたは聖霊の賜物を受けるであろう。 

-   使徒2:41 そこで、彼の勧めの言葉を受けいれた者たちは、**バプテスマ**を受けたが、その日、仲間に加わったものが三千人ほどあった。 

-   使徒8:12 ところが、ピリポが神の国とイエス・キリストの名について宣べ伝えるに及んで、男も女も信じて、ぞくぞくと**バプテスマ**を受けた。 

-   使徒8:13, 16, 36, 38, 9:18, 10:47, 48, 16:15, 33, 18:8, 25, 19:3, 4,5, 22:16

-   その他多数

> **9**Καὶ ἐγένετο ἐν ἐκείναις ταῖς ἡμέραις ἦλθεν Ἰησοῦς ἀπὸ Ναζαρὲτ τῆς Γαλιλαίας καὶ ἐβαπτίσθη εἰς τὸν Ἰορδάνην ὑπὸ Ἰωάννου. **10**καὶ εὐθὺς[^markdq-17] ἀναβαίνων[^markdq-18] ἐκ τοῦ ὕδατος εἶδεν σχιζομένους[^markdq-19] τοὺς οὐρανοὺς[^markdq-20] καὶ τὸ πνεῦμα ὡς περιστερὰν[^markdq-21] καταβαῖνον[^markdq-22] εἰς αὐτόν· **11**καὶ φωνὴ ἐγένετο ἐκ τῶν οὐρανῶν· σὺ εἶ ὁ υἱός μου ὁ ἀγαπητός[^markdq-23], ἐν σοὶ εὐδόκησα[^markdq-24].

[^markdq-17]: εὐθέως: straightway, immediately, forthwith (x40 in Mark)

[^markdq-18]: ἀναβαίνω: ascend; a) to go up, b) to rise, mount, be borne up, spring up

[^markdq-19]: σχίζω: i) to cleave, cleave asunder, rend, ii) to divide by rending, iii) to split into factions, be divided (Mark 15:38)

[^markdq-20]: οὐρανός: the vaulted expanse of the sky with all things visible in it. (The KJV translates heaven (268x), air (10x), sky (5x), heavenly (with G1537) (1x).)

[^markdq-21]: περιστερά: a dove (Mark 11:15)

[^markdq-22]: καταβαίνω: to go down, come down, descend

[^markdq-23]: ἀγαπητός: beloved, esteemed, dear, favourite, worthy of love (Mark 9:7, 12:6)

[^markdq-24]: εὐδοκέω: i) it seems good to one, is one's good pleasure a) think it good, choose, determine, decide, b) to do willingly, c) to be ready to, to prefer, choose rather ii) to be well pleased with, take pleasure in, to be favourably inclined towards one

### 記録

-   日時：2023年5月4日午後7時半〜9時半

-   出席（対面）11名、参加（遠隔）2名

### 問いについて

### メモ

-   マルコは「そのころ」とはじまっている。マルコに多い表現。

-   マタイでは、洗礼の前から、イエスが特別な存在だと、ヨハネは考えている。

-   共観福音書では、基本的に、「聖霊がはとのように自分に下って来るのを、ごらんになった。」のは、イエス。このあとの、言葉を聞いたのは、イエスだけかどうかは不明だが、イエスにとって、特別な経験だったことは、確かなのだろう。

-   「裂けて（σχίζω）」マルコ15:38 そのとき、神殿の幕が上から下まで真二つに裂けた。

-   ヨハネは、洗礼についての言及がなく、いつのことを語っているかは不明だが、御霊がイエスに降ったこと、それによって、御霊によってバプテスマを授ける方であることを知り、証したとなっている。特別なものを、ヨハネは、早い段階から、認めていたことの証言なのだろう。

-   イエスは、このときから、神の子となったのだろうか。「愛する子」とは、何を意味するのだろうか。誰のための証言なのだろうか。

-   「あなたはわたしの愛する子」と、天からの声を聞けば、神の子なのだろうか。

-   まだ、なにも活動する前に「愛する子」と宣言されることは、印象的。そこにこそ、神の愛を感じる。イエスは、間違いなく、神の愛を強く感じただろう。その証言として良いと思う。

## 1:12-13 試みを受ける

> 1:12 それからすぐに、御霊がイエスを荒野に追いやった。 13 イエスは四十日のあいだ荒野にいて、サタンの試みにあわれた。そして獣もそこにいたが、御使たちはイエスに仕えていた。

### マタイ 4:1-11

> 4:1 さて、イエスは御霊によって荒野に導かれた。悪魔に試みられるためである。  2 そして、四十日四十夜、断食をし、そののち空腹になられた。 3 すると試みる者がきて言った、「もしあなたが神の子であるなら、これらの石がパンになるように命じてごらんなさい」。 4 イエスは答えて言われた、「『人はパンだけで生きるものではなく、神の口から出る一つ一つの言で生きるものである』と書いてある」。5 それから悪魔は、イエスを聖なる都に連れて行き、宮の頂上に立たせて 6 言った、「もしあなたが神の子であるなら、下へ飛びおりてごらんなさい。『神はあなたのために御使たちにお命じになると、あなたの足が石に打ちつけられないように、彼らはあなたを手でささえるであろう』と書いてありますから」。 7 イエスは彼に言われた、「『主なるあなたの神を試みてはならない』とまた書いてある」。 8 次に悪魔は、イエスを非常に高い山に連れて行き、この世のすべての国々とその栄華とを見せて 9 言った、「もしあなたが、ひれ伏してわたしを拝むなら、これらのものを皆あなたにあげましょう」。10 するとイエスは彼に言われた、「サタンよ、退け。『主なるあなたの神を拝し、ただ神にのみ仕えよ[^markdq-25]』と書いてある」。11 そこで、悪魔はイエスを離れ去り、そして、御使たちがみもとにきて仕えた。 

[^markdq-25]: λατρεύω: i) to serve for hire, ii) to serve, minister to, either to the gods or men and used alike of slaves and freemen

### ルカ 4:1-13

> 4:1 さて、イエスは聖霊に満ちてヨルダン川から帰り、2 荒野を四十日のあいだ御霊にひきまわされて、悪魔の試みにあわれた。そのあいだ何も食べず、その日数がつきると、空腹になられた。 3 そこで悪魔が言った、「もしあなたが神の子であるなら、この石に、パンになれと命じてごらんなさい」。4 イエスは答えて言われた、「『人はパンだけで生きるものではない』と書いてある」。 5 それから、悪魔はイエスを高い所へ連れて行き、またたくまに世界のすべての国々を見せて 6 言った、「これらの国々の権威と栄華とをみんな、あなたにあげましょう。それらはわたしに任せられていて、だれでも好きな人にあげてよいのですから。 7 それで、もしあなたがわたしの前にひざまずくなら、これを全部あなたのものにしてあげましょう」。 8 イエスは答えて言われた、「『主なるあなたの神を拝し、ただ神にのみ仕えよ』と書いてある」。 9 それから悪魔はイエスをエルサレムに連れて行き、宮の頂上に立たせて言った、「もしあなたが神の子であるなら、ここから下へ飛びおりてごらんなさい。 10 『神はあなたのために、御使たちに命じてあなたを守らせるであろう』とあり、11 また、『あなたの足が石に打ちつけられないように、彼らはあなたを手でささえるであろう』とも書いてあります」。 12 イエスは答えて言われた、「『主なるあなたの神を試みてはならない』と言われている」。 13 悪魔はあらゆる試みをしつくして、一時イエスを離れた。 

[マルコによる福音書1章12-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_12-13.pdf)

### 問い

1.  マルコは、この箇所で何を伝えていますか。

    -   御霊（聖霊）とサタンはどのような働きをしていますか。獣や御使いたちは、何を表しているのでしょうか。

2.  マタイとルカの違いを挙げてみましょう。

3.  マタイとルカで、最初にサタンはどのようにイエスに言っていますか。イエスはそれにどのように答えますか。

    -   イエスは石をパンに変えることができたのでしょうか？ 空腹は満たされたのでしょうか？ など、疑問点や気づいたことをあげてみましょう。

4.  （マタイでは二番目、ルカでは三番目の）神を試みるとはどのようなことを意味しているのでしょうか。神の何を試しているのでしょうか。

5.  （マタイでは三番目、ルカでは二番目では）どのようなことが試されていますか。国々の栄華を得ることが問題なのでしょうか。「神にのみ仕える」とはどのような生き方でしょうか。

6.  なぜイエスは試みを受けたのでしょう。それはどのようなことを意味しているのでしょう。

    -   イエスの受けた試みと、わたしたちの受ける試み・誘惑・試練は同じでしょうか。異なるでしょうか。

### 参照

-   サタン

    -   マタイ12:26 もし**サタン**が**サタン**を追い出すならば、それは内わで分れ争うことになる。それでは、その国はどうして立ち行けよう。マルコ3:23 そこでイエスは彼らを呼び寄せ、譬をもって言われた、「どうして、**サタン**が**サタン**を追い出すことができようか。 マルコ3:26 もし**サタン**が内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。 ルカ11:18 そこで**サタン**も内部で分裂すれば、その国はどうして立ち行けよう。あなたがたはわたしがベルゼブルによって悪霊を追い出していると言うが、 

    -   マルコ4:15 道ばたに御言がまかれたとは、こういう人たちのことである。すなわち、御言を聞くと、すぐに**サタン**がきて、彼らの中にまかれた御言を、奪って行くのである。 

    -   マタイ16:23 イエスは振り向いて、ペテロに言われた、「**サタン**よ、引きさがれ。わたしの邪魔をする者だ。あなたは神のことを思わないで、人のことを思っている」。マルコ8:33 イエスは振り返って、弟子たちを見ながら、ペテロをしかって言われた、「**サタン**よ、引きさがれ。あなたは神のことを思わないで、人のことを思っている」。  

    -   ルカ10:18 彼らに言われた、「わたしは**サタン**が電光のように天から落ちるのを見た。 

    -   ルカ13:16 それなら、十八年間も**サタン**に縛られていた、アブラハムの娘であるこの女を、安息日であっても、その束縛から解いてやるべきではなかったか」。 

    -   ルカ22:3 そのとき、十二弟子のひとりで、イスカリオテと呼ばれていたユダに、**サタン**がはいった。 

    -   ルカ22:31 シモン、シモン、見よ、**サタン**はあなたがたを麦のようにふるいにかけることを願って許された。 

    -   ヨハネ13:27 この一きれの食物を受けるやいなや、**サタン**がユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。

-   悪魔[^markdq-26]

    -   マタイ13:39 それをまいた敵は**悪魔**である。収穫とは世の終りのことで、刈る者は御使たちである。

    -   マタイ25:41 それから、左にいる人々にも言うであろう、『のろわれた者どもよ、わたしを離れて、**悪魔**とその使たちとのために用意されている永遠の火にはいってしまえ。

    -   ルカ8:12 道ばたに落ちたのは、聞いたのち、信じることも救われることもないように、**悪魔**によってその心から御言が奪い取られる人たちのことである。

    -   ヨハネ6:70 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは**悪魔**である」。 

    -   ヨハネ8:44 あなたがたは自分の父、すなわち、**悪魔**から出てきた者であって、その父の欲望どおりを行おうと思っている。彼は初めから、人殺しであって、真理に立つ者ではない。彼のうちには真理がないからである。彼が偽りを言うとき、いつも自分の本音をはいているのである。彼は偽り者であり、偽りの父であるからだ。

    -   ヨハネ13:2 夕食のとき、**悪魔**はすでにシモンの子イスカリオテのユダの心に、イエスを裏切ろうとする思いを入れていたが、

-   試みる者[^markdq-27]：福音書ではマタイ4:3 のみ

    -   1テサロニケ3:5 そこで、わたしはこれ以上耐えられなくなって、もしや「**試みる者**」があなたがたを試み、そのためにわたしたちの労苦がむだになりはしないかと気づかって、あなたがたの信仰を知るために、彼をつかわしたのである。

-   **マタイ4章4節**：現代訳：人はパンさえあれば生きられるわけではない。神の御心でなければ、決して生きられるものではない」

-   **マタイ4章4節：** 申命記8章2節〜5節 あなたの神、主がこの四十年の間、荒野であなたを導かれたそのすべての道を覚えなければならない。それはあなたを苦しめて、あなたを試み、あなたの心のうちを知り、あなたがその命令を守るか、どうかを知るためであった。3 それで主はあなたを苦しめ、あなたを飢えさせ、あなたも知らず、あなたの先祖たちも知らなかったマナをもって、あなたを養われた。人はパンだけでは生きず、人は主の口から出るすべてのことばによって生きることをあなたに知らせるためであった。4 この四十年の間、あなたの着物はすり切れず、あなたの足は、はれなかった。5 あなたはまた人がその子を訓練するように、あなたの神、主もあなたを訓練されることを心にとめなければならない。

-   **宮の頂上**：ソロモンの廊と王室の廊の出会うところ、下はケデロンの谷で 140 m と言われる。

-   **マタイ4章6節** 詩篇91:11,12 これは主があなたのために天使たちに命じて、／あなたの歩むすべての道で／あなたを守らせられるからである。12 彼らはその手で、あなたをささえ、／石に足を打ちつけることのないようにする。(この詩篇は "1 彼らはその手で、あなたをささえ、／石に足を打ちつけることのないようにする。2 主に言うであろう、「わが避け所、わが城、／わが信頼しまつるわが神」と。" 始まっている。)

-   **マタイ4章7節** 申命記6:16 あなたがたがマッサでしたように、あなたがたの神、主を試みてはならない。 

-   **マタイ4章9節** 申命記6:13 あなたの神、主を恐れてこれに仕え、その名をさして誓わなければならない。 

-   詩篇2:7,8 わたしは主の詔をのべよう。主はわたしに言われた、「おまえはわたしの子だ。きょう、わたしはおまえを生んだ。 わたしに求めよ、わたしはもろもろの国を／嗣業としておまえに与え、／地のはてまでもおまえの所有として与える。

-   ルカ22:28 あなたがたは、わたしの試錬のあいだ、わたしと一緒に最後まで忍んでくれた人たちである。 

[^markdq-26]: διάβολος: i) prone to slander, slanderous, accusing falsely, ii) metaph. applied to a man who, by opposing the cause of God, may be said to act the part of the devil or to side with him

[^markdq-27]: πειράζω: i) to try whether a thing can be done ii) to try, make trial of, test: for the purpose of ascertaining his quality, or what he thinks, or how he will behave himself

> **12**Καὶ εὐθὺς τὸ πνεῦμα αὐτὸν ἐκβάλλει[^markdq-28] εἰς τὴν ἔρημον[^markdq-29]. **13**καὶ ἦν ἐν τῇ ἐρήμῳ τεσσεράκοντα ἡμέρας πειραζόμενος[^markdq-30] ὑπὸ τοῦ σατανᾶ[^markdq-31], καὶ ἦν μετὰ τῶν θηρίων[^markdq-32], καὶ οἱ ἄγγελοι[^markdq-33] διηκόνουν[^markdq-34] αὐτῷ.

[^markdq-28]: ἐκβάλλω: to cast out, drive out, to send out, \[historical present\].

[^markdq-29]: ἔρημος: solitary, lonely, desolate, uninhabited

[^markdq-30]: πειράζω: 1. to try whether a thing can be done, 2. to try, make trial of, test: for the purpose of ascertaining his quality, or what he thinks, or how he will behave himself

[^markdq-31]: Σατανᾶς: adversary (one who opposes another in purpose or act), the name given to a) the prince of evil spirits, the inveterate adversary of God and Christ, b) a Satan-like man

[^markdq-32]: θηρίον: i) an animal, ii) a wild animal, wild beast, beast, iii) metaph. a brutal, bestial man, savage, ferocious

[^markdq-33]: ἄγγελος: a messenger, envoy, one who is sent, an angel, a messenger from God

[^markdq-34]: διακονέω: to be a servant, attendant, domestic, to serve, wait upon

### 記録

-   日時：2023年5月11日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）8名

### 問いについて

### メモ

-   マルコには、「それからすぐに、御霊がイエスを荒野に追いやった。」とあるが、それ（それからすぐ）は、イエスがバプテスマを受け「天が裂けて、聖霊がはとのように自分に下って来るのを、ごらんにな」り「あなたはわたしの愛する子、わたしの心にかなう者である」との天からの声を聞いてすぐにを意味している。「あなたはわたしの愛する子、わたしの心にかなう者」の神の宣言は、始まりであって終わりではない。

-   マルコでは、イエスは四十日の間荒野にいたとあるが、共にいたのは、サタン、獣、御使である。試みる者、敵対するもの、悪意を持って近づくもの、助け、神のメッセージを伝えるものが、混在している世界として描かれている。

-   マタイでもルカでも、イエスが空腹になってから「石にパンになれと命じ」るよう促され（試みられ）ている。イエスには、それができなかったとは想定されていない。「わたしには、あなたがたの知らない食物がある」（ヨハネ4:32b）だろうか。このときは、サマリアの女との対話がある。しかし、ここでは、空腹は満たされていないのではないだろうか。「パンだけで」とあり、やはりパンも必要なのではないだろうか。ルカでは後半のことばは書かれていない。経済的な、空腹を満たすそれを解決すればよいということではないことに中心が置かれている。同時に、神の国は、これもあれも手当たり次第に課題が解決されることでもないのかもしれない。

-   「神はあなたのために、御使いたちに命じ」る根拠は、愛されている存在だということだろうが、それを、確認するようなことをしてはならない。神に愛されている存在とは、神のこころを心とすること、神が望まれることをなすことなのだろう。

-   「ひれ伏して拝むなら（マタイ）・ひざまずくなら（ルカ）」にたいして、「神にのみ仕えよ」と返答している。神との関係が絶対だということで、「国々とその栄華（マタイ）・国々の権威と栄華（ルカ）」を手にすることが悪ではない。神に仕えることが具体的に何を意味するのかは、わからない時が多い。内心の問題なのだろうか。何が問われているのかを確定するのは、難しい。

-   イエスが試み・誘惑にあわれたことを語っている意味

    -   イエスも試みにあわれている。

    -   \[参照\] ヘブル人への手紙4章15節 この大祭司は、わたしたちの弱さを思いやることのできないようなかたではない。罪は犯されなかったが、すべてのことについて、わたしたちと同じように試錬に会われたのである。

    -   メシヤ預言のことばではなく、一般信徒へのことばを引用している。

    -   超自然的な力でこの誘惑に打ち勝っているのではない。イエスに倣うものとなることは、不可能なことではない。

    -   イエスが神の愛されている子として生きていくあゆみの確認。一般性もある。

-   マルコは「サタン」、マタイは、最初「試みる者」（3）その後「悪魔」、ルカは「悪魔」

## 1:14-15 ガリラヤで宣教を始める

> 1:14 ヨハネが捕えられた後、イエスはガリラヤに行き、神の福音を宣べ伝えて言われた、15 「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」。 

### マタイ 4:12-17

> 4:12 さて、イエスはヨハネが捕えられたと聞いて、ガリラヤへ退かれた。 13 そしてナザレを去り、ゼブルンとナフタリとの地方にある海べの町カペナウムに行って住まわれた。 14 これは預言者イザヤによって言われた言が、成就するためである。15 「ゼブルンの地、ナフタリの地、／海に沿う地方、ヨルダンの向こうの地、／異邦人のガリラヤ、16 暗黒の中に住んでいる民は大いなる光を見、／死の地、死の陰に住んでいる人々に、光がのぼった」。17 この時からイエスは教を宣べはじめて言われた、「悔い改めよ、天国は近づいた」。 

### ルカ 4:14-15

> 4:14 それからイエスは御霊の力に満ちあふれてガリラヤへ帰られると、そのうわさがその地方全体にひろまった。15 イエスは諸会堂で教え、みんなの者から尊敬をお受けになった。 

[マルコによる福音書1章14-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_14-15.pdf)

### 問い

1.  マルコでは、イエスはいつ、どこで、どのような言葉で宣教を始めたとしていますか。

2.  マタイや、ルカを読み、他に気づいたことを挙げてみましょう。

### 参照

-   ルカ3:31 イエスが宣教をはじめられたのは、年およそ三十歳の時であって、人々の考えによれば、ヨセフの子であった。ヨセフはヘリの子、 （以下系図 〜38）

-   ヨハネ3:22 こののち、イエスは弟子たちとユダヤの地に行き、彼らと一緒にそこに滞在して、バプテスマを授けておられた。23 ヨハネもサリムに近いアイノンで、バプテスマを授けていた。そこには水がたくさんあったからである。人々がぞくぞくとやってきてバプテスマを受けていた。24 そのとき、ヨハネはまだ獄に入れられてはいなかった。 （〜36）

-   マタイ4:15,16 - イザヤ書9:1,2 （他の訳では 8:23, 9:1）1 しかし、苦しみにあった地にも、やみがなくなる。さきにはゼブルンの地、ナフタリの地にはずかしめを与えられたが、後には海に至る道、ヨルダンの向こうの地、異邦人のガリラヤに光栄を与えられる。2 暗やみの中に歩んでいた民は大いなる光を見た。暗黒の地に住んでいた人々の上に光が照った。 

-   死の谷：詩篇23:4 たといわたしは死の陰の谷を歩むとも、／わざわいを恐れません。あなたがわたしと共におられるからです。あなたのむちと、あなたのつえはわたしを慰めます。ルカ1:79 暗黒と死の陰とに住む者を照し、／わたしたちの足を平和の道へ導くであろう」。 

-   マタイ4:17 - マタイ3:2 「悔い改めよ、天国は近づいた」。 

> **14**Μετὰ δὲ τὸ παραδοθῆναι[^markdq-35] τὸν Ἰωάννην ἦλθεν ὁ Ἰησοῦς εἰς τὴν Γαλιλαίαν κηρύσσων[^markdq-36] τὸ εὐαγγέλιον[^markdq-37] τοῦ θεοῦ **15** καὶ λέγων ὅτι πεπλήρωται[^markdq-38] ὁ καιρὸς καὶ ἤγγικεν[^markdq-39] ἡ βασιλεία τοῦ θεοῦ· μετανοεῖτε[^markdq-40] καὶ πιστεύετε ἐν τῷ εὐαγγελίῳ.

[^markdq-35]: παραδίδωμι: to give into the hands (of another)

[^markdq-36]: κηρύσσω: to be a herald, to officiate as a herald

[^markdq-37]: εὐαγγέλιον: a reward for good tidings

[^markdq-38]: πληρόω: o make full, to fill up, i.e. to fill to the full

[^markdq-39]: ἐγγίζω: to bring near, to join one thing to another

[^markdq-40]: μετανοέω: to change one's mind, i.e. to repent

### 問いについて

### メモ

-   マルコとマタイでは「ヨハネが捕えられた後」「この時から」として、ヨハネが捕えられてから以降に活動を開始したとしている。

-   「神の福音」とある。なにが良き訪れなのか。「時は満ちた、神の国は近づいた。」とあり、神の国が近づいたということなのだろう。「神の国が近ついた」とはどういうことだろうか。「福音を信じる」とはどういうことだろうか。地の上でも、神の御心がなるということだろうか。

-   「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」（マルコ）「悔い改めよ、天国は近づいた」（マタイ）当時の人たちは、どう受け取っただろうか。イスラエルの歴史上では、どのような時代なのだろうか。ローマの占領下だが、ある程度の自治がみとめられていた。

    -   \[参照\] [John the Baptist](https://www.seektheoldpaths.com/Maps/106.jpg) (Halman Bible Atlas 106)

    -   \[参照\] イスラエルの歴史：[年表](https://embassies.gov.il/tokyo/AboutIsrael/history/Pages/年表.aspx)（駐日イスラエル大使館）

-   ヨハネの記述3章22節を見ると、ヨハネが捕えられる前にも活動していることがわかる。ヨハネが捕えられたことを契機に、宣教をはじめたというより、活動のひとつの転機を記しているのかもしれない。

-   少なくとも、ペテロとアンデレ、ヤコブとヨハネと会ったのが、マルコに書かれている時が初めてだとは言えないだろう。

## 1:16-20 四人の漁師を弟子にする

> 1:16 さて、イエスはガリラヤの海べを歩いて行かれ、シモンとシモンの兄弟アンデレとが、海で網を打っているのをごらんになった。彼らは漁師であった。17 イエスは彼らに言われた、「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」。 18 すると、彼らはすぐに網を捨てて、イエスに従った。 19 また少し進んで行かれると、ゼベダイの子ヤコブとその兄弟ヨハネとが、舟の中で網を繕っているのをごらんになった。 20 そこで、すぐ彼らをお招きになると、父ゼベダイを雇人たちと一緒に舟において、イエスのあとについて行った。

### マタイ 4:18-22

> 4:18 さて、イエスがガリラヤの海べを歩いておられると、ふたりの兄弟、すなわち、ペテロと呼ばれたシモンとその兄弟アンデレとが、海に網を打っているのをごらんになった。彼らは漁師であった。 19 イエスは彼らに言われた、「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」。20 すると、彼らはすぐに網を捨てて、イエスに従った。21 そこから進んで行かれると、ほかのふたりの兄弟、すなわち、ゼベダイの子ヤコブとその兄弟ヨハネとが、父ゼベダイと一緒に、舟の中で網を繕っているのをごらんになった。そこで彼らをお招きになると、 22 すぐ舟と父とをおいて、イエスに従って行った。 

### ルカ 5:1-11

> 5:1 さて、群衆が神の言を聞こうとして押し寄せてきたとき、イエスはゲネサレ湖畔に立っておられたが、 2 そこに二そうの小舟が寄せてあるのをごらんになった。漁師たちは、舟からおりて網を洗っていた。 3 その一そうはシモンの舟であったが、イエスはそれに乗り込み、シモンに頼んで岸から少しこぎ出させ、そしてすわって、舟の中から群衆にお教えになった。 4 話がすむと、シモンに「沖へこぎ出し、網をおろして漁をしてみなさい」と言われた。5 シモンは答えて言った、「先生、わたしたちは夜通し働きましたが、何も取れませんでした。しかし、お言葉ですから、網をおろしてみましょう」。 6 そしてそのとおりにしたところ、おびただしい魚の群れがはいって、網が破れそうになった。7 そこで、もう一そうの舟にいた仲間に、加勢に来るよう合図をしたので、彼らがきて魚を両方の舟いっぱいに入れた。そのために、舟が沈みそうになった。 8 これを見てシモン・ペテロは、イエスのひざもとにひれ伏して言った、「主よ、わたしから離れてください。わたしは罪深い者です」。 9 彼も一緒にいた者たちもみな、取れた魚がおびただしいのに驚いたからである。 10 シモンの仲間であったゼベダイの子ヤコブとヨハネも、同様であった。すると、イエスがシモンに言われた、「恐れることはない。今からあなたは人間をとる漁師になるのだ」。 11 そこで彼らは舟を陸に引き上げ、いっさいを捨ててイエスに従った。 

### \[ヨハネ 1:35-42\]

> 1:35 その翌日、ヨハネはまたふたりの弟子たちと一緒に立っていたが、 36 イエスが歩いておられるのに目をとめて言った、「見よ、神の小羊」。 37 そのふたりの弟子は、ヨハネがそう言うのを聞いて、イエスについて行った。 38 イエスはふり向き、彼らがついてくるのを見て言われた、「何か願いがあるのか」。彼らは言った、「ラビ（訳して言えば、先生）どこにおとまりなのですか」。39 イエスは彼らに言われた、「きてごらんなさい。そうしたらわかるだろう」。そこで彼らはついて行って、イエスの泊まっておられる所を見た。そして、その日はイエスのところに泊まった。時は午後四時ごろであった。 40 ヨハネから聞いて、イエスについて行ったふたりのうちのひとりは、シモン・ペテロの兄弟アンデレであった。 41  彼はまず自分の兄弟シモンに出会って言った、「わたしたちはメシヤ（訳せば、キリスト）にいま出会った」。42 そしてシモンをイエスのもとにつれてきた。イエスは彼に目をとめて言われた、「あなたはヨハネの子シモンである。あなたをケパ（訳せば、ペテロ）と呼ぶことにする」。 

[マルコによる福音書1章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_16-20.pdf)

### 問い

1.  マルコに書かれている、弟子たちを招いた記事からどのようなことがわかりますか。

2.  「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」を弟子たちはどのように受け取ったでしょうか。

3.  マタイとルカを読んでみましょう。マルコに加えてどのようなことが書かれていますか。

    -   ルカ5:5, 8 のペテロの応答からどのようなことがわかりますか。

4.  弟子たちはどのように応答していますか。あなたならどうしますか。

5.  ヨハネの記事から、さらにどのようなことがわかりますか。

6.  イエスはなぜこの人たちを招いたのでしょうか。

7.  イエスに従っていくとは、どのようなことなのでしょうか。

### 参照

-   ルカと似たエピソード：ヨハネ21:1-14

> **16** Καὶ παράγων[^markdq-41] παρὰ τὴν θάλασσαν τῆς Γαλιλαίας εἶδεν Σίμωνα καὶ Ἀνδρέαν τὸν ἀδελφὸν Σίμωνος ἀμφιβάλλοντας[^markdq-42] ἐν τῇ θαλάσσῃ· ἦσαν γὰρ ἁλιεῖς[^markdq-43]. **17** καὶ εἶπεν αὐτοῖς ὁ Ἰησοῦς· δεῦτε[^markdq-44] ὀπίσω[^markdq-45] μου, καὶ ποιήσω ὑμᾶς γενέσθαι ἁλιεῖς ἀνθρώπων. **18** καὶ εὐθὺς ἀφέντες[^markdq-46] τὰ δίκτυα ἠκολούθησαν[^markdq-47] αὐτῷ. **19** Καὶ προβὰς[^markdq-48] ὀλίγον εἶδεν Ἰάκωβον τὸν τοῦ Ζεβεδαίου καὶ Ἰωάννην τὸν ἀδελφὸν αὐτοῦ καὶ αὐτοὺς ἐν τῷ πλοίῳ[^markdq-49] καταρτίζοντας[^markdq-50] τὰ δίκτυα, **20** καὶ εὐθὺς ἐκάλεσεν αὐτούς. καὶ ἀφέντες τὸν πατέρα αὐτῶν Ζεβεδαῖον ἐν τῷ πλοίῳ μετὰ τῶν μισθωτῶν ἀπῆλθον ὀπίσω αὐτοῦ.

[^markdq-41]: περιπατέω: to walk

[^markdq-42]: βάλλω: to throw or let go of a thing without caring where it falls

[^markdq-43]: ἁλιεύς: a fisherman, fisher

[^markdq-44]: δεῦτε: come hither, come here, come

[^markdq-45]: ποιέω: to make

[^markdq-46]: ἀφίημι:i) to send away, ii) to permit, allow, not to hinder, to give up a thing to a person, iii) to leave, go way from one,

[^markdq-47]: ἀκολουθέω: i) to follow one who precedes, join him as his attendant, accompany him, ii) to join one as a disciple, become or be his disciple

[^markdq-48]: προβαίνω: to go forwards, go on

[^markdq-49]: πλοῖον: a ship

[^markdq-50]: καταρτίζω: to render, i.e. to fit, sound, complete

### 記録

-   日時：2023年5月18日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）8名

### 問いについて

### メモ

-   ペテロとアンデレ、ヤコブとヨハネはどのような人ですか。

    -   漁師。ルカにエピソードが書かれており、さらに、ヨハネには別の出会いが書かれている。メシア（訳せばキリスト）との出会いと、網を捨てて、弟子としてついていくこととは、別のことなのだろう。

    -   ヤコブとヨハネのところには、父と雇人がいる。

    -   ルカでは、舟に乗り座って教えておられる。マルコ3:9 イエスは群衆が自分に押し迫るのを避けるために、小舟を用意しておけと、弟子たちに命じられた。 マルコ4:1 イエスはまたも、海べで教えはじめられた。おびただしい群衆がみもとに集まったので、イエスは舟に乗ってすわったまま、海上におられ、群衆はみな海に沿って陸地にいた。（マタイ13:2 ところが、大ぜいの群衆がみもとに集まったので、イエスは**舟**に乗ってすわられ、群衆はみな岸に立っていた。）

-   皆、漁師はやめてしまったのだろうか。基本的には、やめたのだろう。ルカでは「そこで彼らは舟を陸に引き上げ、いっさいを捨ててイエスに従った。」。

-   ルカと似たエピソードが、ヨハネ21:1-14にもある。

    -   ルカを見ると、イエスは、舟に乗って、群衆に教えておられたが、その教えに感激したのではなかったようだ。徹夜で、疲れていたかもしれない。目が覚めるようなことが起こったことが書かれている。

    -   マタイ17:27 しかし、彼らをつまずかせないために、海に行って、つり針をたれなさい。そして最初につれた魚をとって、その口をあけると、銀貨一枚が見つかるであろう。それをとり出して、わたしとあなたのために納めなさい」。 

-   ヨハネによる福音書の記述。もうひとり？

    -   ヨハネ18:15,16 シモン・ペトロともう一人の弟子は、イエスに付いて行った。この弟子は大祭司の知り合いだったので、イエスと一緒に大祭司の中庭に入ったが、ペトロは門の外に立っていた。大祭司の知り合いである、そのもう一人の弟子は、出て来て門番の女に話し、ペトロを中に入れた。 

    -   ヨハネ20:2-8 そこで、シモン・ペトロのところへ、また、イエスが愛しておられたもう一人の弟子のところへ走って行って、彼らに告げた。「誰かが主を墓から取り去りました。どこに置いたのか、分かりません。」 

-   イエスのことを先生（ラビ）知ってはいたが、「主よ」といって、跪くことが、ペトロの悔い改めの表現で、そのペトロにかけたイエスの言葉によって、ペトロの人生が変わっていったのだろう。イエスに従って歩むことによって。

## 1:21-28 汚れた霊に取りつかれた男を癒やす

> 1:21 それから、彼らはカペナウムに行った。そして安息日にすぐ、イエスは会堂にはいって教えられた。22 人々は、その教に驚いた。律法学者たちのようにではなく、権威ある者のように、教えられたからである。 23 ちょうどその時、けがれた霊につかれた者が会堂にいて、叫んで言った、24 「ナザレのイエスよ、あなたはわたしたちとなんの係わりがあるのです。わたしたちを滅ぼしにこられたのですか。あなたがどなたであるか、わかっています。神の聖者です」。 25 イエスはこれをしかって、「黙れ、この人から出て行け」と言われた。26 すると、けがれた霊は彼をひきつけさせ、大声をあげて、その人から出て行った。 27 人々はみな驚きのあまり、互に論じて言った、「これは、いったい何事か。権威ある新しい教だ。けがれた霊にさえ命じられると、彼らは従うのだ」。 28 こうしてイエスのうわさは、たちまちガリラヤの全地方、いたる所にひろまった。 

### ルカ 4:31-37

> 4:31 それから、イエスはガリラヤの町カペナウムに下って行かれた。そして安息日になると、人々をお教えになったが、  32 その言葉に権威があったので、彼らはその教に驚いた。 33 すると、汚れた悪霊につかれた人が会堂にいて、大声で叫び出した、  34 「ああ、ナザレのイエスよ、あなたはわたしたちとなんの係わりがあるのです。わたしたちを滅ぼしにこられたのですか。あなたがどなたであるか、わかっています。神の聖者です」。35 イエスはこれをしかって、「黙れ、この人から出て行け」と言われた。すると悪霊は彼を人なかに投げ倒し、傷は負わせずに、その人から出て行った。 36 みんなの者は驚いて、互に語り合って言った、「これは、いったい、なんという言葉だろう。権威と力とをもって汚れた霊に命じられると、彼らは出て行くのだ」。 37 こうしてイエスの評判が、その地方のいたる所にひろまっていった。  

[マルコによる福音書1章21-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_21-28.pdf)

### 問い

1.  イエスは、いつどこで教えていますか。

    -   だれでも教えることができたのでしょうか。

2.  イエスの教えはどのようなものだったのでしょうか。人々の反応から考えてみましょう。

3.  マルコとルカを比較して気づいたことを挙げてみましょう。

4.  汚れた霊につかれた者は何を叫んでいますか。イエスはどうしますか。そしてどうなりますか。

5.  人々は、何に驚いていますか。

6.  あなたは、ここでどのようなことが起こったを思いますか。

7.  イエスにとってたいせつなことは、何だったのでしょうか。

### 参照

> **21**Καὶ εἰσπορεύονται[^markdq-51] εἰς Καφαρναούμ· καὶ εὐθὺς τοῖς σάββασιν εἰσελθὼν εἰς τὴν συναγωγὴν ἐδίδασκεν[^markdq-52]. **22**καὶ ἐξεπλήσσοντο[^markdq-53] ἐπὶ τῇ διδαχῇ αὐτοῦ· ἦν γὰρ διδάσκων αὐτοὺς ὡς ἐξουσίαν[^markdq-54] ἔχων καὶ οὐχ ὡς οἱ γραμματεῖς. **23**Καὶ εὐθὺς ἦν ἐν τῇ συναγωγῇ αὐτῶν ἄνθρωπος ἐν πνεύματι ἀκαθάρτῳ[^markdq-55] καὶ ἀνέκραξεν[^markdq-56] **24**λέγων· τί ἡμῖν καὶ σοί, Ἰησοῦ Ναζαρηνέ; ἦλθες ἀπολέσαι[^markdq-57] ἡμᾶς; οἶδά σε τίς εἶ, ὁ ἅγιος τοῦ θεοῦ. **25**καὶ ἐπετίμησεν[^markdq-58] αὐτῷ ὁ Ἰησοῦς λέγων· φιμώθητι[^markdq-59] καὶ ἔξελθε ἐξ αὐτοῦ. **26**καὶ σπαράξαν[^markdq-60] αὐτὸν τὸ πνεῦμα τὸ ἀκάθαρτον καὶ φωνῆσαν φωνῇ μεγάλῃ ἐξῆλθεν ἐξ αὐτοῦ. **27**καὶ ἐθαμβήθησαν[^markdq-61] ἅπαντες ὥστε συζητεῖν[^markdq-62] πρὸς ἑαυτοὺς λέγοντας· τί ἐστιν τοῦτο; διδαχὴ καινὴ[^markdq-63] κατ' ἐξουσίαν· καὶ τοῖς πνεύμασιν τοῖς ἀκαθάρτοις ἐπιτάσσει[^markdq-64], καὶ ὑπακούουσιν[^markdq-65] αὐτῷ. **28**καὶ ἐξῆλθεν ἡ ἀκοὴ[^markdq-66] αὐτοῦ εὐθὺς πανταχοῦ εἰς ὅλην τὴν περίχωρον[^markdq-67] τῆς Γαλιλαίας.

[^markdq-51]: εἰσπορεύομαι: to go into, enter

[^markdq-52]: διδάσκω: to teach

[^markdq-53]: ἐκπλήσσω: i) to strike out, expel by a blow, drive out or away, ii) to cast off by a blow, to drive out, iii) to be struck with amazement, astonished, amazed

[^markdq-54]: ἐξουσία: i) power of choice, liberty of doing as one pleases, ii) physical and mental power, iii) the power of authority (influence) and of right (privilege), iv) the power of rule or government (the power of him whose will and commands must be submitted to by others and obeyed)

[^markdq-55]: ἀκάθαρτος: not cleansed, unclean

[^markdq-56]: ἀνακράζω: to raise a cry from the depth of the throat, to cry out

[^markdq-57]: ἀπόλλυμι: to destroy

[^markdq-58]: ἐπιτιμάω: i) to show honour to, to honour, ii) to raise the price of, iii) to adjudge, award, in the sense of merited penalty, iv) to tax with fault, rate, chide, rebuke, reprove, censure severely

[^markdq-59]: φιμόω: i) to close the mouth with a muzzle, to muzzle, ii) metaph; to stop the mouth, make speechless, reduce to silence, to become speechless, iii) to be kept in check

[^markdq-60]: σπαράσσω: to convulse, tear

[^markdq-61]: θαμβέω: to be astonished, to astonish, terrify

[^markdq-62]: συζητέω: i) to seek or examine together, ii) in the NT to discuss, dispute, question

[^markdq-63]: καινός: new

[^markdq-64]: ἐπιτάσσω: to enjoin upon, order, command, charge

[^markdq-65]: ὑπακούω: i) to listen, to harken, ii) to harken to a command

[^markdq-66]: ἀκοή: i) the sense of hearing, ii) the organ of hearing, the ear, iii) the thing heard

[^markdq-67]: περίχωρος: lying round about, neighbouring

### 記録

-   日時：2023年5月25日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）5名

### 問いについて

### メモ

-   イエスは、ガリラヤで宣教を開始したが（1:14）安息日に会堂で教えている。

    -   ユダヤ人共同体に、聖書の教師として、一程度、認められたいたことが分かる。[参照](#synagogue)

    -   ある程度認知されていたことと共に、このような状態がどの程度続くかも、注視が必要。

-   「律法学者のようにではなく、権威あるもののように」当時の一般的な訓練を受けたわけではない、ある程度自由に語るスタイルが表現されていると共に、権威あるもののようには、詳細は不明だが、27 節の権威ある教えとは、関係しているだろう。

    -   山上の説教（マタイ5-7）などからも、ある程度、想像はつく。ただ、マルコでは、そのようなことは語っていない。ルカ5:1-11 を考えると、群衆に人気があったとも考えられる。ただ、内容まで、理解して、このように告白しているかは不明。

-   汚れた霊の記事をどう読むか。

    -   ある時期には、悪霊に憑かれていると表現し、あるときには、気狂いとあざわらわれ、ある時は、精神分裂病とされ、ある時は、統合失調症として憐れまれたりしつつも、遠ざけられていた存在かもしれない。

    -   「イエスよ、放っておいてくれ。痛めつけ、裁くために来たのか、神から使わされたとでも言うのだろう。」「あなたはたいせつなひとりのひと。」特別のケアをされたのかもしれない。少なくとも、このひとの異常な状態と、この人とを分離・区別している。

    -   現代でも、オープンダイアログによる、愛の、治療もある。（[読書記録](https://icu-hsuzuki.github.io/science/books/books2023.html#opendialogue)参照）「治療 すなわち『キュア』と考えるなら難しいことでも、『ケアにかぎりなく近いキュア』と考えるなら、ありそうに思えてきませんか？」「精神分析が言葉をメスとして用いるというなら、オープンダイアローグは言葉を包帯とし用いるのです。」

    -   奇跡などについて：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#奇跡などについて)

-   テキストからわかるのは、イエスの教えは、律法学者のようではなく「権威のある」教えで、それは、カリスマ性をも意味するが、そのあとの、悪霊を追い出すことによって、力を伴う教えであることを、会堂に来ていた人たちが受け取ったことである。

-   また、「神の国が近づいた」ということが、悪霊につかれた人から、悪霊が逃げ出すことによって、皆に示される意味を持っている。そうであれば、悪霊につかれたひとには、神の国は来たとして、そこに焦点を当てることも可能。

-   排除され、憎まれていたと思われる悪霊につかれたひとの、悪霊と、この人とを区別し、分けることで、ひとりの人が自分を取り戻すことができたとも言える。現代の精神分裂病、統合失調症と同一視する根拠はないが、そのような病に苦しんでいる人にとっても、福音であることは確か。

## 1:29-34 多くの病人を癒やす

> 1:29 それから会堂を出るとすぐ、ヤコブとヨハネとを連れて、シモンとアンデレとの家にはいって行かれた。 30 ところが、シモンのしゅうとめが熱病で床についていたので、人々はさっそく、そのことをイエスに知らせた。31 イエスは近寄り、その手をとって起されると、熱が引き、女は彼らをもてなした。 32 夕暮になり日が沈むと、人々は病人や悪霊につかれた者をみな、イエスのところに連れてきた。 33 こうして、町中の者が戸口に集まった。 34 イエスは、さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出された。また、悪霊どもに、物言うことをお許しにならなかった。彼らがイエスを知っていたからである。

### マタイ 8:14-17

> 8:14 それから、イエスはペテロの家にはいって行かれ、そのしゅうとめが熱病で、床についているのをごらんになった。15 そこで、その手にさわられると、熱が引いた。そして女は起きあがってイエスをもてなした。 16 夕暮になると、人々は悪霊につかれた者を大ぜい、みもとに連れてきたので、イエスはみ言葉をもって霊どもを追い出し、病人をことごとくおいやしになった。 17 これは、預言者イザヤによって「彼は、わたしたちのわずらいを身に受け、わたしたちの病を負うた」と言われた言葉が成就するためである。 

### ルカ 4:38-41

> 4:38 イエスは会堂を出てシモンの家におはいりになった。ところがシモンのしゅうとめが高い熱を病んでいたので、人々は彼女のためにイエスにお願いした。39 そこで、イエスはそのまくらもとに立って、熱が引くように命じられると、熱は引き、女はすぐに起き上がって、彼らをもてなした。40 日が暮れると、いろいろな病気になやむ者をかかえている人々が、皆それをイエスのところに連れてきたので、そのひとりびとりに手を置いて、おいやしになった。41 悪霊も「あなたこそ神の子です」と叫びながら多くの人々から出ていった。しかし、イエスは彼らを戒めて、物を言うことをお許しにならなかった。彼らがイエスはキリストだと知っていたからである。  

[マルコによる福音書1章29-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_29-34.pdf)

### 問い

1.  マルコ、マタイ、ルカを読んでみましょう。シモンとアンデレの家ではどんな問題がありましたか。

2.  姑（しゅうと）の回復の様子はどのように記されていますか。

3.  夕暮れには、どのようなことが起きますか。それはなぜでしょうか。

4.  イエスは何をしますか。

    -   イエスにとって、癒しとはどのような働きだったのでしょうか。

5.  イエスはなぜ、悪霊を黙らせるのでしょうか。

### 参照

-   マタイ8:17 - イザヤ53:3,4 彼は侮られて人に捨てられ、／悲しみの人で、病を知っていた。また顔をおおって忌みきらわれる者のように、／彼は侮られた。われわれも彼を尊ばなかった。 まことに彼はわれわれの病を負い、／われわれの悲しみをになった。しかるに、われわれは思った、／彼は打たれ、神にたたかれ、苦しめられのだと。
    -   病を癒すことと、病を負うことはどう違うのか。
    -   病を知っていたとは？
    -   ルカ8:46 しかしイエスは言われた、「だれかがわたしにさわった。力がわたしから出て行ったのを感じたのだ」。
    -   Hospital の語源：ChatGPT
        -   "Hospital"という単語は、ラテン語の"hospitālis"に由来しています。 "hospitālis"は、"hospes"（宿泊客、旅人）という単語に由来しており、中世ラテン語で「旅人や貧しい人のための宿泊所」という意味で使われていました。

            中世ヨーロッパでは、キリスト教の信仰に基づき、修道院や宗教団体が病人や貧しい人を収容する施設を運営していました。これらの施設は、病院（hospital）と呼ばれ、病人の治療や看護、貧しい人たちへの食事や寝床が提供されていました。

            現代の病院は、中世の病院から発展したものであり、医学や科学技術の進歩によって、より効果的な医療が提供されるようになりました。しかし、病院の最初の目的は、依然として病人の治療と看護にあります。

            なお、英語以外にも、フランス語の"hôpital"、スペイン語の"hospital"、イタリア語の"ospedale"など、多くのヨーロッパ言語で「病院」を意味する単語が"hospitālis"に由来しています。

> **29** Καὶ εὐθὺς ἐκ τῆς συναγωγῆς ἐξελθόντες ἦλθον εἰς τὴν οἰκίαν Σίμωνος καὶ Ἀνδρέου μετὰ Ἰακώβου καὶ Ἰωάννου. **30** ἡ δὲ πενθερὰ[^markdq-68] Σίμωνος κατέκειτο[^markdq-69] πυρέσσουσα[^markdq-70], καὶ εὐθὺς λέγουσιν αὐτῷ περὶ αὐτῆς. **31** καὶ προσελθὼν[^markdq-71] ἤγειρεν αὐτὴν κρατήσας[^markdq-72] τῆς χειρός[^markdq-73]· καὶ ἀφῆκεν[^markdq-74] αὐτὴν ὁ πυρετός[^markdq-75], καὶ διηκόνει αὐτοῖς. **32**Ὀψίας[^markdq-76] δὲ γενομένης, ὅτε ἔδυ[^markdq-77] ὁ ἥλιος, ἔφερον[^markdq-78] πρὸς αὐτὸν πάντας τοὺς κακῶς[^markdq-79] ἔχοντας καὶ τοὺς δαιμονιζομένους[^markdq-80]· **33** καὶ ἦν ὅλη ἡ πόλις ἐπισυνηγμένη[^markdq-81] πρὸς τὴν θύραν. **34** καὶ ἐθεράπευσεν[^markdq-82] πολλοὺς κακῶς ἔχοντας ποικίλαις[^markdq-83] νόσοις[^markdq-84] καὶ δαιμόνια[^markdq-85] πολλὰ ἐξέβαλεν καὶ οὐκ ἤφιεν[^markdq-86] λαλεῖν τὰ δαιμόνια, ὅτι ᾔδεισαν αὐτόν.

[^markdq-68]: πενθερά: mother-in-law, a wife's mother

[^markdq-69]: κατάκειμαι: to have lain down, i.e. to lie prostrate

[^markdq-70]: πυρέσσω: to be sick with a fever

[^markdq-71]: προσέρχομαι: i) to come to, approach, ii) draw near to iii) to assent to

[^markdq-72]: κρατέω: i) to have power, be powerful, ii) to get possession of, iii) to hold

[^markdq-73]: χείρ: i) by the help or agency of any one, by means of any one, ii) fig. applied to God symbolising his might, activity, power

[^markdq-74]: ἀφίημι: i) to send away, ii) to permit, allow, not to hinder, to give up a thing to a person, iii) to leave, go way from one

[^markdq-75]: πυρετός: i) fiery heat, ii) fever

[^markdq-76]: ὄψιος: i) late, ii) evening

[^markdq-77]: δύνω: i) to go into, enter, ii) go under, be plunged into, sink in

[^markdq-78]: φέρω: i) to carry, ii) to bear, i.e. endure, to endure the rigour of a thing, to bear patiently one's conduct, or spare one (abstain from punishing or destroying), iii) to bring, bring to, bring forward

[^markdq-79]: κακῶς: i) miserable, to be ill, ii) improperly, wrongly, iii) to speak ill of, revile, one

[^markdq-80]: δαιμονίζομαι: to be under the power of a demon.

[^markdq-81]: ἐπισυνάγω: i) to gather together besides, to bring together to others already assembled, ii) to gather together against, iii) to gather together in one place

[^markdq-82]: θεραπεύω: i) to serve, do service, ii) to heal, cure, restore to health

[^markdq-83]: ποικίλος: i) a various colours, variegated, ii) of various sorts

[^markdq-84]: νόσος: disease, sickness

[^markdq-85]: διακονέω: to be a servant, attendant, domestic, to serve, wait upon

[^markdq-86]: ἀφίημι: i) to send away, ii) to permit, allow, not to hinder, to give up a thing to a person, iii) to leave, go way from one

### 記録

-   日時：2023年6月1日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）4名

### 問いについて

### メモ

-   マルコと、マタイ、ルカでは話の続き方が異なっていることに注意。マタイと、ルカには、ヤコブとヨハネが一緒であることは、書かれていない。もしかすると、一緒ではなかったのかもしれない。マタイでは、山上の説教のあと、いくつかの癒しが記されそのあと。ルカでは、弟子たちを招くより前に記されている。曜日も変わっており、マルコでも、20節と、21節の間に、切れ目がある。

-   なぜ人々はイエスに熱病のことを知らせたのだろうか。この時点で、すでに、イエスは癒すことができると信じていたのだろうか。

-   ペテロは結婚していた。（[ペテロの妻について](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-ペテロの妻について)）

    -   1コリント9:5 わたしたちには、ほかの使徒たちや主の兄弟たちや**ケパ**のように、信者である妻を連れて歩く権利がないのか。

    -   アレキサンドリアの教父ク レメンス 150--215 は伝説と して、ペテロの妻は、バルナバの兄弟アリストブロスの 娘で、ペルペチュアまたはコ ンコルディアとよんでいる伝説もある。

-   なぜ、[イザヤ53章](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-イザヤ書53章)4節を引用したのか。

    -   ChatGPT: マタイ8:17におけるイザヤ書53章の預言の引用には、イエス・キリストの「苦難のしもべ」であること、彼が人々を救う力を持っていること、そして彼が人々を救うために犠牲を払ったことを示す意味が含まれています。また、この引用は、キリスト教徒にとって、復活や救いの希望を与えるものでもあります。

    -   一般的には、共観福音書では、贖罪のための苦難というモチーフは薄い。癒しと悪霊を追い出すこと自体に、イザヤ書に結びつくものを認めていたのだろう。

    -   イザヤ53章の、マタイ8:17 以外での引用。ルカ22:37 （マルコ15:28）、使徒8:32-35。

    -   ユダヤ教での解釈は、異なること、および、旧約聖書のギリシャ語訳セプチュアギンタの表現も関係していることの確認も、必要。

-   いやしについて：三つの[ギリシャ語](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#healing)

    -   いやしのたいせつな部分は、病人、悪霊に憑かれている人の苦しみを和らげること。現代的な医療（だけ）が、いやしというわけではない。その苦しみを受け取ること、ケアすること、こころをこめて治療すること、それは、免疫力をあげることにも資するかもしれない。それには、罪が赦されること、手などに触れて、安心できること、医療行為が進んでも、それは、残るかもしれない。

-   「また多くの悪霊を追い出された。また、悪霊どもに、物言うことをお許しにならなかった。彼らがイエスを知っていたからである。」とあるが、24節では、物を言っているのでは。この時も、これ以上言わせなかったようなので、それを言っているのか。

## 1:35-39 巡回して宣教する

> 1:35 朝はやく、夜の明けるよほど前に、イエスは起きて寂しい所へ出て行き、そこで祈っておられた。 36 すると、シモンとその仲間とが、あとを追ってきた。37 そしてイエスを見つけて、「みんなが、あなたを捜しています」と言った。 38 イエスは彼らに言われた、「ほかの、附近の町々にみんなで行って、そこでも教を宣べ伝えよう。わたしはこのために出てきたのだから」。  39 そして、ガリラヤ全地を巡りあるいて、諸会堂で教えを宣べ伝え、また悪霊を追い出された。 

### ルカ 4:42-44

> 4:42 夜が明けると、イエスは寂しい所へ出て行かれたが、群衆が捜しまわって、みもとに集まり、自分たちから離れて行かれないようにと、引き止めた。 43 しかしイエスは、「わたしは、ほかの町々にも神の国の福音を宣べ伝えねばならない。自分はそのためにつかわされたのである」と言われた。 44 そして、ユダヤの諸会堂で教を説かれた。 

[マルコによる福音書1章35-39節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_35-39.pdf)

### 問い

1.  21節から34節を読み、前日の出来事を思い起こしてみましょう。どんなことがありましたか。

2.  イエスの祈りについてどんなことがわかりますか。

3.  人々はなぜ、イエスを探しているのでしょうか。

4.  イエスは、どのように答え、またそのあと、どのような活動をしましたか。

5.  イエスは、なぜ、「附近の町々にみんなで行って、教えを宣べ伝える」ことを選んだのでしょう。

6.  イエスは教えを宣べ伝えることと、悪霊を追い出したり、病をいやしたりすることについて、どのように考えていたのでしょうか。

7.  イエスは、福音宣教の初期の活動で、どのような経験をし、何を神様の御心として受け取ったのでしょうか。

### 参照

-   この前日（安息日とその夜）のこと

    1.  カペナウムの会堂で教えた。 （21-22）

    2.  けがれた霊を追い出す。（23-27）

    3.  イエスのうわさが、たちまちガリラヤの全地方、いたる所にひろまった。 （28）

    4.  シモンのしゅうとめの熱病を癒す。（29-31）

    5.  日没後、人々は病人や悪霊につかれた者をみな、イエスのところに連れてきて、町中の者が戸口に集まった。（32,33）

    6.  さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出した。（34a）

-   イエスの祈りの記録（参考：[祈りについて](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-祈りについて)）

    -   **受洗：**ルカ3:21-22 さて、民衆がみなバプテスマを受けたとき、イエスもバプテスマを受けて祈っておられると、天が開けて、 聖霊がはとのような姿をとってイエスの上に下り、そして天から声がした、「あなたはわたしの愛する子、わたしの心にかなう者である」。 

    -   **活動的な安息日明け：**マルコ1:35 朝はやく、夜の明けるよほど前に、イエスは起きて寂しい所へ出て行き、そこで祈っておられた。**（重い皮膚病の人を癒してから）**ルカ5:16 しかしイエスは、寂しい所に退いて祈っておられた。

    -   **十二弟子の選出前：**ルカ6:12 このころ、イエスは祈るために山へ行き、夜を徹して神に祈られた。

    -   **五千人給食後：**マルコ6:46 そして群衆に別れてから、祈るために山へ退かれた。マタイ14:23 そして群衆を解散させてから、祈るためひそかに山へ登られた。夕方になっても、ただひとりそこにおられた。 ヨハネ6:15 イエスは人々がきて、自分をとらえて王にしようとしていると知って、ただひとり、また山に退かれた。 

    -   **ペテロの告白・受難告知前：**ルカ9:18 イエスがひとりで祈っておられたとき、弟子たちが近くにいたので、彼らに尋ねて言われた、「群衆はわたしをだれと言っているか」。

    -   **山上の変貌：**ルカ9:28-29 これらのことを話された後、八日ほどたってから、イエスはペテロ、ヨハネ、ヤコブを連れて、祈るために山に登られた。29 祈っておられる間に、み顔の様が変り、み衣がまばゆいほどに白く輝いた。 祈っておられる間に、み顔の様が変り、み衣がまばゆいほどに白く輝いた。 

    -   **逮捕直前（ゲッセマネの祈り）：**マルコ14:32-42、マタイ26:39-46 、ルカ22:40-45、ヨハネ17章（とりなしの祈り）

        -   マルコ14:36「アバ、父よ、あなたには、できないことはありません。どうか、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころのままになさってください」。

    -   他にもイエスが神に語りかける場所として

        -   ヨハネ6:11 そこで、イエスはパンを取り、感謝してから、すわっている人々に分け与え、また、さかなをも同様にして、彼らの望むだけ分け与えられた。

        -   ヨハネ11:41,42 人々は石を取りのけた。すると、イエスは目を天にむけて言われた、「父よ、わたしの願いをお聞き下さったことを感謝します。42 あなたがいつでもわたしの願いを聞きいれて下さることを、よく知っています。しかし、こう申しますのは、そばに立っている人々に、あなたがわたしをつかわされたことを、信じさせるためであります」。

        -   ヨハネ12:27, 28 今わたしは心が騒いでいる。わたしはなんと言おうか。父よ、この時からわたしをお救い下さい。しかし、わたしはこのために、この時に至ったのです。 父よ、み名があがめられますように」。28 すると天から声があった、「わたしはすでに栄光をあらわした。そして、更にそれをあらわすであろう」。 

> **35** Καὶ πρωῒ[^markdq-87] ἔννυχα[^markdq-88] λίαν[^markdq-89] ἀναστὰς[^markdq-90] ἐξῆλθεν καὶ ἀπῆλθεν[^markdq-91] εἰς ἔρημον[^markdq-92] τόπον κἀκεῖ προσηύχετο[^markdq-93]. **36** καὶ κατεδίωξεν[^markdq-94] αὐτὸν Σίμων καὶ οἱ μετ' αὐτοῦ, **37** καὶ εὗρον[^markdq-95] αὐτὸν καὶ λέγουσιν αὐτῷ ὅτι πάντες ζητοῦσίν[^markdq-96] σε. **38** καὶ λέγει αὐτοῖς· ἄγωμεν[^markdq-97] ἀλλαχοῦ εἰς τὰς ἐχομένας κωμοπόλεις[^markdq-98], ἵνα καὶ ἐκεῖ κηρύξω[^markdq-99]· εἰς τοῦτο γὰρ ἐξῆλθον. **39** Καὶ ἦλθεν κηρύσσων εἰς τὰς συναγωγὰς αὐτῶν εἰς ὅλην τὴν Γαλιλαίαν καὶ τὰ δαιμόνια ἐκβάλλων.

[^markdq-87]: πρωΐ: i) in the morning, early, ii) he fourth watch of the night, from 3 o'clock in the morning until 6 o'clock approximately

[^markdq-88]: ἔννυχος: nightly, nocturnal

[^markdq-89]: λίαν: greatly, exceedingly, exceedingly beyond measure

[^markdq-90]: ἀνίστημι: i) to cause to rise up, raise up, ii) to rise, stand up, iii) at arise, appear, stand forth

[^markdq-91]: ἀπέρχομαι: i) to go away, depart, ii) to go away

[^markdq-92]: ἔρημος: solitary, lonely, desolate, uninhabited

[^markdq-93]: προσεύχομαι: to offer prayers, to pray

[^markdq-94]: καταδιώκω: to follow after, follow up

[^markdq-95]: εὑρίσκω: i) to come upon, hit upon, to meet with, ii) to find by enquiry, thought, examination, scrutiny, observation, to find out by practice and experience, iii) to find out for one's self, to acquire, get, obtain, procure

[^markdq-96]: ζητέω: i) to seek in order to find, ii) to seek i.e. require, demand

[^markdq-97]: ἄγω: i) to lead, take with one, ii) to lead, iii) to pass a day, keep or celebrate a feast, etc., iv) to go, depart

[^markdq-98]: κωμόπολις: a village approximating in size and number of inhabitants to a city, a village city, a town

[^markdq-99]: κηρύσσω: i) to be a herald, to officiate as a herald, ii) to publish, proclaim openly: something which has been done, iii) used of the public proclamation of the gospel and matters pertaining to it, made by John the Baptist, by Jesus, by the apostles and other Christian teachers

### 記録

-   日時：2023年6月8日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）5名

### 問いについて

### メモ

-   イエスに焦点があたっているが、人々と、弟子たちもその場にいるので、それぞれの人たちが、何を求めているかも、考えてみたい。特に、弟子たちは、人々と同じなのか、イエスに近いのか、微妙な立ち位置に感じる。

-   口語訳では「みんな」が2回出てくる。まず、36 「シモンとその仲間とが、あとを追ってきた。」「37 みんなが、あなたを捜しています」38 「ほかの、附近の町々にみんなで行って、そこでも教を宣べ伝えよう。わたしはこのために出てきたのだから」。「みんな」は誰だろうか。イエスと共に行動するものだろうか。主とイエス、イエスとみんな。イエスの祈りの内容を知りたい。

-   イエスが「朝はやく、夜の明けるよほど前」に「寂しい所へ出て行き」祈っていたことが書かれている。ルカにその記述はないが、重い皮膚病のひとの癒しの後5章15,16節に「15 しかし、イエスの評判はますますひろまって行き、おびただしい群衆が、教を聞いたり、病気をなおしてもらったりするために、集まってきた。 16 しかしイエスは、寂しい所に退いて祈っておられた。」の記述がある。

-   マルコの前段でも「32 夕暮になり日が沈むと、人々は病人や悪霊につかれた者をみな、イエスのところに連れてきた。 33 こうして、町中の者が戸口に集まった。 34 イエスは、さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出された。また、悪霊どもに、物言うことをお許しにならなかった。彼らがイエスを知っていたからである。」とあり、やはり、前段の並行箇所である、マタイ8章16節でも「夕暮になると、人々は悪霊につかれた者を大ぜい、みもとに連れてきたので、イエスはみ言葉をもって霊どもを追い出し、病人をことごとくおいやしになった。」とあり、ルカには、大勢の記録が、上記の箇所にあることから、同様の時期または背景のもとで、祈ったことが推測できる。

-   イエスのことばと行動だけから判断すると、ルカの表現を借りると「イエスの評判はますますひろまって行き、おびただしい群衆が、教を聞いたり、病気をなおしてもらったりするために、集まってきた。」ときに、祈り、「38 ほかの、附近の町々にみんなで行って、そこでも教を宣べ伝えよう。わたしはこのために出てきたのだから」。と言って、その場を退いたことがわかる。

-   続いて「39 そして、ガリラヤ全地を巡りあるいて、諸会堂で教えを宣べ伝え、また悪霊を追い出された。」とあり、教えを述べ伝えるだけではなく、悪霊を追い出すこともしている。このあとの、思い皮膚病を患っている人の癒しからも、病気も癒したと思われる。活動に変化はないように見える。

-   祈り（主との対話）の中で、思いとずれていること、しかし、御心に従う、マルコ14:36「アバ、父よ、あなたには、できないことはありません。どうか、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころのままになさってください」。と近いことが示されたのかもしれない。

-   「神の国は近い」の共有の、難しさを認識しつつ、神の子（しもべ）として、歩み続けることを決意したのかもしれない。

## 1:40-45 規定の病を患っている人を清める

> 1:40 ひとりの重い皮膚病にかかった人が、イエスのところに願いにきて、ひざまずいて言った、「みこころでしたら、きよめていただけるのですが」。41 イエスは深くあわれみ、手を伸ばして彼にさわり、「そうしてあげよう、きよくなれ」と言われた。42 すると、重い皮膚病が直ちに去って、その人はきよくなった。 43 イエスは彼をきびしく戒めて、すぐにそこを去らせ、こう言い聞かせられた、 44 「何も人に話さないように、注意しなさい。ただ行って、自分のからだを祭司に見せ、それから、モーセが命じた物をあなたのきよめのためにささげて、人々に証明しなさい」。  45 しかし、彼は出て行って、自分の身に起ったことを盛んに語り、また言いひろめはじめたので、イエスはもはや表立っては町に、はいることができなくなり、外の寂しい所にとどまっておられた。しかし、人々は方々から、イエスのところにぞくぞくと集まってきた。

### マタイ 8:1-4

> 8:1 イエスが山をお降りになると、おびただしい群衆がついてきた。2 すると、そのとき、ひとりの重い皮膚病にかかった人がイエスのところにきて、ひれ伏して言った、「主よ、みこころでしたら、きよめていただけるのですが」。 3 イエスは手を伸ばして、彼にさわり、「そうしてあげよう、きよくなれ」と言われた。すると、重い皮膚病は直ちにきよめられた。4 イエスは彼に言われた、「だれにも話さないように、注意しなさい。ただ行って、自分のからだを祭司に見せ、それから、モーセが命じた供え物をささげて、人々に証明しなさい」。 

### ルカ 5:12-16

> 5:12 イエスがある町におられた時、全身重い皮膚病にかかった人がそこにいた。イエスを見ると、顔を地に伏せて願って言った、「主よ、みこころでしたら、きよめていただけるのですが」。 13 イエスは手を伸ばして彼にさわり、「そうしてあげよう、きよくなれ」と言われた。すると、重い皮膚病がただちに去ってしまった。 14 イエスは、だれにも話さないようにと彼に言い聞かせ、「ただ行って自分のからだを祭司に見せ、それからあなたのきよめのため、モーセが命じたとおりのささげ物をして、人々に証明しなさい」とお命じになった。 15 しかし、イエスの評判はますますひろまって行き、おびただしい群衆が、教を聞いたり、病気をなおしてもらったりするために、集まってきた。 16 しかしイエスは、寂しい所に退いて祈っておられた。

[マルコによる福音書1章40-45節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_40-45.pdf)

### 問い

1.  マルコとともに、マタイとルカも読み、気づいたことを挙げてみましょう。

2.  40節の重い皮膚病の人の言葉からはどんなことが読み取れますか。

3.  イエスについてはどのように描かれていますか。そしてどうなりますか。

4.  イエスは重い皮膚病の人にどのように言い聞かせますか。

5.  なぜ、重い皮膚病の人はイエスが言われたようにはしなかったのでしょうか。そしてどうなりますか。

6.  マルコは「イエス・キリストの福音のはじめ」とこの福音書を書きだし、私達は第一章の終わりまで学んできました。この一章にはイエスがどんな方だと描かれていたでしょうか。あなたはイエスについてどのような印象を受けましたか。

### 参照

#### 重い皮膚病：[参照](#sec-病気)

-   規定の病（日本聖書協会 [重要な訳語の変更](https://www.bible.or.jp/wp-content/uploads/2021/03/si_bible.pdf)）

    旧約におけるヘブライ語ツァラアト：「ツァラアト」(新約においてはギリシア語訳「レプラ」) については、一九九六年の「らい予防法」の廃止も受け、一九九七年に新共同訳の新約において「らい病」と訳され ていたレプラをすべて旧約の訳語に合わせ「重い皮膚病」に改めていましたが、なお同訳語が必ずしも適切なもので ないとの指摘を受け、本新翻訳事業においても当初から検討を続けました。最終的に第七回検討委員会(二〇一七年 三月一三日)において、これを「規定の病」とすることで合意して理事会に答申し、日本聖書協会二〇一八年度第三 回理事会(二〇一八年六月一日)においてこの答申が承認されました。「規定の病」は「律法で規定された病」を意 味し、皮膚だけでなく家や革製品についても同じ訳語を用いることとしました。「規定の病」は「重い」「皮膚」とい う、原語にない意味を含まない点で、従来の「重い皮膚病」の訳語の持つ課題をある程度解決するものと考えていま す。レビ記の関係する箇所の訳文は次のようになります。「祭司がその皮膚の患部を調べて、その患部の毛が白く変 わり、皮膚の下まで及んでいるなら、それは規定の病である。祭司はそれを確認したら、その人を汚けがれていると言い 渡す。」(レビ記一三3)「祭司は行って調べる。家にかびが広がっていたなら、それは家に生じる悪性の規定の病である。その家は汚けがれている。」(レビ記一四 )

-   Q. （新改訳聖書）第3版では，従来の「らい病人」は「ツァラアトに冒された人」と訳されています。「ツァラアト」とは何ですか？　と聞かれた場合、何と答えればよいでしょうか？

    -   A. 聖書のツァラアトは皮膚に現れるだけでなく、家の壁や衣服にも認められる現象であり，それが厳密に何を指しているかはいまだに明らかではありません。しかし，それは「何らかの原因により、人体や物の表面が冒された状態」を描写しています。(第3版「あとがき」より）[新聖書刊行会Q&Aからの引用](https://www.seisho.or.jp/archives/about-3rd/q-and-a/)

-   レビ記13:44,45 その人は重い皮膚病に冒された者であって、汚れた者である。祭司はその人を確かに汚れた者としなければならない。患部が頭にあるからである。重い皮膚病の患者は、その衣服を裂き、その頭を現し、その口ひげをおおって『汚れた者、汚れた者』と呼ばわらなければならない。

-   レビ記14章:1-32 1 主はまたモーセに言われた、2「重い皮膚病の患者が清い者とされる時のおきては次のとおりである。すなわち、その人を祭司のもとに連れて行き、3 祭司は宿営の外に出て行って、その人を見、もし重い皮膚病の患部がいえているならば、

#### ギリシャ語の言葉

-   **深くあわれむ** σπλαγχνίζομαι**:** 12回 マタイ9:36, 14:14, 15:32, 18:27, マルコ1:41, 6:34, 8:2, 9:22, ルカ7:13, 10:33, 15:20。 [参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#%E6%86%90%E3%82%8C%E3%81%BF)

-   **きびしく戒め** ἐμβριμάομαι (em-brim-ah'-om-ahee)**:** 5回 マタイ9:30, マルコ1:43, 14:5, ヨハネ11:33

> **40** Καὶ ἔρχεται πρὸς αὐτὸν λεπρὸς[^markdq-100] π11:38αρακαλῶν[^markdq-101] αὐτὸν \[καὶ γονυπετῶν[^markdq-102]\] καὶ λέγων αὐτῷ ὅτι ἐὰν θέλῃς[^markdq-103] δύνασαί[^markdq-104] με καθαρίσαι[^markdq-105]. **41** καὶ σπλαγχνισθεὶς[^markdq-106] ἐκτείνας τὴν χεῖρα αὐτοῦ ἥψατο[^markdq-107] καὶ λέγει αὐτῷ· θέλω, καθαρίσθητι· **42** καὶ εὐθὺς ἀπῆλθεν ἀπ' αὐτοῦ ἡ λέπρα, καὶ ἐκαθαρίσθη. **43** καὶ ἐμβριμησάμενος[^markdq-108] αὐτῷ εὐθὺς ἐξέβαλεν αὐτὸν **44** καὶ λέγει αὐτῷ· ὅρα μηδενὶ μηδὲν εἴπῃς, ἀλλ' ὕπαγε σεαυτὸν δεῖξον[^markdq-109] τῷ ἱερεῖ[^markdq-110] καὶ προσένεγκε[^markdq-111] περὶ τοῦ καθαρισμοῦ σου ἃ προσέταξεν[^markdq-112] Μωϋσῆς, εἰς μαρτύριον[^markdq-113] αὐτοῖς. **45** Ὁ δὲ ἐξελθὼν ἤρξατο[^markdq-114] κηρύσσειν[^markdq-115] πολλὰ καὶ διαφημίζειν[^markdq-116] τὸν λόγον, ὥστε μηκέτι αὐτὸν δύνασθαι φανερῶς εἰς πόλιν εἰσελθεῖν, ἀλλ' ἔξω ἐπ' ἐρήμοις τόποις ἦν· καὶ ἤρχοντο πρὸς αὐτὸν πάντοθεν[^markdq-117].

[^markdq-100]: λεπρός: i) scaly, rough, ii) leprous, affected with leprosy

[^markdq-101]: παρακαλέω: i) to call to one's side, call for, summon, ii) to address, speak to, (call to, call upon), which may be done in the way of exhortation, entreaty, comfort, instruction, etc.

[^markdq-102]: γονυπετέω: to fall on the knees, the act of imploring aid, and of expressing reverence and honour

[^markdq-103]: θέλω: to will, have in mind, intend

[^markdq-104]: δύναμαι: i) to be able, have power whether by virtue of one's own ability and resources, or of a state of mind, or through favourable circumstances, or by permission of law or custom, ii) to be able to do something, iii) to be capable, strong and powerful

[^markdq-105]: καθαρίζω: i) to make clean, cleanse, ii) to pronounce clean in a levitical sense

[^markdq-106]: σπλαγχνίζομαι: to be moved as to one's bowels, hence to be moved with compassion, have compassion (for the bowels were thought to be the seat of love and pity)

[^markdq-107]: ἅπτομαι: to fasten one's self to, adhere to, cling to

[^markdq-108]: ἐμβριμάομαι: to charge with earnest admonition, sternly to charge, threatened to enjoin

[^markdq-109]: δεικνύω: i) to show, expose to the eyes, ii) metaph. to give evidence or proof of a thing

[^markdq-110]: ἱερεύς: i) a priest, one who offers sacrifices and in general in busied with sacred rites, ii) metaph. of Christians, because, purified by the blood of Christ and brought into close intercourse with God, they devote their life to him alone and to Christ

[^markdq-111]: προσφέρω: i) to bring to, lead to, ii) to be borne towards one, to attack, assail

[^markdq-112]: προστάσσω: i) to assign or ascribe to, join to, ii) to enjoin, order, prescribe, command

[^markdq-113]: μαρτύριον: testimony

[^markdq-114]: ἄρχομαι: i) to be the first to do (anything), to begin, ii) to be chief, leader, ruler, iii) to begin, make a beginning

[^markdq-115]: κηρύσσω: i) to be a herald, to officiate as a herald, ii) to publish, proclaim openly: something which has been done, iii) used of the public proclamation of the gospel and matters pertaining to it, made by John the Baptist, by Jesus, by the apostles and other Christian teachers

[^markdq-116]: διαφημίζω: i) to spread abroad, blaze abroad, ii) to spread abroad his fame or renown

[^markdq-117]: πανταχόθεν: from all sides, from every quarter

### 記録

-   日時：2023年6月15日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）7名

### 問いについて

### メモ

-   [重い皮膚病](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-%E6%84%9B%E3%81%99%E3%82%8B)は、ギリシャ語では、λεπρός (lep-ros': scaly, rough ざらざらのでこぼこの) が使われている。ヘブル語で書かれた旧約聖書の מְצֹרָע や、צָרוּעַ （いずれも語根は צָרַע to be diseased of skin, be leprous）の七十人訳の訳語としても使われている。さまざまな皮膚病を表している。しかし、ハンセン氏病のような古代において恐れられていた感染病の症状でもあるため、共同体ではとくに、注意しなければいけない症状だったと思われ、旧約聖書では、その判断は祭司がすることになっており、汚れている・汚れていないの判断と共同体に対する宣言をすることになっていた。

    -   旧約聖書で実際に重い皮膚病にかかったひとについてどのように記述されているか確認することもたいせつ。モーセの手、ミリアム、ナーマン、ウジヤ、アッシリアの包囲のときの重い皮膚病の人たち

-   どうして、もっと単純に、治して下さいと言わないのか

    -   おそらく、病気の苦しさよりも、汚れているとされていることが、社会的にも、自らの尊厳からも、耐え難い苦痛だったのではないだろうか。

-   イエスはなぜモーセの定めの実行を命じたのでしょうか。

    -   社会的につながることが不可欠と理解していたのでは。

-   イエスはなぜ語らないように注意したのだろうか。

    -   イエスは彼らに言われた、「ほかの、附近の町々にみんなで行って、そこでも教を宣べ伝えよう。わたしはこのために出てきたのだから」。（38）が背景にある。

-   気づいたこと

    -   マルコ1:40 ひざまずいて、マタイ、ひれふして、ルカ、顔を地に伏せて願って、と表現が少しずつずれている。マタイ、ルカには、「主よ Κύριε[^markdq-118]」のことばも伴っている。

    -   きよさは、第一に神との交わりが絶たれ、第二に人との交わりが絶たれ、第三に自分の尊厳が失われた（じぶんが自分でいることが許容される、あなたはあなたでいいよと言えない）状態。永遠の滅びにとどまっている状態。

    -   ヨハネ3:36 御子を信じる者は永遠の命をもつ。御子に従わない者は、命にあずかることがないばかりか、神の怒りがその上にとどまるのである」。（たとえ、御子を信じていると言っていたとしても）だれでも、神様の前には、きよくない存在なのかもしれない。それをみとめてひざまずけるかどうか。

    -   マルコ1:41 深く憐れんで、手を伸ばして（きよくない）彼にさわり。いやしのことばは、共観福音書共通「そうしてあげよう、きよくなれ」

    -   マルコ1:42 直ちに治るとはどういうことだろうか。ちょっと想像しにくい。それがわかる兆候はあったのだろう。治ったことがわかる程度になおり始めたのかもしれない。重い皮膚病が何であったかは、問うても仕方がないように思う。

    -   マルコ1:43,44 誰にも言わず、祭司に見せ、献げものをし、人々に証明。これらが全体的な回復には、必要であるとイエスが考えたからだろう。自分に対して、神様に対して、人々に対して関係を回復することは本質的なのだろう。たんに、群衆が押し寄せてくる、不都合を嫌ったわけではないかもしれない。

    -   ルカには、教えを聴きにきたことも含まれている。

-   一章を通して：人間は、自分のことを思い、主の苦しみ、痛み、望みを知ろうとしない。それでも、イエスは、種を蒔き続ける。神様がそれを育ててくださると信頼しているからか。わたしは、イエスのように、Be available, stay vulnerable でありつつ、主の、苦しみと痛みを、少しでも受け取り、主の望みを受け取っていきたい。とても、難しいことだろうが。

[^markdq-118]: κύριος:he to whom a person or thing belongs, about which he has power of deciding; master, lord, the Sept.for אָדון, בַּעַל

## 2:1-12 体の麻痺した人を癒やす

> 2:1 幾日かたって、イエスがまたカペナウムにお帰りになったとき、家におられるといううわさが立ったので、 2 多くの人々が集まってきて、もはや戸口のあたりまでも、すきまが無いほどになった。そして、イエスは御言を彼らに語っておられた。3 すると、人々がひとりの中風の者を四人の人に運ばせて、イエスのところに連れてきた。 4 ところが、群衆のために近寄ることができないので、イエスのおられるあたりの屋根をはぎ、穴をあけて、中風の者を寝かせたまま、床をつりおろした。 5 イエスは彼らの信仰を見て、中風の者に、「子よ、あなたの罪はゆるされた」と言われた。 6 ところが、そこに幾人かの律法学者がすわっていて、心の中で論じた、7 「この人は、なぜあんなことを言うのか。それは神をけがすことだ。神ひとりのほかに、だれが罪をゆるすことができるか」。 8 イエスは、彼らが内心このように論じているのを、自分の心ですぐ見ぬいて、「なぜ、あなたがたは心の中でそんなことを論じているのか。 9 中風の者に、あなたの罪はゆるされた、と言うのと、起きよ、床を取りあげて歩け、と言うのと、どちらがたやすいか。 10 しかし、人の子は地上で罪をゆるす権威をもっていることが、あなたがたにわかるために」と彼らに言い、中風の者にむかって、11 「あなたに命じる。起きよ、床を取りあげて家に帰れ」と言われた。 12 すると彼は起きあがり、すぐに床を取りあげて、みんなの前を出て行ったので、一同は大いに驚き、神をあがめて、「こんな事は、まだ一度も見たことがない」と言った。

### マタイ 9:1-8

> 1 さて、イエスは舟に乗って海を渡り、自分の町に帰られた。 2 すると、人々が中風の者を床の上に寝かせたままでみもとに運んできた。イエスは彼らの信仰を見て、中風の者に、「子よ、しっかりしなさい。あなたの罪はゆるされたのだ」と言われた。 3 すると、ある律法学者たちが心の中で言った、「この人は神を汚している」。4 イエスは彼らの考えを見抜いて、「なぜ、あなたがたは心の中で悪いことを考えているのか。 5 あなたの罪はゆるされた、と言うのと、起きて歩け、と言うのと、どちらがたやすいか。 6 しかし、人の子は地上で罪をゆるす権威をもっていることが、あなたがたにわかるために」と言い、中風の者にむかって、「起きよ、床を取りあげて家に帰れ」と言われた。7 すると彼は起きあがり、家に帰って行った。 8 群衆はそれを見て恐れ、こんな大きな権威を人にお与えになった神をあがめた。

### ルカ 5:17-26

> 17 ある日のこと、イエスが教えておられると、ガリラヤやユダヤの方々の村から、またエルサレムからきたパリサイ人や律法学者たちが、そこにすわっていた。主の力が働いて、イエスは人々をいやされた。18 その時、ある人々が、ひとりの中風をわずらっている人を床にのせたまま連れてきて、家の中に運び入れ、イエスの前に置こうとした。19 ところが、群衆のためにどうしても運び入れる方法がなかったので、屋根にのぼり、瓦をはいで、病人を床ごと群衆のまん中につりおろして、イエスの前においた。20 イエスは彼らの信仰を見て、「人よ、あなたの罪はゆるされた」と言われた。21 すると律法学者とパリサイ人たちとは、「神を汚すことを言うこの人は、いったい、何者だ。神おひとりのほかに、だれが罪をゆるすことができるか」と言って論じはじめた。22 イエスは彼らの論議を見ぬいて、「あなたがたは心の中で何を論じているのか。23 あなたの罪はゆるされたと言うのと、起きて歩けと言うのと、どちらがたやすいか。24 しかし、人の子は地上で罪をゆるす権威を持っていることが、あなたがたにわかるために」と彼らに対して言い、中風の者にむかって、「あなたに命じる。起きよ、床を取り上げて家に帰れ」と言われた。25 すると病人は即座にみんなの前で起きあがり、寝ていた床を取りあげて、神をあがめながら家に帰って行った。26 みんなの者は驚嘆してしまった。そして神をあがめ、おそれに満たされて、「きょうは驚くべきことを見た」と言った。

[マルコによる福音書2章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_1-12.pdf)

### 問い

1.  マルコを読み、ここで起こったことを確認し、気づいたこと、疑問点を挙げてみましょう。

2.  中風の人はどのように運ばれてきましたか。なぜこれほど人が集まっていたのでしょう。イエスは何をしているところでしたか。マタイやルカも合わせて状況を想像してみましょう。

3.  イエスはどうしますか。中風の人にはこのことばはどう響いたと思いますか。

4.  「彼らの信仰」とは誰のどのような信仰なのでしょうか。

5.  律法学者は、どう反応しますか。なぜ、そのような反応をするのでしょうか。

6.  イエスは、どんなことを気付かせるために9節の質問をしていますか。イエスの問いに対して律法学者はどう考えていたでしょう。あなたは、どう考えますか。

7.  イエスは、中風の人にどのように命じ、そして、どうなりますか。

### 参照

-   パリサイ人・律法学者：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-パリサイ人)
-   病気と罪の関係：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-病気と罪の関係)
-   中風（παραλυτικός）について：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-中風)
-   人の子（ὁ υἱὸς τοῦ ἀνθρώπου）：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-人の子)

> **1** Καὶ εἰσελθὼν[^markdq-119] πάλιν εἰς Καφαρναοὺμ δι' ἡμερῶν ἠκούσθη[^markdq-120] ὅτι ἐν οἴκῳ ἐστίν. **2** καὶ συνήχθησαν[^markdq-121] πολλοὶ ὥστε μηκέτι χωρεῖν[^markdq-122] μηδὲ τὰ πρὸς τὴν θύραν, καὶ ἐλάλει αὐτοῖς τὸν λόγον. **3** Καὶ ἔρχονται[^markdq-123] φέροντες[^markdq-124] πρὸς αὐτὸν παραλυτικὸν[^markdq-125] αἰρόμενον[^markdq-126] ὑπὸ τεσσάρων. **4** καὶ μὴ δυνάμενοι[^markdq-127] προσενέγκαι[^markdq-128] αὐτῷ διὰ τὸν ὄχλον ἀπεστέγασαν[^markdq-129] τὴν στέγην[^markdq-130] ὅπου ἦν, καὶ ἐξορύξαντες[^markdq-131] χαλῶσιν[^markdq-132] τὸν κράβαττον[^markdq-133] ὅπου ὁ παραλυτικὸς[^markdq-134] κατέκειτο[^markdq-135]. **5** καὶ ἰδὼν[^markdq-136] ὁ Ἰησοῦς τὴν πίστιν[^markdq-137] αὐτῶν λέγει τῷ παραλυτικῷ· τέκνον, ἀφίενταί[^markdq-138] σου αἱ ἁμαρτίαι. **6** Ἦσαν δέ τινες τῶν γραμματέων ἐκεῖ καθήμενοι[^markdq-139] καὶ διαλογιζόμενοι[^markdq-140] ἐν ταῖς καρδίαις αὐτῶν· **7**τί οὗτος οὕτως λαλεῖ; βλασφημεῖ[^markdq-141]· τίς δύναται ἀφιέναι ἁμαρτίας εἰ μὴ εἷς ὁ θεός; **8** καὶ εὐθὺς ἐπιγνοὺς[^markdq-142] ὁ Ἰησοῦς τῷ πνεύματι αὐτοῦ ὅτι οὕτως διαλογίζονται ἐν ἑαυτοῖς λέγει αὐτοῖς· τί ταῦτα διαλογίζεσθε ἐν ταῖς καρδίαις ὑμῶν; **9** τί ἐστιν εὐκοπώτερον[^markdq-143], εἰπεῖν τῷ παραλυτικῷ· ἀφίενταί σου αἱ ἁμαρτίαι, ἢ εἰπεῖν· ἔγειρε καὶ ἆρον[^markdq-144] τὸν κράβαττόν σου καὶ περιπάτει;**10** ἵνα δὲ εἰδῆτε[^markdq-145] ὅτι ἐξουσίαν ἔχει ὁ υἱὸς τοῦ ἀνθρώπου ἀφιέναι ἁμαρτίας ἐπὶ τῆς γῆς-- λέγει τῷ παραλυτικῷ· **11** σοὶ λέγω, ἔγειρε[^markdq-146] ἆρον τὸν κράβαττόν σου καὶ ὕπαγε εἰς τὸν οἶκόν σου. **12** καὶ ἠγέρθη[^markdq-147] καὶ εὐθὺς ἄρας τὸν κράβαττον ἐξῆλθεν ἔμπροσθεν πάντων, ὥστε ἐξίστασθαι[^markdq-148] πάντας καὶ δοξάζειν[^markdq-149] τὸν θεὸν λέγοντας ὅτι οὕτως οὐδέποτε εἴδομεν.

[^markdq-119]: εἰσέρχομαι (2AAI-3S): to go out or come in: to enter

[^markdq-120]: ἀκούω (API-3S): i) to be endowed with the faculty of hearing, not deaf, ii) to hear, iii) to hear something

[^markdq-121]: συνάγω (API-3P): i) to gather together, to gather, ii) to bring together, assemble, collect, iii) to lead with one's self

[^markdq-122]: χωρέω (PAN): i) to leave space (which may be filled or occupied by another), to make room, give place, yield, ii) to go forward, advance, proceed, succeed, iii) to have space or room for receiving or holding something

[^markdq-123]: ἔρχομαι (PNI-3P) N: middle or passive doponent

[^markdq-124]: φέρω (PAP-NPM): i) to carry, ii) to bear, i.e. endure, to endure the rigour of a thing, to bear patiently one's conduct, or spare one (abstain from punishing or destroying), iii) to bring, bring to, bring forward

[^markdq-125]: παραλυτικός: paralytic

[^markdq-126]: αἴρω (PPP-ASM): i) to raise up, elevate, lift up, ii) to take upon one's self and carry what has been raised up, to bear, iii) to bear away what has been raised, carry off

[^markdq-127]: PNP-NPM

[^markdq-128]: προσεγγίζω (AAN): to approach unto

[^markdq-129]: ἀποστεγάζω (AAI-3P): to uncover, take off the roof

[^markdq-130]: στέγη (ASF): a roof: of a house

[^markdq-131]: ἐξορύσσω (AAP-NPM): i) to dig out, to pluck out (the eyes), ii) to dig through

[^markdq-132]: χαλάω (PAI-3P): i) to loosen, slacken, relax, ii) to let down from a higher place to a lower

[^markdq-133]: κράβαττος (ASM): a pallet, camp bed (a rather simple bed holding only one person)

[^markdq-134]: παραλυτικός (NSM): paralytic; a) suffering from the relaxing of the nerves of one's side, b) disabled, weak of limb

[^markdq-135]: κατάκειμαι (INI-3S): to have lain down, i.e. to lie prostrate; a) of the sick, b) of those at meals, to recline

[^markdq-136]: ὁράω (2AAP-NSM): i) to see with the eyes, ii) to see with the mind, to perceive, know, iii) to see, i.e. become acquainted with by experience, to experience, iv) to see, to look to, v) I was seen, showed myself, appeared

[^markdq-137]: πίστις (ASF): i) conviction of the truth of anything, belief; in the NT of a conviction or belief respecting man's relationship to God and divine things, generally with the included idea of trust and holy fervour born of faith and joined with it, ii) fidelity, faithfulness

[^markdq-138]: ἀφίημι (RPI-3P): i) to send away, ii) to permit, allow, not to hinder, to give up a thing to a person, iii) to leave, go way from one

[^markdq-139]: κάθημαι (PNP-NPM): i) to sit down, seat one's self, ii) to sit, be seated, of a place occupied

[^markdq-140]: διαλογίζομαι (PNP-NPM): to bring together different reasons, to reckon up the reasons, to reason, revolve in one's mind, deliberate

[^markdq-141]: βλασφημία (APF): i) slander, detraction, speech injurious, to another's good name, ii) impious and reproachful speech injurious to divine majesty

[^markdq-142]: ἐπιγινώσκω (2AAP-NSM): i) to become thoroughly acquainted with, to know thoroughly, ii) to know

[^markdq-143]: εὔκοπος (NSN-C): i) with easy labour, ii) easy

[^markdq-144]: αἴρω (AAM-2S): i) to raise up, elevate, lift up, ii) to take upon one's self and carry what has been raised up, to bear, iii) to bear away what has been raised, carry off

[^markdq-145]: εἴδω (RAS-2P): i) to see, ii) to know

[^markdq-146]: ἐγείρω (AMM-2S): to arouse, cause to rise

[^markdq-147]: ἐγείρω (API-3S): to arouse, cause to rise

[^markdq-148]: ἐξίστημι (PMN): to throw out of position, displace

[^markdq-149]: δοξάζω (PAN): i) to think, suppose, be of opinion, ii) to praise, extol, magnify, celebrate, iii) to honour, do honour to, hold in honour, iv) to make glorious, adorn with lustre, clothe with splendour

### 記録

-   日時：2023年6月22日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  少し長いので、まずは、マルコで全体を確認。

2.  **中風の人が運ばれてきた時の様子**

    -   **どのように運ばれてきたか**「人々が」「四人の人に」「中風の人を」運ばせて、イエスのもとに連れてきた。

    -   **なぜこれほど人が集まったか。**マルコ（だけ）にはカペナウムでの出来事であったことが記されている（1）（マタイは「自分の町」（1））。「1:32 夕暮になり日が沈むと、人々は病人や悪霊につかれた者をみな、イエスのところに連れてきた。 33 こうして、町中の者が戸口に集まった。 34 イエスは、さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出された。」と、ある。また、寂しいところに祈りにいくと人々は捜していた。（1:38）「1:45 彼（重い皮膚病を癒された人）は出て行って、自分の身に起ったことを盛んに語り、また言いひろめはじめたので、イエスはもはや表立っては町に、はいることができなくなり、外の寂しい所にとどまっておられた。しかし、人々は方々から、イエスのところにぞくぞくと集まってきた。」

    -   **イエスは何をしていたか「**御言を彼らに語っておられた。**」**つまり説教中、それでも対応。なぜだろうか。次の問いにつながる。

3.  **イエスのことば、中風のひとの受け取り方**

    -   イエスは彼らの信仰を見て、中風の者に、「子よ、あなたの罪はゆるされた」と言われた。

    -   こう言われたということは、このひとは、やはり罪の中に生きていたということだろうか。

    -   自分では何もできないことに、罪悪感を感じていたかもしれない。役立たず。

    -   彼らの信仰の部分は、次の問いに続く。ここでは、「み言葉を語ること」を中断して。

    -   中風の人も驚いたかもしれない。社会一般的には、中風は罪の故と思っていたかもしれないが、このひとを連れてきた人たちの様子からは、そのような因果応報的な考えかたは見て取れない。それが「（神は憐れんでくださる、これが当然の罪の帰結で許されないものだとは思っていない）信仰」と表現されているのかもしれない。社会的認識が一般的にあったとしてのそれに支配されているとも限らない。

    -   マルコでは「子よ」、マタイでは「子よ、しっかりしなさい」、ルカでは「人よ」と呼びかけ方が異なっている。この呼びかけのことばは、どう理解したら良いのだろうか。ある権威を示している？

4.  **「彼らの信仰」とは**

    -   誰：マルコでは、人々？　マタイでも人々、ルカもおそらく人々。四人に限定されるわけではない。どういう人たちで、どのような関係をこの中風のひとと持っており、どう思っており、このような行動をしたのだろうか。このような関係のひとはいるだろうか。

    -   罪の結果だと一般的には思われていたが、神は憐れんでくださるということか。

    -   罪と信仰と愛の関係はどう考えたらよいでしょうか。愛は単なる助け合いではない。神を信頼するものどうしの相互の愛。

5.  **律法学者の反応**

    -   ルカでは「エルサレム方きたパリサイ人や律法学者」となっている。マルコとマタイは「幾人かの律法学者」「律法学者たち」

    -   イエスが見抜いてとなっており、前列に座っていたのかもしれない。

    -   自分が律法学者のような反応をした経験はありますか。そこで、起こったことをみるよりも、成した人の善悪を評価することなど。

6.  **何を気づかせるため**

    -   イエスは、どちらでもそう変わらないと思っていたのではないか。実際、結局両方言っている。

    -   「罪をゆるすことができるのは神のみ」はなぜなのだろうか。罪のゆるしと捉えたということは、律法学者は、罪の結果だと考えていたのかもしれない。

    -   原理主義ではいけない。

7.  **中風の人に何と語り、どうなったか。**

    -   「床を取り上げて家に帰れ」手伝ってもらってここにきたが、自分で動くことを命じられている。眼に見える、「みんなの前を出て行った」変化がある。

    -   一同は驚き、神をあがめて「こんな事は、まだ一度も見たことがない」と言った。

### メモ

-   カペナウム（マタイでは自分の町）：以前の出来事 マルコ1:21-39 汚れた霊に取りつかれた男を癒す、多くの病人を癒す、巡回して宣教する。規定の病を患っている人を清めるは、マルコの流れでは巡回宣教中。

    -   家（1）は、ペトロとアンデレの家か？

-   彼らの信仰：「人々がひとりの中風の者を四人の人に運ばせて、イエスのところに連れてきた。」とあり、人々（マルコは翻訳によるが、マタイでは入っているようだ）、中風の者、四人の人とある。全員だろうか。これは、神様への挑戦でもあるのだろうか。理不尽さ。

-   神を汚す：なぜ、罪を赦すことが、神を汚すことになるのか。神の先決事項に介入したということか。神に目を向けていると言いながら、神の業を、働きを見ていない。完璧を求め、そこに関わった人を見下すことは、あるように思う。

-   人の子：なぜ、自分の子を、人の子と呼んだのだろう。私たちは、人の子ではないのか。人の子、私たちの役割は何なのだろうか。私たちに、同じことは委ねられているのだろうか。罪を赦すこと。受け入れること。同じ人の子として、ともに生きること。罪に定めることの、ひとの世界のことなのかもしれない。

-   ルカ5:26 「驚くべきこと」の内容は何だろうか。受け取り方は、ひとそれぞれだったのかもしれない。中風の人、中風の人を連れてきた人、その他の人々、律法学者、イエス、そして、それを伝える、弟子たち、その人たちの見たものは、さまざまだったのかもしれない。

-   中風の人は、自分の病は、罪の結果かもしれないと考えていた可能性はある。むろん、こんな罰を受けているほどの罪だろうかとの意識もあったかもしれない。そうであっても、自分から、癒してもらいたいとイエスのもとにいくことはできなかったのではないだろうか。すごいことがおこっていると、聞きつけた周囲の人々が、この中風のひとをイエスのもとに連れて行く。そこには、この中風の人を罪人と定める人はおらず、逆に、愛を持って、さらに、神様が憐れんでなしてくださることに期待をかけた人たちがいたのだろう。その信仰に、心が動かされ、イエスは、「子よ、あなたの罪は赦された」と宣言される。それは、この中風の人にとって、どれほどの慰めと救いだったかと思う。まさに、神の国がここにきたのだ。しかし、それを認めることができず、正しさから、違反を見つけようとする人たちがいる。イエスは、このひとたちにもひとこといい、さらに、中風のひとに語りかけ、中風の人は癒される。すべてを理解できたかどうかはわからないが、神様を賛美せざるをえない人たちが、そこにいたのだろう。感謝。

## 2:13-17 レビを弟子にする

> 2:13 イエスはまた海べに出て行かれると、多くの人々がみもとに集まってきたので、彼らを教えられた。 14 また途中で、アルパヨの子レビが収税所にすわっているのをごらんになって、「わたしに従ってきなさい」と言われた。すると彼は立ちあがって、イエスに従った。15 それから彼の家で、食事の席についておられたときのことである。多くの取税人や罪人たちも、イエスや弟子たちと共にその席に着いていた。こんな人たちが大ぜいいて、イエスに従ってきたのである。 16 パリサイ派の律法学者たちは、イエスが罪人や取税人たちと食事を共にしておられるのを見て、弟子たちに言った、「なぜ、彼は取税人や罪人などと食事を共にするのか」。17 イエスはこれを聞いて言われた、「丈夫な人には医者はいらない。いるのは病人である。わたしがきたのは、義人を招くためではなく、罪人を招くためである」。

### マタイ 9:9-13

> 9 さてイエスはそこから進んで行かれ、マタイという人が収税所にすわっているのを見て、「わたしに従ってきなさい」と言われた。すると彼は立ちあがって、イエスに従った。10 それから、イエスが家で食事の席についておられた時のことである。多くの取税人や罪人たちがきて、イエスや弟子たちと共にその席に着いていた。11 パリサイ人たちはこれを見て、弟子たちに言った、「なぜ、あなたがたの先生は、取税人や罪人などと食事を共にするのか」。12 イエスはこれを聞いて言われた、「丈夫な人には医者はいらない。いるのは病人である。13 『わたしが好むのは、あわれみであって、いけにえではない』とはどういう意味か、学んできなさい。わたしがきたのは、義人を招くためではなく、罪人を招くためである」。

### ルカ 5:27-32

> 27 そののち、イエスが出て行かれると、レビという名の取税人が収税所にすわっているのを見て、「わたしに従ってきなさい」と言われた。28 すると、彼はいっさいを捨てて立ちあがり、イエスに従ってきた。29 それから、レビは自分の家で、イエスのために盛大な宴会を催したが、取税人やそのほか大ぜいの人々が、共に食卓に着いていた。30 ところが、パリサイ人やその律法学者たちが、イエスの弟子たちに対してつぶやいて言った、「どうしてあなたがたは、取税人や罪人などと飲食を共にするのか」。31 イエスは答えて言われた、「健康な人には医者はいらない。いるのは病人である。32 わたしがきたのは、義人を招くためではなく、罪人を招いて悔い改めさせるためである」。

[マルコによる福音書2章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_13-17.pdf)

### 問い

1.  マルコを読み、ここで起こったことを確認し、気づいたこと、疑問点を挙げてみましょう。

2.  レビついてどのようなことがわかりますか。マタイやルカも確認しましょう。

3.  この人の家での食卓には、どんな人たちがついていますか。

4.  パリサイ派の律法学者たちは、誰に、どんなことを聞いていますか。

5.  イエスはこれに対して何と言っていますか。

6.  「罪人を招く」とはどういうことでしょうか。

7.  イエスに従ってきたのは、どのような人たちでしょうか。現代では、それは、どんな人たちで、その人たちを招くことは、どのようなことを意味しているのでしょう。

### 参照

-   マタイ[^markdq-150]（ヤーヴェからの賜り物、アルパヨの子レビ）についての記述（今回の箇所以外）

    -   マルコ3:16-19 こうして、この十二人をお立てになった。そしてシモンにペテロという名をつけ、17 またゼベダイの子ヤコブと、ヤコブの兄弟ヨハネ、彼らにはボアネルゲ、すなわち、雷の子という名をつけられた。18 つぎにアンデレ、ピリポ、バルトロマイ、**マタイ**、トマス、アルパヨの子ヤコブ、タダイ、熱心党のシモン、19 それからイスカリオテのユダ。このユダがイエスを裏切ったのである。イエスが家にはいられると、

    -   マタイ10:2-4 十二使徒の名は、次のとおりである。まずペテロと呼ばれたシモンとその兄弟アンデレ、それからゼベダイの子ヤコブとその兄弟ヨハネ、3 ピリポとバルトロマイ、トマスと取税人**マタイ**、アルパヨの子ヤコブとタダイ、4 熱心党のシモンとイスカリオテのユダ。このユダはイエスを裏切った者である。 

    -   ルカ6:14-16 すなわち、ペテロとも呼ばれたシモンとその兄弟アンデレ、ヤコブとヨハネ、ピリポとバルトロマイ、15 **マタイ**とトマス、アルパヨの子ヤコブと、熱心党と呼ばれたシモン、ヤコブの子ユダ、それからイスカリオテのユダ。このユダが裏切者となったのである。 

    -   使徒1:13 彼らは、市内に行って、その泊まっていた屋上の間にあがった。その人たちは、ペテロ、ヨハネ、ヤコブ、アンデレ、ピリポとトマス、バルトロマイと**マタイ**、アルパヨの子ヤコブと熱心党のシモンとヤコブの子ユダとであった。

-   収税人：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-収税人)

    -   ルカ3:12,13 取税人もバプテスマを受けにきて、彼に言った、「先生、わたしたちは何をすればよいのですか」。彼らに言った、「きまっているもの以上に取り立ててはいけない」。 

-   罪人たち：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-罪人たち)

-   ユダとガリラヤの統治者および徴税について：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-統治者について)

-   マタイ9:13： ホセア6:6 「わたしはいつくしみを喜び、犠牲を喜ばない。燔祭よりもむしろ神を知ることを喜ぶ。」כִּי [^markdq-151]חֶסֶד חָפַצְתִּי וְלֹא־זָבַח וְדַעַת אֱלֹהִים מֵעֹלֽוֹת׃

[^markdq-150]: Μαθθαῖος: A shorter form of Ματταθίας (מַתַּתְיָה:A)a Levite who presided over the offerings, B) a Levite appointed by David to minister in the musical service before the ark, C) one of the family of Nebo who had a foreign wife in the time of Ezra, D) one of the men who stood at the right hand of Ezra when he read the law to the people), Matthew = "gift of Jehovah", 1Chronicles [9:31](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_6); [15:18](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_1); [15:21](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_2); [16:5](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_5); [25:3](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_3); [25:21](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_4), Ezra [10:43](https://www.blueletterbible.org/lexicon/h4993/kjv/wlc/0-1/#si_8), Nehemiah 8:4

[^markdq-151]: חֶסֶד (kheh'-sed): i) goodness, kindness, faithfulness, ii) a reproach, shame

> **13** Καὶ ἐξῆλθεν[^markdq-152] πάλιν παρὰ τὴν θάλασσαν· καὶ πᾶς ὁ ὄχλος ἤρχετο πρὸς αὐτόν, καὶ ἐδίδασκεν[^markdq-153] αὐτούς. **14** Καὶ παράγων[^markdq-154] εἶδεν Λευὶν τὸν τοῦ Ἁλφαίου[^markdq-155] καθήμενον[^markdq-156] ἐπὶ τὸ τελώνιον[^markdq-157], καὶ λέγει αὐτῷ· ἀκολούθει μοι. καὶ ἀναστὰς[^markdq-158] ἠκολούθησεν αὐτῷ. **15** Καὶ γίνεται κατακεῖσθαι[^markdq-159] αὐτὸν ἐν τῇ οἰκίᾳ αὐτοῦ, καὶ πολλοὶ τελῶναι[^markdq-160] καὶ ἁμαρτωλοὶ[^markdq-161] συνανέκειντο[^markdq-162] τῷ Ἰησοῦ καὶ τοῖς μαθηταῖς αὐτοῦ· ἦσαν γὰρ πολλοὶ καὶ ἠκολούθουν αὐτῷ **16** καὶ οἱ γραμματεῖς τῶν Φαρισαίων ἰδόντες[^markdq-163] ὅτι ἐσθίει μετὰ τῶν ἁμαρτωλῶν καὶ τελωνῶν ἔλεγον τοῖς μαθηταῖς αὐτοῦ· ὅτι μετὰ τῶν τελωνῶν καὶ ἁμαρτωλῶν ἐσθίει; **17** καὶ ἀκούσας[^markdq-164] ὁ Ἰησοῦς λέγει αὐτοῖς \[ὅτι\] οὐ χρείαν ἔχουσιν οἱ ἰσχύοντες ἰατροῦ ἀλλ' οἱ κακῶς ἔχοντες· οὐκ ἦλθον καλέσαι δικαίους ἀλλ' ἁμαρτωλούς.

[^markdq-152]: ἐξέρχομαι (2AAI-3S): to go or come forth of

[^markdq-153]: διδάσκω (IAI-3S): to teach

[^markdq-154]: παράγω (PAP-NSM): i) pass by, ii) to pass by, go past

[^markdq-155]: ἀκολουθέω (PAM-2S): i) to follow one who precedes, join him as his attendant, accompany him, ii) to join one as a disciple, become or be his disciple

[^markdq-156]: κάθημαι (PNP-ASM): i) to sit down, seat one's self, ii) to sit, be seated, of a place occupied

[^markdq-157]: τελώνιον: i) customs, toll, ii) toll house, place of toll, tax office, iii) the place in which the tax collector sat to collect the taxes

[^markdq-158]: ἀνίστημι (2AAP-NSM): i) to cause to rise up, raise up, ii) to rise, stand up, iii) at arise, appear, stand forth

[^markdq-159]: κατάκειμαι (PNN): to have lain down, i.e. to lie prostrate

[^markdq-160]: τελώνης: i) a renter or farmer of taxes, ii) a tax gatherer, collector of taxes or tolls, one employed by a publican or farmer general in the collection of taxes. The tax collectors were as a class, detested not only by the Jews, but by other nations also, both on account of their employment and of the harshness, greed, and deception, with which they did their job.

[^markdq-161]: ἁμαρτωλός: devoted to sin, a sinner

[^markdq-162]: συνανάκειμαι: to recline together, feast together

[^markdq-163]: ἐσθίω (PAP-ASM): to eat

[^markdq-164]: ἀκούω (APA-NSM): i) to be endowed with the faculty of hearing, not deaf, ii) to hear, iii) to hear something

### 記録

-   日時：2023年6月29日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）5名

### 問いについて

1.  概要

    1.  多くのひとたちがイエスのもとに集まってきて、海辺で教えた。（この背景はマルコのみ）

    2.  収税所にすわっているアルパよの子レビを従うように招く。

    3.  レビは立ち上がって従う。

    4.  レビの家で、イエスに従ってきた多くの収税人や罪人たちが一緒に食卓についていた。

    5.  パリサイ派の律法学者が、弟子たちに、なぜ、罪人や収税人と食事を共にするのかと問う。

    6.  イエスは、罪人を招くためにきたと断言。

2.  アルパヨの子レビについて。

    -   マタイでは、マタイとなっている。マタイと同一人物としてよいか。

        -   マルコ、マタイ、ルカの記述からして、同一人物としてよいと思われる。

    -   収税人だったのだろうか。たまたま収税所に座っていただけなのだろうか。

    -   ルカ5:27には「レビという名の取税人」とあり、マタイと同一してもよいと思われるが、マタイについては、マタイ10:3 には「取税人マタイ」とある。

        -   おそらく、ヘブル語、アラム語、ギリシャ語を話せ、お金もある。しかし、ユダヤ人からは、嫌われ、ユダヤ人であるにもかかわらず、蔑まれていた。

    -   マタイ：マッタテヤ の省略形 歴代誌15:18, 21, 16:5, 25:3, 21, エズラ10:43 。ネヘミヤ8:4 学者エズラはこの事のために、かねて設けた木の台の上に立ったが、彼のかたわらには右の方にマッタテヤ、シマ、アナヤ、ウリヤ、ヒルキヤおよびマアセヤが立ち、左の方にはペダヤ、ミサエル、マルキヤ、ハシュム、ハシバダナ、ゼカリヤおよびメシュラムが立った。

    -   状況証拠からは、レビ族の出身だった可能性が高いように思う。その中でよく知られた、マタイが呼称だったのか、イエスがそう呼んだのかは不明。

    -   イエスが通りすがりに声をかけたように思われる。イエスは、マタイの様子から何を見、なぜ、声をかけたのだろうか。

    -   レビは、イエスの招きに対して「すると彼は立ち上がって、イエスに従った」と書かれている。ペトロたちのときのように、このときが、最初の出会いではないかもしれない。

        -   おそらく、職を失ったと思われる。ルカ5;28 「彼はいっさいを捨てて立ちあがり」
        -   強調することではないかもしれないが、漁師が船と網を置くこととは多少異なる。

3.  食卓に同席していたひとたち。

    -   誰の家か。ルカでは、レビが「イエスのために盛大な宴会を催した」とある。

    -   マルコ、マタイからは、イエスについてきた人たちが、一緒に食事の席についていることがわかる。レビが招いたのだろうか。それとも、イエスに単についてきたのだろうか。

    -   仲間を連れてきたのか。それとも、イエスについてきたひとたちだから、一緒に食事をしたのか。マタイは（驚きはあったかもしれないが）おそらく歓迎しただろうが、パリサイ派の律法学者は違う見方をした。

    -   収税人や罪人とは、どのような人だろうか。（参照からリンク）

4.  パリサイ人の質問：「なぜ、彼は取税人や罪人などと食事を共にするのか」

    -   なぜ、イエスにではなく、弟子たちに聞くのか。レビ（マタイ）や、弟子には、はっきりとは答えられなかったかもしれない。しかし、どう答えたか、聞いてみたかった。それが、我々の一人の応答を明らかにすることでもあるから。

    -   聞く目的は？非難？すでに、危険視されていたと思われる。（体の麻痺した人を癒すの記事参照）

5.  イエスの答え：「丈夫な人には医者はいらない。いるのは病人である。わたしがきたのは、義人を招くためではなく、罪人を招くためである」

    -   イエスにとっては、至極当然のこと。なぜ、疑問に思うのか。とはいえ、たいせつなことを教えている。

    -   義人を招くとは、罪人を招くとは。

    -   マタイ9:13 『わたしが好むのは、あわれみであって、いけにえではない』とはどういう意味か、学んできなさい。は、どのような意味だろうか。だれでも知っている、当たり前のこと。

    -   その当たり前のことを、受け入れられない頑なさを、現代に移して考えてみよう。

6.  現代では

    -   おそらく、さまざまなことを抱え込むことも含まれている。Welcoming Spirits, Availabiity は、vulnerability をも必要とする。それこそが、イエスが体現したこと、イエスの生涯。
    -   自分にたいする神様の憐れみを、他者にたいする神様の憐れみと同等に考えることができない。自分が神様に愛されていること、その応答として、神様を愛することが、神様が愛される他者に向けられることには、困難がある。

### メモ

-   マルコだけが、「13 イエスはまた海べに出て行かれると、多くの人々がみもとに集まってきたので、彼らを教えられた。」と始めている。

-   マルコも、マタイも、ルカも「すわっていた」ことを書いている。何を表しているのだろう。

    -   「立ちあがって（イエスに）従った」と対置されている。悩んでいたかもしれない。そのひとが、一歩を歩み出す。それが、レビにとっては、宴会を催すこと。

-   マルコと、ルカは、レビ（マルコは、アルパヨの子レビ）、マタイは、マタイとし、マルコと、マタイは、収税所に座っていたことだけ書いているが、ルカは、収税人と明確に書いている。

-   ガリラヤ地方は、ローマ皇帝から領主に任ぜられたエドム人ヘロデ・アンティパスの配下にあった。この徴税を行なっていた。（参照：ユダとガリラヤの統治者および徴税について）

-   Anna Karenina Principle (AKP) 「幸福な家庭はどれも似たものだが、不幸な家庭はいずれもそれぞれに不幸なものである All happy families are alike; each unhappy family is unhappy in its own way.」レオ・トルストイ著、アンナ・カレーニナ冒頭（[Leo Tolstoy](https://en.wikipedia.org/wiki/Leo_Tolstoy "Leo Tolstoy")'s 1877 novel [*Anna Karenina*](https://en.wikipedia.org/wiki/Anna_Karenina "Anna Karenina")）

    -   病人も、罪人も、ひとりひとり異なる。義人と、罪人と二分するのでは、本質は捉えられない。イエスが来たのは、神の国が近いとしらせること、それは、すべてのひとを救うためではなく、罪人（神様の国から遠いと思われている・思っている）一人ひとりを招くこと。一人の例外もなく。

## 2:18-22 断食についての問答

> 2:18 ヨハネの弟子とパリサイ人とは、断食をしていた。そこで人々がきて、イエスに言った、「ヨハネの弟子たちとパリサイ人の弟子たちとが断食をしているのに、あなたの弟子たちは、なぜ断食をしないのですか」。19 するとイエスは言われた、「婚礼の客は、花婿が一緒にいるのに、断食ができるであろうか。花婿と一緒にいる間は、断食はできない。 20 しかし、花婿が奪い去られる日が来る。その日には断食をするであろう。 21 だれも、真新しい布ぎれを、古い着物に縫いつけはしない。もしそうすれば、新しいつぎは古い着物を引き破り、そして、破れがもっとひどくなる。22 まただれも、新しいぶどう酒を古い皮袋に入れはしない。もしそうすれば、ぶどう酒は皮袋をはり裂き、そして、ぶどう酒も皮袋もむだになってしまう。〔だから、新しいぶどう酒は新しい皮袋に入れるべきである〕」。

### マタイ 9:14-17

> 14 そのとき、ヨハネの弟子たちがイエスのところにきて言った、「わたしたちとパリサイ人たちとが断食をしているのに、あなたの弟子たちは、なぜ断食をしないのですか」。15 するとイエスは言われた、「婚礼の客は、花婿が一緒にいる間は、悲しんでおられようか。しかし、花婿が奪い去られる日が来る。その時には断食をするであろう。16 だれも、真新しい布ぎれで、古い着物につぎを当てはしない。そのつぎきれは着物を引き破り、そして、破れがもっとひどくなるから。17 だれも、新しいぶどう酒を古い皮袋に入れはしない。もしそんなことをしたら、その皮袋は張り裂け、酒は流れ出るし、皮袋もむだになる。だから、新しいぶどう酒は新しい皮袋に入れるべきである。そうすれば両方とも長もちがするであろう」。 

### ルカ 5:33-39

> 33 また彼らはイエスに言った、「ヨハネの弟子たちは、しばしば断食をし、また祈をしており、パリサイ人の弟子たちもそうしているのに、あなたの弟子たちは食べたり飲んだりしています」。34 するとイエスは言われた、「あなたがたは、花婿が一緒にいるのに、婚礼の客に断食をさせることができるであろうか。35 しかし、花婿が奪い去られる日が来る。その日には断食をするであろう」。36 それからイエスはまた一つの譬を語られた、「だれも、新しい着物から布ぎれを切り取って、古い着物につぎを当てるものはない。もしそんなことをしたら、新しい着物を裂くことになるし、新しいのから取った布ぎれも古いのに合わないであろう。37 まただれも、新しいぶどう酒を古い皮袋に入れはしない。もしそんなことをしたら、新しいぶどう酒は皮袋をはり裂き、そしてぶどう酒は流れ出るし、皮袋もむだになるであろう。38 新しいぶどう酒は新しい皮袋に入れるべきである。39 まただれも、古い酒を飲んでから、新しいのをほしがりはしない。『古いのが良い』と考えているからである」。

[マルコによる福音書2章18-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_18-22.pdf)

### 問い

1.  マルコ、マタイ、ルカでは、それぞれ、どのようなときに、だれが、イエスに断食について質問していますか。

2.  イエスはどのように答えていますか。（マルコ2:19,20など）

3.  婚礼の客や、花婿とはだれのことだと思いますか。花婿が取り去られる時とはいつのことでしょうか。

4.  ヨハネの弟子たちやパリサイ人たちなどと、イエスでは、どのようなところが違っていたと思いますか。

5.  布きれと服、ぶどう酒と革袋のたとえはどのようなことを説明しているのでしょうか。

6.  イエスのこれらのことばは、現代においては、どのよなことを教えているでしょうか。

### 参照

-   断食について：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-断食)

-   聖書における断食の記述：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-断食に関する聖書箇所)

-   聖書における花婿の記述

    -   イザヤ61:10 わたしは主を大いに喜び、／わが魂はわが神を楽しむ。主がわたしに救の衣を着せ、／義の上衣をまとわせて、／**花婿**が冠をいただき、／花嫁が宝玉をもって飾るようにされたからである。 

    -   イザヤ62:5 若い者が処女をめとるように／あなたの子らはあなたをめとり、／**花婿**が花嫁を喜ぶように／あなたの神はあなたを喜ばれる。

    -   ホセア2:19,20 またわたしは永遠にあなたとちぎりを結ぶ。すなわち正義と、公平と、いつくしみと、あわれみとをもってちぎりを結ぶ。20 わたしは真実をもって、あなたとちぎりを結ぶ。そしてあなたは主を知るであろう。（聖書協会共同訳2:21,22）

    -   マタイ25:1-10 そこで天国は、十人のおとめがそれぞれあかりを手にして、**花婿**を迎えに出て行くのに似ている。 

    -   バプテスマのヨハネの証言：ヨハネ3:29,30 花嫁をもつ者は花婿である。花婿の友人は立って彼の声を聞き、その声を聞いて大いに喜ぶ。こうして、この喜びはわたしに満ち足りている。30 彼は必ず栄え、わたしは衰える。

> **18** Καὶ ἦσαν[^markdq-165] οἱ μαθηταὶ Ἰωάννου καὶ οἱ Φαρισαῖοι νηστεύοντες. καὶ ἔρχονται καὶ λέγουσιν αὐτῷ· διὰ τί οἱ μαθηταὶ Ἰωάννου καὶ οἱ μαθηταὶ τῶν Φαρισαίων νηστεύουσιν[^markdq-166], οἱ δὲ σοὶ μαθηταὶ οὐ νηστεύουσιν; **19** καὶ εἶπεν αὐτοῖς ὁ Ἰησοῦς· μὴ δύνανται οἱ υἱοὶ τοῦ νυμφῶνος[^markdq-167] ἐν ᾧ ὁ νυμφίος[^markdq-168] μετ' αὐτῶν ἐστιν νηστεύειν; ὅσον χρόνον ἔχουσιν τὸν νυμφίον μετ' αὐτῶν οὐ δύνανται νηστεύειν. **20** ἐλεύσονται[^markdq-169] δὲ ἡμέραι ὅταν ἀπαρθῇ[^markdq-170] ἀπ' αὐτῶν ὁ νυμφίος, καὶ τότε νηστεύσουσιν ἐν ἐκείνῃ τῇ ἡμέρᾳ. **21** Οὐδεὶς ἐπίβλημα ῥάκους ἀγνάφου ἐπιράπτει[^markdq-171] ἐπὶ ἱμάτιον παλαιόν· εἰ δὲ μή, αἴρει τὸ πλήρωμα ἀπ' αὐτοῦ τὸ καινὸν τοῦ παλαιοῦ καὶ χεῖρον σχίσμα γίνεται. **22** καὶ οὐδεὶς βάλλει οἶνον[^markdq-172] νέον εἰς ἀσκοὺς παλαιούς· εἰ δὲ μή, ῥήξει ὁ οἶνος τοὺς ἀσκοὺς καὶ ὁ οἶνος ἀπόλλυται καὶ οἱ ἀσκοί· ἀλλ' οἶνον νέον εἰς ἀσκοὺς καινούς.

[^markdq-165]: ἦν (IXI-3P): I was, etc.

[^markdq-166]: νηστεύω (PAP-NPM): to abstain as a religious exercise from food and drink: either entirely, if the fast lasted but a single day, or from customary and choice nourishment, if it continued several days

[^markdq-167]: νυμφών (GSM): the chamber containing the bridal bed, the bridal chamber

[^markdq-168]: νυμφίος: a bridegroom

[^markdq-169]: ἔρχομαι (FDI-3P): to come

[^markdq-170]: ἀπαίρω (APS-3S): i) to lift off, take or carry away, ii) to be taken away from anyone

[^markdq-171]: ἐπιράπτω (PAI-3S): to sew upon, sew to

[^markdq-172]: οἶνος: wine

### 記録

-   日時：2023年7月6日午後7時半〜9時半

-   出席（対面）7名、参加（遠隔）4名

### 問いについて

1.  どのようなときに、だれが質問しているか。

    -   レビの記事の直後。宴会をしているのを見て、「そのとき（中略）断食をしているのに」（マタイ）

    -   マルコ：人々、ルカ：彼ら（パリサイ人や律法学者？）、マタイ：ヨハネの弟子たち。（ヨハネ3:22-30）

    -   断食をする（と定められている）特別なときだったのかもしれない。

2.  イエスの答え。

    -   マルコ2:19 婚礼の客は、花婿が一緒にいるのに、断食ができるであろうか。花婿と一緒にいる間は、断食はできない。 20 しかし、花婿が奪い去られる日が来る。その日には断食をするであろう。

    -   マタイ：悲しんでおられようか。

3.  花婿、婚礼の客

    -   花婿はイエスだろうか。そう取るのがおそらく、一般的。花嫁は、婚礼の客は。ここには、花嫁は登場しない。

    -   レビの家での宴会の主賓は、誰だったのだろうか。何を喜んでいたのだろうか。神様のものとなったのは、レビや、イエスに従うようになった人たち。または、神様のもとに来た人たち。

    -   相互性があるかもしれない。共に喜ぶ場、それが祝宴の場。

    -   しかし、取り去られるのは、イエス自身のことを言っていることは確実だろう。すでに、この時点で、取り去られることについて語っている。

    -   ヨハネ16:20-22 よくよくあなたがたに言っておく。あなたがたは泣き悲しむが、この世は喜ぶであろう。あなたがたは憂えているが、その憂いは喜びに変るであろう。21 女が子を産む場合には、その時がきたというので、不安を感じる。しかし、子を産んでしまえば、もはやその苦しみをおぼえてはいない。ひとりの人がこの世に生れた、という喜びがあるためである。22 このように、あなたがたにも今は不安がある。しかし、わたしは再びあなたがたと会うであろう。そして、あなたがたの心は喜びに満たされるであろう。その喜びをあなたがたから取り去る者はいない。

    -   ヨハネ20:19-21 その日、すなわち、一週の初めの日の夕方、弟子たちはユダヤ人をおそれて、自分たちのおる所の戸をみなしめていると、イエスがはいってきて、彼らの中に立ち、「安かれ」と言われた。20 そう言って、手とわきとを、彼らにお見せになった。弟子たちは主を見て喜んだ。21 イエスはまた彼らに言われた、「安かれ。父がわたしをおつかわしになったように、わたしもまたあなたがたをつかわす」。 

4.  違い

    -   断食など、身を苦しめる、宗教儀式によって、神の国に近づくことができるのか。

    -   確認：イエスの断食、使徒たち初代教会の断食、旧約聖書における断食はどのようなものだったのだろうか。[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-断食に関する聖書箇所)

5.  布きれと服、ぶどう酒と革袋

    -   神様を讃えること、悔い改めること、喜ぶこと。

    -   ルカでは：36 だれも、新しい着物から布ぎれを切り取って、古い着物につぎを当てるものはない。もしそんなことをしたら、新しい着物を裂くことになるし、新しいのから取った布ぎれも古いのに合わないであろう。

    -   ヨブ32:19 見よ、わたしの心は口を開かないぶどう酒のように、／新しいぶどう酒の皮袋のように、／今にも張りさけようとしている。 

6.  イエスの教え

    -   神の国はすぐそこにある。レビの家にもすでに来ている。

### メモ

-   マルコも、マタイも、ルカも、レビの記事の直後にある。特に、マタイは、「そのとき」と始まっている。

-   断食は、旧約では、身を悩ますこと。

-   ヨハネ3章29,30節を加味すると、ヨハネの証言を知っているものが質問をし、それをうけて、イエスが、花婿のことを言ったと解釈するのが自然であり、マタイの証言のように、ここで、質問したのは、バプテスマのヨハネの弟子または、そのような情報を共有しているものととれる。また、アンデレやヨハネは、バプテスマのヨハネの弟子で、このようなバプテスマのヨハネの証言を知っていたと思われる。すると、花婿はイエス、介添人はバプテスマのヨハネ、婚礼の客は、花婿イエスの弟子である。花婿が取り去られることを伝えているのは、すでに、師が取り去られ、断食をしている、バプテスマのヨハネの弟子たちへの配慮もあるように思われる。

-   イザヤや、ホセア、さらに、マタイ25章1-12節の花嫁の譬えから、考えると、花嫁は、イエスと契りをむすぶ、イエスが迎える人たちである。

-   布も、皮袋も、古いもののほうに、重きがある。これも、バプテスマのヨハネの弟子たちのように、イエスに従ってはいないひとたちへのメッセージかもしれない。すなわち、断食をしないことだけを、受け入れると、すべてが壊れてしまう。断食のこともふくめた、イエスの新しい教えを受け入れるなら、そのなかに、入り込まないといけないということを言っているのかもしれない。

-   ただ、かなり、異なる記述もあるルカなども加味すると、ひとつの解釈にこだわってはいけないこともあるのかもしれない。実際、この場には、さまざまな人たちがいたのだから。

## 2:23-28 安息日に麦の穂を摘む

> 2:23 ある安息日に、イエスは麦畑の中をとおって行かれた。そのとき弟子たちが、歩きながら穂をつみはじめた。 24 すると、パリサイ人たちがイエスに言った、「いったい、彼らはなぜ、安息日にしてはならぬことをするのですか」。25 そこで彼らに言われた、「あなたがたは、ダビデとその供の者たちとが食物がなくて飢えたとき、ダビデが何をしたか、まだ読んだことがないのか。26 すなわち、大祭司アビアタルの時、神の家にはいって、祭司たちのほか食べてはならぬ供えのパンを、自分も食べ、また供の者たちにも与えたではないか」。27 また彼らに言われた、「安息日は人のためにあるもので、人が安息日のためにあるのではない。 28 それだから、人の子は、安息日にもまた主なのである」。

### マタイ 12:1-8

> 1 そのころ、ある安息日に、イエスは麦畑の中を通られた。すると弟子たちは、空腹であったので、穂を摘んで食べはじめた。2 パリサイ人たちがこれを見て、イエスに言った、「ごらんなさい、あなたの弟子たちが、安息日にしてはならないことをしています」。3 そこでイエスは彼らに言われた、「あなたがたは、ダビデとその供の者たちとが飢えたとき、ダビデが何をしたか読んだことがないのか。4 すなわち、神の家にはいって、祭司たちのほか、自分も供の者たちも食べてはならぬ供えのパンを食べたのである。5 また、安息日に宮仕えをしている祭司たちは安息日を破っても罪にはならないことを、律法で読んだことがないのか。6 あなたがたに言っておく。宮よりも大いなる者がここにいる。7 『わたしが好むのは、あわれみであって、いけにえではない』とはどういう意味か知っていたなら、あなたがたは罪のない者をとがめなかったであろう。8 人の子は安息日の主である」。 

### ルカ 6:1-5

> 1 ある安息日にイエスが麦畑の中をとおって行かれたとき、弟子たちが穂をつみ、手でもみながら食べていた。2 すると、あるパリサイ人たちが言った、「あなたがたはなぜ、安息日にしてはならぬことをするのか」。3 そこでイエスが答えて言われた、「あなたがたは、ダビデとその供の者たちとが飢えていたとき、ダビデのしたことについて、読んだことがないのか。4 すなわち、神の家にはいって、祭司たちのほかだれも食べてはならぬ供えのパンを取って食べ、また供の者たちにも与えたではないか」。5 また彼らに言われた、「人の子は安息日の主である」。

[マルコによる福音書2章23-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_23-28.pdf)

### 問い

1.  マルコを読み、ここで起こったことを確認し、気づいたこと、疑問点を挙げてみましょう。

2.  弟子たちは「いつ」「どこで」「なに」をしていますか。マタイやルカも合わせて状況を想像してみましょう。

3.  ファリサイ人たちは誰に何を訴えていますか。

4.  ダビデの例を通してイエスはどんなことを説明していますか。（サムエル記上21:1-7）

5.  イエスは安息日の目的をどのように説明していますか。

6.  「人の子は安息日にもまた主なのである。」は何を伝えているのでしょうか。

7.  安息日や主日（日曜日）は、わたしたちにとってどのようなものなのでしょうか。

### 参照

-   安息日について：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#安息日)

-   安息日に関する聖書箇所：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#安息日に関する聖書箇所)

-   申命記23:24,25 あなたが隣人のぶどう畑にはいる時、そのぶどうを心にまかせて飽きるほど食べてもよい。しかし、あなたの器の中に取り入れてはならない。25 あなたが隣人の麦畑にはいる時、手でその穂を摘んで食べてもよい。しかし、あなたの隣人の麦畑にかまを入れてはならない。

-   **供えのパン**

    -   レビ記24:5-9 あなたは麦粉を取り、それで十二個の菓子を焼かなければならない。菓子一個に麦粉十分の二エパ[^markdq-173]を用いなければならない。6 そしてそれを主の前の純金の机の上に、ひと重ね六個ずつ、ふた重ねにして置かなければならない。7 あなたはまた、おのおのの重ねの上に、純粋の乳香を置いて、そのパンの記念の分とし、主にささげて火祭としなければならない。8 **安息日**ごとに絶えず、これを主の前に整えなければならない。これはイスラエルの人々のささぐべきものであって、永遠の契約である。9 これはアロンとその子たちに帰する。彼らはこれを聖なる所で食べなければならない。これはいと聖なる物であって、主の火祭のうち彼に帰すべき永久の分である」。

    -   供えのパンを置く台：出エジプト25:23-30 あなたはまたアカシヤ材の机を造らなければならない。長さは二キュビト[^markdq-174]、幅は一キュビト、高さは一キュビト半。24 純金でこれをおおい、周囲に金の飾り縁を造り、25 またその周囲に手幅の棧を造り、その棧の周囲に金の飾り縁を造らなければならない。26 また、そのために金の環四つを造り、その四つの足のすみ四か所にその環を取り付けなければならない。27 環は棧のわきに付けて、机をかつぐさおを入れる所としなければならない。28 またアカシヤ材のさおを造り、金でこれをおおい、それをもって、机をかつがなければならない。また、その皿、乳香を盛る杯および灌祭を注ぐための瓶と鉢を造り、これらは純金で造らなければならない。30 そして机の上には**供えのパン**を置いて、常にわたしの前にあるようにしなければならない。

    -   補足1：民数記4:7,8 また供えのパンの机の上には、青色の布をうちかけ、その上に、さら、乳香を盛る杯、鉢、および灌祭の瓶を並べ、また絶やさず供えるパンを置き、8 緋色の布をその上にうちかけ、じゅごんの皮のおおいをもって、これをおおい、さおをさし入れる。

    -   補足2：列王記上7:48-50 またソロモンは主の宮にあるもろもろの器を造った。すなわち金の祭壇と、供えのパンを載せる金の机、49 および純金の燭台。この燭台は本殿の前に、五つは南に、五つは北にあった。また金の花と、ともしび皿と、心かきと、50 純金の皿と、心切りばさみと、鉢と、香の杯と、心取り皿と、至聖所である宮の奥のとびらのためおよび、宮の拝殿のとびらのために、金のひじつぼを造った。

    -   補足3: 歴代誌上9:31-32 コラびとシャルムの長子でレビびとのひとりであるマタテヤはせんべいを造る勤めをつかさどった。32 またコハテびとの子孫であるその兄弟たちのうちに供えのパンをつかさどって、安息日ごとにこれを整える者どもがあった。

-   サムエル記上21:1-7 ダビデはノブに行き、祭司アヒメレクのところへ行った。アヒメレクはおののきながらダビデを迎えて言った、「どうしてあなたはひとりですか。だれも供がいないのですか」。2 ダビデは祭司アヒメレクに言った、「王がわたしに一つの事を命じて、『わたしがおまえをつかわしてさせる事、またわたしが命じたことについては、何をも人に知らせてはならない』と言われました。そこでわたしは、ある場所に若者たちを待たせてあります。3 ところで今あなたの手もとにパン五個でもあれば、それをわたしにください。なければなんでも、あるものをください」。4 祭司はダビデに答えて言った、「常のパンはわたしの手もとにありません。ただその若者たちが女を慎んでさえいたのでしたら、聖別したパンがあります」。5 ダビデは祭司に答えた、「わたしが戦いに出るいつもの時のように、われわれはたしかに女たちを近づけていません。若者たちの器は、常の旅であったとしても、清いのです。まして、きょう、彼らの器は清くないでしょうか」。6 そこで祭司は彼に聖別したパンを与えた。その所に、供えのパンのほかにパンがなく、このパンは、これを取り下げる日に、あたたかいパンと置きかえるため、主の前から取り下げたものである。

-   サムエル記上22:20 しかしアヒトブの子アヒメレクの子たちのひとりで、名をアビヤタルという人は、のがれてダビデの所に走った。

[^markdq-173]: エパ 23リットル。十分の二エパは、4.6リットル。

[^markdq-174]: キュビト（アンマ）約45cm なので、机は、90cm x 45cm x 67cm

> **23** Καὶ ἐγένετο αὐτὸν ἐν τοῖς σάββασιν[^markdq-175] παραπορεύεσθαι[^markdq-176] διὰ τῶν σπορίμων[^markdq-177], καὶ οἱ μαθηταὶ αὐτοῦ ἤρξαντο ὁδὸν ποιεῖν τίλλοντες[^markdq-178] τοὺς στάχυας[^markdq-179]. **24** καὶ οἱ Φαρισαῖοι ἔλεγον αὐτῷ· ἴδε τί ποιοῦσιν τοῖς σάββασιν ὃ οὐκ ἔξεστιν[^markdq-180]; **25** καὶ λέγει αὐτοῖς· οὐδέποτε ἀνέγνωτε τί ἐποίησεν Δαυὶδ ὅτε χρείαν ἔσχεν καὶ ἐπείνασεν[^markdq-181] αὐτὸς καὶ οἱ μετ' αὐτοῦ, **26** πῶς εἰσῆλθεν εἰς τὸν οἶκον τοῦ θεοῦ ἐπὶ Ἀβιαθὰρ ἀρχιερέως καὶ τοὺς ἄρτους τῆς προθέσεως[^markdq-182] ἔφαγεν, οὓς οὐκ ἔξεστιν φαγεῖν εἰ μὴ τοὺς ἱερεῖς, καὶ ἔδωκεν καὶ τοῖς σὺν αὐτῷ οὖσιν; **27** Καὶ ἔλεγεν αὐτοῖς· τὸ σάββατον διὰ[^markdq-183] τὸν ἄνθρωπον ἐγένετο καὶ οὐχ ὁ ἄνθρωπος διὰ τὸ σάββατον· **28** ὥστε κύριός ἐστιν ὁ υἱὸς τοῦ ἀνθρώπου καὶ τοῦ σαββάτου.

[^markdq-175]: σάββατον: i) the seventh day of each week which was a sacred festival on which the Israelites were required to abstain from all work, ii) seven days, a week

[^markdq-176]: παραπορεύομαι (PNN): to proceed at the side, go past, pass by

[^markdq-177]: σπόριμος: i) fit for sowing, sown, ii) sown fields, growing crops

[^markdq-178]: τίλλω: to pluck, pluck off

[^markdq-179]: στάχυς: an ear of corn or of growing grain

[^markdq-180]: ἔξεστι: it is lawful

[^markdq-181]: πεινάω: i) to hunger, be hungry, ii) metaph. to crave ardently, to seek with eager desire

[^markdq-182]: πρόθεσις: i) a setting forth of a thing, placing of it in view, the shewbread: twelve loaves of wheaten bread, corresponding to the number of the tribes of Israel, which loaves were offered to God every Sabbath, and separated into two rows, lay for seven days upon a table placed in the sanctuary or front portion of the tabernacle, and afterwards of the temple, ii) a purpose

[^markdq-183]: διά: i) through of place, of time, of means, ii) through the ground or reason by which something is or is not done

### 記録

-   日時：2023年7月13日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）6名

### 問いについて

1.  概要

    -   当時「安息日にしてはならぬ」と考えられていたことを弟子たちはしていた。

    -   パリサイ人がイエスに問う。

    -   イエスは、ダビデの例と、安息日がだれのためかを語り、最後に安息日の主を示す。

2.  「いつ」「どこで」「なに」を

    -   安息日に麦畑の中で弟子たちが歩きながら穂を摘み始めた。

    -   マタイ：空腹だったので

    -   ルカ：穂を摘み手で揉みながら食べていた

    -   「こんな連中」品行方正とは言えない弟子たち。イエスはその面倒を引き受けておられる。

    -   安息日に、十分理解して、これらのことをしたわけではない。

3.  ファリサイ人たちの訴え

    -   いったい彼らはなぜ安息日にしてはならぬことをするのか。

        -   他人の畑のものを無断で食べたのが違法だと言ったわけではない。安息日にしてはならぬことをしたことに焦点がある。（申命記23:25）

    -   ルカ：あなたがたは。しかし、弟子たちが行為者であるとは書いている。

4.  ダビデの例

    -   サムエル記上21:1-7、サムエル記上22:20 にアビヤタルも登場

    -   供えのパン：レビ24:5-9

5.  安息日の目的

    -   安息日は人のためにあるもので、人が安息日のためにあるのではない。（マルコのみ）

    -   マタイ：5 また、安息日に宮仕えをしている祭司たちは安息日を破っても罪にはならないことを、律法で読んだことがないのか。6 あなたがたに言っておく。宮よりも大いなる者がここにいる。7 『わたしが好むのは、あわれみであって、いけにえではない』とはどういう意味か知っていたなら、あなたがたは罪のない者をとがめなかったであろう。

6.  人の子は安息日にもまた主なのである。

    -   マルコでは唐突

    -   マタイでは、4節と5節の関係が唐突

    -   ルカではまったく説明がない

7.  主日は何のため

    -   神の創造のわざ - 休息

    -   マナを通して安息日を定める

    -   礼拝 - 祭り、主を喜ぶ日

    -   バビロン捕囚における、分離

### メモ

-   注：サムエル記上21:1-7 祭司アヒメレクとあり、アビアタルではない。マタイ、ルカには、名前は省略されている。マタイ、ルカにも供の者とあるが、供の者たちもいたとは考えられない。また、大祭司アビアタルの時（26）とあるが、大祭司制度は、確立していないと思われる。引用句でも、祭司。大祭司については、レビ記21:10、民数記35:25, 28, 32 に記述があるが、歴史の記述で登場するのは、口語訳では、列王記下12:10（聖書教会共同訳では11節） 王の書記官と大祭司 が初出、名前が登場するのは、ヨシヤ王の時代の大祭司ヒルキヤから。列王記下 22:4, 8, 23:4, 歴代誌下34:9

-   イエスの弟子たちは、パリサイ人のように、厳格に律法を理解し守る訓練を受けた人たちではなかった。そのような人たちを周りに置いた、イエスは、批判にたいして、弁護している。まずは、お腹が減っているときの行為として、ダビデを例に上げている。名前の間違い（あとから書かれたマタイや、ルカでは省略されている、大祭司という言い方も定着していなかったかもしれない。）供の者がいたかどうかなど、不正確な引用であるようにも思われ、また、ダビデについて引用するときには、注意を払っているようにも思われる。

-   マルコでは、安息日は人のためという部分が強調されるが、安息日の主との繋がりは希薄である。マタイは、それを丁寧に説明もしている。ただ、その一つの正当な解釈に、収斂されてようかどうかは不明。

-   安息日は何のためかについて考えたい。多くの問題が背後に潜んでいるように見える。土曜日か、日曜日か、毎日が主の日か、特別な日とするべきかも含めて、考えるべき課題は多い。続けて考えていきたい。

## 3:1-6 手の萎えた人を癒やす

> 3:1 イエスがまた会堂にはいられると、そこに片手のなえた人がいた。 2 人々はイエスを訴えようと思って、安息日にその人をいやされるかどうかをうかがっていた。 3 すると、イエスは片手のなえたその人に、「立って、中へ出てきなさい」と言い、 4 人々にむかって、「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」と言われた。彼らは黙っていた。5 イエスは怒りを含んで彼らを見まわし、その心のかたくななのを嘆いて、その人に「手を伸ばしなさい」と言われた。そこで手を伸ばすと、その手は元どおりになった。 6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。

### マタイ 12:9-14

> 9 イエスはそこを去って、彼らの会堂にはいられた。10 すると、そのとき、片手のなえた人がいた。人々はイエスを訴えようと思って、「安息日に人をいやしても、さしつかえないか」と尋ねた。11 イエスは彼らに言われた、「あなたがたのうちに、一匹の羊を持っている人があるとして、もしそれが安息日に穴に落ちこんだなら、手をかけて引き上げてやらないだろうか。12 人は羊よりも、はるかにすぐれているではないか。だから、安息日に良いことをするのは、正しいことである」。13 そしてイエスはその人に、「手を伸ばしなさい」と言われた。そこで手を伸ばすと、ほかの手のように良くなった。14 パリサイ人たちは出て行って、なんとかしてイエスを殺そうと相談した。

### ルカ 6:6-11

> 6 また、ほかの安息日に会堂にはいって教えておられたところ、そこに右手のなえた人がいた。7 律法学者やパリサイ人たちは、イエスを訴える口実を見付けようと思って、安息日にいやされるかどうかをうかがっていた。8 イエスは彼らの思っていることを知って、その手のなえた人に、「起きて、まん中に立ちなさい」と言われると、起き上がって立った。9 そこでイエスは彼らにむかって言われた、「あなたがたに聞くが、安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」。10 そして彼ら一同を見まわして、その人に「手を伸ばしなさい」と言われた。そのとおりにすると、その手は元どおりになった。11 そこで彼らは激しく怒って、イエスをどうかしてやろうと、互に話合いをはじめた。 

[マルコによる福音書3章1-6節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_1-6.pdf)

### 問い

1.  このできごとはいつ、どこで、どのような状況のもとでおきますか。

2.  イエスは片手の萎（な）えた人を、なぜ、真ん中に立たせたのでしょうか。

3.  イエスは、人々に、どのように問うていますか。

4.  なぜイエスは怒り嘆くのでしょうか。そしてどうしますか。

5.  パリサイ人たちは、どうしますか。

6.  あなたは、一日をどのように生きようとしていますか。

### 参照

-   ヘロデ党について：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-ヘロデ党)

-   ヘロデ党に関する聖書箇所：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-ヘロデ党に関する聖書箇所)

-   マタイ12:15-21 も繋がっている

    -   イエスはこれを知って、そこを去って行かれた。ところが多くの人々がついてきたので、彼らを皆いやし、 16 そして自分のことを人々にあらわさないようにと、彼らを戒められた。17 これは預言者イザヤの言った言葉が、成就するためである、18 「見よ、わたしが選んだ僕、／わたしの心にかなう、愛する者。わたしは彼にわたしの霊を授け、／そして彼は正義を異邦人に宣べ伝えるであろう。19 彼は争わず、叫ばず、／またその声を大路で聞く者はない。20 彼が正義に勝ちを得させる時まで、／いためられた葦を折ることがなく、／煙っている燈心を消すこともない。

        -   引用：イザヤ42:1-3 わたしの支持するわがしもべ、／わたしの喜ぶわが選び人を見よ。わたしはわが霊を彼に与えた。彼はもろもろの国びとに道をしめす。2 彼は叫ぶことなく、声をあげることなく、／その声をちまたに聞えさせず、3 また傷ついた葦を折ることなく、／ほのぐらい灯心を消すことなく、／真実をもって道をしめす。

-   「わたしはレンガ職人で、わたしの手で自分のパンを稼いでいました。イエスよ。お願いです。恥さらしにもこじきをすることができないために、わたしの健康を取り戻してください。」（4C ヒエロニムス：ナザレ派・エピオン派が用いていたヘブル語のマタイの福音書からの引用）

> **1** Καὶ εἰσῆλθεν πάλιν εἰς τὴν συναγωγήν. καὶ ἦν ἐκεῖ ἄνθρωπος ἐξηραμμένην[^markdq-184] ἔχων τὴν χεῖρα. **2** καὶ παρετήρουν[^markdq-185] αὐτὸν εἰ τοῖς σάββασιν θεραπεύσει αὐτόν, ἵνα κατηγορήσωσιν αὐτοῦ. **3** καὶ λέγει τῷ ἀνθρώπῳ τῷ τὴν ξηρὰν χεῖρα ἔχοντι· ἔγειρε[^markdq-186] εἰς τὸ μέσον. **4** καὶ λέγει αὐτοῖς· ἔξεστιν[^markdq-187] τοῖς σάββασιν ἀγαθὸν[^markdq-188] ποιῆσαι ἢ κακοποιῆσαι[^markdq-189], ψυχὴν σῶσαι ἢ ἀποκτεῖναι; οἱ δὲ ἐσιώπων[^markdq-190]. **5** καὶ περιβλεψάμενος[^markdq-191] αὐτοὺς μετ' ὀργῆς[^markdq-192], συλλυπούμενος[^markdq-193] ἐπὶ τῇ πωρώσει[^markdq-194] τῆς καρδίας αὐτῶν λέγει τῷ ἀνθρώπῳ· ἔκτεινον τὴν χεῖρα. καὶ ἐξέτεινεν καὶ ἀπεκατεστάθη[^markdq-195] ἡ χεὶρ αὐτοῦ. **6** Καὶ ἐξελθόντες οἱ Φαρισαῖοι εὐθὺς μετὰ τῶν Ἡρῳδιανῶν συμβούλιον[^markdq-196] ἐδίδουν κατ' αὐτοῦ ὅπως αὐτὸν ἀπολέσωσιν[^markdq-197].

[^markdq-184]: ξηραίνω (RPP-ASF): i) to make dry, dry up, wither, ii) to become dry, to be dry, be withered, iii) to waste away, pine away, i.e. a withered hand

[^markdq-185]: παρατηρέω (IAI-3P): to stand beside and watch, to watch assiduously, observe carefully

[^markdq-186]: ἐγείρω (AMM-2S): to arouse, cause to rise

[^markdq-187]: ἔξεστι (PQI-3S): it is lawful

[^markdq-188]: ἀγαθοποιέω: i) to do good, do something which profits others, ii) to do well, do right

[^markdq-189]: κακοποιέω (AAN): i) to do harm, ii) to do evil, do wrong

[^markdq-190]: σιωπάω (IAI-3P): i) to be silent, hold one's peace, ii) metaph. of a calm, quiet sea

[^markdq-191]: περιβλέπω (AMP-NSM): i) to look around, ii) to look around about one's self, iii) to look round on one (i.e. to look for one's self at one near by)

[^markdq-192]: ὀργή: i) anger, the natural disposition, temper, character, ii) movement or agitation of the soul, impulse, desire, any violent emotion, but esp. anger, iii) anger, wrath, indignation, iii) anger exhibited in punishment, hence used for punishment itself

[^markdq-193]: συλλυπέω (PNP-NSM): i) to affect with grief together, ii) give with one's self

[^markdq-194]: πώρωσις (DSF): i) the covering with a callus, ii) obtrusiveness of mental discernment, dulled perception, iii) the mind of one has been blunted

[^markdq-195]: ἀποκαθίστημι (API-3S): i) to restore to its former state, ii) to be in its former state

[^markdq-196]: συμβούλιον (ASN): i) counsel, which is given, taken, entered upon, ii) a council

[^markdq-197]: ἀπόλλυμι (AAS-3P): to destroy

### 記録

-   日時：2023年7月20日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）4名

### 問いについて

1.  いつ、どこで、どのような状況

    -   マルコ、マタイ、ルカとも、安息日に起きた、麦畑の記事に続いている。ルカによると「他の安息日」。

    -   会堂でのできごと：マタイには「彼らの会堂」とある。人々の只中にいる。そして、ラビとして教えていると思われる。ルカによると、教えてもいる。

    -   片手の萎えたひとがいた。

    -   イエスを訴えようとしている（ルカによると）律法学者やパリサイ人が、安息日に癒すかどうかをうかがっている。マタイによると、人々が「安息日に人をいやしても、さしつかえないか」と尋ねている。

2.  なぜ、真ん中に立たせたか

    -   「立って、中へ出てきなさい」（マルコ）「起きて、まん中に立ちなさい」（ルカ）

    -   人々に、考えること、教えることを目的としたのではないか。

3.  人々への問い

    -   マルコとルカはほぼ同じ。マタイは異なる。問いは人々に向けられている。

    -   マルコ：「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」ルカ：「あなたがたに聞くが、安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」

    -   マタイ：「あなたがたのうちに、一匹の羊を持っている人があるとして、もしそれが安息日に穴に落ちこんだなら、手をかけて引き上げてやらないだろうか。人は羊よりも、はるかにすぐれているではないか。だから、安息日に良いことをするのは、正しいことである」。

        -   マタイは、「命を救うのと殺すのと、どちらがよいか」に重点をおき、当時も認められていることを例として上げているように見える。

        -   マルコ、ルカの方が一般性が高い。

4.  イエスの怒り嘆き、そして行動

    -   マルコ：彼らは黙っていた。イエスは怒りを含んで彼らを見まわし、その心のかたくななのを嘆いて、その人に「手を伸ばしなさい」と言われた。そこで手を伸ばすと、その手は元どおりになった。

        -   怒りと嘆きは、マルコのみ。黙っていたことへの応答と思われる。

    -   ルカ：そして彼ら一同を見まわして、その人に「手を伸ばしなさい」と言われた。そのとおりにすると、その手は元どおりになった。

    -   マタイ：そしてイエスはその人に、「手を伸ばしなさい」と言われた。そこで手を伸ばすと、ほかの手のように良くなった。

5.  パリサイ人たちの行動

    -   マルコ：パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。

    -   マタイ：パリサイ人たちは出て行って、なんとかしてイエスを殺そうと相談した。

    -   ルカ：そこで彼らは激しく怒って、イエスをどうかしてやろうと、互に話合いをはじめた。

        -   主体が、マルコは明確だが、マタイ、ルカと、不明確になっていく。律法学者や、パリサイ人がいたことは、ルカにあるので、パリサイ人はよいとして、ヘロデ党の者たちとの共謀は、確証が取れなかったのかもしれない。

6.  一日をどう生きるか

    -   善を行い、命を救うことだろうか。しかし、それは、日常的にはどのようなことだろうか。

### メモ

-   マタイは、少し違う内容を伝えようとしているように思われる。イザヤの引用句は、次の箇所で学んでも良いかもしれない。

-   安息日にしてもよいこと、悪いことに重点をおくのは、主要なことではないように思われる。

-   頑なな心を、まずは顧みること。単純な質問に答えられない。答えることを拒否するのは、なぜなのだろう。「単純な問いを難しくしているからか。」イエスが、神の子かどうか、安息日の主かどうか、罪を赦す権威があるか、そちらが解決しなければ、簡単な問いにも答えない。そのような論理に陥ってしまっていることが、頑なさなのだろうか。むろん、生理的に受け入れられない。嫌い。ということもあるかもしれない。しかし、イエスの単純な問いかけに、答えることは、最初の一歩なのかもしれない。拒否が、分断を起こし、抹殺へと発展する。それを、どうすれば、断ち切ることができるのだろうか。

-   善いこととは？　命を救うこととは？　神様が何を望んでおられるか、互いに愛し合うために、何を為すべきかを考えたい。

## 3:7-12 湖の岸辺の群衆

> 3:7 それから、イエスは弟子たちと共に海べに退かれたが、ガリラヤからきたおびただしい群衆がついて行った。またユダヤから、8 エルサレムから、イドマヤから、更にヨルダンの向こうから、ツロ、シドンのあたりからも、おびただしい群衆が、そのなさっていることを聞いて、みもとにきた。9 イエスは群衆が自分に押し迫るのを避けるために、小舟を用意しておけと、弟子たちに命じられた。 10 それは、多くの人をいやされたので、病苦に悩む者は皆イエスにさわろうとして、押し寄せてきたからである。 11 また、けがれた霊どもはイエスを見るごとに、みまえにひれ伏し、叫んで、「あなたこそ神の子です」と言った。 12 イエスは御自身のことを人にあらわさないようにと、彼らをきびしく戒められた。

### （参考1）マタイ4:23-25

> 23 イエスはガリラヤの全地を巡り歩いて、諸会堂で教え、御国の福音を宣べ伝え、民の中のあらゆる病気、あらゆるわずらいをおいやしになった。24 そこで、その評判はシリヤ全地にひろまり、人々があらゆる病にかかっている者、すなわち、いろいろの病気と苦しみとに悩んでいる者、悪霊につかれている者、てんかん、中風の者などをイエスのところに連れてきたので、これらの人々をおいやしになった。25 こうして、ガリラヤ、デカポリス、エルサレム、ユダヤ及びヨルダンの向こうから、おびただしい群衆がきてイエスに従った。

### （参考2）ルカ6:17-19

> 17 そして、イエスは彼らと一緒に山を下って平地に立たれたが、大ぜいの弟子たちや、ユダヤ全土、エルサレム、ツロとシドンの海岸地方などからの大群衆が、18 教を聞こうとし、また病気をなおしてもらおうとして、そこにきていた。そして汚れた霊に悩まされている者たちも、いやされた。19 また群衆はイエスにさわろうと努めた。それは力がイエスの内から出て、みんなの者を次々にいやしたからである。

### （参考3）マタイ12:15-21

> 15 イエスはこれを知って、そこを去って行かれた。ところが多くの人々がついてきたので、彼らを皆いやし、 16 そして自分のことを人々にあらわさないようにと、彼らを戒められた。17 これは預言者イザヤの言った言葉が、成就するためである、18 「見よ、わたしが選んだ僕、／わたしの心にかなう、愛する者。わたしは彼にわたしの霊を授け、／そして彼は正義を異邦人に宣べ伝えるであろう。19 彼は争わず、叫ばず、／またその声を大路で聞く者はない。20 彼が正義に勝ちを得させる時まで、／いためられた葦を折ることがなく、／煙っている燈心を消すこともない。

[マルコによる福音書3章7-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_7-12.pdf)

### 問い

1.  地図で、参考箇所も合わせて、地名を確認しましょう。

2.  「おびただしい群衆」とありますが、人々は何を求めて、イエスのもとにるのでしょうか。

3.  イエスは、どのように、弟子たちに命じますか。

4.  汚れた霊は、イエスを見るとどうしますか。

5.  なぜイエスは、汚れた霊にご自身のことをあらわさないように戒めるのでしょうか。

6.  イエスが宣教を始めてから、どのようなことがあったか、まとめてみましょう。どのようなことがわかりますか。

7.  マタイ12:15-21 のイザヤ書からの引用は、なにを伝えていますか。（イザヤ42:1-3）

### 参照

-   地図：[キリスト時代のパレスチナ](https://upload.wikimedia.org/wikipedia/commons/1/1f/JBS1956-B_map11.png)、[Palestine in the time of Jesus (1)](https://www.seektheoldpaths.com/Maps/103.jpg)

-   引用：イザヤ42:1-3 わたしの支持するわがしもべ、／わたしの喜ぶわが選び人を見よ。わたしはわが霊を彼に与えた。彼はもろもろの国びとに道をしめす。2 彼は叫ぶことなく、声をあげることなく、／その声をちまたに聞えさせず、3 また傷ついた葦を折ることなく、／ほのぐらい灯心を消すことなく、／真実をもって道をしめす。

> **7** Καὶ ὁ Ἰησοῦς μετὰ τῶν μαθητῶν αὐτοῦ ἀνεχώρησεν[^markdq-198] πρὸς τὴν θάλασσαν, καὶ πολὺ πλῆθος ἀπὸ τῆς Γαλιλαίας \[ἠκολούθησεν[^markdq-199]\], καὶ ἀπὸ τῆς Ἰουδαίας **8** καὶ ἀπὸ Ἱεροσολύμων καὶ ἀπὸ τῆς Ἰδουμαίας καὶ πέραν τοῦ Ἰορδάνου καὶ περὶ Τύρον καὶ Σιδῶνα πλῆθος πολὺ ἀκούοντες ὅσα ἐποίει ἦλθον πρὸς αὐτόν. **9** Καὶ εἶπεν τοῖς μαθηταῖς αὐτοῦ ἵνα πλοιάριον[^markdq-200] προσκαρτερῇ[^markdq-201] αὐτῷ διὰ τὸν ὄχλον ἵνα μὴ θλίβωσιν[^markdq-202] αὐτόν· **10** πολλοὺς γὰρ ἐθεράπευσεν[^markdq-203], ὥστε ἐπιπίπτειν[^markdq-204] αὐτῷ ἵνα αὐτοῦ ἅψωνται[^markdq-205] ὅσοι εἶχον μάστιγας[^markdq-206]. **11** καὶ τὰ πνεύματα τὰ ἀκάθαρτα[^markdq-207], ὅταν αὐτὸν ἐθεώρουν, προσέπιπτον αὐτῷ καὶ ἔκραζον λέγοντες ὅτι σὺ εἶ ὁ υἱὸς τοῦ θεοῦ. **12** καὶ πολλὰ ἐπετίμα αὐτοῖς ἵνα μὴ αὐτὸν φανερὸν ποιήσωσιν.

[^markdq-198]: ἀναχωρέω (AAI-3S): i) to go back, return, ii) to withdraw

[^markdq-199]: ἀκολουθέω (AAI-3P): i) to follow one who precedes, join him as his attendant, accompany him, ii) to join one as a disciple, become or be his disciple

[^markdq-200]: πλοιάριον (NSN): a small vessel, a boat

[^markdq-201]: προσκαρτερέω (PAS-3S): i) to adhere to one, be his adherent, to be devoted or constant to one, ii) to be steadfastly attentive unto, to give unremitting care to a thing, iii) to continue all the time in a place, iv) to persevere and not to faint, v) to show one's self courageous for, vi) to be in constant readiness for one, wait on constantly

[^markdq-202]: θλίβω (PAS-3P): i) to press (as grapes), press hard upon, ii) a compressed way, iii) metaph. to trouble, afflict, distress

[^markdq-203]: θεραπεύω (AAI-3S): i) to serve, do service, ii) to heal, cure, restore to health

[^markdq-204]: ἐπιπίπτω (PAN): i) to fall upon, to rush or press upon, ii) to fall upon one i.e. to seize, take possession of him

[^markdq-205]: ἅπτομαι (AMS-3P): to fasten one's self to, adhere to, cling to

[^markdq-206]: μάστιξ (APF): i) a whip, scourge, ii) metaph. a scourge, plague

[^markdq-207]: ἀκάθαρτος (NPN): not cleansed, unclean a) in a ceremonial sense: that which must be abstained from according to the levitical law, b) in a moral sense: unclean in thought and life

### 問いについて

1.  地名

    -   ガリラヤ、ユダヤ、エルサレム、イドマヤ、ヨルダンの向こう、ツロ、シドン（ユダヤ、ガリラヤだけでなく、異邦人の町も含む）

        -   1:28 では、ガリラヤ。「こうしてイエスのうわさは、たちまちガリラヤの全地方、いたる所にひろまった。」（このときは、ガリラヤ）

2.  群衆の要求

    -   なさっていることを聞いて

    -   病苦に悩む者がイエスに触ろうとして（押し寄せた）

        -   パリサイ人や、律法学者は、イエスに敵対しているが、群衆は、必ずしも、そのようには行動していない。

3.  イエスの弟子たちへの依頼

    -   9 イエスは群衆が自分に押し迫るのを避けるために、小舟を用意しておけと、弟子たちに命じられた。

        -   物理的接触以外のことをも求める。

4.  汚れた霊

    -   11 また、けがれた霊どもはイエスを見るごとに、みまえにひれ伏し、叫んで、「あなたこそ神の子です」と言った。

        -   1:24 「ナザレのイエスよ、あなたはわたしたちとなんの係わりがあるのです。わたしたちを滅ぼしにこられたのですか。あなたがどなたであるか、わかっています。神の聖者です」。 

        -   1:34 イエスは、さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出された。また、悪霊どもに、物言うことをお許しにならなかった。彼らがイエスを知っていたからである。 

5.  イエスの汚れた霊への対応

    -   12 イエスは御自身のことを人にあらわさないようにと、彼らをきびしく戒められた。

6.  復習

    -   バプテスマのヨハネの宣教：わたしよりも力のあるかたが、あとからおいでになる。わたしはかがんで、そのくつのひもを解く値うちもない。わたしは水でバプテスマを授けたが、このかたは、聖霊によってバプテスマをお授けになるであろう」。（1:7,8）

        -   力を示した。聖霊によってバプテスマをお授けになったのだろうか。

    -   洗礼を受ける：そして、水の中から上がられるとすぐ、天が裂けて、聖霊がはとのように自分に下って来るのを、ごらんになった。すると天から声があった、「あなたはわたしの愛する子、わたしの心にかなう者である」。（1:10,11）

    -   試みを受ける

    -   ガリラヤでの宣教開始：「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」。（1:15）

    -   弟子を招く：「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」。（1:17）

    -   権威のある教え：汚れた霊に取り憑かれた者を癒す（1:21-28）

    -   ペトロのしゅうとめ、いろいろな病気の人をいやし、悪霊を追い出す。（1:29-34）

    -   祈り、宣教し、悪霊をおいだす（1:35-39）

    -   規定の病を患っている人をいやす。（1:40-45）

    -   中風の人を癒す。罪を赦す権威（2:1-12）

    -   レビを弟子にし、収税人や罪人と宴会（2:13-17）：「丈夫な人には医者はいらない。いるのは病人である。わたしがきたのは、義人を招くためではなく、罪人を招くためである」。 （2:17）

    -   断食について（2:18-22）：だれも、真新しい布ぎれを、古い着物に縫いつけはしない。もしそうすれば、新しいつぎは古い着物を引き破り、そして、破れがもっとひどくなる。まただれも、新しいぶどう酒を古い皮袋に入れはしない。もしそうすれば、ぶどう酒は皮袋をはり裂き、そして、ぶどう酒も皮袋もむだになってしまう。

    -   安息日に麦の穂を摘む（2:23-28）：それだから、人の子は、安息日にもまた主なのである

    -   手の萎えた人を癒す（3:1-6）：「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」

7.  イザヤ書の引用

    -   17 これは預言者イザヤの言った言葉が、成就するためである、18 「見よ、わたしが選んだ僕、／わたしの心にかなう、愛する者。わたしは彼にわたしの霊を授け、／そして彼は正義を異邦人に宣べ伝えるであろう。19 彼は争わず、叫ばず、／またその声を大路で聞く者はない。20 彼が正義に勝ちを得させる時まで、／いためられた葦を折ることがなく、／煙っている燈心を消すこともない。（イザヤ42:1-3）NIV A bruised reed he will not break, and a smoldering wick he will not snuff out, till he has brought justice through to victory.

### 記録

-   日時：2023年7月27日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）3名

### メモ

-   この後に、会堂で教えるのは、マルコでは１箇所のみ。

    -   マルコ6:2 そして、安息日になったので、**会堂**で教えはじめられた。それを聞いた多くの人々は、驚いて言った、「この人は、これらのことをどこで習ってきたのか。また、この人の授かった知恵はどうだろう。このような力あるわざがその手で行われているのは、どうしてか。

-   パリサイ人たちは、反発し、イエスを殺そうとすらする。しかし、群衆は、さまざまな場所から集まってきている。イエスが伝えたかったことを受け取っていたのだろうか。悪霊に語らせなかったのだろうか。イエスが伝えたかったこととは、異なる、そして、悪霊は、追い出すべき存在だったのだろう。イエスは、神の国が近づいたと語っても、それが伝わってはいなかったのかもしれない。

-   マタイがイザヤ書を引用して伝えたかったすがたが、神の僕イエスの姿だったのではないだろうか。大路で語ることなく、傷ついた葦を折ることなく、消えかかった灯心を消すことなく。

-   このあとで、弟子を選ぶが、その弟子を通して、イエスが伝えたことを、少しずつ学んでいきたい。

## 3:13-19 十二人を選ぶ

> 3:13 さてイエスは山に登り、みこころにかなった者たちを呼び寄せられたので、彼らはみもとにきた。14 そこで十二人をお立てになった。彼らを自分のそばに置くためであり、さらに宣教につかわし、15 また悪霊を追い出す権威を持たせるためであった。 16 こうして、この十二人をお立てになった。そしてシモンにペテロという名をつけ、 17 またゼベダイの子ヤコブと、ヤコブの兄弟ヨハネ、彼らにはボアネルゲ、すなわち、雷の子という名をつけられた。18 つぎにアンデレ、ピリポ、バルトロマイ、マタイ、トマス、アルパヨの子ヤコブ、タダイ、熱心党のシモン、19 それからイスカリオテのユダ。このユダがイエスを裏切ったのである。イエスが家にはいられると、

### マタイ 10:1-4

> 1 そこで、イエスは十二弟子を呼び寄せて、汚れた霊を追い出し、あらゆる病気、あらゆるわずらいをいやす権威をお授けになった。2 十二使徒の名は、次のとおりである。まずペテロと呼ばれたシモンとその兄弟アンデレ、それからゼベダイの子ヤコブとその兄弟ヨハネ、3 ピリポとバルトロマイ、トマスと取税人マタイ、アルパヨの子ヤコブとタダイ、4 熱心党のシモンとイスカリオテのユダ。このユダはイエスを裏切った者である。

### ルカ 6:12-16

> 12 このころ、イエスは祈るために山へ行き、夜を徹して神に祈られた。13 夜が明けると、弟子たちを呼び寄せ、その中から十二人を選び出し、これに使徒という名をお与えになった。14 すなわち、ペテロとも呼ばれたシモンとその兄弟アンデレ、ヤコブとヨハネ、ピリポとバルトロマイ、15 マタイとトマス、アルパヨの子ヤコブと、熱心党と呼ばれたシモン、16 ヤコブの子ユダ、それからイスカリオテのユダ。このユダが裏切者となったのである。

[マルコによる福音書3章13-19節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_13-19.pdf)

### 問い

1.  イエスは、どこで、どのようにして十二人を選びましたか。

2.  マルコには、十二人を立てた理由が書かれていますが、それはどのようなものですか。マタイ、ルカではどのように書かれていますか。

3.  マルコ、マタイ、ルカの弟子たちのリストについて気付いたことをあげてましょう。

4.  イスカリオテのユダが含まれていることはなにを意味しているのでしょうか。

5.  これまでのことなども復習して、なぜ、この時点で、十二人を選んだのか考えてみましょう。（マタイ9:35-38）

### 参照

-   **十二弟子を選ぶ直前：**マタイ9:35-38 イエスは、すべての町々村々を巡り歩いて、諸会堂で教え、御国の福音を宣べ伝え、あらゆる病気、あらゆるわずらいをおいやしになった。36 また群衆が飼う者のない羊のように弱り果てて、倒れているのをごらんになって、彼らを深くあわれまれた。37 そして弟子たちに言われた、「収穫は多いが、働き人が少ない。38 だから、収穫の主に願って、その収穫のために働き人を送り出すようにしてもらいなさい」。

-   **十二弟子を選ぶ直後：**ルカ6:17-19 そして、イエスは彼らと一緒に山を下って平地に立たれたが、大ぜいの弟子たちや、ユダヤ全土、エルサレム、ツロとシドンの海岸地方などからの大群衆が、18 教を聞こうとし、また病気をなおしてもらおうとして、そこにきていた。そして汚れた霊に悩まされている者たちも、いやされた。19 また群衆はイエスにさわろうと努めた。それは力がイエスの内から出て、みんなの者を次々にいやしたからである。

-   熱心党：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-熱心党)（聖書に登場するのは十二弟子の箇所のみ）

-   12弟子について：[参照](https://icu-hsuzuki.github.io/science/bible/docs/12disciples.pdf)

-   使徒1:13：彼らは、市内に行って、その泊まっていた屋上の間にあがった。その人たちは、ペテロ、ヨハネ、ヤコブ、アンデレ、ピリポとトマス、バルトロマイとマタイ、アルパヨの子ヤコブと熱心党のシモンとヤコブの子ユダとであった。 

> **13** Καὶ ἀναβαίνει[^markdq-208] εἰς τὸ ὄρος καὶ προσκαλεῖται[^markdq-209] οὓς ἤθελεν αὐτός, καὶ ἀπῆλθον[^markdq-210] πρὸς αὐτόν. **14** Καὶ ἐποίησεν[^markdq-211] δώδεκα \[οὓς καὶ ἀποστόλους ὠνόμασεν\] ἵνα ὦσιν μετ' αὐτοῦ καὶ ἵνα ἀποστέλλῃ[^markdq-212] αὐτοὺς κηρύσσειν[^markdq-213] **15** καὶ ἔχειν ἐξουσίαν[^markdq-214] ἐκβάλλειν τὰ δαιμόνια·**16** \[Καὶ ἐποίησεν τοὺς δώδεκα,\] καὶ ἐπέθηκεν ὄνομα τῷ Σίμωνι Πέτρον, **17** καὶ Ἰάκωβον τὸν τοῦ Ζεβεδαίου καὶ Ἰωάννην τὸν ἀδελφὸν τοῦ Ἰακώβου καὶ ἐπέθηκεν αὐτοῖς ὀνόμα \[τα\] Βοανηργές, ὅ ἐστιν υἱοὶ βροντῆς· **18** καὶ Ἀνδρέαν καὶ Φίλιππον καὶ Βαρθολομαῖον καὶ Μαθθαῖον καὶ Θωμᾶν καὶ Ἰάκωβον τὸν τοῦ Ἁλφαίου καὶ Θαδδαῖον καὶ Σίμωνα τὸν Καναναῖον **19** καὶ Ἰούδαν Ἰσκαριώθ, ὃς καὶ παρέδωκεν αὐτόν.

[^markdq-208]: ἀναβαίνω (PAI-3S): ascend, go up

[^markdq-209]: προσκαλέω (PNI-3S): i) to call to, ii) to call to one's self, iii) to bid to come to one's self, iv) metaph. a) God is said to call to himself the Gentiles, aliens as they are from him, by inviting them, through the preaching of the gospel unto fellowship with himself in the Messiah's kingdom, b) Christ and the Holy Sprit are said to call to themselves those preachers of the gospel to whom they have decided to intrust a service having reference to the extension of the gospel

[^markdq-210]: ἀπέρχομαι (2AAi-3P): i) to go away, depart, ii) to go away

[^markdq-211]: ποιέω (AAI-3S): i) to make, ii) to do

[^markdq-212]: ἀποστέλλω (PAS-3S): i) to order (one) to go to a place appointed, ii) to send away, dismiss

[^markdq-213]: κηρύσσω (PAN): i) to be a herald, to officiate as a herald, ii) to publish, proclaim openly: something which has been done, iii) used of the public proclamation of the gospel and matters pertaining to it, made by John the Baptist, by Jesus, by the apostles and other Christian teachers

[^markdq-214]: ἐξουσία: i) power of choice, liberty of doing as one pleases, ii) physical and mental power, iii) the power of authority (influence) and of right (privilege), iv) the power of rule or government (the power of him whose will and commands must be submitted to by others and obeyed)

### 記録

-   日時：2023年8月3日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）6名

### 問いについて

1.  どこでどのようにして十二人を立てたか

    -   マルコ：山に登り、みこころにかなった者たち（ここにイスカリオテのユダも含まれている）を呼び寄せられた

    -   マタイ：イエスは十二弟子を呼び寄せ

    -   ルカ：このころ、イエスは祈るために山へ行き、**夜を徹して**神に祈られた。夜が明けると、弟子たちを呼び寄せ、その中から十二人を選び出し、これに使徒という名をお与えになった。

    -   いずれもイエスが呼び寄せておられる。

    -   ルカの記述からは、選別があった印象を受ける。

2.  十二人を立てた理由

    -   マルコ：自分のそばに置く、宣教につかわす、悪霊を追い出す権威を持たせるため

    -   マタイ：汚れた霊を追い出し、あらゆる病気、あらゆるわずらいをいやす権威をお授けになった。

    -   ルカ：目的は書かれていない。9章1-6節に、十二人の派遣の記事がある。それ以外に、七十二人の任命と派遣についても記事がある。10章1-12節。派遣は、マルコ 6:7-13、マタイ 10:1,5-15（直後）

    -   使徒（マタイ・ルカ）ἀπόστολος (ap-os'-tol-os): a delegate, messenger, one sent forth with orders a) specifically applied to the twelve apostles of Christ, b) in a broader sense applied to other eminent Christian teachers i) of Barnabas, ii) of Timothy and Silvanus

3.  弟子のリスト

    -   何人かに、名前以外の情報が含まれている。

        -   ペテロ、ボアネルゲ（雷の子）、アルパヨの子、熱心党、イスカリオテ

    -   マタイでは、二組の兄弟、収税人マタイ

    -   バルトロマイ（ピリポとくみになって登場するので、ヨハネ1:45 のナタナエルか）

    -   タダイ（リストを比較すると、ヤコブの子ユダか ヨハネ 14:22）

    -   アルパヨの子ヤコブ、熱心党（熱烈な民族主義者）のシモンについては、他の箇所に、記述なし。

4.  イスカリオテのユダが含まれている理由

    -   マルコでは、みこころにかなった者としている。

    -   マタイ、ルカでも、イエスが呼び寄せた者たちの中にいる。

5.  背景と目的

    -   マルコにおけるこれまでの経緯

    -   直前：マタイ9:35-38

        -   36 群衆が飼う者のない羊のように弱り果てて、倒れているのをごらんになって、彼らを深くあわれまれた。

        -   37 そして弟子たちに言われた、「収穫は多いが、働き人が少ない。38 だから、収穫の主に願って、その収穫のために働き人を送り出すようにしてもらいなさい」。

    -   直後：ルカ6:17-19

    -   次の世代へのバトンタッチを考えていたのか？ マルコ2:19 するとイエスは言われた、「婚礼の客は、花婿が一緒にいるのに、断食ができるであろうか。花婿と一緒にいる間は、断食はできない。

### メモ

-   仲間との交わり

    -   パリサイ Φαρισαῖος：分離されたもの Hebrew origin（פָּרַשׁ：paw-rash' to make distinct, declare, distinguish, separate）a separatist, i.e. exclusively religious; a Pharisean, i.e. Jewish sectary:---Pharisee.

    -   最初から、こんな人たち（2:15 収税人、罪人）との、相互の交わりを大切にしていたと思われる。

-   普通の人

    -   使徒4:13,14 人々はペテロとヨハネとの大胆な話しぶりを見、また同時に、ふたりが無学な、ただの人たちであることを知って、不思議に思った。そして彼らがイエスと共にいた者であることを認め、14 かつ、彼らにいやされた者がそのそばに立っているのを見ては、まったく返す言葉がなかった。 

-   イエスに従っていく人

    -   すでに、ユダヤ教の権威、律法学者などには、危険視されていた。

    -   ヨハネ6:66-71 それ以来、多くの弟子たちは去っていって、もはやイエスと行動を共にしなかった。67 そこでイエスは十二弟子に言われた、「あなたがたも去ろうとするのか」。68 シモン・ペテロが答えた、「主よ、わたしたちは、だれのところに行きましょう。永遠の命の言をもっているのはあなたです。69 わたしたちは、あなたが神の聖者であることを信じ、また知っています」。70 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である」。71 これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。

-   権威を授けられた

    -   権威：ἐξουσία: i) power of choice, liberty of doing as one pleases, ii) physical and mental power, iii) the power of authority (influence) and of right (privilege), iv) the power of rule or government (the power of him whose will and commands must be submitted to by others and obeyed)

    -   実際の活動は、派遣によって：マルコ 6:7-13、マタイ 10:1,5-15、ルカ9章1-6節、ルカには、72人の派遣も書いてある。10章1-12節

    -   マルコ9:17,18 群衆のひとりが答えた、「先生、口をきけなくする霊につかれているわたしのむすこを、こちらに連れて参りました。18 霊がこのむすこにとりつきますと、どこででも彼を引き倒し、それから彼はあわを吹き、歯をくいしばり、からだをこわばらせてしまいます。それでお弟子たちに、この霊を追い出してくださるように願いましたが、できませんでした」。

    -   いやし：θεραπεύω i) to serve, do service, ii) to heal, cure, restore to health. to wait upon menially, i.e. (figuratively) to adore (God), or (specially) to relieve (of disease):---cure, heal, worship.

-   直接的動機

    -   マタイ9:36 群衆が飼う者のない羊のように弱り果てて（ἐκλύω: i) to loose, unloose, to set free, ii) to dissolve, metaph., to weaken, relax, exhaust, a) to have one's strength relaxed, to be enfeebled through exhaustion, to grow weak, grow weary, be tired out, b) to despond, become faint hearted）、倒れているのをごらんになって、彼らを深くあわれまれた。

    -   神に願う、そこから始まる。マタイ9:37b「収穫は多いが、働き人が少ない。38 だから、収穫の主に願って、その収穫のために働き人を送り出すようにしてもらいなさい」

-   選択について

    -   具体的には、この箇所を読んでも、どのように選んだのかよくわからないが、神様が定められたようになったのだろう。それを表現しているのが、ヨハネ6:66-71

## 3:20-30 ベルゼブル論争

> 3:20 群衆がまた集まってきたので、一同は食事をする暇もないほどであった。21 身内の者たちはこの事を聞いて、イエスを取押えに出てきた。気が狂ったと思ったからである。 22 また、エルサレムから下ってきた律法学者たちも、「彼はベルゼブルにとりつかれている」と言い、「悪霊どものかしらによって、悪霊どもを追い出しているのだ」とも言った。 23 そこでイエスは彼らを呼び寄せ、譬をもって言われた、「どうして、サタンがサタンを追い出すことができようか。 24 もし国が内部で分れ争うなら、その国は立ち行かない。 25 また、もし家が内わで分れ争うなら、その家は立ち行かないであろう。 26 もしサタンが内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。 27 だれでも、まず強い人を縛りあげなければ、その人の家に押し入って家財を奪い取ることはできない。縛ってからはじめて、その家を略奪することができる。28 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。 29 しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。 30 そう言われたのは、彼らが「イエスはけがれた霊につかれている」と言っていたからである。

### マタイ 12:22-32

> 22 そのとき、人々が悪霊につかれた盲人で口のきけない人を連れてきたので、イエスは彼をいやして、物を言い、また目が見えるようにされた。23 すると群衆はみな驚いて言った、「この人が、あるいはダビデの子ではあるまいか」。24 しかし、パリサイ人たちは、これを聞いて言った、「この人が悪霊を追い出しているのは、まったく悪霊のかしらベルゼブルによるのだ」。25 イエスは彼らの思いを見抜いて言われた、「おおよそ、内部で分れ争う国は自滅し、内わで分れ争う町や家は立ち行かない。26 もしサタンがサタンを追い出すならば、それは内わで分れ争うことになる。それでは、その国はどうして立ち行けよう。27 もしわたしがベルゼブルによって悪霊を追い出すとすれば、あなたがたの仲間はだれによって追い出すのであろうか。だから、彼らがあなたがたをさばく者となるであろう。 28 しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。29 まただれでも、まず強い人を縛りあげなければ、どうして、その人の家に押し入って家財を奪い取ることができようか。縛ってから、はじめてその家を掠奪することができる。30 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。31 だから、あなたがたに言っておく。人には、その犯すすべての罪も神を汚す言葉も、ゆるされる。しかし、聖霊を汚す言葉は、ゆるされることはない。32 また人の子に対して言い逆らう者は、ゆるされるであろう。しかし、聖霊に対して言い逆らう者は、この世でも、きたるべき世でも、ゆるされることはない。

### ルカ 11:14-23; 12:10

> 11:14 さて、イエスが悪霊を追い出しておられた。それは、物を言えなくする霊であった。悪霊が出て行くと、口のきけない人が物を言うようになったので、群衆は不思議に思った。15 その中のある人々が、「彼は悪霊のかしらベルゼブルによって、悪霊どもを追い出しているのだ」と言い、16 またほかの人々は、イエスを試みようとして、天からのしるしを求めた。17 しかしイエスは、彼らの思いを見抜いて言われた、「おおよそ国が内部で分裂すれば自滅してしまい、また家が分れ争えば倒れてしまう。18 そこでサタンも内部で分裂すれば、その国はどうして立ち行けよう。あなたがたはわたしがベルゼブルによって悪霊を追い出していると言うが、19 もしわたしがベルゼブルによって悪霊を追い出すとすれば、あなたがたの仲間はだれによって追い出すのであろうか。だから、彼らがあなたがたをさばく者となるであろう。20 しかし、わたしが神の指によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。21 強い人が十分に武装して自分の邸宅を守っている限り、その持ち物は安全である。22 しかし、もっと強い者が襲ってきて彼に打ち勝てば、その頼みにしていた武具を奪って、その分捕品を分けるのである。23 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。12:10 また、人の子に言い逆らう者はゆるされるであろうが、聖霊をけがす者は、ゆるされることはない。 

[マルコによる福音書3章20-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_20-30.pdf)

### 問い

1.  イエスの身内のひとたちは、なぜ、取り押さえにきたのでしょうか。

2.  どのような背景で、悪霊を追い出す権威についての論争が起きますか。マタイ、ルカも参考にしましょう。

3.  エルサレムから下ってきた律法学者たちはどのようにイエスを批判していますか。

4.  イエスは、律法学者のことばに、どのように反論していますか。

5.  なぜ、イエスは、聖霊を汚す罪について、語っているのでしょうか。

6.  マルコだけでなく、マタイや、ルカも参照すると、イエスについていろいろな受け止め方があったことがわかりますが、それぞれの人に、イエスは、どのように語りかけているのでしょうか。あなたは、どのように、受け取りますか。（マタイ12:33-37 も参照）

### 参照

-   ベルゼブル（Beelzebub）
    -   **Q. 新約聖書に出てくる、ベルゼブル（Beelzebub）は、どのようなものと考えられていたのでしょうか。聖書以外にも、記録はありますか。**

    -   **ChatGPT.** 『新約聖書』において、ベルゼブル（Beelzebub）は悪魔や悪霊の一つとして言及されています。名前はヘブライ語で「バアル・ゼブブ（Ba'al Zebub）」と書かれ、直訳すると「蠅の君主」という意味です。

        ベルゼブルは主にマタイによる福音書（マタイ12:24-27）やルカによる福音書（ルカ11:15-19）で言及されており、イエス・キリストが悪霊を追い出す力を持っていることを示すために登場します。ユダヤ教の伝統においては、ベルゼブルは悪魔の首領であり、悪霊の王とされています。

        また、聖書以外にもベルゼブルに関する記録はあります。例えば、中世のキリスト教の文献や伝説、悪魔学においてベルゼブルについての言及が見られます。これらの文献では、ベルゼブルは堕天使の一人であり、人々を誘惑し、悪霊を使役する存在として描かれます。

        ただし、ベルゼブルに関する情報は聖書や後の宗教的文献以外では限られており、一般的な知識として広く認知されている内容は限定的です。
-   マタイでは、このときいより以前にも、以下の記述がある。
    -   マタイ9:32-34 彼らが出て行くと、人々は**悪霊につかれて口のきけない人**をイエスのところに連れてきた。33 すると、悪霊は追い出されて、口のきけない人が物を言うようになった。群衆は驚いて、「このようなことがイスラエルの中で見られたことは、これまで一度もなかった」と言った。34 しかし、パリサイ人たちは言った、「彼は、**悪霊どものかしら**によって悪霊どもを追い出しているのだ」。
    -   ベルゼプル議論（マタイ12:22-32）では、悪霊にとりつかれ、目もみえず、口も聞けない人が登場する。9章では、口が聞けない人、悪霊に取りつかれ、口が聞けない人のことが、ルカでは、ベルゼブル議論（ルカ11:14-23）に書かれている。マタイが正しいのかもしれない。そして、ここで、悪霊の頭が登場し、ベルゼブル議論の、予兆を感じさせるようになっている。
-   ユダヤ教における聖霊の理解：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-聖霊)
-   マタイ12:33-37 木が良ければ、その実も良いとし、木が悪ければ、その実も悪いとせよ。木はその実でわかるからである。34 まむしの子らよ。あなたがたは悪い者であるのに、どうして良いことを語ることができようか。おおよそ、心からあふれることを、口が語るものである。35 善人はよい倉から良い物を取り出し、悪人は悪い倉から悪い物を取り出す。36 あなたがたに言うが、審判の日には、人はその語る無益な言葉に対して、言い開きをしなければならないであろう。37 あなたは、自分の言葉によって正しいとされ、また自分の言葉によって罪ありとされるからである」。

> **20** Καὶ ἔρχεται εἰς οἶκον· καὶ συνέρχεται πάλιν \[ὁ\] ὄχλος, ὥστε μὴ δύνασθαι αὐτοὺς μηδὲ ἄρτον φαγεῖν. **21** καὶ ἀκούσαντες οἱ παρ' αὐτοῦ ἐξῆλθον κρατῆσαι[^markdq-215] αὐτόν· ἔλεγον γὰρ ὅτι ἐξέστη[^markdq-216]. **22** Καὶ οἱ γραμματεῖς οἱ ἀπὸ Ἱεροσολύμων καταβάντες[^markdq-217] ἔλεγον ὅτι Βεελζεβοὺλ[^markdq-218] ἔχει καὶ ὅτι ἐν τῷ ἄρχοντι τῶν δαιμονίων[^markdq-219] ἐκβάλλει τὰ δαιμόνια. **23** Καὶ προσκαλεσάμενος[^markdq-220] αὐτοὺς ἐν παραβολαῖς[^markdq-221] ἔλεγεν αὐτοῖς· πῶς δύναται σατανᾶς σατανᾶν ἐκβάλλειν; **24** καὶ ἐὰν βασιλεία ἐφ' ἑαυτὴν μερισθῇ[^markdq-222], οὐ δύναται σταθῆναι ἡ βασιλεία ἐκείνη· **25** καὶ ἐὰν οἰκία ἐφ' ἑαυτὴν μερισθῇ, οὐ δυνήσεται ἡ οἰκία ἐκείνη σταθῆναι. **26** καὶ εἰ ὁ σατανᾶς ἀνέστη ἐφ' ἑαυτὸν καὶ ἐμερίσθη, οὐ δύναται στῆναι ἀλλὰ τέλος ἔχει. **27** ἀλλ' οὐ δύναται οὐδεὶς εἰς τὴν οἰκίαν τοῦ ἰσχυροῦ εἰσελθὼν τὰ σκεύη αὐτοῦ διαρπάσαι, ἐὰν μὴ πρῶτον τὸν ἰσχυρὸν δήσῃ, καὶ τότε τὴν οἰκίαν αὐτοῦ διαρπάσει. **28** Ἀμὴν λέγω ὑμῖν ὅτι πάντα ἀφεθήσεται τοῖς υἱοῖς τῶν ἀνθρώπων τὰ ἁμαρτήματα καὶ αἱ βλασφημίαι[^markdq-223] ὅσα ἐὰν βλασφημήσωσιν· **29** ὃς δ' ἂν βλασφημήσῃ εἰς τὸ πνεῦμα τὸ ἅγιον, οὐκ ἔχει ἄφεσιν εἰς τὸν αἰῶνα, ἀλλ' ἔνοχός ἐστιν αἰωνίου ἁμαρτήματος. **30** ὅτι ἔλεγον· πνεῦμα ἀκάθαρτον ἔχει.

[^markdq-215]: κρατέω (AAN): i) to have power, be powerful, ii) to get possession of, iii) to hold

[^markdq-216]: ἐξίστημι (2AAI3S): to throw out of position, displace

[^markdq-217]: καταβαίνω (2AAP-NPM): to go down, come down, descend

[^markdq-218]: Βεελζεβούλ: Beelzebub = "lord of the house" (a name of Satan, the prince of evil spirits)

[^markdq-219]: δαιμόνιον: i) the divine power, deity, divinity, ii) a spirit, a being inferior to God, superior to men, iii) evil spirits or the messengers and ministers of the devil

[^markdq-220]: προσκαλέω (ADP-NSM): to call to

[^markdq-221]: παραβολή: i) a placing of one thing by the side of another, juxtaposition, as of ships in battle, ii) metaph., iii) a pithy and instructive saying, involving some likeness or comparison and having preceptive or admonitory force, iv) a proverb, v) an act by which one exposes himself or his possessions to danger, a venture, a risk

[^markdq-222]: μερίζω (APS-3S): to divide

[^markdq-223]: βλασφημία: i) slander, detraction, speech injurious, to another's good name, ii) impious and reproachful speech injurious to divine majesty

### 記録

-   日時：2023年8月10日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）5名

### 問いについて

1.  身内の人たちが取り押さえにきた理由

    -   マルコ3:20 群衆がまた集まってきたので、一同は食事をする暇もないほどであった。21 身内の者たちはこの事を聞いて、イエスを取押えに出てきた。気が狂ったと思ったからである。

    -   群衆が押し寄せ、宗教指導者からは、拒否される。少しの弟子は、ついていっていたが、異常だと感じていたのだろう。

    -   マルコではこのあと「イエスの母、きょうだい」の記事が、「3:31 さて、イエスの母と兄弟たちとがきて、外に立ち、人をやってイエスを呼ばせた。」と続く。

    -   マルコ6:3 この人は大工ではないか。マリヤのむすこで、ヤコブ、ヨセ、ユダ、シモンの兄弟ではないか。またその姉妹たちも、ここにわたしたちと一緒にいるではないか」。こうして彼らはイエスにつまずいた。

2.  背景

    -   マタイ12:22 そのとき、人々が悪霊につかれた盲人で口のきけない人を連れてきたので、イエスは彼をいやして、物を言い、また目が見えるようにされた。23 すると群衆はみな驚いて言った、「この人が、あるいはダビデの子ではあるまいか」。

    -   ルカ11:14 さて、イエスが悪霊を追い出しておられた。それは、物を言えなくする霊であった。悪霊が出て行くと、口のきけない人が物を言うようになったので、群衆は不思議に思った。

    -   悪霊を追い出された人の記述がマタイとルカで異なる。また、反応も異なる。

    -   ルカ11:16 またほかの人々は、イエスを試みようとして、天からのしるしを求めた。

3.  エルサレムから下ってきた律法学者の批判

    -   マルコ3:22 また、エルサレムから下ってきた律法学者たちも、「彼はベルゼブルにとりつかれている」と言い、「悪霊どものかしらによって、悪霊どもを追い出しているのだ」とも言った。（マタイ、ルカもほぼ同じ）

4.  イエスの反論

    -   内部分裂は滅びに：もしサタンが内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。

        -   マタイ12:28 しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。（ルカ11:20）

        -   ルカ11:19 もしわたしがベルゼブルによって悪霊を追い出すとすれば、あなたがたの仲間はだれによって追い出すのであろうか。だから、彼らがあなたがたをさばく者となるであろう。（マタイ12:27）

    -   まず強い人を縛りあげなければ、その人の家に押し入って家財を奪い取ることはできない。

        -   マタイ12:30 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。

        -   イエスは何を強い人だと考えていたのか。

            -   困難な状況、真意が伝わらない、頑なな心をみて、イエスは独白をしているのか。

5.  聖霊をけがす罪

    -   28 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。29 しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。

        -   マタイ12:32聖霊に対して言い逆らう者は、この世でも、きたるべき世でも、ゆるされることはない。

6.  それぞれの人へのメッセージ

    -   それぞれの人に対する、聖霊のはたらきについて、考えたい。

        -   木のたとえをみると、救いがない。悔い改め（方向転換）か。

    -   マタイ、ルカは、このあと、さまざまな記事が続き、この箇所と関係しているように見える。

        -   マタイ：12:33-37 実によって木を知る、38-42 しるしを求める、43-45 汚れた霊が戻ってくる、46-50 イエスの母、きょうだい

        -   ルカ：24-26 汚れた霊が戻ってくる、27-28 真の幸い、29-32 人々はしるしを欲しがる、33-36 目は体の灯

### メモ

-   家族：マタイ10:32-39 だから人の前でわたしを受けいれる者を、わたしもまた、天にいますわたしの父の前で受けいれるであろう。33 しかし、人の前でわたしを拒む者を、わたしも天にいますわたしの父の前で拒むであろう。34 地上に平和をもたらすために、わたしがきたと思うな。平和ではなく、つるぎを投げ込むためにきたのである。35 わたしがきたのは、人をその父と、娘をその母と、嫁をそのしゅうとめと仲たがいさせるためである。36 そして家の者が、その人の敵となるであろう。37 わたしよりも父または母を愛する者は、わたしにふさわしくない。わたしよりもむすこや娘を愛する者は、わたしにふさわしくない。38 また自分の十字架をとってわたしに従ってこない者はわたしにふさわしくない。39 自分の命を得ている者はそれを失い、わたしのために自分の命を失っている者は、それを得るであろう。
-   悪霊：使徒10:38 神はナザレのイエスに聖霊と力とを注がれました。このイエスは、神が共におられるので、よい働きをしながら、また**悪魔に押えつけられている**[^markdq-224]**人々をことごとくいやしながら**、巡回されました。
-   共観福音書を読んでいると「悪霊どものかしらによって、悪霊どもを追い出しているのだ」との批判に対して、イエスは、さまざまな方法で、反論しているように見える。神の国は近い、神の国はすでにきている（マタイ・ルカ）ということの、証・しるしとして悪霊が追い出されているのに、それがまったく違ったものに理解されることを警戒したものだろう。マタイの実についての言及も、実を見るべきこととしてこのことに言及しているのかもしれない。しかし、本質は、このことを通して、イエス様と父なる神様の関係のような、神様との交わりを持つ、永遠の命に生きる生活に導かれることだとすると、鍵は、神様の働き、神様が聖霊を通して与えてくださる理解を受け入れることなのだろう。それを阻害するもの、それが何かは明確にはわからないし、さまざまにあるのかもしれないが、それこそが、「強い人」なのかもしれない。

[^markdq-224]: καταδυναστεύω (PPP-APM): i) to exercise harsh control over one, to use one's power against one, ii) to oppress one

## 3:31-35 イエスの母、きょうだい

> 3:31 さて、イエスの母と兄弟たちとがきて、外に立ち、人をやってイエスを呼ばせた。 32 ときに、群衆はイエスを囲んですわっていたが、「ごらんなさい。あなたの母上と兄弟、姉妹たちが、外であなたを尋ねておられます」と言った。 33 すると、イエスは彼らに答えて言われた、「わたしの母、わたしの兄弟とは、だれのことか」。 34 そして、自分をとりかこんで、すわっている人々を見まわして、言われた、「ごらんなさい、ここにわたしの母、わたしの兄弟がいる。35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。

### マタイ 12:46-50

> 46 イエスがまだ群衆に話しておられるとき、その母と兄弟たちとが、イエスに話そうと思って外に立っていた。47 それで、ある人がイエスに言った、「ごらんなさい。あなたの母上と兄弟がたが、あなたに話そうと思って、外に立っておられます」。48 イエスは知らせてくれた者に答えて言われた、「わたしの母とは、だれのことか。わたしの兄弟とは、だれのことか」。49 そして、弟子たちの方に手をさし伸べて言われた、「ごらんなさい。ここにわたしの母、わたしの兄弟がいる。50 天にいますわたしの父のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。 

### ルカ 8:19-21

> 19 さて、イエスの母と兄弟たちとがイエスのところにきたが、群衆のためそば近くに行くことができなかった。20 それで、だれかが「あなたの母上と兄弟がたが、お目にかかろうと思って、外に立っておられます」と取次いだ。21 するとイエスは人々にむかって言われた、「神の御言を聞いて行う者こそ、わたしの母、わたしの兄弟なのである」。

[マルコによる福音書3章31-35節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_31-35.pdf)

### 問い

1.  20節、21節を復習しましょう。イエスの（肉親である）母と兄弟たちは何のためにイエスのもとに来ていますか。

2.  イエスの（肉親である）母や兄弟たちはイエスのことをどう思っていたのでしょうか。

3.  イエスはイエスの（ほんとうの）母や兄弟はどのような人たちだと言っていますか。

4.  「わたしの母、わたしの兄弟」と呼んだ、イエスと共にいる人たちはどのような人たちでしょうか。

5.  イエスはイエスの（肉親である）母や兄弟たちに何を伝えていますか。

### 参照

-   マリアについて：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-マリアについて)

-   **母マリアに関する聖書箇所抜粋**

    -   ルカ1:38 そこでマリヤが言った、「わたしは主のはしためです。お言葉どおりこの身に成りますように」。そして御使は彼女から離れて行った。

    -   ルカ1:45 （エリザベツ）主のお語りになったことが必ず成就すると信じた女は、なんとさいわいなことでしょう」。

    -   ルカ11:27,28 イエスがこう話しておられるとき、群衆の中からひとりの女が声を張りあげて言った、「あなたを宿した胎、あなたが吸われた乳房は、なんとめぐまれていることでしょう」。28 しかしイエスは言われた、「いや、めぐまれているのは、むしろ、神の言を聞いてそれを守る人たちである」。

    -   ヨハネ2:1-5 三日目にガリラヤのカナに婚礼があって、イエスの母がそこにいた。2 イエスも弟子たちも、その婚礼に招かれた。3 ぶどう酒がなくなったので、母はイエスに言った、「ぶどう酒がなくなってしまいました」。4 イエスは母に言われた、「婦人よ、あなたは、わたしと、なんの係わりがありますか。わたしの時は、まだきていません」。5 母は僕たちに言った、「このかたが、あなたがたに言いつけることは、なんでもして下さい」。

-   **イエスの兄弟たち姉妹たち**（郷里のひとたちについても参照）

    -   マルコ6:1-6 ナザレで受け入れられない、マタイ13:53-58、ルカ4:16-30

    -   マルコ6:3 この人は大工ではないか。マリヤのむすこで、ヤコブ、ヨセ、ユダ、シモンの兄弟ではないか。またその姉妹たちも、ここにわたしたちと一緒にいるではないか」。こうして彼らはイエスにつまずいた。

    -   マタイ13:55,56 この人は大工の子ではないか。母はマリヤといい、兄弟たちは、ヤコブ、ヨセフ、シモン、ユダではないか。56 またその姉妹たちもみな、わたしたちと一緒にいるではないか。こんな数々のことを、いったい、どこで習ってきたのか」。

    -   ヨハネ7:1-8 そののち、イエスはガリラヤを巡回しておられた。ユダヤ人たちが自分を殺そうとしていたので、ユダヤを巡回しようとはされなかった。2 時に、ユダヤ人の仮庵の祭が近づいていた。3 そこで、イエスの兄弟たちがイエスに言った、「あなたがしておられるわざを弟子たちにも見せるために、ここを去りユダヤに行ってはいかがです。4 自分を公けにあらわそうと思っている人で、隠れて仕事をするものはありません。あなたがこれらのことをするからには、自分をはっきりと世にあらわしなさい」。5 **こう言ったのは、兄弟たちもイエスを信じていなかったからである。**6 そこでイエスは彼らに言われた、「わたしの時はまだきていない。しかし、あなたがたの時はいつも備わっている。7 世はあなたがたを憎み得ないが、わたしを憎んでいる。わたしが世のおこないの悪いことを、あかししているからである。8 あなたがたこそ祭に行きなさい。わたしはこの祭には行かない。わたしの時はまだ満ちていないから」。9 彼らにこう言って、イエスはガリラヤにとどまっておられた。 

    -   コリント前9:5 わたしたちには、ほかの使徒たちや**主の兄弟**たちやケパのように、信者である妻を連れて歩く権利がないのか。

    -   ガラテヤ1:19 しかし、**主の兄弟**ヤコブ以外には、ほかのどの使徒にも会わなかった。 

-   マタイ10:36 そして家の者が、その人の敵となるであろう。

-   **父の御心を行う**

    -   ヨハネ6:38-40 わたしが天から下ってきたのは、自分のこころのままを行うためではなく、わたしをつかわされたかたのみこころを行うためである。39 わたしをつかわされたかたのみこころは、わたしに与えて下さった者を、わたしがひとりも失わずに、終りの日によみがえらせることである。40 わたしの父のみこころは、子を見て信じる者が、ことごとく永遠の命を得ることなのである。そして、わたしはその人々を終りの日によみがえらせるであろう」。

> **31** Καὶ ἔρχεται ἡ μήτηρ αὐτοῦ καὶ οἱ ἀδελφοὶ αὐτοῦ καὶ ἔξω στήκοντες ἀπέστειλαν[^markdq-225] πρὸς αὐτὸν καλοῦντες αὐτόν. **32** καὶ ἐκάθητο[^markdq-226] περὶ αὐτὸν ὄχλος, καὶ λέγουσιν αὐτῷ· ἰδοὺ ἡ μήτηρ σου καὶ οἱ ἀδελφοί σου \[καὶ αἱ ἀδελφαί σου\] ἔξω ζητοῦσίν[^markdq-227] σε. **33** καὶ ἀποκριθεὶς αὐτοῖς λέγει· τίς ἐστιν ἡ μήτηρ μου καὶ οἱ ἀδελφοί \[μου\]; **34** καὶ περιβλεψάμενος[^markdq-228] τοὺς περὶ αὐτὸν κύκλῳ[^markdq-229] καθημένους λέγει· ἴδε ἡ μήτηρ μου καὶ οἱ ἀδελφοί μου. **35** ὃς \[γὰρ\] ἂν ποιήσῃ τὸ θέλημα[^markdq-230] τοῦ θεοῦ, οὗτος ἀδελφός μου καὶ ἀδελφὴ καὶ μήτηρ ἐστίν.

[^markdq-225]: ἀποστέλλω (AAI-3P): i) to order (one) to go to a place appointed, ii) to send away, dismiss

[^markdq-226]: κάθημαι (INI-3S): i) to sit down, seat one's self, ii) to sit, be seated, of a place occupied

[^markdq-227]: ζητέω (PAI-3P): i) to seek in order to find, ii) to seek i.e. require, demand

[^markdq-228]: περιβλέπω (AMP-NSM): i) to look around, ii) to look around about one's self, iii) to look round on one (i.e. to look for one's self at one near by)

[^markdq-229]: κύκλῳ (DSM): in a circle, around, round about, on all sides

[^markdq-230]: θέλημα (ASN): i) what one wishes or has determined shall be done, ii) will, choice, inclination, desire, pleasure

### 記録

-   日時：2023年8月17日午後7時半〜9時半

-   出席（対面）7名、参加（遠隔）3名

### 問いについて

1.  20,21 の復習
    -   20 群衆がまた集まってきたので、一同は食事をする暇もないほどであった。21 身内の者たちはこの事を聞いて、イエスを取押えに出てきた。気が狂ったと思ったからである。
    -   **「取押えに出てきた」身内の者**であることを確認
    -   マタイ、ルカでは、この表現はなく、柔らかくなっている。マリアや、主の兄弟への配慮か。
2.  肉親はどう思っていたか
    -   マタイ12:46 イエスがまだ群衆に話しておられるとき、その母と兄弟たちとが、イエスに話そうと思って外に立っていた。47 それで、ある人がイエスに言った、「ごらんなさい。あなたの母上と兄弟がたが、あなたに話そうと思って、外に立っておられます」。
    -   群衆が押し寄せ、宗教指導者からは、拒否される。少しの弟子は、ついていっていたが、異常だと感じていたのだろう。
    -   33節は、かなり厳しく響く。33 すると、イエスは彼らに答えて言われた、「わたしの母、わたしの兄弟とは、だれのことか」。「取押さえに」出てくるような人ではないよ。と言っている。
    -   参照のヨハネ7:1-8は、一つの背景を明らかにしている。
    -   参照のルカ11:27,28も、イエスと母マリアの関係を明らかにしている。
3.  本当の母、兄弟とは
    -   34 そして、自分をとりかこんで、すわっている人々を見まわして、言われた、「ごらんなさい、ここにわたしの母、わたしの兄弟がいる。35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。
    -   マタイ：49 そして、弟子たちの方に手をさし伸べて言われた、「ごらんなさい。ここにわたしの母、わたしの兄弟がいる。50 天にいますわたしの父のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。
    -   ルカ：21 するとイエスは人々にむかって言われた、「神の御言を聞いて行う者こそ、わたしの母、わたしの兄弟なのである」。
4.  イエスの周りにいる人：母、兄弟と呼ばれている
    -   父は含まれていない。母と呼ばれるような人だけではなく、姉妹は、おそらく含まれていただろう。
    -   35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。
    -   神のみこころを行っているものたちなのだろうか。
    -   父なる神の子となることが鍵
    -   マルコでは、20：食事を一緒にしようとしていたひと。群衆。前段の続きとすると、22 エルサレムから下ってきた律法学者たち。マタイでは、パリサイ人。まだいただろうか。
5.  肉親へのメッセージ
    -   一般論ではなく「取り押さえに来た」家族に対して語っている。33「わたしの母、わたしの兄弟とは、だれのことか」。
    -   イエスは、バプテスマの時に、神の声を聞き、聖霊が下ったイエスとし、父なる神の子として「神のみこころを行う者」として、生きようとし、そのような者と共に、生きようとしている。
    -   聖霊の働きを見、聖霊の声に聞き従うように。
    -   肉の目ではなく、霊の目で

### メモ

-   「神のみこころを行う者」、マタイ「天にいますわたしの父のみこころを行うもの」、ルカ「神の御言を聞いて行う者」

-   共通の経験：ともに神のみこころに従おうとしたものたち、ともに喜び、ともに悲しみ、泣く人、それが、それぞれの尊厳を形作る。何でも良いわけではないが。

-   共通の興味、同じ方向を向いている。共通の方に従っている。

-   これらが、互いに愛し合うように招かれる。

    -   ヨハネ13:34,35 わたしは、新しいいましめをあなたがたに与える、互に愛し合いなさい。わたしがあなたがたを愛したように、あなたがたも互に愛し合いなさい。35 互に愛し合うならば、それによって、あなたがたがわたしの弟子であることを、すべての者が認めるであろう」。

-   イエスの言葉：34 そして、自分をとりかこんで、すわっている人々を見まわして、言われた、「ごらんなさい、ここにわたしの母、わたしの兄弟がいる。35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。

    -   これをみても、全員が、「わたしの兄弟、また姉妹、また母」だとは言っていないように、見える。「いる」と言っているのだから。

    -   父については、語らないことで（マタイは明確に、「12:50 天にいますわたしの父のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」と言っている。）自分は、神の子として生きていること。そして「神のみこころを行う者はだれでも」イエスの家族、すなわち、神の子だよと言っている。（母も、父の責任下にあると考えられていたのだろう、その意味では、兄弟も姉妹も、母も同じである。）

    -   このことばを聞いた人たちは、おそらく、聖霊の促しを聞いただろう。「神のみこころをおこなう」ここにかかっていることを。エルサレムから下ってきた律法学者たちも、これを聞いたとすると、考える糸口はあったかもしれない。悔い改められるかどうかは、不明だが。

## 4:1-9 「種を蒔く人」のたとえ

> 4:1 イエスはまたも、海べで教えはじめられた。おびただしい群衆がみもとに集まったので、イエスは舟に乗ってすわったまま、海上におられ、群衆はみな海に沿って陸地にいた。2 イエスは譬で多くの事を教えられたが、その教の中で彼らにこう言われた、 3 「聞きなさい、種まきが種をまきに出て行った。4 まいているうちに、道ばたに落ちた種があった。すると、鳥がきて食べてしまった。 5 ほかの種は土の薄い石地に落ちた。そこは土が深くないので、すぐ芽を出したが、6 日が上ると焼けて、根がないために枯れてしまった。 7 ほかの種はいばらの中に落ちた。すると、いばらが伸びて、ふさいでしまったので、実を結ばなかった。 8 ほかの種は良い地に落ちた。そしてはえて、育って、ますます実を結び、三十倍、六十倍、百倍にもなった」。9 そして言われた、「聞く耳のある者は聞くがよい」。

### マタイ 13:1-9

> 1 その日、イエスは家を出て、海べにすわっておられた。2 ところが、大ぜいの群衆がみもとに集まったので、イエスは舟に乗ってすわられ、群衆はみな岸に立っていた。3 イエスは譬で多くの事を語り、こう言われた、「見よ、種まきが種をまきに出て行った。4 まいているうちに、道ばたに落ちた種があった。すると、鳥がきて食べてしまった。5 ほかの種は土の薄い石地に落ちた。そこは土が深くないので、すぐ芽を出したが、6 日が上ると焼けて、根がないために枯れてしまった。7 ほかの種はいばらの地に落ちた。すると、いばらが伸びて、ふさいでしまった。8 ほかの種は良い地に落ちて実を結び、あるものは百倍、あるものは六十倍、あるものは三十倍にもなった。9 耳のある者は聞くがよい」。 

### ルカ 8:4-8

> 4 さて、大ぜいの群衆が集まり、その上、町々からの人たちがイエスのところに、ぞくぞくと押し寄せてきたので、一つの譬で話をされた、5 「種まきが種をまきに出て行った。まいているうちに、ある種は道ばたに落ち、踏みつけられ、そして空の鳥に食べられてしまった。6 ほかの種は岩の上に落ち、はえはしたが水気がないので枯れてしまった。7 ほかの種は、いばらの間に落ちたので、いばらも一緒に茂ってきて、それをふさいでしまった。8 ところが、ほかの種は良い地に落ちたので、はえ育って百倍もの実を結んだ」。こう語られたのち、声をあげて「聞く耳のある者は聞くがよい」と言われた。

[マルコによる福音書4章1-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_1-9.pdf)

### 問い

1.  イエスはどこでどのような人たちにどのようなな方法で教えていますか。

2.  なぜ、舟に乗って教えたのでしょうか。会堂で教えることとは、どのような違いがありますか。

3.  一般的にたとえ話にはどのような特徴・効果がありますか。

4.  種がまかれた４種類の土地について書かれていますが、これらの土地の特徴、そしてその種がどうなったかについてまとめてみましょう。どうして異なる結果になったのでしょうか。

5.  最後に、イエスはなんと言っていますか。

### 参照

-   たとえと比喩：[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#たとえと比喩)
-   これまでに教えた場所
    -   マルコ1:16 海辺：弟子を招く
    -   マルコ1:21 それから、彼らはカペナウムに行った。そして安息日にすぐ、イエスは**会堂**にはいって教えられた。
    -   マルコ1:29 シモンとアンデレとの家
    -   マルコ1:39 そして、ガリラヤ全地を巡りあるいて、諸**会堂**で教えを宣べ伝え、また悪霊を追い出された。重い皮膚病
    -   マルコ2:1,2 幾日かたって、イエスがまたカペナウムにお帰りになったとき、**家**におられるといううわさが立ったので、
    -   マルコ2:13 イエスはまた海べに出て行かれると、多くの人々がみもとに集まってきたので、彼らを教えられた。
    -   マルコ2:15 レビの家
    -   マルコ2:23 麦畑
    -   マルコ3:1 イエスがまた会堂にはいられると、そこに片手のなえた人がいた。
    -   マルコ3:7-10 それから、イエスは弟子たちと共に海べに退かれたが、ガリラヤからきたおびただしい群衆がついて行った。またユダヤから、8 エルサレムから、イドマヤから、更にヨルダンの向こうから、ツロ、シドンのあたりからも、おびただしい群衆が、そのなさっていることを聞いて、みもとにきた。9 イエスは群衆が自分に押し迫るのを避けるために、小舟を用意しておけと、弟子たちに命じられた。10 それは、多くの人をいやされたので、病苦に悩む者は皆イエスにさわろうとして、押し寄せてきたからである。
    -   マルコ3:13 さてイエスは山に登り、みこころにかなった者たちを呼び寄せられたので、彼らはみもとにきた。
    -   マルコ3:19b, 20 イエスが家にはいられると、20 群衆がまた集まってきたので、一同は食事をする暇もないほどであった。 
-   **説教における舟の利用**
    -   マルコ3:9 イエスは群衆が自分に押し迫るのを避けるために、小**舟**を用意しておけと、弟子たちに命じられた。
    -   ルカ5:3 その一そうはシモンの**舟**であったが、イエスはそれに乗り込み、シモンに頼んで岸から少しこぎ出させ、そしてすわって、**舟**の中から群衆にお教えになった。

> **1** Καὶ πάλιν ἤρξατο διδάσκειν παρὰ τὴν θάλασσαν· καὶ συνάγεται[^markdq-231] πρὸς αὐτὸν ὄχλος πλεῖστος, ὥστε αὐτὸν εἰς πλοῖον ἐμβάντα καθῆσθαι ἐν τῇ θαλάσσῃ, καὶ πᾶς ὁ ὄχλος πρὸς τὴν θάλασσαν ἐπὶ τῆς γῆς ἦσαν. **2** καὶ ἐδίδασκεν αὐτοὺς ἐν παραβολαῖς[^markdq-232] πολλὰ καὶ ἔλεγεν αὐτοῖς ἐν τῇ διδαχῇ αὐτοῦ· **3** Ἀκούετε. ἰδοὺ ἐξῆλθεν ὁ σπείρων σπεῖραι[^markdq-233]. **4** καὶ ἐγένετο ἐν τῷ σπείρειν ὃ μὲν ἔπεσεν παρὰ τὴν ὁδόν, καὶ ἦλθεν τὰ πετεινὰ[^markdq-234] καὶ κατέφαγεν[^markdq-235] αὐτό. **5** καὶ ἄλλο ἔπεσεν ἐπὶ τὸ πετρῶδες[^markdq-236] ὅπου οὐκ εἶχεν γῆν πολλήν, καὶ εὐθὺς ἐξανέτειλεν[^markdq-237] διὰ τὸ μὴ ἔχειν βάθος γῆς· **6** καὶ ὅτε ἀνέτειλεν ὁ ἥλιος ἐκαυματίσθη[^markdq-238] καὶ διὰ τὸ μὴ ἔχειν ῥίζαν[^markdq-239] ἐξηράνθη[^markdq-240]. **7** καὶ ἄλλο ἔπεσεν εἰς τὰς ἀκάνθας[^markdq-241], καὶ ἀνέβησαν[^markdq-242] αἱ ἄκανθαι καὶ συνέπνιξαν[^markdq-243] αὐτό, καὶ καρπὸν οὐκ ἔδωκεν. **8** καὶ ἄλλα ἔπεσεν εἰς τὴν γῆν τὴν καλὴν καὶ ἐδίδου καρπὸν ἀναβαίνοντα καὶ αὐξανόμενα καὶ ἔφερεν ἓν τριάκοντα καὶ ἓν ἑξήκοντα καὶ ἓν ἑκατόν. **9** καὶ ἔλεγεν· ὃς ἔχει ὦτα ἀκούειν ἀκουέτω.

[^markdq-231]: συνάγω (API-3S): i) to gather together, to gather, ii) to bring together, assemble, collect, iii) to lead with one's self

[^markdq-232]: παραβολή (DOF): i) a placing of one thing by the side of another, juxtaposition, as of ships in battle, ii) metaph. a) a comparing, comparison of one thing with another, likeness, similitude b) an example by which a doctrine or precept is illustrated c) a narrative, fictitious but agreeable to the laws and usages of human life, by which either the duties of men or the things of God, particularly the nature and history of God's kingdom are figuratively portrayed, d) a parable: an earthly story with a heavenly meaning, iii) a pithy and instructive saying, involving some likeness or comparison and having preceptive or admonitory force, a) an aphorism, a maxim, iv) a proverb, v) an act by which one exposes himself or his possessions to danger, a venture, a risk

[^markdq-233]: σπείρω (AAN): i) to sow, scatter, seed, ii) metaph. of proverbial sayings

[^markdq-234]: πετεινόν: i) flying, winged, ii) flying or winged animals, birds

[^markdq-235]: κατεσθίω (2AAI-3S): i) to consume by eating, to eat up, devour, ii) metaph.

[^markdq-236]: πετρώδης (ASN): rocky, stony

[^markdq-237]: ἐξανατέλλω: i) to make spring up, cause to shoot forth, ii) to spring up

[^markdq-238]: καυματίζω: i) to burn with heat, to scorch, ii) to be tortured with intense heat

[^markdq-239]: ῥίζα: i) a root, ii) that which like a root springs from a root, a sprout, shoot, iii) metaph. offspring, progeny

[^markdq-240]: ξηραίνω (API-3S): i) to make dry, dry up, wither, ii) to become dry, to be dry, be withered, iii) to waste away, pine away, i.e. a withered hand

[^markdq-241]: ἄκανθα (APS): i) thorn, bramble, ii) bush, brier, a thorny plant

[^markdq-242]: ἀναβαίνω: ascend, a) to go up, b) to rise, mount, be borne up, spring up

[^markdq-243]: συμπνίγω: to choke utterly, a) metaph. the seed of the divine word sown in the mind, b) to press round or throng one so as almost to suffocate him

### 記録

-   日時：2023年8月24日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）5名

### 問いについて

1.  どこで、どのようなひとたちに、どのような方法で

    -   1 イエスは**またも**、海べで教えはじめられた。おびただしい群衆がみもとに集まったので、イエスは舟に乗ってすわったまま、海上におられ、群衆はみな海に沿って陸地にいた。2 イエスは譬で多くの事を教えられたが、その教の中で彼らにこう言われた、

    -   陸地にいる、おびただしい群衆（1000人以上か）にむかい、舟に乗って座ったまま、譬でおしえた。

2.  なぜ、舟に乗って、会堂で教えることとの違い

    -   いやしや、悪霊を追い出すのではなく、話をするため

    -   何が大切かをしっていた

    -   会堂は許可がいる、人数が限られる、パリサイ派のひとたちや、律法学者たちとの議論をさけるため

    -   会堂では、律法学者や、長老、会堂司の許可・合意が得られず、イエスはもう教えられなかったかもしれない。一方、屋外では、会堂に入りづらいひとも、聞くことができたかもしれない。

3.  たとえ話

    -   考えてもらうため、何を伝えるためだろうか。
    -   たとえ（παραβολή: a placing of one thing by the side of another, juxtaposition）：あるものの、横に置く
    -   神の国の奥義（11節）は、知らないこと、わからないこと。イエスは、それを教えるのに、たとえを用いられた。

4.  四種類の土地とその結果、なぜ異なる結果となったか

    -   道ばた：鳥が来て食べた。ルカでは「踏みつけられ」

    -   土の薄い石地：すぐに芽を出したが、根がないので枯れてしまった

    -   いばらの中：いばらが伸びて、ふさぎ、実がならなかった（実のことはマルコのみ）

    -   良い地：はえて、そだち、実を結び、三十倍、六十倍、百倍。マタイでは、百倍、六十倍、三十倍、ルカでは、百倍。

    -   種はおなじ、撒かれた場所も偶然に見える。

    -   結果はどこに責任があるのか。実際とたとえ

5.  聞く耳のある者はきくがよい

    -   マタイは「耳のある者は聞くが良い」（ὁ ἔχων ὦτα ἀκουέτω.）
    -   聞き方に注意せよということか

### メモ

-   譬（たとえ）天的な意味を持つ地上の物語。天のこと、神の国のことは、神の国は近いと言われても、想像がつかない。地上の身近なもので説明してもらわないと、わからない。
-   聞きなさい。聞く耳のある者は聞きなさい、と聞くことの大切さ、おそらく、しっかり聞いて、理解することが求められている。そこには、ベルゼブルの話でも出てきた、聖霊の促しがあるのかもしれない。
-   一つ一つのたねの撒かれた地について、イエスが知っていたり、制御していたりするわけではない。聞く側に、すべての責任があるわけでもないだろう。神様に委ねられているとも言えるし、わからないとも言える。それこそ、奥義は、完璧に理解できるわけではないのかもしれな。しかし、注意して聞き、理解しようとすること、心に語りかける聖霊の促しに心をとめることも必要。

## 4:10-12 たとえを用いて話す理由

> 4:10 イエスがひとりになられた時、そばにいた者たちが、十二弟子と共に、これらの譬について尋ねた。11 そこでイエスは言われた、「あなたがたには神の国の奥義が授けられているが、ほかの者たちには、すべてが譬で語られる。 12 それは／『彼らは見るには見るが、認めず、／聞くには聞くが、悟らず、／悔い改めてゆるされることがない』／ためである」。

### マタイ 13:10-17

> 10 それから、弟子たちがイエスに近寄ってきて言った、「なぜ、彼らに譬でお話しになるのですか」。11 そこでイエスは答えて言われた、「あなたがたには、天国の奥義を知ることが許されているが、彼らには許されていない。12 おおよそ、持っている人は与えられて、いよいよ豊かになるが、持っていない人は、持っているものまでも取り上げられるであろう。13 だから、彼らには譬で語るのである。それは彼らが、見ても見ず、聞いても聞かず、また悟らないからである。14 こうしてイザヤの言った預言が、彼らの上に成就したのである。『あなたがたは聞くには聞くが、／決して悟らない。見るには見るが、決して認めない。15 この民の心は鈍くなり、／その耳は聞えにくく、／その目は閉じている。それは、彼らが目で見ず、耳で聞かず、心で悟らず、／悔い改めていやされることがないためである』。16 しかし、あなたがたの目は見ており、耳は聞いているから、さいわいである。17 あなたがたによく言っておく。多くの預言者や義人は、あなたがたの見ていることを見ようと熱心に願ったが、見ることができず、またあなたがたの聞いていることを聞こうとしたが、聞けなかったのである。

### ルカ 8:9-10

> 9 弟子たちは、この譬はどういう意味でしょうか、とイエスに質問した。10 そこで言われた、「あなたがたには、神の国の奥義を知ることが許されているが、ほかの人たちには、見ても見えず、聞いても悟られないために、譬で話すのである。

[マルコによる福音書4章10-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_10-12.pdf)

### 問い

1.  たとえについて尋ね、説明を聞いているのはだれですか。

2.  以下、マタイを中心に考えましょう。なぜイエスはたとえを用いるのでしょうか。

3.  弟子たちが「神の国の奥義を授けられている」とは、どのような意味なのでしょうか。群衆とはなにが違うのでしょうか。

4.  イザヤ書からの引用はなにを伝えているのでしょうか。

5.  マタイ13章17節の「多くの預言者や義人」が見たかったこと、聞きたかったこととは何なのでしょうか。

### 参照

-   **ルカ直前の記事**：ルカ8:1-3 そののちイエスは、神の国の福音を説きまた伝えながら、町々村々を巡回し続けられたが、十二弟子もお供をした。2 また悪霊を追い出され病気をいやされた数名の婦人たち、すなわち、七つの悪霊を追い出してもらったマグダラと呼ばれるマリヤ、3 ヘロデの家令クーザの妻ヨハンナ、スザンナ、そのほか多くの婦人たちも一緒にいて、自分たちの持ち物をもって一行に奉仕した。
    -   マルコ15:40,41 また、遠くの方から見ている女たちもいた。その中には、マグダラのマリヤ、小ヤコブとヨセとの母マリヤ、またサロメがいた。41 彼らはイエスがガリラヤにおられたとき、そのあとに従って仕えた女たちであった。なおそのほか、イエスと共にエルサレムに上ってきた多くの女たちもいた。
    -   （対照句）マタイ27:56 その中には、マグダラのマリヤ、ヤコブとヨセフとの母マリヤ、またゼベダイの子たちの母がいた。（マタイ13:55）
-   イザヤ6:9-10 主は言われた、「あなたは行って、この民にこう言いなさい、／『あなたがたはくりかえし聞くがよい、／しかし悟ってはならない。あなたがたはくりかえし見るがよい、／しかしわかってはならない』と。10 あなたはこの民の心を鈍くし、／その耳を聞えにくくし、／その目を閉ざしなさい。これは彼らがその目で見、／その耳で聞き、／その心で悟り、／悔い改めていやされることのないためである」。
-   ヨハネ12:36-43 光のある間に、光の子となるために、光を信じなさい」。イエスはこれらのことを話してから、そこを立ち去って、彼らから身をお隠しになった。37 このように多くのしるしを彼らの前でなさったが、彼らはイエスを信じなかった。38 それは、預言者イザヤの次の言葉が成就するためである、「主よ、わたしたちの説くところを、だれが信じたでしょうか。また、主のみ腕はだれに示されたでしょうか」。39 こういうわけで、彼らは信じることができなかった。イザヤはまた、こうも言った、40 「神は彼らの目をくらまし、心をかたくなになさった。それは、彼らが目で見ず、心で悟らず、悔い改めていやされることがないためである」。41 イザヤがこう言ったのは、イエスの栄光を見たからであって、イエスのことを語ったのである。42 しかし、役人たちの中にも、イエスを信じた者が多かったが、パリサイ人をはばかって、告白はしなかった。会堂から追い出されるのを恐れていたのである。43 彼らは神のほまれよりも、人のほまれを好んだからである。
-   使徒28:23-28(-29) そこで、日を定めて、大ぜいの人が、パウロの宿につめかけてきたので、朝から晩まで、パウロは語り続け、神の国のことをあかしし、またモーセの律法や預言者の書を引いて、イエスについて彼らの説得につとめた。24 ある者はパウロの言うことを受けいれ、ある者は信じようともしなかった。25 互に意見が合わなくて、みんなの者が帰ろうとしていた時、パウロはひとこと述べて言った、「聖霊はよくも預言者イザヤによって、あなたがたの先祖に語ったものである。26 『この民に行って言え、／あなたがたは聞くには聞くが、決して悟らない。見るには見るが、決して認めない。27 この民の心は鈍くなり、／その耳は聞えにくく、／その目は閉じている。それは、彼らが目で見ず、／耳で聞かず、／心で悟らず、悔い改めて／いやされることがないためである』。28 そこで、あなたがたは知っておくがよい。神のこの救の言葉は、異邦人に送られたのだ。彼らは、これに聞きしたがうであろう」。29 〔パウロがこれらのことを述べ終ると、ユダヤ人らは、互に論じ合いながら帰って行った。〕
-   参照：ローマ11:7-8 では、どうなるのか。イスラエルはその追い求めているものを得ないで、ただ選ばれた者が、それを得た。そして、他の者たちはかたくなになった。8 「神は、彼らに鈍い心と、／見えない目と、聞えない耳とを与えて、／きょう、この日に及んでいる」／と書いてあるとおりである。
    -   申命記29:4 (or 3) しかし、今日まで主はあなたがたの心に悟らせず、目に見させず、耳に聞かせられなかった。
    -   イザヤ29:10 主が深い眠りの霊をあなたがたの上にそそぎ、／あなたがたの目である預言者を閉じこめ、／あなたがたの頭である先見者を／おおわれたからである。

> **10** Καὶ ὅτε ἐγένετο κατὰ μόνας, ἠρώτων[^markdq-244] αὐτὸν οἱ περὶ αὐτὸν σὺν τοῖς δώδεκα τὰς παραβολάς. **11** καὶ ἔλεγεν αὐτοῖς· ὑμῖν τὸ μυστήριον δέδοται τῆς βασιλείας τοῦ θεοῦ· ἐκείνοις δὲ τοῖς ἔξω[^markdq-245] ἐν παραβολαῖς τὰ πάντα γίνεται[^markdq-246], **12** ἵνα *βλέποντες βλέπωσιν καὶ μὴ ἴδωσιν,* *καὶ ἀκούοντες ἀκούωσιν καὶ μὴ συνιῶσιν,* μήποτε *ἐπιστρέψωσιν* καὶ *ἀφεθῇ αὐτοῖς*.

[^markdq-244]: ἐρωτάω (AAI-3P): i) to question, ii) to ask

[^markdq-245]: ἔξω: without, out of doors

[^markdq-246]: γίνομαι: i) to become, i.e. to come into existence, begin to be, receive being, ii) to become, i.e. to come to pass, happen, iii) to arise, appear in history, come upon the stage, iv) to be made, finished, v) to become, be made

マタイ13:10-17

> 10 Καὶ προσελθόντες οἱ μαθηταὶ εἶπαν αὐτῷ· διὰ τί ἐν παραβολαῖς λαλεῖς αὐτοῖς; 11 ὁ δὲ ἀποκριθεὶς εἶπεν αὐτοῖς· ὅτι ὑμῖν δέδοται γνῶναι τὰ μυστήρια τῆς βασιλείας τῶν οὐρανῶν, ἐκείνοις δὲ οὐ δέδοται. 12 ὅστις γὰρ ἔχει, δοθήσεται αὐτῷ καὶ περισσευθήσεται· ὅστις δὲ οὐκ ἔχει, καὶ ὃ ἔχει ἀρθήσεται ἀπ' αὐτοῦ. 13διὰ τοῦτο ἐν παραβολαῖς αὐτοῖς λαλῶ, ὅτι βλέποντες οὐ βλέπουσιν καὶ ἀκούοντες οὐκ ἀκούουσιν οὐδὲ συνίουσιν, 14καὶ ἀναπληροῦται αὐτοῖς ἡ προφητεία Ἠσαΐου ἡ λέγουσα· ἀκοῇ ἀκούσετε καὶ οὐ μὴ συνῆτε, καὶ βλέποντες βλέψετε καὶ οὐ μὴ ἴδητε. 15 ἐπαχύνθη γὰρ ἡ καρδία τοῦ λαοῦ τούτου, καὶ τοῖς ὠσὶν βαρέως ἤκουσαν καὶ τοὺς ὀφθαλμοὺς αὐτῶν ἐκάμμυσαν, μήποτε ἴδωσιν τοῖς ὀφθαλμοῖς καὶ τοῖς ὠσὶν ἀκούσωσιν καὶ τῇ καρδίᾳ συνῶσιν καὶ ἐπιστρέψωσιν καὶ ἰάσομαι αὐτούς. 16 ὑμῶν δὲ μακάριοι οἱ ὀφθαλμοὶ ὅτι βλέπουσιν καὶ τὰ ὦτα ὑμῶν ὅτι ἀκούουσιν. 17 ἀμὴν γὰρ λέγω ὑμῖν ὅτι πολλοὶ προφῆται καὶ δίκαιοι ἐπεθύμησαν ἰδεῖν ἃ βλέπετε καὶ οὐκ εἶδαν, καὶ ἀκοῦσαι ἃ ἀκούετε καὶ οὐκ ἤκουσαν.

### 記録

-   日時：2023年8月31日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）1名

### 問いについて

1.  説明を聞いているのは

    -   マルコ：そばにいた者たち、十二弟子。マタイ、ルカでは、弟子たち。

    -   ルカ8:1-3 参照。多くの女性たちが一緒にいたことがわかる。2 また悪霊を追い出され病気をいやされた数名の婦人たち、すなわち、七つの悪霊を追い出してもらったマグダラと呼ばれるマリヤ、3 ヘロデの家令クーザの妻ヨハンナ、スザンナ、そのほか多くの婦人たちも一緒にいて、自分たちの持ち物をもって一行に奉仕した。

        -   ルカではこの前に、パリサイ人シモンの家での食事の記事（7:36-50）で、罪の女であったものが、香油が入れてある石膏のつぼを持ってきて、泣きながら、イエスのうしろでその足もとに寄り、まず涙でイエスの足をぬらし、自分の髪の毛でぬぐい、そして、その足に接吻して、香油を塗った。記事がある。最後には、イエスは女にむかって言われた、「あなたの信仰があなたを救ったのです。安心して行きなさい」。と伝えている。

2.  なぜ、たとえを用いるのか

    -   マルコ：「あなたがたには神の国の奥義が授けられているが、ほかの者たちには、すべてが譬で語られる。 12 それは／『彼らは見るには見るが、認めず、／聞くには聞くが、悟らず、／悔い改めてゆるされることがない』／ためである」。明確ではないが、旧約聖書からの引用を匂わせる言葉を付け加えている。

    -   ルカ：「あなたがたには、神の国の奥義を知ることが許されているが、ほかの人たちには、見ても見えず、聞いても悟られないために、譬で話すのである。」一番簡単。旧約聖書からの引用も、あまり感じられない。

    -   マタイ：「あなたがたには、天国の奥義を知ることが許されているが、彼らには許されていない。12 おおよそ、持っている人は与えられて、いよいよ豊かになるが、持っていない人は、持っているものまでも取り上げられるであろう。13 だから、彼らには譬で語るのである。それは彼らが、見ても見ず、聞いても聞かず、また悟らないからである。

    -   共通なのは「神の国（天国）の奥義を知ることが許されている」という部分、つまり、神の国についての、たとえなので、直接には語っても理解できない。だから、我々あの住む世界にあるものに置き換えて、たとえで語る。

3.  弟子たちは何が違うのか

    -   そばにいる、つねに、イエスと共にいて、学ぼうとしているかどうか。

        -   そばにいると、なにが違うのか。

    -   神の御心を、天の父の御心として生きること、神の国がすでにきている。近いと感じられる、神の国自体を日常的にみることができるかどうかにかかっている。

    -   みなさんは、神の国（が近いこと）を見ていますか、

4.  イザヤ書

    -   14 こうしてイザヤの言った預言が、彼らの上に成就したのである。『あなたがたは聞くには聞くが、／決して悟らない。見るには見るが、決して認めない。15 この民の心は鈍くなり、／その耳は聞えにくく、／その目は閉じている。それは、彼らが目で見ず、耳で聞かず、心で悟らず、／悔い改めていやされることがないためである』。
    -   イザヤ6:9-10、ヨハネ12:36-43、使徒28:23-28(-29) 参照
    -   （適切に素晴らしいメッセージを）語れば、聞き入れられ、悔い改めに至るわけではない。悔い改めない自由も（自立性）も与えられている。同時に、聖霊が語りかけ、悔い改めが促されていることも事実。そこに、至らない理由は、ひと様々だということもあるのだろう。種まきの譬からも。悔い改めて、イエスに従うことは、神の国の奥義を得ることでもある。

5.  「多くの預言者や義人」が見たかったこと、聞きたかったこと？

    -   16 しかし、あなたがたの目は見ており、耳は聞いているから、さいわいである。17 あなたがたによく言っておく。多くの預言者や義人は、あなたがたの見ていることを見ようと熱心に願ったが、見ることができず、またあなたがたの聞いていることを聞こうとしたが、聞けなかったのである。

    -   おそらく、「天国の奥義」（マタイ13:11）、「神の国の奥義」（マルコ4:11、ルカ8:10）を指していると思われる。

    -   「多くの預言者や義人」が見たかったこと、聞きたかったこととすると、メシヤを意味しているともとれる。そのメシヤを通して、示される神様の御心？

    -   イエスのそばにいることで、神の国がすぐそばにあることを見ることができる。

    -   マタイ12:28-29 28 しかし、わたしが神の霊によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。ルカ11:20-21 20 しかし、わたしが神の指によって悪霊を追い出しているのなら、神の国はすでにあなたがたのところにきたのである。

### メモ

-   「イエスがひとりになられた時、そばにいた者たちが、十二弟子と共に、これらの譬について尋ねた。」（10）とはじまる。それを待っていたのだろうか。そばにいたのに、イエスがひとりになられた時と言っている。イエスに従ってきていたひとは、別としてということだろう。十二弟子と共には、知りたかったのは、そばにいたものたちだが、弟子たちが意味がわからないとは言えなかったのかもしれない。しかし、結局、皆でイエスの下に、聞きにに行く。
-   イエスのそばにいて、何がよかったかは、神の国の奥義を知る鍵でもあるだろう。すこし考えてみる。
    -   直接的には、解きあかしを聞くことができる。説明してもらえる。
    -   そばにいることで、イエスが伝える、神の国の到来を、それが神の国が近いことだとして経験することができる。
    -   イエスは、つねに守ってくれる。レビの家での会食の時。麦の穂を摘んで食べていた時。他にもあるように思える。
    -   共に、働くことができる。舟を用意する。派遣される。他にもあるように思える。
    -   もっと一般的に、神様の御心を知ることなのかもしれない。イエスと共に歩むこと、イエスに従っていくことに勝るものはないように思う。一つのことでは、ないように思う。「神の御心を行う人」（マタイ12:50）になることなのかもしれない。一点ではなく、ずっと継続的に、イエスに従って歩むことだろうか。
-   Matt 13:11b: あなたがたには、天国の奥義を**知ること**が許されているが、彼らには許されていない。ὅτι ὑμῖν δέδοται γνῶναι[^markdq-247] τὰ μυστήρια τῆς βασιλείας τῶν οὐρανῶν, ἐκείνοις δὲ οὐ δέδοται.
-   かたくなにするメッセージ：聖霊による導き、語りかけがあり、それに応答する悔い改めが、同時に促されている。まさに、聞く耳のあるものは、聞きなさい。
-   イザヤの部分は、マルコだけではなく、ルカでもほとんど触れていないので、イエスは、イザヤの言葉として、引用したのではないかもしれない。

[^markdq-247]: γινώσκω: i) to learn to know, come to know, get a knowledge of perceive, feel, ii) to know, understand, perceive, have knowledge of, iii) sexual intercourse between a man and a woman, iv) to become acquainted with, to know

## 4:13-20 「種を蒔く人」のたとえの説明

> 4:13 また彼らに言われた、「あなたがたはこの譬がわからないのか。それでは、どうしてすべての譬がわかるだろうか。14 種まきは御言をまくのである。15 道ばたに御言がまかれたとは、こういう人たちのことである。すなわち、御言を聞くと、すぐにサタンがきて、彼らの中にまかれた御言を、奪って行くのである。16 同じように、石地にまかれたものとは、こういう人たちのことである。御言を聞くと、すぐに喜んで受けるが、 17 自分の中に根がないので、しばらく続くだけである。そののち、御言のために困難や迫害が起ってくると、すぐつまずいてしまう。18 また、いばらの中にまかれたものとは、こういう人たちのことである。御言を聞くが、19 世の心づかいと、富の惑わしと、その他いろいろな欲とがはいってきて、御言をふさぐので、実を結ばなくなる。20 また、良い地にまかれたものとは、こういう人たちのことである。御言を聞いて受けいれ、三十倍、六十倍、百倍の実を結ぶのである」。

### マタイ 13:18-23

> 18 そこで、種まきの譬を聞きなさい。19 だれでも御国の言を聞いて悟らないならば、悪い者がきて、その人の心にまかれたものを奪いとって行く。道ばたにまかれたものというのは、そういう人のことである。20 石地にまかれたものというのは、御言を聞くと、すぐに喜んで受ける人のことである。21 その中に根がないので、しばらく続くだけであって、御言のために困難や迫害が起ってくると、すぐつまずいてしまう。22 また、いばらの中にまかれたものとは、御言を聞くが、世の心づかいと富の惑わしとが御言をふさぐので、実を結ばなくなる人のことである。23 また、良い地にまかれたものとは、御言を聞いて悟る人のことであって、そういう人が実を結び、百倍、あるいは六十倍、あるいは三十倍にもなるのである」。

### ルカ 8:11-15

> 11 この譬はこういう意味である。種は神の言である。12 道ばたに落ちたのは、聞いたのち、信じることも救われることもないように、悪魔によってその心から御言が奪い取られる人たちのことである。13 岩の上に落ちたのは、御言を聞いた時には喜んで受けいれるが、根が無いので、しばらくは信じていても、試錬の時が来ると、信仰を捨てる人たちのことである。 14 いばらの中に落ちたのは、聞いてから日を過ごすうちに、生活の心づかいや富や快楽にふさがれて、実の熟するまでにならない人たちのことである。15 良い地に落ちたのは、御言を聞いたのち、これを正しい良い心でしっかりと守り、耐え忍んで実を結ぶに至る人たちのことである。

[マルコによる福音書3章13-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_13-20.pdf)

### 問い

1.  マルコ、マタイ、ルカを比較しながら読みましょう。たとえのなかで、種まきのまく種は何だと言っていますか。

2.  「道ばたに蒔かれたもの」とはどのような人たちで、どうなりますか。

3.  「石地に蒔かれたもの」とはどのような人たちで、どうなりますか。

4.  「茨の中に蒔かれたもの」とはどのような人たちで、どうなりますか。

5.  「良い土地に蒔かれたもの」とはどのような人たちで、どうなりますか。

6.  イエスは、このたとえとそのときあかしを通して、何を伝えようとしているのでしょうか。弟子たちや、イエスのことばを聞いた人たちは、何に注意し、何を理解しないといけないのでしょうか。

### 参照

> 13 Καὶ λέγει αὐτοῖς· οὐκ οἴδατε τὴν παραβολὴν ταύτην, καὶ πῶς πάσας τὰς παραβολὰς γνώσεσθε; 14 ὁ σπείρων τὸν λόγον σπείρει. 15 οὗτοι δέ εἰσιν οἱ παρὰ τὴν ὁδόν· ὅπου σπείρεται ὁ λόγος καὶ ὅταν ἀκούσωσιν, εὐθὺς ἔρχεται ὁ σατανᾶς καὶ αἴρει τὸν λόγον τὸν ἐσπαρμένον εἰς αὐτούς. 16 καὶ οὗτοί εἰσιν οἱ ἐπὶ τὰ πετρώδη σπειρόμενοι, οἳ ὅταν ἀκούσωσιν τὸν λόγον εὐθὺς μετὰ χαρᾶς λαμβάνουσιν αὐτόν, 17 καὶ οὐκ ἔχουσιν ῥίζαν ἐν ἑαυτοῖς ἀλλὰ πρόσκαιροί εἰσιν, εἶτα γενομένης θλίψεως ἢ διωγμοῦ διὰ τὸν λόγον εὐθὺς σκανδαλίζονται. 18 καὶ ἄλλοι εἰσὶν οἱ εἰς τὰς ἀκάνθας σπειρόμενοι· οὗτοί εἰσιν οἱ τὸν λόγον ἀκούσαντες, 19 καὶ αἱ μέριμναι τοῦ αἰῶνος καὶ ἡ ἀπάτη τοῦ πλούτου καὶ αἱ περὶ τὰ λοιπὰ ἐπιθυμίαι εἰσπορευόμεναι συμπνίγουσιν τὸν λόγον καὶ ἄκαρπος γίνεται. 20 καὶ ἐκεῖνοί εἰσιν οἱ ἐπὶ τὴν γῆν τὴν καλὴν σπαρέντες, οἵτινες ἀκούουσιν τὸν λόγον καὶ παραδέχονται καὶ καρποφοροῦσιν ἓν τριάκοντα καὶ ἓν ἑξήκοντα καὶ ἓν ἑκατόν.

### 記録

-   日時：2023年9月7日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  種まきのまく種

    -   （聞く）御言（マルコ）14 種まきは御言をまくのである。御国の言（マタイ13:19）神の言（ルカ8:11）これ以外は、御言

    -   心にまかれたもの（マタイ13:18）

2.  道ばたに蒔かれたもの

    -   マルコ4:15 道ばたに御言がまかれたとは、こういう人たちのことである。すなわち、御言を聞くと、すぐにサタンがきて、彼らの中にまかれた御言を、奪って行くのである。

    -   マタイ13:19 だれでも御国の言を聞いて悟らないならば、悪い者がきて、その人の心にまかれたものを奪いとって行く。道ばたにまかれたものというのは、そういう人のことである。

    -   ルカ8:12 道ばたに落ちたのは、聞いたのち、信じることも救われることもないように、悪魔によってその心から御言が奪い取られる人たちのことである。

3.  石地に蒔かれたもの

    -   マルコ4:16,17 16 同じように、石地にまかれたものとは、こういう人たちのことである。御言を聞くと、すぐに喜んで受けるが、 17 自分の中に根がないので、しばらく続くだけである。そののち、御言のために困難や迫害が起ってくると、すぐつまずいてしまう。

    -   マタイ13:20,21 20 石地にまかれたものというのは、御言を聞くと、すぐに喜んで受ける人のことである。21 その中に根がないので、しばらく続くだけであって、御言のために困難や迫害が起ってくると、すぐつまずいてしまう。

    -   ルカ8:13 岩の上に落ちたのは、御言を聞いた時には喜んで受けいれるが、根が無いので、しばらくは信じていても、試錬の時が来ると、信仰を捨てる人たちのことである。

4.  茨の中に蒔かれたもの

    -   マルコ4:18,19 18 また、いばらの中にまかれたものとは、こういう人たちのことである。御言を聞くが、19 世の心づかいと、富の惑わしと、その他いろいろな欲とがはいってきて、御言をふさぐので、実を結ばなくなる。

    -   マタイ13:22 また、いばらの中にまかれたものとは、御言を聞くが、世の心づかいと富の惑わしとが御言をふさぐので、実を結ばなくなる人のことである。

    -   ルカ8:14 いばらの中に落ちたのは、聞いてから日を過ごすうちに、生活の心づかいや富や快楽にふさがれて、実の熟するまでにならない人たちのことである。

5.  良い土地に蒔かれたもの

    -   マルコ4:20 20 また、良い地にまかれたものとは、こういう人たちのことである。御言を聞いて受けいれ、三十倍、六十倍、百倍の実を結ぶのである」。

    -   マタイ13:23 また、良い地にまかれたものとは、御言を聞いて悟る人のことであって、そういう人が実を結び、百倍、あるいは六十倍、あるいは三十倍にもなるのである」。

    -   ルカ8:15 良い地に落ちたのは、御言を聞いたのち、これを正しい良い心でしっかりと守り、耐え忍んで実を結ぶに至る人たちのことである。

6.  何を理解しなければいけないのか

    -   マルコ4:13b あなたがたはこの譬がわからないのか。それでは、どうしてすべての譬がわかるだろうか。

### メモ

## 4:21-25 「灯」と「秤」のたとえ

> 4:21 また彼らに言われた、「ますの下や寝台の下に置くために、あかりを持ってくることがあろうか。燭台の上に置くためではないか。22 なんでも、隠されているもので、現れないものはなく、秘密にされているもので、明るみに出ないものはない。23 聞く耳のある者は聞くがよい」。 24 また彼らに言われた、「聞くことがらに注意しなさい。あなたがたの量るそのはかりで、自分にも量り与えられ、その上になお増し加えられるであろう。25 だれでも、持っている人は更に与えられ、持っていない人は、持っているものまでも取り上げられるであろう」。

### ルカ 8:16-18

> 16 だれもあかりをともして、それを何かの器でおおいかぶせたり、寝台の下に置いたりはしない。燭台の上に置いて、はいって来る人たちに光が見えるようにするのである。17 隠されているもので、あらわにならないものはなく、秘密にされているもので、ついには知られ、明るみに出されないものはない。18 だから、どう聞くかに注意するがよい。持っている人は更に与えられ、持っていない人は、持っていると思っているものまでも、取り上げられるであろう」。 

[マルコによる福音書4章21-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_21-25.pdf)

### 問い

1.  21, 22節がたとえについて語っているとすると、イエスは何と言っているのでしょうか。

2.  24, 25節でイエスは神の言葉に注意して耳を傾けることの重要性をどのように強調していますか。

3.  わたしたちが神の言葉に注意しなくなるとどんなことがおこりますか。

4.  ルカ

    1.  「ともし火」のたとえで、「ともし火」「燭台」「秘められたもの」とは何でしょうか。イエスは何を教えようとしておられるのでしょうか。

### 参照

> 21 Καὶ ἔλεγεν αὐτοῖς· μήτι ἔρχεται ὁ λύχνος ἵνα ὑπὸ τὸν μόδιον τεθῇ ἢ ὑπὸ τὴν κλίνην; οὐχ ἵνα ἐπὶ τὴν λυχνίαν τεθῇ; 22 οὐ γάρ ἐστιν κρυπτὸν ἐὰν μὴ ἵνα φανερωθῇ, οὐδὲ ἐγένετο ἀπόκρυφον ἀλλ' ἵνα ἔλθῃ εἰς φανερόν. 23 εἴ τις ἔχει ὦτα ἀκούειν ἀκουέτω. 24 Καὶ ἔλεγεν αὐτοῖς· βλέπετε τί ἀκούετε. ἐν ᾧ μέτρῳ μετρεῖτε μετρηθήσεται ὑμῖν καὶ προστεθήσεται ὑμῖν. 25ὃς γὰρ ἔχει, δοθήσεται αὐτῷ· καὶ ὃς οὐκ ἔχει, καὶ ὃ ἔχει ἀρθήσεται ἀπ' αὐτοῦ.

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 4:26-29 「成長する種」のたとえ

> 4:26 また言われた、「神の国は、ある人が地に種をまくようなものである。27 夜昼、寝起きしている間に、種は芽を出して育って行くが、どうしてそうなるのか、その人は知らない。 28 地はおのずから実を結ばせるもので、初めに芽、つぎに穂、つぎに穂の中に豊かな実ができる。29 実がいると、すぐにかまを入れる。刈入れ時がきたからである」。

[マルコによる福音書4章26-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_26-34.pdf)

### 問い

1.  26--29節のたとえでイエスは私達に何を悟らせようとしていますか。

2.  このたとえは神の国の成長についてどんなことを教えていますか。

### 参照

> **26** Καὶ ἔλεγεν· οὕτως ἐστὶν ἡ βασιλεία τοῦ θεοῦ ὡς ἄνθρωπος βάλῃ τὸν σπόρον ἐπὶ τῆς γῆς **27** καὶ καθεύδῃ καὶ ἐγείρηται νύκτα καὶ ἡμέραν, καὶ ὁ σπόρος βλαστᾷ καὶ μηκύνηται ὡς οὐκ οἶδεν αὐτός. **28** αὐτομάτη ἡ γῆ καρποφορεῖ, πρῶτον χόρτον εἶτα στάχυν εἶτα πλήρη \[ς\] σῖτον ἐν τῷ στάχυϊ. **29** ὅταν δὲ παραδοῖ ὁ καρπός, εὐθὺς ἀποστέλλει τὸ δρέπανον, ὅτι παρέστηκεν ὁ θερισμός.

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 4:30-32 「からし種」のたとえ

> 4:30 また言われた、「神の国を何に比べようか。また、どんな譬で言いあらわそうか。31 それは一粒のからし種のようなものである。地にまかれる時には、地上のどんな種よりも小さいが、 32 まかれると、成長してどんな野菜よりも大きくなり、大きな枝を張り、その陰に空の鳥が宿るほどになる」。

### マタイ 13:31-32, 33

> 31 また、ほかの譬を彼らに示して言われた、「天国は、一粒のからし種のようなものである。ある人がそれをとって畑にまくと、32 それはどんな種よりも小さいが、成長すると、野菜の中でいちばん大きくなり、空の鳥がきて、その枝に宿るほどの木になる」。33 またほかの譬を彼らに語られた、「天国は、パン種のようなものである。女がそれを取って三斗の粉の中に混ぜると、全体がふくらんでくる」。 

### ルカ 13:18-19, 20-21

> 18 そこで言われた、「神の国は何に似ているか。またそれを何にたとえようか。19 一粒のからし種のようなものである。ある人がそれを取って庭にまくと、育って木となり、空の鳥もその枝に宿るようになる」。20 また言われた、「神の国を何にたとえようか。21 パン種のようなものである。女がそれを取って三斗の粉の中に混ぜると、全体がふくらんでくる」。 

### 問い

1.  30--32節のたとえでは神の国のどういう面について教えているのでしょうか。

2.  このたとえは個人の中にある神の国の成長について言っているとするとそれはどのようなことでしょうか。

3.  神の国がこの世界の中で成長していくことにはどう当てはまりますか。

4.  マタイ

    1.  「からし種」と「パン種」のたとえから、天の国についてどんなことが分かりますか。What can you tell about the kingdom of heaven by the parables of a mustard seed and yeast?

### 参照

> 30 Καὶ ἔλεγεν· πῶς ὁμοιώσωμεν τὴν βασιλείαν τοῦ θεοῦ ἢ ἐν τίνι αὐτὴν παραβολῇ θῶμεν; 31 ὡς κόκκῳ σινάπεως, ὃς ὅταν σπαρῇ ἐπὶ τῆς γῆς, μικρότερον ὂν πάντων τῶν σπερμάτων τῶν ἐπὶ τῆς γῆς, 32 καὶ ὅταν σπαρῇ, ἀναβαίνει καὶ γίνεται μεῖζον πάντων τῶν λαχάνων καὶ ποιεῖ κλάδους μεγάλους, ὥστε δύνασθαι ὑπὸ τὴν σκιὰν αὐτοῦ τὰ πετεινὰ τοῦ οὐρανοῦ κατασκηνοῦν.

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 4:33-34 たとえを用いて語る

> 4:33 イエスはこのような多くの譬で、人々の聞く力にしたがって、御言を語られた。34 譬によらないでは語られなかったが、自分の弟子たちには、ひそかにすべてのことを解き明かされた。

### マタイ 13:34-35

> 34 イエスはこれらのことをすべて、譬で群衆に語られた。譬によらないでは何事も彼らに語られなかった。35 これは預言者によって言われたことが、成就するためである、／「わたしは口を開いて譬を語り、／世の初めから隠されていることを語り出そう」。

### 問い

1.  34, 35節では、イエスがたとえで語る理由をどのように言っていますか。Why does Jesus tell in parables? (v 34, 35)

### 参照

> **33** Καὶ τοιαύταις παραβολαῖς πολλαῖς ἐλάλει αὐτοῖς τὸν λόγον καθὼς ἠδύναντο ἀκούειν· **34** χωρὶς δὲ παραβολῆς οὐκ ἐλάλει αὐτοῖς, κατ' ἰδίαν δὲ τοῖς ἰδίοις μαθηταῖς ἐπέλυεν πάντα.

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 4:35-41 突風を静める

> 4:35 さてその日、夕方になると、イエスは弟子たちに、「向こう岸へ渡ろう」と言われた。 36 そこで、彼らは群衆をあとに残し、イエスが舟に乗っておられるまま、乗り出した。ほかの舟も一緒に行った。 37 すると、激しい突風が起り、波が舟の中に打ち込んできて、舟に満ちそうになった。 38 ところが、イエス自身は、舳の方でまくらをして、眠っておられた。そこで、弟子たちはイエスをおこして、「先生、わたしどもがおぼれ死んでも、おかまいにならないのですか」と言った。39 イエスは起きあがって風をしかり、海にむかって、「静まれ、黙れ」と言われると、風はやんで、大なぎになった。 40 イエスは彼らに言われた、「なぜ、そんなにこわがるのか。どうして信仰がないのか」。41 彼らは恐れおののいて、互に言った、「いったい、この方はだれだろう。風も海も従わせるとは」。

### マタイ 8:23-27

> 23 それから、イエスが舟に乗り込まれると、弟子たちも従った。24 すると突然、海上に激しい暴風が起って、舟は波にのまれそうになった。ところが、イエスは眠っておられた。25 そこで弟子たちはみそばに寄ってきてイエスを起し、「主よ、お助けください、わたしたちは死にそうです」と言った。26 するとイエスは彼らに言われた、「なぜこわがるのか、信仰の薄い者たちよ」。それから起きあがって、風と海とをおしかりになると、大なぎになった。27 彼らは驚いて言った、「このかたはどういう人なのだろう。風も海も従わせるとは」。

### ルカ 8:22-25

> 22 ある日のこと、イエスは弟子たちと舟に乗り込み、「湖の向こう岸へ渡ろう」と言われたので、一同が船出した。23 渡って行く間に、イエスは眠ってしまわれた。すると突風が湖に吹きおろしてきたので、彼らは水をかぶって危険になった。24 そこで、みそばに寄ってきてイエスを起し、「先生、先生、わたしたちは死にそうです」と言った。イエスは起き上がって、風と荒浪とをおしかりになると、止んでなぎになった。25 イエスは彼らに言われた、「あなたがたの信仰は、どこにあるのか」。彼らは恐れ驚いて互に言い合った、「いったい、このかたはだれだろう。お命じになると、風も水も従うとは」。 

[マルコによる福音書4章35-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_35-41.pdf)

### 問い

1.  35節に「その日」とありますがこの日はどんな日だったでしょうか。

2.  彼らはいつ出発しますか。出かけようと言い出したのはだれですか。

3.  ガリラヤ湖は突然暴風が起こることで有名です。マルコはこの嵐の激しさをどのように述べて強調していますか。

4.  だれが船の舵を取っていると思いますか。

5.  弟子たちはなぜイエスを起こすのですか。弟子たちの気持ちになって考えてみましょう。

6.  イエスはどうされますか。

7.  弟子たちはこの事件からイエスについて何を感じ何を知ったでしょうか。

8.  マタイ

    1.  湖でどのようなことが起きますか。What happens on the lake?

    2.  人々はなにに驚いたのでしょうか。What surprises the people about these events?

### 参照

> 35 Καὶ λέγει αὐτοῖς ἐν ἐκείνῃ τῇ ἡμέρᾳ ὀψίας γενομένης· διέλθωμεν εἰς τὸ πέραν. 36 καὶ ἀφέντες τὸν ὄχλον παραλαμβάνουσιν αὐτὸν ὡς ἦν ἐν τῷ πλοίῳ, καὶ ἄλλα πλοῖα ἦν μετ' αὐτοῦ. 37 καὶ γίνεται λαῖλαψ μεγάλη ἀνέμου καὶ τὰ κύματα ἐπέβαλλεν εἰς τὸ πλοῖον, ὥστε ἤδη γεμίζεσθαι τὸ πλοῖον. 38 καὶ αὐτὸς ἦν ἐν τῇ πρύμνῃ ἐπὶ τὸ προσκεφάλαιον καθεύδων. καὶ ἐγείρουσιν αὐτὸν καὶ λέγουσιν αὐτῷ· διδάσκαλε, οὐ μέλει σοι ὅτι ἀπολλύμεθα; 39 καὶ διεγερθεὶς ἐπετίμησεν τῷ ἀνέμῳ καὶ εἶπεν τῇ θαλάσσῃ· σιώπα, πεφίμωσο. καὶ ἐκόπασεν ὁ ἄνεμος καὶ ἐγένετο γαλήνη μεγάλη. 40καὶ εἶπεν αὐτοῖς· τί δειλοί ἐστε; οὔπω ἔχετε πίστιν; 41 καὶ ἐφοβήθησαν φόβον μέγαν καὶ ἔλεγον πρὸς ἀλλήλους· τίς ἄρα οὗτός ἐστιν ὅτι καὶ ὁ ἄνεμος καὶ ἡ θάλασσα ὑπακούει αὐτῷ;

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 5:1-20 悪霊に取りつかれたゲラサの人を癒やす

> 1 こうして彼らは海の向こう岸、ゲラサ人の地に着いた。2 それから、イエスが舟からあがられるとすぐに、けがれた霊につかれた人が墓場から出てきて、イエスに出会った。3 この人は墓場をすみかとしており、もはやだれも、鎖でさえも彼をつなぎとめて置けなかった。4 彼はたびたび足かせや鎖でつながれたが、鎖を引きちぎり、足かせを砕くので、だれも彼を押えつけることができなかったからである。5 そして、夜昼たえまなく墓場や山で叫びつづけて、石で自分のからだを傷つけていた。6 ところが、この人がイエスを遠くから見て、走り寄って拝し、7 大声で叫んで言った、「いと高き神の子イエスよ、あなたはわたしとなんの係わりがあるのです。神に誓ってお願いします。どうぞ、わたしを苦しめないでください」。8それは、イエスが、「けがれた霊よ、この人から出て行け」と言われたからである。9 また彼に、「なんという名前か」と尋ねられると、「レギオンと言います。大ぜいなのですから」と答えた。10 そして、自分たちをこの土地から追い出さないようにと、しきりに願いつづけた。11 さて、そこの山の中腹に、豚の大群が飼ってあった。12 霊はイエスに願って言った、「わたしどもを、豚にはいらせてください。その中へ送ってください」。13 イエスがお許しになったので、けがれた霊どもは出て行って、豚の中へはいり込んだ。すると、その群れは二千匹ばかりであったが、がけから海へなだれを打って駆け下り、海の中でおぼれ死んでしまった。14 豚を飼う者たちが逃げ出して、町や村にふれまわったので、人々は何事が起ったのかと見にきた。15 そして、イエスのところにきて、悪霊につかれた人が着物を着て、正気になってすわっており、それがレギオンを宿していた者であるのを見て、恐れた。16 また、それを見た人たちは、悪霊につかれた人の身に起った事と豚のこととを、彼らに話して聞かせた。17 そこで、人々はイエスに、この地方から出て行っていただきたいと、頼みはじめた。18 イエスが舟に乗ろうとされると、悪霊につかれていた人がお供をしたいと願い出た。19 しかし、イエスはお許しにならないで、彼に言われた、「あなたの家族のもとに帰って、主がどんなに大きなことをしてくださったか、またどんなにあわれんでくださったか、それを知らせなさい」。20

### マタイ 8:28-34

> 28 それから、向こう岸、ガダラ人の地に着かれると、悪霊につかれたふたりの者が、墓場から出てきてイエスに出会った。彼らは手に負えない乱暴者で、だれもその辺の道を通ることができないほどであった。29 すると突然、彼らは叫んで言った、「神の子よ、あなたはわたしどもとなんの係わりがあるのです。まだその時ではないのに、ここにきて、わたしどもを苦しめるのですか」。30 さて、そこからはるか離れた所に、おびただしい豚の群れが飼ってあった。31 悪霊どもはイエスに願って言った、「もしわたしどもを追い出されるのなら、あの豚の群れの中につかわして下さい」。32 そこで、イエスが「行け」と言われると、彼らは出て行って、豚の中へはいり込んだ。すると、その群れ全体が、がけから海へなだれを打って駆け下り、水の中で死んでしまった。33 飼う者たちは逃げて町に行き、悪霊につかれた者たちのことなど、いっさいを知らせた。34 すると、町中の者がイエスに会いに出てきた。そして、イエスに会うと、この地方から去ってくださるようにと頼んだ。そこで、彼は立ち去り、そして自分にイエスがしてくださったことを、ことごとくデカポリスの地方に言いひろめ出したので、人々はみな驚き怪しんだ。

### ルカ 8:26-39

> 26 それから、彼らはガリラヤの対岸、ゲラサ人の地に渡った。27 陸にあがられると、その町の人で、悪霊につかれて長いあいだ着物も着ず、家に居つかないで墓場にばかりいた人に、出会われた。28 この人がイエスを見て叫び出し、みまえにひれ伏して大声で言った、「いと高き神の子イエスよ、あなたはわたしとなんの係わりがあるのです。お願いです、わたしを苦しめないでください」。29 それは、イエスが汚れた霊に、その人から出て行け、とお命じになったからである。というのは、悪霊が何度も彼をひき捕えたので、彼は鎖と足かせとでつながれて看視されていたが、それを断ち切っては悪霊によって荒野へ追いやられていたのである。30 イエスは彼に「なんという名前か」とお尋ねになると、「レギオンと言います」と答えた。彼の中にたくさんの悪霊がはいり込んでいたからである。31 悪霊どもは、底知れぬ所に落ちて行くことを自分たちにお命じにならぬようにと、イエスに願いつづけた。32 ところが、そこの山ベにおびただしい豚の群れが飼ってあったので、その豚の中へはいることを許していただきたいと、悪霊どもが願い出た。イエスはそれをお許しになった。33 そこで悪霊どもは、その人から出て豚の中へはいり込んだ。するとその群れは、がけから湖へなだれを打って駆け下り、おぼれ死んでしまった。34 飼う者たちは、この出来事を見て逃げ出して、町や村里にふれまわった。35 人々はこの出来事を見に出てきた。そして、イエスのところにきて、悪霊を追い出してもらった人が着物を着て、正気になってイエスの足もとにすわっているのを見て、恐れた。36 それを見た人たちは、この悪霊につかれていた者が救われた次第を、彼らに語り聞かせた。37 それから、ゲラサの地方の民衆はこぞって、自分たちの所から立ち去ってくださるようにとイエスに頼んだ。彼らが非常な恐怖に襲われていたからである。そこで、イエスは舟に乗って帰りかけられた。38 悪霊を追い出してもらった人は、お供をしたいと、しきりに願ったが、イエスはこう言って彼をお帰しになった。39 「家へ帰って、神があなたにどんなに大きなことをしてくださったか、語り聞かせなさい」。そこで彼は立ち去って、自分にイエスがして下さったことを、ことごとく町中に言いひろめた。

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 5:21-43 ヤイロの娘とイエスの服に触れる女

### マタイ 9:18-26

### ルカ 8:40-56

> 40 イエスが帰ってこられると、群衆は喜び迎えた。みんながイエスを待ちうけていたのである。41 するとそこに、ヤイロという名の人がきた。この人は会堂司であった。イエスの足もとにひれ伏して、自分の家においでくださるようにと、しきりに願った。42 彼に十二歳ばかりになるひとり娘があったが、死にかけていた。ところが、イエスが出て行かれる途中、群衆が押し迫ってきた。43 ここに、十二年間も長血をわずらっていて、医者のために自分の身代をみな使い果してしまったが、だれにもなおしてもらえなかった女がいた。44 この女がうしろから近寄ってみ衣のふさにさわったところ、その長血がたちまち止まってしまった。45 イエスは言われた、「わたしにさわったのは、だれか」。人々はみな自分ではないと言ったので、ペテロが「先生、群衆があなたを取り囲んで、ひしめき合っているのです」と答えた。46 しかしイエスは言われた、「だれかがわたしにさわった。力がわたしから出て行ったのを感じたのだ」。47 女は隠しきれないのを知って、震えながら進み出て、みまえにひれ伏し、イエスにさわった訳と、さわるとたちまちなおったこととを、みんなの前で話した。 48 そこでイエスが女に言われた、「娘よ、あなたの信仰があなたを救ったのです。安心して行きなさい」。49 イエスがまだ話しておられるうちに、会堂司の家から人がきて、「お嬢さんはなくなられました。この上、先生を煩わすには及びません」と言った。50 しかしイエスはこれを聞いて会堂司にむかって言われた、「恐れることはない。ただ信じなさい。娘は助かるのだ」。51 それから家にはいられるとき、ペテロ、ヨハネ、ヤコブおよびその子の父母のほかは、だれも一緒にはいって来ることをお許しにならなかった。52 人々はみな、娘のために泣き悲しんでいた。イエスは言われた、「泣くな、娘は死んだのではない。眠っているだけである」。53 人々は娘が死んだことを知っていたので、イエスをあざ笑った。54 イエスは娘の手を取って、呼びかけて言われた、「娘よ、起きなさい」。55 するとその霊がもどってきて、娘は即座に立ち上がった。イエスは何か食べ物を与えるように、さしずをされた。56 両親は驚いてしまった。イエスはこの出来事をだれにも話さないようにと、彼らに命じられた。 

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:1-6 ナザレで受け入れられない

### マタイ 13:53-58

### ルカ 4:16-30

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:7-13 十二人を派遣する

### マタイ 10:1; 5-15

### ルカ 9:1-6

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:14-29 洗礼者ヨハネ、殺される

### マタイ 14:1-12

### ルカ 9:7-9

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:30-44 五千人に食べ物を与える

### マタイ 14:13-21

### ルカ 9:10-17

### ヨハネ 6:1-14

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:45-52 湖の上を歩く

### マタイ 14:22-33

### ヨハネ 6:15-21

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 6:53-56 ゲネサレとで病人を癒やす

### マタイ 14:34-36

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 7:1-23 昔の人の言い伝え

### マタイ 15:1-20

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 7:24-30 シリア・フェニキアの女の信仰

### マタイ 15:21-28

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 7:31-37 耳が聞こえず舌の回らない人を癒やす

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:1-10 四千人に食べ物を与える

### マタイ 15:32-39

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:11-13 人々はしるしを欲しがる

### マタイ 16:1-4

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:14-21 ファリサイ派の人々とヘロデのパン種

### マタイ 16:5-12

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:22-26 ベトサイダで盲人を癒やす

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:27-30 ペトロ、イエスがメシアであると告白する

### マタイ 16:13-20

### ルカ 9:18-21

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 8:31-38; 9:1 イエス、死と復活を予告する

### マタイ 16:21-28

### ルカ 9:22-27

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:2-13 イエスの姿が変わる

### マタイ 17:1-13

### ルカ 9:28-36

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:14-29 汚れた霊に取りつかれた子を癒やす

### マタイ 17:14-20

### ルカ 9:37-43a

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:30-32 再び自分の死と復活を予告する

### マタイ 17:22-23

### ルカ 9:43b-45

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:33-37 いちばん偉い者

### マタイ 18:1-5

### ルカ 9:46-48

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:38-41 逆らわない者は味方

### ルカ 9:49-50

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 9:42-50 罪への誘惑

### マタイ 18:6-9

### ルカ 17:1-2

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:1-12 離婚について教える

### マタイ 19:1-12

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:13-16 子どもを祝福する

### マタイ 19:13-15

### ルカ 18:15-17

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:17-31 金持ちの男

### マタイ 19:16-30

### ルカ 18:18-30

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:32-34 イエス、三度自分の死と復活を予告する

### マタイ 20:17-19

### ルカ 18;31-34

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:35-45 ヤコブとヨハネの願い

### マタイ 20:20-28

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:46-52 盲人バルティマイを癒やす

### マタイ 20:29-34

### ルカ 18:35-43

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:1-11 エルサレムに迎えられる

### マタイ 21:1-11

### ルカ 19:28-40

### ヨハネ 12:12-19

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:12-14 いちじくの木を呪う

### マタイ 21:18-19

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:15-19 神殿から商人を追い出す

### マタイ 21:12-17

### ルカ 19:45-48

### ヨハネ 2:13-22

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:20-26 枯れたいちじくの木の教訓

### マタイ 21:20-22

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:27-33 権威についての問答

### マタイ 21:23-27

### ルカ 20:1-8

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:1-12 「ぶどう園の農夫」のたとえ

### マタイ 21:33-46

### ルカ 20:9-19

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:13-17 皇帝への税金

### マタイ 22:15-22

### ルカ 20:20-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:18-27 復活についての問答

### マタイ 22:23-33

### ルカ 20:27-40

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:28-34 最も重要な戒め

### マタイ 22:34-40

### ルカ 10:25-28

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:35-37 ダビデの子についての問答

### マタイ 22:41-45

### ルカ 20:41-44

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:38-40 律法学者を非難する

### マタイ 23:1-36

### ルカ 20:45-47

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:41-44 やもめの献金

### ルカ 21:1-4

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:1-2 神殿の崩壊を予告する

### マタイ 24:1-2

### ルカ 21:5-6

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:3-13 終末の徴

### マタイ 24:3-4

### ルカ 21:7-19

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:14-23 大きな苦難を予告する

### マタイ 24:15-28

### ルカ 21:20-24

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:24-27 人の子が来る

### マタイ 24:29-31

### ルカ 21:25-28

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:28-32 いちじくの木の教え

### マタイ 24:32-35

### ルカ 21:29-33

### ヨハネ

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:33-37 目を覚ましていなさい

### マタイ 24:36-44

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:1-2 イエスを殺す計略

### マタイ 26:1-5

### ルカ 22:1-2

### ヨハネ 11:45-53

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:3-9 ベタニアで香油を注がれる

### マタイ 26:6-13

### ヨハネ 12:1-8

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:10-11 ユダ、裏切りを企てる

### マタイ 26:14-16

### ルカ 22:3-6

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:12-21 過越の食事をする

### マタイ 26:17-25

### ルカ 22:7-14; 21-23

### ヨハネ 13:21-30

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:22-25 主の晩餐

### マタイ 26:26-30

### ルカ 22:15-20

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:26-31 ペトロの離反を予告する

### マタイ 26:31-35

### ルカ 22:31-34

### ヨハネ 13:36-38

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:32-42 ゲッセマネで祈る

### マタイ 26:36-46

### ルカ 22:39-46

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:43-50 裏切られ、逮捕される

### マタイ 26:47-56

### ルカ 22:47-53

### ヨハネ 18:3-12

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:51-52 一人の若者、逃げる

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:53-65 最高法院で裁判を受ける

### マタイ 26:57-68

### ルカ 22:54-55; 61-71

### ヨハネ 18:13-14; 19-24

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:66-72 ペトロ、イエスを知らないと言う

### マタイ 26:69-75

### ルカ 22:56-62

### ヨハネ 18:15-18; 25-27

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:1-5 ピラトから尋問される

### マタイ 27:1-2; 11-14

### ルカ 23:1-5

### ヨハネ 18:28-38

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:6-15 死刑の判決を受ける

### マタイ 27:15-26

### ルカ 23:13-25

### ヨハネ 18:39-19:16

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:16-20 兵士から侮辱される

### マタイ 27:27-31

### ヨハネ 19:2-2

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:21-32 十字架につけられる

### マタイ 27:32-44

### ルカ 23:26-43

### ヨハネ 19:17-27

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:33-41 イエスの死

### マタイ 27:45-56

### ルカ 23:44-49

### ヨハネ 19:28-30

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:42-47 墓に葬られる

### マタイ 27:57-61

### ルカ 23:50-56

### ヨハネ 19:38-42

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:1-8 復活する

### マタイ 28:1-8

### ルカ 24:1-12

### ヨハネ 20:1-10

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:9-11 （結び一）マグダラのマリアに現れる

### マタイ 28:9-10

### ヨハネ 20:11-18

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:12-13 二人の弟子に現れる

### ルカ 24:13-35

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:14-18 弟子たちを派遣する

### マタイ 28:16-20

### ルカ 24:36-49

### ヨハネ 20:19-23

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:19-20 天に上げられる

### ルカ 24:50-53

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ
