#  {#markdq}

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:13-16 子どもを祝福する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:17-31 金持ちの男

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:32-34 イエス、三度自分の死と復活を予告する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:35-45 ヤコブとヨハネの願い

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 10:46-52 盲人バルティマイを癒やす

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:1-11 エルサレムに迎えられる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:12-14 いちじくの木を呪う

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:15-19 神殿から商人を追い出す

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:20-26 枯れたいちじくの木の教訓

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 11:27-33 権威についての問答

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:1-12 「ぶどう園の農夫」のたとえ

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:13-17 皇帝への税金

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:18-27 復活についての問答

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:28-34 最も重要な戒め

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:35-37 ダビデの子についての問答

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:38-40 律法学者を非難する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 12:41-44 やもめの献金

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:1-2 神殿の崩壊を予告する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:3-13 終末の徴

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:14-23 大きな苦難を予告する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:24-27 人の子が来る

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:28-32 いちじくの木の教え

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 13:33-37 目を覚ましていなさい

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:1-2 イエスを殺す計略

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:3-9 ベタニアで香油を注がれる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:10-11 ユダ、裏切りを企てる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:12-21 過越の食事をする

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:22-25 主の晩餐

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:26-31 ペトロの離反を予告する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:32-42 ゲッセマネで祈る

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:43-50 裏切られ、逮捕される

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:51-52 一人の若者、逃げる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:53-65 最高法院で裁判を受ける

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 14:66-72 ペトロ、イエスを知らないと言う

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:1-5 ピラトから尋問される

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:6-15 死刑の判決を受ける

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:16-20 兵士から侮辱される

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:21-32 十字架につけられる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:33-41 イエスの死

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 15:42-47 墓に葬られる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:1-8 復活する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:9-11 （結び一）マグダラのマリアに現れる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:12-13 二人の弟子に現れる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

##  16:14-18 弟子たちを派遣する

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ

## 16:19-20 天に上げられる

### マタイ 9:1-8

### ルカ 5:17-26

### 問い

### 参照

### 記録

-   日時：2023年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### メモ
