# マルコ（2003-2005） {#markdq-old}

それぞれの箇所の聖書は（日本聖書協会）口語訳、引用は共同訳が多いと思います。

## マルコによる福音書を学んで行くにあたって  {.unnumbered}

マルコによる福音書は、一般的に福音書の中で最も古いと言われている。マルコと呼ばれるヨハネは聖書の中で8回出てくる。使徒12:12, 12:25, 15:37, 15:39, コロサイ4:10, 2テモテ4:11, ピレモン24, 1ペテロ5:13。

-   テキストから何が分かるかを中心に学びましょう。

-   共観福音書 (synoptic) [^markdq-old-1]の他の箇所は時に応じて参考にしていきましょう。

-   著者が何を伝えたいと思っているかを中心に学びましょう。

[^markdq-old-1]: マタイ、マルコ、ルカの三つの福音書のこと。この三巻は同じできごとについて扱っている部分（並行記事）が多く、「共通の観点を持つ福音書」としてこう呼ばれます。

## マルコによる福音書　第1章

### 1節-8節

> 1:1 神の子イエス・キリストの福音のはじめ。 2 預言者イザヤの書に、／「見よ、わたしは使をあなたの先につかわし、／あなたの道を整えさせるであろう。3 荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と書いてあるように、4 バプテスマのヨハネが荒野に現れて、罪のゆるしを得させる悔改めのバプテスマを宣べ伝えていた。 5 そこで、ユダヤ全土とエルサレムの全住民とが、彼のもとにぞくぞくと出て行って、自分の罪を告白し、ヨルダン川でヨハネからバプテスマを受けた。 6 このヨハネは、らくだの毛ごろもを身にまとい、腰に皮の帯をしめ、いなごと野蜜とを食物としていた。7 彼は宣べ伝えて言った、「わたしよりも力のあるかたが、あとからおいでになる。わたしはかがんで、そのくつのひもを解く値うちもない。 8 わたしは水でバプテスマを授けたが、このかたは、聖霊によってバプテスマをお授けになるであろう」。

-   マルコによる福音書はどのような言葉で始まりますか。

    -   「神の子イエス・キリストの福音の初め。」

        福音＝Good News= Gospel= ユーアンゲリオン = evangelism

        イエス: Joshua = Yahaweh is salvation

        キリスト：メシヤ = 油注がれたもの（旧約では王、祭司、預言者など特別な使命に任命されるものに注がれた。）

-   2,3 節では「使（つかい）」について何といっていますか。使命・働く場所・メッセージ。

    -   マラキ3:1　見よ、わたしは使者を送る。彼はわが前に道を備える。あなたたちが待望している主は／突如、その聖所に来られる。あなたたちが喜びとしている契約の使者／見よ、彼が来る、と万軍の主は言われる。

    -   \[DQ\] 旧約聖書におけるバプテスマのヨハネの役割・仕事は？

    -   イザヤ40:3　呼びかける声がある。主のために、荒れ野に道を備え／わたしたちの神のために、荒れ地に広い道を通せ。

-   ヨハネはどんな人ですか。どんな働きをしますか。

    -   \[DQ\] バプテスマのヨハネは何をし何を語ったか。

-   バプテスマのヨハネは、「使」について上で考えた旧約聖書の予言をどのように成し遂げていますか。

-   ヨハネの働きは、メシヤを迎えるために人々の心をどのように整えるのでしょうか。悔い改めることは、救い主を迎えるのにどう整えるのでしょうか。やがて来る方とどのような違いがありますか。

### 9節-15節

> 1:9 そのころ、イエスはガリラヤのナザレから出てきて、ヨルダン川で、ヨハネからバプテスマをお受けになった。10 そして、水の中から上がられるとすぐ、天が裂けて、聖霊がはとのように自分に下って来るのを、ごらんになった。 11 すると天から声があった、「あなたはわたしの愛する子、わたしの心にかなう者である」。12 それからすぐに、御霊がイエスを荒野に追いやった。 13 イエスは四十日のあいだ荒野にいて、サタンの試みにあわれた。そして獣もそこにいたが、御使たちはイエスに仕えていた。14 ヨハネが捕えられた後、イエスはガリラヤに行き、神の福音を宣べ伝えて言われた、15 「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」。

-   そのころとはどういう時のことですか。地図で、ナザレ、エルサレムと、ヨルダン川を確認（探）しましょう。

    -   ルカ3:1-2 1:皇帝ティベリウスの治世の第十五年、ポンティオ・ピラトがユダヤの総督、ヘロデがガリラヤの領主、その兄弟フィリポがイトラヤとトラコン地方の領主、リサニアがアビレネの領主、2:アンナスとカイアファとが大祭司であったとき、神の言葉が荒れ野でザカリアの子ヨハネに降った。

-   イエスのバプテスマの時どんな事がおきましたが。何を表しているのでしょう。

-   マルコは、このときの誘惑についてどんなことを強調していますか。

    -   \[DQ\] イエスはなぜサタンの試みにあわれたのだろうか。

-   イエスはどこで宣教を始めますか。

    -   \[DQ\] イエスの宣教では何が語られたか。

-   イエスの 15節の教えと、4,7,8節のバプテスマのヨハネの教えとを比べてみましょう。どんな相違点と類似点がありますか。

### 16節-20節

> 1:16 さて、イエスはガリラヤの海べを歩いて行かれ、シモンとシモンの兄弟アンデレとが、海で網を打っているのをごらんになった。彼らは漁師であった。17 イエスは彼らに言われた、「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」。 18 すると、彼らはすぐに網を捨てて、イエスに従った。 19 また少し進んで行かれると、ゼベダイの子ヤコブとその兄弟ヨハネとが、舟の中で網を繕っているのをごらんになった。 20 そこで、すぐ彼らをお招きになると、父ゼベダイを雇人たちと一緒に舟において、イエスのあとについて行った。

-   最初の弟子たちはどんな人たちでしたか。

    -   \[DQ\] イエスの弟子の特徴をあげよ。

-   イエスに声をかけられたときこの人たちはそれぞれ何をしていましたか。

-   この人たちは、何をするために招かれていますか。

-   この人たちはどのように反応しますか。

### 21節-28節

> 1:21 それから、彼らはカペナウムに行った。そして安息日にすぐ、イエスは会堂にはいって教えられた。22 人々は、その教に驚いた。律法学者たちのようにではなく、権威ある者のように、教えられたからである。 23 ちょうどその時、けがれた霊につかれた者が会堂にいて、叫んで言った、24 「ナザレのイエスよ、あなたはわたしたちとなんの係わりがあるのです。わたしたちを滅ぼしにこられたのですか。あなたがどなたであるか、わかっています。神の聖者です」。 25 イエスはこれをしかって、「黙れ、この人から出て行け」と言われた。26 すると、けがれた霊は彼をひきつけさせ、大声をあげて、その人から出て行った。 27 人々はみな驚きのあまり、互に論じて言った、「これは、いったい何事か。権威ある新しい教だ。けがれた霊にさえ命じられると、彼らは従うのだ」。 28 こうしてイエスのうわさは、たちまちガリラヤの全地方、いたる所にひろまった。 

-   イエスの教えに対する人々の反応はどうでしたか。

    -   何に、なぜ人々は驚いたのでしょうか。

    -   律法学者はどのように教えていたのでしょうか。

-   汚れた霊につかれた者は何を叫んでいますか。イエスは、これに対し、なんと言っていますか。

-   27節に、人々の2回目の驚きが記されていますが、ここでは特に何に驚いたのでしょうか。

    -   \[DQ\] 権威あるもののように教えるとはどういうことでしょうか。

    -   \[DQ\] 奇跡はなぜ行なわれたのでしょうか。

### 29節-34節

> 1:29 それから会堂を出るとすぐ、ヤコブとヨハネとを連れて、シモンとアンデレとの家にはいって行かれた。 30 ところが、シモンのしゅうとめが熱病で床についていたので、人々はさっそく、そのことをイエスに知らせた。31 イエスは近寄り、その手をとって起されると、熱が引き、女は彼らをもてなした。 32 夕暮になり日が沈むと、人々は病人や悪霊につかれた者をみな、イエスのところに連れてきた。 33 こうして、町中の者が戸口に集まった。 34 イエスは、さまざまの病をわずらっている多くの人々をいやし、また多くの悪霊を追い出された。また、悪霊どもに、物言うことをお許しにならなかった。彼らがイエスを知っていたからである。

-   シモンとアンデレの家ではどんな問題がありましたか。そして、人々は何をしますか。

-   姑の回復の様子はどのように記されていますか。

-   なぜ、日没後病人たちをつれてきたのでしょうか。（この日はどんな日でしたか。）

-   イエスは何をしますか。

-   25節と同じようにここでもなぜイエスは悪霊を黙らせるのでしょうか。

### 35節-39節

> 1:35 朝はやく、夜の明けるよほど前に、イエスは起きて寂しい所へ出て行き、そこで祈っておられた。 26 すると、シモンとその仲間とが、あとを追ってきた。37 そしてイエスを見つけて、「みんなが、あなたを捜しています」と言った。 38 イエスは彼らに言われた、「ほかの、附近の町々にみんなで行って、そこでも教を宣べ伝えよう。わたしはこのために出てきたのだから」。  39 そして、ガリラヤ全地を巡りあるいて、諸会堂で教えを宣べ伝え、また悪霊を追い出された。

-   安息日の出来事を思い起こしながら次のことを考えてみましょう。

    -   どこで祈っていますか。

    -   なぜ祈るのでしょうか。

    -   \[DQ\] イエスのいのりについて何がわかりますか。

-   人々はイエスにどんな事を求めて探しているのでしょう。

-   イエスは教えといやしの働きのどちらに重点を置いていますか。イエスにとってこの二つにはどんなつながりがあるのでしょうか。

### 40節-45節

> 1:40 ひとりの重い皮膚病にかかった人が、イエスのところに願いにきて、ひざまずいて言った、「みこころでしたら、きよめていただけるのですが」。41 イエスは深くあわれみ、手を伸ばして彼にさわり、「そうしてあげよう、きよくなれ」と言われた。42 すると、重い皮膚病が直ちに去って、その人はきよくなった。 43 イエスは彼をきびしく戒めて、すぐにそこを去らせ、こう言い聞かせられた、 44 「何も人に話さないように、注意しなさい。ただ行って、自分のからだを祭司に見せ、それから、モーセが命じた物をあなたのきよめのためにささげて、人々に証明しなさい」。  45 しかし、彼は出て行って、自分の身に起ったことを盛んに語り、また言いひろめはじめたので、イエスはもはや表立っては町に、はいることができなくなり、外の寂しい所にとどまっておられた。しかし、人々は方々から、イエスのところにぞくぞくと集まってきた。

-   40節のらい病人の言葉にはどんな気持ちが表れていますか。

-   イエスはどう対応しますか。

-   イエスはらい病人にどんな事を命令しますか。

    -   \[DQ\] イエスはなぜ語らないように注意したのでしょうか。

-   なぜ、らい病人はイエスの命令に背くのでしょうか。そしてどうなりますか。

### 1章まとめ

-   マルコは、「神の子イエスキリストの福音のはじめ」としてこの福音書を書きだし、私達は、いま第一章の終わりまで学んできましたが、この一章にはイエスがどんな方だと書かれていたでしょうか。貴方はどんな印象を受けましたか。

## マルコによる福音書　第2章

### 1節-12節

> 2:1 幾日かたって、イエスがまたカペナウムにお帰りになったとき、家におられるといううわさが立ったので、 2 多くの人々が集まってきて、もはや戸口のあたりまでも、すきまが無いほどになった。そして、イエスは御言を彼らに語っておられた。3 すると、人々がひとりの中風の者を四人の人に運ばせて、イエスのところに連れてきた。 4 ところが、群衆のために近寄ることができないので、イエスのおられるあたりの屋根をはぎ、穴をあけて、中風の者を寝かせたまま、床をつりおろした。 5 イエスは彼らの信仰を見て、中風の者に、「子よ、あなたの罪はゆるされた」と言われた。 6 ところが、そこに幾人かの律法学者がすわっていて、心の中で論じた、7 「この人は、なぜあんなことを言うのか。それは神をけがすことだ。神ひとりのほかに、だれが罪をゆるすことができるか」。 8 イエスは、彼らが内心このように論じているのを、自分の心ですぐ見ぬいて、「なぜ、あなたがたは心の中でそんなことを論じているのか。 9 中風の者に、あなたの罪はゆるされた、と言うのと、起きよ、床を取りあげて歩け、と言うのと、どちらがたやすいか。 10 しかし、人の子は地上で罪をゆるす権威をもっていることが、あなたがたにわかるために」と彼らに言い、中風の者にむかって、11 「あなたに命じる。起きよ、床を取りあげて家に帰れ」と言われた。 12 すると彼は起きあがり、すぐに床を取りあげて、みんなの前を出て行ったので、一同は大いに驚き、神をあがめて、「こんな事は、まだ一度も見たことがない」と言った。

-   イエスはカペナウムに戻ってきますが、以前カペナウムではどんなことをしたでしょうか。

-   イエスはみことばを話しておられましたが、どんなことで、どのように中断されますか。その状況を想像してみましょう。

-   イエスはそれにどう対応しますか。4人の人と、その人たちに担がれてきた人の気持ちもあわせて考えてみましょう。

-   律法学者は、どう反応しますか。なぜ、そんな反応をするのでしょうか。

-   イエスは、どんなことを気付かせるために9節の質問をしていますか。

    -   \[DQ\] 中風の人に「あたなの罪はゆるされた」というのと、「起きて寝床をたたんで歩け」というのとどちらがあなたはやさしいと思いますか。律法学者はどう思っていたでしょう。イエスはどう思っていたでしょう。

-   中風の人はどのようにして信仰を表明しますか。

-   イエスはなぜ、5節の様な対応のされ方をしたのでしょうか。

    -   この当時、病気、特に不治のやまいは罪のゆえの神の怒りが原因だと思われていました。

-   このいやしに対して、どのような反応がおこりますか。

### 13節-17節

> 2:13 イエスはまた海べに出て行かれると、多くの人々がみもとに集まってきたので、彼らを教えられた。 14 また途中で、アルパヨの子レビが収税所にすわっているのをごらんになって、「わたしに従ってきなさい」と言われた。すると彼は立ちあがって、イエスに従った。15 それから彼の家で、食事の席についておられたときのことである。多くの取税人や罪人たちも、イエスや弟子たちと共にその席に着いていた。こんな人たちが大ぜいいて、イエスに従ってきたのである。 16 パリサイ派の律法学者たちは、イエスが罪人や取税人たちと食事を共にしておられるのを見て、弟子たちに言った、「なぜ、彼は取税人や罪人などと食事を共にするのか」。17 イエスはこれを聞いて言われた、「丈夫な人には医者はいらない。いるのは病人である。わたしがきたのは、義人を招くためではなく、罪人を招くためである」。

-   ここでイエスの弟子として4人の漁師にどんな人が加えられますか。

-   どんな人たちがこの人の家の食卓についていますか。

-   誰が誰に向かってどんな苦情を言っていますか。

-   イエスはこれに対して何と言っていますか。

### 18節-22節

> 2:18 ヨハネの弟子とパリサイ人とは、断食をしていた。そこで人々がきて、イエスに言った、「ヨハネの弟子たちとパリサイ人の弟子たちとが断食をしているのに、あなたの弟子たちは、なぜ断食をしないのですか」。19 するとイエスは言われた、「婚礼の客は、花婿が一緒にいるのに、断食ができるであろうか。花婿と一緒にいる間は、断食はできない。 20 しかし、花婿が奪い去られる日が来る。その日には断食をするであろう。 21 だれも、真新しい布ぎれを、古い着物に縫いつけはしない。もしそうすれば、新しいつぎは古い着物を引き破り、そして、破れがもっとひどくなる。22 まただれも、新しいぶどう酒を古い皮袋に入れはしない。もしそうすれば、ぶどう酒は皮袋をはり裂き、そして、ぶどう酒も皮袋もむだになってしまう。〔だから、新しいぶどう酒は新しい皮袋に入れるべきである〕」。

-   断食についての質問にイエスは何と答えていますか。

-   パリサイ人たちやヨハネの弟子たちの断食についての考えとどう言うところが違っていたと思いますか。

-   21節、22節の 2つのたとえは、何を言おうとしていますか。断食についての問答とあわせて考えてみましょう。

    -   イエスはどういう時には断食をせず、どういう時には断食をすると言っていますか。

    -   花婿とはだれのことだと思いますか。花婿が取り去られる時とはいつのことでしょうか。

### 23節-28節

> 2:23 ある安息日に、イエスは麦畑の中をとおって行かれた。そのとき弟子たちが、歩きながら穂をつみはじめた。 24 すると、パリサイ人たちがイエスに言った、「いったい、彼らはなぜ、安息日にしてはならぬことをするのですか」。25 そこで彼らに言われた、「あなたがたは、ダビデとその供の者たちとが食物がなくて飢えたとき、ダビデが何をしたか、まだ読んだことがないのか。26 すなわち、大祭司アビアタルの時、神の家にはいって、祭司たちのほか食べてはならぬ供えのパンを、自分も食べ、また供の者たちにも与えたではないか」。27 また彼らに言われた、「安息日は人のためにあるもので、人が安息日のためにあるのではない。 28 それだから、人の子は、安息日にもまた主なのである」。

-   イエスは安息日の目的をどのように説明していますか。

-   イエスは麦畑の出来事について何を言おうとしているのでしょうか。

### 2章まとめ

-   イエスに対する反対が次第に強まっています（3章6節）。どのような人がどのような理由でイエスを批判しているのでしょうか。

-   イエスにであって弟子となったり、いやされたりした人と、反対者とは何が違うのでしょうか。

## マルコによる福音書　第3章

### 1節-6節

> 3:1 イエスがまた会堂にはいられると、そこに片手のなえた人がいた。 2 人々はイエスを訴えようと思って、安息日にその人をいやされるかどうかをうかがっていた。 3 すると、イエスは片手のなえたその人に、「立って、中へ出てきなさい」と言い、 4 人々にむかって、「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」と言われた。彼らは黙っていた。5 イエスは怒りを含んで彼らを見まわし、その心のかたくななのを嘆いて、その人に「手を伸ばしなさい」と言われた。そこで手を伸ばすと、その手は元どおりになった。 6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。

-   この出来事はどんな状況の中でおこりますか。

-   イエスは片手の萎えた人を真ん中に立たせなんと言っていますか。

-   「人々」は安息日をどんな日だと思っていたのでしょうか。

-   なぜイエスは怒り嘆くのでしょうか。

-   この出来事の結果どんなことがおこりますか。

-   もう一度4節を読んでイエスがこの言葉をどのように行動によって示したか考えてみましょう。

-   あなたにとって安息日とはどういう者でしょうか。

### 7節-12節

> 3:7 それから、イエスは弟子たちと共に海べに退かれたが、ガリラヤからきたおびただしい群衆がついて行った。またユダヤから、8 エルサレムから、イドマヤから、更にヨルダンの向こうから、ツロ、シドンのあたりからも、おびただしい群衆が、そのなさっていることを聞いて、みもとにきた。9 イエスは群衆が自分に押し迫るのを避けるために、小舟を用意しておけと、弟子たちに命じられた。 10 それは、多くの人をいやされたので、病苦に悩む者は皆イエスにさわろうとして、押し寄せてきたからである。 11 また、けがれた霊どもはイエスを見るごとに、みまえにひれ伏し、叫んで、「あなたこそ神の子です」と言った。 12 イエスは御自身のことを人にあらわさないようにと、彼らをきびしく戒められた。

-   大勢の人たちがイエスのもとに集まってきたとありますが、地図で調べてみましょう。1章28節からどんな進展が見られますか。

-   なぜそんな大勢の人がイエスに魅力を感じているのでしょうか。

-   11, 12節での汚れた霊に対処するイエスと1章23節-26節での対処について類似点をあげてみましょう。

-   なぜイエスは、汚れた霊に宣伝されたくないのでしょう。

### 13節-19節

> 3:13 さてイエスは山に登り、みこころにかなった者たちを呼び寄せられたので、彼らはみもとにきた。14 そこで十二人をお立てになった。彼らを自分のそばに置くためであり、さらに宣教につかわし、15 また悪霊を追い出す権威を持たせるためであった。 16 こうして、この十二人をお立てになった。そしてシモンにペテロという名をつけ、 17 またゼベダイの子ヤコブと、ヤコブの兄弟ヨハネ、彼らにはボアネルゲ、すなわち、雷の子という名をつけられた。18 つぎにアンデレ、ピリポ、バルトロマイ、マタイ、トマス、アルパヨの子ヤコブ、タダイ、熱心党のシモン、19 それからイスカリオテのユダ。このユダがイエスを裏切ったのである。イエスが家にはいられると、

-   12弟子が任命されたのはどんな目的のためでしょうか。

-   イエスはどんな人たちにどんなニックネームをつけていますか。

-   弟子たちのリストについて気付いたことをあげてみましょう。

### 20節-30節

> 3:20 群衆がまた集まってきたので、一同は食事をする暇もないほどであった。21 身内の者たちはこの事を聞いて、イエスを取押えに出てきた。気が狂ったと思ったからである。 22 また、エルサレムから下ってきた律法学者たちも、「彼はベルゼブルにとりつかれている」と言い、「悪霊どものかしらによって、悪霊どもを追い出しているのだ」とも言った。 23 そこでイエスは彼らを呼び寄せ、譬をもって言われた、「どうして、サタンがサタンを追い出すことができようか。 24 もし国が内部で分れ争うなら、その国は立ち行かない。 25 また、もし家が内わで分れ争うなら、その家は立ち行かないであろう。 26 もしサタンが内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。 27 だれでも、まず強い人を縛りあげなければ、その人の家に押し入って家財を奪い取ることはできない。縛ってからはじめて、その家を略奪することができる。28 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。 29 しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。 30 そう言われたのは、彼らが「イエスはけがれた霊につかれている」と言っていたからである。

-   エルサレムから下ってきた律法学者たちはどのようにイエスを批判していますか。

-   もしイエスが悪霊の頭の力によって悪霊を追い出しているとするとどんな矛盾が起こるとイエスは言っていますか。

-   27節のたとえはそれぞれ何をたとえているのでしょうか。

-   聖霊を汚す罪とはどんな罪でしょうか。30節も含めて考えてみましょう。

### 31節-35節

> 3:31 さて、イエスの母と兄弟たちとがきて、外に立ち、人をやってイエスを呼ばせた。 32 ときに、群衆はイエスを囲んですわっていたが、「ごらんなさい。あなたの母上と兄弟、姉妹たちが、外であなたを尋ねておられます」と言った。 33 すると、イエスは彼らに答えて言われた、「わたしの母、わたしの兄弟とは、だれのことか」。 34 そして、自分をとりかこんで、すわっている人々を見まわして、言われた、「ごらんなさい、ここにわたしの母、わたしの兄弟がいる。35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。

-   この段落の状況を描写してみましょう。20節の様子も一緒に考えてみましょう。

-   イエスの母や兄弟姉妹はイエスのことをどう思っていたのでしょうか。21節も含めて考えてみましょう。

-   イエスは自分の家族はどんな人たちの事だと言っていますか。

## マルコによる福音書　第4章

### 1節-20節

> 4:1 イエスはまたも、海べで教えはじめられた。おびただしい群衆がみもとに集まったので、イエスは舟に乗ってすわったまま、海上におられ、群衆はみな海に沿って陸地にいた。2 イエスは譬で多くの事を教えられたが、その教の中で彼らにこう言われた、 3 「聞きなさい、種まきが種をまきに出て行った。4 まいているうちに、道ばたに落ちた種があった。すると、鳥がきて食べてしまった。 5 ほかの種は土の薄い石地に落ちた。そこは土が深くないので、すぐ芽を出したが、6 日が上ると焼けて、根がないために枯れてしまった。 7 ほかの種はいばらの中に落ちた。すると、いばらが伸びて、ふさいでしまったので、実を結ばなかった。 8 ほかの種は良い地に落ちた。そしてはえて、育って、ますます実を結び、三十倍、六十倍、百倍にもなった」。9 そして言われた、「聞く耳のある者は聞くがよい」。10 イエスがひとりになられた時、そばにいた者たちが、十二弟子と共に、これらの譬について尋ねた。11 そこでイエスは言われた、「あなたがたには神の国の奥義が授けられているが、ほかの者たちには、すべてが譬で語られる。 12 それは／『彼らは見るには見るが、認めず、／聞くには聞くが、悟らず、／悔い改めてゆるされることがない』／ためである」。13 また彼らに言われた、「あなたがたはこの譬がわからないのか。それでは、どうしてすべての譬がわかるだろうか。14 種まきは御言をまくのである。15 道ばたに御言がまかれたとは、こういう人たちのことである。すなわち、御言を聞くと、すぐにサタンがきて、彼らの中にまかれた御言を、奪って行くのである。16 同じように、石地にまかれたものとは、こういう人たちのことである。御言を聞くと、すぐに喜んで受けるが、 17 自分の中に根がないので、しばらく続くだけである。そののち、御言のために困難や迫害が起ってくると、すぐつまずいてしまう。18 また、いばらの中にまかれたものとは、こういう人たちのことである。御言を聞くが、19 世の心づかいと、富の惑わしと、その他いろいろな欲とがはいってきて、御言をふさぐので、実を結ばなくなる。20 また、良い地にまかれたものとは、こういう人たちのことである。御言を聞いて受けいれ、三十倍、六十倍、百倍の実を結ぶのである」。

-   イエスはどんな場所でどんな人たちにどんな方法で教えていますか。

-   3節から8節のたとえの中でまかれた種は落ちた場所によりそれぞれどうなったと書いてありますか。

-   10節からのところでこの解説を受けているのはだれですか。なぜ解説を聞くことが出来るのでしょうか。

-   ここに現れる4種類の人に共通の事は何ですか。

-   ここに現れる4種類の人はそれぞれどんな人ですか。

-   それぞれ何が違うのでしょうか。

-   4種類の土地、み言葉を聞いたそれぞれの人たちの受け取り方はそれぞれ私達のどのような受け取り方を意味しているでしょうか。

-   イエスはこのたとえと、ときあかしを通して私達に一番何を語りたかったのでしょうか。

### 21節-34節

> 4:21 また彼らに言われた、「ますの下や寝台の下に置くために、あかりを持ってくることがあろうか。燭台の上に置くためではないか。22 なんでも、隠されているもので、現れないものはなく、秘密にされているもので、明るみに出ないものはない。23 聞く耳のある者は聞くがよい」。 24 また彼らに言われた、「聞くことがらに注意しなさい。あなたがたの量るそのはかりで、自分にも量り与えられ、その上になお増し加えられるであろう。25 だれでも、持っている人は更に与えられ、持っていない人は、持っているものまでも取り上げられるであろう」。26 また言われた、「神の国は、ある人が地に種をまくようなものである。27 夜昼、寝起きしている間に、種は芽を出して育って行くが、どうしてそうなるのか、その人は知らない。 28 地はおのずから実を結ばせるもので、初めに芽、つぎに穂、つぎに穂の中に豊かな実ができる。29 実がいると、すぐにかまを入れる。刈入れ時がきたからである」。30 また言われた、「神の国を何に比べようか。また、どんな譬で言いあらわそうか。31 それは一粒のからし種のようなものである。地にまかれる時には、地上のどんな種よりも小さいが、 32 まかれると、成長してどんな野菜よりも大きくなり、大きな枝を張り、その陰に空の鳥が宿るほどになる」。33 イエスはこのような多くの譬で、人々の聞く力にしたがって、御言を語られた。34 譬によらないでは語られなかったが、自分の弟子たちには、ひそかにすべてのことを解き明かされた。

-   21, 22節がたとえについて語っているとすると、イエスは何と言っているのでしょうか。

-   24, 25節でイエスは神の言葉に注意して耳を傾けることの重要性をどのように強調していますか。

-   わたしたちが神の言葉に注意しなくなるとどんなことがおこりますか。

-   26--29節のたとえでイエスは私達に何を悟らせようとしていますか。

-   このたとえは神の国の成長についてどんなことを教えていますか。

-   30--32節のたとえでは神の国のどういう面について教えているのでしょうか。

-   このたとえは個人の中にある神の国の成長について言っているとするとそれはどのようなことでしょうか。

-   神の国がこの世界の中で成長していくことにはどう当てはまりますか。

### 35節-41節

> 4:35 さてその日、夕方になると、イエスは弟子たちに、「向こう岸へ渡ろう」と言われた。 36 そこで、彼らは群衆をあとに残し、イエスが舟に乗っておられるまま、乗り出した。ほかの舟も一緒に行った。 37 すると、激しい突風が起り、波が舟の中に打ち込んできて、舟に満ちそうになった。 38 ところが、イエス自身は、舳の方でまくらをして、眠っておられた。そこで、弟子たちはイエスをおこして、「先生、わたしどもがおぼれ死んでも、おかまいにならないのですか」と言った。39 イエスは起きあがって風をしかり、海にむかって、「静まれ、黙れ」と言われると、風はやんで、大なぎになった。 40 イエスは彼らに言われた、「なぜ、そんなにこわがるのか。どうして信仰がないのか」。41 彼らは恐れおののいて、互に言った、「いったい、この方はだれだろう。風も海も従わせるとは」。

-   35節に「その日」とありますがこの日はどんな日だったでしょうか。

-   彼らはいつ出発しますか。出かけようと言い出したのはだれですか。

-   ガリラヤ湖は突然暴風が起こることで有名です。マルコはこの嵐の激しさをどのように述べて強調していますか。

-   だれが船の舵を取っていると思いますか。

-   弟子たちはなぜイエスを起こすのですか。弟子たちの気持ちになって考えてみましょう。

-   イエスはどうされますか。

-   弟子たちはこの事件からイエスについて何を感じ何を知ったでしょうか。

## マルコによる福音書　第5章

### 1節-20節

-   3節-5節からこの人の状態についてどんなことが分かりますか。その地方の人々はこの人のことをどんなふうに思っているでしょうか。

-   8節のイエスの言葉から判断して7節で話しているのは誰でしょう。なんと言っていますか。

-   8節-13節で汚れた霊について新しくどんなことが分かりますか。

-   悪霊につかれた人にどんな変化が起こりますか。

-   15節-17節で、人々はどんな反応をしますか。それはなぜでしょうか。

-   悪霊にとりつかれていた人は何を望みますか。

-   イエスはこの人にどんな使命を与えていますか。

-   そしてこの人はどうしますか。

### 21節-43節

-   ヤイロはどんな人ですか。また、イエスに何を願っていますか。

-   24節以降の事件はどんな状況のもとでおきましたか。

-   この女の人についてわかることを上げてみましょう。またイエスをどのように考えていたのでしょうか。

-   この女の人はなぜヤイロのように公然と願わなかったのでしょう。

-   どんなことがおこりますか。またイエスはどのように対応しますか。

-   この女の人はなぜ恐れおののくのでしょう。

-   イエスはこの女の人に何と言っていますか。

-   ヤイロは、イエスが女の人と話している時、また使いが来た時、何を感じ、また思っていたでしょうか。

-   36節のことばでイエスはヤイロに何を求めていますか。

-   ヤイロの家はどんな状況でしたか。

-   どんなことがおきますか。

-   なぜイエスは少数の人しか立ちあわせなかったのでしょう。

-   あなたはこの二つの事件を通して、イエスについてどんなことを学びましたか。

## マルコによる福音書　第6章

### 1節-6節

-   このできごとの起きた場所、登場人物、その反応をまとめてみましょう。

-   町の人々の態度は何に基づいていますか。

-   なぜイエスは力あるわざをすることができなかったのでしょう。

    -   クリスチャンを通して聖書で語られていることの評価をすることの良い点と問題点について話してみましょう。

    -   \[DQ\] 街の人々はイエスのことをどのように考えていましたか。

### 7節-13節

-   イエスは弟子たちにどのような権威を与え、どのような命令（指導）をしていますか。

-   ひとつひとつの命令について、どのような意味があるのか考えてみましょう。

-   弟子たちは使わされた先でどんな働きをしましたか。

### 14節-29節

-   イエスのことを一般の人々はどのように考えていましたか。
    -   \[DQ\] 4:41 では弟子たちもイエスはだれかを疑問としていた。
-   ヘロデはイエスをどう思っていましたか。
-   ヘロデはなぜバプテスマのヨハネをとらえ殺してしまったのでしょうか。
    -   \[DQ\] ヘロデは殺すことを望んでいたでしょうか。

### 30節-44節

-   旅から戻った弟子たちが感じていることを想像してみましょう。
    -   \[DQ\] イエスはどんなことを勧めていますか。
-   弟子たちが戻ってきたところの状態はどのようでしたか。イエスはどう対処しますか。
-   弟子たちはどんなことをイエスに提案し、イエスはどう応答し、それに弟子たちは応えていったか一つ一つのステップをまとめてみましょう。
-   このできごとを通して、あなたはイエスがどんな方だと思いますか。

### 45節-52節

-   イエスは次に何をしますか。それはなぜでしょうか。（ヨハネ６：１５）

-   この夜どんなことがおこりますか。

-   パンのことを悟っていないとはどういうことでしょうか。

### 53節-56節

-   ゲネサレでの滞在はどのようなことを示していますか。

## マルコによる福音書　第7章

### 1節-8節

-   5節からの議論はどのような人たちの間で、何が原因で始まりますか。

-   パリサイ人と律法学者たちは何を大切にしていますか。それはなぜでしょうか。

-   イエスは、どのように批判していますか。イエスの批判の中心点は何ですか。

### 9節-13節

-   この例では、6節-８節で指摘した要点のどのような面を説明しているのでしょうか。どのような対比がありますか。

### 14節-23節

-   汚れの源は何だとイエスは言っていますか。

-   イエスの言う汚れはどんなことでしょうか。パリサイ人たちが考えるものと何が違いますか。

### 24節-30節

-   この女の人はどんな人ですか。

-   イエスと女の応対からどんなことが分かりますか。

### 31節-37節

-   この人の癒しにはどんな段階がありますか。

-   この人のイエスの言葉に対する対応、人々のそれに対する反応はどうでしたか。

## マルコによる福音書　第8章

### 1節-10節

-   この出来事は6章30ー44節の出来事と似ていますが、違いは何でしょうか。

-   イエスはこれら二つの出来事において、人々とその必要にそれぞれどのように対応しますか。

### 11節-21節

-   11ー13節でパリサイ人はどのようなしるしを考えていたと思いますか。なぜしるしを求めるのでしょう。

-   イエスはどのような対応をしますか。それはなぜでしょうか。

-   イエスはパリサイ人とヘロデのパンだねということばでどのようなことについて警告したのでしょうか。どのような生き方が危険だと言っているのでしょうか。

-   弟子たちは何を心配していますか。イエスは弟子たちに何を悟らせようとしていますか。

### 22節-26節

-   この盲人のいやしについて特徴的なことをあげてみましょう。

-   イエスはなぜこのようにされたのでしょうか。

### 27節-30節

-   ここに書かれているのはどこでの出来事ですか。

-   イエスは弟子たちにどんな二つの質問をしますか。

-   弟子たちは最初の質問にどう答えますか。

-   ペテロは二つめの質問にどう答えますか。

### 31節-38節

-   イエスはどのようなことを教えはじめますか。

-   ペテロはどのように反応しますか。なぜでしょうか。弟子たちの希望はどのようなものだったのでしょうか。

-   ペテロの反応はどんな意味で「神のことを思わないで人のことを思っている」のでしょうか。

-   34節のことばは誰に向かって語られていますか。

-   「自分を捨て、自分の十字架を負う」とはどういうことでしょうか。

-   イエスは 35-38節で、どんなことを求めていますか。

## 第1章〜第8章 復習 {.unnumbered}

-   バプテスマのヨハネについて。
    -   *メッセージ、働き、イエスについての証言、死。*
-   イエスは自分はだれかということについて何を教えていますか。
    -   *使命、自分の行く手にあるもの。*
-   イエスは次のことについて何と教えていますか。
    -   *神の国について、安息日について、汚れとは何かについて、イエスの弟子になることについて。*
-   イエスは個人やグループにどのように接し、自分について何を示していますか。
-   弟子たちはどんな人ですか。
    -   *何を見、どのように反応し、イエスをどのような人だと考えているでしょう。*
-   弟子以外の人たちは、イエスに対してどのように応答していますか。
    -   *どんな肯定的な反応と否定的な反応が見られますか。イエスに対する反応の違いはどうしておこるのでしょう。*
-   あなたは、8章までのイエス、弟子たち、人々の応答を学んできて、どのようなことを感じますか。

## マルコによる福音書　第9章

### 1節-13節

-   変貌と言われているこの出来事はいつ、どこでおこりますか。目撃者はだれですか。

-   どうしてペテロは5節にあるような反応をしていると思いますか。雲の中からの声は何と言ってますか。

-   イエスはどんな命令をしていますか。

-   弟子たちはどんな疑問を持っていますか。

-   エリヤについて 9:11-13 と マタイ 17:10-13 を比べてみましょう。

### 14節-29節

-   どのようなことが起こってますか。弟子たちは、どう対応していますか。

-   弟子たちが追い出せなかったことは、この父親の進行にどう影響していますか。

-   イエスはこの場にいる人たちの一番の問題は何だと見ているのでしょう。

-   子供がイエスのもとに連れてこられた時、何がおこりますか。イエスはなぜ子供の状態について父親と話しているのでしょう。

-   イエスはが信じるように迫った時、父親はどう答えますか。

-   ここで、父親が経験したこと、弟子たちが経験したことを順をおって分析してみましょう。

-   弟子にとって本当にたりなかったのは、何でしょうか。弟子たちは祈るかわりに何をしていましたか。

### 30節-41節

-   なぜイエスは、旅行の行程を秘密にしたいのでしょうか。

-   弟子たちはイエスの教えにどのように反応していますか。

-   イエスの心を占めていたことと、弟子たちの心を占めていたことをそれぞれまとめてみましょう。

-   偉さについてどんなことが教えられていますか。

-   「イエスの名のゆえに」受け入れるとはどういうことでしょうか。

-   37節の言葉を聞いて、ヨハネは何を思い出しましたか。

-   なぜ弟子たちはこの人を咎めたのですか。

-   イエスは、人の行為に対する神の評価について何を教えていますか。

-   なぜイエス・キリストとの関係によってだけ人は評価されるのですか。イエスの名が強調してあることに注意しましょう。

### 42節-50節

-   42節から47節には四つの対比があります。それぞれの場合に何が何よりも良いのですか。

-   他の人との関係についてどんな警告が与えられていますか。

-   小さいものたちとは、誰のことですか。

-   今日の社会で、どんなことが、他の人に罪をおかさせるつまずきになりますか。

-   手や足はどのようにその人に罪をおかさせうるでしょうか。罪の結果は何ですか。

-   塩はどのような意味に使われているのでしょうか。

## マルコによる福音書　第10章

### 1節-12節

-   だれが、どんな目的で、イエスに質問していますか。

-   イエスは離婚についてのモーセの扱い方をどのように説明していますか。

-   イエスは結婚についてどのように教えていますか。弟子たちへのことばとあわせて考えてみましょう。

### 13節-16節

-   なぜ弟子たちは、子供たちをイエスのもとに連れてくる人たちを叱るのでしょうか。

-   幼子のように神の国を受け入れるとはどういうことでしょうか。

### 17節-31節

-   このひとについてどんなことがわかりますか。イエスをどう思っているか。イエスはどう見ているか。

-   イエスはこの人に何を教えようとしているのでしょうか。

-   金持ちが神の国にはいるのがむずかしいのはなぜでしょうか。

-   イエスは弟子たちにどのようなことを伝えていますか。

### 32節-34節

-   この箇所と 8:31, 9:31 をくらべて共通のことと、新しいことを挙げてみましょう。

### 35節-45節

-   ヤコブとヨハネ、そして弟子たちは何を考えていますか。

-   イエスはどのように答えていますか。

-   イエスがきた一番の目的は何だと言っていますか。

-   この目的はイエスの教えや活動によって達せられるものですか、それともそうではないものですか。

### 46節-52節

-   バルテマイの願いは何ですか。

-   イエスは「行け、あなたの信仰があなたを救った」と言っていますが、バルテマイの信仰とはどんなことでしょうか。

## マルコによる福音書　第11章

### 1節-11節

-   イエスは弟子の二人にどんな指示をしていますか。

-   イエスのエルサレム入場と人々の反応をまとめてみましょう。

### 12節-26節

-   エルサレムに戻る途中でどんなことがおこりますか。

-   宮ではどのようなことがおこりますか。

-   イエスの行動は弟子たちに、人々にどううつったでしょうか。祭司長たちはどう考えましたか。

-   いちじくのことから、イエスは弟子たちにどのようなことを教えていますか。

-   イエスは祈りについてどんなことを教えていますか。祈りとゆるしにはどのような関係があるのでしょうか。

### 27節-33節

-   祭司長たちは、なぜこのような質問をするのでしょうか。

-   イエスはどのように答えられますか。

-   祭司長たちは、なぜバプテスマのヨハネを受け入れなかったのでしょうか。

## マルコによる福音書　第12章

### 1節-12節

-   1節から9節のたとえの要点をまとめてみましょう。

-   イエスはこのたとえのなかで、どんな預言をしていますか。ぶどう園の主人、農夫、しもべ、ぶどう園の主人の息子はそれぞれだれを表していますか。

-   旧約聖書からの引用は何をあらわしていますか。

-   イエスは、11:28の質問にどう答えていますか。

### 13節-17節

-   パリサイ人とヘロデ党のひとたちは、どんな動機から、どのような質問をしますか。

-   「納めるべきだ」または「納めないべきだ」と答えた場合どのようなことが予想されますか。

-   偽善（15節）とはこの場合どのようなことでしょうか。

-   イエスはどのように答えていますか。

-   わなにかけようとした人たちは、なぜ驚嘆したのでしょうか。

### 18節-27節

-   サドカイ人たちは、どんな質問をしますか。復活についての彼らはどう思っていましたか。

-   イエスはサドカイ人たちがどんな思い違いをしていると言っていますか。

-   イエスは、復活があることを証明するためにどのように聖書を引用していますか。

### 28節-34節

-   この律法学者はどのような動機からどのような質問をしていますか。何を聞きたいのでしょう。

-   イエスはなんと答えていますか。（申命記6:4,5、レビ記19:18、出エジプト記20:3-17）

-   「あなたの神である主を愛せよ」「隣人を自分と同じように愛せよ」とはどんな意味でしょうか。

-   この律法学者は、イエスの答えにどう反応しますか。この律法学者についてどんなことが分かりますか。

-   なぜ人々は、イエスにこれ以上質問をしないのですか。

### 35節-37節

-   ここでイエスはどのような質問をしますか。

-   イエスはダビデとメシヤ（キリスト）の関係についてどのように言っていますか。

### 38節-44節

-   イエスはどのようなことに注意しなさいと言っていますか。

-   貧しいやもめと金持ちはなにが違うのでしょう。

-   イエスはどのようなことを教えていますか。

## マルコによる福音書　第13章

### 1節-13節

-   この会話はいつどこでどのように始まりますか。

-   イエスは、宮について何と言っていますか。

-   四人の弟子たちは何を知りたがっていますか。

-   イエスはどんなことが起こると言っていますか。

-   弟子たちに何を伝えようとしているのでしょうか。

-   イエスに従うものたちにはさらにどんなことが起こると言っていますか。

-   弟子たちはどのように生きるべきでしょうか。

### 14節-23節

-   14--16節をルカ 21:20--22と比較してみましょう。

-   どんなことが起こると言っていますか。それは、かなり先のことですか。

-   肉体的な危険のほかに、どんな危険について警告していますか。

-   偽預言者や、偽メシアは、見分けることができるのでしょうか。

### 24節-27節

-   人の子は、どのような時に来ますか。

-   人の子は何をしますか。

### 28節-37節

-   これらのことの起きるタイミングについて、イエスは何と言っていますか。

-   31節は何を言っているのでしょうか。

-   イエスはどのような命令を与えていますか。

-   イエスがあげている例は何を強調していますか。

## マルコによる福音書　第14章

### 1節-11節

-   1--11節のできごとをまとめてみましょう。それぞれ、イエスに対してどのような態度の人が登場しますか。

-   イエスに香油を注いだ女に対する人々の態度、それに対するイエスの言葉からあなたは、どんなことを思いますか。マタイ26:6--13、ヨハネ12:1--8と比べてみましょう。

-   ユダについて、マルコはあまり書いていませんが、ユダはなぜ裏切ったのだと思いますか。

### 12節-25節

-   イエスは弟子たちと過ぎ越しの食事をするために、どのような準備をしておきましたか。それは何故でしょう。

-   イエスは食事中に何を弟子たちに知らせますか。弟子たちはどんな反応をしますか。それは何故でしょう。

-   22--25節で、イエスは、何をしていますか。どのような意味があるのでしょうか。

-   イエスはどんな預言をしていますか。

### 26節-31節

-   ペテロは、なぜこれほど強く言い切るのでしょうか。

-   イエスは、そのペテロに何と言っていますか。

### 32節-42節

-   イエスはどのように祈っていますか。

-   弟子たちは、どうしていますか。

### 43節-52節

-   この場面を描いてみましょう。

-   イエスはどのように対応しますか。

-   ペテロや他の弟子たちはなぜ逃げてしまったのでしょう。

### 53節-65節

-   ユダヤの最高裁判所である、議会の目的は何ですか。どのような告発が書いてありますか。

-   大祭司は、どのような尋問をしますか。

### 66節-72節

-   ペテロの裏切りの記事を一回一回追ってみましょう。どのように言われ、ペテロはどのように答えますか。

-   あなたならどうするでしょうか。

## マルコによる福音書　第15章

### 1節-15節

-   議会はなぜ、ピラトに引き渡すのでしょうか。

-   ピラとはどんな尋問をし、イエスはどのように答えますか。

-   ピラトが問題にしているのはどんなことでしょうか。

-   ピラトが群衆を静めようとして利用したのはどんな習慣ですか。バラバについて何がわかりますか。

-   ピラトはどのような価値観から行動していると思いますか。

### 16節-32節

-   10:33, 34 と比較してみましょう。

-   だれが、どのようにイエスをあざけっていますか。

-   シモンというキレネ人はどのようなことをすることになりますか。

（使徒13:1, ローマ16:13）

-   十時架刑についてどのようなことが書かれていますか。

-   詩篇22篇と比べてみましょう。

-   人が信じるために必要なものは何でしょうか。

### 33節-41節

-   イエスの死をどのように描いていますか。

-   イエスの叫びからあなたは、どのようなことを感じますか。

-   神殿の幕のことはなにを意味していると思いますか。

-   その場にどのような人がいますか。百卒長は、なぜこのように告白したのでしょうか。

### 42節-47節

-   ヨセフについてどんなことがわかりますか。

-   どのようなことをしますか。急いでしたのは何故でしょうか。

## マルコによる福音書　第16章

### 1節-8節

-   婦人たちが、墓に近付いたときのことを考えてみましょう。どんなことを心配していますか。

-   墓の中には何があり、婦人たちはなにを告げられますか。

-   婦人たちは、どうしますか。

### ルカによる福音書 第24章 1節-35節

-   どのようなことが、ルカには書かれていますか。

-   なぜ弟子たちは婦人たちの話しを信じないのでしょうか。

-   エマオに向かっている弟子たちはどんな様子ですか。

-   イエスはこの人たちにどのように自分のことを示していますか。

なぜ聖書を学ぶことが必要なのでしょうか。

-   かれらは、いつ、どんなことで、イエスだとわかりますか。そしてどうしますか。

-   エルサレムではどんなことが知らされますか。

### ルカによる福音書 第24章 36節-53節

-   弟子たちの真中に現れた時、彼らはどんな反応を見せますか。

-   弟子たちは、どんなことを確信するようになりますか。なぜ、このように変化するのでしょう。。

-   さらにイエスはどんなことをしますか。それは、どんな効果があったでしょうか。

-   弟子たちがすべきことは何ですか。

-   弟子たちが伝えるべきことと、イエスのメッセージとはどのような相違がありますか。

-   別れをどのように描いていますか。
