# マタイ（2011-2015） {#matthewdq-old}

## マタイによる福音書　第1章
### マタイによる福音書 Matthew 1:1 - 17



- この系図で気づいたことを挙げてみましょう。List what you notice in this genealogy.



- マタイはなぜ系図から始めたのでしょうか。Why do you think Matthew stats from this genealogy?



- この系図を通してマタイが伝えたかったことは何なのでしょうか。What does Matthew communicate through this genealogy.









### マタイによる福音書 Matthew 1:18 - 25



- イエスキリストの誕生について 18節はどのように書いてありますか。What were the unusual things that happened? (v18) What do you think about that?



- ヨセフはどのような人ですか。What can you learn about Joseph?



- 天使はヨセフに何を伝えますか。What did the angel of the Lord tell Joseph?



- 生まれてくる男の子は、将来どのような人になると言われていますか。What is prophesied about the boy?



- あなたがヨセフならそのような気持ちを抱き、天使の言葉にどのように応答するでしょうか。If you were Joseph, what do you feel and how do you respond to angel.



- この章で、イエスについて何を伝えようとしているのでしょうか。What can you tell about Jesus through this chapter?






## マタイによる福音書　第2章
### マタイによる福音書 Matthew 2:1 - 12



- イエスの生まれた場所について、博士たちについてどんなことが分かりますか。What do you learn about where Jesus was born? What do you learn about the wise men?



- ヘロデやエルサレムの人たちの反応はどのようなものでしたか。How do King Herod and the people of Jerusalem respond?



- ヘロデはどうしますか。なぜ密かに博士たちに尋ねたのでしょうか。 What did Herod do? What might be the reason why he kept it as a secret? (v7, 8)



- 博士たちのその後について記されていることをあげてみましょう。What did the wise men do?







### マタイによる福音書 Matthew 2:13 - 23



- なぜヨセフは家族とエジプトに行きますか。Why Joseph takes his family and goes to Egypt?



- ヘロデについてはどんなことがわかりますか。Make a list of the things that you learn about Herod. What sort of person was Herod?



- ヘロデが死んでからのイエスの家族についてどんなことが分かりますか。What do you learn about the family after the death of Herod?



- この家族についてこの章でどのようなことが分かりますか。What do you learn about the family through this chapter?








## マタイによる福音書　第3章
### マタイによる福音書 Matthew 3:1 - 12



- 洗礼者ヨハネは、どこで、どのようなメッセージを語りますか。Where does John the Baptist teach and about what does John teach?



- イザヤの言葉の引用はどのような人のことを語っていますか。What had Isaiah said about the person?



- ヨハネの生活からどんなことが分かりますか。What do you learn from John's clothes and life?



- どのような人たちがヨハネのもとに来ますか。Who come to John?



- ヨハネのファリサイ派やサドカイ派の人々へのメッセージをまとめてみましょう。What is the message of John to Pharisees and Sadducees?



- ヨハネは、ファリサイ派やサドカイ派の人々に、なぜ7節から12節のように語るのでしょうか。Why does John say to Pharisees and Sadducees these words?







### マタイによる福音書 Matthew 3:13 - 17



- 洗礼者ヨハネは、イエスが洗礼をうけるのをなぜ思いとどまらせるのでしょうか。Why does John stop Jesus to be baptized?



- イエスはなぜ洗礼者ヨハネから洗礼を受けるのでしょうか。Why does Jesus get baptized?



- イエスが洗礼を受けたときどんなことが起こりますか。What happens when Jesus is baptized?










## マタイによる福音書　第4章
### マタイによる福音書 Matthew 4:1 - 11



- イエスはどこでどのように誰によって試みられますか。Describe where, how and by whom Jesus was tested.



- 三つの試みが記されていますが、最初にサタンはどのようにイエスに言っていますか。イエスはそれにどのように答えますか。What did the devil suggest first? How did Jesus say to the devil?



- 次にサタンはイエスをどこへ連れて行きどのように言いますか。イエスはどのように答えますか。Where did the devil bring Jesus and what did the devil suggest him? How did Jesus say to the devil?



- 次にサタンは、イエスをどこへ連れて行きますか。そしてどのように言い、イエスはどのように答えますか。Where did the devil bring Jesus next and what did the devil suggest him? How did Jesus say to the devil?



- 結果としてどのようになったと書いてありますか。What was the result?



- イエスのあった試みはあなたにはどのような意味があると思いますか。To you, what is the meaning of this test Jesus went through?









### マタイによる福音書 Matthew 4:12 - 25



- イエスはなぜガリラヤに行きますか。Why did Jesus go to Galilee?



- ガリラヤについて、どんなことが分かりますか。What do you learn about Galilee?



- イエスの宣教はどのようにして始まりますか。What was the first message of Jesus?



- シモンとアンデレについてどのような事が分かりますか。What do you learn about Simon and Andrew?



- ヤコブとヨハネについてどのような事が分かりますか。What do you learn about James and John?



- イエスのガリラヤ宣教についてまとめてみましょう。What do you learn about Jesus' ministry in Galilee?








## マタイによる福音書　第5章
### マタイによる福音書 Matthew 5:1 - 12



- イエスはどのような状況で誰に対してこのメッセージを語っていますか。When, to whom and where did Jesus give this message?



- 「心の貧しい人たち」とはどのような人々でしょうか。Who are the poor in spirit?



- 「悲しむ人々」とはどのような人々でしょうか。Who are those who mourn?



- 「柔和な人々」とはどのような人々でしょうか。Who are the meek?





- 「義に飢え渇く人々」とはどのような人々でしょうか。Who are those who hunger and thirst for righteousness?



- 「憐れみ深い人々」とはどのような人々でしょうか。Who are the merciful?



- 「心の清い人々」とはどのような人々でしょうか。Who are the pure in heart?



- 「平和を実現する人々」とはどのような人々でしょうか。Who are the peacemakers?



- 「義のために迫害される人々」とはどのような人々でしょうか。Who are those who are persecuted because of righteousness?









### マタイによる福音書 Matthew 5:13-16



- 地の塩とはどのようなひとのことでしょうか。What is meant by 'salt'?



- 塩のききめを失うとどうなると言っていますか。What happens if the salt loses saltiness?





- なぜ「あなたがたは、世の光である」と呼ばれているのでしょうか。Why does Jesus call the disciples the light of the world?



- 16節にはどのような命令が書かれていますか。あなたは、どのように感じますか。What does Jesus tell disciples? What is your reaction?









### マタイによる福音書 Matthew 5:17 - 20



- イエスは「律法や預言者」についてどのように言っていますか。What does Jesus tell about

the Law and the Prophets?



- 20節で言われている「律法学者やファリサイ派の人々の義」というのは、どのような義のことでしょうか。そしてそれよりまさる義とはどのような義でしょうか。What does Jesus mean by ''the righteousness surpasses that of the Pharisees and the teachers of the law''?









### マタイによる福音書 Matthew 5:21 - 26



- イエスは『殺すな。人を殺した者は裁きを受ける』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'You shall not murder, and anyone who murders will be subject to judgment'?



- 23節から26節で、イエスはどのようなことを勧めていますか。What does Jesus say in vs 23 - 26?









### マタイによる福音書 Matthew 5:27 - 32



- イエスは『姦淫するな』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'You shall not commit adultery'?


- イエスは『妻を離縁する者は、離縁状を渡せ』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'Anyone who divorces his wife must give her a certificate of divorce'?



### マタイによる福音書 Matthew 5:33 - 42

- イエスは『偽りの誓いを立てるな。主に対して誓ったことは、必ず果たせ』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'Do not break your oath, but fulfill to the Lord the vows you have made'?


- イエスは『目には目を、歯には歯を』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'Eye for eye, and tooth for tooth.'?



### マタイによる福音書 Matthew 5:43 - 48



- イエスは『隣人を愛し、敵を憎め』という言葉をひいてどのように教えていますか。What does Jesus teach by referring to 'Love your neighbor and hate your enemy.'?



- なぜ、「父は悪人にも善人にも太陽を昇らせ、正しい者にも正しくない者にも雨を降らせてくださるからである。」がここで書かれているのでしょうか。



- 最後にイエスは何を勧めていますか。








## マタイによる福音書　第6章
### マタイによる福音書 Matthew 6:1 - 4



- 5章で語られてきた義を行う私たちの態度について 1節ではどのようなことが述べられていますか。What does Jesus teach about our attitude to do right things in verse 1?



- 2節から18節までにはそれぞれどのようなトピックについて述べられていますか。What topics are discussed in verse 2 to 18?



- 施しについてどんなことが教えられていますか。What is taught on giving?



- 結局、義は報酬のために行うのでしょうか。Do we give for reward?



- 5:16 の人々の前で光を輝かすこととの関係はどう考えたらよいでしょうか。What is the relation between 5:16 and 6:1?







### マタイによる福音書 Matthew 6:5 - 15



- 5 - 8節で、祈りについてどんなことが教えられていますか。What is taught in verses 5 - 8 about prayer?



- なぜ密室で祈るのですか。Why are we to go into our room, close the door and pray?



- 8節は祈りについて何を言っているのでしょうか。What does verse 8 tell us about prayer?



- 14, 15節で、赦しについてどのようなことが語られていますか。What is taught about forgiveness in verses 14 and 15?







### マタイによる福音書 Matthew 6:9 - 13 主の祈り Lord's Prayer



- ルカによる福音書にあるものと比べてみましょう。(ルカ11:1 - 4)　Compare with the corresponding verses in Luke 11:1 - 4.



- イエスが祈り方を教えていますが、教えられてはじめて祈る事ができるのでしょうか。Can we pray only when we are taught to pray?



- 一節ずつみてみましょう。どんなことに気づきますか。（新共同訳）Share your observations on each verse. (NIV)



- 天におられるわたしたちの父よ、／御名が崇められますように。(v9) Our Father in heaven,

hallowed be your name,



- 御国が来ますように。御心が行われますように、／天におけるように地の上にも。(v10) your kingdom come, your will be done, on earth as it is in heaven.





- わたしたちに必要な糧を今日与えてください。(v11) Give us today our daily bread.



- わたしたちの負い目を赦してください、／わたしたちも自分に負い目のある人を／赦しましたように。(v12) And forgive us our debts, as we also have forgiven our debtors.



- わたしたちを誘惑に遭わせず、／悪い者から救ってください。(v13) And lead us not into temptation, but deliver us from the evil one.





- 祈りと 14, 15 節はどのように関係しているのでしょうか。What is the relation between the prayer and verses 14 and 15?





### マタイによる福音書 Matthew 6:16 - 18



- 断食はどのようなときにするのでしょうか。When do people fast?



- ここでは断食についてどんなことが教えられていますか。What is taught here about fasting?







### マタイによる福音書 Matthew 6:19 - 24



- 自分の宝を蓄えることについてどんなことを教えていますか。What does Jesus say on treasures?



- 天に宝を蓄えるとはどういう事でしょうか。How do we store up our treasures in heaven?



- 目についてどんなことを教えていますか。What does Jesus say about eyes?



- 神と富とに仕えるとはどういうことでしょうか。What do you think is to serve God and money?



- この箇所は全体として何を言っているのでしょうか。What does Jesus teach in verses 19 - 24?









### マタイによる福音書 Matthew 6:23 - 34



- どんな煩いについて語られていますか。What kind of worries Jesus points here?



- なぜ思い煩ってはいけないのでしょうか。その理由を挙げてみましょう。List up the reasons why we do not need to worry.



- 天の父がわたしたちに必要なものをすべて知っているということは、あなたの生き方にどう影響しますか。What does it mean if our heavenly father knows everything you need?



- 神の国と神の義をと求めるとはどのようなことでしょうか。What is to seek the kingdom and the righteousness of our heavenly father?



- あなたはどのようなことに思い煩いますか？ What do you worry about?








## マタイによる福音書　第7章
### マタイによる福音書 Matthew 7:1 - 6



- 「人を裁く」とはどういうことでしょうか。なぜ裁いてはいけないのでしょうか。What does it mean to judge. Why does Jesus say ''Do not judge"?



- 誰をさばくのでしょうか。誰に裁かれるのでしょうか。Judge who? Who will judge us?



- 6節をみるとやはり判断は必要なのではないでしょうか。According to verse 6, we have to judge, don't we?





- 2節にある「自分の量る秤で量り与えられる」とはどういうことでしょうか。What does verse mean?



- 3, 4節はどんな状況を言っていますか。What does Jesus say in verses 3 and 4?



- ではどうすれば良いのでしょうか。What should we do?



- 6節にある、犬、豚、神聖なもの、真珠はなにを意味しているのでしょうか。What do dogs, swines, what is sacred and pearls mean?







### マタイによる福音書 Matthew 7:7 - 12



- 「求めなさい\\ldots (v7)」は、だれがだれになにを求めることについて言っているのでしょうか。Who asks to whom and what?



- ルカによる福音書ではどのような背景でこの言葉が語られているでしょうか。(11:1-13) Find the background of this verse in Luke 11:1 - 13.



- 「求めよ」「さがせ」「門をたたけ」はそれぞれどんなことを言っているのでしょうか。What does 'ask', 'seek' and 'knock' mean here?



- 9節から11節では「あなたがた」と「天の父」についてどのような対比がなされていますか。What are explained by comparing 'you' and 'heavenly father' in verses 9 to 11?





- 「だから、人にしてもらいたいと思うことは何でも、あなたがたも人にしなさい。」は黄金律とも言われますが、具体的にどのようなことを言っていると思いますか。Verse 12 is often called 'Golden Rule'. What do you think it means here?



- 「己の欲せざる所、人に施すことなかれ。」と同じことでしょうか。Is this same as ''Do not do unto other what you do not want others to do unto you.'' of Confucius?



- この節は文脈の中でなにを言っているのでしょうか。What does this verse 12 say in this paragraph?







### マタイによる福音書 Matthew 7:13 - 14



- 狭い門、細い道とはここでは何を意味しているのでしょうか。What does narrow gate and narrow path mean?



- 命に至る道とは何をさしているのでしょうか。What does 'the road that leads to life' mean?





### マタイによる福音書 Matthew 7:15 - 23



- 偽預言者とはどのような人のことでしょうか。What is the characteristic of false prophets?



- 実とは何を意味しているのでしょうか。What are fruits?



- 偽預言者を見分けることができるのでしょうか。Can we recognize who false prophets are?



- 「主よ、主よ」と言うこと自体が問題なのでしょうか。Is it a problem to say ''Lord. Lord.'







### マタイによる福音書 Matthew 7:24 - 29



- ここで家を建てた二人の人のたとえが書かれていますが、共通点は何で、何が違っているのでしょうか。What are the same and what are the differences in the actions of the two in this parable?



- 土台とは何でしょうか。What is the foundation?



- 三つのたとえのメッセージをまとめてみましょう。Let us summarize three parables.



- 権威ある者として教えたとはどのようなことを言っているのでしょうか。What does it mean to teach as one who had authority.






## マタイによる福音書　第8章
### マタイによる福音書 Matthew 8:1 - 4



- 山を下りてくると、どのようなことが起きますか。What happens when Jesus and the followers go down from the mountainside?



- どうして、もっと単純に、治して下さいと言わないのでしょうか。Why he does not simply ask Jesus to cure his disease?



- イエスはなぜだれにも話さないようにと注意したのでしょうか。Why does Jesus warn him not to tell anyone?



- イエスはなぜモーセの定めの実行を命じたのでしょうか。Why does Jesus tell him to follow what Moses commanded?







### マタイによる福音書 Matthew 8:5 - 13



- どのようなことが起きますか。What happens in Capernaum?



- この百人隊長についてどんなことが分かりますか。What can you tell about this centurion?



- 百人隊長はイエスについてなにを信じていますか。What does this centurion believe in Jesus?



- イエスはこの百人隊長の信仰をほめていますが、実際何をほめているのでしょうか。What is Jesus amazed at?



- イエスは 11, 12節で何を言っているのでしょうか。What Jesus tell us in verses 11 and 12?







### マタイによる福音書 Matthew 8:14 - 17



- ペテロの家ではどのようなことが起きますか。What happens at Peter's house?



- 夕方にはどんなことが起きますか。What happens in the evening?



- イザヤ書のことばがイエスにおいて実現しているとするとそれは何を言っていますか。

If what Isaiah prophesied is fulfilled in Jesus, what does it mean?





### マタイによる福音書 Matthew 8:18 - 22



- どのような状況でこの会話が始まりますか。Describe the scene when the talk started.



- イエスは何を伝えようとしているのでしょうか。What do you think about that instruction?







### マタイによる福音書 Matthew 8:23 - 27



- 湖でどのようなことが起きますか。What happens on the lake?



- 人々はなにに驚いたのでしょうか。What surprises the people about these events?





### マタイによる福音書 Matthew 8:28 - 34



- ガダラ人の地方で何がおきますか。What happens in the region of the Gadarenes?



- イエスはどのようにして悪霊を追い出しますか。How does Jesus expell the demmons?



- なぜ町の人たちは、イエスにその地方から出ていってほしいと願ったのでしょうか。Whay does the people plead Jesus to leave their region?






## マタイによる福音書　第9章
### マタイによる福音書 Matthew 9:1 - 8



- どこで、どのようなときに、このことが起こりましたか。When and where does this happen?



- 「その人たち（彼ら）の信仰」とは誰のどのような信仰なのでしょうか。What does ''their faith'' mean? Whose faith? What kind of faith?



- なぜイエスは「子よ、元気を出しなさい。あなたの罪は赦される」と言ったのでしょうか。Why does Jesus say ''Take heart, son; your sins are forgiven?''



- 『あなたの罪は赦される』と言うのと、『起きて歩け』と言うのと、

どちらが易しいのでしょうか。Which is easier: to say, 'Your sins are forgiven,' or to say, 'Get up and walk'?







### マタイによる福音書 Matthew 9:9 - 13



- マタイはどのような人で、どのようにしてイエスの弟子になりますか。Who is Matthew? How does he become a disciple?



- イエスはどこでどのような人たちと食事をしていますか。Where does Jesus have a dinner? Who are there with him?



- ファリサイ人たちは、なぜこのように弟子達に聞くのでしょうか。Why do Pharisees ask these questions to Jesus' disciples?



- イエスはどのように答えていますか。How does Jesus respond to them?



- イエスはどのような意図で『わたしが求めるのは憐れみであって、いけにえではない』と言っているのでしょうか。Why does Jesus say ''Go and learn what this means: {'I desire mercy, not sacrifice.'''



- 「罪人を招く」とはどのような意味でしょうか。What does it mean to call sinners?







### マタイによる福音書 Matthew 9:14 - 17



- 14節の質問は、誰がしていますか。なぜそのような質問をするのでしょうか。Who asked the question in verse 14?



- イエスはどのように答えていますか。 How did Jesus answer to the question?



- 布きれと服、葡萄酒と革袋のたとえはどのようなことを説明しているのでしょうか。What are a patch of unshrunk cloth on an old garment and new wine in old wineskins?







### マタイによる福音書 Matthew 9:18 - 26



- 指導者はイエスに何を願いますか。What is the request of the leader?



- 途中でどんなことがありますか。What happens on the way?



- イエスはこの女性になんと言っていますか。What does Jesus tell this woman?



- イエスは少女にたいしてどうしますか。What does Jesus do to the girl?









### マタイによる福音書 Matthew 9:27 - 34



- 二人の盲人は、イエスにどのように訴えますか。How do two blind appeal to Jesus?



- イエスは、どう対応しますか。How does Jesus respond to these blind.



- イエスはなぜ誰にも知らせてはいけないと言うのでしょうか。Why does Jesus tell these blind not to tell the story.



- イエスが悪霊を追い出すとどんなことがおきますか。What happens when Jesus drives out demons?









### マタイによる福音書 Matthew 9:35 - 38



- イエスが町や村を巡回したときのことをどのようにまとめていますか。How does Mattew summarize Jesus' ministry?



- イエスは群衆をどう見ていますか。How does Jesus see the crowds.



- イエスは弟子たちにどのように命じていますか。What does Jesus command to his disciples?








## マタイによる福音書　第10章
### マタイによる福音書 Matthew 10:1 - 4



- イエスは12人の弟子を呼び寄せどうしますか。What does Jesus do with his twelve disciples?



- このリストからどんなことが分かりますか。What do you find from this list?



- 他のリストと比較してみましょう。Please compare this with other lists.'


### マタイによる福音書 Matthew 10:5 - 15

- イエスは12人を誰に遣わしていますか。メッセージは何ですか。To whom 12 disciples are sent? What is the message.


- 8節から10節でどのような指示を与えていますか。What instructions are given to disciples in vs 8-10?

- 11節から15節は何を言っているのでしょうか。What does vs 11-15 mean?



### マタイによる福音書 Matthew 10:16 - 25

- 「蛇のように賢く、鳩のように素直」とはどのようなことが求められているのでしょうか。What does 'be as shrewd as snakes and as innocent as doves' mean?


- どのような困難を経験するといわれていますか。What difficulties are waiting for disciples?

- なぜ「何をどう言おうかと心配してはいけない」のでしょうか。Why they should not worry about what to say or how to say it?



- なぜイエスのために憎まれるのでしょう。Why are they hated?



- 迫害されたときのことについてどのように指示されていますか。What is instructed for the days of persecution?



- 「弟子は師にまさるものではない」とは何のための説明でしょうか。What does the saying 'the student is not above the teacher' explain?







### マタイによる福音書 Matthew 10:26 - 31



- 誰をおそれなくてよいのですか、そしてそれはなぜですか。Whom are they not afraid of, and why?



- 「たくさんの雀よりもはるかにまさっている。」とはどういうことでしょうか。What does 'you are worth more than many sparrows' mean?


### マタイによる福音書 Matthew 10:32 - 33



- イエスの仲間であると言い表すとはどのようなことでしょうか。What does it mean to 'acknowledge before my Father in heaven'?



### マタイによる福音書 Matthew 10:34 - 39



- 「平和ではなく、剣をもたらすため」とはどういう意味でしょうか。What does it mean to say 'I did not come to bring peace, but a sword.'?



- イエスに従っていく人とはどのような人でしょうか。Who are the followers of Jesus?


### マタイによる福音書 Matthew 10:40 - 42



- イエスの弟子を受け入れることはなぜイエスを受け入れることになるのでしょうか。Why is to accept Jesus' disciples to accept Jesus?




## マタイによる福音書　第11章
### マタイによる福音書 Matthew 11:1 - 19



- マタイによる福音書3章からバプテスマのヨハネについて復習してみましょう。

Read Matthew 3 and review John the Baptist.



- なぜ、ヨハネはこのような質問を弟子たちにさせたのでしょうか。Why did John ask this question by sending his disciples?



- イエスはどのように答えていますか。What was Jesus' answer?



- イエスは、ヨハネのことをどのような人だと言っていますか。What does Jesus say about John?



- 「天の国で最も小さな者でも、彼よりは偉大である。」とはどういうことでしょうか。

What does ''whoever is least in the kingdom of heaven is greater than he (John the baptist)'' mean?



- 17節の『笛を吹いたのに、／踊ってくれなかった。葬式の歌をうたったのに、／悲しんでくれなかった。』はどのような状況を描写しているのでしょうか。What is described in verse 17?



### マタイによる福音書 Matthew 11:20 - 24



- イエスはなぜ、これらの町を叱っているのでしょうか。Why does Jesus scold these towns?




### マタイによる福音書 Matthew 11:25 - 30



- イエスは25 - 27節でなにを言おうとしているのでしょうか。What does Jesus mean say in verses 25 - 27?



- イエスはどのような人を招いていますか。Who are invited by Jesus?



- 「わたしの軛は負いやすく、わたしの荷は軽い」とはどのような意味でしょうか。What does ''For my yoke is easy and my burden is light'' mean?





## マタイによる福音書　第12章
### マタイによる福音書 Matthew 12:1 - 8



- 弟子たちは「いつ」「どこで」「なに」をしていますか。それはなぜですか。When and what do disciples do? and Why?



- ファリサイ派の人々は誰に何を訴えていますか。To whom and what do Pharisees tell Jesus?



- イエスはどんな二つの例をあげて答えていますか。What are the two examples Jesus used for explanation?



- 7節は何を気づかせようとしているのでしょうか。What does Jesus mean by quoting a verse from the Bible?



- 「人の子は安息日の主なのである。」は何を言っているのでしょうか。What does Jesus mean by saying ''For the Son of Man is Lord of the Sabbath?''




### マタイによる福音書 Matthew 12:9 - 21



- 会堂にはどんな人がいますか。人々の質問の意図は何ですか。Who are there at the synagogue? Why do the people ask a question in verse 10 to Jesus?



- イエスはどのように答えますか。How does Jesus answer to the question?



- 人々はなぜイエスを殺そうとまで思ったのでしょうか。Why do the people plot to kill Jesus?



- イエスはこの企みを知ってどうしますか。What does Jesus do when he knows the plot?



- イザヤ書からの引用は、イエスについてどのようなことを表現していますか。What does the quote from Isaiah tell about Jesus?





### マタイによる福音書 Matthew 12:22 - 37



- どんなことがおきますか。What happened?



- 群衆やファリサイ人はそれぞれどのような反応をしますか。What were the responses of the people and the Pharisees?



- イエスはファリサイ派の人の批判にどのように答えますか。How did Jesus respond to the Pharisees?



- 神の国が来ていることはどのようにして分かると言っていますか。How can they tell that the kingdom of God has come upon them? What was Jesus' explanation?





- 30節は、中立はないと言うことでしょうか。なぜでしょうか。Is there a neutral position? Why?



- 聖霊に言い逆らうとはどのようなことでしょうか。What is blasphemy against the Spirit?



- なぜここで木と実や倉のたとえが語られているのでしょうか。Why does Jesus tell the parables of a tree and its fruit and a storage?



- 実とは何のことでしょうか。倉とは何を意味しているのでしょうか。What are a tree, a fruit and a storage?



- イエスはここで誰に何を伝えたいのでしょうか。What and whom does Jesus want to tell through this message?



### マタイによる福音書 Matthew 12:38 - 45



- 律法学者とファリサイ人はしるしを求めますが、なにの証拠を求めているのでしょうか。What is the sign these Pharisees want Jesus?



- イエスはこれにどのように答えていますか。How does Jesus answer them?



- 「よこしまで神に背いた時代の者たちはしるしを欲しがる」とはどういういみでしょうか。What does it mean to say ''A wicked and adulterous generation asks for a sign''?



- ニネベの人たち、南の女王を引用して、イエスは何を伝えようとしていますか。What does Jesus tries to tell them by quoting the men of Nineveh and the Queeen of the South?





- 汚れた霊のたとえを通してイエスは何を伝えようとしているのでしょうか。What does Jesus tell by this parable?



- 43節にあるこのひとがある人たちを象徴しているとすると、それはどんな人のことでしょうか。If this person in verse 43 represent a kind of people, who are they?





### マタイによる福音書 Matthew 12:46 - 50



- イエスの家族たちが話したいこととは何のことだと思いますか。What do you think Jesus' family members want to tell?



- イエスはどのように答えられますか。What is Jesus' response?



- イエスの兄弟、姉妹、母はどのような人だと言っていますか。Who are Jesus's brothers, sisters and mother?




## マタイによる福音書　第13章

### マタイによる福音書 Matthew 13:1 - 23


- イエスはこのたとえをいつ、どこで、誰に対して話していますか。When, where and to whom does Jesus tell this parable?



- 一般的にたとえ話にはどのような特徴・効果がありますか。In general why and when are parables used?



- イエスはたとえ話をどのように話し始めますか。How does Jesus start this parable?



- 種はどのようなところに落ちましたか。Where do seeds fall?



- なぜイエスはたとえを用いるのでしょうか。Why does Jesus use parables?



- 弟子たちと群衆はなにが違うのでしょうか。What is the difference between the disciples and the crowds?



- イザヤ書からの引用はなにを言っているのでしょうか。What does the quote from Isaiah say?



- 17節の「預言者や正しい人たち」が見たかったこと、聞きたかったこととは何なのでしょうか。What are many prophets and righteus people longed to see and hear?



- 種は何だと言っていますか。What are the seeds sown?



- 「道端に蒔かれたもの」とはどのような人だと言っていますか。What are the seeds sown along the path like?



- 「石だらけの所に蒔かれたもの」とはどのような人だと言っていますか。What are the seeds sown on rocky ground like?



- 「茨の中に蒔かれたもの」とはどのような人だと言っていますか。What are the seeds sown among the thorns like?



- 「良い土地に蒔かれたもの」についてはどのように書かれていますか。What are the seeds sown on good soil like?



- 結局、ここでは何が教えられているのでしょうか。What is the message of this parable?



- 種がみことば以外のものをも表しているとすると、それは、どのような可能性があるでしょうか。If the seeds sown represents something else as well, what are the possibilities?







### マタイによる福音書 Matthew 13:24 - 43



- 24節から43節には三つの譬えが書かれていますが、これらは何についてのたとえですか。There are three parables in 24 - 43. What are the topics?



- 毒麦のたとえでは、どんなことがおきますか。What happens in the parable of the weeds?



- 天の国はからし種に似ている、と言われていますが、どんなところが似ているのでしょう。

Jesus says ''The kingdom of heaven is like a mustard seed.'' Which characteristic of mustard seeds is similar to the kingdom of heaven?



- 天の国はパン種に似ている、と言われていますが、どんなところが似ているのでしょう。

Jesus says ''The kingdom of heaven is like yeast.'' Which characteristic of yeast is similer to the kingdom of heaven?



- 「からし種」と「パン種」のたとえから、天の国についてどんなことが分かりますか。What can you tell about the kingdom of heaven by the parables of a mustard seed and yeast?





- 34, 35節では、イエスがたとえで語る理由をどのように言っていますか。Why does Jesus tell in parables? (v 34, 35)



- 解き明かしはどのような時になされましたか。When does Jesus explain the meaning of the parable?



- 37節からの解き明かしによると、たとえで語られているものは、それぞれ何に対応していると言っていますか。By Jesus' explanation, who is the sower, the field, the good seed, the weeds, the devil, the harvest and the harvesters?



- 世の終わりにはどのようになると言っていますか。What happens at the end of the age?



- これらのたとえは、いまを生きる私たちに何を言っているのでしょうか。What is the message of these parables to us?







### マタイによる福音書 Matthew 13:44 - 52



- 44節から50節には三つの譬えが書かれていますが、これらは何についてのたとえですか。There are three parables in 44 - 50. What are the topics?



- 宝が隠されている畑をみつけたひとはどうすると言っていますか。When a man found treasure hidden in a field, what does he do?



- このたとえは、天の国について、どのようなことを言っているのでしょうか。What does this parable tell about the kingdom of heaven?



- 高価な真珠を見つけた商人は、どうすると言っていますか。When a merchant found a pearl of great value, what does he do?



- 高価な真珠をみつけたひとのたとえから天の国についてどのようなことがわかりますか。What does the parable of a merchant looking for fine pearls tell about the kingdom of heaven?





- 網をおろして漁をするたとえでは、天の国について何を伝えていますか。What does the parable of the net tell about the kingdom of heaven?



- 毒麦のたとえも、世の終わりについて語られていましたが、網をおろして漁をするたとえと何が同じで、何が違うでしょうか。Parable of the weed also tells about the end of the age. What are the similarities and differences?



- 天の国のことを学んだ学者はどのようなものだと言っていますか。What is the teacher of the law who learned the kingdom of heaven like?



- イエスは、天の国について、いくつかの譬えで語られました。どのようなことがわかりますか。What do we understand the kingdom of heaven?







### マタイによる福音書 Matthew 13:53 - 58



- イエスは、たとえを語り終えてから、どこへ向かいますか。After Jesus finished these parables, where did he go?



- イエスは、郷里で何をしますか。What did he do in his hometown?



- 郷里のひとは、何に驚いていますか。What are the people of Jesus' hometown amazed at?



- 郷里の人はイエスについて何を知り、なにを知りませんか。What do they know, and what do they not know?





- なぜ、郷里や、家族は簡単には受け入れられないのでしょうか。Why do they not accept Jesus?



- イエスはこれに対してどのように言っていますか。How does Jesus respond to this?



- なぜ、イエスは、あまり奇跡をなさらなかったのでしょうか。Why did Jesus not do many miracles there?



- この前の譬えと比較してみましょう。なぜ、このひとたちには、隠されていたのでしょうか。Recall the preceding parables. Why do the treasures hidden to these people?





## マタイによる福音書　第14章

### マタイによる福音書 Matthew 14:1 - 12, 13



- 領主ヘロデはイエスについてどのように思っていますか。Who does Herod think of Jesus?



- なぜ王は、イエスがヨハネの生まれ変わりだと思ったのでしょうか。Why did Herod the tetrarch think that Jesus is John the Baptist risen from the dead?



- 領主ヘロデはなぜヨハネを牢に入れましたか。Why did Herod the tetrarch put John the Baptist into prison?



- なぜ、ヘロデはヨハネを殺す決断をしたのでしょう。Why did Herod the tetrarch make decision to kill John the Baptist?





- なぜ、王は心を痛めたのでしょうか。Why was Herod the tetrarch distressed?



- マルコによる福音書 6章14節から20節には、どのように書かれていますか。What is written in Mark 6:14 - 20.



- なぜヘロデは、ヨハネを、イエスを受け入れられなかったのでしょうか。Why do you think Herod could not believe in neither John the Baptist nor Jesus?



- イエスはなぜ人里離れたところに退かれたのでしょうか。Why did Jesus withdraw from there? (v13)







### マタイによる福音書 Matthew 14:13 - 21



- イエスはなぜ人里離れたところに退かれたのでしょうか。Why did Jesus withdraw from there?



- 群衆は何を求めてイエスの後を追いかけたのでしょうか。Why did the crowds follow Jesus?



- イエスは大勢の群衆をみてなぜ深く憐れまれたのでしょうか。Why did Jesus have compassion on the crowds?



- 弟子たちはどのような進言をイエスにし、イエスはそれにどう答えますか。What proposal did disciples make to Jesus, and how did Jesus respond?



- 弟子たちはどのような情報をイエスに伝えますか。What did the disciples tell Jesus?





- イエスはどうしますか。What did Jesus do?



- どうなったと書かれていますか。What were the results?



- 他の福音書の記事から情報を得てみましょう。Get information from other gospels. (Mark 6:30 - 44, Luke 9:10 - 17, John 6:1 - 15)



- この記事からなにを伝えようとしているのでしょうか。What do the gospel writers want to communicate to us?







### マタイによる福音書 Matthew 14:22 - 33



- 「それからすぐ」イエスは群衆や弟子たちをどうしますか。What did Jesus do with the crowds and his disciples immediately after the previous event?



- イエス自身はどうしますか。What did Jesus do?



- 舟に乗った弟子たちにはどのようなことが起こりますか。What happened to the disciples on the boat?



- イエスはどうしますか。What did Jesus do?



- イエスをみて弟子たちはどのような反応をしますか。What were the responses of the disciples when they saw Jesus?



- 怯えている弟子たちに、イエスはどのように話しかけますか。What did Jesus do to the terrified disciples?





- ペテロはどうしますか。イエスはどう応じられますか。What did Peter say? How did Jesus respond to Peter?



- どうなりますか。What happened?



- 舟にいた人たちはどうしますか。What did the people on the boat do?


### マタイによる福音書 Matthew 14:34 - 36



- 一行が舟からあがるとどのようなことが起こりますか。What happened when they landed?


- ひとびとはイエスに何を求めているのでしょうか。What did the crowds want?



## マタイによる福音書　第15章
### マタイによる福音書 Matthew 15:1 - 20


- どのような人がイエスのもとに来ますか。Who come to Jesus?



- どのような質問をしますか。What are their questions?



- イエスはどのように答えますか。How does Jesus reply to them?



- イザヤ書の言葉は、どんなことを言っていますか。What is the message of Isaiah?





- イエスは群衆になにを伝えますか。What does Jesus tell the people to do?



- 弟子たちは、なにをイエスに伝え、イエスはそれにどう答えますか。What is the disciples' report? What does Jesus reply to them?



- ペテロの質問に、イエスは譬えについてどのように説明しますか。



- イエスの言う「人を汚す」とはどういうことなのでしょうか。What does Jesus mean by 'defiling a person'?



- イエスは律法の汚れに関する規定を否定しているのでしょうか。Does Jesus nullify the regulations concerning 'defiling a person' in the law?







### マタイによる福音書 Matthew 15:21 - 28



- 地図でティルスとシドンの場所を確認してみましょう。Find Tyre and Sidon in a map.



- 女のひとはなにをどのように訴えますか。What and how does this woman ask for?



- イエスは最初どうしますか。弟子たちはどうしますか。How does Jesus reply? What do the disciples do?



- 24, 26節を見てみましょう。イエスはなぜこのように答えるのでしょうか。Read verses 24 and 26. What do you think about Jesus' response?





- それに対して、カナンの女は 25, 27節で、どのように答えていますか。Read verses 25 and 27. What is the response of this woman? What do you think?



- イエスは最後にどのように答えますか。What does Jesus tell the woman in verse 28?



- あなたが弟子のひとりとしてその場にいたとしたらどんなことを感じ、学んだと思いますか。Suppose you are a disciple attending there. What do you think you feel and learn?




### マタイによる福音書 Matthew 15:29 - 31



- イエスはどこからどこに移動していますか。Where is Jesus? Where does he travel?



- どのような人がイエスのもとに来ますか。イエスはどうしますか。Who come to Jesus? What does he do to them?



- 群衆はどのような反応をしますか。What reaction do the crowd have?




### マタイによる福音書 Matthew 15:31 - 39



- どんな問題が起こりますか。イエスは、弟子たちにどのように言いますか。What happens? What does Jesus tell his disciples?



- 弟子たちはどのように答えますか。What do disciples reply?





- イエスは、弟子たちにどのように聞きますか。弟子たちはどう答えますか。How does Jesus ask his disciples? What is their response?



- イエスはどのように指示し、どうしますか。What is Jesus' instruction? What does Jesus do?



- 結果はどうなりすか。What is the result?



- 14:13-21 の記事と比較してみましょう。Compare with Mt 14:13-21?




## マタイによる福音書　第16章

### マタイによる福音書 Matthew 16:1 - 4



- どのようなひとたちがイエスのもとに来て、イエスに何を求めますか。それは、なぜですか。Who come to Jesus? What do they ask Jesus? Why?



- イエスはどのように答えますか。How does Jesus reply?



- 「ヨナのしるし」とは何をさしているのでしょうか。What is the sign of Jonah?



- 現代のひとには、イエスはどのように語られるでしょうか。What is the message of Jesus to the people of our age?







### マタイによる福音書 Matthew 16:5 - 12



- 弟子たちには、どのような問題がおこっていましたか。What is the problem Jesus' disciples have?



- イエスは弟子たちにどのように言いますか。そして、弟子たちは、それをどう理解しますか。What does Jesus say to his disciples? What do the disciples think?



- イエスは、どのような過去のできごとを弟子たちに思い出させますか。What does Jesus want his disciples to recall?



- 弟子たちは、どのようなことだと悟りますか。What do the disciples understand?



- 注意すべき「ファリサイ派とサドカイ派の人々の教え」とは何でしょうか。What are the teaching of the Pharisees and Sadducees disciples have to be careful of?







### マタイによる福音書 Matthew 16:13 - 20



- どこでのできごとですか。地図を見て確かめてみましょう。Where does this event happen? Consult your map.



- イエスはまずどのように弟子たちに尋ねますか。What is Jesus' first question to his disciples?



- 弟子たちはどのように答えますか。What are their answers?



- イエスは次にどのように弟子たちに質問しますか。What is the next question of Jesus?



- これに対してだれがどのように答えますか。Who responds to Jesus' question? What is his answer?





- イエスは、ペトロにどのように、答えますか。How does Jesus respond to Peter?



- この岩の上に教会を建てるとはどのような事でしょうか。What does it mean to say ''on this rock I will build my church''?



- イエスが与えるという鍵はどのようなものですか。What is the key given by Jesus?



- 他の弟子たちは、どう聞いていたでしょうか。ペテロだけ特別なのでしょうか。What do you think other disciples are thinking about? Is Peter special?



- なぜ、イエスは、自分がメシアであることをだれにも話さないようにと言ったのでしょうか。Why does Jesus order his disciples not to tell anyone that he is the Messiah?







### マタイによる福音書 Matthew 16:21 - 28



- 21節の「このときから」とはどのような時のことですか。What refers to ''From that time on'' in verse 21?



- イエスは弟子たちにどのようなことを打ち明け始めますか。What does Jesus begin to explain to his disciples?



- これを聞いて、ペトロはどうしますか。What does Peter do?



- イエスはどうしますか。How does Jesus respond?





- 自分を捨て、自分の十字架を負って従うとはどのような事でしょうか。What do you think ''deny themselves and take up their cross and follow me.'' is?



- ここでいわれている「自分の命」とは何でしょうか。What is ''one's life''?



- 「行いに応じて報いる」とはどのような行いのことでしょうか。What does it mean by ''he will reward each person according to what they have done.''?



- 28節のことばはなにを言っているのでしょうか。すでに、そのときは、来たのでしょうか。What does verse 28 say?







## マタイによる福音書　第17章

### マタイによる福音書 Matthew 17:1 - 13



- イエスは誰を連れて山に登りますか。Who does Jesus invite to go up onto a mountain?



- イエスはどのように変貌しますか。How does Jesus change?



- だれがイエスと語り合っていますか。Who are talking with Jesus?



- どのような声が聞こえてきますか。What do they hear?



- この声を聞いて、弟子たちはどうしますか。また、イエスはどうしますか。What do the disciples do? What does Jesus do to his disciples?





- イエスは弟子たちにどのようなことを注意しますか。What does Jesus warn his disciples?



- 弟子とイエスはどのようなことについて語りますか。What do Jesus and his disciples discuss?



- 13節で弟子たちは何を悟ったと書いてありますか。What do the disciples understand in verse 13?



- このできごとは、弟子たちにとって、どのような意味があったでしょうか。What does this mean to his disciples?







### マタイによる福音書 Matthew 17:14 - 21



- この人は、イエスにどんなことを訴えますか。What does this person ask Jesus?



- イエスは、何を嘆かれますか。What does Jesus' feel sad?



- イエスはどうしますか。What does Jesus do?



- 弟子たちはどうしますか。What do Jesus' disciples do?





- イエスはどのように答えますか。What is Jesus' answer?



- マルコによる福音書9:14-29 によると、他にどのようなことが分かりますか。What can you tell from Mark 9:14-29?



- マルコと、ルカはそれぞれ何を伝えようとしているのでしょうか。What do you think are the messages of Mrk and Luke?



- 弟子たちに欠けていたのは何だったのでしょうか。どうすれば良かったのでしょう。What should Jesus' disciples have done?









### マタイによる福音書 Matthew 17:22 - 23



- イエスが死と復活について語ったのは二度目ですが、一度目と比較して見ましょう。This is the second time that Jesus tells of his death and resurrection. Compare with the first.



- 前回と今回はそれぞれどのような時だったのでしょうか。Describe the first and the second time when Jesus tells of his death to his disciples.



- 弟子たちの反応はどのように書かれていますか。What is the disciple's response?







%

### マタイによる福音書 Matthew 17:24 - 27



- ペトロは、どこで誰にどんな質問を受けますか。Where and what Peter is asked?



- ペトロはどのように答えますか。What is Peter's answer?





- イエスはペトロにどのような質問をしますか。What is Jesus's question to Peter?



- 「彼らをつまずかせないようにしよう」(v27) とはどのような事でしょうか。What does it mean to say ''so that we may not cause offense''?



- イエスは、ペトロにどんな指示を与えますか。What instruction does Jesus give to Peter?



- この記事は、なにを私たちに伝えようとしているのでしょうか。What is the message of this paragraph?







## マタイによる福音書　第18章

### マタイによる福音書 Matthew 18:1 - 5



- どんなときに、弟子たちの質問が始まりますか。When does this happen?



- 弟子たちはイエスにどのような質問をしますか。What do the disciples ask Jesus?



- イエスはどのようにしますか。What does Jesus do?



- イエスは、どのようなことを弟子たちに告げますか。What does Jesus say?



- 「子供のようになる」とか「わたしの名のためにこのような一人の子供を受け入れる」とはどのようなことを言っているのでしょうか。What does it mean to become like little children, or to welcome one such child in my name?



- なぜ「子供のようになる」とか「わたしの名のためにこのような一人の子供を受け入れる」ことにそれほどの価値があるのでしょうか。Why is it so critical to become like little children, or to welcome one such child in my name?









### マタイによる福音書 Matthew 18:6 - 9



- 6節ではどのような人のことが語られていますか。Who is mentioned in verse 6?



- 人をつまづかせるとはどのような事でしょうか。What does it mean to stumble a person?



- なぜ、8節、9節のように厳しく言っているのでしょうか。Why does Jesus give harsh words in verses 8 and 9?



- 命にあずかるとはどのような事でしょうか。What is to enter life?







%

### マタイによる福音書 Matthew 18:10 - 14



- 10節では「小さな者」についてどのように書かれていますか。What is said about 'little ones'?



- 一匹の迷い出た羊のたとえは、どのような目的のために挿入されていますか。Why is the parable of the wandering sheep inserted?



- 1節から14節で最も大切なことが言われている節を選ぶとするとあなたはどれを選びますか。If you are to select the most important verse, which verse do you select?



- なぜ、へりくだることが大切なのでしょうか。Why we need to be humble to enter the kingdom of God?









### マタイによる福音書 Matthew 18:15 - 20



- ここでは、どのような問題について語られていますか。What is the problem dealt here?



- まず、どのようにするように書かれていますか。What should we do first?



- 「兄弟を得る」とはどのようないみでしょうか。What does it mean to win a brother and a sister over?



- 16節には「聞き入れないとき」どのようにしなさいと書いてありますか。What should we do if they will not listen?



- 17節には「それでも聞き入れなければ」どのようにするように言っていますか。What should we do if they still refuse to listen?





- 18節はどのようなことを言っているのでしょうか。What does verse 18 mean?



- 「二人が地上で心を一つにして求める」とどのようなことが起こると言っていますか。What happens if two of the disciples on earth agree about anything they ask for?



- イエスの名によって集まるところには、イエスもいるとはどのような事でしょうか。What does it mean that ''For where two or three gather in my name, there am I with them''?



- ここのコンテクストで考えるなら、どんな「罪」が想定され、そしてどんな、ことをこころをあわせていのるのだろうか。From context what should we pray?









### マタイによる福音書 Matthew 18:21 - 35



- ペトロはイエスにどんな質問をしますか。What is the question of Peter to Jesus?



- イエスは何と答えますか。What is Jesus' response?



- たとえについて考えてみましょう。イエスは何のたとえだと言っていますか。What does Jesus say about this parable?



- たとえの前半部分 23-27 にはどのような事が言われていますか。Explain the first part vs22-27 of this parable.



- たとえの中間部分 28-30 にはどのような事が言われていますか。Explain the second part vs28-30 of this parable.





- たとえの最後の部分 31-34 にはどのような事が言われていますか。Explain the last part vs31-34 of this parable.



- イエスは赦すことについてどんなことを告げていますか。What is the teaching of Jesus about forgiveness?



- 18章全体から考えると、赦しについてのこの箇所からどんなことが語られているのでしょうか。Considering the context in chapater 18, what is the message about forgiveness?







## マタイによる福音書　第19章

### マタイによる福音書 Matthew 19:1 - 12



- イエスはどこに行き、なにをしますか。Where does Jesus go? What does he do?



- だれが、どのような質問をイエスにしますか。Who asks Jesus a question? What is it?



- イエスは、どのように答えられますか。What is Jesus' answer?



- この人たちは、イエスの答えに対してどのような質問をしますか。What do these people respond to Jesus' answer?





- イエスは離縁についてどのように言っていますか。What does Jesus say about divorce?



- 弟子たちは、どのような質問をしますか。What do disciples ask Jesus?



- イエスは、結婚しないことについて、どのように言っていますか。What does Jesus say those who choose to live like eunuchs?









### マタイによる福音書 Matthew 19:13 - 15



- 人々は何の目的で子どもたちを連れてきましたか。Why do the people bring little children to Jesus?



- 弟子たちはどうしますか。How do the disciples respond to them?



- イエスはどうしますか。How does Jesus respond?



- 「天の国はこのような者たちのもの」とはどのような意味でしょうか。What does 'he kingdom of heaven belongs to such as these children'?









### マタイによる福音書 Matthew 19:16 - 30



- この人はイエスにどんな質問をしますか。What is the question of this man?



- イエスはどのように答えますか。What is Jesus' answer?



- どの掟かとの質問にイエスはどのように答えますか。How does Jesus reply when the man inquires "Which commandments?"



- 20節のこの人の言葉からどのようなことが分かりますか。What can you tell from this man's reply in verse 20?





- イエスは21節でこの人にどのように答えますか。What does Jesus say to this man?



- この人が持ち物を売り払い、貧しい人々に施すとどうなったと思いますか。What do you think happens if this man sells his possessions and gives to the poor?



- この青年はどうしますか。What does this your man do?



- イエスは弟子たちにどのように告げますか。What does Jesus tell his disciples?





- 弟子たちは、なぜ驚くのでしょうか。Why are the disciples amazed?



- イエスの27節の答えは、何を言っているのでしょうか。What does Jesus' reply in verse 27 mean?



- 幼子と金持ちの青年はなにが違うのでしょうか。What is the difference between little children and this rich man?



- イエスは何と答えますか。What is Jesus' reply?



- 「先にいる多くの者が後になり、後にいる多くの者が先になる。」とはどのような意味でしょうか。What does it mean ''many who are first will be last, and many who are last will be first.''?







## マタイによる福音書　第20章

### マタイによる福音書 Matthew 20:1 - 16



- この主人は、どんな目的のために何をしますか。What does this landowner do? Why?



- 主人は、九時、十二時、三時にどのような事をしますか。What does this man do at 9 in the morning, 12 noon and 3 in the afternoon?



- 五時頃に出会った人はなぜ働いていないのですか。Why is the man the landowner meet at 5 unemployed?



- 主人はどのような順序で給与を払いますか。How does the landowner pay the wage to each worker?



- 最初に雇われた人たちはなぜ不平を言うのでしょう。Why do the workers employed first complain?





- 主人は、それにどのように応答していますか。What is the response of the landowner?



- どのような事を教える譬えだと言っていますか。What is this parable for?



- 弟子たちは、この譬えからなにを学んだでしょうか。What do you think Jesus' disciples learn from this parable?



- あなたは、この主人について、どのようなことを思いますか。What do you think about this landowner?



- 結局、16節の「先の者」「後の者」はどのようなひとを指しているのでしょうか。Who are the last and who are the first in verse 16.









### マタイによる福音書 Matthew 20:17 - 19



- いつ、だれに、どのようにして、エルサレムでのことを話しますか。When, how and to whom does Jesus tell what happens in Jerusalem?



- イエスはどのような事を告げますか。What does Jesus tell his disciples?



### マタイによる福音書 Matthew 20:20 - 28



- どのようときに、だれがイエスのもとに来ますか。Who comes to Jesus? What happens?



- この人はなにを願いますか。What does this person ask Jesus?



- イエスはどのように答えますか。What is Jesus' response?





- イエスの杯を飲むとはどのようなことを意味しているでしょうか。What does it mean to drink Jesus' cup?



- ほかの弟子はどのような反応をしますか。What do other disciples do?



- 弟子たちは、どうすべきだと言っていますか。What should the disciples do?



- イエスは何のために来たと言っていますか。What is the purpose of Jesus' life?



- 身代金として命を捧げるとはどういうことでしょうか。What does it mean to dedicate his life for the ransom of many?









### マタイによる福音書 Matthew 20:29 - 34



- どこでなにが起きますか。What happens? Where does this happen?



- マルコ、ルカの記事と比較して見ましょう。Compare this story with those in Mark and Luke.



- なぜ、群衆は、この人たちを黙らせようとするのでしょうか。Why do the people stop these blind men?





- イエスはどのような質問をし、この人たちはどう答えますか。What does Jesus ask them? What is the response of these men?



- イエスはどうしますか。そして、この人たちはどうしますか。What does Jesus do? What do they do?



- あなたは、なにかイエスに求めるものがありますか。Do you have anything to ask for Jesus?







## マタイによる福音書　第21章

### マタイによる福音書 Matthew 21:1 - 11



- イエスはどこでどのような指示を弟子たちにしますか。What does Jesus instruct his disciples, and where?



- イエスと村の人の間には事前に打ち合わせがあったのでしょうか、無かったのでしょうか。Do you think that Jesus had communication with the villagers in advance?



- 5節の引用は「王」についてイエスについて、どのような事を伝えていますか。What does the verse 5 describe about the King and Jesus?



- イエスはどのようにしてエルサレムに入城しますか。How does Jesus enter Jerusalem? Describe it.





- 群衆はどのようにし、そして叫びますか。How do the crowds do and what do they shout?



- エルサレムの人たちに対して、群衆はどのようにイエスを紹介しますか。How do the crowds introduce Jesus to the people of Jerusalem?



- イエス、弟子たち、イエスを出迎えた群衆、エルサレムの人たち、それに答えた群衆は、それぞれこのことをどのように捉えていたのでしょうか。How do they see this entry, Jesus, his disciples, the welcoming crowds, the people of Jerusalem, and the crowds responded?









### マタイによる福音書 Matthew 21:12 - 17



- イエスは境内でどのようなことをしますか。What does Jesus do in the temple?



- イエスはどのように言いますか。What does Jesus say?



- イエスは境内で次になにをしますか。What does Jesus do next in the temple?



- 祭司長や律法学者たちは、何に腹を立てますか。What do the chief priests and the scribes get angry at?





- なぜ腹を立てるのでしょうか。Why are they angry?



- イエスは、どのように答えますか。How does Jesus respond?



- イエスは神殿とはどのようなものだと伝えようとしているのでしょうか。What is Jesus' message about the temple of God?



- イエスはどのあとどうしますか。What does he do after this?









### マタイによる福音書 Matthew 21:18 - 22



- これはいつどのようなときのできごとですか。When does this happen?



- いちじくとはどのような木でしょうか。What is fig tree?



- イエスは実のないいちじくの木に対してどのように言われますか。そしてどうなりますか。What does Jesus say to the fig tree without fruits? What happens to the fig tree?



- 役に立たないものは滅ぼされるということでしょうか。Does this mean that useless will perish?





- 弟子たちの質問にイエスはどのように答えますか。How does Jesus respond to the question of his disciples?



- 山に『立ち上がって、海に飛び込め』といえば本当に、そのとおりになるのでしょうか。If we say to the mountain 'Be taken up and thrown into the sea,' will it really happen?



- 「山」を動かすことが全く不可能に見えることを意味しているとすると、ここではどのようなことを意味してイエスは言われたと思いますか。If moving the mountain means something impossible, what do you think Jesus has in mind here?



- イエスはここで何を教えているのでしょうか。What is the Jesus' teaching here?









### マタイによる福音書 Matthew 21:23 - 27



- どのようなときに、誰が、どのような質問をしますか。When and who ask Jesus, and what is the question?



- イエスはどのように答えますか。How does Jesus respond?



- これに対して、この人たちはどうしますか。How do they argue and respond?



- イエスはなぜ答えないのでしょうか。Why does not Jesus answer?









### マタイによる福音書 Matthew 21:28 - 32



- このたとえは、どのような場で、誰に対して語られていますか。When and to whom is this parable spoken?



- どのような話しですか。まとめてみましょう。What is the story?



- イエスはたとえを話したあとどのような質問をしますか。そしてそれに、この人たちはどう答えますか。What is the question of Jesus to these people? What is their response?



- イエスはこのたとえをつかってどのような説明をしますか。What message does Jesus relate to them using the parable?



- イエスが伝えたかったメッセージは何なのでしょうか。What is the message Jesus wants to tell?









### マタイによる福音書 Matthew 21:33 - 46



- どのような人たちとのやりとりの後にこのたとえが語られますか。What are the topics of the preceding dialogues and who are the people discussing?



- たとえの登場人物をあげてみましょう。List who are in the parable.



- 主人はどのようなことをしていますか。What does the lord do?



- 農夫たちはどうしますか。What do the farmers do?





- たとえの最後にイエスはどのような質問を投げかけますか。そしてこの人たちはどう答えますか。What does Jesus ask at the end of the parable? What is their answer?



- イエスは聖書を引用してどのようなことを伝えますか。What is the message of Jesus by a quotation of the Bible?



- この人たちはどうしますか。What is their response?



- イエスはこのたとえで、何を伝えているのでしょうか。What are the messages of Jesus?







## マタイによる福音書　第22章

### マタイによる福音書 Matthew 22:1 - 14



- このたとえは、いつ、どのようなときに、だれに対して話されましたか。When and to whom does Jesus speak of this parable?



- 前半（2節から7節）ではどのようなことが語られていますか。Describe the first half (vs 2-7) of the story?



- いままでのたとえから考えるとたとえの登場人物はそれぞれどのような人たちを表しているのでしょうか。Based on the previous parables, who are the corresponding people in this parable?



- 婚宴に来ようとしない人々にこの王はまずどうしますか。What does the king do to those who are not willing to come?



- 招かれた人たちは、どのような理由から、婚宴に出席しないのでしょうか。Why don't they come to the banquet?





- 王はなぜこの人たちを滅ぼしてしまうのでしょうか。Why does the King murder them?



- 王はそれからどのような人を招きますか。The who does the King invite?



- 婚礼の礼服を着ていない人とはどのような人のことを言っているのでしょうか。Who are those without wedding clothes?



- ぶどう園の農夫のたとえと似ていますが、どのような事が同じで、どのような新しいことが加わっていますか。Compare with the parable of tenants. What are the differences?



- イエスは、このたとえで、聞いている人たちに、何を伝えようとしているのでしょうか。What is the message of Jesus to each of them there?









### マタイによる福音書 Matthew 22:15 - 22



- 誰がどのような計略を企てますか。Who plot against Jesus, and what?



- 彼らの弟子たちがヘロデ党の人々と一緒に行ったのは何故でしょうか。Why do their disciples go along with the Herodians?



- どのような質問をしますか。What is their question?



- この人たちはどのような答えを期待していたのでしょうか。What answer do they expect from Jesus?



- イエスはどうしますか。How does Jesus respond to them?





- 最後にイエスはどのように答えますか。What is Jesus' answer to their question?



- イエスの答えからすると、イエスは最初のこの人たちの質問に対してはどのように言っているのでしょうか。From Jesus' response, what is his answer to their question?



- 神のものを神に返すとはどのような意味でしょうか。What does it mean to give back to God what is God's?



- 彼らの反応はどのようなものでしたか。What is their response?









### マタイによる福音書 Matthew 22:23 - 33



- いつ、どのような人が、イエスに質問をしますか。When and who ask Jesus a question?



- どのようなモーセのことばに言及していますか。What do they quote from Moses?



- この人たちの質問はどのようなものですか。What is their question?



- この人たちはなぜこのような質問をするのですか。Why do they ask this question?





- イエスはどのように答えますか。What is Jesus' response?



- イエスは旧約聖書からの引用でなにを伝えようとしているのでしょうか。What does Jesus tell them by quoting from the Bible?



- イエスの「神は死んだ者の神ではなく、生きている者の神なのだ。」は何を伝えているのでしょうか。What does Jesus want to communicate with them by saying ''He is not the God of the dead but of the living''?



- 人々の反応はどのようなものでしたか。そしてそれはなぜでしょう。What is the result?









### マタイによる福音書 Matthew 22:34 - 40



- ファリサイ派の人たちは、どのような目的で集まったのでしょうか。Why do the Pharisees get together?



- そのうちのひとりは、イエスにどんな質問をしますか。What is the question of an expert in the law among them?



- マルコ12:28-34 と比較して見ましょう。どのような違いがありますか。Compare with Mark 12:28-34. What are the differences?



- イエスはどのように答えますか。What does Jesus respond?



- なぜ最も重要な戒めは一つではなく二つなのでしょうか。なぜ二つとも必要なのでしょうか。Why are there two greatest commandments and not one? Why do we need both?



- 他に重要な戒めについての問答を知っていますか。Do you know any other discussion on the greatest commandments?



- 「律法全体と預言者は、この二つの掟に基づいている。」とはどのような意味でしょうか。What does ''All the Law and the Prophets hang on these two commandments.'' mean?









### マタイによる福音書 Matthew 22:41 - 46



- 聴衆はどのような人たちですか。Who are the audience?



- イエスはどのような質問をし、彼らはどう答えますか。What is Jesus's question and what is their answer?



- イエスはどのように答えますか。How does Jesus respond?



- イエスは何を伝えたかったのでしょうか。What does Jesus want to teach them?



- 結果としてどうなりましたか。What is the result?







## マタイによる福音書　第23章

### マタイによる福音書 Matthew 23:1 - 12



- 聴衆はどのような人たちですか。Who is the audience?



- 「モーセの座についている」とはどのような意味でしょうか。What does ''sit in Moses' seat'' mean?



- 「彼らの行いは、見倣ってはならない。言うだけで、実行しないからである。」とはどういうことでしょうか。何を行い、何を実行していないのでしょうか。What does ''You must be careful to do everything they tell you. But do not do what they do, for they do not practice what they preach.'' mean? What do they do and what don't they do?



- 4節ではどのようなことを批判しているのでしょうか。What does Jesus point out in verse 4?





- 5節から7節ではどのような批判をしていますか。What does Jesus point out in verses 5 to 7?



- 8節から10節でイエスは何を伝えようとしているのでしょうか。What is the Jesus' message in verses 8 to 10?



- なぜ仕えることがたいせつなのでしょうか。Why will the greatest be a servant?



- この箇所で、イエスはどのような生き方に対して警告し、どのような生き方を指し示しているのでしょうか。What does Jesus critices here? How should we live?









### マタイによる福音書 Matthew 23:13 - 33



- これらは誰に対して嘆いていますか。To whom is Jesus giving words of warnings?



- どのような事を嘆いていますか。いくつかに分けることができますか。What is Jesus warning these people about? Can you classify them?



- 「自分が入らないばかりか、入ろうとする人をも入らせない。」とは実際にどのようなことをしていたのでしょうか。What does ''You yourselves do not enter, nor will you let those enter who are trying to. '' mean? What are they doing?



- 「ものの見えない者たち」（口語・新改訳：盲目な案内者たち）は、何が見えていないのでしょうか。What can't these people see?





- 内側のことが言われていますが、なにを指摘しているのでしょうか。What does Jesus point out by cleaning inside?



- 「預言者の墓を建てたり、正しい人の記念碑を飾ったり」するのは良くないことなのでしょうか。Is it not good to ''build tombs for the prophets and decorate the graves of the righteous"?



- どうしたら「地獄の罰を免れること」ができるのでしょうか。How is it possible to ''escape being condemned to hell"?



- 偽善とは何でしょうか。What do you think is hypocrisy?









### マタイによる福音書 Matthew 23:32 - 39



- 32節の「32:先祖が始めた悪事の仕上げをしたらどうだ。（口語 (v32)：あなたがたもまた先祖たちがした悪の枡目を満たすがよい。 ）」とはどのような意味でしょうか。What does verse 32 ''Go ahead, then, and complete what your ancestors started!'' mean?



- 前の文章とはどのようにつながっていますか。「だから」とはどういうことですか。How is the verse 34 related to 32-33 by the word 'therefore'?



- 34節ではどんなことが起こると言われていますか。According to verse 34, what will happen?



- アベルの血からゼカルヤの血とはどのようなものでしょうか。What does 'the blood of righteous Abel and Zecharia'?



- 「これらのことの結果はすべて、今の時代の者たちにふりかかってくる」とはどういう意味でしょうか。What does verse 36 'all this will come on this generation' mean?



- エルサレムについてどんなことを嘆いていますか。What does Jesus say about Jerusalem in verse 37?





- 「めん鳥が雛を羽の下に集めるように、わたしはお前の子らを何度集めようとしたことか。」はどんなことを言っていますか。What does 'a hen gathers her chicks under her wings' mean?



- 「お前たちの家」は何のことでしょうか。What does 'your house' mean?



- これでおしまいなのでしょうか。Is there no hope?







## マタイによる福音書　第24章

### マタイによる福音書 Matthew 24:1 - 2



- 弟子は、なぜ、神殿の建物を指さしたのでしょうか。Why do you think Jesus' disciples called his attention to the buildings of the temple.



- イエスは神殿について何と言っていますか。What does Jesus prophesy against the temple?



- イエスはなにを伝えようとしているのでしょうか。What is the message of Jesus?









### マタイによる福音書 Matthew 24:3 - 14



- どのような状況で、だれが質問をしますか。When does it happen? Who ask a question?



- どんな質問をしますか。What is the question?



- イエスはまずどのように注意しますか。What is Jesus' response?



- 「産みの苦しみの始まり」としてどのようなことが起こると言っていますか。As ''the beginning of the birth pains" what would happen?



- 弟子たちに対してはどのようなことが起こると言われていますか。What happens to the dsciples?





- 偽預言者とはどのような人でしょうか。Who are false prophets?



- なぜ愛が冷えるのでしょうか。Why would the love of most grow cold?



- 堪え忍ぶとは、どのようなことでしょうか。What does 'stand firm' mean?



- 「御国のこの福音が証として宣べ伝えられる」とはどのような意味でしょうか。What does 'this gospel of the kingdom will be preached as a testimony' mean?



- なぜ福音が全世界に宣べ伝えられまで、終わりは来ないのでしょうか。Why do the people have to wait until the gospel of the kingdom will be preached in the whole world?









### マタイによる福音書 Matthew 24:15 - 28



- 「憎むべき破壊者が立ってはならない所に立つのを見たら」は具体的な事件を指しているのでしょうか。Does ''standing in the holy place 'the abomination that causes desolation''' indicate a specific historical incidence?



- これが70年のエルサレムの破壊を意味しているとすると、何を教えようとしているのでしょうか。If this relates to the destruction of Jerusalem in 70, what is the message Jesus wants to tell?



- エルサレムの破壊以降の人には、どのような意味があるのでしょうか。What is the message to the people after the destruction of Jerusalem?



- どのような備えが必要なのでしょうか。How should we prepare for the end?



- 人の子はどのように来ると言っていますか。How will the coming of the Son of Man occur?









### マタイによる福音書 Matthew 24:29 - 31



- 人の子が現れる徴としてどのようなことが起こると言われていますか。What will come about as the sign of the Son of Man?



- 人の子が来ることは、人々にとって悲しい事なのでしょうか。Why do the people of the earth mourn when they see the Son of Man coming?



- 31節では、人の子が来るときに起こることについてどのように述べていますか。In verse 31, how is the coming of the Son of Man described?



- 弟子たちの問いに関するイエスの答えは、どのようなものだったのでしょうか。What is the answer to the question of the disciples in verse 3?









### マタイによる福音書 Matthew 24:32 - 35



- いちじくの木から学ぶべきことは何ですか。What lesson do we learn from the fig tree?



- 33,34 節の「これらのこと」とは何を指しているのでしょうか。What are 'all these things' in verses 33 and 34?



- 「天地が滅びるが、わたしの言葉は決して滅びない」とはどのような意味でしょうか。What does 'my words will never pass away' mean when heaven and earth passes away?









%

### マタイによる福音書 Matthew 24:36 - 44



- 「その日、その時」とはどんな時のことですか。What is 'that day or hour'?



- 32節,33節では「その時」が分かると言っているのではないでしょうか。Why cannot we tell that day, when we know that he is at the door? See verses 32, 33.



- 「ノアの時と同じ」とありますが、どのように同じなのでしょうか。In what point, it is in the days of Noah?



- ノアの時代の人たちは何を知らされており、何を理解していなかったのでしょうか。What do the people know in the days of Noah, and what do they not understand?



- 目を覚ましているとか、用意しているとはどのようなことを言っているのでしょうか。What does it mean to 'keep watch' or 'be ready'?









### マタイによる福音書 Matthew 24:45 - 51



- 「忠実で賢い僕」とはどのような人だと言っていますか。Who is the faithful and wise servant?



- この僕はどのようにされると言ってますか。What is his reward?



- 「悪い僕」についてはどのようなことが書かれていますか。



- 「偽善者たちと同じ目に遭わせる」とはどのようなことを言っているのでしょうか。What does 'he will cut him to pieces and assign him a place with the hypocrites' mean?



- 私たちの生き方・備えについて言っているとすると、どのようなことをイエスは教えているのでしょうか。What is the message of Jesus to us?







## マタイによる福音書　第25章

### マタイによる福音書 Matthew 25:1 - 13



- 最初に「そこで」とありますが、どのような話の中でこのたとえが語られていますか。When is this parable given?



- 天の国はどのようにたとえられていますか。What is the king of heaven like?



- たとえのストーリを説明してください。Explain the story of the parable.



- 賢いおとめたちと、愚かなおとめたちの違いはなんですか。What is the difference between the wise and the foolish?





- 花婿は誰のことでしょうか。Who is the bridegroom?



- 油とはいったい何なのでしょうか。What is oil in this parable?



- イエスはなにを伝えようとしているのでしょうか。What is message of this parable?









### マタイによる福音書 Matthew 25:14 - 30



- 天の国はどのようにたとえられていますか。What is the king of heaven like?



- 五タラントン、二タラントン、一タラントン与えられた僕はそれぞれどうしますか。What does the one who receives five talents, two talents, and one talent?



- 主人は、五タラントン、二タラントン預かったものに、それぞれにどのように対応しますか。How does the Lord respond to servants who are entrusted five and two talents?



- 一タラントン預かった僕と他の僕は何が違っていたのでしょうか。What is the difference between the servants received 5 and 2 talents, and the one received one talent?





- 主人は、最後にどのようにこの僕にしますか。How does the Lord deal with this person?



- ルカ19章のムナ（ミナ）のたとえと比較してみましょう。Compare this parable with the parable of Ten Minas in Luke 19.



- タラントンとは何なのでしょうか。What is the talent?



- イエスはなにを伝えようとしているのでしょうか。What is message of this parable?









### マタイによる福音書 Matthew 25:31 - 46



- どのような時のことを語っていますか。When is it?



- だれがどのようにしますか。Who does what?



- 王は、右側にいるひとたちにどのように告げ、その人達はどのように答えますか。What does the king tell the people on the right? What do they respond?



- 王は、左側にいるひとたちにどのように告げ、その人達はどのように答えますか。What does the king tell the people on the left? What do they respond?





- 「飢えていたとき」「のどが渇いていたとき」「旅をしていたとき」「裸のとき」「病気のとき」「牢にいたとき」でなにを表しているのでしょうか。What do 'hungry', 'thirsty', 'being a stranger', 'needed clothes', 'sick', 'in prison' represent?



- 「わたしの兄弟であるこの最も小さいものの一人」とはどのような人のことを言っているのでしょうか。Who is the one of the least of these brothers and sisters of mine?



- 羊と山羊を分けるかぎとなることは何ですか。What is key to separate the sheep from the goats?



- イエスはなにを伝えようとしているのでしょうか。What is message of this parable?







### マタイによる福音書 25章（Part II）



- 最初のたとえで言われている「賢さ」とはどのようなものなのでしょうか。



- 二つめのたとえで言われている「忠実さ」とはどのようなものなのでしょうか。



- 三番目の話しでは、どのような生き方が問われているのでしょうか。



- イエスが最後の三つのメッセージで伝えてたかったのは何なのでしょうか。



- キリストが世の終わりにもう一度来られることがなければ、ここで語られていることは意味がないのでしょうか。






## マタイによる福音書　第26章


### マタイによる福音書 Matthew 26:1 - 5



- イエスは、弟子たちに、どのような時に、どのようなことを伝えますか。When and what does Jesus tell his disciples?



- 同じ頃、祭司長たちや、民の長老たちは、どのようなことを話しますか。About the same time, what do the chief priests and the elders of the people discuss?



- なぜ、祭りの間は避けようとするのでしょうか。Why don't they avoid doing it during the festival?





### マタイによる福音書 Matthew 26:6 - 13



- いつ、どこで、どのようなことが起きますか。What does it happen? When and where is it?



- 他の福音書の記事と比較してみましょう。Compare this with the story in other gospels?





- 女性はなぜ油を注いだのでしょうか。Why does this woman pours very expensive perfume on Jesus's head?



- 女性の行為に対して、だれがどのようなことを言いますか。Who say what against this woman?



- イエスはなんと言われますか。What does Jesus tell them?



- 13節にあるように、なぜそれほどまでに、この女の行為は記念として語り伝えられると言っているのでしょうか。Why will this woman's action to be told?



- わたしたちには、どのような価値判断が必要なのでしょうか。What is valuable to us?









### マタイによる福音書 Matthew 26:14 - 16



- ユダはどのような時に、どのようなことをしますか。When and what does Judas do?



- ユダの動機は何だったのでしょうか。What makes Judas to betray Jesus?



- ユダはお金をもらってから、どうしますか。What does Judas do after he received money.







### マタイによる福音書 Matthew 26:17 - 25



- 弟子たちは、どのような質問をイエスにしますか。What do the disciples ask Jesus?



- イエスはそれにどのように答えますか。What is Jesus' response?





- 食事の席でイエスはなんと言いますか。What does Jesus say at the table?



- 弟子たちの反応はどのようなものでしたか。What do the disciples react?



- イエスはどのように答えますか。What does Jesus say?



- 「生まれなかった方がよかった」と言うような人生があるのでしょうか。What does it mean to say ''it would be better for hime if he had not been born?"



- ユダとイエスの間のどのような会話が記録されていますか。What does Jesus tell Judas?









### マタイによる福音書 Matthew 26:26 - 30



- イエスは食事のときパンをどのようにして配りますか。How does Jesus give bread to his disciples?



- 杯はどのようにして渡しますか。How does Jesus give a cup?



- 「契約の血」とありますが、どのような契約なのでしょうか。What does the blood of covenant mean?



- 29節は何を伝えているのでしょうか。What does verse 29 mean?



- それからどうしますか。What do they do?









### マタイによる福音書 Matthew 26:31 - 35



- イエスは弟子たちにどのような二つのことを告げますか。What are the two messages Jesus tells his disciples?



- ペトロはどのように言いますか。What does Peter say?



- イエスはペトロにどのように答えますか。What does Jesus say?



- これに対して、ペトロはどのように言いますか。What does Peter say to Jesus?









### マタイによる福音書 Matthew 26:36 - 46



- いつ誰がゲッセマネに行きますか。When and who go to Gethsemane?



- マルコ、ルカと比較して見ましょう。Compare with Mark and Luke.



- イエスは、ペテロ、ヤコブ、ヨハネにどのように言いますか。What does Jesus tell Peter, James and John?



- イエスはどのように祈りますか。How does Jesus pray?





- イエスは何に苦しみ、何を信じ、何を願っていたのでしょうか。What does Jesus want, believe and pray?



- イエスが祈っている間、弟子たちはどうしていますか。What are his disciples doing while Jesus is praying?



- イエスは、三度目に戻ってきて、弟子たちにどう伝えますか。What does Jesus tell as he returns the third time?



- あなたは、イエスの祈りから何を学びますか。What do you learn from Jesus' prayer?









### マタイによる福音書 Matthew 26:47 - 56



- どのような状況でこの場面が始まりますか。When does this happen?



- どのような人たちがどのようにして現れますか。Who come to Jesus and how is it described?



- 他の福音書の記事と比較して見ましょう。Compare with other gospels.



- ユダはどのようにイエスに近づきますか。How does Judas come to Jesus?



- イエスはどのように答えますか。How does Jesus reply?





- 人々がイエスを捕らえようとするときどのようなことが起きますか。What happens when the people are trying to arrest Jesus?



- イエスは剣で立ち向かったひとにどのように告げていますか。What does Jesus tell the one who fights with a sword?



- イエスは、群衆にはどのように言われますか。What does Jesus tell the people?



- 弟子たちはどうしますか。What do the disciples do?



- イエスはなぜ、自分の身を任せたのでしょうか。Why does Jesus give himself to the people?



- イエスは何を願っていたでしょうか。What does Jesus wish as he is arrested?









### マタイによる福音書 Matthew 26:57 - 68



- イエスはどこに連れて行かれますか。そこには誰がいますか。After arrested, where do the people take Jesus?



- だれが付いていきますか。Who follows after the people?



- 他の福音書の記事と比較して見ましょう。Compare with other gospels.



- 最高法院ではどのようなことをしていますか。What are the high priests and the Sanhedrin trying to do?

	

- イエスは「神の神殿を打ち倒し、三日あれば建てることができる」と言っていたというのは真実ですか。Is it true that Jesus told that he is able to destroy the temple of God and rebuild it in three days?





- イエスはなぜ黙っていたのでしょうか。Why does Jesus remain silent?



- 大祭司はどのように質問しますか。What is the question of the high priest?



- イエスはどのように答えますか。How does Jesus reply?



- なぜイエスのことばが神を冒涜することなのでしょうか。Why is what Jesus said blasphemy?



- イエスはどのようにされますか。Why happens to Jesus?









### マタイによる福音書 Matthew 26:69 - 75



- このことはいつ起こりますか。When does this happen?



- ペテロはどこにいますか。Where is Peter?



- 他の福音書の記事と比較して見ましょう。Compare with other gospels.



- 最初（69節）では、ペテロに誰がどのように言いますか。ペテロはどう答えますか。In verses 69 and 70, what happens?





- 次（71節）に、誰がどのように言いますか。ペテロはどう答えいますか。In verses 71 and 72, what happens?



- 三度目（73節）には、誰がどのように言いますか。ペテロはどう答えますか。In verses 73 and 74, what happens?



- 鶏が鳴いたとき、ペテロはどうしますか。What happened to Peter when a rooster crowed?



- ペテロはなぜイエスを知らないと言ってしまったのでしょうか。Why does Peter disown Jesus?



- ペテロはなにを学んだでしょうか。What do you think Peter learned?







## マタイによる福音書　第27章

### マタイによる福音書 Matthew 27:1 - 2



- 夜が明けるとどのようなことが起こりますか。What happens early in the morning?




### マタイによる福音書 Matthew 27:3 - 10



- イエスが有罪となったことを知ったユダはどうしますか。When Judas saw that Jesus was condemned, what did he do?



- ユダはイエスが有罪になると考えなかったのでしょうか。





- ユダはどうしますか。What does Judas do?



- ペテロの裏切りを比較して見ましょう。Compare with Peter's betrayal.



- 祭司長たちは、お金をどうしますか。What do the people do with the money?



- 聖書はこの血はだれの血だといっていますか。Whose blood is it?









### マタイによる福音書 Matthew 27:11 - 14



- イエスは誰の前に立っていますか。その人はどのような人ですか。なぜその人の前に連れてこられたのでしょう。Before whom does Jesus stand? What do we know about him? Why is Jesus brought before him?



- その人は何を問い、イエスはどのように答えますか。What does he ask? What does Jesus reply?



- 他の福音書と比較して見ましょう。What do other gospels tell us?



- 告訴理由は何だったのでしょうか。What do they accuse against Jesus?



- イエスはなぜ、祭司長や長老たちの訴えになにも答えないのでしょうか。Why does not Jesus give answer when Jesus is accused by the chief priests and the elders?









### マタイによる福音書 Matthew 27:15 - 26



- バラバはどのような人として登場しますか。Who is Barabas?



- ピラトはイエスをどのように考えていますか。What does Pilate think of Jesus?



- ピラトはなぜ「人々がイエスを引き渡したのは、ねたみのためだと」考えたのでしょう。Why does Pilate think, it was out of self-interest that they had handed Jesus over to him?



- 群衆は、ピラトの言葉に、どのように応答しますか。それは何故ですか。What is the response of the crowd? Why?



- なぜピラトは、十字架につける決断をするのでしょうか。Why does Pilate decide to crucify Jesus?



- イエスはなぜ、十字架にかかることになったのでしょうか。Why is Jesus sentenced to be crucified?









### マタイによる福音書 Matthew 27:27 - 31



- イエスはだれにどこに連れて行かれますか。Who take Jesus to where?



- 兵士たちは、イエスをどのように扱いますか。How do the soldiers treat Jesus?



- このひとたちが、侮辱しようとしているのは、何なのでしょうか。What do they try to mock?



### マタイによる福音書 Matthew 27:32 - 44



- 十字架はだれが担ぐことになりますか。Who take up the cross?



- 他の福音書の記事と比較して見ましょう。Compare with other gospels?





- どこで、どのように、十字架につけられますか。Where do they crucify Jesus? And how?



- イエスの罪状書きは何でしたか。What is Jesus' charge written at the cross?



- イエスと一緒にはどのような人が十字架に架けられますか。Who are crucified with Jesus?



- 人々はそれぞれどのようにイエスをののしりますか。What do the people say to Jesus?



- なぜ人々はののしったり、侮辱したりするのでしょうか。Why do they insult and mock Jesus?



- 聖書記者は何を伝えようとしているのでしょうか。What do the Bible writers tell us?









### マタイによる福音書 Matthew 27:45 - 56



- イエスの死はだれが目撃しますか。Who see the death of Jesus?



- どのようなことが起こりますか。What happens?



- イエスは、何時頃十字架に架けられ、何時頃息を引き取るのでしょうか。About what time is Jesus crucified and what time does he gives up his spirit?



- イエスは何と叫びますか。What does Jesus cry out?



- 人々は、どのような叫びと考えましたか。それは、なぜでしょう。What do the people think of this cry?



- 神はなぜイエスに答えないのでしょう。Why does not God respond to Jesus?



- イエスの最後はどのようなものでしたか。How does Jesus breathe his last?



- どのようなことが起こったと書かれていますか。What does it happen at the death of Jesus?



- ひとびとは、イエスの死に際してどのように告白しますか。What do the people say at Jesus' death?



- マタイはイエスの死をとおして何を伝えようとしていますか。What does Matthew tell us about Jesus' death?









### マタイによる福音書 Matthew 27:57 - 61



- イエスの遺体をひきとったヨセフはどんな人ですか。Who is Joseph who takes Jesus' body?



- 遺体をひきとるにはどのようなことが必要だったと思いますか。What do you think is required to take Jesus' body?



- 他の福音書にはどのようなことが書かれていますか。What do other gospels tell us?



- この日はどのような日でしたか。What does this happen?



- ヨセフはイエスの遺体をどうしますか。What does Joseph do to Jesus' body?



- だれが目撃していますか。Who are watching this?



- マタイはなにを伝えようとしているのでしょうか。What does Matthew tell us?









### マタイによる福音書 Matthew 27:62 - 66



- いつ誰がどこに集まりますか。When and who gather together, and where?



- 何を願い出ますか。それは何故ですか。What are their request?



- 墓はどのような状態になっていますか。Describe the tomb.



- マタイはなぜこのことを記したのでしょうか。Why does Matthew record this?






## マタイによる福音書　第28章
### マタイによる福音書 Matthew 28:1 - 10



- いつ誰が墓を見に行きますか。When and who go to the tomb?



- どんなことがおきますか。What happens?



- 婦人たちはどうしますか。What do they do?





- なにが起こりますか。What happens?



- マタイは復活についてなにを伝えていますか。What does Matthew tell about Jesus' resurrection?



- 他の聖書の箇所で復活について調べてみましょう。What does other gospels tell about Jesus' resurrection?



- 復活は、弟子たちにとって、婦人たちにとってどのようなことだったのでしょうか。What does resurrection mean to the disciples and these women?



### マタイによる福音書 Matthew 28:11 - 15



- 番兵たちはどうしますか。What do the guards do?



- 祭司長たちは、どうしますか。What do the chief priests do?



- 結果はどうなったと書いてありますか。What is the result?









### マタイによる福音書 Matthew 28:16 - 20



- だれがいつどこへ行きますか。それはなぜですか。Who go to where? When is it, and why?



- イエスに会ったときの様子はどのように描かれていますか。How do they meet Jesus?



- イエスはどのようなことを告げますか。What does Jesus tell them?



- 「わたしは天と地の一切の権能を授かっている。」とはどういうことを言っているのでしょうか。What does

''All authority in heaven and on earth has been given to me.'' mean?



- イエスの弟子にするとはどういう意味でしょうか。What does making disciples of all nations mean?





- イエスは最後にどのような約束で締めくくっていますか。What is the promise Jesus makes at the end?



- 他の福音書では、どのようなことを、弟子たちに託していますか。What is the last commission of Jesus to his disciples in other gospels.



- マタイが伝えたかったことは、何なのでしょうか。What is the message Matthew wanted to tell us?



- あなたは、マタイによる福音書からなにを学びましたか。What did you learn from Matthew?



- 聖書を少しずつ共に読む経験は、あなたにとって、どのようなものでしたか。What does reading the Bible little by little with others mean to you?






