# 聖書の会の準備 {#preparation}

聖書の会の準備として、どのようなことをしているか、備忘録、反省もこめて、紹介します。

## 概要

1.  テキストを何回か読み、範囲を決める。

    -   前後のつながりも確認して、どこで切るかを検討する。

2.  特に共観福音書の場合、対照箇所を確認。

    -   前後関係など、位置づけが、同じか、確認する。

    -   対照表を作成。日本語に寄りすぎると、ことばの意味が取れない場合もあるので、英語を加えるのもよい。いくつかの翻訳を併記するのもよいが、訳の違いに囚われて、中身の理解に繋がらないときもあるので、最近は、あまり重視していない。

    -   背景などはことなるので、対照箇所があっても、中心とテキストを決めておいたほうがよい。

3.  対照箇所もふくめて、何回か読み、質問（ディスカッション・クエスチョン）をいくつか作成する。

    -   最初は、この段階は難しいので、すでにあるもの（冊子など）を利用するのもよい。

    -   わたしは、過去の学びがあるので、対照箇所の質問もふくめて、まずは書き出し、それから、取捨選択している。

4.  自分で、質問に対する応答を書いてみる。

    -   自分で応答を書くと、質問の文言が不適切だったり、テキストの用語との違いに気づいたりする。適宜、質問文を修正する。

    -   さらに、応答を活性化するために、場合に応じて追加する、質問事項を書き出す。

5.  聖書の引用箇所を参考に、他の聖書の箇所との関係をみる。

    -   なれないと、なぜ、その聖書箇所が引用されているのか分からなかったり、どんどん、引用箇所に引っ張られたりするが、参考程度に止め、いくつか、メモとして残す。

    -   箇所によっては、地図を参考にすることも、理解の助けになることもあるので、確認。

    -   原語のギリシャ語（や、ヘブル語）が気になる場合がある。ネストレ・アーランド（や、BHS）が一般的だが、簡単に調べられるものとして、わたしは、[blueletterbible.org](https://www.blueletterbible.org/) を利用している。英語だが、単語の意味も確認できる。ブラウザーの翻訳機能を使うことも可能。

6.  注解書・説教集など、参考にできるものを読みながら、質問を加えたり、修正したりする。

    -   この作業を、あまり早くにしないことがたいせつ。そうでないと、どうしても、それに引き寄せられてしまう。

    -   聖書学者や、牧師が書いていることが多く、多くの示唆に富んだ、記述があると思わるが、それに引き寄せられたり、あるいは、自分が受け取った、自分が感動したことに、偏ってしまい、みなで、考えながら、聖書を読むことを阻害することにもつながるので、気をつける。特に、説教集の場合は、教会でのメッセージが想定されており、一つの解釈に導く傾向があり、ディスカッションスタイルで、さまざまな読み方を許容する場合には、妨げとなる場合もあるので、みなが、自分の考え、感想が出しやすいことを優先する。

7.  質問票を完成させ、一部印刷。

    -   この段階で、もう一度、わたしは、手書きで、質問票に自分の応答を書き、これまでに、メモした、様々な情報を、欄外などに加えて、必要に応じて、説明したり、問を発展させたりできるようにする。

    -   この段階で、質問票を修正する必要がある場合もある。配布分完成。

8.  質問票と、対照表を、参加者に配布。

    -   事前配布が望ましいと思うが、一般的には、事前学習をするひとは少ない。

    -   聖書の会のリマインドも含めて、わたしは、これらを配布、連絡している。

9.  聖書の会

    -   そのときの会の出席メンバーによっても対応が変わるので、司会は難しい。

    -   極力、みなが、自分の考えを出しやすいように、それを、歓迎できるようにすることが肝要。

    -   出席メンバーにある程度、慣れた人がいるときは、一回目テキストを読んだ後に、少し、自分で、読む時間を取ってもらい（2-3分）そのあとで「なにか、疑問や考えてみたいこと、印象に残ったことなどありますか。」と聞いている。

    -   質問票にはないが、よい問が出されたときは、メモをして、あとから、それについても、話すときを持つのがよい。

    -   聖書知識があまりないひとも、意見を言えるように、知識豊富な人が、他の箇所をどんどん引用するときには、なるべく、今回のテキストに集中するように促すなど、みなが、安心して発言できる場を作ることがたいせつ。

    -   難しい箇所の場合には、背景を説明するなどから始めるときもあるが、その説明も、最初は非常に簡単にすべきだと思う。理解を助けることに集中したい。

10. 感想

    -   最後に、かならず、ひとりずつ、感想を言ってもらっている。むろん、今日は、パスします。も許容して。

    -   ゆっくり、他者のこえに耳を傾け、できるだけ、一回は発言する機会を作るためでもある。何回か続けてきていると、いつも寡黙なひとが、非常に深い感想、または、日常的な痛みを吐露することもある。それが、互いから学び、互いに愛し合うことに繋がることを聞きながら祈っている。

11. 振り返り

    -   振り返りメッセージがある場合は、送ってもらっている。

    -   自分でも、記録を確認し、出席人数などだけでなく、質問や印象箇所、メモなど、この機会に、書き加えておくとよい。

### 「マルコによる福音書の学び」において

2023年4月20日から2025年6月19日（夏・冬・春、多少休みをとりながら）にかけて毎週木曜日に行ったマルコによる福音書を中心にした学びにおいて、具体的に、どのような準備をしていたかを書いておく。

すでに退職後であり、比較的時間があり、おそらく、学びの準備に、10時間程度は、毎週使ったと思われる。それ以外に、登録者への連絡や、当日の準備など、さらに、妻が、お茶とお菓子など（ケーキやクッキーさらにおにぎりなど軽食）の準備もしてくれていたので、二人合わせると、毎週16時間程度は使っていたと思う。

1.  下準備：一回で読む箇所を定め、四福音書対照表を作成。

2.  特にマルコについては、前後関係も含めて、すこし多めに読み、さらに、四福音書対照箇所を読む。

3.  その箇所から個人的に考えたいことを、問いとして書き上げる。（編集して「福音書についての問い」に列挙）\[ここまでを週末に終わらせる\]

4.  月曜日朝、出席確認と、前回の報告、あれば、振り返りの投稿を加えて登録者に送信。\[月曜日朝\]

5.  聖書の学び

    1.  本文の理解ができるような質問の構成、出席者に考えてもらいたい質問を列挙し、学びに合わせて変更。

    2.  対照表を用いて、福音書ごとの違い、強調点を列挙する。必要に応じて、ギリシャ語本文を、ドイツ聖書協会のサイトの NA28、BLUELETTERBIBLE など何箇所かを活用して調べる。

    3.  過去の、四福音書の学びにおける問いを参考にして、数個の質問に集約。

    4.  本文の理解ができるような質問の答えを自分で考え、さらに、深める問いを \[DQ\] として、加える。

    5.  重要な、ことばなど、調べる必要のあるものを列挙し、時に応じて調べ、付け加える。

    6.  註解を読む。今回、かならずチェックしたのは、バークレイのマルコとヨハネ、榊原康夫のマタイとルカ、いのちのことばしゃ聖書註解。時に応じて、ネット上のものや、ICU図書館から借りた本などを参考にする。

    7.  もう一度、\[DQ\] などを含めて、自分の答えを考えながら書き、問いを膨らませ、広めの理解を得る。

    8.  問いを確定させ、QUESTION SHEET を作成。

    9.  問いのシートに、自分なりの答えを書き、シートだけで会を進めることができるように準備。

    10. Zoom 招待と、質問票、四福音書比較表を加えて、メールで案内。\[木曜日朝\]

    11. もう一度、自分のシートや、WebSite を確認して会の準備。

    12. 聖書の会

    13. 会、終了後、振り返りを送ってもらうためのメールを配信

    14. 聖書の会で新たに得たことを加え、出席者人数を加えて、WebSite をアップデート

    15. 福音書が伝えるイエスのページをアップデート

一通りできるようになったのは、エルサレム入場ごろからで、その前は、試行錯誤で、多少のブレもあった。

## 心がけていること

### 奇跡の解釈

丁寧にテキストを読むことを心がけ、単純化バイアスに陥らないように気をつけています。特に、奇跡物語と呼ばれるものについては、次のような解釈を、否定はしませんが、それ以外の見方ができないかを考えています。

-   科学的に起こり得ないことだから、作り話に違いない

-   イエスは神様だから、なんでもできる

科学的視点というのは、合理的な解釈をしたいとの要求は常にありますが、非常に、狭い価値観で見ているようにも思います。さらに、大切にしたいのは、すこし違う価値観であもあると思う。また、イエスは、神だからなんでもできると考えるのは、楽だが、それも、一つの思考停止で、イエスに倣うものにはなれない。

著者が、伝えたいこと、または、イエスがそのことを通して、伝えていることは何なのかを理解したいと願っています。
