# 福音書に関する問い

聖書を読んでいくときに、問いを持ち、問いと向き合いながら読むことがたいせつだと考えています。信じれば良いと考えられる方もおられるかと思いますが、わたしはそうは考えていません。もし、聖書が、信仰者のためだけのものであれば、それで良いかもしれません。しかし、もし、信仰者またはイエスをキリスト（救い主）と信じるひと以外にも、たいせつな内容が書かれているとするのであれば、疑問がある箇所については、考え、また、聖書はどう語っているのだろうか、それは、本当なのだろうか。何を伝えようとしているのかと考えることは、とても健全なことなのではないでしょうか。実際、私が主催している聖書の会には、キリスト者ではないかたが出席しておられ、その方が多い場合もあります。さらに、基本的なことでも、問われると、適切に答えられなかったり、特定の牧師の説教や、本や、出どころがわからないものをいろいろと根拠にしないと説明できないことも多くあります。自らに問うてみることは、自分のそして、ともに学ぶものたちの理解をえるためにも、そう簡単ではないことを理解まはた確認するためにも、必要なのではないでしょうか。

問うたり、疑うよりも信じることがたいせつだと考えておられる方も多いかもしれません。ある時点で、信じるかどうかを選択する場面はあるかもしれません。しかし、最初から、疑ってはいけないとしてよいのでしょうか。疑うひとは、聖書は読めないのでしょうか。わたしは、一緒に読むなかで、お互いに目が開かれていく経験をたくさんしています。自分だけでは、気づかなかったこと、問われて考え始めたからこそ、学ぶことはたくさんあるように思います。考えることがたいせつで、必ずしも、すっきりとした答えのいきつかないことを許容しながら学び続けることも大切なのではないでしょうか。

解釈は、一人ひとり様々ですが、問いを共に考えられることは、共通の場に立つことにも繋がります。共同作業で、聖書を理解していくこと自体に、価値があると思っています。この共同作業を通して、同じテキスト、同じ問いであっても、異なる視点をもっていることを通して、他者を知ることも、ある共通の観方、同意ができる経験をもつことも素晴らしいのではないでしょうか。他者の背後にある人生を垣間見ることもあるかもしれませんし、この事自体が、共に生きることにつながるように思います。そのような経験をたくさんしていただく一助になればと願っています。

ここでは、福音書を読むことを中心においています。福音書は、イエスについて書かれています。イエスはどのような方だったのかを、一緒に考えながら読んでいくことができればと願っています。キリストは油注がれたものという意味ですが、神様に油を注がれた、救い主と告白する言葉としても使われています。また、福音書は、イエスがキリストであることを証言する文書だという面もあることは確かだと思いますが、それは、福音書を読んで、みなさんが判断することだと思います。そこで、福音書を読むときは、キリストということばは気をつけて使い、必要な場合を除いて、イエスと書いていきたいと思います。わたしは、通常は、イエス様と言っているので、イエス様ということばが出てくるかと思いますが、それはご容赦ください。一緒に、このイエスについて学び、このイエスと出会うことができればと願っています。

ある方は、福音書もイエスが生きた時代からすると、だいぶあとから書かれ、多くのひとたちの伝承をもとにして書かれ、そのひとたちの解釈を経たあとで、書かれているので、福音書を読んで、そこから、実際のイエスについて、知るのは難しいのではないかと考えられるかたもおられるかもしれません。そのように言う学者も多いようです。そのような面は否定できないことは確かですが、わたしは、福音書が一律にそのようなものとは考えていません。すこしずつ、その理由についても、書いていきたいと思います。しかし、このことは、問いとしてはあげず、皆さんに判断していただこうと考えています。まずは、福音書を読んで、わかることから始めるのがよいと考えているからです。

もう一つ大切なのは、聖書の含まれている四つの福音書をどう読むかということです。矛盾なく、一つのことを伝えているのだから、全てに共通なことを読み取っていくべきで、違いを強調することは適切ではないという立場です。わたしは、そうは考えていません。四つの福音書が、それぞれの著者によって、異なった背景のもとで書かれ、それぞれに、強調点があり、著者が受け取り、伝えたいと考えたメッセージが書かれていることは、否定できないのでしょうか。著者が何を伝えようとして、このように書いているのか、どうして同じときのことを表現するのに、このような違いが生じるのかも、考えながら、読み解いて行きたいと思います。

大雑把にいって、近年は、聖書学者たちは、以下のことについては、ほぼ共通の考えを持っているようです。まず、マルコによる福音書が書かれ、次に、おそらく、マルコによる福音書について知っているひとが、マルコはおそらく知らない「イエスの語録文書」を利用し、マタイによる福音書と、ルカによる福音書が書かれた。また、マタイも、ルカも、独自の資料もそれぞれにある程度もっていたこと、そして、それからしばらくたって、これら三つの福音書について知ってはいるが、それらには、載っていないことがらを知っているひとが、ヨハネによる福音書を書いたということです。わたしは、これらにくわえて、もうすこし、想定していることがありますが、すくなくとも、ここに書いたことは、わたしもそうだろうと考えています。このことは、いくつかの文書資料によってある程度、支持されているとともに、丁寧に、四つの福音書を読むと、浮かび上がってくることだとも考えています。

最初に、問いをもって読むたいせつさについて書きました。むろん、ほとんどの、疑問や問いは、わたしたちが丁寧に読んでも、解決しないかもしれません。しかし、それを、問わずに置くことによって、真理に近づくことができないなら、とても、残念なことであるとも思います。真理の探求とまでは、言えないにしても、問いを持ち続けることは、次に、さらに、そのあとで、読むときにも、理解を深める助けになると思うのです。いかがでしょうか。

わたしが考えたい問い、たいせつにしたい問いもあります。それは、自分に問いかける、そして、今の時代に対する問いです。これは、一人ひとりによって異なると思いますが、なにのために聖書を読むかという問いにも関係していることだと思います。真理の探求、神様の御心を求めることをわたしは大切にしていますが、同時に、それは、どう生きるか、どう生きていくかを選択していくことをしたいからです。上にも書いたように、それは、完全な答えを得ることではありません。問いを持ちながら生きる、しかし、同時に、考えながら生きるということでしょうか。

そのようなことを考えて、ここに、いくつかの問いを書いておきたいと思います。

## マルコによる福音書を中心として

### 背後にいる証言者はどのような人たちなのだろうか

-   マルコは使徒言行録に登場するヨハネ・マルコをさすと一般的に考えられているようだが、実際にマルコが著者かどうかには、議論もあるようである。いずれにしても、マルコは、イエスとともに生活をしたひとではない。すると、著者が情報を得た入手先があるだろう。複数かもしれないが、それは、誰なのだろう。

-   エウセビオスが引用しているパピアス断片と呼ばれる文書には、マルコはペテロの通訳だったと書かれている。これについても、議論はあるだろうが、マルコによる福音書を読んでいきながら確認できることもあるように思われる。

-   11章にあるエルサレム入城以降は、筆致が変わっているように見える。それまでは、イエスの行動について書かれているが、教えや譬え、論争記録などで構成されている。このような記録はどのような起源があるのだろうか。

-   残されている記録が限られているが、背後にいる証言者についてすこしずつ情報を集めていきたい。どんな人達なのだろうか。

### 病気の癒やしはどのようなものだったのだろうか

-   ギリシャ語では、テラペウオ、イアオマイ、ソーゾーが使われているようだが、現代の病気が治ることとは同じだと考えてよいのだろうか。

-   イエスのいやしは、どのような行為なのだろうか。

-   マルコでは、イエスの癒やしの活動の中心は、ガリラヤのようだが、病人は、大きく減少したのだろうか。

### イエスはどのような「神の子」「キリスト（油注がれた）・救い主」

-   ダビデの子なのだろうか。ダビデを、イエスはどのように認識していたのだろうか。

-   神の国を宣べ伝え、苦しんでいる人に仕え（いやし：θεραπεύω（テラペウオー））、弟子たちを教えたことは確かで、そのなかに、主との交わりの深さ、主のみこころを行う使命は明確にされていたと思われるが、神の子、救い主と単独のことばで表現すると、危険も伴うので、より丁寧な表現が必要。イエスは、何をたいせつにして、生き・死なれたのだろうか。

-   イエスは、なぜ、十字架の死に向かわなければいけなかったのだろうか。おそらく、イエスはどのような「神の子」「キリスト（油注がれた）・救い主」との問いとも深く関係している。

-   マルコを土台にしたと思われる、マタイやルカに拡大または追加して書かれていることについて、どう理解していったら良いのだろうか。語録のような文書があったとして、それ以外の部分に、絞って論じることも必要。

-   マルコ（の古い信頼できる写本は16章8節まで）は、復活の証言で終わっており、ガリラヤでお会いできるであろうと伝えられるところまでで、復活のイエスとの出会いについては、書かれていない。それは、なぜなのだろうか。（マルコの16章9節〜20節の追記部分を別として）復活のイエスの顕現やルカ文書にある昇天は書かれていないが、それは、どのように受け止められていたのだろうか。

\[参考\] ChatGPT 2025.4.23 \[[リンク](https://chatgpt.com/share/680843b7-13ac-8005-9f66-5bb964e1bef5)\]

## 個別の記事について

### **マルコによる福音書について**

以下は、それぞれの学びのときに、その箇所を理解し、考えるための問いではありませんが、合わせて考えていただければと思います。学びの準備の段階や、学びが終わってから、残った問いなどをリストしています。

**聖書箇所：**1:1 神の子イエス・キリストの福音のはじめ。 

-   マルコは「神の子イエス・キリストの福音のはじめ。」としている。ここで言われている「福音」とは何なのだろうか。それとも、マルコ全体をとおして、福音について語られているということなのだろうか。
-   最初から、イエスは、神の子であり、救い主（キリスト）だとしているが、これは、どう理解したら良いのだろうか。本書を通して、このことを証言しようとしているのか、それとも、イエスが、神の子、キリストであるとしての活動などを描いているのだろうか。

### 洗礼者ヨハネ、悔い改めの洗礼を宣べ伝える

**聖書箇所：**[マルコによる福音書1章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_1-8.pdf)

-   バプテスマのヨハネの使命やメッセージはどのようなものだったのだろうか。イエスのものとの相違は何だったのだろうか。
    -   福音書ごとに伝える内容が異なっているようだが、それは、何を意味するのだろうか。
-   バプテスマのヨハネのことは、イエスの活動に関しても、大きな影響を及ぼしたように見えるが、イエスにとって、ヨハネはどのような存在だったのだろうか。

### イエス、洗礼を受ける

**聖書箇所：**[マルコによる福音書1章9-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_9-11.pdf)

-   イエスは、なぜ、バプテスマのヨハネの洗礼を受けられたのだろうか。

-   「あなたはわたしの愛する子、わたしの心にかなう者である」（11）は、聖霊をうけられたことの具体的内容であるようにも見える。イエスは、神の心にかなうといういみで神の愛する子ということなのだろうか。

-   イエスは、神の子として、生まれたのだろうか、それとも、この時から、神の心にかなう神の子として生きられたのだろうか。そのような問い自体が適切ではないのかもしれないが。

### **試みを受ける**

**聖書箇所：**[マルコによる福音書1章12-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_12-13.pdf)

-   サタンと悪魔はどう違うのだろうか。どのように使い分けられているのだろうか。

    -   悪霊は、サタンや、悪魔とは異なるようだが、どのように違うのだろうか。

-   マルコでは、試みの内容についてかかれていないが、なにが試みられたのだろうか。

    -   試みがあったことがマルコのように書かれている時、われわれはそこからどのようなメッセージを受け取れば良いのであろうか。

-   「獣もそこにいたが、御使たちはイエスに仕えていた。」（13）は何を伝えているのだろうか。

### **ガリラヤで宣教を始める**

**聖書箇所：**[マルコによる福音書1章14-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_14-15.pdf)

-   マルコを手にしたひとは、福音の内容・意味が理解できたのだろうか。

-   「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」。はどのようなメッセージなのだろうか。

    -   時は満ちた

    -   神の国は近づいた

    -   悔い改めて福音を信ぜよ

-   「神の国は近づいた」は神の支配、神の御心がなることを意味しているのかもしれないが、どのようなことがイメージされているのだろうか。

### **四人の漁師を弟子にする**

**聖書箇所：**[マルコによる福音書1章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_16-20.pdf)

-   「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」（17）は、どのような召しなのだろうか。目的は何なのだろう。どのように理解されたのだろうか。

-   ヨハネ（1:35-42）に書かれている記事（このとき以前のことのように思われる）は、何を意味し、この箇所とはどのように関連しているのだろうか。

### **汚れた霊に取りつかれた男を癒やす**

**聖書箇所：**[マルコによる福音書1章21-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_21-28.pdf)

-   「権威ある者のように教えられた」（22）は、どのような特徴を表現しているのだろうか。

-   「ナザレのイエスよ、あなたはわたしたちとなんの係わりがあるのです。わたしたちを滅ぼしにこられたのですか。あなたがどなたであるか、わかっています。神の聖者です」（24）特に「神の聖者」は何を伝えているのだろうか。

-   なぜ、イエスは「黙れ、この人から出て行け」（25）と、この霊を黙らせるのか。

### **多くの病人を癒やす**

**聖書箇所：**[マルコによる福音書1章29-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_29-34.pdf)

-   ペテロの家族構成はどうなっていたのだろうか。

-   「悪霊」と「病」の関係はどうだと人々や、イエスはどのように考えていたのだろうか。

### **巡回して宣教する**

**聖書箇所：**[マルコによる福音書1章35-39節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_35-39.pdf)

-   「みんなが、あなたを捜しています」（37）とあるが、人々はなにを求めているのだろうか。

-   イエスの宣教に関するビジョンは、どのようなものだったのだろうか。（39）

### **規定の病を患っている人を清める**

**聖書箇所：**[マルコによる福音書1章40-45節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark1_40-45.pdf)

-   「重い皮膚病にかかった人が、イエスのところに願いにきて、ひざまずいて言った、『みこころでしたら、きよめていただけるのですが』。イエスは深くあわれみ、手を伸ばして彼にさわり、『そうしてあげよう、きよくなれ』と言われた。」（40,41）とあるが、この、深くあわれみは、なにを意味しているのだろうか。

-   重い皮膚病と、汚れることについて、どのように考えたら良いのだろうか。

### 体の麻痺した人を癒やす

**聖書箇所：**[マルコによる福音書2章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_1-12.pdf)

### レビを弟子にする

**聖書箇所：**[マルコによる福音書2章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_13-17.pdf)

### 断食についての問答

**聖書箇所：**[マルコによる福音書2章18-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_18-22.pdf)

### **安息日に麦の穂を摘む**

**聖書箇所：**[マルコによる福音書2章23-28節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark2_23-28.pdf)

-   「ダビデとその供の者たち」に関する挿入話（25,26）は、唐突に感ずるが、イエスの真意は、どのようなことだったのだろうか。弟子たちを守るために、反論したようにも見えるが、どうなのだろうか。

-   イエス自身は、安息日に、麦の穂を摘むことはしなかったのだろうか。律法に関して、どのように行動していたのだろうか。守っていたのだろうか、それとも、自由人だったのだろうか。

-   「安息日は人のためにあるもので、人が安息日のためにあるのではない。」（27）とあるが、安息日とは何のためにあるのだろうか。

-   同様の規則・習慣で、本来の目的が、捻じ曲げられているものはどのようなものがあるだろうか。

-   「それだから、人の子は、安息日にもまた主なのである」。（28）は、何を伝えているのだろうか。

### **手の萎えた人を癒やす**

**聖書箇所：**[マルコによる福音書3章1-6節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_1-6.pdf)

### **湖の岸辺の群衆**

**聖書箇所：**[マルコによる福音書3章7-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_7-12.pdf)

### **十二人を選ぶ**

**聖書箇所：**[マルコによる福音書3章13-19節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_13-19.pdf)

### **ベルゼブル論争**

**聖書箇所：**[マルコによる福音書3章20-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_20-30.pdf)

### **イエスの母、きょうだい**

**聖書箇所：**[マルコによる福音書3章31-35節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark3_31-35.pdf)

### **「種を蒔く人」のたとえ**

**聖書箇所：**[マルコによる福音書4章1-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_1-9.pdf)

### **たとえを用いて話す理由**

**聖書箇所：**[マルコによる福音書4章10-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_10-12.pdf)

### **「種を蒔く人」のたとえの説明**

**聖書箇所：**[マルコによる福音書3章13-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_13-20.pdf)

### **「灯」と「秤」のたとえ**

**聖書箇所：**[マルコによる福音書4章21-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_21-25.pdf)

### **「成長する種」「からし種」たとえを用いて語る**

**聖書箇所：**[マルコによる福音書4章26-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_26-34.pdf)

### **「成長する種」のたとえ**

**聖書箇所：**[マルコによる福音書4章26-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_26-29.pdf)

### **「からし種」のたとえ**

**聖書箇所：**[マルコによる福音書4章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_30-32.pdf)

### **たとえを用いて語る**

**聖書箇所：**[マルコによる福音書4章33-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_33-34.pdf)

### **突風を静める**

**聖書箇所：**[マルコによる福音書4章35-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark4_35-41.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす**

**聖書箇所：**[マルコによる福音書5章1-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_1-20.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす（１）**

**聖書箇所：**[マルコによる福音書5章1-10節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_1-10.pdf)

### **悪霊に取りつかれたゲラサの人を癒やす（２）**

**聖書箇所：**[マルコによる福音書5章11-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_11-20.pdf)

### **ヤイロの娘とイエスの服に触れる女**

**聖書箇所：**

### **ヤイロの娘とイエスの服に触れる女（１）**

**聖書箇所：**[マルコによる福音書5章25-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_25-34.pdf)

### **ヤイロの娘とイエスの服に触れる女（２）**

**聖書箇所：**[マルコによる福音書5章21-24, 35-43節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark5_21-24_35-43.pdf)

### **ナザレで受け入れられない**

**聖書箇所：**[マルコによる福音書6章1-6節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_1-6.pdf)

### **十二人を派遣する**

**聖書箇所：**[マルコによる福音書6章7-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_7-13.pdf)

### **洗礼者ヨハネ、殺される**

**聖書箇所：**[マルコによる福音書6章14-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_14-29.pdf)

### **五千人に食べ物を与える**

**聖書箇所：**[マルコによる福音書6章30-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_30-44.pdf)

-   五千人の給食とはどのようなものだったのだろうか

### **五千人に食べ物を与える（１）**

**聖書箇所：**[マルコによる福音書6章30-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_30-34.pdf)

### **五千人に食べ物を与える（２）**

**聖書箇所：**[マルコによる福音書6章35-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_35-44.pdf)

### **湖の上を歩く**

**聖書箇所：**[マルコによる福音書6章45-52節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_45-52.pdf)

### **ゲネサレトで病人を癒やす**

**聖書箇所：**[マルコによる福音書6章53-56節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark6_53-56.pdf)

### **昔の人の言い伝え**

**聖書箇所：**

### **昔の人の言い伝え（1）**

**聖書箇所：**[マルコによる福音書7章1-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_1-13.pdf)

### **昔の人の言い伝え（2）**

**聖書箇所：**[マルコによる福音書7章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_14-23.pdf)

### **シリア・フェニキアの女の信仰**

**聖書箇所：**[マルコによる福音書7章24-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_24-30.pdf)

### **耳が聞こえず舌の回らない人を癒やす**

**聖書箇所：**[マルコによる福音書7章31-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_31-37.pdf)

### **四千人に食べ物を与える**

**聖書箇所：**[マルコによる福音書8章1-10節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_1-10.pdf)

### **人々はしるしを欲しがる**

**聖書箇所：**[マルコによる福音書8章11-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_11-13.pdf)

### **ファリサイ派の人々とヘロデのパン種**

**聖書箇所：**[マルコによる福音書8章14-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_14-21.pdf)

### **ベトサイダで盲人を癒やす**

**聖書箇所：**[マルコによる福音書8章22-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_22-26.pdf)

### **ペトロ、イエスがメシアであると告白する**

**聖書箇所：**[マルコによる福音書8章27-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_27-30.pdf)

### **イエス、死と復活を予告する**

**聖書箇所：**[マルコによる福音書8章31-38節, 9章1節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_31-38_9_1.pdf)

### **イエスの姿が変わる**

**聖書箇所：**[マルコによる福音書9章2-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_2-13.pdf)

### **汚れた霊に取りつかれた子を癒やす**

**聖書箇所：**[マルコによる福音書9章14-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_14-29.pdf)

### **再び自分の死と復活を予告する**

**聖書箇所：**[マルコによる福音書9章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32.pdf)/[マルコによる福音書9章30-32節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32_extra.pdf)

### **いちばん偉い者**

**聖書箇所：**[マルコによる福音書9章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_33-37.pdf)

### **逆らわない者は味方**

**聖書箇所：**[マルコによる福音書9章38-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41.pdf)/[マルコによる福音書9章38-41節 福音書対照表（ルカ参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41_extra.pdf)

### **罪への誘惑**

**聖書箇所：**[マルコによる福音書9章42-50節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_42-50.pdf)

### **離婚について教える**

**聖書箇所：**[マルコによる福音書10章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_1-12.pdf)

### **子どもを祝福する**

**聖書箇所：**[マルコによる福音書10章13-16節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_13-16.pdf)

### **金持ちの男**

**聖書箇所：**[マルコによる福音書10章17-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-31.pdf)

### **金持ちの男（1）**

**聖書箇所：**[マルコによる福音書10章17-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-22.pdf)

### **金持ちの男（2）**

**聖書箇所：**[マルコによる福音書10章23-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_23-31.pdf)

### **イエス、三度自分の死と復活を予告する**

**聖書箇所：**[マルコによる福音書10章32-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34.pdf)/[マルコによる福音書10章32-34節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34_extra.pdf)

### **ヤコブとヨハネの願い**

**聖書箇所：**[マルコによる福音書10章35-45節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_35-45.pdf)

-   あがないという言葉は、共観福音書では、ここと対応するマタイの箇所にのみ現れるが、イエスの死は罪の贖いのためなのだろうか。
    -   マルコだけではなく、共観福音書には、ほとんど、罪のあがないについて書かれていないように見える。

### **盲人バルティマイを癒やす**

**聖書箇所：**[マルコによる福音書10章46-52節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_46-52.pdf)

### **エルサレムに迎えられる**

**聖書箇所：**[マルコによる福音書11章1-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_1-11.pdf)

-   マルコ、マタイ、ルカでは、このときが公生涯において、最初にエルサレムに来たときとして描かれているが、ヨハネでは、逆に、エルサレムや、その周辺、ユダヤなどでの活動についてたくさん書かれている。

-   エルサレム入城の書き方が、マルコ、マタイ、ルカ、ヨハネそれぞれに異なる。実際、エルサレム入城は、イエスにとってどのようなものだったのだろう。

### **神殿から商人を追い出す**

**聖書箇所：**[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

-   マルコによると、エルサレム入城のあと、宮も見て回り、その翌日に、宮きよめをしたことが書かれている(11:11, 12)。入城した日も、同じ様子を見ながら、何もしなかったように見える。また、このあと、どうなったかもかかれていない。宮の境内を歩いておられ（11:37）たり、宮の境内で教えておられること（12:35）賽銭箱の前に座っておられること（12:41）も書かれている。

-   祭司長たちや、律法学者たちは、イエスの言葉を聞いて、殺そうとするが、殺意を抱くほどのことを言っているとは思えない。

-   ヨハネでは2章となっている。似た記事だが、終わり方は少し異なっている。

-   宮きよめは、何を伝えているのだろうか。

### **いちじくの木を呪う**

**聖書箇所：**[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

-   悪魔の試みのときも含め、自分のためには、奇跡的な方法を使われないイエスの呪い、魔術的なとも言える力によって、いちじくが枯れてしまったように見える。（マルコでは翌日、マタイではたちまち枯れている。）

-   まだ実がなる時期になっていないときのことであり、道理に適っていない。同時に、その時期ではなかったこと書かれていることも興味深い。

-   マルコでは、祈りについての教えが続き、赦しについても書かれている。

-   ルカには、宮きよめの記事が、エルサレム入城に引き続いて、マルコ、マタイと同じ位置に書かれているが、この記事はない。その代わりかどうかは不明だが、ルカ13:6-9 に、実のならない、いちじくの木について、あと三年待ってほしいと懇願する園丁の話が載っている。しかし「それで来年実がなりましたら結構です。もしそれでもだめでしたら、切り倒してください」という期間限定がなにを意味するのか不明。

-   マルコ、マタイ、ルカとも、いちじくの状態から、季節を見極める、話が登場する。イエスは、いちじくの実のなる季節についても、よく知っておられたのだろうか。それとも、このエピソードのときに学んだのだろうか。（マルコ13:28-32、マタイ24:32-35、ルカ21:29-33）

-   実らないいちじくを枯らすはなしは、何を伝えているのだろうか（マルコ、マタイ）

### 権威についての問答

**聖書箇所：**[マルコによる福音書11章27-33節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_27-33.pdf)

-   「権威についての問答」（マルコ11:27-33, マタイ 21:23-27, ルカ 20:1-8）において、「何の権威によって、これらの事をするのですか」と聞かれ、直接的には答えず「ヨハネのバプテスマは天からであったか、人からであったか」と聞いています。なぜ、祭司長、律法学者、長老たちは、このような質問をしているでしょうか。そして「これらの事」は何を指すのでしょうか。そして、直接的には答えることは、訴える口実を与えてしまうおそれもあったので、それを避けたのでしょうか。

-   イエスは問いに対して問い返すという場面があるように思いますが、「ヨハネのバプテスマは天からであったか、人からであったか」では、イエスは本質的に何を、祭司長、律法学者、長老たちに問い、私たちに、どのようなことを考えることを迫っているのでしょうか。

-   あるものが「天（神）から」か「人から」かは、どのように判断したら良いのだろうか。とても、本質的な問いであもる。民の指導者たちはどう考えていたのだろう。イエスはどうだろうか、そして、私たちは、どのように判断したらよいのだろうか。

### 「ぶどう園の農夫」のたとえ

**聖書箇所：**[マルコによる福音書12章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_1-12.pdf)

-   主人が神様をあらわしているとすると、たとえで語られている、ぶどう園にたいしてしたことは、何を著しているのだろうか。

-   農夫たちが、収穫を主人に与えず、しもべたちを受け入れないことは何を意味しているのだろうか。

-   主人は、すでに、しもべたちが何度もひどい目にあっているのに、なぜ、農夫たちは、息子ならうやまってくれるだろうと考えたのだろうか。

-   語られている「彼ら」が祭司長、律法学者、長老たちであるなら、このたとえを通して、このひとたちに、どのようなメッセージが語られており、また、この人たちは、なにをどうすべきだ（った）と言っているのだろうか。

-   主人と農夫の信頼関係が、壊れてしまったのは何が原因なのだろうか。回復は不可能なのだろうか。

### **皇帝への税金**

**聖書箇所：**[マルコによる福音書12章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_13-17.pdf)

-   イエスに質問をしにきた人たちは、どのような答えを期待していたのだろうか。

-   税金についてイエスはどのように考えていたのだろうか。

-   「カイザルのものはカイザルに、神のものは神に返しなさい」で、イエスは何を教えているのだろうか。

-   このひとたちが考えていたことと、イエスのこたえには、どのような相違があったのだろうか。

### **復活についての問答**

**聖書箇所：**[マルコによる福音書12章18-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_18-27.pdf)

-   サドカイ人は、復活を信ぜず、パリサイ人は、それを信じていたようだが（使徒23:6）なぜ、そのように信じ、何を根拠にそう信じていたのだろうか。そのように信じるような経緯もしりたい。

-   復活を信じる、パリサイ人は、サドカイ人の12:19-23節の問いに、どう答えていたのだろうか。

-   アブラハム、イサク、ヤコブは生きていると証言しているようだが、イエスは復活についてどのような理解をもっていたのだろうか。

-   イエス自身が「よみがえる」ことについて何回か述べられているが（マルコ8:31, 9:9-10, 9:31, 10:34）、イエスは自身の復活についてどのように認識していたのだろうか。

-   死んだひとが生き返ること、イエスの復活、一般の（イエス以外の）ひとの死後の復活、神との関係において生き続けること、それぞれについて、そして相違について、どう考えればよいのだろうか。

### **最も重要な戒め**

**聖書箇所：**[マルコによる福音書12章28-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_28-34.pdf)

-   イエスが「すべてのいましめの中で、どれが第一のものですか」と問われて答えている箇所である。「わたしたちの神は、唯一の神である。その主をあなたのすべてをもって愛せよ。自分を愛するようにあなたの隣人を愛せよ。」（要約）が、聖書の中心的な教えということだろうか。

-   「イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。」で、聖書は、そして、イエスは何を伝えているのだろうか。他の神を認めない、排他的であることを奨励しているのだろうか。

-   なぜ最も重要な戒めは一つではなく二つなのだろうか。二つとも絶対的に必要なのだろうか。二つのいましめは関連しているのだろうか、それとも独立なのだろうか。

### **ダビデの子についての問答**

**聖書箇所：**[マルコによる福音書12章35-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_35-37.pdf)

-   キリストはダビデの子かという問いに対して三つの共観福音書ともイエスは否定している。イエスがダビデの子かという問いに関しては、福音書によってどのように記述されているのだろうか。

-   マルコにおいても、一箇所、エリコで盲人が「ダビデの子イエスよ、わたしをあわれんでください」（10章47節、48節では「イエス」が省略）と叫んでいる箇所があるが、他の福音書と比較して非常に注意して「ダビデの子」とは書かれていないように見える。この箇所でも、ひとびとは、必ずしもメシアをダビデの子だとは考えてないように見える。実際には、どうだったのだろうか。

### **律法学者を非難する**

**聖書箇所：**[マルコによる福音書12章38-40節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_38-40.pdf)

-   なぜ律法学者を非難する記事が入っているのだろう。

-   マルコの律法学者非難は簡素で短く、マタイは非常に長く、ルカは異なる形にまとめてあるようだがそれは何を意味するのだろうか。

### **やもめの献金**

**聖書箇所：**[マルコによる福音書12章41-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_41-44.pdf)

-   やもめはなにかの象徴だろうか。やもめのようになれと言っているのだろうか。それとも、そうではないひとを非難しているのだろうか。

-   イエスはこの「やもめの献金」で何を教えようとしているのだろうか。

### **神殿の崩壊を予告する**

**聖書箇所：**[マルコによる福音書13章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2.pdf)/[マルコによる福音書13章1-2, 3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2_3-13.pdf)

-   宮が（ローマ軍によって AD70に）崩されることの預言なのだろうか。それとも、もっと一般的に、物質的なものへの過度の称賛を戒めたものか。

### **終末の徴**

**聖書箇所：**[マルコによる福音書13章3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_3-13.pdf)/[マルコによる福音書13章1-2, 3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2_3-13.pdf)

-   イエスは「いつ」と「前兆」との問いのうち、「いつ」という問いには、答えていないように見える。イエスが気にかかっていたことは、どんなことだったのだろうか。

### **大きな苦難を予告する**

**聖書箇所：**[マルコによる福音書13章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_14-23.pdf)/[マルコによる福音書13章14-23, 24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_13-23_24-27.pdf)

-   苦難のときをどのように生きれば良いのだろうか。

### **人の子が来る**

**聖書箇所：**[マルコによる福音書13章24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_24-27.pdf)/[マルコによる福音書13章14-23, 24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_13-23_24-27.pdf)

-   人の子が来ることを通して、なにを教えているのだろうか。

### **いちじくの木の教え**

**聖書箇所：**[マルコによる福音書13章28-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32.pdf)/[マルコによる福音書13章28-32, 33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

-   「これらの事が起るのを見たならば、人の子が戸口まで近づいていると知りなさい。」（29b）とあるが、「これらの事」はどこの部分を指しているのだろうか。

-   「その日、その時は、だれも知らない。」そして「子も知らない」と明言している。これは、どのようなメッセージなのだろうか。

### **目を覚ましていなさい**

**聖書箇所：**[マルコによる福音書13章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_33-37.pdf)/[マルコによる福音書13章28-32, 33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

-   「気をつけて、目をさましていなさい。」が中心的なメッセージのようである。気を付けて、目を覚ましているとはどのようなことを命じているのだろうか。

### **イエスを殺す計略**

**聖書箇所：**[マルコによる福音書14章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2.pdf)/[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)/[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

-   いつ頃から、イエスを捕らえ、殺す計画が始まっていたのだろうか。

-   なぜ、捕らえ、殺そうとまで考えたのでしょうか。

-   恐れていたのは、どんなことだったのでしょうか。

### **ベタニアで香油を注がれる**

**聖書箇所：**[マルコによる福音書14章3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_3-9.pdf)/[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

-   ヨハネの福音書では、エルサレム入城前、過越祭の六日前になっているが、いつなのだろうか。

-   厳しく女を咎めたのは、マルコでは人々、マタイでは弟子たち、ヨハネではイスカリオテのユダと書かれているが、実際はどうだったのだろう。

-   イエスは、この女のひとを守ろうとしているようにみえるが、理由は何だろうか。

-   この女のひとが、油を注いだ理由は何だったのだろうか。どこまで、わかってしたいたのだろうか。

-   先に書かれた、マルコやマタイには、名前が出ていないが、後から書かれた、ヨハネには名前が書かれているのは、なぜなのだろうか。

### **ユダ、裏切りを企てる**

**聖書箇所：**[マルコによる福音書14章10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_10-11.pdf)/[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)/[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

-   ユダは「引き渡す」ことを計画しますが、これは、どのようなことを意図したのでしょうか。

-   ユダが、イエスを祭司長たちに引き渡そうとしたのは、なぜなのでしょうか。

### **過越の食事をする**

**聖書箇所：**[マルコによる福音書14章12-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_12-21.pdf)

-   過越の食事の場所とその準備は、それだけ注意して、食事をしようとしていたということだろうか。

-   イエスは、なぜ「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」と弟子たちに告げたのだろうか。弟子たちは、どのように受け取っただろうか。（マルコ14:18b）

-   「人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」（マルコ14:21b）はどのように受け取り理解したらよいのだろうか。

### **主の晩餐**

**聖書箇所：**[マルコによる福音書14章22-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_22-25.pdf)

-   なぜ、パンとぶどう酒を配餐し、イエスの死について語る前に、弟子の裏切りのことを語ったのだろうか。

-   パンはわたしのからだ、ぶどう酒は契約の血は、何を意味しているのだろうか。

### **ペトロの離反を予告する**

**聖書箇所：**[マルコによる福音書14章26-31 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_26-31.pdf)

-   イエスは、ここでは、何を弟子たちに伝えているのだろうか。

-   つまづくことは、十二人の一人が裏切ろうとしているということと同じだろうか。

-   あなた方より先にガリラヤに行くは、「たしかに人の子は、自分について書いてあるとおりに去って行く。」（21）と関連して、言っているのだろうか、それとも異なることについて伝えているのだろうか。

### **ゲッセマネで祈る**

**聖書箇所：**[マルコによる福音書14章32-42 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_32-42.pdf)

-   弟子たちに期待したことはどのようなことなのだろうか。

-   恐れ慄（おのの）きとあるが、イエスの悲しみの内容は、なになのだろうか。

-   イエスのいのりはどのようなものだったのだろうか。何を求めているのだろうか。

### **裏切られ、逮捕される**

**聖書箇所：**[マルコによる福音書14章43-50 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50.pdf)/[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)

-   「祭司長、律法学者、長老たちから送られた群衆」とはどのような人たちなのだろうか。

-   「イエスのそばに立っていた者のひとりが、剣を抜いて大祭司の僕に切りかかり、その片耳を切り落した」にもかかわらず、逮捕されたようには書かれていないのはなぜなのだろうか。

-   なぜ、宮にいるときに、捕まえなかったのか。

-   戦う意思も持っていたようだが、弟子たちは、なぜ、逃げたのだろうか。

### **一人の若者、逃げる**

**聖書箇所：**[マルコによる福音書14章51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_51-52.pdf)/[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)

-   この若者はだれなのか、なぜ、このような記事が記されているのか。

### **最高法院で裁判を受ける**

**聖書箇所：**[マルコによる福音書14章53-65節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_53-65.pdf)

-   何箇所かに連れて行かれるようだが、イエスは、全体として、どのような裁判を受けているのか。

-   イエスは、神の子である、キリストであると、弟子たちや人々に伝えていたのだろうか。

-   イエスは自分が神の子キリストだとは、明確には伝えていなかったように見えるが、ここでは、どのような気持ちで、大祭司の「あなたは、ほむべき者の子、キリストであるか」との問いに、「わたしがそれである。あなたがたは人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」と肯定的に答えたのだろうか。

### **ペトロ、イエスを知らないと言う**

**聖書箇所：**[マルコによる福音書14章66-72節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_66-72.pdf)/[マルコによる福音書14章26-31, 66-72節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_26-31_66-72.pdf)

-   四つの福音書がみな、このことを伝えているが、すべて微妙に異なっている。これは、何を意味しているのだろうか。

-   十分、勇気のいる行動をしているようにも見えるが、なぜ、ペテロは、イエスを知らないと言ってしまうのだろうか。

-   ペテロは、このあとどのように、立ち直ったのだろうか。

### **ピラトから尋問される**

**聖書箇所：**[マルコによる福音書15章1-5節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_1-5.pdf)

-   なぜ、全議会は、ピラトにイエスを引き渡したのだろうか。

-   ピラトの問い「あなたはユダヤ人の王であるか」に対して、なぜイエスは肯定したのだろうか。（共観福音書とヨハネを比較）

### **死刑の判決を受ける**

**聖書箇所：**[マルコによる福音書15章6-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_6-15.pdf)

-   ピラトはなぜイエスを十字架につける決断をしたのだろうか。

-   イエスが十字架刑に至ったのは、誰の何が責任なのだろうか。

-   それぞれの福音書がたいせつなこととして伝えているのはどのようなことなのだろうか。

### **兵士から侮辱される**

**聖書箇所：**[マルコによる福音書15章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_16-20s.pdf)（ルカを加えたもの）

-   嘲弄しているのは、兵士のようだが、兵士はなぜイエスを侮辱したのだろうか。

-   群衆や祭司長、長老たちは、どのようにこの光景を見ていただろうか。

### **十字架につけられる**

**聖書箇所：**[マルコによる福音書15章21-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_21-32.pdf)

-   アレキサンデルとルポスとの父シモンはなぜイエスの十字架を負わされることになったのだろう。

-   イエスの十字架は、どのようなもので、人々の目には、どのように映ったのだろうか。

### **イエスの死**

**聖書箇所：**[マルコによる福音書15章33-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_33-41.pdf)

-   「わが神、わが神、どうしてわたしをお見捨てになったのですか」と言われたイエスの心の中はどのようなものだったのだろうか。

-   百卒長は、なぜ、「まことに、この人は神の子であった」と言ったのだろうか。

### **墓に葬られる**

**聖書箇所：**[マルコによる福音書15章42-47節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_42-47.pdf)

-   アリマタヤのヨセフはなにを思いこのような行動をとったのだろうか。

-   ピラトはなぜイエスの死の確認をしたのだろうか。百卒長の役割は？

### **復活する**

**聖書箇所：**[マルコによる福音書16章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_1-8.pdf)

-   女たちが受け取ったものは何なのだろうか。

-   なぜ、女たちは、何も言わなかったのだろうか。

### **（結び一）マグダラのマリアに現れる**

**聖書箇所：**[マルコによる福音書16章9-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_9-11.pdf)

-   マタイにも少し書かれているが、詳細はヨハネのみにあるのは、なぜなのだろう。

-   どのようにして、マグダラのマリアはイエスだと気づいたのだろうか。

### **二人の弟子に現れる**

**聖書箇所：**[マルコによる福音書16章12-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_12-13.pdf)

-   イエスであることがわかったのは、いつでしょうか。それは、そのようにして、分かったのでしょうか。

-   「シモンに現れなさった」とあるが、それは、いつの、どのようなことについて述べているのだろうか。

### **弟子たちを派遣する**

**聖書箇所：**[マルコによる福音書16章14-18節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_14-18.pdf)

-   いつ、どこでのことなのだろうか。

-   追記とも考えられるが他の福音書とは、記述が異なる。別の資料だろうか。

### **天に上げられる**

**聖書箇所：**[マルコによる福音書16章19-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_19-20.pdf)

-   信仰告白なのだろうか、それとも、実際の経験なのだろうか。
-   復活の主との出会いの期間をある時点で区切ることと、さらに再び来られる（再臨）のメッセージを送ることで、主人不在のときの僕の生き方をわれわれに期待しておられるのだろうか。

### 復活について

**聖書箇所：**[マルコによる福音書16章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_1-8.pdf)

[マルコによる福音書16章9-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_9-11.pdf)

[マルコによる福音書16章12-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_12-13.pdf)

[マルコによる福音書16章14-18節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_14-18.pdf)

[マルコによる福音書16章19-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_19-20.pdf)

**参考箇所（上記以外の復活に関係する聖書箇所）：**

イエス自身についての証言（マルコを中心に。ルカではもっと数が多い）：

-   一回目：[マルコによる福音書8章31-38節, 9章1節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_31-38_9_1.pdf)

-   二回目：[マルコによる福音書9章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32.pdf)

-   三回目：[マルコによる福音書10章32-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34.pdf)

-   参照付き：[マルコによる福音書10章32-34節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34_extra.pdf)

    -   ルカ：5:35、9:22、44、12:50、13:32、17:25、18:31-34

-   ヨナのしるし：マタイ12:39-41、16:4、 ルカ11:29-32

高い山でイエスの姿が変わる：[マルコによる福音書9章2-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_2-13.pdf)

エルサレムでの復活に関する問答：[マルコによる福音書12章18-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_18-27.pdf)

マタイに含まれる番兵の配置と報告：27:62-66, 28:11-15

ヨハネ独自の記事：イエスの死のあとに、19:32-37

-   トマスに関する追記　ヨハネ20:24-29

-   ガリラヤでのこと ヨハネ21章

パウロによる証言：コリント前書15:3-8, 35-44

#### A. パウロ証言

#### B. 福音書証言

（整合性をたいせつに）

#### C. 問い

#### D. マルコを中心に

#### E. 個人的瞑想

## ヨハネによる福音書を中心として

## マタイによる福音書、ルカによる福音書を読むときに

### 復讐してはならない/敵を愛しなさい

マタイ5:38-48、ルカ6:27-36

-   実際にこのようにすべきだと命じているのだろうか。

    -   詐欺にあったとき、強盗に襲われた時、テロにあった時、他国が侵略してきた時、それをひたすら受け入れることが命じられているのか。
