# 資料

## マルコによる福音書表題 {#mark-titles}

```{r}
#| include: false
library(tidyverse)
library(DT)
library(showtext)
showtext_auto()
```

```{r}
#| label: marklist
#| message: false
#| echo: false

marklist <- read_csv("data/marklist.csv", 
    col_types = cols(...4 = col_skip(), ...6 = col_skip(), 
        ...8 = col_skip(), ...9 = col_skip()))
knitr::kable(head(marklist,98))
```

### マルコに含まれていない表題

```{r}
#| label: excmark
#| message: false
#| echo: false

excmark <- read_csv("data/excmark.csv")
knitr::kable(head(excmark, 67))
```

[マルコによる福音書の表題](https://icu-hsuzuki.github.io/science/bible/docs/mark.pdf)

## 登録・対面・遠隔

```{r}
#| message: false
#| echo: false
participants <- read_csv("./data/participants.csv") |>
  pivot_longer(cols = 3:4, names_to = "参加", values_to = "参加者数") |>
  mutate(参加 = factor(参加, levels = c("遠隔", "対面")))
```

```{r}
#| message: false
#| warning: false
#| echo: false
participants |> drop_na(参加, 登録) |>
  ggplot() + geom_col(aes(参加者数, 日付, fill = 参加)) +
  geom_point(aes(登録, 日付)) + 
  labs(title = "参加者数と登録者数（点で表示）", fill = "") 
```
