## 7:1-23 昔の人の言い伝え

> 1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。2 そして弟子たちのうちに、不浄な手、すなわち洗わない手で、パンを食べている者があるのを見た。3 もともと、パリサイ人をはじめユダヤ人はみな、昔の人の言伝えをかたく守って、念入りに手を洗ってからでないと、食事をしない。4 また市場から帰ったときには、身を清めてからでないと、食事をせず、なおそのほかにも、杯、鉢、銅器を洗うことなど、昔から受けついでかたく守っている事が、たくさんあった。5 そこで、パリサイ人と律法学者たちとは、イエスに尋ねた、「なぜ、あなたの弟子たちは、昔の人の言伝えに従って歩まないで、不浄な手でパンを食べるのですか」。6 イエスは言われた、「イザヤは、あなたがた偽善者について、こう書いているが、それは適切な預言である、／『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。7 人間のいましめを教として教え、／無意味にわたしを拝んでいる』。8 あなたがたは、神のいましめをさしおいて、人間の言伝えを固執している」。9 また、言われた、「あなたがたは、自分たちの言伝えを守るために、よくも神のいましめを捨てたものだ。10 モーセは言ったではないか、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。11 それだのに、あなたがたは、もし人が父または母にむかって、あなたに差上げるはずのこのものはコルバン、すなわち、供え物ですと言えば、それでよいとして、12 その人は父母に対して、もう何もしないで済むのだと言っている。13 こうしてあなたがたは、自分たちが受けついだ言伝えによって、神の言を無にしている。また、このような事をしばしばおこなっている」。14 それから、イエスは再び群衆を呼び寄せて言われた、「あなたがたはみんな、わたしの言うことを聞いて悟るがよい。15 すべて外から人の中にはいって、人をけがしうるものはない。かえって、人の中から出てくるものが、人をけがすのである。16 〔聞く耳のある者は聞くがよい〕」。17 イエスが群衆を離れて家にはいられると、弟子たちはこの譬について尋ねた。18 すると、言われた、「あなたがたも、そんなに鈍いのか。すべて、外から人の中にはいって来るものは、人を汚し得ないことが、わからないのか。19 それは人の心の中にはいるのではなく、腹の中にはいり、そして、外に出て行くだけである」。イエスはこのように、どんな食物でもきよいものとされた。20 さらに言われた、「人から出て来るもの、それが人をけがすのである。21 すなわち内部から、人の心の中から、悪い思いが出て来る。不品行、盗み、殺人、22 姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴。23 これらの悪はすべて内部から出てきて、人をけがすのである」。

### マタイ 15:1-20

> 1 ときに、パリサイ人と律法学者たちとが、エルサレムからイエスのもとにきて言った、2 「あなたの弟子たちは、なぜ昔の人々の言伝えを破るのですか。彼らは食事の時に手を洗っていません」。3 イエスは答えて言われた、「なぜ、あなたがたも自分たちの言伝えによって、神のいましめを破っているのか。4 神は言われた、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。5 それだのに、あなたがたは『だれでも父または母にむかって、あなたにさしあげるはずのこのものは供え物です、と言えば、6 父または母を敬わなくてもよろしい』と言っている。こうしてあなたがたは自分たちの言伝えによって、神の言を無にしている。7 偽善者たちよ、イザヤがあなたがたについて、こういう適切な預言をしている、8 『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。9 人間のいましめを教として教え、／無意味にわたしを拝んでいる』」。10 それからイエスは群衆を呼び寄せて言われた、「聞いて悟るがよい。11 口にはいるものは人を汚すことはない。かえって、口から出るものが人を汚すのである」。12 そのとき、弟子たちが近寄ってきてイエスに言った、「パリサイ人たちが御言を聞いてつまずいたことを、ご存じですか」。13 イエスは答えて言われた、「わたしの天の父がお植えにならなかったものは、みな抜き取られるであろう。14 彼らをそのままにしておけ。彼らは盲人を手引きする盲人である。もし盲人が盲人を手引きするなら、ふたりとも穴に落ち込むであろう」。15 ペテロが答えて言った、「その譬を説明してください」。16 イエスは言われた、「あなたがたも、まだわからないのか。17 口にはいってくるものは、みな腹の中にはいり、そして、外に出て行くことを知らないのか。18 しかし、口から出て行くものは、心の中から出てくるのであって、それが人を汚すのである。19 というのは、悪い思い、すなわち、殺人、姦淫、不品行、盗み、偽証、誹りは、心の中から出てくるのであって、20 これらのものが人を汚すのである。しかし、洗わない手で食事することは、人を汚すのではない」。

## 7:1-13 昔の人の言い伝え（1）

> 1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。2 そして弟子たちのうちに、不浄な手、すなわち洗わない手で、パンを食べている者があるのを見た。3 もともと、パリサイ人をはじめユダヤ人はみな、昔の人の言伝えをかたく守って、念入りに手を洗ってからでないと、食事をしない。4 また市場から帰ったときには、身を清めてからでないと、食事をせず、なおそのほかにも、杯、鉢、銅器を洗うことなど、昔から受けついでかたく守っている事が、たくさんあった。5 そこで、パリサイ人と律法学者たちとは、イエスに尋ねた、「なぜ、あなたの弟子たちは、昔の人の言伝えに従って歩まないで、不浄な手でパンを食べるのですか」。6 イエスは言われた、「イザヤは、あなたがた偽善者について、こう書いているが、それは適切な預言である、／『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。7 人間のいましめを教として教え、／無意味にわたしを拝んでいる』。8 あなたがたは、神のいましめをさしおいて、人間の言伝えを固執している」。9 また、言われた、「あなたがたは、自分たちの言伝えを守るために、よくも神のいましめを捨てたものだ。10 モーセは言ったではないか、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。11 それだのに、あなたがたは、もし人が父または母にむかって、あなたに差上げるはずのこのものはコルバン、すなわち、供え物ですと言えば、それでよいとして、12 その人は父母に対して、もう何もしないで済むのだと言っている。13 こうしてあなたがたは、自分たちが受けついだ言伝えによって、神の言を無にしている。また、このような事をしばしばおこなっている」。

### マタイ 15:1-9

> 1 ときに、パリサイ人と律法学者たちとが、エルサレムからイエスのもとにきて言った、2 「あなたの弟子たちは、なぜ昔の人々の言伝えを破るのですか。彼らは食事の時に手を洗っていません」。3 イエスは答えて言われた、「なぜ、あなたがたも自分たちの言伝えによって、神のいましめを破っているのか。4 神は言われた、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。5 それだのに、あなたがたは『だれでも父または母にむかって、あなたにさしあげるはずのこのものは供え物です、と言えば、6 父または母を敬わなくてもよろしい』と言っている。こうしてあなたがたは自分たちの言伝えによって、神の言を無にしている。7 偽善者たちよ、イザヤがあなたがたについて、こういう適切な預言をしている、8 『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。9 人間のいましめを教として教え、／無意味にわたしを拝んでいる』」。

### （参考）ルカ11:37-44

> 37 イエスが語っておられた時、あるパリサイ人が、自分の家で食事をしていただきたいと申し出たので、はいって食卓につかれた。38 ところが、食前にまず洗うことをなさらなかったのを見て、そのパリサイ人が不思議に思った。39 そこで主は彼に言われた、「いったい、あなたがたパリサイ人は、杯や盆の外側をきよめるが、あなたがたの内側は貪欲と邪悪とで満ちている。40 愚かな者たちよ、外側を造ったかたは、また内側も造られたではないか。41 ただ、内側にあるものをきよめなさい。そうすれば、いっさいがあなたがたにとって、清いものとなる。42 しかし、あなた方パリサイ人は、わざわいである。はっか、うん香、あらゆる野菜などの十分の一を宮に納めておりながら、義と神に対する愛とをなおざりにしている。それもなおざりにはできないが、これは行わねばならない。43 あなたがたパリサイ人は、わざわいである。会堂の上席や広場での敬礼を好んでいる。44 あなたがたは、わざわいである。人目につかない墓のようなものである。その上を歩いても人々は気づかないでいる」。（43-44 は、マルコ12:38-40 参照）

[マルコによる福音書7章1-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_1-13.pdf)

### 問い

1.  どのようなことが原因で、議論が始まりますか。（1,2）

2.  パリサイ人をはじめユダヤ人はみなどのようにしていたと書かれていますか。（3,4）

3.  パリサイ人と律法学者たちは何をたいせつにしていますか。それはなぜでしょうか。（5）

4.  イエスは、どのように批判していますか。イエスの批判の中心点は何ですか。（6-8）

5.  9節-12節の例では、6節-８節で指摘した要点のどのような面を説明しているのでしょうか。どのような対比がありますか。（9-12）

6.  「神の言を無にしている」とは何を指しているのでしょうか。（13）

### 参照

-   汚れについて

    -   使徒10:14 ペテロは言った、「主よ、それはできません。わたしは今までに、清くないもの、汚れたものは、何一つ食べたことがありません」。

    -   使徒10:28 ペテロは彼らに言った、「あなたがたが知っているとおり、ユダヤ人が他国の人と交際したり、出入りしたりすることは、禁じられています。ところが、神は、どんな人間をも清くないとか、汚れているとか言ってはならないと、わたしにお示しになりました。

    -   使徒11:8 わたしは言った、『主よ、それはできません。わたしは今までに、清くないものや汚れたものを口に入れたことが一度もございません』。

    -   黙示録21:27 しかし、汚れた者や、忌むべきこと及び偽りを行う者は、その中に決してはいれない。はいれる者は、小羊のいのちの書に名をしるされている者だけである。

-   汚れた手（κοιναῖς χερσίν）

    -   レビ8:6 そしてモーセはアロンとその子たちを連れてきて、水で彼らを洗い清め、

-   念入りに手を洗ってからでないと（πυγμῇ νίψωνται τὰς χεῖρας）πυγμῇ: i) the fist, clenched hand, ii) up to the elbow （聖書でここだけ）

-   歩む（περιπατοῦσιν: to walk）

    -   ローマ6:4 すなわち、わたしたちは、その死にあずかるバプテスマによって、彼と共に葬られたのである。それは、キリストが父の栄光によって、死人の中からよみがえらされたように、わたしたちもまた、新しいいのちに生きるためである。

    -   ローマ8:4 これは律法の要求が、肉によらず霊によって歩くわたしたちにおいて、満たされるためである。

-   偽善者（ὑποκριτής: i) one who answers, an interpreter, ii) an actor, stage player, iii) a dissembler, pretender, hypocrite）

-   ミシュナー、シャッパト1:4-8, ベラコート8:2-4, ヤーダイム1-2

-   昔の人々（ヘブル11:2）長老のこと（ラビ・ヒレルとラビ・シャンマイ）

-   出エジプト20:12 あなたの父と母を敬え。これは、あなたの神、主が賜わる地で、あなたが長く生きるためである。

-   出エジプト21:17 自分の父または母をのろう者は、必ず殺されなければならない。

-   出エジプト32:16 その板は神の作、その文字は神の文字であって、板に彫ったものである。

-   イザヤ29:13-20 主は言われた、／「この民は口をもってわたしに近づき、／くちびるをもってわたしを敬うけれども、／その心はわたしから遠く離れ、／彼らのわたしをかしこみ恐れるのは、／そらで覚えた人の戒めによるのである。14 それゆえ、／見よ、／わたしはこの民に、／再び驚くべきわざを行う、／それは不思議な驚くべきわざである。彼らのうちの賢い人の知恵は滅び、／さとい人の知識は隠される」。15 わざわいなるかな、／おのが計りごとを主に深く隠す者。彼らは暗い中でわざを行い、／「だれがわれわれを見るか、／だれがわれわれのことを知るか」と言う。16 あなたがたは転倒して考えている。陶器師は粘土と同じものに思われるだろうか。造られた物はそれを造った者について、／「彼はわたしを造らなかった」と言い、／形造られた物は形造った者について、／「彼は知恵がない」と言うことができようか。17 しばらくしてレバノンは変って肥えた畑となり、／肥えた畑は林のように／思われる時が来るではないか。18 その日、耳しいは書物の言葉を聞き、／目しいの目はその暗やみから、見ることができる。19 柔和な者は主によって新たなる喜びを得、／人のなかの貧しい者は／イスラエルの聖者によって楽しみを得る。20 あらぶる者は絶え、／あざける者はうせ、／悪を行おうと、おりをうかがう者は、／ことごとく断ち滅ぼされるからである。（アリエル：神の炉）

-   偽善（ヒュポクリーテス）：答える人、型にはまった対話・会話に答える人、俳優、その人の全生涯がその背後に全く何の真実もなく、芝居をするような人を意味するようになった。（バークレイ）

-   コルバン（κορβᾶν: i) a gift offered (or to be offered) to God, ii) the sacred treasury）קָרְבָּן: offering, oblation - レビ1:2, 3, 10, 14, 2:1, 4, 5, 7, 12, 13, 3:1, 2, 6, 7, 8, 12, 14, 4:23, 28, 5:11, 6:20, 7:13, 14, 15, 16, 29, 38, 9:7, 9:15, 17:4, 22:18, 27, 23:14, 27:9, 11, 民数記 5:15, 6:14, 21, 7:3, 10, 11, 12, 13, 17, 19, 23, 25, 29, 31,35, 37, 41, 43, 47, 49, 53, 55, 59, 61, 65, 67, 71, 73, 77, 79, 83, 9:7, 13, 15:4, 25, 18:9, 28:2, 31:50, ネヘミヤ 10:34, 13:31, エゼキエル 20:28, 40:43 - offering

### 記録

-   日時：2023年12月21日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）5名

### 問いについて

1.  どのようなことが原因で、議論が始まりますか。（1,2）

    -   1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。2 そして弟子たちのうちに、不浄な手、すなわち洗わない手で、パンを食べている者があるのを見た。

    -   \[DQ\] なぜ、エルサレムから、パリサイ人と、（ある）律法学者たちとが、イエスのもとに集まったのでしょう。

        -   いつのことなのか書いてない。ガリラヤから離れる直前に置かれている。

2.  パリサイ人をはじめユダヤ人はみなどのようにしていたと書かれていますか。（3,4）

    -   3 もともと、パリサイ人をはじめユダヤ人はみな、昔の人の言伝えをかたく守って、念入りに手を洗ってからでないと、食事をしない。4 また市場から帰ったときには、身を清めてからでないと、食事をせず、なおそのほかにも、杯、鉢、銅器を洗うことなど、昔から受けついでかたく守っている事が、たくさんあった
    -   \[DQ\] なぜ、ユダヤ人である弟子たちのある者が、洗わない手で、パンを食べていたのでしょうか。

3.  パリサイ人と律法学者たちは何をたいせつにしていますか。それはなぜでしょうか。（5）

    -   5 そこで、パリサイ人と律法学者たちとは、イエスに尋ねた、「なぜ、あなたの弟子たちは、昔の人の言伝えに従って歩まないで、不浄な手でパンを食べるのですか」。

    -   \[DQ\] なぜ、行為者の弟子に問わないで、イエスに問うているのでしょうか。

    -   \[DQ\] イエスはどうだったのでしょうか。

        -   このときのイエスについては不明。しかし、非難された、弟子たちをまずは、庇（かば）っているようにも見える。

        -   「安息日に麦の穂を摘む」（2:23-28）弟子たち

        -   ルカ11:37-44 37 イエスが語っておられた時、あるパリサイ人が、自分の家で食事をしていただきたいと申し出たので、はいって食卓につかれた。38 ところが、食前にまず洗うことをなさらなかったのを見て、そのパリサイ人が不思議に思った。

    -   \[DQ\] パリサイ人と律法学者たちにとって「昔のひとの言い伝え」は、どんな意味を持っているのでしょうか。

        -   律法を厳格に守ろうとしたひとたちの教えを忠実に守ることによって、律法を守っていることを証明すること。

4.  イエスは、どのように批判していますか。イエスの批判の中心点は何ですか。（6-8）

    -   6 イエスは言われた、「イザヤは、あなたがた偽善者について、こう書いているが、それは適切な預言である、／『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。7 人間のいましめを教として教え、／無意味にわたしを拝んでいる』。8 あなたがたは、神のいましめをさしおいて、人間の言伝えを固執している」。

    -   何を大切にしているかがずれてきてしまっている。

    -   \[DQ\] 本当に「神のいましめをさしおいて、人間の言伝えを固執している」という状態になってしまっているのでしょうか。

    -   \[DQ\] イエスが批判しているのは、何なのでしょうか。

5.  9節-12節の例では、6節-８節で指摘した要点のどのような面を説明しているのでしょうか。どのような対比がありますか。（9-12）

    -   9 また、言われた、「あなたがたは、自分たちの言伝えを守るために、よくも神のいましめを捨てたものだ。10 モーセは言ったではないか、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。11 それだのに、あなたがたは、もし人が父または母にむかって、あなたに差上げるはずのこのものはコルバン、すなわち、供え物ですと言えば、それでよいとして、12 その人は父母に対して、もう何もしないで済むのだと言っている。

    -   \[DQ\] どのようなことが行われていたのだと思いますか。

    -   \[DQ\] 異なる例を挙げていますが、手を洗わないことに関して解釈すると、どのようなことを言っているのでしょうか。

        -   衛生面を強調して、肯定することも、できたのではないだろうか。おそらく、後半から次につながる部分が大切だとしたのだろう。

6.  「神の言を無にしている」とは何を指しているのでしょうか。（13）

    -   13 こうしてあなたがたは、自分たちが受けついだ言伝えによって、神の言を無にしている。また、このような事をしばしばおこなっている」。

    -   コルバンに関しては、そのように解釈することで、実際には、父母を大切にしないことになってしまっていないいか。

    -   手を洗わないことに関しては、単に、あるひとたちを排除したり、分断を作り出すようなことをしていないか。

### メモ

-   山浦玄嗣（やまうら はるつぐ）訳「ガリラヤのイェシュー」イー・ピックス出版では、次のように訳されている

    -   2 ところで、イェシューさまの弟子たちの中には、お浄めもしない手で、つまり洗いもしないてで、飯を食う者がござった。お歴々はこれに目くじらを立ててござる。

    -   8 お前さまがたは神さまの掟のほうは打ち棄てて、人のつくった仕来りばかりシッカリ固くお守りなさる。」

    -   12の後にかっこ付きで追記（辻褄の合わぬこんな屁理屈をこねまわして、親への孝養をないがしろにする、かかる悪しき習わしが当世の流行りにて、子から捨てられて難儀する貧しい年老いた親たちの何と多かったことか。イェシューさまはこれをおしかりになっておられるのでござる。）

    -   13 こうしてお前さまがたは自分たちが受け継いできた仕来りのために神様の言葉を破り捨てていなさる。そうして更に、この類のことをさまざまなさっている。

-   何を本当に大切にするのか。

    -   書かれたものの解釈に終始するのではなく、御心はなにかを求め続けること。

## 7:14-23 昔の人の言い伝え（2）

> 14 それから、イエスは再び群衆を呼び寄せて言われた、「あなたがたはみんな、わたしの言うことを聞いて悟るがよい。15 すべて外から人の中にはいって、人をけがしうるものはない。かえって、人の中から出てくるものが、人をけがすのである。16 〔聞く耳のある者は聞くがよい〕」。17 イエスが群衆を離れて家にはいられると、弟子たちはこの譬について尋ねた。18 すると、言われた、「あなたがたも、そんなに鈍いのか。すべて、外から人の中にはいって来るものは、人を汚し得ないことが、わからないのか。19 それは人の心の中にはいるのではなく、腹の中にはいり、そして、外に出て行くだけである」。イエスはこのように、どんな食物でもきよいものとされた。20 さらに言われた、「人から出て来るもの、それが人をけがすのである。21 すなわち内部から、人の心の中から、悪い思いが出て来る。不品行、盗み、殺人、22 姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴。23 これらの悪はすべて内部から出てきて、人をけがすのである」。

### マタイ 15:10-20

> 10 それからイエスは群衆を呼び寄せて言われた、「聞いて悟るがよい。11 口にはいるものは人を汚すことはない。かえって、口から出るものが人を汚すのである」。12 そのとき、弟子たちが近寄ってきてイエスに言った、「パリサイ人たちが御言を聞いてつまずいたことを、ご存じですか」。13 イエスは答えて言われた、「わたしの天の父がお植えにならなかったものは、みな抜き取られるであろう。14 彼らをそのままにしておけ。彼らは盲人を手引きする盲人である。もし盲人が盲人を手引きするなら、ふたりとも穴に落ち込むであろう」。15 ペテロが答えて言った、「その譬を説明してください」。16 イエスは言われた、「あなたがたも、まだわからないのか。17 口にはいってくるものは、みな腹の中にはいり、そして、外に出て行くことを知らないのか。18 しかし、口から出て行くものは、心の中から出てくるのであって、それが人を汚すのである。19 というのは、悪い思い、すなわち、殺人、姦淫、不品行、盗み、偽証、誹りは、心の中から出てくるのであって、20 これらのものが人を汚すのである。しかし、洗わない手で食事することは、人を汚すのではない」。

[マルコによる福音書7章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_14-23.pdf)

### 問い

1.  前回の部分を復習しましょう。どのようなできごとがあり、またパリサイ人の批判に、イエスはどのように答えていますか。

2.  イエスは、誰に対して、何を語っていますか。（14-16）

3.  マタイでは、さらに、どのようなことを伝えていますか。（マタイ15:12-15）

4.  イエスは人を汚すものについてどのように説明していますか。（17-23）

5.  「不品行、盗み、殺人、姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴」が人を汚すのは、なぜでしょうか。（22）

6.  イエスの言う人を汚すとはどのようなことで、パリサイ人たちが考える汚れと何が違いますか。

### 参照

-   食べてはならない
    -   創世記2:17 しかし善悪を知る木からは取って**食べてはならない**。それを取って食べると、きっと死ぬであろう」。
    -   創世記9:4 しかし肉を、その命である血のままで、**食べてはならない**。
    -   レビ3:17 あなたがたは脂肪と血とをいっさい**食べてはならない**。これはあなたがたが、すべてその住む所で、代々守るべき永久の定めである』」。
    -   レビ11 4 ただし、反芻するもの、またはひずめの分かれたもののうち、次のものは**食べてはならない**。すなわち、らくだ、これは、反芻するけれども、ひずめが分かれていないから、あなたがたには汚れたものである。\[その他多数\]
    -   申命記14 7 ただし、反芻するものと、ひずめの分れたもののうち、次のものは**食べてはならない**。すなわち、らくだ、野うさぎ、および岩だぬき、これらは反芻するけれども、ひずめが分れていないから汚れたものである。8 また豚、これは、ひずめが分れているけれども、反芻しないから、汚れたものである。その肉を**食べてはならない**。またその死体に触れてはならない。\[その他多数\]
-   使徒行伝10:1-11:18, 15:6-11（汚れについて）
    -   使徒10:14 ペテロは言った、「主よ、それはできません。わたしは今までに、清くないもの、汚れたものは、何一つ食べたことがありません」。

    -   使徒10:28 ペテロは彼らに言った、「あなたがたが知っているとおり、ユダヤ人が他国の人と交際したり、出入りしたりすることは、禁じられています。ところが、神は、どんな人間をも清くないとか、汚れているとか言ってはならないと、わたしにお示しになりました。

    -   使徒11:8 わたしは言った、『主よ、それはできません。わたしは今までに、清くないものや汚れたものを口に入れたことが一度もございません』。

    -   使徒15:6-11 そこで、使徒たちや長老たちが、この問題について審議するために集まった。 7 激しい争論があった後、ペテロが立って言った、「兄弟たちよ、ご承知のとおり、異邦人がわたしの口から福音の言葉を聞いて信じるようにと、神は初めのころに、諸君の中からわたしをお選びになったのである。8 そして、人の心をご存じである神は、聖霊をわれわれに賜わったと同様に彼らにも賜わって、彼らに対してあかしをなし、9 また、その信仰によって彼らの心をきよめ、われわれと彼らとの間に、なんの分けへだてもなさらなかった。10 しかるに、諸君はなぜ、今われわれの先祖もわれわれ自身も、負いきれなかったくびきをあの弟子たちの首にかけて、神を試みるのか。11 確かに、主イエスのめぐみによって、われわれは救われるのだと信じるが、彼らとても同様である」。
-   マルコ3:28-30 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。そう言われたのは、彼らが「イエスはけがれた霊につかれている」と言っていたからである。マタイ12:31 だから、あなたがたに言っておく。人には、その犯すすべての罪も神を汚す言葉も、ゆるされる。しかし、聖霊を汚す言葉は、ゆるされることはない。
-   マカバイ記一1章 62節-64節 だがイスラエル人の多くはそれにも屈せず、断固として不浄のものを口にしなかった。63 彼らは、食物によって身を汚して聖なる契約に背くよりは、死を選んで命を落としていった。64 大いなる怒りがイスラエルの上に激しく臨んだ。
-   マカバイ記二7章1節-42節 また、七人の兄弟が母親と共に捕らえられ、鞭や革ひもで責め苦を受け、律法に反して豚肉を食するように王から強いられることとなった。2 彼らの一人が弁明して言った。「あなたは何を尋ね、我々から聞き出そうとしているのか。我々は、父祖の律法に違反するぐらいなら死ぬ覚悟がある。」3 激怒した王は、鍋や大釜に火をつけるように命じた。

### 記録

-   日時：2024年1月11日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）1名

### 問いについて

1.  前回の部分を復習しましょう。どのようなできごとがあり、またパリサイ人の批判に、イエスはどのように答えていますか。

    -   （きっかけ）1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。2 そして弟子たちのうちに、不浄な手、すなわち洗わない手で、パンを食べている者があるのを見た。

    -   （問）5 そこで、パリサイ人と律法学者たちとは、イエスに尋ねた、「なぜ、あなたの弟子たちは、昔の人の言伝えに従って歩まないで、不浄な手でパンを食べるのですか」。

    -   （イエスの答え）6 イエスは言われた、「イザヤは、あなたがた偽善者について、こう書いているが、それは適切な預言である、／『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。7 人間のいましめを教として教え、／無意味にわたしを拝んでいる』。その後に例示

    -   自分たちの言い伝えを、神の戒めよりも優先している。

    -   イエスは、論点を変えているように見える。

    -   本当にそれが重要なのと聞いているのようにも見える。

2.  イエスは、誰に対して、何を語っていますか。（14-16）

    -   14 それから、イエスは再び群衆を呼び寄せて言われた、「あなたがたはみんな、わたしの言うことを聞いて悟るがよい。15 すべて外から人の中にはいって、人をけがしうるものはない。かえって、人の中から出てくるものが、人をけがすのである。16 〔聞く耳のある者は聞くがよい〕」。

    -   「『再び（πάλιν: 写本に依存）』群衆を呼び寄せて言われた」からは、群衆たちは、エルサレムからのパリサイ人とある律法学者が問うているときに、身を引いている印象をうける。群衆は、権威とは、違うことを、あるていど、理解していたのかもしれない。

    -   「あなたがたはみんな、わたしの言うことを聞いて悟るがよい。」（14b, マタイ15:10 にもある）および「〔聞く耳のある者は聞くがよい〕」。」（16）（マルコ4:9, 23, ルカ8:8 種まきのたとえ）からは、とても大切なこと、本質的なことを語っているように見える。

    -   「すべて外から人の中にはいって、人をけがしうるものはない。かえって、人の中から出てくるものが、人をけがすのである。」（15）は、これだけで、群衆がどれだけ、理解できたかは、不明だが、非常に過激なことをいっているように見える。

3.  マタイでは、さらに、どのようなことを伝えていますか。（マタイ15:12-15）

    -   12 そのとき、弟子たちが近寄ってきてイエスに言った、「パリサイ人たちが御言を聞いてつまずいたことを、ご存じですか」。13 イエスは答えて言われた、「わたしの天の父がお植えにならなかったものは、みな抜き取られるであろう。14 彼らをそのままにしておけ。彼らは盲人を手引きする盲人である。もし盲人が盲人を手引きするなら、ふたりとも穴に落ち込むであろう」。15 ペテロが答えて言った、「その譬を説明してください」。

    -   弟子たちが問うのではなく、挿入がある。そして、ペテロがお願いをしている。しかし、このあとの、つながりから、パリサイ人たちが、躓いたのは、汚れについてであることと思われる。イエスのメッセージ、「聞いて悟るがよい。11 口にはいるものは人を汚すことはない。かえって、口から出るものが人を汚すのである」と、律法との関係を深く理解して、躓いたのかは、不明。

    -   躓く（σκανδαλίζω: to put a stumbling block or impediment in the way, upon which another may trip and fall, metaph. to offend; a) to entice to sin b) to cause a person to begin to distrust and desert one whom he ought to trust and obey, c) since one who stumbles or whose foot gets entangled feels annoyed）立ち上がれなくなるとの意味だろうが、価値観も入っているかもしれない。一般的には、イエスのことばは、まったく受け入れられないと反発したということか。

4.  イエスは人を汚すものについてどのように説明していますか。（17-23）

    -   17 イエスが群衆を離れて家にはいられると、弟子たちはこの譬について尋ねた。18 すると、言われた、「あなたがたも、そんなに鈍いのか。すべて、外から人の中にはいって来るものは、人を汚し得ないことが、わからないのか。19 それは人の心の中にはいるのではなく、腹の中にはいり、そして、外に出て行くだけである」。イエスはこのように、どんな食物でもきよいものとされた。20 さらに言われた、「人から出て来るもの、それが人をけがすのである。21 すなわち内部から、人の心の中から、悪い思いが出て来る。不品行、盗み、殺人、22 姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴。23 これらの悪はすべて内部から出てきて、人をけがすのである」。

    -   「イエスが群衆を離れて家にはいられると、弟子たちはこの譬について尋ねた。」から始まっており、この部分、詳しい解説は、弟子たちに話したことになっている。おそらく、群衆には理解が難しく、パリサイ人や律法学者とは、激しい議論になってしまうことを避けたのかもしれない。争い以外生み出さないかもしれないので。

    -   「あなたがたも、そんなに鈍いのか。」と始めているところからも、弟子たちは、悟るべきだったことがわかる。イエスは、神の子だからわかるのではなく、我々も、御心を求めていれば、理解できるはずというのが、イエスの論理なのだろう。

        -   マタイでは、弟子たちが叱責されたようには、記述せず、パリサイ人が躓いたとして、ペテロに「その譬を説明してください」。（マタイ15:15）と語らせている。

    -   「人から出て来るもの、それが人をけがすのである。」ここに本質がある。

        -   しかし、実によって木がわかるように、さらに、人の中に問題があるとも考えられる。

    -   \[DQ\] ここにある悪は、だれを汚すのでしょうか。悪い思いが出た人でしょうか、それとも、その周囲の人でしょうか。

        -   周囲の人が汚されるように見える。

        -   おそらく、神との交わりが、危うくなることを言っているのだろう。明確ではない。

5.  「不品行、盗み、殺人、姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴」が人を汚すのは、なぜでしょうか。

    -   イエスの頭にあるのは、神さまとの関係が壊れてしまう。神さまの御心がなる世界とは、まったく違うということなのかもしれない。神の国が近くない状態になる。

    -   神との関係より、肉との関係を優先、または、神が愛される他者を犯す、傷付ける。

    -   μοιχεῖαι (adultery), πορνεῖαι ((i) illicit sexual intercourse, (ii) metaph. the worship of idols) φόνοι (murder, slaughter) κλοπαί (theft) πλεονεξίαιπονηρίαι (greedy desire to have more, covetousness, avarice) δόλος (craft, deceit, guile) ἀσέλγεια (unbridled lust, excess, licentiousness, lasciviousness, wantonness, outrageousness, shamelessness, insolence) ὀφθαλμὸς πονηρός ((i) full of labours, annoyances, hardships, (ii) bad, of a bad nature or condition) βλασφημία ((i) slander, detraction, speech injurious, to another's good name. (ii) impious and reproachful speech injurious to divine majesty) ὑπερηφανία ((i) pride, haughtiness, arrogance, (ii) the character of one who, with a swollen estimate of his own powers or merits, looks down on others and even treats them with insolence and contempt) ἀφροσύνη ((i) foolishness, folly, senselessness, (ii) thoughtlessness, recklessness)

    -   女郎買い、盗み、追剥ぎ、人殺し、人の女房さ手を出したり、よその男を引っ張り込むような外道の振る舞い、強欲、意地の悪い腐れ根性、噓語りの悪巧み、際限のねぁ色好み、嫉妬、悪口に、我ばり立派ぶる威張った心、無分別、こんな碌でもねァごどづァみんな人の心の中がら、ゴダビダ出はって、人を汚く汚すのだ。

6.  イエスの言う人を汚すとはどのようなことで、パリサイ人たちが考える汚れと何が違いますか。

    -   イエスの言えう汚すとは、神のみ心をおこなうことから、離れさす。パリサイ人たちが考える汚れは、神のもとにいる清い自分たちが、神のもとにいないものと接触することによって、自分たちが汚れ、神のもとにいられなくなる。

    -   \[DQ\] イエスは、人々や弟子たちに何を教えているのでしょうか。

        -   何が、本質的なことかを問うているように見える。

    -   神との関係を断つこと、神との交わりを大切にしないこと、パリサイ人も本来は、それを、求めている。

    -   マカバイ一 1:62-64、マカバイ二 7:1-42

### メモ

-   当時としては、非常に革命的な発言だったと思われる。そしてそれが、キリスト教会が世界宗教へとなっていった、鍵となる出来事でもある。異邦人の捉え方に、大きな影響を持つことになったのだから。

    -   レビ記11章の長いリストの否定。おそらく、それを明確には、イエスは告げていない。イエスは、それよりも、上の次元、神さま目線での交わりを大切にされたのではないだろうか。神さまが大切な一人ひとりをたいせつにすること、それを犯すことが、汚すということなのではないだろうか。そのレベルで理解できないと、パリサイ人や、律法学者の理解と、同じ地平となり、単なる分裂をうみだすだけとなってしまう。

    -   ユダヤ人が死をもいとわず、拒否したもの。食べ物のこと、その議論は、キリスト教会のなかでも続くが、それが最終的ではないことを、リーダーたちが確認できたことは、やはり、重要だったのだろう。コルネリオとのこと、エルサレム使徒会議に続く部分が、この次のシリア・フェニキアの女の信仰へとつながる。それ故に、独立であっても、ここに置かれたのだろう。マルコ的にはとても、得意な記事の挿入になっている。ペトロ由来として、たいせつな記事だったのだろう。

## 7:24-30 シリア・フェニキアの女の信仰

> 24 さて、イエスは、そこを立ち去って、ツロの地方に行かれた。そして、だれにも知れないように、家の中にはいられたが、隠れていることができなかった。25 そして、けがれた霊につかれた幼い娘をもつ女が、イエスのことをすぐ聞きつけてきて、その足もとにひれ伏した。26 この女はギリシヤ人で、スロ・フェニキヤの生れであった。そして、娘から悪霊を追い出してくださいとお願いした。27 イエスは女に言われた、「まず子供たちに十分食べさすべきである。子供たちのパンを取って小犬に投げてやるのは、よろしくない」。28 すると女は答えて言った、「主よ、お言葉どおりです。でも、食卓の下にいる小犬も、子供たちのパンくずは、いただきます」。29 そこでイエスは言われた、「その言葉で、じゅうぶんである。お帰りなさい。悪霊は娘から出てしまった」。30 そこで、女が家に帰ってみると、その子は床の上に寝ており、悪霊は出てしまっていた。

### マタイ 15:21-28

> 21 さて、イエスはそこを出て、ツロとシドンとの地方へ行かれた。22 すると、そこへ、その地方出のカナンの女が出てきて、「主よ、ダビデの子よ、わたしをあわれんでください。娘が悪霊にとりつかれて苦しんでいます」と言って叫びつづけた。23 しかし、イエスはひと言もお答えにならなかった。そこで弟子たちがみもとにきて願って言った、「この女を追い払ってください。叫びながらついてきていますから」。24 するとイエスは答えて言われた、「わたしは、イスラエルの家の失われた羊以外の者には、つかわされていない」。25 しかし、女は近寄りイエスを拝して言った、「主よ、わたしをお助けください」。26 イエスは答えて言われた、「子供たちのパンを取って小犬に投げてやるのは、よろしくない」。27 すると女は言った、「主よ、お言葉どおりです。でも、小犬もその主人の食卓から落ちるパンくずは、いただきます」。28 そこでイエスは答えて言われた、「女よ、あなたの信仰は見あげたものである。あなたの願いどおりになるように」。その時に、娘はいやされた。

[マルコによる福音書7章24-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_24-30.pdf)

### 問い

1.  イエスは、どこから、どこへ移動しますか。それは、なぜでしょうか。（24）

2.  この女の人はどのようなひとで、どんな問題を持っていますか。(25,26)

3.  この女の人と、イエスの対話は、どのように進みますか。（26b-29）

4.  そしてどうなりますか。（30）

5.  マタイからはさらにどのようなことがわかりますか。

6.  イエスの対応から、あなたは、どのようなことを感じますか。

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   新約聖書にでてくるスロ・フェニキヤ（Syrophenician）は、どこのことだと考えられていますか。

    -   Google Bard：新約聖書に登場するスロ・フェニキヤ（Syrophenician）は、シリアとフェニキアの両方に属する地域を指すと考えられています。具体的には、現在のレバノン、シリア、イスラエル北部にあたります。

        スロ・フェニキアの語源は、ギリシャ語で「シリア人」を意味する「Σύρος（スュロス）」と、「フェニキア人」を意味する「Φοίνικες（フォイニケス）」を組み合わせたものです。このことから、スロ・フェニキヤは、フェニキア人の住む地域であるシリアを含む地域を指すと考えられています。

        新約聖書のマルコによる福音書7章24節とマタイによる福音書15章22節には、イエス・キリストがスロ・フェニキアの地方で、汚れた霊にとりつかれた娘を持つ女性を癒したという記述があります。この女性は、ユダヤ人ではない異邦人であったため、イエスは最初は彼女の願いを拒みました。しかし、女性の信仰に心を動かされたイエスは、彼女の娘を癒しました。

        このエピソードは、イエス・キリストが異邦人にも救いの手を差し伸べたことを示すものとして、重要な意味を持っています。

    -   Poe Assistant: 新約聖書における「スロ・フェニキヤ」（Syrophenician）という表現は、マルコによる福音書（マルコ7:26）および[^markdq7-1]。しかし、この表現については諸説あります。

        一般的には、「スロ・フェニキヤ」とは、シリア地方のフェニキヤ人（フェニキア人）出身の女性を指すと解釈されています。フェニキヤは古代の地域であり、現在のレバノンやシリアの一部に相当します。この女性はギリシャ語で「カナン人の女」とも呼ばれています。

        ただし、この表現については異論も存在します。一部の学者は、スロ・フェニキヤがフェニキヤ人ではなく、シリア人やスリア人（アラム人）を指す可能性もあると主張しています。これは、ギリシャ語の表現や文脈に基づく解釈です。

        したがって、「スロ・フェニキヤ」が具体的にどの地域や民族を指しているのか正確に特定することは難しいです。ただし、この女性はイエス・キリストに対して求めていた癒しや恵みを受けるために頼み込んでいたことが記されており、彼女の信仰心とイエスへの信頼が強調されています。

[^markdq7-1]: 実際には、マタイには、ない。

### 記録

-   日時：2024年1月18日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）7名

### 問いについて

1.  イエスは、どこから、どこへ移動しますか。それは、なぜでしょうか。（24）

    -   24 さて、イエスは、そこを立ち去って（Ἐκεῖθεν (from thence) δὲ ἀναστὰς" (arose) ἀπῆλθεν (went)）、ツロの地方に行かれた。そして、だれにも知れないように、家の中にはいられたが、隠れていることができなかった。

    -   「そこ」はどこかは、不明だが、おそらく、ガリラヤ。ツロは、カペナウムからは、北西へ 64km。シドンは、ツロの41km 東北。

    -   \[DQ\] イエスはなぜ、「だれにも知れないように、家の中にはいられたが、隠れてい」たのでしょうか。

        -   すでに危険な状態になっていたのかもしれない。

    -   \[DQ\] イエスはなぜ、「だれにも知れないように、家の中にはいられたが、隠れていることができなかった。」のでしょうか。

        -   群衆の支持はあったようなので、噂は、十分広がっていたと思われる。

        -   参照：マルコ3:8 エルサレムから、イドマヤから、更にヨルダンの向こうから、ツロ、シドンのあたりからも、おびただしい群衆が、そのなさっていることを聞いて、みもとにきた。（マルコでは、ツロは、引用箇所と、7:24,31 のみ）

2.  この女の人はどのようなひとで、どんな問題を持っていますか。(25,26)

    -   25 そして、けがれた霊につかれた幼い娘をもつ女が、イエスのことをすぐ聞きつけてきて、その足もとにひれ伏した。26 この女はギリシヤ人で、スロ・フェニキヤの生れであった。そして、娘から悪霊を追い出してくださいとお願いした。

    -   隠れていくることができなかったことにも関係している。

    -   足元にひれ伏しは、一般的には、礼拝をしたことを意味する。

    -   ギリシャ人で、スロ・フェニキヤの生れ（スロ・フェニキヤは、ここだけ）

    -   「娘から悪霊を追い出してくださいとお願いした。」この状態は、不明だが、「30 そこで、女が家に帰ってみると、その子は床の上に寝ており、悪霊は出てしまっていた。」との対比により、多少の情報を与えている。わめいて、泣きじゃくったり、怒ったり、癇癪をおことしたり死て、床に大人しく寝ているような娘ではなかったのだろう。すくなくとも、平安をもって、神さまのみこころを求められるような状態ではなかったのだろう。

3.  この女の人と、イエスの対話は、どのように進みますか。（26b-29）

    -   26b そして、娘から悪霊を追い出してくださいとお願いした。27 イエスは女に言われた、「まず子供たちに十分食べさすべきである。子供たちのパンを取って小犬に投げてやるのは、よろしくない」。28 すると女は答えて言った、「主よ、お言葉どおりです。でも、食卓の下にいる小犬も、子供たちのパンくずは、いただきます」。29 そこでイエスは言われた、「その言葉で、じゅうぶんである。お帰りなさい。悪霊は娘から出てしまった」。

    -   子犬：κυνάριον（a little dog）27 も 28 も同じことば。マタイも同じ言葉を使っている。犬：κύων（i) a dog, ii) metaph. a man of impure mind, an impudent man - Mt 7:6, Luke 16:21, Phil 3:2, 2Pet 2:22, Rev 22:15）

    -   \[DQ\] イエスは、ユダヤ人を、子供たちと、異邦人を、犬または子犬と思っていたのでしょうか。

    -   \[DQ\] イエスは、なぜ「その言葉で、じゅうぶんである。お帰りなさい。（行きなさい。ὕπαγε）悪霊は娘から出てしまった」。と言えるほどの確信を持っていたのでしょうか。

    -   「まず」が印象的、「子犬」も、差別的に取っていない。「食卓」の話をしているのは、女性のみ。神の食卓を思わされる。

4.  そしてどうなりますか。（30）

    -   30 そこで、女が家に帰ってみると、その子は床の上に寝ており、悪霊は出てしまっていた。

    -   この記述にも、女の信仰が現れているように見える。マタイほど具体的には書かれていないが。

    -   「女が帰ってみると」とある。その前には、イエスが「その言葉で、じゅうぶんである。お帰りなさい。悪霊は娘から出てしまった」と宣言している。実際に、悪霊が娘からでた証拠はなにも与えられていない。しかし、帰ってみるとの表現からは、疑いもあったかもしれないが、やはり信じて帰ったように見える。マタイでは、それを、「28 そこでイエスは答えて言われた、「女よ、あなたの信仰は見あげたものである。あなたの願いどおりになるように」。その時に、娘はいやされた。」と表現して、信仰のゆえに、いやされた表現になっている。

5.  マタイからはさらにどのようなことがわかりますか。

    -   「その地方出のカナンの女」と紹介している。

    -   「主よ、ダビデの子よ、わたしをあわれんでください。娘が悪霊にとりつかれて苦しんでいます」この表現もマルコとは、かなり異なる。ダビデの子は、救い主の通称だろうが、マルコでは、イエスを「ダビデの子」と呼んだのは、10:47,48 のみで、イエスはその呼称を不適切としている。

        -   10:47 ところが、ナザレのイエスだと聞いて、彼は「ダビデの子イエスよ、わたしをあわれんでください」と叫び出した。48 多くの人々は彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子イエスよ、わたしをあわれんでください」。

        -   12:35 イエスが宮で教えておられたとき、こう言われた、「律法学者たちは、どうしてキリストを**ダビデの子**だと言うのか。37 このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。大ぜいの群衆は、喜んでイエスに耳を傾けていた。

        -   「わたしをあわれんでください」そして、さらに、25 しかし、女は近寄りイエスを拝して言った、「主よ、わたしをお助けください」。でも「わたしを」とあり、この女の苦しみ、訴えを中心に描いている。

        -   この娘の存在が、この女性にたいする批判・非難にもつながっていたかもしれない。

    -   23 しかし、イエスはひと言もお答えにならなかった。そこで弟子たちがみもとにきて願って言った、「この女を追い払ってください。叫びながらついてきていますから」。このことばは、かなり厳しいように見える。それゆえに、イエスも、それにつられて、24 するとイエスは答えて言われた、「わたしは、イスラエルの家の失われた羊以外の者には、つかわされていない」。と言ったように見える。このあたりは、マルコと微妙にことなる。

6.  イエスの対応から、あなたは、どのようなことを感じますか。

    -   隠れていたかった理由があるのだろう。そして、イスラエルの民のことを、第一に考えていたのではないだろうか。なかなか受け入れられず、指導者からは、疑いの目で見られ、悪意をもたれ、おそらく、バプテスマのヨハネの処刑以降は、身の危険も感じはじめている。群衆には、必要はあり、求めてはくるものの、イエスをそして、神の国に関する、メッセージを理解せず、弟子たちも、神の国の奥義を理解するという意味では、十分な訓練を受けているとは、見えない。

### メモ

-   マタイでは、主導権を取っているのは、女のようにみえる。しかし、マルコでは、その度合は弱く、イエスの、正直であっても、こだわりがない、丁寧な対応が、浮き彫りにされているようにみえる。

-   引きこもりのイエスについては、しっかり考えたいと思った。非常に、珍しい表現であるように思う。「24 さて、イエスは、そこを立ち去って、ツロの地方に行かれた。そして、だれにも知れないように、家の中にはいられたが、隠れていることができなかった。」

-   翻訳の関係もあるが、最後の「お帰りなさい。悪霊は娘から出てしまった」と「悪霊は出てしまっていた。」の呼応は単純ではあるが、印象的である。イエスは、なぜ、ここまで確信を持てたのだろうか。

-   イエスのこの期間の行動は興味深い。しかし、あたらしい出発でもあるように見えるのは、その後の歴史を見ているからか。

-   イエスは、自分が遣わされたユダヤ人たちの状態を見て、苦慮していたと思われる。それが、まさにイエスがこころをいためていた問題だった。そこでの女性との出会いである。あまり、イエスは神の子だから、最初から普遍性、すべてのひとの救いを考えていたなどと取ったり、逆に、差別的なユダヤ人てき考えを持っていたが、ここで変わったとか、そのように理解するのは、どちらも、問題があるように思われる。イエスの関心は、こどもたちに向けられていて、苦慮していただけである。しかしそんなときにも、この女に向き合われたことが記録され、そが、キリスト教として、普遍化へと進むときに、おおきな、支えとなったと考えたほうがよいように、思われる。

## 7:31-37 耳が聞こえず舌の回らない人を癒やす

> 31 それから、イエスはまたツロの地方を去り、シドンを経てデカポリス地方を通りぬけ、ガリラヤの海べにこられた。32 すると人々は、耳が聞えず口のきけない人を、みもとに連れてきて、手を置いてやっていただきたいとお願いした。33 そこで、イエスは彼ひとりを群衆の中から連れ出し、その両耳に指をさし入れ、それから、つばきでその舌を潤し、34 天を仰いでため息をつき、その人に「エパタ」と言われた。これは「開けよ」という意味である。35 すると彼の耳が開け、その舌のもつれもすぐ解けて、はっきりと話すようになった。36 イエスは、この事をだれにも言ってはならぬと、人々に口止めをされたが、口止めをすればするほど、かえって、ますます言いひろめた。37 彼らは、ひとかたならず驚いて言った、「このかたのなさった事は、何もかも、すばらしい。耳の聞えない者を聞えるようにしてやり、口のきけない者をきけるようにしておやりになった」。

### マタイ 15:29-31（参照）

> 29 イエスはそこを去って、ガリラヤの海べに行き、それから山に登ってそこにすわられた。30 すると大ぜいの群衆が、足、手、目や口などが不自由な人々、そのほか多くの人々を連れてきて、イエスの足もとに置いたので、彼らをおいやしになった。31 群衆は、口のきけなかった人が物を言い、手や足が不自由だった人がいやされ、盲人が見えるようになったのを見て驚き、そしてイスラエルの神をほめたたえた。

[マルコによる福音書7章31-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark7_31-37.pdf)

### 問い

1.  イエスの移動経路を確認しましょう。どのような背景が考えられますか。（31）

2.  人々は、どんなひとを連れてきますか。何を願っていますか。（32）

3.  イエスはどうしますか。そしてどうなりますか。（33-35）

4.  イエスは、誰に対して、口止めをしていますか。それはなぜでしょうか。（36）

5.  人々の反応から、どのようなことがわかりますか。（37）

6.  あなたは、この箇所から、どんなことを感じ、学びましたか。

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   デカポリス：直接ローマ帝国スリヤ総督配下に属し、独自の貨幣を作っている十の異邦人都市地帯。（バークレイ）

-   手を置く：マルコ7:32 「すると人々は、耳が聞えず口のきけない人を、みもとに連れてきて、手を置いてやっていただきたいとお願いした。」以外

    -   ルカ4:40 日が暮れると、いろいろな病気になやむ者をかかえている人々が、皆それをイエスのところに連れてきたので、そのひとりびとりに手を置いて、おいやしに（θεραπεύω: i) to serve, do service, ii) to heal, cure, restore to health）なった。

    -   ルカ14:4 （安息日に水腫を患っている人を癒やす）彼らは黙っていた。そこでイエスはその人に手を置いていやし（ἰάομαι: i) to cure, heal, ii) to make whole）てやり、そしてお帰しになった。マルコでは、ἰάομαι は、5:29 一箇所のみ。

-   つばきでのいやし：7章33節以外

    -   マルコ8:23 イエスはこの盲人の手をとって、村の外に連れ出し、その両方の目につばきをつけ、両手を彼に当てて、「何か見えるか」と尋ねられた。

    -   ヨハネ9:6 イエスはそう言って、地につばきをし、そのつばきで、どろをつくり、そのどろを盲人の目に塗って言われた、

-   スキナゾー στενάζω: a sigh, to groan

    -   7:34 天を仰いで**ため息をつき**、その人に「エパタ」と言われた。これは「開けよ」という意味である。

    -   ローマ8:23 それだけではなく、御霊の最初の実を持っているわたしたち自身も、心の内で**うめきながら**、子たる身分を授けられること、すなわち、からだのあがなわれることを待ち望んでいる。

    -   2コリント5:2-4 そして、天から賜わるそのすみかを、上に着ようと切に望みながら、この幕屋の中で**苦しみもだえ**ている。それを着たなら、裸のままではいないことになろう。この幕屋の中にいるわたしたちは、重荷を負って**苦しみもだえ**ている。それを脱ごうと願うからではなく、その上に着ようと願うからであり、それによって、死ぬべきものがいのちにのまれてしまうためである。

    -   ヘブル13:17 あなたがたの指導者たちの言うことを聞きいれて、従いなさい。彼らは、神に言いひらきをすべき者として、あなたがたのたましいのために、目をさましている。彼らが**嘆かない**で、喜んでこのことをするようにしなさい。そうでないと、あなたがたの益にならない。

    -   ヤコブ5:9 兄弟たちよ。互に**不平を言い合**ってはならない。さばきを受けるかも知れないから。見よ、さばき主が、すでに戸口に立っておられる。

-   エパタ：アラム語の使用：\[[参照](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-新約聖書におけるアラム語の使用)\]

-   預言

    -   イザヤ29:18 その日、耳しいは書物の言葉を聞き、／目しいの目はその暗やみから、見ることができる。

    -   イザヤ35:6 その時、足の不自由な人は、しかのように飛び走り、／口のきけない人の舌は喜び歌う。それは荒野に水がわきいで、／さばくに川が流れるからである。

### 記録

-   日時：2024年1月25日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）5名

### 問いについて

1.  イエスの移動経路を確認しましょう。どのような背景が考えられますか。（31）

    -   31 それから、イエスはまたツロの地方を去り、シドンを経てデカポリス地方を通りぬけ、ガリラヤの海べにこられた。

    -   おそらく、ある程度の期間も要する旅だったろう。しばらく、ガリラヤにはいない。なにをした期間なのだろうか。

2.  人々は、どんなひとを連れてきますか。何を願っていますか。（32）

    -   32 すると人々は、耳が聞えず口のきけない人を、みもとに連れてきて、手を置いてやっていただきたいとお願いした。

    -   別訳「耳が聞こえないので、話すのに口ごもった」（ティンデル）

        -   原理的には、これが正しいだろう。

3.  イエスはどうしますか。そしてどうなりますか。（33-35）

    -   33 そこで、イエスは彼ひとりを群衆の中から連れ出し、その両耳に指をさし入れ、それから、つばきでその舌を潤し、34 天を仰いでため息をつき、その人に「エパタ」と言われた。これは「開けよ」という意味である。35 すると彼の耳が開け、その舌のもつれもすぐ解けて、はっきりと話すようになった。

    -   \[DQ\] なぜ、イエスは「彼ひとりを群衆の中から連れ出し」たのでしょうか。

        -   見世物ではない。聾者は、差別されていただろうか。舌がもつれているということは、長期間、聾者であったと思われる。

    -   \[DQ\] なぜ、イエスは「その両耳に指をさし入れ、それから、つばきでその舌を潤し」などという行為をしたのでしょうか。

        -   つばきは、通常の医療行為と思われる。天をあおぎ、神の国が近いことを求めたのだろうか。

    -   \[DQ\] なぜ、イエスは「天を仰いでため息をつき」言われたのでしょうか。

        -   神の国、神の支配が見られないことへの嘆きであろうか。

        -   ため息をつき：στενάζω: a sigh, to groan

    -   \[DQ\] なぜ、イエスは「エパタ」と言われたのでしょうか。

        -   弟子たちの耳には、鮮明に残っているということだろう。

4.  イエスは、誰に対して、口止めをしていますか。それはなぜでしょうか。（36）

    -   36 イエスは、この事をだれにも言ってはならぬと、人々に口止めをされたが、口止めをすればするほど、かえって、ますます言いひろめた。

    -   このひとだけではなく、人々に語っている。ニュースが広がることを願っていない。

5.  人々の反応から、どのようなことがわかりますか。（37）

    -   37 彼らは、ひとかたならず驚いて言った、「このかたのなさった事は、何もかも、すばらしい。耳の聞えない者を聞えるようにしてやり、口のきけない者をきけるようにしておやりになった」。

        -   創世記1:31 神が造ったすべての物を見られたところ、それは、はなはだ良かった。夕となり、また朝となった。第六日である。

        -   イエスの反応は書かれていない。反発が強くなり、排除されることを、恐れただけとは考えにくい。

    -   \[DQ\] マタイによる福音書の記述からは、どんなことがわかりますか。

        -   31 群衆は、口のきけなかった人が物を言い、手や足が不自由だった人がいやされ、盲人が見えるようになったのを見て驚き、そしてイスラエルの神をほめたたえた。

        -   いろいろな病人などがいて、それぞれいやされ、それが、「イスラエルの神」への賛美につながっている。

6.  あなたは、この箇所から、どんなことを感じ、学びましたか。

### メモ

-   イエスの医療行為は、見せるためでも、魔術的な力の発揮でもない。通常のことをしているようにも見える。

-   「耳が聞えず口のきけない人」を連れてきたのは、人々であって、本人が願ったのではない。一般に、人は、障害などを取り除くことを優先して考え、それによって、問題が解決すると考える。目に見えるものによる判断が大きく優先されるということだろう。しかし、障害をもった本人、大きな課題をかかけたひとにとっては、その障害や課題を取り除くことで、幸せになるわけではないことは、理解できているだろう。それは、その人の一部になっているからだ。ここでも、この障害を負ったひとのことばは、ひとことも伝えられていない。障害が取り除けられることは、様々な課題と向き合うひとつのステップではあるかもしれないが、それをもって、問題の解決と考えるひとを前にすると、気後れがすることでもある。イエスのため息のなかには、それも含まれているのかもしれない。ひとりひとりの心の重荷を、イエスは受け取ろうとし、イエス様によって示される神さまも、同様だろう。その神さまにとって、イエス様にとって、この事件は、どのようなものだったのだろう。

-   「このかたのなさった事は、何もかも、すばらしい。耳の聞えない者を聞えるようにしてやり、口のきけない者をきけるようにしておやりになった」。は、おそらく、キリスト教会にたいせつなメッセージとして伝えられただろう。そして、受け取った人の中には、これこそ、イザヤ書29章18節や、35章6節の成就だと考えた人もいるだろう。さらには、ペトロなど、一緒に旅をして回ったと思われる、弟子たちにとっては、このような積み重ねが、イエスは、神の子、キリストだと確信することにつながっているのだろう。我々は、そこからスタートして、マルコを呼んではいけない。弟子たちとともに、そのように、確信する、歩みをしなければならない。同時に、ここでの表現が、イエスが望んでいた証であったかどうかも明らかではないことも、心すべきである。イエスと、パリサイ人や、律法学者、そして、ヘロデなどの政治的支配者に理解されていなかったことは、一般的に受け入れられている。しかし、群衆とのやり取りをみていると、イエスは、群衆に理解されていないこと、大きなズレがあることは、確信していたと思われる。ヨハネ2:23-25「過越の祭の間、イエスがエルサレムに滞在しておられたとき、多くの人々は、その行われたしるしを見て、イエスの名を信じた。しかしイエスご自身は、彼らに自分をお任せにならなかった。それは、すべての人を知っておられ、また人についてあかしする者を、必要とされなかったからである。それは、ご自身人の心の中にあることを知っておられたからである。」によらずとも、マルコを読んでいるとたびたび示されること、そして、それが、このことを語らないようにいった大きな原因ではないかとも思わされる。そして、弟子たちの理解も遅い。他の人に比べると、イエスについて、まんでいったことを多いと思うが、人によっても異なるだろうし、その理解の形も様々だったろう。わたしたちは、マルコを通して、ペトロの理解の歩みを辿っている。ピリポカイザリアでの告白も、そこでのエピソードが伝えているように、十分な理解から、発せられているわけではない。ともに、イエスを、そして、神さまをすこしでも理解する歩みを続けたいものである。

## 8:1-10 四千人に食べ物を与える

> 1 そのころ、また大ぜいの群衆が集まっていたが、何も食べるものがなかったので、イエスは弟子たちを呼び寄せて言われた、2 「この群衆がかわいそうである。もう三日間もわたしと一緒にいるのに、何も食べるものがない。3 もし、彼らを空腹のまま家に帰らせるなら、途中で弱り切ってしまうであろう。それに、なかには遠くからきている者もある」。4 弟子たちは答えた、「こんな荒野で、どこからパンを手に入れて、これらの人々にじゅうぶん食べさせることができましょうか」。5 イエスが弟子たちに、「パンはいくつあるか」と尋ねられると、「七つあります」と答えた。6 そこでイエスは群衆に地にすわるように命じられた。そして七つのパンを取り、感謝してこれをさき、人々に配るように弟子たちに渡されると、弟子たちはそれを群衆に配った。7 また小さい魚が少しばかりあったので、祝福して、それをも人々に配るようにと言われた。8 彼らは食べて満腹した。そして残ったパンくずを集めると、七かごになった。9 人々の数はおよそ四千人であった。それからイエスは彼らを解散させ、10 すぐ弟子たちと共に舟に乗って、ダルマヌタの地方へ行かれた。

### マタイ 15:32-39

> 32 イエスは弟子たちを呼び寄せて言われた、「この群衆がかわいそうである。もう三日間もわたしと一緒にいるのに、何も食べるものがない。しかし、彼らを空腹のままで帰らせたくはない。恐らく途中で弱り切ってしまうであろう」。33 弟子たちは言った、「荒野の中で、こんなに大ぜいの群衆にじゅうぶん食べさせるほどたくさんのパンを、どこで手に入れましょうか」。34 イエスは弟子たちに「パンはいくつあるか」と尋ねられると、「七つあります。また小さい魚が少しあります」と答えた。35 そこでイエスは群衆に、地にすわるようにと命じ、36 七つのパンと魚とを取り、感謝してこれをさき、弟子たちにわたされ、弟子たちはこれを群衆にわけた。37 一同の者は食べて満腹した。そして残ったパンくずを集めると、七つのかごにいっぱいになった。38 食べた者は、女と子供とを除いて四千人であった。39 そこでイエスは群衆を解散させ、舟に乗ってマガダンの地方へ行かれた。

[マルコによる福音書8章1-10節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_1-10.pdf)

### 問い

1.  イエスたちと、群衆について、どのようなことがわかりますか。（1a）

2.  イエスの弟子たちへのことばからどのようなことがわかりますか。(1b-3)

3.  弟子たちと、イエスは、どのような会話をしますか。（4,5）

4.  イエスは、どうしますか。（6,7）

5.  どうなりますか。(8-10)

6.  以前の五千人の給食の記事と比較し、気づいたことをあげてみましょう。（6:30-44）

7.  実際には、なにがおこったのだと思いますか。

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   新約聖書の「ダルマヌタ（Dalmanutha, mark 8:10）」はどこだと考えられているのでしょうか。

    -   Google Bard: 新約聖書の「ダルマヌタ」は、マルコの福音書8章10節に登場する地名です。この節によると、イエスはガリラヤ湖畔の「ダルマヌタ」で弟子たちに、パリサイ人やヘロデ党員のパン種に注意するようにと教えました。

        ダルマヌタの地名は、他の聖書の書物には登場せず、マルコの福音書のこの一節にしか記されていません。そのため、ダルマヌタの具体的な位置は、古くから聖書学者や考古学者によってさまざまな説が唱えられてきました。

        主な説としては、以下のようなものが挙げられます。

        -   ガリラヤ湖北岸の「タブハ」であるとする説

        -   ガリラヤ湖南岸の「デカポリスの一都市」であるとする説

        -   ガリラヤ湖南岸の「ガザリヤ」であるとする説

        -   ガリラヤ湖北岸の「カイファリア」であるとする説

        これらの説の中で、最も有力と考えられているのが、ガリラヤ湖北岸の「タブハ」であるとする説です。タブハは、ガリラヤ湖畔の町で、イエスの奇跡である「パンと魚の増加」の伝承が残る場所です。また、タブハの近くには、「ペテロの召命」の伝承が残る「ペテロの召命教会」があります。これらのことから、ダルマヌタはタブハであると考えられています。

        なお、近年の考古学的調査では、タブハの近くに「ダルマヌタの丘」と呼ばれる丘があることが明らかになっています。この丘には、古代ローマ時代の集落の跡があり、ダルマヌタの町がここにあった可能性も指摘されています。

-   マルコ8:7 の小さな魚（ἰχθύδιον）と、マルコ6:41 などの 魚（ἰχθύς）とはどのように違うのですか。

    -   Google Bard: マルコの福音書8章7節と6章41節に登場する「魚」は、ギリシャ語でそれぞれ「ἰχθύδιον（イクトュディオン）」と「ἰχθύς（イクトュス）」と書かれています。これらの言葉は、どちらも「魚」を意味しますが、具体的な大きさや種類には若干の違いがあります。

        「ἰχθύδιον（イクトュディオン）」は、一般的に「小さな魚」を意味する言葉です。特に、食用として捕獲される魚よりも小さな魚を指すことが多いです。

        一方、「ἰχθύς（イクトュス）」は、一般的に「魚」を意味する言葉です。大きさや種類にかかわらず、魚全般を指すことができます。

        マルコの福音書8章7節では、イエスが弟子たちに、パンの残りを集めて、小さな魚と共に食べるように命じています。この小さな魚は、食用として捕獲される魚よりも小さな魚であると考えられます。これは、パンの残りが比較的多く、さまざまな種類の食べ物が含まれていたためと考えられます。

        一方、マルコの福音書6章41節では、イエスが弟子たちに、5000人の人々に食事をふるまうために、魚を用意するように命じています。この魚は、一般的に「魚」を指す「ἰχθύς（イクトュス）」であると考えられます。これは、魚が大量に必要だったためと考えられます。

        なお、両者の違いについては、文献学的、考古学的な研究に基づいて、さまざまな説が唱えられていますが、一般的には、上記のような解釈がされています。

-   かご（σπυρίς）5000人のときのかごは（κόφινος）

-   マルコ8:8 のかご（σπυρίς）と、マルコ6:44 のかごは（κόφινος）はどのような違いがあるのですか。

    -   Google Bard: マルコの福音書8章8節と6章44節に登場する「かご」は、ギリシャ語でそれぞれ「σπυρίς（スプュリス）」と「κόφινος（コフィノス）」と書かれています。これらの言葉は、どちらも「バスケット」や「かご」を意味しますが、具体的な形状や用途には若干の違いがあります。

        「σπυρίς（スプュリス）」は、一般的に「バスケット」や「かご」を意味する言葉です。特に、果物や野菜、魚介類などを運ぶために使われていました。また、葬儀の際に遺体を運ぶために使われることもありました。

        一方、「κόφινος（コフィノス）」は、より具体的に「魚かご」を意味する言葉です。底が網で編まれているため、魚を捕獲したり、運んだりするのに適していました。また、乾燥させた果実や穀物を保管するために使われることもありました。

        マルコの福音書8章8節では、イエスが弟子たちに、パンの残りを集めて、かごに入れるように命じています。このかごは、一般的に「バスケット」や「かご」を意味する「σπυρίς（スプュリス）」であると考えられています。これは、パンの残りが比較的多く、さまざまな種類の食べ物が含まれていたためと考えられます。

        一方、マルコの福音書6章44節では、イエスが弟子たちに、5000人の人々に食事をふるまうために、パンと魚を準備するように命じています。このかごは、より具体的に「魚かご」を意味する「κόφινος（コフィノス）」であると考えられています。これは、魚が大量に必要だったためと考えられます。

        なお、両者の違いについては、文献学的、考古学的な研究に基づいて、さまざまな説が唱えられています。

    -   Poe Assistant: マルコによる福音書8章8節と6章44節に登場する「かご」には、ギリシャ語で異なる単語が使用されています。これらの単語にはいくつかの違いがあります。

        1.  マルコ8:8の「かご」（σπυρίς, spyris）: これは小さなかごやかご状の容器を指します。この場面では、イエス・キリストが多くの人々にパンを配るために使われたかごを指しています。このかごは、イエスが5つのパンと2つの魚を祝福し、それを使って多くの人々を満足させた奇跡的な出来事を記述しています。

        2.  マルコ6:44の「かご」（κόφινος, kophinos）: これはより大きなかごやかご状の容器を指します。この場面では、イエスが5つのパンと2つの魚を祝福して多くの人々を満足させた後、残ったパンと魚を集めるために使われたかごを指しています。このかごは、集められた残りの食べ物を入れるために使用されたものです。

        したがって、マルコ8:8の「かご」（σπυρίς）は配布に使用される小さなかごであり、マルコ6:44の「かご」（κόφινος）は残りの食べ物を集めるために使用される大きなかごです。

-   マタイ4:1-4 さて、イエスは御霊によって荒野に導かれた。悪魔に試みられるためである。2 そして、四十日四十夜、断食をし、そののち空腹になられた。3 すると試みる者がきて言った、「もしあなたが神の子であるなら、これらの石がパンになるように命じてごらんなさい」。4 イエスは答えて言われた、「『人はパンだけで生きるものではなく、神の口から出る一つ一つの言で生きるものである』と書いてある」。

-   マルコ8:14-21 で再登場。

### 記録

-   日時：2024年2月1日午後7時半〜9時半

-   出席（対面）6名、参加（遠隔）4名

### 問いについて

1.  イエスたちと、群衆について、どのようなことがわかりますか。（1a）

    -   1 そのころ、また大ぜいの群衆が集まっていたが、何も食べるものがなかったので、イエスは弟子たちを呼び寄せて言われた、

    -   どこにいるのか不明。デカポリスのガリラヤ湖畔？ このあと船で移動しているので、ガリラヤ湖畔。かつ、カペナウムなどではない。ダルマヌタの場所が不明であることからも、特定は難しいが、おそらく、前段の話の続きと思われる。

2.  イエスの弟子たちへのことばからどのようなことがわかりますか。(1b-3)

    -   1 そのころ、また大ぜいの群衆が集まっていたが、何も食べるものがなかったので、イエスは弟子たちを呼び寄せて言われた、2 「この群衆がかわいそうである。もう三日間もわたしと一緒にいるのに、何も食べるものがない。3 もし、彼らを空腹のまま家に帰らせるなら、途中で弱り切ってしまうであろう。それに、なかには遠くからきている者もある」。

    -   ここでも、深く憐れんで（かわいそうである：σπλαγχνίζομαι）マルコ6:34

    -   \[DQ\] イエスはどのように弟子たちに語っていますか。これから、群衆の状況について、そして、イエスの関心事について何がわかりますか。

    -   \[DQ\] イエスは、何を考えて、このように語っているのでしょうか。

    -   イエスの、群衆に対する、思いやりが際立っている。

3.  弟子たちと、イエスは、どのような会話をしますか。（4,5）

    -   4 弟子たちは答えた、「こんな荒野で、どこからパンを手に入れて、これらの人々にじゅうぶん食べさせることができましょうか」。5 イエスが弟子たちに、「パンはいくつあるか」と尋ねられると、「七つあります」と答えた。

    -   \[DQ\] 弟子たちは、どのように状況を判断していますか。

    -   \[DQ\] イエスのことばから何がわかりますか。

4.  イエスは、どうしますか。（6,7）

    -   6 そこでイエスは群衆に地にすわるように命じられた。そして七つのパンを取り、感謝してこれをさき、人々に配るように弟子たちに渡されると、弟子たちはそれを群衆に配った。7 また小さい魚が少しばかりあったので、祝福して、それをも人々に配るようにと言われた。

    -   \[DQ\] イエスの行動からは、どのようなことがわかりますか。

    -   イエスは、何がおこるかを理解していたかはわからないが、神さまに信頼しているように見える。

5.  どうなりますか。(8-10)

    -   8 彼らは食べて満腹した。そして残ったパンくずを集めると、七かごになった。9 人々の数はおよそ四千人であった。それからイエスは彼らを解散させ、10 すぐ弟子たちと共に舟に乗って、ダルマヌタの地方へ行かれた。

    -   満腹。パンくず、七カゴ。

6.  以前の五千人の給食の記事と比較し、気づいたことをあげてみましょう。（6:30-44）

    -   おきた場所：おそらくベツサイダの近くと、デカポリスのあたり、ユダヤ人が多い地域と、異邦人が多い地域

    -   背景：弟子たちも疲れており、群衆は、「飼う者のない羊のようなその有様を深くあわれんで」(6:34)、ここでも、「この群衆がかわいそうである。」どちらも、σπλαγχνίζομαι: to be moved as to one's bowels, hence to be moved with compassion, have compassion (for the bowels were thought to be the seat of love and pity)。

    -   弟子たちとの対話：「あなたがたの手で食物をやりなさい」

    -   イエスの指示：39 そこでイエスは、みんなを組々に分けて、青草の上にすわらせるように命じられた。40 人々は、あるいは百人ずつ、あるいは五十人ずつ、列をつくってすわった。ここでは、「35 そこでイエスは群衆に、地にすわるようにと命じ、」

    -   配布：41 それから、イエスは五つのパンと二ひきの魚とを手に取り、天を仰いでそれを祝福し、パンをさき、弟子たちにわたして配らせ、また、二ひきの魚もみんなにお分けになった。ここでは、「そして七つのパンを取り、感謝してこれをさき、人々に配るように弟子たちに渡されると、弟子たちはそれを群衆に配った。7 また小さい魚（ἰχθύδιον: a little fish）が少しばかりあったので、祝福して、それをも人々に配るようにと言われた。」

    -   結果：42 みんなの者は食べて満腹した。43 そこで、パンくずや魚の残りを集めると、十二のかごにいっぱいになった。44 パンを食べた者は男五千人であった。ここでは、「8 彼らは食べて満腹した。そして残ったパンくずを集めると、七かごになった。9 人々の数はおよそ四千人であった。それからイエスは彼らを解散させ、」

7.  実際には、なにがおこったのだと思いますか。

    -   石がパンになったというようなことは書かれていない。（マタイ4:1-4）

    -   実際に、何が起こったか、イエスの手の中で、パンが増えたのか、配っている間に変化が起こったのか、人々の間で、何かが起きたのかは書かれていない。

### メモ

-   五千人養いのときとの対比が興味深い。共通なのは、深く憐れんだこと。自助に頼らなかったこと。石をパンに変えることもおそらくなかった。

-   表現が少しずつことなり、明らかな違いがあり、それがこのあとの、マルコ8:14-21 にもつながっている。

-   イエスは、そして、神さまも、深く憐れまれた。そして、それを、弟子たちと協働して、取り組まれた。そして、皆、満腹して、このまま帰らすことはできないと考えられた状態から、人々を安心して、解散させられる状態になったことは、確かめられる。また、残りのパンくずからも、これが、精神的な満足で満たされたのとは、異なるだろうことが推測される。まさに、神の国は来たことが、共有されたのだろう。ここには、現場にいた人が、4000人、また、前には、5000人は、いたことになる。その証言は、残されていない。また、この人たちが、これらの奇跡によって、イエスについてきたとは書かれていない。それも、不思議なことではある。

## 8:11-13 人々はしるしを欲しがる

> 11 パリサイ人たちが出てきて、イエスを試みようとして議論をしかけ、天からのしるしを求めた。12 イエスは、心の中で深く嘆息して言われた、「なぜ、今の時代はしるしを求めるのだろう。よく言い聞かせておくが、しるしは今の時代には決して与えられない」。13 そして、イエスは彼らをあとに残し、また舟に乗って向こう岸へ行かれた。

### マタイ 16:1-4

> 1 パリサイ人とサドカイ人とが近寄ってきて、イエスを試み、天からのしるしを見せてもらいたいと言った。2 イエスは彼らに言われた、「あなたがたは夕方になると、『空がまっかだから、晴だ』と言い、3 また明け方には『空が曇ってまっかだから、きょうは荒れだ』と言う。あなたがたは空の模様を見分けることを知りながら、時のしるしを見分けることができないのか。4 邪悪で不義な時代は、しるしを求める。しかし、ヨナのしるしのほかには、なんのしるしも与えられないであろう」。そして、イエスは彼らをあとに残して立ち去られた。

[マルコによる福音書8章11-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_11-13.pdf)

### （参照）マタイ 12:38-42

> 38 そのとき、律法学者、パリサイ人のうちのある人々がイエスにむかって言った、「先生、わたしたちはあなたから、しるしを見せていただきとうございます」。39 すると、彼らに答えて言われた、「邪悪で不義な時代は、しるしを求める。しかし、預言者ヨナのしるしのほかには、なんのしるしも与えられないであろう。40 すなわち、ヨナが三日三晩、大魚の腹の中にいたように、人の子も三日三晩、地の中にいるであろう。41 ニネベの人々が、今の時代の人々と共にさばきの場に立って、彼らを罪に定めるであろう。なぜなら、ニネベの人々はヨナの宣教によって悔い改めたからである。しかし見よ、ヨナにまさる者がここにいる。42 南の女王が、今の時代の人々と共にさばきの場に立って、彼らを罪に定めるであろう。なぜなら、彼女はソロモンの知恵を聞くために地の果から、はるばるきたからである。しかし見よ、ソロモンにまさる者がここにいる。

### （参照）ルカ 11:29-32

> 29 さて群衆が群がり集まったので、イエスは語り出された、「この時代は邪悪な時代である。それはしるしを求めるが、ヨナのしるしのほかには、なんのしるしも与えられないであろう。30 というのは、ニネベの人々に対してヨナがしるしとなったように、人の子もこの時代に対してしるしとなるであろう。31 南の女王が、今の時代の人々と共にさばきの場に立って、彼らを罪に定めるであろう。なぜなら、彼女はソロモンの知恵を聞くために、地の果からはるばるきたからである。しかし見よ、ソロモンにまさる者がここにいる。32 ニネベの人々が、今の時代の人々と共にさばきの場に立って、彼らを罪に定めるであろう。なぜなら、ニネベの人々はヨナの宣教によって悔い改めたからである。しかし見よ、ヨナにまさる者がここにいる。

### 問い

1.  パリサイ人たちがイエスに議論をしかけた目的は何ですか。（11）

2.  パリサイ人が求める「天からのしるし」とはどのようなものなのでしょうか。（11b）

3.  イエスの応答からは、どのようなことが読み取れますか。（12）

4.  イエスは「しるし」についてどう考えていたのでしょうか。

5.  イエスはどうしますか。（13）

6.  マタイ16:1-4 や、その他の関連箇所（マタイ12:38-42, ルカ11:29-32）からは「しるし」について、どのようなことがわかりますか。

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   マルコでの「しるし」についての二回目：マルコ13章、マタイ24章、ルカ21章

    -   13:1 イエスが宮から出て行かれるとき、弟子のひとりが言った、「先生、ごらんなさい。なんという見事な石、なんという立派な建物でしょう」。2 イエスは言われた、「あなたは、これらの大きな建物をながめているのか。その石一つでもくずされないままで、他の石の上に残ることもなくなるであろう」。3 またオリブ山で、宮にむかってすわっておられると、ペテロ、ヤコブ、ヨハネ、アンデレが、ひそかにお尋ねした。4 「わたしたちにお話しください。いつ、そんなことが起るのでしょうか。またそんなことがことごとく成就するような場合には、どんな前兆がありますか」。5 そこで、イエスは話しはじめられた、「人に惑わされないように気をつけなさい。

-   しるし（σημεῖον: a sign, mark, token; a) that by which a person or a thing is distinguished from others and is known, b) a sign, prodigy, portent, i.e. an unusual occurrence, transcending the common course of nature, i) of signs portending remarkable events soon to happen, ii) of miracles and wonders by which God authenticates the men sent by him, or by which men prove that the cause they are pleading is God's）

    -   マルコ8:11, 12 パリサイ人たちが出てきて、イエスを試みようとして議論をしかけ、天からのしるしを求めた。12 イエスは、心の中で深く嘆息して言われた、「なぜ、今の時代はしるしを求めるのだろう。よく言い聞かせておくが、しるしは今の時代には決して与えられない」。

    -   マルコ13:4 「わたしたちにお話しください。いつ、そんなことが起るのでしょうか。またそんなことがことごとく成就するような場合には、どんな前兆がありますか」。

    -   マルコ13:22 にせキリストたちや、にせ預言者たちが起って、しるしと奇跡とを行い、できれば、選民をも惑わそうとするであろう。

    -   マルコ16:17 信じる者には、このようなしるしが伴う。すなわち、彼らはわたしの名で悪霊を追い出し、新しい言葉を語り、

    -   マルコ16:20 弟子たちは出て行って、至る所で福音を宣べ伝えた。主も彼らと共に働き、御言に伴うしるしをもって、その確かなことをお示しになった。〕

    -   ルカ 23:8 ヘロデはイエスを見て非常に喜んだ。それは、かねてイエスのことを聞いていたので、会って見たいと長いあいだ思っていたし、またイエスが何か奇跡を行うのを見たいと望んでいたからである。

    -   マタイ 12:38, 39, 16:1, 3, 4, 24:3, 24, 30

    -   マタイ26:48

    -   ヨハネ 2:11. 18, 23, 3:2, 4:48, 54, 6:2, 14, 26, 30, 7:31, 9:16, 10:41, 47, 12:18, 37, 20:30

-   サドカイ派：名前の由来は不明。ギリシャ語（スンディコイ（財務管理人））のユダヤ化したものか。議会議員の意味。ユダヤの貴族の間に多く、特に宗教上の最高権威者である大祭司はサイドカイ派で、最高議会サンヘドリンの議員の多くもこの派に属していた。パリサイ派のように多くの伝承や規則を認めず、聖書だけを信じ、それも、合理的に解釈して、時のギリシャ・ローマ文化の流れに妥協していた。霊の実在も死人の復活も信じず、髪の聖定や摂理より、人間の自由意志と自由行動を重視。（榊原「マタイによる福音書 中巻」）

    -   使徒23：6-8 パウロは、議員の一部がサドカイ人であり、一部はパリサイ人であるのを見て、議会の中で声を高めて言った、「兄弟たちよ、わたしはパリサイ人であり、パリサイ人の子である。わたしは、死人の復活の望みをいだいていることで、裁判を受けているのである」。7 彼がこう言ったところ、パリサイ人とサドカイ人との間に争論が生じ、会衆は相分れた。8 元来、サドカイ人は、復活とか天使とか霊とかは、いっさい存在しないと言い、パリサイ人は、それらは、みな存在すると主張している。

-   Zoom Earth \[[リンク](https://zoom.earth/maps/satellite/#view=31.417,36.34,6z)\]

### 記録

-   日時：2024年2月8日午後7時半〜9時半

-   出席（対面）8名、参加（遠隔）2名

### 問いについて

1.  パリサイ人たちがイエスに議論をしかけた目的は何ですか。（11）

    -   11 パリサイ人たちが出てきて、イエスを試みようとして議論をしかけ、天からのしるしを求めた。

    -   「出てきて」は、ここにも現れてということであろうか。イエスは、反対者から、距離をおくことはできなかったということか。

    -   「試み」「議論」「しるし」いずれも、イエスの活動には、反するものだったのだろう。

    -   「試み」からは、イエスの弱点を探ろうとする印象を受け、「議論」からは、自分たちの正当性を主張する雰囲気を感じる。「しるし」は、最初の「試み」とは異なるのか。なにの、しるしだろうか。

2.  パリサイ人が求める「天からのしるし」とはどのようなものなのでしょうか。（11b）

    -   11b 天からのしるしを求めた。

    -   「何の」しるしなのか。権威？ 神の子であること、メシヤであることの天からのしるしだろうか。

    -   出エジプトにまつわるような、紅海が分かれたり、ヨルダン川が分かれたり、パン（マナ）のようなものが降ってきたりだろうか。それとも、エリヤや、エリシャのような預言者と同じようなことをするイエスだろうか。

    -   しるし。神の国到来、メシヤ到来（外国（ローマ）の支配からの解放）、非常に驚くべき破壊的なことが起こる

        -   ヨルダン川を二つにわけ、一言で城壁を崩壊（自然の法則を無視した、人々を驚かす破壊的な出来事）神の国の到来の無分別

3.  イエスの応答からは、どのようなことが読み取れますか。（12）

    -   12 イエスは、心の中で深く嘆息して言われた、「なぜ、今の時代はしるしを求めるのだろう。よく言い聞かせておくが、しるしは今の時代には決して与えられない」。

    -   しるしはいらない。信じるからだろうか。

    -   \[DQ\]「今の時代」と二回いっているが、これは何を意味しているのだろうか。

    -   ファリサイ人の態度を批判しているのではなく、「今の時代」といっている。

4.  イエスは「しるし」についてどう考えていたのでしょうか。

    -   与えられない。

    -   与えられないのでしょうか、与えられてもそれを天からのものと見分けられないのでしょうか。

    -   イエスが伝えている、神の国の到来はどのようなものか、神の息吹でみちている。神を見出すために教会に行くのではなく、あらゆるところに神を見出す

5.  イエスはどうしますか。（13）

    -   13 そして、イエスは彼らをあとに残し、また舟に乗って向こう岸へ行かれた。

    -   （参照）マルコ8:10 10 すぐ弟子たちと共に舟に乗って、ダルマヌタの地方へ行かれた。マタイ15:39 そこでイエスは群衆を解散させ、舟に乗ってマガダンの地方へ行かれた。

        -   不明の地にいるが、ユダヤ人が多い地域でのことだったのだろう。マタイのマガダンは、KJV では、マグダラ（Magdala）となっており、マグダラとすると、西岸である。カペナウムなどでは、ないが、ユダヤ人が多い地では、パリサイ人もおり、議論をふっかけられる。イエスはそれを好まなかったのだろう。

        -   向こう岸：ダルマヌタ、マガダンは不明だが、そこには、パリサイ人がいる。おそらく、向こう岸は、東岸だろう。そのあと、ベトサイダ、ピリポ・カイザリア。ユダヤ人、パリサイ人を避けている。

    -   イエスを試みるもの、議論をしかけるもの、しるしを求めるもの、それらを退けるのではなく、自分から退散している。とはいっても、ずっと、退散し続けるわけではない。

6.  マタイ16:1-4 や、その他の関連箇所（マタイ12:38-42, ルカ11:29-32）からは「しるし」について、どのようなことがわかりますか。

    -   何らかの「しるし」では、納得できないということか。

    -   同様の質問が、マタイ12:38-42 にも含まれている。

### メモ

-   それなりに、弟子たちに含めても、大変になりつつある時期なのだおる。イエスは基本的にしるしを拒否している。

-   キリスト教でも、しるしは、探し出そうとしていたように思い出される。それが、ヨナのしるしにあらわれ、この世の終わりのしるしに反映されている。しかし、イエスは、この世の終わりについても、気をつけていなさいが、メッセージであるように思われる。70年のエルサレム陥落をうけて、さまざまな議論があったことは、容易に想像がつくが。

-   イエスのしるしをみて、イエスの神の国の到来を知りたい。

-   このあと、イエスは、どうして、また、エルサレムへの歩みを始めるのだろう。

-   科学的観察で天候を見分けることなどを否定はされていない。しかし、当時、わかることは、経験則に多少加わった程度だったのではないだろうか。現代の科学的知見については、イエスはむろん、判断してはいない。しかし、互いに愛し合うことのために、科学的知見をつかうことは、イエスは奨励されるのではないだろうか。

    -   Quotation: Florence Nightingale \[[Link](https://mathshistory.st-andrews.ac.uk/Biographies/Nightingale/quotations/)\], "To understand God's thoughts we must study statistics, for these are the measure of his purpose." \[[Link](https://bibleportal.com/bible-quote/to-understand-god-s-thoughts-we-must-study-statistics-for-these-are-the-measure-of-his-purpose)\]

## 8:14-21 ファリサイ派の人々とヘロデのパン種

> 14 弟子たちはパンを持って来るのを忘れていたので、舟の中にはパン一つしか持ち合わせがなかった。15 そのとき、イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。16 弟子たちは、これを自分たちがパンを持っていないためであろうと、互に論じ合った。17 イエスはそれと知って、彼らに言われた、「なぜ、パンがないからだと論じ合っているのか。まだわからないのか、悟らないのか。あなたがたの心は鈍くなっているのか。18 目があっても見えないのか。耳があっても聞えないのか。また思い出さないのか。19 五つのパンをさいて五千人に分けたとき、拾い集めたパンくずは、幾つのかごになったか」。弟子たちは答えた、「十二かごです」。20 「七つのパンを四千人に分けたときには、パンくずを幾つのかごに拾い集めたか」。「七かごです」と答えた。21 そこでイエスは彼らに言われた、「まだ悟らないのか」。

### マタイ 16:5-12

> 5 弟子たちは向こう岸に行ったが、パンを持って来るのを忘れていた。6 そこでイエスは言われた、「パリサイ人とサドカイ人とのパン種を、よくよく警戒せよ」。7 弟子たちは、これは自分たちがパンを持ってこなかったためであろうと言って、互に論じ合った。8 イエスはそれと知って言われた、「信仰の薄い者たちよ、なぜパンがないからだと互に論じ合っているのか。9 まだわからないのか。覚えていないのか。五つのパンを五千人に分けたとき、幾かご拾ったか。10 また、七つのパンを四千人に分けたとき、幾かご拾ったか。11 わたしが言ったのは、パンについてではないことを、どうして悟らないのか。ただ、パリサイ人とサドカイ人とのパン種を警戒しなさい」。12 そのとき彼らは、イエスが警戒せよと言われたのは、パン種のことではなく、パリサイ人とサドカイ人との教のことであると悟った。

[マルコによる福音書8章14-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_14-21.pdf)

### 問い

1.  どのような状況で、イエスは弟子たち「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われますか。（14,15）

2.  弟子たちは、イエスのことばをどのように受け取りますか。（16）

3.  イエスは、どのように、弟子たちに問いますか。何に気づかせようとしているのでしょうか。（17-20）

4.  マタイ 16:5-12 は、なにを伝えていますか。

5.  弟子たちは、何を悟らなければいけなかったのでしょうか。（21）

6.  最初のイエスの言葉は、どんなことに警戒せよと言っているのでしょうか。（15）

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   パン種（yeast）：\[[リンク](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-パン種)\]

-   パリサイ派とヘロデ党

    -   マルコ3:6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。

-   サドカイ派とパリサイ派

    -   協力：マタイ16:1 1 パリサイ人とサドカイ人とが近寄ってきて、イエスを試み、天からのしるしを見せてもらいたいと言った。

    -   対立：使徒23：6-8 パウロは、議員の一部がサドカイ人であり、一部はパリサイ人であるのを見て、議会の中で声を高めて言った、「兄弟たちよ、わたしはパリサイ人であり、パリサイ人の子である。わたしは、死人の復活の望みをいだいていることで、裁判を受けているのである」。7 彼がこう言ったところ、パリサイ人とサドカイ人との間に争論が生じ、会衆は相分れた。8 元来、サドカイ人は、復活とか天使とか霊とかは、いっさい存在しないと言い、パリサイ人は、それらは、みな存在すると主張している。

    -   サドカイ：名前の由来は不明。ギリシャ語、スンディコイ（財務管理人）のユダヤ化したものと言われる。つまり、議会議員の意味。Σαδώκ（正しいの可能性も）

        -   Σαδδουκαῖος: Sadducees = "the righteous" a. a religious party at the time of Christ among the Jews, who denied that the oral law was a revelation of God to the Israelites, and who deemed the written law alone to be obligatory on the nation, as the divine authority. They denied the following doctrines: i) resurrection of the body, ii) immortality of the soul, iii) existence of spirits and angels, iv) divine predestination, affirmed free will

-   ヘロデとピラト

    -   ルカ23:12 ヘロデとピラトとは以前は互に敵視していたが、この日に親しい仲になった。

    -   ルカ9:9 そこでヘロデが言った、「ヨハネはわたしがすでに首を切ったのだが、こうしてうわさされているこの人は、いったい、だれなのだろう」。そしてイエスに会ってみようと思っていた。

-   異邦人とユダヤ人

    -   使徒14:5 その時、異邦人やユダヤ人が役人たちと一緒になって反対運動を起し、使徒たちをはずかしめ、石で打とうとしたので、

-   イザヤ6:10 あなたはこの民の心を鈍くし、／その耳を聞えにくくし、／その目を閉ざしなさい。これは彼らがその目で見、／その耳で聞き、／その心で悟り、／悔い改めていやされることのないためである」。(マタイ13:15 参照)

-   1コリント2:11-13 いったい、人間の思いは、その内にある人間の霊以外に、だれが知っていようか。それと同じように神の思いも、神の御霊以外には、知るものはない。12 ところが、わたしたちが受けたのは、この世の霊ではなく、神からの霊である。それによって、神から賜わった恵みを悟るためである。13 この賜物について語るにも、わたしたちは人間の知恵が教える言葉を用いないで、御霊の教える言葉を用い、霊によって霊のことを解釈するのである。

-   ルカ12:1 その間に、おびただしい群衆が、互に踏み合うほどに群がってきたが、イエスはまず弟子たちに語りはじめられた、「パリサイ人のパン種、すなわち彼らの偽善に気をつけなさい。

-   1コリント5:6-7 あなたがたが誇っているのは、よろしくない。あなたがたは、少しのパン種が粉のかたまり全体をふくらませることを、知らないのか。6 新しい粉のかたまりになるために、古いパン種を取り除きなさい。あなたがたは、事実パン種のない者なのだから。わたしたちの過越の小羊であるキリストは、すでにほふられたのだ。

### 記録

-   日時：2024年2月15日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）6名

### 問いについて

1.  どのような状況で、イエスは弟子たち「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われますか。（14,15）

    -   14 弟子たちはパンを持って来るのを忘れていたので、舟の中にはパン一つしか持ち合わせがなかった。15 そのとき、イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。

    -   \[DQ\] なぜ、弟子たちは、パンを持ってくるのを忘れたのでしょうか。（背景を復習しましょう）

        -   11 パリサイ人たちが出てきて、イエスを試みようとして議論をしかけ、天からのしるしを求めた。12 イエスは、心の中で深く嘆息して言われた、「なぜ、今の時代はしるしを求めるのだろう。よく言い聞かせておくが、しるしは今の時代には決して与えられない」。13 そして、イエスは彼らをあとに残し、また舟に乗って向こう岸へ行かれた。

        -   ユダヤ人が住んでいる地域に久しぶりに行ったが、落ち着く暇もなく、パリサイ人たちが、イエスを試そうとして、天からのしるしをもとめ、議論をしかけてきたので、あまり重要なことはせずに、立ち去ったように思われる。

    -   \[DQ\] イエスは、どのような気持ちで、訪問した地を離れたのでしょうか。

        -   群衆との時間も持てなかった。イエスの、深く嘆息したなかに、イエスの心情が表れているように見える。

2.  弟子たちは、イエスのことばをどのように受け取りますか。（16）

    -   16 弟子たちは、これを自分たちがパンを持っていないためであろうと、互に論じ合った。

    -   \[DQ\] 「互いに論じあった」はどんなことを意味しているでしょうか。

        -   イエスは、議論をしかけてきた、パリサイ人たちをさけて、その地を去ってきた。ここで、もしかすると、弟子たちは、責任論などを議論していたのかもしれない。

    -   \[DQ\] なぜ、弟子たちは、自分たちがパンを持っていなかったためだと考えたのでしょうか。

        -   イエスの関心事、イエスの心の痛みを理解しようとしていない。

        -   自分の責任・役割にだけ、関心を持っている。

3.  イエスは、どのように、弟子たちに問いますか。何に気づかせようとしているのでしょうか。（17-20）

    -   17 イエスはそれと知って、彼らに言われた、「なぜ、パンがないからだと論じ合っているのか。まだわからないのか、悟らないのか。あなたがたの心は鈍くなっているのか。18 目があっても見えないのか。耳があっても聞えないのか。また思い出さないのか。19 五つのパンをさいて五千人に分けたとき、拾い集めたパンくずは、幾つのかごになったか」。弟子たちは答えた、「十二かごです」。20 「七つのパンを四千人に分けたときには、パンくずを幾つのかごに拾い集めたか」。「七かごです」と答えた。

    -   \[DQ\] イエスは、かなり怒っているように見えますが、なにに怒っているのでしょうか。

    -   \[DQ\] 「五つのパンをさいて五千人に分けたとき、拾い集めたパンくずは、幾つのかごになったか」「七つのパンを四千人に分けたときには、パンくずを幾つのかごに拾い集めたか」は、何に気づかせようとしているのでしょうか。

        -   最初は、理由も示さず、イライラしているように見えるが、あとでは、一緒に経験したところに戻って、気づかせようとしている。

        -   物質的な不足が問題なのではない。それにとらわれてはいけない。

        -   いまも、パンが一つしかない、物質的な欠乏に、こころがとらわれていたら、神様のみこころは理解できない。

    -   \[DQ\] 何を思い出させたいのでしょうか。

        -   ① イエスはスーパースターで何でもできること、② 神様のめぐみに生きれば不足しないこと、③ もっとたいせつなことに目を向けるべきこと。

    -   \[DQ\] イエスは、いくらでも、パンを生み出してくれることを、悟りなさいと言っているのでしょうか。

        -   そうであれば、わたしたちとは、ほとんど、関係のないことのように見える。

4.  マタイ 16:5-12 は、なにを伝えていますか。

    -   マタイでは、6 そこでイエスは言われた、「パリサイ人とサドカイ人とのパン種を、よくよく警戒せよ」。となっている。

        -   「そこで」には順接的な感じを受ける。ὁ δὲ Ἰησοῦς εἶπεν αὐτοῖς Ὁρᾶτε καὶ προσέχετε ἀπὸ τῆς ζύμης τῶνΦαρισαίων καὶ Σαδδουκαίων マルコでは、καὶ διεστέλλετο[^markdq7-2] ὐτοῖς λέγων, Ὁρᾶτε βλέπετε ἀπὸ τῆς ζύμης τῶνΦαρισαίων καὶ　τῆς ζύμης Ἡρῴδου

        -   パリサイ人とサドカイ人となっており、マルコの「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」とは異なる。

    -   \[DQ\] なぜ、マタイは、「パリサイ人とサドカイ人」としたのでしょうか。

        -   おそらく、最後に鍵がある。「12 そのとき彼らは、イエスが警戒せよと言われたのは、パン種のことではなく、パリサイ人とサドカイ人との教のことであると悟った。」「教え」と理解すると、ヘロデは、そぐわない。

    -   \[DQ\] マタイが書いているように、本当に「教え」なのでしょうか。

        -   12 イエスは、心の中で深く嘆息して言われた、「なぜ、今の時代はしるしを求めるのだろう。よく言い聞かせておくが、しるしは今の時代には決して与えられない」。ここに鍵があるように思う。パリサイ人のような、「イエスを試みようとして議論をしかけ、天からのしるしを求め」（11）を非難せず「今の時代」と言っている。

        -   対応箇所のマタイでは「1 パリサイ人とサドカイ人とが近寄ってきて、イエスを試み、天からのしるしを見せてもらいたいと言った。」と、パリサイ人とサドカイ人となっている。

    -   マタイでは「信仰の薄いものよ」と、信仰の問題にしている。ということは、マタイでは、物質的な欠乏は問題ないと言っているようにも取れる。

    -   「11 わたしが言ったのは、パンについてではないことを、どうして悟らないのか。」が、教えを誘導しているようにも見える。マルコには、そのような表現はない。マルコの文章では理解できなかったのだろう。

5.  弟子たちは、何を悟らなければいけなかったのでしょうか。（21）

    -   21 そこでイエスは彼らに言われた、「まだ悟らないのか」。

    -   ① パンの個数や人の人数ではないこと。② イエスはいくらでも、奇跡を起こされる方であること。③ もっとたいせつなものがあること。

    -   \[DQ\] 弟子たちは、悟ることができたのでしょうか。

        -   おそらく、その一つの解釈がマタイにある。

        -   しかし、イエスは、マルコでは「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」。ここには「今の時代」も現れている。

6.  最初のイエスの言葉は、どんなことに警戒せよと言っているのでしょうか。（15）

    -   「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」- 今の時代。

    -   \[DQ\] パリサイ人の問題点は、何だと、イエスは考えていたのでしょうか。ここまでに書かれていたことを振り返って考えてみましょう。

        -   しるしを求める。（マルコ8:11-13）

        -   神の戒めを棄てて、人間の言い伝えを固く守っている。（マルコ7:8）神のみこころを求めようとしない。（マルコ3:35）

        -   聖霊を冒涜するもの。（マルコ3:29）マルコではエルサレムから下ってきた律法学者たちとあるが、マタイではファリサイ派の人々。

        -   安息日に善いことをするのは許されているのにたいして、イエスを殺そうとする。（マルコ3:4,6）

    -   \[DQ\] ヘロデの問題点は何だと、イエスは考えていたのでしょうか。ここまでに書かれていたことを振り返って考えてみましょう。

        -   マルコでは、イエスが宣教をはじめたのは「ヨハネが捕えられた後、イエスはガリラヤに行き、神の福音を宣べ伝えて言われた、『時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ』。」（1:14,15）イエスたちが、カペナウムを離れたのは、ヨハネが殺された頃から。直後に、五千人の給食。ヘロデのことが関わっていることが描写されている。

        -   マルコ6:19,20 そこで、ヘロデヤはヨハネを恨み、彼を殺そうと思っていたが、できないでいた。それはヘロデが、ヨハネは正しくて聖なる人であることを知って、彼を恐れ、彼に保護を加え、またその教を聞いて非常に悩みながらも、なお喜んで聞いていたからである。

        -   イエスの弟子たちと、ヨハネの弟子たちは、緊密な関係にあった。（ヨハネ1:35-42, マタイ9:14）

        -   ヨハネを殺したヘロデについても、十分な情報を持っていただろう。

        -   「教えを喜びながら、王としての力を捨ててまで、悔い改めて信じはしない。」

    -   このときの、イエスや、弟子たちについて、あなたはどのような印象を受けますか。

[^markdq7-2]: διαστέλλω: i) to draw asunder, divide, distinguish, dispose, order, ii) to open one's self i.e. one's mind, to set forth distinctly, iii) to admonish, order, charge

### メモ

-   イエスは、どのような状況だったのだろう。どのように状況を考えていたのだろう。おそらく、久しぶりに戻った、ガリラヤ（ガリラヤ湖西岸）で、深く嘆息するようなできごとがあり、そそくさと、ほとんど何もしないで、舟で立ち去ったその舟の中での出来事である。「今の時代」について嘆き、パリサイ人の失礼な態度をいかっているわけではない。更に、高いレベルでの嘆きがここにある。

-   いろいろと考えた挙げ句、イエスが言った言葉が、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」である。やはり、パリサイ的なもの、ヘロデ的なものに注意せよ。それが、どんどん膨れて、腐らせてしまうと言いたかったのだろう。

-   パンを買ってくること（を忘れた）できなかった、弟子たちが、その悔恨に互いに言い合っている有り様は、パリサイ派の議論とは違うにしても、やはり、イエスを、とてもがっかりさせることだったろう。最初は、明らかに、怒ってしまったイエス。こう怒られても、弟子たちがなにかを理解できるわけではない。そこで、次に、覚えていないのかといい、五千人養いと、四千人養いのときの、最後にパンくずをあつめたかご（五千人のときは大きなかご、四千人のときは小さなかご）の数を問うている。一緒に経験した、神の国の到来を思い出させたのだろう。

-   マルコでは、どうも、弟子たちは、理解できなかったようである。それをすなおに表現している。（マタイではひとつの理解を書いている。そのために、パン種についても、パリサイ派とサドカイ派のパンだねと変化させ、向こう岸で、しるしをもとめるときも、パリサイ派とサドカイ派としている）考えさせる効果がある。

-   神の国についての理解、神の国の到来のひとつの例として、五千人養いと、四千人養いについてしるし、それは、パリサイがもとめるしるしや、ヘロデ的なものともことなることをも同時に伝えているのだろう。十分理解できているわけではないが、単純に理解してわかったきになってはいけないとも思う。

-   この時期の、イエス、次に移っていくイエス。丁寧に見ていきたい。

## 8:22-26 ベトサイダで盲人を癒やす

> 22 そのうちに、彼らはベツサイダに着いた。すると人々が、ひとりの盲人を連れてきて、さわってやっていただきたいとお願いした。23 イエスはこの盲人の手をとって、村の外に連れ出し、その両方の目につばきをつけ、両手を彼に当てて、「何か見えるか」と尋ねられた。24 すると彼は顔を上げて言った、「人が見えます。木のように見えます。歩いているようです」。25 それから、イエスが再び目の上に両手を当てられると、盲人は見つめているうちに、なおってきて、すべてのものがはっきりと見えだした。26 そこでイエスは、「村にはいってはいけない」と言って、彼を家に帰された。

[マルコによる福音書8章22-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_22-26.pdf)

### 問い

1.  イエスと弟子たちは、どこにつきますか。それはどのような場所ですか。どのような経路で移動したのでしょう。（22a）

2.  どのようなひとがイエスのもとに連れてこられますか。（22b）

3.  イエスはどうしますか。（23-25）

4.  なぜイエスは、このひとに、村にはいることを許されなかったのでしょうか。（26）

5.  このときのイエスから、どのようなことがわかりますか。

### 参照

-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>

-   ベツサイダ（Βηθσαϊδά: Bethsaida = "house of fish (hunting: צַיָּד hunter)", i) a small fishing village on the west shore of Lake Gennesaret, home of Andrew, Peter, Philip and John, ii) a village in lower Gaulanitis on the eastern shore of Lake Gennesaret, not far from where the Jordan empties into it）

    -   マルコ6:45 それからすぐ、イエスは自分で群衆を解散させておられる間に、しいて弟子たちを舟に乗り込ませ、向こう岸のベツサイダへ先におやりになった。

        -   ルカ9:10 使徒たちは帰ってきて、自分たちのしたことをすべてイエスに話した。それからイエスは彼らを連れて、ベツサイダという町へひそかに退かれた。

        -   ヨハネ6:1 そののち、イエスはガリラヤの海、すなわち、テベリヤ湖の向こう岸へ渡られた。

    -   マルコ8:22 そのうちに、彼らはベツサイダに着いた。すると人々が、ひとりの盲人を連れてきて、さわってやっていただきたいとお願いした。

    -   マタイ11:21 「わざわいだ、コラジンよ。わざわいだ、ベツサイダよ。おまえたちのうちでなされた力あるわざが、もしツロとシドンでなされたなら、彼らはとうの昔に、荒布をまとい灰をかぶって、悔い改めたであろう。

        -   ルカ10:13 わざわいだ、コラジンよ。わざわいだ、ベツサイダよ。おまえたちの中でなされた力あるわざが、もしツロとシドンでなされたなら、彼らはとうの昔に、荒布をまとい灰の中にすわって、悔い改めたであろう。

    -   ヨハネ1:44,45 ピリポは、アンデレとペテロとの町ベツサイダの人であった。45 このピリポがナタナエルに出会って言った、「わたしたちは、モーセが律法の中にしるしており、預言者たちがしるしていた人、ヨセフの子、ナザレのイエスにいま出会った」。

    -   ヨハネ12:21 彼らはガリラヤのベツサイダ出であるピリポのところにきて、「君よ、イエスにお目にかかりたいのですが」と言って頼んだ。

    -   参照： ヨハネ5:2 エルサレムにある羊の門のそばに、ヘブル語でベテスダ（Βηθεσδά: Bethesda = "house of mercy" or "flowing water", the name of a pool near the sheep-gate at Jerusalem, whose waters had curative powers）と呼ばれる池があった。そこには五つの廊があった。

### 記録

-   日時：2024年2月22日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）6名

### 問いについて

1.  イエスと弟子たちは、どこにつきますか。それはどのような場所ですか。どのような経路で移動したのでしょう。（22a）

    -   22a そのうちに、彼らはベツサイダに着いた。

    -   \[DQ\] ベッサイダとはどのような地ですか。過去にはどのようなことがありましたか。

        -   5000人の給食はここであったのかもしれない。（マルコ6:45からすると、ヨルダン川西岸のガリラヤとも考えられる。しかし、ルカ9:10は明らかに、ベッサイダ、また、ヨハネ6:1 の記述からは、ベッサイダの可能性が強い。西岸でも寂しいところはあるだろうが、記述からは、東岸のベッサイダ周辺の可能性が高い。）

        -   ヨハネ1:44,45 アンデレ、ペテロ、ピリポは、ベッサイダの出身。（ヨハネ12:21 ピリポがベッサイダの出身であること再術）

        -   マタイ11:21、ルカ10:13 「わざわいだ、コラジンよ。わざわいだ、ベツサイダよ。」ベッサイダで力あるわざがなされたことが強調され、ここには、カペナウムはない。

    -   \[DQ\] なぜ、ここにいるのでしょうか。

        -   ユダヤ人がたくさんいる（ファリサイ派の人が多い）地域をさけているように見える。また、このあとは、ピリポ・カイザリアに飛んでいる。舟を係留する地として、人が多いカペナウムではなく、ベッサイダを選んだ可能性もある。

        -   このあと、ピリポ・カイザリア、６日後に、高い山、ガリラヤを通り、カペナウム（議論）、10章では、ユダヤ地方とヨルダン川の向こう、10:32 エルサレムへ上る途上となる。

2.  どのようなひとがイエスのもとに連れてこられますか。（22b）

    -   22b すると人々が、ひとりの盲人を連れてきて、さわってやっていただきたいとお願いした。

    -   \[DQ\] なぜ人々が、この盲人を連れてきたのでしょうか。

        -   目が見えないから、手を引いてきた可能性もある。

        -   人々が、強いてそれをしたのかもしれない。このひとが、無理だと思っている時に。もう、これでいいと思っているときに。

        -   ベッサイダは、イエスが、何度も来ている場所で、かつ小さな村でもある。

3.  イエスはどうしますか。（23-25）

    -   23 イエスはこの盲人の手をとって、村の外に連れ出し、その両方の目につばきをつけ、両手を彼に当てて、「何か見えるか」と尋ねられた。24 すると彼は顔を上げて[^markdq7-3]言った、「人が見えます。木のように見えます。歩いているようです」。25 それから、イエスが再び目の上に両手を当てられると、盲人は見つめているうち[^markdq7-4]に、なおってきて、すべてのものがはっきりと見えだした。

    -   \[DQ\] なぜ、イエスは、この盲人の手をとって、村の外に連れ出したのでしょうか。

    -   \[DQ\] なぜ、一回で、治さなかった、治らなかったのでしょうか。

    -   \[DQ\] なぜ、このように、記録されたのでしょうか。イエスが、さわられると、癒やされたではいけないのでしょうか。

        -   「何か見えるか」と尋ねている。イエスがわからないことがあると考えるのが自然。

        -   「なおってきて」には、イエスが、何回もさわるとそのたびに、良くなったと言うより、回復力、神様の力なあど、あるはたらきがそこにあるような印象をうける。

4.  なぜイエスは、このひとに、村にはいることを許されなかったのでしょうか。（26）

    -   26 そこでイエスは、「村にはいってはいけない」[^markdq7-5]と言って、彼を家に帰された。

    -   旅の途中で、寄っただけで、村の人に知られたくなかった。大げさにしたくなかった。いやしが中心的なしごとだと思われたくなかった。

    -   \[DQ\] 家はどこにあったのでしょうか。

        -   おそらく、村から程遠くない、村の外。

    -   \[DQ\] どうやって帰ってたのでしょうか。

        -   目が見えるようになったから？ おそらく、ちょっと違うことが、そこに働いているのだろう。

5.  このときのイエスから、どのようなことがわかりますか。

    -   Available であることは、変わっていないが、どんどん、癒やす、村人の要求に答える感じではない。

    -   イエスが、何を考えていたかは、あまりよくはわからない。

[^markdq7-3]: 「みえるようになって」との翻訳もある。

[^markdq7-4]: 未完了形：動作の継続。

[^markdq7-5]: 「村でだれにも語らないように」との写本もある。

### メモ

-   マルコ７章31-37節　耳が聞こえず舌の回らない人を癒やす との類似を指摘する人もいる。

-   長い、逃避行の中で、ユダヤ人のいる地域から、舟で移動している。どこかに係留して、ベッサイダに向かった可能性もあるが、おそらく、ペテロや、アンデレ、ピリポの故郷でもある、ベッサイダまで舟で戻ったのだろう。ここから、次は、ピリポ・カイザリアに向かう。ヨルダン川西側は、避けたように見える。

-   この目の見えない人は、人々に連れてこられる。目が見えないからそうされた可能性もあるが、促されて来たのかもしれない。また、今度、読んでいて考えたのは、もしかすると、このとき一回の治療ではないかもしれないとも思った。縮約して書かれているのかもしれないということである。段階的に治ったこと、群衆や人々からは離れてなされたことも書かれているからである。このあとは、山上の変貌もあり、エルサレムに向かい始める。ベッサイダへはこれが最後だったかもしれないことを考えると、ここで、完全に癒やされたことは印象深い。

-   マタイ、ルカに入っていないことの意味を考えるのも、興味深い。単純ではない、いやしの記事は不要だったのかもしれない。流れとして、なぜここにベッサイダの記事が入るのかも、不自然に思えたかもしれない。しかし、イエスらしさが、ペトロの目撃証言として、記されているのが、興味深い。

## 8:27-30 ペトロ、イエスがメシアであると告白する

> 27 さて、イエスは弟子たちとピリポ・カイザリヤの村々へ出かけられたが、その途中で、弟子たちに尋ねて言われた、「人々は、わたしをだれと言っているか」。28 彼らは答えて言った、「バプテスマのヨハネだと、言っています。また、エリヤだと言い、また、預言者のひとりだと言っている者もあります」。29 そこでイエスは彼らに尋ねられた、「それでは、あなたがたはわたしをだれと言うか」。ペテロが答えて言った、「あなたこそキリストです」。30 するとイエスは、自分のことをだれにも言ってはいけないと、彼らを戒められた。

### マタイ 16:13-20

> 13 イエスがピリポ・カイザリヤの地方に行かれたとき、弟子たちに尋ねて言われた、「人々は人の子をだれと言っているか」。14 彼らは言った、「ある人々はバプテスマのヨハネだと言っています。しかし、ほかの人たちは、エリヤだと言い、また、エレミヤあるいは預言者のひとりだ、と言っている者もあります」。15 そこでイエスは彼らに言われた、「それでは、あなたがたはわたしをだれと言うか」。16 シモン・ペテロが答えて言った、「あなたこそ、生ける神の子キリストです」。17 すると、イエスは彼にむかって言われた、「バルヨナ・シモン、あなたはさいわいである。あなたにこの事をあらわしたのは、血肉ではなく、天にいますわたしの父である。18 そこで、わたしもあなたに言う。あなたはペテロである。そして、わたしはこの岩の上にわたしの教会を建てよう。黄泉の力もそれに打ち勝つことはない。19 わたしは、あなたに天国のかぎを授けよう。そして、あなたが地上でつなぐことは、天でもつながれ、あなたが地上で解くことは天でも解かれるであろう」。20 そのとき、イエスは、自分がキリストであることをだれにも言ってはいけないと、弟子たちを戒められた。

### ルカ 9:18-21

> 18 イエスがひとりで祈っておられたとき、弟子たちが近くにいたので、彼らに尋ねて言われた、「群衆はわたしをだれと言っているか」。19 彼らは答えて言った、「バプテスマのヨハネだと、言っています。しかしほかの人たちは、エリヤだと言い、また昔の預言者のひとりが復活したのだと、言っている者もあります」。20 彼らに言われた、「それでは、あなたがたはわたしをだれと言うか」。ペテロが答えて言った、「神のキリストです」。21 イエスは彼らを戒め、この事をだれにも言うなと命じ、そして言われた、

[マルコによる福音書8章27-30節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_27-30.pdf)

### （参考）ヨハネ 6:59-71

> 59 これらのことは、イエスがカペナウムの会堂で教えておられたときに言われたものである。60 弟子たちのうちの多くの者は、これを聞いて言った、「これは、ひどい言葉だ。だれがそんなことを聞いておられようか」。61 しかしイエスは、弟子たちがそのことでつぶやいているのを見破って、彼らに言われた、「このことがあなたがたのつまずきになるのか。62 それでは、もし人の子が前にいた所に上るのを見たら、どうなるのか。63 人を生かすものは霊であって、肉はなんの役にも立たない。わたしがあなたがたに話した言葉は霊であり、また命である。64 しかし、あなたがたの中には信じない者がいる」。イエスは、初めから、だれが信じないか、また、だれが彼を裏切るかを知っておられたのである。65 そしてイエスは言われた、「それだから、父が与えて下さった者でなければ、わたしに来ることはできないと、言ったのである」。66　それ以来、多くの弟子たちは去っていって、もはやイエスと行動を共にしなかった。67 そこでイエスは十二弟子に言われた、「あなたがたも去ろうとするのか」。68 シモン・ペテロが答えた、「主よ、わたしたちは、だれのところに行きましょう。永遠の命の言をもっているのはあなたです。69 わたしたちは、あなたが神の聖者であることを信じ、また知っています」。70 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である」。71 これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。

### 問い

1.  どのようなときに、イエスは、弟子たちに、自分について人々がだれだと言っているかと聞いていますか。（27）

2.  弟子たちは、どのように答えますか。（28）

3.  それに対して、イエスはどのように尋ねますか。（29a）

4.  だれがどのように答えますか。（29b）

5.  イエスは、なぜ、自分のことをだれにも言ってはいけないと、弟子たちを戒めるのでしょうか。（30）

6.  マタイや、ルカからはさらにどのようなことがわかりますか。

7.  弟子たちにとって、イエスは、どのような存在だったのでしょうか。

### 参照

-   ヨハネ6:59-71
-   地図 The ministry of Jesus beyond Galilee: <https://www.seektheoldpaths.com/Maps/109.jpg>
-   ピリポ・カイザリア
    -   ベツサイダから北へ 41km、ガリラヤ湖面から 520m 上。海抜350m
    -   パニアスと呼ばれ、パネアスという山に洞窟があり、パン（森・牧童の神）とニンフ（川、泉、洞穴、林の神）の誕生の地
    -   ヘロデ・ピリポによって建てられた街で、地中海沿岸にある、カイザリアと区別するためにピリポ・カイザリアと呼ばれる。
-   エリヤ
    -   マラキ4:5,6（3:23）見よ、主の大いなる恐るべき日が来る前に、わたしは預言者エリヤをあなたがたにつかわす。6 彼は父の心をその子供たちに向けさせ、子供たちの心をその父に向けさせる。これはわたしが来て、のろいをもってこの国を撃つことのないようにするためである」。
-   キリスト（ギリシャ語）、メシヤ（ヘブル語）：油注がれたもの
    -   旧約聖書では、祭司（出エジプト記29:7, 21）、王（サムエル記上10:1）、預言者（列王記上19:16）などが油を注がれた。特に、ダビデの子孫から王としてのメシヤが現れるという期待があった。（サムエル記下7:12,13、詩篇18:50、89:19-37、132:11,12、イザヤ9:6,7、11:1-5、アモス9:11,12）。この期待は中間時代にも受け継がれ、マカベヤ時代のユダヤ人たちの間で、レビの部族から祭司であり王であるメシヤが出るとの期待が高まった。しかし、ダビデの子孫としてのメシヤに対する期待も依然として存続していた。（ソロモンの詩篇17:5-8, 23-28, 18:6-8）。クムラン教団では、祭司としてのメシヤと、王としてのメシヤという、二人のメシヤに対する期待があった。イエスの時代にも、人々はダビデの王国を回復してくれるメシヤに対する期待を抱いた。しかし、このメシヤは、地上における、ダビデ王国を政治的に確立する人物であり、武力を持って、独立を獲得するものと考えられていた。イエスは、メシヤであったが、それは、地上の王国ではなく、霊の王国を確立し、武力による独立ではなく、十字架上のあがないの死によって、罪の力から霊を解放するかたであった。したがって、当時ユダヤ人の間に一般的に使われていた「メシヤ」という称号は誤った印象を与えるので、イエスはこれを用いることを避け「人の子」という表現を好んで用いた。しかし、旧約の預言において約束されていたメシヤの約束を真に成就するものとして、イエスは来られた。この意味において。ペテロの答えは正しかった。（マタイ16:17）。イエスの使命は、真に神のことばを語る預言者であり、霊のイスラエルの罪を贖う祭司であり、新しい霊のイスラエル王国（キリスト者の群れ）を建設し支配する王である。しかし、ペテロのすぐあとの態度（32）を見ると、彼はイエスをキリストとして告白しながらも、依然として当時のユダヤ人と同様に、地上的、政治的メシヤとして考えていたことがわかる。（いのちのことば社「新聖書注解」マルコによる福音書 山口昇）
    -   イザヤ9:6,7 ひとりのみどりごがわれわれのために生れた、／ひとりの男の子がわれわれに与えられた。まつりごとはその肩にあり、／その名は、「霊妙なる議士、大能の神、／とこしえの父、平和の君」ととなえられる。7 そのまつりごとと平和とは、増し加わって限りなく、／ダビデの位に座して、その国を治め、／今より後、とこしえに公平と正義とをもって／これを立て、これを保たれる。万軍の主の熱心がこれをなされるのである。
    -   イザヤ11:1-10 エッサイの株から一つの芽が出、／その根から一つの若枝が生えて実を結び、2 その上に主の霊がとどまる。これは知恵と悟りの霊、深慮と才能の霊、／主を知る知識と主を恐れる霊である。3 彼は主を恐れることを楽しみとし、／その目の見るところによって、さばきをなさず、／その耳の聞くところによって、定めをなさず、4 正義をもって貧しい者をさばき、／公平をもって国のうちの／柔和な者のために定めをなし、／その口のむちをもって国を撃ち、／そのくちびるの息をもって悪しき者を殺す。5 正義はその腰の帯となり、／忠信はその身の帯となる。6 おおかみは小羊と共にやどり、／ひょうは子やぎと共に伏し、／子牛、若じし、肥えたる家畜は共にいて、／小さいわらべに導かれ、7 雌牛と熊とは食い物を共にし、／牛の子と熊の子と共に伏し、／ししは牛のようにわらを食い、8 乳のみ子は毒蛇のほらに戯れ、／乳離れの子は手をまむしの穴に入れる。9 彼らはわが聖なる山のどこにおいても、そこなうことなく、／やぶることがない。水が海をおおっているように、／主を知る知識が地に満ちるからである。10 その日、エッサイの根が立って、もろもろの民の旗となり、もろもろの国びとはこれに尋ね求め、その置かれる所に栄光がある。
    -   エレミヤ22:4 もしあなたがたがこの言葉を真実に行うならば、ダビデの位にすわる王とその家臣、およびその民は、車と馬に乗って、この家の門にはいることができる。
    -   エレミヤ23:5 主は仰せられる、見よ、わたしがダビデのために一つの正しい枝を起す日がくる。彼は王となって世を治め、栄えて、公平と正義を世に行う。
    -   エレミヤ30:9 彼らはその神、主と、わたしが彼らのために立てるその王ダビデに仕える。

### 記録

-   日時：2024年2月29日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）7名

### 問いについて

1.  どのようなときに、イエスは、弟子たちに、自分について人々がだれだと言っているかと聞いていますか。（27）

    -   27 さて、イエスは弟子たちとピリポ・カイザリヤの村々へ出かけられたが、その途中で、弟子たちに尋ねて（繰り返し）言われた、「人々は、わたしをだれと言っているか」。

    -   \[DQ\] なぜ、ピリポ・カイザリヤの村々への途中で、尋ねたのでしょうか。

        -   ガリラヤから離れ、弟子たちだけがいるところで、聞いたのかもしれない。

        -   パリサイ派の人などがいるところでの、議論とは違う場で、おちついて弟子たちに問いたかったのでは。

    -   \[DQ\] なぜ、人々がだれだと言っているかを、まず聞いたのでしょうか。

        -   ある程度は、理解していたと思うが、全体像を把握しておきたいと思ったのかもしれない。

        -   パリサイ人などは、別として、人々の考えは様々だったろう。それを聞いておきたかったように思う。

    -   汚れた霊に憑かれたひと「神の聖者」（1:24）汚れた霊ども「神の子」（3:11）

    -   エリヤ：マラキ3:23 見よ、主の大いなる恐るべき日が来る前に、わたしは預言者エリヤをあなたがたにつかわす。

2.  弟子たちは、どのように答えますか。（28）

    -   28 彼らは答えて言った、「バプテスマのヨハネだと、言っています。また、エリヤだと言い、また、預言者のひとりだと言っている者もあります」。

        -   過去の偉人の生まれ変わりまたは復活。旧約の預言の成就としてのメシヤの前ぶれ。

    -   \[DQ\] これまでには、イエスについての人々の考えは、どのように書かれていましたか。

        -   6:14,15 14 さて、イエスの名が知れわたって、ヘロデ王の耳にはいった。ある人々は「バプテスマのヨハネが、死人の中からよみがえってきたのだ。それで、あのような力が彼のうちに働いているのだ」と言い、15 他の人々は「彼はエリヤだ」と言い、また他の人々は「昔の預言者のような預言者だ」と言った。

        -   ルカ9:7,8 7 さて、領主ヘロデはいろいろな出来事を耳にして、あわて惑っていた。それは、ある人たちは、ヨハネが死人の中からよみがえったと言い、8 またある人たちは、エリヤが現れたと言い、またほかの人たちは、昔の預言者のひとりが復活したのだと言っていたからである。（対応するマタイでは、バプテスマのヨハネのみ）

    -   \[DQ\] これまで、弟子たちは、どのように表現していましたか。

3.  それに対して、イエスはどのように尋ねますか。（29a）

    -   29a そこでイエスは彼らに尋ねられた、「それでは、あなたがたはわたしをだれと言うか」。

    -   \[DQ\] イエスは、どのような応答を期待・想定していたのでしょうか。

    -   \[DQ\] 弟子たちは、この問いを、これまで考えてきていたでしょうか。

        -   つねに問うていた（自問していた）のではないだろうか。

    -   \[DQ\] イエスは、なぜ、ここで、この時点で、このような問を弟子たちにしたのでしょうか。

        -   イエス自身、弟子たちが、どこにいるのか、まだよくわかっていなかったかもしれない。

    -   \[DQ\] これまで、弟子たちは、どのように表現していましたか。

        -   4:41 一体この方はどなたなのだろう。風も、湖さえも従わせるとは。

    -   \[DQ\] イエスの苦しみは、どのようなものだったのでしょうか。

        -   自分は神様の使命を果たしうるのだろうか。現状が神様の御心なのだろうか。

4.  だれがどのように答えますか。（29b）

    -   29b ペテロが答えて言った、「あなたこそキリストです」。

        -   「キリスト」という言葉は、どのような意味を持っているでしょうか。

    -   \[DQ\] これは「正解」、期待していた答えなのでしょうか。

        -   そうかもしれないが、正確ではないのだろう。キリストということばは曖昧だから。

        -   なぜ、ペテロは、キリストと答えたのでしょうか。ほかにも、答えはあるかもしれない。「神の子」

        -   メシヤ、キリストについての真実を語る前に、弟子たちが、キリストとして受け入れていることが大切だったのかもしれない。

5.  イエスは、なぜ、自分のことをだれにも言ってはいけないと、弟子たちを戒めるのでしょうか。（30）

    -   30 するとイエスは、自分のことをだれにも言ってはいけないと、彼らを戒められた。

    -   \[DQ\] イエスが、メシヤだということを言ってはいけないということでしょうか。

    -   \[DQ\] イエスが、恐れていたのはどのようなことでしょうか。

    -   \[DQ\] 「自分のことをだれにも言ってはいけない」ことは期限があるのでしょうか。

        -   マルコ9:9 一同が山を下って来るとき、イエスは「人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない」と、彼らに命じられた。

    -   過去に、伝えるなと言った例。家に帰れも、それに近い。

        -   黙れ（1:25）、ものを言うことを許さない（1:34）、規定の病が癒やされた人（1:44)、汚れた霊（3:11）、ヤイロ（5:43）、耳の聞こえない人口の聞けない人（7:36）

6.  マタイや、ルカからはさらにどのようなことがわかりますか。

    -   マタイ16:13 イエスがピリポ・カイザリヤの地方に行かれたとき、弟子たちに尋ねて言われた、「人々は人の子をだれと言っているか」。

        -   マルコでは、単に、その場に行った以上の内容が含まれているように見える。

            -   8:27 さて、イエスは弟子たちとピリポ・カイザリヤの村々へ出かけられたが、その途中で、弟子たちに尋ねて（繰り返し）言われた、「人々は、わたしをだれと言っているか」。

    -   ルカ 9:18 イエスがひとりで祈っておられたとき、弟子たちが近くにいたので、彼らに尋ねて言われた、「群衆はわたしをだれと言っているか」。

        -   祈っているときに、尋ねたは、少し不自然に感じるが、おそらく、重要な決断を暗示しているのだろう。

    -   マタイ16:14b また、エレミヤあるいは預言者のひとりだ、と言っている者もあります

        -   \[DQ\] 預言者のひとりのような人だと言っているのか、または、エレミヤや旧約の預言者が復活したと言っているのか、

            -   ルカ9:19 彼らは答えて言った、「バプテスマのヨハネだと、言っています。しかしほかの人たちは、エリヤだと言い、また昔の預言者のひとりが復活したのだと、言っている者もあります」。

    -   マタイ16:16 シモン・ペテロが答えて言った、「あなたこそ、生ける神の子キリストです」。

        -   このあとに、教会のことなど続く。

            -   マタイ16:17 すると、イエスは彼にむかって言われた、「バルヨナ・シモン、あなたはさいわいである。あなたにこの事をあらわしたのは、血肉ではなく、天にいますわたしの父である。18 そこで、わたしもあなたに言う。あなたはペテロである。そして、わたしはこの岩の上にわたしの教会を建てよう。黄泉の力もそれに打ち勝つことはない。19 わたしは、あなたに天国のかぎを授けよう。そして、あなたが地上でつなぐことは、天でもつながれ、あなたが地上で解くことは天でも解かれるであろう」。

            -   鍵（κλείς a key: a) since the keeper of the keys has the power to open and to shut, b) metaph. in the NT to denote power and authority of various kinds）の複数形：

                -   黙示録 1:18 また、生きている者である。わたしは死んだことはあるが、見よ、世々限りなく生きている者である。そして、死と黄泉とのかぎを持っている。

                -   黙示録 3:7 ヒラデルヒヤにある教会の御使に、こう書きおくりなさい。『聖なる者、まことなる者、ダビデのかぎを持つ者、開けばだれにも閉じられることがなく、閉じればだれにも開かれることのない者が、次のように言われる。

                -   イザヤ22:22 わたしはまたダビデの家のかぎを彼の肩に置く。彼が開けば閉じる者なく、彼が閉じれば開く者はない。

        -   \[DQ\] なぜマタイには、このような記述が入っており、マルコや、ルカには入っていないのでしょうか。

        -   マタイ14:33 舟の中にいた者たちはイエスを拝して、「ほんとうに、あなたは神の子です」と言った。

        -   マタイではこれが正解のような表現になっている。

7.  弟子たちにとって、イエスは、どのような存在だったのでしょうか。

    -   \[DQ\] 人々の評価「バプテスマのヨハネ」「エリヤ」「預言者のひとり」だと思っていたでしょうか。

    -   \[DQ\] なぜ人々の評価とは異なるのでしょうか。

    -   \[DQ\] どのようなことによって、イエスをみていたのでしょうか。

### メモ

-   地図を見ると、以前に、ツロ（7:24-30）、シドンを経てデカポリス地方を通り抜け（7:31）ガリラヤの海べにこられたときに、経路からして、ピリポ・カイザリアを通り過ぎたかもしれない。そのような、ガリラヤの北での活動が、マタイ11:21 「わざわいだ、コラジンよ。わざわいだ、ベツサイダよ。おまえたちのうちでなされた力あるわざが、もしツロとシドンでなされたなら、彼らはとうの昔に、荒布をまとい灰をかぶって、悔い改めたであろう。（ルカ10:13）に反映しているのかもしれない。

-   ここから大きな変化がある。イエスは、ヨハネ2:22-25 「それで、イエスが死人の中からよみがえったとき、弟子たちはイエスがこう言われたことを思い出して、聖書とイエスのこの言葉とを信じた。23 過越の祭の間、イエスがエルサレムに滞在しておられたとき、多くの人々は、その行われたしるしを見て、イエスの名を信じた。24 しかしイエスご自身は、彼らに自分をお任せにならなかった。それは、すべての人を知っておられ、25 また人についてあかしする者を、必要とされなかったからである。それは、ご自身人の心の中にあることを知っておられたからである。」からもわかるように、ペテロがどの程度理解できていたかも知っていたろう。しかし、マタイにかかれているほどではないが、是としたのだろう。これから、その告白したことばのように、生きることについて、学んでいくことになる。告白は、ローマ10:9,10 のように、大切ではあっても、それで完結ではない。

-   ヨハネ1:41 彼はまず自分の兄弟シモンに出会って言った、「わたしたちはメシヤ（訳せば、キリスト）にいま出会った」。ヨハネでは、すでに、シモン・ペテロの兄弟アンデレが、このように、メシヤであるとの証言をしている。バプテスマのヨハネの弟子だったアンデレにとって、このような証言は自然だったのだろうか。

## 8:31-38; 9:1 イエス、死と復活を予告する

> 31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32 しかもあからさまに、この事を話された。すると、ペテロはイエスをわきへ引き寄せて、いさめはじめたので、33 イエスは振り返って、弟子たちを見ながら、ペテロをしかって言われた、「サタンよ、引きさがれ。あなたは神のことを思わないで、人のことを思っている」。34 それから群衆を弟子たちと一緒に呼び寄せて、彼らに言われた、「だれでもわたしについてきたいと思うなら、自分を捨て、自分の十字架を負うて、わたしに従ってきなさい。35 自分の命を救おうと思う者はそれを失い、わたしのため、また福音のために、自分の命を失う者は、それを救うであろう。36 人が全世界をもうけても、自分の命を損したら、なんの得になろうか。37 また、人はどんな代価を払って、その命を買いもどすことができようか。38 邪悪で罪深いこの時代にあって、わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、父の栄光のうちに聖なる御使たちと共に来るときに、その者を恥じるであろう」。9:1 また、彼らに言われた、「よく聞いておくがよい。神の国が力をもって来るのを見るまでは、決して死を味わわない者が、ここに立っている者の中にいる」。

### マタイ 16:21-28

> 21 この時から、イエス・キリストは、自分が必ずエルサレムに行き、長老、祭司長、律法学者たちから多くの苦しみを受け、殺され、そして三日目によみがえるべきことを、弟子たちに示しはじめられた。22 すると、ペテロはイエスをわきへ引き寄せて、いさめはじめ、「主よ、とんでもないことです。そんなことがあるはずはございません」と言った。23 イエスは振り向いて、ペテロに言われた、「サタンよ、引きさがれ。わたしの邪魔をする者だ。あなたは神のことを思わないで、人のことを思っている」。24 それからイエスは弟子たちに言われた、「だれでもわたしについてきたいと思うなら、自分を捨て、自分の十字架を負うて、わたしに従ってきなさい。25 自分の命を救おうと思う者はそれを失い、わたしのために自分の命を失う者は、それを見いだすであろう。26 たとい人が全世界をもうけても、自分の命を損したら、なんの得になろうか。また、人はどんな代価を払って、その命を買いもどすことができようか。27 人の子は父の栄光のうちに、御使たちを従えて来るが、その時には、実際のおこないに応じて、それぞれに報いるであろう。28 よく聞いておくがよい、人の子が御国の力をもって来るのを見るまでは、死を味わわない者が、ここに立っている者の中にいる」。

### ルカ 9:22-27

> 22 「人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日目によみがえる」。23 それから、みんなの者に言われた、「だれでもわたしについてきたいと思うなら、自分を捨て、日々自分の十字架を負うて、わたしに従ってきなさい。24 自分の命を救おうと思う者はそれを失い、わたしのために自分の命を失う者は、それを救うであろう。25 人が全世界をもうけても、自分自身を失いまたは損したら、なんの得になろうか。26 わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、自分の栄光と、父と聖なる御使との栄光のうちに現れて来るとき、その者を恥じるであろう。27 よく聞いておくがよい、神の国を見るまでは、死を味わわない者が、ここに立っている者の中にいる」。

[マルコによる福音書8章31-38節, 9章1節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark8_31-38_9_1.pdf)

### 問い

1.  背景を復習しましょう。どのようなことがありましたか。

2.  イエスが伝えたことはどのようなことでしたか。（31,32a）

3.  ペテロはどうしますか。また、イエスはそれに対してどのように応じますか。（32b,33）

4.  イエスについてきたいと思うものに、どのようなことを伝えていますか。（34-37）

5.  自分を捨て、自分の十字架を負って、イエスに従っていくとはどのようなことでしょうか。（34）

6.  最後にイエスはどのようなことを語っていますか。（38,9:1）

### 参照

-   この出来事から逆順にエピソードを段落ごとにたどる。[福音書対照表](https://icu-hsuzuki.github.io/biblestudy/tables.html)

    -   マルコ：8:27-30 ペトロ、イエスがメシアであること告白する。8:22-26 ベトサイダで盲人を癒やす。8:14-21 ファリサイ派の人々とヘロデのパン種。8:11-13 人々はしるしを欲しがる。8:1-10 四千人に食べ物を与える。7:31-37 耳が聞こえず舌の回らないひとを癒やす。7:24-30 シリア・フェニキアの女の信仰。7:1-22 昔の人の言い伝え。6:53-56 ゲネサレトで病人を癒やす。6:45-52 湖の上を歩く。6:30-44 五千人に食べ物を与える。6:14-29 洗礼者ヨハネ、殺される。6:7-13 十二人を派遣する。6:1-6 ナザレで受け入れられない。

    -   マタイ：16:9-25 ペトロ、イエスがメシアであると告白する。16:5-12 ファリサイ派とサドカイ派の人々のパン種。16:1-4 人々はしるしを欲しがる。15:32-39 四千人に食べ物を与える。15:29-31 大勢の病人を癒やす。15:21-28 カナンの女の信仰。15:1-20 昔の人の言い伝え。14:34-36 ゲネサレトで病人を癒やす。14:22-33 湖の上を歩く。14:13-21 五千人に食べ物を与える。14:1-12 洗礼者ヨハネ、殺される。14:53-58 ナザレで受け入れられない。

    -   ルカ：9:18-20 ペトロ、イエスがメシアであると告白する。9:10-17 五千人に食べ物を与える。9:7-9 ヘロデ、困惑する。9:1-6 十二人を派遣する。

    -   まとめ：マルコとマタイは、記述内容な多少ことなるが、ほぼ同じ時系列になっている。十二人の派遣の位置はマタイでは、10:1, 5-15 に置かれ、洗礼者ヨハネが殺される記事や、五千人に食べ物を食べさせる記事とは、分けている。ルカでは、ガリラヤから離れて、異邦人の地などを彷徨する記事は省略され、五千人に食べ物を与える記事の直後に、ペトロ、イエスがメシアであると告白する記事を置いている。この記事のあと、9章の終わりまでは、マルコ、マタイ、ルカはほぼ並行して進む。

-   マタイ16:21 「この時から」

    -   マタイ4:17 この時からイエスは教を宣べはじめて言われた、「悔い改めよ、天国は近づいた」。

-   死と復活の予告

    -   8:31-32a 31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32a しかもあからさまに、この事を話された。

    -   9:30-32 30 それから彼らはそこを立ち去り、ガリラヤをとおって行ったが、イエスは人に気づかれるのを好まれなかった。31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

    -   10:32-34 32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。

-   イザヤ52:13-53:12

    -   52:13 見よ、わがしもべは栄える。彼は高められ、あげられ、ひじょうに高くなる。14 多くの人が彼に驚いたように――／彼の顔だちは、そこなわれて人と異なり、／その姿は人の子と異なっていたからである――15 彼は多くの国民を驚かす。王たちは彼のゆえに口をつむぐ。それは彼らがまだ伝えられなかったことを見、／まだ聞かなかったことを悟るからだ。53:1 だれがわれわれの聞いたことを／信じ得たか。主の腕は、だれにあらわれたか。2 彼は主の前に若木のように、／かわいた土から出る根のように育った。彼にはわれわれの見るべき姿がなく、威厳もなく、／われわれの慕うべき美しさもない。3 彼は侮られて人に捨てられ、／悲しみの人で、病を知っていた。また顔をおおって忌みきらわれる者のように、／彼は侮られた。われわれも彼を尊ばなかった。4 まことに彼はわれわれの病を負い、／われわれの悲しみをになった。しかるに、われわれは思った、／彼は打たれ、神にたたかれ、苦しめられたのだと。5 しかし彼はわれわれのとがのために傷つけられ、／われわれの不義のために砕かれたのだ。彼はみずから懲らしめをうけて、／われわれに平安を与え、／その打たれた傷によって、／われわれはいやされたのだ。6 われわれはみな羊のように迷って、／おのおの自分の道に向かって行った。主はわれわれすべての者の不義を、／彼の上におかれた。7 彼はしえたげられ、苦しめられたけれども、／口を開かなかった。ほふり場にひかれて行く小羊のように、／また毛を切る者の前に黙っている羊のように、／口を開かなかった。8 彼は暴虐なさばきによって取り去られた。その代の人のうち、だれが思ったであろうか、／彼はわが民のとがのために打たれて、／生けるものの地から断たれたのだと。9 彼は暴虐を行わず、／その口には偽りがなかったけれども、／その墓は悪しき者と共に設けられ、／その塚は悪をなす者と共にあった。10 しかも彼を砕くことは主のみ旨であり、／主は彼を悩まされた。彼が自分を、とがの供え物となすとき、／その子孫を見ることができ、／その命をながくすることができる。かつ主のみ旨が彼の手によって栄える。11 彼は自分の魂の苦しみにより光を見て満足する。義なるわがしもべはその知識によって、／多くの人を義とし、また彼らの不義を負う。12 それゆえ、わたしは彼に大いなる者と共に／物を分かち取らせる。彼は強い者と共に獲物を分かち取る。これは彼が死にいたるまで、自分の魂をそそぎだし、／とがある者と共に数えられたからである。しかも彼は多くの人の罪を負い、／とがある者のためにとりなしをした。

-   イエスの受難についての記述

    -   マルコ2:19, 20 するとイエスは言われた、「婚礼の客は、花婿が一緒にいるのに、断食ができるであろうか。花婿と一緒にいる間は、断食はできない。20 しかし、花婿が奪い去られる日が来る。その日には断食をするであろう。

        -   マタイ9:15 するとイエスは言われた、「婚礼の客は、花婿が一緒にいる間は、悲しんでおられようか。しかし、花婿が奪い去られる日が来る。その時には断食をするであろう。

    -   マルコ3:6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。

    -   マタイ10:38, 39 また自分の十字架をとってわたしに従ってこない者はわたしにふさわしくない。39 自分の命を得ている者はそれを失い、わたしのために自分の命を失っている者は、それを得るであろう。

    -   マタイ12:40 すなわち、ヨナが三日三晩、大魚の腹の中にいたように、人の子も三日三晩、地の中にいるであろう。

    -   ヨハネ2:19 イエスは彼らに答えて言われた、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。

-   パウロのエルサレム行きについて（使徒21:10-14）

### 記録

-   日時：2024年4月11日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）4名

### 問いについて

1.  背景を復習しましょう。どのようなことがありましたか。

    -   6章から9章への構成を復習。ルカとの違いを確認。（参照）

    -   8:27-30 ペトロ、イエスがメシアであると告白する の直後。

        -   27 さて、イエスは弟子たちとピリポ・カイザリヤの村々へ出かけられたが、その途中で、弟子たちに尋ねて言われた、「人々は、わたしをだれと言っているか」。28 彼らは答えて言った、「バプテスマのヨハネだと、言っています。また、エリヤだと言い、また、預言者のひとりだと言っている者もあります」。29 そこでイエスは彼らに尋ねられた、「それでは、あなたがたはわたしをだれと言うか」。ペテロが答えて言った、「あなたこそキリストです」。30 するとイエスは、自分のことをだれにも言ってはいけないと、彼らを戒められた。

    -   「するとイエスは、自分のことをだれにも言ってはいけないと、彼らを戒められた。」に続いている。

2.  イエスが伝えたことはどのようなことでしたか。（31,32a）

    -   31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32 しかもあからさまに、この事を話された。

    -   \[DQ\] 人の子とは誰のことでしょうか。弟子たちは、誰のことかわかったのでしょうか。

        -   このあとのペテロの反応から、それがイエスであることを、弟子たちは理解していたろう。

        -   人の子（マルコ 15件）：2:10, 28, 3:28, 8:38, 9:9, 12, 31, 10:33, 45, 13:26, 29, 14:21, 41, 62。マタイ30件、ルカ26件、ヨハネ12件、使徒7:56、（黙示録 1:13, 14:14 人の子のような者）

    -   \[DQ\] 具体的には、どのようなことを、どのような順番で述べていますか。

        -   ① 多くの苦しみを受け、② 長老、祭司長、律法学者たちに捨てられ、③ 殺され、④ 三日の後によみがえる（べきこと）

    -   \[DQ\] 「あらかさまにこの事を話された」とはどのようなことでしょうか。

        -   だれにでも分かる言葉でということだろうか。

3.  ペテロはどうしますか。また、イエスはそれに対してどのように応じますか。（32b,33）

    -   32b すると、ペテロはイエスをわきへ引き寄せて、いさめはじめたので、33 イエスは振り返って、弟子たちを見ながら、ペテロをしかって言われた、「サタンよ、引きさがれ。あなたは神のことを思わないで、人のことを思っている」。

    -   この記事は、ルカには欠けている。

    -   \[DQ\] ペテロは、なぜいさめたのでしょうか。それは、何を意味しているのでしょうか。

        -   「いさめる」ἐπιτιμάω i) to show honour to, to honour, ii) to raise the price of, iii) to adjudge, award, in the sense of merited penalty, iv) to tax with fault, rate, chide, rebuke, reprove, censure severely; to admonish or charge sharply: Mark 1:25, 3:12, 4:39, 8:30, 32, 33, 9:25, 10:13, 48

        -   8:30 するとイエスは、自分のことをだれにも言ってはいけないと、彼らを戒められた。

        -   8:30, 32b の対比からも、相互理解ができていないことがわかる。

        -   イエスも言っているように、人間的な思いなのだろう。イエスがキリストであることは、神の思いであり、それが人の思いとなるかどうかが鍵なのだろう。

    -   マタイ16:22 22 すると、ペテロはイエスをわきへ引き寄せて、いさめはじめ、「主よ、とんでもないことです。そんなことがあるはずはございません」と言った。

        -   少し深く読むと、それが、神様のみこころではないことを言っているのだろう。

        -   \[DQ\] イエスのことばの、なにが、ペテロにとって「とんでもないこと」なのでしょうか。

    -   \[DQ\] ペトロや弟子たちは「イエスがキリストである」ことをどのように考えていたのでしょうか。

        -   開放者。征服者。ダビデのような王。

        -   \[DQ\] あなたは、救い主にどのようなことを期待しますか。

    -   \[DQ\] なぜ、イエスは、振り返って、弟子たちを見ながら、ペテロをしかって「サタンよ、引きさがれ。あなたは神のことを思わないで、人のことを思っている」と言われたのでしょうか。

        -   生き生きと描かれている。直接的には、ペテロに対してであっても、本質的には、弟子たち全員、すなわち、わたしたちへのメッセージなのだろう。

    -   \[DQ\] なぜ、これほど、厳しい言葉で、ペテロを叱ったのでしょうか。

        -   イエス自身も含めて、もっとも警戒していたことなのかもしれない。

        -   マタイ4:8-10 次に悪魔は、イエスを非常に高い山に連れて行き、この世のすべての国々とその栄華とを見せて 9 言った、「もしあなたが、ひれ伏してわたしを拝むなら、これらのものを皆あなたにあげましょう」。10 するとイエスは彼に言われた、「サタンよ、退け。『主なるあなたの神を拝し、ただ神にのみ仕えよ』と書いてある」。

        -   この世を去ること（死）を望んでいなかったのかもしれない。

        -   \[DQ\] ペテロが正しいということはあり得なかったのだろうか。

4.  イエスについてきたいと思うものに、どのようなことを伝えていますか。（34-37）

    -   34 それから群衆を弟子たちと一緒に呼び寄せて、彼らに言われた、「だれでもわたしについてきたいと思うなら、自分を捨て、自分の十字架を負うて、わたしに従ってきなさい。35 自分の命を救おうと思う者はそれを失い、わたしのため、また福音のために、自分の命を失う者は、それを救うであろう。36 人が全世界をもうけても、自分の命を損したら、なんの得になろうか。37 また、人はどんな代価を払って、その命を買いもどすことができようか。

    -   \[DQ\] だれに向かって言っていますか。

        -   「それから群衆を弟子たちと一緒に呼び寄せて」弟子たちだけではなく、群衆もそこにいたことになる。（ルカでも「みんなの者に」（9:23）。マタイでは「弟子たちに」（16:24））

    -   「イエスについてきたい」と願う人にむけて語っている。まとめると

        -   ① 自分を捨て、② 自分の十字架を負うて、③ わたしに従ってきなさい。

        -   いのちがたいせつ。

    -   「だれでもわたしについてきたいと思うなら」

        -   弟子なら師についていくのは当然だとも言えるが、これは裏返すとイエスがどのようにこれから生きていこうかということを語っているのだろう。

    -   \[DQ\] 前半 34節と、後半 35-37 の関係はどうなっているのだろうか。

    -   \[DQ\] ここで言われている「命」とは「命を失う」「命を救う」とは、なんだろうか。

        -   命は、代価を払って買い戻すことができないもの。

    -   \[DQ\] 「福音のため」とは何を意味するのだろうか。

        -   伝道して、反対にあい、迫害されて殺されることでしょうか。

        -   「福音」とは何なのでしょうか。「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」（1:15）

5.  自分を捨て、自分の十字架を負って、イエスに従っていくとはどのようなことでしょうか。（34）

    -   「だれでもわたしについてきたいと思うなら、自分を捨て、自分の十字架を負うて、わたしに従ってきなさい。」

    -   \[DQ\] 「自分の十字架」とは何なのでしょうか。

        -   イエスの十字架のように、それぞれに、十字架があるということなのだろう。

6.  最後にイエスはどのようなことを語っていますか。（38,9:1）

    -   38 邪悪で罪深いこの時代にあって、わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、父の栄光のうちに聖なる御使たちと共に来るときに、その者を恥じるであろう」。9:1 また、彼らに言われた、「よく聞いておくがよい。神の国が力をもって来るのを見るまでは、決して死を味わわない者が、ここに立っている者の中にいる」。

    -   後に追加されたものなのではないかと思わされる。あくまでも、核は、前半の部分であるように思われる。（2回目、3回目の告知と比較。唐突で、このことについては、何も語られていない。弟子たちの期待の現れ。しかし、おそらくなにか関連したことは言われたのかもしれない。）

        -   マタイ16:27,28 27 人の子は父の栄光のうちに、御使たちを従えて来るが、その時には、実際のおこないに応じて、それぞれに報いるであろう。28 よく聞いておくがよい、人の子が御国の力をもって来るのを見るまでは、死を味わわない者が、ここに立っている者の中にいる」。

        -   ルカ9:26,27 26 わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、自分の栄光と、父と聖なる御使との栄光のうちに現れて来るとき、その者を恥じるであろう。27 よく聞いておくがよい、神の国を見るまでは、死を味わわない者が、ここに立っている者の中にいる」。

        -   参照：ダニエル7:13,14 わたしはまた夜の幻のうちに見ていると、／見よ、人の子のような者が、／天の雲に乗ってきて、／日の老いたる者のもとに来ると、／その前に導かれた。14 彼に主権と光栄と国とを賜い、／諸民、諸族、諸国語の者を彼に仕えさせた。その主権は永遠の主権であって、／なくなることがなく、／その国は滅びることがない。

    -   \[DQ\] これは、いつのことを言っているのでしょうか。

        -   この次の記事の山上変貌

        -   終末の再臨

        -   キリスト教会の設立をとおして、神の国の顕現を見る。

            -   マタイ16:18,19 18 そこで、わたしもあなたに言う。あなたはペテロである。そして、わたしはこの岩の上にわたしの教会を建てよう。黄泉の力もそれに打ち勝つことはない。19 わたしは、あなたに天国のかぎを授けよう。そして、あなたが地上でつなぐことは、天でもつながれ、あなたが地上で解くことは天でも解かれるであろう」。

### メモ

-   3つの部分に分かれている。

    1.  弟子への受難と死と復活の予告と、それをいさめるペテロの叱責（31-33）

    2.  弟子と群衆にむけたイエスに従うことについてのチャンレンジ（34-37）

    3.  イエスとその言葉を恥じるものについて（38-39）

    -   3は、要約も難しく、二文が関係しているのかどうかも不明である。

    -   死と復活の予告はあとからじっくりする選択肢もある。（二回目：9:30-32、三回目：10:32-34 は独立した学びをする予定）

    -   最後の部分もあとからじっくり考え、基本的な枠組みと、中心部分に集中するのがよいように思われる。（13章で、神殿の崩壊の予告のあと、弟子の質問にこたえて、終末の予兆について語る）

-   このエピソードのあと、山上の変貌の記事があり、ふもとでの、悪霊に憑かれた子を癒やす記事があり、ガリラヤに入り、カファルナウムにも行き、エルサレムに向かう。（10章から）これまでとは雰囲気が変わっている。

-   「35 自分の命を救おうと思う者はそれを失い、わたしのため、また福音のために、自分の命を失う者は、それを救うであろう。」ここに非対称がある。自分の命を失おうとするわけではない。どのように、失うことになるのかは不明。

-   イエスに従っていくものの大変さが書かれているようにも思うが、神の国は近い、このことを経験しながら生きることができるのは、まさに、福音に生きることであり、幸せなことなのだろう。

## 9:2-13 イエスの姿が変わる

> 2 六日の後、イエスは、ただペテロ、ヤコブ、ヨハネだけを連れて、高い山に登られた。ところが、彼らの目の前でイエスの姿が変り、3 その衣は真白く輝き、どんな布さらしでも、それほどに白くすることはできないくらいになった。4 すると、エリヤがモーセと共に彼らに現れて、イエスと語り合っていた。5 ペテロはイエスにむかって言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。6 そう言ったのは、みんなの者が非常に恐れていたので、ペテロは何を言ってよいか、わからなかったからである。7 すると、雲がわき起って彼らをおおった。そして、その雲の中から声があった、「これはわたしの愛する子である。これに聞け」。8 彼らは急いで見まわしたが、もはやだれも見えず、ただイエスだけが、自分たちと一緒におられた。9 一同が山を下って来るとき、イエスは「人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない」と、彼らに命じられた。10 彼らはこの言葉を心にとめ、死人の中からよみがえるとはどういうことかと、互に論じ合った。11 そしてイエスに尋ねた、「なぜ、律法学者たちは、エリヤが先に来るはずだと言っているのですか」。12 イエスは言われた、「確かに、エリヤが先にきて、万事を元どおりに改める。しかし、人の子について、彼が多くの苦しみを受け、かつ恥ずかしめられると、書いてあるのはなぜか。13 しかしあなたがたに言っておく、エリヤはすでにきたのだ。そして彼について書いてあるように、人々は自分かってに彼をあしらった」。

### マタイ 17:1-13

> 1 六日ののち、イエスはペテロ、ヤコブ、ヤコブの兄弟ヨハネだけを連れて、高い山に登られた。2 ところが、彼らの目の前でイエスの姿が変り、その顔は日のように輝き、その衣は光のように白くなった。3 すると、見よ、モーセとエリヤが彼らに現れて、イエスと語り合っていた。4 ペテロはイエスにむかって言った、「主よ、わたしたちがここにいるのは、すばらしいことです。もし、おさしつかえなければ、わたしはここに小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。5 彼がまだ話し終えないうちに、たちまち、輝く雲が彼らをおおい、そして雲の中から声がした、「これはわたしの愛する子、わたしの心にかなう者である。これに聞け」。6 弟子たちはこれを聞いて非常に恐れ、顔を地に伏せた。7 イエスは近づいてきて、手を彼らにおいて言われた、「起きなさい、恐れることはない」。8 彼らが目をあげると、イエスのほかには、だれも見えなかった。9 一同が山を下って来るとき、イエスは「人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない」と、彼らに命じられた。10 弟子たちはイエスにお尋ねして言った、「いったい、律法学者たちは、なぜ、エリヤが先に来るはずだと言っているのですか」。11 答えて言われた、「確かに、エリヤがきて、万事を元どおりに改めるであろう。12 しかし、あなたがたに言っておく。エリヤはすでにきたのだ。しかし人々は彼を認めず、自分かってに彼をあしらった。人の子もまた、そのように彼らから苦しみを受けることになろう」。13 そのとき、弟子たちは、イエスがバプテスマのヨハネのことを言われたのだと悟った。

### ルカ 9:28-36

> 28 これらのことを話された後、八日ほどたってから、イエスはペテロ、ヨハネ、ヤコブを連れて、祈るために山に登られた。29 祈っておられる間に、み顔の様が変り、み衣がまばゆいほどに白く輝いた。30 すると見よ、ふたりの人がイエスと語り合っていた。それはモーセとエリヤであったが、31 栄光の中に現れて、イエスがエルサレムで遂げようとする最後のことについて話していたのである。32 ペテロとその仲間の者たちとは熟睡していたが、目をさますと、イエスの栄光の姿と、共に立っているふたりの人とを見た。33 このふたりがイエスを離れ去ろうとしたとき、ペテロは自分が何を言っているのかわからないで、イエスに言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。34 彼がこう言っている間に、雲がわき起って彼らをおおいはじめた。そしてその雲に囲まれたとき、彼らは恐れた。35 すると雲の中から声があった、「これはわたしの子、わたしの選んだ者である。これに聞け」。36 そして声が止んだとき、イエスがひとりだけになっておられた。弟子たちは沈黙を守って、自分たちが見たことについては、そのころだれにも話さなかった。

[マルコによる福音書9章2-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_2-13.pdf)

### 問い

1.  いつ、どこで、起きたことが記されていますか。そこにいたのは誰ですか。（2-4）

2.  ペテロはどのような提案をしますか。その状況はどのように描かれていますか。（5-6）

3.  雲の中からの声については、どのように描かれていますか。（7-8）

4.  イエスはどのように、命じますか。なぜでしょうか。（9-10）

5.  弟子たちはどのような質問をし、イエスはそれにどう答えますか。（11-13）

6.  この記事は、何を伝えているのでしょう。マタイやルカの記述も参考にしましょう。

### 参照

-   ヘルモン山：ヘルモン山（Mount Hermon, ヘブライ語: הר חרמון‎）シャイフ山（Jabal al‐Shaykh\[1\], アラビア語: جبل الشيخ‎）は、レバノンとシリアの国境にあるアンチレバノン山脈の最高峰で、最高点の標高は2,814mである。

-   タボル山：タボル山（ヘブライ語: הר תבור‎、英語: Mount Tabor）は、イスラエルの北部地区にある標高575mの山。ヘブライ語で「Har Tavor」、アラビヤ語では「ジェベル・エト・トゥール」と呼ばれる。聖書の記述に関連して日本では変貌山とも書かれるが、これは他の山のことであるとする説もある。

    -   ヨセフスはタボル山の頂上に要塞があったと証言している。

-   マラキ3:1　見よ、わたしはわが使者をつかわす。彼はわたしの前に道を備える。またあなたがたが求める所の主は、たちまちその宮に来る。見よ、あなたがたの喜ぶ契約の使者が来ると、万軍の主が言われる。

-   マラキ4:4-6 あなたがたは、わがしもべモーセの律法、すなわちわたしがホレブで、イスラエル全体のために、彼に命じた定めとおきてとを覚えよ。5 見よ、主の大いなる恐るべき日が来る前に、わたしは預言者エリヤをあなたがたにつかわす。6 彼は父の心をその子供たちに向けさせ、子供たちの心をその父に向けさせる。これはわたしが来て、のろいをもってこの国を撃つことのないようにするためである」。

-   イザヤ40:3　呼ばわる者の声がする、／「荒野に主の道を備え、／さばくに、われわれの神のために、／大路をまっすぐにせよ。

    -   イザヤ40:3-5 は、マタイ3:3, マルコ1:3、ルカ3:4、ヨハネ1:23 と四福音書にバプテスマのヨハネとの関連で引用されている

-   復活

    -   マルコ12:26-27 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている」。

-   エリヤ

    -   列王記下2:11 彼らが進みながら語っていた時、火の車と火の馬があらわれて、ふたりを隔てた。そしてエリヤはつむじ風に乗って天にのぼった。

    -   マルコ6:15 他の人々は「彼はエリヤだ」と言い、また他の人々は「昔の預言者のような預言者だ」と言った。

    -   マルコ8:28 彼らは答えて言った、「バプテスマのヨハネだと、言っています。また、エリヤだと言い、また、預言者のひとりだと言っている者もあります」。

    -   マルコ9:4,5 すると、エリヤがモーセと共に彼らに現れて、イエスと語り合っていた。5 ペテロはイエスにむかって言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。

    -   マルコ9:11-13 そしてイエスに尋ねた、「なぜ、律法学者たちは、エリヤが先に来るはずだと言っているのですか」。12 イエスは言われた、「確かに、エリヤが先にきて、万事を元どおりに改める。しかし、人の子について、彼が多くの苦しみを受け、かつ恥ずかしめられると、書いてあるのはなぜか。13 しかしあなたがたに言っておく、エリヤはすでにきたのだ。そして彼について書いてあるように、人々は自分かってに彼をあしらった」。

    -   マルコ15:35,36 すると、そばに立っていたある人々が、これを聞いて言った、「そら、エリヤを呼んでいる」。36 ひとりの人が走って行き、海綿に酢いぶどう酒を含ませて葦の棒につけ、イエスに飲ませようとして言った、「待て、エリヤが彼をおろしに来るかどうか、見ていよう」。

-   モーセ

    -   申命記34:1-8 モーセはモアブの平野からネボ山に登り、エリコの向かいのピスガの頂へ行った。そこで主は彼にギレアデの全地をダンまで示し、2 ナフタリの全部、エフライムとマナセの地およびユダの全地を西の海まで示し、3 ネゲブと低地、すなわち、しゅろの町エリコの谷をゾアルまで示された。4 そして主は彼に言われた、「わたしがアブラハム、イサク、ヤコブに、これをあなたの子孫に与えると言って誓った地はこれである。わたしはこれをあなたの目に見せるが、あなたはそこへ渡って行くことはできない」。5 こうして主のしもべモーセは主の言葉のとおりにモアブの地で死んだ。6 主は彼をベテペオルに対するモアブの地の谷に葬られたが、今日までその墓を知る人はない。7 モーセは死んだ時、百二十歳であったが、目はかすまず、気力は衰えていなかった。8 イスラエルの人々はモアブの平野で三十日の間モーセのために泣いた。そしてモーセのために泣き悲しむ日はついに終った。

    -   マルコ1:44 「何も人に話さないように、注意しなさい。ただ行って、自分のからだを祭司に見せ、それから、モーセが命じた物をあなたのきよめのためにささげて、人々に証明しなさい」。

    -   マルコ7:10 モーセは言ったではないか、『父と母とを敬え』、また『父または母をののしる者は、必ず死に定められる』と。

    -   マルコ9:4,5 すると、エリヤがモーセと共に彼らに現れて、イエスと語り合っていた。5 ペテロはイエスにむかって言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。

    -   マルコ10:3-5 イエスは答えて言われた、「モーセはあなたがたになんと命じたか」。4 彼らは言った、「モーセは、離縁状を書いて妻を出すことを許しました」。5 そこでイエスは言われた、「モーセはあなたがたの心が、かたくななので、あなたがたのためにこの定めを書いたのである。

    -   マルコ12:19 「先生、モーセは、わたしたちのためにこう書いています、『もし、ある人の兄が死んで、その残された妻に、子がない場合には、弟はこの女をめとって、兄のために子をもうけねばならない』。

    -   マルコ12:26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。

-   ペテロ後書1:16-18 わたしたちの主イエス・キリストの力と来臨とを、あなたがたに知らせた時、わたしたちは、巧みな作り話を用いることはしなかった。わたしたちが、そのご威光の目撃者なのだからである。17 イエスは父なる神からほまれと栄光とをお受けになったが、その時、おごそかな栄光の中から次のようなみ声がかかったのである、「これはわたしの愛する子、わたしの心にかなう者である」。18 わたしたちもイエスと共に聖なる山にいて、天から出たこの声を聞いたのである。

-   デバーリーム・ラッバー（Devarim（申命記）Rabbah）３：メシヤの日には、モーセとエリヤが「一人のように」共に来るといった。（榊原康夫）未確認。

### 記録

-   日時：2024年4月18日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）4名

### 問いについて

1.  いつ、どこで、起きたことが記されていますか。そこにいたのは誰ですか。（2-4）

    -   2 六日の後、イエスは、ただペテロ、ヤコブ、ヨハネだけを連れて、高い山に登られた。ところが、彼らの目の前でイエスの姿が変り、3 その衣は真白く輝き、どんな布さらしでも、それほどに白くすることはできないくらいになった。4 すると、エリヤがモーセと共に彼らに現れて、イエスと語り合っていた。

    -   「六日の後」「高い山」「イエスの衣が白くなった」「エリヤとモーセがイエスと語り合っていた」「ペテロ、ヤコブ、ヨハネだけを連れて」

    -   \[DQ\] いつから「六日の後」なのでしょうか。（ルカも参照）

        -   ルカでは「八日ほどたって」。かつ「祈るために山に登られ」「祈っておられる間に」と祈りが強調されている。

    -   \[DQ\] どのあたりの山でしょうか。

    -   \[DQ\] なぜ、ペトロ、ヤコブ、ヨハネだけを連れて行ったのでしょうか。

        -   マルコ5:37,40 そしてペテロ、ヤコブ、ヤコブの兄弟ヨハネのほかは、ついて来ることを、だれにもお許しにならなかった。40 人々はイエスをあざ笑った。しかし、イエスはみんなの者を外に出し、子供の父母と供の者たちだけを連れて、子供のいる所にはいって行かれた。

        -   マルコ14:33 （ゲッセマネ）そしてペテロ、ヤコブ、ヨハネを一緒に連れて行かれたが、恐れおののき、また悩みはじめて、彼らに言われた、

        -   証人：申命記19:15 どんな不正であれ、どんなとがであれ、すべて人の犯す罪は、ただひとりの証人によって定めてはならない。ふたりの証人の証言により、または三人の証人の証言によって、その事を定めなければならない。

    -   \[DQ\] ここで描かれている状況は何を伝えているのでしょうか。

        -   「彼らの目の前でイエスの姿が変わり」弟子たちは皆が認められるような変化だったことが、まさに、目撃証言として語られている。

        -   「エリヤがモーセとともに彼らに現れて」とあり、イエスだけに現れたわけではない。

        -   エリヤとモーセは生きているのでしょうか。（12:26参照）

        -   ルカでは「栄光の中に現れて」「イエスの栄光の姿と共に立っている二人の人とを見た」とあり、栄光が強調されている。これがキリスト教会で共有されていたことなのだろう。

    -   \[DQ\] なぜ、エリヤとモーセなのでしょうか。

        -   聖書は、「律法と預言者」と呼ばれていた。その代表？　なぜエリヤが先か。（マタイ、ルカはモーセが先）おそらく、このあとのエリヤ談義と関係があってそのように記憶されていたのだろう。

2.  ペテロはどのような提案をしますか。その状況はどのように描かれていますか。（5-6）

    -   5 ペテロはイエスにむかって言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。6 そう言ったのは、みんなの者が非常に恐れていたので、ペテロは何を言ってよいか、わからなかったからである。

    -   \[DQ\] なぜ小屋を建てると提案したのでしょうか。

        -   自分たちの「すばらしい」経験を形にして残したかった？

        -   非常におそれていて、自分でも何を言っているのかわからなかった。混濁状態。

        -   仮庵の祭りが近かったとの説もある。（9月末から10月半ば）たとえそうだったとしても、それだけを理由にするのは、本質を外しているように見える。

    -   モーセと、エリヤを認識していたことが証言されている。

        -   イエスのことばから推測したのだろうか。「エリヤがモーセと共に彼らに現れて」

    -   非常に恐れていて、何を言ってよいかわからなかったとあり、混乱状態も考えられる。

3.  雲の中からの声については、どのように描かれていますか。（7-8）

    -   7 すると、雲がわき起って彼らをおおった。そして、その雲の中から声があった、「これはわたしの愛する子である。これに聞け」。8 彼らは急いで見まわしたが、もはやだれも見えず、ただイエスだけが、自分たちと一緒におられた。

    -   参照：マルコ1:9-11 そのころ、イエスはガリラヤのナザレから出てきて、ヨルダン川で、ヨハネからバプテスマをお受けになった。10 そして、水の中から上がられるとすぐ、天が裂けて、聖霊がはとのように自分に下って来るのを、ごらんになった。11 すると天から声があった、「あなたはわたしの愛する子、わたしの心にかなう者である」。

    -   \[DQ\] 彼らをおおったの「彼ら」とは誰でしょうか。

        -   不明だが、「ただイエスだけが、自分たちと一緒におられた」という表現から、モーセとエリヤは、見えなくなったのだろう。

    -   \[DQ\] 「これはわたしの愛する子である。これに聞け」は、何を意味しているのでしょうか。ペテロの提案の答えだろうか。

    -   モーセとエリヤの実像がどのようなものだったかは不明だが、イエスが、モーセとエリヤと語り合っていたことはわかったのだろう。

    -   \[DQ\] だれにむけて、どのようなメッセージを語っているのでしょうか。

    -   \[DQ\] 「これに聞け」は、何を聞けと言っているのでしょうか。

        -   おそらく、ペテロの提案に対する答えもあるだろうが、もっと大きな意味で、イエスに聞くことが、神の御心を知ることだと言っているようにも見える。

    -   申命記18:15 あなたの神、主はあなたのうちから、あなたの同胞のうちから、わたしのようなひとりの預言者をあなたのために起されるであろう。あなたがたは彼に聞き従わなければならない。

4.  イエスはどのように、命じますか。なぜでしょうか。（9-10）

    -   9 一同が山を下って来るとき、イエスは「人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない」と、彼らに命じられた。10 彼らはこの言葉を心にとめ、死人の中からよみがえるとはどういうことかと、互に論じ合った。

    -   \[DQ\] なぜ「人の子が死人の中からよみがえるまで」なのでしょうか。

        -   イエスも、受難と死と復活を告げていたので、そこまでが使命と考えていたのかもしれない。

        -   復活とは何なのかの問は難しい。イエスも、完全には理解できていなかったのかもしれない。

    -   \[DQ\] イエスが伝えたこと、弟子たちが理解したことは何だったのでしょうか。

    -   よみがえりで完結だと、イエスが理解していたのではないだろうか。

    -   律法や、預言者から、神様のみこころを確認していたのだろうか。

    -   モーセやエリヤは、イエスとしては、生きている存在だったのだろう。

5.  弟子たちはどのような質問をし、イエスはそれにどう答えますか。（11-13）

    -   11 そしてイエスに尋ねた、「なぜ、律法学者たちは、エリヤが先に来るはずだと言っているのですか」。12 イエスは言われた、「確かに、エリヤが先にきて、万事を元どおりに改める。しかし、人の子について、彼が多くの苦しみを受け、かつ恥ずかしめられると、書いてあるのはなぜか。13 しかしあなたがたに言っておく、エリヤはすでにきたのだ。そして彼について書いてあるように、人々は自分かってに彼をあしらった」。

    -   エリヤが先にくるはずだという説について。

        -   マルコ1:2-4 預言者イザヤの書に、／「見よ、わたしは使をあなたの先につかわし、／あなたの道を整えさせるであろう。3 荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と書いてあるように、4 バプテスマのヨハネが荒野に現れて、罪のゆるしを得させる悔改めのバプテスマを宣べ伝えていた。

        -   マラキ3:1, 4:4-6 5 見よ、主の大いなる恐るべき日が来る前に、わたしは預言者エリヤをあなたがたにつかわす。6 彼は父の心をその子供たちに向けさせ、子供たちの心をその父に向けさせる。これはわたしが来て、のろいをもってこの国を撃つことのないようにするためである」。

    -   「人の子について、彼が多くの苦しみを受け、かつ恥ずかしめられると、書いてある」と言っている。内容は、受難の告知と似ているが、書いてあるとは、旧約聖書を意味しているのだろう。

        -   おそらく、イザヤ書を念頭においている。

        -   「なぜか。」と問うている、これは、イエス自身への問だったのかもしれない。弟子たちには、考えが及ぶことではないだろう。まさに、そのような問いについて、聖書のひとたちと、聖書箇所を思い出しながら、語り合い、神様とコミュニケーションしていたのかもしれない。

    -   \[DQ\]「そして彼について書いてあるように、人々は自分かってに彼をあしらった」は、何を意味しているのだろうか。

        -   マタイ11:7-19 13 すべての預言者と律法とが預言したのは、ヨハネの時までである。14 そして、もしあなたがたが受けいれることを望めば、この人こそは、きたるべきエリヤなのである。15 耳のある者は聞くがよい。16 今の時代を何に比べようか。それは子供たちが広場にすわって、ほかの子供たちに呼びかけ、17 『わたしたちが笛を吹いたのに、／あなたたちは踊ってくれなかった。弔いの歌を歌ったのに、／胸を打ってくれなかった』／と言うのに似ている。18 なぜなら、ヨハネがきて、食べることも、飲むこともしないと、あれは悪霊につかれているのだ、と言い、19 また人の子がきて、食べたり飲んだりしていると、見よ、あれは食をむさぼる者、大酒を飲む者、また取税人、罪人の仲間だ、と言う。しかし、知恵の正しいことは、その働きが証明する」。

        -   ルカ1:13-17 16 そして、イスラエルの多くの子らを、主なる彼らの神に立ち帰らせるであろう。17 彼はエリヤの霊と力とをもって、みまえに先立って行き、父の心を子に向けさせ、逆らう者に義人の思いを持たせて、整えられた民を主に備えるであろう」。

    -   \[DQ\] エリヤの役割は何なのでしょうか。本当に、元どおりに改めたのでしょうか。

        -   そして彼について書いてあるように、人々は自分かってに彼をあしらった。

        -   それは書いてあるのだろうか。書いてあるとすると、イザヤ書。

6.  この記事は、何を伝えているのでしょう。マタイやルカの記述も参考にしましょう。

    -   受難告知の裏側を示していることは確かだろう。

    -   イエスにとって

        -   モーセ（律法授与者）とエリヤ（偉大な預言者）に出会い、語り合った。

        -   神からのメッセージ：すると、雲がわき起って彼らをおおった。そして、その雲の中から声があった、「これはわたしの愛する子である。これに聞け」。

    -   弟子たちにとって

        -   理解できなくても、信頼すること。

        -   栄光の証人。

    -   マタイ17:6-8 6 弟子たちはこれを聞いて非常に恐れ、顔を地に伏せた。7 イエスは近づいてきて、手を彼らにおいて言われた、「起きなさい、恐れることはない」。8 彼らが目をあげると、イエスのほかには、だれも見えなかった。

### メモ

-   仮庵の祭り：9月末から10月中旬（ザドク暦第七ホデシュの15日から7日間）

    -   レビ記23章34-43節、ヨハネによる福音書7章37-38節

-   だれがイエスと語り合っていますか。エリヤについて 9:11-13 と マタイ 17:10-13 を比べてみましょう。

-   ルカでは「栄光の中に現れて」「イエスの栄光の姿と共に立っている二人の人とを見た」とあり、栄光が強調されている。これがキリスト教会で共有されていたことなのだろう。また、このことが、ペテロ後書からも見て取れる。イエスの再臨のときの、栄光の姿を垣間見る経験だったとしているのだろう。それが、8:38-9:1 とも関連している。

    -   38 邪悪で罪深いこの時代にあって、わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、父の栄光のうちに聖なる御使たちと共に来るときに、その者を恥じるであろう」。9:1 また、彼らに言われた、「よく聞いておくがよい。神の国が力をもって来るのを見るまでは、決して死を味わわない者が、ここに立っている者の中にいる」。

    -   2ペテロ1:16-18 わたしたちの主イエス・キリストの力と来臨とを、あなたがたに知らせた時、わたしたちは、巧みな作り話を用いることはしなかった。わたしたちが、そのご威光の目撃者なのだからである。17 イエスは父なる神からほまれと栄光とをお受けになったが、その時、おごそかな栄光の中から次のようなみ声がかかったのである、「これはわたしの愛する子、わたしの心にかなう者である」。18 わたしたちもイエスと共に聖なる山にいて、天から出たこの声を聞いたのである。

-   イエスにとって、バプテスマのヨハネの存在はとても大きかったのだろう。バプテスマのヨハネの役割は十分認識していた。それがエリヤの出現預言とつながっているように見える。マルコ冒頭でも、イザヤ預言と、マラキ預言を一緒にして、それを、預言者イザヤの書にこう書いてあるとしている。

-   ２つに分けて学んだほうが良いかもしれない。内容が濃く、十分消化するのが難しい。

## 9:14-29 汚れた霊に取りつかれた子を癒やす

> 14 さて、彼らがほかの弟子たちの所にきて見ると、大ぜいの群衆が弟子たちを取り囲み、そして律法学者たちが彼らと論じ合っていた。15 群衆はみな、すぐイエスを見つけて、非常に驚き、駆け寄ってきて、あいさつをした。16 イエスが彼らに、「あなたがたは彼らと何を論じているのか」と尋ねられると、17 群衆のひとりが答えた、「先生、口をきけなくする霊につかれているわたしのむすこを、こちらに連れて参りました。18 霊がこのむすこにとりつきますと、どこででも彼を引き倒し、それから彼はあわを吹き、歯をくいしばり、からだをこわばらせてしまいます。それでお弟子たちに、この霊を追い出してくださるように願いましたが、できませんでした」。19 イエスは答えて言われた、「ああ、なんという不信仰な時代であろう。いつまで、わたしはあなたがたと一緒におられようか。いつまで、あなたがたに我慢ができようか。その子をわたしの所に連れてきなさい」。20 そこで人々は、その子をみもとに連れてきた。霊がイエスを見るや否や、その子をひきつけさせたので、子は地に倒れ、あわを吹きながらころげまわった。21 そこで、イエスが父親に「いつごろから、こんなになったのか」と尋ねられると、父親は答えた、「幼い時からです。22 霊はたびたび、この子を火の中、水の中に投げ入れて、殺そうとしました。しかしできますれば、わたしどもをあわれんでお助けください」。23 イエスは彼に言われた、「もしできれば、と言うのか。信ずる者には、どんな事でもできる」。24 その子の父親はすぐ叫んで言った、「信じます。不信仰なわたしを、お助けください」。25 イエスは群衆が駆け寄って来るのをごらんになって、けがれた霊をしかって言われた、「言うことも聞くこともさせない霊よ、わたしがおまえに命じる。この子から出て行け。二度と、はいって来るな」。26 すると霊は叫び声をあげ、激しく引きつけさせて出て行った。その子は死人のようになったので、多くの人は、死んだのだと言った。27 しかし、イエスが手を取って起されると、その子は立ち上がった。28 家にはいられたとき、弟子たちはひそかにお尋ねした、「わたしたちは、どうして霊を追い出せなかったのですか」。29 すると、イエスは言われた、「このたぐいは、祈によらなければ、どうしても追い出すことはできない」。

### マタイ 17:14-21

> 14 さて彼らが群衆のところに帰ると、ひとりの人がイエスに近寄ってきて、ひざまずいて、言った、15 「主よ、わたしの子をあわれんでください。てんかんで苦しんでおります。何度も何度も火の中や水の中に倒れるのです。16 それで、その子をお弟子たちのところに連れてきましたが、なおしていただけませんでした」。17 イエスは答えて言われた、「ああ、なんという不信仰な、曲った時代であろう。いつまで、わたしはあなたがたと一緒におられようか。いつまであなたがたに我慢ができようか。その子をここに、わたしのところに連れてきなさい」。18 イエスがおしかりになると、悪霊はその子から出て行った。そして子はその時いやされた。19 それから、弟子たちがひそかにイエスのもとにきて言った、「わたしたちは、どうして霊を追い出せなかったのですか」。20 するとイエスは言われた、「あなたがたの信仰が足りないからである。よく言い聞かせておくが、もし、からし種一粒ほどの信仰があるなら、この山にむかって『ここからあそこに移れ』と言えば、移るであろう。このように、あなたがたにできない事は、何もないであろう。21 〔しかし、このたぐいは、祈と断食とによらなければ、追い出すことはできない〕」。

### ルカ 9:37-43a

> 37 翌日、一同が山を降りて来ると、大ぜいの群衆がイエスを出迎えた。38 すると突然、ある人が群衆の中から大声をあげて言った、「先生、お願いです。わたしのむすこを見てやってください。この子はわたしのひとりむすこですが、39 霊が取りつきますと、彼は急に叫び出すのです。それから、霊は彼をひきつけさせて、あわを吹かせ、彼を弱り果てさせて、なかなか出て行かないのです。40 それで、お弟子たちに、この霊を追い出してくださるように願いましたが、できませんでした」。41 イエスは答えて言われた、「ああ、なんという不信仰な、曲った時代であろう。いつまで、わたしはあなたがたと一緒におられようか、またあなたがたに我慢ができようか。あなたの子をここに連れてきなさい」。42 ところが、その子がイエスのところに来る時にも、悪霊が彼を引き倒して、引きつけさせた。イエスはこの汚れた霊をしかりつけ、その子供をいやして、父親にお渡しになった。43a 人々はみな、神の偉大な力に非常に驚いた。

[マルコによる福音書9章14-29節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_14-29.pdf)

### 問い

1.  背景を復習しましょう。（14）

2.  どのような問題が起こっていますか。（15-18）

3.  イエスはどうしますか。（19-22）

4.  父親とイエスの対話からどのようなことがわかりますか。（22-24）

5.  イエスはどうしますか、そしてどうなりますか。（25-27）

6.  弟子たちは、イエスにどのような質問をし、イエスはどう答えますか。（28,29）

7.  イエスは人々の「不信仰」に対して何を求めているのでしょうか。

### 参照

-   不信仰：9:24 εὐθὺς κράξας ὁ πατὴρ τοῦ παιδίου ἔλεγεν πιστεύω βοήθει μου τῇ ἀπιστίᾳ

    -   ἀπιστίᾳ: i) unfaithfulness, faithless, ii) want of faith, unbelief, iii) weakness of faith

    -   6:6 そして、彼らの不信仰を驚き怪しまれた。それからイエスは、附近の村々を巡りあるいて教えられた。マタイ13:58 そして彼らの不信仰のゆえに、そこでは力あるわざを、あまりなさらなかった。

    -   9:24 24 その子の父親はすぐ叫んで言った、「信じます。不信仰なわたしを、お助けください」。

    -   16:14 その後、イエスは十一弟子が食卓についているところに現れ、彼らの不信仰と、心のかたくななことをお責めになった。彼らは、よみがえられたイエスを見た人々の言うことを、信じなかったからである。

    -   マタイ17:20 するとイエスは言われた、「あなたがたの信仰が足りないからである。よく言い聞かせておくが、もし、からし種一粒ほどの信仰があるなら、この山にむかって『ここからあそこに移れ』と言えば、移るであろう。このように、あなたがたにできない事は、何もないであろう。

### 記録

-   日時：2024年4月25日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）4名

### 問いについて

1.  背景を復習しましょう。（14）

    -   14 さて、彼らがほかの弟子たちの所にきて見ると、大ぜいの群衆が弟子たちを取り囲み、そして律法学者たちが彼らと論じ合っていた。

    -   山上のイエスの栄光の姿への変貌と、現実の世界の喧騒の対比がある。

        -   9:5 5 ペテロはイエスにむかって言った、「先生、わたしたちがここにいるのは、すばらしいことです。それで、わたしたちは小屋を三つ建てましょう。一つはあなたのために、一つはモーセのために、一つはエリヤのために」。

    -   \[DQ\] だれがいますか。

        -   山から降りてきたイエスとペテロ、ヤコブ、ヨハネ。他の弟子たち。群衆。律法学者。

    -   \[DQ\] どのような光景が想像できますか。

        -   律法学者も群衆もいるので、ガリラヤ地方ではないかと思われる。すると、他の弟子たちを、ガリラヤの村に残して、イエスが三人だけつれて、山に行ったのかもしれない。（ルカでは「翌日、一同が山を降りてくると」となっている。）

    -   \[DQ\] 律法学者と弟子たちは何を論じていたのでしょうか。

        -   イエスはどこへ行ってしまったのか。ユダヤ人のもとには戻ってこないのかと考えていたかもしれない。ほどんど、ユダヤ人の前に現れていない時期が続いていた。しかし、弟子たちを見つけて、議論をふっかけたのだろうか。

        -   汚れた霊を追い出す権威を授けられていた弟子たちも、何もできなかったので、単に、誹謗されていたのか。

    -   \[DQ\] イエスと一緒に行った、ペテロ、ヤコブ、ヨセフは、どのようなことを感じたでしょうか。

        -   イエスの栄光の姿、自分たちの見た幻とは非常に異なる、現実の喧騒だろうか。現実に引き戻されたことは確かだろう。

2.  どのような問題が起こっていますか。（15-18）

    -   15 群衆はみな、すぐイエスを見つけて、非常に驚き、駆け寄ってきて、あいさつをした。16 イエスが彼らに、「あなたがたは彼らと何を論じているのか」と尋ねられると、17 群衆のひとりが答えた、「先生、口をきけなくする霊につかれているわたしのむすこを、こちらに連れて参りました。18 霊がこのむすこにとりつきますと、どこででも彼を引き倒し、それから彼はあわを吹き、歯をくいしばり、からだをこわばらせてしまいます。それでお弟子たちに、この霊を追い出してくださるように願いましたが、できませんでした」。

    -   \[DQ\] 群衆は、なぜ非常に驚いたのでしょうか。律法学者たちが、弟子たちと論じ合っていたこともあわせて考えてみましょう。

        -   イエスは逃げていて戻ってこないのではないかと思っていたかもしれない。

        -   自分たちの問題を解決するために、奉仕されるイエスは、もういなくなったとおもっていたかもしれない。

    -   \[DQ\] この息子の状態はどのように描かれていますか。

        -   口をきけなくする霊につかれている息子を父親が連れてきた。

            -   症状：霊がこのむすこにとりつきますと、どこででも彼を引き倒し、それから彼はあわを吹き、歯をくいしばり、からだをこわばらせてしまいます。

        -   マタイではてんかん。ルカでは引き付け。

        -   癲癇（てんかん épilèpsy）：大脳の神経細胞が過剰に興奮することで発作症状を引き起こす慢性的な脳の疾患。 突然意識を失い、四肢をピクピクさせたり硬直させたりする発作、体の一部が勝手に動いたり、会話の途中に意識を失う発作などもあります。 年齢・性別・環境に関わらず発作は発症します。

    -   \[DQ\] 「それでお弟子たちに、この霊を追い出してくださるように願いましたが、できませんでした」からは、どのようなことが伝えられていますか。

        -   やっぱり、無理なのだろうかということだろうか。

        -   弟子たちが、汚れた霊を追い出すことが書かれている。

            -   6:12-13 12 そこで、彼らは出て行って、悔改めを宣べ伝え、13 多くの悪霊を追い出し、大ぜいの病人に油をぬっていやした。（θεραπεύω）

3.  イエスはどうしますか。（19-22）

    -   19 イエスは答えて言われた、「ああ、なんという不信仰な時代であろう。いつまで、わたしはあなたがたと一緒におられようか。いつまで、あなたがたに我慢ができようか。その子をわたしの所に連れてきなさい」。20 そこで人々は、その子をみもとに連れてきた。霊がイエスを見るや否や、その子をひきつけさせたので、子は地に倒れ、あわを吹きながらころげまわった。21 そこで、イエスが父親に「いつごろから、こんなになったのか」と尋ねられると、父親は答えた、「幼い時からです。22 霊はたびたび、この子を火の中、水の中に投げ入れて、殺そうとしました。しかしできますれば、わたしどもをあわれんでお助けください」。

    -   \[DQ\] 「ああ、なんという不信仰な時代であろう。いつまで、わたしはあなたがたと一緒におられようか。」は誰に対して言っていますか。イエスの関心事は何ですか。

        -   「あなたがた」とあるが、それに人々が対応しているところをみると、「人々」だろうか。それとも、弟子たちのことだろうか。時代と言っているので、課題の対応に関する人々の対応だろうか。

        -   何を不信仰と言っているのだろうか。

            -   魔術的な力に頼ることだろうか。

        -   まずは、だれかを批判するようなことはしていない。「不信仰な時代」ということで、残念に思っていることは確か。それぞれの人達が、それぞれに受け取っただろう。

    -   \[DQ\] イエスはなぜ「いつごろから、こんなになったのか」と尋ねたのでしょうか。

        -   丁寧に対応している。課題の正確な把握。

    -   \[DQ\] 父親のことばからは、どのようなことが感じられますか。

        -   20 そこで人々は、その子をみもとに連れてきた。霊がイエスを見るや否や、その子をひきつけさせたので、子は地に倒れ、あわを吹きながらころげまわった。21 そこで、イエスが父親に「いつごろから、こんなになったのか」と尋ねられると、父親は答えた、「幼い時からです。22 霊はたびたび、この子を火の中、水の中に投げ入れて、殺そうとしました。しかしできますれば、わたしどもをあわれんでお助けください」。

        -   起こっていることであたふたしている。そこに目を囚われている。

4.  父親とイエスの対話からどのようなことがわかりますか。（22-24）

    -   22 霊はたびたび、この子を火の中、水の中に投げ入れて、殺そうとしました。しかしできますれば、わたしどもをあわれんでお助けください」。23 イエスは彼に言われた、「もしできれば、と言うのか。信ずる者には、どんな事でもできる」。24 その子の父親はすぐ叫んで言った、「信じます。不信仰なわたしを、お助けください」。

    -   イエスは、父親の言葉にツッコミを入れかつ、上の不信仰な時代ともつながっており、印象的なことばとして、そこにいるものが伝えたのだろう。ペテロなどによる証言だろうか。史実性が高い。

    -   \[DQ\] 父親はなんといえばよかったのでしょうか。

        -   1:40 ひとりの重い皮膚病にかかった人が、イエスのところに願いにきて、ひざまずいて言った、「みこころでしたら、きよめていただけるのですが」。

        -   おそらく、そのような技術的なことを言っているのではない。

    -   \[DQ\] 憐れみを受けるのは、なにが鍵だと言っていますか。

        -   神様に信頼すること？ 神様に責任をなすりつけているのだろうか。

        -   なにかの因果なのだろうか。

    -   \[DQ\] イエスの、「信じるものにはどんなことでもできる」は何を伝えようとしているのでしょうか。本当になんでもできるのでしょうか。

        -   問題は何だったのでしょうか。弟子たちの不信仰、弟子たちが、イエスのような力を持っていなかったこと？ 父親の不信仰？ 神の国が近いことを見ようとすることだろうか。

        -   バークレイ：あなたの子供をいやすことは、わたしではなく、あなたにかかっている。

    -   \[DQ\] 「信じます。不信仰なわたしを、お助けください」。は、信じることと、信仰を持っていない自分とを表現しているのでしょうか。

        -   これがよけい、史実性を高めている。

5.  イエスはどうしますか、そしてどうなりますか。（25-27）

    -   25 イエスは群衆が駆け寄って来るのをごらんになって、けがれた霊をしかって言われた、「言うことも聞くこともさせない霊よ、わたしがおまえに命じる。この子から出て行け。二度と、はいって来るな」。26 すると霊は叫び声をあげ、激しく引きつけさせて出て行った。その子は死人のようになったので、多くの人は、死んだのだと言った。27 しかし、イエスが手を取って起されると、その子は立ち上がった。

    -   ここでも汚れた霊に対して叱っている。汚れた霊に対する権威を示し、かつ、二度と入ってくるなと命じている。

    -   \[DQ\] 弟子たちも、確信をもって、このように言えばよかったのでしょうか。

6.  弟子たちは、イエスにどのような質問をし、イエスはどう答えますか。（28,29）

    -   28 家にはいられたとき、弟子たちはひそかにお尋ねした、「わたしたちは、どうして霊を追い出せなかったのですか」。29 すると、イエスは言われた、「このたぐいは、祈によらなければ、どうしても追い出すことはできない」。

    -   \[DQ\] 祈ればよいのでしょうか。

    -   \[DQ\] イエスはなにを伝えているのでしょうか。

        -   バークレイ：あなたがたの生活は神にあまり近くない。

        -   マルコ6:7 また十二弟子を呼び寄せ、ふたりずつつかわすことにして、彼らにけがれた霊を制する権威を与え、

        -   マルコ6:13 多くの悪霊を追い出し、大ぜいの病人に油をぬっていやした（θεραπεύω）。

        -   注：断食が入っている写本もあるが、2:18-20 から重要視されていない。

7.  イエスは人々の「不信仰」に対して何を求めているのでしょうか。

    -   \[DQ\] 御心を求め続けることでしょうか。

        -   わからない。

    -   \[DQ\] この父親や、家族は、これから問題もなく、幸せに暮らしたのでしょうか。

        -   問題は、いくらでもあるだろう。

### メモ

-   汚れた霊につかれていると捉えるか、てんかんのような現代的に考えると、大脳の神経の病気と捉えるかの差もあるように見える。ただ、マルコでは一貫して、汚れた霊であるとし、イエスもそのように扱っているので、そのまま扱ったほうがよいように思われる。神様のはたらきを妨げるものだろうか。なぜ、その働きがあるのかの判断は難しいが、イエスの「不信仰」発言をどの程度拡大して考えてよいかは不明だが、イエスは、不信仰が問題だと言っているように見える。ただ、神様に任せればよいのだろうか。おそらく、そうではない。

-   このときに、癒やされればよいのかは、ひとつ重要な点のような気がする。問題は、いくらでも人生に起きるのだから。しかし、ここで、言っている信仰とは何かは、よくはわからない。

-   不信仰のやりとりから、弟子たちが癒せなかったことにたいして、イエスが怒っているのではないように見える。同時に、残された日々が短いことも、イエスは思っていることも確かだろう。

-   イエスのスーパーパワーで汚れた霊が追い出されたとは言っていない。この父親の信仰でもなさそうである。弟子たちも、祈っていれば、このひとの息子が癒やされたわけではないのだろう。非常に興味深い。

## 9:30-32 再び自分の死と復活を予告する

> 30 それから彼らはそこを立ち去り、ガリラヤをとおって行ったが、イエスは人に気づかれるのを好まれなかった。31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

### マタイ 17:22-23

> 22 彼らがガリラヤで集まっていた時、イエスは言われた、「人の子は人々の手にわたされ、23 彼らに殺され、そして三日目によみがえるであろう」。弟子たちは非常に心をいためた。

### ルカ 9:43b-45

> 43b みんなの者がイエスのしておられた数々の事を不思議に思っていると、弟子たちに言われた、44 「あなたがたはこの言葉を耳におさめて置きなさい。人の子は人々の手に渡されようとしている」。45 しかし、彼らはなんのことかわからなかった。それが彼らに隠されていて、悟ることができなかったのである。また彼らはそのことについて尋ねるのを恐れていた。

[マルコによる福音書9章30-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32.pdf)

[マルコによる福音書9章30-32節 福音書対照表（参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_30-32_extra.pdf)

### 問い

1.  背景を復習しましょう。

2.  彼らはどこへ向かっているのでしょうか。イエスについてどのように書かれていますか。（30）

3.  イエスは弟子たちに何を伝えていますか。（31）

4.  弟子たちについては、どう描かれていますか。（32）

5.  一回目（8:31）、三回目（10:33,34）と比較するとどんな事がわかりますか。

6.  イエスは、何を目指し、弟子たちには何を期待しているのでしょうか。

### 参照

-   マルコにおけるエルサレム

    -   1:5 そこで、ユダヤ全土とエルサレムの全住民とが、彼のもとにぞくぞくと出て行って、自分の罪を告白し、ヨルダン川でヨハネからバプテスマを受けた。

    -   3:8 エルサレムから、イドマヤから、更にヨルダンの向こうから、ツロ、シドンのあたりからも、おびただしい群衆が、そのなさっていることを聞いて、みもとにきた。

    -   3:22 また、エルサレムから下ってきた律法学者たちも、「彼はベルゼブルにとりつかれている」と言い、「悪霊どものかしらによって、悪霊どもを追い出しているのだ」とも言った。

    -   7:1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。

    -   10:32,33 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。

    -   11:1 さて、彼らがエルサレムに近づき、オリブの山に沿ったベテパゲ、ベタニヤの附近にきた時、イエスはふたりの弟子をつかわして言われた、

    -   11:11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。

    -   11:15 それから、彼らはエルサレムにきた。イエスは宮に入り、宮の庭で売り買いしていた人々を追い出しはじめ、両替人の台や、はとを売る者の腰掛をくつがえし、

    -   11:27 彼らはまたエルサレムにきた。そして、イエスが宮の内を歩いておられると、祭司長、律法学者、長老たちが、みもとにきて言った、

    -   15:41 彼らはイエスがガリラヤにおられたとき、そのあとに従って仕えた女たちであった。なおそのほか、イエスと共にエルサレムに上ってきた多くの女たちもいた。

-   イザヤ

    -   マルコ1:2,3 預言者イザヤの書に、／「見よ、わたしは使をあなたの先につかわし、／あなたの道を整えさせるであろう。3 荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と書いてあるように、

        -   イザヤ40:3 呼ばわる者の声がする、／「荒野に主の道を備え、／さばくに、われわれの神のために、／大路をまっすぐにせよ。

    -   マルコ7:6 イエスは言われた、「イザヤは、あなたがた偽善者について、こう書いているが、それは適切な預言である、／『この民は、口さきではわたしを敬うが、／その心はわたしから遠く離れている。

        -   イザヤ29:13 主は言われた、／「この民は口をもってわたしに近づき、／くちびるをもってわたしを敬うけれども、／その心はわたしから遠く離れ、／彼らのわたしをかしこみ恐れるのは、／そらで覚えた人の戒めによるのである。

    -   マタイ3:3 預言者イザヤによって、「荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』」／と言われたのは、この人のことである。(ルカ3:4 それは、預言者イザヤの言葉の書に書いてあるとおりである。すなわち／「荒野で呼ばわる者の声がする、／『主の道を備えよ、／その道筋をまっすぐにせよ』。ヨハネ1:23 彼は言った、「わたしは、預言者イザヤが言ったように、『主の道をまっすぐにせよと荒野で呼ばわる者の声』である」。)

    -   ルカ4:17 すると預言者イザヤの書が手渡されたので、その書を開いて、こう書いてある所を出された、

    -   マタイ4:14 これは預言者イザヤによって言われた言が、成就するためである。

    -   マタイ8:17 これは、預言者イザヤによって「彼は、わたしたちのわずらいを身に受け、わたしたちの病を負うた」と言われた言葉が成就するためである。

    -   マタイ12:17 これは預言者イザヤの言った言葉が、成就するためである、

    -   マタイ13:14 こうしてイザヤの言った預言が、彼らの上に成就したのである。『あなたがたは聞くには聞くが、／決して悟らない。見るには見るが、決して認めない。

    -   マタイ15:7 偽善者たちよ、イザヤがあなたがたについて、こういう適切な預言をしている、

    -   ヨハネ12:39 こういうわけで、彼らは信じることができなかった。イザヤはまた、こうも言った、

    -   ヨハネ12:41 イザヤがこう言ったのは、イエスの栄光を見たからであって、イエスのことを語ったのである。

-   死と復活の予告

    -   8:31-32a 31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32a しかもあからさまに、この事を話された。

    -   9:30-32 30 それから彼らはそこを立ち去り、ガリラヤをとおって行ったが、イエスは人に気づかれるのを好まれなかった。31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

    -   10:32-34 32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。

### 記録

-   日時：2024年5月2日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）4名

### 問いについて

1.  背景を復習しましょう。

    -   8:27-30 ペトロ、イエスがメシアであると告白する

    -   8:31-38; 9:1 イエス、死と復活を予告する

    -   9:2-13 イエスの姿が変わる

    -   9:14-29 汚れた霊に取りつかれた子を癒やす

    -   ガリラヤ以外の土地を周り、ガリラヤに帰ることを躊躇された時期に、イエスの決断、イエスの問に対する、ペテロの信仰告白、イエスの受難告知、山上の変貌を経て、山の下で待っている弟子たちが癒されなかった、不信仰を嘆き、汚れた霊につかれた息子を癒やす。その後での二回目の受難告知の記事である。

    -   受難告知に対して、メシヤだと信仰告白したペテロもイエスをいさめ、山上でイエスの栄光の姿への変貌を目撃したでしたちも、わからないことばかり。「9 一同が山を下って来るとき、イエスは『人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない』と、彼らに命じられた。10 彼らはこの言葉を心にとめ、死人の中からよみがえるとはどういうことかと、互に論じ合った。」

2.  彼らはどこへ向かっているのでしょうか。イエスについてどのように書かれていますか。（30）

    -   30 それから彼らはそこを立ち去り、ガリラヤをとおって行ったが、イエスは人に気づかれるのを好まれなかった。

    -   ここに至るまで：8:37 ピリポ・カイザリア、9:2 山上、

    -   9:14 さて、彼らがほかの弟子たちの所にきて見ると、大ぜいの群衆が弟子たちを取り囲み、そして律法学者たちが彼らと論じ合っていた。

    -   ガリラヤを通って、おそらく、エルサレムに向かっている。

        -   10:32,33 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。

    -   \[DQ\] なぜイエスは、旅行の行程を秘密にしたいのでしょうか。

        -   \[Q\] 誰に「気づかれるのを好まれなかった」のでしょうか。

            -   「人」とあるが、弟子たち以外だろうか。パリサイ派、律法学者、群衆も含めて。

    -   \[DQ\] 人との交渉を避けられたのでしょうか。

        -   ガリラヤを通っていかれたとあり、イエスとしては、おそらく、最後のガリラヤだと考えていただろう。これまで、どこに行っていたのか、これから、どこに行くのか、どうするのかといった議論をしたくなかったのか。では、人々の必要には答えたくなかったのだろうか。（奉仕については）

            -   このあとは、イエスは弟子たちを教え、人々も教えるが（10:1-16 離婚について教える、10:13-16 子どもを祝福する、17-22 金持ちの男）癒やしについては、10:46-52 盲人バルティマイを癒やす の記事のみ。

        -   理由は、次の節に秘められている。31 それは、... と言っておられたからである。

            -   受難ことは、弟子たちには、話しているが、人々には、秘密にしている。

            -   \[DQ\] 受難については、弟子たちに、話してはいけないと命じているでしょうか。

3.  イエスは弟子たちに何を伝えていますか。（31）

    -   31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。

    -   ① 人々の手にわたされ、② 殺され、③ 三日の後によみがえる

    -   \[DQ\] イエスが死と復活について語ったのは二度目ですが、一度目と比較して見ましょう。

        -   8:31-32a 31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32a しかもあからさまに、この事を話された。

        -   「多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ」が欠けている。

        -   「人々の手にわたされ」が加わっている。

            -   わたされ（παραδίδωμι: to give into the hands (of another)）「誰かに」と「誰かによって」または「誰から」が背後にある。

    -   \[DQ\] 「誰に」の部分はどんな人が想定されているのでしょうか。

        -   8:31b 必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ

        -   直接的には、これらの民の指導者が想定されているだろうが、群衆・人々をも含んでいるのではないだろうか。

    -   \[DQ\] 「誰によって」の部分は、どのような人が想定されているのでしょうか。

        -   ユダ？

            -   ヨハネ6:66-71 それ以来、多くの弟子たちは去っていって、もはやイエスと行動を共にしなかった。67 そこでイエスは十二弟子に言われた、「あなたがたも去ろうとするのか」。68 シモン・ペテロが答えた、「主よ、わたしたちは、だれのところに行きましょう。永遠の命の言をもっているのはあなたです。69 わたしたちは、あなたが神の聖者であることを信じ、また知っています」。70 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である」。71 これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。

    -   \[DQ\] 前回と今回はそれぞれどのような時だったのでしょうか。

        -   前回はイエスの問に対する、ペテロの告白のあと。

    -   \[DQ\] イエスが教えたかったことは何なのでしょうか。

        -   前回：8:34 それから群衆を弟子たちと一緒に呼び寄せて、彼らに言われた、「だれでもわたしについてきたいと思うなら、自分を捨て、自分の十字架を負うて、わたしに従ってきなさい。35 自分の命を救おうと思う者はそれを失い、わたしのため、また福音のために、自分の命を失う者は、それを救うであろう。36 人が全世界をもうけても、自分の命を損したら、なんの得になろうか。37 また、人はどんな代価を払って、その命を買いもどすことができようか。38 邪悪で罪深いこの時代にあって、わたしとわたしの言葉とを恥じる者に対しては、人の子もまた、父の栄光のうちに聖なる御使たちと共に来るときに、その者を恥じるであろう」。

4.  弟子たちについては、どう描かれていますか。（32）

    -   32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

    -   \[DQ\] 弟子たちはイエスの教えにどのように反応していますか。

    -   \[DQ\] なにを悟っていなかったのでしょうか。

        -   受難の意味だろうか。引き渡されるの具体的な内容までは、頭が回らなかったように思われる。ユダは、気づいていたのだろうか。

        -   受難の意味だとすると、イエスは明確に理解していたのだろうか。

    -   \[DQ\] なにを尋ねるのを恐れていたのでしょうか。

        -   死とよみがえりは何を意味しているかということだろうか。想像すらできないことは、当然であるように見える。

        -   イエスは明確に理解していたのだろうか。

    -   \[DQ\] イエスはなにのために、弟子たちに伝えて（教えて）いたのでしょうか。（6で考察）

        -   神様に信頼していたことは確かだろう。これも、神の国は近いことの一つだったのか。

5.  一回目（8:31）、三回目（10:33,34）と比較するとどんな事がわかりますか。（参考）

    -   一回目は、受難、二回目は、人の手に引き渡されること、三回目は、エルサレムで起こることと、祭司長、律法学者たちの手に渡され、彼らが死刑を宣告し、異邦人に引き渡され、あざけり、つばきをかけ、ついに殺してしまうとかなり細かく書かれている。

    -   毎回「三日の後によみがえる」ことが伝えられている。

6.  イエスは、何を目指し、弟子たちには何を期待しているのでしょうか。

    -   \[DQ\] イエスは、受難・受苦、人々の手に引き渡され、さらに、死とよみがえりの意味について、十分理解していたのだろうか。

    -   \[DQ\] 死とよみがえりについては、毎回語られているが、それは、イエスはどのように理解していたのだろうか。

    -   \[DQ\] わたしたちが、イエスにこのように伝えられたとき、どのように理解するか、悟ることができるか、考えてみましょう。

        -   それほど、簡単ではない。イエスが、この道を選んだ、または、ここに主のみこころがあると確信したことは確かだろうが、どのように理解していたかは不明。

        -   しかし、教えたということは、弟子たちになにかを託していることは確か。

### メモ

-   イエスから、もっと、この受苦・死・よみがえりについて聞いてほしかった。これだけ、教えられたということは、この事を通して、イエスが託した事があるのだろう。単に、未来を予知できる能力があると伝えたかったわけではないと思う。

-   あらかじめ伝えられていることによって、短い期間で、立ち直ることができたことは確かだろう。五旬節は、50日後、または7週間後だから、その間に、イエスの死と復活を消化できたと聖書は証言している。

-   イエスについていくもの（8:34）に委ねたということだろう。それは、イエスのように歩む者である。正直に行って、イエスの十字架上での死による贖罪を宣べつたえるよりは、もっと広い意味をもつと思われる。

## 9:33-37 いちばん偉い者

> 33 それから彼らはカペナウムにきた。そして家におられるとき、イエスは弟子たちに尋ねられた、「あなたがたは途中で何を論じていたのか」。34 彼らは黙っていた。それは途中で、だれが一ばん偉いかと、互に論じ合っていたからである。35 そこで、イエスはすわって十二弟子を呼び、そして言われた、「だれでも一ばん先になろうと思うならば、一ばんあとになり、みんなに仕える者とならねばならない」。36 そして、ひとりの幼な子をとりあげて、彼らのまん中に立たせ、それを抱いて言われた。37 「だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。

### マタイ 18:1-5

> 1 そのとき、弟子たちがイエスのもとにきて言った、「いったい、天国ではだれがいちばん偉いのですか」。2 すると、イエスは幼な子を呼び寄せ、彼らのまん中に立たせて言われた、3 「よく聞きなさい。心をいれかえて幼な子のようにならなければ、天国にはいることはできないであろう。4 この幼な子のように自分を低くする者が、天国でいちばん偉いのである。5 また、だれでも、このようなひとりの幼な子を、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。

### ルカ 9:46-48

> 46 弟子たちの間に、彼らのうちでだれがいちばん偉いだろうかということで、議論がはじまった。47 イエスは彼らの心の思いを見抜き、ひとりの幼な子を取りあげて自分のそばに立たせ、彼らに言われた、48 「だれでもこの幼な子をわたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そしてわたしを受けいれる者は、わたしをおつかわしになったかたを受けいれるのである。あなたがたみんなの中でいちばん小さい者こそ、大きいのである」。

[マルコによる福音書9章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_33-37.pdf)

### 問い

1.  どこにいますか。どのような状況でこの会話が始まりますか。（33a）

2.  弟子たちは、なにについて話していますか。（33b, 34）

3.  イエスは、どのように答えていますか。（35）

4.  イエスは、幼子を呼び寄せてどのように教えていますか。（36,37）

5.  弟子たちの議論と、幼子を受け入れることとはどのように関係しているのでしょうか。

6.  イエスは弟子たちになにを教えているのでしょうか。

### 参照

-   10:13-16 13 イエスにさわっていただくために、人々が幼な子らをみもとに連れてきた。ところが、弟子たちは彼らをたしなめた。14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。16 そして彼らを抱き、手をその上において祝福された。（マタイ19:13-15, ルカ18:15-17）

-   仕えるもの（διάκονος）one who executes the commands of another, esp. of a master, a servant, attendant, minister；a) the servant of a king, b) a deacon, one who, by virtue of the office assigned to him by the church, cares for the poor and has charge of and distributes the money collected for their use, c) a waiter, one who serves food and drink

    -   διώκω: 1) to make to run or flee, put to flight, drive away, 2) to run swiftly in order to catch a person or thing, to run after, 3) in any way whatever to harass, trouble, molest one, 4) without the idea of hostility, to run after, follow after: someone, 5) metaph., to pursue

-   マタイではこの記事の直前に「神殿税を納める」記事が挿入されている。17:24-27

    -   24 彼らがカペナウムにきたとき、宮の納入金を集める人たちがペテロのところにきて言った、「あなたがたの先生は宮の納入金を納めないのか」。25 ペテロは「納めておられます」と言った。そして彼が家にはいると、イエスから先に話しかけて言われた、「シモン、あなたはどう思うか。この世の王たちは税や貢をだれから取るのか。自分の子からか、それとも、ほかの人たちからか」。26 ペテロが「ほかの人たちからです」と答えると、イエスは言われた、「それでは、子は納めなくてもよいわけである。27 しかし、彼らをつまずかせないために、海に行って、つり針をたれなさい。そして最初につれた魚をとって、その口をあけると、銀貨一枚が見つかるであろう。それをとり出して、わたしとあなたのために納めなさい」。
    -   宮の納入金を集める人たちを躓かせないため？

-   九十九匹の羊

    -   マタイ19:12,13 （直後）あなたがたはどう思うか。ある人に百匹の羊があり、その中の一匹が迷い出たとすれば、九十九匹を山に残しておいて、その迷い出ている羊を捜しに出かけないであろうか。13 もしそれを見つけたなら、よく聞きなさい、迷わないでいる九十九匹のためよりも、むしろその一匹のために喜ぶであろう。

    -   ルカ15:4 「あなたがたのうちに、百匹の羊を持っている者がいたとする。その一匹がいなくなったら、九十九匹を野原に残しておいて、いなくなった一匹を見つけるまでは捜し歩かないであろうか。

-   10:35-45 ヤコブとヨハネの願い

    -   35 さて、ゼベダイの子ヤコブとヨハネとがイエスのもとにきて言った、「先生、わたしたちがお頼みすることは、なんでもかなえてくださるようにお願いします」。36 イエスは彼らに「何をしてほしいと、願うのか」と言われた。37 すると彼らは言った、「栄光をお受けになるとき、ひとりをあなたの右に、ひとりを左にすわるようにしてください」。38 イエスは言われた、「あなたがたは自分が何を求めているのか、わかっていない。あなたがたは、わたしが飲む杯を飲み、わたしが受けるバプテスマを受けることができるか」。39 彼らは「できます」と答えた。するとイエスは言われた、「あなたがたは、わたしが飲む杯を飲み、わたしが受けるバプテスマを受けるであろう。40 しかし、わたしの右、左にすわらせることは、わたしのすることではなく、ただ備えられている人々だけに許されることである」。41 十人の者はこれを聞いて、ヤコブとヨハネとのことで憤慨し出した。42 そこで、イエスは彼らを呼び寄せて言われた、「あなたがたの知っているとおり、異邦人の支配者と見られている人々は、その民を治め、また偉い人たちは、その民の上に権力をふるっている。43 しかし、あなたがたの間では、そうであってはならない。かえって、あなたがたの間で偉くなりたいと思う者は、仕える人となり、44 あなたがたの間でかしらになりたいと思う者は、すべての人の僕とならねばならない。45 人の子がきたのも、仕えられるためではなく、仕えるためであり、また多くの人のあがないとして、自分の命を与えるためである」。

-   ローマ14:15 もし食物のゆえに兄弟を苦しめるなら、あなたは、もはや愛によって歩いているのではない。あなたの食物によって、兄弟を滅ぼしてはならない。キリストは彼のためにも、死なれたのである。

-   マタイ25:40 すると、王は答えて言うであろう、『あなたがたによく言っておく。わたしの兄弟であるこれらの最も小さい者のひとりにしたのは、すなわち、わたしにしたのである』。

### 記録

-   日時：2024年5月9日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）2名

### 問いについて

1.  どこにいますか。どのような状況でこの会話が始まりますか。（33a）

    -   33 それから彼らはカペナウムにきた。そして家におられるとき、イエスは弟子たちに尋ねられた、「あなたがたは途中で何を論じていたのか」。

    -   カペナウムの家

        -   マルコ1:29 それから（カペナウムの（21））会堂を出るとすぐ、ヤコブとヨハネとを連れて、シモンとアンデレとの家にはいって行かれた。

        -   マルコ2:1 幾日かたって、イエスがまたカペナウムにお帰りになったとき、家におられるといううわさが立ったので、

        -   マルコ3:19 それからイスカリオテのユダ。このユダがイエスを裏切ったのである。イエスが家にはいられると、

        -   マルコ7:17 イエスが群衆を離れて家にはいられると、弟子たちはこの譬について尋ねた。

        -   マルコ9:28 家にはいられたとき、弟子たちはひそかにお尋ねした、「わたしたちは、どうして霊を追い出せなかったのですか」。

        -   マルコ10:10 家にはいられたとき、弟子たちはひそかにお尋ねした、「わたしたちは、どうして霊を追い出せなかったのですか」。

    -   論じる（33）διαλογίζομαι: to bring together different reasons, to reckon up the reasons, to reason, revolve in one's mind, deliberate (34) διαλέγομαι: i) to think different things with one's self, mingle thought with thought, ii) to converse, discourse with one, argue, discuss

        -   2:6-9 ところが、そこに幾人かの律法学者がすわっていて、心の中で論じた、7 「この人は、なぜあんなことを言うのか。それは神をけがすことだ。神ひとりのほかに、だれが罪をゆるすことができるか」。8 イエスは、彼らが内心このように論じているのを、自分の心ですぐ見ぬいて、「なぜ、あなたがたは心の中でそんなことを論じているのか。9 中風の者に、あなたの罪はゆるされた、と言うのと、起きよ、床を取りあげて歩け、と言うのと、どちらがたやすいか。

        -   8:15,17 そのとき、イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。16 弟子たちは、これを自分たちがパンを持っていないためであろうと、互に論じ合った。17 イエスはそれと知って、彼らに言われた、「なぜ、パンがないからだと論じ合っているのか。まだわからないのか、悟らないのか。あなたがたの心は鈍くなっているのか。18 目があっても見えないのか。耳があっても聞えないのか。また思い出さないのか。

        -   9:33 それから彼らはカペナウムにきた。そして家におられるとき、イエスは弟子たちに尋ねられた、「あなたがたは途中で何を論じていたのか」。

2.  弟子たちは、なにについて話していますか。（33b, 34）

    -   33 それから彼らはカペナウムにきた。そして家におられるとき、イエスは弟子たちに尋ねられた、「あなたがたは途中で何を論じていたのか」。34 彼らは黙っていた。それは途中で、だれが一ばん偉いかと、互に論じ合っていたからである。

    -   \[DQ\] 「論じ合っていた」とはどのような状態を表現しているのでしょうか。

        -   おそらく、評価が異なっていたのだろう。イエスは、その評価の仕方について述べることになる。

    -   \[DQ\] 弟子たちは、なぜ、黙っていたのでしょうか。

        -   イエスの様子と、「人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえる」という覚悟は感じ、そのことと、だれがいちばん偉いかはそぐわないことは理解できた。

        -   イエスが望むことではないことは理解していた。

    -   \[DQ\] イエスの心を占めていたことと、弟子たちの心を占めていたことをそれぞれまとめてみましょう。

    -   \[DQ\] あなたがイエスなら、どうしますか。

        -   親の心子知らずだなと怒り出しそう。

        -   イエスは、まず、すわって、二段階で話をしている。

    -   ヤコブとヨハネ（その母）10:35-45 ヤコブとヨハネの願い（マタイ 20:20-28）

3.  イエスは、どのように答えていますか。（35）

    -   35 そこで、イエスはすわって十二弟子を呼び、そして言われた、「だれでも一ばん先になろうと思うならば、一ばんあとになり、みんなに仕える者とならねばならない」。

    -   \[DQ\] イエスがすわって十二弟子を呼んだとありますが、なぜ、そのようにしたのでしょうか。

        -   瞬発的に、怒ったりはしていない。弟子たちの興味に、本質論で答えている。

    -   \[DQ\] 偉さについてどんなことが教えられていますか。

        -   「だれでも一ばん先になろうと思うならば、一ばんあとになり、みんなに仕える者とならねばならない」

        -   弟子たちは、すぐに理解できたでしょうか。

        -   弟子たちは、どのように考えていたのでしょうか。

    -   \[DQ\] 「みんな」とは、誰のことでしょうか。（聖書協会共同訳では「すべてのひと」）

    -   \[DQ\] いちばん先になろうと思うこと自体は、悪いことではないとうことでしょうか。

        -   いちばん先になることが目的になってしまうことに問題があるのでは。

    -   \[DQ\] 「いちばんあとになる」とか「仕えるものになる」とはどのようなことを意味しているのでしょうか。

        -   仕えるもの（διάκονος）one who executes the commands of another, esp. of a master, a servant, attendant, minister

        -   先頭をあるくことではないのだろう。

            -   10:32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、

            -   イエスは、通常は、先頭を歩いてはいなかったようである。

            -   あとから付いていくと、様子がわかり、仕えることができる。先頭を歩く人も必要だが、そのひとは様子はわからない。

        -   イエスが目指したこと、神の子として目指したことだろうか。

4.  イエスは、幼子を呼び寄せてどのように教えていますか。（36,37）

    -   36 そして、ひとりの幼な子をとりあげて、彼らのまん中に立たせ、それを抱いて言われた。37 「だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。

    -   \[DQ\] どのような様子が描かれていますか。

        -   ①ひとりの幼な子をとりあげて、②彼らのまん中に立たせ、③それを抱いて（ἐναγκαλίζομαι: to take into one's arms, embrace）言われた。

        -   「抱いて」とも書かれている。目撃証言として、やさしいイエスの姿が活写されている。

    -   \[DQ\] こどもとは、どのようなものだとされていたのでしょうか。

        -   おとなより劣っている。不完全なもの。役に立たないもの。\[[参考](https://icu-hsuzuki.github.io/biblestudy/aboutmark.html#sec-こども)\]

        -   同時に、何があっても、親にとっては、大切な存在であると認識しているのでは。

    -   \[DQ\] なぜ「わたしの名のためにこのような一人の子供を受け入れる」ことにそれほどの価値があるのでしょうか。

    -   \[DQ\] イエスはどのような子どもだったのでしょうか。

        -   すくなくとも、父親に愛されたこどもではなかったのではないか。しかし、天の神様からは、あなたはわたしの愛する子ということばを二回聞き、そのことを意識していただろう。

            -   1:11 すると天から声があった、「あなたはわたしの愛する子、わたしの心にかなう者である」。

            -   9:7 すると、雲がわき起って彼らをおおった。そして、その雲の中から声があった、「これはわたしの愛する子である。これに聞け」。

        -   イエスにとっては、神様のみこころを行うものが、神の子。きょうだい。家族。とはいえ、神様のみこころを知り、完璧におこなっているとの確信はなかったのではないだろうか。そのいみで、イエスは、神の子、幼子だったのだろう。そのイエスが、神様からの「あなたはわたしの愛する子」との声をうけとっている。それをもって、「わたしの名のためにこのような一人の子供を受け入れるものは、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。と伝えている。

            -   3:35 神のみこころを行う者はだれでも、わたしの兄弟、また姉妹、また母なのである」。

    -   \[DQ\] マタイでは、「よく聞きなさい。心をいれかえて幼な子のようにならなければ、天国にはいることはできないであろう。4 この幼な子のように自分を低くする者が、天国でいちばん偉いのである。」とありますが、このことは何を伝えているのでしょうか。

5.  弟子たちの議論と、幼子を受け入れることとはどのように関係しているのでしょうか。

    -   \[DQ\]「イエスの名のゆえに」受け入れるとはどういうことでしょうか。

        -   たいせつなイエス様のたいせつなものをたいせつにすること。

    -   \[DQ\] 最も小さいものが最も偉い（大きい）ものとはどういうことでしょうか。

    -   \[DQ\] イエスは、なぜ、幼子を受け入れることを大切にしたのでしょうか。

        -   弟子たちが、考える機会にはなったろう。

6.  イエスは弟子たちになにを教えているのでしょうか。

    -   \[DQ\] だれがいちばん偉いか、「一ばん先になろうと思う」こととは、どのように関係しているのでしょうか。

    -   \[DQ\] 弟子たちは、理解できたのだろうか。

    -   \[DQ\] だれが、偉いかではなく、偉いとはどういうことか。

### メモ

-   弟子たちをおしえることを大切にしていたことは読み取ることができる。

-   人に、神様に自分が評価されることを考えるなら、なにがその方にとってたいせつなのかを考えるべき。すくなくとも、自分を偉いと認めることをたいせつにしてはいないはず。

-   イエスは、まず、直接的な応答をされ、さらに本質的なことを教えられる。この場合はどうだろうか。自分が偉いかどうかではなく、どうしたら、神様の御心を生きることができるかに注力することだろうか。つまり、神様は何を大切にされ、神様が大切にしておられるのはどのようなひとかを考えると、幼子を受け入れることだろうか。それは、イエスの象徴でもあるのかもしれないが、そこで止まってしまっては行けないのだろう。

-   未熟さからの不適切なことを議論することについて、嘆いたり、怒ったりではなく、その機会を捉えて、教えている。しかし、弟子たちは、理解できたのだろうか。

-   イエスの神様像は、仕えてくださる方なのだろうか。

-   弟子たちも、イエスが、たいせつにされていることをだんだんと理解していったのではないだろうか。

-   こどもをたいせつにすることは、当時は、それほど一般的ではなかったのだろう。名家の子女教育などは別として。しかし、イエスは、こどもをたいせつにしている。これは、おそらく、著しい特徴だろう。だれがいちばん偉いかの問に対しても、こどもと立てている。たとえばではない。パウロとはかなり異なるように見える。福音宣教者が偉い、聖書を教えるものが偉い、慈善事業をするものが偉いとは言わない。もっと本質的なものをこどもを受け入れることに見出し、それを教えておられるのだろう。自らが、こどもであることも、おそらく、認識していた。それは、みこころを十分知っているわけではないということではないだろうか。それでも、神様が、これはわたしの愛する子と言ってくださる。そのような関係をたいせつにすることが、ここで伝えられているのではないだろうか。福音の本質が、ここにあるように思う。

## 9:38-41 逆らわない者は味方

> 38 ヨハネがイエスに言った、「先生、わたしたちについてこない者が、あなたの名を使って悪霊を追い出しているのを見ましたが、その人はわたしたちについてこなかったので、やめさせました」。39 イエスは言われた、「やめさせないがよい。だれでもわたしの名で力あるわざを行いながら、すぐそのあとで、わたしをそしることはできない。40 わたしたちに反対しない者は、わたしたちの味方である。41 だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。

### ルカ 9:49-50

> 49 するとヨハネが答えて言った、「先生、わたしたちはある人があなたの名を使って悪霊を追い出しているのを見ましたが、その人はわたしたちの仲間でないので、やめさせました」。50 イエスは彼に言われた、「やめさせないがよい。あなたがたに反対しない者は、あなたがたの味方なのである」。

[マルコによる福音書9章38-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41.pdf)

[マルコによる福音書9章38-41節 福音書対照表（ルカ参照付）](https://icu-hsuzuki.github.io/science/bible/docs/mark9_38-41_extra.pdf)

### 問い

1.  どのような背景があるのでしょうか。ルカ9:49 も参考にしましょう。

2.  ヨハネは、どのようなことをイエスに伝えていますか。（38）

3.  イエスはどのように答えますか。（39,40）

4.  イエスはさらにどのようなことを伝えていますか。（41）

5.  ルカ9:51-56 からはどのようなことがわかりますか。

6.  イエスはどのようなことを教えているのでしょうか。

### 参照

-   ルカでは別のエピソードが続く

    -   9:51-56 さて、イエスが天に上げられる日が近づいたので、エルサレムへ行こうと決意して、その方へ顔をむけられ、52 自分に先立って使者たちをおつかわしになった。そして彼らがサマリヤ人の村へはいって行き、イエスのために準備をしようとしたところ、53 村人は、エルサレムへむかって進んで行かれるというので、イエスを歓迎しようとはしなかった。54 弟子のヤコブとヨハネとはそれを見て言った、「主よ、いかがでしょう。彼らを焼き払ってしまうように、天から火をよび求めましょうか」。55 イエスは振りかえって、彼らをおしかりになった。56 そして一同はほかの村へ行った。

-   寛容（口語訳）

    -   エレミヤ15:15 主よ、あなたは知っておられます。わたしを覚え、わたしを顧みてください。わたしを迫害する者に、あだを返し、／あなたの寛容によって、／わたしを取り去らないでください。わたしがあなたのために、／はずかしめを受けるのを知ってください。

    -   ローマ2:4 それとも、神の慈愛があなたを悔改めに導くことも知らないで、その慈愛と忍耐と寛容との富を軽んじるのか。

    -   ローマ9:22 もし、神が怒りをあらわし、かつ、ご自身の力を知らせようと思われつつも、滅びることになっている怒りの器を、大いなる寛容をもって忍ばれたとすれば、

    -   コリント前書13:4 愛は寛容であり、愛は情深い。また、ねたむことをしない。愛は高ぶらない、誇らない。

    -   コリント後書6:6 真実と知識と寛容と、慈愛と聖霊と偽りのない愛と、

    -   ガラテヤ5:22 しかし、御霊の実は、愛、喜び、平和、寛容、慈愛、善意、忠実、

    -   エペソ4:2 できる限り謙虚で、かつ柔和であり、**寛容**を示し、愛をもって互に忍びあい、

    -   ピリピ4:5 あなたがたの寛容を、みんなの人に示しなさい。主は近い。

    -   コロサイ3:12 だから、あなたがたは、神に選ばれた者、聖なる、愛されている者であるから、あわれみの心、慈愛、謙そん、柔和、寛容を身に着けなさい。

    -   テサロニケ前書5:14 兄弟たちよ。あなたがたにお勧めする。怠惰な者を戒め、小心な者を励まし、弱い者を助け、すべての人に対して寛容でありなさい。

    -   テモテ前書1:16 しかし、わたしがあわれみをこうむったのは、キリスト・イエスが、まずわたしに対して限りない寛容を示し、そして、わたしが今後、彼を信じて永遠のいのちを受ける者の模範となるためである。

    -   テモテ前書3:3 酒を好まず、乱暴でなく、寛容であって、人と争わず、金に淡泊で、

    -   テモテ後書3:10 しかしあなたは、わたしの教、歩み、こころざし、信仰、寛容、愛、忍耐、

    -   テモテ後書4:2 御言を宣べ伝えなさい。時が良くても悪くても、それを励み、あくまでも寛容な心でよく教えて、責め、戒め、勧めなさい。

    -   テトス3:2 だれをもそしらず、争わず、寛容であって、すべての人に対してどこまでも柔和な態度を示すべきことを、思い出させなさい。

    -   ヤコブ3:17 しかし上からの知恵は、第一に清く、次に平和、寛容、温順であり、あわれみと良い実とに満ち、かたより見ず、偽りがない。

    -   ペテロ前書2:18 僕たる者よ。心からのおそれをもって、主人に仕えなさい。善良で寛容な主人だけにでなく、気むずかしい主人にも、そうしなさい。

    -   ペテロ前書3:20 これらの霊というのは、むかしノアの箱舟が造られていた間、神が寛容をもって待っておられたのに従わなかった者どものことである。その箱舟に乗り込み、水を経て救われたのは、わずかに八名だけであった。

    -   ペテロ後書3:15 また、わたしたちの主の寛容は救のためであると思いなさい。このことは、わたしたちの愛する兄弟パウロが、彼に与えられた知恵によって、あなたがたに書きおくったとおりである。

-   寛容について：ウイリアム・バークレイ「マルコ福音書」

    -   ウイリアム・ペン（1644-1718 クエーカー）：汝が理解できないものを軽蔑し、また反対するなかれ

    -   キングズリ・ウイリアムズ訳ユダ10：これらの人々は彼らの理解しないことをののしる（聖書協会共同訳：しかし、この人々は自分が知りもしないことをそしり、また、分別のない動物のように、ただ本能的な知識にあやまられて、自らの滅亡を招いている。）

    -   テニソン：神やご自身を多くの方法で成就される。

    -   セルバンテス：神は彼の民を天国に運ぶ多くの路を持ちたもう

    -   ジョン・モーリー（1838-1923）：寛容は真理のあらゆる可能性に対する尊敬を意味する。真理は様々の家に住み、多彩な衣服を身にまとい、種々の聞き慣れない言葉で語るのを認めることを意味する。それは機械的な形式、公認の慣例、社会的勢力に対して、内在する良心の自由を率直に尊敬することである。それは、慈愛が信仰や希望よりも大きいことを意味する。

    -   ヴォルテール（1694-1778）：わたしはあなたのいったことは大嫌いだ。しかし、わたしはそういうあなたの権利のためなら、死んでもよい。

    -   チャルマーズ博士（17C スコットランド）：クリスチャンの良さを生み出す手段としての教会でなければ、いったい誰が教会に関心を示すだろうか。

    -   誰でもその指輪をはめると、その性質がやさしく誠実になり、すべての人々に愛された。ほかにふたつ作られこどもたちに贈った。どれが本物か判定を任された裁判官は「わたしにはどれが魔法の指輪かわからない。しかし、あなたが、それを証明できる。もし、本当の指輪が、それをはめる者の正確にやさしさを与えることが真実ならば、その人の善良なる生活によって、わたしもこの町にいる他の人々も本当の指輪をはめている人を見分けることができるだろう。だから、それぞれ自分の方法でやりなさい。親切、誠実、勇敢、正確でありなさい。これらのことを行った人が本当の指輪の持ち主なのだ。」

    -   彼はわたしを締め出す円を描いた。反逆者、異端者、あざける事柄。しかし愛とわたしは機知を持って勝ちを得た。われわれは彼を包み込む円を描いた。

-   マタイ12:30 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。

    -   ベルゼブル論争（マルコ3:20-30、マタイ12:22-32、ルカ12:10）\[[参照](https://icu-hsuzuki.github.io/biblestudy/markdq.html#ベルゼブル論争)\]

    -   ルカ11:40 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。

    -   マルコ3:28-29 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。29 しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。

### 記録

-   日時：2024年5月16日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）2名

### 問いについて

1.  どのような背景があるのでしょうか。ルカ9:49 も参考にしましょう。

    -   49a するとヨハネが答えて言った、（聖書協会共同訳：ヨハネが答えて言った。）

    -   \[DQ\] （特にルカでは、）前の話とつながっているように、描かれていますが、もし、つながっているとすると、ヨハネは、イエスのどのような言葉に反応したのでしょうか。

        -   イエスの名に関係しているのかもしれない。

            -   38b あなたの名を使って悪霊を追い出しているのを見ました

            -   \[Q\] この行為によって、受け入れる人がいるかもしれないということだろうか。

        -   もしかすると、自分はこんなことをしたという偉さに関係しているのかもしれない。

        -   イエスを受け入れるという言葉に反応したのだろうか。十分には理解しづらい。

            -   37 「だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。

2.  ヨハネは、どのようなことをイエスに伝えていますか。（38）

    -   38 ヨハネがイエスに言った、「先生、わたしたちについてこない者が、あなたの名を使って悪霊を追い出しているのを見ましたが、その人はわたしたちについてこなかったので、やめさせました」。

    -   \[参考\] ルカ9:49 するとヨハネが答えて言った、「先生、わたしたちはある人があなたの名を使って悪霊を追い出しているのを見ましたが、その人はわたしたちの仲間でないので、やめさせました」。Ἀποκριθεὶς δὲ ὁ Ἰωάννης εἶπεν Ἐπιστάτα εἴδομέν τινα ἐπὶ τῷ ὀνόματίσου ἐκβάλλοντα τά δαιμόνια καὶ ἐκωλύσαμεν αὐτὸν ὅτι οὐκ ἀκολουθεῖ μεθ᾽ἡμῶν

        -   仲間ではない ὅτι οὐκ ἀκολουθεῖ (ἀκολουθέω: i) to follow one who precedes, join him as his attendant, accompany him, ii) to join one as a disciple, become or be his disciple, 1:18, 2:14,15, 3:7, 5:24, 6:1, 8:34, 9:38, 10:21, 28, 32, 52, 11:9, 14:13, 51, 54, 15:41) μεθ᾽ἡμῶν

    -   \[DQ\] なぜ、イエスの名を使って悪霊を追い出すものが登場したのでしょうか。

        -   より有力な名前に抵抗できないと考えられていた。

        -   悪霊（汚れた霊）を追い出すことがいちばん人々が印象的だったことなのだろう。

        -   イエスには従えないが、その力には興味があったのかもしれない。

    -   参考：使徒19:13-17 そこで、ユダヤ人のまじない師で、遍歴している者たちが、悪霊につかれている者にむかって、主イエスの名をとなえ、「パウロの宣べ伝えているイエスによって命じる。出て行け」と、ためしに言ってみた。14 ユダヤの祭司長スケワという者の七人のむすこたちも、そんなことをしていた。15 すると悪霊がこれに対して言った、「イエスなら自分は知っている。パウロもわかっている。だが、おまえたちは、いったい何者だ」。16 そして、悪霊につかれている人が、彼らに飛びかかり、みんなを押えつけて負かしたので、彼らは傷を負ったまま裸になって、その家を逃げ出した。17 このことがエペソに住むすべてのユダヤ人やギリシヤ人に知れわたって、みんな恐怖に襲われ、そして、主イエスの名があがめられた。

    -   \[DQ\] ヨハネはなぜやめさせたのでしょうか。

        -   自分たちについてこない。イエスに従わない。

        -   イエス（の教え）を受け入れる、神様を受け入れることとの区別がついていないのだろうか。

        -   何をもって仲間とするかの判断基準がここでも重要に思える。

    -   \[DQ\] 悪霊を追い出していた人たちはどのような人たちだと思いますか。

        -   律法学者やパリサイ派の人たちではありませんか。おそらく NO。

        -   なぜそう考えるのでしょうか。では、どのような人たちですか。

3.  イエスはどのように答えますか。（39,40）

    -   39 イエスは言われた、「やめさせないがよい。だれでもわたしの名で力あるわざを行いながら、すぐそのあとで、わたしをそしることはできない。40 わたしたちに反対しない者は、わたしたちの味方である。

    -   \[DQ\] 「だれでもわたしの名で力あるわざを行いながら、すぐそのあとで、わたしをそしることはできない。」はどのようなことを伝えていますか。

        -   ある意味で、（神様が与えられた）イエスの力（権威）に信頼していることを表現している。おそらく、律法学者やパリサイ派の人は、そのようにはしないだろう。

        -   （ベルゼブル論争）「3:23b どうして、サタンがサタンを追い出すことができようか。 24 もし国が内部で分れ争うなら、その国は立ち行かない。 25 また、もし家が内わで分れ争うなら、その家は立ち行かないであろう。 26 もしサタンが内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。 

            -   \[Q\] 内部分裂しないためでしょうか。

    -   \[DQ\] イエスの視点は、ヨハネの視点とどのようなところが異なっていますか。

        -   「わたしたちについてくるか」「かみさまの御心を行っているか」前者は、分かり易いが、後者はそのとおりだとしても、判断は難しい。

    -   \[DQ\] 一般的に「寛容」であれと言っているのでしょうか。

        -   そうかも知れない。寛容が心の広さをもって受け入れることであるなら、

        -   愛は寛容であり（1コリント13:4）μακροθυμέω: to be of a long spirit, not to lose heart (a) to persevere patiently and bravely in enduring misfortunes and troubles, (b) to be patient in bearing the offenses and injuries of others (Mat 18:26, 29, Luke 18:7, 1Thess 5:14, Heb 6:15, Jas 5:7, 8, 2Pet 3:9)

        -   なぜ、寛容さが大切なのでしょうか。

    -   \[DQ\] 反対しないものは、ほんとうに、味方なのでしょうか。

    -   ① 反対しない、② 悪霊を追い出す奉仕の業、③ イエスの名を唱えている

4.  イエスはさらにどのようなことを伝えていますか。（41）

    -   41 だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。

    -   \[DQ\] 「キリストについている者」かどうかが、重要なのでしょうか。

        -   キリストについていない者に恵みの業を行っても報われないのでしょうか。（おそらくそう入っていない。）

    -   参照：マタイ25:31-46 40 すると、王は答えて言うであろう、『あなたがたによく言っておく。わたしの兄弟であるこれらの最も小さい者のひとりにしたのは、すなわち、わたしにしたのである』。

    -   \[DQ\] 「報い」とはなんでしょうか。

5.  ルカ9:51-56 からはどのようなことがわかりますか。

    -   \[DQ\] なぜサマリア人はイエスを歓迎しなかったのでしょう。

    -   \[DQ\] 弟子達の派遣のときと、何が違うのでしょうか。

        -   6:11 また、あなたがたを迎えず、あなたがたの話を聞きもしない所があったなら、そこから出て行くとき、彼らに対する抗議のしるしに、足の裏のちりを払い落しなさい」。

    -   参考：マルコ3:17 またゼベダイの子ヤコブと、ヤコブの兄弟ヨハネ、彼らにはボアネルゲ、すなわち、雷の子という名をつけられた。

6.  イエスはどのようなことを教えているのでしょうか。

    -   \[DQ\] マタイ12:30 「わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。」と比較してどのように理解すればよいのでしょうか。

        -   ベルゼブル論争では、23 そこでイエスは彼らを呼び寄せ、譬をもって言われた、「どうして、サタンがサタンを追い出すことができようか。 24 もし国が内部で分れ争うなら、その国は立ち行かない。 25 また、もし家が内わで分れ争うなら、その家は立ち行かないであろう。 26 もしサタンが内部で対立し分争するなら、彼は立ち行けず、滅んでしまう。 27 だれでも、まず強い人を縛りあげなければ、その人の家に押し入って家財を奪い取ることはできない。縛ってからはじめて、その家を略奪することができる。28 よく言い聞かせておくが、人の子らには、その犯すすべての罪も神をけがす言葉も、ゆるされる。 29 しかし、聖霊をけがす者は、いつまでもゆるされず、永遠の罪に定められる」。 （マルコ）

        -   マタイでは引用句が含まれている。本筋はまず、「もし国が内部で分れ争うなら、その国は立ち行かない。 」と始めている。マタイでは、引用句が含まれるが、マルコでは含まれない。「ルカ11:23 わたしの味方でない者は、わたしに反対するものであり、わたしと共に集めない者は、散らすものである。」も参照。

### メモ

-   背景は不明：ルカの「すると」のように、直接的につながっているのかは不明だが、ここに置かれたことは確かなので、ある程度の連続性は仮定して良いように思われる。すると、単純なのは、「イエスの名」だろうか。

-   全体として、ヨハネ6章66-71節にあるように、イエスから去っていくものが多かったのかもしれない。このあとの、ルカにあるサマリアのエピソードのように、イエスのメシヤとしての行動を理解するものはほとんどいなかったということもあるように思われる。

-   寛容は神様の性質、わたしたちを受け入れてくださっている。これが基本。歓迎は、受け入れがたいものを受け入れることなのだから。

-   マタイ12:30、ルカ11:23 は、時代的背景もあるかもしれない。イエスの直接の教えは、マルコであるが、分断が初代教会時代にある程度広がったのかもしれない。

-   ひとは、単純化バイアスから自由にはなれない。しかし、単純化バイアスにつねに繋ぎ止められるのではなく、それから、解き放たれることも可能で、それもひとのたいせつな部分。自由になれないとしても、それを、さばいてはならない。だれにとっても難しいこと。同時に、自由になることをもとめることも大切。

## 9:42-50 罪への誘惑

> 42 また、わたしを信じるこれらの小さい者のひとりをつまずかせる者は、大きなひきうすを首にかけられて海に投げ込まれた方が、はるかによい。43 もし、あなたの片手が罪を犯させるなら、それを切り捨てなさい。両手がそろったままで地獄の消えない火の中に落ち込むよりは、片手になって命に入る方がよい。44 〔地獄では、うじがつきず、火も消えることがない。〕45 もし、あなたの片足が罪を犯させるなら、それを切り捨てなさい。両足がそろったままで地獄に投げ入れられるよりは、片足で命に入る方がよい。46 〔地獄では、うじがつきず、火も消えることがない。〕47 もし、あなたの片目が罪を犯させるなら、それを抜き出しなさい。両眼がそろったままで地獄に投げ入れられるよりは、片目になって神の国に入る方がよい。48 地獄では、うじがつきず、火も消えることがない。49 人はすべて火で塩づけられねばならない。50 塩はよいものである。しかし、もしその塩の味がぬけたら、何によってその味が取りもどされようか。あなたがた自身の内に塩を持ちなさい。そして、互に和らぎなさい」。

### マタイ 18:6-9

> 6 しかし、わたしを信ずるこれらの小さい者のひとりをつまずかせる者は、大きなひきうすを首にかけられて海の深みに沈められる方が、その人の益になる。7 この世は、罪の誘惑があるから、わざわいである。罪の誘惑は必ず来る。しかし、それをきたらせる人は、わざわいである。8 もしあなたの片手または片足が、罪を犯させるなら、それを切って捨てなさい。両手、両足がそろったままで、永遠の火に投げ込まれるよりは、片手、片足になって命に入る方がよい。9 もしあなたの片目が罪を犯させるなら、それを抜き出して捨てなさい。両眼がそろったままで地獄の火に投げ入れられるよりは、片目になって命に入る方がよい。

### ルカ 17:1-2

> 1 イエスは弟子たちに言われた、「罪の誘惑が来ることは避けられない。しかし、それをきたらせる者は、わざわいである。2 これらの小さい者のひとりを罪に誘惑するよりは、むしろ、ひきうすを首にかけられて海に投げ入れられた方が、ましである。

[マルコによる福音書9章42-50節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark9_42-50.pdf)

### 問い

1.  これまでの部分とどのように関係していますか。

2.  「小さいもの」とは、誰のことでしょうか。（42）

3.  描かれている、四つのことがらについて上げてみましょう。（42-47）

4.  片手、片足、片目が罪を犯させるとはどのようなことでしょうか。（43-47）

5.  いのちに入る、神の国に入る、地獄に投げ入れられるとはどのようなことでしょうか。（43-48）

6.  「塩を持ちなさい、互いに和らぎなさい」はなにを教えているのでしょうか。（49,50）

### 参照

-   マタイではこのあと、「迷い出た羊」のたとえ（18:10-14）、きょうだいの忠告（18:15-20）、「仲間を赦さない家来」のたとえ（18:21-35）が挿入

-   ルカでは、9章の終わりから、16章まで全く別構成になっている。

-   天国

    -   天国は地上における社会で、そこでは神の意志が天において行われているように、完全に地上で行われるところである。

-   塩

    -   レビ記2:13　あなたの素祭の供え物は、すべて塩をもって味をつけなければならない。あなたの素祭に、あなたの神の契約の塩を欠いてはならない。すべて、あなたの供え物は、塩を添えてささげなければならない。

    -   民数記18:19　イスラエルの人々が、主にささげる聖なる供え物はみな、あなたとあなたのむすこ娘とに与えて、永久に受ける分とする。これは主の前にあって、あなたとあなたの子孫とに対し、永遠に変らぬ塩の契約である」。

    -   歴代誌下13:5　あなたがたはイスラエルの神、主が塩の契約をもってイスラエルの国をながくダビデとその子孫に賜わったことを知らないのか。

    -   ヨブ6:6 味のない物は塩がなくて食べられようか。すべりひゆのしるは味があろうか。

    -   エゼキエル43:24 これを主の前に持ってきて、祭司らはその上に塩をまき、これらを燔祭として主にささげよ。

    -   マタイ5:13 あなたがたは、地の塩である。もし塩のききめがなくなったら、何によってその味が取りもどされようか。もはや、なんの役にも立たず、ただ外に捨てられて、人々にふみつけられるだけである。

    -   マルコ9:49, 50 人はすべて火で塩づけられねばならない。50 塩はよいものである。しかし、もしその塩の味がぬけたら、何によってその味が取りもどされようか。あなたがた自身の内に塩を持ちなさい。そして、互に和らぎなさい」。

    -   ルカ14:34 塩は良いものだ。しかし、塩もききめがなくなったら、何によって塩味が取りもどされようか。35 土にも肥料にも役立たず、外に投げ捨てられてしまう。聞く耳のあるものは聞くがよい」。

    -   コロサイ4:6 いつも、塩で味つけられた、やさしい言葉を使いなさい。そうすれば、ひとりびとりに対してどう答えるべきか、わかるであろう。

    -   ヤコブ3:12 わたしの兄弟たちよ。いちじくの木がオリブの実を結び、ぶどうの木がいちじくの実を結ぶことができようか。塩水も、甘い水を出すことはできない。

-   地獄（ゲヘナ） γέεννα: Hell is the place of the future punishment called "Gehenna" or "Gehenna of fire". This was originally the valley of Hinnom, south of Jerusalem, where the filth and dead animals of the city were cast out and burned; a fit symbol of the wicked and their future destruction.

    -   マルコ9:43-48

    -   マタイ5:22 しかし、わたしはあなたがたに言う。兄弟に対して怒る者は、だれでも裁判を受けねばならない。兄弟にむかって愚か者と言う者は、議会に引きわたされるであろう。また、ばか者と言う者は、地獄の火に投げ込まれるであろう。

    -   マタイ5:29,30 もしあなたの右の目が罪を犯させるなら、それを抜き出して捨てなさい。五体の一部を失っても、全身が地獄に投げ入れられない方が、あなたにとって益である。30 もしあなたの右の手が罪を犯させるなら、それを切って捨てなさい。五体の一部を失っても、全身が地獄に落ち込まない方が、あなたにとって益である。

    -   マタイ10:28 また、からだを殺しても、魂を殺すことのできない者どもを恐れるな。むしろ、からだも魂も地獄で滅ぼす力のあるかたを恐れなさい。

    -   マタイ18:9 もしあなたの片目が罪を犯させるなら、それを抜き出して捨てなさい。両眼がそろったままで地獄の火に投げ入れられるよりは、片目になって命に入る方がよい。

    -   マタイ23:15 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたはひとりの改宗者をつくるために、海と陸とを巡り歩く。そして、つくったなら、彼を自分より倍もひどい地獄の子にする。

    -   マタイ23:33 へびよ、まむしの子らよ、どうして地獄の刑罰をのがれることができようか。

    -   ルカ12:5 恐るべき者がだれであるか、教えてあげよう。殺したあとで、更に地獄に投げ込む権威のあるかたを恐れなさい。そうだ、あなたがたに言っておくが、そのかたを恐れなさい。

    -   ヤコブ3:6 舌は火である。不義の世界である。舌は、わたしたちの器官の一つとしてそなえられたものであるが、全身を汚し、生存の車輪を燃やし、自らは地獄の火で焼かれる。

-   ベンヒンノム（ゲヒンノムの谷）

    -   ヨシュア15:8 またその境はベンヒンノムの谷に沿って、エブスびとの地、すなわちエルサレムの南のわきに上り、ヒンノムの谷の西にある山の頂に上る。これはレパイムの谷の北の果にあるものである。

    -   ヨシュア18:16 ついでその境は、レパイムの谷の北の端にあるベンヒンノムの谷を見おろす山の端に下り、進んでエブスびとのわきの南、ヒンノムの谷に下り、また下ってエンロゲルに至り、

    -   列王記下23:10 王はまた、だれもそのむすこ娘を火に焼いて、モレクにささげ物とすることのないように、ベンヒンノムの谷にあるトペテを汚した。

    -   歴代誌下28:3 ベンヒンノムの谷で香をたき、その子らを火に焼いて供え物とするなど、主がイスラエルの人々の前から追い払われた異邦人の憎むべき行いにならい、

        -   エレミヤ7:31,32 またベンヒンノムの谷にあるトペテの高き所を築いて、むすこ娘を火に焼いた。わたしはそれを命じたことはなく、またそのようなことを考えたこともなかった。32 主は言われる、それゆえに見よ、その所をトペテ、またはベンヒンノムの谷と呼ばないで、ほふりの谷と呼ぶ日が来る。それはほかに場所がないので、トペテに葬るからである。

    -   歴代誌下33:6 彼はまたベンヒンノムの谷でその子供を火に焼いて供え物とし、占いをし、魔法をつかい、まじないを行い、口寄せと、占い師を任用するなど、主の前に多くの悪を行って、その怒りをひき起した。

        -   エレミヤ32:35 またベンヒンノムの谷にバアルの高き所を築いて、むすこ娘をモレクにささげた。わたしは彼らにこのようなことを命じたことはなく、また彼らがこの憎むべきことを行って、ユダに罪を犯させようとは考えもしなかった。

    -   エレミヤ19:2 瀬戸かけの門の入口にあるベンヒンノムの谷へ行き、その所で、わたしがあなたに語る言葉をのべて、

    -   エレミヤ19:6 主は言われる、それゆえ、見よ、この所をトペテまたはベンヒンノムの谷と呼ばないで、虐殺の谷と呼ぶ日がくる。

-   イザヤ書66:24 「彼らは出て、わたしにそむいた人々のしかばねを見る。そのうじは死なず、その火は消えることがない。彼らはすべての人に忌みきらわれる」。

### 記録

-   日時：2024年5月23日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）1名

### 問いについて

1.  これまでの部分とどのように関係していますか。

    -   聖書協会共同訳では、38節から新しい段落になっているが、口語訳では、38節のヨハネの問からつながっている。

    -   山上の変貌とおしの霊につかれたこどもを癒やす記事以降

        -   9:30-32 再び自分の死と復活を予告する：30 イエスは人に気づかれるのを好まれなかった。32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

        -   9:33-37 いちばん偉い者：37 だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。

        -   9:38-41 逆らわない者は味方：41 だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。

        -   このエピソードの背景は明確ではないが、弟子たちとイエスの間に十分な共通理解があったわけではないことも踏まえつつ、このように話が進んだと仮定して読んでみよう。イエスにとって、弟子たちにとって、なにがたいせつなのか、そのすり合わせをしているようなときのようにも見える。イエスにとっては、残された地上での日々が短いことを意識しつつ、弟子たちに託していくことについて考え、弟子たちにとっては、基本的に自分たちだけがイエスに従っているような状況の中で、どんな生き方が偉いのか、イエスに従っていくことが絶対ではないのか、おさなごを受け入れるとはどのようなことなのか、イエスからのメッセージを必死で受け取ろうとしてたように思われる。

    -   \[DQ\] 前段の寛容とはかなりトーンが異なるように思われますが、誰に対して語られているのでしょうか。

        -   前後関係からすると、弟子たちに語られているように見える。マタイには、ヨハネの記事はないが、ほぼ同じ構成になっており、「いちばん偉い者」で、幼子を受け入れるに続いて描かれている。ルカでは、前後関係など、構成は異なるが、弟子たちに語られている。

        -   マタイでは、「18:7 この世は、罪の誘惑があるから、わざわいである。罪の誘惑は必ず来る。しかし、それをきたらせる人は、わざわいである。」と書かれており。イエス様は、弟子たちや、その後の、リーダーたちに迫る、様々な困難を予想していたのだろう。もしかすると、イエス様も、悪魔の誘惑も含めて、様々な罪の誘惑と対峙していたのかもしれない。マタイによる福音書記者は、このようなことをすでにたくさん見てきたのかもしれない。

2.  「小さいもの」とは、誰のことでしょうか。（42）

    -   42 また、わたしを信じるこれらの小さい者のひとりをつまずかせる者は、大きなひきうすを首にかけられて海に投げ込まれた方が、はるかによい。

        -   「41 だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。」に続くと考えると、あなたがた、つまり弟子たちが意識されているように見える。しかし、ことばとしては、もっと一般的に響く。イエス（または神）が、または、イエス（または神）を、完全ではないが、愛そうとしているものだろうか。

        -   「36 そして、ひとりの幼な子をとりあげて、彼らのまん中に立たせ、それを抱いて言われた。37 k『だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである』。」に関係しているとすると、もっとずっと広いことが関係しているように見える。「幼子（またはイエス、または不完全な自分のような存在）を受け入れようとするもの」

    -   \[DQ\] 人をつまづかせるとはどのような事でしょうか。

        -   おそらく、水いっぱいがとても嬉しいというひとに、水をあげることと対比されているのだろう。

    -   \[DQ\] 他の人との関係についてどんな警告が与えられていますか。

        -   「つまづかせる」は、だれか他者をつまづかせるように感じるが、このあとは、自分の手や足や目について言及されている。小さいものとして想定されていることと、罪を犯させるとの関係は、単純ではない。

3.  描かれている、四つのことがらについて上げてみましょう。（42-47）

    -   42 また、わたしを信じるこれらの小さい者のひとりをつまずかせる者は、大きなひきうすを首にかけられて海に投げ込まれた方が、はるかによい。43 もし、あなたの片手が罪を犯させるなら、それを切り捨てなさい。両手がそろったままで地獄の消えない火の中に落ち込むよりは、片手になって命に入る方がよい。44 〔地獄では、うじがつきず、火も消えることがない。〕45 もし、あなたの片足が罪を犯させるなら、それを切り捨てなさい。両足がそろったままで地獄に投げ入れられるよりは、片足で命に入る方がよい。46 〔地獄では、うじがつきず、火も消えることがない。〕47 もし、あなたの片目が罪を犯させるなら、それを抜き出しなさい。両眼がそろったままで地獄に投げ入れられるよりは、片目になって神の国に入る方がよい。

    -   42節から47節には四つの対比があります。それぞれの場合に何が何よりも良いのですか。

        1.  「わたしを信じるこれらの小さい者のひとりをつまずかせる」より「大きなひきうす（聖書協会共同訳：ロバの挽く石臼）を首にかけられて海に投げ込まれた方が、はるかによい」。

        2.  「あなたの片手が罪を犯させる」なら「切り捨てなさい」。「両手がそろったままで地獄の消えない火の中に落ち込むよりは、片手になって命に入る方がよい。」

        3.  「あなたの片足が罪を犯させる」なら「切り捨てなさい」。「両足がそろったままで地獄に投げ入れられるよりは、片足で命に入る方がよい。」

        4.  「あなたの片目が罪を犯させる」なら「抜き出しなさい」。「両眼がそろったままで地獄に投げ入れられるよりは、片目になって神の国に入る方がよい。」

    -   \[DQ\]「つまづかせる」と「罪を犯させる」は、同じなのでしょうか。

        -   興味深い問である。「罪を犯す」は理解できても、ここでは、「罪を犯させる」「つまづかせる」ことが問われている。マタイ18:7 の「罪の誘惑は必ず来る」と連動させると両方に視点がある。

        -   誰を想定しているか、混在しているように見える。前段では、「キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるもの」と言っているので、つまづかせられるのは、弟子たちであるように見えるが、このあとには、あなたの片手、片足、片目が罪を犯させるならとなっているので、つまづかせる主体は、弟子たちであるようにも見える。

    -   \[DQ\] なにを教えているのでしょうか。

        -   「41 だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。」とはいえ、あなたがたが、逆に、つまづかせる、罪を犯させるようなことは、絶対にいけないよ。と言っているかのようである。

    -   \[DQ\] 絶対にしてはならないことと、犠牲をともなっても、守るべきたいせつなことについて述べているようですが、それらはどのようなことなのでしょう。

        -   神の意志を行うためにするいかなる犠牲も、訓練も、自己否定も値打ちのあるものである。

4.  片手、片足、片目が罪を犯させるとはどのようなことでしょうか。（43-47）

    -   43 もし、あなたの片手が罪を犯させるなら、それを切り捨てなさい。両手がそろったままで地獄の消えない火の中に落ち込むよりは、片手になって命に入る方がよい。44 〔地獄では、うじがつきず、火も消えることがない。〕45 もし、あなたの片足が罪を犯させるなら、それを切り捨てなさい。両足がそろったままで地獄に投げ入れられるよりは、片足で命に入る方がよい。46 〔地獄では、うじがつきず、火も消えることがない。〕47 もし、あなたの片目が罪を犯させるなら、それを抜き出しなさい。両眼がそろったままで地獄に投げ入れられるよりは、片目になって神の国に入る方がよい。

    -   \[DQ\] 手や足はどのようにその人に罪をおかさせうるでしょうか。罪の結果は何ですか。

        -   おそらく、なにがあっても、イエスをしんじつ、小さいもの（完璧ではない弱いもの）を、指導者でもある、あなた方は、絶対に、躓かせてはいけない。もし、そのような要因があるなら、それを断固切り捨てなさい。と言っているかのようである。

    -   \[DQ\] 今日の社会で、どんなことが、他の人に罪をおかさせるつまずきになりますか。

        -   ちいさなものを無視。イエスの名のゆえに受け入れることの逆。

        -   ちいさなものを愛しておられるかみさまを見逃す、みようとしない。

        -   神様の、よろこばれることを考えず、自分の名があげられることを求める。

5.  いのちに入る、神の国に入る、地獄に投げ入れられるとはどのようなことでしょうか。（43-48）

    -   43 もし、あなたの片手が罪を犯させるなら、それを切り捨てなさい。両手がそろったままで地獄の消えない火の中に落ち込むよりは、片手になって命に入る方がよい。44 〔地獄では、うじがつきず、火も消えることがない。〕45 もし、あなたの片足が罪を犯させるなら、それを切り捨てなさい。両足がそろったままで地獄に投げ入れられるよりは、片足で命に入る方がよい。46 〔地獄では、うじがつきず、火も消えることがない。〕47 もし、あなたの片目が罪を犯させるなら、それを抜き出しなさい。両眼がそろったままで地獄に投げ入れられるよりは、片目になって神の国に入る方がよい。48 地獄では、うじがつきず、火も消えることがない。

    -   \[DQ\] いのちに入る、神の国に入るとは。

        -   神様の国（みこころがなる世界）に生きることを求めること。

        -   神のみこころとシンクロして生きること。

        -   神の意志を行うためにするいかなる犠牲も、訓練も、自己否定も値打ちのあるものである。

    -   \[DQ\] 地獄に投げ入れられるとは。

        -   神様のみこころを受け入れることを拒否した生活を送ること。

    -   \[DQ\] 火とはどのような意味に使われているのでしょうか。

        -   48 地獄では、うじがつきず、火も消えることがない。49 人はすべて火で塩づけられねばならない。（イザヤ書66:24 「彼らは出て、わたしにそむいた人々のしかばねを見る。そのうじは死なず、その火は消えることがない。彼らはすべての人に忌みきらわれる」。）

6.  「塩を持ちなさい、互いに和らぎなさい」はなにを教えているのでしょうか。（49,50）

    -   49 人はすべて火で塩づけられねばならない。50 塩はよいものである。しかし、もしその塩の味がぬけたら、何によってその味が取りもどされようか。あなたがた自身の内に塩を持ちなさい。そして、互に和らぎなさい」。

    -   \[DQ\] 塩はどのような意味に使われているのでしょうか。

        -   味をつける、防腐剤、

        -   レビ記2:13　あなたの素祭の供え物は、すべて塩をもって味をつけなければならない。あなたの素祭に、あなたの神の契約の塩を欠いてはならない。すべて、あなたの供え物は、塩を添えてささげなければならない。

        -   民数記18:19　イスラエルの人々が、主にささげる聖なる供え物はみな、あなたとあなたのむすこ娘とに与えて、永久に受ける分とする。これは主の前にあって、あなたとあなたの子孫とに対し、永遠に変らぬ塩の契約である」。

        -   歴代誌下13:5　あなたがたはイスラエルの神、主が塩の契約をもってイスラエルの国をながくダビデとその子孫に賜わったことを知らないのか。

    -   バークレイ：クリスチャンの生活が神に受け入れられるものとなるためには、ちょうど、すべての犠牲が塩で処理されたように、火で処理されなければならない。

    -   バークレイ：あなたがたのうちに、キリストの霊のきよめる力を持ちなさい。利己心、自我意識から、苦さ、怒り、妬みからきよめられなさい。焦燥、気まぐれ、自己中心から清められなさい。それによってのみ、あなたがたは自分の仲間と平和に過ごすことができるのである。

    -   参考：

        -   マタイ5:13 あなたがたは、地の塩である。もし塩のききめがなくなったら、何によってその味が取りもどされようか。もはや、なんの役にも立たず、ただ外に捨てられて、人々にふみつけられるだけである。

        -   ルカ14:34 塩は良いものだ。しかし、塩もききめがなくなったら、何によって塩味が取りもどされようか。35 土にも肥料にも役立たず、外に投げ捨てられてしまう。聞く耳のあるものは聞くがよい」。

    -   \[DQ\] ここで、塩はなにを意味しているのでしょうか。

        -   たいせつなものという漠然とした解釈でも良いかもしれない。あなたにとって、たいせつなもの失ってはいけないものは何でしょうか。

        -   十分理解できていない、幼子のような態度で、みこころを求め、生きることだろうか。

    -   \[DQ\] ここでなぜ「和らぎなさい」と言っているのでしょうか。

        -   あとになり、仕えるものとなり、仕え合うことだろうか。

        -   水いっぱいを求めるものに与え、つまづきとなっていないか顧み、みこころを求め続けることか。

### メモ

-   なかなか難しい。どのように扱ったらよいのだろうか。バークレイは、「塩」や「火」で結び付けられた他の箇所の言葉が入り込んでいるとすらかいている。

-   塩・火：自分も、ひとりの、幼子のように、神様のみこころを十分は理解できていないことを自覚しつつ、生きることが求められている。しかし、みこころに生きることを求めるところが忘れられてしまったら、慈善活動も、福音宣教も、まったく、意味のないものになってしまうと言っているように感じる。

-   全体として、つながっているように見える。イエスが、弟子たちに伝えたかったこと。それが凝縮しているのだろう。ちいさいものとして、そして、たいせつなものをたいせつに、躓かせないようにと厳しく話すところには、ヨハネのような行為に、注意するようにとのメッセージが含まれているようにみえるし、また、最後に「たいせつなことをたいせつにすることによって、和らぎなさい」も、批判的にならず、自分を攻めるのでもなく、互いに、和らぐことを勧めている。塩がなにかは、明確ではないが、大切なものであることはわかる。

## 10:1-12 離婚について教える

> 1 それから、イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれたが、群衆がまた寄り集まったので、いつものように、また教えておられた。2 そのとき、パリサイ人たちが近づいてきて、イエスを試みようとして質問した、「夫はその妻を出しても差しつかえないでしょうか」。3 イエスは答えて言われた、「モーセはあなたがたになんと命じたか」。4 彼らは言った、「モーセは、離縁状を書いて妻を出すことを許しました」。5 そこでイエスは言われた、「モーセはあなたがたの心が、かたくななので、あなたがたのためにこの定めを書いたのである。6 しかし、天地創造の初めから、『神は人を男と女とに造られた。7 それゆえに、人はその父母を離れ、8 ふたりの者は一体となるべきである』。彼らはもはや、ふたりではなく一体である。9 だから、神が合わせられたものを、人は離してはならない」。10 家にはいってから、弟子たちはまたこのことについて尋ねた。11 そこで、イエスは言われた、「だれでも、自分の妻を出して他の女をめとる者は、その妻に対して姦淫を行うのである。12 また妻が、その夫と別れて他の男にとつぐならば、姦淫を行うのである」。

### マタイ 19:1-12

> 1 イエスはこれらのことを語り終えられてから、ガリラヤを去ってヨルダンの向こうのユダヤの地方へ行かれた。2 すると大ぜいの群衆がついてきたので、彼らをそこでおいやしになった。3 さてパリサイ人たちが近づいてきて、イエスを試みようとして言った、「何かの理由で、夫がその妻を出すのは、さしつかえないでしょうか」。4 イエスは答えて言われた、「あなたがたはまだ読んだことがないのか。『創造者は初めから人を男と女とに造られ、5 そして言われた、それゆえに、人は父母を離れ、その妻と結ばれ、ふたりの者は一体となるべきである』。6 彼らはもはや、ふたりではなく一体である。だから、神が合わせられたものを、人は離してはならない」。7 彼らはイエスに言った、「それでは、なぜモーセは、妻を出す場合には離縁状を渡せ、と定めたのですか」。8 イエスが言われた、「モーセはあなたがたの心が、かたくななので、妻を出すことを許したのだが、初めからそうではなかった。9 そこでわたしはあなたがたに言う。不品行のゆえでなくて、自分の妻を出して他の女をめとる者は、姦淫を行うのである」。10 弟子たちは言った、「もし妻に対する夫の立場がそうだとすれば、結婚しない方がましです」。11 するとイエスは彼らに言われた、「その言葉を受けいれることができるのはすべての人ではなく、ただそれを授けられている人々だけである。12 というのは、母の胎内から独身者に生れついているものがあり、また他から独身者にされたものもあり、また天国のために、みずから進んで独身者となったものもある。この言葉を受けられる者は、受けいれるがよい」。

[マルコによる福音書10章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_1-12.pdf)

### 問い

1.  状況と背景を確認しましょう。どこからどこへ向かっていますか。（1）

2.  誰が、どのような目的で、どのような質問をしますか。（2）

3.  イエスはまずどのようなやり取りをしますか。（3,4）

4.  イエスは、どのようなことを教えますか。（5-9）

5.  さらに、弟子たちには、どのように教えますか。（10-12）

6.  イエスは、なにをたいせつなこととして教えているのでしょうか。

### 参照

-   地図：ガリラヤからエルサレムへ

    -   Jesus' Ministry in Galilee and Journey to Jerusalem \[[参照](https://www.seektheoldpaths.com/Maps/107a.jpg)\]

    -   Jesus' Journeys from Gal1lee to Judea \[[参照](https://www.seektheoldpaths.com/Maps/110.jpg)\]

-   マタイでは、「罪への誘惑」（18:6-9、マルコ9:42-48）のあと、「迷い出た羊」のたとえ、きょうだいの忠告、「仲間を赦さない家来」のたとえがあり、その後で、離縁について教える今回の記事が続く。このあとは、こどもを祝福する、金持ちの青年とマルコと同じ配列になっている。

-   6 しかし、天地創造の初めから、『神は人を男と女とに造られた。7 それゆえに、人はその父母を離れ、8 ふたりの者は一体となるべきである』。彼らはもはや、ふたりではなく一体である。

    -   創世記1:27 神は自分のかたちに人を創造された。すなわち、神のかたちに創造し、男と女とに創造された。

    -   創世記2:18-25 また主なる神は言われた、「人がひとりでいるのは良くない。彼のために、ふさわしい助け手を造ろう」。19 そして主なる神は野のすべての獣と、空のすべての鳥とを土で造り、人のところへ連れてきて、彼がそれにどんな名をつけるかを見られた。人がすべて生き物に与える名は、その名となるのであった。20 それで人は、すべての家畜と、空の鳥と、野のすべての獣とに名をつけたが、人にはふさわしい助け手が見つからなかった。21 そこで主なる神は人を深く眠らせ、眠った時に、そのあばら骨の一つを取って、その所を肉でふさがれた。22 主なる神は人から取ったあばら骨でひとりの女を造り、人のところへ連れてこられた。23 そのとき、人は言った。「これこそ、ついにわたしの骨の骨、／わたしの肉の肉。男から取ったものだから、／これを女と名づけよう」。創世記2:24 それで人はその父と母を離れて、妻と結び合い、一体となるのである。25 人とその妻とは、ふたりとも裸であったが、恥ずかしいとは思わなかった。

    -   エペソ5:31-33 「それゆえに、人は父母を離れてその妻と結ばれ、ふたりの者は一体となるべきである」。32 この奥義は大きい。それは、キリストと教会とをさしている。33 いずれにしても、あなたがたは、それぞれ、自分の妻を自分自身のように愛しなさい。妻もまた夫を敬いなさい。

    -   コリント前書6:16-20 それとも、遊女につく者はそれと一つのからだになることを、知らないのか。「ふたりの者は一体となるべきである」とあるからである。17 しかし主につく者は、主と一つの霊になるのである。18 不品行を避けなさい。人の犯すすべての罪は、からだの外にある。しかし不品行をする者は、自分のからだに対して罪を犯すのである。19 あなたがたは知らないのか。自分のからだは、神から受けて自分の内に宿っている聖霊の宮であって、あなたがたは、もはや自分自身のものではないのである。20 あなたがたは、代価を払って買いとられたのだ。それだから、自分のからだをもって、神の栄光をあらわしなさい。

-   離縁状（マルコ10:4, マタイ19:7 以外）

    -   申命記24:1-4 人が妻をめとって、結婚したのちに、その女に恥ずべきことのあるのを見て、好まなくなったならば、離縁状を書いて彼女の手に渡し、家を去らせなければならない。2 女がその家を出てのち、行って、ほかの人にとつぎ、3 後の夫も彼女をきらって、離縁状を書き、その手に渡して家を去らせるか、または妻にめとった後の夫が死んだときは、4 彼女はすでに身を汚したのちであるから、彼女を去らせた先の夫は、ふたたび彼女を妻にめとることはできない。これは主の前に憎むべき事だからである。あなたの神、主が嗣業としてあなたに与えられる地に罪を負わせてはならない。

    -   イザヤ50:1-3 主はこう言われる、／「わたしがあなたがたの母を去らせたその離縁状は、／どこにあるか。わたしはどの債主にあなたがたを売りわたしたか。見よ、あなたがたは、その不義のために売られ、／あなたがたの母は、／あなたがたのとがのために出されたのだ。2 わたしが来たとき、／なぜひとりもいなかったか。わたしが呼んだとき、／なぜひとりも答える者がなかったか。わたしの手が短くて、／あがなうことができないのか。わたしは救う力を持たないのか。見よ、わたしが、しかると海はかれ、／川は荒野となり、／その中の魚は水がないために、／かわき死んで悪臭を放つ。3 わたしは黒い衣を天に着せ、／荒布をもってそのおおいとする」。

    -   エレミヤ3:8-10 わたしが背信のイスラエルを、そのすべての姦淫のゆえに、離縁状を与えて出したのをユダは見た。しかもその不信の姉妹ユダは恐れず、自分も行って姦淫を行った。9 彼女にとって姦淫は軽いことであったので、石と木とに姦淫を行って、この地を汚した。10 このすべての事があっても、なおその不信の姉妹ユダは真心をもってわたしに帰らない、ただ偽っているだけだ」と主は言われる。

        -   エレミヤ3:1 もし人がその妻を離婚し、／女が彼のもとを去って、他人の妻となるなら、／その人はふたたび彼女に帰るであろうか。その地は大いに汚れないであろうか。あなたは多くの恋人と姦淫を行った。しかもわたしに帰ろうというのか」と主は言われる。

    -   マタイ5:31-32 また『妻を出す者は離縁状を渡せ』と言われている。32 しかし、わたしはあなたがたに言う。だれでも、不品行以外の理由で自分の妻を出す者は、姦淫を行わせるのである。また出された女をめとる者も、姦淫を行うのである。

        -   マタイ5:33-37 また昔の人々に『いつわり誓うな、誓ったことは、すべて主に対して果せ』と言われていたことは、あなたがたの聞いているところである。34 しかし、わたしはあなたがたに言う。いっさい誓ってはならない。天をさして誓うな。そこは神の御座であるから。35 また地をさして誓うな。そこは神の足台であるから。またエルサレムをさして誓うな。それは『大王の都』であるから。36 また、自分の頭をさして誓うな。あなたは髪の毛一すじさえ、白くも黒くもすることができない。37 あなたがたの言葉は、ただ、しかり、しかり、否、否、であるべきだ。それ以上に出ることは、悪から来るのである。

-   姦淫（マルコ10:11,12、マタイ19:9 以外の福音書）

    -   マルコ7:20-23 さらに言われた、「人から出て来るもの、それが人をけがすのである。21 すなわち内部から、人の心の中から、悪い思いが出て来る。不品行、盗み、殺人、22 姦淫、貪欲、邪悪、欺き、好色、妬み、誹り、高慢、愚痴。23 これらの悪はすべて内部から出てきて、人をけがすのである」。（マタイ15:1-20）

    -   マルコ10:17-22 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。18 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。19 いましめはあなたの知っているとおりである。『殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え』」。20 すると、彼は言った、「先生、それらの事はみな、小さい時から守っております」。21 イエスは彼に目をとめ、いつくしんで言われた、「あなたに足りないことが一つある。帰って、持っているものをみな売り払って、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。22 すると、彼はこの言葉を聞いて、顔を曇らせ、悲しみながら立ち去った。たくさんの資産を持っていたからである。（マタイ19:16-30、ルカ18:18-30）

    -   マタイ5:27-30 『姦淫するな』と言われていたことは、あなたがたの聞いているところである。28 しかし、わたしはあなたがたに言う。だれでも、情欲をいだいて女を見る者は、心の中ですでに姦淫をしたのである。29 もしあなたの右の目が罪を犯させるなら、それを抜き出して捨てなさい。五体の一部を失っても、全身が地獄に投げ入れられない方が、あなたにとって益である。30 もしあなたの右の手が罪を犯させるなら、それを切って捨てなさい。五体の一部を失っても、全身が地獄に落ち込まない方が、あなたにとって益である。

    -   ルカ16:18 すべて自分の妻を出して他の女をめとる者は、姦淫を行うものであり、また、夫から出された女をめとる者も、姦淫を行うものである。

    -   ルカ18:11 パリサイ人は立って、ひとりでこう祈った、『神よ、わたしはほかの人たちのような貪欲な者、不正な者、姦淫をする者ではなく、また、この取税人のような人間でもないことを感謝します。

    -   ヨハネ8:3-5 すると、律法学者たちやパリサイ人たちが、姦淫をしている時につかまえられた女をひっぱってきて、中に立たせた上、イエスに言った、4 「先生、この女は姦淫の場でつかまえられました。5 モーセは律法の中で、こういう女を石で打ち殺せと命じましたが、あなたはどう思いますか」。

-   姦淫（日本国語大辞典）

    -   かん‐いん【姦淫・奸淫】

        〘名〙 男女が道義に反する肉体関係を結ぶこと。不倫な情事。

        ＊読本・翁丸物語（1807）上

        「今年四十一歳なり。されど奸淫を好みて」

    -   かんいん‐ざい【姦淫罪】

        〘名〙 姦淫をする罪。

        ㋑法律で、婦女の真意に反して性交を強制する罪をいう。強姦罪、準強姦罪および淫行勧誘罪の総称。旧法では姦通罪を含めていた。

        ＊民法（明治二九年）（1896）八一三条

        「夫婦の一方は左の場合に限り離婚の訴を提起することを得。〈略〉三、夫が姦淫罪に因りて刑に処せられたるとき」

        ㋺キリスト教などの宗教で、姦淫禁止の戒律を破る罪。

        ＊大津順吉（1912）〈志賀直哉〉一

        「私にとって教へでの最も不調和なものは姦淫罪の律おきてであった」

-   日本の離婚に関する法律

    -   協議離婚・調停離婚・審判離婚・裁判離婚

    -   法律上における5つの離婚の条件

        （1）配偶者に不貞行為があった

        （2）配偶者から悪意の遺棄を受けた

        （3）生死が3年以上不明

        （4）配偶者が強度の精神病で回復の見込みがない

        （5）その他婚姻関係を継続できない重大な事由

    -   第770条【裁判上の離婚】

        ①　夫婦の一方は、次に掲げる場合に限り、離婚の訴えを提起することができる。

        一　配偶者に不貞な行為があったとき。

        二　配偶者から悪意で遺棄されたとき。

        三　配偶者の生死が3年以上明らかでないとき。

        四　配偶者が強度の精神病にかかり、回復の見込みがないとき。

        五　その他婚姻を継続し難い重大な事由があるとき。

        ②　裁判所は、前項第一号から第四号までに掲げる事由がある場合であっても、一切の事情を考慮して婚姻の継続を相当と認めるときは、離婚の請求を棄却することができる。

### 記録

-   日時：2024年5月30日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）1名

### 問いについて

1.  状況と背景を確認しましょう。どこからどこへ向かっていますか。（1）

    -   1 それから、イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれたが、群衆がまた寄り集まったので、いつものように、また教えておられた。

    -   一行はカペナウムに来て家にいたときに（33）、弟子たちを呼び寄せ、すわって教えられた。（35a）① みなに仕えるものとなるべきこと。（35b）② 幼な子をイエスの名のゆえに受け入れるべきこと。（36,37）③ ヨハネの応答に対して教え。（38-40）④ イエスを信じるちいさなものをたいせつにするべきこと。（41-48）⑤ 自分のうちに塩を持ち、互いに和らげ。（49，50）

    -   「イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれた」とあるが、マタイでは「1 イエスはこれらのことを語り終えられてから、ガリラヤを去ってヨルダンの向こうのユダヤの地方へ行かれた。2 すると大ぜいの群衆がついてきたので、彼らをそこでおいやしになった。」となっている。マルコには、いやしの記事はない。マルコでは、山を降りてきたときのいやしの記事以降は、エリコでの盲人バルティマイのいやしのみ。

    -   \[DQ\] どこでの出来事なのでしょうか。

        -   マルコは、「そこを去って、ユダヤの地方とヨルダンの向こう側へ行かれた」とあるが、マタイでは「ガリラヤを去ってヨルダンの向こうのユダヤの地方へ行かれた。」とある。特定するのが、困難である。ただ、基本的には、地名や土地勘に関しては、マタイ記者のほうが正確な場合が多いようである。ペテロは、無論、土地勘があるが、マルコは、それが十分ではなかったのかもしれない。ヨルダンの向こうは、デカポリスや、ペレアと思われるが、川沿いは南の方は、ユダヤだったのかもしれない。また、ルカでは、サマリヤの地を通ったことになっているが、経路も不明である。すくなくとも、急いで、エルサレムに直行したのではなく、いくつかの町を通って、南下していかれたのだろう。

        -   10:32「さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。」とあるが、この時点では、どこにいるかは不明で、1節は、大雑把な、導入なのかもしれない。10節の「家」は、カペナウムのペトロに家を想起させる。すると、1節はあるものの、カペナウムの可能性が高い。

    -   \[DQ\] どのような状況で、このことが起こりますか。ここには、だれがいますか。

        -   **「**群衆がまた寄り集まったので、いつものように、また教えておられた。**」**とあり、群衆に教えておられたなかで起こったこととして描かれている。具体的な問としてあるかうより、群衆に教えている中で、多少、裏のある、問が、パリサイ人から投げかけられたと見るのがよいように思われる。

    -   マタイでは 19:1「イエスはこれらのことを語り終えられてから、ガリラヤを去ってヨルダンの向こうのユダヤの地方へ行かれた。」と一つの区切りとしている。7:28「イエスがこれらの言を語り終えられると、群衆はその教にひどく驚いた。」, 11:1「イエスは十二弟子にこのように命じ終えてから、町々で教えまた宣べ伝えるために、そこを立ち去られた。」, 13:53「イエスはこれらの譬を語り終えてから、そこを立ち去られた。」, 26:1「イエスはこれらの言葉をすべて語り終えてから、弟子たちに言われた。」

2.  誰が、どのような目的で、どのような質問をしますか。（2）

    -   2 そのとき、パリサイ人たちが近づいてきて、イエスを試みようとして質問した、「夫はその妻を出しても差しつかえないでしょうか」。

    -   \[DQ\] どのような質問ですか。

        -   パリサイ人が、イエスを試みようとして、離婚の是非について問うている。

        -   表面的には、離婚の是非について一般的に問うているが、このあとのやり取りをみると、真意は、もう少し違うところにあるようにも見える。その背景をしっかり理解しなくてはいけないのだろう。

    -   \[DQ\] 「試そうとして」とありますが、どのようなことを試そうとしたのでしょうか。

        -   試みようとしてとあるが、このあとは、なにも、反論をしていないので、その意図がどの程度強かったのかは不明。すくなくとも、このあと弟子も「このことについて」おそらく、イエスが言われたことについて質問しているので、パリサイ人を批判したり、忌避したりという様子は見受けられない。パリサイ人の意図がどうであれ、イエスは、本質的な教えを説いている。

    -   \[DQ\] なぜ、離婚についての質問をしたのでしょうか。

        -   おそらく、その理由は、このあとの、イエスとのやり取りにヒントがある。

3.  イエスはまずどのようなやり取りをしますか。（3,4）

    -   3 イエスは答えて言われた、「モーセはあなたがたになんと命じたか」。4 彼らは言った、「モーセは、離縁状を書いて妻を出すことを許しました」。

    -   \[DQ\] なぜ、イエスは、「モーセはあなたがたになんと命じたか」と問い返したのでしょうか。

        -   意図を明確にし、それから答える。共通の立脚点を確認する。

        -   いつもの方法。問に問で返すことで、問の意味を深め、意図を明確にする。自ら考え始めるように促す。

            -   2:7-9 「この人は、なぜあんなことを言うのか。それは神をけがすことだ。神ひとりのほかに、だれが罪をゆるすことができるか」。8 イエスは、彼らが内心このように論じているのを、自分の心ですぐ見ぬいて、「なぜ、あなたがたは心の中でそんなことを論じているのか。9 中風の者に、あなたの罪はゆるされた、と言うのと、起きよ、床を取りあげて歩け、と言うのと、どちらがたやすいか。

            -   3:2-5 人々はイエスを訴えようと思って、安息日にその人をいやされるかどうかをうかがっていた。3 すると、イエスは片手のなえたその人に、「立って、中へ出てきなさい」と言い、4 人々にむかって、「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」と言われた。彼らは黙っていた。5 イエスは怒りを含んで彼らを見まわし、その心のかたくななのを嘆いて、その人に「手を伸ばしなさい」と言われた。そこで手を伸ばすと、その手は元どおりになった。

            -   3:32,33 ときに、群衆はイエスを囲んですわっていたが、「ごらんなさい。あなたの母上と兄弟、姉妹たちが、外であなたを尋ねておられます」と言った。33 すると、イエスは彼らに答えて言われた、「わたしの母、わたしの兄弟とは、だれのことか」。

    -   \[DQ\] どのように答えますか。

        -    「モーセは、離縁状を書いて妻を出すことを許しました」。

    -   \[DQ\] 申命記24:1 からの引用のようですが、申命記24:1 は何を教えているのでしょうか。

        -   申命記24:1-4 1 人が妻をめとって、結婚したのちに、その女に恥ずべきことのあるのを見て、好まなくなったならば、離縁状を書いて彼女の手に渡し、家を去らせなければならない。

        -   離縁状があれば、女性は他の男性と結婚することが可能となった。

    -   \[DQ\] 「モーセは、離縁状を書いて妻を出すことを許しました」。と答えていますが、では、なぜ、このひとたちは、イエスに問うたのでしょう。（最初の問の目的）

        -   ユダヤ教の中で、ホットなトピックだったようだ、申命記の「恥ずべきこと（עֶרְוָה ：nakedness）」をどう取るかで、何でも理由にしうると考える派（ヒレル派）と、姦淫に限定する派（シャンマイ派）とがあったようだ。そのどちら側にたつかという質問の可能性もある。

        -   バプテスマのヨハネがヘロデが妻を離縁して、ヘロデヤを娶ったことを避難したかどで、投獄されたとする節から、なにか、そのような立場をとるかとの質問かもしれない。

            -   マルコ6:17,18 このヘロデは、自分の兄弟ピリポの妻ヘロデヤをめとったが、そのことで、人をつかわし、ヨハネを捕えて獄につないだ。18 それは、ヨハネがヘロデに、「兄弟の妻をめとるのは、よろしくない」と言ったからである。イエスはまずどのようなやり取りをしますか。（3,4）

        -   イエスの教えを聞いていたのかもしれない。

            -   マタイ5:31-32 また『妻を出す者は離縁状を渡せ』と言われている。32 しかし、わたしはあなたがたに言う。だれでも、不品行以外の理由で自分の妻を出す者は、姦淫を行わせるのである。また出された女をめとる者も、姦淫を行うのである。

4.  イエスは、どのようなことを教えますか。（5-9）

    -   5 そこでイエスは言われた、「モーセはあなたがたの心が、かたくななので、あなたがたのためにこの定めを書いたのである。6 しかし、天地創造の初めから、『神は人を男と女とに造られた。7 それゆえに、人はその父母を離れ、8 ふたりの者は一体となるべきである』。彼らはもはや、ふたりではなく一体である。9 だから、神が合わせられたものを、人は離してはならない」。

    -   \[DQ\] 「あなたがたの心がかたくななので」は、何を意味しているのでしょうか。

        -   結婚を神のわざと考えず、離婚をしようとする。離婚によってもたらされる悲劇を最低限にするため。

    -   \[DQ\] 引用箇所を確認しましょう。どこに書かれていますか。

        -   創世記1:27 神は自分のかたちに人を創造された。すなわち、神のかたちに創造し、男と女とに創造された。

        -   創世記2:18 また主なる神は言われた、「人がひとりでいるのは良くない。彼のために、ふさわしい助け手を造ろう」。

        -   創世記2:20 それで人は、すべての家畜と、空の鳥と、野のすべての獣とに名をつけたが、人にはふさわしい助け手が見つからなかった。

        -   創世記2:23 そのとき、人は言った。「これこそ、ついにわたしの骨の骨、／わたしの肉の肉。男から取ったものだから、／これを女と名づけよう」。

        -   創世記2:24 それで人はその父と母を離れて、妻と結び合い、一体となるのである。

    -   \[DQ\] イエスは結婚についてどのように教えていますか。

        -   \[Q\] これは、新しい教えなのでしょうか。

        -   \[Q\] 質問者は、これで満足したのでしょうか。

5.  さらに、弟子たちには、どのように教えますか。（10-12）

    -   10 家にはいってから、弟子たちはまたこのことについて尋ねた。11 そこで、イエスは言われた、「だれでも、自分の妻を出して他の女をめとる者は、その妻に対して姦淫を行うのである。12 また妻が、その夫と別れて他の男にとつぐならば、姦淫を行うのである」。

    -   \[DQ\] 弟子たちは、なぜ、家にはいってから、また尋ねたのでしょうか。何を知りたかったのでしょうか。

        -   身近な現実の問題なので、パリサイ人と、群衆と、弟子たち、関心はあまり差がなかったのかもしれない。

    -   \[DQ\] 「姦淫」とはどのようなことですか。これは、どのような罪なのでしょうか。

        -   日本国語大辞典：男女が道義に反する肉体関係を結ぶこと。不倫な情事。

        -   マタイ5:27-30 『姦淫するな』と言われていたことは、あなたがたの聞いているところである。28 しかし、わたしはあなたがたに言う。だれでも、情欲をいだいて女を見る者は、心の中ですでに姦淫をしたのである。29 もしあなたの右の目が罪を犯させるなら、それを抜き出して捨てなさい。五体の一部を失っても、全身が地獄に投げ入れられない方が、あなたにとって益である。30 もしあなたの右の手が罪を犯させるなら、それを切って捨てなさい。五体の一部を失っても、全身が地獄に落ち込まない方が、あなたにとって益である。

6.  イエスは、なにをたいせつなこととして教えているのでしょうか。

    -   \[DQ\] どのようなことを正しているのでしょうか。
        -   なには、赦されるのかを問うている。つまり、実際には、姦淫に興味がある。それを正当化する方法を探している。そのような、価値観に挑戦している。
        -   ちいさきものに目を向けると同時に、ちいさなことには、目を向けないで、神様のみこころを求める。
    -   \[DQ\] パリサイ人は、何を最終根拠とし、イエスは、何を最終根拠としているのでしょうか。
        -   パリサイ人は、律法に書いてあること、それをどう解釈するか、または解釈された律法を最終基準としているが、イエスは、神様のみこころを最終基準としているように見える。

### メモ

-   場所は不明だが、なにか、緊張感が薄いようにも見える。ガリラヤなのか、離れた場所なのか。

-   結婚の神聖さについての、教えなのだろうか。最初に試そうとしてを正確に理解しないといけない。

-   イエスは、正しいことをここで述べているとすると、ひとをさばくことにもつながる。しかし、より、一般的なことを述べているようにも、みえる。すなわち、かみさまのみこころとの向き合い方だろうか。自分の都合の良い解釈を選択するのはもってのほかだが、わからないことをも許容しないと、裁きとなる。

-   同時に、離婚があまりに、軽く考えられている現代に対して、問も投げかけている。なんでも理由をみつけて離婚にいたる（性格の不一致）ことでよいのだろうか。み心を求め続けるものでありたい。

-   山上の説教でも、姦淫のこと（マタイ5:27-30）、離婚のこと（マタイ5:31-32）について語っているので、パリサイ人も聞いて知っていたかもしれない。すなわち、イエスの答えも、知っていたかもしれない。しかし、ここでは、そのあと、あえて問うていないように見える。

-   パリサイ人は、律法に書いてあること、それをどう解釈するか、または解釈された律法を最終基準としている（記録された神の御心と思われるもの）が、イエスは、神様のみこころを最終基準としているように見える。後者のように生きられればよいだろうが、それは、可能なのだろうか。おそらく、神のみこころを求めることを、大切にするということなのだろう。

## 10:13-16 子どもを祝福する

> 13 イエスにさわっていただくために、人々が幼な子らをみもとに連れてきた。ところが、弟子たちは彼らをたしなめた。14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。16 そして彼らを抱き、手をその上において祝福された。

### マタイ 19:13-15

> 13 そのとき、イエスに手をおいて祈っていただくために、人々が幼な子らをみもとに連れてきた。ところが、弟子たちは彼らをたしなめた。14 するとイエスは言われた、「幼な子らをそのままにしておきなさい。わたしのところに来るのをとめてはならない。天国はこのような者の国である」。15 そして手を彼らの上においてから、そこを去って行かれた。

### ルカ 18:15-17

> 15 イエスにさわっていただくために、人々が幼な子らをみもとに連れてきた。ところが、弟子たちはそれを見て、彼らをたしなめた。16 するとイエスは幼な子らを呼び寄せて言われた、「幼な子らをわたしのところに来るままにしておきなさい、止めてはならない。神の国はこのような者の国である。17 よく聞いておくがよい。だれでも幼な子のように神の国を受け入れる者でなければ、そこにはいることは決してできない」。

[マルコによる福音書10章13-16節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_13-16.pdf)

### 問い

1.  このことは、どのような背景のもとで起きましたか。

2.  誰が、何の目的のために、幼な子らを連れてきますか。（13a）

3.  弟子たちはどうしますか。それは、なぜでしょうか。（13b）

4.  イエスはどうしますか。（14,16）

5.  イエスはさらにどのようなことを教えていますか。（14,15）

6.  人々にとって、弟子たちにとって、イエスにとって、あなたにとって、幼な子は、どのような存在ですか。

### 参照

-   幼な子（παιδίον：a young child, a little boy, a little girl， a) infants, b) children, little ones, c) an infant of a (male) child just recently born, of a more advanced child; of a mature child; metaph. children (like children) in intellect）

    -   マルコ5:39,40,41 内にはいって、彼らに言われた、「なぜ泣き騒いでいるのか。子供は死んだのではない。眠っているだけである」。40 人々はイエスをあざ笑った。しかし、イエスはみんなの者を外に出し、子供の父母と供の者たちだけを連れて、子供のいる所にはいって行かれた。41 そして子供の手を取って、「タリタ、クミ」と言われた。それは、「少女よ、さあ、起きなさい」という意味である。

    -   マルコ7:28 すると女は答えて言った、「主よ、お言葉どおりです。でも、食卓の下にいる小犬も、子供たちのパンくずは、いただきます」。

    -   マルコ9:24 その子の父親はすぐ叫んで言った、「信じます。不信仰なわたしを、お助けください」。

    -   マルコ9:36,37 そして、ひとりの幼な子をとりあげて、彼らのまん中に立たせ、それを抱いて言われた。37 「だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。

    -   マルコ10:13,14,15 イエスにさわっていただくために、人々が幼な子らをみもとに連れてきた。ところが、弟子たちは彼らをたしなめた。14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。

    -   ルカでは、幼な子は、βρέφος: i) an unborn child, embryo, a foetus, ii) a new-born child, an infant, a babe、しかし、マルコの記述からは、走り回っているように見える。

-   こどもに関する聖書箇所

    -   マタイ21:16 イエスに言った、「あの子たちが何を言っているのか、お聞きですか」。イエスは彼らに言われた、「そうだ、聞いている。あなたがたは『幼な子（νήπιος： i） an infant, little child， ii）a minor, not of age， iii） metaph. childish, untaught, unskilled）、乳のみ子たち（θηλάζω：i） to give the breast, give suck, to suckle，ii）to suck）の口にさんびを備えられた』とあるのを読んだことがないのか」。

### 記録

-   日時：2024年6月6日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）4名

### 問いについて

1.  このことは、どのような背景のもとで起きましたか。

    -   1 それから、イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれたが、群衆がまた寄り集まったので、いつものように、また教えておられた。ここから新しい設定。

    -   1-13 「夫はその妻を出しても差しつかえないでしょうか」。の問に答えて。- おとなの事情のとりあつかい。

    -   17-22 金持ちの男との対話

        -   17 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。

        -   マタイ19:22 では、「青年（νεανίσκος： a young man, youth, used of a young attendant or servant）」マルコで使われているのは、14:51 と、16:5 のみ。

    -   23-31 弟子たちへの教え。「子を捨てたもの」

        -   29-31 「よく聞いておくがよい。だれでもわたしのために、また福音のために、家、兄弟、姉妹、母、父、子、もしくは畑を捨てた者は、30 必ずその百倍を受ける。すなわち、今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け、また、きたるべき世では永遠の生命を受ける。31 しかし、多くの先の者はあとになり、あとの者は先になるであろう」。

    -   こどものことは、この前後では、意識に入っていないように見える。その中で唐突な、短いエピソードに見える。

    -   マタイでは「そのとき」（19:13）

    -   \[DQ\] イエスはどのようなときにありますか。

        -   10:1 それから、イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれたが、群衆がまた寄り集まったので、いつものように、また教えておられた。

        -   受難と死と復活の告知の二回目（9:30-32）と三回目（10:32-34）の間。（1回目は8:31）

2.  誰が、何の目的のために、幼な子らを連れてきますか。（13a）

    -   13a イエスにさわっていただくために、人々が幼な子らをみもとに連れてきた。

    -   \[DQ\] 「さわっていただく」は、どのようなことを意味していますか。

        -   16 そして彼らを抱き、手をその上において祝福された。

        -   ユダヤ人は生後一年の赤ん坊を高名なラビに祝福してもらう習慣があった。（ルカ2:22-33）（出エジプト13章）

3.  弟子たちはどうしますか。それは、なぜでしょうか。（13b）

    -   13b ところが、弟子たちは彼らをたしなめた。

    -   \[DQ\] なぜ弟子たちは、幼な子らをイエスのもとに連れて来た人々をたしなめ（叱）るのでしょうか。

        -   イエスの受難告知以降、緊張状態にあったと思われる。「空気を読めないのか。」

        -   おとなの事情（離縁について）弟子たちが、より詳しく説明してもらいたい途中だった。「ちょっとあとにしてくれ。」

        -   カペナウムでのイエスのメッセージを忘れていた。「こどもなんかにかかわってはいられない」

            -   9:33-37 それから彼らはカペナウムにきた。そして家におられるとき、イエスは弟子たちに尋ねられた、「あなたがたは途中で何を論じていたのか」。34 彼らは黙っていた。それは途中で、だれが一ばん偉いかと、互に論じ合っていたからである。35 そこで、イエスはすわって十二弟子を呼び、そして言われた、「だれでも一ばん先になろうと思うならば、一ばんあとになり、みんなに仕える者とならねばならない」。36 そして、ひとりの幼な子をとりあげて、彼らのまん中に立たせ、それを抱いて言われた。37 「だれでも、このような幼な子のひとりを、わたしの名のゆえに受けいれる者は、わたしを受けいれるのである。そして、わたしを受けいれる者は、わたしを受けいれるのではなく、わたしをおつかわしになったかたを受けいれるのである」。

            -   このメッセージを真剣にうけとることには、困難もある。

    -   \[DQ\] イエスが、教えておられる途中であればどうでしょうか。

        -   10:1 それから、イエスはそこを去って、ユダヤの地方とヨルダンの向こう側へ行かれたが、群衆がまた寄り集まったので、いつものように、また教えておられた。

        -   10:10 家にはいってから、弟子たちはまたこのことについて尋ねた。

        -   \[Q\] 教会での説教中に、こどもが、入ってきて、だれかのもとに走り寄ってきたらどうしますか。

4.  イエスはどうしますか。（14,16）

    -   14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。

    -   16 そして彼らを抱き、手をその上において祝福された。

    -   \[DQ\] 幼な子らの様子についてなにかわかりますか。

        -   わたしの所に来るままにしておきなさい。

            -   なすがままにさせる。ここに大切な目があるように感じる。

        -   イエスのもとに走ってくるものもいたのではないだろうか。まだ、カペナウム周辺にいたとすると、イエスを知っていたかもしれない。

    -   \[DQ\] イエスは、なぜ、受難告知以降も、このように振る舞われるのでしょうか。

    -   \[DQ\] 憤るとはどのようなことでしょうか。

        -   ἀγανακτέω: to be indignant, moved with indignation, be very displeased

        -   マタイ20:24、21:15、26:8、マルコ10:14、41、14:4、ルカ13:14

    -   \[DQ\] 「神の国はこのような者の国である。」とは、どのような意味でしょうか。

        -   \[Q\] なぜ、幼な子のような者の国なのでしょうか。

    -   \[DQ\] ここで言われている、幼な子のなにかの特色について言われているのでしょうか。

        -   まだ、おとなになっていない、成長途中、成長している存在である。いきいきと生きることは成長し続けること、学び続けること。

        -   バークレイ：謙遜、従順、信頼、長く覚えていない

        -   榊原：子どもの示す美徳の第一は、嬉々として贈り物を受け取る能力・受容力です。「ただほど高いものはない」というのがおとなの哲学ですから「こどものように神の国を受け入れる」ことができるのは、大変な能力です。その能力を強調すうるため、ルカは「幼子（嬰児）」とした。なんのためらいもなく「来る」平然とした態度。

    -   \[DQ\] イエスは最後に抱いて、祝福をしていますが、どのようなことを表していますか。

        -   ἐναγκαλίζομαι：to take into one's arms, embrace（マルコ9:36、10:16）

    -   \[DQ\] イエスの祝福はどのようなものなのでしょうか。

        -   「あなたは愛されています。」by TV evangelist, Rex Humbard

        -   「神の国はこの（あなたの）ような者の国である。」（14）

        -   「あなたの人生が神様に祝福されたすばらしいものでありますように」

5.  イエスはさらにどのようなことを教えていますか。（14,15）

    -   14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。

    -   \[DQ\] 幼な子のように神の国を受け入れるとはどういうことでしょうか。

    -   \[DQ\] 「幼な子」の対極「幼な子ではない」とは、どのような人のことでしょうか。

        -   成長しないもの、成長しきったと思っているもの、変われないもの、不完全さを体さないもの。

        -   おとなの事情をならべたてて、離縁をかんがえるひとたち。

        -   次のエピソードの「金持ち」？

    -   離婚の話のあとに、こどもは、大切なものであることを、示している。

        -   教育ママ、育児ノイローゼとは異なる。

6.  人々にとって、弟子たちにとって、イエスにとって、あなたにとって、幼な子は、どのような存在ですか。

    -   不完全な存在。不完全さを知っていてときに応じて誰かに頼る。

    -   未来・将来の担うものたち

    -   \[DQ\] あなたは、こどもたち、おさなごたちのために祈るとしたら、どのように祈りますか。

### メモ

-   「離縁についての教え」と、「金持ちの男」の話に挟まれた、「子どもを祝福する」話。

    -   「先生、それらの事はみな、小さい時から守っております」という男に対するイエスのいつくしみ

-   マルコの思い出としてのイエス

    -   マルコもイエスに会ったことがあるのかもしれない。覚えていなくても、祝福してもらったよとか、もう少し大きくなっていたら、こどもをいつくしまれたイエスを覚えているのではないだろうか。

-   イエスはどのような祝福の祈りをしたのだろうか。

    -   このあとには、イエスの死があり、ステパノなどからのキリスト教会の迫害があり、AD70 には、エルサレム陥落、散り散りになってしまうときも来る。そのようなことを考えること自体が、この箇所からは離れてしまっているのかもしれない。イエスの祝福のいのりを、受け取りたい。

-   こども、おさなごとは

    -   14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。

    -   よくわからないが、離縁の正当化を考えたり、富のゆえに、イエスに従うことができなくなる、それは、幼子ではすでにないのだろう。考えさせられる。

-   よいこどもとは

    -   おとなにとって都合の良いこどもがよい子どもではないだろう。しかし、往々にして、良い子だねと言われる子は、おとなにとって都合の良い子どもの場合が多い。おとなの願いをかなえるこどもがよいこどもだろうか。おそらく、そうでもないだろう。ましてや、おとなの悔しさを晴らす存在がよいこどもでもないはずだ。しかし、同時に、おとなにとって都合が良くないこどもは、手間がかかり、周囲のおとなを疲弊させる存在でもある。社会的養護のための、児童養護施設でも、こどもをどのような存在とみるかは、とても難しい。現実は厳しいからである。どうじに、どんなこどもが、良い子どもなのか。イエス様が、おさなごのように、神の国を受け入れるものでなければと言われる、こどもとは、どのような存在なのかと考えてしまう。

## 10:17-31 金持ちの男

> 17 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。18 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。19 いましめはあなたの知っているとおりである。『殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え』」。20 すると、彼は言った、「先生、それらの事はみな、小さい時から守っております」。21 イエスは彼に目をとめ、いつくしんで言われた、「あなたに足りないことが一つある。帰って、持っているものをみな売り払って、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。22 すると、彼はこの言葉を聞いて、顔を曇らせ、悲しみながら立ち去った。たくさんの資産を持っていたからである。
>
> 23 それから、イエスは見まわして、弟子たちに言われた、「財産のある者が神の国にはいるのは、なんとむずかしいことであろう」。24 弟子たちはこの言葉に驚き怪しんだ。イエスは更に言われた、「子たちよ、神の国にはいるのは、なんとむずかしいことであろう。25 富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。26 すると彼らはますます驚いて、互に言った、「それでは、だれが救われることができるのだろう」。27 イエスは彼らを見つめて言われた、「人にはできないが、神にはできる。神はなんでもできるからである」。
>
> 28 ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。29 イエスは言われた、「よく聞いておくがよい。だれでもわたしのために、また福音のために、家、兄弟、姉妹、母、父、子、もしくは畑を捨てた者は、30 必ずその百倍を受ける。すなわち、今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け、また、きたるべき世では永遠の生命を受ける。31 しかし、多くの先の者はあとになり、あとの者は先になるであろう」。

### マタイ 19:16-30

> 16 すると、ひとりの人がイエスに近寄ってきて言った、「先生、永遠の生命を得るためには、どんなよいことをしたらいいでしょうか」。17 イエスは言われた、「なぜよい事についてわたしに尋ねるのか。よいかたはただひとりだけである。もし命に入りたいと思うなら、いましめを守りなさい」。18 彼は言った、「どのいましめですか」。イエスは言われた、「『殺すな、姦淫するな、盗むな、偽証を立てるな。19 父と母とを敬え』。また『自分を愛するように、あなたの隣り人を愛せよ』」。20 この青年はイエスに言った、「それはみな守ってきました。ほかに何が足りないのでしょう」。21 イエスは彼に言われた、「もしあなたが完全になりたいと思うなら、帰ってあなたの持ち物を売り払い、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。22 この言葉を聞いて、青年は悲しみながら立ち去った。たくさんの資産を持っていたからである。
>
> 23 それからイエスは弟子たちに言われた、「よく聞きなさい。富んでいる者が天国にはいるのは、むずかしいものである。24 また、あなたがたに言うが、富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。25 弟子たちはこれを聞いて非常に驚いて言った、「では、だれが救われることができるのだろう」。26 イエスは彼らを見つめて言われた、「人にはそれはできないが、神にはなんでもできない事はない」。
>
> 27 そのとき、ペテロがイエスに答えて言った、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従いました。ついては、何がいただけるでしょうか」。28 イエスは彼らに言われた、「よく聞いておくがよい。世が改まって、人の子がその栄光の座につく時には、わたしに従ってきたあなたがたもまた、十二の位に座してイスラエルの十二の部族をさばくであろう。29 おおよそ、わたしの名のために、家、兄弟、姉妹、父、母、子、もしくは畑を捨てた者は、その幾倍もを受け、また永遠の生命を受けつぐであろう。30 しかし、多くの先の者はあとになり、あとの者は先になるであろう。

### ルカ 18:18-30

> 18 また、ある役人がイエスに尋ねた、「よき師よ、何をしたら永遠の生命が受けられましょうか」。19 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。20 いましめはあなたの知っているとおりである、『姦淫するな、殺すな、盗むな、偽証を立てるな、父と母とを敬え』」。21 すると彼は言った、「それらのことはみな、小さい時から守っております」。22 イエスはこれを聞いて言われた、「あなたのする事がまだ一つ残っている。持っているものをみな売り払って、貧しい人々に分けてやりなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。23 彼はこの言葉を聞いて非常に悲しんだ。大金持であったからである。 
>
> 24 イエスは彼の様子を見て言われた、「財産のある者が神の国にはいるのはなんとむずかしいことであろう。25 富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。26 これを聞いた人々が、「それでは、だれが救われることができるのですか」と尋ねると、27 イエスは言われた、「人にはできない事も、神にはできる」。
>
> 28 ペテロが言った、「ごらんなさい、わたしたちは自分のものを捨てて、あなたに従いました」。29 イエスは言われた、「よく聞いておくがよい。だれでも神の国のために、家、妻、兄弟、両親、子を捨てた者は、30 必ずこの時代ではその幾倍もを受け、また、きたるべき世では永遠の生命を受けるのである」。 

[マルコによる福音書10章17-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-31.pdf)

## 10:17-22 金持ちの男（1）

> 17 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。18 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。19 いましめはあなたの知っているとおりである。『殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え』」。20 すると、彼は言った、「先生、それらの事はみな、小さい時から守っております」。21 イエスは彼に目をとめ、いつくしんで言われた、「あなたに足りないことが一つある。帰って、持っているものをみな売り払って、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。22 すると、彼はこの言葉を聞いて、顔を曇らせ、悲しみながら立ち去った。たくさんの資産を持っていたからである。

### マタイ 19:16-22

> 16 すると、ひとりの人がイエスに近寄ってきて言った、「先生、永遠の生命を得るためには、どんなよいことをしたらいいでしょうか」。17 イエスは言われた、「なぜよい事についてわたしに尋ねるのか。よいかたはただひとりだけである。もし命に入りたいと思うなら、いましめを守りなさい」。18 彼は言った、「どのいましめですか」。イエスは言われた、「『殺すな、姦淫するな、盗むな、偽証を立てるな。19 父と母とを敬え』。また『自分を愛するように、あなたの隣り人を愛せよ』」。20 この青年はイエスに言った、「それはみな守ってきました。ほかに何が足りないのでしょう」。21 イエスは彼に言われた、「もしあなたが完全になりたいと思うなら、帰ってあなたの持ち物を売り払い、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。22 この言葉を聞いて、青年は悲しみながら立ち去った。たくさんの資産を持っていたからである。

### ルカ 18:18-23

> 18 また、ある役人がイエスに尋ねた、「よき師よ、何をしたら永遠の生命が受けられましょうか」。19 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。20 いましめはあなたの知っているとおりである、『姦淫するな、殺すな、盗むな、偽証を立てるな、父と母とを敬え』」。21 すると彼は言った、「それらのことはみな、小さい時から守っております」。22 イエスはこれを聞いて言われた、「あなたのする事がまだ一つ残っている。持っているものをみな売り払って、貧しい人々に分けてやりなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。23 彼はこの言葉を聞いて非常に悲しんだ。大金持であったからである。 

[マルコによる福音書10章17-22節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_17-22.pdf)

### 問い

1.  このことは、どのような背景のもとで起きましたか。

2.  どのように、イエスに問うことから、はじまりますか。（17）

3.  イエスは、どのように応答しますか。（18,19）

4.  このひとの答えなどから、わかることをあげてみましょう。（20）

5.  イエスは、どのようにこのひとに命じますか。（21）

6.  このひとの求めていたものと、イエスが告げたこととには、どのような開きがあったのでしょうか。（22）

### 参照

-   弟子たちに語る後半が続き、マタイではこのあとに「ぶどう園の労働者」のたとえ（20:1-16）が挿入されている
-   十戒
    -   出エジプト記34章28節 モーセは主と共に、四十日四十夜、そこにいたが、パンも食べず、水も飲まなかった。そして彼は契約の言葉、十誡（聖書協会共同訳：十の言葉）を板の上に書いた。
    -   出エジプト記20章1-17節 1 神はこのすべての言葉を語って言われた。2 「わたしはあなたの神、主であって、あなたをエジプトの地、奴隷の家から導き出した者である。3 あなたはわたしのほかに、なにものをも神としてはならない。4 あなたは自分のために、刻んだ像を造ってはならない。上は天にあるもの、下は地にあるもの、また地の下の水のなかにあるものの、どんな形をも造ってはならない。5 それにひれ伏してはならない。それに仕えてはならない。あなたの神、主であるわたしは、ねたむ神であるから、わたしを憎むものには、父の罪を子に報いて、三、四代に及ぼし、6 わたしを愛し、わたしの戒めを守るものには、恵みを施して、千代に至るであろう。7 あなたは、あなたの神、主の名を、みだりに唱えてはならない。主は、み名をみだりに唱えるものを、罰しないでは置かないであろう。8 安息日を覚えて、これを聖とせよ。9 六日のあいだ働いてあなたのすべてのわざをせよ。10 七日目はあなたの神、主の安息であるから、なんのわざをもしてはならない。あなたもあなたのむすこ、娘、しもべ、はしため、家畜、またあなたの門のうちにいる他国の人もそうである。11 主は六日のうちに、天と地と海と、その中のすべてのものを造って、七日目に休まれたからである。それで主は安息日を祝福して聖とされた。12 あなたの父と母を敬え。これは、あなたの神、主が賜わる地で、あなたが長く生きるためである。13 あなたは殺してはならない。14 あなたは姦淫してはならない。15 あなたは盗んではならない。16 あなたは隣人について、偽証してはならない。17 あなたは隣人の家をむさぼってはならない。隣人の妻、しもべ、はしため、牛、ろば、またすべて隣人のものをむさぼってはならない」。
    -   申命記5:1-21 17 あなたは殺してはならない。18 あなたは姦淫してはならない。19 あなたは盗んではならない。20 あなたは隣人について偽証してはならない。21 あなたは隣人の妻をむさぼってはならない。また隣人の家、畑、しもべ、はしため、牛、ろば、またすべて隣人のものをほしがってはならない
-   エペソ6:1-3 子たる者よ。主にあって両親に従いなさい。これは正しいことである。2 「あなたの父と母とを敬え」。これが第一の戒めであって、次の約束がそれについている、3 「そうすれば、あなたは幸福になり、地上でながく生きながらえるであろう」。（約束を伴う戒め）
-   ヒエロニムス『オリゲネスのマタイによる福音書注解ラテン語訳（偽オリゲネス）』ヘブル人による、と称されるある福音書に、（もし少なくともこれを権威の書としてではなく、今の問題に光を投げかけるものとして受け取る注意を払うなら）、次のように記されている。そこで主は彼に言われた。あなたはどうして、律法と預言者を守ったと言うのか。律法には『隣人を自分のように愛せよ』と書かれている。しかも見よ、おおぜいのあなたの同胞、アブラハムの子たちが、汚れをまとい、飢え死にしそうなのに、あなたの屋敷は多くの良き物で満ちていて、そのうちから何一つ彼らの手に渡らないのだ。それから、かたわらに座していたシモンに振り向いて言われた。バル・ヨナ・シモン。富めるものが天国にはいるよりも、らくだが針の穴を通るほうがたやすい。（榊原康夫著『聖書講解　ルカの福音書』より）

### 記録

-   日時：2024年6月13日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）2名

### 問いについて

1.  このことは、どのような背景のもとで起きましたか。

    -   離縁についてのパリサイ人の質問とイエスの答え、そして、弟子たちとの対話

        -   4b 「モーセはあなたがたの心が、かたくななので、あなたがたのためにこの定めを書いたのである。6 しかし、天地創造の初めから、『神は人を男と女とに造られた。7 それゆえに、人はその父母を離れ、8 ふたりの者は一体となるべきである』。彼らはもはや、ふたりではなく一体である。9 だから、神が合わせられたものを、人は離してはならない」。

    -   おさなごの祝福

        -   14b 神の国はこ（幼な子ら）のような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない

    -   17 イエスが道に出て行かれると、

        -   家から出ていったように見える。

2.  どのように、イエスに問うことから、はじまりますか。（17）

    -   17 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。

    -   \[DQ\] このひとの様子はどのように描かれていますか。どのようなことを感じますか。

        -   「イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、」からは、特別な状態を感じる。ある程度若かったのではないか。（マタイでは青年）しかし、富を持ち、ルカでは「役人」としている。ある興奮状態も感じるが、ここを逃してはいけないという緊迫感、必死さも感じる。

    -   \[DQ\] イエスに何と呼びかけていますか。

        -   「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」 Διδάσκαλε ἀγαθέ τί ποιήσω ἵνα ζωὴν αἰώνιον κληρονομήσω

            -   διδάσκαλος: 1) a teacher, 2) in the NT one who teaches concerning the things of God, and the duties of man, i) one who is fitted to teach, or thinks himself so, ii) the teachers of the Jewish religion, iii) of those who by their great power as teachers draw crowds around them i.e. John the Baptist, Jesus, iv) by preeminence used of Jesus by himself, as one who showed men the way of salvation, v) of the apostles, and of Paul, vi) of those who in the religious assemblies of the Christians, undertook the work of teaching, with the special assistance of the Holy Spirit, vii) of false teachers among Christians

            -   κληρονομέω: 1) to receive a lot, receive by lot i) esp. to receive a part of an inheritance, receive as an inheritance, obtain by right of inheritance, ii) to be an heir, to inherit

    -   \[DQ\] 「永遠の生命を受ける（遺産として受ける）」とは、どのようなことを求めているのでしょうか。

        -   \[Q\] 永遠の命とはどのようなものと理解していたのでしょうか。

            -   神の国にあずかるものに与えられるいのち。神様との交わり。

            -   ヨハネ前書1:1-4 初めからあったもの、わたしたちが聞いたもの、目で見たもの、よく見て手でさわったもの、すなわち、いのちの言について――2 このいのちが現れたので、この永遠のいのちをわたしたちは見て、そのあかしをし、かつ、あなたがたに告げ知らせるのである。この永遠のいのちは、父と共にいましたが、今やわたしたちに現れたものである―― 3すなわち、わたしたちが見たもの、聞いたものを、あなたがたにも告げ知らせる。それは、あなたがたも、わたしたちの交わりにあずかるようになるためである。わたしたちの交わりとは、父ならびに御子イエス・キリストとの交わりのことである。4 これを書きおくるのは、わたしたちの喜びが満ちあふれるためである。

    -   \[DQ\] このひとは、何によって、永遠の命を受けることができと考えていたでしょうか。

        -   なにかをすることによって。

    -   \[DQ\] この節からは、この人についてどのようなことがわかりますか。

        -   「ひざまずく」は礼拝に近い。一般的な「教師（ラビ）」に対するよりも、特別なものと認識している可能性もある。「走り寄り」からも、とくべつな思いが見て取れる。

3.  イエスは、どのように応答しますか。（18,19）

    -   18 イエスは言われた、「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。19 いましめはあなたの知っているとおりである。『殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え』」。

    -   マタイ19:18,19 彼は言った、「どのいましめですか」。イエスは言われた、「『殺すな、姦淫するな、盗むな、偽証を立てるな。19 父と母とを敬え』。また『自分を愛するように、あなたの隣り人を愛せよ』」。（レビ19:18 を加えている。）

    -   ルカ18:20 いましめはあなたの知っているとおりである、『姦淫するな、殺すな、盗むな、偽証を立てるな、父と母とを敬え』」。

    -   \[DQ\] 「なぜわたしをよき者と言うのか。神ひとりのほかによい者はいない。」は、なにを気づかせようとしているのでしょうか。

        -   出鼻をくじいているようにも見える。

        -   師を見る（興奮する）のではなく、神をみなければならない。

        -   バークレイ：とどまって感がえなさい。あたなは全く興奮しており、また感情が高ぶっている。わたしは、あなたが興奮して、わたしのところに来るのを好まない。あなたのしていることを冷静に考えなさい。わたしに対する感傷的な情熱ではクリスチャンになれない。神を見なければならない。

    -   \[DQ\] 『殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え』この戒めを混燃えれば、永遠のいのちがえられるのでしょうか。

        -   通常は、父と母を敬えのほうが最初に来る。ここでは、最後になっている。マルコ7:9-13 との関連で、特別なものとしたのか、それとも、すでに、財産を相続していたことを知っていたのかもしれない。

    -   \[DQ\] イエスは、なにを気づかせようとしているのでしょうか。

4.  このひとの答えなどから、わかることをあげてみましょう。（20）

    -   20 すると、彼は言った、「先生、それらの事はみな、小さい時から守っております」。

        -   ピリピ3:6 熱心の点では教会の迫害者、律法の義については落ち度のない者である。

    -   マタイ19:20：「それはみな守ってきました。ほかに何が足りないのでしょう」

    -   「殺すな、姦淫するな、盗むな、偽証を立てるな。欺き取るな。父と母とを敬え」をずっと守ってきた。

    -   \[DQ\] これらは、どのような教えですか。

        -   十戒からとったと思われるが、父と母を敬え以外は、何かをするなという禁止命令。守ってきたは、悪いことはしていないということか。

    -   このひとの応答を見る限りにおいて、永遠の命をえることができそうであることに鍵があるのだろう。

5.  イエスは、どのようにこのひとに命じますか。（21）

    -   21 イエスは彼に目をとめ、いつくしんで言われた、「あなたに足りないことが一つある。帰って、持っているものをみな売り払って、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。

    -   マタイ19:21 イエスは彼に言われた、「もしあなたが完全になりたいと思うなら、帰ってあなたの持ち物を売り払い、貧しい人々に施しなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。

    -   ルカ18:22 イエスはこれを聞いて言われた、「あなたのする事がまだ一つ残っている。持っているものをみな売り払って、貧しい人々に分けてやりなさい。そうすれば、天に宝を持つようになろう。そして、わたしに従ってきなさい」。

    -   \[DQ\] イエスは、なにが足りないと言っているのでしょうか。

        -   「あなたにたりないことが一つある。」といっているが、そこで、示しているのは、「帰って、持っているものをみな売り払って、貧しい人々に施しなさい。」である。しかし、それが、難しいことは、イエスもおそらく知っていただろう。

        -   続けて「そうすれば、天に宝を持つようになろう。」と言っている。まず、よき師よから、神様に目を向けるように指し示されたように、ここでも、指し示されているのは、天に（神様のもとに）宝を持つことなのだろう。どうしたら、神様のみこころのように生きられるか。み心を生きることができるか。

        -   さらに、「そして、わたしに従ってきなさい」と言っている。このときに、イエスに従っているものは多くないだろう。そして、エルサレムに向かっている。イエスに従うということは、このような道であることを示して入るだろう。このときには、応答できなくても、後には、そのように、ある程度できたかもしれない。イエスは、その先をもみて、慈しんで（ὁ δὲ Ἰησοῦς ἐμβλέψας αὐτῷ ἠγάπησεν αὐτὸν καὶ εἶπεν αὐτῷ）言われたのではないだろうか。

        -   足りないというより、たいせつなことを教えておられるのだろう。最後のレッスンとして。

    -   \[DQ\] マタイやルカとも比較してみましょう。

        -   マタイ19:19b また『自分を愛するように、あなたの隣り人を愛せよ』が挟まっている。

        -   ルカ18:22b あなたのする事がまだ一つ残っている。

    -   \[DQ\] イエスが伝えていることは何なのでしょうか。

        -   バークレイ：因襲道徳のこだわりから抜け出しなさい。善とは、なにかをなすことによっては成り立っていないと考えるのはやめなさい。あなた自身の持ち物のすべてを他の人々のために、用いなさい。するとこの世においても、また永遠にいたるまで、真の幸せを見出すであろう。

6.  このひとの求めていたものと、イエスが告げたこととには、どのような開きがあったのでしょうか。（22）

    -   22 すると、彼はこの言葉を聞いて、顔を曇らせ、悲しみながら立ち去った。たくさんの資産を持っていたからである。

    -   明らかに、このひとにそれはできなかった。なにをすればの答えを聞くと、それは、できないことだった。

    -   \[DQ\] このひとが、永遠の命を受け継ぐにはどうしたらよいのでしょうか。

### メモ

-   三回に分けるか、二回に分けるか：17-22と23-26, 27-31
-   「慈しんで」はなにを意味するのだろうか。
-   最初から「イエスに従いたい」とは言っていない。
-   場所は不明だが、家をカペナウムのペテロの家（カペナウムを本拠地とし、しばしば十二弟子とそこに泊まったとすると、ペテロの家ではないかもしれない。定宿があったのかもしれない。ゼベダイの子ヤコブとヨハネもこのあたりの出身で、網元でも会ったようにみえるから）だとすると、イエスは、このひとを以前から知っていたかもしれない。この熱心さにも、危うさもふくめて、このひとについて、知っていたのかもしれない。ときは、イエスが、エルサレムに向かっている特別なときである。そして、おそらく、十二弟子以外は（多少の女性はいたかもしれないが）離れ去ったときであることも、加味すべきだろう。このひとの願いも、最後の願い、イエスにとっても、最後の授業として教えたのではないだろうか。慈しみの眼差しは、もっと長い目で見た、イエスの愛なのかもしれない。一般論として、このときだけに限って、無理に解釈することには、注意すべきである。
-   以前のマタイによる福音書からの学びに「この人が持ち物を売り払い、貧しい人々に施すとどうなったと思いますか。」という問いがあったが、これも、興味深い問である。単純に、貧しくなった、貧しい人々の気持ちがわかるようになったかなど、どうなったかもあるだろう。しかし、ここで終わらず、イエスは、わたしに従ってきなさいと言っている、その部分がより際立つのかもしれないとも思う。

## 10:23-31 金持ちの男（2）

> 23 それから、イエスは見まわして、弟子たちに言われた、「財産のある者が神の国にはいるのは、なんとむずかしいことであろう」。24 弟子たちはこの言葉に驚き怪しんだ。イエスは更に言われた、「子たちよ、神の国にはいるのは、なんとむずかしいことであろう。25 富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。26 すると彼らはますます驚いて、互に言った、「それでは、だれが救われることができるのだろう」。27 イエスは彼らを見つめて言われた、「人にはできないが、神にはできる。神はなんでもできるからである」。
>
> 28 ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。29 イエスは言われた、「よく聞いておくがよい。だれでもわたしのために、また福音のために、家、兄弟、姉妹、母、父、子、もしくは畑を捨てた者は、30 必ずその百倍を受ける。すなわち、今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け、また、きたるべき世では永遠の生命を受ける。31 しかし、多くの先の者はあとになり、あとの者は先になるであろう」。

### マタイ 19:23-30

> 23 それからイエスは弟子たちに言われた、「よく聞きなさい。富んでいる者が天国にはいるのは、むずかしいものである。24 また、あなたがたに言うが、富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。25 弟子たちはこれを聞いて非常に驚いて言った、「では、だれが救われることができるのだろう」。26 イエスは彼らを見つめて言われた、「人にはそれはできないが、神にはなんでもできない事はない」。
>
> 27 そのとき、ペテロがイエスに答えて言った、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従いました。ついては、何がいただけるでしょうか」。28 イエスは彼らに言われた、「よく聞いておくがよい。世が改まって、人の子がその栄光の座につく時には、わたしに従ってきたあなたがたもまた、十二の位に座してイスラエルの十二の部族をさばくであろう。29 おおよそ、わたしの名のために、家、兄弟、姉妹、父、母、子、もしくは畑を捨てた者は、その幾倍もを受け、また永遠の生命を受けつぐであろう。30 しかし、多くの先の者はあとになり、あとの者は先になるであろう。

### ルカ 18:24-30

> 24 イエスは彼の様子を見て言われた、「財産のある者が神の国にはいるのはなんとむずかしいことであろう。25 富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。26 これを聞いた人々が、「それでは、だれが救われることができるのですか」と尋ねると、27 イエスは言われた、「人にはできない事も、神にはできる」。
>
> 28 ペテロが言った、「ごらんなさい、わたしたちは自分のものを捨てて、あなたに従いました」。29 イエスは言われた、「よく聞いておくがよい。だれでも神の国のために、家、妻、兄弟、両親、子を捨てた者は、30 必ずこの時代ではその幾倍もを受け、また、きたるべき世では永遠の生命を受けるのである」。 

[マルコによる福音書10章23-31節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_23-31.pdf)

### 問い

1.  背景と、前半部分（13節から22節）を復習しましょう。どのようなことがありましたか。

2.  イエスは、誰にむかってどのように語っていますか。その反応はどのようなものでしたか。（23,24a）

3.  神の国にはいることについて、イエスはどのように語っていますか。（24b-27）

4.  ペテロはどのようにイエスに言い、それにイエスはどう答えますか。（28-31）

5.  「多くの先の者はあとになり、あとの者は先になる」は、なにを教えているのでしょうか。（31）

6.  あなたは、神の国について、永遠の命について何を学び、どのように考えますか。（10:14,15,17参照）

### 参照

-   マタイではこのあとに「ぶどう園の労働者」のたとえ（20:1-16）が挿入されている

### 記録

-   日時：2024年6月27日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  背景と、前半部分（13節から22節）を復習しましょう。どのようなことがありましたか。

    -   10章は、離縁についてからはじまり、幼な子の祝福の記事が続き、金持ちの男の話につながっている。

    -   22 すると、彼はこの言葉を聞いて、顔を曇らせ、悲しみながら立ち去った。たくさんの資産を持っていたからである。

    -   \[DQ\] イエスと弟子たちはどのような眼差しでこのひとを見送っただろうか。

        -   おそらく、しばらく、ずっと見ていたのではないだろうか。とても、印象的な姿だが、もしかすると、このひとほどはっきりはしていなくても、そのような姿を、イエスも、弟子たちも何回も見ていたかもしれない。

        -   イエスはこの人に何を伝えようとしたのだろうか。それは、伝わったのだろうか。

        -   ルカには、立ち去ったという記述はない。「23 彼はこの言葉を聞いて非常に悲しんだ。大金持であったからである。」

2.  イエスは、誰にむかってどのように語っていますか。その反応はどのようなものでしたか。（23,24a）

    -   23 それから、イエスは見まわして、弟子たちに言われた、「財産のある者が神の国にはいるのは、なんとむずかしいことであろう」。24 弟子たちはこの言葉に驚き怪しんだ。

    -   \[DQ\] 弟子たちは、なぜ驚き怪しんだのでしょうか。

        -   参照：26 すると彼らはますます驚いて、互に言った、「それでは、だれが救われることができるのだろう」。

    -   \[DQ\] 財産・富は、神様の祝福の証ではないのでしょうか。（因果応報）

        -   詩篇37:25 わたしは、むかし年若かった時も、年老いた今も、／正しい人が捨てられ、あるいはその子孫が／食物を請いあるくのを見たことがない。

    -   \[DQ\] 財産のある者が神の国にはいるのがむずかしいのはなぜでしょうか。

        -   財産（χρῆμα: a thing, a matter, affair, event, business, spec. money, riches）Mark 10:23,24, Luke 18:24

        -   アリストテレス（BC384-322）貨幣制度によってその価値が評価されるすべてのもの。

        -   \[A\] バークレイ：①物質的な所有物は、人の心をこの世に固定させる。②金銭で買えるものの価値がすべてになる。③富はひとを傲慢にする。大きな責任を負う。

3.  神の国にはいることについて、イエスはどのように語っていますか。（24b-27）

    -   24b イエスは更に言われた、「子たちよ、神の国にはいるのは、なんとむずかしいことであろう。25 富んでいる者が神の国にはいるよりは、らくだが針の穴を通る方が、もっとやさしい」。26 すると彼らはますます驚いて、互に言った、「それでは、だれが救われることができるのだろう」。27 イエスは彼らを見つめて言われた、「人にはできないが、神にはできる。神はなんでもできるからである」。

    -   「それでは、だれが救われることができるのだろう」。は、インパクトを与えている。

    -   \[DQ\] なぜ彼らは「それでは、だれが救われることができるのだろう」。と言ったのでしょうか。

        -   幼な子・金持ちの対比もある。当時の感覚か。

4.  ペテロはどのようにイエスに言い、それにイエスはどう答えますか。（28-30）

    -   28 ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。29 イエスは言われた、「よく聞いておくがよい。だれでもわたしのために、また福音のために、家、兄弟、姉妹、母、父、子、もしくは畑を捨てた者は、30 必ずその百倍を受ける。すなわち、今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け、また、きたるべき世では永遠の生命を受ける。

    -   \[参考\] マタイでは、19:27b,28「ついては、何がいただけるでしょうか」。28 イエスは彼らに言われた、「よく聞いておくがよい。世が改まって、人の子がその栄光の座につく時には、わたしに従ってきたあなたがたもまた、十二の位に座してイスラエルの十二の部族をさばくであろう。」が、挿入されている。

    -   \[DQ\] イエスは、どのような「約束？」「預言」をしていますか。必ずそうなるのでしょうか。

    -   \[DQ\] 「福音のために捨てる」とはどのようなことを意味しているのでしょうか。

        -   マタイでは「29b わたしの名のため」

        -   ルカでは「29b 神の国のために」

    -   \[DQ\] 「だれでもわたしのために、また福音のために、家、兄弟、姉妹、母、父、子、もしくは畑を捨てた者は」どうなると言っていますか。「百倍」の内容は？

        -   \[Q\] 「今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け」とはどのような意味だろうか。

        -   \[Q\] 「きたるべき世では永遠の生命を受ける」とはどのような意味だろうか。

    -   \[DQ\] 「受ける」のは、いつのことでしょうか。

        -   30b すなわち、今この時代では家、兄弟、姉妹、母、子および畑を迫害と共に受け、また、きたるべき世では永遠の生命を受ける。

        -   マタイ：世が改まって、人の子がその栄光の座につく時

        -   ルカ：30 必ずこの時代ではその幾倍もを受け、また、きたるべき世では永遠の生命を受けるのである」。

5.  「多くの先の者はあとになり、あとの者は先になる」は、なにを教えているのでしょうか。（31）

    -   31 しかし、多くの先の者はあとになり、あとの者は先になるであろう」。

    -   \[DQ\] 弟子たちに伝えたかったことは何なのでしょうか。

    -   マタイでは、ぶどう園の労働者のたとえがつづき、最後に、また、この言葉が続いている。すなわち、この言葉の説明として、たとえを挿入しているようにみえる。

6.  あなたは、神の国について、永遠の命について何を学び、どのように考えますか。（10:14,15,17参照）

    -   10:14 それを見てイエスは憤り、彼らに言われた、「幼な子らをわたしの所に来るままにしておきなさい。止めてはならない。神の国はこのような者の国である。15 よく聞いておくがよい。だれでも幼な子のように神の国を受けいれる者でなければ、そこにはいることは決してできない」。

    -   17 イエスが道に出て行かれると、ひとりの人が走り寄り、みまえにひざまずいて尋ねた、「よき師よ、永遠の生命を受けるために、何をしたらよいでしょうか」。

    -   \[DQ\] 幼な子と金持ちの人とはなにが違うのでしょうか。

    -   \[DQ\] 金持ちの人は、全財産を施せば、永遠のいのちを得ることができたのでしょうか。

        -   おそらくそうではないだろう。「そして、わたしに従ってきなさい」ともついている。このことは、一つに過ぎないのだろう。イエスに、したがって学ぶことがある。しかし、本当にそうだろうか。イエスは、もうすぐ、死なれる。

### メモ

-   28 ペテロがイエスに言い出した、「ごらんなさい、わたしたちはいっさいを捨てて、あなたに従って参りました」。
    -   ペテロにとっては、これが彼の全てだったのだろう。
    -   マルコ1:16-18 さて、イエスはガリラヤの海べを歩いて行かれ、シモンとシモンの兄弟アンデレとが、海で網を打っているのをごらんになった。彼らは漁師であった。17 イエスは彼らに言われた、「わたしについてきなさい。あなたがたを、人間をとる漁師にしてあげよう」。18 すると、彼らはすぐに網を捨てて、イエスに従った。
    -   もっとほかに言うことはないのとも感じるが、これがペテロの富・財産の全てだったのだろう。それは、やはり素晴らしい。わたしには、いえないことのように思う。
-   教義としてとらえるのではなく、イエスが、伝えようとしたこと、弟子たちが、受け取ったことをまずは、理解したい。それは何なのだろう。
    -   イエスは、弟子たちになにを伝えたかったのだろうか。弟子たちは、なにを受け取ったのだろうか。

## 10:32-34 イエス、三度自分の死と復活を予告する

> 32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。

### マタイ 20:17-19

> 17 さて、イエスはエルサレムへ上るとき、十二弟子をひそかに呼びよせ、その途中で彼らに言われた、18 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に渡されるであろう。彼らは彼に死刑を宣告し、19 そして彼をあざけり、むち打ち、十字架につけさせるために、異邦人に引きわたすであろう。そして彼は三日目によみがえるであろう」。

### ルカ 18:31-34

> 31 イエスは十二弟子を呼び寄せて言われた、「見よ、わたしたちはエルサレムへ上って行くが、人の子について預言者たちがしるしたことは、すべて成就するであろう。32 人の子は異邦人に引きわたされ、あざけられ、はずかしめを受け、つばきをかけられ、33 また、むち打たれてから、ついに殺され、そして三日目によみがえるであろう」。34 弟子たちには、これらのことが何一つわからなかった。この言葉が彼らに隠されていたので、イエスの言われた事が理解できなかった。

[マルコによる福音書10章32-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark10_32-34.pdf)

### 問い

1.  この箇所と 8:31, 9:31 をくらべて共通のことと、新しいことを挙げてみましょう。

2.  マタイ

    1.  いつ、だれに、どのようにして、エルサレムでのことを話しますか。When, how and to whom does Jesus tell what happens in Jerusalem?

    2.  イエスはどのような事を告げますか。What does Jesus tell his disciples?

3.  ルカ

    1.  以前にもイエスは死と復活を予告しています。それらと比べてみましょう。(Compare these verses with Lk 9:21, 22 or other verses.)

### 参照

-   死と復活の予告

    -   8:31-32a 31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、32a しかもあからさまに、この事を話された。

    -   9:30-32 30 それから彼らはそこを立ち去り、ガリラヤをとおって行ったが、イエスは人に気づかれるのを好まれなかった。31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。32 しかし、彼らはイエスの言われたことを悟らず、また尋ねるのを恐れていた。

    -   10:32-34 32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、33 「見よ、わたしたちはエルサレムへ上って行くが、人の子は祭司長、律法学者たちの手に引きわたされる。そして彼らは死刑を宣告した上、彼を異邦人に引きわたすであろう。34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。

### 記録

-   日時：2024年6月27日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 10:35-45 ヤコブとヨハネの願い

> 35 さて、ゼベダイの子ヤコブとヨハネとがイエスのもとにきて言った、「先生、わたしたちがお頼みすることは、なんでもかなえてくださるようにお願いします」。36 イエスは彼らに「何をしてほしいと、願うのか」と言われた。37 すると彼らは言った、「栄光をお受けになるとき、ひとりをあなたの右に、ひとりを左にすわるようにしてください」。38 イエスは言われた、「あなたがたは自分が何を求めているのか、わかっていない。あなたがたは、わたしが飲む杯を飲み、わたしが受けるバプテスマを受けることができるか」。39 彼らは「できます」と答えた。するとイエスは言われた、「あなたがたは、わたしが飲む杯を飲み、わたしが受けるバプテスマを受けるであろう。40 しかし、わたしの右、左にすわらせることは、わたしのすることではなく、ただ備えられている人々だけに許されることである」。41 十人の者はこれを聞いて、ヤコブとヨハネとのことで憤慨し出した。42 そこで、イエスは彼らを呼び寄せて言われた、「あなたがたの知っているとおり、異邦人の支配者と見られている人々は、その民を治め、また偉い人たちは、その民の上に権力をふるっている。43 しかし、あなたがたの間では、そうであってはならない。かえって、あなたがたの間で偉くなりたいと思う者は、仕える人となり、44 あなたがたの間でかしらになりたいと思う者は、すべての人の僕とならねばならない。45 人の子がきたのも、仕えられるためではなく、仕えるためであり、また多くの人のあがないとして、自分の命を与えるためである」。

### マタイ 20:20-28

> 20 そのとき、ゼベダイの子らの母が、その子らと一緒にイエスのもとにきてひざまずき、何事かをお願いした。21 そこでイエスは彼女に言われた、「何をしてほしいのか」。彼女は言った、「わたしのこのふたりのむすこが、あなたの御国で、ひとりはあなたの右に、ひとりは左にすわれるように、お言葉をください」。22 イエスは答えて言われた、「あなたがたは、自分が何を求めているのか、わかっていない。わたしの飲もうとしている杯を飲むことができるか」。彼らは「できます」と答えた。23 イエスは彼らに言われた、「確かに、あなたがたはわたしの杯を飲むことになろう。しかし、わたしの右、左にすわらせることは、わたしのすることではなく、わたしの父によって備えられている人々だけに許されることである」。24 十人の者はこれを聞いて、このふたりの兄弟たちのことで憤慨した。25 そこで、イエスは彼らを呼び寄せて言われた、「あなたがたの知っているとおり、異邦人の支配者たちはその民を治め、また偉い人たちは、その民の上に権力をふるっている。26 あなたがたの間ではそうであってはならない。かえって、あなたがたの間で偉くなりたいと思う者は、仕える人となり、27 あなたがたの間でかしらになりたいと思う者は、僕とならねばならない。28 それは、人の子がきたのも、仕えられるためではなく、仕えるためであり、また多くの人のあがないとして、自分の命を与えるためであるのと、ちょうど同じである」。

### 問い

1.  ヤコブとヨハネ、そして弟子たちは何を考えていますか。

2.  イエスはどのように答えていますか。

3.  イエスがきた一番の目的は何だと言っていますか。

4.  この目的はイエスの教えや活動によって達せられるものですか、それともそうではないものですか。

5.  マタイ

    1.  どのようときに、だれがイエスのもとに来ますか。Who comes to Jesus? What happens?

    2.  この人はなにを願いますか。What does this person ask Jesus?

    3.  イエスはどのように答えますか。What is Jesus' response?

    4.  イエスの杯を飲むとはどのようなことを意味しているでしょうか。What does it mean to drink Jesus' cup?

    5.  ほかの弟子はどのような反応をしますか。What do other disciples do?

    6.  弟子たちは、どうすべきだと言っていますか。What should the disciples do?

    7.  イエスは何のために来たと言っていますか。What is the purpose of Jesus' life?

    8.  身代金として命を捧げるとはどういうことでしょうか。What does it mean to dedicate his life for the ransom of many?

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 10:46-52 盲人バルティマイを癒やす

> 46 それから、彼らはエリコにきた。そしてイエスが弟子たちや大ぜいの群衆と共にエリコから出かけられたとき、テマイの子、バルテマイという盲人のこじきが、道ばたにすわっていた。47 ところが、ナザレのイエスだと聞いて、彼は「ダビデの子イエスよ、わたしをあわれんでください」と叫び出した。48 多くの人々は彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子イエスよ、わたしをあわれんでください」。49 イエスは立ちどまって、「彼を呼べ」と命じられた。そこで、人々はその盲人を呼んで言った、「喜べ、立て、おまえを呼んでおられる」。50 そこで彼は上着を脱ぎ捨て、踊りあがってイエスのもとにきた。51 イエスは彼にむかって言われた、「わたしに何をしてほしいのか」。その盲人は言った、「先生、見えるようになることです」。52 そこでイエスは言われた、「行け、あなたの信仰があなたを救った」。すると彼は、たちまち見えるようになり、イエスに従って行った。

### マタイ 20:29-34

> 29 それから、彼らがエリコを出て行ったとき、大ぜいの群衆がイエスに従ってきた。30 すると、ふたりの盲人が道ばたにすわっていたが、イエスがとおって行かれると聞いて、叫んで言った、「主よ、ダビデの子よ、わたしたちをあわれんで下さい」。31 群衆は彼らをしかって黙らせようとしたが、彼らはますます叫びつづけて言った、「主よ、ダビデの子よ、わたしたちをあわれんで下さい」。32 イエスは立ちどまり、彼らを呼んで言われた、「わたしに何をしてほしいのか」。33 彼らは言った、「主よ、目をあけていただくことです」。34 イエスは深くあわれんで、彼らの目にさわられた。すると彼らは、たちまち見えるようになり、イエスに従って行った。

### ルカ 18:35-43

> 35 イエスがエリコに近づかれたとき、ある盲人が道ばたにすわって、物ごいをしていた。36 群衆が通り過ぎる音を耳にして、彼は何事があるのかと尋ねた。37 ところが、ナザレのイエスがお通りなのだと聞かされたので、38 声をあげて、「ダビデの子イエスよ、わたしをあわれんで下さい」と言った。39 先頭に立つ人々が彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子よ、わたしをあわれんで下さい」。40 そこでイエスは立ちどまって、その者を連れて来るように、とお命じになった。彼が近づいたとき、41 「わたしに何をしてほしいのか」とおたずねになると、「主よ、見えるようになることです」と答えた。42 そこでイエスは言われた、「見えるようになれ。あなたの信仰があなたを救った」。43 すると彼は、たちまち見えるようになった。そして神をあがめながらイエスに従って行った。これを見て、人々はみな神をさんびした。

### 問い

1.  バルテマイの願いは何ですか。

2.  イエスは「行け、あなたの信仰があなたを救った」と言っていますが、バルテマイの信仰とはどんなことでしょうか。

3.  マタイ

    1.  どこでなにが起きますか。What happens? Where does this happen?

    2.  マルコ、ルカの記事と比較して見ましょう。Compare this story with those in Mark and Luke.

    3.  なぜ、群衆は、この人たちを黙らせようとするのでしょうか。Why do the people stop these blind men?

    4.  イエスはどのような質問をし、この人たちはどう答えますか。What does Jesus ask them? What is the response of these men?

    5.  イエスはどうしますか。そして、この人たちはどうしますか。What does Jesus do? What do they do?

    6.  あなたは、なにかイエスに求めるものがありますか。Do you have anything to ask for Jesus?

4.  ルカ

    1.  この盲人は、イエスのことを何と呼んでいますか。(How does the blind man call Jesus?)

    2.  この盲人は、イエスに何を期待していましたか。(What does the blind man expect from Jesus?)

    3.  この章に登場した人たちからあなたはどのような事を学びましたか。(What have you leaned from those introduced in this chapter?)

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ
