## 14:1-2 イエスを殺す計略

> 1 さて、過越と除酵との祭の二日前になった。祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。2 彼らは、「祭の間はいけない。民衆が騒ぎを起すかも知れない」と言っていた。

### マタイ 26:1-5

> 1 イエスはこれらの言葉をすべて語り終えてから、弟子たちに言われた。2 「あなたがたが知っているとおり、ふつかの後には過越の祭になるが、人の子は十字架につけられるために引き渡される」。3 そのとき、祭司長たちや民の長老たちが、カヤパという大祭司の中庭に集まり、4 策略をもってイエスを捕えて殺そうと相談した。5 しかし彼らは言った、「祭の間はいけない。民衆の中に騒ぎが起るかも知れない」。

### ルカ 22:1-2

> 1 さて、過越といわれている除酵祭が近づいた。2 祭司長たちや律法学者たちは、どうかしてイエスを殺そうと計っていた。民衆を恐れていたからである。

### ヨハネ 11:45-53

> 45 マリヤのところにきて、イエスのなさったことを見た多くのユダヤ人たちは、イエスを信じた。46 しかし、そのうちの数人がパリサイ人たちのところに行って、イエスのされたことを告げた。47 そこで、祭司長たちとパリサイ人たちとは、議会を召集して言った、「この人が多くのしるしを行っているのに、お互は何をしているのだ。48 もしこのままにしておけば、みんなが彼を信じるようになるだろう。そのうえ、ローマ人がやってきて、わたしたちの土地も人民も奪ってしまうであろう」。49 彼らのうちのひとりで、その年の大祭司であったカヤパが、彼らに言った、「あなたがたは、何もわかっていないし、50 ひとりの人が人民に代って死んで、全国民が滅びないようになるのがわたしたちにとって得だということを、考えてもいない」。51 このことは彼が自分から言ったのではない。彼はこの年の大祭司であったので、預言をして、イエスが国民のために、52 ただ国民のためだけではなく、また散在している神の子らを一つに集めるために、死ぬことになっていると、言ったのである。53 彼らはこの日からイエスを殺そうと相談した。

[マルコによる福音書14章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2.pdf)

[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)

[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)

[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

<!-- ### 問い -->

<!-- 1.  1--11節のできごとをまとめてみましょう。それぞれ、イエスに対してどのような態度の人が登場しますか。 -->

<!-- 2.  イエスに香油を注いだ女に対する人々の態度、それに対するイエスの言葉からあなたは、どんなことを思いますか。マタイ26:6--13、ヨハネ12:1--8と比べてみましょう。 -->

<!-- 3.  ユダについて、マルコはあまり書いていませんが、ユダはなぜ裏切ったのだと思いますか。 -->

<!-- ### 参照 -->

<!-- ### 記録 -->

<!-- -   日時：2024年M月DD日午後7時半〜9時半 -->

<!-- -   出席（対面）X名、参加（遠隔）Y名 -->

<!-- ### 問いについて -->

<!-- ### メモ -->

## 14:3-9 ベタニアで香油を注がれる

> 3 イエスがベタニヤで、重い皮膚病の人シモンの家にいて、食卓についておられたとき、ひとりの女が、非常に高価で純粋なナルドの香油が入れてある石膏のつぼを持ってきて、それをこわし、香油をイエスの頭に注ぎかけた。4 すると、ある人々が憤って互に言った、「なんのために香油をこんなにむだにするのか。5 この香油を三百デナリ以上にでも売って、貧しい人たちに施すことができたのに」。そして女をきびしくとがめた。6 するとイエスは言われた、「するままにさせておきなさい。なぜ女を困らせるのか。わたしによい事をしてくれたのだ。7 貧しい人たちはいつもあなたがたと一緒にいるから、したいときにはいつでも、よい事をしてやれる。しかし、わたしはあなたがたといつも一緒にいるわけではない。8 この女はできる限りの事をしたのだ。すなわち、わたしのからだに油を注いで、あらかじめ葬りの用意をしてくれたのである。9 よく聞きなさい。全世界のどこででも、福音が宣べ伝えられる所では、この女のした事も記念として語られるであろう」。

### マタイ 26:6-13

> 6 さて、イエスがベタニヤで、重い皮膚病の人シモンの家におられたとき、7 ひとりの女が、高価な香油が入れてある石膏のつぼを持ってきて、イエスに近寄り、食事の席についておられたイエスの頭に香油を注ぎかけた。8 すると、弟子たちはこれを見て憤って言った、「なんのためにこんなむだ使をするのか。9 それを高く売って、貧しい人たちに施すことができたのに」。10 イエスはそれを聞いて彼らに言われた、「なぜ、女を困らせるのか。わたしによい事をしてくれたのだ。11 貧しい人たちはいつもあなたがたと一緒にいるが、わたしはいつも一緒にいるわけではない。12 この女がわたしのからだにこの香油を注いだのは、わたしの葬りの用意をするためである。13 よく聞きなさい。全世界のどこででも、この福音が宣べ伝えられる所では、この女のした事も記念として語られるであろう」。

### ヨハネ 12:1-8

> 1 過越の祭の六日まえに、イエスはベタニヤに行かれた。そこは、イエスが死人の中からよみがえらせたラザロのいた所である。2 イエスのためにそこで夕食の用意がされ、マルタは給仕をしていた。イエスと一緒に食卓についていた者のうちに、ラザロも加わっていた。3 その時、マリヤは高価で純粋なナルドの香油一斤を持ってきて、イエスの足にぬり、自分の髪の毛でそれをふいた。すると、香油のかおりが家にいっぱいになった。4 弟子のひとりで、イエスを裏切ろうとしていたイスカリオテのユダが言った、5 「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」。6 彼がこう言ったのは、貧しい人たちに対する思いやりがあったからではなく、自分が盗人であり、財布を預かっていて、その中身をごまかしていたからであった。7 イエスは言われた、「この女のするままにさせておきなさい。わたしの葬りの日のために、それをとっておいたのだから。8 貧しい人たちはいつもあなたがたと共にいるが、わたしはいつも共にいるわけではない」。

### （参考）ルカ 7:36-50

> 36 あるパリサイ人がイエスに、食事を共にしたいと申し出たので、そのパリサイ人の家にはいって食卓に着かれた。37 するとそのとき、その町で罪の女であったものが、パリサイ人の家で食卓に着いておられることを聞いて、香油が入れてある石膏のつぼを持ってきて、38 泣きながら、イエスのうしろでその足もとに寄り、まず涙でイエスの足をぬらし、自分の髪の毛でぬぐい、そして、その足に接吻して、香油を塗った。39 イエスを招いたパリサイ人がそれを見て、心の中で言った、「もしこの人が預言者であるなら、自分にさわっている女がだれだか、どんな女かわかるはずだ。それは罪の女なのだから」。40 そこでイエスは彼にむかって言われた、「シモン、あなたに言うことがある」。彼は「先生、おっしゃってください」と言った。41 イエスが言われた、「ある金貸しに金をかりた人がふたりいたが、ひとりは五百デナリ、もうひとりは五十デナリを借りていた。42 ところが、返すことができなかったので、彼はふたり共ゆるしてやった。このふたりのうちで、どちらが彼を多く愛するだろうか」。43 シモンが答えて言った、「多くゆるしてもらったほうだと思います」。イエスが言われた、「あなたの判断は正しい」。44 それから女の方に振り向いて、シモンに言われた、「この女を見ないか。わたしがあなたの家にはいってきた時に、あなたは足を洗う水をくれなかった。ところが、この女は涙でわたしの足をぬらし、髪の毛でふいてくれた。45 あなたはわたしに接吻をしてくれなかったが、彼女はわたしが家にはいった時から、わたしの足に接吻をしてやまなかった。46 あなたはわたしの頭に油を塗ってくれなかったが、彼女はわたしの足に香油を塗ってくれた。47 それであなたに言うが、この女は多く愛したから、その多くの罪はゆるされているのである。少しだけゆるされた者は、少しだけしか愛さない」。48 そして女に、「あなたの罪はゆるされた」と言われた。49 すると同席の者たちが心の中で言いはじめた、「罪をゆるすことさえするこの人は、いったい、何者だろう」。50 しかし、イエスは女にむかって言われた、「あなたの信仰があなたを救ったのです。安心して行きなさい」。

[マルコによる福音書14章3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_3-9.pdf)

[マルコによる福音書14章1-2,3-9節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9.pdf)

[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

### 問い

1.  1--11節のできごとをまとめてみましょう。イエスに対してどのような態度の人が登場しますか。

2.  女の人は、どこで、どのようなことをしますか。(3)

3.  女の人に対して、どのような人が、どのような対応をしますか。それは、なぜですか。（4,5）

4.  イエスは、どのように、言われますか。（6-9）

5.  他の福音書からは、さらにどのようなことがわかりますか。

6.  あなたは、この女の人の行為、人々の対応、イエスのことばについてどう思いますか。

### 参照

-   過越と除酵との祭の二日前（マタイ26:2 過越の祭、ルカ22:1 過越といわれている除酵祭）

    -   過越の祭：ニサンの月の十四日（4月14日頃）、大祭で安息日のような日

        -   ペンテコステ、仮庵の祭とともに三大祭。これらには、ユダヤの成年男子でエルサレムから24キロ以内に居住するものは、参加する義務があった。

        -   意義１：出エジプト12章、エジプトでの奴隷身分からの解放。子羊の血を入口のかもいに塗ってある家以外の長子は死の天使によって殺された。種入れぬパンをたべて祝った。

        -   意義２：農業的意義、大麦の取り入れのしるし（レビ23:10-11）

        -   巡礼者のエルサレム、ベタニヤとベテパゲでの宿泊は無料

        -   ヨセフスの記録、AD65 256500頭の子羊が殺された、一頭10人が最小単位であったので、300万人の巡礼者と推定されている。

    -   除酵の祭：過越の祭に続く七日間。小祭で、その期間中に新しい働きは始められなかったが「大衆の利益のために必要なもの、個人の損失を防ぐ働き」は許された。

    -   実際には、二つの祭りは明確に区別するものではあるが、ヨセフスにも「われわれは種入れぬパンの祭りと呼ばれる八日間の祭りを守る」（ユダヤ古代史II.15.1）との記述もあり、ひとまとめに言われることもあった。

-   祭司長たち：大祭司（ἀρχιερεύς）の複数形（ἀρχιερεῖς）、chief priest, high priest

    -   旧約聖書では世襲終身職だが、ヘロデ時代は引退も他家への移動もある。ボエトスの子エレアザル（BC4-3）、セツの子イエス（BC3-6）、ボエトスの子ヨアザル（6）、セツの子アンナス（6-15）、バビの子イシマエル（15-16）、アンナスの子エレアザル（16-17）、カミの子シメオン（17-18）、アンナスの養子ヨセフ・カヤパ（18-36）

-   ルカ 7:36-50 にも似た記述があるが、どう考えたら良いか。

    -   たとえがあり、その実例のようなものとして書かれている。

    -   場面もことなり、別のことを記述しているのだろう。

-   食事の姿勢：右の手で食物を取れるように、左の肘で長椅子に寄りかかって横になった。

-   ナルド油

    -   インドから来た珍しい植物で作られ、客人が家に到着したとき、あるいは食事の席についたとき、その人に数滴の香油をかける習慣があった。

    -   割ることですべてを使い切ることを意味していると思われる。

-   \[Q to Gemini-1.0-Pro\] ナルド（στάκτος）について教えてください。

    -   \[Gemini-1.0-Pro\]

    -   スタクテスについて スタクテスは、古代ギリシャ語で「στάκτος」と書かれ、特定の種類のナルドを指します。ナルドは、インド原産の常緑低木から抽出された、非常に珍重されていた芳香性樹脂です。

    -   特徴:

        香り: スタクテスは、甘く、温かく、ウッディな香りが特徴です。 色: 濃い黄色から茶褐色です。 粘稠度: 粘稠度の高い液体です。 用途: スタクテスは、古代世界では、香水、軟膏、薬として広く使用されていました。また、宗教的な儀式や埋葬にも使われていました。 歴史:

        スタクテスは、古代エジプト、ギリシャ、ローマで高く評価されていました。聖書にも登場し、ヨハネによる福音書 12:3 では、マリヤがイエスの足にスタクテスを塗ったことが記されています。

    -   現代での使用:

        今日でも、スタクテスは、香水、アロマセラピー、伝統的な医学で使用されています。また、高級な香料として珍重されています。

    -   その他の情報:

        スタクテスは、インド、ネパール、ブータンで栽培されています。 スタクテスの抽出には、水蒸気蒸留法が使用されます。 スタクテスの精油は、非常に濃縮されているため、希釈して使用する必要があります。 参考資料:

    -   Wikipedia: [Nard](https://en.wikipedia.org/wiki/Nardostachys) （植物）[Spikenard](https://en.wikipedia.org/wiki/Spikenard)（香料）

    -   追加情報:

        スタクテスは、鎮静、抗炎症、抗菌などの薬効があるとされています。 スタクテスは、不安、不眠症、頭痛などの症状を緩和するのに役立つと言われています。

-   香油の量（1リトラ＝327.5g）

    -   \[Gemini-1.0-Pro\] 香油の量

    -   ヨハネによる福音書 12:3 は次のように述べています。

        > 「すると、マリヤは、約一リトラの本物のナルド、高価な香油を取り、イエスの足に注ぎ、自分の髪の毛でその足を拭いた。家は香油の香りに満たされた。」

        元のギリシャ語のテキストでは、「λίτρα」(リトラ)という単語が使われており、これは約 12 オンスまたは 340 グラムに相当する重量単位です。しかし、英語の翻訳である「pint」(パイント)は体積の単位であり、測定する液体によって異なる場合があります。

        したがって、マリヤが使用した香油の正確な量を判断するのは難しいです。しかし、香油の高価さと家がその香りで満たされたことを考えると、かなりの量であったと推定できます。

        マリヤが使用した香油についての追加情報は次のとおりです。

        香油の種類: ギリシャ語の「στάκτος」(スタクテス)は、その香りや薬効で高く評価されていた特定の種類のナルドを指します。 香油の価値: マルコによる福音書 14:5 は、ナルドの価値が 300 デナリであったと述べており、これは労働者にとって 1 年分の賃金に相当します。 行為の意義: マリヤが香油でイエスを塗った行為は、彼への献身と愛の象徴的なジェスチャーでした。また、ナルドは死者の体に塗るために使用されたため、彼の死と埋葬も予兆していました。

-   １デナリ：労働者１日分の賃金

-   貧しい人

    -   申命記15:7-11 あなたの神、主が賜わる地で、もしあなたの兄弟で貧しい者がひとりでも、町の内におるならば、その貧しい兄弟にむかって、心をかたくなにしてはならない。また手を閉じてはならない。 8 必ず彼に手を開いて、その必要とする物を貸し与え、乏しいのを補わなければならない。9 あなたは心に邪念を起し、『第七年のゆるしの年が近づいた』と言って、貧しい兄弟に対し、物を惜しんで、何も与えないことのないように慎まなければならない。その人があなたを主に訴えるならば、あなたは罪を得るであろう。10 あなたは心から彼に与えなければならない。彼に与える時は惜しんではならない。あなたの神、主はこの事のために、あなたをすべての事業と、手のすべての働きにおいて祝福されるからである。11 貧しい者はいつまでも国のうちに絶えることがないから、わたしは命じて言う、『あなたは必ず国のうちにいるあなたの兄弟の乏しい者と、貧しい者とに、手を開かなければならない』。

-   よい事：καλός beautiful, handsome, excellent, eminent, choice, surpassing, precious, useful, suitable, commendable, admirable 生き生きとした美しいこと、ἀγαθός は、道徳的に善なること。

    -   ~6~Ὁ δὲ Ἰησοῦς εἶπεν· ἄφετε αὐτήν· τί αὐτῇ κόπους παρέχετε; καλὸν ἔργον ἠργάσατο ἐν ἐμοί. ~7~πάντοτε γὰρ τοὺς πτωχοὺς ἔχετε μεθ' ἑαυτῶν καὶ ὅταν θέλητε δύνασθε αὐτοῖς εὖ ποιῆσαι, ἐμὲ δὲ οὐ πάντοτε ἔχετε. 

    -   ここでのよい事は、愛と通じるものであろうか。それとも、美しいというところに、焦点があるのだろうか。

-   ヨハネによる福音書直前の記事 11:17-45

    -   17 さて、イエスが行ってごらんになると、ラザロはすでに四日間も墓の中に置かれていた。18 ベタニヤはエルサレムに近く、二十五丁ばかり離れたところにあった。19 大ぜいのユダヤ人が、その兄弟のことで、マルタとマリヤとを慰めようとしてきていた。20 マルタはイエスがこられたと聞いて、出迎えに行ったが、マリヤは家ですわっていた。21 マルタはイエスに言った、「主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう。22 しかし、あなたがどんなことをお願いになっても、神はかなえて下さることを、わたしは今でも存じています」。23 イエスはマルタに言われた、「あなたの兄弟はよみがえるであろう」。24 マルタは言った、「終りの日のよみがえりの時よみがえることは、存じています」。25 イエスは彼女に言われた、「わたしはよみがえりであり、命である。わたしを信じる者は、たとい死んでも生きる。26 また、生きていて、わたしを信じる者は、いつまでも死なない。あなたはこれを信じるか」。27 マルタはイエスに言った、「主よ、信じます。あなたがこの世にきたるべきキリスト、神の御子であると信じております」。28 マルタはこう言ってから、帰って姉妹のマリヤを呼び、「先生がおいでになって、あなたを呼んでおられます」と小声で言った。29 これを聞いたマリヤはすぐに立ち上がって、イエスのもとに行った。30 イエスはまだ村に、はいってこられず、マルタがお迎えしたその場所におられた。31 マリヤと一緒に家にいて彼女を慰めていたユダヤ人たちは、マリヤが急いで立ち上がって出て行くのを見て、彼女は墓に泣きに行くのであろうと思い、そのあとからついて行った。32 マリヤは、イエスのおられる所に行ってお目にかかり、その足もとにひれ伏して言った、「主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう」。33 イエスは、彼女が泣き、また、彼女と一緒にきたユダヤ人たちも泣いているのをごらんになり、激しく感動し、また心を騒がせ、そして言われた、34 「彼をどこに置いたのか」。彼らはイエスに言った、「主よ、きて、ごらん下さい」。35 イエスは涙を流された。36 するとユダヤ人たちは言った、「ああ、なんと彼を愛しておられたことか」。37 しかし、彼らのある人たちは言った、「あの盲人の目をあけたこの人でも、ラザロを死なせないようには、できなかったのか」。38 イエスはまた激しく感動して、墓にはいられた。それは洞穴であって、そこに石がはめてあった。39 イエスは言われた、「石を取りのけなさい」。死んだラザロの姉妹マルタが言った、「主よ、もう臭くなっております。四日もたっていますから」。40 イエスは彼女に言われた、「もし信じるなら神の栄光を見るであろうと、あなたに言ったではないか」。41 人々は石を取りのけた。すると、イエスは目を天にむけて言われた、「父よ、わたしの願いをお聞き下さったことを感謝します。42 あなたがいつでもわたしの願いを聞きいれて下さることを、よく知っています。しかし、こう申しますのは、そばに立っている人々に、あなたがわたしをつかわされたことを、信じさせるためであります」。43 こう言いながら、大声で「ラザロよ、出てきなさい」と呼ばわれた。44 すると、死人は手足を布でまかれ、顔も顔おおいで包まれたまま、出てきた。イエスは人々に言われた、「彼をほどいてやって、帰らせなさい」。45 マリヤのところにきて、イエスのなさったことを見た多くのユダヤ人たちは、イエスを信じた。

### 記録

-   日時：2025年1月9日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）1名

### 問いについて

1.  1--11節のできごとをまとめてみましょう。イエスに対してどのような態度の人が登場しますか。

    -   1 さて、過越と除酵との祭の二日前になった。祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。2 彼らは、「祭の間はいけない。民衆が騒ぎを起すかも知れない」と言っていた。

    -   \[DQ\] いつのことだと書かれていますか。

        -   \[A\] 過越と除酵との祭の二日前（マタイ26:2 過越の祭、ルカ22:1 過越といわれている除酵祭）

    -   過越と除酵との祭の二日前、策略をもってイエスを捕らえ殺そうとしている民の指導者たち、そして、この女、さらに、イスカリオテのユダ

2.  女の人は、どこで、どのようなことをしますか。(3)

    -   3 イエスがベタニヤで、重い皮膚病の人シモンの家にいて、食卓についておられたとき、ひとりの女が、非常に高価で純粋なナルドの香油が入れてある石膏のつぼを持ってきて、それをこわし、香油をイエスの頭に注ぎかけた。
    -   \[DQ\] 場所
        -   \[A\] ベタニヤの重い皮膚病の人シモンの家の食卓
        -   \[Q\] 当時はどのようにして食事をしていましたか。
            -   \[A\] 右の手で食物を取れるように、左の肘で長椅子に寄りかかって横になってたべていた。
    -   \[DQ\] 行為
        -   \[A\] 非常に高価で純粋なナルドの香油が入れてある石膏のつぼをこわし、イエスの頭に注ぎかける。
        -   \[Q\] なぜ、つぼをこわしたのでしょうか。
            -   \[A\] 残しておくことを考えてない。
            -   \[A\] イエスにのみささげる。
    -   \[DQ\] この行為は、イエスには迷惑ではなかったのでしょうか。
        -   量は書かれていないが、ヨハネによると、一斤（600g, 1 pound = 450g）おそらく、0.5リットルより少ない量
    -   \[DQ\] この女の人は、なぜ、このようなことをしたのでしょうか。

3.  女の人に対して、どのような人が、どのような対応をしますか。それは、なぜですか。（4,5）

    -   4 すると、ある人々が憤って互に言った、「なんのために香油をこんなにむだにするのか。5 この香油を三百デナリ以上にでも売って、貧しい人たちに施すことができたのに」。そして女をきびしくとがめた。
    -   \[DQ\] だれが、咎めていますか。
        -   \[A\] 「ある人々」（マタイ「弟子たち」、ヨハネ「イスカリオテのユダ」）
    -   \[DQ\] どのように咎めていますか。
        -   \[A\] 「貧しい人たちに施すべきだ」
        -   \[A\] 「売れば、三百デナリ以上になる」勿体（もったい）ない。
    -   \[DQ\] なぜ、そのようなことをいって、この女のひとを咎めるのでしょうか。
        -   \[A\] この女の人の行為を、値踏みしている。他の行為と取り替え可能だと考えている。

4.  イエスは、どのように、言われますか。（6-9）

    -   6 するとイエスは言われた、「するままにさせておきなさい。なぜ女を困らせるのか。わたしによい事をしてくれたのだ。7 貧しい人たちはいつもあなたがたと一緒にいるから、したいときにはいつでも、よい事をしてやれる。しかし、わたしはあなたがたといつも一緒にいるわけではない。8 この女はできる限りの事をしたのだ。すなわち、わたしのからだに油を注いで、あらかじめ葬りの用意をしてくれたのである。9 よく聞きなさい。全世界のどこででも、福音が宣べ伝えられる所では、この女のした事も記念として語られるであろう」。
    -   \[DQ\] イエスは、まずどのように言われますか。（6,7）
        -   イエスは、あきらかにこの女性をかばっている。
        -   するままにさせておきなさい。なぜ女を困らせるのか。わたしによい事をしてくれたのだ。一人の兄弟・姉妹が自ら良しと定めたことについて、とやかく批判して、彼女を「困らせる」べきではない。
        -   貧しい人たちはいつもあなたがたと一緒にいるから、したいときにはいつでも、よい事をしてやれる。しかし、わたしはあなたがたといつも一緒にいるわけではない。
    -   \[DQ\] イエスは、この女のひとは自分にどのようなことをしてくれたと言っていますか。
        -   よい事をしてくれた。
        -   できる限りの事をした
        -   わたしのからだに油を注いで、あらかじめ葬りの用意をしてくれた
    -   \[DQ\] 記念として語られると言ってますが、なぜ、名前を出さないのでしょうか。
        -   \[A\] マルコが書かれた時点では、この女は生きていて、危険に晒されないように、名前を出さなかったのでは。

5.  他の福音書からは、さらにどのようなことがわかりますか。

    -   マタイ 26:6-13

    -   ヨハネ 12:1-8：19-29, 1-18, 30, 31-42 の順が正しいとも言われる。

    -   参考：ルカ 7:36-50 罪の赦しと愛のことが書かれている。

6.  あなたは、この女の人の行為、人々の対応、イエスのことばについてどう思いますか。

    -   \[DQ\] この女の人は、なぜ、このようなことをしたのでしょうか。この女の人はどこまで理解してこの行為に至ったのでしょうか。

        -   \[A\] マルコでは不明としか言えない。

        -   \[A\] ヨハネでは、兄弟ラザロの復活の直後に位置付けられているので、その感謝もあったのでは。

        -   \[A\] ルカ10:38-42 のマルタとマリアの話などからすると、マリアは、イエスの真意を受け取っていたのかもしれない。

    -   \[DQ\] この女のしたことは愛の行為なのでしょうか。

### メモ

-   福音書の差異：ヨハネはかなり異なっている。油注ぎはヨハネでは、「過越の祭の六日まえ」（12:1）としている。おそらく、そちらが正しく、流れとして、マルコやマタイでは、油注ぎを、ここに置いているのだろう。マタイでは、「イエスはこれらの言葉をすべて語り終えてから」とはじまる（7:28, 11:1, 13:53, 18:1, 26:1 にありこれによって、イエスの説教を五つに分けているともとれる）十字架の死の予告をイエスがしている。「あなたがたが知っているとおり、ふつかの後には過越の祭になるが、人の子は十字架につけられるために引き渡される」。

-   重い皮膚病のシモン：不明だが、ヨハネの記述をみると、ラザロや、マリアと近い存在であることもわかる。

-   マリア：ヨハネによると香油を注いだのは、ベタニアのマリア、すなわち、マルタ、ラザロの兄弟のマリアである。マリアは、ルカ10:38-41 にも登場するが、言葉を発するのは、一箇所のみで、「マリヤは、イエスのおられる所に行ってお目にかかり、その足もとにひれ伏して言った、『主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう』。」（ヨハネ11:32）のみである。そして、このことばは、マルタが語った言葉と同じである。

    人間関係に関してある特性をもった女性であった可能性もあるようにみえる。その女性の行動を、イエスは弁護し「よい（うつくしい）事」と言っておられるように見える。

-   マルコ12:42,43 との比較：

    -   42 ところが、ひとりの貧しいやもめがきて、レプタ二つを入れた。それは一コドラントに当る。43 そこで、イエスは弟子たちを呼び寄せて言われた、「よく聞きなさい。あの貧しいやもめは、さいせん箱に投げ入れている人たちの中で、だれよりもたくさん入れたのだ。

-   マリアのしたことは、無駄遣い、馬鹿な事だったのだろうか。そうかもしれない。しかし、イエス様は、それを弁護しておられる。その背後には、このマリアへの愛があったのではないだろうか。マリアの行動をみていると、ヨハネ11章、ルカ10章など、非常に限られてはいるが、静かに座り、そして、今回の大胆な行動をしている。ある障害特性をもっていたのかもしれないとさえ思う。しかし、そのことを、美しい事とイエスは評価され、困らせてはいけないといい、特別な歴史的できごとに変えておられる。驚きである。

## 14:10-11 ユダ、裏切りを企てる

> 10 ときに、十二弟子のひとりイスカリオテのユダは、イエスを祭司長たちに引きわたそうとして、彼らの所へ行った。11 彼らはこれを聞いて喜び、金を与えることを約束した。そこでユダは、どうかしてイエスを引きわたそうと、機会をねらっていた。

### マタイ 26:14-16

> 14 時に、十二弟子のひとりイスカリオテのユダという者が、祭司長たちのところに行って 15 言った、「彼をあなたがたに引き渡せば、いくらくださいますか」。すると、彼らは銀貨三十枚を彼に支払った。16 その時から、ユダはイエスを引きわたそうと、機会をねらっていた。

### ルカ 22:3-6

> 3 そのとき、十二弟子のひとりで、イスカリオテと呼ばれていたユダに、サタンがはいった。4 すなわち、彼は祭司長たちや宮守がしらたちのところへ行って、どうしてイエスを彼らに渡そうかと、その方法について協議した。5 彼らは喜んで、ユダに金を与える取決めをした。6 ユダはそれを承諾した。そして、群衆のいないときにイエスを引き渡そうと、機会をねらっていた。

[マルコによる福音書14章10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_10-11.pdf)

[マルコによる福音書14章1-2,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_10-11.pdf)

[マルコによる福音書14章1-2,3-9,10-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_1-2_3-9_10-11.pdf)

**(マルコ14:1-2, 10-11 を中心に)**

### 問い

1.  1--11節のできごとを復習しましょう。
2.  いつ、どのような人たちが、どのようなことを計画しますか。（1）
3.  なぜ、祭りの間に計画を実行することを避けたのでしょうか。（2）
4.  ユダは、どのような人で、どのようなことをしますか。（10）
5.  ユダは、なぜこのような決断をしたのだと思いますか。（11 その他）
6.  それぞれのひとたちは、イエスについてどのように考えていたのでしょうか。

### 参照

-   マルコ14:1-2 1 さて、過越と除酵との祭の二日前になった。祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。2 彼らは、「祭の間はいけない。民衆が騒ぎを起すかも知れない」と言っていた。

    -   ~1~Ἦν δὲ τὸ πάσχα καὶ τὰ ἄζυμα μετὰ δύο ἡμέρας. καὶ ἐζήτουν οἱ ἀρχιερεῖς καὶ οἱ γραμματεῖς πῶς αὐτὸν ἐν δόλῳ κρατήσαντες ἀποκτείνωσιν· ~2~ἔλεγον γάρ· μὴ ἐν τῇ ἑορτῇ, μήποτε ἔσται θόρυβος τοῦ λαοῦ.

    -   1 After two days was the feast of the passover, and of unleavened bread: and the chief priests and the scribes sought how they might take him by craft, and put him to death. 2 But they said, Not on the feast day, lest there be an uproar of the people.

-   過越と除酵との祭の二日前（マタイ26:2 過越の祭、ルカ22:1 過越といわれている除酵祭）

    -   過越の祭：ニサンの月の十四日（4月14日頃）、大祭で安息日のような日

        -   ペンテコステ、仮庵の祭とともに三大祭。これらには、ユダヤの成年男子でエルサレムから24キロ以内に居住するものは、参加する義務があった。

        -   意義１：出エジプト12章、エジプトでの奴隷身分からの解放。子羊の血を入口のかもいに塗ってある家以外の長子は死の天使によって殺された。種入れぬパンをたべて祝った。

        -   意義２：農業的意義、大麦の取り入れのしるし（レビ23:10-11）

        -   巡礼者のエルサレム、ベタニヤとベテパゲでの宿泊は無料

        -   ヨセフスの記録、AD65 256500頭の子羊が殺された、一頭10人が最小単位であったので、300万人の巡礼者と推定されている。

    -   除酵の祭：過越の祭に続く七日間。小祭で、その期間中に新しい働きは始められなかったが「大衆の利益のために必要なもの、個人の損失を防ぐ働き」は許された。

    -   実際には、二つの祭りは明確に区別するものではあるが、ヨセフスにも「われわれは種入れぬパンの祭りと呼ばれる八日間の祭りを守る」（ユダヤ古代史II.15.1）との記述もあり、ひとまとめに言われることもあった。

    -   出エジプト23章14-17節 14 あなたは年に三度、わたしのために祭を行わなければならない。15 あなたは種入れぬパンの祭を守らなければならない。わたしが、あなたに命じたように、アビブの月の定めの時に七日のあいだ、種入れぬパンを食べなければならない。それはその月にあなたがエジプトから出たからである。だれも、むなし手でわたしの前に出てはならない。16 また、あなたが畑にまいて獲た物の勤労の初穂をささげる刈入れの祭と、あなたの勤労の実を畑から取り入れる年の終りに、取入れの祭を行わなければならない。17 男子はみな、年に三度、主なる神の前に出なければならない。

    -   参照（ユダヤの祭りについて）：日本イスラエル親善協会 \[[リンク](https://japan-israel-friendship.or.jp/category/special/festival/)\]・ミルトス（イスラエル・ユダヤ文化の出版社）\[[リンク](https://myrtos.co.jp/?mode=f6)\]

-   サタンの働き：

    -   ルカ22:3 そのとき、十二弟子のひとりで、イスカリオテと呼ばれていたユダに、サタンがはいった。

    -   ヨハネ13:27 27 この一きれの食物を受けるやいなや、サタンがユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。

-   ユダ：\[[十二弟子](https://icu-hsuzuki.github.io/science/bible/docs/12disciples.pdf)\]

    -   イスカリオテのユダは、共観福音書すべての、十二弟子のリストに含まれ、それも、みな、最後に入れている。（マルコ3:13–19、マタイ10:1–4、ルカ6:12-16、マルコとマタイは「イエスを裏切った」ルカは「後に裏切り者となった」参照：使徒言行録1:13）

        -   マルコ3:19a それからイスカリオテのユダ。このユダがイエスを裏切ったのである。（3:19 καὶ Ἰούδαν Ἰσκαριώτην, ὃς καὶ παρέδωκεν (V-AAI-3S) αὐτόν καὶ ἔρχονται εἴς οἶκον）

        -   マタイ10:4 熱心党のシモンとイスカリオテのユダ。このユダはイエスを裏切った者である。(10:4 Σίμων ὁ Κανανίτης, καὶ Ἰούδας Ἰσκαριώτης ὁ καὶ παραδοὺς (V-2AAP-NSM) αὐτόν)

        -   ルカ6:16b それからイスカリオテのユダ。このユダが裏切者となったのである。（6:16 Ἰούδαν Ἰακώβου καὶ Ἰούδαν Ἰσκαριώτην, ὃς καὶ ἐγένετο προδότης (a betrayer, traitor N-NSM)）

    -   イスカリオテのユダについては、共感福音書では、十二弟子のリスト以外は、祭司長たちに引き渡すことを、相談に行った箇所、最後の晩餐、イエスの捕縛、ユダの死のみである。このうちマルコであり、最後の晩餐では、裏切るものがマルコであること特定されてはいない。また、ユダの死については、言及されていない。ヨハネにおいては、６章に裏切ることになったユダについての言及があり、マリヤが香油を注ぐ箇所での弟子の発言を、イスカリオテのユダと特定している。

    -   ヨハネ6:70-71 イエスは彼らに答えられた、「あなたがた十二人を選んだのは、わたしではなかったか。それだのに、あなたがたのうちのひとりは悪魔である」。71 これは、イスカリオテのシモンの子ユダをさして言われたのである。このユダは、十二弟子のひとりでありながら、イエスを裏切ろうとしていた。

    -   ヨハネ12:3-6 3 その時、マリヤは高価で純粋なナルドの香油一斤を持ってきて、イエスの足にぬり、自分の髪の毛でそれをふいた。すると、香油のかおりが家にいっぱいになった。4 弟子のひとりで、イエスを裏切ろうとしていたイスカリオテのユダが言った、5 「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」。6 彼がこう言ったのは、貧しい人たちに対する思いやりがあったからではなく、自分が盗人であり、財布を預かっていて、その中身をごまかしていたからであった。7 イエスは言われた、「この女のするままにさせておきなさい。わたしの葬りの日のために、それをとっておいたのだから。8 貧しい人たちはいつもあなたがたと共にいるが、わたしはいつも共にいるわけではない」。

    -   ヨハネ13:26 イエスは答えられた、「わたしが一きれの食物をひたして与える者が、それである」。そして、一きれの食物をひたしてとり上げ、シモンの子イスカリオテのユダにお与えになった。

    -   ヨハネ13:29 ある人々は、ユダが金入れをあずかっていたので、イエスが彼に、「祭のために必要なものを買え」と言われたか、あるいは、貧しい者に何か施させようとされたのだと思っていた。

-   弟子である（ユダ）の裏切りに関する旧約預言

    -   詩篇41:9 わたしの信頼した親しい友、／わたしのパンを食べた親しい友さえも／わたしにそむいてくびすをあげた。

    -   詩篇109:8 その日を少なくし、／その財産をほかの人にとらせ、

    -   ゼカリヤ11:12,13 わたしは彼らに向かって、「あなたがたがもし、よいと思うならば、わたしに賃銀を払いなさい。もし、いけなければやめなさい」と言ったので、彼らはわたしの賃銀として、銀三十シケルを量った。13 主はわたしに言われた、「彼らによって、わたしが値積られたその尊い価を、宮のさいせん箱に投げ入れよ」。わたしは銀三十シケルを取って、これを主の宮のさいせん箱に投げ入れた。

-   ユダはイエスの死を望んでいたか？

    -   （バークレイ）人々の心は、ユダがイエスの死を全然望んでいなかったであろうという考えに魅惑されて来た。ユダが狂信的な愛国者であり、彼がイエスのうちに、彼の夢である民族の力と栄光を実現させる最後の企ての一つとして、イエスに行動を強いるために、イエスを裏切ったのであろう。彼が当局者にイエスを引き渡したのは、そのことによって、今やイエスは、ご自身を救うためには、行動に出ざるを得ないようにさせられるだろう、そしてその行動は、彼が夢にていた勝利的な作戦の始まりになるだろう、という考えからであった。そのユダの考えは、つぎの事実によって裏づけられるだろう。すなわち、彼は自分のしたことがわかったとき、出かけて行って、ユダの当局者の足元に、その非難される金を投げつけた。そして、外に出て行き、首を吊り、自殺したからである（マタイ27:3-5）。もし、そうであるなら、ユダの悲劇は歴史上の最大の悲劇である。

        -   マタイ27:1- 1 夜が明けると、祭司長たち、民の長老たち一同は、イエスを殺そうとして協議をこらした上、2 イエスを縛って引き出し、総督ピラトに渡した。3 そのとき、イエスを裏切ったユダは、イエスが罪に定められたのを見て後悔し、銀貨三十枚を祭司長、長老たちに返して 4 言った、「わたしは罪のない人の血を売るようなことをして、罪を犯しました」。しかし彼らは言った、「それは、われわれの知ったことか。自分で始末するがよい」。5 そこで、彼は銀貨を聖所に投げ込んで出て行き、首をつって死んだ。6 祭司長たちは、その銀貨を拾いあげて言った、「これは血の代価だから、宮の金庫に入れるのはよくない」。7 そこで彼らは協議の上、外国人の墓地にするために、その金で陶器師の畑を買った。8 そのために、この畑は今日まで血の畑と呼ばれている。

            -   使徒1:15-22 15 そのころ、百二十名ばかりの人々が、一団となって集まっていたが、ペテロはこれらの兄弟たちの中に立って言った、16 「兄弟たちよ、イエスを捕えた者たちの手びきになったユダについては、聖霊がダビデの口をとおして預言したその言葉は、成就しなければならなかった。17 彼はわたしたちの仲間に加えられ、この務を授かっていた者であった。18 （彼は不義の報酬で、ある地所を手に入れたが、そこへまっさかさまに落ちて、腹がまん中から引き裂け、はらわたがみな流れ出てしまった。19 そして、この事はエルサレムの全住民に知れわたり、そこで、この地所が彼らの国語でアケルダマと呼ばれるようになった。「血の地所」との意である。）20 詩篇に、／『その屋敷は荒れ果てよ、／そこにはひとりも住む者がいなくなれ』／と書いてあり、また／『その職は、ほかの者に取らせよ』／とあるとおりである。21 そういうわけで、主イエスがわたしたちの間にゆききされた期間中、22 すなわち、ヨハネのバプテスマの時から始まって、わたしたちを離れて天に上げられた日に至るまで、始終わたしたちと行動を共にした人たちのうち、だれかひとりが、わたしたちに加わって主の復活の証人にならねばならない」。

    -   コリント前書15:1-8 1 兄弟たちよ。わたしが以前あなたがたに伝えた福音、あなたがたが受けいれ、それによって立ってきたあの福音を、思い起してもらいたい。2 もしあなたがたが、いたずらに信じないで、わたしの宣べ伝えたとおりの言葉を固く守っておれば、この福音によって救われるのである。3 わたしが最も大事なこととしてあなたがたに伝えたのは、わたし自身も受けたことであった。すなわちキリストが、聖書に書いてあるとおり、わたしたちの罪のために死んだこと、4 そして葬られたこと、聖書に書いてあるとおり、三日目によみがえったこと、5 ケパに現れ、次に、十二人に現れたことである。6 そののち、五百人以上の兄弟たちに、同時に現れた。その中にはすでに眠った者たちもいるが、大多数はいまなお生存している。7 そののち、ヤコブに現れ、次に、すべての使徒たちに現れ、8 そして最後に、いわば、月足らずに生れたようなわたしにも、現れたのである。

-   マルコ14:17-21 17 夕方になって、イエスは十二弟子と一緒にそこに行かれた。18 そして、一同が席について食事をしているとき言われた、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」。19 弟子たちは心配して、ひとりびとり「まさか、わたしではないでしょう」と言い出した。20 イエスは言われた、「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者が、それである。21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。

-   野心：シェークスピア『ヘンリー八世』の中でもウルジーのことば「クロムウェル。わたしはあなたに、野心を捨てよと勧める。その罪によって天使たちも堕落した。それなら、創造主の似姿である人は、野心によって勝てるだろうか。決しておのれを愛してはならない。」

-   銀貨：明確には書かれていないので不明だが、おそらく、デンリオン銀貨か、ドラクメ銀貨。それぞれについて、聖書協会共同訳から引用する。

    -   デナリオン銀貨：ローマの銀貨で、１デナリオンは、１ドラクメと等価（1日の賃金にあたる）

    -   ドラクメ銀貨：ギリシャの銀貨で、重さ約4.3g、デナリオンと等価

### 記録

-   日時：2024年1月16日午後7時半〜9時半

-   出席（対面）4名、参加（遠隔）0名

### 問いについて

1.  1--11節のできごとを復習しましょう。
    -   \[DQ\] いつのことですか。
        -   過越と除酵との祭の二日前（共観福音書ではこの時期としている。）
    -   \[DQ\] どのような人たちが登場しますか。
        -   民の指導者たち（祭司長たちや律法学者たち）
        -   ベタニヤの女のひと：油を注ぐ（イエスの葬りの準備）
        -   ユダ：祭司長たちに、引き渡す、他の弟子たち。
        -   周囲の人々：ヨハネによるとラザロのことのあと人気が高まっていた
        -   イエス：神に委ねて抵抗していない（ヨハネ11:45-57）
2.  いつ、どのような人たちが、どのようなことを計画しますか。（1）
    -   1 さて、過越と除酵との祭の二日前になった。祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。
    -   \[DQ\] いつ頃から、イエスを捕らえ、殺す計画が始まっていたのでしょうか。
        -   このマルコの箇所からだけでは不明。しかし、イエスを殺そうと言う計画は、かなり以前からあった。
        -   マルコ3:1-6 イエスがまた会堂にはいられると、そこに片手のなえた人がいた。2 人々はイエスを訴えようと思って、安息日にその人をいやされるかどうかをうかがっていた。3 すると、イエスは片手のなえたその人に、「立って、中へ出てきなさい」と言い、4 人々にむかって、「安息日に善を行うのと悪を行うのと、命を救うのと殺すのと、どちらがよいか」と言われた。彼らは黙っていた。5 イエスは怒りを含んで彼らを見まわし、その心のかたくななのを嘆いて、その人に「手を伸ばしなさい」と言われた。そこで手を伸ばすと、その手は元どおりになった。6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。（存在を抹殺、居てほしくない存在というレベルだったかもしれない）
        -   マルコ11:18 祭司長、律法学者たちはこれを聞いて、どうかしてイエスを殺そうと計った。彼らは、群衆がみなその教に感動していたので、イエスを恐れていたからである。(宮清めのあと。ただ、マルコで、これだけで判断するのは、難しい。おそらく、ラザロの復活など、関係者が生きていて、マルコには収録しにくいことが存在したのだろう。)
        -   参照:イエスの予告
            -   マルコ8:31 それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、 （一回目の予告）
            -   マルコ9:31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。 （二回目の予告）
            -   マルコ10:34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。 （三回目の予告）
            -   「ぶどう園と農夫」のたとえ：マルコ12:1-12 7 すると、農夫たちは『あれはあと取りだ。さあ、これを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と話し合い、8 彼をつかまえて殺し、ぶどう園の外に投げ捨てた。
    -   \[DQ\] なぜ、民の指導者たちは、捕らえ、殺そうとまで考えたのでしょうか。
        -   マルコだけでは明確ではない。群衆の人気には、注意していたかもしれない。
        -   ヨハネ11:45-48 45 マリヤのところにきて、イエスのなさったことを見た多くのユダヤ人たちは、イエスを信じた。46 しかし、そのうちの数人がパリサイ人たちのところに行って、イエスのされたことを告げた。47 そこで、祭司長たちとパリサイ人たちとは、議会を召集して言った、「この人が多くのしるしを行っているのに、お互は何をしているのだ。48 もしこのままにしておけば、みんなが彼を信じるようになるだろう。そのうえ、ローマ人がやってきて、わたしたちの土地も人民も奪ってしまうであろう」。
            -   ヨハネによると、ローマ人が脅威だと感じ、指導者たちに任せておかなくなることを恐れていたと言っているようだ。
3.  なぜ、祭りの間に計画を実行することを避けたのでしょうか。（2）
    -   2 彼らは、「祭の間はいけない。民衆が騒ぎを起すかも知れない」と言っていた。
    -   \[DQ\] 恐れていたのは、どんなことだったのでしょうか。
        -   「祭司長たちとパリサイ人たちとは、イエスを捕えようとして、そのいどころを知っている者があれば申し出よ、という指令を出していた。」（ヨハネ11:57）
        -   ルカ11:6 群衆のいないときにイエスを引き渡そうと、機会をねらっていた。
4.  ユダは、どのような人で、どのようなことをしますか。（10）
    -   10 ときに、十二弟子のひとりイスカリオテのユダは、イエスを祭司長たちに引きわたそうとして、彼らの所へ行った。
    -   \[DQ\] ユダは「引き渡す」ことを計画しますが、これは、どのようなことを意図したのでしょうか。
5.  ユダは、なぜこのような決断をしたのだと思いますか。（11 その他）
    -   11 彼らはこれを聞いて喜び、金を与えることを約束した。そこでユダは、どうかしてイエスを引きわたそうと、機会をねらっていた。
    -   \[DQ\] ユダが、イエスを祭司長たちに引き渡そうとしたのは、なぜなのでしょうか。
        -   サタンが入った：
            -   ルカ22:3 そのとき、十二弟子のひとりで、イスカリオテと呼ばれていたユダに、サタンがはいった。
            -   ヨハネ13:27 27 この一きれの食物を受けるやいなや、サタンがユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。
        -   ヨハネ12:3 その時、マリヤは高価で純粋なナルドの香油一斤を持ってきて、イエスの足にぬり、自分の髪の毛でそれをふいた。すると、香油のかおりが家にいっぱいになった。4 弟子のひとりで、イエスを裏切ろうとしていたイスカリオテのユダが言った、5 「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」。6 彼がこう言ったのは、貧しい人たちに対する思いやりがあったからではなく、自分が盗人であり、財布を預かっていて、その中身をごまかしていたからであった。
    -   \[DQ\] ユダは弟子たちの中で特別だったのでしょうか。他の弟子たちと比較して違いがあるとすると、それは、何なのでしょうか。
        -   マルコ14:18-21 そして、一同が席について食事をしているとき言われた、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」。19 弟子たちは心配して、ひとりびとり「まさか、わたしではないでしょう」と言い出した。20 イエスは言われた、「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者が、それである。21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。
6.  それぞれのひとたちは、イエスについてどのように考えていたのでしょうか。
    -   支配者たち（ピラト、ヘロデ）
    -   民の指導者（祭司長たち、長老たち、律法学者）
    -   一般のひとたち（エルサレムのひとたち、ガリラヤのひとたち）
    -   弟子たち（ユダを含む十二弟子、同行している女性たち、他の弟子たち）

### メモ

-   福音書の差異（1-2 など）：油注ぎについては、ヨハネは過越祭の6日前としているが、共観福音書では、過越祭の前の日曜日ごろに、エルサレム入城で、すべて、それ以降のこととしているので、エルサレムの民の指導者たちが、イエスと捕らえた上、殺そうと計画したのも、最後の一週間に入れている。背景を考えると、ヨハネの記述の方が実際に近いと思われる。マタイによる福音書によると、イエスは、26:2 「あなたがたが知っているとおり、ふつかの後には過越の祭になるが、人の子は十字架につけられるために引き渡される」。と告げ（預言し）、一方、26:3-5 「そのとき、祭司長たちや民の長老たちが、カヤパという大祭司の中庭に集まり、4 策略をもってイエスを捕えて殺そうと相談した。5 しかし彼らは言った、「祭の間はいけない。民衆の中に騒ぎが起るかも知れない」。としている。実際には、祭りの間に処刑されたと記録されている。マルコとマタイでは、捕らえて、殺すことが書かれているが、ルカでは、殺すことの計画のみが書かれている。マルコとマタイには、民衆の中の騒ぎをおそれて、祭りの間を回避することが、図られたことが、書かれているが、ルカには、殺そうと計った理由に、民衆を恐れていたとあるが、祭りの間を避ける記述はない。
-   福音書の差異（10-11）：マルコでは、イスカリオテのユダからは、金のことは要求していないが、マタイでは、ユダからの提案になっている。マルコには、金額は書かれていないが、マタイには書かれている。マルコ、マタイでは「引き渡す」と書かれているがルカでは「渡す」となっている。ただし、動詞はいずれも παραδίδωμι (to give into the hands (of another), to give over into (one's) power or use）、ヨハネには、ユダの行為についての記述がない。しかし、ユダの行為の裏側を暗示させることばはある。「祭司長たちとパリサイ人たちとは、イエスを捕えようとして、そのいどころを知っている者があれば申し出よ、という指令を出していた。」（11:57）
-   ヨハネ11:45-53には、なぜ、民の指導者が、イエスを殺すことを計ったかが書かれている。
    -   （ラザロの復活によってイエスを信じるものが増えたことを背景に）民衆がイエスを信じるようになることを恐れた。
    -   （カリスマ性がある指導者に民衆が率いられると）ローマ人がやってきて、民の指導者たちが指導力を発揮している、イスラエルの土地も人民も奪ってしまうだろう。
    -   （これらのことを元に大祭司カヤパは）「あなたがたは、何もわかっていないし、50 ひとりの人が人民に代って死んで、全国民が滅びないようになるのがわたしたちにとって得だということを、考えてもいない」。という。
        -   （しかしこの言葉は）イエスが国民のためにや、散在している神の子らを一つに集めるために、死ぬことになっているという、神の言葉の預言だとも言える。
-   ユダがイエスを引き渡した背景
    -   マルコ14:1 さて、過越と除酵との祭の二日前になった。祭司長たちや律法学者たちは、策略をもってイエスを捕えたうえ、なんとかして殺そうと計っていた。
    -   ヨハネ11:53 53 彼らはこの日からイエスを殺そうと相談した。
    -   ヨハネ11:57「祭司長たちとパリサイ人たちとは、イエスを捕えようとして、そのいどころを知っている者があれば申し出よ、という指令を出していた。」
    -   ルカ11:6 群衆のいないときにイエスを引き渡そうと、機会をねらっていた。
    -   ルカ22:3、ヨハネ13:27 27：サタンがユダに入った
-   榊原康夫『ルカによる福音書』
    -   貪欲説：地所ほしさか、会計横領の穴埋めの金欲しさ。疑問点：なぜ後悔して自殺したか説明不能（マタイ27:3-5）
        -   ヨハネ12:6 彼がこう言ったのは、貧しい人たちに対する思いやりがあったからではなく、自分が盗人であり、財布を預かっていて、その中身をごまかしていたからであった。
        -   使徒1:18 （彼は不義の報酬で、ある地所を手に入れたが、そこへまっさかさまに落ちて、腹がまん中から引き裂け、はらわたがみな流れ出てしまった。
    -   単純な信仰喪失説または師の末路を見越しての寝返り説。疑問点：なぜ裁判証人にたたなかったか（マルコ14:55-59）なぜ、師の死刑判決に後悔したか説明不能。
    -   熱心党起爆剤説（政治的メシヤを）期待して入門したのに、イエスの優柔不断に業を煮やし、危地ににおいやって奇跡力を発揮させようとして仕組んだ芝居。ヨハネ12:4 などの古代語写本に「スカリオテのユダ」とあるので、「シカリ（刺客）」出身だと想像。
    -   ルカの説明は明快だが神秘です、「サタンがユダに入った」（ルカ22:3）サタンの再攻撃
        -   ルカ22:31 シモン、シモン、見よ、サタンはあなたがたを麦のようにふるいにかけることを願って許された。
        -   ルカ22:53 毎日あなたがたと一緒に宮にいた時には、わたしに手をかけなかった。だが、今はあなたがたの時、また、やみの支配の時である」。
    -   アリマタヤのヨセフ物語：そこで彼らは、イスカリオテのユダのもとの言い送った。彼はカヤパの兄弟の子で、ユダヤ人たちから、イエスの弟子になって彼の教えには従わずに裏切るようにと、説得されていた人物であった。人々は、ユダに1日あたり、２ドラクマの金を支給したので、、イエスの弟子ヨハネの言うとおり2年の間イエスと共にいた。

## 14:12-21 過越の食事をする

> 12 除酵祭の第一日、すなわち過越の小羊をほふる日に、弟子たちがイエスに尋ねた、「わたしたちは、過越の食事をなさる用意を、どこへ行ってしたらよいでしょうか」。13 そこで、イエスはふたりの弟子を使いに出して言われた、「市内に行くと、水がめを持っている男に出会うであろう。その人について行きなさい。14 そして、その人がはいって行く家の主人に言いなさい、『弟子たちと一緒に過越の食事をする座敷はどこか、と先生が言っておられます』。15 するとその主人は、席を整えて用意された二階の広間を見せてくれるから、そこにわたしたちのために用意をしなさい」。16 弟子たちは出かけて市内に行って見ると、イエスが言われたとおりであったので、過越の食事の用意をした。17 夕方になって、イエスは十二弟子と一緒にそこに行かれた。18 そして、一同が席について食事をしているとき言われた、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」。19 弟子たちは心配して、ひとりびとり「まさか、わたしではないでしょう」と言い出した。20 イエスは言われた、「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者が、それである。21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。

### マタイ 26:17-25

> 17 さて、除酵祭の第一日に、弟子たちはイエスのもとにきて言った、「過越の食事をなさるために、わたしたちはどこに用意をしたらよいでしょうか」。18 イエスは言われた、「市内にはいり、かねて話してある人の所に行って言いなさい、『先生が、わたしの時が近づいた、あなたの家で弟子たちと一緒に過越を守ろうと、言っておられます』」。19 弟子たちはイエスが命じられたとおりにして、過越の用意をした。20 夕方になって、イエスは十二弟子と一緒に食事の席につかれた。21 そして、一同が食事をしているとき言われた、「特にあなたがたに言っておくが、あなたがたのうちのひとりが、わたしを裏切ろうとしている」。22 弟子たちは非常に心配して、つぎつぎに「主よ、まさか、わたしではないでしょう」と言い出した。23 イエスは答えて言われた、「わたしと一緒に同じ鉢に手を入れている者が、わたしを裏切ろうとしている。24 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。25 イエスを裏切ったユダが答えて言った、「先生、まさか、わたしではないでしょう」。イエスは言われた、「いや、あなただ」。

### ルカ 22:7-14; 21-23

> 7 さて、過越の小羊をほふるべき除酵祭の日がきたので、8 イエスはペテロとヨハネとを使いに出して言われた、「行って、過越の食事ができるように準備をしなさい」。9 彼らは言った、「どこに準備をしたらよいのですか」。10 イエスは言われた、「市内にはいったら、水がめを持っている男に出会うであろう。その人がはいる家までついて行って、11 その家の主人に言いなさい、『弟子たちと一緒に過越の食事をする座敷はどこか、と先生が言っておられます』。12 すると、その主人は席の整えられた二階の広間を見せてくれるから、そこに用意をしなさい」。13 弟子たちは出て行ってみると、イエスが言われたとおりであったので、過越の食事の用意をした。14 時間になったので、イエスは食卓につかれ、使徒たちも共に席についた。
>
> 21 しかし、そこに、わたしを裏切る者が、わたしと一緒に食卓に手を置いている。22 人の子は定められたとおりに、去って行く。しかし人の子を裏切るその人は、わざわいである」。23 弟子たちは、自分たちのうちだれが、そんな事をしようとしているのだろうと、互に論じはじめた。

### ヨハネ 13:21-30

> 21 イエスがこれらのことを言われた後、その心が騒ぎ、おごそかに言われた、「よくよくあなたがたに言っておく。あなたがたのうちのひとりが、わたしを裏切ろうとしている」。22 弟子たちはだれのことを言われたのか察しかねて、互に顔を見合わせた。23 弟子たちのひとりで、イエスの愛しておられた者が、み胸に近く席についていた。24 そこで、シモン・ペテロは彼に合図をして言った、「だれのことをおっしゃったのか、知らせてくれ」。25 その弟子はそのままイエスの胸によりかかって、「主よ、だれのことですか」と尋ねると、26 イエスは答えられた、「わたしが一きれの食物をひたして与える者が、それである」。そして、一きれの食物をひたしてとり上げ、シモンの子イスカリオテのユダにお与えになった。27 この一きれの食物を受けるやいなや、サタンがユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。28 席を共にしていた者のうち、なぜユダにこう言われたのか、わかっていた者はひとりもなかった。29 ある人々は、ユダが金入れをあずかっていたので、イエスが彼に、「祭のために必要なものを買え」と言われたか、あるいは、貧しい者に何か施させようとされたのだと思っていた。30 ユダは一きれの食物を受けると、すぐに出て行った。時は夜であった。

### （参照：主の晩餐）ルカ 22:15-20

> 15 イエスは彼らに言われた、「わたしは苦しみを受ける前に、あなたがたとこの過越の食事をしようと、切に望んでいた。16 あなたがたに言って置くが、神の国で過越が成就する時までは、わたしは二度と、この過越の食事をすることはない」。17 そして杯を取り、感謝して言われた、「これを取って、互に分けて飲め。18 あなたがたに言っておくが、今からのち神の国が来るまでは、わたしはぶどうの実から造ったものを、いっさい飲まない」。19 またパンを取り、感謝してこれをさき、弟子たちに与えて言われた、「これは、あなたがたのために与えるわたしのからだである。わたしを記念するため、このように行いなさい」。20 食事ののち、杯も同じ様にして言われた、「この杯は、あなたがたのために流すわたしの血で立てられる新しい契約である。

[マルコによる福音書14章12-21節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_12-21.pdf)

### 問い

1.  1-11節を復習しましょう。どんなことがありましたか。(1-11)

2.  イエスが弟子たちと過ぎ越しの食事をする場所の準備はどのように描かれていますか。（12-16）

3.  イエスは食事をしているときに、弟子たちに何を伝えますか、また、弟子たちはどんな反応をしますか。（18,19）

4.  イエスはなぜこのことを告げ、弟子たちは、なぜこのような反応をしたのでしょうか。

5.  イエスはさらに、どのように伝えますか。（20,21）

6.  イエスのどのような思いがあるのでしょうか。(特に 21)

### 参照

-   ルカでは、途中に、聖餐の記事がはさまり、このあと「いちばん偉いもの」の記事挿入（ルカ22:24-30）

-   ヨハネではこの前に、イエスが弟子たちの足を洗う記事があり、このあとに「新しい戒め」（ヨハネ13:31-35）について書かれている。

-   \[荒井献（直）訳\] 人の子を裏切るその人は = 彼を介して人の子が引き渡されるその人は

-   ペテロとヨハネ（ルカのみ）

    -   ルカ22:8 イエスはペテロとヨハネとを使いに出して言われた、「行って、過越の食事ができるように準備をしなさい」。

    -   使徒3:1-4 1 さて、ペテロとヨハネとが、午後三時の祈のときに宮に上ろうとしていると、2 生れながら足のきかない男が、かかえられてきた。この男は、宮もうでに来る人々に施しをこうため、毎日、「美しの門」と呼ばれる宮の門のところに、置かれていた者である。3 彼は、ペテロとヨハネとが、宮にはいって行こうとしているのを見て、施しをこうた。4 ペテロとヨハネとは彼をじっと見て、「わたしたちを見なさい」と言った。5 彼は何かもらえるのだろうと期待して、ふたりに注目していると、6 ペテロが言った、「金銀はわたしには無い。しかし、わたしにあるものをあげよう。ナザレ人イエス・キリストの名によって歩きなさい」。7 こう言って彼の右手を取って起してやると、足と、くるぶしとが、立ちどころに強くなって、8 踊りあがって立ち、歩き出した。そして、歩き回ったり踊ったりして神をさんびしながら、彼らと共に宮にはいって行った。

    -   使徒3:11 彼がなおもペテロとヨハネとにつきまとっているとき、人々は皆ひどく驚いて、「ソロモンの廊」と呼ばれる柱廊にいた彼らのところに駆け集まってきた。

    -   使徒4:13 人々はペテロとヨハネとの大胆な話しぶりを見、また同時に、ふたりが無学な、ただの人たちであることを知って、不思議に思った。そして彼らがイエスと共にいた者であることを認め、

    -   使徒4:19 ペテロとヨハネとは、これに対して言った、「神に聞き従うよりも、あなたがたに聞き従う方が、神の前に正しいかどうか、判断してもらいたい。

    -   使徒8:14 エルサレムにいる使徒たちは、サマリヤの人々が、神の言を受け入れたと聞いて、ペテロとヨハネとを、そこにつかわした。

-   過越の儀式

    -   最初は、パンだねの儀式的な捜索。過越の前には、パンだねのいかなる細片も家から放逐しなければならなかった。それは、エジプトでの最初の過越（出エジプト記12章）で、種入れぬパンが食されたからである。種入れぬパンは全然パンのようではない。それは薄くて硬いビスケットのようである。それがエジプトで用いられたのは、パンだねをいれたパンよりもよほど早く焼くことができたからであった。そして、最初の過越は、エジプトからの脱出の過越で、大急ぎで食べなければならなかった。また、みんなは、旅路の準備をしなければならなかった。それに加えて、パンだねは腐敗のシンボルであって。パンダねは発酵した生パンであり、ユダヤ人は発酵と腐敗とを同一視していた。それゆえ、パンだねは、腐敗と破壊を意味していた。過越の祭りの前日に、家の主人は、火を灯した蝋燭をもって、家の中のパンダねを儀式的に探した。その捜索の前に彼は祈った。

        -   汝エホバ、わが神、宇宙の王をたたえまつる。汝は、その戒めによって、われらを聖別なしたまい、パンだねを除くように命じられた。

    -   また捜索の終わりに家の主人は言った。

        -   わたしの所有にかかる、わたしが見たことのあるもの、またみたことのない全てのパンだねは、無効になれ。また、それは大地の塵として数えられよ。

    -   つぎに、過越の夕に先んずる午後に、過越の子羊の犠牲があった。すべての人々は神殿にやってきた。それによって、あたかも彼自身を犠牲にささげているように、参拝者は自分の子羊を殺さなければならなかった。

    -   血は注ぎ出され、内臓と脂肪は捧げ物、ざくろの木で作った焼き串で、裸火の上で焼かなければならなかった。その焼き串は、子羊の口から尻へ刺し貫かれ、子羊は、頭、四肢、尾をからだにつけたままで丸焼きにしなければならなかった。

    -   食事内容

        -   子羊：過越

        -   たね入れぬパン：いそいで食したパン

        -   一鉢の塩水（カソーレト、煉瓦色のスープ）：エジプトでかれらが流した涙と、奇跡的にわたって危機を脱した紅海の水

        -   苦菜：わさび、キクニガナ、キクヂシャ、レタス、ニガハッカ、奴隷の苦味

        -   ハロシュス：りんご、なつめ、ざくろ、ナッツをまぜたものにシナモンの小片がつきさしてある。煉瓦の泥と、藁

        -   四杯の葡萄酒：約0.6Lで、五分の三が葡萄酒、五分の二が水。四つの盃は、食事の他の段階で飲まれたが、それは人々に出エジプト記5:6-7 の四つの約束を想起させるため。

            -   6 それゆえ、イスラエルの人々に言いなさい、『わたしは主である。わたしはあなたがたをエジプトびとの労役の下から導き出し、奴隷の務から救い、また伸べた腕と大いなるさばきをもって、あなたがたをあがなうであろう。7 わたしはあなたがたを取ってわたしの民とし、わたしはあなたがたの神となる。わたしがエジプトびとの労役の下からあなたがたを導き出すあなたがたの神、主であることを、あなたがたは知るであろう。

-   聖餐式における自己吟味：コリント前書11:27-29 27 だから、ふさわしくないままでパンを食し主の杯を飲む者は、主のからだと血とを犯すのである。28 だれでもまず自分を吟味し、それからパンを食べ杯を飲むべきである。29 主のからだをわきまえないで飲み食いする者は、その飲み食いによって自分にさばきを招くからである。

-   イエスの愛しておられた弟子

    -   ヨハネ13:23 23 弟子たちのひとりで、イエスの愛しておられた者が、み胸に近く席についていた。

    -   ヨハネ19:26,27 26 イエスは、その母と愛弟子とがそばに立っているのをごらんになって、母にいわれた、「婦人よ、ごらんなさい。これはあなたの子です」。27 それからこの弟子に言われた、「ごらんなさい。これはあなたの母です」。そのとき以来、この弟子はイエスの母を自分の家に引きとった。

    -   ヨハネ20:2 そこで走って、シモン・ペテロとイエスが愛しておられた、もうひとりの弟子のところへ行って、彼らに言った、「だれかが、主を墓から取り去りました。どこへ置いたのか、わかりません」。

    -   ヨハネ21:7 イエスの愛しておられた弟子が、ペテロに「あれは主だ」と言った。シモン・ペテロは主であると聞いて、裸になっていたため、上着をまとって海にとびこんだ。

    -   ヨハネ21:20 ペテロはふり返ると、イエスの愛しておられた弟子がついて来るのを見た。この弟子は、あの夕食のときイエスの胸近くに寄りかかって、「主よ、あなたを裏切る者は、だれなのですか」と尋ねた人である。21 ペテロはこの弟子を見て、イエスに言った、「主よ、この人はどうなのですか」。22 イエスは彼に言われた、「たとい、わたしの来る時まで彼が生き残っていることを、わたしが望んだとしても、あなたにはなんの係わりがあるか。あなたは、わたしに従ってきなさい」。23 こういうわけで、この弟子は死ぬことがないといううわさが、兄弟たちの間にひろまった。しかし、イエスは彼が死ぬことはないと言われたのではなく、ただ「たとい、わたしの来る時まで彼が生き残っていることを、わたしが望んだとしても、あなたにはなんの係わりがあるか」と言われただけである。24 これらの事についてあかしをし、またこれらの事を書いたのは、この弟子である。そして彼のあかしが真実であることを、わたしたちは知っている。25 イエスのなさったことは、このほかにまだ数多くある。もしいちいち書きつけるならば、世界もその書かれた文書を収めきれないであろうと思う。

-   「いや、あなただ」(σὺ εἶπας) ‘You have said so.’ (NIV)「いや、そうかもしれない」（塚本虎二訳）

    -   マタイ26:25 イエスを裏切ったユダが答えて言った、「先生、まさか、わたしではないでしょう」。イエスは言われた、「いや、あなただ」。

    -   マタイ26:63,64 63 しかし、イエスは黙っておられた。そこで大祭司は言った、「あなたは神の子キリストなのかどうか、生ける神に誓ってわれわれに答えよ」。64 イエスは彼に言われた、「あなたの言うとおりである。しかし、わたしは言っておく。あなたがたは、間もなく、人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」。(~64~λέγει αὐτῷ ὁ Ἰησοῦς· σὺ εἶπας. πλὴν λέγω ὑμῖν· ἀπ’ ἄρτι ὄψεσθε τὸν υἱὸν τοῦ ἀνθρώπου καθήμενον ἐκ δεξιῶν τῆς δυνάμεως καὶ ἐρχόμενον ἐπὶ τῶν νεφελῶν τοῦ οὐρανοῦ. \[NIV\] ‘You have said so,’ Jesus replied. ‘But I say to all of you: from now on you will see the Son of Man sitting at the right hand of the Mighty One and coming on the clouds of heaven.’)

    -   マタイ27:11 さて、イエスは総督の前に立たれた。すると総督はイエスに尋ねて言った、「あなたがユダヤ人の王であるか」。イエスは「そのとおりである」と言われた。(~11~Ὁ δὲ Ἰησοῦς ἐστάθη ἔμπροσθεν τοῦ ἡγεμόνος· καὶ ἐπηρώτησεν αὐτὸν ὁ ἡγεμὼν λέγων· σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων; ὁ δὲ Ἰησοῦς ἔφη· σὺ λέγεις. \[NIV\] ~11~Meanwhile Jesus stood before the governor, and the governor asked him, ‘Are you the king of the Jews?’ ‘You have said so,’ Jesus replied.)

    -   マルコ15:2 ピラトはイエスに尋ねた、「あなたがユダヤ人の王であるか」。イエスは、「そのとおりである」とお答えになった。(~2~Καὶ ἐπηρώτησεν αὐτὸν ὁ Πιλᾶτος· σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων; ὁ δὲ ἀποκριθεὶς αὐτῷ λέγει· σὺ λέγεις. \[NIV\] ‘Are you the king of the Jews?’ asked Pilate. ‘You have said so,’ Jesus replied.)

    -   ルカ22:70 彼らは言った、「では、あなたは神の子なのか」。イエスは言われた、「あなたがたの言うとおりである」。(~70~εἶπαν δὲ πάντες· σὺ οὖν εἶ ὁ υἱὸς τοῦ θεοῦ; ὁ δὲ πρὸς αὐτοὺς ἔφη· ὑμεῖς λέγετε ὅτι ἐγώ εἰμι. \[NIV\] ~70~They all asked, ‘Are you then the Son of God?’ He replied, ‘You say that I am.’)

### 記録

-   日時：2025年1月16日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  1-11節を復習しましょう。どんなことがありましたか。(1-11)

    -   祭司長、律法学者たちが、策略をもってイエスを捕らえ、どうにかして殺そうとしていた。

    -   ベタニヤで、女が葬りの準備として油をイエスに注ぐ。

    -   イスカリオテのユダが祭司長たちのもとへ行き、イエスを引き渡すことを約束する。

2.  イエスが弟子たちと過ぎ越しの食事をする場所の準備はどのように描かれていますか。（12-17）

    -   12 除酵祭の第一日、すなわち過越の小羊をほふる日に、弟子たちがイエスに尋ねた、「わたしたちは、過越の食事をなさる用意を、どこへ行ってしたらよいでしょうか」。13 そこで、イエスはふたりの弟子を使いに出して言われた、「市内に行くと、水がめを持っている男に出会うであろう。その人について行きなさい。14 そして、その人がはいって行く家の主人に言いなさい、『弟子たちと一緒に過越の食事をする座敷はどこか、と先生が言っておられます』。15 するとその主人は、席を整えて用意された二階の広間を見せてくれるから、そこにわたしたちのために用意をしなさい」。16 弟子たちは出かけて市内に行って見ると、イエスが言われたとおりであったので、過越の食事の用意をした。17 夕方になって、イエスは十二弟子と一緒にそこに行かれた。

    -   \[DQ\] なぜこのような記事が記録されているのでしょうか。

        -   \[Q\] 他にもイエスが用意周到だった箇所がありますか。(11:1-11) \[A\] ろばの子。

        -   夕方から新しい日。（木曜日夜６時以降）

    -   \[DQ\] 「16 弟子たちは出かけて市内に行って見ると、イエスが言われたとおりであったので、過越の食事の用意をした。」とありますが、これは、イエスの予言的能力を表現しているのでしょうか。

        -   おそらく、前もって、手配してあったのではないか。

        -   \[参照\] マタイ26:18 イエスは言われた、「市内にはいり、かねて話してある人の所に行って言いなさい、『先生が、わたしの時が近づいた、あなたの家で弟子たちと一緒に過越を守ろうと、言っておられます』」。（~18~ὁ δὲ εἶπεν· ὑπάγετε εἰς τὴν πόλιν πρὸς τὸν δεῖνα καὶ εἴπατε αὐτῷ· ὁ διδάσκαλος λέγει· ὁ καιρός μου ἐγγύς ἐστιν, πρὸς σὲ ποιῶ τὸ πάσχα μετὰ τῶν μαθητῶν μου. (NIV) ~18~He replied, ‘Go into the city to a certain man and tell him, “The Teacher says: my appointed time is near. I am going to celebrate the Passover with my disciples at your house.” ’）

            -   「かねて話してある人のところに行って」と書かれている。また「わたしの時が近づいた」ということは、言っていたとある。

    -   \[DQ\] このときの背景を考え、イエスがなぜこのようにしたか考えてみましょう。

        -   水瓶を運ぶのは女の仕事。ここでは、男となっている。

        -   おそらく外側からの梯子でのぼる、静思と瞑想の場所、客室、集会所

3.  イエスは食事をしているときに、弟子たちに何を伝えますか、また、弟子たちはどんな反応をしますか。（18,19）

    -   18 そして、一同が席について食事をしているとき言われた、「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」。19 弟子たちは心配して、ひとりびとり「まさか、わたしではないでしょう」と言い出した。
    -   \[DQ\] どのような人たちと食事を共にしていますか。
        -   \[A\] 弟子たちとあるが、イエスと一緒に行動していた女性たちも一緒だったろうし、十二弟子以外にも、とくにエルサレムまたはその周辺に居た弟子たちもいたかもしれない。同時に、危険もあるので、ある程度人数を制限していたとも思われる。

4.  イエスはなぜこのことを告げ、弟子たちは、なぜこのような反応をしたのでしょうか。

    -   \[DQ\] イエスは、なぜ「特にあなたがたに言っておくが、あなたがたの中のひとりで、わたしと一緒に食事をしている者が、わたしを裏切ろうとしている」（マルコ14:18b）と弟子たちに告げたのだろうか。
    -   \[DQ\] 弟子たちは、イエスのことばを、どのように受け取っただろうか。

5.  イエスはさらに、どのように伝えますか。（20,21）

    -   20 イエスは言われた、「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者が、それである。21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。

    -   \[DQ\] 「十二人の中のひとりで、わたしと一緒に同じ鉢にパンをひたしている者」とは何を意味しているのでしょうか。

        -   \[A\] 他にも、その場、または階下にひとはいたかもしれないが、十二人と限定することは、十二弟子にとっては、とても、大きなチャレンジだったろう。共に食事をすることは、とくに、この時は、親しさ、信頼関係のもとでもあったろう。

        -   他にもひとはいたかもしれないが、十二弟子に限定されている。おそらく、もう逃れられない状況があったろう。ユダはなおさらである。ユダには、最後の悔い改めの機会だったかもしれない。

    -   \[DQ\] 21節では、自分についての「予定」と「裏切るその人」について、それぞれどのようなことを言っていますか。

        -   たしかに人の子は、自分について書いてあるとおりに去って行く。

            -   詩篇41:9 わたしの信頼した親しい友、／わたしのパンを食べた親しい友さえも／わたしにそむいてくびすをあげた。

        -   しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう

            -   自分について書いてあるとおりに去ることになることと、そのことをもたらすことの評価は別だと言っているように見える。

            -   主の定めどおりに起こることを手伝っている忠実な僕とは描いていない。

    -   \[参照\] マタイではどのように描かれていますか。ユダとイエスの間のどのような会話が記録されていますか。

        -   マタイ26:25 イエスを裏切ったユダが答えて言った、「先生、まさか、わたしではないでしょう」。イエスは言われた、「いや、あなただ」。(~25~ἀποκριθεὶς δὲ Ἰούδας ὁ παραδιδοὺς αὐτὸν εἶπεν· μήτι ἐγώ εἰμι, ῥαββί; λέγει αὐτῷ· σὺ εἶπας. \[NIV\] Then Judas, the one who would betray him, said, ‘Surely you don’t mean me, Rabbi?’ Jesus answered, ‘You have said so.’)

            -   「それはあなたの言ったこと」はあまりにも、日本語としておかしいので「いや、あなただ」と訳されているが、うちに秘めた言い方であることは確かだろう。「いや、そうかもしれない」（塚本虎二訳）

            -   いくつかの用例がある。マルコ15:2、マタイ26:25、64、27:11、ルカ22:70

    -   \[参照\] ヨハネはどう描いていますか。

        -   ヨハネ13:23-27 23 弟子たちのひとりで、イエスの愛しておられた者が、み胸に近く席についていた。24 そこで、シモン・ペテロは彼に合図をして言った、「だれのことをおっしゃったのか、知らせてくれ」。25 その弟子はそのままイエスの胸によりかかって、「主よ、だれのことですか」と尋ねると、26 イエスは答えられた、「わたしが一きれの食物をひたして与える者が、それである」。そして、一きれの食物をひたしてとり上げ、シモンの子イスカリオテのユダにお与えになった。27 この一きれの食物を受けるやいなや、サタンがユダにはいった。そこでイエスは彼に言われた、「しようとしていることを、今すぐするがよい」。

            -   その場にいたひとたちも、やはり理解できなかったとするのが適切だろう。

        -   \[Q\] イエスの愛しておられた者と、イエスと、ユダの位置は、どのような関係だったと思いますか。

            -   \[A\] おそらく、イエスの右に、イエスの愛しておられたもの、左に、ユダ。

            -   イエスの愛しておられたもの：ヨハネ13:23、19:26、20:2、21:7、20

6.  イエスのどのような思いがあるのでしょうか。(特に 21)

    -   21 たしかに人の子は、自分について書いてあるとおりに去って行く。しかし、人の子を裏切るその人は、わざわいである。その人は生れなかった方が、彼のためによかったであろう」。

    -   \[DQ\] 「生まれなかった方がよかった」と言うような人生があるのでしょうか。

        -   単純に辛い人生だというように取ることもできるように思える。

    -   \[DQ\] ここでイエスは、なぜ、ユダが裏切ろうとしていると明確に告げなかったのでしょうか。ユダが裏切ろうとしていると告げたらどうなったでしょうか。

### メモ

-   福音書の差異：ルカは、配餐の記事が挟まっており、ユダもそのときにいたことになっている。また、過越の食事の準備のために遣わされたのは、マルコでは二人、マタイでは弟子たち、ペテロとヨハネであったことが、ルカにのみ書かれている。ペテロとヨハネは、ルカが書いたとされる、使徒行伝で、ほとんど最初からリーダー的に描かれている。ほどなく、ヨハネの兄弟ヤコブが殺されたことも関係しており、その後、イエスの兄弟ヤコブが力を持ってくる中で、ここでは、その二人にしたということもあるかもしれない。いずれにしても、ペテロやヨハネのような弟子の中でも主要なメンバーにも、秘密にして、場所が設定されたことは事実だろう。裏切りも予想でき、それだけ、危険が差し迫っていたということか。この準備自体も秘密で、マタイのように、弟子たちみなが関わるような状況にはなかったのかもしれない。「その人は生れなかった方が、彼のためによかったであろう」は、ルカにはない。「わたしと一緒に同じ鉢にパンをひたしている者」の表現は、ルカにはない。ヨハネには「弟子たちのひとりで、イエスの愛しておられた者」の存在がクローズアップされているが、結局、その質問に、イエスが答えたように書かれているものの、ユダが裏切ろうとしているという確信に至っていないということは、やはり明確な行為ではなかったと考えるほうが適切であろう。

## 14:22-25 主の晩餐

> 22 一同が食事をしているとき、イエスはパンを取り、祝福してこれをさき、弟子たちに与えて言われた、「取れ、これはわたしのからだである」。23 また杯を取り、感謝して彼らに与えられると、一同はその杯から飲んだ。24 イエスはまた言われた、「これは、多くの人のために流すわたしの契約の血である。25 あなたがたによく言っておく。神の国で新しく飲むその日までは、わたしは決して二度と、ぶどうの実から造ったものを飲むことをしない」。

### マタイ 26:26-30

> 26 一同が食事をしているとき、イエスはパンを取り、祝福してこれをさき、弟子たちに与えて言われた、「取って食べよ、これはわたしのからだである」。27 また杯を取り、感謝して彼らに与えて言われた、「みな、この杯から飲め。28 これは、罪のゆるしを得させるようにと、多くの人のために流すわたしの契約の血である。29 あなたがたに言っておく。わたしの父の国であなたがたと共に、新しく飲むその日までは、わたしは今後決して、ぶどうの実から造ったものを飲むことをしない」。30 彼らは、さんびを歌った後、オリブ山へ出かけて行った。

### ルカ 22:15-20

> 15 イエスは彼らに言われた、「わたしは苦しみを受ける前に、あなたがたとこの過越の食事をしようと、切に望んでいた。16 あなたがたに言って置くが、神の国で過越が成就する時までは、わたしは二度と、この過越の食事をすることはない」。17 そして杯を取り、感謝して言われた、「これを取って、互に分けて飲め。18 あなたがたに言っておくが、今からのち神の国が来るまでは、わたしはぶどうの実から造ったものを、いっさい飲まない」。19 またパンを取り、感謝してこれをさき、弟子たちに与えて言われた、「これは、あなたがたのために与えるわたしのからだである。わたしを記念するため、このように行いなさい」。20 食事ののち、杯も同じ様にして言われた、「この杯は、あなたがたのために流すわたしの血で立てられる新しい契約である。

[マルコによる福音書14章22-25節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_22-25.pdf)

### 問い

1.  22--25節で、イエスは、何をしていますか。どのような意味があるのでしょうか。

2.  イエスはどんな預言をしていますか。

### 参照

-   コリント前書11:23-28 23 わたしは、主から受けたことを、また、あなたがたに伝えたのである。すなわち、主イエスは、渡される夜、パンをとり、24 感謝してこれをさき、そして言われた、「これはあなたがたのための、わたしのからだである。わたしを記念するため、このように行いなさい」。25 食事ののち、杯をも同じようにして言われた、「この杯は、わたしの血による新しい契約である。飲むたびに、わたしの記念として、このように行いなさい」。26 だから、あなたがたは、このパンを食し、この杯を飲むごとに、それによって、主がこられる時に至るまで、主の死を告げ知らせるのである。27 だから、ふさわしくないままでパンを食し主の杯を飲む者は、主のからだと血とを犯すのである。28 だれでもまず自分を吟味し、それからパンを食べ杯を飲むべきである。29 主のからだをわきまえないで飲み食いする者は、その飲み食いによって自分にさばきを招くからである。

### 記録

-   日時：2025年1月23日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 14:26-31 ペトロの離反を予告する

> 26 彼らは、さんびを歌った後、オリブ山へ出かけて行った。27 そのとき、イエスは弟子たちに言われた、「あなたがたは皆、わたしにつまずくであろう。『わたしは羊飼を打つ。そして、羊は散らされるであろう』と書いてあるからである。28 しかしわたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」。29 するとペテロはイエスに言った、「たとい、みんなの者がつまずいても、わたしはつまずきません」。30 イエスは言われた、「あなたによく言っておく。きょう、今夜、にわとりが二度鳴く前に、そう言うあなたが、三度わたしを知らないと言うだろう」。31 ペテロは力をこめて言った、「たといあなたと一緒に死なねばならなくなっても、あなたを知らないなどとは、決して申しません」。みんなの者もまた、同じようなことを言った。

### マタイ 26:31-35

> 31 そのとき、イエスは弟子たちに言われた、「今夜、あなたがたは皆わたしにつまずくであろう。『わたしは羊飼を打つ。そして、羊の群れは散らされるであろう』と、書いてあるからである。32 しかしわたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」。33 するとペテロはイエスに答えて言った、「たとい、みんなの者があなたにつまずいても、わたしは決してつまずきません」。34 イエスは言われた、「よくあなたに言っておく。今夜、鶏が鳴く前に、あなたは三度わたしを知らないと言うだろう」。35 ペテロは言った、「たといあなたと一緒に死なねばならなくなっても、あなたを知らないなどとは、決して申しません」。弟子たちもみな同じように言った。

### ルカ 22:31-34

> 31 シモン、シモン、見よ、サタンはあなたがたを麦のようにふるいにかけることを願って許された。32 しかし、わたしはあなたの信仰がなくならないように、あなたのために祈った。それで、あなたが立ち直ったときには、兄弟たちを力づけてやりなさい」。33 シモンが言った、「主よ、わたしは獄にでも、また死に至るまでも、あなたとご一緒に行く覚悟です」。34 するとイエスが言われた、「ペテロよ、あなたに言っておく。きょう、鶏が鳴くまでに、あなたは三度わたしを知らないと言うだろう」。

### ヨハネ 13:36-38

> 36 シモン・ペテロがイエスに言った、「主よ、どこへおいでになるのですか」。イエスは答えられた、「あなたはわたしの行くところに、今はついて来ることはできない。しかし、あとになってから、ついて来ることになろう」。37 ペテロはイエスに言った、「主よ、なぜ、今あなたについて行くことができないのですか。あなたのためには、命も捨てます」。38 イエスは答えられた、「わたしのために命を捨てると言うのか。よくよくあなたに言っておく。鶏が鳴く前に、あなたはわたしを三度知らないと言うであろう」。

[マルコによる福音書14章26-31 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_26-31.pdf)

### 問い

1.  ペテロは、なぜこれほど強く言い切るのでしょうか。

2.  イエスは、そのペテロに何と言っていますか。

### 参照

-   ルカではこのあと「財布と袋と剣」の記事の挿入（ルカ22:35-38）

### 記録

-   日時：2025年1月30日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 14:32-42 ゲッセマネで祈る

> 32 さて、一同はゲツセマネという所にきた。そしてイエスは弟子たちに言われた、「わたしが祈っている間、ここにすわっていなさい」。33 そしてペテロ、ヤコブ、ヨハネを一緒に連れて行かれたが、恐れおののき、また悩みはじめて、彼らに言われた、34 「わたしは悲しみのあまり死ぬほどである。ここに待っていて、目をさましていなさい」。35 そして少し進んで行き、地にひれ伏し、もしできることなら、この時を過ぎ去らせてくださるようにと祈りつづけ、そして言われた、36 「アバ、父よ、あなたには、できないことはありません。どうか、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころのままになさってください」。37 それから、きてごらんになると、弟子たちが眠っていたので、ペテロに言われた、「シモンよ、眠っているのか、ひと時も目をさましていることができなかったのか。38 誘惑に陥らないように、目をさまして祈っていなさい。心は熱しているが、肉体が弱いのである」。39 また離れて行って同じ言葉で祈られた。40 またきてごらんになると、彼らはまだ眠っていた。その目が重くなっていたのである。そして、彼らはどうお答えしてよいか、わからなかった。41 三度目にきて言われた、「まだ眠っているのか、休んでいるのか。もうそれでよかろう。時がきた。見よ、人の子は罪人らの手に渡されるのだ。42 立て、さあ行こう。見よ。わたしを裏切る者が近づいてきた」。

### マタイ 26:36-46

> 36 それから、イエスは彼らと一緒に、ゲツセマネという所へ行かれた。そして弟子たちに言われた、「わたしが向こうへ行って祈っている間、ここにすわっていなさい」。37 そしてペテロとゼベダイの子ふたりとを連れて行かれたが、悲しみを催しまた悩みはじめられた。38 そのとき、彼らに言われた、「わたしは悲しみのあまり死ぬほどである。ここに待っていて、わたしと一緒に目をさましていなさい」。39 そして少し進んで行き、うつぶしになり、祈って言われた、「わが父よ、もしできることでしたらどうか、この杯をわたしから過ぎ去らせてください。しかし、わたしの思いのままにではなく、みこころのままになさって下さい」。40 それから、弟子たちの所にきてごらんになると、彼らが眠っていたので、ペテロに言われた、「あなたがたはそんなに、ひと時もわたしと一緒に目をさましていることが、できなかったのか。41 誘惑に陥らないように、目をさまして祈っていなさい。心は熱しているが、肉体が弱いのである」。42 また二度目に行って、祈って言われた、「わが父よ、この杯を飲むほかに道がないのでしたら、どうか、みこころが行われますように」。43 またきてごらんになると、彼らはまた眠っていた。その目が重くなっていたのである。44 それで彼らをそのままにして、また行って、三度目に同じ言葉で祈られた。45 それから弟子たちの所に帰ってきて、言われた、「まだ眠っているのか、休んでいるのか。見よ、時が迫った。人の子は罪人らの手に渡されるのだ。46 立て、さあ行こう。見よ、わたしを裏切る者が近づいてきた」。

### ルカ 22:39-46

> 39 イエスは出て、いつものようにオリブ山に行かれると、弟子たちも従って行った。40 いつもの場所に着いてから、彼らに言われた、「誘惑に陥らないように祈りなさい」。41 そしてご自分は、石を投げてとどくほど離れたところへ退き、ひざまずいて、祈って言われた、42 「父よ、みこころならば、どうぞ、この杯をわたしから取りのけてください。しかし、わたしの思いではなく、みこころが成るようにしてください」。43 そのとき、御使が天からあらわれてイエスを力づけた。44 イエスは苦しみもだえて、ますます切に祈られた。そして、その汗が血のしたたりのように地に落ちた。45 祈を終えて立ちあがり、弟子たちのところへ行かれると、彼らが悲しみのはて寝入っているのをごらんになって 46 言われた、「なぜ眠っているのか。誘惑に陥らないように、起きて祈っていなさい」。

[マルコによる福音書14章32-42 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_32-42.pdf)

### 問い

1.  イエスはどのように祈っていますか。

2.  弟子たちは、どうしていますか。

### 参照

### 記録

-   日時：2025年2月6日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 14:43-50 裏切られ、逮捕される

> 43 そしてすぐ、イエスがまだ話しておられるうちに、十二弟子のひとりのユダが進みよってきた。また祭司長、律法学者、長老たちから送られた群衆も、剣と棒とを持って彼についてきた。44 イエスを裏切る者は、あらかじめ彼らに合図をしておいた、「わたしの接吻する者が、その人だ。その人をつかまえて、まちがいなく引っぱって行け」。45 彼は来るとすぐ、イエスに近寄り、「先生」と言って接吻した。46 人々はイエスに手をかけてつかまえた。47 すると、イエスのそばに立っていた者のひとりが、剣を抜いて大祭司の僕に切りかかり、その片耳を切り落した。48 イエスは彼らにむかって言われた、「あなたがたは強盗にむかうように、剣や棒を持ってわたしを捕えにきたのか。49 わたしは毎日あなたがたと一緒に宮にいて教えていたのに、わたしをつかまえはしなかった。しかし聖書の言葉は成就されねばならない」。50 弟子たちは皆イエスを見捨てて逃げ去った。

### マタイ 26:47-56

> 47 そして、イエスがまだ話しておられるうちに、そこに、十二弟子のひとりのユダがきた。また祭司長、民の長老たちから送られた大ぜいの群衆も、剣と棒とを持って彼についてきた。48 イエスを裏切った者が、あらかじめ彼らに、「わたしの接吻する者が、その人だ。その人をつかまえろ」と合図をしておいた。49 彼はすぐイエスに近寄り、「先生、いかがですか」と言って、イエスに接吻した。50 しかし、イエスは彼に言われた、「友よ、なんのためにきたのか」。このとき、人々は進み寄って、イエスに手をかけてつかまえた。51 すると、イエスと一緒にいた者のひとりが、手を伸ばして剣を抜き、そして大祭司の僕に切りかかって、その片耳を切り落した。52 そこで、イエスは彼に言われた、「あなたの剣をもとの所におさめなさい。剣をとる者はみな、剣で滅びる。53 それとも、わたしが父に願って、天の使たちを十二軍団以上も、今つかわしていただくことができないと、あなたは思うのか。54 しかし、それでは、こうならねばならないと書いてある聖書の言葉は、どうして成就されようか」。55 そのとき、イエスは群衆に言われた、「あなたがたは強盗にむかうように、剣や棒を持ってわたしを捕えにきたのか。わたしは毎日、宮ですわって教えていたのに、わたしをつかまえはしなかった。56 しかし、すべてこうなったのは、預言者たちの書いたことが、成就するためである」。そのとき、弟子たちは皆イエスを見捨てて逃げ去った。

### ルカ 22:47-53

> 47 イエスがまだそう言っておられるうちに、そこに群衆が現れ、十二弟子のひとりでユダという者が先頭に立って、イエスに接吻しようとして近づいてきた。48 そこでイエスは言われた、「ユダ、あなたは接吻をもって人の子を裏切るのか」。49 イエスのそばにいた人たちは、事のなりゆきを見て、「主よ、つるぎで切りつけてやりましょうか」と言って、50 そのうちのひとりが、祭司長の僕に切りつけ、その右の耳を切り落した。51 イエスはこれに対して言われた、「それだけでやめなさい」。そして、その僕の耳に手を触れて、おいやしになった。52 それから、自分にむかって来る祭司長、宮守がしら、長老たちに対して言われた、「あなたがたは、強盗にむかうように剣や棒を持って出てきたのか。53 毎日あなたがたと一緒に宮にいた時には、わたしに手をかけなかった。だが、今はあなたがたの時、また、やみの支配の時である」。

### ヨハネ 18:3-12

> 3 さてユダは、一隊の兵卒と祭司長やパリサイ人たちの送った下役どもを引き連れ、たいまつやあかりや武器を持って、そこへやってきた。4 しかしイエスは、自分の身に起ろうとすることをことごとく承知しておられ、進み出て彼らに言われた、「だれを捜しているのか」。5 彼らは「ナザレのイエスを」と答えた。イエスは彼らに言われた、「わたしが、それである」。イエスを裏切ったユダも、彼らと一緒に立っていた。6 イエスが彼らに「わたしが、それである」と言われたとき、彼らはうしろに引きさがって地に倒れた。7 そこでまた彼らに、「だれを捜しているのか」とお尋ねになると、彼らは「ナザレのイエスを」と言った。8 イエスは答えられた、「わたしがそれであると、言ったではないか。わたしを捜しているのなら、この人たちを去らせてもらいたい」。9 それは、「あなたが与えて下さった人たちの中のひとりも、わたしは失わなかった」とイエスの言われた言葉が、成就するためである。10 シモン・ペテロは剣を持っていたが、それを抜いて、大祭司の僕に切りかかり、その右の耳を切り落した。その僕の名はマルコスであった。11 すると、イエスはペテロに言われた、「剣をさやに納めなさい。父がわたしに下さった杯は、飲むべきではないか」。12 それから一隊の兵卒やその千卒長やユダヤ人の下役どもが、イエスを捕え、縛りあげて、

[マルコによる福音書14章43-50 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50.pdf)

[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)

<!-- ### 問い -->

<!-- 1.  この場面を描いてみましょう。 -->

<!-- 2.  イエスはどのように対応しますか。 -->

<!-- 3.  ペテロや他の弟子たちはなぜ逃げてしまったのでしょう。 -->

<!-- ### 参照 -->

<!-- ### 記録 -->

<!-- -   日時：2025年2月13日午後7時半〜9時半 -->

<!-- -   出席（対面）X名、参加（遠隔）Y名 -->

<!-- ### 問いについて -->

<!-- ### メモ -->

## 14:51-52 一人の若者、逃げる

> 51 ときに、ある若者が身に亜麻布をまとって、イエスのあとについて行ったが、人々が彼をつかまえようとしたので、52 その亜麻布を捨てて、裸で逃げて行った。

[マルコによる福音書14章51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_51-52.pdf)

[マルコによる福音書14章43-50,51-52 節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_43-50_51-52.pdf)

### 問い

1.  この場面を描いてみましょう。

2.  イエスはどのように対応しますか。

3.  ペテロや他の弟子たちはなぜ逃げてしまったのでしょう。

### 参照

### 記録

-   日時：2025年2月13日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 14:53-65 最高法院で裁判を受ける

> 53 それから、イエスを大祭司のところに連れて行くと、祭司長、長老、律法学者たちがみな集まってきた。54 ペテロは遠くからイエスについて行って、大祭司の中庭まではいり込み、その下役どもにまじってすわり、火にあたっていた。55 さて、祭司長たちと全議会とは、イエスを死刑にするために、イエスに不利な証拠を見つけようとしたが、得られなかった。56 多くの者がイエスに対して偽証を立てたが、その証言が合わなかったからである。57 ついに、ある人々が立ちあがり、イエスに対して偽証を立てて言った、58 「わたしたちはこの人が『わたしは手で造ったこの神殿を打ちこわし、三日の後に手で造られない別の神殿を建てるのだ』と言うのを聞きました」。59 しかし、このような証言も互に合わなかった。60 そこで大祭司が立ちあがって、まん中に進み、イエスに聞きただして言った、「何も答えないのか。これらの人々があなたに対して不利な証言を申し立てているが、どうなのか」。61 しかし、イエスは黙っていて、何もお答えにならなかった。大祭司は再び聞きただして言った、「あなたは、ほむべき者の子、キリストであるか」。62 イエスは言われた、「わたしがそれである。あなたがたは人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」。63 すると、大祭司はその衣を引き裂いて言った、「どうして、これ以上、証人の必要があろう。64 あなたがたはこのけがし言を聞いた。あなたがたの意見はどうか」。すると、彼らは皆、イエスを死に当るものと断定した。65 そして、ある者はイエスにつばきをかけ、目隠しをし、こぶしでたたいて、「言いあててみよ」と言いはじめた。また下役どもはイエスを引きとって、手のひらでたたいた。

### マタイ 26:57-68

> 57 さて、イエスをつかまえた人たちは、大祭司カヤパのところにイエスを連れて行った。そこには律法学者、長老たちが集まっていた。58 ペテロは遠くからイエスについて、大祭司の中庭まで行き、そのなりゆきを見とどけるために、中にはいって下役どもと一緒にすわっていた。59 さて、祭司長たちと全議会とは、イエスを死刑にするため、イエスに不利な偽証を求めようとしていた。60 そこで多くの偽証者が出てきたが、証拠があがらなかった。しかし、最後にふたりの者が出てきて、61 言った、「この人は、わたしは神の宮を打ちこわし、三日の後に建てることができる、と言いました」。62 すると、大祭司が立ち上がってイエスに言った、「何も答えないのか。これらの人々があなたに対して不利な証言を申し立てているが、どうなのか」。63 しかし、イエスは黙っておられた。そこで大祭司は言った、「あなたは神の子キリストなのかどうか、生ける神に誓ってわれわれに答えよ」。64 イエスは彼に言われた、「あなたの言うとおりである。しかし、わたしは言っておく。あなたがたは、間もなく、人の子が力ある者の右に座し、天の雲に乗って来るのを見るであろう」。65 すると、大祭司はその衣を引き裂いて言った、「彼は神を汚した。どうしてこれ以上、証人の必要があろう。あなたがたは今このけがし言を聞いた。66 あなたがたの意見はどうか」。すると、彼らは答えて言った、「彼は死に当るものだ」。67 それから、彼らはイエスの顔につばきをかけて、こぶしで打ち、またある人は手のひらでたたいて言った、68 「キリストよ、言いあててみよ、打ったのはだれか」。

### ルカ 22:54-55; 61-71

> 54 それから人々はイエスを捕え、ひっぱって大祭司の邸宅へつれて行った。ペテロは遠くからついて行った。55 人々は中庭のまん中に火をたいて、一緒にすわっていたので、ペテロもその中にすわった。
>
> 61 主は振りむいてペテロを見つめられた。そのときペテロは、「きょう、鶏が鳴く前に、三度わたしを知らないと言うであろう」と言われた主のお言葉を思い出した。62 そして外へ出て、激しく泣いた。63 イエスを監視していた人たちは、イエスを嘲弄し、打ちたたき、64 目かくしをして、「言いあててみよ。打ったのは、だれか」ときいたりした。65 そのほか、いろいろな事を言って、イエスを愚弄した。66 夜が明けたとき、人民の長老、祭司長たち、律法学者たちが集まり、イエスを議会に引き出して言った、67 「あなたがキリストなら、そう言ってもらいたい」。イエスは言われた、「わたしが言っても、あなたがたは信じないだろう。68 また、わたしがたずねても、答えないだろう。69 しかし、人の子は今からのち、全能の神の右に座するであろう」。70 彼らは言った、「では、あなたは神の子なのか」。イエスは言われた、「あなたがたの言うとおりである」。71 すると彼らは言った、「これ以上、なんの証拠がいるか。われわれは直接彼の口から聞いたのだから」。

### ヨハネ 18:13-14; 19-24

> 13 まずアンナスのところに引き連れて行った。彼はその年の大祭司カヤパのしゅうとであった。14 カヤパは前に、ひとりの人が民のために死ぬのはよいことだと、ユダヤ人に助言した者であった。
>
> 19 大祭司はイエスに、弟子たちのことやイエスの教のことを尋ねた。20 イエスは答えられた、「わたしはこの世に対して公然と語ってきた。すべてのユダヤ人が集まる会堂や宮で、いつも教えていた。何事も隠れて語ったことはない。21 なぜ、わたしに尋ねるのか。わたしが彼らに語ったことは、それを聞いた人々に尋ねるがよい。わたしの言ったことは、彼らが知っているのだから」。22 イエスがこう言われると、そこに立っていた下役のひとりが、「大祭司にむかって、そのような答をするのか」と言って、平手でイエスを打った。23 イエスは答えられた、「もしわたしが何か悪いことを言ったのなら、その悪い理由を言いなさい。しかし、正しいことを言ったのなら、なぜわたしを打つのか」。24 それからアンナスは、イエスを縛ったまま大祭司カヤパのところへ送った。

[マルコによる福音書14章53-65節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_53-65.pdf)

### 問い

1.  ユダヤの最高裁判所である、議会の目的は何ですか。どのような告発が書いてありますか。

2.  大祭司は、どのような尋問をしますか。

### 参照

### 記録

-   日時：2025年2月20日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 14:66-72 ペトロ、イエスを知らないと言う

> 66 ペテロは下で中庭にいたが、大祭司の女中のひとりがきて、67 ペテロが火にあたっているのを見ると、彼を見つめて、「あなたもあのナザレ人イエスと一緒だった」と言った。68 するとペテロはそれを打ち消して、「わたしは知らない。あなたの言うことがなんの事か、わからない」と言って、庭口の方に出て行った。69 ところが、先の女中が彼を見て、そばに立っていた人々に、またもや「この人はあの仲間のひとりです」と言いだした。70 ペテロは再びそれを打ち消した。しばらくして、そばに立っていた人たちがまたペテロに言った、「確かにあなたは彼らの仲間だ。あなたもガリラヤ人だから」。71 しかし、彼は、「あなたがたの話しているその人のことは何も知らない」と言い張って、激しく誓いはじめた。72 するとすぐ、にわとりが二度目に鳴いた。ペテロは、「にわとりが二度鳴く前に、三度わたしを知らないと言うであろう」と言われたイエスの言葉を思い出し、そして思いかえして泣きつづけた。

### マタイ 26:69-75

> 69 ペテロは外で中庭にすわっていた。するとひとりの女中が彼のところにきて、「あなたもあのガリラヤ人イエスと一緒だった」と言った。70 するとペテロは、みんなの前でそれを打ち消して言った、「あなたが何を言っているのか、わからない」。71 そう言って入口の方に出て行くと、ほかの女中が彼を見て、そこにいる人々にむかって、「この人はナザレ人イエスと一緒だった」と言った。72 そこで彼は再びそれを打ち消して、「そんな人は知らない」と誓って言った。73 しばらくして、そこに立っていた人々が近寄ってきて、ペテロに言った、「確かにあなたも彼らの仲間だ。言葉づかいであなたのことがわかる」。74 彼は「その人のことは何も知らない」と言って、激しく誓いはじめた。するとすぐ鶏が鳴いた。75 ペテロは「鶏が鳴く前に、三度わたしを知らないと言うであろう」と言われたイエスの言葉を思い出し、外に出て激しく泣いた。

### ルカ 22:56-62

> 56 すると、ある女中が、彼が火のそばにすわっているのを見、彼を見つめて、「この人もイエスと一緒にいました」と言った。57 ペテロはそれを打ち消して、「わたしはその人を知らない」と言った。58 しばらくして、ほかの人がペテロを見て言った、「あなたもあの仲間のひとりだ」。するとペテロは言った、「いや、それはちがう」。59 約一時間たってから、またほかの者が言い張った、「たしかにこの人もイエスと一緒だった。この人もガリラヤ人なのだから」。60 ペテロは言った、「あなたの言っていることは、わたしにわからない」。すると、彼がまだ言い終らぬうちに、たちまち、鶏が鳴いた。61 主は振りむいてペテロを見つめられた。そのときペテロは、「きょう、鶏が鳴く前に、三度わたしを知らないと言うであろう」と言われた主のお言葉を思い出した。62 そして外へ出て、激しく泣いた。

### ヨハネ 18:15-18; 25-27

> 15 シモン・ペテロともうひとりの弟子とが、イエスについて行った。この弟子は大祭司の知り合いであったので、イエスと一緒に大祭司の中庭にはいった。16 しかし、ペテロは外で戸口に立っていた。すると大祭司の知り合いであるその弟子が、外に出て行って門番の女に話し、ペテロを内に入れてやった。17 すると、この門番の女がペテロに言った、「あなたも、あの人の弟子のひとりではありませんか」。ペテロは「いや、そうではない」と答えた。18 僕や下役どもは、寒い時であったので、炭火をおこし、そこに立ってあたっていた。ペテロもまた彼らに交じり、立ってあたっていた。
>
> 25 シモン・ペテロは、立って火にあたっていた。すると人々が彼に言った、「あなたも、あの人の弟子のひとりではないか」。彼はそれをうち消して、「いや、そうではない」と言った。26 大祭司の僕のひとりで、ペテロに耳を切りおとされた人の親族の者が言った、「あなたが園であの人と一緒にいるのを、わたしは見たではないか」。27 ペテロはまたそれを打ち消した。するとすぐに、鶏が鳴いた。

[マルコによる福音書14章66-72節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark14_66-72.pdf)

### 問い

1.  ペテロの裏切りの記事を一回一回追ってみましょう。どのように言われ、ペテロはどのように答えますか。

2.  あなたならどうするでしょうか。

### 参照

### 記録

-   日時：2025年2月27日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:1-5 ピラトから尋問される

> 1 夜が明けるとすぐ、祭司長たちは長老、律法学者たち、および全議会と協議をこらした末、イエスを縛って引き出し、ピラトに渡した。2 ピラトはイエスに尋ねた、「あなたがユダヤ人の王であるか」。イエスは、「そのとおりである」とお答えになった。3 そこで祭司長たちは、イエスのことをいろいろと訴えた。4 ピラトはもう一度イエスに尋ねた、「何も答えないのか。見よ、あなたに対してあんなにまで次々に訴えているではないか」。5 しかし、イエスはピラトが不思議に思うほどに、もう何もお答えにならなかった。

### マタイ 27:1-2; 11-14

> 1 夜が明けると、祭司長たち、民の長老たち一同は、イエスを殺そうとして協議をこらした上、2 イエスを縛って引き出し、総督ピラトに渡した。
>
> 11 さて、イエスは総督の前に立たれた。すると総督はイエスに尋ねて言った、「あなたがユダヤ人の王であるか」。イエスは「そのとおりである」と言われた。12 しかし、祭司長、長老たちが訴えている間、イエスはひと言もお答えにならなかった。13 するとピラトは言った、「あんなにまで次々に、あなたに不利な証言を立てているのが、あなたには聞えないのか」。14 しかし、総督が非常に不思議に思ったほどに、イエスは何を言われても、ひと言もお答えにならなかった。

### ルカ 23:1-5

> 1 群衆はみな立ちあがって、イエスをピラトのところへ連れて行った。2 そして訴え出て言った、「わたしたちは、この人が国民を惑わし、貢をカイザルに納めることを禁じ、また自分こそ王なるキリストだと、となえているところを目撃しました」。3 ピラトはイエスに尋ねた、「あなたがユダヤ人の王であるか」。イエスは「そのとおりである」とお答えになった。4 そこでピラトは祭司長たちと群衆とにむかって言った、「わたしはこの人になんの罪もみとめない」。5 ところが彼らは、ますます言いつのってやまなかった、「彼は、ガリラヤからはじめてこの所まで、ユダヤ全国にわたって教え、民衆を煽動しているのです」。

### ヨハネ 18:28-38

> 28 それから人々は、イエスをカヤパのところから官邸につれて行った。時は夜明けであった。彼らは、けがれを受けないで過越の食事ができるように、官邸にはいらなかった。29 そこで、ピラトは彼らのところに出てきて言った、「あなたがたは、この人に対してどんな訴えを起すのか」。30 彼らはピラトに答えて言った、「もしこの人が悪事をはたらかなかったなら、あなたに引き渡すようなことはしなかったでしょう」。31 そこでピラトは彼らに言った、「あなたがたは彼を引き取って、自分たちの律法でさばくがよい」。ユダヤ人らは彼に言った、「わたしたちには、人を死刑にする権限がありません」。32 これは、ご自身がどんな死にかたをしようとしているかを示すために言われたイエスの言葉が、成就するためである。33 さて、ピラトはまた官邸にはいり、イエスを呼び出して言った、「あなたは、ユダヤ人の王であるか」。34 イエスは答えられた、「あなたがそう言うのは、自分の考えからか。それともほかの人々が、わたしのことをあなたにそう言ったのか」。35 ピラトは答えた、「わたしはユダヤ人なのか。あなたの同族や祭司長たちが、あなたをわたしに引き渡したのだ。あなたは、いったい、何をしたのか」。36 イエスは答えられた、「わたしの国はこの世のものではない。もしわたしの国がこの世のものであれば、わたしに従っている者たちは、わたしをユダヤ人に渡さないように戦ったであろう。しかし事実、わたしの国はこの世のものではない」。37 そこでピラトはイエスに言った、「それでは、あなたは王なのだな」。イエスは答えられた、「あなたの言うとおり、わたしは王である。わたしは真理についてあかしをするために生れ、また、そのためにこの世にきたのである。だれでも真理につく者は、わたしの声に耳を傾ける」38 ピラトはイエスに言った、「真理とは何か」。こう言って、彼はまたユダヤ人の所に出て行き、彼らに言った、「わたしには、この人になんの罪も見いだせない。

[マルコによる福音書15章1-5節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_1-5.pdf)

### 問い

1.  議会はなぜ、ピラトに引き渡すのでしょうか。

2.  ピラとはどんな尋問をし、イエスはどのように答えますか。

### 参照

-   マタイでは、ユダ、自殺するが挿入されている（マタイ27:3-10）

-   ルカでは、ヘロデから尋問される（23:6-12）

### 記録

-   日時：2025年3月6日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:6-15 死刑の判決を受ける

> 6 さて、祭のたびごとに、ピラトは人々が願い出る囚人ひとりを、ゆるしてやることにしていた。7 ここに、暴動を起し人殺しをしてつながれていた暴徒の中に、バラバという者がいた。8 群衆が押しかけてきて、いつものとおりにしてほしいと要求しはじめたので、9 ピラトは彼らにむかって、「おまえたちはユダヤ人の王をゆるしてもらいたいのか」と言った。10 それは、祭司長たちがイエスを引きわたしたのは、ねたみのためであることが、ピラトにわかっていたからである。11 しかし祭司長たちは、バラバの方をゆるしてもらうように、群衆を煽動した。12 そこでピラトはまた彼らに言った、「それでは、おまえたちがユダヤ人の王と呼んでいるあの人は、どうしたらよいか」。13 彼らは、また叫んだ、「十字架につけよ」。14 ピラトは言った、「あの人は、いったい、どんな悪事をしたのか」。すると、彼らは一そう激しく叫んで、「十字架につけよ」と言った。15 それで、ピラトは群衆を満足させようと思って、バラバをゆるしてやり、イエスをむち打ったのち、十字架につけるために引きわたした。

### マタイ 27:15-26

> 15 さて、祭のたびごとに、総督は群衆が願い出る囚人ひとりを、ゆるしてやる慣例になっていた。16 ときに、バラバという評判の囚人がいた。17 それで、彼らが集まったとき、ピラトは言った、「おまえたちは、だれをゆるしてほしいのか。バラバか、それとも、キリストといわれるイエスか」。18 彼らがイエスを引きわたしたのは、ねたみのためであることが、ピラトにはよくわかっていたからである。19 また、ピラトが裁判の席についていたとき、その妻が人を彼のもとにつかわして、「あの義人には関係しないでください。わたしはきょう夢で、あの人のためにさんざん苦しみましたから」と言わせた。20 しかし、祭司長、長老たちは、バラバをゆるして、イエスを殺してもらうようにと、群衆を説き伏せた。21 総督は彼らにむかって言った、「ふたりのうち、どちらをゆるしてほしいのか」。彼らは「バラバの方を」と言った。22 ピラトは言った、「それではキリストといわれるイエスは、どうしたらよいか」。彼らはいっせいに「十字架につけよ」と言った。23 しかし、ピラトは言った、「あの人は、いったい、どんな悪事をしたのか」。すると彼らはいっそう激しく叫んで、「十字架につけよ」と言った。24 ピラトは手のつけようがなく、かえって暴動になりそうなのを見て、水を取り、群衆の前で手を洗って言った、「この人の血について、わたしには責任がない。おまえたちが自分で始末をするがよい」。25 すると、民衆全体が答えて言った、「その血の責任は、われわれとわれわれの子孫の上にかかってもよい」。26 そこで、ピラトはバラバをゆるしてやり、イエスをむち打ったのち、十字架につけるために引きわたした。

### ルカ 23:13-25

> 13 ピラトは、祭司長たちと役人たちと民衆とを、呼び集めて言った、14 「おまえたちは、この人を民衆を惑わすものとしてわたしのところに連れてきたので、おまえたちの面前でしらべたが、訴え出ているような罪は、この人に少しもみとめられなかった。15 ヘロデもまたみとめなかった。現に彼はイエスをわれわれに送りかえしてきた。この人はなんら死に当るようなことはしていないのである。16 だから、彼をむち打ってから、ゆるしてやることにしよう」。17 〔祭ごとにピラトがひとりの囚人をゆるしてやることになっていた。〕18 ところが、彼らはいっせいに叫んで言った、「その人を殺せ。バラバをゆるしてくれ」。19 このバラバは、都で起った暴動と殺人とのかどで、獄に投ぜられていた者である。20 ピラトはイエスをゆるしてやりたいと思って、もう一度かれらに呼びかけた。21 しかし彼らは、わめきたてて「十字架につけよ、彼を十字架につけよ」と言いつづけた。22 ピラトは三度目に彼らにむかって言った、「では、この人は、いったい、どんな悪事をしたのか。彼には死に当る罪は全くみとめられなかった。だから、むち打ってから彼をゆるしてやることにしよう」。23 ところが、彼らは大声をあげて詰め寄り、イエスを十字架につけるように要求した。そして、その声が勝った。24 ピラトはついに彼らの願いどおりにすることに決定した。25 そして、暴動と殺人とのかどで獄に投ぜられた者の方を、彼らの要求に応じてゆるしてやり、イエスの方は彼らに引き渡して、その意のままにまかせた。

### ヨハネ 18:39-19:16

> 39 過越の時には、わたしがあなたがたのために、ひとりの人を許してやるのが、あなたがたのしきたりになっている。ついては、あなたがたは、このユダヤ人の王を許してもらいたいのか」。40 すると彼らは、また叫んで「その人ではなく、バラバを」と言った。このバラバは強盗であった。
>
> 1 そこでピラトは、イエスを捕え、むちで打たせた。2 兵卒たちは、いばらで冠をあんで、イエスの頭にかぶらせ、紫の上着を着せ、3 それから、その前に進み出て、「ユダヤ人の王、ばんざい」と言った。そして平手でイエスを打ちつづけた。4 するとピラトは、また出て行ってユダヤ人たちに言った、「見よ、わたしはこの人をあなたがたの前に引き出すが、それはこの人になんの罪も見いだせないことを、あなたがたに知ってもらうためである」。5 イエスはいばらの冠をかぶり、紫の上着を着たままで外へ出られると、ピラトは彼らに言った、「見よ、この人だ」。6 祭司長たちや下役どもはイエスを見ると、叫んで「十字架につけよ、十字架につけよ」と言った。ピラトは彼らに言った、「あなたがたが、この人を引き取って十字架につけるがよい。わたしは、彼にはなんの罪も見いだせない」。7 ユダヤ人たちは彼に答えた、「わたしたちには律法があります。その律法によれば、彼は自分を神の子としたのだから、死罪に当る者です」。8 ピラトがこの言葉を聞いたとき、ますますおそれ、9 もう一度官邸にはいってイエスに言った、「あなたは、もともと、どこからきたのか」。しかし、イエスはなんの答もなさらなかった。10 そこでピラトは言った、「何も答えないのか。わたしには、あなたを許す権威があり、また十字架につける権威があることを、知らないのか」。11 イエスは答えられた、「あなたは、上から賜わるのでなければ、わたしに対してなんの権威もない。だから、わたしをあなたに引き渡した者の罪は、もっと大きい」。12 これを聞いて、ピラトはイエスを許そうと努めた。しかしユダヤ人たちが叫んで言った、「もしこの人を許したなら、あなたはカイザルの味方ではありません。自分を王とするものはすべて、カイザルにそむく者です」。13 ピラトはこれらの言葉を聞いて、イエスを外へ引き出して行き、敷石（ヘブル語ではガバタ）という場所で裁判の席についた。14 その日は過越の準備の日であって、時は昼の十二時ころであった。ピラトはユダヤ人らに言った、「見よ、これがあなたがたの王だ」。15 すると彼らは叫んだ、「殺せ、殺せ、彼を十字架につけよ」。ピラトは彼らに言った、「あなたがたの王を、わたしが十字架につけるのか」。祭司長たちは答えた、「わたしたちには、カイザル以外に王はありません」。16 そこでピラトは、十字架につけさせるために、イエスを彼らに引き渡した。彼らはイエスを引き取った。

[マルコによる福音書15章6-15節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_6-15.pdf)

### 問い

1.  ピラトが問題にしているのはどんなことでしょうか。

2.  ピラトが群衆を静めようとして利用したのはどんな習慣ですか。バラバについて何がわかりますか。

3.  ピラトはどのような価値観から行動していると思いますか。

### 参照

### 記録

-   日時：2025年3月13日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:16-20 兵士から侮辱される

> 16 兵士たちはイエスを、邸宅、すなわち総督官邸の内に連れて行き、全部隊を呼び集めた。17 そしてイエスに紫の衣を着せ、いばらの冠を編んでかぶらせ、18 「ユダヤ人の王、ばんざい」と言って敬礼をしはじめた。19 また、葦の棒でその頭をたたき、つばきをかけ、ひざまずいて拝んだりした。20 こうして、イエスを嘲弄したあげく、紫の衣をはぎとり、元の上着を着せた。それから、彼らはイエスを十字架につけるために引き出した。

### マタイ 27:27-31

> 27 それから総督の兵士たちは、イエスを官邸に連れて行って、全部隊をイエスのまわりに集めた。28 そしてその上着をぬがせて、赤い外套を着せ、29 また、いばらで冠を編んでその頭にかぶらせ、右の手には葦の棒を持たせ、それからその前にひざまずき、嘲弄して、「ユダヤ人の王、ばんざい」と言った。30 また、イエスにつばきをかけ、葦の棒を取りあげてその頭をたたいた。31 こうしてイエスを嘲弄したあげく、外套をはぎ取って元の上着を着せ、それから十字架につけるために引き出した。

### ヨハネ 19:2-3

> 2 兵卒たちは、いばらで冠をあんで、イエスの頭にかぶらせ、紫の上着を着せ、3 それから、その前に進み出て、「ユダヤ人の王、ばんざい」と言った。そして平手でイエスを打ちつづけた。

[マルコによる福音書15章16-20節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_16-20.pdf)

### 問い

1.  10:33, 34 と比較してみましょう。

2.  だれが、どのようにイエスをあざけっていますか。

### 参照

### 記録

-   日時：2025年3月20日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:21-32 十字架につけられる

> 21 そこへ、アレキサンデルとルポスとの父シモンというクレネ人が、郊外からきて通りかかったので、人々はイエスの十字架を無理に負わせた。22 そしてイエスをゴルゴタ、その意味は、されこうべ、という所に連れて行った。23 そしてイエスに、没薬をまぜたぶどう酒をさし出したが、お受けにならなかった。24 それから、イエスを十字架につけた。そしてくじを引いて、だれが何を取るかを定めたうえ、イエスの着物を分けた。25 イエスを十字架につけたのは、朝の九時ごろであった。26 イエスの罪状書きには「ユダヤ人の王」と、しるしてあった。27 また、イエスと共にふたりの強盗を、ひとりを右に、ひとりを左に、十字架につけた。28 〔こうして「彼は罪人たちのひとりに数えられた」と書いてある言葉が成就したのである。〕29 そこを通りかかった者たちは、頭を振りながら、イエスをののしって言った、「ああ、神殿を打ちこわして三日のうちに建てる者よ、30 十字架からおりてきて自分を救え」。31 祭司長たちも同じように、律法学者たちと一緒になって、かわるがわる嘲弄して言った、「他人を救ったが、自分自身を救うことができない。32 イスラエルの王キリスト、いま十字架からおりてみるがよい。それを見たら信じよう」。また、一緒に十字架につけられた者たちも、イエスをののしった。

### マタイ 27:32-44

> 32 彼らが出て行くと、シモンという名のクレネ人に出会ったので、イエスの十字架を無理に負わせた。33 そして、ゴルゴタ、すなわち、されこうべの場、という所にきたとき、34 彼らはにがみをまぜたぶどう酒を飲ませようとしたが、イエスはそれをなめただけで、飲もうとされなかった。35 彼らはイエスを十字架につけてから、くじを引いて、その着物を分け、36 そこにすわってイエスの番をしていた。37 そしてその頭の上の方に、「これはユダヤ人の王イエス」と書いた罪状書きをかかげた。38 同時に、ふたりの強盗がイエスと一緒に、ひとりは右に、ひとりは左に、十字架につけられた。39 そこを通りかかった者たちは、頭を振りながら、イエスをののしって 40 言った、「神殿を打ちこわして三日のうちに建てる者よ。もし神の子なら、自分を救え。そして十字架からおりてこい」。41 祭司長たちも同じように、律法学者、長老たちと一緒になって、嘲弄して言った、42 「他人を救ったが、自分自身を救うことができない。あれがイスラエルの王なのだ。いま十字架からおりてみよ。そうしたら信じよう。43 彼は神にたよっているが、神のおぼしめしがあれば、今、救ってもらうがよい。自分は神の子だと言っていたのだから」。44 一緒に十字架につけられた強盗どもまでも、同じようにイエスをののしった。

### ルカ 23:26-43

> 26 彼らがイエスをひいてゆく途中、シモンというクレネ人が郊外から出てきたのを捕えて十字架を負わせ、それをになってイエスのあとから行かせた。27 大ぜいの民衆と、悲しみ嘆いてやまない女たちの群れとが、イエスに従って行った。28 イエスは女たちの方に振りむいて言われた、「エルサレムの娘たちよ、わたしのために泣くな。むしろ、あなたがた自身のため、また自分の子供たちのために泣くがよい。29 『不妊の女と子を産まなかった胎と、ふくませなかった乳房とは、さいわいだ』と言う日が、いまに来る。30 そのとき、人々は山にむかって、われわれの上に倒れかかれと言い、また丘にむかって、われわれにおおいかぶされと言い出すであろう。31 もし、生木でさえもそうされるなら、枯木はどうされることであろう」。32 さて、イエスと共に刑を受けるために、ほかにふたりの犯罪人も引かれていった。33 されこうべと呼ばれている所に着くと、人々はそこでイエスを十字架につけ、犯罪人たちも、ひとりは右に、ひとりは左に、十字架につけた。34 そのとき、イエスは言われた、「父よ、彼らをおゆるしください。彼らは何をしているのか、わからずにいるのです」。人々はイエスの着物をくじ引きで分け合った。35 民衆は立って見ていた。役人たちもあざ笑って言った、「彼は他人を救った。もし彼が神のキリスト、選ばれた者であるなら、自分自身を救うがよい」。36 兵卒どももイエスをののしり、近寄ってきて酢いぶどう酒をさし出して言った、37 「あなたがユダヤ人の王なら、自分を救いなさい」。38 イエスの上には、「これはユダヤ人の王」と書いた札がかけてあった。39 十字架にかけられた犯罪人のひとりが、「あなたはキリストではないか。それなら、自分を救い、またわれわれも救ってみよ」と、イエスに悪口を言いつづけた。40 もうひとりは、それをたしなめて言った、「おまえは同じ刑を受けていながら、神を恐れないのか。41 お互は自分のやった事のむくいを受けているのだから、こうなったのは当然だ。しかし、このかたは何も悪いことをしたのではない」。42 そして言った、「イエスよ、あなたが御国の権威をもっておいでになる時には、わたしを思い出してください」。43 イエスは言われた、「よく言っておくが、あなたはきょう、わたしと一緒にパラダイスにいるであろう」。

### ヨハネ 19:17-27

> 17 イエスはみずから十字架を背負って、されこうべ（ヘブル語ではゴルゴタ）という場所に出て行かれた。18 彼らはそこで、イエスを十字架につけた。イエスをまん中にして、ほかのふたりの者を両側に、イエスと一緒に十字架につけた。19 ピラトは罪状書きを書いて、十字架の上にかけさせた。それには「ユダヤ人の王、ナザレのイエス」と書いてあった。20 イエスが十字架につけられた場所は都に近かったので、多くのユダヤ人がこの罪状書きを読んだ。それはヘブル、ローマ、ギリシヤの国語で書いてあった。21 ユダヤ人の祭司長たちがピラトに言った、「『ユダヤ人の王』と書かずに、『この人はユダヤ人の王と自称していた』と書いてほしい」。22 ピラトは答えた、「わたしが書いたことは、書いたままにしておけ」。23 さて、兵卒たちはイエスを十字架につけてから、その上着をとって四つに分け、おのおの、その一つを取った。また下着を手に取ってみたが、それには縫い目がなく、上の方から全部一つに織ったものであった。24 そこで彼らは互に言った、「それを裂かないで、だれのものになるか、くじを引こう」。これは、「彼らは互にわたしの上着を分け合い、わたしの衣をくじ引にした」という聖書が成就するためで、兵卒たちはそのようにしたのである。25 さて、イエスの十字架のそばには、イエスの母と、母の姉妹と、クロパの妻マリヤと、マグダラのマリヤとが、たたずんでいた。26 イエスは、その母と愛弟子とがそばに立っているのをごらんになって、母にいわれた、「婦人よ、ごらんなさい。これはあなたの子です」。27 それからこの弟子に言われた、「ごらんなさい。これはあなたの母です」。そのとき以来、この弟子はイエスの母を自分の家に引きとった。

[マルコによる福音書15章21-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_21-32.pdf)

### 問い

1.  シモンというキレネ人はどのようなことをすることになりますか。（使徒13:1, ローマ16:13）

2.  十時架刑についてどのようなことが書かれていますか。

3.  詩篇22篇と比べてみましょう。

4.  人が信じるために必要なものは何でしょうか。

### 参照

### 記録

-   日時：2025年4月17日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:33-41 イエスの死

> 33 昼の十二時になると、全地は暗くなって、三時に及んだ。34 そして三時に、イエスは大声で、「エロイ、エロイ、ラマ、サバクタニ」と叫ばれた。それは「わが神、わが神、どうしてわたしをお見捨てになったのですか」という意味である。35 すると、そばに立っていたある人々が、これを聞いて言った、「そら、エリヤを呼んでいる」。36 ひとりの人が走って行き、海綿に酢いぶどう酒を含ませて葦の棒につけ、イエスに飲ませようとして言った、「待て、エリヤが彼をおろしに来るかどうか、見ていよう」。37 イエスは声高く叫んで、ついに息をひきとられた。38 そのとき、神殿の幕が上から下まで真二つに裂けた。39 イエスにむかって立っていた百卒長は、このようにして息をひきとられたのを見て言った、「まことに、この人は神の子であった」。40 また、遠くの方から見ている女たちもいた。その中には、マグダラのマリヤ、小ヤコブとヨセとの母マリヤ、またサロメがいた。41 彼らはイエスがガリラヤにおられたとき、そのあとに従って仕えた女たちであった。なおそのほか、イエスと共にエルサレムに上ってきた多くの女たちもいた。

### マタイ 27:45-56

> 45 さて、昼の十二時から地上の全面が暗くなって、三時に及んだ。46 そして三時ごろに、イエスは大声で叫んで、「エリ、エリ、レマ、サバクタニ」と言われた。それは「わが神、わが神、どうしてわたしをお見捨てになったのですか」という意味である。47 すると、そこに立っていたある人々が、これを聞いて言った、「あれはエリヤを呼んでいるのだ」。48 するとすぐ、彼らのうちのひとりが走り寄って、海綿を取り、それに酢いぶどう酒を含ませて葦の棒につけ、イエスに飲ませようとした。49 ほかの人々は言った、「待て、エリヤが彼を救いに来るかどうか、見ていよう」。50 イエスはもう一度大声で叫んで、ついに息をひきとられた。51 すると見よ、神殿の幕が上から下まで真二つに裂けた。また地震があり、岩が裂け、52 また墓が開け、眠っている多くの聖徒たちの死体が生き返った。53 そしてイエスの復活ののち、墓から出てきて、聖なる都にはいり、多くの人に現れた。54 百卒長、および彼と一緒にイエスの番をしていた人々は、地震や、いろいろのできごとを見て非常に恐れ、「まことに、この人は神の子であった」と言った。55 また、そこには遠くの方から見ている女たちも多くいた。彼らはイエスに仕えて、ガリラヤから従ってきた人たちであった。56 その中には、マグダラのマリヤ、ヤコブとヨセフとの母マリヤ、またゼベダイの子たちの母がいた。

### ルカ 23:44-49

> 44 時はもう昼の十二時ごろであったが、太陽は光を失い、全地は暗くなって、三時に及んだ。45 そして聖所の幕がまん中から裂けた。46 そのとき、イエスは声高く叫んで言われた、「父よ、わたしの霊をみ手にゆだねます」。こう言ってついに息を引きとられた。47 百卒長はこの有様を見て、神をあがめ、「ほんとうに、この人は正しい人であった」と言った。48 この光景を見に集まってきた群衆も、これらの出来事を見て、みな胸を打ちながら帰って行った。49 すべてイエスを知っていた者や、ガリラヤから従ってきた女たちも、遠い所に立って、これらのことを見ていた。

### ヨハネ 19:28-30

> 28 そののち、イエスは今や万事が終ったことを知って、「わたしは、かわく」と言われた。それは、聖書が全うされるためであった。29 そこに、酢いぶどう酒がいっぱい入れてある器がおいてあったので、人々は、このぶどう酒を含ませた海綿をヒソプの茎に結びつけて、イエスの口もとにさし出した。30 すると、イエスはそのぶどう酒を受けて、「すべてが終った」と言われ、首をたれて息をひきとられた。

[マルコによる福音書15章33-41節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_33-41.pdf)

### 問い

1.  イエスの死をどのように描いていますか。

2.  イエスの叫びからあなたは、どのようなことを感じますか。

3.  神殿の幕のことはなにを意味していると思いますか。

4.  その場にどのような人がいますか。百卒長は、なぜこのように告白したのでしょうか。

### 参照

### 記録

-   日時：2025年4月24日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 15:42-47 墓に葬られる

> 42 さて、すでに夕がたになったが、その日は準備の日、すなわち安息日の前日であったので、43 アリマタヤのヨセフが大胆にもピラトの所へ行き、イエスのからだの引取りかたを願った。彼は地位の高い議員であって、彼自身、神の国を待ち望んでいる人であった。44 ピラトは、イエスがもはや死んでしまったのかと不審に思い、百卒長を呼んで、もう死んだのかと尋ねた。45 そして、百卒長から確かめた上、死体をヨセフに渡した。46 そこで、ヨセフは亜麻布を買い求め、イエスをとりおろして、その亜麻布に包み、岩を掘って造った墓に納め、墓の入口に石をころがしておいた。47 マグダラのマリヤとヨセの母マリヤとは、イエスが納められた場所を見とどけた。

### マタイ 27:57-61

> 57 夕方になってから、アリマタヤの金持で、ヨセフという名の人がきた。彼もまたイエスの弟子であった。58 この人がピラトの所へ行って、イエスのからだの引取りかたを願った。そこで、ピラトはそれを渡すように命じた。59 ヨセフは死体を受け取って、きれいな亜麻布に包み、60 岩を掘って造った彼の新しい墓に納め、そして墓の入口に大きい石をころがしておいて、帰った。61 マグダラのマリヤとほかのマリヤとが、墓にむかってそこにすわっていた。

### ルカ 23:50-56

> 50 ここに、ヨセフという議員がいたが、善良で正しい人であった。51 この人はユダヤの町アリマタヤの出身で、神の国を待ち望んでいた。彼は議会の議決や行動には賛成していなかった。52 この人がピラトのところへ行って、イエスのからだの引取り方を願い出て、53 それを取りおろして亜麻布に包み、まだだれも葬ったことのない、岩を掘って造った墓に納めた。54 この日は準備の日であって、安息日が始まりかけていた。55 イエスと一緒にガリラヤからきた女たちは、あとについてきて、その墓を見、またイエスのからだが納められる様子を見とどけた。56 そして帰って、香料と香油とを用意した。それからおきてに従って安息日を休んだ。

### ヨハネ 19:38-42

> 38 そののち、ユダヤ人をはばかって、ひそかにイエスの弟子となったアリマタヤのヨセフという人が、イエスの死体を取りおろしたいと、ピラトに願い出た。ピラトはそれを許したので、彼はイエスの死体を取りおろしに行った。39 また、前に、夜、イエスのみもとに行ったニコデモも、没薬と沈香とをまぜたものを百斤ほど持ってきた。40 彼らは、イエスの死体を取りおろし、ユダヤ人の埋葬の習慣にしたがって、香料を入れて亜麻布で巻いた。41 イエスが十字架にかけられた所には、一つの園があり、そこにはまだだれも葬られたことのない新しい墓があった。42 その日はユダヤ人の準備の日であったので、その墓が近くにあったため、イエスをそこに納めた。

[マルコによる福音書15章42-47節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark15_42-47.pdf)

### 問い

1.  ヨセフについてどんなことがわかりますか。

2.  どのようなことをしますか。急いでしたのは何故でしょうか。

### 参照

-   マタイにはこのあと、番兵、墓を見張る記事（27:62-66）

### 記録

-   日時：2025年5月1日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 16:1-8 復活する

> 1 さて、安息日が終ったので、マグダラのマリヤとヤコブの母マリヤとサロメとが、行ってイエスに塗るために、香料を買い求めた。2 そして週の初めの日に、早朝、日の出のころ墓に行った。3 そして、彼らは「だれが、わたしたちのために、墓の入口から石をころがしてくれるのでしょうか」と話し合っていた。4 ところが、目をあげて見ると、石はすでにころがしてあった。この石は非常に大きかった。5 墓の中にはいると、右手に真白な長い衣を着た若者がすわっているのを見て、非常に驚いた。6 するとこの若者は言った、「驚くことはない。あなたがたは十字架につけられたナザレ人イエスを捜しているのであろうが、イエスはよみがえって、ここにはおられない。ごらんなさい、ここがお納めした場所である。7 今から弟子たちとペテロとの所へ行って、こう伝えなさい。イエスはあなたがたより先にガリラヤへ行かれる。かねて、あなたがたに言われたとおり、そこでお会いできるであろう、と」。8 女たちはおののき恐れながら、墓から出て逃げ去った。そして、人には何も言わなかった。恐ろしかったからである。

### マタイ 28:1-8

> 1 さて、安息日が終って、週の初めの日の明け方に、マグダラのマリヤとほかのマリヤとが、墓を見にきた。2 すると、大きな地震が起った。それは主の使が天から下って、そこにきて石をわきへころがし、その上にすわったからである。3 その姿はいなずまのように輝き、その衣は雪のように真白であった。4 見張りをしていた人たちは、恐ろしさの余り震えあがって、死人のようになった。5 この御使は女たちにむかって言った、「恐れることはない。あなたがたが十字架におかかりになったイエスを捜していることは、わたしにわかっているが、6 もうここにはおられない。かねて言われたとおりに、よみがえられたのである。さあ、イエスが納められていた場所をごらんなさい。7 そして、急いで行って、弟子たちにこう伝えなさい、『イエスは死人の中からよみがえられた。見よ、あなたがたより先にガリラヤへ行かれる。そこでお会いできるであろう』。あなたがたに、これだけ言っておく」。8 そこで女たちは恐れながらも大喜びで、急いで墓を立ち去り、弟子たちに知らせるために走って行った。

### ルカ 24:1-12

> 1 週の初めの日、夜明け前に、女たちは用意しておいた香料を携えて、墓に行った。2 ところが、石が墓からころがしてあるので、3 中にはいってみると、主イエスのからだが見当らなかった。4 そのため途方にくれていると、見よ、輝いた衣を着たふたりの者が、彼らに現れた。5 女たちは驚き恐れて、顔を地に伏せていると、このふたりの者が言った、「あなたがたは、なぜ生きた方を死人の中にたずねているのか。6 そのかたは、ここにはおられない。よみがえられたのだ。まだガリラヤにおられたとき、あなたがたにお話しになったことを思い出しなさい。7 すなわち、人の子は必ず罪人らの手に渡され、十字架につけられ、そして三日目によみがえる、と仰せられたではないか」。8 そこで女たちはその言葉を思い出し、9 墓から帰って、これらいっさいのことを、十一弟子や、その他みんなの人に報告した。10 この女たちというのは、マグダラのマリヤ、ヨハンナ、およびヤコブの母マリヤであった。彼女たちと一緒にいたほかの女たちも、このことを使徒たちに話した。11 ところが、使徒たちには、それが愚かな話のように思われて、それを信じなかった。12 〔ペテロは立って墓へ走って行き、かがんで中を見ると、亜麻布だけがそこにあったので、事の次第を不思議に思いながら帰って行った。〕

### ヨハネ 20:1-10

> 1 さて、一週の初めの日に、朝早くまだ暗いうちに、マグダラのマリヤが墓に行くと、墓から石がとりのけてあるのを見た。2 そこで走って、シモン・ペテロとイエスが愛しておられた、もうひとりの弟子のところへ行って、彼らに言った、「だれかが、主を墓から取り去りました。どこへ置いたのか、わかりません」。3 そこでペテロともうひとりの弟子は出かけて、墓へむかって行った。4 ふたりは一緒に走り出したが、そのもうひとりの弟子の方が、ペテロよりも早く走って先に墓に着き、5 そして身をかがめてみると、亜麻布がそこに置いてあるのを見たが、中へははいらなかった。6 シモン・ペテロも続いてきて、墓の中にはいった。彼は亜麻布がそこに置いてあるのを見たが、7 イエスの頭に巻いてあった布は亜麻布のそばにはなくて、はなれた別の場所にくるめてあった。8 すると、先に墓に着いたもうひとりの弟子もはいってきて、これを見て信じた。9 しかし、彼らは死人のうちからイエスがよみがえるべきことをしるした聖句を、まだ悟っていなかった。10 それから、ふたりの弟子たちは自分の家に帰って行った。

[マルコによる福音書16章1-8節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark16_1-8.pdf)

### 問い

1.  婦人たちが、墓に近付いたときのことを考えてみましょう。どんなことを心配していますか。

2.  墓の中には何があり、婦人たちはなにを告げられますか。

3.  婦人たちは、どうしますか。

### 参照

### 記録

-   日時：2025年5月8日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 16:9-11 （結び一）マグダラのマリアに現れる

> 9 〔週の初めの日の朝早く、イエスはよみがえって、まずマグダラのマリヤに御自身をあらわされた。イエスは以前に、この女から七つの悪霊を追い出されたことがある。10 マリヤは、イエスと一緒にいた人々が泣き悲しんでいる所に行って、それを知らせた。11 彼らは、イエスが生きておられる事と、彼女に御自身をあらわされた事とを聞いたが、信じなかった。

### マタイ 28:9-10

> 9 すると、イエスは彼らに出会って、「平安あれ」と言われたので、彼らは近寄りイエスのみ足をいだいて拝した。10 そのとき、イエスは彼らに言われた、「恐れることはない。行って兄弟たちに、ガリラヤに行け、そこでわたしに会えるであろう、と告げなさい」。

### ヨハネ 20:11-18

> 11 しかし、マリヤは墓の外に立って泣いていた。そして泣きながら、身をかがめて墓の中をのぞくと、12 白い衣を着たふたりの御使が、イエスの死体のおかれていた場所に、ひとりは頭の方に、ひとりは足の方に、すわっているのを見た。13 すると、彼らはマリヤに、「女よ、なぜ泣いているのか」と言った。マリヤは彼らに言った、「だれかが、わたしの主を取り去りました。そして、どこに置いたのか、わからないのです」。14 そう言って、うしろをふり向くと、そこにイエスが立っておられるのを見た。しかし、それがイエスであることに気がつかなかった。15 イエスは女に言われた、「女よ、なぜ泣いているのか。だれを捜しているのか」。マリヤは、その人が園の番人だと思って言った、「もしあなたが、あのかたを移したのでしたら、どこへ置いたのか、どうぞ、おっしゃって下さい。わたしがそのかたを引き取ります」。16 イエスは彼女に「マリヤよ」と言われた。マリヤはふり返って、イエスにむかってヘブル語で「ラボニ」と言った。それは、先生という意味である。17 イエスは彼女に言われた、「わたしにさわってはいけない。わたしは、まだ父のみもとに上っていないのだから。ただ、わたしの兄弟たちの所に行って、『わたしは、わたしの父またあなたがたの父であって、わたしの神またあなたがたの神であられるかたのみもとへ上って行く』と、彼らに伝えなさい」。18 マグダラのマリヤは弟子たちのところに行って、自分が主に会ったこと、またイエスがこれこれのことを自分に仰せになったことを、報告した。

### 問い

### 参照

-   マタイにはこのあと、番兵、報告する記事（28:11-15）

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 16:12-13 二人の弟子に現れる

> 12 この後、そのうちのふたりが、いなかの方へ歩いていると、イエスはちがった姿で御自身をあらわされた。13 このふたりも、ほかの人々の所に行って話したが、彼らはその話を信じなかった。

### ルカ 24:13-35

> 13 この日、ふたりの弟子が、エルサレムから七マイルばかり離れたエマオという村へ行きながら、14 このいっさいの出来事について互に語り合っていた。15 語り合い論じ合っていると、イエスご自身が近づいてきて、彼らと一緒に歩いて行かれた。16 しかし、彼らの目がさえぎられて、イエスを認めることができなかった。17 イエスは彼らに言われた、「歩きながら互に語り合っているその話は、なんのことなのか」。彼らは悲しそうな顔をして立ちどまった。18 そのひとりのクレオパという者が、答えて言った、「あなたはエルサレムに泊まっていながら、あなただけが、この都でこのごろ起ったことをご存じないのですか」。19 「それは、どんなことか」と言われると、彼らは言った、「ナザレのイエスのことです。あのかたは、神とすべての民衆との前で、わざにも言葉にも力ある預言者でしたが、20 祭司長たちや役人たちが、死刑に処するために引き渡し、十字架につけたのです。21 わたしたちは、イスラエルを救うのはこの人であろうと、望みをかけていました。しかもその上に、この事が起ってから、きょうが三日目なのです。22 ところが、わたしたちの仲間である数人の女が、わたしたちを驚かせました。というのは、彼らが朝早く墓に行きますと、23 イエスのからだが見当らないので、帰ってきましたが、そのとき御使が現れて、『イエスは生きておられる』と告げたと申すのです。24 それで、わたしたちの仲間が数人、墓に行って見ますと、果して女たちが言ったとおりで、イエスは見当りませんでした」。25 そこでイエスが言われた、「ああ、愚かで心のにぶいため、預言者たちが説いたすべての事を信じられない者たちよ。26 キリストは必ず、これらの苦難を受けて、その栄光に入るはずではなかったのか」。27 こう言って、モーセやすべての預言者からはじめて、聖書全体にわたり、ご自身についてしるしてある事どもを、説きあかされた。28 それから、彼らは行こうとしていた村に近づいたが、イエスがなお先へ進み行かれる様子であった。29 そこで、しいて引き止めて言った、「わたしたちと一緒にお泊まり下さい。もう夕暮になっており、日もはや傾いています」。イエスは、彼らと共に泊まるために、家にはいられた。30 一緒に食卓につかれたとき、パンを取り、祝福してさき、彼らに渡しておられるうちに、31 彼らの目が開けて、それがイエスであることがわかった。すると、み姿が見えなくなった。32 彼らは互に言った、「道々お話しになったとき、また聖書を説き明してくださったとき、お互の心が内に燃えたではないか」。33 そして、すぐに立ってエルサレムに帰って見ると、十一弟子とその仲間が集まっていて、34 「主は、ほんとうによみがえって、シモンに現れなさった」と言っていた。35 そこでふたりの者は、途中であったことや、パンをおさきになる様子でイエスだとわかったことなどを話した。

### 問い

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 16:14-18 弟子たちを派遣する

> 14 その後、イエスは十一弟子が食卓についているところに現れ、彼らの不信仰と、心のかたくななことをお責めになった。彼らは、よみがえられたイエスを見た人々の言うことを、信じなかったからである。15 そして彼らに言われた、「全世界に出て行って、すべての造られたものに福音を宣べ伝えよ。16 信じてバプテスマを受ける者は救われる。しかし、不信仰の者は罪に定められる。17 信じる者には、このようなしるしが伴う。すなわち、彼らはわたしの名で悪霊を追い出し、新しい言葉を語り、18 へびをつかむであろう。また、毒を飲んでも、決して害を受けない。病人に手をおけば、いやされる」。

### マタイ 28:16-20

> 16 さて、十一人の弟子たちはガリラヤに行って、イエスが彼らに行くように命じられた山に登った。17 そして、イエスに会って拝した。しかし、疑う者もいた。18 イエスは彼らに近づいてきて言われた、「わたしは、天においても地においても、いっさいの権威を授けられた。19 それゆえに、あなたがたは行って、すべての国民を弟子として、父と子と聖霊との名によって、彼らにバプテスマを施し、20 あなたがたに命じておいたいっさいのことを守るように教えよ。見よ、わたしは世の終りまで、いつもあなたがたと共にいるのである」。

### ルカ 24:36-49

> 36 こう話していると、イエスが彼らの中にお立ちになった。〔そして「やすかれ」と言われた。〕37 彼らは恐れ驚いて、霊を見ているのだと思った。38 そこでイエスが言われた、「なぜおじ惑っているのか。どうして心に疑いを起すのか。39 わたしの手や足を見なさい。まさしくわたしなのだ。さわって見なさい。霊には肉や骨はないが、あなたがたが見るとおり、わたしにはあるのだ」。40 〔こう言って、手と足とをお見せになった。〕41 彼らは喜びのあまり、まだ信じられないで不思議に思っていると、イエスが「ここに何か食物があるか」と言われた。42 彼らが焼いた魚の一きれをさしあげると、43 イエスはそれを取って、みんなの前で食べられた。44 それから彼らに対して言われた、「わたしが以前あなたがたと一緒にいた時分に話して聞かせた言葉は、こうであった。すなわち、モーセの律法と預言書と詩篇とに、わたしについて書いてあることは、必ずことごとく成就する」。45 そこでイエスは、聖書を悟らせるために彼らの心を開いて 46 言われた、「こう、しるしてある。キリストは苦しみを受けて、三日目に死人の中からよみがえる。47 そして、その名によって罪のゆるしを得させる悔改めが、エルサレムからはじまって、もろもろの国民に宣べ伝えられる。48 あなたがたは、これらの事の証人である。49 見よ、わたしの父が約束されたものを、あなたがたに贈る。だから、上から力を授けられるまでは、あなたがたは都にとどまっていなさい」。

### ヨハネ 20:19-23

> 19 その日、すなわち、一週の初めの日の夕方、弟子たちはユダヤ人をおそれて、自分たちのおる所の戸をみなしめていると、イエスがはいってきて、彼らの中に立ち、「安かれ」と言われた。20 そう言って、手とわきとを、彼らにお見せになった。弟子たちは主を見て喜んだ。21 イエスはまた彼らに言われた、「安かれ。父がわたしをおつかわしになったように、わたしもまたあなたがたをつかわす」。22 そう言って、彼らに息を吹きかけて仰せになった、「聖霊を受けよ。23 あなたがたがゆるす罪は、だれの罪でもゆるされ、あなたがたがゆるさずにおく罪は、そのまま残るであろう」。

### 問い

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 16:19-20 天に上げられる

> 19 主イエスは彼らに語り終ってから、天にあげられ、神の右にすわられた。20 弟子たちは出て行って、至る所で福音を宣べ伝えた。主も彼らと共に働き、御言に伴うしるしをもって、その確かなことをお示しになった。〕

### ルカ 24:50-53

> 50 それから、イエスは彼らをベタニヤの近くまで連れて行き、手をあげて彼らを祝福された。51 祝福しておられるうちに、彼らを離れて、〔天にあげられた。〕52 彼らは〔イエスを拝し、〕非常な喜びをもってエルサレムに帰り、53 絶えず宮にいて、神をほめたたえていた。

### 問い

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ
