## 11:1-11 エルサレムに迎えられる

> 1 さて、彼らがエルサレムに近づき、オリブの山に沿ったベテパゲ、ベタニヤの附近にきた時、イエスはふたりの弟子をつかわして言われた、2 「むこうの村へ行きなさい。そこにはいるとすぐ、まだだれも乗ったことのないろばの子が、つないであるのを見るであろう。それを解いて引いてきなさい。3 もし、だれかがあなたがたに、なぜそんな事をするのかと言ったなら、主がお入り用なのです。またすぐ、ここへ返してくださいますと、言いなさい」。4 そこで、彼らは出かけて行き、そして表通りの戸口に、ろばの子がつないであるのを見たので、それを解いた。5 すると、そこに立っていた人々が言った、「そのろばの子を解いて、どうするのか」。6 弟子たちは、イエスが言われたとおり彼らに話したので、ゆるしてくれた。7 そこで、弟子たちは、そのろばの子をイエスのところに引いてきて、自分たちの上着をそれに投げかけると、イエスはその上にお乗りになった。8 すると多くの人々は自分たちの上着を道に敷き、また他の人々は葉のついた枝を野原から切ってきて敷いた。9 そして、前に行く者も、あとに従う者も共に叫びつづけた、／「ホサナ、／主の御名によってきたる者に、祝福あれ。10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。

### マタイ 21:1-11

> 1 さて、彼らがエルサレムに近づき、オリブ山沿いのベテパゲに着いたとき、イエスはふたりの弟子をつかわして言われた、2 「向こうの村へ行きなさい。するとすぐ、ろばがつながれていて、子ろばがそばにいるのを見るであろう。それを解いてわたしのところに引いてきなさい。3 もしだれかが、あなたがたに何か言ったなら、主がお入り用なのです、と言いなさい。そう言えば、すぐ渡してくれるであろう」。4 こうしたのは、預言者によって言われたことが、成就するためである。5 すなわち、／「シオンの娘に告げよ、／見よ、あなたの王がおいでになる、／柔和なおかたで、ろばに乗って、／くびきを負うろばの子に乗って」。6 弟子たちは出て行って、イエスがお命じになったとおりにし、7 ろばと子ろばとを引いてきた。そしてその上に自分たちの上着をかけると、イエスはそれにお乗りになった。8 群衆のうち多くの者は自分たちの上着を道に敷き、また、ほかの者たちは木の枝を切ってきて道に敷いた。9 そして群衆は、前に行く者も、あとに従う者も、共に叫びつづけた、／「ダビデの子に、ホサナ。主の御名によってきたる者に、祝福あれ。いと高き所に、ホサナ」。10 イエスがエルサレムにはいって行かれたとき、町中がこぞって騒ぎ立ち、「これは、いったい、どなただろう」と言った。11 そこで群衆は、「この人はガリラヤのナザレから出た預言者イエスである」と言った。

### ルカ 19:28-40

> 28 イエスはこれらのことを言ったのち、先頭に立ち、エルサレムへ上って行かれた。29 そしてオリブという山に沿ったベテパゲとベタニヤに近づかれたとき、ふたりの弟子をつかわして言われた、30 「向こうの村へ行きなさい。そこにはいったら、まだだれも乗ったことのないろばの子がつないであるのを見るであろう。それを解いて、引いてきなさい。31 もしだれかが『なぜ解くのか』と問うたら、『主がお入り用なのです』と、そう言いなさい」。32 そこで、つかわされた者たちが行って見ると、果して、言われたとおりであった。33 彼らが、そのろばの子を解いていると、その持ち主たちが、「なぜろばの子を解くのか」と言ったので、34 「主がお入り用なのです」と答えた。35 そしてそれをイエスのところに引いてきて、その子ろばの上に自分たちの上着をかけてイエスをお乗せした。36 そして進んで行かれると、人々は自分たちの上着を道に敷いた。37 いよいよオリブ山の下り道あたりに近づかれると、大ぜいの弟子たちはみな喜んで、彼らが見たすべての力あるみわざについて、声高らかに神をさんびして言いはじめた、38 「主の御名によってきたる王に、／祝福あれ。天には平和、／いと高きところには栄光あれ」。39 ところが、群衆の中にいたあるパリサイ人たちがイエスに言った、「先生、あなたの弟子たちをおしかり下さい」。40 答えて言われた、「あなたがたに言うが、もしこの人たちが黙れば、石が叫ぶであろう」。

### ヨハネ 12:12-19

> 12 その翌日、祭にきていた大ぜいの群衆は、イエスがエルサレムにこられると聞いて、13 しゅろの枝を手にとり、迎えに出て行った。そして叫んだ、／「ホサナ、／主の御名によってきたる者に祝福あれ、／イスラエルの王に」。14 イエスは、ろばの子を見つけて、その上に乗られた。それは 15 「シオンの娘よ、恐れるな。見よ、あなたの王が／ろばの子に乗っておいでになる」／と書いてあるとおりであった。16 弟子たちは初めにはこのことを悟らなかったが、イエスが栄光を受けられた時に、このことがイエスについて書かれてあり、またそのとおりに、人々がイエスに対してしたのだということを、思い起した。17 また、イエスがラザロを墓から呼び出して、死人の中からよみがえらせたとき、イエスと一緒にいた群衆が、そのあかしをした。18 群衆がイエスを迎えに出たのは、イエスがこのようなしるしを行われたことを、聞いていたからである。19 そこで、パリサイ人たちは互に言った、「何をしてもむだだった。世をあげて彼のあとを追って行ったではないか」。

[マルコによる福音書11章1-11節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_1-11.pdf)

### 問い

1.  イエスたちは、どこにいますか。背景も復習しましょう。（1）

2.  イエスは弟子の二人にどんな指示をしていますか。（2,3）

3.  そして、どうなりますか。（3-6）

4.  イエスは、どうしますか。そのようすは、どのように描かれていますか。（7-10）

5.  これは、どのようなことを伝えているのでしょうか。他の福音書から人々の反応もみてみましょう。

6.  この日の、イエスの様子は、どのように描かれていますか。（11）

### 参照

-   受難週のエルサレムの地図 \[[The Passion Week in Jerusalem](https://www.seektheoldpaths.com/Maps/113.jpg)\]

-   ベテパゲ（Βηθφαγή： "house of unripe figs" 熟していないいちじくの家 または、単に、fig house いちじくの家）

    -   エリコからエルサレムに向かう途中にあるベタニヤに近い小村。（the name of a hamlet between Jericho and Jerusalem, close to Bethany）

    -   聖書では、マルコ11:11、マタイ21:1、ルカ19:29 すなわち今回の箇所のみ。

    -   安息日に旅することが可能。1.6km 以内。巡礼者の宿泊所

-   ベタニヤ（Βηθανία："house of dates" or, "house of misery"）ナツメヤシの家　עֲנִיָּה בֵּית

    -   a village at the Mount of Olives, about two miles (3 km) from Jerusalem, on or near the normal road to Jericho

-   ろば：山を旅するには馬よりも強く、女子供でも乗りやすい背丈であることから、ろばが愛用された。

    -   民数記22章 21節 明くる朝起きてバラムは、ろばにくらをおき、モアブのつかさたちと一緒に行った。

    -   士師記5章 9-10節 わたしの心は民のうちの喜び勇んで／進み出たイスラエルのつかさたちと共にある。主をさんびせよ。茶色のろばに乗るもの、／毛氈の上にすわるもの、／および道を歩むものよ、共に歌え。

    -   サムエル記上 9章 3節 サウルの父キシの数頭のろばがいなくなった。そこでキシは、その子サウルに言った、「しもべをひとり連れて、立って行き、ろばを捜してきなさい」。

    -   サムエル記下 16章 1-2節 ダビデが山の頂を過ぎて、すこし行った時、メピボセテのしもべヂバは、くらを置いた二頭のろばを引き、その上にパン二百個、干ぶどう百ふさ、夏のくだもの一百、ぶどう酒一袋を載せてきてダビデを迎えた。王はヂバに言った、「あなたはどうしてこれらのものを持ってきたのですか」。ヂバは答えた、「ろばは王の家族が乗るため、パンと夏のくだものは若者たちが食べるため、ぶどう酒は荒野で弱った者が飲むためです」。

    -   参照：列王紀上 10章 28-29節 ソロモンが馬を輸入したのはエジプトとクエからであった。すなわち王の貿易商はクエから代価を払って受け取ってきた。エジプトから輸入される戦車一両は銀六百シケル、馬は百五十シケルであった。このようにして、これらのものが王の貿易商によって、ヘテびとのすべての王たちおよびスリヤの王たちに輸出された。

-   ゼカリヤ9:8-14

    -   その時わたしは、わが家のために営を張って、見張りをし、行き来する者のないようにする。しえたげる者は、かさねて通ることがない。わたしが今、自分の目で見ているからである。9 シオンの娘よ、大いに喜べ、エルサレムの娘よ、呼ばわれ。見よ、あなたの王はあなたの所に来る。彼は義なる者であって勝利を得、柔和であって、ろばに乗る。すなわち、ろばの子である子馬に乗る。10 わたしはエフライムから戦車を断ち、エルサレムから軍馬を断つ。また、いくさ弓も断たれる。彼は国々の民に平和を告げ、その政治は海から海に及び、大川から地の果にまで及ぶ。11 あなたについてはまた、あなたとの契約の血のゆえに、わたしはかの水のない穴から、あなたの捕われ人を解き放す。12 望みをいだく捕われ人よ、あなたの城に帰れ。わたしはきょうもなお告げて言う、必ず倍して、あなたをもとに返すことを。13 わたしはユダを張って、わが弓となし、エフライムをその矢とした。シオンよ、わたしはあなたの子らを呼び起して、ギリシヤの人々を攻めさせ、あなたを勇士のつるぎのようにさせる。14 その時、主は彼らの上に現れて、その矢をいなずまのように射られる。主なる神はラッパを吹きならし、南のつむじ風に乗って出てこられる。

        -   背景を考えると難しい。捕囚のあと一部が帰還したエルサレムでの預言である。ここでは、周囲の海の民（ペリシテなど）からの圧迫に苦しむ必要はないとして、9節、10節が語られているように見える。エルサレムに、諸国民に平和を告げる王がくることを預言している。

        -   おそらく「彼は義なる者であって勝利を得、柔和であって、ろばに乗る。すなわち、ろばの子である子馬に乗る。」が、イエスのイメージと、エルサレム入城に適合していることを主張した人たちがおり、さらに、「わたしはエフライムから戦車を断ち、エルサレムから軍馬を断つ。また、いくさ弓も断たれる。彼は国々の民に平和を告げ、その政治は海から海に及び、大川から地の果にまで及ぶ。」に期待を抱いたのかもしれない。

-   マカバイ記一 13章 51節 第百七十一年の第二の月の二十三日、ユダヤの人々は賛美のうちにしゅろの枝をかざし、竪琴、シンバル、十二絃を鳴らし、賛歌と歌を歌いながら要塞に入った。イスラエルから大敵が根絶されたからである。

-   列王記下9章13節 すると彼らは急いで、おのおの衣服をとり、それを階段の上のエヒウの下に敷き、ラッパを吹いて「エヒウは王である」と言った。

-   ルカにはこのあと挿入（19:41-44）

    -   41 いよいよ都の近くにきて、それが見えたとき、そのために泣いて言われた、42 「もしおまえも、この日に、平和をもたらす道を知ってさえいたら.........しかし、それは今おまえの目に隠されている。43 いつかは、敵が周囲に塁を築き、おまえを取りかこんで、四方から押し迫り、44 おまえとその内にいる子らとを地に打ち倒し、城内の一つの石も他の石の上に残して置かない日が来るであろう。それは、おまえが神のおとずれの時を知らないでいたからである」。

-   イエスのエルサレム訪問

    -   ルカ2:22 それから、モーセの律法による彼らのきよめの期間が過ぎたとき、両親は幼な子を連れてエルサレムへ上った。

    -   ルカ2:41 さて、イエスの両親は、過越の祭には毎年エルサレムへ上っていた。

    -   ヨハネ2:13 さて、ユダヤ人の過越の祭が近づいたので、イエスはエルサレムに上られた。

    -   ヨハネ5:1,2 こののち、ユダヤ人の祭があったので、イエスはエルサレムに上られた。2 エルサレムにある羊の門のそばに、ヘブル語でベテスダと呼ばれる池があった。そこには五つの廊があった。

    -   ヨハネ7:10 しかし、兄弟たちが（仮庵の）祭に行ったあとで、イエスも人目にたたぬように、ひそかに行かれた。

    -   \[参照\] マタイ23:37 ああ、エルサレム、エルサレム、預言者たちを殺し、おまえにつかわされた人たちを石で打ち殺す者よ。ちょうど、めんどりが翼の下にそのひなを集めるように、わたしはおまえの子らを幾たび集めようとしたことであろう。それだのに、おまえたちは応じようとしなかった。

    -   \[参考\] エルサレムの周辺30km 以内に住む成人男性は、この祭りに参加する定めになっていたと言われている。

-   ヨハネには、エルサレムでの活動がたびたび書かれている。

    -   2:13-25 （過越祭の折）神殿から商人を追い出す。（共観福音書では、これを今回の記事のあとに置いている）

    -   3:1-21 （または15節まで）のニコデモとの会話も、エルサレムである可能性が高い。（イエスの葬りのときに現れ（19:39）、サンヘドリンの議員であるかは不明だが、議員はファリサイ派の人の中に登場する。（7:50））

    -   3:22 以降も、4:42 まで、ユダヤ、サマリアに弟子たちと、滞在している。（4:43-54 は、ガリラヤに滞在）

    -   5:1-47 ユダヤ人の祭りにエルサレムに登り、ベテスダの池で病人を癒やす。（6:1-71 五千人の給食はガリラヤ。）

    -   7:1-10:42-12:11 （エルサレム入城の直前まで） 明確にはわからないが、エルサレムまたは周辺のユダヤに滞在していると思われる。

    -   ガリラヤでの活動の記事は、非常に限定的で、エルサレムでの活動ばかり書かれている。ガリラヤでは、カナでの活動が、二回と、五千人の給食のみ。共観福音書にかかれているから書かないとも考えられないこともないが、記述が詳細であることから、目撃者証言と言えるものも多い。カナ、五千人給食の地、エルサレムをつなぐ線上に、証言者がいるように見える。また、マリアとの関係も、最初のカナでの婚礼、そして、最後にイエスの愛しておられる弟子に、マリアを委ねるところからも、特別なものであったように見える。五千人給食に関しては、ピリポ、アンデレが登場し、バプテスマのヨハネのところでの、仲間だった可能性もあり、そこから、得た情報なのかもしれない。

### 記録

-   日時：2024年9月12日午後7時半〜9時半

-   出席（対面）5名、参加（遠隔）2名

### 問いについて

1.  イエスたちは、どこにいますか。背景も復習しましょう。（1）

    -   1 さて、彼らがエルサレムに近づき、オリブの山に沿ったベテパゲ、ベタニヤの附近にきた時、イエスはふたりの弟子をつかわして言われた、

    -   \[DQ\] どこを出発して、どこへ向かい、今いる場所はどこでしょうか。

        -   \[A\] 彼らがエルサレムに近づき、オリブの山に沿ったベテパゲ、ベタニヤの附近にきた時

            -   マタイでは、ベテパゲとしているが、ルカは、マルコを引き継いでいる。おそらく、マタイは、それがベテパゲであることを知っていたのだろう。

            -   では、なぜ、ベタニヤも入っているかが気になる。ヨハネによると、この前には、ラザロの復活の記事、マルタ、マリア、ラザロの家での宴会の記事、マリアが油を注いだ記事、そして、そのことが人々に衝撃を与えたことが書かれている。

            -   マルコはなぜ、そのような記事をとばしているのだろうか。

    -   \[DQ\] イエスは、弟子たちと共にエルサレムに何度も来ていたのだろうか。それとも、これが初めてだろうか。

        -   ルカには幼い頃に、両親と、エルサレムに来た記事がある。（2:22, 41）しかし、共観福音書には、書かれていないので、このときが最初であるような印象を受ける。一般的には、エルサレムから 30km 程度の範囲内の住人（成人男性）は、過越祭にエルサレムに上ることが義務と考えられており、熱心なひとは、遠くにいても、祭りのとき、特に、過越祭には、エルサレムに上っていた。このことが、ルカ2:41 でも表現されている。「イエスの両親は、過越の祭には毎年エルサレムへ上っていた。」

        -   ヨハネは、「（イエスの）愛する」弟子が著者とされているが、エルサレムでの活動が中心に書かれている。自分が、その場にいた、目撃者であれば、目撃したこと以外については、確実なことしか、書かないだろう。むろん、実際に起こったときから、かなりの年月がたってからだと、混乱もあるかもしれないが。

2.  イエスは弟子の二人にどんな指示をしていますか。（2,3）

    -   2 「むこうの村へ行きなさい。そこにはいるとすぐ、まだだれも乗ったことのないろばの子が、つないであるのを見るであろう。それを解いて引いてきなさい。3 もし、だれかがあなたがたに、なぜそんな事をするのかと言ったなら、主がお入り用なのです。またすぐ、ここへ返してくださいますと、言いなさい」。

    -   \[DQ\] 「むこうの村」とは、どこでしょうか。

        -   \[A\] おそらく、ベテパゲ。マタイでは、ベテパゲだけがあげられている。

        -   \[Q\] ではなぜ、ベタニヤが入っているのか。

    -   \[DQ\] イエスはどんな指示をしていますか。

        -   配慮もあるように見える。「またすぐ、ここへ返してくださいます」（確認は次の問でもよい）

    -   \[DQ\] ろばは、どんなろばですか。なぜ、そのようなろばを選ばれたのでしょう。

        -   \[A\] まだだれも乗ったことのないろばの子（2）

            -   聖なる目的のためには、未使用のものを。

                -   民数記 19章 02節 「主の命じられた律法の定めは次のとおりである。すなわち『イスラエルの人々に告げて、完全で、傷がなく、まだくびきを負ったことのない赤い雌牛を、あなたのもとに引いてこさせ、

                -   申命記 21章 03節 そしてその殺された者のある所に最も近い町の長老たちは、まだ使わない、まだくびきを負わせて引いたことのない若い雌牛をとり、

            -   マタイでは、ろばところばとなっている。(マタイ21:2,5,7)

        -   マタイ21:4,5 4 こうしたのは、預言者によって言われたことが、成就するためである。5 すなわち、／「シオンの娘に告げよ、／見よ、あなたの王がおいでになる、／柔和なおかたで、ろばに乗って、／くびきを負うろばの子に乗って」。

        -   ヨハネ12:15,16 「シオンの娘よ、恐れるな。見よ、あなたの王が／ろばの子に乗っておいでになる」／と書いてあるとおりであった。16 弟子たちは初めにはこのことを悟らなかったが、イエスが栄光を受けられた時に、このことがイエスについて書かれてあり、またそのとおりに、人々がイエスに対してしたのだということを、思い起した。

        -   ゼカリヤ9:8-14 参照

3.  そして、どうなりますか。（3-6）

    -   3 もし、だれかがあなたがたに、なぜそんな事をするのかと言ったなら、主がお入り用なのです。またすぐ、ここへ返してくださいますと、言いなさい」。4 そこで、彼らは出かけて行き、そして表通りの戸口に、ろばの子がつないであるのを見たので、それを解いた。5 すると、そこに立っていた人々が言った、「そのろばの子を解いて、どうするのか」。6 弟子たちは、イエスが言われたとおり彼らに話したので、ゆるしてくれた。

    -   \[DQ\] イエスとこの村の人との関係はどのようなものだったのでしょうか。

        -   \[A\] ベテパゲは、ここにしか登場しないので、不明だが、ベタニヤに近いことからも、このあたりには、イエスは何回も来ていたと思われる。ヨハネによるとこの直前にも、ベタニヤに滞在していた。

    -   \[DQ\] イエスと村の人の間には事前に打ち合わせがあったのでしょうか。

        -   \[A\] その証拠はないが、ベタニヤに近いということは、ラザロの事件も知っていたろうから、事前の打ち合わせがなくても、これらのことばで通じたかもしれない。同時に、ある信頼関係のあるひとがいたことも十分考えられる。そして、これらのことばで、その意味も通じた可能性が高い。

    -   \[DQ\] 「イエスが言われた通り」とは、どんなことを指していますか。

        -   \[A\] 「主がお入り用なのです。またすぐ、ここへ返してくださいます」

    -   ルカでは『主がお入り用なのです』の部分が強調されている。（ルカ 19:31,34）

4.  イエスは、どうしますか。そのようすは、どのように描かれていますか。（7-10）

    -   7 そこで、弟子たちは、そのろばの子をイエスのところに引いてきて、自分たちの上着をそれに投げかけると、イエスはその上にお乗りになった。8 すると多くの人々は自分たちの上着を道に敷き、また他の人々は葉のついた枝を野原から切ってきて敷いた。9 そして、前に行く者も、あとに従う者も共に叫びつづけた、／「ホサナ、／主の御名によってきたる者に、祝福あれ。10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。

    -   \[DQ\] どのような人々がイエスの入城に立ち会いますか。

        -   弟子たち、多くの人々、他の人々、前に行く者、あとに従う者

        -   この人たちは、どのような人たちでしょうか。

            -   弟子とそのお付き？ ガリラヤから来た人々？ エルサレムの人々？

    -   \[DQ\] イエスはどのようにしてエルサレムに入城しますか。

        -   \[Q\] エルサレム凱旋のようなイメージがあるが、本当に、そのように、マルコは描いたいるのだろうか。ろばの子というのは、興味深い。

5.  これは、どのようなことを伝えているのでしょうか。他の福音書から人々の反応もみてみましょう。

    -   マルコでは「ホサナ、／主の御名によってきたる者に、祝福あれ。10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。だが、他の福音書では、意味が付け加えられている。

    -   \[DQ\] エルサレムの人たちに対して、群衆はどのようにイエスを紹介しますか。

        -   「ホサナ、／主の御名によってきたる者に、祝福あれ。10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。

        -   「今きたる、われらの父ダビデの国に」は、旧約聖書に対応箇所がない。ダビデの子とすることを、避けていることは確かなように思われる。

    -   \[参照\] 詩篇118:25,26 主よ、どうぞわれらをお救いください。主よ、どうぞわれらを栄えさせてください。26 主のみ名によってはいる者はさいわいである。われらは主の家からあなたをたたえます。

    -   他の福音書からの考察

        -   \[DQ\] マタイは、「王」についてイエスについて、どのような事を伝えていますか。

            -   21:4,5 4 こうしたのは、預言者によって言われたことが、成就するためである。5 すなわち、／「シオンの娘に告げよ、／見よ、あなたの王がおいでになる、／柔和なおかたで、ろばに乗って、／くびきを負うろばの子に乗って」。

                -   ゼカリヤ9:9 シオンの娘よ、大いに喜べ、エルサレムの娘よ、呼ばわれ。見よ、あなたの王はあなたの所に来る。彼は義なる者であって勝利を得、柔和であって、ろばに乗る。すなわち、ろばの子である子馬に乗る。

            -   21:9 そして群衆は、前に行く者も、あとに従う者も、共に叫びつづけた、／「ダビデの子に、ホサナ。主の御名によってきたる者に、祝福あれ。いと高き所に、ホサナ」。

    -   \[DQ\] 人々は、どのようにして、イエスを迎えますか。それぞれの福音書を比較してみましょう。

        -   弟子たち、群衆、エルサレムの人々、パリサイ派の人々

    -   \[DQ\] イエスは、なぜ、ろばの子に乗って、エルサレムに入城したのでしょうか。

        -   ゼカリヤ9:9-10 との関係はどのように理解したらよいのだろうか。

    -   \[参照\] 旧約聖書のゼカリヤ書9章9節を読んでみましょう。イエスはご自身をどういう人物として、人々に紹介しようとしていますか。

        -   \[Q\] なぜ、マルコには書かれていないのか。ヨハネをみると、弟子たちはわからなかったということだろう。すなわち、イエスは、ゼカリヤ9：9 を知っていても、それを強調はしない。預言に制約される方ではない。

    -   戦いのときには、馬で、平和のときには、ろばで。

    -   \[ルカ\] イエスはなぜ、都を見て泣くのでしょう。（41節〜42節）

    -   \[ヨハネ\] 弟子たちが、あとから気づいたのはどのようなことでしょうか。

    -   この日はいつだったのでしょうか。棕櫚の聖日。

6.  この日の、イエスの様子は、どのように描かれていますか。（11）

    -   11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。

    -   \[DQ\] それぞれの福音書は何を伝えているのでしょうか。

        -   ヨハネはこの背景を丁寧に伝えているように見える。マルコの時代には、それは危険が伴い、マタイや、ルカは、マルコをそのまま引き継いだか。ヨハネの時代には、このことが明かされても安全だったのかもしれない。

### メモ

-   ベテパゲ、ベタニヤは、正確にはわからないが、イエスは何度も、この地域を訪ねていることは確かである。

-   マルコは非常にあっさり描いている。そのようにしか、描けなかったのかもしれないが、同時に、大きな騒ぎはなかったのかもしれない。ただ、ヨハネの記述とのギャップは感じる。

-   マタイでは、流れは、マルコと同じく、エリコでの（マタイでは二人の）盲人の癒やしのあとに置かれ、場所は、ベテパゲと断言している。これは、ベタニヤではないことを証言し、ベタニヤとあるのは、別の理由で入っていることを知っているものが執筆に関わっていたのだろう。またろばについては、二回にわたり、ろばと子ろばとの表現になっている。そして、イエスがどちらに乗られたか明確ではない。ゼカリヤ預言が挿入され、そこでもろばに乗って、くびきを負うろばの子に乗ってとなっている。群衆の声には「ダビデの子」が挿入されている。マルコにはそれはない。最後は、「イエスがエルサレムにはいって行かれたとき、町中がこぞって騒ぎ立ち、「これは、いったい、どなただろう」と言った。そこで群衆は、「この人はガリラヤのナザレから出た預言者イエスである」と言った。」と締めくくっている。群衆の、認識としては、預言者である。

-   ルカには、エリコでのザアカイの話が挿入されており、そのあとで、ムナの譬えがあり、一ムナを布に包んでしまっておいたものへのかなり厳しい裁きを宣告し、つづけて、「イエスはこれらのことを言ったのち、先頭に立ち、エルサレムへ上って行かれた。」と続けている。先頭に立ちは、マルコ10:32 「さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。」を思い起こさせる。場所に関しては、「オリブという山に沿ったベテパゲとベタニヤに近づかれたとき」とし、多少不自然な、マルコを踏襲しているように見える。「主がお入り用なのです」が二回繰り返され（マルコ、マタイでは一回）、それに応じたことが印象的に、伝えられている。「いよいよオリブ山の下り道あたりに近づかれると」の記述はあるが、エルサレム入城については、書かれていない。呼びかけには「王」と入っている。逆に、パリサイ人とのやり取り（拒否といってもよいだろう）が挿入されている。そして、この記事のあとには、「いよいよ都の近くにきて、それが見えたとき、そのために泣いて言われた」に続けて、エルサレムの破壊について語り、「それは、おまえが神のおとずれの時を知らないでいたからである」。と結んでいる。エルサレム入城の記事とは、違う表現になっている。

    -   ~33~λυόντων δὲ αὐτῶν τὸν πῶλον εἶπαν οἱ κύριοι αὐτοῦ πρὸς αὐτούς· τί λύετε τὸν πῶλον; ~34~οἱ δὲ εἶπαν· ὅτι ὁ κύριος αὐτοῦ χρείαν ἔχει. \[[NA28:LK19](https://www.die-bibel.de/en/bible/NA28/LUK.19)\]

        -   \[私訳\] 彼らが、その子ろばを解いていると、その子ろばの主人たちは（οἱ κύριοι αὐτοῦ）彼らに、なぜ、子ろばを解くのかと言うと、彼らは、その主人が（ὁ κύριος αὐτοῦ）、必要としているのですと言った。

-   ヨハネでは、11章、12章前半にラザロのことが書かれており、エルサレム入城（過越の祭りの5日前）のときにも、人々がそのことを知っていて、イエスを、迎えたことが書かれている。しかし、マルコでは、ベタニヤという言葉を出すだけで、そのことには言及しない。ロバを引いてきたのはおそらくマタイにもあるように、ベテパゲなのだろう。すると、マルコにある、ベタニヤは意味深である。ボウカムの「イエスとその目撃者たち」から学んだことだが、マルコが書かれた時代、または、ペテロが説教した時代には、そのことを語る危険性がまだ会ったのかもしれない。実際、ラザロをも殺そうとする動きがあったことも書かれているのだから。

    -   ヨハネ12:9-11 大ぜいのユダヤ人たちが、そこにイエスのおられるのを知って、押しよせてきた。それはイエスに会うためだけではなく、イエスが死人のなかから、よみがえらせたラザロを見るためでもあった。10 そこで祭司長たちは、ラザロも殺そうと相談した。11 それは、ラザロのことで、多くのユダヤ人が彼らを離れ去って、イエスを信じるに至ったからである。

-   マルコを読んでいると、イエスは、ゼカリヤ預言を自分のことに当てはめてはいなかったように思う。たしかに、ある部分、イエスに適合する部分はあるが、ラザロの復活以降は特に、エルサレムでは、すでに、お尋ね者になっている、イエスは、正々堂々とエルサレムに向かうことだけを考えて、人混みに紛れてではなく、ろばに乗って、エルサレムに向かったのではないだろうか。ヨハネで、ゼカリヤ預言については、弟子たちは、気づいていなかったことが書かれている。イエスは、そのことを言わなかった証拠でもある。すくなくとも、凱旋のようなイメージで捉えるのは、間違っていると思う。すぐ返すことや、最後のエルサレムを見て回ったことなども、マルコにしか書かれておらず、興味深い。そのあとに、ひとが、様々に、意味づけしたことが、他の福音書に含まれているのだろう。生のイエスではなくなっているようにみえる。

## 11:12-14 いちじくの木を呪う

> 12 翌日、彼らがベタニヤから出かけてきたとき、イエスは空腹をおぼえられた。13 そして、葉の茂ったいちじくの木を遠くからごらんになって、その木に何かありはしないかと近寄られたが、葉のほかは何も見当らなかった。いちじくの季節でなかったからである。14 そこで、イエスはその木にむかって、「今から後いつまでも、おまえの実を食べる者がないように」と言われた。弟子たちはこれを聞いていた。

### マタイ 21:18-19

> 18 朝はやく都に帰るとき、イエスは空腹をおぼえられた。19 そして、道のかたわらに一本のいちじくの木があるのを見て、そこに行かれたが、ただ葉のほかは何も見当らなかった。そこでその木にむかって、「今から後いつまでも、おまえには実がならないように」と言われた。すると、いちじくの木はたちまち枯れた。

[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

### メモ

-   マルコ11:20-26 と一緒に学ぶ

## 11:15-19 神殿から商人を追い出す

> 15 それから、彼らはエルサレムにきた。イエスは宮に入り、宮の庭で売り買いしていた人々を追い出しはじめ、両替人の台や、はとを売る者の腰掛をくつがえし、16 また器ものを持って宮の庭を通り抜けるのをお許しにならなかった。17 そして、彼らに教えて言われた、「『わたしの家は、すべての国民の祈の家ととなえらるべきである』と書いてあるではないか。それだのに、あなたがたはそれを強盗の巣にしてしまった」。18 祭司長、律法学者たちはこれを聞いて、どうかしてイエスを殺そうと計った。彼らは、群衆がみなその教に感動していたので、イエスを恐れていたからである。19 夕方になると、イエスと弟子たちとは、いつものように都の外に出て行った。

### マタイ 21:12-17

> 12 それから、イエスは宮にはいられた。そして、宮の庭で売り買いしていた人々をみな追い出し、また両替人の台や、はとを売る者の腰掛をくつがえされた。13 そして彼らに言われた、「『わたしの家は、祈の家ととなえらるべきである』と書いてある。それだのに、あなたがたはそれを強盗の巣にしている」。14 そのとき宮の庭で、盲人や足なえがみもとにきたので、彼らをおいやしになった。15 しかし、祭司長、律法学者たちは、イエスがなされた不思議なわざを見、また宮の庭で「ダビデの子に、ホサナ」と叫んでいる子供たちを見て立腹し、16 イエスに言った、「あの子たちが何を言っているのか、お聞きですか」。イエスは彼らに言われた、「そうだ、聞いている。あなたがたは『幼な子、乳のみ子たちの口にさんびを備えられた』とあるのを読んだことがないのか」。17 それから、イエスは彼らをあとに残し、都を出てベタニヤに行き、そこで夜を過ごされた。

### ルカ 19:45-48

> 45 それから宮にはいり、商売人たちを追い出しはじめて、46 彼らに言われた、「『わが家は祈の家であるべきだ』と書いてあるのに、あなたがたはそれを盗賊の巣にしてしまった」。47 イエスは毎日、宮で教えておられた。祭司長、律法学者また民衆の重立った者たちはイエスを殺そうと思っていたが、48 民衆がみな熱心にイエスに耳を傾けていたので、手のくだしようがなかった。

### ヨハネ 2:13-22

> 13 さて、ユダヤ人の過越の祭が近づいたので、イエスはエルサレムに上られた。14 そして牛、羊、はとを売る者や両替する者などが宮の庭にすわり込んでいるのをごらんになって、15 なわでむちを造り、羊も牛もみな宮から追いだし、両替人の金を散らし、その台をひっくりかえし、16 はとを売る人々には「これらのものを持って、ここから出て行け。わたしの父の家を商売の家とするな」と言われた。17 弟子たちは、「あなたの家を思う熱心が、わたしを食いつくすであろう」と書いてあることを思い出した。18 そこで、ユダヤ人はイエスに言った、「こんなことをするからには、どんなしるしをわたしたちに見せてくれますか」。19 イエスは彼らに答えて言われた、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。20 そこで、ユダヤ人たちは言った、「この神殿を建てるのには、四十六年もかかっています。それだのに、あなたは三日のうちに、それを建てるのですか」。21 イエスは自分のからだである神殿のことを言われたのである。22 それで、イエスが死人の中からよみがえったとき、弟子たちはイエスがこう言われたことを思い出して、聖書とイエスのこの言葉とを信じた。

[マルコによる福音書11章15-19節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_15-19.pdf)

[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

### 問い

1.  背景を復習しましょう。前日について、この日についてどんなことがわかりますか。（11:1-14）

2.  イエスは、どこで、どんなことをしますか。（15,16）

3.  イエスは、どのように言っていますか。（17）

4.  イエスの行動は弟子たちに、人々にどううつったでしょうか。祭司長や律法学者たちはどう考えましたか。（18）

5.  イエスは、このあとどうしますか。（19）

6.  他の福音書、特に、ヨハネによる福音書の記事と比較してみましょう。どんなことがわかりますか。

### 参照

-   ベタニヤ（ナツメヤシの家）について（ヨハネ1:28 にある、ヨルダン川付近のベタニヤは省略）エリコから、エルサレムへ向かう途上の、エルサレムから3km ほどの村。

    -   マルコ14:3-9 3 イエスがベタニヤで、重い皮膚病の人シモンの家にいて、食卓についておられたとき、ひとりの女が、非常に高価で純粋なナルドの香油が入れてある石膏のつぼを持ってきて、それをこわし、香油をイエスの頭に注ぎかけた。（マタイ26:6-13）

        -   ヨハネ 12章1-11節 1 過越の祭の六日まえに、イエスはベタニヤに行かれた。そこは、イエスが死人の中からよみがえらせたラザロのいた所である。

    -   ルカ10:38-42 （マルタとマリアについて）一同が旅を続けているうちに、イエスがある村へはいられた。するとマルタという名の女がイエスを家に迎え入れた。この女にマリヤという妹がいたが、主の足もとにすわって、御言に聞き入っていた。（ベタニヤとは明確には書かれていない）

    -   ルカ24:50-53 昇天 50 それから、イエスは彼らをベタニヤの近くまで連れて行き、手をあげて彼らを祝福された。

    -   ヨハネ11章全体 1 さて、ひとりの病人がいた。ラザロといい、マリヤとその姉妹マルタの村ベタニヤの人であった。

-   エルサレムについては、エルサレム入城 \[[参考](https://icu-hsuzuki.github.io/biblestudy/markdq.html#参照-59)\]

    -   宣教活動を始めたからは、ヨハネのみに記載：2:13-25、3:1-21、5:1-47 ユダヤが中心で、サマリヤについても、記述がある。

-   受難週のエルサレムの地図 \[[The Passion Week in Jerusalem](https://www.seektheoldpaths.com/Maps/113.jpg)\]

-   ヘロデ神殿　\[[Herod's Temple](https://www.seektheoldpaths.com/Maps/126a.jpg)\]

    -   BC20/19 ごろ、BC520-515 ごろの、ゼルバベルの神殿の改築を開始、AD63に完成、AD70にテトスにより破壊。

-   The Temple at Jerusalem in Jesus' Day, Clyde W. Votaw \[[pdf](https://www.journals.uchicago.edu/doi/pdf/10.1086/473359)\]

-   イザヤ56:7 わたしはこれをわが聖なる山にこさせ、／わが祈の家のうちで楽しませる、／彼らの燔祭と犠牲とは、／わが祭壇の上に受けいれられる。わが家はすべての民の／祈の家ととなえられるからである」。

-   エレミヤ7:11 わたしの名をもって、となえられるこの家が、あなたがたの目には盗賊の巣と見えるのか。わたし自身、そう見たと主は言われる。

-   ヨハネにはこのあと、イエスは人の心を知っておられる、の記事が入っている。（ヨハネ2:23-25）

    -   23 過越の祭の間、イエスがエルサレムに滞在しておられたとき、多くの人々は、その行われたしるしを見て、イエスの名を信じた。24 しかしイエスご自身は、彼らに自分をお任せにならなかった。それは、すべての人を知っておられ、25 また人についてあかしする者を、必要とされなかったからである。それは、ご自身人の心の中にあることを知っておられたからである。

-   宮・神殿

    -   コリント前書3:16-17 あなたがたは神の神殿であり、神の霊が自分の内に住んでいることを知らないのですか。17 神の神殿を壊す者がいれば、神はその人を滅ぼされます。神の神殿は聖なるものだからです。あなたがたはその神殿なのです。

    -   申命記14:24-26 しかし、あなたの神、主があなたを祝福しても、あなたの神、主がその名を置くために選ぶ場所が遠く離れ、その道のりが長すぎて、それを携えて行くことができないなら、25 あなたはそれを銀に換え、その銀を携え、あなたの神、主が選ぶ場所に向かい、26 その銀であなたの望むもの、すなわち、牛でも羊でもぶどう酒でも麦の酒でも、何でもあなたの好きなものを求め、あなたの神、主の前で食べ、あなたも家族も楽しみなさい。

### 記録

-   日時：2024年9月19日午後7時半〜9時半

-   出席（対面）2名、参加（遠隔）3名

### 問いについて

1.  背景を復習しましょう。前日について、この日についてどんなことがわかりますか。（11:1-14）

    -   子ろばに乗りエルサレム入城。その後、「11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。」

    -   12 翌日、彼らがベタニヤから出かけてきたとき、イエスは空腹をおぼえられた。

    -   \[DQ\] ベタニヤについてどのようなことが聖書には書かれていますか。

        -   マルコ14:3-9（香油）（マタイ26:6-13、ヨハネ 12:1-11）、ルカ10:38-42（マルタとマリア）、ルカ24:50-53（昇天）、ヨハネ11章（ラザロの復活）、

        -   \[考察\] ベタニアの滞在先などについては、語らない。イエスと弟子の一団は、おそらく、弟子と女性たちもふくめると、20人は降らず、もっと多かったかもしれないので、十分、打ち合わせもあったはずである。すくなくとも、マルタ、マリア、ラザロの家などがあったと思われるが、おそらく、ペテロが語った時点では、このようなエピソードを語ることは、ベタニヤのひとたちに危険があった可能性もあったのだろう。それもあって、ベタニヤについては、語らないのかもしれない。

    -   \[DQ\] 「すべてのものを見回った」とありますが、どんなことを観察したと思いますか。

        -   \[A\] おそらく、宮のことも観察したはずである。

    -   \[DQ\] すべてのものを見まわったとき、イエスは、神殿（宮）について、どう見ておられたのでしょうか。そのときは、憤りをもっても、なにもしないことにして、十分考えてから以下の行動をしたのだろうか。

2.  イエスは、どこで、どんなことをしますか。（15,16）

    -   15 それから、彼らはエルサレムにきた。イエスは宮に入り、宮の庭で売り買いしていた人々を追い出しはじめ、両替人の台や、はとを売る者の腰掛をくつがえし、16 また器ものを持って宮の庭を通り抜けるのをお許しにならなかった。

    -   \[A\] ①宮の庭で売り買いしていた人々を追い出し　②両替人の台や、はとを売る者の腰掛けをくつがえし　③器ものをもって宮の庭を通り抜けるのを許さない。

        -   律法通り、シケル税を納めるには、外国貨幣の使われていた当時には必須だった。（出エジプト30:12-16 30:13 すべて数に入る者は聖所のシケルで、半シケルを払わなければならない。一シケルは二十ゲラであって、おのおの半シケルを主にささげ物としなければならない。参照：レビ記5:15, 27:3, 25、民数記 3:47,50,7:13,19,25,31,37,43,49,55,61,67,73,79,85,86,18:16）

        -   物の売買 申命記14:25,26 あなたはその物を金に換え、その金を包んで手に取り、あなたの神、主が選ばれる場所に行き、26 その金をすべてあなたの好む物に換えなければならない。すなわち牛、羊、ぶどう酒、濃い酒など、すべてあなたの欲する物に換え、その所であなたの神、主の前でそれを食べ、家族と共に楽しまなければならない。

        -   鳩を売る者たち：レビ記5:7 もし小羊に手のとどかない時は、山ばと二羽か、家ばとのひな二羽かを、彼が犯した罪のために償いとして主に携えてきて、一羽を罪祭に、一羽を燔祭にしなければならない。

            -   レビ記12:8 もしその女が小羊に手の届かないときは、山ばと二羽か、家ばとのひな二羽かを取って、一つを燔祭、一つを罪祭とし、祭司はその女のために、あがないをしなければならない。こうして女は清まるであろう』」。

    -   \[DQ\] それぞれ、どのようなことをしている人なのでしょうか。

        -   \[A\] 宮の庭で商売をしていたひとの邪魔をした。

            -   おそらく、ささげ物を売っている人々や、神殿に納めるお金のための換金であろう。

        -   \[Q\] 売り買いをしているのと、はとを売るのは、違うのでしょうか。

    -   \[DQ\] このイエスの行為は、（公的に認められている商売を邪魔をする）犯罪ではないのでしょうか。

        -   メシアの権威？

    -   \[DQ\] かなり、乱暴に見えますが、もっと、他の方法はなかったのでしょうか。The Lesser Evil？

3.  イエスは、どのように言っていますか。（17）

    -   17 そして、彼らに教えて言われた、「『わたしの家は、すべての国民の祈の家ととなえらるべきである』と書いてあるではないか。それだのに、あなたがたはそれを強盗の巣にしてしまった」。

    -   イザヤ56:7 わたしはこれをわが聖なる山にこさせ、／わが祈の家のうちで楽しませる、／彼らの燔祭と犠牲とは、／わが祭壇の上に受けいれられる。わが家はすべての民の／祈の家ととなえられるからである」。

        -   主が喜ぶひとのことが書かれ、そのあとに、その人達を導き、その結果として、主の家が、祈りの家と唱えられるとしている。

        -   \[注\] すべての民、すべての国民は、一般的には異邦人を含む。マタイでは省略。また、商売は、異邦人の庭で開かれていたとされる。

    -   エレミヤ7:11 わたしの名をもって、となえられるこの家が、あなたがたの目には盗賊の巣と見えるのか。わたし自身、そう見たと主は言われる。

        -   主が喜ばれることをしていないことを指摘しており、商売などについて、言っているわけではない。

    -   \[DQ\] イエスが伝えたかったことは、何なのでしょうか。イエスにとって神の宮（神殿）とは、どのようなものなのでしょうか。

        -   \[A\] 神が臨在される場所、聖霊が住む場所（？）

        -   \[A\] 神殿にふさわしい状況ではなかったかもしれないが、そこまで、怒ることもなかったのではないだろうか。ただ、不適切な状況があることを、指摘した面はあるように見える。乱暴だが。他の改善があってよいのではないかと思われるし、イエスの伝えたいメッセージの中心では、ないように見える。

    -   神の宮（神殿）について：宗教行事を行う場所ではなく、より普遍的な神殿を意識していたのかもしれない。

        -   1コリ3:16,17 あなたがたは神の宮であって、神の御霊が自分のうちに宿っていることを知らないのか。17 もし人が、神の宮を破壊するなら、神はその人を滅ぼすであろう。なぜなら、神の宮は聖なるものであり、そして、あなたがたはその宮なのだからである。

        -   1コリ6:19 あなたがたは知らないのか。自分のからだは、神から受けて自分の内に宿っている聖霊の宮であって、あなたがたは、もはや自分自身のものではないのである。

        -   2コリ6:16 神の宮と偶像となんの一致があるか。わたしたちは、生ける神の宮である。神がこう仰せになっている、／「わたしは彼らの間に住み、／かつ出入りをするであろう。そして、わたしは彼らの神となり、／彼らはわたしの民となるであろう」。

        -   （より抽象的）エペソ2:21 このキリストにあって、建物全体が組み合わされ、主にある聖なる宮に成長し、

4.  イエスの行動は弟子たちに、人々にどううつったでしょうか。祭司長や律法学者たちはどう考えましたか。（18）

    -   18 祭司長、律法学者たちはこれを聞いて、どうかしてイエスを殺そうと計った。彼らは、群衆がみなその教に感動していたので、イエスを恐れていたからである。

    -   \[DQ\] イエスのどんな教えに群衆は感動し、イエスを恐れていたのでしょうか。

        -   \[A\] ここには、神殿のことしか、書かれていない。ガリラヤから来た人々は、すでに、いろいろと聞いてかもしれないが、エルサレムの人々、ここではじめてイエスにであったひとたちは、どんな教えを聞いたのだろうか。

        -   \[Q\] イエスを恐れる（φοβέω: 恐怖を感じる、心配をする、畏れかしこむ）とは、どんな状態を言っているのでしょうか。

    -   \[DQ\] 弟子たちは、いつものイエス様として、当然と思ったでしょうか。ガリラヤでは、似たことはありましたか。かたくなさを嘆いたことはあった。

    -   \[DQ\] 祭司長や、律法学者が、イエスを殺そうとまで思ったのは、何が理由なのでしょうか。

        -   \[A\] 宗教活動の本質を、変えようとしたことかもしれない。宮きよめは、関係はしているが、それがコアだとは、思えない。

    -   \[考察\] イエスを殺そうと計る理由は、いくつかあっただろうが、ほんとうに、この宮清めが、祭司長や、律法学者の怒りをかったとは思えない。むろん、イエスの行為は、問題だと感じただろうが。

5.  イエスは、このあとどうしますか。（19）

    -   19 夕方になると、イエスと弟子たちとは、いつものように都の外に出て行った。

    -   \[DQ\] なにか、あっさり書かれていますが、この日は、宮清めだけだったのでしょうか。

    -   \[DQ\] いつものようにとは、なにを意味しているのでしょうか。都では、このようなことがしばしばあったのでしょうか。エルサレムには、何回も来ていますか。

        -   \[A\] マルコでは、このときが、初めてであるが、ヨハネでは、何回も、エルサレムに来ていることが書かれている。なにかを飛ばしているように思われる。

    -   \[考察\] エルサレムに来ていたことを、書かない理由が何かしらあったのだろう。そして、「いつものように都の外に出て行った」としか書けなかった理由があったのだろう。

    -   \[DQ\] マタイと、ルカでは、どのようなことが最後に書かれていますか。

        -   マタイ 21:14-16 14 そのとき宮の庭で、盲人や足なえがみもとにきたので、彼らをおいやしになった。15 しかし、祭司長、律法学者たちは、イエスがなされた不思議なわざを見、また宮の庭で「ダビデの子に、ホサナ」と叫んでいる子供たちを見て立腹し、16 イエスに言った、「あの子たちが何を言っているのか、お聞きですか」。イエスは彼らに言われた、「そうだ、聞いている。あなたがたは『幼な子、乳のみ子たちの口にさんびを備えられた』とあるのを読んだことがないのか」。

        -   ルカ 19:47,48 47 イエスは毎日、宮で教えておられた。祭司長、律法学者また民衆の重立った者たちはイエスを殺そうと思っていたが、48 民衆がみな熱心にイエスに耳を傾けていたので、手のくだしようがなかった。

        -   \[A\] マタイと、ルカでは、祭司長、律法学者たちが、イエスを殺そうとする、または、反対する、それなりに、理解できる理由が、書かれている。（マルコを読んだひとには、理解できなかったから、書いたのだろう。）

            -   マタイ：不思議なわざ、こどもたちが、ダビデの子に、ホサナと叫んでいる。

            -   ルカ：毎日宮で教えておられた。民衆は、それに、熱心に耳を傾けていた。

6.  他の福音書、特に、ヨハネによる福音書の記事と比較してみましょう。どんなことがわかりますか。

    -   \[DQ\] ヨハネ2:17：「あなたの家を思う熱意がわたしを食い尽くす」とはどのような意味ですか。

    -   \[DQ\] ヨハネ2:18-22：ユダヤ人、イエスでどのようなやり取りをしますか。弟子たちは、どう理解しますか。

    -   \[DQ\] ヨハネでは、いつ頃のこととして書かれていますか。

        -   かなり初期のことだとされている。過越の祭りが近いことは同じ。(2:13)

        -   この神殿を建てるのには、四十六年もかかっています。(2:20b)

            -   BC19から、ヘロデが再建を始めたと言われている。AD28 頃と思われる。

        -   \[注\] マタイとルカには、日付（翌日）の記述はない。「それから」としており、エルサレム入場時のこととしている。そのほうが、自然にも見える。しかし、マルコの記述が不自然とした、編集とも考えられる。

    -   \[DQ\] ヨハネでは、イエスが、どのようなことをし、その行為の理由は何だと言っていますか。

        -   2:14-16 14 そして牛、羊、はとを売る者や両替する者などが宮の庭にすわり込んでいるのをごらんになって、15 なわでむちを造り、羊も牛もみな宮から追いだし、両替人の金を散らし、その台をひっくりかえし、16 はとを売る人々には「これらのものを持って、ここから出て行け。わたしの父の家を商売の家とするな」と言われた。

        -   \[A\] 自分の父の家だと考えている。

        -   2:17-22 17 弟子たちは、「あなたの家を思う熱心が、わたしを食いつくすであろう」と書いてあることを思い出した。18 そこで、ユダヤ人はイエスに言った、「こんなことをするからには、どんなしるしをわたしたちに見せてくれますか」。19 イエスは彼らに答えて言われた、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。20 そこで、ユダヤ人たちは言った、「この神殿を建てるのには、四十六年もかかっています。それだのに、あなたは三日のうちに、それを建てるのですか」。21 イエスは自分のからだである神殿のことを言われたのである。22 それで、イエスが死人の中からよみがえったとき、弟子たちはイエスがこう言われたことを思い出して、聖書とイエスのこの言葉とを信じた。

        -   \[A\] 「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。とまで言っている。ちょっと早すぎるように思う。

        -   \[参照\] マルコ14:58 「わたしたちはこの人が『わたしは手で造ったこの神殿を打ちこわし、三日の後に手で造られない別の神殿を建てるのだ』と言うのを聞きました」。マルコ15:29 そこを通りかかった者たちは、頭を振りながら、イエスをののしって言った、「ああ、神殿を打ちこわして**三日**のうちに建てる者よ、（マタイ26:61, 27:64）（これが実際いつの時点でどのように言われたかはマルコには書かれていない。訴えられた理由でもあるので、明言は避けたのか。）

        -   \[参照\] 詩篇69:9 (または 10) あなたの家を思う熱心がわたしを食いつくし、／あなたをそしる者のそしりが／わたしに及んだからです。

        -   \[参照\] 46年（BC20/19年開始）このとき、AD28年頃となる。イエスの十字架は　AD30の過越祭頃と思われる。

    -   \[DQ\] 同じ時のことなのでしょうか。それとも、こんなことが、何度もあったのでしょうか。

### メモ

-   個人的には、宮清めは、ヨハネの記述のように、受難週とよばれる最後の週ではなく、早い時期に、あったほうが自然であるように、感じる。マルコの記述をみると、エルサレム入城を堂々とおこない、宮を見て回られてから、そのままベタニヤに帰り、次の朝、早くに、エルサレムに戻ったように書いてあるが、この日にしたこととしては、宮清めだけである。不自然にも感じる。それと、メッセージをこめて、これだけの行為をするなら、前の日に見て回ったときに、しても良さそうである。そのときには、なにもせず、次の日の朝、このような行為をするのは、不自然である。ここでは、祭司長、律法学者との緊張関係（イエスを殺そうとする）と、群衆の様子を描くために、この記事を、入れたように見える。ヨハネは「さて、ユダヤ人の過越の祭が近づいたので、イエスはエルサレムに上られた。」（2:13）と始まり、このときに、何人かの弟子たちも同行したかもしれない。「アンデレと、もう一人の弟子」（1:10）は、一緒にいたのではないだろうか。目撃証言として書かれている。マルコでは、エルサレムや、ベタニヤの人たちを、守る必要があったからだろうか、エルサレム入城を書いたヨハネに登場するラザロのことは、なにも書かれていない。しかし、何らかの背景をかかないと、緊張状態を描けなかったのではないだろうか。それが、この記事であると思われる。ただし、ヨハネでは、エルサレム入城を日曜日に設定しているようだが、そのあとは、ギリシャ人、イエスに会いに来る。人の子はあげられる。イエスを信じない者たち。イエスの言葉による裁きと、12章にあるが、すぐ木曜日の夜と思われる、13章に突入し、ほとんど、時系列的な、出来事は記していない。拙速には、判断しにくいのかもしれない。

-   イエスの行為として、最初の頃なら、激昂してということも、理解できる。ヨハネが、記す「17 弟子たちは、『あなたの家を思う熱心が、わたしを食いつくすであろう』と書いてあることを思い出した。」も、ある程度の興奮状態を表現しているとも見える。一方、最後のエルサレム入城のときは、イエスは、隠れて入るつもりは、まったくないことを示すためもあり、ふさわしいと考えた、子ろばに乗って入ったのであろうが、イエスの行為は「いつものように」と、ふつうなのだろう。神殿を壊したらも、このころに言うのは、預言としては、早いように思うが、イエスの中では、神殿についての思い、自分という神殿、さまざまなものが、ここで結びついたのかもしれない。マルコでは、イザヤからの引用を中心として描いている。それは、正統にみえるので。マルコの不自然な記述を考え、それに、マタイや、ルカが、注をつけていることを考えると、当時も、不自然と考えたのだろう。それは、致し方ないことだったのだろう。ベタニヤや、エルサレム周辺のひとたちを危険にさらさないために。

## 11:12-14, 20-26 いちじくの木を呪う/枯れたいちじくの木の教訓

> 12 翌日、彼らがベタニヤから出かけてきたとき、イエスは空腹をおぼえられた。13 そして、葉の茂ったいちじくの木を遠くからごらんになって、その木に何かありはしないかと近寄られたが、葉のほかは何も見当らなかった。いちじくの季節でなかったからである。14 そこで、イエスはその木にむかって、「今から後いつまでも、おまえの実を食べる者がないように」と言われた。弟子たちはこれを聞いていた。

> 20 朝はやく道をとおっていると、彼らは先のいちじくが根元から枯れているのを見た。21 そこで、ペテロは思い出してイエスに言った、「先生、ごらんなさい。あなたがのろわれたいちじくが、枯れています」。22 イエスは答えて言われた、「神を信じなさい。23 よく聞いておくがよい。だれでもこの山に、動き出して、海の中にはいれと言い、その言ったことは必ず成ると、心に疑わないで信じるなら、そのとおりに成るであろう。24 そこで、あなたがたに言うが、なんでも祈り求めることは、すでにかなえられたと信じなさい。そうすれば、そのとおりになるであろう。25 また立って祈るとき、だれかに対して、何か恨み事があるならば、ゆるしてやりなさい。そうすれば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださるであろう。26 〔もしゆるさないならば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださらないであろう〕」。

### マタイ 21:18-19, 20-22

> 18 朝はやく都に帰るとき、イエスは空腹をおぼえられた。19 そして、道のかたわらに一本のいちじくの木があるのを見て、そこに行かれたが、ただ葉のほかは何も見当らなかった。そこでその木にむかって、「今から後いつまでも、おまえには実がならないように」と言われた。すると、いちじくの木はたちまち枯れた。

> 20 弟子たちはこれを見て、驚いて言った、「いちじくがどうして、こうすぐに枯れたのでしょう」。21 イエスは答えて言われた、「よく聞いておくがよい。もしあなたがたが信じて疑わないならば、このいちじくにあったようなことが、できるばかりでなく、この山にむかって、動き出して海の中にはいれと言っても、そのとおりになるであろう。22 また、祈のとき、信じて求めるものは、みな与えられるであろう」。

[マルコによる福音書11章12-14, 20-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-14_20-26.pdf)

[マルコによる福音書11章12-26節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_12-26.pdf)

### 問い

1.  背景を確認しましょう。どのようなときのことですか。（12）

2.  イエスは、どのようなことをしますか。（13-14）

3.  このいちじくは、どうなりますか。（20,21）

4.  いちじくのことから、イエスは弟子たちにどのようなことを教えていますか。（22-24）

5.  祈りとゆるしにはどのような関係があるのでしょか。(25,(26))

6.  あなたは、このいちじくの話から何を学びますか。

### 参照

-   \[バークレイ\] 過越の季節は4月の半ばごろ、日陰の場所にあるいちじくの木は、3月早々には葉をつけるだろうが、しかし、5月の終わりか、6月にならないと実をつけないものである。マルコは、いちじくの季節ではなかったと言っている。

-   旧約/新約聖書におけるいちじく

    -   創世記3:7 すると、ふたりの目が開け、自分たちの裸であることがわかったので、いちじくの葉をつづり合わせて、腰に巻いた。

    -   民数記13:23 ついに彼らはエシコルの谷に行って、そこで一ふさのぶどうの枝を切り取り、これを棒をもって、ふたりでかつぎ、また、ざくろといちじくをも取った。

    -   民数記20:3 どうしてあなたがたはわれわれをエジプトから上らせて、この悪い所に導き入れたのですか。ここには種をまく所もなく、いちじくもなく、ぶどうもなく、ざくろもなく、また飲む水もありません」。

    -   士師記9:10,11 もろもろの木はまたいちじくの木に言った、『きてわたしたちの王になってください』。しかしいちじくの木は彼らに言った、『わたしはどうしてわたしの甘味と、わたしの良い果実とを捨てて行って、もろもろの木を治めることができましょう』。

    -   サムエル記上25:18 その時、アビガイルは急いでパン二百、ぶどう酒の皮袋二つ、調理した羊五頭、いり麦五セア、ほしぶどう百ふさ、ほしいちじくのかたまり二百を取って、ろばにのせ、

    -   サムエル記上30:12 また彼らはほしいちじくのかたまり一つと、ほしぶどう二ふさを彼に与えた。彼は食べて元気を回復した。彼は三日三夜、パンを食べず、水を飲んでいなかったからである。

    -   列王紀上4:25 ソロモンの一生の間、ユダとイスラエルはダンからベエルシバに至るまで、安らかにおのおの自分たちのぶどうの木の下と、いちじくの木の下に住んだ。

    -   列王紀下18:31 あなたがたはヒゼキヤの言葉を聞いてはならない。アッスリヤの王はこう仰せられる、『あなたがたはわたしと和解して、わたしに降服せよ。そうすればあなたがたはおのおの自分のぶどうの実を食べ、おのおの自分のいちじくの実を食べ、おのおの自分の井戸の水を飲むことができるであろう。

    -   列王紀下20:7 そしてイザヤは言った、「干しいちじくのひとかたまりを持ってきて、それを腫物につけさせなさい。そうすれば直るでしょう」。（ヒゼキヤへのことば）

    -   歴代志上12:40 また彼らに近い人々はイッサカル、ゼブルン、ナフタリなどの遠い所の者まで、ろば、らくだ、騾馬、牛などに食物を負わせて来た。すなわち麦粉の食物、干いちじく、干ぶどう、ぶどう酒、油、牛、羊などを多く携えて来た。これはイスラエルに喜びがあったからである。

    -   ネヘミヤ記13:15 そのころわたしはユダのうちで安息日に酒ぶねを踏む者、麦束を持ってきて、ろばに負わす者、またぶどう酒、ぶどう、いちじくおよびさまざまの荷を安息日にエルサレムに運び入れる者を見たので、わたしは彼らが食物を売っていたその日に彼らを戒めた。

    -   詩篇 78:47 神はひょうをもって彼らのぶどうの木を枯らし、／霜をもって彼らのいちじく桑の木を枯らされた。（出エジプト時のしるし）

    -   詩篇105:33 主は彼らのぶどうの木と、いちじくの木とを撃ち、／彼らの国のもろもろの木を折り砕かれた。（出エジプト時のしるし）

    -   箴言27:18 いちじくの木を守る者はその実を食べる、／主人を尊ぶ者は誉を得る。

    -   雅歌2:13 いちじくの木はその実を結び、／ぶどうの木は花咲いて、かんばしいにおいを放つ。わが愛する者よ、わが麗しき者よ、／立って、出てきなさい。

    -   イザヤ書28:4 肥えた谷のかしらにある／しぼみゆく花の美しい飾りは、／夏前に熟した初なりのいちじくのようだ。人がこれを見ると、取るやいなや、食べてしまう。

    -   イザヤ書34:4 天の万象は衰え、／もろもろの天は巻物のように巻かれ、／その万象はぶどうの木から葉の落ちるように、／いちじくの木から葉の落ちるように落ちる。（国々への裁き）

    -   イザヤ書36:16 あなたがたはヒゼキヤの言葉を聞いてはならない。アッスリヤの王はこう仰せられる、『あなたがたは、わたしと和ぼくして、わたしに降服せよ。そうすれば、あなたがたはめいめい自分のぶどうの実を食べ、めいめい自分のいちじくの実を食べ、めいめい自分の井戸の水を飲むことができる。

    -   イザヤ書38:21 イザヤは言った、「干いちじくのひとかたまりを持ってこさせ、それを腫物につけなさい。そうすれば直るでしょう」。

    -   エレミヤ書5:17 彼らはあなたが刈り入れた物と、／あなたの糧食とを食い尽し、／あなたのむすこ娘を食い尽し、／あなたの羊と牛を食い尽し、／あなたのぶどうの木といちじくの木を食い尽し、／またつるぎをもって、あなたが頼みとする／堅固な町々を滅ぼす」。

    -   エレミヤ書8:13 主は言われる、わたしが集めようと思うとき、／ぶどうの木にぶどうはなく、／いちじくの木に、いちじくはなく、／葉さえ、しぼんでいる。わたしが彼らに与えたものも、／彼らを離れて、うせ去った」。

    -   エレミヤ書24:1-8 バビロンの王ネブカデレザルがユダの王エホヤキムの子エコニヤおよびユダの君たちと工匠と鍛冶をエルサレムからバビロンに移して後、主はわたしにこの幻をお示しになった。見よ、主の宮の前に置かれているいちじくを盛った二つのかごがあった。2 その一つのかごには、はじめて熟したような非常に良いいちじくがあり、ほかのかごには非常に悪くて食べられないほどの悪いいちじくが入れてあった。3 主はわたしに、「エレミヤよ、何を見るか」と言われた。わたしは、「いちじくです。その良いいちじくは非常によく、悪いほうのいちじくは非常に悪くて、食べられません」と答えた。4 主の言葉がまたわたしに臨んだ、5 「イスラエルの神、主はこう仰せられる、この所からカルデヤびとの地に追いやったユダの捕われ人を、わたしはこの良いいちじくのように顧みて恵もう。6 わたしは彼らに目をかけてこれを恵み、彼らをこの地に返し、彼らを建てて倒さず、植えて抜かない。7 わたしは彼らにわたしが主であることを知る心を与えよう。彼らはわたしの民となり、わたしは彼らの神となる。彼らは一心にわたしのもとに帰ってくる。8 主はこう仰せられる、わたしはユダの王ゼデキヤとそのつかさたち、およびエルサレムの人の残ってこの地にいる者、ならびにエジプトの地に住んでいる者を、この悪くて食べられない悪いいちじくのようにしよう。

    -   エレミヤ書29:17 『万軍の主はこう言われる、見よ、わたしは、つるぎと、ききんと、疫病を彼らに送り、彼らを悪くて食べられない腐ったいちじくのようにしてしまう。

    -   ホセア書2:12 わたしはまた彼女が先に『これはわたしの恋人らが、／わたしに与えた報酬だ』と言った彼女の／ぶどうの木と、いちじくの木とを荒し、／これを林とし、／野の獣にこれを食わせる。

    -   ホセア書9:10 わたしはイスラエルを荒野のぶどうのように見、／あなたがたの先祖たちを、／いちじくの木の初めに結んだ初なりのように見た。ところが彼らはバアル・ペオルへ行き、／身をバアルにゆだね、／彼らが愛した物と同じように憎むべき者となった。

    -   ヨエル書1:12 ぶどうの木は枯れ、いちじくの木はしおれ、／ざくろ、やし、りんご、野のすべての木はしぼんだ。それゆえ楽しみは人の子らからかれうせた。

    -   ヨエル書2:22 野のもろもろの獣よ、恐るな。荒野の牧草はもえいで、木はその実を結び、／いちじくの木とぶどうの木とは豊かに実る。

    -   アモス書4:9 「わたしは立ち枯れと腐り穂とをもって／あなたがたを撃ち、／あなたがたの園と、ぶどう畑とを荒した。いちじくの木とオリブの木とは、いなごが食った。それでも、あなたがたはわたしに帰らなかった」と／主は言われる。

    -   アモス書7:14 アモスはアマジヤに答えた、「わたしは預言者でもなく、また預言者の子でもない。わたしは牧者である。わたしはいちじく桑の木を作る者である。

    -   ミカ書4:4 彼らは皆そのぶどうの木の下に座し、／そのいちじくの木の下にいる。彼らを恐れさせる者はない。これは万軍の主がその口で語られたことである。

    -   ミカ書7:1 わざわいなるかな、わたしは夏のくだものを集める時のように、／ぶどうの収穫の残りを集める時のようになった。食らうべきぶどうはなく、／わが心の好む初なりのいちじくもない。

    -   ナホム3:12 あなたのとりでは皆／初なりの実をもつ、いちじくの木のようだ。これをゆすぶればその実は落ちて、／食べようとする者の口にはいる。

    -   ハバクク書3:17 いちじくの木は花咲かず、／ぶどうの木は実らず、／オリブの木の産はむなしくなり、／田畑は食物を生ぜず、／おりには羊が絶え、／牛舎には牛がいなくなる。

    -   ハガイ書2:19 種はなお、納屋にあるか。ぶどうの木、いちじくの木、ざくろの木、オリブの木もまだ実を結ばない。しかし、わたしはこの日から、あなたがたに恵みを与える」。

    -   ゼカリヤ書3:10 万軍の主は言われる、その日には、あなたがたはめいめいその隣り人を招いて、ぶどうの木の下、いちじくの木の下に座すのである」。

    -   マタイによる福音書7:16 あなたがたは、その実によって彼らを見わけるであろう。茨からぶどうを、あざみからいちじくを集める者があろうか。(ルカ6:44木はそれぞれ、その実でわかる。いばらからいちじくを取ることはないし、野ばらからぶどうを摘むこともない。)

    -   ルカによる福音書19:4 それでイエスを見るために、前の方に走って行って、いちじく桑の木に登った。そこを通られるところだったからである。

    -   ヨハネによる福音書1:48-50 ナタナエルは言った、「どうしてわたしをご存じなのですか」。イエスは答えて言われた、「ピリポがあなたを呼ぶ前に、わたしはあなたが、いちじくの木の下にいるのを見た」。49 ナタナエルは答えた、「先生、あなたは神の子です。あなたはイスラエルの王です」。50 イエスは答えて言われた、「あなたが、いちじくの木の下にいるのを見たと、わたしが言ったので信じるのか。これよりも、もっと大きなことを、あなたは見るであろう」。

    -   ヤコブの手紙3:12 わたしの兄弟たちよ。いちじくの木がオリブの実を結び、ぶどうの木がいちじくの実を結ぶことができようか。塩水も、甘い水を出すことはできない。

    -   ヨハネの黙示録6:13 天の星は、いちじくのまだ青い実が大風に揺られて振り落されるように、地に落ちた。

-   いちじくに関する他の記述（マルコ13:28-32、マタイ24:32-35、ルカ21:29-33）28 いちじくの木からこの譬を学びなさい。その枝が柔らかになり、葉が出るようになると、夏の近いことがわかる。29 そのように、これらの事が起るのを見たならば、人の子が戸口まで近づいていると知りなさい。30 よく聞いておきなさい。これらの事が、ことごとく起るまでは、この時代は滅びることがない。31 天地は滅びるであろう。しかしわたしの言葉は滅びることがない。32 その日、その時は、だれも知らない。天にいる御使たちも、また子も知らない、ただ父だけが知っておられる。

-   ルカ13:6-9 それから、この譬を語られた、「ある人が自分のぶどう園にいちじくの木を植えて置いたので、実を捜しにきたが見つからなかった。7 そこで園丁に言った、『わたしは三年間も実を求めて、このいちじくの木のところにきたのだが、いまだに見あたらない。その木を切り倒してしまえ。なんのために、土地をむだにふさがせて置くのか』。8 すると園丁は答えて言った、『ご主人様、ことしも、そのままにして置いてください。そのまわりを掘って肥料をやって見ますから。9 それで来年実がなりましたら結構です。もしそれでもだめでしたら、切り倒してください』」。

    -   ルカのみのもの、またルカには、枯れたいちじくの話は含まれていない。

-   イエスのが十字架に架かった日

    -   \[Gemini-1.5-Pro\] AD30年説：この年は、福音書に記されている出来事と、当時の歴史的な出来事 (例：ピラトのユダヤ総督在任期間、カヤパの大祭司在任期間) との整合性が比較的高い。特に、ルカによる福音書3章1節では、ヨハネがバプテスマを始めたのが「ティベリウス皇帝の治世の15年」と記されており、これはAD28年または29年に当たると考えられています。イエスはヨハネからバプテスマを受けた後、宣教を開始したとされているため、十字架刑がAD30年頃であった可能性が出てきます。AD30年の過越の祭りは、ユダヤ暦ニサンの月15日にあたり、グレゴリオ暦では4月7日(金曜日)にあたります。

    -   \[GPT-4o\] ルカの福音書によれば、ヨハネの洗礼活動はティベリウス帝の治世15年目に始まったとされています（ルカ3:1-3）。ティベリウス帝はAD 14に即位したため、15年目はAD 28-29に該当します。イエスの公生涯がこの頃に始まったと考えられます。イエスの公生涯が約3年だったとすると、AD 28-29に始まり、AD 30に十字架に架けられたと計算されます。AD 30の過越の祭りが金曜日に当たるため、イエスが金曜日に十字架に架けられたという伝統的な考えと一致します。

    -   春分のあとの満月の日：紀元28年: 4月17日、紀元29年: 4月6日、紀元30年: 4月6日、紀元31年: 4月25日、紀元32年: 4月17日紀元33年: 4月6日（個人的には、紀元30年: 4月6日が一番可能性が高いと考えてている。）

-   とうごまや、いちじくが、虫などに食われて、急に枯れることはあるのでしょうか。

    -   \[Gemini-1.5-Pro\] はい、トウゴマもイチジクも、虫害によって急に枯れることがあります。

        トウゴマの場合:

        -   主な害虫: ワタノメイガ、ハスモンヨトウ、フタテンチビヨコバイなど

        -   被害状況: これらの害虫は、葉や茎を食害したり、吸汁したりすることで、植物を弱らせます。大量発生すると、短期間で枯死することもあります。

        イチジクの場合:

        -   主な害虫: カミキリムシ類（ゴマダラカミキリ、キボシカミキリなど）、クワカミキリ、イチジクヒトリモドキなど

        -   被害状況: カミキリムシ類の幼虫は、幹や枝に侵入して内部を食害するため、樹勢が著しく衰え、枯死に至ることもあります。イチジクヒトリモドキは、葉を大量に食害し、樹勢を弱らせます。

-   「神を信じなさい」「心に疑わないで信じる」

    -   ~22~καὶ ἀποκριθεὶς ὁ Ἰησοῦς λέγει αὐτοῖς· ἔχετε πίστιν θεοῦ. ~23~ἀμὴν λέγω ὑμῖν ὅτι ὃς ἂν εἴπῃ τῷ ὄρει τούτῳ· ἄρθητι καὶ βλήθητι εἰς τὴν θάλασσαν, καὶ μὴ διακριθῇ ἐν τῇ καρδίᾳ αὐτοῦ ἀλλὰ πιστεύῃ ὅτι ὃ λαλεῖ γίνεται, ἔσται αὐτῷ. 

    -   神を信じるとは、信じるとは、一体どういうことだろう。

-   「ゆるし」ἀφίημι: i. to send away, ii. to permit, allow, not to hinder, to give up a thing to a person, iii. to leave, go way from one = 「いいよ」「いいことにしてあげなさい」ぐらいな感じ。

    -   ~24~διὰ τοῦτο λέγω ὑμῖν, πάντα ὅσα προσεύχεσθε καὶ αἰτεῖσθε, πιστεύετε ὅτι ἐλάβετε, καὶ ἔσται ὑμῖν. ~25~Καὶ ὅταν στήκετε προσευχόμενοι, ἀφίετε εἴ τι ἔχετε κατά τινος, ἵνα καὶ ὁ πατὴρ ὑμῶν ὁ ἐν τοῖς οὐρανοῖς ἀφῇ ὑμῖν τὰ παραπτώματα ὑμῶν.

    -   ἀφίημι: The KJV translates Strong's G863 in the following manner: leave (52x), forgive (47x), suffer (14x), let (8x), forsake (6x), let alone (6x), miscellaneous (13x)

        -   Mark 1:18, 20, 31, 34, 2:5, 7, 9, 10, 11, 3:28, 4:12, 36, 6:19, 37, 7:8, 12, 27, 8:13, 10:14, 29, 11:6, 16, 25, 12:12, 19, 20, 22, 13:2, 34, 14:6, 50, 15:36, 37

    -   παραπτώματα: i. to fall beside or near something, ii. a lapse or deviation from truth and uprightness = 「ちょっとそれてしまう」あやまちまで強くない。

### 記録

-   日時：2024年9月26日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）2名

### 問いについて

1.  背景を確認しましょう。どのようなときのことですか。（12）

    -   12 翌日、彼らがベタニヤから出かけてきたとき、イエスは空腹をおぼえられた。

    -   \[DQ\] 朝食は摂らなかったのでしょうか。弟子たちは空腹を覚えなかったのでしょうか。

    -   \[A\] 翌日とは、エルサレム入城の次の日である。入城のあと、「11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。」とあり、この節につながっている。ベタニヤは、エルサレムから3km 程度とされているので、当時としては、それほど、遠い距離ではなかったろう。1節に登場する、ベテファゲは、いちじくの家または、未熟ないちじくの家を意味するので、このあたりには、いちじくの木が何本も生えていたのだろう。

    -   \[A\] マタイでは、宮きよめを先に記し、そのあとで、「21:18 朝はやく都に帰るとき、イエスは空腹をおぼえられた。」と始めている。朝早くなのだろう。朝食はとらなかったと思われる。ただ、イエスだけが、空腹を覚えたとの記述は、少し奇異に感じられる。弟子たちは、空腹を覚えなかったのだろうか。

    -   \[Q\] 朝だと思われるが、この日は、昼食はどうするつもりだったのでしょうか。ほしいちじくや、ほしぶどうなど、何ももっていなかったのでしょうか。弟子たちはどうするつもりだったのでしょうか。

    -   \[A\] いろいろと不自然。おそらく、空腹は、それほど重要ではない。よくは、わからないが。

    -   このあとに、挟まる形で、宮きよめの記事がある。時系列が、このままであるとすると、この日は、イエスは、かなり癇癪持ち、ご機嫌ななめであったように見える。十分な理解をしたかどうかは別として、このエピソードが語られた時、イエスがご機嫌ななめとして、この記事を挿入し、宮きよめの記事を入れ、あとから、弟子たちを教えられた記事を入れたのかもしれない。不自然に感じされる記事ではあるが、意図的にそうしたのかもしれない。

    -   \[参考\] 空腹について（πεινάω：i. to hunger, be hungry a. to suffer want, b. to be needy, ii. metaph. to crave ardently, to seek with eager desire）

        -   マルコ8:3 もし、彼らを空腹のまま家に帰らせるなら、途中で弱り切ってしまうであろう。それに、なかには遠くからきている者もある」。（マタイ15:32）

        -   マタイ4:2 そして、四十日四十夜、断食をし、そののち空腹になられた。（ルカ4:2）

        -   マタイ5:6 義に飢えかわいている人たちは、さいわいである、／彼らは飽き足りるようになるであろう。

        -   マタイ12:1 そのころ、ある安息日に、イエスは麦畑の中を通られた。すると弟子たちは、空腹であったので、穂を摘んで食べはじめた。（マルコ2:23-28 においても空腹が想定されている）

        -   マタイ25:35,37,42,44 わたしが空腹のとき

        -   ルカ1:53 飢えている者を良いもので飽かせ、／富んでいる者を空腹のまま帰らせなさいます。（聖書協会共同訳では何も持たせずに追い払い）

2.  イエスは、どのようなことをしますか。（13-14）

    -   13 そして、葉の茂ったいちじくの木を遠くからごらんになって、その木に何かありはしないかと近寄られたが、葉のほかは何も見当らなかった。いちじくの季節でなかったからである。14 そこで、イエスはその木にむかって、「今から後いつまでも、おまえの実を食べる者がないように」と言われた。弟子たちはこれを聞いていた。

    -   \[DQ\] いちじくとはどのような木ですか。

        -   \[A\] 日本国語大辞典（精選版）いちじく【無花果・映日果】〘名〙

            ①クワ科の落葉小高木。小アジア原産で江戸初期に渡来し、各地で栽植される。高さ二～五メートル。樹皮は褐色。多く分枝し、幹、枝は湾曲する。葉は掌状に三～五裂し、裏面に細毛をもつ。春から夏に倒卵形で肉厚の花嚢をつける。花嚢は中に無数の白い小さな花をもち、暗紫色か白緑色に熟し、食用となる。乾した茎、葉、実は駆虫、緩下剤、下痢止めになり、液汁は疣いぼ、うおのめなどに効くという。とうがき。ほろろいし。《季・秋》

            ②植物「いぬびわ（犬枇杷）」の異名。〔大和本草（1709）〕

        -   過越の季節は4月の半ばごろ、日陰の場所にあるいちじくの木は、3月早々には葉をつけるが、5月の終わりか、6月にならないと実をつけない。イエスが十字架に架けられる年として、有力とされるAD30年説を用いると、過越の日は、4月7日（金）、もし、この記事が月曜日であるなら、4月3日（月）となり、おそらく、いちじくで実をならしているものは非常に少ないと思われる。

        -   6月ごろ初生りのいちじく、8,9月に秋いちじく、年に二三回収穫された。

    -   \[DQ\] 実がないのは、いちじくの季節ではなかったからと書いてありますが、イエスは、それを知らなかったのでしょうか。

        -   \[Q\] マタイには、この記述がありません（省略してあります）が、それは、なぜだと思いますか。

        -   \[参照\] マルコ13:28-32、28 いちじくの木からこの譬を学びなさい。その枝が柔らかになり、葉が出るようになると、夏の近いことがわかる。（マタイ24:32-35、ルカ21:29-33）

        -   ここには、実がなる時期については書かれていないし、このいちじくを呪ったときに弟子たちに教えてもらったという可能性を否定はできないが、ここでは「あなたがたがそう言っている」という言い方はせず、一般的に、このような記述があるということは、イエスは、十分知識を持っていたのだろう。いちじくは、パレスチナでは一般的な植物だから。

    -   \[DQ\] イエスは実のないいちじくの木に対してどのように言われますか。

        -   \[A\] 「今から後いつまでも、おまえの実を食べる者がないように」

            -   マタイは「そこでその木にむかって、「今から後いつまでも、おまえには実がならないように」と言われた。すると、いちじくの木はたちまち枯れた。」

        -   かなり厳しい言葉である。イエスは、どのような気持ちで、このようなことを言ったのだろうか。宮きよめの前に、このようなことを記載した可能性もあるが、ほかにもあるのだろう。あとで、祈りのことを語っていることからして、もう少し、他の意味もあると思われる。何らかの実がならないことへの失望であろうか。自分が十分、使命を果たせなかったとの意識が入っているか。

        -   悪魔の試みのときも含め、自分のためには、奇跡的な方法を使われないイエスの呪い、魔術的なとも言える力によって、いちじくが枯れてしまったように見える。（マルコでは翌日、マタイではたちまち枯れている。）

    -   \[DQ\] 役に立たないものは滅ぼされるということでしょうか。

        -   そのようにも取れる。これに関しては、ルカ13:6-9 参照。

        -   空腹のときに食べさせるというのは、素晴らしいこと。（マタイ25）

3.  このいちじくは、どうなりますか。（20,21）

    -   20 朝はやく道をとおっていると、彼らは先のいちじくが根元から枯れているのを見た。21 そこで、ペテロは思い出してイエスに言った、「先生、ごらんなさい。あなたがのろわれたいちじくが、枯れています」。

    -   \[DQ\] ペテロはなぜこのように言ったのでしょうか。

        -   \[A\] 驚いたから？イエスの行動の意味をいつも知りたいから？

    -   朝早くとあるが、翌日とは書かれていない。ペテロは、まず、思い出してと言い、イエスはいちじくを呪ったと認識している。根本から枯れているというのは、「今から後いつまでも、おまえの実を食べる者がないように」の、完全な実現。

    -   \[DQ\] 具体的には、何が起こったのでしょうか。

    -   \[A\] 一般的には、「葉の茂ったいちじくの木」が、急に枯れるというのは、現実的ではない。しかし、この会話から、それが奇跡だとは、言っていないようである。

        -   虫害は可能性あり：

            -   主な害虫：カミキリムシ類（ゴマダラカミキリ、キボシカミキリなど）、クワカミキリ、イチジクヒトリモドキなど

            -   カミキリムシ類の幼虫は、幹や枝に侵入して内部を食害するため、樹勢が著しく衰え、枯死に至ることもあります。イチジクヒトリモドキは、葉を大量に食害し、樹勢を弱らせます。

        -   詩篇 78:47 神はひょうをもって彼らのぶどうの木を枯らし、／霜をもって彼らのいちじく桑の木を枯らされた。

        -   詩篇105:33 主は彼らのぶどうの木と、いちじくの木とを撃ち、／彼らの国のもろもろの木を折り砕かれた。

        -   アモス書4:9 「わたしは立ち枯れと腐り穂とをもって／あなたがたを撃ち、／あなたがたの園と、ぶどう畑とを荒した。いちじくの木とオリブの木とは、いなごが食った。それでも、あなたがたはわたしに帰らなかった」と／主は言われる。

4.  いちじくのことから、イエスは弟子たちにどのようなことを教えていますか。（22-24）

    -   22 イエスは答えて言われた、「神を信じなさい。23 よく聞いておくがよい。だれでもこの山に、動き出して、海の中にはいれと言い、その言ったことは必ず成ると、心に疑わないで信じるなら、そのとおりに成るであろう。24 そこで、あなたがたに言うが、なんでも祈り求めることは、すでにかなえられたと信じなさい。そうすれば、そのとおりになるであろう。

    -   \[A\]「心に疑わないで神を信じる」ことを、まずは、説いている。そして、「祈り求めることは、すでにかなえられたと信じる」ことでもある。しかし、このことは、神をどのような方と捉えるかによっては、課題も生じる。

    -   弟子たちを教える、通常モードに戻っている。特殊なことから、重要なこと、そして、一番伝えたいことへと深くなっていくのは、イエスの教えかたの特徴のようにも見える。

    -   \[DQ\] 山に『立ち上がって、海に飛び込め』といえば本当に、そのとおりになるのでしょうか。

        -   \[A\] 祈りの力というより、神の力を示しているのだろう。だから、「神を信じなさい」と言っている。

        -   「山」は困難の象徴か、また、オリーブ山からは、死海を望むことができたと言われている。'

    -   \[DQ\] すでに得られたと信じればよいのでしょうか。

        -   \[A\] 信じることなしには、かなえられないのだろう。しかし、何を信じるかがたいせつ。神様がそのことをお望みなら、実現するのだろう。
        -   おそらく、そう単純ではない。神を信じるとは、神様に信頼することであり、それは、神様がどのような方かをよく知っていることとも関係していると思われる。イエスにとっては、日々の交わりから、明らかなのだろうが、一般的にはそうではない。

5.  祈りとゆるしにはどのような関係があるのでしょか。(25,(26))

    -   25 また立って祈るとき、だれかに対して、何か恨み事があるならば、ゆるしてやりなさい。そうすれば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださるであろう。26 〔もしゆるさないならば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださらないであろう〕」。

    -   \[DQ\] なぜ、ゆるしのことが出てくるのでしょうか。

    -   \[A\] わたし（イエス）のようなことをしてはいけないよと言っているのだろうか。

    -   \[A\] 最初の、いちじくのことにもどり、勝手な解釈をしてはいけないことを戒めているのだろう。また、神を信じることとは、神様との関係を確認すること、神様に赦していただいている存在であることの認識だろうか。

    -   「ゆるし」とひらがなで書かれているが、非常に一般的な、アフィエーミ「いいことにしてあげなさい」ぐらいの意味と捉えたほうがよいのかもしれない。「あやまち」パラプトーマも「ちょっとそれてしまう」という軽い意味にもとれる。ずれが本質と理解することもできないことはないが。日常的な課題を問うているようにも見える。

    -   \[参照\] 立って祈る

        -   ネヘミヤ記9:4 その時エシュア、バニ、カデミエル、シバニヤ、ブンニ、セレビヤ、バニ、ケナニらはレビびとの台の上に立ち、大声をあげて、その神、主に呼ばわった。

        -   エレミヤ書18:20 悪をもって善に報いるべきでしょうか。しかもなお彼らはわたしの命を取ろうとして／穴を掘りました。わたしがあなたの前に立って、／彼らのことを良く言い、／あなたの憤りを止めようとしたのを／覚えてください。

        -   マタイ6:5 また祈る時には、偽善者たちのようにするな。彼らは人に見せようとして、会堂や大通りのつじに立って祈ることを好む。よく言っておくが、彼らはその報いを受けてしまっている。

        -   ルカ18:11-14 パリサイ人は立って、ひとりでこう祈った、『神よ、わたしはほかの人たちのような貪欲な者、不正な者、姦淫をする者ではなく、また、この取税人のような人間でもないことを感謝します。12 わたしは一週に二度断食しており、全収入の十分の一をささげています』。13 ところが、取税人は遠く離れて立ち、目を天にむけようともしないで、胸を打ちながら言った、『神様、罪人のわたしをおゆるしください』と。14 あなたがたに言っておく。神に義とされて自分の家に帰ったのは、この取税人であって、あのパリサイ人ではなかった。おおよそ、自分を高くする者は低くされ、自分を低くする者は高くされるであろう」。

    -   \[参照\] マタイ6:12 わたしたちに負債のある者をゆるしましたように、／わたしたちの負債をもおゆるしください。

6.  あなたは、このいちじくの話から何を学びますか。

    -   「宮きよめ」の挿入に問題があったのかもしれない。それが、ペテロなのかどうかは、不明だが。すくなくとも、間違った理解をしないように、最後に、神様との関係に戻っている。

    -   実りのない、イスラエルに対する神のさばきとする解釈もある。そのようなイメージがイエスにもあったかもしれない。

    -   このいちじくを枯らす記事は、不自然に感じる。宮きよめと連動し、ユダヤや、エルサレム付近の人々を守るために、そこでの出来事を書かないために、起こっている不自然さをぬぐうためであるかもしれない。いずれにしても、最後には、祈りと、神への信頼と、ゆるしというイエスの本来的な教えにつなげている。

### メモ

-   ルカ13:6-9 は、いちじくの話に関し、実がならないと、すぐイエスに呪われて、根こそぎ、枯れてしまう、すなわち、滅びてしまうのかという問いにこたえるための、物語であるように思われる。ルカが見つけてきたのか。イエスの性質から、このようなことも言われたとしているのか、祈りの教えから、こちらに導かれたのか。悔い改めなければ滅びるというメッセージのあとに置かれており、それは、自然だとも言える。
-   個人的には、この地域の信仰者を守るため、ユダヤやエルサレムでの活動を書かなかったしわ寄せが背景にあったので、宮きよめの直前に連動させてここに置かれているのではないかと思うが、実際に、このようなこともあったのかもしれない。すなわち、イエスが空腹のゆえに、不機嫌になり、それがゆえに、乱暴なこともしてしまう。イエスは、「食をむさぼる者、大酒を飲む者（マタイ11:18,19、ルカ7:33,34）」だとも言われており、あまり、聖人君主にしないほうが良いのかもしれない。それを、弟子たちは眺めている。同時に、そうであっても、不機嫌ではおわらずに、かならず、大切なことを教えてくださるのが、イエスだったのだろう。最後の部分は、罪の赦しのように大げさに考えず、身近なことと結びつけたほうが良いかもしれない。神様との信頼関係こそが大切なのだろう。
-   祈りについて、または、願いの実現について、簡単には、語れない。ここでは、最初に、「神を信じなさい」とはじめ、「よく聞いておくがよい。」という重要なことを語るときの、慣用句ではじめ、まずは、神に信頼することから、「だれでもこの山に、動き出して、海の中にはいれと言い、その言ったことは必ず成ると、心に疑わないで信じるなら、そのとおりに成るであろう。」と続ける。おそらく、眼の前に、オリーブ山があり、死海が見えているかどうかは別として、その光景も想像できる場所だったのだろう。つづけて「24 そこで、あなたがたに言うが、なんでも祈り求めることは、すでにかなえられたと信じなさい。そうすれば、そのとおりになるであろう。」というが、危険も伴う。神様への信頼、そして、神様が何を望まれるかが理解できていなければ、利己的に、祈りを使ってしまう可能性もあるからである。ここで、「25 また立って祈るとき、だれかに対して、何か恨み事があるならば、ゆるしてやりなさい。そうすれば、天にいますあなたがたの父も、あなたがたのあやまちを、ゆるしてくださるであろう。」と日常に引き戻すように、ゆるしについて語っている。ここでは、恨み事とあるので、それはなにかと考えてしまうが、「だれかに対して何らかのわだかまり (anything you have against someone)」ぐらいの意味で、それを、許容（προσεύχομαι）しなさいとしているように見える。つづけて「あなたがたのあやまち（παράπτωμα）」とあるものも、英語では、trespasses とも訳されている。それが、神様のご性質なのだろう。常に、小さな過誤も、ゆるしてくださっているということなのだろう。

## 11:27-33 権威についての問答

> 27 彼らはまたエルサレムにきた。そして、イエスが宮の内を歩いておられると、祭司長、律法学者、長老たちが、みもとにきて言った、28 「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。29 そこで、イエスは彼らに言われた、「一つだけ尋ねよう。それに答えてほしい。そうしたら、何の権威によって、わたしがこれらの事をするのか、あなたがたに言おう。30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。31 すると、彼らは互に論じて言った、「もし天からだと言えば、では、なぜ彼を信じなかったのか、とイエスは言うだろう。32 しかし、人からだと言えば......」。彼らは群衆を恐れていた。人々が皆、ヨハネを預言者だとほんとうに思っていたからである。33 それで彼らは「わたしたちにはわかりません」と答えた。するとイエスは言われた、「わたしも何の権威によってこれらの事をするのか、あなたがたに言うまい」。

### マタイ 21:23-27

> 23 イエスが宮にはいられたとき、祭司長たちや民の長老たちが、その教えておられる所にきて言った、「何の権威によって、これらの事をするのですか。だれが、そうする権威を授けたのですか」。24 そこでイエスは彼らに言われた、「わたしも一つだけ尋ねよう。あなたがたがそれに答えてくれたなら、わたしも、何の権威によってこれらの事をするのか、あなたがたに言おう。25 ヨハネのバプテスマはどこからきたのであったか。天からであったか、人からであったか」。すると、彼らは互に論じて言った、「もし天からだと言えば、では、なぜ彼を信じなかったのか、とイエスは言うだろう。26 しかし、もし人からだと言えば、群衆が恐ろしい。人々がみなヨハネを預言者と思っているのだから」。27 そこで彼らは、「わたしたちにはわかりません」と答えた。すると、イエスが言われた、「わたしも何の権威によってこれらの事をするのか、あなたがたに言うまい。

### ルカ 20:1-8

> 1 ある日、イエスが宮で人々に教え、福音を宣べておられると、祭司長や律法学者たちが、長老たちと共に近寄ってきて、2 イエスに言った、「何の権威によってこれらの事をするのですか。そうする権威をあなたに与えたのはだれですか、わたしたちに言ってください」。3 そこで、イエスは答えて言われた、「わたしも、ひと言たずねよう。それに答えてほしい。4 ヨハネのバプテスマは、天からであったか、人からであったか」。5 彼らは互に論じて言った、「もし天からだと言えば、では、なぜ彼を信じなかったのか、とイエスは言うだろう。6 しかし、もし人からだと言えば、民衆はみな、ヨハネを預言者だと信じているから、わたしたちを石で打つだろう」。7 それで彼らは「どこからか、知りません」と答えた。8 イエスはこれに対して言われた、「わたしも何の権威によってこれらの事をするのか、あなたがたに言うまい」。

[マルコによる福音書11章27-33節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark11_27-33.pdf)

### 問い

1.  背景を復習しましょう。これまで、エルサレムの宮ではどのようなことがありましたか。（15-19）

2.  祭司長、律法学者、長老たちは、なぜこのような質問をするのでしょうか。(27,28)

3.  イエスはどのように答えますか。（29,30）

4.  祭司長、律法学者、長老たちは、どのようなことを考えますか。（31-33）

5.  祭司長、律法学者、長老たちは、なぜバプテスマのヨハネを受け入れなかったのでしょうか。

6.  イエスがこの人たちに問うていることは何なのでしょうか。

### 参照

-   受難週のエルサレムの地図 \[[The Passion Week in Jerusalem](https://www.seektheoldpaths.com/Maps/113.jpg)\]

-   ヘロデ神殿　\[[Herod's Temple](https://www.seektheoldpaths.com/Maps/126a.jpg)\]

    -   The Temple at Jerusalem in Jesus' Day, Clyde W. Votaw \[[pdf](https://www.journals.uchicago.edu/doi/pdf/10.1086/473359)\]

    -   2つの回廊、ソロモンの回廊（東）と王の回廊（南）コリント式の約12メートルの高さの円柱で、王の回廊のものは、直径二メートル、162本の柱（バークレイ）

-   \[参考\] ストア学派（ゼノン BC343-262）は、ストア・ポイキレ（Ποικίλη στοά (Stoa Poikile) Painted Portico 柱廊）を歩きながら教えた。

-   \[正統なラビ\] 最低三人のラビの前で、恩師のラビによって按手される必要がある。（新聖書注解：マタイ：増田誉雄）

-   議員・役人たちは、イエスをどう見ていたか。

    -   \[参考\] 15:43 アリマタヤのヨセフが大胆にもピラトの所へ行き、イエスのからだの引取りかたを願った。彼は地位の高い議員であって、彼自身、神の国を待ち望んでいる人であった。

    -   \[参考\] ヨハネ7:25,26 さて、エルサレムのある人たちが言った、「この人は人々が殺そうと思っている者ではないか。26 見よ、彼は公然と語っているのに、人々はこれに対して何も言わない。役人たちは、この人がキリストであることを、ほんとうに知っているのではなかろうか。

    -   \[参考\] ヨハネ7:45-51 さて、下役どもが祭司長たちやパリサイ人たちのところに帰ってきたので、彼らはその下役どもに言った、「なぜ、あの人を連れてこなかったのか」。46 下役どもは答えた、「この人の語るように語った者は、これまでにありませんでした」。47 パリサイ人たちが彼らに答えた、「あなたがたまでが、だまされているのではないか。48 役人たちやパリサイ人たちの中で、ひとりでも彼を信じた者があっただろうか。49 律法をわきまえないこの群衆は、のろわれている」。50 彼らの中のひとりで、以前にイエスに会いにきたことのあるニコデモが、彼らに言った、51 「わたしたちの律法によれば、まずその人の言い分を聞き、その人のしたことを知った上でなければ、さばくことをしないのではないか」。52 彼らは答えて言った、「あなたもガリラヤ出なのか。よく調べてみなさい、ガリラヤからは預言者が出るものではないことが、わかるだろう」。

    -   \[参考\] ヨハネ12:42,43 しかし、役人たちの中にも、イエスを信じた者が多かったが、パリサイ人をはばかって、告白はしなかった。会堂から追い出されるのを恐れていたのである。43 彼らは神のほまれよりも、人のほまれを好んだからである。

        -   \[参考\] ヨハネ18:15-18 シモン・ペテロともうひとりの弟子とが、イエスについて行った。この弟子は大祭司の知り合いであったので、イエスと一緒に大祭司の中庭にはいった。16 しかし、ペテロは外で戸口に立っていた。すると大祭司の知り合いであるその弟子が、外に出て行って門番の女に話し、ペテロを内に入れてやった。17 すると、この門番の女がペテロに言った、「あなたも、あの人の弟子のひとりではありませんか」。ペテロは「いや、そうではない」と答えた。18 僕や下役どもは、寒い時であったので、炭火をおこし、そこに立ってあたっていた。ペテロもまた彼らに交じり、立ってあたっていた。

### 記録

-   日時：2024年10月3日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）1名

### 問いについて

1.  背景を復習しましょう。これまで、エルサレムの宮ではどのようなことがありましたか。（15-19）

    -   マルコ：エルサレム入城後は、中を見て回り、宮きよめのみ。

        -   （入城）「ホサナ、／主の御名によってきたる者に、祝福あれ。10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。11 こうしてイエスはエルサレムに着き、宮にはいられた。そして、すべてのものを見まわった後、もはや時もおそくなっていたので、十二弟子と共にベタニヤに出て行かれた。

        -   （宮きよめ）11:15-17 15 それから、彼らはエルサレムにきた。イエスは宮に入り、宮の庭で売り買いしていた人々を追い出しはじめ、両替人の台や、はとを売る者の腰掛をくつがえし、16 また器ものを持って宮の庭を通り抜けるのをお許しにならなかった。17そして、彼らに教えて言われた、「『わたしの家は、すべての国民の祈の家ととなえらるべきである』と書いてあるではないか。それだのに、あなたがたはそれを強盗の巣にしてしまった」

            -   追い出し始めの、「はじめ」が気になる。完璧に、なくしたのではないのかもしれない。

            -   いちじくの挿入記事でも「いのり」について教えている。さらに赦しについての述べられている。主の御心を聞くことこそが、たいせつだと言っているのかもしれない。

        -   27 彼らはまたエルサレムにきた。そして、イエスが宮の内を歩いておられると、祭司長、律法学者、長老たちが、みもとにきて言った、

            -   教えていたことに対して問われているのかもしれない。正式な教師ではない。ガリラヤでは巡回教師。預言者であれば、おそらく、問題はないだろうが、それは、サンヘドリンとはぶつかるであろう。

    -   マタイ21（直前には、エルサレム入城、いちじくの木を呪う）：「ダビデの子にホサナ」との言葉をもってエルサレム入城、直後に、宮きよめ。以下が追加されている。

        -   14 そのとき宮の庭で、盲人や足なえがみもとにきたので、彼らをおいやしになった。15 しかし、祭司長、律法学者たちは、イエスがなされた不思議なわざを見、また宮の庭で「ダビデの子に、ホサナ」と叫んでいる子供たちを見て立腹し、16 イエスに言った、「あの子たちが何を言っているのか、お聞きですか」。イエスは彼らに言われた、「そうだ、聞いている。あなたがたは『幼な子、乳のみ子たちの口にさんびを備えられた』とあるのを読んだことがないのか」。

    -   ルカ19（直前には、エルサレム入城、都の陥落・崩壊、宮きよめ、その直後が権威についての問答）：

        -   38 「主の御名によってきたる王に、／祝福あれ。天には平和、／いと高きところには栄光あれ」。39 ところが、群衆の中にいたあるパリサイ人たちがイエスに言った、「先生、あなたの弟子たちをおしかり下さい」。40 答えて言われた、「あなたがたに言うが、もしこの人たちが黙れば、石が叫ぶであろう」。との声とともに、エルサレム入城

        -   47 イエスは毎日、宮で教えておられた。祭司長、律法学者また民衆の重立った者たちはイエスを殺そうと思っていたが、48 民衆がみな熱心にイエスに耳を傾けていたので、手のくだしようがなかった。

    -   ヨハネ12（参考：エルサレム入城、ギリシャ人、イエスに会いに来る、人の子は上げられる、イエスを信じない者たち、イエスの言葉による裁き、弟子の足を洗うにつながる。月曜日から木曜日までほとんど記されていない。）

2.  祭司長、律法学者、長老たちは、なぜこのような質問をするのでしょうか。(27,28)

    -   27 彼らはまたエルサレムにきた。そして、イエスが宮の内を歩いておられると、祭司長、律法学者、長老たちが、みもとにきて言った、28 「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。

    -   \[DQ\] 「祭司長、律法学者、長老たち」とはどのような人たちですか。

        -   οἱ ἀρχιερεῖς (ἀρχιερεύς: chief priest, high priest) καὶ οἱ γραμματεῖς (γραμματεύς: a clerk, scribe, esp.a public servant, secretary, recorder, whose office and influence differed in different states, in the Bible, a man learned in the Mosaic law and in the sacred writings, an interpreter, teacher.) καὶ οἱ πρεσβύτεροι (πρεσβύτερος: i. elder, of age, ii. a term of rank or office, among the Jews, members of the great council or Sanhedrin (because in early times the rulers of the people, judges, etc., were selected from elderly men)) 

        -   いずれも複数で書かれている。祭司長は退任しても、祭司長と言われていたようだが、それでも、異常に感じる。集合的に、最高議会をあらわし、そこから、派遣された人たちだろうか。

        -   書記、ラビ、長老たち、サンヘドリン（最高議会）からの代理人？

    -   \[DQ\] イエスが何をしているときに、この人たちは質問をしますか。

        -   \[A\] 「イエスが宮の内を歩いておられると」とあるが、これは、おそらく、教えておられた時なのだろう。（マタイ21:23a, ルカ20:1）スコラ（柱廊）

            -   マタイ21:23 イエスが宮にはいられたとき、祭司長たちや民の長老たちが、その教えておられる所にきて言った、

            -   ルカ20:1 1 ある日、イエスが宮で人々に教え、福音を宣べておられると、祭司長や律法学者たちが、長老たちと共に近寄ってきて、

            -   歩きながら教えるのが通常。

    -   \[DQ\] 「これらの事」とは何を指しているのでしょうか。

        -   \[A\] 宮きよめをさすと考えるのが自然。しかし、この時、どのような状況であったかは書かれておらず不明。

            -   15 それから、彼らはエルサレムにきた。イエスは宮に入り、宮の庭で売り買いしていた人々を追い出しはじめ、両替人の台や、はとを売る者の腰掛をくつがえし、16 また器ものを持って宮の庭を通り抜けるのをお許しにならなかった。

        -   マルコでは、宮きよめ以外何もしてない。弟子たちを引き連れて歩き回っているのは目立ったかもしれないが。

    -   \[DQ\] どのような答えが想定されているのでしょうか。

        -   \[A\] 神殿は祈りをする場所で売り買いはよくない。① 自分の判断（人から）⇒だれがその権威を授けたか ②神は現状を望んでおられない（神（天）から）⇒神の神殿での騒ぎを神は喜ばれるのか。

3.  イエスはどのように答えますか。（29,30）

    -   29 そこで、イエスは彼らに言われた、「一つだけ尋ねよう。それに答えてほしい。そうしたら、何の権威によって、わたしがこれらの事をするのか、あなたがたに言おう。30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。

    -   \[A\] ヨハネのバプテスマは天からか、人からか？

    -   \[DQ\] バプテスマのヨハネについて知っていることを上げてみましょう。活動、教え、その後。マルコから。

        -   マルコ1:1-8 洗礼者ヨハネ、悔い改めの洗礼を述べ伝える。(マタイ3:1-12, ルカ3:1-9, 15-17, ヨハネ1:19-28)

            -   1:4 罪のゆるしを得させる悔改めのバプテスマを宣べ伝えていた。

            -   1:7 わたしよりも力のあるかたが、あとからおいでになる。

            -   1:6 このヨハネは、らくだの毛ごろもを身にまとい、腰に皮の帯をしめ、いなごと野蜜とを食物としていた。（これは何を意味しているのでしょう）もともとは、祭司の家系？（ルカ1）

        -   マルコ1:9-11 イエス、洗礼を受ける（マタイ3:13-17, ルカ3:21-22）

        -   マルコ1:14,15 ヨハネが捕えられた後、イエスはガリラヤに行き、神の福音を宣べ伝えて言われた、15 「時は満ちた、神の国は近づいた。悔い改めて福音を信ぜよ」。(マタイ4:12-17, ルカ4:14-15)

        -   マルコ2:18-22 断食についての問答（マタイ9:14-17, ルカ5:33-39）

            -   2:18 ヨハネの弟子とパリサイ人とは、断食をしていた。そこで人々がきて、イエスに言った、「ヨハネの弟子たちとパリサイ人の弟子たちとが断食をしているのに、あなたの弟子たちは、なぜ断食をしないのですか」。

        -   マルコ6:14-29 洗礼者ヨハネ、殺される。（マタイ14:1-12, ルカ9:7-9）

            -   6:14-16 さて、イエスの名が知れわたって、ヘロデ王の耳にはいった。ある人々は「バプテスマのヨハネが、死人の中からよみがえってきたのだ。それで、あのような力が彼のうちに働いているのだ」と言い、15 他の人々は「彼はエリヤだ」と言い、また他の人々は「昔の預言者のような預言者だ」と言った。16 ところが、ヘロデはこれを聞いて、「わたしが首を切ったあのヨハネがよみがえったのだ」と言った。

        -   マルコ8:28 彼らは答えて言った、「バプテスマのヨハネだと、言っています。また、エリヤだと言い、また、預言者のひとりだと言っている者もあります」。（マタイ16:14, ルカ9:19）

        -   マルコ11:30-32 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。31 すると、彼らは互に論じて言った、「もし天からだと言えば、では、なぜ彼を信じなかったのか、とイエスは言うだろう。32 しかし、人からだと言えば......」。彼らは群衆を恐れていた。人々が皆、ヨハネを預言者だとほんとうに思っていたからである。（マタイ21:25,26, ルカ20:4-6）

    -   \[DQ\] なぜ、イエスは、問いに答えないのでしょう。

        -   \[A\] マタイ7:6 聖なるものを犬にやるな。また真珠を豚に投げてやるな。恐らく彼らはそれらを足で踏みつけ、向きなおってあなたがたにかみついてくるであろう。（これが理由だろうか）

        -   \[A\] 良心に問いかけている？

    -   \[DQ\] 答えても良かったのではないでしょうか。

        -   \[参考\] 使徒4:7 そして、そのまん中に使徒たちを立たせて尋問した、「あなたがたは、いったい、なんの権威、また、だれの名によって、このことをしたのか」。4:10 あなたがたご一同も、またイスラエルの人々全体も、知っていてもらいたい。この人が元気になってみんなの前に立っているのは、ひとえに、あなたがたが十字架につけて殺したのを、神が死人の中からよみがえらせたナザレ人イエス・キリストの御名によるのである。

    -   \[DQ\] 「ヨハネのバプテスマ」について、聞いていますが、「バプテスマのヨハネ」とは、どう違うのでしょうか。

        -   \[A\] 人についてではなく、もう少し本質的なことに目を向けるためか。

4.  祭司長、律法学者、長老たちは、どのようなことを考えますか。（31-33）

    -   31 すると、彼らは互に論じて言った、「もし天からだと言えば、では、なぜ彼を信じなかったのか、とイエスは言うだろう。32 しかし、人からだと言えば......」。彼らは群衆を恐れていた。人々が皆、ヨハネを預言者だとほんとうに思っていたからである。33 それで彼らは「わたしたちにはわかりません」と答えた。するとイエスは言われた、「わたしも何の権威によってこれらの事をするのか、あなたがたに言うまい」。

    -   \[A\] 天から：なぜ彼（が自分を指し示していること）を信じなかったのか。人から：群衆は、天から、神から遣わされた預言者だと信じていた。

    -   \[DQ\] このひとたちは、結局どうしますか。

        -   \[A\] 「わたしたちにはわかりません」

        -   \[Rep\] イエス：「わたしも何の権威によってこれらの事をするのか、あなたがたに言うまい」

    -   \[DQ\] 問いの本質は何だったのでしょうか。

        -   \[A\] 真理（神の御心をもとめて）に向き合うかどうか。表面的なことではなく、本質を問うている。

    -   \[DQ\] この人たちは、何を知りたかったのでしょうか。

        -   \[A\] 言葉尻を捉えるだけで、なにかを知りたいわけではなかったのだろうか。

        -   \[A\] 求める気持ちよりも、排除の根拠が欲しかったのだろう。真理を探求することはしない。

    -   \[DQ\] 議員たちは、イエスについてどう見ていたのだろうか。一致した見解を持っていたのだろうか。

        -   \[参考\] 15:43 アリマタヤのヨセフが大胆にもピラトの所へ行き、イエスのからだの引取りかたを願った。彼は地位の高い議員であって、彼自身、神の国を待ち望んでいる人であった。

        -   \[参考\] ヨハネ7:1 そののち、イエスはガリラヤを巡回しておられた。ユダヤ人たちが自分を殺そうとしていたので、ユダヤを巡回しようとはされなかった。

        -   \[参考\] ヨハネ7:25-27, 32, 40-52

        -   \[参考\] ヨハネ12:42,43 しかし、役人（ἄρχων： a ruler, commander, chief, leader）たちの中にも、イエスを信じた者が多かったが、パリサイ人をはばかって、告白はしなかった。会堂から追い出されるのを恐れていたのである。43 彼らは神のほまれよりも、人のほまれを好んだからである。

5.  祭司長、律法学者、長老たちは、なぜバプテスマのヨハネを受け入れなかったのでしょうか。

    -   \[A\] 大きな問題がないと考えていたときに、悔い改めを説いていたからか。

    -   \[A\] 本質的な問い、神からのメッセージとして悔い改めるかどうか。その問いに向き合えない。

    -   自分たちは、神の御心、真理を知っている。少なくとも、群衆とは比較にならない知識をもっている。

    -   真理を探求するのではなく、自分たちがもっている知識で判断しようとする。

    -   自分たちの優越によって、築いてきたものを手放せない。したがって、悔い改めには至れない。

6.  イエスがこの人たちに問うていることは何なのでしょうか。

    -   \[A\] 神の御心（真理）を求めて、それに従う生き方。祈り。

    -   \[A\] 自分の弱さを知り、悔い改めて生きる生き方。

    -   \[A\] 悔い改めて、神の国（神の支配）の中に身を委ねる生き方。

    -   わたしたちにも問うている。単なるレトリックとして、この問いを受け取ってはいけない。

    -   \[DQ\] ヨハネのパプてスマは、人からであったか、天からであったか。

        -   \[A\] ヨハネの問いとまずは、向き合うこと。それは、我々にとって何を意味しているのだろうか。

    -   \[DQ\] イエスはこの問いについてはどう考えていたのでしょうか。

        -   \[A\] 結局のところ、一人ひとりの信仰告白、真理との向き合い方が問われている。

### メモ

-   エルサレム入城から、マルコによる福音著の筆致が変化しているように見える。今回の箇所などは、3つの福音書が非常に似通っている。議論にしっかり向き合っている。いままでの、行動中心、Jesus in Action の記述とは異なるように見える。軽々に判断はできないが、マルコのもとにすでに、共通の伝承があったのかもしれない。

-   何の権威によってこれらのことをするのか。とは、何を聞いているのだろう。答えることが難しい問いに、問いで返すという技術として捉えてはいけないのだろう。文脈からすると、宮きよめ、神殿での礼拝の改革のように見える。本当にそうなのだろうか。もう少し、本質的な問いをしているのかもしれない。なぜ、教えるのか。なぜ、いやしなどの行為をおこなうのか。

-   この前の、宮きよめも、いちじくも、祈りについて教えている。この権威についての箇所も、結局、謙虚に、神様のみこころを求めることを教えているのか。祭司長、律法学者、長老たちには、まさに、御心に聴く部分が欠けていたと言っているのだろうか。おそらく、わたしたちも同じだろう。すくなくとも、イエスにとっては、神様との交わりのなかで、神様の御心をもとめる日常がたいせつだったのではと思う。

-   「互いに論じて言った」とあるが、そう簡単に、答えが出なかったのだろうか。正直な思いと、立場上のことなど、さまざまに入り混じっていたのだろうか。

## 12:1-12 「ぶどう園の農夫」のたとえ

> 1 そこでイエスは譬で彼らに語り出された、「ある人がぶどう園を造り、垣をめぐらし、また酒ぶねの穴を掘り、やぐらを立て、それを農夫たちに貸して、旅に出かけた。2 季節になったので、農夫たちのところへ、ひとりの僕を送って、ぶどう園の収穫の分け前を取り立てさせようとした。3 すると、彼らはその僕をつかまえて、袋だだきにし、から手で帰らせた。4 また他の僕を送ったが、その頭をなぐって侮辱した。5 そこでまた他の者を送ったが、今度はそれを殺してしまった。そのほか、なお大ぜいの者を送ったが、彼らを打ったり、殺したりした。6 ここに、もうひとりの者がいた。それは彼の愛子であった。自分の子は敬ってくれるだろうと思って、最後に彼をつかわした。7 すると、農夫たちは『あれはあと取りだ。さあ、これを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と話し合い、8 彼をつかまえて殺し、ぶどう園の外に投げ捨てた。9 このぶどう園の主人は、どうするだろうか。彼は出てきて、農夫たちを殺し、ぶどう園を他の人々に与えるであろう。10 あなたがたは、この聖書の句を読んだことがないのか。『家造りらの捨てた石が／隅のかしら石になった。11 これは主がなされたことで、／わたしたちの目には不思議に見える』」。12 彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。

### マタイ 21:33-46

> 33 もう一つの譬を聞きなさい。ある所に、ひとりの家の主人がいたが、ぶどう園を造り、かきをめぐらし、その中に酒ぶねの穴を掘り、やぐらを立て、それを農夫たちに貸して、旅に出かけた。34 収穫の季節がきたので、その分け前を受け取ろうとして、僕たちを農夫のところへ送った。35 すると、農夫たちは、その僕たちをつかまえて、ひとりを袋だたきにし、ひとりを殺し、もうひとりを石で打ち殺した。36 また別に、前よりも多くの僕たちを送ったが、彼らをも同じようにあしらった。37 しかし、最後に、わたしの子は敬ってくれるだろうと思って、主人はその子を彼らの所につかわした。38 すると農夫たちは、その子を見て互に言った、『あれはあと取りだ。さあ、これを殺して、その財産を手に入れよう』。39 そして彼をつかまえて、ぶどう園の外に引き出して殺した。40 このぶどう園の主人が帰ってきたら、この農夫たちをどうするだろうか」。41 彼らはイエスに言った、「悪人どもを、皆殺しにして、季節ごとに収穫を納めるほかの農夫たちに、そのぶどう園を貸し与えるでしょう」。42 イエスは彼らに言われた、「あなたがたは、聖書でまだ読んだことがないのか、／『家造りらの捨てた石が／隅のかしら石になった。これは主がなされたことで、／わたしたちの目には不思議に見える』。43 それだから、あなたがたに言うが、神の国はあなたがたから取り上げられて、御国にふさわしい実を結ぶような異邦人に与えられるであろう。44 またその石の上に落ちる者は打ち砕かれ、それがだれかの上に落ちかかるなら、その人はこなみじんにされるであろう」。45 祭司長たちやパリサイ人たちがこの譬を聞いたとき、自分たちのことをさして言っておられることを悟ったので、46 イエスを捕えようとしたが、群衆を恐れた。群衆はイエスを預言者だと思っていたからである。

### ルカ 20:9-19

> 9 そこでイエスは次の譬を民衆に語り出された、「ある人がぶどう園を造って農夫たちに貸し、長い旅に出た。10 季節になったので、農夫たちのところへ、ひとりの僕を送って、ぶどう園の収穫の分け前を出させようとした。ところが、農夫たちは、その僕を袋だたきにし、から手で帰らせた。11 そこで彼はもうひとりの僕を送った。彼らはその僕も袋だたきにし、侮辱を加えて、から手で帰らせた。12 そこで更に三人目の者を送ったが、彼らはこの者も、傷を負わせて追い出した。13 ぶどう園の主人は言った、『どうしようか。そうだ、わたしの愛子をつかわそう。これなら、たぶん敬ってくれるだろう』。14 ところが、農夫たちは彼を見ると、『あれはあと取りだ。あれを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と互に話し合い、15 彼をぶどう園の外に追い出して殺した。そのさい、ぶどう園の主人は、彼らをどうするだろうか。16 彼は出てきて、この農夫たちを殺し、ぶどう園を他の人々に与えるであろう」。人々はこれを聞いて、「そんなことがあってはなりません」と言った。17 そこで、イエスは彼らを見つめて言われた、「それでは、／『家造りらの捨てた石が／隅のかしら石になった』／と書いてあるのは、どういうことか。18 すべてその石の上に落ちる者は打ち砕かれ、それがだれかの上に落ちかかるなら、その人はこなみじんにされるであろう」。19 このとき、律法学者たちや祭司長たちはイエスに手をかけようと思ったが、民衆を恐れた。いまの譬が自分たちに当てて語られたのだと、悟ったからである。

[マルコによる福音書12章1-12節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_1-12.pdf)

### 問い

1.  エルサレムではこれまでにどのようなことがありましたか。

2.  1節から8節のたとえの要点をまとめてみましょう。（1-8）

3.  ある人（ぶどう園の主人）、ぶどう園、農夫たち、僕たち、ぶどう園の主人（彼）の息子はそれぞれだれを表していますか。（1-8）

4.  イエスはこのたとえのなかで、どんな預言をしていますか。（9）

5.  旧約聖書からの引用は何をあらわしていますか。(10,11)

6.  イエスは、このたとえで、何を伝えているのでしょうか。（12）

### 参照

-   マタイは、この前に、「二人息子」のたとえ（21:28-32）
    -   あなたがたはどう思うか。ある人にふたりの子があったが、兄のところに行って言った、『子よ、きょう、ぶどう園へ行って働いてくれ』。29 すると彼は『おとうさん、参ります』と答えたが、行かなかった。30 また弟のところにきて同じように言った。彼は『いやです』と答えたが、あとから心を変えて、出かけた。31 このふたりのうち、どちらが父の望みどおりにしたのか」。彼らは言った、「あとの者です」。イエスは言われた、「よく聞きなさい。取税人や遊女は、あなたがたより先に神の国にはいる。32 というのは、ヨハネがあなたがたのところにきて、義の道を説いたのに、あなたがたは彼を信じなかった。ところが、取税人や遊女は彼を信じた。あなたがたはそれを見たのに、あとになっても、心をいれ変えて彼を信じようとしなかった。
-   ぶどう園：
    -   イザヤ5:1-7 わたしはわが愛する者のために、／そのぶどう畑についてのわが愛の歌をうたおう。わが愛する者は土肥えた小山の上に、／一つのぶどう畑をもっていた。2 彼はそれを掘りおこし、石を除き、／それに良いぶどうを植え、／その中に物見やぐらを建て、／またその中に酒ぶねを掘り、／良いぶどうの結ぶのを待ち望んだ。ところが結んだものは野ぶどうであった。3 それで、エルサレムに住む者とユダの人々よ、／どうか、わたしとぶどう畑との間をさばけ。4 わたしが、ぶどう畑になした事のほかに、／何かなすべきことがあるか。わたしは良いぶどうの結ぶのを待ち望んだのに、／どうして野ぶどうを結んだのか。5 それで、わたしが、ぶどう畑になそうとすることを、／あなたがたに告げる。わたしはそのまがきを取り去って、／食い荒されるにまかせ、そのかきをとりこわして、／踏み荒されるにまかせる。6 わたしはこれを荒して、／刈り込むことも、耕すこともせず、／おどろと、いばらとを生えさせ、／また雲に命じて、その上に雨を降らさない。7 万軍の主のぶどう畑はイスラエルの家であり、／主が喜んでそこに植えられた物は、／ユダの人々である。主はこれに公平を望まれたのに、／見よ、流血。正義を望まれたのに、／見よ、叫び。
    -   レビ19:23-25 あなたがたが、かの地にはいって、もろもろのくだものの木を植えるときは、その実はまだ割礼をうけないものと、見なさなければならない。すなわち、それは三年の間あなたがたには、割礼のないものであって、食べてはならない。24 四年目には、そのすべての実を聖なる物とし、それをさんびの供え物として主にささげなければならない。25 しかし五年目には、あなたがたはその実を食べることができるであろう。こうするならば、それはあなたがたのために、多くの実を結ぶであろう。わたしはあなたがたの神、主である。
-   たとえの要点（バークレイ）
    -   譬えの背景
        1.  神の寛大さ、準備が整えられている
        2.  神の信頼：農夫たちを信頼している
        3.  神の忍耐：幾度も送る
        4.  究極的な正義の勝利
    -   譬えにおけるイエス
        1.  イエスは子
        2.  イエスは死ぬ、殺される
        3.  究極的な神への信頼
    -   譬えにおける人間
        1.  神への背き、甘え
        2.  他のものに与えられる
-   詩篇118:22-23 家造りらの捨てた石は／隅のかしら石となった。23 これは主のなされた事で／われらの目には驚くべき事である。
    -   使徒4:11 このイエスこそは『あなたがた家造りらに捨てられたが、隅のかしら石となった石』なのである。
    -   ペテロ前書2:3-9 あなたがたは、主が恵み深いかたであることを、すでに味わい知ったはずである。4 主は、人には捨てられたが、神にとっては選ばれた尊い生ける石である。5 この主のみもとにきて、あなたがたも、それぞれ生ける石となって、霊の家に築き上げられ、聖なる祭司となって、イエス・キリストにより、神によろこばれる霊のいけにえを、ささげなさい。6 聖書にこう書いてある、／「見よ、わたしはシオンに、／選ばれた尊い石、隅のかしら石を置く。それにより頼む者は、／決して、失望に終ることがない」。7 この石は、より頼んでいるあなたがたには尊いものであるが、不信仰な人々には「家造りらの捨てた石で、隅のかしら石となったもの」、8 また「つまずきの石、妨げの岩」である。しかし、彼らがつまずくのは、御言に従わないからであって、彼らは、実は、そうなるように定められていたのである。9 しかし、あなたがたは、選ばれた種族、祭司の国、聖なる国民、神につける民である。それによって、暗やみから驚くべきみ光に招き入れて下さったかたのみわざを、あなたがたが語り伝えるためである。
    -   ローマ9:32-33 なぜであるか。信仰によらないで、行いによって得られるかのように、追い求めたからである。彼らは、つまずきの石につまずいたのである。33 「見よ、わたしはシオンに、／つまずきの石、さまたげの岩を置く。それにより頼む者は、失望に終ることがない」／と書いてあるとおりである。
    -   エペソ2:20 またあなたがたは、使徒たちや預言者たちという土台の上に建てられたものであって、キリスト・イエスご自身が隅のかしら石である。
-   イザヤ8:14,15 主はイスラエルの二つの家には聖所となり、またさまたげの石、つまずきの岩となり、エルサレムの住民には網となり、わなとなる。 15 多くの者はこれにつまずき、かつ倒れ、破られ、わなにかけられ、捕えられる」。
-   ローマ11:22 神の慈愛と峻厳とを見よ。神の峻厳は倒れた者たちに向けられ、神の慈愛は、もしあなたがその慈愛にとどまっているなら、あなたに向けられる。そうでないと、あなたも切り取られるであろう。

### 記録

-   日時：2024年10月10日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）3名

### 問いについて

1.  エルサレムではこれまでにどのようなことがありましたか。

    -   \[A\] エルサレム入城、宮きよめ - 神殿から商人を追い出す（11:18 18 祭司長、律法学者たちはこれを聞いて、どうかしてイエスを殺そうと計った。）、権威についての問答、「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。（11:28）「ヨハネのバプテスマは天からであったか、人からであったか」（30）

    -   \[DQ\] このたとえは誰に向けて語られましたか。（1a）

        -   \[Q\] 「そこでイエスは譬で彼らに語り出された」の「彼ら」とは。

    -   \[DQ\] どのような人たちとのやりとりの後にこのたとえが語られますか。これは、前の権威についての問答からつながっているのでしょうか。

        -   \[A\] 祭司長、律法学者、長老たち。おそらくつながっている。

            -   「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。（11:28）「ヨハネのバプテスマは天からであったか、人からであったか」（11:30）

        -   マタイでは「二人の息子」のたとえ（21:28-32）が挟まり、「32 というのは、ヨハネがあなたがたのところにきて、義の道を説いたのに、あなたがたは彼を信じなかった。ところが、取税人や遊女は彼を信じた。あなたがたはそれを見たのに、あとになっても、心をいれ変えて彼を信じようとしなかった。」と結んでいる。そうであっても、マタイでは、このたとえの中の「どうするだろうか」に「彼ら」が答えている。マルコとルカは、この挿入はない。ただ、ルカでは「そんなことがあってはなりません。」（20:16）の句が挿入されている。

        -   いずれの場合も、前段の「権威についての問答」からつながっており、そこでは、イエスは、答えておられないが、ここでは、ヨハネのバプテスマは、天からか、人からかにも、ここで暗にではあるが、答えている。

2.  1節から8節のたとえの要点をまとめてみましょう。（1-8）

    -   \[DQ\] 登場人物を上げてみましょう。

    -   \[A\] ある人（ぶどう園の主人）、ぶどう園、農夫たち、僕たち、ぶどう園の主人（彼）の息子

    -   \[DQ\] それぞれどのようなことをしたとされていますか。主人、農夫たち。しもべたちの役割は何ですか。

        -   \[Q\] ぶどう園の主人は、ぶどう園にたいして、どのようにしていますか。

            -   ある人（ぶどう園の主人）：ある人がぶどう園を造り、垣をめぐらし、また酒ぶねの穴を掘り、やぐらを立て、それを農夫たちに貸して（ἐκδίδωμι: give out, let out something）、旅に出かけた（ἀποδημέω: to go away into foreign parts, go abroad）。2 季節になった（καιρός： i due measure, ii. a measure of time, a larger or smaller portion of time）ので、農夫たちのところへ、ひとりの僕を送って、ぶどう園の収穫の分け前を取り立てさせようとした。（中略）6 ここに、もうひとりの者がいた。それは彼の愛子であった。自分の子は敬ってくれるだろうと思って、最後に彼をつかわした。

            -   \[参考\] イザヤ5:1-7 わたしはわが愛する者のために、／そのぶどう畑についてのわが愛の歌をうたおう。わが愛する者は土肥えた小山の上に、／一つのぶどう畑をもっていた。2 彼はそれを掘りおこし、石を除き、／それに良いぶどうを植え、／その中に物見やぐらを建て、／またその中に酒ぶねを掘り、／良いぶどうの結ぶのを待ち望んだ。ところが結んだものは野ぶどうであった。

        -   農夫たち：3 すると、彼らはその僕をつかまえて、袋だだきにし、から手で帰らせた。4 また他の僕を送ったが、その頭をなぐって侮辱した。5 そこでまた他の者を送ったが、今度はそれを殺してしまった。そのほか、なお大ぜいの者を送ったが、彼らを打ったり、殺したりした。（中略）7 すると、農夫たちは『あれはあと取りだ。さあ、これを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と話し合い、8 彼をつかまえて殺し、ぶどう園の外に投げ捨てた。

            -   \[Q\] 農夫たちは、なぜこれほどひどいことをするのでしょうか。

                -   3 すると、彼らはその僕をつかまえて、袋だだきにし、から手で帰らせた。

                -   4 また他の僕を送ったが、その頭をなぐって侮辱した。

                -   5 そこでまた他の者を送ったが、今度はそれを殺してしまった。

                -   そのほか、なお大ぜいの者を送ったが、彼らを打ったり、殺したりした。

                -   6 ここに、もうひとりの者がいた。それは彼の愛子であった。自分の子は敬ってくれるだろうと思って、最後に彼をつかわした。7 すると、農夫たちは『あれはあと取りだ。さあ、これを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と話し合い、8 彼をつかまえて殺し、ぶどう園の外に投げ捨てた。

            -   \[A\] 主人について理解できていない。主人が農夫たちのことをよくわかっていない。お人好し。

        -   僕たち：ぶどう園の収穫の分け前を取り立て

            -   \[Q\] 僕の役割は何ですか。

            -   \[A\] 収穫を得る。

        -   ぶどう園の主人（彼）の息子

        -   \[DQ\] なぜ、息子は敬ってくれると考えたのでしょうか。

        -   \[A\] 主には熱心だったのかもしれない。だから、欲はかいても、主には適切に対応してくれると思ったのだろうか。

3.  ある人（ぶどう園の主人）、ぶどう園、農夫たち、僕たち、ぶどう園の主人（彼）の息子はそれぞれだれを表していますか。（1-8）

    -   ある人がぶどう園を造り、垣をめぐらし、また酒ぶねの穴を掘り、やぐらを立て、それを農夫たちに貸して、旅に出かけた。2 季節になったので、農夫たちのところへ、ひとりの僕を送って、ぶどう園の収穫の分け前を取り立てさせようとした。3 すると、彼らはその僕をつかまえて、袋だだきにし、から手で帰らせた。4 また他の僕を送ったが、その頭をなぐって侮辱した。5 そこでまた他の者を送ったが、今度はそれを殺してしまった。そのほか、なお大ぜいの者を送ったが、彼らを打ったり、殺したりした。6 ここに、もうひとりの者がいた。それは彼の愛子であった。自分の子は敬ってくれるだろうと思って、最後に彼をつかわした。7 すると、農夫たちは『あれはあと取りだ。さあ、これを殺してしまおう。そうしたら、その財産はわれわれのものになるのだ』と話し合い、8 彼をつかまえて殺し、ぶどう園の外に投げ捨てた。9 このぶどう園の主人は、どうするだろうか。彼は出てきて、農夫たちを殺し、ぶどう園を他の人々に与えるであろう。

    -   ある人（ぶどう園の主人）：神

    -   ぶどう園：イスラエルの人々、神が愛するものたち

    -   農夫たち：イスラエルの支配者たち、指導することを神に委ねられているものたち

    -   僕たち：預言者たち、神の御心、直接の指示、指導に関する修正点を伝える人

        -   しもべ：モーセ（ヨシュア1:1,2,7,13,15　主のしもべモーセ）、ヨシュア（ヨシュア24:29 これらの事の後、主のしもべ、ヌンの子ヨシュアは百十歳で死んだ、）、ダビデ（サムエル記下3:18 わたしのしもべダビデ）、

        -   アモス3:7 まことに主なる神は／そのしもべである預言者にその隠れた事を／示さないでは、何事をもなされない。

        -   エレミヤ7:25あなたがたの先祖がエジプトの地を出た日から今日まで、わたしはわたしのしもべである預言者たちを日々彼らにつかわした。

        -   ゼカリヤ1:6 しかしわたしのしもべである預言者たちに命じたわが言葉と、わが定めとは、あなたがたの先祖たちに及んだではないか。それで彼らは立ち返って言った、『万軍の主がわれわれの道にしたがい、おこないに従って、われわれに、なそうと思い定められたように、そのとおりされたのだ』と」。

        -   \[DQ\] 民の指導者や、人々は、多くの預言者を殺したのでしょうか。

            -   \[A\] 聞き従わなかったことは、書かれている。

            -   バプテスマのヨハネは、どうでしょうか。やはり、民の指導者に殺されたのでしょうか。

    -   ぶどう園の主人（彼）の息子：イエス

    -   \[DQ\] 主人が、ぶどう園にしたことは、何に対応しているのでしょうか。

        -   イザヤ5:1-7 わたしはわが愛する者のために、／そのぶどう畑についてのわが愛の歌をうたおう。わが愛する者は土肥えた小山の上に、／一つのぶどう畑をもっていた。2 彼はそれを掘りおこし、石を除き、／それに良いぶどうを植え、／その中に物見やぐらを建て、／またその中に酒ぶねを掘り、／良いぶどうの結ぶのを待ち望んだ。ところが結んだものは野ぶどうであった。3 それで、エルサレムに住む者とユダの人々よ、／どうか、わたしとぶどう畑との間をさばけ。4 わたしが、ぶどう畑になした事のほかに、／何かなすべきことがあるか。わたしは良いぶどうの結ぶのを待ち望んだのに、／どうして野ぶどうを結んだのか。5 それで、わたしが、ぶどう畑になそうとすることを、／あなたがたに告げる。わたしはそのまがきを取り去って、／食い荒されるにまかせ、そのかきをとりこわして、／踏み荒されるにまかせる。6 わたしはこれを荒して、／刈り込むことも、耕すこともせず、／おどろと、いばらとを生えさせ、／また雲に命じて、その上に雨を降らさない。7 万軍の主のぶどう畑はイスラエルの家であり、／主が喜んでそこに植えられた物は、／ユダの人々である。主はこれに公平を望まれたのに、／見よ、流血。正義を望まれたのに、／見よ、叫び。

        -   \[比較\] ある人がぶどう園を造り、垣をめぐらし、また酒ぶねの穴を掘り、やぐらを立て、それを農夫たちに貸して、旅に出かけた。

            -   彼はそれを掘りおこし、石を除き、\[ぶどう園を造り、垣をめぐらし\]／それに良いぶどうを植え、／その中に物見やぐらを建て、\[やぐらを立て\]／またその中に酒ぶねを掘り、\[酒ぶねの穴を掘り\]／良いぶどうの結ぶのを待ち望んだ。

            -   イザヤでは、よいぶどうを植えたのに、野ぶどうを結んだとなっている。ここでは、収穫を主人に与えないことが言われている。

    -   \[DQ\] 主人は、なぜ、農夫に、管理を委ねるのでしょうか。直接、人々に伝えないのでしょうか。

    -   \[A\] 時代的、特質があるかもしれないが、一般的には、難しいのかもしれない。どの時代にも、指導者は必要。

    -   \[DQ\] もし、祭司長、律法学者、長老たちが、農夫に、人々がぶどう園に、譬えられているとすると、どんな事をしたと言っているのでしょうか。

    -   \[A\] 預言者（主の御心を伝えるもの）のことばに向き合わなかった。御心、主が喜ばれることをうけとって、人々にそのことを伝える役割を果たすのではなく、自分たちの優位性を主張したということだろうか。

    -   \[DQ\] なぜ、このようなことになってしまったのでしょうか。

    -   \[A\] ヨハネ12:43 彼らは神のほまれよりも、人のほまれを好んだからである。

4.  イエスはこのたとえのなかで、どんな預言をしていますか。（9）

    -   9 このぶどう園の主人は、どうするだろうか。彼は出てきて、農夫たちを殺し、ぶどう園を他の人々に与えるであろう。

    -   \[DQ\] マタイとルカも見てみましょう。どのように描かれていますか。

        -   マタイ21:40,41 40 このぶどう園の主人が帰ってきたら、この農夫たちをどうするだろうか」。41 彼らはイエスに言った、「悪人どもを、皆殺しにして、季節ごとに収穫を納めるほかの農夫たちに、そのぶどう園を貸し与えるでしょう」。

            -   彼らが答えている。

        -   ルカ20:15b,16 そのさい、ぶどう園の主人は、彼らをどうするだろうか。16 彼は出てきて、この農夫たちを殺し、ぶどう園を他の人々に与えるであろう」。人々はこれを聞いて、「そんなことがあってはなりません」と言った。

            -   イエスが答えているが、人々の言葉が追加されている。

        -   この答えの部分は、なかったのではないだろうか。

    -   \[DQ\] 「農夫を殺し」とあるが、それは、何を意味しているのだろうか。

    -   \[A\] 基本的には不明だが、すくなくとも、ぶどう園の管理（貸すこと）はしなくなることは確かだろう。

    -   \[DQ\] 他の人々はどのような人を指すのでしょうか。

    -   \[A\] マルコには「他の人々」とあるだけで、書かれていない。

        -   マタイ: 41b 季節ごとに収穫を納めるほかの農夫たち。43b 御国にふさわしい実を結ぶような異邦人

        -   ルカでも、「他の人々」とあるだけだが、同時に、「そんなことがあってはなりません」との人々のコメントが追加されている。

5.  旧約聖書からの引用は何をあらわしていますか。(10,11)

    -   10 あなたがたは、この聖書の句を読んだことがないのか。『家造りらの捨てた石が／隅のかしら石になった。11 これは主がなされたことで、／わたしたちの目には不思議に見える』」。

    -   \[DQ\] 家造りはなにに譬えられていますか。隅の頭石はなにに譬えられていますか。

    -   \[A\] 家造り：祭司長、律法学者、長老たちなど、民の指導者。しかし、同時に、背後に神様がおられる。隅の頭石：イエス。しかし、具体的にどうされるかは書かれていない。背後におられる家造りの神様が最後に置かれる大切な Corner Stone、Cap Stone となる。

    -   \[Q\] マタイや、ルカの引用は何を言っているのでしょうか。

        -   \[A\] 石につまづき、打たれて、滅ぼされるということか。

        -   マタイ21:44 またその石の上に落ちる者は打ち砕かれ、それがだれかの上に落ちかかるなら、その人はこなみじんにされるであろう」。ルカ20:18 すべてその石の上に落ちる者は打ち砕かれ、それがだれかの上に落ちかかるなら、その人はこなみじんにされるであろう」。

        -   イザヤ8:14 主はイスラエルの二つの家には聖所となり、またさまたげの石、つまずきの岩となり、エルサレムの住民には網となり、わなとなる。

        -   ローマ9:33 「見よ、わたしはシオンに、／つまずきの石、さまたげの岩を置く。それにより頼む者は、失望に終ることがない」／と書いてあるとおりである。

        -   ペテロ前2:8 また「つまずきの石、妨げの岩」である。しかし、彼らがつまずくのは、御言に従わないからであって、彼らは、実は、そうなるように定められていたのである。

        -   ダニエル2:44 それらの王たちの世に、天の神は一つの国を立てられます。これはいつまでも滅びることがなく、その主権は他の民にわたされず、かえってこれらのもろもろの国を打ち破って滅ぼすでしょう。そしてこの国は立って永遠に至るのです。45 一つの石が人手によらずに山から切り出され、その石が鉄と、青銅と、粘土と、銀と、金とを打ち砕いたのを、あなたが見られたのはこの事です。大いなる神がこの後に起るべきことを、王に知らされたのです。その夢はまことであって、この解き明かしは確かです」。

6.  イエスは、このたとえで、何を伝えているのでしょうか。（12）

    -   12 彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。

    -   \[A\] 直接的には、祭司長、律法学者、長老たちにむけて語られている。

    -   \[DQ\] 祭司長、律法学者、長老たちには、何を伝えているのでしょうか。

        -   神から委ねられたもの（神様の御心を行うこと）にたいして、忠実ではなく、背いている。

        -   神の、様々な配慮のもとで、委ねられているにもかかわらず、そのことを忘れてしまっている。

    -   \[DQ\] 「権威についての問答」（11:27-33）と関連しているとすると、イエスは、祭司長、律法学者、長老たちの問い、そしてイエスが発した問いに、どのように語っているのでしょうか。

        -   28 「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。

        -   30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。

    -   \[A\] イエスは、神の子で、祭司長、律法学者、長老たちによって殺されることになる。しかし、神は、イエスを、隅のかしら石とされる。さらに、民の指導者たちを滅ぼし、すなわち、神の仕事を担う責任から解き、人々を他の指導者のもとに置くことなる。

    -   \[DQ\] では、祭司長、律法学者、長老たちは、どうすればよかったのでしょうか。

    -   \[A\] 神の配慮に感謝し、委ねられているものに忠実に、御心を行うこと。このもとで、民を愛し、導き、民がみ心を行うことによって、神様に喜んでいただくこと。

### メモ

-   マタイは、権威についての問答と、「ぶどう園と農夫」のたとえの間に「二人の息子」のたとえを挟んでいる。民の指導者たちは、ヨハネの（悔い改めの）バプテスマ（バプテスマのヨハネではない）を信じなかったが、群衆はヨハネが預言者だとほうとうに思っていた（マルコ11:32、マタイ21: 26、ルカ20:6（ルカでは信じていた））。その心のうちをのぞきみた応答として、二人の息子のたとえを入れており、その最後には、イエスの言葉として「よく聞きなさい。取税人や遊女は、あなたがたより先に神の国にはいる。32 というのは、ヨハネがあなたがたのところにきて、義の道を説いたのに、あなたがたは彼を信じなかった。ところが、取税人や遊女は彼を信じた。あなたがたはそれを見たのに、あとになっても、心をいれ変えて彼を信じようとしなかった。」（マタイ21:31b,32）と、あからさまに、語ってから、ぶどう園のたとえを「もう一つの譬を聞きなさい。」と始めている。たしかに、そのほうが、わかりやすい。実際には、どの時点でこれらのたとえが語られたかは不明だが。なお、ルカは、マルコと同様、権威についての問答の直後に、「ぶどう園と農夫」のたとえが置かれている。

-   イエスは、なにを気づかせようとしたのだろうか。委ねられたものに忠実ではなかった？ 十分な配慮のもで委ねられたことに気付けなかった。神様との関係の中で、生かされていることを気づかない。自分たちへの愛を受け止められない。

## 12:13-17 皇帝への税金

> 13 さて、人々はパリサイ人やヘロデ党の者を数人、イエスのもとにつかわして、その言葉じりを捕えようとした。14 彼らはきてイエスに言った、「先生、わたしたちはあなたが真実なかたで、だれをも、はばかられないことを知っています。あなたは人に分け隔てをなさらないで、真理に基いて神の道を教えてくださいます。ところで、カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。15 イエスは彼らの偽善を見抜いて言われた、「なぜわたしをためそうとするのか。デナリを持ってきて見せなさい」。16 彼らはそれを持ってきた。そこでイエスは言われた、「これは、だれの肖像、だれの記号か」。彼らは「カイザルのです」と答えた。17 するとイエスは言われた、「カイザルのものはカイザルに、神のものは神に返しなさい」。彼らはイエスに驚嘆した。

### マタイ 22:15-22

> 15 そのときパリサイ人たちがきて、どうかしてイエスを言葉のわなにかけようと、相談をした。16 そして、彼らの弟子を、ヘロデ党の者たちと共に、イエスのもとにつかわして言わせた、「先生、わたしたちはあなたが真実なかたであって、真理に基いて神の道を教え、また、人に分け隔てをしないで、だれをもはばかられないことを知っています。17 それで、あなたはどう思われますか、答えてください。カイザルに税金を納めてよいでしょうか、いけないでしょうか」。18 イエスは彼らの悪意を知って言われた、「偽善者たちよ、なぜわたしをためそうとするのか。19 税に納める貨幣を見せなさい」。彼らはデナリ一つを持ってきた。20 そこでイエスは言われた、「これは、だれの肖像、だれの記号か」。21 彼らは「カイザルのです」と答えた。するとイエスは言われた、「それでは、カイザルのものはカイザルに、神のものは神に返しなさい」。22 彼らはこれを聞いて驚嘆し、イエスを残して立ち去った。

### ルカ 20:20-26

> 20 そこで、彼らは機会をうかがい、義人を装うまわし者どもを送って、イエスを総督の支配と権威とに引き渡すため、その言葉じりを捕えさせようとした。21 彼らは尋ねて言った、「先生、わたしたちは、あなたの語り教えられることが正しく、また、あなたは分け隔てをなさらず、真理に基いて神の道を教えておられることを、承知しています。22 ところで、カイザルに貢を納めてよいでしょうか、いけないでしょうか」。23 イエスは彼らの悪巧みを見破って言われた、24 「デナリを見せなさい。それにあるのは、だれの肖像、だれの記号なのか」。「カイザルのです」と、彼らが答えた。25 するとイエスは彼らに言われた、「それなら、カイザルのものはカイザルに、神のものは神に返しなさい」。26 そこで彼らは、民衆の前でイエスの言葉じりを捕えることができず、その答に驚嘆して、黙ってしまった。

[マルコによる福音書12章13-17節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_13-17.pdf)

### 問い

1.  神殿でのイエスが語り合ったことについて復習しましょう。（11:27-12:12）

2.  ここでは、どのような人たちが、どのような動機から、どのような質問をしますか。（13-14）

3.  「税を納めるべきだ」または「税を納めないべきだ」と答えた場合どのようなことが予想されますか。

4.  イエスはどのように対応し、どのように答えますか。（15-17a）

5.  この人たちは、なぜ驚嘆したのでしょうか。（17b）

6.  イエスは、どのようなことを教えているのだと思いますか。

### 参照

-   マタイはこの前に「婚礼の祝宴」のたとえ（マタイ22:1-14、参照ルカ14:15-24）
-   パリサイ派
    -   **荒井献「イエスとその時代」**(p.33-34)：「パリサイ派」は「分離者」を意味するヘブライ語「ベルーシーム」に由来すると言われる。彼らは実際、律法を守らない者、いわゆる「地の民（アム・ハ・アレツ）」の不浄から自己を「分離する」ことによって、宗教的清浄の理念を世俗内に貫徹し、その場を彼らの同志的結合「ハーベール」の中に形成していった。その際、彼らがとった手段は「律法」の敷衍解釈であった。その目的は元来、古き律法からその「理念」（ラティオ）を取り出し、それを解釈することに依って新しい時代に生かそうとする、律法のいわゆる「合理化」（ラティオナリジールング）にあったのである（M.ヴェーバー）。彼らが、 サドカイ派と違って、天使論や復活信仰を積極的に受け入れたのも、モーセ五書に固有な「神の使い」（天使）の概念や一元的人間観を、ペルシアから導入された新思想や、マカベア戦争（対シリア解放戦争（BC168-164））による殉教者の排出という新事態に即応せしめて解釈した結果なのである。このような法理念の現実的解釈に依拠する彼らの合理主義は、他国支配勢力に寄りかかった法の精神を曖昧にするサドカイ派、また、法を遵守しない「地の民」から自らを分離しただけではなく、マカベア戦争時代にともに「敬虔派」（ハシーディーム）としてシリアに対する抵抗運動を担ったかつての彼らの同志、いわゆる黙示文学的ラディカリストたちからも袂を分かっていた。このラディカリストたちはー後述するように彼らの中にも種々の分派が存在するがー終末の時に救世主（マスーアハ（メシア）＝キリスト（ギリシャ語）、本来は油注がれた者、つまり「王」の意）によって導入される神の国の故に、現実における一切の政治的・宗教的妥協を拒否し、その結果として霊的熱狂に基づく予言活動を行っていた。これに対してパリサイ派は、預言者の時代は既に終わったという認識に立ち、法理念のこの世における貫徹の中に神の国の建設を期待したのである。その結果、律法とその解釈に基づく細則を守らない者は救われないという、いわゆる律法主義に陥る傾向は十分にあったが、この傾向が前景に出てくるのは紀元後70年以後に、この派がユダヤ教正統派の位置についた以後のことであって、イエスの時代にこの傾向を読み取ることについては、慎重でなければならない。なお、主としてパリサイ派出身の律法学者たちは、「教師（ラビ）」と呼ばれて、ガリラヤを含む地方の各地に設立された「会堂（シュナゴーゲー）」で礼拝を司どり、民衆に律法の教育を与えた。最高法院においては、長老たちが保守勢力を代表したのに対して、彼らは都市（主としてエルサレム）の小市民階級を背景に革新勢力を代表した。彼ら自身多くの場合その日常生活においては、皮鞣（なめし）工・天幕作り、大工などの手工に携わっていたのである。
    -   \[パリサイ人\] マルコでは 2:18, 24, 3:6, 7:3, 5, 8:11, 15, 10:2, 12:13
        -   2:18 ヨハネの弟子とパリサイ人とは、断食をしていた。そこで人々がきて、イエスに言った、「ヨハネの弟子たちとパリサイ人の弟子たちとが断食をしているのに、あなたの弟子たちは、なぜ断食をしないのですか」。
        -   2:24 すると、パリサイ人たちがイエスに言った、「いったい、彼らはなぜ、安息日にしてはならぬことをするのですか」。
        -   3:6 パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。
        -   7:1 さて、パリサイ人と、ある律法学者たちとが、エルサレムからきて、イエスのもとに集まった。
        -   7:3 もともと、パリサイ人をはじめユダヤ人はみな、昔の人の言伝えをかたく守って、念入りに手を洗ってからでないと、食事をしない。
        -   7:5 そこで、パリサイ人と律法学者たちとは、イエスに尋ねた、「なぜ、あなたの弟子たちは、昔の人の言伝えに従って歩まないで、不浄な手でパンを食べるのですか」。
        -   8:11 パリサイ人たちが出てきて、イエスを試みようとして議論をしかけ、天からのしるしを求めた。
        -   8:15 そのとき、イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。
        -   10:2 そのとき、パリサイ人たちが近づいてきて、イエスを試みようとして質問した、「夫はその妻を出しても差しつかえないでしょうか」。
        -   12:13 さて、人々はパリサイ人やヘロデ党の者を数人、イエスのもとにつかわして、その言葉じりを捕えようとした。
-   歴史的背景（バークレー）
    -   BC4 ローマの属国としてパレスチナ全域を治めていたヘロデ大王の死
        -   ガリラヤとペレア：ヘロデ・アンティパス
        -   荒野の地方、東北のテラコニテスとイツリアとアビレネ：ヘロデ・ピリポ
        -   ユダヤとサマリア：アケラオ
            -   失政のためローマが介入、行政長官を置いて直轄
            -   課税のため人口調査
            -   ガウロナイトのユダス「課税は奴隷制度導入より悪い」として反乱
    -   賦課された税
        -   地租：すべての穀物の十分の一、産出されたぶどう酒や果実の五分の一（一部は現物、また一部は金銭）
        -   所得税：人の収入の１％
        -   人頭税：十四才から六十五歳までのすべての男子と、十二歳から六十五歳までのすべての女子に一人一デナリ
    -   皇帝ティベリウス（第二代 14-37）アウグスト・ティベリウス・カエサル
        -   貨幣の表には、名前、裏には、ポンティフェクス・マクシムス（最高の神祇官）
    -   貨幣
        -   権力の象徴
        -   貨幣が通用するところでは主権がよく維持されていた
        -   皇帝名が刻まれており、皇帝のもの
    -   国家のもとでの個人
        -   国家は神によって制定され、法によって統治される
        -   国家が人に与えるすべての恩恵を受け入れておきながら、すべての責任を拒否することはできない。
        -   もし、国家が正当な領域の中にとどまり、正当な要求をするなら、個人はそれに対して誠実と奉仕を尽くさなければならない。しかし、要するに国家と人は共に神に属する。ゆえに、国家と神の要求が重なるなら、神への忠誠が優先する。しかし、通常の環境の下においては、ある人のキリスト教信仰は、彼を他の人々よりもよき市民にすべきである、ということも真理である。
-   デナリオン銀貨（Denarius 何種類かある）\[[CoinArchives](https://www.coinarchives.com/a/results.php?results=100&search=PONTIF+and+tiberius)\], \[[Roman Coins](https://www.wildwinds.com/coins/sear5/s1763.html)\]
    -   表：ティベリウス帝 TI CAESAR DIVI AVG F AVGVSTVS (ティベリウス・カエサル 神君アウグストゥスの息子にして皇帝) Tiberius Caesar Divi Augusti Filius Augustus, Tiberius Caesar, son of divine Augustus, emperor (Augustus)
    -   裏：リウィア坐像 PONTIF MAXIM (The pontifex maximus (Latin for "supreme pontiff") was the chief high priest of the College of Pontiffs (Collegium Pontificum) in ancient Rome. )
-   カイザル：イエスを訴える口実
    -   そして訴え出て言った、「わたしたちは、この人が国民を惑わし、貢をカイザルに納めることを禁じ、また自分こそ王なるキリストだと、となえているところを目撃しました」。（ルカ23:2）
    -   これを聞いて、ピラトはイエスを許そうと努めた。しかしユダヤ人たちが叫んで言った、「もしこの人を許したなら、あなたはカイザルの味方ではありません。自分を王とするものはすべて、カイザルにそむく者です」。(ヨハネ19:12)
    -   すると彼らは叫んだ、「殺せ、殺せ、彼を十字架につけよ」。ピラトは彼らに言った、「あなたがたの王を、わたしが十字架につけるのか」。祭司長たちは答えた、「わたしたちには、カイザル以外に王はありません」。(ヨハネ19:15)
    -   その人たちをヤソンが自分の家に迎え入れました。この連中は、みなカイザルの詔勅にそむいて行動し、イエスという別の王がいるなどと言っています」。(使徒17:7)
    -   パウロは「わたしは、ユダヤ人の律法に対しても、宮に対しても、またカイザルに対しても、なんら罪を犯したことはない」と弁明した。（使徒25:8）
    -   パウロは言った、「わたしは今、カイザルの法廷に立っています。わたしはこの法廷で裁判されるべきです。よくご承知のとおり、わたしはユダヤ人たちに、何も悪いことをしてはいません。もしわたしが悪いことをし、死に当るようなことをしているのなら、死を免れようとはしません。しかし、もし彼らの訴えることに、なんの根拠もないとすれば、だれもわたしを彼らに引き渡す権利はありません。わたしはカイザルに上訴します」。そこでフェストは、陪席の者たちと協議したうえ答えた、「おまえはカイザルに上訴を申し出た。カイザルのところに行くがよい」。(使徒25:10-12)
-   しかし、彼らをつまずかせないために、海に行って、つり針をたれなさい。そして最初につれた魚をとって、その口をあけると、銀貨一枚が見つかるであろう。それをとり出して、わたしとあなたのために納めなさい」。（マタイ17:27）
-   取税人
    -   マルコ2:15,16 それから彼の家で、食事の席についておられたときのことである。多くの取税人や罪人たちも、イエスや弟子たちと共にその席に着いていた。こんな人たちが大ぜいいて、イエスに従ってきたのである。パリサイ派の律法学者たちは、イエスが罪人や取税人たちと食事を共にしておられるのを見て、弟子たちに言った、「なぜ、彼は取税人や罪人などと食事を共にするのか」。(マタイ9:10,11、ルカ5:29,30)
    -   マタイ11:19 また人の子がきて、食べたり飲んだりしていると、見よ、あれは食をむさぼる者、大酒を飲む者、また取税人、罪人の仲間だ、と言う。しかし、知恵の正しいことは、その働きが証明する」。(ルカ7:34)
    -   ルカ19:2 ところが、そこにザアカイという名の人がいた。この人は取税人のかしらで、金持であった。
    -   マタイ、ルカでは、取税人を罪人としているが、マルコはそのような表現はない。
        -   マタイ5:46 あなたがたが自分を愛する者を愛したからとて、なんの報いがあろうか。そのようなことは取税人でもするではないか。
        -   マタイ18:17 もし彼らの言うことを聞かないなら、教会に申し出なさい。もし教会の言うことも聞かないなら、その人を異邦人または取税人同様に扱いなさい。
        -   マタイ21:31,32 このふたりのうち、どちらが父の望みどおりにしたのか」。彼らは言った、「あとの者です」。イエスは言われた、「よく聞きなさい。取税人や遊女は、あなたがたより先に神の国にはいる。というのは、ヨハネがあなたがたのところにきて、義の道を説いたのに、あなたがたは彼を信じなかった。ところが、取税人や遊女は彼を信じた。あなたがたはそれを見たのに、あとになっても、心をいれ変えて彼を信じようとしなかった。
-   異邦人に従うこと
    -   エレミヤ29:7 わたしがあなたがたを捕え移させたところの町の平安を求め、そのために主に祈るがよい。その町が平安であれば、あなたがたも平安を得るからである。
    -   テモテ一2:1-2 そこで、まず第一に勧める。すべての人のために、王たちと上に立っているすべての人々のために、願いと、祈と、とりなしと、感謝とをささげなさい。それはわたしたちが、安らかで静かな一生を、真に信心深くまた謹厳に過ごすためである。
    -   ローマ13:1 すべての人は、上に立つ権威に従うべきである。なぜなら、神によらない権威はなく、おおよそ存在している権威は、すべて神によって立てられたものだからである。
    -   ローマ13:6-7 あなたがたが貢を納めるのも、また同じ理由からである。彼らは神に仕える者として、もっぱらこの務に携わっているのである。あなたがたは、彼らすべてに対して、義務を果しなさい。すなわち、貢を納むべき者には貢を納め、税を納むべき者には税を納め、恐るべき者は恐れ、敬うべき者は敬いなさい。
-   神のもの
    -   創世記1:27 神は自分のかたちに人を創造された。すなわち、神のかたちに創造し、男と女とに創造された。
    -   ヨハネ8:31-34 イエスは自分を信じたユダヤ人たちに言われた、「もしわたしの言葉のうちにとどまっておるなら、あなたがたは、ほんとうにわたしの弟子なのである。32 また真理を知るであろう。そして真理は、あなたがたに自由を得させるであろう」。33 そこで、彼らはイエスに言った、「わたしたちはアブラハムの子孫であって、人の奴隷になったことなどは、一度もない。どうして、あなたがたに自由を得させるであろうと、言われるのか」。34 イエスは彼らに答えられた、「よくよくあなたがたに言っておく。すべて罪を犯す者は罪の奴隷である。
-   驚いた（θαυμάζω: to wonder, wonder at, marvel, to be wondered at, to be had in admiration, Mk 5:20, 6:6, 12:17, 15:5, 44. ἐκπλήσσω: i. to strike out, expel by a blow, drive out or away, ii. to cast off by a blow, to drive out, iii. to be struck with amazement, astonished, amazed, Mk 1:22, 6:2, 7:37, 10:26, 11:18, θαμβέω: i. to be astonished, ii. to astonish, terrify, Mk 1:27,10:24, 10:32, ἐξίστημι: to throw out of position, displace, to amaze, to astonish, throw into wonderment, to be amazed, astounded, to be out of one's mind, besides one's self, insane, Mk 2:12, 3:21, 5:42, 6:51, ἐκθαμβέω: to throw into terror or amazement, to be struck with amazement. Mk 9:15, 14:33, 16:5, 16:6）
    -   マルコ 5:20 そこで、彼は立ち去り、そして自分にイエスがしてくださったことを、ことごとくデカポリスの地方に言いひろめ出したので、人々はみな驚き怪しんだ。（レギオン）
    -   マルコ 6:6　そして、彼らの不信仰を驚き怪しまれた。それからイエスは、附近の村々を巡りあるいて教えられた。（ナザレで）
    -   マルコ 12:17 するとイエスは言われた、「カイザルのものはカイザルに、神のものは神に返しなさい」。彼らはイエスに驚嘆した。
    -   マルコ 15:5 しかし、イエスはピラトが不思議に思うほどに、もう何もお答えにならなかった。
    -   マルコ 15:44 ピラトは、イエスがもはや死んでしまったのかと不審に思い、百卒長を呼んで、もう死んだのかと尋ねた。
    -   マルコ 1:22 人々は、その教に驚いた。律法学者たちのようにではなく、権威ある者のように、教えられたからである。
    -   マルコ6:2 そして、安息日になったので、会堂で教えはじめられた。それを聞いた多くの人々は、驚いて言った、「この人は、これらのことをどこで習ってきたのか。また、この人の授かった知恵はどうだろう。このような力あるわざがその手で行われているのは、どうしてか。
    -   マルコ 7:37 彼らは、ひとかたならず驚いて言った、「このかたのなさった事は、何もかも、すばらしい。耳の聞えない者を聞えるようにしてやり、口のきけない者をきけるようにしておやりになった」。
    -   マルコ 10:26 すると彼らはますます驚いて、互に言った、「それでは、だれが救われることができるのだろう」。
    -   マルコ 1:27 人々はみな驚きのあまり、互に論じて言った、「これは、いったい何事か。権威ある新しい教だ。けがれた霊にさえ命じられると、彼らは従うのだ」。
    -   マルコ 2:12 すると彼は起きあがり、すぐに床を取りあげて、みんなの前を出て行ったので、一同は大いに驚き、神をあがめて、「こんな事は、まだ一度も見たことがない」と言った。
    -   マルコ5:42 すると、少女はすぐに起き上がって、歩き出した。十二歳にもなっていたからである。彼らはたちまち非常な驚きに打たれた。
    -   マルコ6:51 そして、彼らの舟に乗り込まれると、風はやんだ。彼らは心の中で、非常に驚いた。
    -   マルコ9:15 群衆はみな、すぐイエスを見つけて、非常に驚き、駆け寄ってきて、あいさつをした。
    -   マルコ10:24 弟子たちはこの言葉に**驚**き怪しんだ。イエスは更に言われた、「子たちよ、神の国にはいるのは、なんとむずかしいことであろう。
    -   マルコ 10:32 さて、一同はエルサレムへ上る途上にあったが、イエスが先頭に立って行かれたので、彼らは驚き怪しみ、従う者たちは恐れた。するとイエスはまた十二弟子を呼び寄せて、自分の身に起ろうとすることについて語りはじめられた、
    -   マルコ16:5,6 墓の中にはいると、右手に真白な長い衣を着た若者がすわっているのを見て、非常に驚いた。するとこの若者は言った、「驚くことはない。あなたがたは十字架につけられたナザレ人イエスを捜しているのであろうが、イエスはよみがえって、ここにはおられない。ごらんなさい、ここがお納めした場所である。

### 記録

-   日時：2024年10月17日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）1名

### 問いについて

1.  神殿でのイエスが語り合ったことについて復習しましょう。（11:27-12:12）

    -   権威についての問答

        -   11:28 「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。

        -   11:30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。

    -   「ぶどう園の農夫」のたとえ

        -   12:9a このぶどう園の主人は、どうするだろうか。

        -   12:12 彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。

2.  ここでは、どのような人たちが、どのような動機から、どのような質問をしますか。（13-14）

    -   13 さて、人々はパリサイ人やヘロデ党の者を数人、イエスのもとにつかわして、その言葉じりを捕えようとした。14 彼らはきてイエスに言った、「先生、わたしたちはあなたが真実なかたで、だれをも、はばかられないことを知っています。あなたは人に分け隔てをなさらないで、真理に基いて神の道を教えてくださいます。ところで、カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。

    -   ἔξεστιν (it is lawful) δοῦναι κῆνσον Καίσαρι ἢ οὔ; δῶμεν ἢ μὴ δῶμεν;

    -   \[DQ\] 「人々はパリサイ人やヘロデ党の者を数人、イエスのもとにつかわし」とありますが、この「人々」とは誰のことでしょうか。

        -   祭司長、律法学者、長老たち（11:27）ではないだろうか。前段の最後には、「そしてイエスをそこに残して立ち去った。」とあることを考えると、直後にこのことがあったとは考えにくい。まとめられているのだろう。

    -   \[DQ\] 実際に遣わされた人たちはどのような人たちですか。（マタイ、ルカも確認しましょう）

        -   \[A\] 数人とあるだけで、不明、しかし、祭司長、律法学者、長老たちが直接問うたわけではない。また、マタイでは「パリサイ人たちが、彼らの弟子を、ヘロデ党の者たちと共に」イエスのもとに遣わしたとある。また、ルカでは、「彼らは、義人を装うまわし者ども」を送ったとある。

    -   \[DQ\] パリサイ人とヘロデ党のひとたちは、それぞれどのような人たちですか。

        -   \[パリサイ人\] マルコでは 2:18, 24, 3:6, 7:3, 5, 8:11, 15, 10:2, 12:13

        -   \[ヘロデ党\] パリサイ人たちは出て行って、すぐにヘロデ党の者たちと、なんとかしてイエスを殺そうと相談しはじめた。(3:6) - ヘロデ党については、今回の箇所と対応するマタイの箇所以外は、3:6 のみ。

        -   イエスは彼らを戒めて、「パリサイ人のパン種とヘロデのパン種とを、よくよく警戒せよ」と言われた。(8:15b)

    -   \[DQ\] その言葉じりを捕えようとした。とありますが、これは、どのようなことでしょうか。

        -   マタイ：どうかしてイエスを言葉のわなにかけようと、相談をした。

        -   ルカ：彼らは機会をうかがい、義人を装うまわし者どもを送って、イエスを総督の支配と権威とに引き渡すため、その言葉じりを捕えさせようとした。

    -   \[DQ\] どのような質問ですか。質問の仕方からどのようなことが伺われますか。

    -   \[A\] 「先生、わたしたちはあなたが真実なかたで、だれをも、はばかられないことを知っています。あなたは人に分け隔てをなさらないで、真理に基いて神の道を教えてくださいます。ところで、カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。

        -   かなり露骨に慇懃無礼（表面の態度は丁寧だが，心の中では相手を軽くみている・こと（さま））

        -   税を納めてよいかいけないか、納めるべきか、納めてはならないかと聞いている。

        -   マタイ：「先生、わたしたちはあなたが真実なかたであって、真理に基いて神の道を教え、また、人に分け隔てをしないで、だれをもはばかられないことを知っています。17 それで、あなたはどう思われますか、答えてください。カイザルに税金を納めてよいでしょうか、いけないでしょうか」。

        -   ルカ：「先生、わたしたちは、あなたの語り教えられることが正しく、また、あなたは分け隔てをなさらず、真理に基いて神の道を教えておられることを、承知しています。22 ところで、カイザルに貢を納めてよいでしょうか、いけないでしょうか」。

3.  「税を納めるべきだ」または「税を納めないべきだ」と答えた場合どのようなことが予想されますか。

    -   基本的には、支配者には、従うべきかどうか、自由を保持すべきかどうかが問われている。

    -   \[DQ\] 納めてよい、納めるべき、納めなくてよい、納めるべきでない、それぞれについて考えましょう。

        -   \[Q\] 税金を納めないかどうか議論できるのでしょうか。なぜ、このような質問が出てきたのでしょうか。

    -   \[DQ\] この人たちはどのような答えを期待していたのでしょうか。

        -   \[A\] 神以外のもの、異邦人、異教徒に従うことは、拒否するはず、それが、主に対する熱心さだと考えていたのだろうか。

        -   \[参照\] ヨハネ8:33 そこで、彼らはイエスに言った、「わたしたちはアブラハムの子孫であって、人の奴隷になったことなどは、一度もない。どうして、あなたがたに自由を得させるであろうと、言われるのか」。

        -   \[参照\] そして訴え出て言った、「わたしたちは、この人が国民を惑わし、貢をカイザルに納めることを禁じ、また自分こそ王なるキリストだと、となえているところを目撃しました」。（ルカ23:2）

    -   \[DQ\] この人たち（パリサイ人やヘロデ党の者）が一緒に質問したことには、どのような意味があるのでしょうか。

        -   \[A\] パリサイ人は、熱心党のようではないが、それでも、税を納めたくない。ヘロデ党は、ローマの支配に阿（おもね）って、ある地位を維持している人たちで、税を納めない反逆者は、取り締まるだろう。

4.  イエスはどのように対応し、どのように答えますか。（15-17a）

    -   15 イエスは彼らの偽善を見抜いて言われた、「なぜわたしをためそうとするのか。デナリを持ってきて見せなさい」。16 彼らはそれを持ってきた。そこでイエスは言われた、「これは、だれの肖像、だれの記号か」。彼らは「カイザルのです」と答えた。17 するとイエスは言われた、「カイザルのものはカイザルに、神のものは神に返しなさい」。

    -   \[DQ\] 偽善（15節）とはこの場合どのようなことでしょうか。

        -   ある目的のために、自分の信条とは異なることをすること。意のままにならないひとを、貶めるために、本心にないことを言い、手段を選ばず、言葉尻を捉えようとすること。

    -   \[DQ\] まず、イエスはどうしますか。これは、どのような意味がありますか。

        -   「なぜわたしをためそうとするのか。デナリを持ってきて見せなさい」。「これは、だれの肖像、だれの記号か」。

            -   実物から確認する？

        -   コインには、おそらく、表には、ティベリウス帝の横顔があり、周囲に TI CAESAR DIVI AVG F AVGVSTVS と書かれていた。これは、ティベリウス・カエサル、神君アウグストゥスの息子にして皇帝。とあり、裏には、母リヴィアの坐像があり、周囲に、PONTIF MAXIM と書かれていた。これは、最高司祭という意味である。デナリ銀貨 \[[CoinArchives](https://www.coinarchives.com/a/results.php?results=100&search=PONTIF+and+tiberius)\], \[[Roman Coins](https://www.wildwinds.com/coins/sear5/s1763.html)\]

            -   像（イメージ）を忌避し、かつ、他の神を認めないユダヤ人にとって、デナリ自体が挑戦だと受け取られていたかもしれない。

    -   \[DQ\] 神のものを神に返すとはどのような意味でしょうか。

        -   対比とすると、一義的には、神殿税を意味するかもしれないが、もっと本質的な意味が含まれているだろう。ここには、カイザルのものと、神のものをどう考えるかという問いも含まれている。

        -   \[参考\] しかし、彼らをつまずかせないために、海に行って、つり針をたれなさい。そして最初につれた魚をとって、その口をあけると、銀貨一枚が見つかるであろう。それをとり出して、わたしとあなたのために納めなさい」。（マタイ17:27）

        -   \[参考\] 創世記1:27 神は自分のかたちに人を創造された。すなわち、神のかたちに創造し、男と女とに創造された。

    -   \[DQ\] 税金は国に、心は教会にでしょうか。

5.  この人たちは、なぜ驚嘆したのでしょうか。（17b）

    -   17a 彼らはイエスに驚嘆した。

        -   マルコでは、驚いたがいくつかの言葉を使って多く表現されている。参考を参照

        -   \[『驚』で口語検索\] マタイ10件（7:28, 8:27, 9:33, 12:23, 13:54, 15:31, 19:25, 21:20, 22:22, 33）、ルカ13件（2:47, 48, 4:32, 36, 5:9, 26, 8:25, 56, 9:43, 20:26, 24:5, 22, 37）、ヨハネ3件（実質的には7:15のみ）マルコ16件

        -   マルコ 1:22, 27, 2:12, 5:20, 42, 6:2, 6, 51, 7:37, 9:15, 10:24, 26,32, 12:12, 16:5, (6)

    -   \[DQ\] 問と、答えはどのように対応しているのでしょうか。

        -   問い：「カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」（14b）

            -   言葉じりを捕らえることは、まったくできなかったと思われる。

        -   回答：「カイザルのものはカイザルに、神のものは神に返しなさい」（17a）

            -   直接的な答えは、税金はカイザルに納めなさい。納めるべき。

            -   同時に、貨幣がカイザルのものであるように、すべて、神様のものは、神様にお返ししなさい。

            -   神様にお返しするとは？

6.  イエスは、どのようなことを教えているのだと思いますか。

    -   「カイザルのものはカイザルに、神のものは神に返しなさい」（17a）

        -   難しい問いは、神に引き寄せて、神の支配のもとにあるとして考えなさい。

        -   神のもの「すべて」をどのようにお返しするか考えなさい。

    -   熱心党のシモンもおり、取税人レビ、マタイもいたはずであろう。そして、このイエスのことばを聞いていただろう。

        -   徴税のしごとを尊重したことも含められているように思われる。

### メモ

-   税金が課せられているということは、その支配下にある。かつ逃れられないことが前提だと思うが、質問者は、そう単純には、考えていないところをまずは、理解しなければならないのだろう。

    -   貨幣に書かれていた銘や、ヨハネ8:33の「わたしたちはアブラハムの子孫であって、人の奴隷になったことなどは、一度もない。どうして、あなたがたに自由を得させるであろうと、言われるのか」。にヒントが有るのかもしれない。

-   イエスを捕らえ殺そうと機会を狙っている人たちにたいする痛快な対応ではあるが、それを喜んでいるだけで良いのだろうか、イエスは、質問者に、そして我々になにを語りかけているのだろうか。

-   「カイザルのものはカイザルに、神のものは神に返しなさい」で、イエスは何を教えているのだろうか。

    -   「カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか」。（14b）

    -   「神様のものは神様にお返しすべきでしょうか。お返ししなければならないでしょうか。」

    -   「すべてのものが神様のものであるなら、神様のものを神様にお返しするにはどのようにしたら良いのでしょうか。」

-   現代的問いに何らかのヒントを与えているのだろうか。

    -   国または統治者と信仰の問題、政治・経済と宗教だろうか、神様のもとでの自由も関係するだろうか。

    -   困難な問題が目の前にあるときに、神様の視点で見てみることが促されているのだろうか。自分の置かれた状況や、その他の障壁に困難や苦しみや理不尽さの原因を求めるのではなく、神様がなにを求めておられるか、わたしたちが、どのような応答をすべきかは、問われているように思う。神のものが、神様のしるしが付いているものに囲まれているならば。

-   このひとたちが考えていたことと、イエスのこたえには、どのような相違があったのだろうか。

    -   イエスに質問をしにきた人たちは、どのような答えを期待していたのだろうか。

    -   イエスを殺そうとするなら、反逆罪が手っ取り早い。実際、法定でも、そのような訴えが出されている。ということは、税金は納めなくて良い。納めることは適切ではないということの言質をとることが期待されていたのだろう。それは、パリサイ人が考えていたことと大きくは異ならない。つまり何が正しいかの議論がここでされているわけではない。

## 12:18-27 復活についての問答

> 18 復活ということはないと主張していたサドカイ人たちが、イエスのもとにきて質問した、19 「先生、モーセは、わたしたちのためにこう書いています、『もし、ある人の兄が死んで、その残された妻に、子がない場合には、弟はこの女をめとって、兄のために子をもうけねばならない』。20 ここに、七人の兄弟がいました。長男は妻をめとりましたが、子がなくて死に、21 次男がその女をめとって、また子をもうけずに死に、三男も同様でした。22 こうして、七人ともみな子孫を残しませんでした。最後にその女も死にました。23 復活のとき、彼らが皆よみがえった場合、この女はだれの妻なのでしょうか。七人とも彼女を妻にしたのですが」。24 イエスは言われた、「あなたがたがそんな思い違いをしているのは、聖書も神の力も知らないからではないか。25 彼らが死人の中からよみがえるときには、めとったり、とついだりすることはない。彼らは天にいる御使のようなものである。26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている」。

### マタイ 22:23-33

> 23 復活ということはないと主張していたサドカイ人たちが、その日、イエスのもとにきて質問した、24 「先生、モーセはこう言っています、『もし、ある人が子がなくて死んだなら、その弟は兄の妻をめとって、兄のために子をもうけねばならない』。25 さて、わたしたちのところに七人の兄弟がありました。長男は妻をめとったが死んでしまい、そして子がなかったので、その妻を弟に残しました。26 次男も三男も、ついに七人とも同じことになりました。27 最後に、その女も死にました。28 すると復活の時には、この女は、七人のうちだれの妻なのでしょうか。みんながこの女を妻にしたのですが」。29 イエスは答えて言われた、「あなたがたは聖書も神の力も知らないから、思い違いをしている。30 復活の時には、彼らはめとったり、とついだりすることはない。彼らは天にいる御使のようなものである。31 また、死人の復活については、神があなたがたに言われた言葉を読んだことがないのか。32 『わたしはアブラハムの神、イサクの神、ヤコブの神である』と書いてある。神は死んだ者の神ではなく、生きている者の神である」。33 群衆はこれを聞いて、イエスの教に驚いた。

### ルカ 20:27-40

> 27 復活ということはないと言い張っていたサドカイ人のある者たちが、イエスに近寄ってきて質問した、28 「先生、モーセは、わたしたちのためにこう書いています、『もしある人の兄が妻をめとり、子がなくて死んだなら、弟はこの女をめとって、兄のために子をもうけねばならない』。29 ところで、ここに七人の兄弟がいました。長男は妻をめとりましたが、子がなくて死に、30 そして次男、三男と、次々に、その女をめとり、31 七人とも同様に、子をもうけずに死にました。32 のちに、その女も死にました。33 さて、復活の時には、この女は七人のうち、だれの妻になるのですか。七人とも彼女を妻にしたのですが」。34 イエスは彼らに言われた、「この世の子らは、めとったり、とついだりするが、35 かの世にはいって死人からの復活にあずかるにふさわしい者たちは、めとったり、とついだりすることはない。36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。37 死人がよみがえることは、モーセも柴の篇で、主を『アブラハムの神、イサクの神、ヤコブの神』と呼んで、これを示した。38 神は死んだ者の神ではなく、生きている者の神である。人はみな神に生きるものだからである」。39 律法学者のうちのある人々が答えて言った、「先生、仰せのとおりです」。40 彼らはそれ以上何もあえて問いかけようとしなかった。

[マルコによる福音書12章18-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_18-27.pdf)

### 問い

1.  これまで、神殿でどのような人たちとどのようなことについて話したか復習しましょう。（11:27-12:17）

2.  サドカイ人は、どのような人たちですか。復活についてはどう考えていますか。（18）

3.  サドカイ人たちは、どんな質問をしますか。（19-23）

4.  イエスはサドカイ人たちがどんな思い違いをしていると言っていますか。（24, 25）

5.  イエスは、復活について、どのような聖書を引用していますか。（26,27）

6.  イエスは、この箇所で復活についてどのようなことを教えているのでしょうか。

### 参照

-   サドカイ派

    -   聖書箇所

        -   マルコ12:8 復活ということはないと主張していた**サドカイ**人たちが、イエスのもとにきて質問した、（マタイ22:23、ルカ20:27）

        -   マタイ3:7 ヨハネは、パリサイ人やサドカイ人が大ぜいバプテスマを受けようとしてきたのを見て、彼らに言った、「まむしの子らよ、迫ってきている神の怒りから、おまえたちはのがれられると、だれが教えたのか。

        -   マタイ16:1 パリサイ人とサドカイ人とが近寄ってきて、イエスを試み、天からのしるしを見せてもらいたいと言った。

        -   マタイ16:6 そこでイエスは言われた、「パリサイ人とサドカイ人とのパン種を、よくよく警戒せよ」。

        -   マタイ16:11,12 わたしが言ったのは、パンについてではないことを、どうして悟らないのか。ただ、パリサイ人とサドカイ人とのパン種を警戒しなさい」。12そのとき彼らは、イエスが警戒せよと言われたのは、パン種のことではなく、パリサイ人とサドカイ人との教のことであると悟った。

        -   マタイ22:34 さて、パリサイ人たちは、イエスがサドカイ人たちを言いこめられたと聞いて、一緒に集まった。（最も重要な戒め冒頭）

        -   使徒4:1-3 彼ら（ペテロとヨハネ）が人々にこのように語っているあいだに、祭司たち、宮守がしら、サドカイ人たちが近寄ってきて、2 彼らが人々に教を説き、イエス自身に起った死人の復活を宣伝しているのに気をいら立て、3 彼らに手をかけて捕え、はや日が暮れていたので、翌朝まで留置しておいた。

        -   使徒5:17 そこで、大祭司とその仲間の者、すなわち、サドカイ派の人たちが、みな嫉妬の念に満たされて立ちあがり、

        -   使徒23:6-8 パウロは、議員の一部がサドカイ人であり、一部はパリサイ人であるのを見て、議会の中で声を高めて言った、「兄弟たちよ、わたしはパリサイ人であり、パリサイ人の子である。わたしは、死人の復活の望みをいだいていることで、裁判を受けているのである」。7 彼がこう言ったところ、パリサイ人とサドカイ人との間に争論が生じ、会衆は相分れた。8 元来、サドカイ人は、復活とか天使とか霊とかは、いっさい存在しないと言い、パリサイ人は、それらは、みな存在すると主張している。

    -   **荒井献「イエスとその時代」**(p.33) サドカイ派の呼称は、イスラエルにおける最古・最大の大祭司「サドク」に由来するといわれる。また、一説によるとこの呼称は、「義を行使する」意味のヘブライ語「サドゥク」に遡るとも言われる。いずれにしても彼らは、伝統主義・保守主義の立場をとり、「モーセ律法」ないしは「モーセ五書」のみを聖文書として、ここに認められない、あるいはこれ以後の時代に成立したと言われる新思想ー例えば律法の敷衍解釈による法の細則・天使論・復活思想などーを一切認めなかった。もっとも、政治的には、彼らがユダヤ社会の経済的上層と密着していただけに、外国支配勢力に対しては一般的に協調策をとっている。そのために、たとえば復活思想の否認は、当時における世界体制の思想であるヘレニズム・ローマ思想を受容した結果であるとも説明できる。その意味で、サドカイ派の保守的国民主義は自由主義として機能することもできたのである。実際この派は、紀元前66年にはローマ軍から神殿祭儀を守り、信教の自由を確保してはいる。しかし、イエスの時代には、ローマの傀儡的存在であったアンナス家の大祭司、祭司長たち、長老たちと密着することにより、体制を思想的に擁護する役割を果たしていたのである。

    -   **榊原康夫**「**マタイによる福音書 下巻**」（p.77）「サドカイ人」というのは、前の「パリサイ人」と、あらゆる点で正反対の人々でした。パリサイ派が純宗教団体であるのに対して、サドカイ派は、むしろ政治団体に近く、当時の最高議会議員の大半を占めていました。彼らはそのように、時の権力者と結びつく世俗主義者であるために、時代の流行に敏感な進歩主義者・合理主義者でもありました。それで、一応ユダヤ教を信じはしても、モーセの律法にしるされた明白な定め以外は何者も、ーラビの学説も伝承もー権威を認めません。従って、パリサイ人や一般民衆が長い間信じ込んできたことも、この一派の手にかかると、「律法に明記されていない」という理由で否定されてしまいました。使徒行伝23章8節に「元来、サドカイ人は、復活とか霊とかは、一切存在しないと言い、パリサイ人は、それらはみな存在すると主張している」とあるとおりです。要するに、彼らは、まったく現代的な合理的唯物主義の立場に立っていました。

    -   **山口昇**「**新聖書注解**（いのちのことば社）」貴族階級に属し、大祭司や、エルサレムの有力者からなっていた。彼らは経済的に恵まれ、富裕であったが、この世的でもあった。彼らはモーセ五書だけを律法として認めていたので、復活の教理は受け入れなかった。（Cf 使徒23:6-8）なぜなら、死人の復活に関する教えはイザヤ26:19、ダニエル12:2 に至るまで現れなかったからである。

        -   イザヤ26:19　あなたの死者は生き、彼らのなきがらは起きる。ちりに伏す者よ、さめて喜びうたえ。あなたの露は光の露であって、／それを亡霊の国の上に降らされるからである。

        -   ダニエル12:2　また地のちりの中に眠っている者のうち、多くの者は目をさますでしょう。そのうち永遠の生命にいたる者もあり、また恥と、限りなき恥辱をうける者もあるでしょう。

    -   **ヨセフス**「**ユダヤ人古代史**」

        -   [13-10-6](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0146%3Abook%3D13%3Awhiston+chapter%3D10%3Awhiston+section%3D6) ヨナタンという人がヒルカノスの非常に親しい友人だったが、サドカイ派に属していて、その考えはパリサイ人とは全く正反対であった。ヨナタンはヒルカノスに、エレアザルがパリサイ人全員の共通の考えに従ってヒルカノスにそのような非難をしたこと、そして、パリサイ人全員に「彼らはこの男にどんな罰がふさわしいと思うか」と尋ねさえすれば、それが明らかになるだろう、と言った。彼らが彼の罪にふさわしい罰を与えたとしても、非難は彼らの承認によって彼に下されたのではないことは、彼が確信できるからである。そこでパリサイ人は、彼は鞭打ちと縄目に値したが、非難を死で罰するのは正しくないだろうと答えた。実際、パリサイ人は他の場合でさえ、罰を厳しくする傾向はない。この穏やかな判決にヒルカノスは非常に怒り、この男が彼らの承認によって彼を非難したのだと思った。このヨナタンこそが、ヨナタンを最も怒らせ、ヨナタンに影響を与えたため、ヨナタンはヨナタンをパリサイ派から離脱させ、彼らが民衆に課した法令を廃止させ、それを守る者を罰した。このことから、ヨナタンとその息子たちが民衆から受けた憎悪が生じたのである。しかし、これらの事柄については、これから述べることにする。私が今説明したいのは、パリサイ人は、モーセの律法には書かれていない、先祖から受け継いだ多くの慣習を民衆に伝えてきたということである。そのため、サドカイ人はそれを拒絶し、書かれた言葉にある慣習は義務であるとみなすべきだが、先祖の伝統に由来するものは守るべきではないと言うのである。そして、これらのことに関して、彼らの間には大きな論争と不和が生じており、サドカイ派は富裕層以外を説得できず、民衆の支持も得られないが、パリサイ派は大衆の支持を得ている。しかし、この二つの宗派とエッセン派については、ユダヤ事情第二巻で正確に扱っている。(Google Chrome 翻訳)

        -   [18-1-4](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0146%3Abook%3D18%3Awhiston+chapter%3D1%3Awhiston+section%3D4) しかし、サドカイ派の教えはこうです。魂は肉体と共に死ぬということです。彼らは、律法が命じていること以外は何事も守ろうとしません。なぜなら、彼らは、よく会う哲学の教師たちと議論することが美徳であると考えているからです。しかし、この教えを受け入れるのは少数の人たち、それでも最も高貴な人たちだけです。しかし、彼らは自分ではほとんど何もすることができません。なぜなら、時には不本意に、そして強制的にそうならざるを得ないのですが、行政官になると、彼らはパリサイ人の観念に溺れるからです。そうでなければ、大衆はそれを受け入れないでしょうから。(Google Chrome 翻訳)

-   復活に関する当時のユダヤ教会の意見（榊原康夫）

    -   パリサイ派・エッセネ派・一般大衆：人の霊魂は死後も存在し続け、従って、その霊魂はいつかからだをとりもどす、すなわち復活する。

    -   サドカイ派：人間はしにおいて体が朽ちる時、一切が終わり、従って復活もない。

-   復活・よみがえりに関する記事

    -   イエス自身についての証言（マルコを中心に）よみがえる（ἀνίστημι: i. to cause to rise up, raise up, ii. to rise, stand upto rise, stand up, iii. at arise, appear, stand forth）他の意味にも使われる マルコ1:35, 2:14, 3:26, 5:42, 7:24, 9:27, 10:1, 10:50.

        -   8:31,32a それから、人の子は必ず多くの苦しみを受け、長老、祭司長、律法学者たちに捨てられ、また殺され、そして三日の後によみがえるべきことを、彼らに教えはじめ、しかもあからさまに、この事を話された。（マタイ16:21）

        -   9:9,10 一同が山を下って来るとき、イエスは「人の子が死人の中からよみがえるまでは、いま見たことをだれにも話してはならない」と、彼らに命じられた。彼らはこの言葉を心にとめ、死人の中からよみがえるとはどういうことかと、互に論じ合った。(マタイ17:9)

        -   9:31 それは、イエスが弟子たちに教えて、「人の子は人々の手にわたされ、彼らに殺され、殺されてから三日の後によみがえるであろう」と言っておられたからである。(マタイ17:23)

        -   10:34 また彼をあざけり、つばきをかけ、むち打ち、ついに殺してしまう。そして彼は三日の後によみがえるであろう」。(マタイ20:19)

        -   参照：「長官、あの偽り者がまだ生きていたとき、『三日の後に自分はよみがえる』と言ったのを、思い出しました。（マタイ27:63）

    -   「復活（ἀνάστασις： i. a raising up, rising (e.g. from a seat), a rising from the dead）」口語訳（福音書）

        -   マルコ12:18 復活ということはないと主張していたサドカイ人たちが、イエスのもとにきて質問した、（マタイ22:23, ルカ20:27）

        -   マルコ12:23 復活のとき、彼らが皆よみがえった場合、この女はだれの妻なのでしょうか。七人とも彼女を妻にしたのですが」。（マタイ22:28, ルカ20:33）

        -   マタイ22:30,31 復活の時には、彼らはめとったり、とついだりすることはない。彼らは天にいる御使のようなものである。31 また、死人の復活については、神があなたがたに言われた言葉を読んだことがないのか。（ルカ20:35,36）

        -   マタイ27:53 そしてイエスの復活ののち、墓から出てきて、聖なる都にはいり、多くの人に現れた。

        -   ルカ9:8 またある人たちは、エリヤが現れたと言い、またほかの人たちは、昔の預言者のひとりが復活したのだと言っていたからである。

        -   ルカ9:19 彼らは答えて言った、「バプテスマのヨハネだと、言っています。しかしほかの人たちは、エリヤだと言い、また昔の預言者のひとりが復活したのだと、言っている者もあります」。

        -   ルカ14:14 そうすれば、彼らは返礼ができないから、あなたはさいわいになるであろう。正しい人々の復活の際には、あなたは報いられるであろう」。

        -   ヨハネ5:29 善をおこなった人々は、生命を受けるためによみがえり、悪をおこなった人々は、さばきを受けるためによみがえって、それぞれ出てくる時が来るであろう。

        -   ヨハネ11:24,25 マルタは言った、「終りの日のよみがえりの時よみがえることは、存じています」。25 イエスは彼女に言われた、「わたしはよみがえりであり、命である。わたしを信じる者は、たとい死んでも生きる。

        -   使徒1:22, 2:31, 4:2, 33, 17:18, 32, 23:6, 8, 24:15, 21, 26:23

        -   パウロ書簡

            -   ローマ1:4 聖なる霊によれば、死人からの復活により、御力をもって神の御子と定められた。これがわたしたちの主イエス・キリストである。

            -   ローマ6:5 もしわたしたちが、彼に結びついてその死の様にひとしくなるなら、さらに、彼の復活の様にもひとしくなるであろう。

            -   1コリント15:12,13 さて、キリストは死人の中からよみがえったのだと宣べ伝えられているのに、あなたがたの中のある者が、死人の復活などはないと言っているのは、どうしたことか。13 もし死人の復活がないならば、キリストもよみがえらなかったであろう。

            -   1コリント15:21 それは、死がひとりの人によってきたのだから、死人の復活もまた、ひとりの人によってこなければならない。

            -   1コリント15:35-44 しかし、ある人は言うだろう。「どんなふうにして、死人がよみがえるのか。どんなからだをして来るのか」。36 おろかな人である。あなたのまくものは、死ななければ、生かされないではないか。37 また、あなたのまくのは、やがて成るべきからだをまくのではない。麦であっても、ほかの種であっても、ただの種粒にすぎない。38 ところが、神はみこころのままに、これにからだを与え、その一つ一つの種にそれぞれのからだをお与えになる。39 すべての肉が、同じ肉なのではない。人の肉があり、獣の肉があり、鳥の肉があり、魚の肉がある。40 天に属するからだもあれば、地に属するからだもある。天に属するものの栄光は、地に属するものの栄光と違っている。41 日の栄光があり、月の栄光があり、星の栄光がある。また、この星とあの星との間に、栄光の差がある。42 死人の復活も、また同様である。朽ちるものでまかれ、朽ちないものによみがえり、43 卑しいものでまかれ、栄光あるものによみがえり、弱いものでまかれ、強いものによみがえり、44 肉のからだでまかれ、霊のからだによみがえるのである。肉のからだがあるのだから、霊のからだもあるわけである。

            -   ピリピ3:10 すなわち、キリストとその復活の力とを知り、その苦難にあずかって、その死のさまとひとしくなり、(11 なんとかして死人のうちからの復活に達したいのである。）

            -   2テモテ2:18 彼らは真理からはずれ、復活はすでに済んでしまったと言い、そして、ある人々の信仰をくつがえしている。

        -   その他の書簡

            -   ヘブル6:2 洗いごとについての教と按手、死人の復活と永遠のさばき、などの基本の教をくりかえし学ぶことをやめようではないか。

            -   1ペテロ3:21 この水はバプテスマを象徴するものであって、今やあなたがたをも救うのである。それは、イエス・キリストの復活によるのであって、からだの汚れを除くことではなく、明らかな良心を神に願い求めることである。

            -   黙示録20:5,6 （それ以外の死人は、千年の期間が終るまで生きかえらなかった。）これが第一の復活である 6 この第一の復活にあずかる者は、さいわいな者であり、また聖なる者である。この人たちに対しては、第二の死はなんの力もない。彼らは神とキリストとの祭司となり、キリストと共に千年の間、支配する。

    -   よみがえ（って）（ἐγείρω: to arouse, cause to rise, i. to arouse from sleep, to awake, ii. to arouse from the sleep of death, to recall the dead to life, iii. to cause to rise from a seat or bed etc., iv to raise up, produce, cause to appear）Mt 9:25, 10:8, 11:5, 14:2, 16:21, 17:9, 23, 20:19, 26:32, 27:52, 27:63, 64, 28:6, Mk 5:41, 6:16, 12:26, 14:28, 16:6, 14. Lk 7:14, 7:22, 8:54, 9:7, 22, Jn 2:19, 20, 5:21, 12:1, 9, 17, 21:14, Acts 5:30, 10:40, 13:30, 37, 26:8, Rm 4:24, 25, 6:4, 9, 7:4, 8:11, 8:34, 10:9, 1Cor 6:14, 15:4, 12, 13, 14, 15, 16, 17, 20, 29, 32, 35, 42, 43, 44, 52, 2Cor 1:9, 2Cor 1:9, 4:14, 5:15, Gal 1:1, Eph 1:20, 5:14, Phil 1:17, Co 2:12, 1Th 1:10, 2Ti 2:8, Heb 11:19, Jas 5:15?, 1Pet 1:21

        -   マルコ5:41 そして子供の手を取って、「タリタ、クミ」と言われた。それは、「少女よ、さあ、起きなさい」という意味である。

        -   マルコ6:14-16 さて、イエスの名が知れわたって、ヘロデ王の耳にはいった。ある人々は「バプテスマのヨハネが、死人の中からよみがえってきたのだ。それで、あのような力が彼のうちに働いているのだ」と言い、15 他の人々は「彼はエリヤだ」と言い、また他の人々は「昔の預言者のような預言者だ」と言った。16 ところが、ヘロデはこれを聞いて、「わたしが首を切ったあのヨハネがよみがえったのだ」と言った。

        -   マルコ12:26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。

        -   マルコ14:28 しかしわたしは、よみがえってから、あなたがたより先にガリラヤへ行くであろう」。

        -   マルコ16:6 するとこの若者は言った、「驚くことはない。あなたがたは十字架につけられたナザレ人イエスを捜しているのであろうが、イエスはよみがえって、ここにはおられない。ごらんなさい、ここがお納めした場所である。

        -   マルコ16:14 その後、イエスは十一弟子が食卓についているところに現れ、彼らの不信仰と、心のかたくななことをお責めになった。彼らは、よみがえられたイエスを見た人々の言うことを、信じなかったからである。

        -   ヨハネ12:1 過越の祭の六日まえに、イエスはベタニヤに行かれた。そこは、イエスが死人の中からよみがえらせたラザロのいた所である。

        -   ヨハネ12:9 大ぜいのユダヤ人たちが、そこにイエスのおられるのを知って、押しよせてきた。それはイエスに会うためだけではなく、イエスが死人のなかから、よみがえらせたラザロを見るためでもあった。

        -   ヨハネ21:14 イエスが死人の中からよみがえったのち、弟子たちにあらわれたのは、これで既に三度目である。

        -   ローマ4:24, 25, 6:4, 9, 7:4, 8:11, 8:34, 10:9

        -   ローマ6:4 すなわち、わたしたちは、その死にあずかるバプテスマによって、彼と共に葬られたのである。それは、キリストが父の栄光によって、死人の中からよみがえらされたように、わたしたちもまた、新しいいのちに生きるためである。

        -   ローマ6:9 キリストは死人の中からよみがえらされて、もはや死ぬことがなく、死はもはや彼を支配しないことを、知っているからである。

        -   ローマ7:4 わたしの兄弟たちよ。このように、あなたがたも、キリストのからだをとおして、律法に対して死んだのである。それは、あなたがたが他の人、すなわち、死人の中からよみがえられたかたのものとなり、こうして、わたしたちが神のために実を結ぶに至るためなのである。

        -   ローマ8:11 もし、イエスを死人の中からよみがえらせたかたの御霊が、あなたがたの内に宿っているなら、キリスト・イエスを死人の中からよみがえらせたかたは、あなたがたの内に宿っている御霊によって、あなたがたの死ぬべきからだをも、生かしてくださるであろう。

        -   ローマ8:34 だれが、わたしたちを罪に定めるのか。キリスト・イエスは、死んで、否、よみがえって、神の右に座し、また、わたしたちのためにとりなして下さるのである。

        -   ローマ10:9 すなわち、自分の口で、イエスは主であると告白し、自分の心で、神が死人の中からイエスをよみがえらせたと信じるなら、あなたは救われる。

        -   1コリント6:14 そして、神は主をよみがえらせたが、その力で、わたしたちをもよみがえらせて下さるであろう。

        -   1コリント15:4, 12, 13, 14, 15, 16, 17, 20, 29, 32, 35, 42, 43, 44, 52

-   旧約聖書からの引用

    -   申命記25:5-10 兄弟が一緒に住んでいて、そのうちのひとりが死んで子のない時は、その死んだ者の妻は出て、他人にとついではならない。その夫の兄弟が彼女の所にはいり、めとって妻とし、夫の兄弟としての道を彼女につくさなければならない。6 そしてその女が初めに産む男の子に、死んだ兄弟の名を継がせ、その名をイスラエルのうちに絶やさないようにしなければならない。7 しかしその人が兄弟の妻をめとるのを好まないならば、その兄弟の妻は町の門へ行って、長老たちに言わなければならない、『わたしの夫の兄弟はその兄弟の名をイスラエルのうちに残すのを拒んで、夫の兄弟としての道をつくすことを好みません』。8 そのとき町の長老たちは彼を呼び寄せて、さとさなければならない。もし彼が固執して、『わたしは彼女をめとることを好みません』と言うならば、9 その兄弟の妻は長老たちの目の前で、彼のそばに行き、その足のくつを脱がせ、その顔につばきして、答えて言わなければならない。『兄弟の家をたてない者には、このようにすべきです』。10 そして彼の家の名は、くつを脱がされた者の家と、イスラエルのうちで呼ばれるであろう。

        -   以下の規定に関する例外事項としてしるされている。レビ18:16 あなたの兄弟の妻を犯してはならない。それはあなたの兄弟をはずかしめることだからである。レビ20:21 人がもし、その兄弟の妻を取るならば、これは汚らわしいことである。彼はその兄弟をはずかしめたのであるから、彼らは子なき者となるであろう。

    -   出エジプト3:1-10 モーセは妻の父、ミデヤンの祭司エテロの羊の群れを飼っていたが、その群れを荒野の奥に導いて、神の山ホレブにきた。2 ときに主の使は、しばの中の炎のうちに彼に現れた。彼が見ると、しばは火に燃えているのに、そのしばはなくならなかった。3 モーセは言った、「行ってこの大きな見ものを見、なぜしばが燃えてしまわないかを知ろう」。4 主は彼がきて見定めようとするのを見、神はしばの中から彼を呼んで、「モーセよ、モーセよ」と言われた。彼は「ここにいます」と言った。5 神は言われた、「ここに近づいてはいけない。足からくつを脱ぎなさい。あなたが立っているその場所は聖なる地だからである」。6 また言われた、「わたしは、あなたの先祖の神、アブラハムの神、イサクの神、ヤコブの神である」。モーセは神を見ることを恐れたので顔を隠した。6 また言われた、「わたしは、あなたの先祖の神、アブラハムの神、イサクの神、ヤコブの神である」。モーセは神を見ることを恐れたので顔を隠した。7 主はまた言われた、「わたしは、エジプトにいるわたしの民の悩みを、つぶさに見、また追い使う者のゆえに彼らの叫ぶのを聞いた。わたしは彼らの苦しみを知っている。8 わたしは下って、彼らをエジプトびとの手から救い出し、これをかの地から導き上って、良い広い地、乳と蜜の流れる地、すなわちカナンびと、ヘテびと、アモリびと、ペリジびと、ヒビびと、エブスびとのおる所に至らせようとしている。9 いまイスラエルの人々の叫びがわたしに届いた。わたしはまたエジプトびとが彼らをしえたげる、そのしえたげを見た。10 さあ、わたしは、あなたをパロにつかわして、わたしの民、イスラエルの人々をエジプトから導き出させよう」。

-   ヨハネ11:25-36 イエスは彼女に言われた、「わたしはよみがえりであり、命である。わたしを信じる者は、たとい死んでも生きる。26 また、生きていて、わたしを信じる者は、いつまでも死なない。あなたはこれを信じるか」。27 マルタはイエスに言った、「主よ、信じます。あなたがこの世にきたるべきキリスト、神の御子であると信じております」。28 マルタはこう言ってから、帰って姉妹のマリヤを呼び、「先生がおいでになって、あなたを呼んでおられます」と小声で言った。29 これを聞いたマリヤはすぐに立ち上がって、イエスのもとに行った。30 イエスはまだ村に、はいってこられず、マルタがお迎えしたその場所におられた。31 マリヤと一緒に家にいて彼女を慰めていたユダヤ人たちは、マリヤが急いで立ち上がって出て行くのを見て、彼女は墓に泣きに行くのであろうと思い、そのあとからついて行った。32 マリヤは、イエスのおられる所に行ってお目にかかり、その足もとにひれ伏して言った、「主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう」。33 イエスは、彼女が泣き、また、彼女と一緒にきたユダヤ人たちも泣いているのをごらんになり、激しく感動し、また心を騒がせ、そして言われた、34 「彼をどこに置いたのか」。彼らはイエスに言った、「主よ、きて、ごらん下さい」。35 イエスは涙を流された。36 するとユダヤ人たちは言った、「ああ、なんと彼を愛しておられたことか」。

-   バークレイ

    -   サドカイ人たちは、この世の像のなかに天を作り出す過ちを犯した。彼らは、この世の事物の言葉の中で天を考えた。人々は常にそうするものである。

        -   １コリント2:9 しかし、聖書に書いてあるとおり、／「目がまだ見ず、耳がまだ聞かず、／人の心に思い浮びもしなかったことを、／神は、ご自分を愛する者たちのために備えられた」／のである。

        -   イザヤ64:4 いにしえからこのかた、／あなたのほか神を待ち望む者に、／このような事を行われた神を聞いたことはなく、／耳に入れたこともなく、目に見たこともない。

    -   イエスは復活についての確信を、神と善人との関係はなにものも破ることができないという事実に基礎づけた。一度、ひとが永遠なる神との人格的関係にはいると、その関係は永遠である。神は、アブラハム、イサク、ヤコブが生きていた時、彼らの友であられた。

        -   神は、神に仕え、神を愛するひとにたいして、神であることをやめることができない。（ロアジ 1857-1940）

        -   詩篇73:23-24 けれどもわたしは常にあなたと共にあり、／あなたはわたしの右の手を保たれる。24 あなたはさとしをもってわたしを導き、／その後わたしを受けて栄光にあずからせられる。

-   エノク書10:17-19

    -   その時、すべての義人はまぬがれて、何千人の子を生むに至るまで生きながらえ、その若き日と老年のすべての日を、彼らは平安のうちにまっとうする。その時、全地は義によって耕され、くまなく木々がうえられて祝福に満ちる。すべて望ましい木はそこに植えられ、ぶどうが飢えられる。そこに飢えたぶどうはおびただしい酒を生じ、まかれたすべての種は、一マスが千マスを生じ、一マスのオリーブは十マスの油をもたらす。

-   クムラン宗規要覧

    -   すべてこれ（真実の霊）によって歩むものへの報いは、いやし、長命にともなう豊かな平安、永遠の祝福をもつ多くの子供、永遠の命による永久の喜び、栄光の冠と永久の光に輝く衣である。

-   ヨセフス

    -   ユダヤ人古代史18:1:3 パリサイ人は、霊魂はそのうちに不滅の力をもち、ひとが現世で有徳に生きたかよこしまに生きたかに応じて、地下で報酬と刑罰があり、後者は永遠の獄屋に閉じ込められるのに対して、前者は生まれ変わって再び生きる力を持つと信じる。

    -   ユダヤ戦記2:8:11 エッセネ派の教えは次の通り。肉体は朽つべきもので、それが作られている物質もまた永遠でないが、霊魂は永続する。それは最も微妙な大気から出て、獄に入るように体に結合される。一種自然ないざないによって引き込まれるのである。しかし、肉のかせから解き放たれるときには、年久しい奴隷のくびきからすくわれたかのように、喜んで上に昇る。

-   タルムード

    -   あの世では女は毎日子をうむとか（シャッバス30b）、復活者は死人に触れたのだから清めの儀式が必要いなかまで論じられる。（ニッダー70b、サンヘドリン70b）

-   レビラト婚（Levirate marriage）

    -   Wikipedia ([日](https://ja.wikipedia.org/wiki/レビラト婚)）（[E](https://en.wikipedia.org/wiki/Levirate_marriage)）寡婦が死亡した夫の兄弟と結婚する慣習。レビラトは、ラテン語で夫の兄弟を意味するレウィル(levir)に由来する。レビレート婚とも。Levirate marriage is a type of marriage in which the brother of a deceased man is obliged to marry his brother's widow. Levirate marriage has been practiced by societies with a strong clan structure in which exogamous marriage (i.e. marriage outside the clan) is forbidden.

-   天使

    -   旧約聖書

        -   ヨブ記4:18 見よ、彼はそのしもべをさえ頼みとせず、／その天使をも誤れる者とみなされる。

        -   ヨブ記33:23 もしそこに彼のためにひとりの天使があり、／千のうちのひとりであって、仲保となり、／人にその正しい道を示すならば、

        -   詩篇78:25 人は天使のパンを食べた。神は彼らに食物をおくって飽き足らせられた。

        -   詩篇78:49 神は彼らの上に激しい怒りと、憤りと、／恨みと、悩みと、滅ぼす天使の群れとを放たれた。

        -   詩篇91:11 これは主があなたのために天使たちに命じて、／あなたの歩むすべての道で／あなたを守らせられるからである。

        -   詩篇148:2 その天使よ、みな主をほめたたえよ。その万軍よ、／みな主をほめたたえよ。

        -   ダニエル10:13 ペルシャの国の君が、二十一日の間わたしの前に立ちふさがったが、天使の長のひとりであるミカエルがきて、わたしを助けたので、わたしは、彼をペルシャの国の君と共に、そこに残しておき、

    -   福音書

        -   ルカ20:36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。

    -   その他の新約聖書

        -   使徒6:15 議会で席についていた人たちは皆、ステパノに目を注いだが、彼の顔は、ちょうど天使の顔のように見えた。

        -   使徒23:8，9 元来、サドカイ人は、復活とか天使とか霊とかは、いっさい存在しないと言い、パリサイ人は、それらは、みな存在すると主張している。9 そこで、大騒ぎとなった。パリサイ派のある律法学者たちが立って、強く主張して言った、「われわれは、この人には何も悪いことがないと思う。あるいは、霊か天使かが、彼に告げたのかも知れない」。

        -   ローマ8:38 わたしは確信する。死も生も、天使も支配者も、現在のものも将来のものも、力あるものも、

        -   1コリント4:9 わたしはこう考える。神はわたしたち使徒を死刑囚のように、最後に出場する者として引き出し、こうしてわたしたちは、全世界に、天使にも人々にも見せ物にされたのだ。

        -   1コリ11:10 それだから、女は、かしらに権威のしるしをかぶるべきである。それは天使たちのためでもある。

        -   2コリ11:14 しかし、驚くには及ばない。サタンも光の天使に擬装するのだから。

        -   ガラテヤ3:19 それでは、律法はなんであるか。それは違反を促すため、あとから加えられたのであって、約束されていた子孫が来るまで存続するだけのものであり、かつ、天使たちをとおし、仲介者の手によって制定されたものにすぎない。

        -   コロサイ2:18 あなたがたは、わざとらしい謙そんと天使礼拝とにおぼれている人々から、いろいろと悪評されてはならない。彼らは幻を見たことを重んじ、肉の思いによっていたずらに誇るだけで、

        -   1テサロニケ4:16 すなわち、主ご自身が天使のかしらの声と神のラッパの鳴り響くうちに、合図の声で、天から下ってこられる。その時、キリストにあって死んだ人々が、まず最初によみがえり、

        -   2テサロニケ1:7 それは、主イエスが炎の中で力ある天使たちを率いて天から現れる時に実現する。

        -   ヘブル2:16 確かに、彼は天使たちを助けることはしないで、アブラハムの子孫を助けられた。

        -   ヘブル12:22 しかしあなたがたが近づいているのは、シオンの山、生ける神の都、天にあるエルサレム、無数の天使の祝会、

        -   1ペテロ3:22 キリストは天に上って神の右に座し、天使たちともろもろの権威、権力を従えておられるのである。

### 記録

-   日時：2024年10月24日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）1名

### 問いについて

1.  これまで、神殿でどのような人たちとどのようなことについて話したか復習しましょう。（11:27-12:17）

    -   \[DQ\] どのようなグループの人たちとの話かも同時に復習しましょう。

    -   権威についての問答（11:27-33）vs 祭司長、律法学者、長老たち（27）

        -   問：11:28「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。

        -   イエス：11:30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。

    -   「ぶどう園の農夫」のたとえ（12:1-12）vs （おそらく）祭司長、律法学者、長老たち（27）

        -   イエス：12:9 このぶどう園の主人は、どうするだろうか。彼は出てきて、農夫たちを殺し、ぶどう園を他の人々に与えるであろう。

        -   人々：12:12 彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。

    -   皇帝への税金（12:13-17）vs パリサイ人やヘロデ党の者数人

        -   12:14b カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか

        -   12:17b カイザルのものはカイザルに、神のものは神に返しなさい

2.  サドカイ人は、どのような人たちですか。復活についてはどう考えていますか。（18）

    -   18 復活ということはないと主張していたサドカイ人たちが、イエスのもとにきて質問した、

    -   荒井献：伝統主義・保守主義の立場をとり、「モーセ律法」ないしは「モーセ五書」のみを聖文書として、ここに認められない、あるいはこれ以後の時代に成立したと言われる新思想ー例えば律法の敷衍解釈による法の細則・天使論・復活思想などーを一切認めなかった。もっとも、政治的には、彼らがユダヤ社会の経済的上層と密着していただけに、外国支配勢力に対しては一般的に協調策をとっている。そのために、たとえば復活思想の否認は、当時における世界体制の思想であるヘレニズム・ローマ思想を受容した結果であるとも説明できる。

    -   榊原康夫：政治団体に近く、当時の最高議会議員の大半を占めていました。彼らはそのように、時の権力者と結びつく世俗主義者であるために、時代の流行に敏感な進歩主義者・合理主義者でもありました。それで、一応ユダヤ教を信じはしても、モーセの律法にしるされた明白な定め以外は認めません。

    -   使徒行伝23章8節 元来、サドカイ人は、復活とか天使とか霊とかは、いっさい存在しないと言い、パリサイ人は、それらは、みな存在すると主張している。

    -   ヨセフス「ユダヤ人古代史」

        -   [13-10-6](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0146%3Abook%3D13%3Awhiston+chapter%3D10%3Awhiston+section%3D6) 後半：パリサイ人は、モーセの律法には書かれていない、先祖から受け継いだ多くの慣習を民衆に伝えてきたということである。そのため、サドカイ人はそれを拒絶し、書かれた言葉にある慣習は義務であるとみなすべきだが、先祖の伝統に由来するものは守るべきではないと言うのである。そして、これらのことに関して、彼らの間には大きな論争と不和が生じており、サドカイ派は富裕層以外を説得できず、民衆の支持も得られないが、パリサイ派は大衆の支持を得ている。(Google Chrome 翻訳)

        -   [18-1-4](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0146%3Abook%3D18%3Awhiston+chapter%3D1%3Awhiston+section%3D4) しかし、サドカイ派の教えはこうです。魂は肉体と共に死ぬということです。彼らは、律法が命じていること以外は何事も守ろうとしません。なぜなら、彼らは、よく会う哲学の教師たちと議論することが美徳であると考えているからです。しかし、この教えを受け入れるのは少数の人たち、それでも最も高貴な人たちだけです。しかし、彼らは自分ではほとんど何もすることができません。なぜなら、時には不本意に、そして強制的にそうならざるを得ないのですが、行政官になると、彼らはパリサイ人の観念に溺れるからです。そうでなければ、大衆はそれを受け入れないでしょうから。(Google Chrome 翻訳)

    -   死人の復活に関する教えはイザヤ26:19、ダニエル12:2 に至るまで現れなかったからである。

        -   イザヤ26:19　あなたの死者は生き、彼らのなきがらは起きる。ちりに伏す者よ、さめて喜びうたえ。あなたの露は光の露であって、／それを亡霊の国の上に降らされるからである。

        -   ダニエル12:2　また地のちりの中に眠っている者のうち、多くの者は目をさますでしょう。そのうち永遠の生命にいたる者もあり、また恥と、限りなき恥辱をうける者もあるでしょう。

3.  サドカイ人たちは、どんな質問をしますか。（19-23）

    -   19 「先生、モーセは、わたしたちのためにこう書いています、『もし、ある人の兄が死んで、その残された妻に、子がない場合には、弟はこの女をめとって、兄のために子をもうけねばならない』。20 ここに、七人の兄弟がいました。長男は妻をめとりましたが、子がなくて死に、21 次男がその女をめとって、また子をもうけずに死に、三男も同様でした。22 こうして、七人ともみな子孫を残しませんでした。最後にその女も死にました。23 復活のとき、彼らが皆よみがえった場合、この女はだれの妻なのでしょうか。七人とも彼女を妻にしたのですが」。

    -   \[DQ\] どのようなモーセのことばに言及していますか。

    -   \[A\] 申命記25:5(-10) 兄弟が一緒に住んでいて、そのうちのひとりが死んで子のない時は、その死んだ者の妻は出て、他人にとついではならない。その夫の兄弟が彼女の所にはいり、めとって妻とし、夫の兄弟としての道を彼女につくさなければならない。

    -   目的

        1.  家族の名称が継続された。

        2.  家族の財産が家族の内部にとどまった。

    -   レビラト婚（Levirate marriage）

        -   Wikipedia ([日](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%93%E3%83%A9%E3%83%88%E5%A9%9A)）（[E](https://en.wikipedia.org/wiki/Levirate_marriage)）寡婦が死亡した夫の兄弟と結婚する慣習。レビラトは、ラテン語で夫の兄弟を意味するレウィル(levir)に由来する。レビレート婚とも。

    -   \[DQ\] この人たちはなぜこのような質問をするのですか。

    -   \[A\] モーセ五書には書いておらず、今の世には何も関係がない合理性がない。

    -   \[A\] 未亡人の救済の法律が、かえってあの世で彼女を困らせるのは妙だ。（榊原康夫）

    -   \[DQ\] 霊魂不滅という、哲学思想からの問いなのでしょうか。

4.  イエスはサドカイ人たちがどんな思い違いをしていると言っていますか。（24, 25）

    -   24 イエスは言われた、「あなたがたがそんな思い違いをしているのは、聖書も神の力も知らないからではないか。25 彼らが死人の中からよみがえるときには、めとったり、とついだりすることはない。彼らは天にいる御使のようなものである。

    -   復活が起こり、ひとがよみがえるとき、肉体的生活の古い法則はもはや通用しない、よみがえったものは、天使のようであり、結婚するとか、結婚したとかいうような肉体的な事柄は、その事柄の中に入っていない。（バークレイ）

        -   エノク書、バルクの黙示の中にも似たような記述あり。（エノク書10:17-19）

        -   来たるべき命は、この世の言葉では考えることができない。

    -   来世では、出産がなく、したがって結婚はない。その生命は神から受けるので、だれがしかの子といわれず、「神の子」と呼ばれる。この相違を知らないのは、聖書も神の力も知らぬ宗教的無知から生じている。（榊原康夫）

    -   \[参照\] ルカ20:36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。

5.  イエスは、復活について、どのような聖書を引用していますか。（26,27）

    -   26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている」。

    -   \[DQ\] イエスは旧約聖書からの引用でなにを伝えているのでしょうか。

    -   \[Ref\] 出エジプト3:6 また言われた、「わたしは、あなたの先祖の神、アブラハムの神、イサクの神、ヤコブの神である」。モーセは神を見ることを恐れたので顔を隠した。

    -   もし、神がこれらの族長たちの神であれば、生きています神は生きている人々の神であり、存在せず、死んだ者の神ではないので、それは、彼らがなお生きておらねばならないことを意味する。（バークレイ）

    -   \[DQ\] 「神は死んだ者の神ではなく、生きている者の神である。」は何を伝えているのでしょうか。

    -   生きるのはすべて神に対して生きる。（榊原康夫）

        -   ヨハネ11:25-26 イエスは彼女に言われた、「わたしはよみがえりであり、命である。わたしを信じる者は、たとい死んでも生きる。26 また、生きていて、わたしを信じる者は、いつまでも死なない。あなたはこれを信じるか」。

        -   （真に生きるということ）2テサロニケ3:11 ところが、聞くところによると、あなたがたのうちのある者は怠惰な生活を送り、働かないで、ただいたずらに動きまわっているとのことである。

        -   （生ける屍とは異なる生きから）1テモテ5:6 これに反して、みだらな生活をしているやもめは、生けるしかばねにすぎない。

        -   （永遠の神との関係）ハバクク1:12 わが神、主、わが聖者よ。あなたは永遠からいますかたではありませんか。わたしたちは死んではならない。主よ、あなたは彼らをさばきのために備えられた。岩よ、あなたは彼らを懲らしめのために立てられた。

    -   今、生命の源泉たる神との関わり方をかえるべき。

        -   彼らはもう死ぬことができない。

            -   ルカ20:36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。

6.  イエスは、この箇所で復活についてどのようなことを教えているのでしょうか。

    -   \[DQ\] マタイとルカには、どのような反応が描かれていますか。

        -   マタイ22:33 群衆はこれを聞いて、イエスの教に驚いた。

        -   ルカ20:39,40 律法学者のうちのある人々が答えて言った、「先生、仰せのとおりです」。40 彼らはそれ以上何もあえて問いかけようとしなかった。

    -   \[DQ\] イエスの復活、神理解について、この箇所から分かることを上げてみましょう。

    -   \[DQ\] 死んだひとが生き返ること、イエスの復活、一般の（イエス以外の）ひとの死後の復活、神との関係において、生き続けること、それぞれの関係と、それぞれの意味についてはどう考えたらよいのでしょうか。

### メモ

-   問い：サドカイ人は、復活を信ぜず、パリサイ人は、それを信じていたようだが（使徒23:6）なぜ、そのように信じ、何を根拠にそう信じていたのだろうか。そのように信じるような経緯もしりたい。復活を信じる、パリサイ人は、サドカイ人の12:19-23節の問いに、どう答えていたのだろうか。

-   問い：アブラハム、イサク、ヤコブは生きていると証言しているようだが、イエスは復活についてどのような理解をもっていたのだろうか。イエス自身が「よみがえる」ことについて何回か述べられているが（マルコ8:31, 9:9-10, 9:31, 10:34）、イエスは自身の復活についてどのように認識していたのだろうか。

-   共観福音書（マルコとの）差異：マタイは、最後に反応を記述した「33 群衆はこれを聞いて、イエスの教に驚いた。」のみが加わっているが、本文は基本的に同じとしてよい。ルカは、イエスの答えの中に、復活に関する理解の差異がある。最後の反応が異なるが、これは、ルカでは、次の「最も重要な戒め」が欠けており、並行箇所が「善いサマリア人」の前半に対応しており、議論としては、最後にしているので、マルコでは、「最も重要な戒め」の最後にある「それから後は、イエスにあえて問う者はなかった。」で閉じられている。復活に関する記述の違いは、重要である。まず、35節では、死人からの復活はすべての人ではなく「復活にあずかるにふさわしい者たち」となっている点、さらに、36節には「天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ない」と、マルコにはないことがが付け加えられている。

    -   ルカ20:35 かの世にはいって死人からの復活にあずかるにふさわしい者たちは、めとったり、とついだりすることはない。36 彼らは天使に等しいものであり、また復活にあずかるゆえに、神の子でもあるので、もう死ぬことはあり得ないからである。

    -   ルカ20:38b 人はみな神に生きるものだからである」。39 律法学者のうちのある人々が答えて言った、「先生、仰せのとおりです」。40 彼らはそれ以上何もあえて問いかけようとしなかった。

-   イエスは二種類の応答をしている。1つ目は、「死人の中からよみがえるときは、天にいる御使いのようなもので、めとったり、とついだりしない。」ということ、2つ目は、「神は死んだ者の神ではなく、生きている者の神であり、アブラハム、イサク、ヤコブも（神に対して）生きているのだということ、である。1つ目は、宣言であり、説明としては理解できるが、2つ目は、混乱を来すように思える。

-   イエスと共に生きる、神の子として生きるいのちは、この世の社会的な制度や規則に縛られるものではなく、復活を考える時には、拘束されない。また、主（神、神の子イエス）との交わり、主との結びつきは、現在から続く、永遠のものである。

-   イエスの聖書解釈には、驚かされる。本当に、これが、死人がよみがえることについて語られている箇所なのだろうか。

    -   37 死人がよみがえることは、モーセも柴の篇で、主を『アブラハムの神、イサクの神、ヤコブの神』と呼んで、これを示した。38 神は死んだ者の神ではなく、生きている者の神である。人はみな神に生きるものだからである」。

## 12:28-34 最も重要な戒め

> 28 ひとりの律法学者がきて、彼らが互に論じ合っているのを聞き、またイエスが巧みに答えられたのを認めて、イエスに質問した、「すべてのいましめの中で、どれが第一のものですか」。29 イエスは答えられた、「第一のいましめはこれである、『イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。30 心をつくし、精神をつくし、思いをつくし、力をつくして、主なるあなたの神を愛せよ』。31 第二はこれである、『自分を愛するようにあなたの隣り人を愛せよ』。これより大事ないましめは、ほかにない」。32 そこで、この律法学者はイエスに言った、「先生、仰せのとおりです、『神はひとりであって、そのほかに神はない』と言われたのは、ほんとうです。33 また『心をつくし、知恵をつくし、力をつくして神を愛し、また自分を愛するように隣り人を愛する』ということは、すべての燔祭や犠牲よりも、はるかに大事なことです」。34 イエスは、彼が適切な答をしたのを見て言われた、「あなたは神の国から遠くない」。それから後は、イエスにあえて問う者はなかった。

### マタイ 22:34-40

> 34 さて、パリサイ人たちは、イエスがサドカイ人たちを言いこめられたと聞いて、一緒に集まった。35 そして彼らの中のひとりの律法学者が、イエスをためそうとして質問した、36 「先生、律法の中で、どのいましめがいちばん大切なのですか」。37 イエスは言われた、「『心をつくし、精神をつくし、思いをつくして、主なるあなたの神を愛せよ』。38 これがいちばん大切な、第一のいましめである。39 第二もこれと同様である、『自分を愛するようにあなたの隣り人を愛せよ』。40 これらの二つのいましめに、律法全体と預言者とが、かかっている」。

### ルカ 10:25-28

> 25 するとそこへ、ある律法学者が現れ、イエスを試みようとして言った、「先生、何をしたら永遠の生命が受けられましょうか」。26 彼に言われた、「律法にはなんと書いてあるか。あなたはどう読むか」。27 彼は答えて言った、「『心をつくし、精神をつくし、力をつくし、思いをつくして、主なるあなたの神を愛せよ』。また、『自分を愛するように、あなたの隣り人を愛せよ』とあります」。28 彼に言われた、「あなたの答は正しい。そのとおり行いなさい。そうすれば、いのちが得られる」。

[マルコによる福音書12章28-34節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_28-34.pdf)

### 問い

1.  これまで、神殿でどのような人たちとどのようなことについて話したか復習しましょう。（11:27-12:27）

2.  この律法学者はどのような動機からどのような質問をしていますか。（28）

3.  イエスはなんと答えていますか。（29-31）

4.  「あなたの神である主を愛せよ」「隣人を自分と同じように愛せよ」とはどのようないましめですか。（29-31）

5.  この律法学者は、イエスの答えを聞いて、どのように語り、イエスはこの律法学者にどう伝えますか。（32-34）

6.  あなたは、イエスが神殿で語ったことから、どのようなことを学びましたか。

### 参照

-   出エジプト記20:3-17 あなたはわたしのほかに、なにものをも神としてはならない。4 あなたは自分のために、刻んだ像を造ってはならない。上は天にあるもの、下は地にあるもの、また地の下の水のなかにあるものの、どんな形をも造ってはならない。5 それにひれ伏してはならない。それに仕えてはならない。あなたの神、主であるわたしは、ねたむ神であるから、わたしを憎むものには、父の罪を子に報いて、三、四代に及ぼし、6 わたしを愛し、わたしの戒めを守るものには、恵みを施して、千代に至るであろう。7 あなたは、あなたの神、主の名を、みだりに唱えてはならない。主は、み名をみだりに唱えるものを、罰しないでは置かないであろう。8 安息日を覚えて、これを聖とせよ。9 六日のあいだ働いてあなたのすべてのわざをせよ。10 七日目はあなたの神、主の安息であるから、なんのわざをもしてはならない。あなたもあなたのむすこ、娘、しもべ、はしため、家畜、またあなたの門のうちにいる他国の人もそうである。11 主は六日のうちに、天と地と海と、その中のすべてのものを造って、七日目に休まれたからである。それで主は安息日を祝福して聖とされた。12 あなたの父と母を敬え。これは、あなたの神、主が賜わる地で、あなたが長く生きるためである。13 あなたは殺してはならない。14 あなたは姦淫してはならない。15 あなたは盗んではならない。16 あなたは隣人について、偽証してはならない。17 あなたは隣人の家をむさぼってはならない。隣人の妻、しもべ、はしため、牛、ろば、またすべて隣人のものをむさぼってはならない」。

-   バークレイ

    -   ヒルレル（片足で立っている間に律法の全体を教えてくれるようにとの依頼にこたえ）：あなたが自分自身にされるのを憎むことを、あなたの隣人にするな。これが律法の全体である。残りはその注解である。行って学べ。

    -   アキバ：『隣人をあなた自身のように愛せよ』ーこれが一番大きい、一般的な律法である。

    -   義人シモン：三つのことの上に世界は成り立っているー律法と、礼拝と、愛の働きの上に。

    -   サムラー：モーセがシナイ山によいて６１３の法則を授けられた、それは太陽年の日数に従って３６５（榊原：禁止命令），人間の世代数に従って２４８（榊原：積極命令）を受けた。

    -   ダビデ（詩篇１５篇）主よ、あなたの幕屋に宿るものはだれですか、あなたの聖なる山に住むべき者はだれですか。

        1.  直く歩む者。

        2.  義を行う者。

        3.  心から真実を語る者。

        4.  その舌をもってそしらぬ者。

        5.  その友に悪をなさざる者。

        6.  その隣り人に対するそしりを取りあざける者。

        7.  その目が神に捨てられた者を卑しめる者。

        8.  主を恐れる者を尊ぶ者。

        9.  誓ったことは自分の損害になっても変えない者。

        10. 利益をとって金銭を貸さない者。

        11. 罪のない者の不利をはからない者。

    -   イザヤ（イザヤ33:15）

        1.  正しく歩む者。

        2.  正直に語る者。

        3.  しえたげて得た利を卑しめる者。

        4.  手を振って、まいないを取らない者。

        5.  耳をふさいで地を流す謀略を聞かない者。

        6.  目を閉じて悪を見ない者。

    -   ミカ（ミカ6:8）主のあなたに求められることは、

        1.  公義をおこない。

        2.  いつくしみを愛し。

        3.  へりくだってあなたの神と共に歩むことである。

    -   イザヤ（イザヤ56:1）

        1.  あなたがたは公平を守れ。

        2.  そして正義を行え。

    -   ハバクク（ハバクク2:4）

        -   義人はその信仰によって生きる。

    -   アウグスティヌス（354-430）

        -   神を愛しーそして、あなたの好きなようにしなさい。

    -   十二族長の遺訓（[Early Christian Writings](https://www.earlychristianwritings.com): [The Testaments of the Twelve Patriarchs](https://www.earlychristianwritings.com/text/patriarchs-charles.html)）

        -   [イッサカル](ref_docs/twelve_patriarchs.qmd#Issachar)の遺訓 （THE TESTAMENT OF ISSACHAR, THE FIFTH SON OF JACOB AND LEAH）5:2：主を愛し、あなたの隣人を愛せよ。貧しき者と弱き者に同情せよ。But love the Lord and your neighbour, Have compassion on the poor and weak.

        -   [イッサカル](ref_docs/twelve_patriarchs.qmd#Issachar)の遺訓（THE TESTAMENT OF ISSACHAR, THE FIFTH SON OF JACOB AND LEAH）7:6：わたしは主を愛した、同様に、すべての人々を心を尽くして愛した。I loved the Lord; Likewise also every man with all my heart.

        -   [ダン](ref_docs/twelve_patriarchs.qmd#Dan)の遺訓（THE TESTAMENT OF DAN, THE SEVENTH SON OF JACOB AND BILHAH.）5:3：あなたの全生涯をかけて主を愛せよ。また、真実の心をもってお互いに愛し合え。Love the Lord through all your life, And one another with a true heart.

-   シェマ（聞け）聖句箱（小さな革の小箱）の中に入れ、祈る時に、身につけた。

    -   申命記6:4-9 イスラエルよ聞け。われわれの神、主は唯一の主である。5 あなたは心をつくし、精神をつくし、力をつくして、あなたの神、主を愛さなければならない。6 きょう、わたしがあなたに命じるこれらの言葉をあなたの心に留め、7 努めてこれをあなたの子らに教え、あなたが家に座している時も、道を歩く時も、寝る時も、起きる時も、これについて語らなければならない。8 またあなたはこれをあなたの手につけてしるしとし、あなたの目の間に置いて覚えとし、9 またあなたの家の入口の柱と、あなたの門とに書きしるさなければならない。

    -   申命記11:13-21 もし、きょう、あなたがたに命じるわたしの命令によく聞き従って、あなたがたの神、主を愛し、心をつくし、精神をつくして仕えるならば、14 主はあなたがたの地に雨を、秋の雨、春の雨ともに、時にしたがって降らせ、穀物と、ぶどう酒と、油を取り入れさせ、15 また家畜のために野に草を生えさせられるであろう。あなたは飽きるほど食べることができるであろう。16 あなたがたは心が迷い、離れ去って、他の神々に仕え、それを拝むことのないよう、慎まなければならない。17 おそらく主はあなたがたにむかい怒りを発して、天を閉ざされるであろう。そのため雨は降らず、地は産物を出さず、あなたがたは主が賜わる良い地から、すみやかに滅びうせるであろう。18 それゆえ、これらのわたしの言葉を心と魂におさめ、またそれを手につけて、しるしとし、目の間に置いて覚えとし、19 これを子供たちに教え、家に座している時も、道を歩く時も、寝る時も、起きる時も、それについて語り、20 また家の入口の柱と、門にそれを書きしるさなければならない。21 そうすれば、主が先祖たちに与えようと誓われた地に、あなたがたの住む日数およびあなたがたの子供たちの住む日数は、天が地をおおう日数のように多いであろう。

    -   民数記15:37-41 主はまたモーセに言われた、38 「イスラエルの人々に命じて、代々その衣服のすその四すみにふさをつけ、そのふさを青ひもで、すその四すみにつけさせなさい。39 あなたがたが、そのふさを見て、主のもろもろの戒めを思い起して、それを行い、あなたがたが自分の心と、目の欲に従って、みだらな行いをしないためである。40 こうして、あなたがたは、わたしのもろもろの戒めを思い起して、それを行い、あなたがたの神に聖なる者とならなければならない。41 わたしはあなたがたの神、主であって、あなたがたの神となるために、あなたがたをエジプトの国から導き出した者である。わたしはあなたがたの神、主である」。

    -   シェマについて

        -   夕方の何時からシェマをとなえればよいか。祭司たちが挙祭を食べにはいってから第一の刻の初めまで。そうラビ・エリエゼルは言った」（ミシュナー：ベーラーコート1:1）朝の何時からシェマをとなえればよいか。青と白とを見分けられるようになったら即刻。ラビ・エリエゼルは、青と緑をと言う。そして日の出前に終わらねばならぬ。（2）

    -   ヤコブ2:19 あなたは、神はただひとりであると信じているのか。それは結構である。悪霊どもでさえ、信じておののいている。

-   レビ記19:18 あなたはあだを返してはならない。あなたの民の人々に恨みをいだいてはならない。あなた自身のようにあなたの隣人を愛さなければならない。わたしは主である。

    -   本来の背景としては、自分の仲間のユダヤ人について。

    -   ローマ13:9 「姦淫するな、殺すな、盗むな、むさぼるな」など、そのほかに、どんな戒めがあっても、結局「自分を愛するようにあなたの隣り人を愛せよ」というこの言葉に帰する。

    -   ガラテヤ5:14 律法の全体は、「自分を愛するように、あなたの隣り人を愛せよ」というこの一句に尽きるからである。

    -   ヤコブ2:8 しかし、もしあなたがたが、「自分を愛するように、あなたの隣り人を愛せよ」という聖書の言葉に従って、このきわめて尊い律法を守るならば、それは良いことである。

### 記録

-   日時：2024年10月31日午後7時半〜9時半

-   出席（対面）3名、参加（遠隔）2名

### 問いについて

1.  これまで、神殿でどのような人たちとどのようなことについて話したか復習しましょう。（11:27-12:27）

    -   権威についての問答（11:27-33）vs 祭司長、律法学者、長老たち（27）

        -   問：11:28「何の権威によってこれらの事をするのですか。だれが、そうする権威を授けたのですか」。

        -   イエス：11:30 ヨハネのバプテスマは天からであったか、人からであったか、答えなさい」。

    -   「ぶどう園の農夫」のたとえ（12:1-12）vs （おそらく）祭司長、律法学者、長老たち（27）

        -   イエス：12:9 このぶどう園の主人は、どうするだろうか。彼は出てきて、農夫たちを殺し、ぶどう園を他の人々に与えるであろう。

        -   人々：12:12 彼らはいまの譬が、自分たちに当てて語られたことを悟ったので、イエスを捕えようとしたが、群衆を恐れた。そしてイエスをそこに残して立ち去った。

    -   皇帝への税金（12:13-17）vs パリサイ人やヘロデ党の者数人

        -   12:14b カイザルに税金を納めてよいでしょうか、いけないでしょうか。納めるべきでしょうか、納めてはならないのでしょうか

        -   12:17b カイザルのものはカイザルに、神のものは神に返しなさい

    -   復活についての問答（12:18-27）vs サドカイ人たち

        -   問：12:23 復活のとき、彼らが皆よみがえった場合、この女はだれの妻なのでしょうか。七人とも彼女を妻にしたのですが」。

        -   イエス：12:24,25 24 イエスは言われた、「あなたがたがそんな思い違いをしているのは、聖書も神の力も知らないからではないか。25 彼らが死人の中からよみがえるときには、めとったり、とついだりすることはない。彼らは天にいる御使のようなものである。

        -   イエス：12:26,27 26 死人がよみがえることについては、モーセの書の柴の篇で、神がモーセに仰せられた言葉を読んだことがないのか。『わたしはアブラハムの神、イサクの神、ヤコブの神である』とあるではないか。27 神は死んだ者の神ではなく、生きている者の神である。あなたがたは非常な思い違いをしている」。

2.  この律法学者はどのような動機からどのような質問をしていますか。（28）

    -   28 ひとりの律法学者がきて、彼らが互に論じ合っているのを聞き、またイエスが巧みに答えられたのを認めて、イエスに質問した、「すべてのいましめの中で、どれが第一のものですか」。

    -   \[DQ\] 何を聞きたいのでしょう。質問の意図は何でしょうか。マタイと、ルカではどのように表現していますか。

        -   マルコ：イエスが巧みに答えられたのを認めて、- 敬意が現れている。

        -   マタイ：イエスをためそうとして質問した

        -   ルカ：イエスを試みようとして

    -   \[A\] マルコの文章からは悪意は感じられない。マタイやルカでは「ためそうとして、試みようとして」とあるが、質問からすると、受け取り方の問題であり、悪意がなかった可能性もある。マルコが最初に書かれたとすると、ルカは背景が異なるかもしれないが、マタイにおいては、喜捨の、律法学者に対する敵愾心があるのかもしれない。

    -   \[DQ\] 質問については、マタイと、ルカからは、どのようなことがわかりますか。

        -   マルコ：先生、すべてのいましめの中で、どれが第一のものですか

        -   マタイ：先生、律法の中で、どのいましめがいちばん大切なのですか

        -   ルカ：先生、何をしたら永遠の生命が受けられましょうか

3.  イエスはなんと答えていますか。（29-31）

    -   29 イエスは答えられた、「第一のいましめはこれである、『イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。30 心をつくし、精神をつくし、思いをつくし、力をつくして、主なるあなたの神を愛せよ』。31 第二はこれである、『自分を愛するようにあなたの隣り人を愛せよ』。これより大事ないましめは、ほかにない」。

    -   申命記6:4,5 イスラエルよ聞け。われわれの神、主は唯一の主である。5 あなたは心をつくし、精神をつくし、力をつくして、あなたの神、主を愛さなければならない。

    -   レビ記19:18 あなたはあだを返してはならない。あなたの民の人々に恨みをいだいてはならない。あなた自身のようにあなたの隣人を愛さなければならない。わたしは主である。

        -   「あなたの民」とあり、基本的には、隣人は「同胞」を意味すると理解されており、それが当然であったと思われる。

    -   マルコは、シェマーの「イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。」から初めているが、マタイでは、それが省略されている。また、「力を尽くし」も省略されている。また、マルコ、マタイ、ルカとも、申命記にない「思いをつくし」が挿入されている。しかし、律法学者のことばは、旧約聖書に従っているのか、「思いをつくし」がない。

    -   \[DQ\] この違いは、大したことはないのだろうか。どのような意図があるのだろうか。

    -   \[DQ\]「律法全体と預言者は、この二つの掟に基づいている。」とはどのような意味でしょうか。

4.  「あなたの神である主を愛せよ」「隣人を自分と同じように愛せよ」とはどのようないましめですか。（29-31）

    -   29 イエスは答えられた、「第一のいましめはこれである、『イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。30 心をつくし、精神をつくし、思いをつくし、力をつくして、主なるあなたの神を愛せよ』。31 第二はこれである、『自分を愛するようにあなたの隣り人を愛せよ』。これより大事ないましめは、ほかにない」。

    -   \[DQ\] なぜ第一の（最も重要な）戒めは一つではなく二つなのでしょうか。なぜ二つとも必要なのでしょうか。

    -   \[DQ\] ２つ独立のいましめでしょうか。関連しているのでしょうか。

    -   \[HS\] たいせつなひと（かた）をたいせつにすることは、たいせつなひと（かた）のたいせつなひとをたいせつにすること。

    -   \[参照\] １ヨハネ4:19-21 わたしたちが愛し合うのは、神がまずわたしたちを愛して下さったからである。20 「神を愛している」と言いながら兄弟を憎む者は、偽り者である。現に見ている兄弟を愛さない者は、目に見えない神を愛することはできない。21 神を愛する者は、兄弟をも愛すべきである。この戒めを、わたしたちは神から授かっている。

5.  この律法学者は、イエスの答えを聞いて、どのように語り、イエスはこの律法学者にどう伝えますか。（32-34）

    -   32 そこで、この律法学者はイエスに言った、「先生、仰せのとおりです、『神はひとりであって、そのほかに神はない』と言われたのは、ほんとうです。33 また『心をつくし、知恵をつくし、力をつくして神を愛し、また自分を愛するように隣り人を愛する』ということは、すべての燔祭や犠牲よりも、はるかに大事なことです」。34 イエスは、彼が適切な答をしたのを見て言われた、「あなたは神の国から遠くない」。それから後は、イエスにあえて問う者はなかった。

    -   \[参照\] サムエル記上15:22 サムエルは言った、／「主はそのみ言葉に聞き従う事を喜ばれるように、／燔祭や犠牲を喜ばれるであろうか。見よ、従うことは犠牲にまさり、／聞くことは雄羊の脂肪にまさる。

    -   \[参照\] ホセア6:6 わたしはいつくしみを喜び、犠牲を喜ばない。燔祭よりもむしろ神を知ることを喜ぶ。

    -   \[DQ\] 律法学者はどのように理解したのでしょうか。（32-33）

    -   \[DQ\] 「あなたは神の国から遠くない」とは、どのような意味なのでしょうか。（34b）

        -   \[A\] 文脈からは、十分な称賛だと考えてよいだろう。しかし、同時に、完璧ではないこと、つまり、イエスの理解からは、まだ、離れていることを示した言葉なのだろう。

    -   \[DQ\] なぜ人々は、イエスにこれ以上質問をしないのですか。（34c）

6.  あなたは、イエスが神殿で語ったことから、どのようなことを学びましたか。

    -   イエスが、それぞれの反対勢力からの問いに対して、適切に伝え（反論し）ていることを伝えている。

    -   ヨハネのバプテスマとも関連しており、主のみこころ、主の働きが背後にあることを伝えている。

    -   復活も、人間の興味よりも、神が生きているものの神であることを伝えることにより、神について伝えている。

    -   最後に、中心的な、生き方について伝えている。

### メモ

-   共観福音書の差異：マルコでは、「イエスが巧みに答えられたのを認めて、イエスに質問した」と始め、最後に、イエスが「あなたは神の国から遠くない」と言い、「それから後は、イエスにあえて問う者はなかった。」と書かれて対話が終わっている。しかし、マタイでは、「イエスをためそうとして質問した」と始めている。ルカでは、別の箇所、善いサマリア人のたとえの前におかれ、かつ、「何をしたら永遠の生命が受けられましょうか」（10:25b）との問いから始まり、イエスは、「律法にはなんと書いてあるか。あなたはどう読むか」（10:26b）と問い、律法学者が同じような答えをしている。まずこのことから、律法学者と、イエスが考える、最も重要ないましめは、共通していたことがわかる。

-   細かいことだが、イエスの答えも微妙に異なる。「思いをつくして with thy mind」が、申命記にないのに、共観福音書ではすべて入っていることに特別な意味があるとすると、驚きである。もし、そうであれば、感情や霊的なものだけでなく、知的、または理性的な面も含めているということだろうか。

-   イエスが「すべてのいましめの中で、どれが第一のものですか」と問われて答えている箇所である。「わたしたちの神は、唯一の神である。その主をあなたのすべてをもって愛せよ。自分を愛するようにあなたの隣人を愛せよ。」（要約）が、聖書の中心的な教えということだろうか。

-   「イスラエルよ、聞け。主なるわたしたちの神は、ただひとりの主である。」で、聖書は、そして、イエスは何を伝えているのだろうか。他の神を認めない、排他的であることを奨励しているのだろうか。

-   なぜ最も重要な戒めは一つではなく二つなのだろうか。二つとも絶対的に必要なのだろうか。二つのいましめは関連しているのだろうか、それとも独立なのだろうか。

-   \[HS\] 隣人とは、唯一の神、主の前で、わたしと、同じ関係のおかれているひとのこと。つまり、神様が愛しておられる一人ひとりのことである。たいせつなひと（かた）をたいせつにすることは、たいせつなひと（かた）のたいせつなひとをたいせつにすること。

    -   ヨハネ7:44-49 彼らのうちのある人々は、イエスを捕えようと思ったが、だれひとり手をかける者はなかった。45 さて、下役どもが祭司長たちやパリサイ人たちのところに帰ってきたので、彼らはその下役どもに言った、「なぜ、あの人を連れてこなかったのか」。46 下役どもは答えた、「この人の語るように語った者は、これまでにありませんでした」。47 パリサイ人たちが彼らに答えた、「あなたがたまでが、だまされているのではないか。48 役人たちやパリサイ人たちの中で、ひとりでも彼を信じた者があっただろうか。49 律法をわきまえないこの群衆は、のろわれている」。

    -   一般大衆「アム・ハーアレツ（土民・無学の衆）」イエスにとっては、深く憐れむ対象。

-   イエスが、それぞれの反対勢力からの問いに対して、適切に伝え（反論し）ていること、を伝えていて、ローマ帝国に処刑されたひとを救い主とする批判・非難に対して、当時のキリスト者に対する護教的な面も含まれているように思われる。

## 12:35-37 ダビデの子についての問答

> 35 イエスが宮で教えておられたとき、こう言われた、「律法学者たちは、どうしてキリストをダビデの子だと言うのか。36 ダビデ自身が聖霊に感じて言った、／『主はわが主に仰せになった、／あなたの敵をあなたの足もとに置くときまでは、／わたしの右に座していなさい』。37 このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。大ぜいの群衆は、喜んでイエスに耳を傾けていた。

### マタイ 22:41-45(-46)

> 41 パリサイ人たちが集まっていたとき、イエスは彼らにお尋ねになった、42 「あなたがたはキリストをどう思うか。だれの子なのか」。彼らは「ダビデの子です」と答えた。43 イエスは言われた、「それではどうして、ダビデが御霊に感じてキリストを主と呼んでいるのか。44 すなわち／『主はわが主に仰せになった、／あなたの敵をあなたの足もとに置くときまでは、／わたしの右に座していなさい』。45 このように、ダビデ自身がキリストを主と呼んでいるなら、キリストはどうしてダビデの子であろうか」。46 イエスにひと言でも答えうる者は、なかったし、その日からもはや、進んでイエスに質問する者も、いなくなった。

### ルカ 20:41-44

> 41 イエスは彼らに言われた、「どうして人々はキリストをダビデの子だと言うのか。42 ダビデ自身が詩篇の中で言っている、／『主はわが主に仰せになった、43 あなたの敵をあなたの足台とする時までは、／わたしの右に座していなさい』。44 このように、ダビデはキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。

[マルコによる福音書12章35-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_35-37.pdf)

### 問い

1.  イエスは、どこで、どのようなことについて話し始めますか。（35）

2.  ダビデは、どのようなひとですか。

3.  イエスは、これまでに、ダビデの子と呼ばれたことはありますか。

4.  イエスは、どのように説明しますか。（36,37a）

5.  イエスは、何を伝えているのでしょうか。（36,37a）

6.  群衆は、どのように、イエスのことばを聞いていますか。（37b）

### 参照

-   メシア מָשִׁיחַ（ギリシャ語はキリスト、油注がれたもの。ここでは定冠詞がつき、ὁ Χριστὸς）マルコにおける「キリスト」

    -   マルコ 1:1　神の子イエス・キリストの福音のはじめ。

    -   マルコ 8:29　そこでイエスは彼らに尋ねられた、「それでは、あなたがたはわたしをだれと言うか」。ペテロが答えて言った、「あなたこそキリストです」。

    -   マルコ 9:41　だれでも、キリストについている者だというので、あなたがたに水一杯でも飲ませてくれるものは、よく言っておくが、決してその報いからもれることはないであろう。

    -   マルコ 12:35　イエスが宮で教えておられたとき、こう言われた、「律法学者たちは、どうしてキリストをダビデの子だと言うのか。

    -   （マルコ 12:37 このように、ダビデ自身がキリスト（彼）を主と呼んでいる。それなら、どうしてキリスト（彼）はダビデの子であろうか」。大ぜいの群衆は、喜んでイエスに耳を傾けていた。）

    -   マルコ 13:21　このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。大ぜいの群衆は、喜んでイエスに耳を傾けていた。

    -   マルコ 14:61　しかし、イエスは黙っていて、何もお答えにならなかった。大祭司は再び聞きただして言った、「あなたは、ほむべき者の子、キリストであるか」。

    -   マルコ 15:32　イスラエルの王キリスト、いま十字架からおりてみるがよい。それを見たら信じよう」。また、一緒に十字架につけられた者たちも、イエスをののしった。

-   メシア מָשִׁיחַ について信じられていたこと

    -   イザヤ9:1-7 しかし、苦しみにあった地にも、やみがなくなる。さきにはゼブルンの地、ナフタリの地にはずかしめを与えられたが、後には海に至る道、ヨルダンの向こうの地、異邦人のガリラヤに光栄を与えられる。2 暗やみの中に歩んでいた民は大いなる光を見た。暗黒の地に住んでいた人々の上に光が照った。3 あなたが国民を増し、その喜びを大きくされたので、／彼らは刈入れ時に喜ぶように、／獲物を分かつ時に楽しむように、／あなたの前に喜んだ。4 これはあなたが彼らの負っているくびきと、／その肩のつえと、しえたげる者のむちとを、／ミデアンの日になされたように折られたからだ。5 すべて戦場で、歩兵のはいたくつと、／血にまみれた衣とは、／火の燃えくさとなって焼かれる。6 ひとりのみどりごがわれわれのために生れた、／ひとりの男の子がわれわれに与えられた。まつりごとはその肩にあり、／その名は、「霊妙なる議士、大能の神、／とこしえの父、平和の君」ととなえられる。7 そのまつりごとと平和とは、増し加わって限りなく、／ダビデの位に座して、その国を治め、／今より後、とこしえに公平と正義とをもって／これを立て、これを保たれる。万軍の主の熱心がこれをなされるのである。

    -   イザヤ11:1-9 エッサイの株から一つの芽が出、／その根から一つの若枝が生えて実を結び、2 その上に主の霊がとどまる。これは知恵と悟りの霊、深慮と才能の霊、／主を知る知識と主を恐れる霊である。3 彼は主を恐れることを楽しみとし、／その目の見るところによって、さばきをなさず、／その耳の聞くところによって、定めをなさず、4 正義をもって貧しい者をさばき、／公平をもって国のうちの／柔和な者のために定めをなし、／その口のむちをもって国を撃ち、／そのくちびるの息をもって悪しき者を殺す。5 正義はその腰の帯となり、／忠信はその身の帯となる。6 おおかみは小羊と共にやどり、／ひょうは子やぎと共に伏し、／子牛、若じし、肥えたる家畜は共にいて、／小さいわらべに導かれ、7 雌牛と熊とは食い物を共にし、／牛の子と熊の子と共に伏し、／ししは牛のようにわらを食い、8 乳のみ子は毒蛇のほらに戯れ、／乳離れの子は手をまむしの穴に入れる。9 彼らはわが聖なる山のどこにおいても、そこなうことなく、／やぶることがない。水が海をおおっているように、／主を知る知識が地に満ちるからである。

    -   エレミヤ23:5-8 主は仰せられる、見よ、わたしがダビデのために一つの正しい枝を起す日がくる。彼は王となって世を治め、栄えて、公平と正義を世に行う。 6 その日ユダは救を得、イスラエルは安らかにおる。その名は『主はわれわれの正義』ととなえられる。7 主は言われる、それゆえ見よ、人々は『イスラエルの民をエジプトの地から導き出された主は生きておられる』とまた言わないで、8 『イスラエルの家の子孫を北の地と、そのすべて追いやられた地から導き出された神は生きておられる』という日がくる。その時、彼らは自分の地に住んでいる」。

    -   エレミヤ33:14-18 主は言われる、見よ、わたしがイスラエルの家とユダの家に約束したことをなし遂げる日が来る。15 その日、その時になるならば、わたしはダビデのために一つの正しい枝を生じさせよう。彼は公平と正義を地に行う。16 その日、ユダは救を得、エルサレムは安らかにおる。その名は『主はわれわれの正義』ととなえられる。17 主はこう仰せられる、イスラエルの家の位に座する人がダビデの子孫のうちに欠けることはない。

    -   エゼキエル23:23-27 わたしは彼らの上にひとりの牧者を立てる。すなわちわがしもべダビデである。彼は彼らを養う。彼は彼らを養い、彼らの牧者となる。24 主なるわたしは彼らの神となり、わがしもべダビデは彼らのうちにあって君となる。主なるわたしはこれを言う。25 わたしは彼らと平和の契約を結び、国の内から野獣を追い払う。彼らは心を安んじて荒野に住み、森の中に眠る。26 わたしは彼らおよびわが山の周囲の所々を祝福し、季節にしたがって雨を降らす。これは祝福の雨となる。27 野の木は実を結び、地は産物を出す。彼らは心を安んじてその国におり、わたしが彼らのくびきの棒を砕き、彼らを奴隷とした者の手から救い出す時、彼らはわたしが主であることを悟る。

    -   詩篇89:20-20 わたしはわがしもべダビデを得て、／これにわが聖なる油をそそいだ。21 わが手は常に彼と共にあり、／わが腕はまた彼を強くする。22 敵は彼をだますことなく、／悪しき者は彼を卑しめることはない。23 わたしは彼の前にもろもろのあだを打ち滅ぼし、／彼を憎む者どもを打ち倒す。24 わがまことと、わがいつくしみは彼と共にあり、／わが名によって彼の角は高くあげられる。

-   （福音書における）ダビデ

    -   マルコ 2:25 そこで彼らに言われた、「あなたがたは、ダビデとその供の者たちとが食物がなくて飢えたとき、ダビデが何をしたか、まだ読んだことがないのか。

    -   マルコ 11:10 今きたる、われらの父ダビデの国に、祝福あれ。いと高き所に、ホサナ」。

    -   マタイ 1:6 エッサイはダビデ王の父であった。ダビデはウリヤの妻によるソロモンの父であり、

    -   マタイ 1:17 だから、アブラハムからダビデまでの代は合わせて十四代、ダビデからバビロンへ移されるまでは十四代、そして、バビロンへ移されてからキリストまでは十四代である。

    -   マタイ 1:20 彼がこのことを思いめぐらしていたとき、主の使が夢に現れて言った、「ダビデの子ヨセフよ、心配しないでマリヤを妻として迎えるがよい。その胎内に宿っているものは聖霊によるのである。

    -   マタイ 12:3 そこでイエスは彼らに言われた、「あなたがたは、ダビデとその供の者たちとが飢えたとき、ダビデが何をしたか読んだことがないのか。(Cf. マルコ２:25)

    -   ルカ 1:27 この処女はダビデ家の出であるヨセフという人のいいなづけになっていて、名をマリヤといった。

    -   ルカ 1:32 彼は大いなる者となり、いと高き者の子と、となえられるでしょう。そして、主なる神は彼に父ダビデの王座をお与えになり、

    -   ルカ 1:69 わたしたちのために救の角を／僕ダビデの家にお立てになった。

    -   ルカ 2:4 ヨセフもダビデの家系であり、またその血統であったので、ガリラヤの町ナザレを出て、ユダヤのベツレヘムというダビデの町へ上って行った。

    -   ルカ 2:11 きょうダビデの町に、あなたがたのために救主がお生れになった。このかたこそ主なるキリストである。

    -   ルカ 3:31 メレヤ、メナ、マタタ、ナタン、ダビデ、

    -   ルカ 6:3 そこでイエスが答えて言われた、「あなたがたは、ダビデとその供の者たちとが飢えていたとき、ダビデのしたことについて、読んだことがないのか。(Cf. マルコ２:25)

-   ダビデの子（イエスに関して）

    -   マルコ 10:47,48　ところが、ナザレのイエスだと聞いて、彼は「ダビデの子イエスよ、わたしをあわれんでください」と叫び出した。48 多くの人々は彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子イエスよ、わたしをあわれんでください」。

    -   マルコ 12:35-37 イエスが宮で教えておられたとき、こう言われた、「律法学者たちは、どうしてキリストをダビデの子だと言うのか。36 ダビデ自身が聖霊に感じて言った、／『主はわが主に仰せになった、／あなたの敵をあなたの足もとに置くときまでは、／わたしの右に座していなさい』。37 このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。大ぜいの群衆は、喜んでイエスに耳を傾けていた。

    -   マタイ 1:1 アブラハムの子であるダビデの子、イエス・キリストの系図。

    -   マタイ 9:27 そこから進んで行かれると、ふたりの盲人が、「ダビデの子よ、わたしたちをあわれんで下さい」と叫びながら、イエスについてきた。（Cf. マルコ10:47,48）

    -   マタイ 12:23 すると群衆はみな驚いて言った、「この人が、あるいはダビデの子ではあるまいか」。

    -   マタイ 15:22 すると、そこへ、その地方出のカナンの女が出てきて、「主よ、ダビデの子よ、わたしをあわれんでください。娘が悪霊にとりつかれて苦しんでいます」と言って叫びつづけた。

    -   マタイ 20:30,31 すると、ふたりの盲人が道ばたにすわっていたが、イエスがとおって行かれると聞いて、叫んで言った、「主よ、ダビデの子よ、わたしたちをあわれんで下さい」。31 群衆は彼らをしかって黙らせようとしたが、彼らはますます叫びつづけて言った、「主よ、ダビデの子よ、わたしたちをあわれんで下さい」。

    -   マタイ 21:9 そして群衆は、前に行く者も、あとに従う者も、共に叫びつづけた、／「ダビデの子に、ホサナ。主の御名によってきたる者に、祝福あれ。いと高き所に、ホサナ」。(Cf. マルコ 11:9)

    -   マタイ 21:15 しかし、祭司長、律法学者たちは、イエスがなされた不思議なわざを見、また宮の庭で「ダビデの子に、ホサナ」と叫んでいる子供たちを見て立腹し、(Cf. マルコ 11:9)

    -   マタイ 22:42,43 「あなたがたはキリストをどう思うか。だれの子なのか」。彼らは「ダビデの子です」と答えた。43 イエスは言われた、「それではどうして、ダビデが御霊に感じてキリストを主と呼んでいるのか。(Cf. マルコ 12:35-37)

    -   ルカ 18:38,39 声をあげて、「ダビデの子イエスよ、わたしをあわれんで下さい」と言った。39 先頭に立つ人々が彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子よ、わたしをあわれんで下さい」。（Cf. マルコ10:47,48）

    -   ルカ 20:41-44 イエスは彼らに言われた、「どうして人々はキリストをダビデの子だと言うのか。42 ダビデ自身が詩篇の中で言っている、／『主はわが主に仰せになった、43 あなたの敵をあなたの足台とする時までは、／わたしの右に座していなさい』。44 このように、ダビデはキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。(Cf. マルコ 12:35-37)

    -   ヨハネ 7:42 キリストは、ダビデの子孫から、またダビデのいたベツレヘムの村から出ると、聖書に書いてあるではないか」と言った。

    -   ローマ1:3 御子に関するものである。御子は、肉によればダビデの子孫から生れ、

    -   テモテへの第二の手紙 2:8 ダビデの子孫として生れ、死人のうちからよみがえったイエス・キリストを、いつも思っていなさい。これがわたしの福音である。

### 記録

-   日時：2024年11月7日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  イエスは、どこで、どのようなことについて話し始めますか。（35）

    -   35 イエスが宮で教えておられたとき、こう言われた、「律法学者たちは、どうしてキリストをダビデの子だと言うのか。~35~ Καὶ ἀποκριθεὶς ὁ Ἰησοῦς ἔλεγεν διδάσκων ἐν τῷ ἱερῷ· πῶς λέγουσιν οἱ γραμματεῖς ὅτι ὁ χριστὸς υἱὸς Δαυίδ ἐστιν; 

    -   \[DQ\] 「キリスト」は何ですか。イエスのことですか。

    -   \[A\] ὁ χριστὸς となっていて、イエスのことではない。そのことを含めて訳すと「どうして学者は、来たるべき神の油注がれた王が、ダビデの子であると言えるか。」

2.  ダビデは、どのようなひとですか。

    -   サムエル記上・下

    -   イザヤ9:6,7 ひとりのみどりごがわれわれのために生れた、／ひとりの男の子がわれわれに与えられた。まつりごとはその肩にあり、／その名は、「霊妙なる議士、大能の神、／とこしえの父、平和の君」ととなえられる。7 そのまつりごとと平和とは、増し加わって限りなく、／ダビデの位に座して、その国を治め、／今より後、とこしえに公平と正義とをもって／これを立て、これを保たれる。万軍の主の熱心がこれをなされるのである。

    -   イザヤ11:1,2 エッサイの株から一つの芽が出、／その根から一つの若枝が生えて実を結び、2 その上に主の霊がとどまる。これは知恵と悟りの霊、深慮と才能の霊、／主を知る知識と主を恐れる霊である。

    -   エゼキエル23:23,24 わたしは彼らの上にひとりの牧者を立てる。すなわちわがしもべダビデである。彼は彼らを養う。彼は彼らを養い、彼らの牧者となる。24 主なるわたしは彼らの神となり、わがしもべダビデは彼らのうちにあって君となる。主なるわたしはこれを言う。

    -   詩篇89:20 わたしはわがしもべダビデを得て、／これにわが聖なる油をそそいだ。

3.  イエスは、これまでに、ダビデの子と呼ばれたことはありますか。

    -   マルコ 10:47,48　ところが、ナザレのイエスだと聞いて、彼は「ダビデの子イエスよ、わたしをあわれんでください」と叫び出した。48 多くの人々は彼をしかって黙らせようとしたが、彼はますます激しく叫びつづけた、「ダビデの子イエスよ、わたしをあわれんでください」。

4.  イエスは、どのように説明しますか。（36,37a）

    -   36 ダビデ自身が聖霊に感じて言った、／『主はわが主に仰せになった、／あなたの敵をあなたの足もとに置くときまでは、／わたしの右に座していなさい』。37 このように、ダビデ自身がキリストを主と呼んでいる。それなら、どうしてキリストはダビデの子であろうか」。

    -   詩篇110:0-1 ダビデの歌 1 主はわが主に言われる、／「わたしがあなたのもろもろの敵を／あなたの足台とするまで、わたしの右に座せよ」と。

    -   イエスはダビデとメシヤ（キリスト）の関係についてどのように言っていますか。

5.  イエスは、何を伝えているのでしょうか。

    -   \[DQ\] イエスは、キリストはダビデの子ということを否認しているのでしょうか。

    -   \[DQ\] イエスは、自分がダビデの子であることを否定しているのでしょうか。

    -   \[DQ\] キリストは、ダビデの子を超えるものである。ということでしょうか。

6.  群衆は、どのように、イエスのことばを聞いていますか。（37b）

    -   37b 大ぜいの群衆は、喜んでイエスに耳を傾けていた。

### メモ

-   共観福音書の差異：三つの共観福音書とも、イエスがこの問いを語りだしている。しかし、マタイでは、「パリサイ人たちが集まっていたとき」（マタイ22:41）となっており、さらに、イエスが「あなたがたはキリストをどう思うか。だれの子なのか」と問うたときに、パリサイ人が「ダビデの子です」と答えたように書かれている。マルコでは、そのように言っているのが「律法学者」であるとしており、マタイと通じる面があるが、ルカでは「人々」と一般化している。そのルカには、最後に人々の反応は書かれておらず、マルコでは「大ぜいの群衆は、喜んでイエスに耳を傾けていた。」とこのトピックを閉じ、マタイでは、「イエスにひと言でも答えうる者は、なかったし、その日からもはや、進んでイエスに質問する者も、いなくなった。」として、イエスの答えが素晴らしかったところに力点がおかれ、人々の反応とは、少し異なる表現になっている。ただ、マルコも、マタイも、ルカもこのあと、律法学者に注意せよとのくだりに移る。マタイは、そこでも「律法学者とパリサイ人」として、パリサイ人を明示している。

-   問い：キリストはダビデの子かという問いに対して三つの共観福音書ともイエスは否定している。イエスがダビデの子かという問いに関しては、福音書によってどのように記述されているのだろうか。

-   問い：マルコにおいても、一箇所、エリコで盲人が「ダビデの子イエスよ、わたしをあわれんでください」（10章47節、48節では「イエス」が省略）と叫んでいる箇所があるが、他の福音書と比較して非常に注意して「ダビデの子」とは書かれていないように見える。この箇所でも、ひとびとは、必ずしもメシアをダビデの子だとは考えてないように見える。実際には、どうだったのだろうか。

    -   マルコは、イエスがダビデの子かということに、一貫して否定しているように見える。次の項にあるように、ダビデの子と登場するのは、この箇所以外は、エリコで盲人が読んだ箇所だけである。ダビデのような、または、ダビデの家系から、救い主が現れることは、預言書には、書いてあるように見える。しかし、イエスは、そのような表現をここで、否定し、神に油注がれたメシアは、ダビデの子ではないと言っているように見える。

    -   マタイや、ルカの誕生物語などから見ると、生まれにおいては、イエスはダビデの系列、末裔であることが書かれており、かつ、ダビデの子と、キリストを明確に区別しているようには見えず、マルコとの差が見え、あまり注意していないように見える。単純に、ダビデの子キリストという定式のもとでキリストについて語られているように見える。パウロ文書においても、肉において、つまり生まれが、ダビデの末裔であることは、書かれており、そのことを強調はしないものの、この箇所を深く認識しているようには見えない。その意味でも、この箇所は、たいせつなのであろう。

## 12:38-40 律法学者を非難する

> 38 イエスはその教の中で言われた、「律法学者に気をつけなさい。彼らは長い衣を着て歩くことや、広場であいさつされることや、39 また会堂の上席、宴会の上座を好んでいる。40 また、やもめたちの家を食い倒し、見えのために長い祈をする。彼らはもっときびしいさばきを受けるであろう」。

### マタイ 23:1-36

> 1 そのときイエスは、群衆と弟子たちとに語って言われた、2 「律法学者とパリサイ人とは、モーセの座にすわっている。3 だから、彼らがあなたがたに言うことは、みな守って実行しなさい。しかし、彼らのすることには、ならうな。彼らは言うだけで、実行しないから。4 また、重い荷物をくくって人々の肩にのせるが、それを動かすために、自分では指一本も貸そうとはしない。5 そのすることは、すべて人に見せるためである。すなわち、彼らは経札を幅広くつくり、その衣のふさを大きくし、6 また、宴会の上座、会堂の上席を好み、7 広場であいさつされることや、人々から先生と呼ばれることを好んでいる。8 しかし、あなたがたは先生と呼ばれてはならない。あなたがたの先生は、ただひとりであって、あなたがたはみな兄弟なのだから。9 また、地上のだれをも、父と呼んではならない。あなたがたの父はただひとり、すなわち、天にいます父である。10 また、あなたがたは教師と呼ばれてはならない。あなたがたの教師はただひとり、すなわち、キリストである。11 そこで、あなたがたのうちでいちばん偉い者は、仕える人でなければならない。12 だれでも自分を高くする者は低くされ、自分を低くする者は高くされるであろう。13 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたは、天国を閉ざして人々をはいらせない。自分もはいらないし、はいろうとする人をはいらせもしない。14 〔偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたは、やもめたちの家を食い倒し、見えのために長い祈をする。だから、もっときびしいさばきを受けるに違いない。〕15 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたはひとりの改宗者をつくるために、海と陸とを巡り歩く。そして、つくったなら、彼を自分より倍もひどい地獄の子にする。16 盲目な案内者たちよ。あなたがたは、わざわいである。あなたがたは言う、『神殿をさして誓うなら、そのままでよいが、神殿の黄金をさして誓うなら、果す責任がある』と。17 愚かな盲目な人たちよ。黄金と、黄金を神聖にする神殿と、どちらが大事なのか。18 また、あなたがたは言う、『祭壇をさして誓うなら、そのままでよいが、その上の供え物をさして誓うなら、果す責任がある』と。19 盲目な人たちよ。供え物と供え物を神聖にする祭壇とどちらが大事なのか。20 祭壇をさして誓う者は、祭壇と、その上にあるすべての物とをさして誓うのである。21 神殿をさして誓う者は、神殿とその中に住んでおられるかたとをさして誓うのである。22 また、天をさして誓う者は、神の御座とその上にすわっておられるかたとをさして誓うのである。23 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。はっか、いのんど、クミンなどの薬味の十分の一を宮に納めておりながら、律法の中でもっと重要な、公平とあわれみと忠実とを見のがしている。それもしなければならないが、これも見のがしてはならない。24 盲目な案内者たちよ。あなたがたは、ぶよはこしているが、らくだはのみこんでいる。25 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。杯と皿との外側はきよめるが、内側は貪欲と放縦とで満ちている。26 盲目なパリサイ人よ。まず、杯の内側をきよめるがよい。そうすれば、外側も清くなるであろう。27 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたは白く塗った墓に似ている。外側は美しく見えるが、内側は死人の骨や、あらゆる不潔なものでいっぱいである。28 このようにあなたがたも、外側は人に正しく見えるが、内側は偽善と不法とでいっぱいである。29 偽善な律法学者、パリサイ人たちよ。あなたがたは、わざわいである。あなたがたは預言者の墓を建て、義人の碑を飾り立てて、こう言っている、30 『もしわたしたちが先祖の時代に生きていたなら、預言者の血を流すことに加わってはいなかっただろう』と。31 このようにして、あなたがたは預言者を殺した者の子孫であることを、自分で証明している。32 あなたがたもまた先祖たちがした悪の枡目を満たすがよい。33 へびよ、まむしの子らよ、どうして地獄の刑罰をのがれることができようか。34 それだから、わたしは、預言者、知者、律法学者たちをあなたがたにつかわすが、そのうちのある者を殺し、また十字架につけ、そのある者を会堂でむち打ち、また町から町へと迫害して行くであろう。35 こうして義人アベルの血から、聖所と祭壇との間であなたがたが殺したバラキヤの子ザカリヤの血に至るまで、地上に流された義人の血の報いが、ことごとくあなたがたに及ぶであろう。36 よく言っておく。これらのことの報いは、みな今の時代に及ぶであろう。

### ルカ 20:45-47, (11:37-54)

> 45 民衆がみな聞いているとき、イエスは弟子たちに言われた、46 「律法学者に気をつけなさい。彼らは長い衣を着て歩くのを好み、広場での敬礼や会堂の上席や宴会の上座をよろこび、47 やもめたちの家を食い倒し、見えのために長い祈をする。彼らはもっときびしいさばきを受けるであろう」。
>
> （参考）ルカ11:37-54 37 イエスが語っておられた時、あるパリサイ人が、自分の家で食事をしていただきたいと申し出たので、はいって食卓につかれた。38 ところが、食前にまず洗うことをなさらなかったのを見て、そのパリサイ人が不思議に思った。39 そこで主は彼に言われた、「いったい、あなたがたパリサイ人は、杯や盆の外側をきよめるが、あなたがたの内側は貪欲と邪悪とで満ちている。40 愚かな者たちよ、外側を造ったかたは、また内側も造られたではないか。41 ただ、内側にあるものをきよめなさい。そうすれば、いっさいがあなたがたにとって、清いものとなる。42 しかし、あなた方パリサイ人は、わざわいである。はっか、うん香、あらゆる野菜などの十分の一を宮に納めておりながら、義と神に対する愛とをなおざりにしている。それもなおざりにはできないが、これは行わねばならない。43 あなたがたパリサイ人は、わざわいである。会堂の上席や広場での敬礼を好んでいる。44 あなたがたは、わざわいである。人目につかない墓のようなものである。その上を歩いても人々は気づかないでいる」。45 ひとりの律法学者がイエスに答えて言った、「先生、そんなことを言われるのは、わたしたちまでも侮辱することです」。46 そこで言われた、「あなたがた律法学者も、わざわいである。負い切れない重荷を人に負わせながら、自分ではその荷に指一本でも触れようとしない。47 あなたがたは、わざわいである。預言者たちの碑を建てるが、しかし彼らを殺したのは、あなたがたの先祖であったのだ。48 だから、あなたがたは、自分の先祖のしわざに同意する証人なのだ。先祖が彼らを殺し、あなたがたがその碑を建てるのだから。49 それゆえに、『神の知恵』も言っている、『わたしは預言者と使徒とを彼らにつかわすが、彼らはそのうちのある者を殺したり、迫害したりするであろう』。50 それで、アベルの血から祭壇と神殿との間で殺されたザカリヤの血に至るまで、世の初めから流されてきたすべての預言者の血について、この時代がその責任を問われる。51 そうだ、あなたがたに言っておく、この時代がその責任を問われるであろう。52 あなたがた律法学者は、わざわいである。知識のかぎを取りあげて、自分がはいらないばかりか、はいろうとする人たちを妨げてきた」。53 イエスがそこを出て行かれると、律法学者やパリサイ人は、激しく詰め寄り、いろいろな事を問いかけて、54 イエスの口から何か言いがかりを得ようと、ねらいはじめた。 

[マルコによる福音書12章38-40節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_38-40.pdf)

### 問い

1.  イエスはどのようなことに注意しなさいと言っていますか。

2.  マタイ：

    1.  聴衆はどのような人たちですか。Who is the audience?

    2.  「モーセの座についている」とはどのような意味でしょうか。What does ''sit in Moses' seat'' mean?

    3.  「彼らの行いは、見倣ってはならない。言うだけで、実行しないからである。」とはどういうことでしょうか。何を行い、何を実行していないのでしょうか。What does ''You must be careful to do everything they tell you. But do not do what they do, for they do not practice what they preach.'' mean? What do they do and what don't they do?

    4.  4節ではどのようなことを批判しているのでしょうか。What does Jesus point out in verse 4?

    5.  5節から7節ではどのような批判をしていますか。What does Jesus point out in verses 5 to 7?

    6.  8節から10節でイエスは何を伝えようとしているのでしょうか。What is the Jesus' message in verses 8 to 10?

    7.  なぜ仕えることがたいせつなのでしょうか。Why will the greatest be a servant?

    8.  この箇所で、イエスはどのような生き方に対して警告し、どのような生き方を指し示しているのでしょうか。What does Jesus critices here? How should we live?

    9.  これらは誰に対して嘆いていますか。To whom is Jesus giving words of warnings?

    10. どのような事を嘆いていますか。いくつかに分けることができますか。What is Jesus warning these people about? Can you classify them?

    11. 「自分が入らないばかりか、入ろうとする人をも入らせない。」とは実際にどのようなことをしていたのでしょうか。What does ''You yourselves do not enter, nor will you let those enter who are trying to.'' mean? What are they doing?

    12. 「ものの見えない者たち」（口語・新改訳：盲目な案内者たち）は、何が見えていないのでしょうか。What can't these people see?

    13. 内側のことが言われていますが、なにを指摘しているのでしょうか。What does Jesus point out by cleaning inside?

    14. 「預言者の墓を建てたり、正しい人の記念碑を飾ったり」するのは良くないことなのでしょうか。Is it not good to ''build tombs for the prophets and decorate the graves of the righteous"?

    15. どうしたら「地獄の罰を免れること」ができるのでしょうか。How is it possible to ''escape being condemned to hell"?

    16. 偽善とは何でしょうか。What do you think is hypocrisy?

    17. 32節の「32:先祖が始めた悪事の仕上げをしたらどうだ。（口語 (v32)：あなたがたもまた先祖たちがした悪の枡目を満たすがよい。 ）」とはどのような意味でしょうか。What does verse 32 ''Go ahead, then, and complete what your ancestors started!'' mean?

    18. 前の文章とはどのようにつながっていますか。「だから」とはどういうことですか。How is the verse 34 related to 32-33 by the word 'therefore'?

    19. 34節ではどんなことが起こると言われていますか。According to verse 34, what will happen?

    20. アベルの血からゼカルヤの血とはどのようなものでしょうか。What does 'the blood of righteous Abel and Zecharia'?

    21. 「これらのことの結果はすべて、今の時代の者たちにふりかかってくる」とはどういう意味でしょうか。What does verse 36 'all this will come on this generation' mean?

3.  ルカ：

    1.  イエスは律法学者をどのように非難していますか。ぞれぞれどのような事を指摘しているのか考えてみましょう。(How is Jesus criticizing the scribes?)

    2.  なぜこのような人たちが人一倍厳しい裁きを受けるのでしょう。(Why is it dangerous to be responsible for \`\`turning people off" spiritually?)

    3.  ルカ11:37-54

        1.  イエスはパリサイ人にどんな注意をしていますか。（vs 37-44）

        2.  律法の専門家にはどんな注意をしていますか。（vs 45-52）

### 参照

### 記録

-   日時：2024年11月14日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 12:41-44 やもめの献金

> 41 イエスは、さいせん箱にむかってすわり、群衆がその箱に金を投げ入れる様子を見ておられた。多くの金持は、たくさんの金を投げ入れていた。42 ところが、ひとりの貧しいやもめがきて、レプタ二つを入れた。それは一コドラントに当る。43 そこで、イエスは弟子たちを呼び寄せて言われた、「よく聞きなさい。あの貧しいやもめは、さいせん箱に投げ入れている人たちの中で、だれよりもたくさん入れたのだ。44 みんなの者はありあまる中から投げ入れたが、あの婦人はその乏しい中から、あらゆる持ち物、その生活費全部を入れたからである」。

### ルカ 21:1-4

> 1 イエスは目をあげて、金持たちがさいせん箱に献金を投げ入れるのを見られ、2 また、ある貧しいやもめが、レプタ二つを入れるのを見て 3 言われた、「よく聞きなさい。あの貧しいやもめはだれよりもたくさん入れたのだ。4 これらの人たちはみな、ありあまる中から献金を投げ入れたが、あの婦人は、その乏しい中から、持っている生活費全部を入れたからである」。

[マルコによる福音書12章41-44節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark12_41-44.pdf)

### 問い

1.  貧しいやもめと金持ちはなにが違うのでしょう。

2.  イエスはどのようなことを教えていますか。

### 参照

### 記録

-   日時：2024年11月21日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

1.  貧しいやもめと金持ちはなにが違うのでしょう。

2.  イエスはどのようなことを教えていますか。

3.  ルカ

    1.  イエスは金持ちたちの献金とまずしいやもめの献金をどのように比較していますか。(How does Jesus compare the gifts of the rich with the gift of the poor widow?)

### メモ

## 13:1-2 神殿の崩壊を予告する

> 1 イエスが宮から出て行かれるとき、弟子のひとりが言った、「先生、ごらんなさい。なんという見事な石、なんという立派な建物でしょう」。2 イエスは言われた、「あなたは、これらの大きな建物をながめているのか。その石一つでもくずされないままで、他の石の上に残ることもなくなるであろう」。

### マタイ 24:1-2

> 1 イエスが宮から出て行こうとしておられると、弟子たちは近寄ってきて、宮の建物にイエスの注意を促した。2 そこでイエスは彼らにむかって言われた、「あなたがたは、これらすべてのものを見ないか。よく言っておく。その石一つでもくずされずに、そこに他の石の上に残ることもなくなるであろう」。

### ルカ 21:5-6

> 5 ある人々が、見事な石と奉納物とで宮が飾られていることを話していたので、イエスは言われた、6 「あなたがたはこれらのものをながめているが、その石一つでもくずされずに、他の石の上に残ることもなくなる日が、来るであろう」。

[マルコによる福音書13章1-2節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2.pdf)

[マルコによる福音書13章1-2,3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_1-2_3-13.pdf)

### 問い

1.  この会話はいつどこでどのように始まりますか。

2.  イエスは、宮について何と言っていますか。

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 13:3-13 終末の徴

> 3 またオリブ山で、宮にむかってすわっておられると、ペテロ、ヤコブ、ヨハネ、アンデレが、ひそかにお尋ねした。4 「わたしたちにお話しください。いつ、そんなことが起るのでしょうか。またそんなことがことごとく成就するような場合には、どんな前兆がありますか」。5 そこで、イエスは話しはじめられた、「人に惑わされないように気をつけなさい。6 多くの者がわたしの名を名のって現れ、自分がそれだと言って、多くの人を惑わすであろう。7 また、戦争と戦争のうわさとを聞くときにも、あわてるな。それは起らねばならないが、まだ終りではない。8 民は民に、国は国に敵対して立ち上がるであろう。またあちこちに地震があり、またききんが起るであろう。これらは産みの苦しみの初めである。9 あなたがたは自分で気をつけていなさい。あなたがたは、わたしのために、衆議所に引きわたされ、会堂で打たれ、長官たちや王たちの前に立たされ、彼らに対してあかしをさせられるであろう。10 こうして、福音はまずすべての民に宣べ伝えられねばならない。11 そして、人々があなたがたを連れて行って引きわたすとき、何を言おうかと、前もって心配するな。その場合、自分に示されることを語るがよい。語る者はあなたがた自身ではなくて、聖霊である。12 また兄弟は兄弟を、父は子を殺すために渡し、子は両親に逆らって立ち、彼らを殺させるであろう。13 また、あなたがたはわたしの名のゆえに、すべての人に憎まれるであろう。しかし、最後まで耐え忍ぶ者は救われる。

### マタイ 24:3-14

> 3 またオリブ山ですわっておられると、弟子たちが、ひそかにみもとにきて言った、「どうぞお話しください。いつ、そんなことが起るのでしょうか。あなたがまたおいでになる時や、世の終りには、どんな前兆がありますか」。4 そこでイエスは答えて言われた、「人に惑わされないように気をつけなさい。5 多くの者がわたしの名を名のって現れ、自分がキリストだと言って、多くの人を惑わすであろう。6 また、戦争と戦争のうわさとを聞くであろう。注意していなさい、あわててはいけない。それは起らねばならないが、まだ終りではない。7 民は民に、国は国に敵対して立ち上がるであろう。またあちこちに、ききんが起り、また地震があるであろう。8 しかし、すべてこれらは産みの苦しみの初めである。9 そのとき人々は、あなたがたを苦しみにあわせ、また殺すであろう。またあなたがたは、わたしの名のゆえにすべての民に憎まれるであろう。10 そのとき、多くの人がつまずき、また互に裏切り、憎み合うであろう。11 また多くのにせ預言者が起って、多くの人を惑わすであろう。12 また不法がはびこるので、多くの人の愛が冷えるであろう。13 しかし、最後まで耐え忍ぶ者は救われる。14 そしてこの御国の福音は、すべての民に対してあかしをするために、全世界に宣べ伝えられるであろう。そしてそれから最後が来るのである。

### ルカ 21:7-19

> 7 そこで彼らはたずねた、「先生、では、いつそんなことが起るのでしょうか。またそんなことが起るような場合には、どんな前兆がありますか」。8 イエスが言われた、「あなたがたは、惑わされないように気をつけなさい。多くの者がわたし名を名のって現れ、自分がそれだとか、時が近づいたとか、言うであろう。彼らについて行くな。9 戦争と騒乱とのうわさを聞くときにも、おじ恐れるな。こうしたことはまず起らねばならないが、終りはすぐにはこない」。10 それから彼らに言われた、「民は民に、国は国に敵対して立ち上がるであろう。11 また大地震があり、あちこちに疫病やききんが起り、いろいろ恐ろしいことや天からの物すごい前兆があるであろう。12 しかし、これらのあらゆる出来事のある前に、人々はあなたがたに手をかけて迫害をし、会堂や獄に引き渡し、わたしの名のゆえに王や総督の前にひっぱって行くであろう。13 それは、あなたがたがあかしをする機会となるであろう。14 だから、どう答弁しようかと、前もって考えておかないことに心を決めなさい。15 あなたの反対者のだれもが抗弁も否定もできないような言葉と知恵とを、わたしが授けるから。16 しかし、あなたがたは両親、兄弟、親族、友人にさえ裏切られるであろう。また、あなたがたの中で殺されるものもあろう。17 また、わたしの名のゆえにすべての人に憎まれるであろう。18 しかし、あなたがたの髪の毛一すじでも失われることは ない。19 あなたがたは耐え忍ぶことによって、自分の魂をかち取るであろう。

[マルコによる福音書13章3-13節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_3-13.pdf)

### 問い

1.  四人の弟子たちは何を知りたがっていますか。

2.  イエスはどんなことが起こると言っていますか。

3.  弟子たちに何を伝えようとしているのでしょうか。

4.  イエスに従うものたちにはさらにどんなことが起こると言っていますか。

5.  弟子たちはどのように生きるべきでしょうか。

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 13:14-23 大きな苦難を予告する

> 14 荒らす憎むべきものが、立ってはならぬ所に立つのを見たならば（読者よ、悟れ）、そのとき、ユダヤにいる人々は山へ逃げよ。15 屋上にいる者は、下におりるな。また家から物を取り出そうとして内にはいるな。16 畑にいる者は、上着を取りにあとへもどるな。17 その日には、身重の女と乳飲み子をもつ女とは、不幸である。18 この事が冬おこらぬように祈れ。19 その日には、神が万物を造られた創造の初めから現在に至るまで、かつてなく今後もないような患難が起るからである。20 もし主がその期間を縮めてくださらないなら、救われる者はひとりもないであろう。しかし、選ばれた選民のために、その期間を縮めてくださったのである。21 そのとき、だれかがあなたがたに『見よ、ここにキリストがいる』、『見よ、あそこにいる』と言っても、それを信じるな。22 にせキリストたちや、にせ預言者たちが起って、しるしと奇跡とを行い、できれば、選民をも惑わそうとするであろう。23 だから、気をつけていなさい。いっさいの事を、あなたがたに前もって言っておく。

### マタイ 24:15-28

> 15 預言者ダニエルによって言われた荒らす憎むべき者が、聖なる場所に立つのを見たならば（読者よ、悟れ）、16 そのとき、ユダヤにいる人々は山へ逃げよ。17 屋上にいる者は、家からものを取り出そうとして下におりるな。18 畑にいる者は、上着を取りにあとへもどるな。19 その日には、身重の女と乳飲み子をもつ女とは、不幸である。20 あなたがたの逃げるのが、冬または安息日にならないように祈れ。21 その時には、世の初めから現在に至るまで、かつてなく今後もないような大きな患難が起るからである。22 もしその期間が縮められないなら、救われる者はひとりもないであろう。しかし、選民のためには、その期間が縮められるであろう。23 そのとき、だれかがあなたがたに『見よ、ここにキリストがいる』、また、『あそこにいる』と言っても、それを信じるな。24 にせキリストたちや、にせ預言者たちが起って、大いなるしるしと奇跡とを行い、できれば、選民をも惑わそうとするであろう。25 見よ、あなたがたに前もって言っておく。26 だから、人々が『見よ、彼は荒野にいる』と言っても、出て行くな。また『見よ、へやの中にいる』と言っても、信じるな。27 ちょうど、いなずまが東から西にひらめき渡るように、人の子も現れるであろう。28 死体のあるところには、はげたかが集まるものである。

### ルカ 21:20-24

> 20 エルサレムが軍隊に包囲されるのを見たならば、そのときは、その滅亡が近づいたとさとりなさい。21 そのとき、ユダヤにいる人々は山へ逃げよ。市中にいる者は、そこから出て行くがよい。また、いなかにいる者は市内にはいってはいけない。22 それは、聖書にしるされたすべての事が実現する刑罰の日であるからだ 23 その日には、身重の女と乳飲み子をもつ女とは、不幸である。地上には大きな苦難があり、この民にはみ怒りが臨み、24 彼らはつるぎの刃に倒れ、また捕えられて諸国へ引きゆかれるであろう。そしてエルサレムは、異邦人の時期が満ちるまで、彼らに踏みにじられているであろう。

[マルコによる福音書13章14-23節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_14-23.pdf)

[マルコによる福音書13章14-23,24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_14-23_24-27.pdf)

### 問い

1.  14--16節をルカ 21:20--22と比較してみましょう。

2.  どんなことが起こると言っていますか。それは、かなり先のことですか。

3.  肉体的な危険のほかに、どんな危険について警告していますか。

4.  偽預言者や、偽メシアは、見分けることができるのでしょうか。

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 13:24-27 人の子が来る

> 24 その日には、この患難の後、日は暗くなり、月はその光を放つことをやめ、25 星は空から落ち、天体は揺り動かされるであろう。26 そのとき、大いなる力と栄光とをもって、人の子が雲に乗って来るのを、人々は見るであろう。27 そのとき、彼は御使たちをつかわして、地のはてから天のはてまで、四方からその選民を呼び集めるであろう。

### マタイ 24:29-31

> 29 しかし、その時に起る患難の後、たちまち日は暗くなり、月はその光を放つことをやめ、星は空から落ち、天体は揺り動かされるであろう。30 そのとき、人の子のしるしが天に現れるであろう。またそのとき、地のすべての民族は嘆き、そして力と大いなる栄光とをもって、人の子が天の雲に乗って来るのを、人々は見るであろう。31 また、彼は大いなるラッパの音と共に御使たちをつかわして、天のはてからはてに至るまで、四方からその選民を呼び集めるであろう。

### ルカ 21:25-28

> 25 また日と月と星とに、しるしが現れるであろう。そして、地上では、諸国民が悩み、海と大波とのとどろきにおじ惑い、26 人々は世界に起ろうとする事を思い、恐怖と不安で気絶するであろう。もろもろの天体が揺り動かされるからである。27 そのとき、大いなる力と栄光とをもって、人の子が雲に乗って来るのを、人々は見るであろう。28 これらの事が起りはじめたら、身を起し頭をもたげなさい。あなたがたの救が近づいているのだから」。

[マルコによる福音書13章24-27節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_24-27.pdf)

### 問い

1.  人の子は、どのような時に来ますか。

2.  人の子は何をしますか。

### 参照

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 13:28-32 いちじくの木の教え

> 28 いちじくの木からこの譬を学びなさい。その枝が柔らかになり、葉が出るようになると、夏の近いことがわかる。29 そのように、これらの事が起るのを見たならば、人の子が戸口まで近づいていると知りなさい。30 よく聞いておきなさい。これらの事が、ことごとく起るまでは、この時代は滅びることがない。31 天地は滅びるであろう。しかしわたしの言葉は滅びることがない。32 その日、その時は、だれも知らない。天にいる御使たちも、また子も知らない、ただ父だけが知っておられる。

### マタイ 24:32-35

> 32 いちじくの木からこの譬を学びなさい。その枝が柔らかになり、葉が出るようになると、夏の近いことがわかる。33 そのように、すべてこれらのことを見たならば、人の子が戸口まで近づいていると知りなさい。34 よく聞いておきなさい。これらの事が、ことごとく起るまでは、この時代は滅びることがない。35 天地は滅びるであろう。しかしわたしの言葉は滅びることがない。

### ルカ 21:29-33

> 29 それから一つの譬を話された、「いちじくの木を、またすべての木を見なさい。30 はや芽を出せば、あなたがたはそれを見て、夏がすでに近いと、自分で気づくのである。31 このようにあなたがたも、これらの事が起るのを見たなら、神の国が近いのだとさとりなさい。32 よく聞いておきなさい。これらの事が、ことごとく起るまでは、この時代は滅びることがない。33 天地は滅びるであろう。しかしわたしの言葉は決して滅びることがない。

[マルコによる福音書13章28-32節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32.pdf)

[マルコによる福音書13章28-32,33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

### 問い

1.  これらのことの起きるタイミングについて、イエスは何と言っていますか。

2.  31節は何を言っているのでしょうか。

### 参照

-   ルカには、このあと「目を覚ましていなさい」（21:34-37）

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ

## 13:33-37 目を覚ましていなさい

> 33 気をつけて、目をさましていなさい。その時がいつであるか、あなたがたにはわからないからである。34 それはちょうど、旅に立つ人が家を出るに当り、その僕たちに、それぞれ仕事を割り当てて責任をもたせ、門番には目をさましておれと、命じるようなものである。35 だから、目をさましていなさい。いつ、家の主人が帰って来るのか、夕方か、夜中か、にわとりの鳴くころか、明け方か、わからないからである。36 あるいは急に帰ってきて、あなたがたの眠っているところを見つけるかも知れない。37 目をさましていなさい。わたしがあなたがたに言うこの言葉は、すべての人々に言うのである」。

### マタイ 24:36-44

> 36 その日、その時は、だれも知らない。天の御使たちも、また子も知らない、ただ父だけが知っておられる。37 人の子の現れるのも、ちょうどノアの時のようであろう。38 すなわち、洪水の出る前、ノアが箱舟にはいる日まで、人々は食い、飲み、めとり、とつぎなどしていた。39 そして洪水が襲ってきて、いっさいのものをさらって行くまで、彼らは気がつかなかった。人の子の現れるのも、そのようであろう。40 そのとき、ふたりの者が畑にいると、ひとりは取り去られ、ひとりは取り残されるであろう。41 ふたりの女がうすをひいていると、ひとりは取り去られ、ひとりは残されるであろう。42 だから、目をさましていなさい。いつの日にあなたがたの主がこられるのか、あなたがたには、わからないからである。43 このことをわきまえているがよい。家の主人は、盗賊がいつごろ来るかわかっているなら、目をさましていて、自分の家に押し入ることを許さないであろう。44 だから、あなたがたも用意をしていなさい。思いがけない時に人の子が来るからである。

[マルコによる福音書13章33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_33-37.pdf)

[マルコによる福音書13章28-32,33-37節 福音書対照表](https://icu-hsuzuki.github.io/science/bible/docs/mark13_28-32_33-37.pdf)

### 問い

1.  イエスはどのような命令を与えていますか。

2.  イエスがあげている例は何を強調していますか。

### 参照

-   このあとマタイは、充実な僕と悪い僕（マタイ24:45-51、参照：ルカ12:41-48）

### 記録

-   日時：2024年M月DD日午後7時半〜9時半

-   出席（対面）X名、参加（遠隔）Y名

### 問いについて

### メモ
