# 受難物語

> **The Passion Narrative**
>
> [Early Christian Writings](https://www.earlychristianwritings.com) （初期キリスト教文書）サイトの [The Passion Narrative](https://www.earlychristianwritings.com/passion.html)（受難物語）に関してまとめたページ中の [The Pre-Markan Passion Narrative](https://www.earlychristianwritings.com/passion-young.html)（マルコ以前の受難物語） からの翻訳である。
>
> マルコ以前の受難物語に関してはさまざまな議論があるようで、その根拠についての記述は、上記受難物語のページに含まれる、Information on the Passion Narrative（受難物語に関する情報）を、Google Chrome の翻訳機能を使って日本語化したもの（2025.7.5）をもとに編集したものです。このページには、他にも文献や Website の情報もある。

## マルコ以前の受難物語

Google Chrome による和訳（2025.7.5）

以下は、マルコによる福音書の受難物語14章32節から15章47節までのヤング訳に基づいています。色分けはイエス・セミナーにヒントを得ています。各節の真正性を支持する学者の数に関するデータは、マリオン・L・ソーズ編『[メシアの死』](http://www.amazon.com/exec/obidos/ASIN/0385494491/peterkirby)（ニューヨーク：ダブルデイ、1994年）第2巻の付録IXから引用しました。より詳細な情報はソーズ編を参照してください。

ソーズは34名の学者に関するデータを提供しています。アンダーソン、バックリー、ブルトマン、チェルスキー、ディベリウス、ドナヒュー、ドーマイヤー、エルンスト、グラント、ジョンソン、ケルバー、クロスターマン、コレンコウ、クーン、レーン、レオン＝デュフール、ライトフット、ローゼ、リューアマン、モーン、ミリコスキ、ナインハム、ペディンハウス、ペッシュ、プライク、シェンク、シュネンケ、シレ、シュミタルス、シュナイダー、シュライバー、シュヴァイツァー、スクロッグス、テイラーです。ソーズは受難物語の各節について各学者の意見を示す表を提供しています。各節について、筆者は当該節または節の一部がマルコ以前の受難物語に属すると考える学者の数を数えました。ヤング訳聖書では、各節の横に学者の数が表示されています。

\[英語の原文は色分けがされている\] 色分けの仕組みは次のとおりです。7〜13 人の学者がその節を真正または部分的に真正だと考えている場合は黒、14〜15 人の学者がその節を真正または部分的に真正だと考えている場合は灰色、16〜19 人の学者がその節を真正または部分的に真正だと考えている場合はピンク、20〜26 人の学者がその節を真正または部分的に真正だと考えている場合は赤。色分けの仕組みでは、マルコ以前の受難物語の一部であると考えられているマルコの資料の量の一般的な印象を与えることはできません。その数字は、合計 87 節のうち学者 1 人あたり 40.6 節です。この仕組みは、各色の括弧にほぼ同数の節を割り当てるように明示的に設計されています。つまり、この仕組みは、マルコ以前の受難物語に対する真正性の相対的な可能性を知るために、個々の節同士を比較する場合に最適です。

------------------------------------------------------------------------

**14:32** \[17\] そして彼らはゲッセマネという所に来た。そこでイエスは弟子たちに言われた。「わたしが祈るまで、ここに座っていなさい。」

**14:33** \[11\] そしてイエスはペテロ、ヤコブ、ヨハネを連れて行かれたが、非常に驚​​き、悲しみに暮れ始められた。

**14:34** \[15\] そしてイエスは彼らに言われた。「わたしの魂は悲しみのあまり死んでしまいそうです。ここに留まって目を覚ましていなさい。」

**14:35** \[16\] そして、イエスは少し進み出て、地にひれ伏し、できればこの時が過ぎ去るようにと祈られた。

**14:36** \[15\] そして彼は言った、「アバ、父よ。あなたには、すべてのことができます。この杯を私から過ぎ去らせてください。しかし、私の思いではなく、あなたの思いのままにしてください。」

**14:37** \[15\] イエスは帰って来て、彼らが眠っているのをごらんになり、ペテロに言われた。「シモン、あなたは眠っている。一時間も目を覚ましていられなかったではないか。

**14:38** \[12\] 誘惑に陥らないように、目を覚まして祈りなさい。心は進んでいても、肉体は弱いのです。

**14:39** \[9\] そして、イエスはまた立ち去ってから、同じことばで祈った。

**14:40** \[13\] そして、イエスが戻って来られると、彼らはまた眠っていた。彼らの目は重く、何と答えてよいか分からなかったからである。

**14:41** \[14\] そして、イエスは三度目に近づいて来て、彼らに言われた。「もう眠って休みなさい。時が来たのです。見よ、人の子は罪人たちの手に引き渡されます。

**14:42** \[9\] 起きなさい。行きましょう。見よ、わたしを引き渡す者が近づいて来たのです。」

**14:43** \[24\] イエスがまだ話しておられるうちに、十二弟子のひとりのユダが、祭司長、律法学者、長老たちから遣わされた大勢の群衆を従えて、剣や棒を持って近づいて来た。

**14:44** \[21\] イエスを引き渡す者は、彼らに合図をして言った。「私が接吻する者が、その人だ。彼を捕らえて安全に連れ出しなさい。」

**14:45** \[24\] そして、イエスはすぐに近寄ってきて、「ラビ、ラビ」と言って、イエスに接吻した。

**14:46** \[25\] そして彼らはイエスの上に手を置いて、つかみとめた。

**14:47** \[20\]すると、そこに立っていた者のひとりが、剣を抜いて、祭司長の僕に切りかかり、その耳を切り落とした。

**14:48** \[18\] そこでイエスは答えて言われた、「あなたたちは、まるで強盗に襲いかかるように、剣や棒を持って、わたしを捕らえにきたのだ。

**14:49** \[19\] 毎日、わたしはあなたがたと一緒に宮で教えていたが、あなたがたはわたしを捕らえなかった。それは、聖書に記されたことが成就するためであった。』

**14:50** \[22\] そして彼らは皆イエスを残されて逃げ去った。

**14:51** \[17\] ある若者が、裸の体に亜麻布を巻いてイエスの後を追っていたが、若者たちは彼を捕らえた。

**14:52** \[17\] 彼は亜麻布を残して、裸のまま彼らから逃げた。

**14:53** \[24\] そこで彼らはイエスを祭司長のところ​​に連れて行き、祭司長たち、長老たち、律法学者たち全員がイエスのところに集まった。

**14:54** \[16\] ペテロは遠く離れてイエスに従って行き、祭司長の広間に入った。ペテロは下役たちと一緒に座って、火のそばに暖まっていた。

**14:55** \[12\] 祭司長たちと全議会は、イエスを死刑にするために、イエスに不利な証言を求めたが、見つけられなかった。

**14:56** \[12\] 多くの者がイエスに不利な偽証を立てたが、その証言は一致していなかった。

**14:57** \[9\] そして、ある人々が立ち上がり、イエスに不利な偽証をして言った。

**14:58** \[9\] 「私たちは彼がこう言うのを聞いた。『わたしは手で造ったこの聖所を打ち壊し、三日のうちに、手で造らない別の聖所を建てよう。』」

**14:59** \[7\] そして彼らの証言もまた同じではなかった。

**14:60** \[12\] すると、祭司長が真ん中で立ち上がり、イエスに尋ねた。「何も答えない。これらのことは、あなたに不利な証言をしているのですか。」

**14:61** \[14\] 彼は黙って、何も答えなかった。祭司長は再び彼に尋ねて言った。「あなたは聖なる方の子、キリストですか。」

**14:62** \[11\] イエスは言われた、「わたしがそうである。あなたがたは、人の子が天の力ある方の右に座し、雲に乗って来るのを、見るであろう」。

**14:63** \[13\]すると、祭司長は衣を引き裂いて言った。「まだ証人は要らないのか。

**14:64** \[13\] あなたがたは悪口を言っているのを聞いたが、どう思うか。」そして彼らは皆、イエスを死刑に処すべきだと断定した。

**14:65** \[14\] そして、ある人たちはイエスにつばきをかけ、顔を覆い、たたきつけ、「預言してみろ」と言い、また下役たちは手のひらでイエスをたたき始めた。

**14:66** \[14\] ペテロが下の広間にいたとき、祭司長の侍女の一人が来て、

**14:67** \[13\] そして、ペテロが暖まっているのを見て、彼を見つめながら、「あなたもナザレ人イエスと一緒だったのね」と言った。

**14:68** \[13\] 彼はそれを否定して言った、「わたしは彼を知りませんし、あなたの言うことも分かりません。」 そして鶏の鳴き声が聞こえる中、彼は外の廊へ出て行った。

**14:69** \[13\] 侍女は再び彼を見て、近くに立っていた人々に、「これは彼らのうちの者です」と言い始めた。

**14:70** \[14\] 彼はまたもや否定し始めた。しばらくして、また近くに立っていた人々がペテロに言った。「確かにあなたも彼らの仲間だ。あなたもガリラヤ人だが、言葉遣いも彼らと似ている。」

**14:71** \[14\] そして彼は呪いの言葉を唱え始め、誓って言った。「私はあなたがたが話しているその人を知らない。」

**14:72** \[14\] 二度目に鶏が鳴いた。ペテロは、イエスが彼に言われた、「鶏が二度鳴く前に、あなたは三度私を知らないと言うであろう」という言葉を思い出し、そのことを思い巡らして泣いた。

**15:1** \[19\] 翌朝すぐに、祭司長たち、長老たち、律法学者たち、全議会は協議の末、イエスを縛って連行し、ピラトに引き渡した。

**15:2** \[18\] ピラトは彼に尋ねた。「あなたはユダヤ人の王なのか。」彼は答えた。「あなたの言うとおりだ。」

**15:3** \[21\]祭司長たちはいろいろとイエスを訴えたが、イエスは何も答えられなかった。

**15:4** \[19\]そこでピラトは、もう一度イエスに尋ねた。「何も答えない。見よ、彼らはあなたに不利な証言をこんなにたくさんしているではないか。」

**15:5** \[20\] イエスはもう何も答えられなかったので、ピラトは不思議に思った。

**15:6** \[17\] そして、祭りのたびに、イエスは彼らが願う囚人を一人ずつ釈放しておられた。

**15:7** \[17\] バラバという者が、暴動を起こして殺人を犯した暴徒たちと共に縛られていた。

**15:8** \[16\] そして群衆は叫び声をあげ、イエスがいつものように彼らに求め始めた。

**15:9** \[17\] ピラトは彼らに答えて言った。「ユダヤ人の王を釈放してほしいのか。」

**15:10** \[15\] 祭司長たちがイエスを引き渡したのは、ねたみのためであることを、イエスは知っていたからである。

**15:11** \[16\]そこで祭司長たちは、むしろバラバを釈放するよう、群衆を唆した。

**15:12** \[13\] そこでピラトは、また答えて言った。「それでは、あなたがたがユダヤ人の王と呼んでいるこの人を、どうしたらよいのか。」

**15:13** \[14\]そして彼らはまた叫んだ。「十字架につけろ。」

**15:14** \[14\] ピラトは彼らに言った、「なぜ、彼はどんな悪事をしたのか。」彼らはますます激しく叫んだ、「彼を十字架につけよ。」

**15:15** \[21\]ピラトは群衆を満足させようとして、バラバを釈放し、イエスを鞭打ってから、十字架につけるために引き渡した。

**15:16** \[16\] そこで兵士たちは彼を総督官邸の広間に連れて行き、全軍を呼び集めて、

**15:17** \[16\] 彼に紫の衣を着せ、茨で冠を編んでかぶらせ、

**15:18** \[15\] そして、「ユダヤ人の王。万歳」と挨拶し始めた。

**15:19** \[17\] そして彼らは葦の棒でイエスの頭をたたき、つばきをかけ、ひざまずいて拝んだ。

**15:20** \[22\] そして彼らはイエスを嘲笑したのち、紫の衣をはぎ取って、もとの着物を着せ、十字架につけるために引き出した。

**15:21** \[24\] そこで彼らは、畑から出て来たクレネ人シモンに、イエスの十字架を担いでもらうよう命じた。

**15:22** \[24\] そして彼らはイエスをゴルゴタという場所に連れて行った。ゴルゴタとは、訳せば「されこうべの場所」という意味である。

**15:23** \[23\] そして彼らはイエスに没薬を混ぜたぶどう酒を飲ませようとしたが、イエスは受け取られなかった。

**15:24** \[26\] そして、彼らはイエスを十字架につけてから、その着物を分け、各々が何を取るかと、くじを引いた。

**15:25** \[14\] そして午後九時になった。彼らはイエスを十字架につけた。

**15:26** \[18\]その上には、彼を告発する碑文が書かれていた。「ユダヤ人の王」

**15:27** \[23\] そして、イエスと一緒に二人の強盗を十字架につけた。一人は右に、一人は左に。

**15:28** \[含まれていません\] そして、「彼は不法な者たちとともに数えられた」と書いてある聖書が成就した。

**15:29** \[20\] 道行く人々は、頭を振りながらイエスのことを悪く言い、「ああ、この聖所をこわし、三日のうちに建てた者だ」と言った。

**15:30** \[16\] 自分を救え。十字架から降りて来なさい。』

**15:31** \[14\] 祭司長たちも同じように、律法学者たちと互に嘲笑して言った。「ほかの人たちは救ったが、自分自身を救うことができないのだ。」

**15:32** \[20\] 「イスラエルの王、キリストよ、今十字架から降りて来なさい。私たちは見て信じます。」そして、イエスと一緒に十字架につけられた者たちは、イエスを非難した。

**15:33** \[13\] そして午後三時になって、全地は暗くなり、午後九時まで続いた。

**15:34** \[19\] そして三時に、イエスは大声で叫んで言われた、「エロイ、エロイ、ラムマ、サバクタニ」。これは、訳せば、「わが神、わが神、なぜわたしをお見捨てになったのですか」という意味である。

**15:35** \[17\] すると、そばに立っていた人々のうちのある者は、それを聞いて、「見よ、エリヤを呼んでいる」と言った。

**15:36** \[21\] すると、ひとりが走り寄ってきて、海綿に酢いぶしを含ませ、それを葦にもつけて、イエスに飲ませながら言った。「さあ、エリヤが彼を降ろしに来るかどうか、見ていよう。」

**15:37** \[22\] イエスは大声で叫んでから、霊を降ろされた。

**15:38** \[12\] そして聖所の垂れ幕は上から下まで二つに裂け、

**15:39** \[14\] イエスの向かいに立っていた百人隊長は、イエスがこのように叫び、霊を引いたのを見て、「本当に、この人は神の子だった」と言った。

**15:40** \[13\] 遠くから見ていた婦人たちもいたが、その中にはマグダラのマリア、小ヤコブとヨセのマリア、サロメもいた。

**15:41** \[11\] （彼女たちも、イエスがガリラヤにおられたとき、イエスに従い、仕えていた。）また、イエスと共にエルサレムに上った多くの婦人たちもいた。

**15:42** \[13\] さて夕方になったが、それは準備の日、すなわち安息日の前日であったので、

**15:43** \[14\] アリマタヤのヨセフという尊敬すべき議員がいて、神の国を待ち望んでいたが、大胆にピラトのところに行き、イエスの遺体の返還を求めた。

**15:44** \[10\] ピラトはイエスがもう死んだのではないかと疑い、百人隊長を呼び寄せて、もうとっくに死んでいたのかと尋ねた。

**15:45** \[11\] そして百人隊長からそれを聞いて、イエスの遺体をヨセフに引き渡した。

**15:46** \[14\] そこで彼は亜麻布を持って来て、イエスを降ろし、その亜麻布で包み、岩を掘って造った墓の中に納め、墓の入り口に石を転がして置いた。

**15:47** \[13\] マグダラのマリアとヨセフのマリアも、イエスが納められている場所を見ていた。

## 参考：受難物語に関する情報

Google Chrome による和訳（2025.7.5)

マルコ以前の受難物語の存在は疑問視されてきました。マルコ以前の受難物語という仮説は、マルコ福音書の最後の3章に福音書全体を通して展開されるテーマが含まれていることを示そうとする研究によって覆されてきました。*ドナヒュー、ロビンズ、ケルバー、ペリン、デューイ、ウィードン、クロッサンは『マルコにおける受難』*の中で、最初の13章に示された「解釈上の手がかり」を用いて受難物語を解釈しています。(153ページ) ケルバーは、そこから導き出される結論を次のように述べています。「マルコ14-16章をマルコ福音書の神学的に不可欠な部分と理解することは、マルコ以前の独立した一貫した受難物語に関する古典的な形式批評論に疑問を投げかけます。テーマ的には、マルコ14-16章にマルコ以外の主要な推進力やテーマを特定することは困難であり、ましてやマルコ以前の一貫した資料を推測することは困難です。」 （前掲書、157ページ）

それでもなお、マルコ以前の受難物語という考えは、大多数の学者にとって依然として有力であると考えられている。ゲルト・タイセンは*『文脈の中の福音書』*の中で最近の研究を発表しており、以下の考察はこの研究に基づいている。

タイセンは、マルコによる福音書の背後には、ヨハネによる福音書に見られる、イエスが過越祭の前の準備日に亡くなるという年代記に対応する物語が存在していることを指摘することから議論を始める。タイセンは次のように述べている（166-167ページ）。

> 私の見解では、マルコによる福音書において、現在私たちが手にしているテキストの背後には、特定の年代順を前提とする、連続した物語が読み取れます。マルコによれば、イエスは過越の日に亡くなりましたが、伝承では過越の前の準備の日とされています。14章1-2節では、サンヘドリン（ユダヤ教最高評議会）が、祭りの日に民衆の不安を防ぐため、祭りの前にイエスを殺害することを決定しました。これは、15章21節でキレネ人シモンが畑から帰ってきているという状況と合致しており、これは彼が仕事から帰ってきたことを意味していると理解できます。過越の日には何の仕事もなかったため、過越の日の出来事を描写する記述において、これほど誤解を招きやすい表現を用いる著者は考えにくいでしょう。さらに、15章42節では、イエスの埋葬は「準備の日」とされていますが、関係詞節が付け加えられ、安息日の準備の日となっています。本来、それは過ぎ越しの準備の日だったと考えられます（ヨハネ19:42参照）。日没前にイエスを十字架から降ろし、埋葬した動機は、おそらくこの作業を祭りが始まる前に済ませるためだったでしょう。もしそれが既に過ぎ越しの日であったならば、この行為は意味をなさないでしょう。最後に、サンヘドリンにおける「裁判」は、この日が祭りの日ではないことを前提としています。なぜなら、その日には司法手続きは行われないからです。これは法典違反であり、語り手が無視することはほとんど不可能だったでしょう。なぜなら、この物語の主旨は、イエスに対する裁判を、矛盾する証人と大祭司によって事前に下された判決による不公平な裁判として描くことだからです。

その後の議論の着想は、R. ペッシュの提言に由来する。ペッシュは、「大祭司」が名前を挙げられていないことから、受難物語は西暦37年以前に書かれたに違いないと主張した。この主張は確実ではないものの、出エジプト記に登場するファラオも名前を挙げられていないという反例を踏まえると、タイセンは物語に登場する人物の言及方法について包括的な評価を行うことになる。

タイセンは、大祭司の匿名性に別の理由を見いだしている。それは、必ずしも紀元37年以前に書かれたからではない。むしろ、紀元30年から70年の間、「カヤパとその一族が権力を握っていない時期はなかった」（173頁）からである。タイセンは、この理由について「彼らの影響力圏内で流布していた伝承では、彼らの名前を否定的な文脈で言及しないよう勧告されていた」（173頁）と述べている。対照的に、フィロンとヨセフスが示すように、ピラトは「他の多くの長官や総督よりも否定的な伝承の対象となっていた」ため、元の受難物語の作者にはピラトの名を挙げず、彼に責任を負わせない理由はなかった。この状況は、第一次ユダヤ反乱後のマタイとルカの著作の中で変化し、ピラトは無罪となり、大祭司の名前がためらいなく挙げられる。

「小ヤコブ」という呼称について、タイセンは次のように記している。「西暦30年から65年頃のエルサレムでは、『小ヤコブ』（または『小ヤコブ』）を、『年長者』（または『年長者』）の同名を持つ者と区別することが特に必要だったであろう」（178ページ）。タイセンは、「小ヤコブの母でヨセフの母であるマリア」はマルコ6章3節のイエスの母と同一視されるべきであり、「小ヤコブ」はイエスの兄弟ヤコブであると推測している。もしそうだとすれば、この表現はゼベダイの子ヤコブがより重要だった西暦44年以前の時代のものである。

出身地による人々の呼称（14:67、14:10、14:70、15:21、15:40、15:43）について、タイセンは次のように述べています。「出身地の言及は、その地名が伝承者と聴衆にとって差別化要因となることを前提としています。つまり、それらの地名は、ほぼ同程度によく知られている他の地名と区別できるものでなければなりません。ナザレ、マグダラ、アリマタヤといった町は、その知名度という点ではほぼ同等です。パレスチナ以外では、これらの地名がそうであるかどうか、ほんの少しでも知る人はいないでしょう。…パレスチナの主要都市、特にキレネ出身のユダヤ人が明確に言及されているエルサレム（使徒行伝 6:9）においては、地域的背景と地域外的背景の融合は容易に想像できるでしょう。」（179ページ）

タイセンは別の考察を指摘している。それは、人物の特定は父親によって最も一般的に行われていたにもかかわらず、受難物語においては父称によって人物が特定されている例がないということである。共観福音書の伝統の中では、受難物語において人物が父称で特定されている箇所は他にない。タイセンは、「初期キリスト教徒が両親と決別し、家を出てからイエスの弟子になったこと（マタイ伝8:20-21参照）を考慮すると、父親が人物特定における重要度を低下させた可能性は十分に考えられる」（180頁）と述​​べている。

バラバの物語について、タイセンは次のように述べている。「このテキストは、『反乱』の際に捕虜となった『反乱者たち』について、ごく簡潔に述べている*。* …*この*テキストは次の大反乱の前に書かれたとしか考えられない。その後、著者は以前の『停滞』と最近の『停滞』を区別することで、この記述を『歴史化』したのだろう。エルサレムを襲った次の血なまぐさい衝突を伴う騒乱は、クスピウス・ファドゥス率いるテウダスの出現（紀元44-45年。使徒言行録5章36節、*アンティオピオ*20章97-98節参照）であった。」

最後に、この物語には二人の無名の人物が登場します。大祭司の奴隷の耳を剣で切り落とす傍観者（マルコ14:47）と、逃亡して逮捕を逃れる若者（マルコ14:51-52）です。タイセンは次のように書いています（186-187ページ）。

> この匿名性の物語的動機は、私には容易に推測できる。二人とも「警察」に引っかかるからだ。剣を抜く者は、誰かの耳を切り落とすという軽犯罪を犯しているわけではない。少しでも外れていれば、頭部や喉に傷を負わせていたかもしれない。剣によるこの一撃は、致命傷を負う可能性のある暴力である。匿名の若者も抵抗した。格闘の結果、彼の服は引き裂かれ、裸で逃げ去らざるを得なくなった。この後、二人は危険にさらされた。大祭司の奴隷が生きている限り（そして剣による傷跡が見える限り）、彼らの名前を口にするのは不適切だっただろう。彼らが初期キリスト教徒の共同体の一員であることを明らかにすることさえ賢明ではなかっただろう。彼らが匿名であるのは彼らを守るためであり、イエスとの良好な関係を隠蔽するのは、用心深いための戦略である。語り手も聞き手も、この二人についてより深く知っている。彼らが誰だったのか、剣を持っていたのはペテロだったのか、二人は同一人物なのか、イエスの最期の物語の信憑性を高めるために彼らに言及されたのか、それらについて語れるのは彼らだけだった。これらすべては、私たちには明かされないままである。

それでも、この根拠から、これらの登場人物の匿名性は慎重さのためである可能性が示唆される。同様の例は古代にも引用されている。タイセンは殉教者ユスティノスについて述べている。彼は、夫と離婚した高潔なキリスト教徒の女性の物語を語る。夫は彼女をキリスト教徒として告発した。彼女の裁判は皇帝によって延期されたが、判決に抗議した彼女のキリスト教徒の教師と他の二人は処刑された。ユスティノスは二人の殉教者の名前を明かしているが、女性の名前は機転を利かせて隠している。タイセンはまた、ヨセフスが十字架にかけられた三人の男の物語の中で、ヨセフスが三人を十字架から降ろすことができたが、三人の名前を明かさなかったことを示唆している。したがって、受難物語も同様のケースである可能性がある。

タイセンは次のように書いている。「もし我々の仮説が正しければ、受難伝承の所在地は明白である。エルサレムにおいてのみ、自らの行動によって危険にさらされたイエスの信奉者たちに匿名のベールをかぶせる理由があった。年代も特定できるだろう。受難物語の一部は、目撃者とその同時代人の世代、つまり西暦30年から60年の間に書かれたはずだ。」

これらの証拠はどれも偶然の一致として片付けられるかもしれないが、タイセンは一連のもっともらしいつながりを作り出し、全体としてはマルコ以前の初期の受難物語の存在を立証する根拠となっている。

このマルコ以前の受難物語はどこで終わったのでしょうか？空の墓の物語以外に、2つの妥当な答えがあります。1つ目は、百人隊長の告白で物語が最高潮に達し、終わったというものです。2つ目は、J・D・クロッサンとレジナルド・フラーが提唱したように、ガリラヤで弟子たちに現れる物語で物語が終わったというものです。
