# 失われた語録 Q

> **The Lost Sayings Gospel Q**
>
> [Early Christian Writings](https://www.earlychristianwritings.com) （初期キリスト教文書）サイトの [The Lost Sayings Gospel Q](https://www.earlychristianwritings.com/q.html) （失われた語録 Q）に関してまとめたページ中の [Gregory Riley: NRSV Translation of Q according to Funk/Miller](https://www.earlychristianwritings.com/text/q-funk.html) から グレゴリー・ライリー：ファンク/ミラーによるQのNRSV翻訳からの引用に、聖書協会口語訳を加えたもの。
>
> 失われた語録 Q のルカとマタイ対照表（The Contents of Q, The Synopsis of Q）など（順次記載）
>
> 失われた語録 Q の根拠についての記述は、上記失われた語録 Q のページに含まれる、Information on the Lost Sayings Gospel Q（失われた語録 Q に関する情報）を、Google Chrome の翻訳機能を使って日本語化したもの（2025.7.5）をもとに編集したものです。
>
> 上記のページには、豊富な参考文献やサイトの情報があります。

## グレゴリー・ライリー：ファンク/ミラーによる失われた語録 Q 

英語翻訳（NRSV）に、口語訳を付け加えたもの

**Q \[NRSV\] (Text according to Funk/Miller)**\
 

3:7-9 John said to the crowds that came out to be baptized by him, "You brood of vipers! Who warned you to flee from the wrath to come?   8 Bear fruits worthy of repentance. Do not begin to say to yourselves, \`We have Abraham as our ancestor'; for I tell you, God is able from these stones to raise up children to Abraham.   9 Even now the ax is lying at the root of the trees; every tree therefore that does not bear good fruit is cut down and thrown into the fire."

3:16-17 John answered all of them by saying, "I baptize you with water; but one who is more powerful than I is coming; I am not worthy to untie the thong of his sandals. He will baptize you with the Holy Spirit and fire.   17 His winnowing fork is in his hand, to clear his threshing floor and to gather the wheat into his granary; but the chaff he will burn with unquenchable fire."

4:1-13 Jesus, full of the Holy Spirit, returned from the Jordan and was led by the Spirit in the wilderness,   2 where for forty days he was tempted by the devil. He ate nothing at all during those days, and when they were over, he was famished.   3 The devil said to him, "If you are the Son of God, command this stone to become a loaf of bread."   4 Jesus answered him, "It is written, \`One does not live by bread alone.'"   5 Then the devil led him up and showed him in an instant all the kingdoms of the world.   6 And the devil said to him, "To you I will give their glory and all this authority; for it has been given over to me, and I give it to anyone I please.   7 If you, then, will worship me, it will all be yours."   8 Jesus answered him, "It is written, \`Worship the Lord your God, and serve only him.'"   9 Then the devil took him to Jerusalem, and placed him on the pinnacle of the temple, saying to him, "If you are the Son of God, throw yourself down from here,   10 for it is written, \`He will command his angels concerning you, to protect you,'   11 and \`On their hands they will bear you up, so that you will not dash your foot against a stone.'"   12 Jesus answered him, "It is said, \`Do not put the Lord your God to the test.'"   13 When the devil had finished every test, he departed from him until an opportune time.

6:12, 17, 20 Now during those days he went out to the mountain to pray; and he spent the night in prayer to God.    17 He came down with them and stood on a level place, with a great crowd of his disciples and a great multitude of people from all Judea, Jerusalem, and the coast of Tyre and Sidon.    20 Then he looked up at his disciples and said:

6:20-26 "Blessed are you who are poor, for yours is the kingdom of God.   21  "Blessed are you who are hungry now, for you will be filled. "Blessed are you who weep now, for you will laugh.   22  "Blessed are you when people hate you, and when they exclude you, revile you, and defame you on account of the Son of Man.   23 Rejoice in that day and leap for joy, for surely your reward is great in heaven; for that is what their ancestors did to the prophets.   24  "But woe to you who are rich, for you have received your consolation.   25  "Woe to you who are full now, for you will be hungry. "Woe to you who are laughing now, for you will mourn and weep.   26  "Woe to you when all speak well of you, for that is what their ancestors did to the false prophets.

6:27-36 "But I say to you that listen, Love your enemies, do good to those who hate you,   28 bless those who curse you, pray for those who abuse you.   29 If anyone strikes you on the cheek, offer the other also; and from anyone who takes away your coat do not withhold even your shirt.   30 Give to everyone who begs from you; and if anyone takes away your goods, do not ask for them again.   31 Do to others as you would have them do to you.   32  "If you love those who love you, what credit is that to you? For even sinners love those who love them.   33 If you do good to those who do good to you, what credit is that to you? For even sinners do the same.   34 If you lend to those from whom you hope to receive, what credit is that to you? Even sinners lend to sinners, to receive as much again.   35 But love your enemies, do good, and lend, expecting nothing in return. Your reward will be great, and you will be children of the Most High; for he is kind to the ungrateful and the wicked.   36 Be merciful, just as your Father is merciful.

6:37-38 "Do not judge, and you will not be judged; do not condemn, and you will not be condemned. Forgive, and you will be forgiven;   38 give, and it will be given to you. A good measure, pressed down, shaken together, running over, will be put into your lap; for the measure you give will be the measure you get back."

6:39-40 He also told them a parable: "Can a blind person guide a blind person? Will not both fall into a pit?   40 A disciple is not above the teacher, but everyone who is fully qualified will be like the teacher.

6:41-42 Why do you see the speck in your neighbor's eye, but do not notice the log in your own eye?   42 Or how can you say to your neighbor, \`Friend, let me take out the speck in your eye,' when you yourself do not see the log in your own eye? You hypocrite, first take the log out of your own eye, and then you will see clearly to take the speck out of your neighbor's eye.

6:43-45 "No good tree bears bad fruit, nor again does a bad tree bear good fruit;   44 for each tree is known by its own fruit. Figs are not gathered from thorns, nor are grapes picked from a bramble bush.   45 The good person out of the good treasure of the heart produces good, and the evil person out of evil treasure produces evil; for it is out of the abundance of the heart that the mouth speaks.

6:46-49 "Why do you call me \`Lord, Lord,' and do not do what I tell you?   47 I will show you what someone is like who comes to me, hears my words, and acts on them.   48   That one is like a man building a house, who dug deeply and laid the foundation on rock; when a flood arose, the river burst against that house but could not shake it, because it had been well built.   49 But the one who hears and does not act is like a man who built a house on the ground without a foundation. When the river burst against it, immediately it fell, and great was the ruin of that house."

7:1-10 After Jesus had finished all his sayings in the hearing of the people, he entered Capernaum.   2 A centurion there had a slave whom he valued highly, and who was ill and close to death.   3 When he heard about Jesus, he sent some Jewish elders to him, asking him to come and heal his slave.   4 When they came to Jesus, they appealed to him earnestly, saying, "He is worthy of having you do this for him,   5 for he loves our people, and it is he who built our synagogue for us."   6 And Jesus went with them, but when he was not far from the house, the centurion sent friends to say to him, "Lord, do not trouble yourself, for I am not worthy to have you come under my roof;   7 therefore I did not presume to come to you. But only speak the word, and let my servant be healed.   8 For I also am a man set under authority, with soldiers under me; and I say to one, \`Go,' and he goes, and to another, \`Come,' and he comes, and to my slave, \`Do this,' and the slave does it."   9 When Jesus heard this he was amazed at him, and turning to the crowd that followed him, he said, "I tell you, not even in Israel have I found such faith."   10 When those who had been sent returned to the house, they found the slave in good health.

7:18-20, 22-23 The disciples of John reported all these things to him. So John summoned two of his disciples  19 and sent them to the Lord to ask, "Are you the one who is to come, or are we to wait for another?"   20 When the men had come to him, they said, "John the Baptist has sent us to you to ask, \`Are you the one who is to come, or are we to wait for another?'"   22 And he answered them, "Go and tell John what you have seen and heard: the blind receive their sight, the lame walk, the lepers are cleansed, the deaf hear, the dead are raised, the poor have good news brought to them.   23 And blessed is anyone who takes no offense at me."

7:24-28 When John's messengers had gone, Jesus began to speak to the crowds about John: "What did you go out into the wilderness to look at? A reed shaken by the wind?   25 What then did you go out to see? Someone dressed in soft robes? Look, those who put on fine clothing and live in luxury are in royal palaces.   26 What then did you go out to see? A prophet? Yes, I tell you, and more than a prophet.   27 This is the one about whom it is written, \`See, I am sending my messenger ahead of you, who will prepare your way before you.'   28 I tell you, among those born of women no one is greater than John; yet the least in the kingdom of God is greater than he."

7:31-35 "To what then will I compare the people of this generation, and what are they like?   32 They are like children sitting in the marketplace and calling to one another, \`We played the flute for you, and you did not dance; we wailed, and you did not weep.'   33 For John the Baptist has come eating no bread and drinking no wine, and you say, \`He has a demon';   34 the Son of Man has come eating and drinking, and you say, \`Look, a glutton and a drunkard, a friend of tax collectors and sinners!'   35 Nevertheless, wisdom is vindicated by all her children."

9:57-62 As they were going along the road, someone said to him, "I will follow you wherever you go."   58 And Jesus said to him, "Foxes have holes, and birds of the air have nests; but the Son of Man has nowhere to lay his head."   59 To another he said, "Follow me." But he said, "Lord, first let me go and bury my father."   60 But Jesus said to him, "Let the dead bury their own dead; but as for you, go and proclaim the kingdom of God."   61 Another said, "I will follow you, Lord; but let me first say farewell to those at my home."   62 Jesus said to him, "No one who puts a hand to the plow and looks back is fit for the kingdom of God."

10:2-12 He said to them, "The harvest is plentiful, but the laborers are few; therefore ask the Lord of the harvest to send out laborers into his harvest.   3 Go on your way. See, I am sending you out like lambs into the midst of wolves.   4 Carry no purse, no bag, no sandals; and greet no one on the road.   5 Whatever house you enter, first say, \`Peace to this house!'   6 And if anyone is there who shares in peace, your peace will rest on that person; but if not, it will return to you.   7 Remain in the same house, eating and drinking whatever they provide, for the laborer deserves to be paid. Do not move about from house to house.   8 Whenever you enter a town and its people welcome you, eat what is set before you;   9 cure the sick who are there, and say to them, \`The kingdom of God has come near to you.'   10 But whenever you enter a town and they do not welcome you, go out into its streets and say,   11  \`Even the dust of your town that clings to our feet, we wipe off in protest against you. Yet know this: the kingdom of God has come near.'   12 I tell you, on that day it will be more tolerable for Sodom than for that town.

10:13-15 "Woe to you, Chorazin! Woe to you, Bethsaida! For if the deeds of power done in you had been done in Tyre and Sidon, they would have repented long ago, sitting in sackcloth and ashes.   14 But at the judgment it will be more tolerable for Tyre and Sidon than for you.   15 And you, Capernaum, will you be exalted to heaven? No, you will be brought down to Hades.

10:16  "Whoever listens to you listens to me, and whoever rejects you rejects me, and whoever rejects me rejects the one who sent me."

10:21-22 At that same hour Jesus rejoiced in the Holy Spirit and said, "I thank you, Father, Lord of heaven and earth, because you have hidden these things from the wise and the intelligent and have revealed them to infants; yes, Father, for such was your gracious will.   22 All things have been handed over to me by my Father; and no one knows who the Son is except the Father, or who the Father is except the Son and anyone to whom the Son chooses to reveal him."

10:23-24  Then turning to the disciples, Jesus said to them privately, "Blessed are the eyes that see what you see!   24 For I tell you that many prophets and kings desired to see what you see, but did not see it, and to hear what you hear, but did not hear it."

11:2-4 He said to them, "When you pray, say: Father, hallowed be your name. Your kingdom come.   3 Give us each day our daily bread.   4 And forgive us our sins, for we ourselves forgive everyone indebted to us. And do not bring us to the time of trial."

11:9-13 "So I say to you, Ask, and it will be given you; search, and you will find; knock, and the door will be opened for you.   10 For everyone who asks receives, and everyone who searches finds, and for everyone who knocks, the door will be opened.   11 Is there anyone among you who, if your child asks for a fish, will give a snake instead of a fish?   12 Or if the child asks for an egg, will give a scorpion?   13 If you then, who are evil, know how to give good gifts to your children, how much more will the heavenly Father give the Holy Spirit to those who ask him!"

11:14-23 Now he was casting out a demon that was mute; when the demon had gone out, the one who had been mute spoke, and the crowds were amazed.   15 But some of them said, "He casts out demons by Beelzebul, the ruler of the demons."    17 But he knew what they were thinking and said to them, "Every kingdom divided against itself becomes a desert, and house falls on house.   18 If Satan also is divided against himself, how will his kingdom stand? -- for you say that I cast out the demons by Beelzebul.   19 Now if I cast out the demons by Beelzebul, by whom do your exorcists cast them out? Therefore they will be your judges.   20 But if it is by the finger of God that I cast out the demons, then the kingdom of God has come to you.   21 When a strong man, fully armed, guards his castle, his property is safe.   22 But when one stronger than he attacks him and overpowers him, he takes away his armor in which he trusted and divides his plunder.   23 Whoever is not with me is against me, and whoever does not gather with me scatters.

11:24-26 "When the unclean spirit has gone out of a person, it wanders through waterless regions looking for a resting place, but not finding any, it says, \`I will return to my house from which I came.'   25 When it comes, it finds it swept and put in order.   26 Then it goes and brings seven other spirits more evil than itself, and they enter and live there; and the last state of that person is worse than the first."

11:27-28 \[no Mt //\] While he was saying this, a woman in the crowd raised her voice and said to him, "Blessed is the womb that bore you and the breasts that nursed you!"   28 But he said, "Blessed rather are those who hear the word of God and obey it!"

11:16, 29-32 16 Others, to test him, kept demanding from him a sign from heaven.  29 When the crowds were increasing, he began to say, "This generation is an evil generation; it asks for a sign, but no sign will be given to it except the sign of Jonah.   30 For just as Jonah became a sign to the people of Nineveh, so the Son of Man will be to this generation.   31 The queen of the South will rise at the judgment with the people of this generation and condemn them, because she came from the ends of the earth to listen to the wisdom of Solomon, and see, something greater than Solomon is here!   32 The people of Nineveh will rise up at the judgment with this generation and condemn it, because they repented at the proclamation of Jonah, and see, something greater than Jonah is here!

11:33 "No one after lighting a lamp puts it in a cellar, but on the lampstand so that those who enter may see the light.

11:34-36 Your eye is the lamp of your body. If your eye is healthy, your whole body is full of light; but if it is not healthy, your body is full of darkness.   35 Therefore consider whether the light in you is not darkness.   36 If then your whole body is full of light, with no part of it in darkness, it will be as full of light as when a lamp gives you light with its rays."

11:42 "But woe to you Pharisees! For you tithe mint and rue and herbs of all kinds, and neglect justice and the love of God; it is these you ought to have practiced, without neglecting the others.

11:39-41 Then the Lord said to him, "Now you Pharisees clean the outside of the cup and of the dish, but inside you are full of greed and wickedness.   40 You fools! Did not the one who made the outside make the inside also?   41 So give for alms those things that are within; and see, everything will be clean for you.

11:43  Woe to you Pharisees! For you love to have the seat of honor in the synagogues and to be greeted with respect in the marketplaces.

11:44 Woe to you! For you are like unmarked graves, and people walk over them without realizing it."

11:46  And he said, "Woe also to you lawyers! For you load people with burdens hard to bear, and you yourselves do not lift a finger to ease them.

11:47-48 Woe to you! For you build the tombs of the prophets whom your ancestors killed.   48 So you are witnesses and approve of the deeds of your ancestors; for they killed them, and you build their tombs.

11:49-51  Therefore also the Wisdom of God said, \`I will send them prophets and apostles, some of whom they will kill and persecute,'   50 so that this generation may be charged with the blood of all the prophets shed since the foundation of the world,   51 from the blood of Abel to the blood of Zechariah, who perished between the altar and the sanctuary. Yes, I tell you, it will be charged against this generation.

11:52 Woe to you lawyers! For you have taken away the key of knowledge; you did not enter yourselves, and you hindered those who were entering."

12:2-3 Nothing is covered up that will not be uncovered, and nothing secret that will not become known.   3 Therefore whatever you have said in the dark will be heard in the light, and what you have whispered behind closed doors will be proclaimed from the housetops.

12:4-7  "I tell you, my friends, do not fear those who kill the body, and after that can do nothing more.   5 But I will warn you whom to fear: fear him who, after he has killed, has authority to cast into hell. Yes, I tell you, fear him!   6 Are not five sparrows sold for two pennies? Yet not one of them is forgotten in God's sight.   7 But even the hairs of your head are all counted. Do not be afraid; you are of more value than many sparrows.

12:8-9 "And I tell you, everyone who acknowledges me before others, the Son of Man also will acknowledge before the angels of God;   9 but whoever denies me before others will be denied before the angels of God.

12:10 And everyone who speaks a word against the Son of Man will be forgiven; but whoever blasphemes against the Holy Spirit will not be forgiven.

12:11-12 When they bring you before the synagogues, the rulers, and the authorities, do not worry about how you are to defend yourselves or what you are to say;   12 for the Holy Spirit will teach you at that very hour what you ought to say."

12:13-14 \[no Mt //\] Someone in the crowd said to him, "Teacher, tell my brother to divide the family inheritance with me."   14 But he said to him, "Friend, who set me to be a judge or arbitrator over you?"

12:16-21 \[no Mt //\] Then he told them a parable: "The land of a rich man produced abundantly.   17 And he thought to himself, \`What should I do, for I have no place to store my crops?'   18 Then he said, \`I will do this: I will pull down my barns and build larger ones, and there I will store all my grain and my goods.   19 And I will say to my soul, \`Soul, you have ample goods laid up for many years; relax, eat, drink, be merry.'   20 But God said to him, \`You fool! This very night your life is being demanded of you. And the things you have prepared, whose will they be?'   21 So it is with those who store up treasures for themselves but are not rich toward God."

12:22-31 He said to his disciples, "Therefore I tell you, do not worry about your life, what you will eat, or about your body, what you will wear.   23 For life is more than food, and the body more than clothing.   24 Consider the ravens: they neither sow nor reap, they have neither storehouse nor barn, and yet God feeds them. Of how much more value are you than the birds!   25 And can any of you by worrying add a single hour to your span of life?   26 If then you are not able to do so small a thing as that, why do you worry about the rest?   27 Consider the lilies, how they grow: they neither toil nor spin; yet I tell you, even Solomon in all his glory was not clothed like one of these.   28 But if God so clothes the grass of the field, which is alive today and tomorrow is thrown into the oven, how much more will he clothe you-- you of little faith!   29 And do not keep striving for what you are to eat and what you are to drink, and do not keep worrying.   30 For it is the nations of the world that strive after all these things, and your Father knows that you need them.   31 Instead, strive for his kingdom, and these things will be given to you as well.

12:33-34 Sell your possessions, and give alms. Make purses for yourselves that do not wear out, an unfailing treasure in heaven, where no thief comes near and no moth destroys.   34 For where your treasure is, there your heart will be also.

12:39-40 "But know this: if the owner of the house had known at what hour the thief was coming, he would not have let his house be broken into.   40 You also must be ready, for the Son of Man is coming at an unexpected hour."

12:42-46 And the Lord said, "Who then is the faithful and prudent manager whom his master will put in charge of his slaves, to give them their allowance of food at the proper time?   43 Blessed is that slave whom his master will find at work when he arrives.   44 Truly I tell you, he will put that one in charge of all his possessions.   45 But if that slave says to himself, \`My master is delayed in coming,' and if he begins to beat the other slaves, men and women, and to eat and drink and get drunk,   46 the master of that slave will come on a day when he does not expect him and at an hour that he does not know, and will cut him in pieces, and put him with the unfaithful.

12:49, 51-53 "I came to bring fire to the earth, and how I wish it were already kindled!  51 Do you think that I have come to bring peace to the earth? No, I tell you, but rather division!   52 From now on five in one household will be divided, three against two and two against three;   53 they will be divided: father against son and son against father, mother against daughter and daughter against mother, mother-in-law against her daughter-in-law and daughter-in-law against mother-in-law."

12:54-56 He also said to the crowds, "When you see a cloud rising in the west, you immediately say, \`It is going to rain'; and so it happens.   55 And when you see the south wind blowing, you say, \`There will be scorching heat'; and it happens.   56 You hypocrites! You know how to interpret the appearance of earth and sky, but why do you not know how to interpret the present time?

12:57-59 "And why do you not judge for yourselves what is right?   58 Thus, when you go with your accuser before a magistrate, on the way make an effort to settle the case, or you may be dragged before the judge, and the judge hand you over to the officer, and the officer throw you in prison.   59 I tell you, you will never get out until you have paid the very last penny."

13:18-21 He said therefore, "What is the kingdom of God like? And to what should I compare it?   19 It is like a mustard seed that someone took and sowed in the garden; it grew and became a tree, and the birds of the air made nests in its branches."   20 And again he said, "To what should I compare the kingdom of God?   21 It is like yeast that a woman took and mixed in with three measures of flour until all of it was leavened."

13:24-27 "Strive to enter through the narrow door; for many, I tell you, will try to enter and will not be able.   25 When once the owner of the house has got up and shut the door, and you begin to stand outside and to knock at the door, saying, \`Lord, open to us,' then in reply he will say to you, \`I do not know where you come from.'   26 Then you will begin to say, \`We ate and drank with you, and you taught in our streets.'   27 But he will say, \`I do not know where you come from; go away from me, all you evildoers!'

13:28-30  There will be weeping and gnashing of teeth when you see Abraham and Isaac and Jacob and all the prophets in the kingdom of God, and you yourselves thrown out.   29 Then people will come from east and west, from north and south, and will eat in the kingdom of God.   30 Indeed, some are last who will be first, and some are first who will be last."

13:34-35 Jerusalem, Jerusalem, the city that kills the prophets and stones those who are sent to it! How often have I desired to gather your children together as a hen gathers her brood under her wings, and you were not willing!   35 See, your house is left to you. And I tell you, you will not see me until the time comes when you say, \`Blessed is the one who comes in the name of the Lord.'"

14:11, 18:14 For all who exalt themselves will be humbled, and those who humble themselves will be exalted."\
  18:14 I tell you, this man went down to his home justified rather than the other; for all who exalt themselves will be humbled, but all who humble themselves will be exalted."

14:16-24 Then Jesus said to him, "Someone gave a great dinner and invited many.   17 At the time for the dinner he sent his slave to say to those who had been invited, \`Come; for everything is ready now.'   18 But they all alike began to make excuses. The first said to him, \`I have bought a piece of land, and I must go out and see it; please accept my regrets.'   19 Another said, \`I have bought five yoke of oxen, and I am going to try them out; please accept my regrets.'   20 Another said, \`I have just been married, and therefore I cannot come.'   21 So the slave returned and reported this to his master. Then the owner of the house became angry and said to his slave, \`Go out at once into the streets and lanes of the town and bring in the poor, the crippled, the blind, and the lame.'   22 And the slave said, \`Sir, what you ordered has been done, and there is still room.'   23 Then the master said to the slave, \`Go out into the roads and lanes, and compel people to come in, so that my house may be filled.   24 For I tell you, none of those who were invited will taste my dinner.'"

14:26-27, 17:33 "Whoever comes to me and does not hate father and mother, wife and children, brothers and sisters, yes, and even life itself, cannot be my disciple.   27 Whoever does not carry the cross and follow me cannot be my disciple.\
  17:33 Those who try to make their life secure will lose it, but those who lose their life will keep it.

14:34-35 "Salt is good; but if salt has lost its taste, how can its saltiness be restored?   35 It is fit neither for the soil nor for the manure pile; they throw it away. Let anyone with ears to hear listen!"

15:4-10 \[no Mt // to vss.8-10\] "Which one of you, having a hundred sheep and losing one of them, does not leave the ninety-nine in the wilderness and go after the one that is lost until he finds it?   5 When he has found it, he lays it on his shoulders and rejoices.   6   And when he comes home, he calls together his friends and neighbors, saying to them, \`Rejoice with me, for I have found my sheep that was lost.'   7 Just so, I tell you, there will be more joy in heaven over one sinner who repents than over ninety-nine righteous persons who need no repentance.\
  8  "Or what woman having ten silver coins, if she loses one of them, does not light a lamp, sweep the house, and search carefully until she finds it?   9 When she has found it, she calls together her friends and neighbors, saying, \`Rejoice with me, for I have found the coin that I had lost.'   10 Just so, I tell you, there is joy in the presence of the angels of God over one sinner who repents."

16:13 No slave can serve two masters; for a slave will either hate the one and love the other, or be devoted to the one and despise the other. You cannot serve God and wealth."

16:16 "The law and the prophets were in effect until John came; since then the good news of the kingdom of God is proclaimed, and everyone tries to enter it by force.

16:17 But it is easier for heaven and earth to pass away, than for one stroke of a letter in the law to be dropped.

16:18  "Anyone who divorces his wife and marries another commits adultery, and whoever marries a woman divorced from her husband commits adultery.

17:1-2 Jesus said to his disciples, "Occasions for stumbling are bound to come, but woe to anyone by whom they come!   2 It would be better for you if a millstone were hung around your neck and you were thrown into the sea than for you to cause one of these little ones to stumble.

17:3-4 Be on your guard! If another disciple sins, you must rebuke the offender, and if there is repentance, you must forgive.   4 And if the same person sins against you seven times a day, and turns back to you seven times and says, \`I repent,' you must forgive."

17:6 The Lord replied, "If you had faith the size of a mustard seed, you could say to this mulberry tree, \`Be uprooted and planted in the sea,' and it would obey you.

17:22-24, 26-30, 34-35, 37 Then he said to the disciples, "The days are coming when you will long to see one of the days of the Son of Man, and you will not see it.   23 They will say to you, \`Look there!' or \`Look here!' Do not go, do not set off in pursuit.   24 For as the lightning flashes and lights up the sky from one side to the other, so will the Son of Man be in his day.\
  26 Just as it was in the days of Noah, so too it will be in the days of the Son of Man.   27 They were eating and drinking, and marrying and being given in marriage, until the day Noah entered the ark, and the flood came and destroyed all of them.   28 Likewise, just as it was in the days of Lot: they were eating and drinking, buying and selling, planting and building,   29 but on the day that Lot left Sodom, it rained fire and sulfur from heaven and destroyed all of them  30 -- it will be like that on the day that the Son of Man is revealed.\
  34 I tell you, on that night there will be two in one bed; one will be taken and the other left.   35 There will be two women grinding meal together; one will be taken and the other left."\
  37Then they asked him, "Where, Lord?" He said to them, "Where the corpse is, there the vultures will gather."

19:12-26 So he said, "A nobleman went to a distant country to get royal power for himself and then return.   13 He summoned ten of his slaves, and gave them ten pounds, and said to them, \`Do business with these until I come back.'   14 But the citizens of his country hated him and sent a delegation after him, saying, \`We do not want this man to rule over us.'   15 When he returned, having received royal power, he ordered these slaves, to whom he had given the money, to be summoned so that he might find out what they had gained by trading.   16 The first came forward and said, \`Lord, your pound has made ten more pounds.'   17 He said to him, \`Well done, good slave! Because you have been trustworthy in a very small thing, take charge of ten cities.'   18 Then the second came, saying, \`Lord, your pound has made five pounds.'   19 He said to him, \`And you, rule over five cities.'   20 Then the other came, saying, \`Lord, here is your pound. I wrapped it up in a piece of cloth,   21 for I was afraid of you, because you are a harsh man; you take what you did not deposit, and reap what you did not sow.'   22 He said to him, \`I will judge you by your own words, you wicked slave! You knew, did you, that I was a harsh man, taking what I did not deposit and reaping what I did not sow?   23 Why then did you not put my money into the bank? Then when I returned, I could have collected it with interest.'   24 He said to the bystanders, \`Take the pound from him and give it to the one who has ten pounds.'   25  (And they said to him, \`Lord, he has ten pounds!')   26  \`I tell you, to all those who have, more will be given; but from those who have nothing, even what they have will be taken away.

22:28-30 "You are those who have stood by me in my trials;   29 and I confer on you, just as my Father has conferred on me, a kingdom,   30   so that you may eat and drink at my table in my kingdom, and you will sit on thrones judging the twelve tribes of Israel.

## 失われた語録 Q のルカとマタイ対照表

### 対照表

+------------------------------------+---------------------------------+
| **ルカ 3:3**                       | マタイ 3:5-6                    |
+------------------------------------+---------------------------------+
| **ルカ 3:7b-9**                    | マタイ 3:7b-9.                  |
+------------------------------------+---------------------------------+
| **ルカ 3:16b-17**                  | マタイ 3:11-13                  |
+------------------------------------+---------------------------------+
| **ルカ 3:21-22**                   | マタイ 3:13-17                  |
+------------------------------------+---------------------------------+
| **ルカ 4:1-13**                    | マタイ 4:1-11                   |
+------------------------------------+---------------------------------+
| **ルカ 4:16a**                     | マタイ 4:13.                    |
+------------------------------------+---------------------------------+
| **ルカ 6:20-23**                   | マタイ 5:2-12                   |
+------------------------------------+---------------------------------+
| **ルカ 6:24-26**                   | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 6:27-36**                   | マタイ 5:38-48                  |
+------------------------------------+---------------------------------+
| **ルカ 6:37-42**                   | マタイ 7:1-5                    |
+------------------------------------+---------------------------------+
| **ルカ 7:1**                       | マタイ 7:28-29                  |
+------------------------------------+---------------------------------+
| **ルカ 7:43-45**                   | マタイ 7:16-20\                 |
|                                    |                                 |
|                                    | マタイ 12:33-35                 |
+------------------------------------+---------------------------------+
| **ルカ 6:46**                      | マタイ 7:21-23                  |
+------------------------------------+---------------------------------+
| **ルカ 6:47-49**                   | マタイ 7:24-27                  |
+------------------------------------+---------------------------------+
| **ルカ 7:1-10**                    | マタイ 8:5-13                   |
+------------------------------------+---------------------------------+
| **ルカ 7:18-23**                   | マタイ 11:2-6                   |
+------------------------------------+---------------------------------+
| **ルカ 7:24-28**                   | マタイ 11:7-11                  |
+------------------------------------+---------------------------------+
| **ルカ 7:29-30**                   | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 7:31-35**                   | マタイ 11:16-19                 |
+------------------------------------+---------------------------------+
| **ルカ 9:57-62**                   | マタイ 8:18-22                  |
+------------------------------------+---------------------------------+
| **ルカ 10:2-16**                   | マタイ 9:37-38\                 |
|                                    |                                 |
|                                    | マタイ 10:9-16                  |
|                                    |                                 |
|                                    | マタイ 11:20-24                 |
+------------------------------------+---------------------------------+
| **ルカ 10:21-22**                  | マタイ 11:25-27                 |
+------------------------------------+---------------------------------+
| **ルカ 10:23-24**                  | マタイ 13:16-17                 |
+------------------------------------+---------------------------------+
| **対応箇所なし**                   | マタイ 10:5b-6, 23              |
+------------------------------------+---------------------------------+
| **ルカ 10:25-28**                  | マタイ 22:35-40                 |
+------------------------------------+---------------------------------+
| **ルカ 11:2-4**                    | マタイ 6:9-15                   |
+------------------------------------+---------------------------------+
| **ルカ 11:5-8**                    | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 11:9-13**                   | マタイ 7:7-11.                  |
+------------------------------------+---------------------------------+
| **ルカ 11:14-20**                  | マタイ 12:22-28                 |
+------------------------------------+---------------------------------+
| **ルカ 11:21-23**                  | マタイ 11:29-30                 |
+------------------------------------+---------------------------------+
| **ルカ 11:24-26**                  | マタイ 12:43-45.                |
+------------------------------------+---------------------------------+
| **ルカ 11:27-28**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 11:29-32**                  | マタイ 12:38-42                 |
+------------------------------------+---------------------------------+
| **ルカ 11:33-36**                  | マタイ 5:15-16\                 |
|                                    |                                 |
|                                    | マタイ 6:22-23                  |
+------------------------------------+---------------------------------+
| **ルカ 11:39-52**                  | マタイ 23:25-36                 |
+------------------------------------+---------------------------------+
| **ルカ 12:2-12**                   | マタイ 10:26-33                 |
+------------------------------------+---------------------------------+
| **ルカ 12:13-14**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 12:16-21**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 12:22-34**                  | マタイ 6:25-34\                 |
|                                    |                                 |
|                                    | マタイ 6:19-21                  |
+------------------------------------+---------------------------------+
| **ルカ 12:35-38**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 12:39-40**                  | マタイ 24:43-44                 |
+------------------------------------+---------------------------------+
| **ルカ 12:42-46**                  | マタイ 24:45-51                 |
+------------------------------------+---------------------------------+
| **ルカ 12:49, 51-53**              | マタイ 10:34-36                 |
+------------------------------------+---------------------------------+
| **ルカ 12:54-56**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 12:58-59**                  | マタイ 5:25-26                  |
+------------------------------------+---------------------------------+
| **ルカ 13:18-21**                  | マタイ 13:31-33                 |
+------------------------------------+---------------------------------+
| **ルカ 13:24-25**                  | マタイ 7:13-14\                 |
|                                    |                                 |
|                                    | マタイ 25:11-12                 |
+------------------------------------+---------------------------------+
| **ルカ 13:28-30**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 13:34-35**                  | マタイ 23:37-39                 |
+------------------------------------+---------------------------------+
| **ルカ 14:5**                      | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 14:11**\                    | 対応箇所なし                    |
|                                    |                                 |
| ルカ 18:14                         |                                 |
+------------------------------------+---------------------------------+
| **ルカ 14:16-24**                  | マタイ 22:1-14                  |
+------------------------------------+---------------------------------+
| **ルカ 14:26-27**\                 | マタイ 10:37-39                 |
|                                    |                                 |
| ルカ 17:33                         |                                 |
+------------------------------------+---------------------------------+
| **ルカ 14:34-35**                  | マタイ 5:13                     |
+------------------------------------+---------------------------------+
| **ルカ 15:4-7**                    | マタイ 18:12-14                 |
+------------------------------------+---------------------------------+
| **ルカ 15:8-10**                   | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 16:13**                     | マタイ 6:24                     |
+------------------------------------+---------------------------------+
| **ルカ 16:16**                     | マタイ 11:12                    |
+------------------------------------+---------------------------------+
| **ルカ 16:17-18**                  | マタイ 5:18\                    |
|                                    |                                 |
|                                    | マタイ 5:31-32                  |
|                                    |                                 |
|                                    | マタイ 19:9                     |
+------------------------------------+---------------------------------+
| ルカ 17:1-2                        | マタイ 18:6-7                   |
+------------------------------------+---------------------------------+
| **ルカ 17:3-4**                    | マタイ 18:15\                   |
|                                    |                                 |
|                                    | マタイ 18:21-22                 |
+------------------------------------+---------------------------------+
| **ルカ 17:6**                      | マタイ 17:20-21                 |
+------------------------------------+---------------------------------+
| **ルカ 17:23-24, 37**              | マタイ 24:26-28                 |
+------------------------------------+---------------------------------+
| **ルカ 17:26-27**                  | マタイ 24:37-39                 |
+------------------------------------+---------------------------------+
| **ルカ 17:28-30**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+
| **ルカ 17:34-35**                  | マタイ 24:40-41.                |
+------------------------------------+---------------------------------+
| **ルカ 19:12-27**                  | マタイ 25:14-30                 |
+------------------------------------+---------------------------------+
| **ルカ 22:28-30**                  | 対応箇所なし                    |
+------------------------------------+---------------------------------+

### Q の内容

[The Contents of Q](earlychristianwritings.com/q-contents.html) の Google Chrome による和訳（2025.7.5）

Q の内容についての、さまざまな近年の文献、特に以下の三つの文献における対照表をまとめたもの。

-   Richard A. Edwards, A Theology of Q: Eschatology, Prophecy, and Wisdom (Philadelphia, PA: Fortress Press 1976).

-   Robert J. Miller, ed., The Complete Gospels: Annotated Scholars Version (Sonoma, CA: Polebridge Press 1992).

-   Burton L. Mack, The Lost Gospel: The Book of Q & Christian Origins (San Francisco, CA: HarperCollins 1993).

-   John S. Kloppenborg Verbin, Excavating Q: The History and Setting of the Sayings Gospel (Minneapolis, MN: Fortress Press 2000).

------------------------------------------------------------------------

#### Edward *A Theology of Q* pp. xi-xiii

+--------------------------------+------------+------------+-----------+
| タイトル                       | **マタイ** | **マルコ** | **ルカ**  |
+--------------------------------+------------+------------+-----------+
| ヨハネの説教                   | 3:7-10\    | 1:7-8      | 3:7-9\    |
|                                | 3:11-12    |            | 3:15-18   |
+--------------------------------+------------+------------+-----------+
| 誘惑                           | 4:1-11     |            | 4:1-13    |
+--------------------------------+------------+------------+-----------+
| 至福の教え                     | 5:3-12     |            | 6:20b-23  |
+--------------------------------+------------+------------+-----------+
| 敵を愛せよ                     | 5:38-48\   |            | 6:27-36   |
|                                | 7:12       |            |           |
+--------------------------------+------------+------------+-----------+
| 裁くな                         | 7:1-5\     | 4:24-25    | 6:37-42   |
|                                | 12:36-37\  |            |           |
|                                | 15:14\     |            |           |
|                                | 10:24-25   |            |           |
+--------------------------------+------------+------------+-----------+
| 実について                     | 7:15-20\   |            | 6:43-45   |
|                                | 12:33-35   |            |           |
+--------------------------------+------------+------------+-----------+
| 岩の上に建てられた家           | 7:21-27    |            | 6:46-49   |
+--------------------------------+------------+------------+-----------+
| カペナウムの百卒長             | 8:5-13     |            | 7:1-10\   |
|                                |            |            | 13:28-29  |
+--------------------------------+------------+------------+-----------+
| ヨハネの質問とイエスの答え     | 11:2-6     |            | 7:18-23   |
+--------------------------------+------------+------------+-----------+
| ヨハネについてのイエスの証言   | 11:7-19\   |            | 7:24-35\  |
|                                | 21:31-32   |            | 16:16     |
+--------------------------------+------------+------------+-----------+
| 十二弟子の派遣                 | 10:1\      | 6:6b-13    | 9:1-6     |
|                                | 10:7-11\   |            |           |
|                                | 10:14      |            |           |
+--------------------------------+------------+------------+-----------+
| イエスに従うということ         | 8:18-22    |            | 9:57-62   |
+--------------------------------+------------+------------+-----------+
| 七十人の派遣                   | 9:37-38\   |            | 10:1-12   |
|                                | 10:7-16    |            |           |
+--------------------------------+------------+------------+-----------+
| ガリラヤへの呪い               | 11:20-24   |            | 10:13-15\ |
|                                |            |            | 10:12     |
+--------------------------------+------------+------------+-----------+
| あなたに聞くものは私に聞くもの | 10:40      |            | 10:16     |
+--------------------------------+------------+------------+-----------+
| 弟子についての感謝と祝福       | 11:25-27\  |            | 10:21-24  |
|                                | 13:16-17   |            |           |
+--------------------------------+------------+------------+-----------+
| 主の祈り                       | 6:9-13     |            | 11:1-4    |
+--------------------------------+------------+------------+-----------+
| 祈りの勧め                     | 7:7-11     |            | 11:9-13   |
+--------------------------------+------------+------------+-----------+
| ベエルゼブルについて           | 12:22-30\  | 3:22-27    | 11:14-23  |
|                                | 9:32-34    |            |           |
+--------------------------------+------------+------------+-----------+
| 悪霊が戻ってくる               | 12:43-45   |            | 11:24-26  |
+--------------------------------+------------+------------+-----------+
| ヨナのしるし                   | 12:38-42\  | 8:11-12    | 11:16\    |
|                                | 16:1-4     |            | 11:29-32  |
+--------------------------------+------------+------------+-----------+
| 澄んだ目                       | 6:22-23    |            | 11:34-36  |
+--------------------------------+------------+------------+-----------+
| パリサイ人批判                 | 23:4-36    | 7:1-9      | 11:37-54  |
+--------------------------------+------------+------------+-----------+
| 告白を恐れるな                 | 10:26-33   |            | 12:2-9    |
+--------------------------------+------------+------------+-----------+
| 聖霊を冒涜すること             | 12:31-32   | 3:29-30    | 12:10     |
+--------------------------------+------------+------------+-----------+
| 聖霊の導き                     | 10:19-20   | 13:11      | 12:11-12\ |
|                                |            |            | 21:14-15  |
+--------------------------------+------------+------------+-----------+
| 思い煩い                       | 6:25-34    |            | 12:22-32  |
+--------------------------------+------------+------------+-----------+
| 天の宝                         | 6:19-21    |            | 12:33-34  |
+--------------------------------+------------+------------+-----------+
| 気をつけていなさい             | 24:42-51   |            | 12:35-48  |
+--------------------------------+------------+------------+-----------+
| 家の中の分断                   | 10:34-36   |            | 12:49-53  |
+--------------------------------+------------+------------+-----------+
| 時のしるし                     | 16:2-3     |            | 12:54-56  |
+--------------------------------+------------+------------+-----------+
| 訴えるものとの和解             | 5:25-26    |            | 12:57-59  |
+--------------------------------+------------+------------+-----------+
| からし種                       | 13:31-32   | 4:30-32    | 13:18-19  |
+--------------------------------+------------+------------+-----------+
| パン種                         | 13:33      |            | 13:20-21  |
+--------------------------------+------------+------------+-----------+
| 神の国からの追い出される       | 7:13-14\   |            | 13:22-30  |
|                                | 7:22-23\   |            |           |
|                                | 8:11-12\   |            |           |
|                                | 19:30      |            |           |
+--------------------------------+------------+------------+-----------+
| エルサレムについて嘆く         | 23:37-39   |            | 13:34-35  |
+--------------------------------+------------+------------+-----------+
| 王子のための婚宴               | 22:1-14    |            | 14:15-24  |
+--------------------------------+------------+------------+-----------+
| 弟子の条件                     | 10:37-38   |            | 14:25-33  |
+--------------------------------+------------+------------+-----------+
| 塩のたとえ                     | 5:13       | 9:49-50    | 14:34-35  |
+--------------------------------+------------+------------+-----------+
| 失われた羊                     | 18:12-14   |            | 15:1-7    |
+--------------------------------+------------+------------+-----------+
| ふたりの主人                   | 6:24       |            | 16:13     |
+--------------------------------+------------+------------+-----------+
| 律法について                   | 11:12-13\  |            | 16:16-17  |
|                                | 5:18       |            |           |
+--------------------------------+------------+------------+-----------+
| 非難について                   | 18:6-7     | 9:42       | 17:1-3a   |
+--------------------------------+------------+------------+-----------+
| ゆるしについて                 | 18:15\     |            | 17:3b-4   |
|                                | 18:21-22   |            |           |
+--------------------------------+------------+------------+-----------+
| 信仰について                   | 17:19-20   | 9:28-29    | 17:5-6    |
+--------------------------------+------------+------------+-----------+
| 人の子の日                     | 24:23\     | 13:19-23\  | 17:22-37  |
|                                | 24:26-27\  | 13:14-16   |           |
|                                | 24:37-39\  |            |           |
|                                | 24:17-18\  |            |           |
|                                | 10:39\     |            |           |
|                                | 24:40-41\  |            |           |
|                                | 24:28      |            |           |
+--------------------------------+------------+------------+-----------+
| タラントのたとえ               | 25:14-30   |            | 19:11-27  |
+--------------------------------+------------+------------+-----------+
| 先の者                         | 19:28      | 10:41-45   | 22:28-30  |
+--------------------------------+------------+------------+-----------+

------------------------------------------------------------------------

#### Robert J. Miller, ed., *The Complete Gospels*, pp. 249-300

|  |  |  |
|----|----|----|
| **タイトル** | **ルカ** | **マタイ** |
| ヨハネの説教 | ルカ 3:7-9 | マタイ 3:7-10 |
| 来るべき方 | ルカ 3:16-17 | マタイ 3:11-12 |
| 誘惑 | ルカ 4:1-13 | マタイ 4:1-4, 9-12, 5-7, 13 |
| 最初の説教 | ルカ 6:12, 17, 20 | マタイ 5:1-2 |
| 幸いなるかな | ルカ 6:20-26 | マタイ 5:3, 6, 4, 11-12 |
| 敵を愛せよ | ルカ 6:27-36 | マタイ 5:44, 39-42; 7:12; 5:46-47, 45, 48 |
| 裁くな | ルカ 6:37-38 | マタイ 7:1-2 |
| 盲人の手引き | ルカ 6:39-40 | マタイ 15:14; 10:24-25 |
| 虚勢 | ルカ 6:41-42 | マタイ 7:3-5 |
| 木とその実 | ルカ 6:43-45 | マタイ 7:16-20; 12:33-35 |
| 土台 | ルカ 6:46-49 | マタイ 7:21, 24-27 |
| 百卒長の僕 | ルカ 7:1-10 | マタイ 7:28; 8:5-10, 13 |
| ヨハネの問い | ルカ 7:18-20, 22-23 | マタイ 11:2-6 |
| イエス、ヨハネを祝福 | ルカ 7:24-28 | マタイ 11:7-11 |
| 律法と預言者 | ルカ 16:16 | マタイ 11:12-13 |
| 市場のこどもたち | ルカ 7:31-35 | マタイ 11:16-19 |
| きつねには穴 | ルカ 9:57-62 | マタイ 8:19-22 |
| 宣教について | ルカ 10:2-12 | マタイ 9:37-38; 10:7-16 |
| コラジンを呪う | ルカ 10:13-15 | マタイ 11:21-24 |
| おつかわしになった方を拒む | ルカ 10:16 | マタイ 10:40 |
| 父と子 | ルカ 10:21-22 | マタイ 11:25-27 |
| 見ているものは幸い | ルカ 10:23-24 | マタイ 13:16-17 |
| 主の祈り | ルカ 11:2-4 | マタイ 6:9-13 |
| 求め、探し、門を叩け | ルカ 11:9-13 | マタイ 7:7-11 |
| ベエルゼブルについて | ルカ 11:14-23 | マタイ 12:22-30 |
| 悪霊が戻ってくる | ルカ 11:24-26 | マタイ 12:43-45 |
| 恵まれた胎 | ルカ 11:27-28 |  |
| しるしを求める | ルカ 11:16, 29-32 | マタイ 12:38-42 |
| あかりとかご | ルカ 11:33 | マタイ 5:15 |
| 目とひかり | ルカ 11:34-36 | マタイ 6:22-23 |
| 預言者の墓 | ルカ 11:47-48 | マタイ 23:29-32 |
| 義人の血の報い | ルカ 11:49-51 | マタイ 23:34-36 |
| 天国への道を閉ざすもの | ルカ 11:52 | マタイ 23:13 |
| 覆われたもの | ルカ 12:2-3 | マタイ 10:26-27 |
| 神とつばめ | ルカ 12:4-7 | マタイ 10:28-31 |
| 父の前で受け入れる | ルカ 12:8-9 | マタイ 10:32-33 |
| 冒涜 | ルカ 12:10 | マタイ 12:32 |
| 霊が語る | ルカ 12:11-12 | マタイ 10:19 |
| 遺産の問題 | ルカ 12:13-14 |  |
| 富んだ農夫 | ルカ 12:16-21 |  |
| 思い煩い | ルカ 12:22-31 | マタイ 6:25-33 |
| 持ち物 | ルカ 12:33-34 | マタイ 6:19-21 |
| 家の主人と強盗 | ルカ 12:39-40 | マタイ 24:43-44 |
| 予想しない時に来る | ルカ 12:42-46 | マタイ 24:45-51 |
| 平和と紛争 | ルカ 12:49, 51-53 | マタイ 10:34-36 |
| 時を知ること | ルカ 12:54-56 | マタイ 16:2-3 |
| 裁判官の前で | ルカ 12:57-59 | マタイ 5:25-26 |
| からしだねとぱんだね | ルカ 13:18-21 | マタイ 13:31-33 |
| 二つの門 | ルカ 13:24-27 | マタイ 7:13-14, 22-23 |
| Dining with patriarchs | ルカ 13:28-30 | マタイ 8:11-12; 20:16 |
| Jerusalem indicted | ルカ 13:34-35 | マタイ 23:37-39 |
| Promotion & demotion | ルカ 14:11, 18:14 | マタイ 23:12 |
| The feast | ルカ 14:16-24 | マタイ 22:1-10 |
| Hating one's family | ルカ 14:26-27, 17:33 | マタイ 10:37-39 |
| Saltless salt | ルカ 14:34-35 | マタイ 5:13 |
| Lost sheep & coin | ルカ 15:4-10 | マタイ 18:12-13 |
| Two masters | ルカ 16:13 | マタイ 6:24 |
| God's rule & violence | ルカ 16:16 | マタイ 11:12-13 |
| Not one serif | ルカ 16:17 | マタイ 5:18 |
| On divorce | ルカ 16:18 | マタイ 5:32 |
| Millstone award | ルカ 17:1-2 | マタイ 18:6-7 |
| Scold & forgive | ルカ 17:3-4 | マタイ 18:15, 21-22 |
| Mountains into the sea | ルカ 17:6 | マタイ 17:20 |
| Coming of son of Adam | ルカ 17:22-24, 26-30, 34-35, 37 | マタイ 24:26-28, 37, 39-41 |
| Entrusted money | ルカ 19:12-26 | マタイ 25:14-30 |
| On twelve thrones | ルカ 22:28-30 | マタイ 19:28 |

------------------------------------------------------------------------

#### Burton L. Mack in *The Lost Gospel*, pp. 260-261

|  |  |  |
|----|----|----|
| **Title** | **ルカ** | **Verses in Thomas** |
| QS 1. Title |  |  |
| QS 2. The Setting for the Instructions |  |  |
| QS 3. The Appearance of John | 3:1-6 |  |
| QS 4. John's Address to the People | 3:7-9 |  |
| QS 5. John's Prediction of Someone to Come | 3:16-17 |  |
| QS 6. Jesus Tempted by the Accuser | 4:1-13 |  |
| QS 7. Introduction | 6:20 |  |
| QS 8. On Those who are Fortunate | 6:20-23 | 54; 68; 69 |
| QS 9. On Responding to Reproach | 6:27-35 | 95; 6:2 |
| QS 10. On Making Judgments | 6:36-38 |  |
| QS 11. On Teachers and Students | 6:39-40 | 34 |
| QS 12. On Hypocrisy | 6:41-42 | 26 |
| QS 13. On Integrity | 6:43-45 | 45 |
| QS 14. On Practical Obedience | 6:46-69 |  |
| QS 15. The Occasion | 7:1-10 |  |
| QS 16. John's Inquiry | 7:18-23 |  |
| QS 17. What Jesus Said about John | 7:24-28 | 74; 46 |
| QS 18. What Jesus Said about this Generation | 7:31-35 |  |
| QS 19. On Becoming a Follower of Jesus | 9:57-62 | 86 |
| QS 20. On Working for the Kingdom of God | 10:1-11 | 73; 14:2 |
| QS 21. The Unreceptive Town | 10:12 |  |
| QS 22. The Galilean Towns | 10:13-15 |  |
| QS 23. On the one who Receives the Worker | 10:16 |  |
| QS 24. On the one who Receives Revelation | 10:21-22 | 61? |
| QS 25. On the one who Hears and Sees | 10:23-24 |  |
| QS 26. How to Pray | 11:1-4 |  |
| QS 27. Confidence in Asking | 11:9-13 | 2; 92; 94 |
| QS 28. On Kingdoms in Conflict | 11:14-23 | 35 |
| QS 29. Those for and those against | 11:23 |  |
| QS 30. On the Return of an Evil Spirit | 11:24-26 |  |
| QS 31. Hearing and Keeping the Teaching of God | 11:27-28 |  |
| QS 32. The Sign of Jonah | 11:16, 29-32 |  |
| QS 33. The Lamp and the Eye | 11:33-35 | 33:2 |
| QS 34. O You Pharisees | 11:39-52 | 39:1; 89; 102 |
| QS 35. On Speaking Out | 12:2-3 | 5:2; 6:3; 33:1 |
| QS 36. On Fear | 12:4-7 |  |
| QS 37. On Public Confessions | 12:8-12 | 44 |
| QS 38. Foolish Possessions | 12:13-21 |  |
| QS 39. On Food and Clothing | 12:22-31 | 36 |
| QS 40. On Heavenly Treasure | 12:33-34 | 76:2 |
| QS 41. The Hour | 12:39-40 | 21:3; 103 |
| QS 42. On Faithfulness | 12:42-46 |  |
| QS 43. Fire and Division | 12:49-53 | 16 |
| QS 44. Signs of the Times | 12:54-56 | 91 |
| QS 45. Settling Accounts | 12:57-59 |  |
| QS 46. The Mustard and the Yeast | 13:18-21 | 20, 96 |
| QS 47. The Narrow Gate and Closed Door | 13:24-27 |  |
| QS 48. Exclusion from the Kingdom | 13:28-30 |  |
| QS 49. Lament over Jerusalem | 13:34-35 |  |
| QS 50. On Humility | 14:11; 18:14 |  |
| QS 51. The Great Supper | 14:16-24 | 64 |
| QS 52. On the Cost of Being a Disciple | 14:26-27; 17:33 | 55; 101 |
| QS 53. Savorless Salt | 14:34-35 |  |
| QS 54. When to Rejoice | 15:4-10 | 107 |
| QS 55. Either/Or | 16:13 | 47:2 |
| QS 56. The Kingdom and the Law | 16:16-18 |  |
| QS 57. On Scandals | 17:1-2 |  |
| QS 58. On Forgiveness | 17:3-4 |  |
| QS 59. On Faith | 17:6 |  |
| QS 60. The Day of Separation | 17:23-37 | 3; 51; 61; 113 |
| QS 61. Squaring Accounts | 19:11-27 | 41 |
| QS 62. Judging Israel | 22:28-30 |  |

------------------------------------------------------------------------

#### John S. Kloppenborg Verbin, *Excavating Q*, p. 100

Sigla

|             |                 |
|-------------|-----------------|
| 3:7b-9      | Highly Probable |
| 3:(3)       | Probable        |
| \<3:21-22\> | Doubtful        |

|          |                                |
|----------|--------------------------------|
| 3:(3)    | Setting of John's Preaching    |
| 3:7b-9   | John's Preaching of Repentance |
| 3:16b-17 | The Coming One                 |

|                      |                                              |
|----------------------|----------------------------------------------|
| \<3:21-22\>          | \<The Baptism of Jesus\>                     |
| 4:1-13               | The Temptations                              |
| 4:(16a)              | Reference to Nazara                          |
| 6:20a                | Introduction to the Sermon                   |
| 6:20b-23             | Beatitudes                                   |
| 6:(24-26)            | Woes                                         |
| 6:27-33              | On Retaliation; Generous Giving; Golden Rule |
| (Q/Matt 5:41)        | Go the Second Mile                           |
| 6:(34-35b), 35c      | Conclusion                                   |
| 6:36-37b, 38c        | On Mercy and Judging                         |
| 6:39-45              | On Self-Correction                           |
| 6:46                 | Why Do You Call Me Lord?                     |
| 6:46-49              | The Two House-Builders                       |
| 7:1b-2, 6b-10        | The Centurion at Kefar Nahum                 |
| 7:18-19, 22-23       | John's Question                              |
| 7:24-28              | Jesus' Eulogy of John                        |
| 7:(29-30)            | John, Tax Collectors, and Prostitutes        |
| 7:31-35              | Children in the Agora                        |
| 9:57-60, (61-62)     | Two (Three?) Volunteers                      |
| 10:2-16              | Mission Instructions                         |
| 10:21-22             | Thanksgiving for Revelation                  |
| 10:23b-24            | Commendation of Disciples                    |
| \<Matt 10:5b-6, 23\> | \<Limiting the Mission to Israel\>           |
| \<10:25-28\>         | \<The Great Command\>                        |
| 11:2-4, \<5-8\>      | The Lord's Prayer, \<Midnight Friend\>       |
| 11:9-13              | Sayings on Prayer                            |
| 11:14-20             | The Beelzebul Controversy                    |
| 11:(21-22)           | Binding the Strong Man                       |
| 11:23                | Whoever is Not against Me                    |
| 11:24-26             | Return of the Evil Spirit                    |
| 11:(27-28)           | A Woman in the Crowd                         |
| 11:29-32             | Request for a Sign                           |
| 11:33-35 (36)        | Lamp; Sayings on Light                       |
| 11:39-44, 46-52      | Woes against Pharisees and Lawyers           |
| 12:2-12              | Fearless Confession                          |

------------------------------------------------------------------------

## 参考：失われた語録 Q に関する情報

Google Chrome による和訳（2025.7.5）

現代の学者の大多数が受け入れている二源説によれば、マタイとルカの著者はそれぞれ二つの異なる源泉、すなわちマルコ福音書と、現存しない第二の源泉であるQを用いていたとされる。Qのシグルム（印章）はドイツ語の「Quelle」（源泉）に由来し、これは「源泉」を意味する。Qは主に「二重伝承」の資料、すなわちマタイとルカの両方に存在するがマルコには存在しない資料から構成されている。しかし、Qにはマタイのみ、あるいはルカのみに残されている資料（「ゾンダーグート」と呼ばれる）や、マルコで類似する資料（マルコ/Q重複と呼ばれる）も含まれている可能性がある。誘惑の物語と百人隊長の息子の癒しは一般にQに帰せられるが、資料の大部分は言葉で構成されている。このため、Qは共観言葉源、あるいは言葉福音書と呼ばれることもある。一部の学者は、トマスによる福音書と Q 資料は、正典の 4 つの福音書と比較すると、イエスの受難ではなくイエスの言動を強調している点で似ていると指摘しています。

[2 つの源泉仮説を支持する議論は、「Q の存在」](https://www.earlychristianwritings.com/q-exist.html) に関するエッセイに記載されています。

Q が書かれたかどうかについて、タケットは次のように書いている（*『アンカー聖書辞典*』第 5 巻、568 ページ）。「Q が口承伝承の集合体であるという説は、Q 資料の共通の順序を説明できない。マタイが関連資料をまとめて大規模な説教にまとめる習慣を考慮すれば、この共通の順序は明らかである（テイラー、1953 年、1959 年）。このような共通の順序は、Q が何らかの段階で書面の形で存在していたという説を必然的に生み出す。」

CM タケットは、マタイとルカの相違はアラム語の Q の異訳によるものだという議論について次のようにコメントしています (同上、567-568 ページ)。

> マタイとルカの間の差異は、ごく少数の例に過ぎず、この方法で説明できるかどうかは疑わしい。Qのギリシャ語がセム語系であるため、アラム語原典を必要としない。ギリシャ語を話すユダヤ・キリスト教社会においては、LXXの影響は十分に考えられる。翻訳上の差異とされるものの多くは、単なる同義語の例であることが判明し、マタイとルカの相違は、福音書記者の編集作業によっても十分に説明できる場合が多い（Kloppenborg 1987）。例えば、ルカ11:41の「施しをする」は、ルカの施しに対する関心を反映して、LkR（ルカによる編集）である可能性が高い。Q資料の他の部分では、マタイとルカの語法の一致は、ギリシャ語では事実上、語法の同一性に等しい（ルカ3:7-9、11:9-10および各節）。これらの例において、言葉の一致の程度は共通のギリシャ語源を必要とするように思われる。さらに、Qのギリシャ語には、元々ギリシャ語で書かれた資料の特徴であり、翻訳ギリシャ語の特徴ではないことが示される（Turner 1969）。これは、Qの資料の多くがギリシャ語の形でマタイとルカに利用可能であったことを示唆している。

ウド・シュネルは、Qの起源について次のようにコメントしている（*『新約聖書の歴史と神学』* 186ページ）。

> 言行録は、その神学的視点が主にイスラエルに向けられていることから、おそらく（北）*パレスチナ*で発祥したと考えられる。文書の冒頭と末尾にある裁きの宣言はイスラエルに向けられており（ルカ3:7-9Q、ルカ22:28-30Q参照）、多くのロギア（logia）は、その地理的参照と想定される文化世界によってパレスチナを中心としている（ルカ7:1Q、10:13-15Qのみ参照）、Qの伝統の担い手は律法に忠実であると認識している（ルカ16:17Q、ルカ11:42Q参照）、そしてQの論争はパリサイ人に向けられている（例えばルカ11:39b-44Q参照）。

ヘルムート・ケスターは、Qの起源について次のようにコメントしている（*古代キリスト教福音書*、164ページ）。

> 問10:13-15は、ガリラヤの二つの町、コラジンとベツサイダに向けられた、来たるべき裁きを明示的に告げています。ティルスとディドンでさえ、来たるべき裁きにおいてより良い状態となるでしょう。そして同じ言葉は、カペナウムがハデスに堕ちると警告しています。エルサレムへの嘆き（問13:34-35）と、洗礼者ヨハネの活動がヨルダン川流域に限局していること（問3:3）を除けば、これらは問に登場する唯一の地名です。したがって、問の編集はガリラヤのどこかで行われ、文書全体がイエスの弟子であるガリラヤの共同体の経験を反映していると考えるのは魅力的です。しかし、そのような結論にはいくつかの理由から注意が必要です。一つの言葉だけでは、非常に狭い根拠しか提供できないからです。パリサイ人に対する論争はガリラヤ起源であることを確証することはできない。ギリシャ語を話すパリサイ人はディアスポラの他の場所にも存在した可能性がある。例えば、シリアかキリキアのギリシャ語圏の会堂で教会を迫害したパウロなどである。Qの原文に使われた格言さえも、古くから知られ、他の場所でも使われていた。パウロも知っていたし、コリントでは彼の反対者によって使われ、おそらく東シリアでは*トマスによる福音書の文に使われ、1世紀末にはローマでクレメンス1世*によって引用された。最終的に編集された形で、その文書自体は、パレスチナ外のギリシャ語圏の教会で生まれたマタイによる福音書とルカによる福音書という2つの福音書の文に使われた。

ウド・シュネルはQの年代について次のように書いている（同上、186ページ）。

> ルカ13:34-35Qにあるエルサレムと神殿に対する言葉はいかなる軍事的出来事も前提としていないため、言行録は神殿破壊以前に執筆されたものである。執筆時期のより正確な決定は仮説の域を出ないが、いくつかの兆候は*西暦40年から50年*の間を示唆している：(1) おそらく復活祭前にまで遡る言行録の伝承者には、イエス運動の放浪説教者と地元の教会の両方が含まれていた。したがって、言行録が生まれた状況には、始まりとの連続性、および地域全体で発展する教会構造の両方が含まれていた。(2) 言行録は、パレスチナ系ユダヤ人による若い教会への迫害を前提としている（ルカ6:22-23 Q、ルカ11:49-51 Q、ルカ12:4-5 Q、12:11-12 Qを参照）。西暦50年頃、パウロはテサロニケ人への第一の手紙2章14-16節で、ユダヤにおけるキリスト教徒への迫害が既に起こっていたことを述べています。ゼベダイの子ヤコブがアグリッパ1世によって処刑されたのは（使徒言行録12章2節参照）、西暦44年頃でした。(3) 異邦人に関する肯定的な言及（ルカ10章13-15節Q、ルカ11章29-31節Q、マタイ8章5-13節Q、マタイ5章47節Q、マタイ22章1-10節Q参照）は、異邦人への宣教が始まっていたことを示唆しており、それはおそらく西暦40年から50年の間に始まったと考えられます。

バートン・マックはマルコとQについて次のように書いています（*『失われた福音書*』177～179ページ）。

> マルコは戦争後しばらくして、QがQ3の加筆によって改訂された直後にイエスの物語を執筆しました。戦争の影響が明らかにあった加筆を考慮してQ3の年代を西暦75年頃とすると、マルコは西暦75年から80年の間に遡ることができます。マルコにとってQは非常に有益でした。なぜなら、Qは既にイエスを叙事詩的・黙示録的な歴史の要に位置付けており、イエスの公の場における出現をより波瀾万丈な描写に容易に転換できるテーマや物語の材料を含んでいたからです。Qはマルコに、彼の物語に不可欠な多くのテーマを与えました。彼は叙事詩的・黙示録的な神話、預言的な予言、そして律法学者、パリサイ人、そして「この世代」への裁きの告知に魅了されていました。人の子というイメージは彼を魅了した。神の国は、人の子（マルコによればイエス）が（再）現れる終末においてのみ完全に啓示されるという考えも同様だった。Qはまた、首尾一貫した物語の構成要素として容易に活用できる素材を提供した。ヨハネとイエスに関する素材は素晴らしい導入部となった。聖霊の比喩は、ヨハネとイエスに関するQの素材とマルコが用いる奇跡物語を結びつけるのに既に用意されていた。Qがイエスを全知者として描写したことは、マルコが自身の共同体から既に得ていた宣告物語において、自己言及的な語り手としてのQの権威を高めるために利用された。イエスを神の子とする概念は、神秘性を生み出し、イエスの真の正体に関する疑問をめぐって議論を二分し、物語への期待を高めるために利用された。学者たちがマルコの「メシア的秘密」と呼ぶ手法である。収穫の働き手への指示は、伝道の使命へと転換され、弟子としての生き方というテーマは、物語に弟子を何人か登場させることで、物語の輪郭を帯びたものへと変化させることもできるでしょう。そして、Qの終わりにある終末的な預言は、イエスがエルサレムへ向かう物語の時点で、弟子たちへの指示となるかもしれません。そして、研究者たちが知っているように、マルコとQの間には、いわゆる「重なり合う部分」が数多く存在し、マルコがQの資料を自身の物語構成に利用していることを示しています。

ウド・シュネルはQとマークの関係について次のようにコメントしている（同上、195ページ）。

> Q とマルコの共通素材 (マルコ 1.2、1.7-8、1.12-13、3.22-26、27-29、4.21、22、24、25、4.30-32、6.7-13、8.11、12、8.34-35、8.38、9.37、40、42、50、10.10-11、10.31、11.22-23、12.37b-40、13.9、11、33-37 を参照) は、マルコが Q に文学的に依存しているという仮説を何度も導きました。しかし、マルコが Q を知っていたとしたら、彼が使用した素材の選択基準、特に省略した言葉は説明できません。挙げられた理由は仮説にとどまっており（マルコは言行録の補足、Qはマルコの補足、マルコによる言行録のキリスト論に対する批判的な論争）、Qとマルコの文学的構成と神学的志向における大きな相違を納得させるには至っていない。マルコとQを直接文学的に結びつけることはまず考えられない。両者が共有するテキスト複合体は、むしろそれぞれが古いイエスの伝承に*独立してアクセス*していたことを示唆しているが、編集以前のレベルでの二つの伝承の接触も排除できない。

タケットは次のように述べています（同上、570-571ページ）。

> Qのよく議論される特徴は、Qの宣教命令の解釈に由来しています。Qの宣教師たちは、旅のために食料や衣服といった生活必需品さえも一切持参してはならないと告げられています。また、Qの教えは他の箇所でも、過去の個人的な絆との極めて根本的な断絶を前提としているように思われます。Qのクリスチャンは、自分の家族を「憎む」べきであると告げられ（ルカ12:46）、自分の十字架を背負わなければならないと告げられています（ルカ14:27）。神が彼らのために必要なものを備えてくださるので、日々の必要について心配する必要はありません（ルカ12:22-34）。彼らは、頭を置く場所のない人の子に従うべきであり、自分の家族を埋葬するために故郷に帰ることさえ許されないほど、過去との根本的な断絶を迫られています（ルカ9:57-60）。これらの言行録から、Qの背後にはこれらの指示を忠実に守ったキリスト教徒の集団が存在するという、もっともらしい説が導き出された。したがって、Qは、自らの故郷を根本的に断ち切り、神の国のメッセージを宣べ伝えた放浪の預言者やカリスマ派の存在を前提としている（Hoffmann 1972; Theissen 1979）。しかし、10章2節のような言行録の存在は、Qの最終段階において、放浪の説教者たちを支援する定住したキリスト教徒の集団の存在も前提としていることを示唆しているのかもしれない（Zeller 1982, 1984）。

ウド・シュネルは、クロッペンボルグが提案した階層化を要約している（前掲書、188-189ページ）。

> JSクロッペンボルグは、Qの起源を三層モデルで説明しようと提唱している。彼の見解では、Qの最古の層は「知恵の説教」で構成されており、そこには平野／山上の説教と宣教説教の核となる要素に加え、ルカ11章2-4節、9-13節のQ、ルカ12章2-12節、22-34節のQ、ルカ13章24-14章35節のQなどが含まれた。後期には、この複合体はイスラエルに対する裁きの宣告を扱う資料（洗礼者の説教、カペナウムの貴族、洗礼者の質問、ベルゼブル論争、しるしの要求、Qの黙示録）と組み合わされ、部分的に再構成された。三番目で最後の層は誘惑物語であり、これはイエスを神との関係の模範として提示する。

ヘルムート・ケスターは次のように述べています（同上、150ページ）。

> Q の原版には、終末論的な言行だけでなく知恵に関する言行も含まれていたに違いありません。Q が元々、終末論的なメッセージなしにイエスを知恵の教師として描いていたと主張することはできません。*トマスによる福音書*と Q の密接な関係は偶然ではあり得ません。Q の編集者の特徴である人の子に関する典型的な言行や審判の告知は、*トマスによる福音書*ではまったく取り上げられていないため、その著者は Q の最終版についても、Q の編集者がそれ以前の終末論的な言行に重ね合わせた二次的な終末論的解釈についても知らなかったことは明らかです。*トマスによる福音書は、* Q の以前のバージョン、またはその構成で使用された一連の言行に依存しています。

ヘルムート・ケスターは次のように述べています（同上、159ページ）。

> Qの原典にその伝統が表されているイエスの信奉者たちにとって、時代の転換点はイエスの告知である。イエスの言行録の中に、信奉者たちはこの告知の継続を見出す。これらの言行録は終末論的な瞬間を再確認するものであるだけでなく、イエスが知恵の言葉と共同体のための規則を通して語り続ける限りにおいて、新しい時代の共同体の生活の規範でもある。イエスは確かに天の知恵とみなされていたのかもしれない。これは特にQ10:21-22において明らかであり、そこではイエスと父なる神との関係が、知恵と神という確立された知性の概念に基づいて定義されている。Q13:34-35のエルサレムへの嘆きがQの原典に属するならば、イエスは知恵の使者を遣わす者でもある。
>
> 知恵やその使者の逝去が、そのメッセージの緊急性に変化をもたらさないように、イエスの死もまた、彼の宣教の危機とはみなされないでしょう。弟子たちは既に、弟子としての立場（コヘレト9:57-62）と、イエスの宣教を継承する使命（コヘレト10:2-12）において、イエスの足跡に従うよう召されています。イエスの逝去は、この召命をさらに緊急なものにするでしょう。イエスの宣教宣言によって、時代はすでに変わり始めています。この文脈において、イエスの苦しみ、死、そして復活を強調することは無意味です。したがって、コヘレトは、パウロのケリュグマによって神学が代表される共同体にとって、教義の補足として見ることはできません。コヘレト神学と救済論は根本的に異なるのです。

ヘルムート・ケスターは次のように述べています（前掲書、165ページ）。「一方、『共観福音書』の『言行録』は、十字架と復活のケリュグマとは無関係なイエスの信奉者たちの神学が継続していたことを示す重要な証拠です。これは孤立した現象ではなかったことが今や明らかです。コリントの信徒への手紙一1-4章、*トマスによる福音書*、*『救世主の対話』*におけるパウロの反対者、そしてヨハネ福音書共同体におけるヨハネによる福音書の反対者たちは皆、イエスの到来の意義についてこの理解を共有していました。」

タケットは書いている（前掲書、571ページ）

> 近年の研究は、Qに対する編集批判的アプローチがいかに有益であるかを示している。一見すると、こうした研究は極めて仮説的なものに見えるかもしれない。なぜなら、一部の人々が非常に疑わしい前提（Qが単一の文書として存在すること自体）に基づいているからだ。しかしながら、近年のQに関する編集批判的研究によって示されたQ資料の独自性そのものが、共観福音書の伝統の発展過程のある段階で、この資料が独立した実体として存在していたことを示唆している。したがって、Qの神学に関する理論が成功すれば、Qの存在という仮説を裏付けるものとなるかもしれない。Qはまた、原始キリスト教の多様性を私たちに気づかせてくれるかもしれない。それは、例えばパウロやマルコほど十字架中心ではないかもしれないキリスト教信仰のあり方を示している。しかし、それでもなお、それは真実である。
