# しるしの福音

> ### The Signs Gospel
>
> [Early Christian Writings](https://www.earlychristianwritings.com) （初期キリスト教文書）サイトの [The Signs Gospel](https://www.earlychristianwritings.com/signs.html) （しるしの福音）に関してまとめたページ中の [Signs Gospel](https://www.earlychristianwritings.com/text/signs.html) から アンドリュー・バーンハードによるフォートナの復元による英語翻訳の、NRSV からの引用を、聖書協会口語訳に置き換えたもの。
>
> しるしの福音の根拠についての記述は、上記しるしの福音のページに含まれる、Information on the Signs Gospel（しるし福音に関する情報）を、Google Chrome の翻訳機能を使って日本語化したもの（2025.7.3）をもとに編集したものです。

### アンドリュー・バーンハードによるフォートナの復元による英語翻訳からの和訳

英文には、聖書協会口語訳をあて、英文で斜体になっている部分も含め、修正はせず、節をそのまま挿入した。

#### ヨハネ1章

\[6\] There was a man sent from God, whose name was John.

ここにひとりの人があって、神からつかわされていた。その名をヨハネと言った。

\[7\] He came as a witness, so that all might believe through him.

この人はあかしのためにきた。光についてあかしをし、彼によってすべての人が信じるためである。

\[19\] This is the testimony given by John when priests and Levites *came* to ask him, "Who are you?"

さて、ユダヤ人たちが、エルサレムから祭司たちやレビ人たちをヨハネのもとにつかわして、「あなたはどなたですか」と問わせたが、その時ヨハネが立てたあかしは、こうであった。

\[20\] *He* confessed, "I am not the Messiah."

すなわち、彼は告白して否まず、「わたしはキリストではない」と告白した。

\[21\] And they asked him, "What then? Are you Elijah?"

そこで、彼らは問うた、「それでは、どなたなのですか、あなたはエリヤですか」。

He said, "I am not."

彼は「いや、そうではない」と言った。

"Are you the prophet?"

「では、あの預言者ですか」。

He answered, "No."

彼は「いいえ」と答えた。

\[22\] Then they said to him, "Who are you? What do you say about yourself?"

そこで、彼らは言った、「あなたはどなたですか。わたしたちをつかわした人々に、答えを持って行けるようにしていただきたい。あなた自身をだれだと考えるのですか」。

\[23\] He said, "I am the voice of one crying out in the wilderness, 'Make straight the way of the Lord,' " as the prophet Isaiah said. I baptize with water. Among you stands

彼は言った、「わたしは、預言者イザヤが言ったように、『主の道をまっすぐにせよと荒野で呼ばわる者の声』である」。

\[27\] the one who is coming after me; I am not worthy to untie the thong of his sandal."

それがわたしのあとにおいでになる方であって、わたしはその人のくつのひもを解く値うちもない」。

\[28\] He saw Jesus coming toward him and declared, "Here is the Lamb of God. I came for this reason, that he might be revealed to Israel. I saw the Spirit descending from heaven like a dove on him.

これらのことは、ヨハネがバプテスマを授けていたヨルダンの向こうのベタニヤであったのである。

\[34\] And I myself have seen and have testified that this is the Son of God."

わたしはそれを見たので、このかたこそ神の子であると、あかしをしたのである」。

\[35\] *Now* John was standing with two of his disciples

その翌日、ヨハネはまたふたりの弟子たちと一緒に立っていたが、

\[37\] *who* heard him say this, and they followed Jesus.

そのふたりの弟子は、ヨハネがそう言うのを聞いて、イエスについて行った。

\[38\] They said to him, "Rabbi, where are you staying?"

イエスはふり向き、彼らがついてくるのを見て言われた、「何か願いがあるのか」。彼らは言った、「ラビ（訳して言えば、先生）どこにおとまりなのですか」。

\[39\] He said to them, "Come and see." They came and saw where he was staying, and they remained with him that day. It was about four o'clock in the afternoon.

イエスは彼らに言われた、「きてごらんなさい。そうしたらわかるだろう」。そこで彼らはついて行って、イエスの泊まっておられる所を見た。そして、その日はイエスのところに泊まった。時は午後四時ごろであった。

\[40\] One of the two who heard John speak and followed him was Andrew.

ヨハネから聞いて、イエスについて行ったふたりのうちのひとりは、シモン・ペテロの兄弟アンデレであった。

\[41\] He first found his brother Simon and said to him, "We have found the Messiah."

彼はまず自分の兄弟シモンに出会って言った、「わたしたちはメシヤ（訳せば、キリスト）にいま出会った」。

\[42\] He brought Simon to Jesus, who looked at him and said, "You are Simon son of John. You are to be called Cephas."

そしてシモンをイエスのもとにつれてきた。イエスは彼に目をとめて言われた、「あなたはヨハネの子シモンである。あなたをケパ（訳せば、ペテロ）と呼ぶことにする」。

\[43\] He found Philip and *Jesus* said to him, "Follow me."

その翌日、イエスはガリラヤに行こうとされたが、ピリポに出会って言われた、「わたしに従ってきなさい」。

\[44\] Now Philip was from Bethsaida, the city of Andrew and Peter.

ピリポは、アンデレとペテロとの町ベツサイダの人であった。

\[45\] Philip found Nathanael and said to him, "We have found him about whom Moses in the law wrote, Jesus son of Joseph from Nazareth."

このピリポがナタナエルに出会って言った、「わたしたちは、モーセが律法の中にしるしており、預言者たちがしるしていた人、ヨセフの子、ナザレのイエスにいま出会った」。

\[46\] Nathanael said to him, "Can anything good come out of Nazareth?"

ナタナエルは彼に言った、「ナザレから、なんのよいものが出ようか」。

Philip said to him, "Come and see."

ピリポは彼に言った、「きて見なさい」。

\[47\] When Jesus saw Nathanael coming toward him, he said of him, "Here is truly an Israelite."

イエスはナタナエルが自分の方に来るのを見て、彼について言われた、「見よ、あの人こそ、ほんとうのイスラエル人である。その心には偽りがない」。

\[49\] Nathanael replied, "Rabbi, you are the Son of God! You are the King of Israel!"

ナタナエルは答えた、「先生、あなたは神の子です。あなたはイスラエルの王です」。

#### ヨハネ2章

\[1\] There was a wedding in Cana, and the mother of Jesus was there.

三日目にガリラヤのカナに婚礼があって、イエスの母がそこにいた。

\[2\] Jesus and his disciples had also been invited to the wedding.

イエスも弟子たちも、その婚礼に招かれた。

\[3\] When the wine gave out, the mother of Jesus said to the servants, "Do whatever he tells you."

ぶどう酒がなくなったので、母はイエスに言った、「ぶどう酒がなくなってしまいました」。

\[6\] Now standing there were six stone water jars, each holding twenty or thirty gallons.

そこには、ユダヤ人のきよめのならわしに従って、それぞれ四、五斗もはいる石の水がめが、六つ置いてあった。

\[7\] Jesus said to them, "Fill the jars with water." And they filled them up to the brim.

イエスは彼らに「かめに水をいっぱい入れなさい」と言われたので、彼らは口のところまでいっぱいに入れた。

\[8\] He said to them, "Now draw some out, and take it to the chief steward." So they took it.

そこで彼らに言われた、「さあ、くんで、料理がしらのところに持って行きなさい」。すると、彼らは持って行った。

\[9\] When the steward tasted the water that had become wine, the steward called the bridegroom

料理がしらは、ぶどう酒になった水をなめてみたが、それがどこからきたのか知らなかったので、（水をくんだ僕たちは知っていた）花婿を呼んで

\[10\] and said to him, "Everyone serves the good wine first, and then the inferior wine after the guests have become drunk. But you have kept the good wine until now."

言った、「どんな人でも、初めによいぶどう酒を出して、酔いがまわったころにわるいのを出すものだ。それだのに、あなたはよいぶどう酒を今までとっておかれました」。

\[11\] Jesus did this, the first of his signs; and his disciples believed in him.

イエスは、この最初のしるしをガリラヤのカナで行い、その栄光を現された。そして弟子たちはイエスを信じた。

\[12\] After this he went down to Capernaum with his disciples.

そののち、イエスは、その母、兄弟たち、弟子たちと一緒に、カペナウムに下って、幾日かそこにとどまられた。

#### ヨハネ4章

\[46\] Now there was a royal official whose son lay ill in Capernaum.

イエスは、またガリラヤのカナに行かれた。そこは、かつて水をぶどう酒にかえられた所である。ところが、病気をしているむすこを持つある役人がカペナウムにいた。

\[47\] He went and said to him, "Sir, come down before my little boy dies."

この人が、ユダヤからガリラヤにイエスのきておられることを聞き、みもとにきて、カペナウムに下って、彼の子をなおしていただきたいと、願った。その子が死にかかっていたからである。

\[50\] Jesus said, "Go; your son will live."

イエスは彼に言われた、「お帰りなさい。あなたのむすこは助かるのだ」。

The man started on his way.

彼は自分に言われたイエスの言葉を信じて帰って行った。

\[51\] As he was going down, his slaves met him and told him that his child was alive.

その下って行く途中、僕たちが彼に出会い、その子が助かったことを告げた。

\[52\] So he asked them the hour when he began to recover, and they said to him, "Yesterday at one in the afternoon the fever left him."

そこで、彼は僕たちに、そのなおりはじめた時刻を尋ねてみたら、「きのうの午後一時に熱が引きました」と答えた。

\[53\] So he himself believed, along with his whole household.

それは、イエスが「あなたのむすこは助かるのだ」と言われたのと同じ時刻であったことを、この父は知って、彼自身もその家族一同も信じた。

\[54\] Now this was the second sign that Jesus did.

これは、イエスがユダヤからガリラヤにきてなされた第二のしるしである。

#### ヨハネ21章

\[2\] Gathered there together were Simon Peter, Thomas called the Twin, Nathanael of Cana, the sons of Zebedee.

シモン・ペテロが、デドモと呼ばれているトマス、ガリラヤのカナのナタナエル、ゼベダイの子らや、ほかのふたりの弟子たちと一緒にいた時のことである。

\[3\] Simon Peter said to them, "I am going fishing."

シモン・ペテロは彼らに「わたしは漁に行くのだ」と言うと、

They said to him, "We will go with you."

彼らは「わたしたちも一緒に行こう」と言った。彼らは出て行って舟に乗った。

They went out and got into the boat, but that night they caught nothing.

しかし、その夜はなんの獲物もなかった。

\[4\] Just after daybreak, Jesus stood on the beach.

夜が明けたころ、イエスが岸に立っておられた。しかし弟子たちはそれがイエスだとは知らなかった。

\[6\] He said to them, "Cast the net to the right side of the boat, and you will find some."

すると、イエスは彼らに言われた、「舟の右の方に網をおろして見なさい。そうすれば、何かとれるだろう」。

So they cast it, and now they were not able to haul it in because there were so many fish.

彼らは網をおろすと、魚が多くとれたので、それを引き上げることができなかった。

\[7\] Simon Peter put on some clothes and jumped into the sea

イエスの愛しておられた弟子が、ペテロに「あれは主だ」と言った。シモン・ペテロは主であると聞いて、裸になっていたため、上着をまとって海にとびこんだ。

\[8\] for they were not far from the land, only about a hundred yards off.

しかし、ほかの弟子たちは舟に乗ったまま、魚のはいっている網を引きながら帰って行った。陸からはあまり遠くない五十間ほどの所にいたからである。

\[11\] So Simon Peter went ashore and hauled the net *ashore*, full of large fish, a hundred fifty-three of them; and though there were so many, the net was not torn.

シモン・ペテロが行って、網を陸へ引き上げると、百五十三びきの大きな魚でいっぱいになっていた。そんなに多かったが、網はさけないでいた。

\[14\] This was now the third sign that Jesus *did before* the disciples

イエスが死人の中からよみがえったのち、弟子たちにあらわれたのは、これで既に三度目である。

#### ヨハネ6章

\[1\] After this Jesus went to the other side of the Sea of Tiberias.

そののち、イエスはガリラヤの海、すなわち、テベリヤ湖の向こう岸へ渡られた。

\[3\] *He* went up the mountain and sat down there with his disciples.

イエスは山に登って、弟子たちと一緒にそこで座につかれた。

\[5\] When he looked up and saw a large crowd coming toward him, Jesus said to Philip, "Where are we to buy bread for these people to eat?"

イエスは目をあげ、大ぜいの群衆が自分の方に集まって来るのを見て、ピリポに言われた、「どこからパンを買ってきて、この人々に食べさせようか」。

\[7\] Philip answered him, "Six months' wages would not buy enough bread for each of them to get a little."

すると、ピリポはイエスに答えた、「二百デナリのパンがあっても、めいめいが少しずついただくにも足りますまい」。

\[8\] One of his disciples said to him,

弟子のひとり、シモン・ペテロの兄弟アンデレがイエスに言った、

\[9\] "There is a boy here who has five barley loaves and two fish. But what are they among so many people?"

「ここに、大麦のパン五つと、さかな二ひきとを持っている子供がいます。しかし、こんなに大ぜいの人では、それが何になりましょう」。

\[10\] Jesus said, "Make the people sit down." Now there was a great deal of grass in the place; so they sat down, about five thousand in all.

イエスは「人々をすわらせなさい」と言われた。その場所には草が多かった。そこにすわった男の数は五千人ほどであった。

\[11\] Then Jesus took the loaves, and when he had given thanks, he distributed them to those who were seated; so also the fish, as much as they wanted.

そこで、イエスはパンを取り、感謝してから、すわっている人々に分け与え、また、さかなをも同様にして、彼らの望むだけ分け与えられた。

\[13\] And from the fragments of the five barley loaves, left by those who had eaten, they filled twelve baskets.

そこで彼らが集めると、五つの大麦のパンを食べて残ったパンくずは、十二のかごにいっぱいになった。

\[14\] When the people saw the sign that he had done, they began to say, "This is indeed the prophet who is to come into the world."

人々はイエスのなさったこのしるしを見て、「ほんとうに、この人こそ世にきたるべき預言者である」と言った。

\[15\] *Jesus* withdrew again to the mountain by himself.

イエスは人々がきて、自分をとらえて王にしようとしていると知って、ただひとり、また山に退かれた。

\[16\] When evening came, his disciples went down to the sea,

夕方になったとき、弟子たちは海ベに下り、

\[17\] got into a boat, and started across the sea to Capernaum.

舟に乗って海を渡り、向こう岸のカペナウムに行きかけた。すでに暗くなっていたのに、イエスはまだ彼らのところにおいでにならなかった。

\[18\] The sea became rough because a strong wind was blowing.

その上、強い風が吹いてきて、海は荒れ出した。

\[19\] When they had rowed about three or four miles, they saw Jesus walking on the sea, and they were terrified.

四、五十丁こぎ出したとき、イエスが海の上を歩いて舟に近づいてこられるのを見て、彼らは恐れた。

\[20\] But he said to them, "It is I; do not be afraid."

すると、イエスは彼らに言われた、「わたしだ、恐れることはない」。

\[21\] And immediately the boat reached the land toward which they were going.

そこで、彼らは喜んでイエスを舟に迎えようとした。すると舟は、すぐ、彼らが行こうとしていた地に着いた。

#### ヨハネ11章

\[1\] Now a certain Mary;

さて、ひとりの病人がいた。ラザロといい、マリヤとその姉妹マルタの村ベタニヤの人であった。

\[2\] her brother Lazarus was ill.

このマリヤは主に香油をぬり、自分の髪の毛で、主の足をふいた女であって、病気であったのは、彼女の兄弟ラザロであった。

\[3\] *She* sent a message to Jesus, "Lord, he whom you love is ill."

姉妹たちは人をイエスのもとにつかわして、「主よ、ただ今、あなたが愛しておられる者が病気をしています」と言わせた。

\[7\] He said to the disciples, "Our friend Lazarus has fallen asleep. Let us go to him."

それから弟子たちに、「もう一度ユダヤに行こう」と言われた。

\[17\] When Jesus arrived, he found that Lazarus had already been in the tomb four days.

さて、イエスが行ってごらんになると、ラザロはすでに四日間も墓の中に置かれていた。

\[32\] When Mary saw him, she knelt at his feet and said to him, "Lord, if you had been here, my brother would not have died."

マリヤは、イエスのおられる所に行ってお目にかかり、その足もとにひれ伏して言った、「主よ、もしあなたがここにいて下さったなら、わたしの兄弟は死ななかったでしょう」。

\[33\] When Jesus saw her weeping, he was greatly disturbed in spirit and deeply moved.

イエスは、彼女が泣き、また、彼女と一緒にきたユダヤ人たちも泣いているのをごらんになり、激しく感動し、また心を騒がせ、そして言われた、

\[34\] He said, "Where have you laid him?"

「彼をどこに置いたのか」。

They said to him, "Lord, come and see."

彼らはイエスに言った、「主よ、きて、ごらん下さい」。

\[38\] Then Jesus came to the tomb. It was a cave, and a stone was lying against it.

イエスはまた激しく感動して、墓にはいられた。それは洞穴であって、そこに石がはめてあった。

\[39\] Jesus said, "Take away the stone." Then he cried with a loud voice, "Lazarus, come out!"

イエスは言われた、「石を取りのけなさい」。死んだラザロの姉妹マルタが言った、「主よ、もう臭くなっております。四日もたっていますから」。

\[44\] The dead man came out, his hands and feet bound with strips of cloth, and his face wrapped in a cloth. Jesus said to them, "Unbind him, and let him go."

すると、死人は手足を布でまかれ、顔も顔おおいで包まれたまま、出てきた。イエスは人々に言われた、「彼をほどいてやって、帰らせなさい」。

\[45\] *Those who* had seen what Jesus did, believed in him.

マリヤのところにきて、イエスのなさったことを見た多くのユダヤ人たちは、イエスを信じた。

#### ヨハネ9章

\[1\] As he walked along, he saw a man blind from birth.

イエスが道をとおっておられるとき、生れつきの盲人を見られた。

\[6\] He spat on the ground and made mud with the saliva and spread the mud on the man's eyes,

イエスはそう言って、地につばきをし、そのつばきで、どろをつくり、そのどろを盲人の目に塗って言われた、

\[7\] saying to him, "Go, wash in the pool of Siloam." Then he went and washed and came back able to see.

「シロアム（つかわされた者、の意）の池に行って洗いなさい」。そこで彼は行って洗った。そして見えるようになって、帰って行った。

\[8\] The neighbors and those who had seen him before as a beggar began to ask, "Is this not the man who used to sit and beg?"

近所の人々や、彼がもと、こじきであったのを見知っていた人々が言った、「この人は、すわってこじきをしていた者ではないか」。

#### ヨハネ5章

\[2\] Now in Jerusalem by the Sheep Gate there is a pool, called in Hebrew Beth-zatha, which has five porticoes.

エルサレムにある羊の門のそばに、ヘブル語でベテスダと呼ばれる池があった。そこには五つの廊があった。

\[3\] In these lay many invalids — blind, lame, and paralyzed.

その廊の中には、病人、盲人、足なえ、やせ衰えた者などが、大ぜいからだを横たえていた。〔彼らは水の動くのを待っていたのである。

\[5\] One man was there who had been ill for thirty-eight years.

さて、そこに三十八年のあいだ、病気に悩んでいる人があった。

\[6\] When Jesus saw him lying there and knew that he had been there a long time, he said to him, "Do you want to be made well?"

イエスはその人が横になっているのを見、また長い間わずらっていたのを知って、その人に「なおりたいのか」と言われた。

\[7\] The sick man answered him, "Sir, I have no one to put me into the pool when the water is stirred up; and while I am making my way, someone else steps down ahead of me."

この病人はイエスに答えた、「主よ、水が動く時に、わたしを池の中に入れてくれる人がいません。わたしがはいりかけると、ほかの人が先に降りて行くのです」。

\[8\] Jesus said to him, "Stand up, take your mat and walk."

イエスは彼に言われた、「起きて、あなたの床を取りあげ、そして歩きなさい」。

\[9\] At once the man was made well, and he took up his mat and began to walk.

すると、この人はすぐにいやされ、床をとりあげて歩いて行った。その日は安息日であった。

#### ヨハネ2章

\[14\] In the temple *Jesus* found people selling cattle, sheep, and doves, and the money changers seated at their tables.

そして牛、羊、はとを売る者や両替する者などが宮の庭にすわり込んでいるのをごらんになって、

\[15\] Making a whip of cords, he drove all of them out of the temple, both the sheep and the cattle. He also poured out the coins of the money changers and overturned their tables.

なわでむちを造り、羊も牛もみな宮から追いだし、両替人の金を散らし、その台をひっくりかえし、

\[16\] He told those who were selling the doves, "Take these things out of here! Stop making my Father's house a marketplace!"

はとを売る人々には「これらのものを持って、ここから出て行け。わたしの父の家を商売の家とするな」と言われた。

\[18\] The Jews then said to him, "What sign can you show us for doing this?"

そこで、ユダヤ人はイエスに言った、「こんなことをするからには、どんなしるしをわたしたちに見せてくれますか」。

\[19\] Jesus answered them, "Destroy this temple, and in three days I will raise it up."

イエスは彼らに答えて言われた、「この神殿をこわしたら、わたしは三日のうちに、それを起すであろう」。

#### ヨハネ11章

\[47\] So the chief priests called a meeting of the council, and said, "This man is performing many signs.

そこで、祭司長たちとパリサイ人たちとは、議会を召集して言った、「この人が多くのしるしを行っているのに、お互は何をしているのだ。

\[48\] If we let him go on like this, everyone will believe in him, and the Romans will come and destroy our nation."

もしこのままにしておけば、みんなが彼を信じるようになるだろう。そのうえ、ローマ人がやってきて、わたしたちの土地も人民も奪ってしまうであろう」。

\[49\] But one of them, Caiaphas, who was high priest that year, said to them,

彼らのうちのひとりで、その年の大祭司であったカヤパが、彼らに言った、「あなたがたは、何もわかっていないし、

\[50\] "It is better for you to have one man die for the people than to have the whole nation destroyed."

ひとりの人が人民に代って死んで、全国民が滅びないようになるのがわたしたちにとって得だということを、考えてもいない」。

\[53\] So from that day on they planned to put him to death.

彼らはこの日からイエスを殺そうと相談した。

#### ヨハネ12章

\[37\] Although he had performed so many signs, they did not believe in him.

このように多くのしるしを彼らの前でなさったが、彼らはイエスを信じなかった。

\[38\] This was to fulfill the word spoken by the prophet Isaiah: "Lord, who has believed our message, and to whom has the arm of the Lord been revealed?"

それは、預言者イザヤの次の言葉が成就するためである、「主よ、わたしたちの説くところを、だれが信じたでしょうか。また、主のみ腕はだれに示されたでしょうか」。

\[39\] And so they could not believe, because Isaiah also said,

こういうわけで、彼らは信じることができなかった。イザヤはまた、こうも言った、

\[40\] "He has blinded their eyes and hardened their heart, so that they might not look with their eyes, and understand with their heart and turn -- and I would heal them."

「神は彼らの目をくらまし、心をかたくなになさった。それは、彼らが目で見ず、心で悟らず、悔い改めていやされることがないためである」。

\[1\] Six days before the Passover Jesus came to Bethany, the home of Lazarus, whom he had raised from the dead.

過越の祭の六日まえに、イエスはベタニヤに行かれた。そこは、イエスが死人の中からよみがえらせたラザロのいた所である。

\[2\] There they gave a dinner for him. Martha served, and Lazarus was one of those at the table with him.

イエスのためにそこで夕食の用意がされ、マルタは給仕をしていた。イエスと一緒に食卓についていた者のうちに、ラザロも加わっていた。

\[3\] Mary took a pound of costly perfume made of pure nard, anointed Jesus, and wiped them with her hair. The house was filled with the fragrance of the perfume.

その時、マリヤは高価で純粋なナルドの香油一斤を持ってきて、イエスの足にぬり、自分の髪の毛でそれをふいた。すると、香油のかおりが家にいっぱいになった。

\[4\] But Judas Iscariot, one of his disciples, said,

弟子のひとりで、イエスを裏切ろうとしていたイスカリオテのユダが言った、

\[5\] "Why was this perfume not sold for three hundred denarii and the money given to the poor?"

「なぜこの香油を三百デナリに売って、貧しい人たちに、施さなかったのか」。

\[7\] Jesus said, "She bought it so that she might keep it for the day of my burial.

イエスは言われた、「この女のするままにさせておきなさい。わたしの葬りの日のために、それをとっておいたのだから。

\[8\] You always have the poor with you, but you do not always have me."

貧しい人たちはいつもあなたがたと共にいるが、わたしはいつも共にいるわけではない」。

\[12\] The next day the great crowd that had come to the festival heard that Jesus was coming to Jerusalem.

その翌日、祭にきていた大ぜいの群衆は、イエスがエルサレムにこられると聞いて、

\[13\] So they took branches of palm trees and went out to meet him, shouting, "Hosanna! Blessed is the one who comes in the name of the Lord -- the King of Israel!"

しゅろの枝を手にとり、迎えに出て行った。そして叫んだ、／「ホサナ、／主の御名によってきたる者に祝福あれ、／イスラエルの王に」。

\[14\] Jesus found a young donkey and sat on it; as it is written:

イエスは、ろばの子を見つけて、その上に乗られた。それは

\[15\] "Do not be afraid, daughter of Zion. Look, your king is coming, sitting on a donkey's colt!"

「シオンの娘よ、恐れるな。見よ、あなたの王が／ろばの子に乗っておいでになる」／と書いてあるとおりであった。

#### ヨハネ13章

\[1\] Now before the festival of the Passover, Jesus knew that his hour had come to depart from this world and go to the Father. Having loved his own who were in the world, he loved them to the end.

過越の祭の前に、イエスは、この世を去って父のみもとに行くべき自分の時がきたことを知り、世にいる自分の者たちを愛して、彼らを最後まで愛し通された。

\[2\] The devil had already put it into the heart of Judas son of Simon Iscariot to betray him. And during supper

夕食のとき、悪魔はすでにシモンの子イスカリオテのユダの心に、イエスを裏切ろうとする思いを入れていたが、

\[3\] Jesus, knowing that the Father had given all things into his hands, and that he had come from God and was going to God,

イエスは、父がすべてのものを自分の手にお与えになったこと、また、自分は神から出てきて、神にかえろうとしていることを思い、

\[4\] got up from the table, took off his outer robe, and tied a towel around himself.

夕食の席から立ち上がって、上着を脱ぎ、手ぬぐいをとって腰に巻き、

\[5\] Then he poured water into a basin and began to wash the disciples' feet and to wipe them with the towel that was tied around him.

それから水をたらいに入れて、弟子たちの足を洗い、腰に巻いた手ぬぐいでふき始められた。

\[6\] He came to Simon Peter, who said to him, "Lord, are you going to wash my feet?"

こうして、シモン・ペテロの番になった。すると彼はイエスに、「主よ、あなたがわたしの足をお洗いになるのですか」と言った。

\[7\] Jesus answered, "You do not know now what I am doing, but later you will understand."

イエスは彼に答えて言われた、「わたしのしていることは今あなたにはわからないが、あとでわかるようになるだろう」。

\[8\] Peter said to him, "You will never wash my feet."

ペテロはイエスに言った、「わたしの足を決して洗わないで下さい」。

Jesus answered, "Unless I wash you, you have no share with me."

イエスは彼に答えられた、「もしわたしがあなたの足を洗わないなら、あなたはわたしとなんの係わりもなくなる」。

\[9\] Simon Peter said to him, "Lord, not my feet only but also my hands and my head!"

シモン・ペテロはイエスに言った、「主よ、では、足だけではなく、どうぞ、手も頭も」。

\[10\] Jesus said to him, "One who has bathed does not need to wash, except for the feet, but is entirely clean. And you are clean, though not all of you."

イエスは彼に言われた、「すでにからだを洗った者は、足のほかは洗う必要がない。全身がきれいなのだから。あなたがたはきれいなのだ。しかし、みんながそうなのではない」。

\[11\] For he knew who was to betray him; for this reason he said, "Not all of you are clean."

イエスは自分を裏切る者を知っておられた。それで、「みんながきれいなのではない」と言われたのである。

\[12\] After he had washed their feet, had put on his robe, and had returned to the table, he said to them, "Do you know what I have done to you?

こうして彼らの足を洗ってから、上着をつけ、ふたたび席にもどって、彼らに言われた、「わたしがあなたがたにしたことがわかるか。

\[13\] You call me Teacher and Lord -- and you are right, for that is what I am.

あなたがたはわたしを教師、また主と呼んでいる。そう言うのは正しい。わたしはそのとおりである。

\[14\] So if I, your Lord and Teacher, have washed your feet, you also ought to wash one another's feet.

しかし、主であり、また教師であるわたしが、あなたがたの足を洗ったからには、あなたがたもまた、互に足を洗い合うべきである。

\[15\] For I have set you an example, that you also should do as I have done to you.

わたしがあなたがたにしたとおりに、あなたがたもするように、わたしは手本を示したのだ。

\[16\] Very truly, I tell you, servants are not greater than their master, nor are messengers greater than the one who sent them.

よくよくあなたがたに言っておく。僕はその主人にまさるものではなく、つかわされた者はつかわした者にまさるものではない。

\[17\] If you know these things, you are blessed if you do them.

もしこれらのことがわかっていて、それを行うなら、あなたがたはさいわいである。

\[18\] I am not speaking of all of you; I know whom I have chosen. But it is to fulfill the scripture, 'The one who ate my bread has lifted his heel against me.'

あなたがた全部の者について、こう言っているのではない。わたしは自分が選んだ人たちを知っている。しかし、『わたしのパンを食べている者が、わたしにむかってそのかかとをあげた』とある聖書は成就されなければならない。

\[19\] I tell you this now, before it occurs, so that when it does occur, you may believe that I am he.

そのことがまだ起らない今のうちに、あなたがたに言っておく。いよいよ事が起ったとき、わたしがそれであることを、あなたがたが信じるためである。

\[20\] Very truly, I tell you, whoever receives one whom I send receives me; and whoever receives me receives him who sent me."

よくよくあなたがたに言っておく。わたしがつかわす者を受けいれる者は、わたしを受けいれるのである。わたしを受けいれる者は、わたしをつかわされたかたを、受けいれるのである」。

#### ヨハネ18章

\[1\] Jesus went out with his disciples across the Kidron valley to a place where there was a garden.

イエスはこれらのことを語り終えて、弟子たちと一緒にケデロンの谷の向こうへ行かれた。そこには園があって、イエスは弟子たちと一緒にその中にはいられた。

\[2\] Now Judas, who betrayed him, also knew the place, because Jesus often met there with his disciples.

イエスを裏切ったユダは、その所をよく知っていた。イエスと弟子たちとがたびたびそこで集まったことがあるからである。

\[3\] So Judas brought a detachment of soldiers together with police from the chief priests, and they came there with lanterns and torches and weapons.

さてユダは、一隊の兵卒と祭司長やパリサイ人たちの送った下役どもを引き連れ、たいまつやあかりや武器を持って、そこへやってきた。

\[4\] Then Jesus asked them, "Whom are you looking for?"

しかしイエスは、自分の身に起ろうとすることをことごとく承知しておられ、進み出て彼らに言われた、「だれを捜しているのか」。

\[5\] They answered, "Jesus of Nazareth."

彼らは「ナザレのイエスを」と答えた。

Jesus replied, "I am he."

イエスは彼らに言われた、「わたしが、それである」。イエスを裏切ったユダも、彼らと一緒に立っていた。

\[10\] Then Simon Peter, who had a sword, drew it, struck the high priest's slave, and cut off his right ear. The slave's name was Malchus.

シモン・ペテロは剣を持っていたが、それを抜いて、大祭司の僕に切りかかり、その右の耳を切り落した。その僕の名はマルコスであった。

\[11\] Jesus said to Peter, "Put your sword back into its sheath. Am I not to drink the cup that the Father has given me?"

すると、イエスはペテロに言われた、「剣をさやに納めなさい。父がわたしに下さった杯は、飲むべきではないか」。

\[12\] So the soldiers, their officer, and the Jewish police arrested Jesus and bound him.

それから一隊の兵卒やその千卒長やユダヤ人の下役どもが、イエスを捕え、縛りあげて、

\[13\] First they took him to Annas, who was the father-in-law of Caiaphas, the high priest that year.

まずアンナスのところに引き連れて行った。彼はその年の大祭司カヤパのしゅうとであった。

\[15\] Simon Peter and another disciple followed Jesus. Since that disciple was known to the high priest, he went with Jesus into the courtyard of the high priest,

シモン・ペテロともうひとりの弟子とが、イエスについて行った。この弟子は大祭司の知り合いであったので、イエスと一緒に大祭司の中庭にはいった。

\[16\] but Peter was standing outside at the gate. So the other disciple, who was known to the high priest, went out, spoke to the woman who guarded the gate, and brought Peter in.

しかし、ペテロは外で戸口に立っていた。すると大祭司の知り合いであるその弟子が、外に出て行って門番の女に話し、ペテロを内に入れてやった。

\[17\] The woman said to Peter, "You are not also one of this man's disciples, are you?"

すると、この門番の女がペテロに言った、「あなたも、あの人の弟子のひとりではありませんか」。

He said, "I am not."

ペテロは「いや、そうではない」と答えた。

\[18\] Now the slaves and the police had made a charcoal fire because it was cold, and they were standing around it and warming themselves. Peter also was standing with them and warming himself.

僕や下役どもは、寒い時であったので、炭火をおこし、そこに立ってあたっていた。ペテロもまた彼らに交じり、立ってあたっていた。

\[19\] Then the high priest questioned Jesus about his teaching.

大祭司はイエスに、弟子たちのことやイエスの教のことを尋ねた。

\[20\] Jesus answered, "I have always taught in the temple, where all come together.

イエスは答えられた、「わたしはこの世に対して公然と語ってきた。すべてのユダヤ人が集まる会堂や宮で、いつも教えていた。何事も隠れて語ったことはない。

\[21\] Why do you ask me?"

なぜ、わたしに尋ねるのか。わたしが彼らに語ったことは、それを聞いた人々に尋ねるがよい。わたしの言ったことは、彼らが知っているのだから」。

\[22\] When he had said this, one of the police standing nearby struck Jesus on the face, saying, "Is that how you answer the high priest?"

イエスがこう言われると、そこに立っていた下役のひとりが、「大祭司にむかって、そのような答をするのか」と言って、平手でイエスを打った。

\[24\] Then Annas sent him bound to Caiaphas the high priest.

それからアンナスは、イエスを縛ったまま大祭司カヤパのところへ送った。

\[25\] They asked him, "You are not also one of his disciples, are you?"

シモン・ペテロは、立って火にあたっていた。すると人々が彼に言った、「あなたも、あの人の弟子のひとりではないか」。

He denied it and said, "I am not."

彼はそれをうち消して、「いや、そうではない」と言った。

\[26\] One of the slaves of the high priest, a relative of the man whose ear Peter had cut off, asked, "Did I not see you in the garden with him?"

大祭司の僕のひとりで、ペテロに耳を切りおとされた人の親族の者が言った、「あなたが園であの人と一緒にいるのを、わたしは見たではないか」。

\[27\] Again Peter denied it, and at that moment the cock crowed.

ペテロはまたそれを打ち消した。するとすぐに、鶏が鳴いた。

\[28\] Then they took Jesus from Caiaphas to Pilate's headquarters. It was early in the morning.

それから人々は、イエスをカヤパのところから官邸につれて行った。時は夜明けであった。彼らは、けがれを受けないで過越の食事ができるように、官邸にはいらなかった。

\[29\] Pilate said, "What accusation do you bring against this man?"

そこで、ピラトは彼らのところに出てきて言った、「あなたがたは、この人に対してどんな訴えを起すのか」。

\[33\] Then Pilate summoned Jesus and asked him, "Are you the King of the Jews?"

さて、ピラトはまた官邸にはいり、イエスを呼び出して言った、「あなたは、ユダヤ人の王であるか」。

\[37\] Jesus answered, "You say that I am a king."

そこでピラトはイエスに言った、「それでは、あなたは王なのだな」。イエスは答えられた、「あなたの言うとおり、わたしは王である。わたしは真理についてあかしをするために生れ、また、そのためにこの世にきたのである。だれでも真理につく者は、わたしの声に耳を傾ける」

\[38\] He told them, "I find no case against him.

ピラトはイエスに言った、「真理とは何か」。こう言って、彼はまたユダヤ人の所に出て行き、彼らに言った、「わたしには、この人になんの罪も見いだせない。

\[39\] But you have a custom that I release someone for you at the Passover. Do you want me to release for you the King of the Jews?"

過越の時には、わたしがあなたがたのために、ひとりの人を許してやるのが、あなたがたのしきたりになっている。ついては、あなたがたは、このユダヤ人の王を許してもらいたいのか」。

\[40\] They shouted in reply, "Not this man, but Barabbas!" Now Barabbas was a bandit.

すると彼らは、また叫んで「その人ではなく、バラバを」と言った。このバラバは強盗であった。

#### ヨハネ19章

\[1\] Then Pilate took Jesus and had him flogged.

そこでピラトは、イエスを捕え、むちで打たせた。

\[2\] And the soldiers wove a crown of thorns and put it on his head, and they dressed him in a purple robe.

兵卒たちは、いばらで冠をあんで、イエスの頭にかぶらせ、紫の上着を着せ、

\[3\] They kept coming up to him, saying, "Hail, King of the Jews!" and striking him on the face.

それから、その前に進み出て、「ユダヤ人の王、ばんざい」と言った。そして平手でイエスを打ちつづけた。

\[6\] And the police saw him, they shouted, "Crucify him! Crucify him!"

祭司長たちや下役どもはイエスを見ると、叫んで「十字架につけよ、十字架につけよ」と言った。

Pilate said to them, "I find no case against him."

ピラトは彼らに言った、「あなたがたが、この人を引き取って十字架につけるがよい。わたしは、彼にはなんの罪も見いだせない」。

\[13\] Pilate brought Jesus outside and sat on the judge's bench at a place called The Stone Pavement, or in Hebrew Gabbatha.

ピラトはこれらの言葉を聞いて、イエスを外へ引き出して行き、敷石（ヘブル語ではガバタ）という場所で裁判の席についた。

\[14\] Now it was the day of Preparation; and it was about noon.

その日は過越の準備の日であって、時は昼の十二時ころであった。ピラトはユダヤ人らに言った、「見よ、これがあなたがたの王だ」。

\[16\] Then he handed him over to them to be crucified.

そこでピラトは、十字架につけさせるために、イエスを彼らに引き渡した。

So they took Jesus.

彼らはイエスを引き取った。

\[17\] He went out to what is called The Place of the Skull, which in Hebrew is called Golgotha.

イエスはみずから十字架を背負って、されこうべ（ヘブル語ではゴルゴタ）という場所に出て行かれた。

\[18\] There they crucified him, and with him two others, one on either side.

彼らはそこで、イエスを十字架につけた。イエスをまん中にして、ほかのふたりの者を両側に、イエスと一緒に十字架につけた。

\[19\] *And there was written,* "Jesus of Nazareth, the King of the Jews."

ピラトは罪状書きを書いて、十字架の上にかけさせた。それには「ユダヤ人の王、ナザレのイエス」と書いてあった。

\[20\] And it was written in Hebrew, in Latin, and in Greek.

イエスが十字架につけられた場所は都に近かったので、多くのユダヤ人がこの罪状書きを読んだ。それはヘブル、ローマ、ギリシヤの国語で書いてあった。

\[23\] When the soldiers had crucified Jesus, they took his clothes and divided them into four parts, one for each soldier. They also took his tunic; now the tunic was seamless, woven in one piece from the top.

さて、兵卒たちはイエスを十字架につけてから、その上着をとって四つに分け、おのおの、その一つを取った。また下着を手に取ってみたが、それには縫い目がなく、上の方から全部一つに織ったものであった。

\[24\] So they said to one another, "Let us not tear it, but cast lots for it to see who will get it." This was to fulfill what the scripture says, "They divided my clothes among themselves, and for my clothing they cast lots."

そこで彼らは互に言った、「それを裂かないで、だれのものになるか、くじを引こう」。これは、「彼らは互にわたしの上着を分け合い、わたしの衣をくじ引にした」という聖書が成就するためで、兵卒たちはそのようにしたのである。

\[25\] And that is what the soldiers did. Meanwhile, standing near the cross of Jesus were his mother, and his mother's sister, Mary the wife of Clopas, and Mary Magdalene.

さて、イエスの十字架のそばには、イエスの母と、母の姉妹と、クロパの妻マリヤと、マグダラのマリヤとが、たたずんでいた。

\[28\] After this, he said (in order to fulfill the scripture), "I am thirsty."

そののち、イエスは今や万事が終ったことを知って、「わたしは、かわく」と言われた。それは、聖書が全うされるためであった。

\[29\] A jar full of sour wine was standing there. So they put a sponge full of the wine on a branch of hyssop and held it to his mouth.

そこに、酢いぶどう酒がいっぱい入れてある器がおいてあったので、人々は、このぶどう酒を含ませた海綿をヒソプの茎に結びつけて、イエスの口もとにさし出した。

\[30\] When Jesus had received the wine, he said, "It is finished." Then he bowed his head and gave up his spirit.

すると、イエスはそのぶどう酒を受けて、「すべてが終った」と言われ、首をたれて息をひきとられた。

\[31\] Since it was the day of Preparation, the Jews did not want the bodies left on the cross during the sabbath. So they asked Pilate to have the legs of the crucified men broken and the bodies removed.

さてユダヤ人たちは、その日が準備の日であったので、安息日に死体を十字架の上に残しておくまいと、（特にその安息日は大事な日であったから）、ピラトに願って、足を折った上で、死体を取りおろすことにした。

\[32\] Then the soldiers came and broke the legs of the first and of the other who had been crucified with him.

そこで兵卒らがきて、イエスと一緒に十字架につけられた初めの者と、もうひとりの者との足を折った。

\[33\] But when they came to Jesus and saw that he was already dead, they did not break his legs.

しかし、彼らがイエスのところにきた時、イエスはもう死んでおられたのを見て、その足を折ることはしなかった。

\[34\] Instead, one of the soldiers pierced his side with a spear, and at once blood and water came out.

しかし、ひとりの兵卒がやりでそのわきを突きさすと、すぐ血と水とが流れ出た。

\[36\] These things occurred so that the scripture might be fulfilled, "None of his bones shall be broken."

これらのことが起ったのは、「その骨はくだかれないであろう」との聖書の言葉が、成就するためである。

\[37\] And again another passage of scripture says, "They will look on the one whom they have pierced."

また聖書のほかのところに、「彼らは自分が刺し通した者を見るであろう」とある。

\[38\] After these things, Joseph of Arimathea, who was a disciple of Jesus, asked Pilate to let him take away the body of Jesus. Pilate gave him permission; so he came and removed his body and wrapped it with the spices in linen cloths.

そののち、ユダヤ人をはばかって、ひそかにイエスの弟子となったアリマタヤのヨセフという人が、イエスの死体を取りおろしたいと、ピラトに願い出た。ピラトはそれを許したので、彼はイエスの死体を取りおろしに行った。

\[41\] Now there was a garden in the place where he was crucified, and in the garden there was a new tomb in which no one had ever been laid.

イエスが十字架にかけられた所には、一つの園があり、そこにはまだだれも葬られたことのない新しい墓があった。

\[42\] And so, because it was the day of Preparation, and the tomb was nearby, they laid Jesus there.

その日はユダヤ人の準備の日であったので、その墓が近くにあったため、イエスをそこに納めた。

#### ヨハネ20章

\[1\] Early on the first day of the week, Mary Magdalene came to the tomb and saw that the stone had been removed from the tomb.

さて、一週の初めの日に、朝早くまだ暗いうちに、マグダラのマリヤが墓に行くと、墓から石がとりのけてあるのを見た。

\[2\] So she ran and went to Simon Peter and said, "They have taken the Lord out of the tomb, and we do not know where they have laid him."

そこで走って、シモン・ペテロとイエスが愛しておられた、もうひとりの弟子のところへ行って、彼らに言った、「だれかが、主を墓から取り去りました。どこへ置いたのか、わかりません」。

\[3\] Then Peter set out and went toward the tomb and went into the tomb.

そこでペテロともうひとりの弟子は出かけて、墓へむかって行った。

\[9\] For as yet they did not understand the scripture, that he must rise from the dead.

しかし、彼らは死人のうちからイエスがよみがえるべきことをしるした聖句を、まだ悟っていなかった。

\[10\] Then *he* returned to *his* home.

それから、ふたりの弟子たちは自分の家に帰って行った。

\[11\] But Mary stood weeping outside the tomb. As she wept, she bent over to look into the tomb;

しかし、マリヤは墓の外に立って泣いていた。そして泣きながら、身をかがめて墓の中をのぞくと、

\[12\] and she saw two angels in white, sitting where the body of Jesus had been lying, one at the head and the other at the feet.

白い衣を着たふたりの御使が、イエスの死体のおかれていた場所に、ひとりは頭の方に、ひとりは足の方に、すわっているのを見た。

\[14\] She turned around and saw Jesus standing there.

そう言って、うしろをふり向くと、そこにイエスが立っておられるのを見た。しかし、それがイエスであることに気がつかなかった。

\[15\] Jesus said to her, "Whom are you looking for, Mary?"

イエスは女に言われた、「女よ、なぜ泣いているのか。だれを捜しているのか」。マリヤは、その人が園の番人だと思って言った、「もしあなたが、あのかたを移したのでしたら、どこへ置いたのか、どうぞ、おっしゃって下さい。わたしがそのかたを引き取ります」。

\[16\] She said to him in Hebrew, "Rabbouni!."

イエスは彼女に「マリヤよ」と言われた。マリヤはふり返って、イエスにむかってヘブル語で「ラボニ」と言った。それは、先生という意味である。

\[17\] Jesus said to her, "Do not hold on to me. But go to my brothers."

イエスは彼女に言われた、「わたしにさわってはいけない。わたしは、まだ父のみもとに上っていないのだから。ただ、わたしの兄弟たちの所に行って、『わたしは、わたしの父またあなたがたの父であって、わたしの神またあなたがたの神であられるかたのみもとへ上って行く』と、彼らに伝えなさい」。

\[18\] Mary Magdalene went and announced to the disciples, "I have seen the Lord."

マグダラのマリヤは弟子たちのところに行って、自分が主に会ったこと、またイエスがこれこれのことを自分に仰せになったことを、報告した。

\[19\] When it was evening on that day and the doors of the house where the disciples had met were locked, Jesus came and stood among them and said, "Peace be with you."

その日、すなわち、一週の初めの日の夕方、弟子たちはユダヤ人をおそれて、自分たちのおる所の戸をみなしめていると、イエスがはいってきて、彼らの中に立ち、「安かれ」と言われた。

\[20\] He showed them his hands and his side. Then the disciples rejoiced when they saw the Lord.

そう言って、手とわきとを、彼らにお見せになった。弟子たちは主を見て喜んだ。

\[22\] He breathed on them and said to them, "Receive the Holy Spirit."

そう言って、彼らに息を吹きかけて仰せになった、「聖霊を受けよ。

\[30\] Now Jesus did many other signs in the presence of his disciples, which are not written in this book.

イエスは、この書に書かれていないしるしを、ほかにも多く、弟子たちの前で行われた。

\[31\] But these are written so that you may come to believe that Jesus is the Messiah, the Son of God.

しかし、これらのことを書いたのは、あなたがたがイエスは神の子キリストであると信じるためであり、また、そう信じて、イエスの名によって命を得るためである。

### 参考：しるし福音に関する情報

Google Chrome による和訳（2025.7.3)）

D・ムーディー・スミスは（『ヨハネ福音書』 63ページ）次のように述べている。「現在では、福音書記者が共観福音書とは実質的に独立した奇跡の伝承や文献を参考にしていたことは広く認められている。共観福音書のいずれか、あるいは複数の福音書について彼が知っていたかどうかは関係ない。ルドルフ・ブルトマンによる画期的な解説以来、奇跡の源泉（セミア）という仮説は広く受け入れられている。」

D・ムーディー・スミスは（ヨハネ福音書、63ページ）こう記している。「ブルトマンや彼を支持する一部の人々が考えるように、奇跡の源泉を正確に分離・特定できるかどうかは、ここで判断する必要はない。源泉（あるいは複数の源泉）の存在を証明することは、福音書全体を通してそれを確実かつ正確に特定できるかどうかに完全に依存しているわけではない。」

ノーマン・ペリンは次のように書いています（『新約聖書入門』 225ページ）。

しかし、その使用を認識しなければならないソースが 1 つあります。それは、サイン ソースです。

2章11節では、カナにおけるイエスの奇跡が「最初のしるし」と記されています。2章23節では、その後のしるしについて概説的に述べられており、4章54節では、カペナウムの役人の息子の癒しが「ユダヤからガリラヤに来られたイエスが行われた二番目のしるし」と記されています。そして12章37節では、「イエスは彼らの前でこれほど多くのしるしを行われたが、彼らはイエスを信じなかった」と述べられており、この記述は福音書本文の最後の要約である20章30-31節にも再び現れています。「イエスは弟子たちの前で、この書物には書かれていない、ほかにも多くのしるしを行われた。しかし、これらのことが書かれたのは、あなたがたが信じるようになるためである。…」ヨハネ福音書に記された奇跡のうち、共観福音書に比肩するものがないものは、12章37節以前に起きていることから、福音記者が12章37節までの物語において、共観福音書もしくはそれらの福音書に代表される伝承以外の資料を用いていた可能性が強まります。ベトザタの池での癒し（5章1-9節）、盲人の癒し（9章1-12節）、ラザロの復活（11章1-44節）などです。これらの奇跡は、共観福音書に記されているものよりも概して壮大で精緻であり、イエスをヘレニズム的な「神人」として描く点でより深遠なものとなっているようです。福音書全体を通して12章37-38節まで、そして20章30-31節においても、これらの奇跡は信仰を呼び起こすためのものとして描かれています。2章11節、4章53節、6章14節、7章31節、そして20章30-31節では、これらの奇跡は信仰を呼び起こすためのものとして描かれています。 11:45, 47b-48; 12:37-38; 20:31。共観福音書では奇跡の前提条件としての信仰に重点が置かれているのに対し（例えばマルコ6:5-6）、ヨハネ福音書では奇跡が信仰を誘発する。これらの言及は共観福音書と対照的であるだけでなく、ヨハネ福音書の残りの部分とも対照的である。2:23-25でも4:48と同様に、イエスはしるしによって誘発されるような信仰を否定している。ニコデモとの会話では、そのような信仰が「上から」「霊から」の再生と好ましくない形で対比されている（3:2, 3, 5-6）。これらの要素から、ヨハネ福音書の著者が、イエスを奇跡によって信仰を誘発するヘレニズム的な「神人」として描くしるしの書を資料として用い、再解釈している可能性が非常に高い。

Kysar は次のように書いています ( The Anchor Bible Dictionary、第 3 巻、921-922 ページ):

文学的資料として最も広く支持されているのは、しるし資料という説です。福音書には、そのような資料を再構築する試みに貢献する要素が数多くあります。例えば、物語における一連の奇跡物語の存在、そのような奇跡を指す「 semeia」（「しるし」）という語の独特な用法、2章11節と4章54節におけるしるしの番号付け、そして福音書の結びにおけるしるしへの言及などです。さらに、福音書全体を通して見られる、信仰を育む上でのしるしの役割に対する繊細で複雑な態度は、福音記者が奇跡物語集を用いていたという事実によって説明できると提唱されています。この奇跡物語集は、福音書の著者が多少の留保を持っていたしるしの見解を表明していました。つまり、福音書が書かれる以前、ヨハネ福音書共同体の中でイエスの奇跡を集めた資料が流通していたという説です。福音書からそのようなしるし資料を再構築する試みは様々です。一方の極端な主張は、福音書に記された奇跡だけでなく、1章19-51節に記された弟子たちの召命と受難物語も含まれているというものです。もう一方の極端な主張は、この集成は7つの奇跡物語を連続して語ったに過ぎないというものです。こうした説は多くのヨハネ福音書学者に支持されていますが、この説についてはまだ合意に至っていません。

ロバート・フォートナは次のように書いています（『アンカー聖書辞典』第6巻、19ページ）。

SQの題名が示すように、まず第一に「しるし」という言葉が、この福音書のテキストに古い層が残っていることを示唆しています。一方で、この用語、特に信仰との関連において、共観福音書ではこの用語はごくまれにしか、そして否定的な意味で用いられておらず、イエスが行った奇跡については全く言及されていません。また、第四福音書においても「しるしと信仰」は時折批判的な意味合いで用いられますが（例えば4:48、6:26）、他の箇所（おそらくヨハネ福音書以前の箇所）では、完全に肯定的な意味で理解されるべきです。

さらに、福音書の前半には、しるしを数えるというパターンの痕跡が見られる（2:11、4:54）。実際、これらの奇跡物語と、現在では数えられていない他の物語、そしてそれらから派生したイエスの対話や長い独白（「説教」）こそが、イエスの公的な活動を構成していると言える。他の福音書において、そしてはるかに多様な形でイエスの「奉仕」と呼ばれてきたものは、この福音書においては、しるしの行使とそれについての長々とした語りを通してイエスが自らを現したこととしてしか描写できない。

そのため、多くの学者にとって、このテキストの背後には、イエスのしるし、それも一連のしるしのみを、しかも完全に肯定的に提示する原福音書が隠されているように思われてきた。それらはイエスのメシア的地位を示すもの（つまり、実証するもの）であり、それに基づいて最初の弟子たち、そしてその後多くの人々がイエスを信じたのである。「来て見」（1:39）た人々は、イエスがユダヤ人が長らく待ち望んでいた方であることをすぐに認識したのである。

フォルトナは、しるし福音書の内容について次のように述べています（同書、19ページ）。「ヨハネによる福音書に現在挿入されている箇所を除けば、イエスの以下の行為がしるし福音書の大部分を占めていたでしょう。水をぶどう酒に変えたこと（2:1-11）、役人の息子を癒したこと（4:46-54）、足の不自由な人を癒したこと（5:2-9）、群衆に食事を与えたこと（6:1-14）、おそらく海を渡ったこと（6:15-25）、盲人に視力を与えたこと（9:1-8）、そしてラザロを蘇らせたこと（11:1-45）。（21:1-14に現在見られる魚の捕獲も含めるという意見もあります。）この復元によって、単なる奇跡物語の寄せ集めではなく、明確な一連の出来事が浮かび上がります。また、他のいくつかの箇所も含まれることになります。例えば、1章の一部（少なくとも35-49節の最初の弟子たちの集合）は導入として、そして結論として、 20:30-31a、おそらく12:37-41の一部も。

しるし福音書には受難物語が含まれていたのか、それとも七つの奇跡物語の集合体だけが含まれていたのかについては、かなりの議論があります。フォルトナによる再構成では、受難物語が含まれています。

しるし福音書の年代については、手がかりとなるものはほとんどありません。5章2節でベテスダの池が西暦70年にローマ人によって破壊されたにもかかわらず、まだ存在していたと言及されていることから、西暦70年以前、あるいはそのすぐ後に遡る年代が示唆されます。最も遅い年代は、ヨハネによる福音書に編入されたことから推定されます。
