# ユダヤ戦記

> **THE WARS OF THE JEWS, OR HISTORY OF THE DESTRUCTION OF JERUSALEM By Flavius Josephus**
>
> At the Project Gutenberg, Translted by William Whiston （ウィリアム・ウィストンによる英訳）から Google Chrome の翻訳機能で日本語化し、その後多少修正したものです。

## 序文

1\. 1 ユダヤ人がローマ人と戦った戦争は、現代における戦争だけでなく、ある意味では、これまで聞いたことのある戦争の中でも最大のものでした。都市が都市と戦った戦争、あるいは国家が国家と戦った戦争の両方においてです。事件自体には関係のない人々が、うわさで矛盾した話を寄せ集め、詭弁的なやり方で書き留めました。また、その場にいた人々は、ローマ人へのお世辞かユダヤ人への憎しみから、物事について偽りの報告をしました。彼らの著作には、時には非難や賛辞が含まれていますが、事実の正確な真実はどこにも含まれていません。そこで、私は、ローマの統治下で暮らす人々のために、以前私たちの国の言葉で書いて上野に送った本をギリシャ語に翻訳することを思いつきました。2マティアスの息子ヨセフはヘブライ人として生まれ、祭司でもあり、最初はローマ人と戦い、その後の出来事に立ち会うことを余儀なくされた者です。\[私はこの作品の著者です\]

2\. さて、この大混乱が起こった当時、ローマ人の情勢は大混乱に陥っていた。改革を求めるユダヤ人たちも、時代が混乱すると立ち上がった。彼らはまた、力と富を求めて栄えていたため、東方の情勢は当時非常に混乱しており、ある者は利益を望み、他の者はそのような混乱の中で損失を恐れていた。ユダヤ人は、ユーフラテス川の向こう側の同胞全員が自分たちとともに反乱を起こすことを期待していた。ローマ人の近隣のガリア人も動き、ゲルティン人も静かではなかったが、ネロの死後、すべてが混乱していた。そして、今や与えられた機会に促されて、多くの人が王権を狙うようになり、兵士たちは金銭を得ることを期待して、変化を装った。したがって、私は、このような重大な情勢で真実が偽造されているのを見て、それに注意を払わないのはばかげたことだと思った。しかし、戦争に参加しなかったギリシャ人やローマ人がこれらのことを知らず、お世辞や作り話を読んでいるのを許す一方で、パルティア人、バビロニア人、最も遠いアラブ人、そしてユーフラテス川の向こう側、アディアベニ川の向こう側の我が国民は、私の情報を通じて、戦争がどこで始まり、それが我々にどのような悲惨さをもたらしたか、そしてどのような形で終わったかを正確に知っていた。

3\. 確かに、これらの著者は、その記述を歴史と呼ぶことに自信を持っている。しかし、その点で、彼らは目的を果たせていないだけでなく、健全なことを何も語っていないように私には思える。なぜなら、彼らはローマ人の偉大さを誇示しようとしながら、ユダヤ人の行動を軽視し、小さく征服しただけの者が偉大に見えるのは当然であるとは考えていないからだ。また、彼らは戦争の長さ、戦争で非常に苦しんだローマ軍の多さ、指揮官の力を見過ごすことを恥じていない。彼らのエルサレム周辺での多大な労働は、彼らが成し遂げたことが小さなこととみなされれば、不名誉なものとみなされるだろう。

4\. しかし、私はローマ人を賞賛する人々に反対して他の極端に行くつもりはなく、また私の同胞の行動を過度に高く評価しようと決心するつもりもありません。私は両方の行動を正確に追及するつもりです。しかし、私が記述する出来事に関して、私が抱いている情熱に合わせて言葉を選び、私の祖国が被った悲惨さについていくらかの嘆きを許していただく必要があります。なぜなら、それを破壊したのは私たち自身の扇動的な気質であり、ユダヤ人の暴君たちがローマの権力を私たちにもたらし、不本意ながら私たちを攻撃し、私たちの聖なる神殿を焼き払ったこと、それを破壊したティトゥス・シーザー自身がその証人であり、戦争中ずっと、扇動者によって抑圧された人々を哀れみ、しばしば自発的に都市の占領を遅らせ、その作成者に悔い改めの機会を与えるために包囲に時間を与えたからです。しかし、もし誰かが我々に対して不当な非難をするなら、我々が暴君や強盗について熱く語ったり、我が国の不幸をひどく嘆いたりしているとき、歴史を書く際の規則に反するとしても、ここでの私の感情を許して欲しい。なぜなら、我々の都市エルサレムはローマ統治下の他のどの都市よりも幸福な状態に達したが、最後には再び最悪の災難に陥ったからである。したがって、私には、世界の始まり以来のすべての人々の不幸は、ユダヤ人の不幸と比較すれば、それほど重要 ではないように思われる。その作者も外国人ではない。このため、私は嘆きを抑えることができない。しかし、もし誰かが私を非難することに固執するなら、事実そのものは歴史部分に帰し、嘆きは作者自身にのみ帰する。

5\. しかし、ギリシャ人の学者たちが、比較すると昔の戦争をはるかに凌ぐほどの偉大な行為が自分たちの時代になされたにもかかわらず、いまだにそれらの事件の裁判官として座り、古代の最高の作家たちの努力を痛烈に非難していることは、正当に非難できる。現代の学者たちは、雄弁さでは昔の作家たちより優れているかもしれないが、彼らが意図したことを実行する点では彼らに劣っている。また、彼らはアッシリア人とメディア人について新しい歴史を書いているが、まるで古代の作家たちが彼らの事件を記述すべきでなかったかのように。しかし、彼らは能力において彼らにはるかに劣っており、彼らの概念も彼らとは異なっている。なぜなら、昔は誰もが自分の時代に起こったことを書くことを引き受けたからである。彼らの行動への直接の関心が価値あるものを約束し、読者に嘘だとわかるような嘘を書くことは非難されるべきことであった。しかし、以前に記録されていないことの記憶を保存し、自分の時代の出来事を後世に伝えるという仕事は、本当に賞賛と称賛に値する。さて、他の人の作品の配置と順序を変更するだけの人ではなく、以前に語られなかったことを語るだけでなく、自分自身の歴史全体を構成した人は、真剣に苦労したと評価されるべきである。したがって、私は外国人であるにもかかわらず、\[この歴史について\]多大な費用と多大な労力を費やした。そして、この作品を、ギリシャ人と蛮族の両方に対する偉大な行為の記念碑として捧げます。しかし、私たちの主要人物の中には、利益と訴訟のために口を大きく開けて舌を自由にしているが、歴史を書くときは完全に口を閉ざしている人もいる。歴史を書くときは、真実を語り、多大な労力をかけて事実を集めなければならない。そして彼らは、そのような歴史の執筆を、より弱い人々、君主の行動を知らない人々に任せています。しかし、ギリシャの歴史家の間でどれほど無視されても、歴史的事実の真実は、私たちによって優先されるべきです。

6\. ユダヤ人の古代史について、彼らがもともと何者だったのか、エジプト人に対してどのように反乱を起こしたのか、どの国を旅したのか、その後どの国を占領したのか、そしてどのようにそこから追い出されたのかを書くのは、適切な機会ではないし、他の理由からも不必要であると思う。それは、私より前の多くのユダヤ人が、私たちの祖先の歴史を非常に正確に書き記したからである。ギリシャ人の中にも、私たちの歴史を自分たちの言語に翻訳した者がいたが、彼らの歴史の真実をあまり間違えていない。しかし、これらの出来事の著者や私たちの預言者が書き終えたところから、私は立ち上がり、歴史を書き始める。さて、私の時代に起こった戦争については、できる限り熱心に、非常に広範囲に検討するが、私の時代以前のことについては、簡単に触れる。

7\. \[例えば、私が語るには\]エピファネスという名のアンティオコスがエルサレムを武力で奪い、3年3か月保持した後、アサモネウスの息子たちによって国外に追い出されたこと、その後、彼らの子孫が政府について争い、彼らの居住地にローマ人とポンペイウスを招いたこと、アンティパトロスの息子ヘロデが彼らの政府を解体し、ソシンスを招いたこと、また、アウグストゥスがローマ皇帝でクィンティリウス・ウァルスがその国にいたときに、ヘロデの死後、私たちの民が暴動を起こしたこと、ネロの12年に戦争が勃発し、ケスティウスに何が起こったか、戦争の最初の出撃でユダヤ人が敵対的に襲撃した場所など。

8\. また、彼らが近隣の都市の周囲に壁を築いた経緯、ケスティウスの敗北でネロが戦争の結末を恐れ、ウェスパシアヌスをこの戦争の将軍に任命した経緯、ウェスパシアヌスが息子の長男とともにユダヤ地方に遠征した経緯、彼が使用したローマ軍の数はどのくらいだったか、ガリラヤ全土で彼の援軍のうち何人が孤立したか、彼がガリラヤの都市のいくつかを完全に武力で、他の都市を条約や条件で占領した経緯についても述べる。さて、ここまで来たら、ローマ軍の戦闘時の秩序の良さと軍団の規律、ガリラヤ両地方の広さ、その性質、ユダヤの境界について説明するつもりである。そして、これに加えて、私は特に、その地方特有のもの、そこにある湖や泉、そしてそれらが陥落したときに各都市に起こった悲惨な出来事について、私がそこで行われたことや受けた苦しみを目にしたとおり正確に述べます。私自身が経験した災難を一つも隠さず、真実を知る人々に語ります。

9\. この後、ユダヤ人の状況が非常に悪くなったとき、ネロが死に、エルサレムを攻撃しようとしていたウェスパシアヌスが政権を握るために呼び戻されたこと、政権の獲得に関連してどのような兆候が彼に起こったか、そのときローマでどのような政権の変化が起こったか、そして彼が兵士たちによって不本意ながら皇帝にされたこと、そして彼が帝国の政権を握るためにエジプトへ出発したとき、ユダヤ人の状況が非常に混乱したこと、また暴君たちがユダヤ人に対して反乱を起こし、彼らの間で不和に陥ったことなどを語る。

10\. さらに、ティトゥスが二度目にエジプトからユダヤに進軍した経緯、また、彼がどのようにして、どこで、何人の軍隊を集めたか、彼が到着したとき、反乱軍によって町がどのような状態にあったか、彼がどのような攻撃をし、何個の塁壁を築いたか、町を囲む三つの城壁とその寸法、町の強さ、神殿と聖なる家の構造、さらにそれらの建物と祭壇の寸法、そしてすべて正確に測定されたこと、また、彼らの祭りのいくつか、清めの七つの儀式、5祭司の神聖な儀式、祭司と大祭司の衣服、神殿の至聖所の性質についても記述する。ただし、何事も隠さず、既知の事実に何事も付け加えない。

11\. この後、私は、暴君たちが自国民に対して行った蛮行、ローマ人が外国人を容赦した寛容さ、そしてティトゥスが都市と神殿を守りたいという願いから、反乱分子に妥協するよう何度も促したことについて語る。また、人々の苦しみと災難、反乱によってどれほど苦しめられ、飢餓によってどれほど苦しめられ、ついには捕らえられたかについても述べる。また、脱走兵の不幸や捕虜に与えられた罰についても言及する。また、カエサルの同意に反して神殿が焼かれたこと、神殿に保管されていた多くの聖なる品々が火の中から取り出されたこと、また、都市全体が破壊され、その前に起こったしるしや不思議についても言及する。そして、暴君たちを捕虜にし、大勢の奴隷にし、彼らそれぞれがどのようなさまざまな不幸に見舞われたか。さらに、ローマ人が城壁の残骸に何をしたか、国中にあった要塞をどのように破壊したか、ティトゥスが国中を巡り、その問題を整理し、イタリアに帰還して凱旋したか。

12\. 私はこれらすべてのことを七冊の本にまとめ、この戦争を知る人々には不満や非難の余地がないようにした。そして、私は真実を愛する人々のためにそれを書き記したのであり、虚偽の関係に満足する人々のためではない。そして、私はこれらのことの記述を、私が第一章と呼ぶものから始めることにする。

## 第一巻

### 第1章

> エルサレムの町がいかにして陥落し、神殿が略奪されたか（アンティオコス・エピファネスによる）。また、マカバイ家、マティアス、ユダの行動についても、またユダの死についても。

1\. エピファネスと呼ばれたアンティオコスが、シリア全土に対する権利をめぐって第 6 代プトレマイオスと口論していたのと時を同じくして、ユダヤの権力者たちの間で大きな反乱が起こり、彼らは政権獲得をめぐって争いました。一方、高位の者たちは、それぞれが同等の者に従うことに耐えられませんでした。しかし、大祭司のひとりであるオニアスが優勢に立ち、トビアスの息子たちを町から追い出しました。彼らはアンティオコスのもとに逃げ、彼らを指導者として利用し、ユダヤに遠征するよう懇願しました。王は事前にそのように準備していたので、彼らの要求に従い、大軍を率いてユダヤ人を襲撃し、力ずくで町を占領し、プトレマイオスを支持する大勢の人々を殺害し、兵士たちを派遣して容赦なく略奪しました。彼はまた神殿を略奪し、3年6か月間、毎日罪の償いの犠牲を捧げるという習慣を止めさせました。しかし、大祭司オニアスはプトレマイオスのもとに逃げ、ヘリオポリスのノムスで彼から地位を与えられ、そこにエルサレムに似た都市と、その神殿に似た神殿を建てました。これ については、後で適切な場所でさらに詳しく説明します。

2\. アンティオコスは、この都市を思いがけず占領したり、略奪したり、そこで大虐殺を行ったりしても満足せず、激しい怒りに駆られ、包囲中に受けた苦しみを思い出し、ユダヤ人にその国の法律を破棄させ、幼児に割礼を受けさせず、祭壇に豚の肉を捧げるように強要した​​。ユダヤ人は皆これに反対し、最も有能な者たちは死刑に処された。要塞の守備に派遣されたバッキデスもまた、これらの邪悪な命令を受け、生来の蛮行に加わり、あらゆる種類の極悪非道な行為にふけり、住民の中でも最も立派な者たちを一人ずつ苦しめ、毎日公然と都市を破壊すると脅し、ついには極悪非道な行為によって貧しい人々を刺激して復讐させた。

3\. そこで、モディンという村に住む祭司の一人、アサモネウスの息子マティアスは、5人の息子がいる自分の家族とともに武装し、短剣でバッキデスを殺した。そして、多数の守備隊を恐れて山に逃げた。そして、多くの民衆が彼に従ったので、彼は勇気づけられて山から下り、アンティオコスの将軍たちと戦い、彼らを打ち負かしてユダヤから追い払った。こうして、彼はこの成功によって政権を握り、自らの民衆の自由な同意によって君主となり、その後、長男のユダに政権を残して亡くなった。

4\. ユダは、アンティオコスがじっとしているはずがないと考えて、同国人から軍隊を集め、ローマ人と友好関係を結んだ最初の者となり、エピファネスが二度目の遠征を行ったときに、ローマで大敗を喫して彼を国外に追い出した。この大勝利に勇気づけられたユダは、それまで隔離されていなかった市内の守備隊を襲撃した。そこでユダは彼らを市街地から追い出し、兵士たちを下市街地、つまりシタデルと呼ばれる地域に追いやった。それからユダは神殿を掌握し、その場所全体を清めて周囲を壁で囲み、祭儀用の新しい器を作って神殿に持ち込んだ。以前の器は汚されていたからである。またユダは別の祭壇を築き、犠牲を捧げ始めた。そして市街地が再び神聖な秩序を取り戻したとき、アンティオコスは死んだ。その息子アンティオコスが王国を継承したが、ユダヤ人に対する憎悪も継承された。

5\. そこでこのアンティオコスは、歩兵五万、騎兵五千、象八十頭を集め、ユダヤを通って山岳地帯に進軍した。それから彼は小さな町ベツスラを占領したが、道の狭いベツザカリスという所でユダが軍隊を率いて彼と出会った。しかし、軍勢が戦闘に入る前に、ユダの兄弟エレアザルは、象の一番高いところに大きな塔が飾られ、金の軍装で守られているのを見て、アンティオコス自身がその上にいると思い、自分の軍勢よりずっと先に走り、敵の軍勢を切り抜けて象に追いついたが、王と思われるその象は背が高すぎて、近づくことができなかった。しかし、彼は武器を獣の腹に突き刺し、獣を倒し、圧死させた。彼は偉大なことを試みたに過ぎず、命よりも名誉を優先していることを示しただけだった。象を支配していたのは単なる一介の人間であり、もし彼がアンティオコスであることが判明したとしても、エレアザルがこの大胆な一撃によって成し遂げたことは、彼が死を選んだように見えることだけだった。彼には栄光ある行動を起こすというわずかな希望があったのに。いや、この失望は、彼の兄弟\[ユダ\]にとって、戦い全体がどのように終わるかの前兆となった。ユダヤ人が長い間勇敢に戦ったのは事実だが、王の軍は数で勝り、運も味方していたため、勝利を得た。そして、彼の部下の多くが殺されると、ユダは残りの者を連れてゴフナの領地に逃げた。そこでアンティオコスはエルサレムに行き、食料が不足していたため、数日だけそこに留まり、そのまま出発した。彼はその地を守るのに十分だと考えた守備隊を後に残したが、残りの軍はシリアに冬営地を構えるために撤退した。

6\. さて、王が去った後、ユダは怠け者ではなかった。同胞の多くが彼のもとに来たので、彼は戦いから逃れた者たちを集め、アダサという村でアンティオコスの将軍たちと再び戦った。そして、戦いで敵に強敵となり、多くの敵を殺したが、最後には彼自身も殺された。それから数日後、彼の兄弟ヨハネはアンティオコスの党派に陰謀を企てられ、彼らに殺された。

### 第2章

> ユダの後継者であるヨナタンとシモン、そしてヨハネ・ヒルカノスについて。

1\. ユダの兄弟であるヨナタンが王位を継承すると、彼は他の点でも、自分の民との関係でも非常に慎重に行動し、ローマ人との友好関係を維持することで権威を強固にした。また、息子のアンティオコスとも同盟を結んだ。しかし、これだけでは彼の安全は確保できなかった。アンティオコスの息子の後見人であった暴君トリフォンが彼に対して陰謀を企てたのだ。さらに、トリフォンは彼の友人たちを奪おうとし、ヨナタンが数人の仲間とともにプトレマイスからアンティオコスのもとへ向かう途中、策略で彼を捕らえて拘束し、その後ユダヤ人に対する遠征を行った。しかし、後にヨナタンの兄弟であるシモンに追い払われ、敗北に激怒したシモンは、ヨナタンを殺害した。

2\. しかし、シモンは勇敢に政務を遂行し、近隣の都市であるガザラ、ヨッパ、ヤムニアを占領した。また、守備隊を制圧し、城塞を破壊した。その後、シモンはアンティオコスの援軍となり、アンティオコスがメディア遠征に出る前にドラで包囲したトリフォンに対抗した。シモンはトリフォン殺害に協力したにもかかわらず、王にその野心を恥じ入らせることはできなかった。アンティオコスが将軍ケンデベウスを軍隊と共に派遣し、ユダヤを荒廃させ、シモンを征服するのにそれほど時間はかからなかったからである。シモンは年老いていたにもかかわらず、ずっと若いときのように戦争を指揮した。また、シモンは息子たちを一団の勇士と共にアンティオコスに派遣し、自らも軍隊の一部を率いて別の方面から攻撃した。彼はまた、山岳地帯の多くの場所で多数の兵士を待ち伏せさせ、彼らに対するあらゆる攻撃で優勢に立った。そして、このように輝かしい勝利を収めた後、大祭司に任命され、また、170年続いた\[セレウコス\]帝国の統治の後、ユダヤ人をマケドニア人の支配から解放した。

3\. このシモンも陰謀を企てられ、宴会で義理の息子のプトレマイオスに殺された。プトレマイオスはシモンの妻と二人の息子を牢に入れ、ヨハネを殺すために何人かの者を遣わした。ヨハネはヒルカノスとも呼ばれていた。2しかし、若者は彼らが来ることを事前に知らされると、急いで町に向かった。町の人々は父の輝かしい行いの記憶とプトレマイオスの不正に対する憎しみを心に抱いていたため、非常に信頼していたからである。プトレマイオスはまた別の門から町に入ろうとしたが、ちょうどその時ヒルカノスを認めた人々によって撃退された。そこで彼はすぐにエリコの周囲のダゴンと呼ばれる要塞に退却した。さて、ヒルカノスは、父が以前に務めていた大祭司の地位を受け、神に犠牲を捧げた後、母と兄弟たちを救おうと、急いでプトレマイオスを攻撃した。

4\. そこでヒルカノスは要塞を包囲し、他の点ではプトレマイオスより優れていたが、親族に対する正当な愛情に関しては彼に圧倒された。プトレマイオスは困惑すると、母親と兄弟たちを連れ出し、城壁の上に立たせ、皆の目の前で棒で殴り、すぐに立ち去らなければ真っ逆さまに突き落とすと脅した。これを見たヒルカノスの同情と気遣いは怒りをこらえるには強すぎた。しかし母親は鞭打ちにも、脅された死にも動揺せず、手を伸ばして息子に、自分が受けた傷に動揺せず、この哀れな男を助けてやってくれと懇願した。なぜなら、プトレマイオスが家族に与えた傷の罰を受けるかもしれないとしても、プトレマイオスの力で死ぬ方が、いつまでも生き続けるよりはましだったからだ。さて、ヨハネの場合、彼は母親の勇気を思い、彼女の懇願を聞いて攻撃を開始した。しかし、彼女が殴られ、鞭で引き裂かれているのを見ると、彼は弱り果て、完全に愛情に打ち負かされた。こうして包囲が遅れたので、ユダヤ人が7年ごとに7日目に休む安息の年がやってきた。そのため、この年にプトレマイオスは包囲から解放され、ヨハネの兄弟たちとその母親を殺し、フィラデルフィアの僭主であったコティラスとも呼ばれるゼノンの元に逃げた。

5\. アンティオコスはシモンに苦しめられたことに激怒し、ユダヤに遠征し、エルサレムの前に座り込んでヒルカノスを包囲した。しかしヒルカノスは、すべての王の中で最も裕福であったダビデの墓を開け、そこからおよそ三千タラントの金を奪い取り、三千タラントの約束でアンティオコスに包囲を解かせた。さらに、彼は十分な金を持った最初のユダヤ人であり、外国人の援軍も雇い始めた。

6\. しかし、別の時、アンティオコスがメディアへの遠征に出かけ、ヒルカノスに復讐の機会を与えたとき、彼はシリアの都市にすぐ攻撃を仕掛けた。そこには優秀な軍隊がいないことがわかったからである。そこで彼はメダバとサメア、その近隣の町々、シェケム、ゲリジムを占領した。さらに、エルサレムの神殿を模して建てられた神殿の周囲に住んでいたクテア人の国を征服した。また、イドマヤの多くの都市、アドレオン、マリサも占領した。 7. 彼はまた、ヘロデ王が建てたセバステの町があるサマリアまで進軍し、周囲を城壁で囲み、息子のアリストブロスとアンティゴノスを包囲に当たらせた。彼らはそれを非常に強く押し進めたので、市内に飢饉が広がり、人々は決して評価されない食物を食べざるを得なくなった。彼らはまた、キュジケノスと呼ばれていたアンティオコスに援助を求めた。そこで彼は準備を整えて彼らの招きに応じたが、アリストブロスとアンティゴノスに打ち負かされ、実際彼はこれらの兄弟たちにスキトポリスまで追跡され、彼らから逃げ去った。そこで彼らはサマリアに戻り、再び群衆を壁の中に閉じ込めた。そして彼らは都市を占領すると、それを破壊し、住民を奴隷にした。そして彼らは事業で依然として大きな成功を収めていたので、熱意が冷めるのを許さず、軍隊を率いてスキトポリスまで行軍し、そこを侵略して、カルメル山内の全地域を荒廃させた。

8\. しかし、ヨハネとその息子たちのこうした成功は、妬まれ、国内で反乱を引き起こした。そして、多くの人々が結束し、戦争に突入するまでは落ち着こうとしなかったが、戦争で敗北した。そこでヨハネは残りの人生を非常に幸せに過ごし、33年間にわたって、非常に並外れたやり方で政府を運営した。彼は5人の息子を残して亡くなった。彼は確かに非常に幸せな人であり、彼のせいで財産について不満を言う理由はまったくなかった。彼だけが、世界で最も望ましい3つのもの、すなわち国家の統治、高位の神官職、そして予言の才能を持っていた。なぜなら、神は彼と会話し、彼はその後に起こることを何も知らなかったわけではなかったからである。そのため、彼は、2人の長男が引き続き政府の主人となることはないだろうと予見し、予言した。そして、彼らの悲惨な運命と、彼らが幸福において父親よりどれほど劣っていたかを説明することは、我々の物語として大いに価値があるだろう。

### 第3章

> アリストブロスは頭に王冠をかぶった最初の人物であり、母と兄弟を殺した後、わずか一年しか統治せずに自らも死んだ。

1\. 彼らの父の死後、彼らのうちの長男アリストブロスは、政府を王国に変え、バビロニアの奴隷状態から解放されて我々の民がこの地に降り立ってから 471 年 3 か月後に、最初に頭に王冠をかぶった。さて、彼は兄弟の中で、自分と隣り合っていたアンティゴノスに愛情を抱いていたようで、アンティゴノスを自分と同等の者とした。しかし、他の兄弟については、彼らを縛り、牢獄に送った。また、彼は母親を拘束した。なぜなら、彼女が彼と政府を争ったからである。なぜなら、ヨハネスは彼女を公務の女官として残していたからである。彼はまた、彼女を牢獄で縛り殺すほどの蛮行を行った。

2\. しかし、彼が愛し、王国のパートナーにしていた兄アンティゴノスの件では、復讐は彼の手を逃れた。宮殿の悪人が彼に対して企てた中傷によって、彼は兄を殺したのである。確かに、最初は、アリストブロスは、兄に対する愛情から、また、これらの話の大部分は、その話の語り手たちの嫉妬によるものだと考えたために、彼らの話を信じようとしなかった。しかし、かつて、アンティゴノスは、神のために幕屋を建てるという古い習慣がある祭りに、軍隊から華麗な姿でやって来たことがある。ちょうどその頃、アリストブロスは病気で、祭りの終わりに、アンティゴノスは武装した部下たちを従えて、できるだけ美しく着飾って、そして、主に、兄のために神に祈るためにやって来たのである。ちょうどそのとき、これらの悪党たちが王のもとにやって来て、武装した兵士たちがいかに尊大な態度でやって来たか、アンティゴノスがいかに横柄な態度で進軍したか、その横柄さは一私人としては大きすぎるため、大勢の兵士を率いて王を殺すために来たのだ、と告げた。アンティゴノスは、王国を自ら奪取する力があるのに、王の名誉をわずかに享受しているだけでは耐えられない、と。

3\. アリストブロスは、次第に、不本意ながら、これらの告発を信じるようになった。そのため、彼は、いかなる事故に対しても安全を確保するよう心掛けながらも、公然と疑惑を明かさないように注意した。そこで、彼は、かつてはシタデルと呼ばれ、後にアントニアと改名された場所に病床にあったため、彼の遺体の警備員をある暗い地下道に配置した。そして、アンティゴノスが武器を持たずに来たら、そのままにしておけ、しかし、もし彼が鎧を着て来たら、殺せと命令した。また、彼は、武器を持たずに来るように事前に知らせるために、何人かを遣わした。しかし、このとき、王妃は、彼の破滅を企む者たちと非常に巧妙に共謀した。彼女は、派遣された者たちに、王の伝言を隠蔽するよう説得し、アンティゴノスに、彼の兄弟が、ガリラヤで、素晴らしい軍用装飾が施された鎧を手に入れたと聞いたと告げさせたのである。そして、彼は現在病気のため、来てそのすべての豪華な衣装を見ることができないので、今すぐに鎧を着た彼に会いたいと強く望んでいた。なぜなら、彼は言った、「もうすぐあなたは私から去っていくからです。」

4\. アンティゴノスはこれを聞くとすぐに、兄の温厚な性格から、兄が危害を加えるとは考えず、鎧を着て兄に見せに来た。しかし、ストラトスの塔と呼ばれたあの暗い通路を歩​​いているときに、護衛兵に殺され、中傷がいかにしてすべての善意と自然な愛情を破壊するか、また、我々の善意のどれもが嫉妬に永久に抵抗できるほど強くないことを示す顕著な例となった。

5\. そして、この機会にユダが来たことには誰もが驚くだろう。彼はエッセン派に属し、これまで予言で人を裏切ったり騙したりしたことはなかった。この男は、神殿のそばを通りかかったアンティゴノスを見て、知り合いに叫んだ。\[アンティゴノスの教え子として彼に付き添っていたのは、少なくなかった\] 「おや、不思議だ！」彼は言った。「真実は私の目の前で死んでおり、私が予言したことのいくつかは偽りであることが判明したので、今死ぬのは私にとって良いことだ。このアンティゴノスは今日生きているが、今日死ぬべきだった。そして、あの致命的な判決によれば、彼が殺されるはずの場所は、ここから600ファーロング離れたストラトスの塔だった。しかし、今日は既に4時間が経過しており、その時点で予言が満たされることは不可能だ。」老人はこれを言うと、心の中で落胆し、こう続けた。しかし、しばらくして、アンティゴノスが地下の場所で殺害されたという知らせが入りました。その地下の場所は、海辺にあったカエサレアと同じ名前で、ストラトスの塔とも呼ばれていました。この曖昧さが、預言者の動揺を引き起こしたのです。

6\. そこでアリストブロスは自分が犯した大罪を悔い改めたが、これが彼の病気を悪化させる原因となった。彼の病状はますます悪化し、自分の犯した罪を考えるだけで彼の魂は絶えず動揺し、耐え難い悲しみで内臓が引き裂かれ、大量の血を吐いた。そして彼に付き添っていた召使の一人がその血を吐いているとき、超自然的な摂理によって、彼はアンティゴノスが殺されたまさにその場所で足を滑らせて倒れ、殺害された彼の血の跡に殺人者の血をこぼし、その跡は今も残っていた。そこで、まるで召使がその場所にわざと血をこぼしたかのように、見物人の間で悲痛な叫び声が上がった。王はその叫び声を聞くと、何が原因なのか尋ねた。誰も彼に告げる勇気がなかったため、彼はますます彼らに何が起こったのかを知らせるよう迫った。そしてついに、彼が彼らを脅して、彼らに話すように強いると、彼らは告げた。すると彼は涙を流し、うめき声​​をあげて言った。「私は、自分が犯した大罪に関して、神の全能の目から逃れることはできないと悟った。しかし、私の親族の血の復讐が私を急いで追いかけてくる。おお、この最も厚かましい体よ！ 殺された母と兄弟のために受けるべき罰のために死ぬべき魂を、いつまで引き留めておくつもりだ！ 私自身、いつまで血を一滴ずつ使い果たすつもりだ？ 彼らにそれを一度に全部飲ませよう。そして、彼らの亡霊が、私の腸のいくつかの包みを彼らに差し出しても失望しないようにしよう。」彼がこれらの言葉を言うとすぐに、彼は1年も統治せずにすぐに死んだ。

### 第4章

> 27年間 統治したアレクサンダー・ヤネウスはどのような行動をとったか。

1\. そして今、王の妻は王の兄弟たちを解放し、アレクサンダーを王とした。アレクサンダーは他の兄弟たちよりも年上で、気質も温和であった。アレクサンダーは政権に就くと、自らを治めようとする兄弟の一人を殺害したが、もう一人の兄弟は静かな生活を愛し、公務に干渉しないとして大いに尊敬していた。

2\. そのとき、アレクサンダーと、アソキス市を占領したラテュルスと呼ばれるプトレマイオスとの間に戦いがあった。彼は確かに多くの敵を殺したが、勝利はむしろプトレマイオスに傾いた。しかし、このプトレマイオスが母親のクレオパトラに追われてエジプトに退却すると、アレクサンダーはガダラを包囲してこれを占領した。また、ヨルダン周辺の要塞の中で最も強固なアマトスも占領した。そこにはゼノンの息子テオドロスの最も貴重な所有物があった。そこでテオドロスは彼に向かって進軍し、自分の所有物と王の荷物を奪い、ユダヤ人一万人を殺害した。しかし、アレクサンダーはこの打撃を挽回し、軍を海沿いの地域に向け、ラフィアとガザ、そして後にヘロデ王によってアグリッピアスと呼ばれるようになったアンテドンも占領した。

3\. しかし、彼がこれらすべての都市の住民を奴隷にした後、ユダヤ人の国民は祭りの時に彼に対して反乱を起こした。というのも、こうした祭りでは一般的に暴動が起きるからである。そして、彼の外国の援軍であるピシディア人とキリキア人が彼を助けなければ、彼らが彼に仕掛けた陰謀から逃れられないように思われた。シリア人に関しては、ユダヤ人に対する生来の敵意のため、彼は彼らを傭兵部隊に決して受け入れなかった。そして、彼は反乱者を6000人以上殺害した後、アラビアに侵攻し、その地をギレアデ人とモアブ人と共に占領すると、彼らに貢物を納めるよう命じ、アレトゥスに戻った。そして、テオドロスがその大成功に驚いたので、彼は要塞を占領し、それを破壊した。

4\. しかし、ゴラン高原付近で彼を待ち伏せし、陰謀を企てていたアラビアの王オボダスと戦ったとき、彼は全軍を失い、軍は深い谷間に密集し、ラクダの大群に粉砕された。そしてエルサレムに逃げたとき、彼は以前から彼を憎んでいた群衆を挑発し、彼に対する反乱を起こさせた。これは彼が受けていた災難の重大さのためであった。しかし、彼は当時彼らにとって手ごわすぎた。そして、両軍の間で戦われた数々の戦いで、彼は6年間の間に5万人以上のユダヤ人を殺した。しかし、彼はこれらの勝利を喜ぶ理由がなかった。彼は自分の王国を滅ぼしただけだったからである。ついに彼は戦いをやめ、臣民と話し合い、和解しようと努めた。しかし、彼の行動のこの変わりやすく不規則な性質は、彼らに彼をさらに憎まれるようにした。そして、ユダヤ人がなぜ自分をそんなに憎んでいるのか、そして彼らをなだめるために何をすべきかと尋ねると、彼らは自殺すればいいと答えた。なぜなら、死んでからでさえ彼らにそのような悲劇的なことをした彼と和解するには、そうすることしかできなかったからだ。同時に、彼らはエウケロスと呼ばれるデメトリオスに協力を依頼した。彼は大きな利益を期待して彼らの要求に快く応じ、軍隊を率いて来たので、ユダヤ人はシェケムの周りの援軍と合流した。

5\. アレクサンダーは、1000人の騎兵と8000人の歩兵傭兵で両軍を迎え撃った。また、味方のユダヤ人も1万人を率いていた。一方、敵軍は3000人の騎兵と14000人の歩兵を率いていた。さて、彼らが戦闘に入る前に、両王は布告を出し、互いの兵士を引き離して反乱を起こそうとした。一方、デメトリオスはアレクサンダーの傭兵を自分から引き離そうとし、アレクサンダーはデメトリオスに味方するユダヤ人を自分から引き離そうとした。しかし、ユダヤ人は怒りを止めようとせず、ギリシア軍も不誠実な態度をとらなかったため、彼らは交戦し、武器を駆使して激しい戦いを繰り広げた。この戦いでは、アレクサンダーの傭兵が心身ともに最大の功績を挙げたにもかかわらず、デメトリオスが勝利した。しかし、この戦いの結果は、両者にとって予想と異なるものとなった。デメトリオスを招いた者たちも、彼が勝利したにもかかわらず、彼に固執し続けたわけではなかった。そして、アレクサンダーが山に逃げたとき、彼の状態の変化を憐れんで六千人のユダヤ人が彼のもとにやって来た。しかし、デメトリオスはこの事態に耐えることができなかった。しかし、アレクサンダーがすでに彼に匹敵する存在になり、国全体が彼のところに駆け寄ってくるだろうと考えて、国を離れ、自分の道を歩み始めた。

6\. しかし、残りのユダヤ人たちは、外国の援軍が去った後も彼との争いをやめず、アレクサンダーと絶え間なく戦い、アレクサンダーは彼らの大半を殺し、残りをベルネセリスの町に追いやった。そして、その町を破壊した後、捕虜をエルサレムに連行した。いや、彼の怒りは極度に高まり、その蛮行は不敬虔なレベルにまで達した。800人を町の真ん中で十字架に掛けるよう命じたとき、彼は彼らの妻や子供たちの喉を彼らの目の前で切り裂いた。そして、彼は妾たちと酒を飲み、寝ているときに、これらの処刑を見た。人々はこれに非常に驚き、翌晩、反対派の8000人がユダヤ全土から逃げ出した。彼らの逃亡はアレクサンダーの死によってようやく終わった。こうして、彼は、遅くとも非常に困難な状況ではあったが、このような行動によってついに王国に平穏をもたらし、それ以上の戦闘をやめた。

7\. しかし、ディオニュシオスとも呼ばれるアンティオコスは、再び問題の原因となった。この男はデメトリオスの兄弟であり、セレウコス家最後の人物であった。3アレクサンダーは、アラビア人に向かって進軍していたとき、彼を恐れていた。そこで、山に近いアンティパトリスとヨッパの海岸の間に深い溝を掘り、溝の前に高い壁を築き、突然の接近を防ぐため、木の塔を建てた。しかし、それでも彼はアンティオコスを追い払うことができず、塔を焼き、溝を埋め、軍隊を率いて進軍した。そして、アレクサンドロスが彼を阻止しようとしたことに対する復讐を、取るに足らないこととみなしたので、彼はアラブ人に向かって直接進軍した。アラブ人の王は、敵と交戦するのに最も適した地域に退却し、それから突然、一万人の騎兵を引き返しさせ、混乱したアンティオコスの軍隊に襲いかかり、恐ろしい戦いが起こった。アンティオコスの軍隊は、彼が生きている間は戦い続けたが、アラブ人によって大虐殺が行われた。しかし、彼が倒れると、彼は最前線にいて、軍隊を結集する上で極めて危険な状況にあったため、彼らは皆退却し、彼の軍隊の大部分は戦闘中または逃走中に壊滅した。カナ村に逃げた残りの者たちは、わずかな例外を除いて、必需品の欠乏で全員が死に絶えた。

8\. この頃、ダマスカスの人々はメンヘンスの息子プトレマイオスに対する憎しみから、アレタスを招いてケレシリア王とした。アレタスもまたユダヤに遠征し、戦いでアレクサンダーを打ち負かしたが、その後双方の合意により撤退した。しかしアレクサンダーはペラを占領した後、テオドロスの領地を欲しがって再びゲラサに進軍し、守備隊の周囲に三重の城壁を築いてから、その地を力ずくで占領した。またゴラン、セレウキア、アンティオコスの谷と呼ばれた地域を破壊した。さらに、ガマラの堅固な要塞を占領し、そこの知事であったデメトリオスから、彼にかけられた多くの罪のゆえに、その財産を剥奪し、この遠征に丸三年を費やした後、ユダヤに戻った。そして今、彼はその成功のゆえに国民から好意的に迎えられた。そこで戦争から一息ついたとき、彼は病気にかかった。四日熱にかかっていたため、再び軍事活動に取り組めばこの病気が治るだろうと考えた。しかし、時宜にかなわない時期にそのような遠征を行い、体に耐えられる以上の苦難を強いたために、彼は自ら命を絶った。こうして、彼は27年間の統治の後、苦難のさなかに亡くなった。

### 第5章

> アレクサンドラは9年間統治し、その間、パリサイ人が国の実質的な支配者でした。

1\. さて、アレクサンドリアは王国を妻のアレクサンドリアに残し、ユダヤ人が今や喜んで彼女に服従するだろうと期待した。なぜなら、彼女は彼がユダヤ人に対して行ったような残酷な扱いを非常に嫌っており、彼らの法律を破ることに反対し、それによって人々の好意を得ていたからである。彼の期待は間違っていなかった。この女性は、人々が彼女の敬虔さについて抱いていた評価によって、領土を維持したからである。彼女は主に自国の古い慣習を研究し、彼らの神聖な法律に反する人々を政府から追放した。そして、彼女はアレクサンドリアとの間に二人の息子をもうけたので、彼女は年長のヒルカノスを大祭司に任命した。それは彼の年齢のためであり、またそれに加えて、彼の無気力な性格が公衆を混乱させるような性格ではないためであった。しかし、彼女は弟のアリストブロスを、彼の気質が激しいため、私人として彼女のもとに留めた。

2\. そして、パリサイ人たちが彼女に加わり、彼女の政治を助けた。彼らはユダヤ人の一派で、他の人たちよりも信心深く、法律をより正確に解釈しているようだった。アレクサンドラは神に対して非常に敬虔な女性だったので、彼らに並外れたほど従った。しかし、これらのパリサイ人たちは、少しずつ巧妙に彼女の好意を得、彼ら自身が公務の実質的な管理者となった。彼らは望む者を追放し、権力を弱め、望むままに人を縛り、解放した。4つまり、彼らは王権を享受し、その費用と困難はアレクサンドラのものだった。彼女は大事の運営に賢明な女性で、常に兵士を集めることに熱心だった。そこで彼女は軍隊を半分に増強し、外国の軍隊を大量に獲得した。その結果、彼女の国家は国内で非常に強力になっただけでなく、外国の有力者たちからも恐れられるようになり、彼女は他の人々を統治し、パリサイ人が彼女を統治した。

3\. そこで、彼らは、アレクサンドロスの友人で、名士でもあったディオゲネスを自ら殺害し、彼が王の助言に加担して、800人の男たちを十字架につけたと告発した。また、アレクサンドラを説得して、自分たちに対して彼を怒らせた残りの者たちを死刑にするよう説得した。彼女は迷信深く、彼らの望みを聞き入れ、彼らは好きな者を殺した。しかし、危険にさらされた者のうちの主だった者はアリストブロスのもとに逃げ、彼は母親を説得して、男たちの威厳を理由に彼らを許すが、無実だと思わない限りは町から追放するよう説得した。そのため、男たちは処罰されずに、国中に散らばった。しかし、アレクサンドラがダマスカスに軍隊を派遣したとき、プトレマイオスが常にその町を抑圧しているという口実で、彼女はダマスカスを占領し、大きな抵抗もしなかった。彼女はまた、プトレマイス付近に軍を率いて駐屯し、協定と贈り物でクレオパトラを包囲していたアルメニア王ティグラネスを説得し、立ち去るよう要求した。その結果、ルクルスのアルメニア遠征中に起こった国内の騒乱のため、ティグラネスはすぐに包囲から解放された。

4\. その間にアレクサンドラは病気になり、彼女の息子アリストブロスは、若さゆえの温情で友人であった大勢の召使たちとともにこの機会を捉え、すべての要塞を占領した。また、彼はその中の金銭を使って傭兵を集め、自ら王となった。さらに、ヒルカノスが母親に訴えると、母親は彼の事情を憐れみ、アリストブロスの妻と息子たちをアントニアに拘留した。アントニアは神殿の北側に接する要塞であった。すでに述べたように、そこは昔はシタデルと呼ばれていたが、後にアントニウスが\[東の領主\]であったときにアントニアという名前が付けられた。同様に、他の都市、セバステとアグリッピアスも名前が変更され、セバストゥスとアグリッパからその名前が与えられた。しかし、アレクサンドラは、アリストブロスが弟を相続権から排除したことに対する罰を与える前に、9年間統治した後に亡くなった。

### 第6章

> アレクサンドロスの後継者ヒルカノスが王位継承権を放棄すると、アリストブロスが王位に就く。その後、同じヒルカノスはアンティパトロスの助けによりアベタスに連れ戻される。最後にポンペイウスが兄弟間の争いの仲裁者となる。

1\. さて、ヒルカノスは王国の相続人であり、彼の母は死ぬ前にそれを彼に託した。しかし、アリストブロスは力と寛大さにおいて彼より優れていた。そして、エリコの近くで王国をめぐる争いを決着させるために彼らの間に戦いがあったとき、大部分はヒルカノスを捨ててアリストブロスに寝返った。しかし、ヒルカノスは彼と共にいた仲間たちとともにアントニアに逃げ、彼の身を守るために人質（アリストブロスの妻とその子供たち）を彼の手に渡した。しかし、事態が極限に達する前に、彼らは合意に達した。アリストブロスが王となり、ヒルカノスはそれを辞任するが、王の兄弟として他のすべての名誉を保持することであった。そこで彼らは神殿で和解し、人々が彼らの周りに集まる中、非常に親切に抱き合った。彼らも住居を変え、アリストブロスは王宮へ行き、ヒルカノスはアリストブロスの家に退いた。

2\. アリストブロスと意見が合わない人々は、彼が予期せず政権を獲得したことを恐れた。特に、アリストブロスが昔から憎んでいたアンティパトロスが恐れた。アンティパトロスはイドマヤ人の生まれで、祖先や富、その他の権威からその国の有力者の一人であった。アンティパトロスはヒルカノスを説得して、アラビアの王アレタスのもとに逃げ、王国を主張させた。また、アレタスを説得してヒルカノスを迎え入れ、王国に連れ戻すよう説得した。また、アリストブロスの道徳観を大いに非難し、ヒルカノスを大いに褒め、アレタスに彼を迎えるよう勧め、これほど大きな王国を統治する彼が、傷ついた者を助けるのは、いかに恥ずべきことかを語った。アリストブロスは、ヒルカノスが生まれながらの特権によって属していた領土を奪われ、不当に扱われたと主張した。そして、二人に自分の望むことをするように仕向けた後、彼は夜にヒルカノスを捕らえて町から逃げ出し、非常に素早く逃走を続け、アラビア王の王宮であるペトラという場所に逃げ込み、そこでヒルカノスをアレタスの手に委ねた。そして、彼と多くの話し合いをし、多くの贈り物で彼を説得し、王国を回復できる軍隊を与えるよう説得した。この軍隊は5万人の歩兵と騎兵で構成されており、アリストブロスはこれに抵抗することができず、最初の攻撃で見捨てられ、エルサレムに追いやられた。ローマの将軍スカウルスがやって来て時宜にかなった介入をして包囲を解かなければ、彼も最初は力ずくで捕らえられていただろう。このスカウルスは、ティグラネスと戦ったとき、ポンペイウス大王によってアルメニアからシリアに派遣された。そこでスカウルスは、メテッルスとロリウスが最近占領したダマスカスに来て、彼らにその地から立ち去らせた。そして、ユダヤの状況を聞いて、ある戦利品を求めてそこへ急いだ。

3\. それで、彼が国に着くとすぐに、両兄弟から使者がやって来て、それぞれが彼の援助を求めた。しかし、アリストブロスの三百タラントは、彼にとって、大義の正当性よりも重要であった。スカウルスはその金額を受け取ると、ヒルカノスとアラビア人に使者を送り、包囲を解かなければローマ人とポンペイウスの恨みを買ってやるぞと脅した。それでアレタスは恐れおののき、ユダヤからフィラデルフィアに撤退し、スカウルスも再びダマスカスに戻った。アリストブロスは\[兄弟の手から\]逃げるだけでは満足せず、全軍を集めて敵を追跡し、パピロンと呼ばれる場所で戦い、敵の約六千人を殺し、アンティパトロスの兄弟ファリオンも殺した。

4\. ヒルカノスとアンティパトロスは、アラビア人からの希望をこのように奪われると、その希望を敵に転嫁した。ポンペイウスがシリアを通ってダマスカスに来ていたので、彼らはポンペイウスのもとに助けを求めて逃げた。そして、賄賂もなしに、アレタスに使ったのと同じ公正な嘆願をし、アリストブロスの暴力的な振る舞いを憎むように、そして、彼の善良な性格と年齢の優越性の両方から、王国が正当に属する彼に王国を与えるように懇願した。しかし、この場合、アリストブロスはスカウルスが受け取った賄賂を頼りにしていたため、自分自身も不足していなかった。彼自身もそこにいて、できる限り王族にふさわしい方法で身を飾った。しかし、すぐに彼は、そのような卑屈な態度で来るのは自分にふさわしくないと考え、慣れているよりもずっと卑しい方法で自分の目的を果たすことに耐えられなかった。そこで彼はディオスポリスから出発した。

5\. この彼の行動にポンペイウスは大いに憤慨した。ヒルカノスとその友人たちもポンペイウスに大いにとりなしをした。そこでポンペイウスはローマ軍だけでなく、シリアの援軍の多くも率いてアリストブロスに向かって進軍した。しかしペラとスキトポリスを通り過ぎてコリアに着いたとき、地中海地方を通ってユダヤ地方に入るところであるが、そこでアリストブロスがアレクサンドリアに逃げたと聞いた。アレクサンドリアは高い山の上にある、極めて壮麗に要塞化された要塞である。そこでポンペイウスはアリストブロスに使いを送って下りてくるように命じた。彼はそのように横柄な態度で呼ばれたので、その呼びかけに応じるよりも、戦いで運試しをしたいと思った。しかし群衆が大いに恐れているのを見て、友人たちはローマ軍の力はどれほどのものか、それがいかに無敵であるかを考えるよう彼に勧めた。そこで彼は彼らの助言に従い、ポンペイウスのもとに下って行った。そして、自分のことと、政権を握った自分の大義の正当性について長々と弁明した後、要塞に戻った。そして、兄が再び彼を招き入れると（自分の大義を弁護するよう）、彼は下って来て、その正当性を語り、それからポンペイウスから何の妨害も受けずに立ち去った。彼は希望と不安の間で揺れ動いていた。そして彼が下って来たのは、ポンペイウスに政権を全面的に認めてもらうためだった。そして、彼が城塞に上って行ったのは、あまりに身分を卑しめているように思われないようにするためだった。しかし、ポンペイウスは彼に要塞を明け渡すよう命じ、要塞を明け渡すよう総督全員に手紙を書かせた。彼らは、ポンペイウスの自筆以外の手紙には従わないという命令を受けていた。そこで彼は命令に従ったが、それでも行われたことに憤慨し、エルサレムに退き、ポンペイウスと戦う準備をした。

6\. しかしポンペイウスは彼に包囲の準備をする時間を与えず、彼の後を追った。また、エリコでミトリダテスの死を知らされたため、彼は攻撃を急がざるを得なかった。さて、ここはユダヤで最も肥沃な土地で、バルサムの木のほかに、たくさんのヤシの木が生えている。その新芽は鋭い石で切り取られ、切り口から涙のように滴る汁が採取される。そこでポンペイウスはその場所に一晩陣を張り、翌朝エルサレムに急いだ。しかし、アリストブロスは彼が近づいてくるのを恐れ、懇願するために彼に会いに来た。彼はまた、金銭を約束し、自分と町の両方を彼の手に引き渡すと約束し、それによってポンペイウスの怒りを和らげた。しかし、彼は同意した条件を一つも実行しなかった。というのは、アリストブロスの一派は、約束した金を受け取るために派遣されたガビニウスを市内に入れることさえしなかったからである。

### 第7章

> ポンペイウスはエルサレムの町を明け渡し、神殿を力ずくで奪取した。ポンペイウスはどのようにして至聖所に入ったのか。また、ユダヤで彼が行ったその他の功績は何だったのか。

1\. この仕打ちにポンペイウスは激怒し、アリストブロスを拘留した。そして、彼は町に到着すると、どこから攻撃を仕掛けるかを調べた。なぜなら、城壁は非常に堅固で、突破するのは困難であり、城壁の前の谷は恐ろしく、その谷の中にある神殿自体も非常に堅固な城壁に囲まれており、町が陥落しても、その神殿は敵が退却する第二の避難場所となるだろうと考えたからである。

2\. さて、彼がこの件について長々と議論しているうちに、市内の民衆の間で騒乱が起こった。アリストブロス派は戦って王を解放する用意があり、一方ヒルカノス派はポンペイウスに門を開けるつもりだった。そして、ローマ兵の整然とした秩序を見て、人々は後者の派閥が非常に多数派になることを恐れた。そこでアリストブロス派は敗北し、神殿に退却し、神殿と市内を結ぶ橋を破壊して両者の連絡を遮断し、最大限の抵抗を準備した。しかし、他の者たちはローマ軍を市内に迎え入れ、宮殿を彼に引き渡したので、ポンペイウスは彼の高官の一人であるピソを軍隊とともに宮殿に送り、神殿に逃げ込んだ者たちのうち誰一人として妥協に応じさせることができなかったため、彼は市内のあちこちに守備隊を配置した。それから彼は、ヒルカノスの部隊が彼らに助言と援助を与える用意ができているように、彼らの周囲にあるすべてのものを攻撃に有利になるように配置した。

3\. しかしポンペイウスは自ら神殿の北側にあった溝と谷全体を埋めた。軍隊自身がその目的のために資材を運ばなければならなかった。そして谷の深さがあまりにも深かったため、その谷を埋めるのは確かに困難なことだった。特にユダヤ人は優位な立場から彼らを撃退するためにあらゆる手段を講じていた。ローマ軍もその努力に成功しなかった。ポンペイウスはユダヤ人が宗教上の理由であらゆる仕事を断つ第七日に注意を払っていなかったため、土手を上げ、その日に兵士たちが戦うのを控えていた。なぜならユダヤ人は安息日にのみ防御行動をとったからである。しかしポンペイウスは谷を埋めるとすぐに、土手に高い塔を建て、ティルスから運んできた武器を城壁に近づけ、それを打ち壊そうとした。そして石を投げる者たちは、その上に立っていたものを打ちのめし、追い払った。しかし、この街のこちら側にある塔は非常に大きな抵抗力を持っており、その大きさと壮麗さはまさに並外れたものでした。

4\. さて、ここで、ローマ人が経験した多くの困難において、ポンペイウスは、ユダヤ人の不屈の精神の他の例だけでなく、特に彼らが四方から矢で包囲されたときでさえ、宗教的な儀式をまったく中断しなかったことに感心せざるを得なかった。というのは、まるで町が完全に平和であるかのように、彼らの毎日の犠牲と浄化、そして彼らの宗教的礼拝のあらゆる分野が、依然として極めて厳格に神に捧げられていたからである。また、神殿が実際に陥落し、彼らが祭壇の周りで毎日殺されたときでさえ、彼らは法律で定められた神への礼拝の例を怠ることはなかった。というのも、包囲の 3 ヶ月目に、ローマ人は大変な苦労をしながらも塔の 1 つを倒し、神殿に入ることができたからである。さて、最初に壁を乗り越えようとしたのは、シラの息子ファウストゥス・コルネリウスであり、次に彼に続いたのは 2 人の百人隊長、フリウスとファビウスであった。そして、これらの各部隊には、自らの部隊が従い、ユダヤ人を四方から包囲して、神殿に避難しようと逃げているユダヤ人や、しばらくの間自衛のために戦っているユダヤ人を殺害した。

5\. 祭司たちの多くは、敵が剣を手に襲いかかってくるのを見ても、何の妨害もなく礼拝を続け、神への礼拝の義務を自分の身の安全よりも優先したため、酒を捧げたり、香を焚いたりしているときに殺された。祭司たちの大部分は敵対する同胞によって殺され、数え切れないほどの群衆が断崖から身を投げた。いや、中には、自分たちが直面している克服できない困難に混乱し、壁に近い建物に火を放ち、彼らも一緒に焼けた者もいた。ユダヤ人は1万2千人が殺されたが、ローマ人は殺されたのはごくわずかで、負傷した者の方が多かった。

6\. しかし、当時国民が被っていた災難の中で、これまで誰にも見られなかった聖所が外国人に開放されたことほど国民を動揺させたものはなかった。ポンペイウスと彼の取り巻きたちは、大祭司以外は誰も立ち入ることが許されていない神殿に入り、そこに保管されているもの、すなわち燭台とそのランプ、テーブル、注ぎ口、香炉などすべて金でできており、また大量の香料が山積みにされ、聖なる金二千タラントも積まれていた。しかしポンペイウスはその金にも、そこに保管されていた他の物にも触れず、神殿を奪った翌日には、神殿の周りの大臣たちに神殿を清め、いつもの供え物を捧げるよう命じた。さらに、彼はヒルカノスを大祭司に任命した。それは、包囲戦の間、他の点では彼の側に非常に機敏に動いただけでなく、国内の民衆がアリストブロスのために戦うのを阻止する手段となったからである。彼らはそうでなければ、アリストブロスのために戦うことを非常に喜んでいた。その手段によって、ヒルカノスは良き将軍の役割を演じ、恐怖よりも慈悲によって民衆を彼と和解させた。さて、捕虜の中には、アリストブロスの義父で彼の叔父でもある人物が捕らえられた。そこで、彼は最も罪深い者たちを斬首で罰したが、ファウストスと彼と共に勇敢に戦った者たちには、栄誉ある贈り物で報い、国とエルサレム自体に貢物を課した。

7\. 彼はまた、彼らが以前占領していたケレシリアに属するすべての都市を国から奪い、当時ローマの長官に任命されていた者の支配下に置き、ユダヤをその本来の境界内に収めた。また、ユダヤ人によって破壊されていたガダラを再建した。9これは、ガダラ出身で、彼自身の解放奴隷の一人であったデメトリオスを満足させるためであった。彼はまた、国土の中央にあった、それまでに破壊されていなかった都市、すなわちヒッポス、スキトポリス、ペラ、サマリア、マリサ、さらにアシュドド、ヤムニア、アレトゥサを彼らの支配から解放した。彼はまた、ガザ、ヨッパ、ドラという海沿いの都市、そして昔はストラトスの塔と呼ばれていたが、後にヘロデ王によって最も壮麗な建物が再建され、カエサレアと名前を変えられた都市についても同様に対処した。彼はこれらすべてを市民に返還し、シリア属州の管轄下に置いた。この属州とユダヤ、エジプト、ユーフラテスまでの地域をスカウルスに総督として委ね、2個軍団を彼に支援させた。一方、スカウルスはアリストブロスとその子供たちを捕虜として連れて、キリキアを通ってローマに向かうのに全力を尽くした。2人の娘と2人の息子のうち、息子のアレクサンダーは行く途中で逃げたが、弟のアンティゴノスは姉妹たちとともにローマに連れて行かれた。

### 第8章

> ポンペイウスから逃亡したアリストブロスの息子アレクサンダーはヒルカノスに対して遠征を行うが、ガビニウスに打ち負かされ、要塞を彼に引き渡す。その後、アリストブロスはローマから脱出し、軍隊を集めるが、ローマ人に敗れ、ローマに連れ戻される。ガビニウス、クラッスス、カッシウスに関するその他の事柄も含む。

1\. その間、スカウルスはアラビアに遠征したが、ペトラ周辺の場所の難しさで阻止された。しかし、彼はペラ周辺の地域を荒廃させたが、そこでも彼は大きな困難に直面していた。彼の軍隊は飢餓に苦しんでいたからである。その不足を補うために、ヒルカノスは彼にいくらかの援助を与え、アンティパトロスを通して彼に食料を送った。スカウルスは、彼とよく知り合いだったアレタスに彼を送り、和平を買うための金銭を払うよう説得した。アラビアの王はその提案に応じ、彼に300タラントを与えた。それを受けてスカウルスはアラビアから軍を撤退させた。

2\. しかし、ポンペイウスから逃亡したアリストブロスの息子アレクサンダーは、しばらくしてかなりの数の兵を集め、ヒルカノスに重くのしかかり、ユダヤを制圧し、すぐに彼を倒そうとした。実際、彼はエルサレムに来て、ポンペイウスによって破壊された城壁を再建しようとしていたが、スカウルスの後継者としてシリアに派遣されたガビニウスは、他の多くの点と同様に、アレクサンダーに対する遠征で勇敢さを示した。アレクサンダーは、ガビニウスが自分を攻撃することを恐れて、武装した一万人の歩兵と千五百人の騎兵からなる大軍を集めた。彼はまた、アラビアの山々にあるアレクサンドリア、ヒルカニオン、マカエロスなど、適切な場所の周囲に城壁を築いた。

3\. しかしガビニウスは、マルクス・アントニウスを先に遣わし、全軍を率いて自らも従った。ただし、アンティパトロスの周囲の精鋭部隊と、マリコスとピトラオスの指揮下にあるユダヤ人部隊は、マルクス・アントニウスの周囲の指揮官たちと合流し、アレクサンダーと対峙した。ガビニウスはその後すぐに主力部隊を率いてその部隊に向かった。アレクサンダーは、合流した敵軍の突撃に耐えることができず、撤退した。しかし、エルサレムに近づくと、戦闘を強いられ、戦闘で6千人の兵士を失った。そのうち3千人が倒れ、3千人が生き残ったため、残りの兵士とともにアレクサンドリアに逃げた。

4\. さて、ガビニウスがアレクサンドリアに着くと、そこに多数の者が陣取っていたため、戦いになる前に彼らに以前の罪を赦すと約束して、彼らを説得しようとした。しかし、彼らが妥協の条件に耳を傾けなかったので、彼は彼らの多くを殺し、多くを城塞に閉じ込めた。彼らのリーダーであるマルクス・アントニウスは、この戦いで目覚ましい活躍を見せた。彼はいつも勇敢だったが、今回ほど勇敢さを見せたことはなかった。しかし、ガビニウスは城塞を奪取する軍隊を残して自ら出発し、破壊されなかった都市を定住させ、破壊された都市を再建した。したがって、彼の命令により、次の都市が復興された。スキトポリス、サマリア、アンテドン、アポロニア、ヤムニア、ラフィア、マリアッサ、アドロエウス、ガマラ、アシュドド、その他多数。すると、大勢の男たちが喜んでそれぞれの島に駆けつけ、そこの住民となった。

5\. ガビニウスはこれらの都市を制圧すると、アレクサンドリアに戻り、包囲を続けた。アレクサンドリアは政権獲得を諦め、使節を派遣して、アレクサンドリアを侮辱した罪を許すよう懇願し、後にアレクサンドリアをアレクサンドリアに引き渡す際に、残りの要塞であるヒルカニウムとマカエロスをガビニウスに引き渡した。アレクサンドリアの母の説得により、ガビニウスはこれらを全て破壊した。第二の戦争でガビニウスが収容所にされないようにするためである。母は、ローマで捕虜となった親族、つまり夫と他の子供たちを心配して、ガビニウスをなだめるためにそこにいた。その後、ガビニウスはヒルカニウムをエルサレムに連れて行き、神殿の維持を彼に委ねたが、その他の政治は貴族が行うことを定めた。彼はまた、国全体を5つの地域に分け、1つの地域をエルサレムに、別の地域をガダラに、別の地域をアマトスに、4番目をエリコに割り当て、5番目の地域にはガリラヤの都市セフォリスを割り当てました。こうして人々は君主制から解放されて喜び、今後はすべて貴族によって統治されることになりました。

6\. しかし、アリストブロスは新たな騒乱の根拠をもう一つ与えた。彼はローマから逃亡し、昔から彼に好意を抱いていた、変化を望むユダヤ人の多くを再び集めた。そして、最初にアレクサンドリアを占領したとき、彼はその周りに壁を築こうとした。しかし、ガビニウスがシスクリア、アントニウス、セルウィリウスの指揮する軍隊を彼に向けて送ると、彼はすぐにそれに気づき、マカエロスに撤退した。そして、役に立たない群衆については、彼は解散させ、武装した者だけを連れて進軍した。その数は8000人だった。その中には、エルサレムで副官を務めていたが、1000人の部下とともにアリストブロスに逃亡したピトラオスもいた。そのため、ローマ軍は彼に従い、戦闘になると、アリストブロスの部隊は長い間勇敢に戦った。しかし、ついに彼らはローマ軍に打ち負かされ、そのうちの五千人が倒れ、約二千人が小さな丘に逃げたが、アリストブロスと共に残った千人はローマ軍を突破し、マカエロスに進軍した。王は最初の夜をその廃墟に宿営した後、戦争がしばらく止むなら、別の軍隊を召集できると期待していた。したがって、彼はその要塞を強化したが、やり方は悪かった。しかし、ローマ軍が襲い掛かると、彼は二日間、自分の力を超えて抵抗したが、その後捕らえられ、ローマから一緒に逃げていた息子のアンティゴノスとともに、捕虜としてガビニウスのもとへ連れて行かれた。そして、ガビニウスのもとから、彼は再びローマへ連れて行かれた。そこで、元老院は彼を監禁したが、彼の子供たちをユダヤに返した。なぜなら、ガビニウスは手紙で、要塞を彼に引き渡す代わりに、アリストブロスの母親にそうすることを約束したと彼らに伝えたからである。

7\. ガビニウスがパルティア人との戦争に進軍していたとき、プトレマイオスの妨害を受けた。ガビニウスはユーフラテス川から戻るとプトレマイオスをエジプトに連れ戻し、ヒルカノスとアンティパトロスを利用してこの遠征に必要なすべてのものを用意させた。アンティパトロスは彼に金、武器、穀物、援軍を提供した。また、彼はそこにいたユダヤ人を説得し、ペルシウムの大通りを警備して彼らが通れるようにした。しかし、ガビニウスが不在の間、シリアの他の地域が動き出し、アリストブロスの息子アレクサンダーが再びユダヤ人を反乱させた。そこで彼は非常に大きな軍隊を集め、国内のローマ人全員を殺害し始めた。ガビニウスは恐れて（彼はすでにエジプトから戻っていたが、この騒動のために急いで戻らざるを得なかった）、アンティパトロスを派遣し、反乱者の一部を説得して静かにさせた。しかし、アレクサンダーのもとには三万人が残っており、アレクサンダー自身も戦う気満々だった。そこでガビニウスは戦いに出向いたが、ユダヤ人たちは彼と出会った。タボル山の近くで戦いが起こり、一万人が殺され、残りの群衆は散り散りになって逃げていった。そこでガビニウスはエルサレムに来て、アンティパトロスの望むとおりに政府を定め、そこから進軍してナバテア人と戦い、打ち負かした。パルティンから逃げたミトリダテスとオルサネスについては、密かに追い払ったが、兵士たちには逃げたと告げた。

8\. その間に、クラッススがガビニウスの後継者としてシリアにやって来た。彼はパルティア遠征の資金としてエルサレム神殿の残りの金貨をすべて奪った。またポンペイウスが触れなかった二千タラントも奪ったが、ユーフラテス川を渡ったとき、クラッスス自身も軍も共に滅んだ。この件については、今は語るにふさわしい時期ではない。

9\. しかし、カッシウスはクラッススに続いて、シリアに進軍していたパルティア軍を阻止した。カッシウスはその州に逃げ、そこを占領すると、急いでユダヤに進軍し、タリケアを占領すると、3万人のユダヤ人を奴隷にした。また、アリストブロスの反乱軍を支援していたピトラオスも殺害したが、そうするように助言したのはアンティパトロスであった。このアンティパトロスは、アラビソスの名門キュプロス家の妻を娶り、ファサイロスとヘロデ（後に王となった）の4人の息子をもうけた。さらに、ヨセフとフェロラスもいた。また、サロメという名の娘もいた。彼は、親切な奉仕と親切なもてなしによって、あらゆる場所で権力者たちと親交を深めた。アレクサンドロスは、その親戚と結婚することで、アラビア王と最大の友好関係を結んだ。そのため、アレクサンドロスがアリストブロスと戦争をしたとき、彼は子供たちを彼に託した。カッシウスがアレクサンドロスに和解と静穏を強いると、彼はパルティア人が再びそこを渡るのを防ぐためにユーフラテス川に戻った。この件については、別の機会に述べることにする。11

### 第9章

> アリストブロスはポンペイウスの友人によって連れ去られ、その息子アレクサンダーもスキピオによって連れ去られた。アンティパトロスはポンペイウスの死後、カエサルとの友情を育み、その戦争でもミトリダテスを支援して大きな功績を挙げた。

1\. さて、ポンペイウスと元老院がイオニア海を越えて逃亡すると、カエサルはローマと帝国を支配下に置き、アリストブロスを解放した。また、彼に2個軍団を委ね、急いでシリアに送り込んだ。彼ならシリアとユダヤに隣接する地域を容易に征服できると期待したからである。しかし、嫉妬がアリストブロスの敏捷性とカエサルの期待を妨げた。ポンペイウスの党員が毒を盛って殺したためである。そして、長い間、彼は自分の国で埋葬されることさえなく、彼の死体は蜂蜜に保存されたまま地上に横たわっていたが、アントニウスによってユダヤ人に送られ、王家の墓に埋葬された。

2\. 彼の息子アレクサンドロスも、アンティオキアでスキピオに斬首されたが、これはポンペイウスの命令によるもので、ローマ人に対して行った悪事の罪で法廷に告発された。しかし、当時レバノスの下でカルキスの支配者であったメネウスの息子プトレマイオスは、息子フィリッピオをアスカロンに送り、兄弟たちを彼のもとに連れて行った。アスカロンはアンティゴノスとその姉妹たちをアリストブロスの妻から引き離し、父親のもとに連れて帰った。そして、アンティゴノスは妹に恋をして結婚したが、後に彼女のせいで父親に殺された。プトレマイオス自身も息子を殺した後、アレクサンドラという名の彼女と結婚し、その結婚のおかげで、彼は彼女の兄妹をより大切に扱うようになった。

3\. さて、ポンペイウスが死んだ後、アンティパトロスは寝返り、カエサルとの友好関係を育んだ。ペルガモスのミトリダテスは、エジプトに対抗する軍勢を率いてペルシウム周辺の街道から締め出され、アセアロンに留まらざるを得なくなったので、かつて暮らしていたアラビア人たちに助力を説き、自らも三千人の武装兵を率いてカエサルのもとに赴いた。また、シリアの有力者たち、またリバノス、プトレマイオス、ヤンブリコス、そしてもう一人のプトレマイオスの住民たちにも助力を促した。こうして、その国の都市は喜んでこの戦争に参戦した。そのため、ミトリダテスは、アンティパトロスから得たさらなる力を頼りに、ペルシウムに進軍することを敢えてした。そして、彼らが通行を拒否すると、彼はその都市を包囲した。この場所への攻撃でアンティパトロスは特に目立った。彼は向かい側の城壁の一部を崩し、周囲の兵士たちとともに真っ先に市内に飛び込んだのである。

4\. こうしてペルシウムは陥落した。しかし、彼らが進軍を続けると、オニアスの国と呼ばれる地域に住むエジプトのユダヤ人たちが彼らを阻止した。そこでアンティパテルは彼らを阻止しないよう説得しただけでなく、彼らの軍隊に食料を与えるよう説得した。そのため、メンフィス周辺の人々でさえ彼らと戦わず、自ら進んでミトリダテスに加わった。そこで彼はデルタを回り、ユダヤ人の陣営と呼ばれる場所で残りのエジプト人と戦った。いや、右翼のすべてが戦いで危険にさらされたとき、アンティパテルは方向転換し、川岸に沿って彼のところまで来た。なぜなら、彼は左翼を率いて彼に反対する者たちを打ち負かしていたからである。この勝利の後、彼はミトリダテスを追撃していた者たちを襲撃し、その大部分を殺し、残りの者たちを追撃して彼らの陣営を奪取したが、自分の部下のうち失ったのはせいぜい80人であった。ミトリダテスは追撃の間に約800人の兵士を失った。彼自身も予想外に助かり、アンティパトロスの偉大な行為についてシーザーに非の打ちどころのない証人となった。

5\. そこでカエサルは、アンティパトロスに他の危険な計画を遂行するよう奨励し、そのために彼に大きな賞賛と報酬の希望を与えた。そのすべての計画において、彼は多くの危険に身をさらし、最も勇敢な戦士となった。そして、彼の勇敢さの証拠として、彼の体中に多くの傷があった。そしてカエサルはエジプトの問題を解決し、再びシリアに戻るとき、彼にローマ市民の特権と免税を与え、彼に名誉と友情の印を与えて彼を賞賛の対象にした。このため、彼はヒルカノスを大祭司に任命した。

### 第10章

> シーザーはアンティパトロスをユダヤの総督に任命し、同様にファサエロスをエルサレムの総督に、ヘロデをガリラヤの総督に任命した。しばらくしてヘロデは \[サンヘドリンの前で\]自ら釈明するよう求められ、無罪となった。セクストゥス・シーザーはバッソスによって裏切り殺され、マルクスが後を継いだ。

1\. この頃、アリストブロスの息子アンティゴノスがカエサルのもとにやって来て、驚くべき形でアンティパトロスのさらなる昇進のきっかけとなった。というのは、アンティパトロスは、父がポンペイウスとの争いのために毒殺されたらしいことを嘆き、スキピオの兄に対する蛮行を訴え、恩赦を請う際に敵意を混ぜるべきではなかったのに、カエサルの前に出て、ヒルカノスとアンティパトロスが彼とその兄弟たちを故郷から完全に追い出し、彼らの国に関して多くの例で不当かつ法外な行動をとったことを非難した。また、彼らが彼をエジプトに送り込んだ援助については、それは彼に対する善意からではなく、以前の争いから彼らが抱いていた恐れから、そして\[敵\]ポンペイウスとの友情に対する許しを得るために行われたものであった。

2\. そこでアンティパトロスは上着を脱ぎ捨て、自分の受けた傷の数々を見せ、カエサルに対する好意については、自分自身は何も言わなかったが、体が悲鳴を上げていたため、一言も言う必要がなかった、アンティゴノス自身もローマ人の敵であり逃亡者の息子であり、父から受け継いだ革新と反乱を好む性格でありながら、ローマ総督の前で他人を告発し、自分が生き長らえていることに満足すべきときに、自分に利益をもたらそうとするアンティゴノスの大胆さに驚いた、と言った。というのは、彼が公務を統括したいと望んだ理由は、それを必要としていたからというよりも、もし彼がそれを手にすることができれば、ユダヤ人の間に反乱を起こさせ、ローマ人から得たものを、彼にそれを与えた人々に不利益となるように利用するかもしれないからであった。

3\. カエサルはこれを聞くと、ヒルカノスを最高神官に最もふさわしい者と宣言し、アンティパトロスに望む権威を選ぶ許可を与えた。しかし、その権威の決定は、その権威を授けた者に委ねた。こうしてヒルカノスはユダヤ全土の行政長官に任命され、さらに、破壊された国の城壁を再建する許可を得た。カエサルは、これらの名誉ある許可をカピトリオンに刻ませるように命令し、それがカエサル自身の正義とアンティパトロスの美徳の証としてそこに立つようにした。

4\. しかし、アンティパトロスはカエサルをシリアから連れ出すとすぐにユダヤに戻り、まずポンペイウスが倒した自国\[エルサレム\]の城壁を再建し、次に国中を巡って、そこにある騒乱を鎮めようとした。そこで彼は、すべての人々を半ば脅し、半ば忠告し、ヒルカノスに服従すれば、幸福で平和に暮らし、所有物を享受し、しかも全世界が平和で平穏であると告げた。しかし、利得を得るために新たな問題を起こして冷淡な希望を抱いている者たちの言うことを聞いてしまうと、ヒルカノスは総督ではなく領主となり、ヒルカノスは王ではなく暴君となり、ローマ人もカエサルも支配者ではなく敵となるだろうと告げた。なぜなら、彼らはヒルカノスを総督に任命したのだから、彼を政府から排除することを許さなかったからである。そして、こう言うと同時に、彼はヒルカノスが無気力で、王国の事柄を管理するのに適さないと見て、自ら国の事柄を解決した。そこで彼は長男のファサエロスをエルサレムとその周辺の地域の総督に任命し、また、非常に幼かった次男のヘロデを同等の権限をもってガリラヤに派遣した。

5\. ヘロデは活動的な人物であり、すぐにその活動的な精神を働かせるのにふさわしい材料を見つけた。盗賊の首領ヒゼキヤが大勢の男たちを率いてシリアの近隣地域を襲撃しているのを知ったヘロデは、ヒゼキヤを捕らえて殺し、さらに他の多くの盗賊たちも殺した。この功績はシリア人にとって特に喜ばしいものであったため、ヘロデは村々や都市で、ヒゼキヤがシリアの平穏を守り、所有物を守ったことを称えて賛美歌を歌った。このとき、ヘロデは偉大な皇帝の親族でシリアの大統領であったセクストゥス・シーザーと知り合いになった。彼の輝かしい行動に正当な見習いたいという気持ちから、ファサイロスも彼に倣うようになった。したがって、彼は自ら市の事務を管理することでエルサレムの住民の好意を獲得し、いかなる不愉快な方法でも権力を乱用しなかった。それによって、国民はアンティパトロスに王にのみ与えられるべき敬意を払い、国民全員が彼に与えた名誉は絶対君主に与えられるべき名誉と同等であった。しかし、アンティパトロスはヒルカノスに対する善意や忠誠心を少しも減らさなかった。

6\. しかし、彼はその繁栄の中で嫉妬から逃れることは不可能だと分かった。というのは、これらの若者たちの名声は、ヒルカノス自身にも内心では影響を与えていたが、ヒルカノスは誰にもそのことを言わなかった。しかし、彼が主に悲しんでいたのは、ヘロデの偉大な行為と、多くの使者が次々にやって来て、彼があらゆる事業で得た大きな評判を彼に伝えたことであった。また、王宮自体にも、彼に対する嫉妬をかき立てる多くの人々がいた。つまり、若者たちかアンティパトロスの慎重さによって計画が妨げられた人々である。これらの人々は、アンティパトロスとその息子たちに公務を委ねることで、彼は王の名だけを持ち、その権威を全く持たずに座についた、と言った。そして、自分の利益に反して王を育てるという誤った行動をいつまで続けるのかと彼に尋ねた。というのは、彼らはもはや政務を隠すことはなく、明らかに国の君主となり、彼を権威から追放したからである。ヘロデが口述や手紙で命令することなく、ユダヤ人の法律に反して、あれほど多くの者を殺したときもそうであった。したがって、彼が王ではなく私人であったとしても、ユダヤ人は裁判に臨み、彼に答えるべきであり、また、裁判で有罪判決が下されるまでは誰も殺されないという彼の国の法律にも従うべきである。

7\. ヒルカノスは、次第にこれらの説教に激怒し、ついには耐えられなくなり、裁判を受けるためにヘロデを召喚した。そこで、父の助言に従い、ガリラヤの状況が許すとすぐに、彼はガリラヤに駐屯軍を置いた後、エルサレムに上陸した。しかし、彼は十分な兵士を率いて来た。確かに、ヒルカノスの政府を打倒できるほどの軍隊を持っているようには見えないほどの人数であったが、嫉妬する者たちの侮辱を受けるほどの人数ではなかった。しかし、セクストゥス・カエサルは、若者が敵に捕らえられ、処罰されるのではないかと恐れた。そこで、ヒルカノスに、死刑の告発を無罪にするよう、何人かを差し向けた。ヒルカノスは、自分も死刑に処する気だったから、死刑に処する気だったとして、彼を無罪とした。

8\. しかしヘロデは、王の同意なしに処罰を逃れたと思い、セクストゥス、ダマスカスに退き、再び召喚されても従わないよう、あらゆる準備を整えた。すると、悪意ある者たちがヒルカノスを怒らせ、ヘロデは怒って出て行き、自分と戦う用意をしていると告げた。王は彼らの言うことを信じたが、敵が自分より強いのを見て、どうしたらよいか分からなかった。そして今、ヘロデはセクストゥス・カエサルによってコエレシリアとサマリアの将軍に任命されたので、国民の好意だけでなく、彼自身の力によっても恐るべき存在となった。そのためヒルカノスは極度の恐怖に陥り、彼がすぐに軍隊を率いて自分に向かって進軍してくるだろうと予想した。

9\. 彼の推測は間違っていなかった。なぜなら、ヘロデは、ヒルカノスが公の法廷で告発して脅したことに対する怒りから、軍隊を召集し、エルサレムに進軍してヒルカノスを王国から追放しようとしたからである。そして、父と兄が一緒に出かけてヒルカノスの怒りの勢いを弱めなければ、彼はすぐにそれを成し遂げた。その怒りの強さは、脅迫と恐怖以上の復讐はせず、彼が権力を握っていた王を赦すようにと彼に説き伏せたことによる。また、裁判にかけられたことに腹を立てるあまり、無罪放免になったことへの感謝を忘れるべきではないし、憂鬱なことについて長く考えすぎて、救出されたことへの感謝を忘れるべきではないとも説き伏せたことによる。そして、もし私たちが、戦争の勝敗の裁定者は神であるとみなすべきであるならば、不当な理由は軍隊が有利になるよりも不利になる。そして、それゆえ、ヘロデは、自分の王、自分の支持者、そしてしばしば自分の恩人であり、自分に対して決して厳しくなかった者、つまり、邪悪な助言者たちの言うことに耳を傾けたのと同程度、そして不正の影を自分にもたらしただけである者と戦う場合、勝利を確信しきれないはずだ、と。こうしてヘロデはこれらの議論に説得され、自分がすでに行ったことは将来の希望には十分であり、国民に自分の力を十分に示せたと考えた。

10\. その間に、アパミアをめぐってローマ人の間で騒乱が起こり、ポンペイウスへの好意からセクストゥス・カエサルを裏切り殺害したケシリウス・バッススが内戦を起こした。バッススはポンペイウスの軍隊の指揮権も握った。しかし、カエサルの残りの指揮官たちがカエサル殺害の罰としてバッススを全軍で攻撃したため、アンティパトロスもまた、殺害されたバッススとまだ生きていたカエサルの友人である息子たちを派遣して彼らに援助を求めた。この戦争が長引くと、セクストゥスの後継者としてマルクスがイタリアからやって来た。

### 第11章

> ヘロデはシリア全土の総督に任命され、マリコスは 彼を恐れてアンティパトロスを毒殺した。そこで兵士の護民官たちは彼を殺すよう説得された。

1\. 当時、ローマ人の間では、カエサルが3年7ヶ月間政権を握っていたのに、カッシウスとブルートゥスがカエサルを突然裏切り殺害したことで、激しい戦争が勃発していた。14この殺害により、非常に大きな動揺が起こり、有力者たちは互いに激しく対立し、誰もが自分たちが前進するために最も希望を抱いている党派に味方した。そこでカッシウスは、アパミアの軍勢を受け入れるためにシリアに赴き、そこでバッススとマルクス、そして彼と対立していた軍団との和解を実現した。そこで彼はアパミアの包囲を解き、軍の指揮を執り、都市から貢物を徴収し、彼らが耐えられないほどの金銭を要求した。

2\. そこで彼はユダヤ人に七百タラントを納めるように命じた。そこでアンティパトロスはカッシウスの脅しを恐れて、この金額を集めるのを息子たちや知り合いの人たちに分担させ、すぐにやらせた。その中で彼は、自分と敵対していたマリコスという人物にも、必要に迫られて自分の分もやるように要求した。さて、ヘロデはまず第一に、カッシウスの怒りを和らげるために、ガリラヤから百タラントの自分の分を持ってきて、カッシウスに大いに気に入られた。そして、残りの者たちが遅れていると非難すると、町々自体に怒りを覚えた。そこで彼はゴフナとエマオ、および他の二人のあまり有名でない者たちを奴隷にした。それどころか、マリコスがもっと急いで貢物を徴収しなかったからと、まるでマリコスを殺すかのように事を進めた。しかしアンティパトロスは、この男と他の都市の破滅を防ぎ、すぐに100タラントを持ち込んでカッシウスの好意を得た。15

3\. しかし、カッシウスが去ると、マリコスはアンティパトロスが自分にしてくれた親切を忘れ、自分の邪悪な行いの邪魔者だったマリコスを急いで追い払おうと、自分を救ってくれたアンティパトロスに対して度々陰謀を企てた。しかし、アンティパトロスはマリコスの権力と狡猾さを非常に恐れ、彼の裏切りの計画から身を守るために軍隊を編成するためにヨルダン川を越えて行った。しかし、マリコスが陰謀に巻き込まれると、彼は厚かましさでアンティパトロスの息子たちを苦しめた。なぜなら、彼はエルサレムの守護者であったファサイロスと、戦争の武器を託されていたヘロデを、多くの言い訳と誓いによって完全に欺き、父との和解を成立させるよう説得したからである。こうして、彼は再びアンティパトロスによって守られ、シリアの当時の総督マルクスは、マリコスが革新を企てたためにマリコスを殺害する決意を思いとどまった。

4\. カッシウスとブルートゥスが、他方で若いカエサル（アウグストゥス）とアントニウスと戦ったとき、カッシウスとマルクスはシリアから軍隊を集めた。ヘロデは必需品の調達に大いに貢献しそうだったので、彼らは彼をシリア全土の総督に任命し、歩兵と騎兵の軍隊を与えた。カッシウスはまた、戦争が終わったら彼をユダヤの王にすると約束した。しかし、息子の権力と希望が彼の破滅の原因となった。マリコスはこれを恐れ、アンティパトロスに毒入りの薬を与えるために、金銭で王の酌官の一人を堕落させた。こうして、マリコスはマリコスの悪行の犠牲となり、宴会で死んだ。彼は他の点では政務に積極的で、ヒルカノスに政権を取り戻し、それを彼の手に保持した人物であった。

5\. しかし、マリコスは、アンティパトロスを毒殺した疑いをかけられ、群衆が彼に怒りをぶつけたとき、それを否定し、人々に自分が無罪であると信じさせた。彼はまた、もっと大きな存在になろうと準備し、兵士を募った。なぜなら、彼は、ヘロデが父の死を復讐するために軍隊を率いてすぐにマリコスに襲い掛かってきたので、彼が黙っているとは思わなかったからである。しかし、群衆が暴動を起こす恐れがあるので、公然とマリコスを処罰しないようにという兄弟ファサイロスの助言を聞いて、マリコスはマリコスの謝罪を認め、その疑いを晴らしたと公言し、また、父親のために盛大な葬儀を行った。

6\. そこでヘロデは、当時騒乱状態にあったサマリアに行き、その町を平和に治め、その後、ペンテコステ祭の日に武装した部下を連れてエルサレムに戻った。そこでヒルカノスは、非難を恐れたマリコスの要請により、部下が身を清めている間、外国人を国に招き入れて混じり合うことを禁じた。しかしヘロデはその口実と、その命令を下した者を軽蔑し、夜中にやって来た。そこでマリコスがやって来てアンティパテルの死を嘆いた。ヘロデもまたマリコスを信じ込ませたが（彼はマリコスの嘆きを真実であると認めた）、彼に対する怒りを抑えるのに苦労した。しかし、彼自身もカッシウスに宛てた手紙の中で父の殺害を嘆いた。カッシウスもまた、他の理由でマリコスを憎んでいた。カッシウスはヘロデに父の死の復讐をするよう言い、部下の護民官たちにはヘロデが行っている正義の行為に協力するよう密かに命令した。

7\. カッシウスがラオデキアを占領すると、権力者たちが贈り物や王冠を手に、四方八方から集まってきたので、ヘロデはマリコスを処罰するためにこの時間を割いた。マリコスはそれを察知してティルスにいたとき、人質にしていた息子をティルス人の中からひそかに引き離し、自分はユダヤに逃げる準備をしようと決心した。逃げ切れないという絶望感から、もっと大きなことを考えるようになった。カッシウスがアントニウスとの戦争に忙しい間に、国をローマ人に対する反乱へと駆り立て、ヒルカノスを簡単に退位させて王冠を手に入れようと考えたからである。

8\. しかし運命は彼の望みをあざ笑った。ヘロデは彼が熱心になっていることを見抜いて、ヒルカノスと彼を夕食に招いた。しかし、彼の傍らにいた主立った召使の一人を呼び出して、夕食の準備をさせるかのように彼を送り出したが、実際には彼に対して企てられた陰謀を事前に知らせるためであった。そこで彼らはカッシウスが彼らに与えた命令を思い出し、剣を手に町から出て海岸に向かい、マリコスを四方から取り囲み、多くの傷を負わせて殺した。ヒルカノスはすぐに驚いて気を失い、驚いたために倒れた。マリコスを殺したのは誰かと尋ねた時、彼はやっと意識を取り戻した。そして護民官の一人が、それはカッシウスの命令によるものだと答えると、彼は「それでは」と言った。「カッシウスは、私と祖国の両方を、彼らに対して陰謀を企てていた者を断ち切ることで救ってくれたのだ」。彼が自分の感情に従って言ったのか、それとも恐れが大きかったためにそう言ってその行動を賞賛せざるを得なかったのかは定かではないが、この方法でヘロデはマリコスに罰を与えた。

### 第12章

> ファサイロスはフェリクスにとって手ごわすぎた。ヘロデもまた、ラトルでアンティゴノスを打ち負かした。ユダヤ人はヘロデとファサイロスの両者を告発したが、アントニウスは彼らを無罪とし、四分領主とした。

1\. カッシウスがシリアから去った後、エルサレムでまた暴動が起こり、フェリクスは軍隊を率いてファサイロスを襲撃した。ヘロデにマリコスの死の復讐をするために、彼の兄弟を襲おうとしたのである。ヘロデはちょうどその時、ダマスカスの総督ファビウスと一緒にいて、兄の助けに行く途中、病気で足止めされた。その間、ファサイロスはフェリクスに厳しく接し、マリコスを助けたことと、マリコスの兄弟が要塞を占領した際に見落としたことの両方について、ヒルカノスの恩知らずを非難した。ヒルカノスはすでに多くの要塞を占領しており、その中で最も強固だったマサダも占領していたからである。

2\. しかし、ヘロデの力に対抗できるものは何もなかった。ヘロデは回復するとすぐに他の要塞を再び奪い、嘆願者の姿勢で彼をマサダから追い出した。また、すでに3つの要塞を占領していたティルスの暴君マリオンをガリラヤから追い出した。しかし、捕らえたティルス人については、全員生かしておいた。それどころか、何人かに贈り物をして追い払い、それによって町から好意を勝ち取り、暴君に憎しみを抱かせた。マリオンは、シリア全土に暴君を置いたカッシウスの暴君的権力を確かに得ており 、ヘロデへの憎しみから、アリストブロスの息子アンティゴノスを助けたが、それは主にファビウスのおかげであった。アンティゴノスは金銭でファビウスを助手にし、彼が下ったときには彼を味方につけていた。しかし、彼が必要とするものをすべて供給したのは、アンティゴノスの親族であるプトレマイオスだった。

3\. ヘロデはユダヤの街路でこれらの者たちと戦って勝利し、アンティゴノスを追い払ってエルサレムに帰った。彼はその輝かしい行動により、すべての人から愛されていた。以前は彼に好意を寄せていなかった人々も、彼がヒルカノス家と結婚したことにより、彼に加わったのである。彼は以前、自分の国から、ドリスという名の、高貴な血筋の妻を娶り、彼女からアンティパトロスをもうけたのと同様に、今度は、アリストブロスの息子でヒルカノスの孫娘であるアレクサンダーの娘であるマリアムネと結婚し、それによって王の血縁者となったのである。

4\. しかし、カエサルとアントニーがフィリッピ近郊でカッシウスを殺害し、カエサルがイタリアへ、アントニーがアジアへ、そしてビテュニアのアントニーに大使を送った他の都市へ行ったとき、ユダヤ人の有力者たちもやって来て、ファサイロスとヘロデを、彼らが力ずくで政権を維持しており、ヒルカノスは名誉ある名声以上のものを持っていないと非難した。ヘロデはこの非難に答える用意があるように見え、多額の金銭を与えてアントニーを友人にし、アントニーを怒らせて、他の人々が彼に反対するのを聞かないようにした。こうして彼らはこのとき別れた。

5\. しかし、その後、ユダヤ人の主だった人物百人が、アンティオキアを通ってダフネにやって来た。アントニーは、すでにクレオパトラに奴隷の身分になるほど恋をしていた。これらのユダヤ人は、威厳と雄弁さの両方で最も有力な人物を前面に押し出し、兄弟たちを非難した。17 しかしメッサラは彼らに反対し、兄弟たちを擁護し、ヒルカノスは彼らとの関係を理由に彼の側に立った。アントニーは両方の言い分を聞いた後、ヒルカノスにどちらの党派が統治に最も適しているか尋ねた。ヒルカノスは、ヘロデとその党派が最も適していると答えた。アントニーはその答えに喜んだ。なぜなら、以前ガビニウスと共にユダヤに進軍したとき、父アンティパトロスから親切で親切なもてなしを受けたからである。そこで彼は兄弟たちを四分領主とし、ユダヤの統治を彼らに委ねた。

6\. しかし、使節たちがこのやり方に憤慨すると、アントニーは彼らのうち15人を捕らえて拘留し、すぐに殺すつもりで、残りの者も追い払った。このときエルサレムでさらに大きな騒動が起こった。そこで彼らは、エルサレムへ向かう途中のアントニーが滞在していたティルスに、再び1000人の使節を派遣した。騒ぎを起こしたこれらの人々に対して、アントニーはティルスの総督を派遣し、捕まえられる者全員を処罰し、四分領主とした者たちを行政に定着させるよう命じた。

7\. しかし、その前にヘロデとヒルカノスは海岸に出て、これらの使節たちに、軽率な争いで自らを破滅させたり、祖国に戦争をもたらさないように熱心に頼んだ。彼らがさらに暴虐を極めると、アントニーは武装した兵士たちを派遣し、大勢の人々を殺し、さらに負傷させた。殺された者たちはヒルカノスによって埋葬され、負傷者は医師の手当てを受けた。しかし、逃げ延びた者たちは静かにしていたわけではなく、むしろ町の情勢を混乱に陥れたため、アントニーは激怒し、拘束していた者たちも殺した。

### 第13章

> パルティア人はアンティゴノスをユダヤに連れ戻し、ヒルカノスとファサエロスを投獄した。ヘロデの逃亡、エルサレムの占領、そしてヒルカノスとファサエロスの苦難。

1\. それから二年後、パルティア人の総督バルザファルネスと王の息子パエオルスがシリアを占領し、リサニアスが父プトレマイオス（メネウスの息子）の死後、カルキスの統治権を継承していたとき、彼は総督を説得し、千タラントと五百人の女性を約束してアンティゴノスを王国に連れ戻し、ヒルカノスを王国から追い出した。パコルスはこれらの手段で説得され、海岸に沿って行軍し、地中海沿いにユダヤ人を襲うようバルザファルネスに命じた。しかし、海辺の民のうち、ティルス人はパコルスを受け入れなかったが、プトレマイオスとシドンの人々は彼を受け入れた。そこで彼は、自分の馬の一隊を、王家の、彼自身の名を持つある酌官\[パコルス\]に託し、ユダヤに進軍して敵の情勢を調べ、アンティゴノスが援助を必要とするときに助けるよう命令した。

2\. これらの人々がカルメル山を荒らしていたとき、多くのユダヤ人がアンティゴノスのもとに駆けつけ、この地への侵攻の用意を見せた。そこで彼は彼らをドライモスと呼ばれる場所（森18 ）に先に送り、その場所を占領させた。そこで彼らの間で戦いが起こり、彼らは敵を追い払い、追撃してエルサレムまで追いかけ、人数が増えて王宮まで進んだ。しかしヒルカノスとファサイロスが強力な部隊を率いて彼らを迎え撃つと、広場で戦いが起こり、ヘロデの党は敵を打ち負かし、神殿に閉じ込め、隣接する家に60人の男を警備兵として配置した。しかし兄弟たちに対して騒ぎを起こしていた民衆が押し寄せ、その男たちを焼き殺した。一方、ヘロデは、彼らを殺したことに激怒し、民衆の多くを襲撃して殺害した。その結果、一方が待ち伏せして毎日交互に他方を襲撃し、民衆の間で虐殺が絶え間なく行われた。

3\. さて、ペンテコステと呼ばれる祭りが近づいたとき、神殿の周りのすべての場所と町全体が、田舎から出てきた大勢の人々でいっぱいでした。彼らの大部分は武装していました。そのとき、ファサイロスは城壁を守り、ヘロデは少数の兵士とともに王宮を守っていました。そして、町の北側で戦列を乱していた敵を襲撃し、非常に多くの敵を殺し、全員を敗走させました。そして、そのうちの何人かを町の中に閉じ込め、他の何人かを外側の城壁の中に閉じ込めました。その間、アンティゴノスは、パコルスが彼らの間の調停者になることを望みました。そして、ファサイロスは、騒乱を鎮めるために来たと見せかけて、実際にはアンティゴノスを助けるために来たパルティア人を、500騎の騎兵とともに町に入れ、手厚くもてなすように説得されました。しかし、彼はファサイロスに陰謀を企て、戦争を終わらせるためにバルザファルネスに使節として行くよう説得した。ヘロデはそれに反対し、陰謀者を殺すよう勧めたが、野蛮人は生来不誠実なので、彼が仕掛けた罠にはかからないようにした。しかし、パコルスは出かけて行き、疑われないようにヒルカノスを連れて行った。また、自由人と呼ばれる騎兵の何人かをヘロデに残し、ファサイロスを残りの者たちと一緒に導いた。

4\. ところが、ガリラヤに着くと、その地方の民衆が反乱を起こし、武装していたことが分かり、彼らは非常に巧妙に指導者のもとにやって来て、自分たちへの親切な態度で裏切りの意図を隠すように懇願した。そこで指導者はまず贈り物をし、その後、彼らが立ち去るときに待ち伏せをした。そして、エクディポンと呼ばれる海沿いの都市の一つに着くと、彼らは陰謀が企てられていることに気づいた。そこで彼らは、千タラントの約束と、アンティゴノスが彼らと一緒にいた五百人の女性のうち最も多くの女性をパルティア人に捧げたことを知らされたからである。また、夜間に蛮族が常に待ち伏せしていることも知った。彼らは、エルサレムでヘロデが最初に捕らえられるのを待っていなければ、この前にも捕らえられていた。なぜなら、ヘロデが彼らのこの裏切りを一度でも知らされれば、彼は自分の身を守るだろうからである。これは単なる報告ではなく、彼らはすでに警備員がそれほど遠くないところにいたのを目撃した。

5\. ファサイロスは、オフェリウスが熱心に説得したにもかかわらず、ヒルカノスを見捨てて逃げ去ろうとは考えなかった。なぜなら、この男は、シリア人の中で最も裕福なサラマッラから陰謀の全容を聞き出していたからである。しかし、ファサイロスはパルフィリア総督のもとへ行き、この裏切りの陰謀を企てたこと、そして主に金銭目的でやったことを面と向かって非難した。そして、アンティゴノスが王国のために約束した以上の金銭を、彼らを守るために与えると約束した。しかし、この狡猾なパルティア人は、謝罪と誓いによってこの疑惑をすべて払拭しようと努め、それからパコルスのもとへ向かった。その直後、残って指揮権を握っていたパルティア人たちは、ファサイロスとヒルカノスを捕らえたが、彼らは彼らの不誠実さと偽証を呪うことしかできなかった。

6\. その間に、献酌官が送り返され、ヘロデを騙して町から連れ出し、命令通りに捕らえる計画を立てた。しかしヘロデは最初から蛮族を疑っていた。そして、裏切りの計画を知らせる手紙を届ける使者が敵に捕まったという知らせを受けて、町から出ようとしなかった。パコルスは、手紙を届けた使者に会いに行くべきだと強く主張した。手紙は敵に盗まれておらず、内容は陰謀ではなくファサエロスの仕業であると。しかし、他の人から弟が捕らえられたと聞いていた。そして、世界で最も聡明な女性であり、ヒルカノスの娘である アレクサンドラ20 は、彼に、外出しないでほしい、そして今や公然と彼を攻撃しに来た野蛮人たちに身を委ねないようにと懇願した。

7\. パコルスとその友人たちは、いかにして秘密裏に計画を実行に移すかを検討していた。これほどの慎重さを持つ男を公然と攻撃してかわすのは不可能だったからである。そこでヘロデは彼らを阻止し、敵に知られることなく、夜中に最も近しい人々と出発した。しかし、パルティア人はそれを知るや否や彼らを追跡した。彼は母と妹、婚約中の若い女性とその母親、そして末の弟に、最善を尽くすように命じ、自分は家来たちとともに、蛮族を寄せ付けないように全力を尽くした。そして襲撃のたびに、多数の蛮族を殺し、マサダの要塞にたどり着いた。

8\. いや、彼は経験から、パルティア人よりもユダヤ人が彼に激しく攻撃し、絶えず彼を悩ませていることを知った。これは彼が町から60スタディオン離れたときからずっと続いていた。このため、町は時々、ある種の定期的な戦闘に発展した。さて、ヘロデがユダヤ人を打ち負かし、その多くを殺した場所に、彼は後に、そこで行った偉大な行為を記念して城塞を建設し、最も高価な宮殿でそれを飾り、非常に強力な要塞を建て、自分の名前にちなんでヘロディウムと名付けた。さて、彼らが逃げている間、毎日多くの人が彼に加わった。そして、イドマヤのトレサと呼ばれる場所で、彼の兄弟ヨセフが彼に会い、マサダは9000人以上のそのような大群を収容できないので、彼の多くの追随者を休ませるよう彼に勧めた。ヘロデはこの助言に従い、従者のうち最も重荷となる部分をイドマヤへ行かせて旅の糧食を与えた。しかし、彼は近親者と共に無事に要塞にたどり着き、従者のうち最も勇敢な者だけを残した。そして、そこに女性たちの護衛として部下 800 人と包囲戦に十分な糧食を残し、自らはアラビアのペトラへと急いだ。

9\. エルサレムのパルティア人は略奪に明け暮れ、逃げた人々の家や王宮を襲撃し、ヒルカノスの金だけは惜しまず奪った。その金は三百タラントを越えなかった。彼らは他の人々の金も奪ったが、期待したほどではなかった。ヘロデは長い間蛮族の不誠実さを疑っていたので、彼の財宝の中でも最も豪華なものをイドマヤに移送するように気を配っていたし、彼の家臣たちも皆同じようにしていた。しかしパルティア人は、国中を戦争で満たしながらもそれを非難せず、マリッサの町を破壊し、アンティゴノスを王に据えただけでなく、ファサイロスとヒルカノスを縛って彼の手に引き渡し、アンティゴノスに苦しめようとした。アンティゴノス自身も、ヒルカノスにひざまずいて彼の耳を自分の歯で噛み切った。それは、いかなる状況の変化があっても、彼が二度と大祭司の地位に就くことができないようにするためであった。なぜなら、職務を遂行する大祭司は完全で、傷のない者でなければならなかったからである。

10\. しかし、彼は勇気のせいでファサイロスを虐待する目的を果たせなかった。剣も手も使いこなせなかったが、石に頭をぶつけて虐待をすべて防いだ。こうして彼はヘロデの実の兄弟であり、ヒルカノスが最も堕落した親戚であることを示し、非常に勇敢に死に、その行動にふさわしい人生の終わりを迎えた。また、彼の最期については別の報告もある。すなわち、彼はその脳卒中から回復し、アンティゴノスが彼を治療するために派遣した外科医が傷口に毒物を詰めて彼を殺したという。彼がどの死に方をしたにせよ、その始まりは輝かしいものだった。また、彼が息を引き取る前に、ある貧しい女性からヘロデが彼らの手から逃れたことを知らされ、そのとき彼は「私は今、安らかに死にます。私の敵に復讐してくれる一人を生き残らせたからです」と言ったと伝えられている。

11\. これがファサエロスの死であった。しかしパルティア人は、彼らが最も望んでいた女性たちを逃したにもかかわらず、エルサレムの統治権をアンティゴノスの手に委ね、ヒルカノスを捕らえて縛り、パルティアに連行した。

### 第14章

> ヘロデはアラビアで拒絶されると、急いでローマに行き、そこでアントニーとシーザーが協力して彼を王にしようとします。

1\. さて、ヘロデは、兄がまだ生きている間に、王から金を急いで手に入れようと、アラビアへの旅をますます熱心に続けた。その金だけによって、彼は野蛮人の強欲な気質を説得して、ファサイロスを助けようとした。なぜなら、彼はこう考えていたからだ。アラビアの王が父の友情を忘れ、強欲で彼に無償の贈り物をしてくれないとしても、兄を救い出すのに十分な金を彼から借り、救い出すべき彼の息子を質物として彼の手に渡すだろう。そこで、彼は兄の息子、7歳になる息子を連れて行った。今や彼は兄のために300タラントを与える用意ができており、それを受け入れてもらうためにティルス人のとりなしを願うつもりだった。しかし、運命は彼の勤勉さをはるかに超え、ファサイロスが死んだので、ヘロデの兄弟愛は今や無駄になった。さらに、彼はアラビア人の間に永続的な友情を見出すことができなかった。彼らの王マリコスはすぐに彼のもとに使者を送り、国外へ戻るよう命じ、パルティア人の名を口実に、あたかも彼らが使節を通してヘロデをアラビアから追放するよう彼に告発したかのようにした。しかし実際には、彼らはアンティパトロスに借りがあるものを隠しておき、父親が息子たちに与えた無償の贈り物に対する返礼をしたくないと考えていた。彼はまた、自分と同様にアンティパトロスが彼らの間に預けたものをヘロデから奪おうとする人々の厚かましい助言を受け入れた。そしてこれらの人々は彼の王国にいたすべての人々の中で最も有力であった。

2\. ヘロデは、アラビア人が敵であり、彼らが最も友好的であると期待していたまさにその理由から敵であると知り、自分の情熱が示唆するような返答を彼らに与えたので、引き返してエジプトに向かった。さて、彼は最初の晩、後に残してきた人々と会うために、その国の寺院の一つに宿泊した。しかし、翌日、彼がリノクラに向かっているとき、彼の兄弟が死んだこと、そして彼がなぜ死んだのかという知らせがもたらされた。彼は、現在の状況に耐えられる限りの悲しみを味わった後、すぐにそのような心配を捨てて、旅を続けた。しかし、しばらくして、アラビアの王は自分のしたことを悔い改め、すぐに使者を送って彼を呼び戻した。ヘロデは彼らを阻止してペルシウムに来たが、そこでは艦隊にいた者たちから通行許可を得ることができなかったので、彼らの艦長たちに、彼らを通して行かせてくれるように頼んだ。そこで、彼らはその男の名声と威厳を尊敬していたので、彼をアレクサンドリアに案内した。彼がその町に到着すると、クレオパトラは彼を盛大に迎えた。クレオパトラは、彼が今行っている遠征の軍の指揮官になるよう説得されるかもしれないと期待した。しかし、彼は女王の懇願を断り、その時起こった嵐の激しさにも、イタリアで起こっていた騒乱にも恐れることなく、ローマに向けて出航した。

3\. しかし、パンフィリア付近で危険にさらされ、船の積荷の大部分を降ろさざるを得なかったため、カッシウスとの戦争でひどく荒廃したロドス島になんとか無事にたどり着いた。そこで彼は友人のプトレマイオスとサッピニウスに迎えられ、当時は金欠であったにもかかわらず、非常に大きな三層構造の船を準備し、友人たちとブルンドゥシウムへ航海し、そこから急いでローマへ向かった。そこで彼はまず、父の友情の故にアントニウスのもとへ行き、自分と家族の災難を告げ、要塞に包囲された近親者を残して嵐の中を航海し、助けを懇願した。

4\. そこでアントニーは、ヘロデの情勢の変化に同情心を抱いた。それは、アンティパトロスから受けた厚遇を思い起こしたからでもあったが、とりわけヘロデ自身の徳のためでもあった。そこで彼は、かつて自ら領主としたユダヤ人をアンティパトロスに王位に就けようと決心した。また、アンティゴノスとの争いも、彼がヘロデに対して抱いていた大きな尊敬に劣らず重要な動機であった。アンティゴノスは反乱者であり、ローマ人の敵であるとみなしていたからである。カエサルに関しては、ヘロデはアントニーよりもカエサルのほうが準備が整っていると感じた。カエサルは、父と共に経験した戦争、カエサルから受けた厚遇、カエサルが示した善意を非常に鮮明に覚えていたからである。さらに、ヘロデ自身にも活動的なところがあった。そこで彼は元老院を召集し、メッサラスとそれに続いてアトラティヌスがヘロデを彼らの前に連れ出し、彼の父の功績とローマ人に対する彼自身の好意を詳細に説明した。同時に彼らは、アンティゴノスが敵であることを示した。それは彼がすぐに彼らと争ったからだけではなく、彼が今やローマ人を無視し、パルティア人を利用して政府を握ったからであった。これらの理由は元老院を大いに動かした。その時点でアントニーがやって来て、パルティア戦争ではヘロデが王になるのが彼らの利益になると彼らに告げたので、彼らは全員それに賛成票を投じた。そして元老院が解散すると、アントニーとシーザーはヘロデを間に挟んで出かけ、執政官と他の行政官たちは犠牲を捧げ、カピトリノで勅令を布告するために彼らの前に出た。アントニーはまた、ヘロデの治世の初日に彼のために祝宴を催した。

### 第15章

### 第16章

### 第17章

### 第18章

### 第19章

### 第20章

### 第21章

### 第22章

### 第23章

### 第24章

### 第25章

### 第26章

### 第27章

### 第28章

### 第29章

### 第30章

### 第31章

### 第32章

### 第33章

## 第二巻

### 第1章

### 第2章

### 第3章

### 第4章

### 第5章

### 第6章

### 第7章

### 第8章

### 第9章

### 第10章

### 第11章

### 第12章

### 第13章

### 第14章

### 第15章

### 第16章

### 第17章

### 第18章

### 第19章

### 第20章

### 第21章

### 第22章

## 第三巻

### 第1章

### 第2章

### 第3章

### 第4章

### 第5章

### 第6章

### 第7章

### 第8章

### 第9章

### 第10章

## 第四巻

### 第1章

### 第2章

### 第3章

### 第4章

### 第5章

### 第6章

### 第7章

### 第8章

### 第9章

### 第10章

### 第11章

## 第五巻

### 第1章

### 第2章

### 第3章

### 第4章

### 第5章

### 第6章

### 第7章

### 第8章

### 第9章

### 第10章

### 第11章

### 第12章

### 第13章

## 第六巻

> 約 1 か月の間隔を含みます。ユダヤ人がティトゥスによるエルサレム占領まで追い込まれた極限状態から。

### 第1章

> 悲惨さがさらに悪化し、ローマ軍がアントニアの塔を攻撃した経緯。

1\. こうしてエルサレムの惨状は日増しに悪化し、反乱分子たちは、飢餓が人々を襲った後、自分たちをも襲う中、自分たちが受けている災難にますます苛立っていた。そして実際、山積みになった多数の死体は恐ろしい光景で、悪臭を放ち、町から出撃して敵と戦おうとする者たちの妨げとなった。しかし、すでに一万人の殺人に慣れていた者たちは、死体を踏みつけながら行進しなければならなかったので、彼らは恐れることはなく、死体の上を行進する者たちを憐れむこともなかった。また、死者に対するこの侮辱が自分たちにとって不吉な前兆であるとも考えなかった。しかし、彼らはすでに自国の人々を殺害して右手を汚しており、その状態で外国人と戦うために駆け出したため、あたかも神が彼らを罰するのに遅すぎるかのように、神自身を非難したように私には思える。というのは、彼らは勝利の希望を持っているかのように戦争を進めなかったからである。彼らはすでに陥っていた救済の絶望を、残忍なやり方で誇っていたからである。そして今や、ローマ人は、物資を集めるのに非常に苦労していたにもかかわらず、すでに述べたように、都市に隣接する田園地帯のすべての木を切り倒した後、21日間で堤防を築き上げた。そして実際、田園地帯の景色自体が憂鬱なものであった。というのは、以前は木々や美しい庭園で飾られていた場所が、今ではどこもかしこも荒れ果て、木々はすべて切り倒されていたからである。かつてユダヤやこの都市の最も美しい郊外を見た外国人が、今は砂漠と化したこの地を目にすれば、この大きな変化に悲嘆せずにはいられない。戦争が美の痕跡をすべて完全に破壊してしまったからである。また、以前この地を知っていた人が、今突然この地を訪れても、再びこの地を知ることはできなかったであろう。しかし、たとえその人がこの都市にいたとしても、それでもこの地を尋ねたであろう。

2\. そして今や堤防が完成し、ローマ人とユダヤ人の双方に恐怖の根拠を与えた。というのは、ユダヤ人は堤防を焼き払わない限り、都市は陥落するだろうと予想していたが、ローマ人も、一度堤防を焼き払ったら、決して陥落できないと予想していた。なぜなら、物資がひどく不足し、兵士たちの肉体は過酷な労働で衰弱し始め、魂は多くの失敗に終わり弱り始めたからである。いや、市内で起きた災難そのものが、市内の災難よりもローマ人にとって大きな落胆となった。ユダヤ人の戦士たちが、そのようなひどい苦難の中でもまったく慰められず、一方で彼ら自身も勝利の望みがどんどん薄れていき、堤防は敵の策略に、武器は壁の堅固さに、最も接近した戦いは攻撃の大胆さに屈することを余儀なくされたからである。そして、何よりも彼らを落胆させたのは、ユダヤ人の勇敢な魂が、暴動、飢餓、そして戦争そのものによって彼らが被っている多くの苦難を凌駕していることに気づいたことだった。彼らは、ユダヤ人の攻撃の激しさは無敵であり、彼らが示す敏捷性は災難によっても落胆することはないだろうと容易に想像した。不幸を勇気の向上に変えた幸運な者たちが、耐えられないはずがないからだ。これらの考慮から、ローマ人は以前よりも川岸の警備を厳重にした。

3\. しかし、ヨハネと彼の仲間は、この城壁が崩れ落ちた場合に備えて、その後の安全確保に気を配り、破城槌が彼らに向けられる前に任務に取りかかった。しかし、彼らはやろうとしていたことを成し遂げることができず、たいまつを持って出かけ、岸に近づく前に大いに落胆して戻ってきた。その理由は次のとおりである。第一に、彼らの行動は一致しているようには見えず、別々のグループに分かれて、別々の間隔で、ゆっくりと、おずおずと、一言で言えば、ユダヤ人らしい勇気もなく出かけた。というのは、彼らは今や、わが国民特有の、大胆さ、攻撃の激しさ、敵に一斉に突撃すること、そして最初は成功しないものの、やろうとしていることを粘り強く続けることに欠陥があったからである。しかし、彼らは今、いつもより気だるく出撃し、同時にローマ軍がいつもより勇敢に隊列を組んでおり、体と鎧で堤防を守り、四方八方から火が入り込む余地がないようにしていた。そして、彼らの魂はみな非常に勇敢で、隊列を離れるくらいなら死んでもいいくらいだった。というのは、もし彼らの作品が一度でも焼け落ちれば、すべての希望が断たれるという考えに加えて、兵士たちは、勇気には狡猾さが、鎧には狂気が、技術には群衆が、そしてローマ人にはユダヤ人がまったく手ごわいことを、非常に恥じていたからである。ローマ軍には、今やもう一つの有利な点があった。それは、ユダヤ人が町から出てくるとき、包囲用の兵器が彼らと協力して、遠くのユダヤ人にまで矢や石を投げることができたということである。それによって倒れた者は隣にいる者の邪魔となり、さらに進む危険が彼らの試みに対する熱意をそぐのであった。そして矢の下を逃げた者たちは、接近戦になる前に敵の隊列の整然とした緊密さに恐れをなした者もいれば、槍で刺されて引き返した者もいた。ついに彼らは互いの臆病さを非難し、何もせずに撤退した。この攻撃はパネムス（タムズ）の月の最初の日に行われた。ユダヤ人が撤退すると、ローマ軍は武器を持ってきたが、その間ずっとアントニアの塔から石が投げつけられ、火と剣、そしてユダヤ人が必然的に利用したあらゆる種類の矢で攻撃された。というのも、ローマ軍は自分たちの城壁に大きく依存しており、ローマ軍の武器を軽蔑していたにもかかわらず、ローマ軍が武器を持ってくるのを阻止しようと努めたからである。ローマ人は逆に激しく抵抗した。ユダヤ人のこの熱心さは、アントニアの塔の壁が弱く、基礎が腐っていたため、塔に何らかの影響が及ぶのを避けるためだと考えたからである。しかし、塔は兵器の打撃に屈することはなかった。しかし、ローマ軍は敵の矢が絶えず投げつけられる衝撃に耐え、上から襲いかかるいかなる危険にも屈することはなく、そこで兵器を投入した。しかし、そのとき、彼らは敵の下にいて、投げつけられた石によってひどく傷ついたので、彼らのうちの何人かは盾を体に投げつけ、一部は手、一部は体、一部はカラスを使って、塔の基礎を掘り崩し、苦労して石を4つ取り除いた。その後、両軍に夜が訪れ、当面この戦いは終わった。しかし、その夜、ジョンが以前に策略を使って堤防を崩した場所の城壁は破城槌によって大きく揺さぶられ、地面が崩れて突然城壁が崩れ落ちた。

4\. この事故が予期せず起こったとき、双方の心はさまざまな影響を受けた。ユダヤ人は、壁の陥落が予期せぬことであり、その場合に備えて何も準備していなかったため、落胆するだろうと予想されたが、アントニアの塔自体はまだ立っていたため、勇気を奮い起こした。ローマ軍は、壁の陥落に予想外の喜びを覚えたが、ヨハネとその一行がその中に築いた別の壁を見て、すぐに喜びが消えた。しかし、この第二の壁への攻撃は、以前の壁の攻撃よりも容易であるように思われた。なぜなら、今や崩れ落ちた以前の壁の部分を通って、この壁まで登るのがはるかに容易であるように思われたからである。この新しい壁は、アントニアの塔よりもずっと脆弱であるように思われたため、ローマ軍は、この壁があまりにも突然に建てられたため、すぐに倒壊するだろうと考えた。しかし、誰も今この壁に登ろうとはしなかった。なぜなら、最初に登ろうとした者は、必ず殺されるからである。

5\. さて、ティトゥスは、戦争における兵士の機敏さは主に希望と善意の言葉によって刺激されるということ、また、激励と約束はしばしば人々に危険を忘れさせ、時には死そのものを軽蔑させるということを考慮して、軍隊の最も勇敢な部分を集め、これらの方法で兵士たちに何ができるかを試した。 「おお、戦友よ」と彼は言った。「危険のないことをするように人々に勧めることは、まさにその勧めを受ける人々にとって不名誉なことである。そして実際、勧める側にとっても、それは彼自身の臆病さの議論である。したがって、私は、そのような勧めは、事態が危険な状態にあり、それでも誰もが自ら試みる価値がある場合にのみ利用されるべきであると考える。したがって、この壁を登るのは困難な仕事であるという点で、私はあなたと完全に同じ意見である。しかし、勇敢さに対する名声を望む人々が、栄光のうちに死ぬことは勇敢なことであり、ここで必要な勇気は最初に試みを始める人々に報われないことはないと私が特に示したときに、その後に明らかになるような困難と格闘するのは適切である。そして、あなたたちを説得するための私の最初の議論は、おそらく一部の人があなたたちを思いとどまらせるのに適切であると考えるであろうもの、つまり、彼らの過酷な状況下でさえ、これらのユダヤ人の不屈さと忍耐から取ろう。なぜなら、平時においても戦争のやり方を教え込まれ、また戦争で勝利を収めてきたローマ人であり私の兵士であるあなたがたが、手腕においても、あるいは魂の勇気においても、ユダヤ人に劣るというのは、似つかわしくないことであり、特にあなたがたが勝利の最終段階にあり、神ご自身の助けを受けているときに、そうであるからだ。私たちの不幸はユダヤ人の狂気によるものであり、彼らの苦しみはあなたがたの勇気と神があなたがたに与えた助けによるものである。彼らが起こした暴動、彼らが受けている飢餓、彼らが今耐えている包囲、そして私たちの軍隊の力なしに彼らの城壁が崩壊したことは、彼らに対する神の怒りと、神が私たちに与えた助けの表れでなくて何だろうか。したがって、あなた方が本当に優れている人々に対して自分達が劣っていることを示すことも、あなた方に与えられた神の助けを裏切ることも、あなた方にとって適切ではない。そして実際、ユダヤ人は長い間他人の奴隷になることを学んできたので、見捨てられてもあまり恥じる必要はないが、それでも死を軽蔑し、もはやそうではないようにし、我々を征服する希望ではなく、我々の真ん中に頻繁に突撃してくることは、卑しく価値のないこととしか考えられない。彼らの勇気を示すためだけに。我々は、陸と海に属する世界のほとんどすべてを支配しており、もし彼らを征服しなければ非常に恥ずべきことになるので、一度も危険を伴う敵に対する試みをせず、我々が持っている勇敢な武器を持って何もせずにじっと座り、飢餓と幸運が我々の仕事を成し遂げるまで待つだけです。そして、我々が望むものをすべて手に入れるために、少しの危険を冒して力を得たときです！ 我々がアントニアのこの塔に登れば、我々は都市を占領します。もし都市内の人々と戦う機会がもうあれば、それはないと思いますが、その時我々は丘の頂上にいるでしょうから。1そして敵が息をつく前に攻撃すれば、これらの利点は我々に確実かつ突然の勝利を約束する。私としては、今のところ戦争で死んだ人たちを賞賛するつもりはない。2勇敢な戦いの最中に殺された人々の不滅性については語るのを怠ることはできない。しかし、反対の性格の人たちが平和な時に何らかの病気で死ぬかもしれないと呪わずにはいられない。彼らの魂は肉体とともに墓場に送られる運命にあるからだ。剣によって戦いで肉体から切り離された魂は、エーテル、つまり最も純粋な元素に受け入れられ、星々の間に置かれた仲間と結合し、善良な悪魔や幸運の英雄となり、その後子孫にその姿を見せるということを知らない徳の高い人がいるだろうか。一方、病んだ肉体とともに消耗する魂には、地下の夜が訪れて無に溶解し、深い忘却が訪れてすべての記憶を消し去るが、それにもかかわらず、彼らはこの世のすべての汚れや穢れから清らかである。それで、この安楽さの中で、魂は同時にその生命、その肉体、そしてその記念碑の極限に達するのです。しかし、神はすべての人に死が必然的に訪れると定めたので、剣はどんな病気よりもその目的に適した道具です。では、運命に明け渡さなければならないものを公共の利益に明け渡さないことは、なぜ非常に卑しいことではないのでしょうか。そして、この話を私がしたのは、最初にこの壁を登ろうとする者は、その試みで殺されるに違いないが、それでも真の勇気のある者は最も危険な試みでさえ逃れるチャンスがあるという仮定のためです。第一に、以前の壁の倒壊した部分は簡単に登ることができます。そして、新しく建てられた壁は簡単に破壊されます。ですから、あなた方の多くは勇気を奮い起こしてこの仕事に取り掛かり、互いに励まし合い、助け合ってください。そうすれば、この勇気はすぐに敵の心を打ち砕くでしょう。そして、おそらくあなた方のような素晴らしい計画は流血なしに達成されるかもしれません。なぜなら、ユダヤ人があなた方が彼らのところへ向かおうとする最初の段階であなた方を妨害しようとすることは当然想定されるからです。しかし、あなた方がいったん彼らから身を隠し、力ずくで追い払えば、あなた方のほんの少数が彼らを阻止して壁を乗り越えたとしても、彼らはあなた方の努力をこれ以上持ちこたえることはできないでしょう。最初に壁を登った人については、私が与えるであろう報酬によって、他の人が彼を羨むようにしなかったとしたら、私は恥ずかしさで顔を赤らめます。そのような人が命からがら逃れたなら、彼は今彼と同等である他の人々を支配するでしょう。しかし、試みで死んだ者に最大の報酬が与えられることも事実です。」 3

6\. ティトゥスのこの言葉を聞いて、群衆の残りは、このような大きな危険に怯えた。しかし、サビヌスという名の、シリア生まれの兵士がいた。彼は、行動においても、示した魂の勇気においても、非常に不屈の精神の持ち主のように見えた。しかし、彼が任務に就く前は、彼の体は弱く、兵士には不向きだと誰もが思っただろう。なぜなら、彼の肌は黒く、肉は痩せて薄く、肉づきが悪かったからだ。しかし、この小さな体には、ある種の英雄的な魂が宿っていた。その体は、彼の中にあるあの特別な勇気には、実に狭すぎた。したがって、彼は最初に立ち上がり、こう言った。「私は喜んであなたに身を委ねます、シーザー。まず城壁を登り、私の勇気と決意に運命が続くことを心から望みます。そして、もし不運が私の計画の成功を阻むことがあっても、私の不運は予期せぬものではなく、あなたのために自ら死を選ぶものであることに留意してください。」こう言って、左手で盾を頭上に広げ、右手で剣を抜くと、ちょうどその日の午後六時ごろ、城壁に向かって行進した。彼の勇敢さを真似しようと決心した他の 11 人が彼に続いたが、それ以上ではなかった。しかし、それでもこの人物は彼ら全員の中で主役であり、神の怒りに駆られたように先頭に立った。すると、城壁の警備員がそこから彼らを撃ち、四方八方から無数の矢を彼らに投げつけた。また、非常に大きな石を彼らの上に転がし、彼と一緒にいた11人のうちの何人かを倒した。しかしサビヌス自身は、投げつけられた矢に当たったが、その矢に圧倒されたにもかかわらず、城壁の頂上に登り敵を敗走させるまで攻撃の勢いを緩めなかった。ユダヤ人たちは彼の強大な力と勇敢な精神に驚嘆し、さらに、城壁の上に登ったのは実際よりも多くの者だと想像したため、敗走した。ここで、運がまだ美徳を妬み、輝かしい業績の達成を常に妨げていると嘆かずにはいられない。これは、私たちの前にいる男が目的を達成したばかりのときの場合だった。そのとき、彼はある大きな石につまずき、非常に大きな音を立ててその上に真っ逆さまに倒れたのである。そこでユダヤ人たちは引き返し、彼がひとりで倒れているのを見て、四方八方から矢を投げつけた。しかし、彼はひざまずいて盾で身を隠し、まず彼らから身を守った。そして、彼に近づいた者の多くを傷つけたが、受けた傷の多さのせいで、彼はすぐに右手を緩めざるを得なくなり、ついには体中が矢で覆われて息絶えた。彼はその勇敢さゆえに、もっとましな運命に値する者だったが、予想通り、あまりにも大きな試みで倒れた。彼の仲間の残りは、ユダヤ人が3人を石で打ち砕き、壁の頂上に登ったところで殺害した。他の8人は負傷し、引きずり降ろされて野営地に運ばれた。これらのことは、パネムス（タムズ）の月の3日目に行われた。

7\. 二日後、最前線にいて川岸の見張りをしていた十二人の男たちが集まり、第五軍団の旗手と騎兵隊の二人、そしてラッパ手一人を呼び寄せた。彼らは夜の九時ごろ、音を立てずに廃墟を抜けてアントニアの塔に向かった。そして眠っている最初の衛兵の喉を切り裂いた後、城壁を占領し、ラッパ手にラッパを鳴らすよう命じた。すると、残りの衛兵は突然立ち上がり、何人立ち上がったか誰にも分からないうちに逃げ去った。彼らは恐怖から、またラッパの音を聞いて、敵の大勢が立ち上がったと思ったからである。しかし、シーザーは合図を聞くとすぐに、軍隊に直ちに武装するよう命じ、指揮官たちとともにそこへ行き、まず最初に、彼とともにいた選抜兵とともに上っていった。ユダヤ人が神殿へ逃げ去ろうとしていたとき、彼らはヨハネがローマ軍の土手の下に掘った坑道に落ちた。そこで、ユダヤ軍の両部隊、ヨハネの部隊とシモンの部隊の反乱分子が彼らを追い払った。そして、最高レベルの力と敏捷性において、まったく不足はなかった。なぜなら、彼らは、ローマ軍が神殿に侵入すれば、自分たちは完全に破滅するとみなしていたからである。ローマ軍も同じことを、彼らの全征服の始まりとみなしていた。そこで、神殿の入り口で恐ろしい戦いが繰り広げられ、ローマ軍は神殿を占領するために押し寄せ、ユダヤ人は彼らをアントニアの塔まで追い返していた。その戦いでは、槍も槍も双方とも役に立たず、双方とも剣を抜いて、白兵戦を繰り広げた。この戦いの間、両軍の兵士の配置は区別がつかず、場所が狭いために兵士たちが互いに入り乱れて混乱し、無作為に戦った。一方、立てられた音は、非常に大きな音であったため、不明瞭な形で耳に届いた。両軍で大虐殺が行われ、戦闘員たちは死んだ者の死体や鎧を踏みつけ、粉々に打ち砕いた。したがって、戦いがどちらの側に傾いたとしても、有利な者は互いに前進するよう励まし合い、敗れた者は大いに嘆いた。しかし、それでも逃げる余地も追撃する余地もなく、無秩序な革命と退却が続き、軍は互いに入り乱れていた。しかし、最前列にいる者たちは、殺すか殺されるかのどちらかを余儀なくされていた。逃げ場は全くなかった。なぜなら、両軍とも後ろから来た者たちが、前にいる者たちを進軍させ、軍の間に隙間を作らせなかったからである。ついに、ユダヤ人の激しい熱意はローマ軍の技量にはかなわず、戦いは完全にその方向に傾いた。戦いは夜の9時から朝の7時まで続いたが、ユダヤ人は群れをなして進軍し、神殿が危険にさらされていることを動機としていた。ローマ軍はここに軍の一部しか残っていなかった。なぜなら、その側の兵士たちが頼りにしていた軍団は、彼らのところまで来ていなかったからである。そのため、現時点では、ローマ軍はアントニアの塔を占領するだけで十分だと考えた。

8\. しかし、ビテュニア出身の百人隊長ユリアンがいた。彼は非常に評判が高く、以前その戦争で私が会ったことがあり、その戦闘技術、肉体の強さ、そして魂の勇気の両方において最も名声の高い人物の一人であった。この男は、ローマ軍が敗走し、悲惨な状況にあるのを見て（アントニアの塔でティトゥスの傍らに立っていた）、飛び降り、すでに勝利していたユダヤ人をたった一人で逃げさせ、神殿の内庭の隅まで退却させた。群衆は彼の力も激しい攻撃も単なる人間のものではないと考えたのか、彼から群がって逃げ去った。そこで、彼は散り散りになっていたユダヤ人の真ん中を突進し、捕まえた者を殺した。実際、カエサルの目にこれより素晴らしいもの、あるいは他の人々にこれより恐ろしいものに映った光景は他になかった。しかし、彼自身も運命に追われており、人間に過ぎない彼が逃れることは不可能だった。なぜなら、彼の靴は厚くて鋭い釘でいっぱいだったからである。他の兵士たちと同じように、彼も神殿の舗道を走っているときに足を滑らせ、鎧が立てた大きな音とともに仰向けに倒れた。逃げていた者たちは引き返した。そこでアントニアの塔にいたローマ兵たちは、その男を恐れて大声で叫んだ。しかしユダヤ人たちは群がって彼を取り囲み、槍や剣で四方八方から彼を襲った。彼は盾にこれらの鉄の武器の打撃を何度も受け、何度も立ち上がろうとしたが、襲ってきた者たちに倒された。しかし、横たわったまま、剣で何人もの敵を刺した。また、致命傷を受ける可能性のある体の部位はすべて兜と胸当てで覆われていたため、すぐには殺されなかった。彼もまた首を体に引き寄せ、他の手足はすべて粉砕され、誰も彼を守ろうとはせず、運命に身を任せた。さて、カエサルはこの非常に勇敢な男に、特に大勢の人々の目の前で殺されたことに深く心を痛めた。彼自身も助けに行きたいと思ったが、その場所は許してくれず、助けることのできる者もあまりに恐れおののいて試みることができなかった。こうして、ユリアヌスは死と長い間格闘し、致命傷を与えた者のうち無傷で済ませた者はほとんどいなかったが、ついには首を切り裂くことができた。そして、ローマ人の間だけでなく、カエサル自身だけでなく、敵の間でも非常に大きな評判を残した。その後、ユダヤ人が彼の死体を拾い上げ、ローマ人を再び逃げさせ、アントニアの塔に閉じ​​込めた。さて、ユダヤ人側のこの戦いで最も勇敢に戦い、最も熱心に戦ったのは、ヨハネの党からはアレクサスとギュフテウス、シモンの党からはマラキア、メルトの子ユダ、イドマヤ人の司令官ソサスの子ヤコブ、そして熱心党からはヤイロの子シモンとユダの二人の兄弟であった。

### 第2章

> ティトゥスがアントニアの塔を破壊するよう命令し、その後ヨセフスにユダヤ人に再び降伏を勧めるよう説得した経緯。

1\. そして今、ティトゥスは、彼と一緒にいた兵士たちに、アントニアの塔の基礎を掘り起こし、彼の軍隊が登るための通路を整備するように命じた。一方、彼自身はヨセフスを彼のもとに連れて来た。\[というのは、彼は、その日、すなわちパネムス\[タムズ\]の17日目に、「毎日の犠牲」と呼ばれる犠牲が失敗し、それを捧げる人がいなかったために神に捧げられず、人々がそれにひどく困惑していると知らされていたからである\]。そして、ヨセフスに、もし彼が悪意を持って戦う気があるなら、自分の町や神殿を破壊する危険なしに、好きなだけ兵士を連れて出かけて戦うことができるが、神殿を汚したり、それによって神に反抗したりすることは望まない、と以前ヨハネに言ったのと同じことを言うように命じた。彼が攻め込んだユダヤ人の誰かが今ややめてしまった犠牲を、彼が望むなら捧げることができる、と。そこでヨセフスは、ヨハネだけでなく、もっと多くの人々に聞かれるような場所に立ち、カエサルが彼に与えた任務をヘブライ語で彼らに告げた。6そこで彼は、彼ら自身の都市を救い、神殿を襲おうとしている火災を防ぎ、そこで神にいつもの供物を捧げるよう熱心に人々に懇願した。彼のこの言葉を聞いて、民衆は大きな悲しみと沈黙に包まれた。しかし、暴君自身はヨセフスに対して多くの非難を浴びせ、さらに呪いの言葉も加え、最後に、そこは神の都市であるため、都市の陥落を恐れることはないと付け加えた。これに答えて、ヨセフスは大声でこう言った。「確かに、あなたは神のためにこの町を驚くほど清浄に保ってきた。神殿も全く汚れていない！ また、あなたが助けを期待している神に対して不敬虔な罪を犯したことはない！ 彼は今でもいつもの供物を受けている！ あなたは卑劣な悪党だ！ 誰かがあなたの毎日の食べ物を奪うなら、あなたは彼を敵とみなすだろう。しかし、あなたは永遠の崇拝を奪ったあの神をこの戦争であなたの支援者にしたいと望んでいる。そして、あなたはその罪をローマ人に帰している。彼らは今に至るまで私たちの法律を遵守させ、あなたの力で中断されたこれらの供物を神に捧げることをほとんど強制しているのだ！ この町でなされた驚くべき変化に、うめき声​​と嘆きを免れることができる人がいるだろうか？ 外国人や敵でさえ、今やそのことを正そうとしているのだから。汝が引き起こした不信心は、ユダヤ人であり、我々の法律を学んだ汝が、他の者たちよりも彼らにとって大きな敵となったということである。しかし、それでも、ヨハネよ、悔い改めて、最後の最後になっても、間違ったことを改めることは決して不名誉なことではない。汝には、エコニヤ書にその例がある。ユダヤ人の王よ、もしあなたがこの町を救おうとお考えなら、バビロンの王が彼と戦ったとき、この町が陥落する前に自ら進んでこの町から出て、家族とともに自主的に捕囚となった者よ。それは、聖所が敵に渡されないようにするため、また神の家が放火されるのを見ないようにするためである。このため、彼はすべてのユダヤ人の間で神聖な記念物として讃えられ、彼の記憶は不滅となり、あらゆる時代を通じて私たちの子孫に新鮮に伝えられるであろう。ヨハネよ、これはこのような危険な時代には優れた例であり、私はローマ人があなたを許すであろうとあえて約束しよう。そして、あなたにこの勧告をする私は、あなたの同胞の一人であることに留意しなさい。ユダヤ人である私が、あなたにこの約束をするのである。そして、あなたにこの勧告を与える私が誰であるか、そして私がどこから来たのかを考えるのは、あなたにとってふさわしいことである。生きている間は、自分の親族を見捨てたり、先祖の法律を忘れたりするような奴隷状態にはならないでしょう。あなたはまたも私に対して憤慨し、私に向かって騒ぎ立て、私を非難しています。実際、私は、運命に逆らってあなたにこのような親切な招待をし、神が非難した人々を強制的に解放しようと努めている以上、これらすべてよりもひどい扱いを受けるに値することを否定できません。そして、古代の預言者の書物、特に今まさにこの惨めな都市に実現しようとしているあの神託に何が書かれているのか知らない人がいるでしょうか。彼らは、誰かが自分の同胞を虐殺し始めたときにこの都市が陥落すると予言したからです。そして、今やこの都市も神殿もあなたの同胞の死体で満ちているではありませんか。ですから、ローマ人を通してあの町と神殿を清めるために、この火を起こしているのは神であり、 8あなたがたの汚れで満ちているこの町を根こそぎにしようとしているのは神ご自身なのです。」

2\. ヨセフスがこれらの言葉を話すとき、彼の目はうめき声と涙でいっぱいだったが、彼の声はすすり泣きに遮られた。しかし、ローマ人は彼の苦しみを哀れに思い、彼の行為に驚かざるを得なかった。しかし、ヨハネと彼と共にいた人々は、このことでローマ人に対してますます憤慨し、ヨセフスをも彼らの手中に収めようと望んだ。しかし、この演説は多くの良識ある人々に影響を与えた。実際、彼らの中には、反乱軍が配置した警備隊を恐れて、そこに留まった者もいたが、それでも自分たちと都市は破滅する運命にあると確信していた。また、ローマに逃げた者もいた。ローマには、大祭司ヨセフとイエス、大祭司の息子３人（父はキレネで斬首されたイシュマエル）、マティアスの息子４人、マティアスの息子１人（父の死後逃亡、９すでに述べたように、その父はギオラスの子シモンによって３人の息子とともに殺された）、大祭司たちとともにローマに寝返った貴族たちも多かった。さて、カエサルは他の点ではこれらの人々を非常に親切に迎えただけでなく、彼らが他の国の慣習に従って生きることを好まないことを知っていたので、彼らをゴフナに送り、当分そこに留まるように頼み、この戦争から解放されたら、各自の所有地を再び返すと告げた。そこで彼らは、危険を恐れることなく、喜んで割り当てられた小さな町に退却した。しかし、彼らが姿を現さなかったため、反乱分子は再び、これらの脱走兵はローマ軍に殺されたと流した。これは、同様の扱いを恐れて残りの者たちが逃亡するのを思いとどまらせるためのものだった。彼らのこの策略は、以前の同様の策略と同様に、しばらくの間成功した。なぜなら、残りの者たちは、同様の扱いを恐れて、これによって逃亡を思いとどまったからである。

3\. しかし、ティトゥスはゴフナからこれらの人々を呼び戻した後、ヨセフスと共に城壁を回り、人々に姿を見せるよう命じた。これを受けて、多くの者がローマ人の元へ逃げた。これらの人々も大勢で集まり、ローマ人の前に立ち、うめき声​​と涙を浮かべながら、まずローマ人を市内に完全に受け入れ、そこを自分たちの居住地として残すよう扇動者に懇願した。しかし、もしそのような提案に同意しないのであれば、少なくとも神殿から出て、自分たちのために聖なる家を残しておいて欲しいと。なぜなら、ローマ人は最も差し迫った必要がない限り、聖域に火をつけることはしないだろうからである。しかし、扇動者はますます彼らに反対した。そして彼らは、これらの脱走兵を激しく激しく非難する一方で、神殿の神聖な門に矢や槍や石を投げつける準備をした。門は互いに適切な距離を置いて設置されたので、神殿の周囲の空間全体が墓地に例えられるほどだった。そこには死体の数が非常に多かったからである。聖なる家自体が城塞に例えられるほどであった。したがって、これらの男たちは、そうでなければ近づくことのできないこれらの聖なる場所に、鎧を着て突撃し、彼らの手は流した同胞の血でまだ温かいままであった。いや、彼らは非常に大きな罪を犯したので、ユダヤ人がローマ人に対してそのような虐待を犯していたなら当然抱くであろう憤りと全く同じ憤りを、ローマ人は今や、自分たちの宗教的慣習に対するユダヤ人の不敬虔さに対して抱いたのである。いや、実際、ローマ兵の中には、聖なる家を神聖な恐怖の目で見、崇拝し、強盗たちがその苦しみが癒えなくなる前に悔い改めることを願わなかった者は一人もいなかった。

4\. さて、ティトゥスはこの事態に心を痛め、ヨハネとその一行を非難して言った。「あなたたち、卑劣な悪党どもは、我々の許可を得て、聖所の前にこの仕切り壁を立てたではないか。あなたたちは、その壁から離れたところに柱を立て、ギリシャ語とあなたたちの文字で、外国人は誰もこの壁の向こう側へ行ってはならないというこの禁令を刻むことを許されたではないか。10 我々は、たとえローマ人であっても、向こう側へ行った者を殺すことをあなたたちに許可したではないか。それなのに、あなたたち は今何をしているのだ、この悪党ども。なぜこの神殿で死体を踏みつけるのか。なぜ、外国人とユダヤ人自身の血でこの聖なる家を汚すのか。私は、自分の国の神々と、かつてこの場所を気にかけたすべての神に訴える。\[なぜなら、私は、今、この場所が誰からも気にかけられているとは思わないからである。\] また、自分の軍隊と、今私と一緒にいるユダヤ人たちにも訴える。そして、あなたたち自身にも、この聖域を汚すことを強制しないよう、約束する。そして、あなたたちが戦う場所を変えさえすれば、ローマ人はあなたたちの聖域に近づいたり、そこを攻撃したりはしない。いや、あなたたちが望むと望まざるとにかかわらず、私はあなたたちの聖なる家を守るよう努力する。」11

5\. ヨセフスがカエサルの口からこれらのことを説明したので、盗賊も暴君も、これらの勧告はティトゥスの彼らに対する善意からではなく、恐怖から出たものだと考え、そのことで傲慢になった。しかし、ティトゥスは、これらの人々が自分たちに対する同情によって動かされるわけでもなく、聖なる家を救うことに何の関心も持っていないのを見て、しぶしぶ彼らに対する戦争を再開した。確かに、その場所は非常に狭かったので、全軍を彼らに向かわせることはできなかったが、百人中最も勇敢な兵士三十人を選び、各護民官に千人ずつ割り当て、ケレアリスを彼らの総司令官に任命し、その夜の九時ごろに神殿の衛兵を攻撃するよう命令した。しかし、彼はすでに鎧を着て彼らとともに下る準備をしていたが、彼の友人たちは危険の大きさと司令官たちが彼らに示唆したことのために、彼を行かせようとしなかった。というのは、彼らは、カエサルが塔の上に座り、戦いで名を成した兵士たちに褒賞を与える方が、塔から降りてきて兵士たちの先頭に立って危険を冒すよりも、彼ら全員が勇敢に戦い、カエサルが見守る中、勇敢に戦うだろうと言ったからである。この助言にカエサルは従い、兵士たちにこのように従う唯一の理由は、彼らの勇敢な行動を判断でき、勇敢な兵士が隠れて褒賞を逃すことがなく、臆病な兵士が罰を受けずに済むことがあり、彼らへの罰と褒賞の分配者である彼自身が目撃者となり、行われたすべてのことを証言できるからだと言った。そこで彼は、兵士たちを前述の時間に仕事に送り出し、自分はアントニアの塔の高い場所へ出て、何が起こったのかを見ようとし、そこで待ち焦がれながら出来事を待っていた。

6\. しかし、派遣された兵士たちは、彼らが期待したように神殿の衛兵が眠っているのを見つけられず、大声で叫びながら激しく襲い掛かってきたので、すぐに彼らと白兵戦を強いられた。神殿内の他の者たちは、見張りの者たちの叫び声を聞くとすぐに、軍隊を率いて彼らに襲い掛かった。そこでローマ軍は、最初に襲い掛かってきた者たちの攻撃を受けたが、その後に続いた者たちは自軍に襲い掛かり、その多くは自軍の兵士を敵のように扱った。両側で立てられた大きな混乱した騒音のせいで、互いの声を聞き分けることはできず、夜の闇のせいで視覚による判別もできなかった。さらに、同時に彼らが抱いていた激情と恐怖から生じた盲目状態もあった。そのため、兵士たちにとって、誰が襲われたかは皆同じだった。しかし、この無知は、ローマ人よりもユダヤ人に害を及ぼさなかった。なぜなら、彼らは盾の下に団結し、他の者たちよりも規則的に出撃し、それぞれが合言葉を覚えていたからである。一方、ユダヤ人は絶えず散在し、攻撃と退却を無作為に行い、そのためしばしば互いに敵であるように見えた。なぜなら、彼らは皆、暗闇の中でローマ人として戻ってきて襲撃してきた自軍の兵士たちを受け入れたからである。そのため、敵よりも自軍の兵士によって負傷した者の方が多かった。そして、夜が明けて、正義の性質が後で目で見て分かった。それから、彼らは別々の集団で戦闘隊形を組み、規則的に矢を投げ、規則的に防御した。どちらの側も屈したり疲れたりすることはなかった。ローマ人は、ティトゥスの監視下にあるとして、単独の兵士と全連隊の両方で、誰が最も激しく戦うべきかを互いに争った。そして誰もが、勇敢に戦えばこの日が昇進の始まりだと結論づけた。ユダヤ人が勇敢に行動する大きな動機となったのは、自分たちと神殿に対する恐怖と、勇敢に行動するよう一部の者を激励し、他の者を殴打し脅迫する暴君の存在であった。さて、この戦いは大部分が静止した戦いで、兵士たちは前進し、すぐに突然戻ってくるという展開だった。逃げるにも追撃するにも長い距離はなかったからだ。しかし、アントニアの塔からはローマ軍の間で騒々しい声が聞こえ、ユダヤ人に手強いときはいつでも勇敢に前進するよう大声で叫んでいた。そして彼らが後退しているときに留まるように命じた。そのため、ここは一種の戦場であった。この戦いで何が行われたかは、ティトゥスにも彼の周囲にいた者にも隠し切れなかったからである。ついに、夜の九時に始まったこの戦いは、日の五時過ぎまで終わらなかったことが明らかになった。そして、戦いが始まったのと同じ場所で、どちらの側も相手を後退させたとは言えなかった。しかし、両軍とも勝利はほぼ不確かなままであった。その中で、ローマ軍として名乗り出た者は大勢いたが、ユダヤ軍の側では、シモンの側にいた者のうち、メルトの子ユダとヨサスの子シモン、イドマヤ人からはヤコブとシモン（後者はカスラスの子、ヤコブはソサスの子）、ヨハネの側にいた者のうち、ギュフテウスとアレクサス、熱心党からはヤイロの子シモンが名乗り出た。

7\. その間に、ローマ軍の残りは、7日間でアントニアの塔の基礎を一部破壊し、神殿への広い通路を確保した。それから軍団は第一の中庭に近づき、12堤防を築き始めた。1つの堤防は内神殿の北西の角に面し、 13 もう一つは二つの門の間にある北の建物に面していた。他の2つは、一つは神殿の外庭の西側の回廊に、もう一つは北側の回廊に面していた。しかし、ローマ軍はこれらの工事をここまで進めたが、大きな苦労と困難を伴い、特に100スタディオンも離れたところから資材を運ばなければならなかった。さらに困難もあった。ユダヤ人が仕掛けた罠を突破できるほどの自信過剰と、逃げ切れないという絶望感からユダヤ人が奮い立ったことによるものであった。というのは、ユダヤ人の騎手の中には、薪や干し草を集めに出かけるときに、餌を探している間、手綱をつけずに馬に餌を食べさせていた者がいたからである。ユダヤ人は、その馬に群がって襲いかかり、馬を奪ったのである。そして、このようなことが何度も繰り返され、カエサルは、馬が盗まれたのはユダヤ人の勇敢さによるというよりも、自分の部下の不注意によるものだと確信し、残りの兵士たちに馬の世話をさせるために、もっと厳しくしようと決心した。そこで、馬を失った兵士の一人を死刑にするよう命じた。これによって残りの兵士たちは大いに恐れおののき、彼らは今後のため馬を温存した。もはや、自分たちだけで餌を食べにいくために馬を放っておかず、まるで馬が自分たちに馴染んだかのように、必需品が不足するときはいつも彼らについていくようになったのである。このようにして、ローマ軍は神殿に対して戦いを続け、神殿に対して堤防を築き続けたのである。

8\. ローマ軍が突破口を登ってから 1 日が経った後、反乱軍の多くは飢餓に苦しめられ、略奪も失敗に終わり、集まってオリーブ山にいたローマ軍を襲撃した。これは 11 時頃のことである。ローマ軍は、まずこのような襲撃は予想していないだろう、次に、ローマ軍はその時は身の安全を保っているだろうから、簡単に打ち負かすことができるだろうと考えた。しかし、ローマ軍はローマ軍が攻撃に来ることを事前に知っていたので、突然近隣の陣地から一斉に駆けつけ、ローマ軍が要塞を越えたり、周囲に築かれた壁を突破したりするのを阻止した。この後激しい戦闘が起こり、ここで双方が多くの素晴らしい行動をとった。ローマ軍は勇気と戦争の技術の両方を発揮し、ユダヤ人は度を越した暴力と耐え難い情熱でローマ軍に襲いかかった。一方の者は恥辱に駆られ、他方の者は必要に迫られて駆り立てられた。というのは、ユダヤ人を逃がすのはローマ人にとって非常に恥ずべきことと思われたからである。彼らは今や一種の網に捕らえられていた。一方、ユダヤ人が助かる唯一の望みは、暴力によってローマの壁を突破することであった。そして、ユダヤ人がすでに打ち負かされ、谷に押し込められていたとき、騎兵隊に属するペダニウスという名の男が、激しい勢いで彼らの側面に馬を駆り立て、逃げる敵の若者の足首をつかんだ。しかし、その男は頑丈な体格で、鎧を着ていた。ペダニウスは馬から身を低くかがめ、疾走しながらも、右手と体の他の部分の力は強大で、また、馬術にも非常に長けていた。そこで、この男は獲物を貴重な宝物のようにつかみ、捕虜としてカエサルの元へ連れて行った。そこでティトゥスは、相手を捕らえた男の力強さに感心し、捕らえられた男にローマの城壁への攻撃の罪で死刑に処するよう命じたが、自らは神殿の包囲と土手の築堤の強化に取り組んだ。

9\. 一方、ユダヤ人は、戦争がどんどん高くなり、聖なる家そのものにまで迫るにつれて、これまでの戦いに非常に苦しんでいたので、病気がこれ以上広がらないように、いわば感染した体の手足を切り落とした。彼らは、アントニアの塔に繋がっている北西の回廊に火をつけ、その後、その回廊の約 20 キュビトを破壊し、それによって聖域を焼き始めた。その 2 日後、または前述の月 \[パネムスまたはタムズ\] の 24 日、ローマ人は、火がさらに 15 キュビト広がったときに、もう 1 つの回廊に火をつけた。ユダヤ人は同様にその屋根を切り落とし、アントニアの塔が神殿から切り離されるまで、火を止めることができたにもかかわらず、彼らはその作業を完全にやめなかった。いや、彼らは神殿が最初に放火されたときじっとしていて、この火の広がりが自分たちの利益になると考えた。しかし、両軍は神殿の周りでまだ互いに戦い続けており、戦争は特定の勢力が互いに攻撃を繰り返すことによって進められた。

10\. さて、そのころユダヤ人の中に、背が低く、見苦しい容姿をしており、家柄も他の面でも品位のない男がいた。その名はヨナタンであった。彼は大祭司ヨハネの記念碑のところに出て行き、ローマ人に対してそのほか多くの横柄な言葉を吐き、ローマ人の中でも最も優れた者たちに一騎打ちを挑んだ。しかし、そこにいた軍隊の多くは彼を怒鳴りつけ、その多くは彼を恐れた。彼らの中には、死を望んでいる者と戦うのはふさわしくない、なぜなら、救いを全く望まない者たちは、他の感情のほかに、対抗できない者を攻撃する激しさを持ち、神自身を顧みないからである、と考えた者もいた。そして、たとえ打ち負かしても大したことにはならず、捕虜にされる危険のある人物に危険を冒すのは、男らしい勇気ではなく、男らしくない無謀さの例となるだろう。そこで、その男の挑戦を受ける者は誰も出てきてはこなかったため、ユダヤ人は臆病者と何度も非難を浴びせたが（彼自身は非常に傲慢な男で、ローマ人をひどく軽蔑していた）、騎兵隊のプデンスという名の男が、相手の言葉とその厚かましさ、そしておそらくは相手の背丈の低さに対する軽率な傲慢さから、相手に向かって走り出し、他の点では手ごわかったが、不運に見放された。というのは、彼が倒れたので、倒れたところをヨナタンが駆け寄ってきて喉を切り裂き、それから死体の上に立ち、血まみれの剣を振り回し、左手で盾を振り回し、ローマ軍に何度も喝采を送り、死者を喜び、ローマ軍をからかった。ついに百人隊長のプリスコスが、彼が飛び跳ねて馬鹿騒ぎをしているところに矢を放ち、彼を貫いた。それに対して、ユダヤ人とローマ人の両方が、それぞれ別の理由で叫び声を上げた。そこでヨナタンは傷の痛みでめまいがして、敵の死体の上に倒れ込んだ。これは、戦争で成功した人々に、正当な理由もなく、突然復讐が降りかかることがあるという明白な例であった。

### 第3章

> ユダヤ人が考案した、多くのローマ人を焼き殺した策略について。また、ローマ市内で起こった恐ろしい飢餓についても記述。

1\. ところが、神殿にいた反乱分子は毎日、土手にいた兵士たちを撃退しようと公然と試み、前述の月 \[パネムスまたはタムズ\] の 27 日には、次のような策略を企てた。彼らは西側の回廊14 の 梁とその下の屋根の間にある部分を乾いた材料で満たし、またアスファルトとピッチも詰め、それから、苦労に疲れたかのようにその場所から退いた。このやり方で、激しい感情に駆られたローマ人の中でも最も無分別な者の多くが、彼らが退くのを必死に追いかけ、梯子を回廊にかけ、突然そこに登った。しかし、彼らのうちの賢明な者は、ユダヤ人のこの説明のつかない撤退を理解すると、以前いた場所に立ち止まった。しかし、回廊は梯子を上った者たちでいっぱいだった。そのとき、ユダヤ人たちはそのすべてに火をつけた。そして、突然、あらゆるところで炎が噴き出すと、危険から逃れていたローマ人は、非常に大きな驚きに襲われた。危険の真っ只中にいる人々も同様に、非常に困惑していた。それで、自分たちが炎に囲まれていることに気づいたとき、彼らのうちの何人かは町に後ろ向きに身を投げ、何人かは敵の中に飛び込んだ。また、多くの者は仲間のところに飛び降り、手足を粉々に砕いた。しかし、こうした暴力的な手段を取ろうとした者の多くは、火によって阻止された。中には自分の剣で火を防いだ者もいた。しかし、突然、火は、そうでなければ死んでいたであろう人々を囲むほどにまで広がった。しかし、カエサル自身は、多くの人々を救出する方法がなかったので、命令もなしにそこに駆けつけたにもかかわらず、このようにして死んだ人々に同情せずにはいられなかった。しかし、これは滅ぼされた者たちにとって、いくらか慰めとなった。皆が、その死の責任を負わされたその人物の悲嘆を見ることができたからである。その人物は、彼らに向かって公然と叫び、飛び上がって、周囲の者たちに、彼らを救うために全力を尽くすよう勧めた。こうして、彼らは皆、カエサルのこの言葉と意図を墓碑として携え、明るく死んだ。確かに、広い回廊の壁の中に退避し、火を免れた者もいたが、そのときユダヤ人に包囲された。彼らは長い間ユダヤ人に抵抗したが、それでもユダヤ人に傷つけられ、ついには皆倒れて死んだ。

2\. 最後に、彼らの中にいたロンガスという名の若者が、この悲しい事件の記念品となった。亡くなった者全員が記念碑に値するが、この男は他の誰よりも記念碑に値するようだった。ユダヤ人たちはこの男の勇気を称賛し、さらに彼を殺したいと望んだ。そこで彼らは、命の保証を与えて、彼らに下って来るよう説得した。しかし、彼の兄弟コルネリウスは、逆に、彼自身の栄光もローマ軍の栄光も汚すなと説得した。彼はこの最後の忠告に従い、両軍の前で剣を振り上げ、自ら命を絶った。しかし、火に囲まれた者の中に、アルトリウスという一人がいて、彼は巧妙な手口で逃げた。なぜなら、彼は同じテントで寝ていた仲間の兵士の一人ルキウスを大声で呼び、「もしあなたが来て私を迎えてくれるなら、私はすべての財産をあなたに相続させる」と言ったからである。すると、彼はすぐに駆け寄って彼を迎えた。アルトリウスは彼の上に身を投げ出して自分の命を救ったが、彼を迎えた者は相手の体重で石畳に激しく打ち付けられ、即死した。この悲惨な事故はローマ人をしばらく悲しませたが、それでもなお将来に対する警戒を強め、ユダヤ人の妄想に対する有利にもなった。ユダヤ人は、その場所や住民の性質を知らないために、その妄想によって大きな損害を受けたのである。さて、この回廊は、ヨハネの塔まで焼失した。ヨハネは、クシストゥスに通じる門をめぐってシモンと戦った際にこの塔を建てた。ユダヤ人はまた、回廊に上った者を滅ぼした後、その回廊の残りの部分を神殿から切り離した。しかし翌日、ローマ人は北の回廊を東の回廊まで完全に焼き払った。東の回廊の共通の角は、ケドロンと呼ばれる谷につながり、その上に建てられていた。そのため、その深さは恐ろしいほどでした。これが当時の神殿の状態でした。

3\. さて、市内で飢餓で死んだ人々の数は膨大で、彼らが経験した悲惨さは言葉に尽くせないほどでした。なぜなら、どこかに何か食べ物の影が少しでも見えれば、すぐに戦争が始まり、親友たちがそれをめぐって互いに戦い、お互いから最もみじめな生活の糧を奪い合うからです。死にゆく人々に食べ物がないとは誰も信じようとしませんでしたが、強盗たちは彼らが死ぬときに、誰かが懐に食べ物を隠し、死んだふりをしていないかと捜索しました。いや、強盗たちは欠乏にあきれ、狂犬のようによろめき、よろめきながら走り回り、酔っ払いのように家のドアにぶつかりました。また、彼らは非常に困窮していたため、同じ日に同じ家に2、3回も押し入りました。さらに、彼らの飢えは耐え難いものだったので、彼らはあらゆるものをかみ砕かざるを得なかったが、最も汚らしい動物でさえも触れようとしないものを集め、それを食べるのを我慢した。ついには、彼らは帯や靴も手放さなかった。盾に付いていた革さえも剥がしてかじった。古い干し草の切れ端さえも、ある人たちの食べ物となった。また、ある人たちは繊維を集め、ごく少量を4アテネ（ドラクマ）で売った。しかし、なぜ私は飢餓が人々にもたらした、無生物を食べるという恥知らずな厚かましさについて記述する一方で、ギリシャ人にも蛮族にも歴史にない事実を語ろうとしているのだろうか 。それについて話すのは恐ろしいし、聞いても信じがたいことだ。私は実際、後世にこれほど不吉なことを伝えていると思われないように、わざとこのわが国の災難を省いたが、私の時代には数え切れないほど多くの目撃者がいる。それに、この時祖国が経験した悲惨さを抑えたことに対して、祖国が私に感謝する理由はほとんどなかったでしょう。

4\. ヨルダン川の向こうに、マリアという名の女性が住んでいました。彼女の父はエレアザルで、ベテゾブ村の出身です。ベテゾブはヒソプの家を意味します。彼女は一族と富で名声を博し、他の群衆とともにエルサレムに逃げ、その時は彼らとともにそこで包囲されていました。この女性のその他の所持品、つまりペレアから持ち出して町に移したものは、すでに押収されていました。彼女が蓄えていたものや、なんとか取っておいた食べ物も、毎日彼女の家に駆け込んできた強欲な番兵に奪われていました。このことでこの哀れな女性は激怒し、強欲な悪党たちを頻繁に非難したり呪ったりして、彼女に対する彼らの怒りをかき立てていました。しかし、彼女が自分自身に対して起こした憤りからか、彼女の境遇への同情からか、彼らのうちの誰も彼女の命を奪おうとはしなかった。そして、もし彼女が何か食べ物を見つけたとしても、彼女は自分の労働が自分のためではなく他人のためであることを悟った。そして、飢餓が彼女の内臓と骨髄を突き刺し、彼女の情熱が飢餓そのものを超越するほどに燃え上がる中、もはや彼女にはこれ以上の食べ物を見つける方法がなくなっていた。彼女は自分の情熱と自分が置かれている窮状以外のことは考えなかった。そこで彼女は非常に不自然なことを試みた。そして、自分の乳房を吸っている幼い息子をつかみ上げ、こう言った。「ああ、この哀れな子よ！この戦争、この飢饉、この暴動で、誰のためにお前を守ればいいのだ？ローマ人との戦争に関して言えば、彼らが我々の命を守れば、我々は奴隷になるしかない。この飢饉もまた、奴隷になる前に我々を破滅させるだろう。しかし、この暴動を起こす悪党どもは、他の二人よりも恐ろしい。さあ、私の糧となり、この暴動を起こす悪党どもを怒らせ、世間の物笑いとなりなさい。それが、我々ユダヤ人の災難を完遂するのに今欠けているすべてなのだから。」こう言うとすぐに、彼女は息子を殺し、それから焼いて、半分を食べ、もう半分を自分のそばに隠しておいた。すると、すぐに反乱軍がやって来て、この食べ物のひどい臭いを嗅ぎつけ、どんな食べ物を用意したか見せなければ、すぐに喉を切ると脅した。彼女は、彼らのために非常に良い分を取っておいたと答え、息子の残りを覆い隠した。そこで彼らは恐怖と驚きに襲われ、その光景に驚いて立ち尽くした。彼女は彼らに言った。「これは私の息子です。そして、起こったことは私自身の仕業です。さあ、この食べ物を食べなさい。私自身が食べたのですから。女性よりも優しいふりをしたり、あるいは母親よりも慈悲深い者よ。しかし、あなたがそんなに几帳面で、私が半分食べたのにこの私の供え物を忌み嫌うなら、残りも私のために取っておけ。」その後、男たちは震えながら出て行った。これほど恐れたことは他にない。そして、なんとか残りの肉を母親に残した。すると、町全体がこの恐ろしい出来事で溢れ、誰もがこの悲惨な状況を目の当たりにすると、まるでこの前代未聞の行為を自分たちがやったかのように震え上がった。このように飢餓に苦しむ人々はとても死にたがり、すでに死んでいた人々は、そのような悲惨な話を聞くことも見ることもないほど長く生きていなかったので、幸いだとみなされた。

5\. この悲しい出来事はすぐにローマ人に伝えられたが、彼らの中にはそれを信じられなかった者もいれば、ユダヤ人が苦しんでいることを哀れに思った者もいた。しかし、これによって我々の国に対して通常よりも激しい憎しみを抱くようになった者も多かった。しかし、カエサルは、この件に関して神の前で弁解し、ユダヤ人に平和と自由を与え、彼らの以前の横柄な習慣をすべて忘れ去ることを提案したが、彼らは和平の代わりに反乱を、平和の代わりに戦争を、そして飽食と豊かさの代わりに飢饉を選んだのだ、と言った。彼らは我々がこれまで守ってきたあの神殿を自らの手で焼き払い始めたのだから、このような食べ物を食べるのは当然だ。しかし、自分の子供を食べるというこの恐ろしい行為は、祖国そのものの転覆によって覆い隠されるべきであり、人々は、母親たちがこのようにして養われているこのような都市を、居住可能な地球上の太陽の見える場所に残すべきではない。このような食物は、母親たちよりも父親たちが食べるのにふさわしいが、彼らはこのような悲惨な状況に耐えた後も、我々に対して依然として戦争状態にあるのだから。そして、彼はこう言うと同時に、これらの人々が置かれている絶望的な状況について考えていた。また、このような苦しみに耐えた後で、このような人々が冷静さを取り戻すことは期待できない。おそらく、そのような苦しみを避けるためだけに、彼らは悔い改めたのである。

### 第4章

> 堤防の建設が完了し、破城槌が運び込まれたが、何もできなかったため、ティトゥスは神殿の門に火をつけるよう命令を出した。その後間もなく、彼の同意に反して、聖なる家自体が焼き払われた。

1\. そして今、2つの軍団がルース\[アブ\]の月の8日目にその壁の防御を完了した。そこでティトゥスは破城槌を持ってきて内陣の西側の建物に向けるよう命令した。なぜなら、破城槌が運ばれる前に、他のすべての機械の中で最も頑丈なものが6日間休むことなく壁を叩き続け、何の痕跡も残さなかったからである。しかし、石の巨大な大きさと強い結合は、その機械や他の破城槌よりも優れていた。他のローマ人は確かに北門の基礎を掘り起こし、苦労の末に最も外側の石を取り除きましたが、門は内側の石によって支えられ、無傷のまま立っていた。機械やカラスによるそのような試みに絶望した作業員が、はしごを回廊に運び込むまで。ユダヤ人は彼らがそうするのを邪魔しなかったが、彼らが立ち上がると、彼らに襲い掛かり、戦った。彼らは梯子を突き落とし、真逆の方向に投げ飛ばした。また、梯子を降りてきた者を多く殴り、盾で身を守る前に剣で殺した。さらに、梯子が武装した兵士でいっぱいのときに、梯子のいくつかを上から投げ落とした。同時にユダヤ人も大虐殺されたが、旗を掲げていた者たちは、旗が盗まれるのを許すのは恐ろしいことであり、自分たちの大きな恥辱となると考え、旗のために懸命に戦った。しかし、ユダヤ人はついにこれらの兵器を手に入れ、梯子を上った者たちを破壊した。残りの者たちは、殺された者たちの苦しみに非常に怯え、撤退した。ローマ人のうち、死ぬ前に良い功績を残さずに死んだ者は一人もいなかったが。反乱軍のうち、以前の戦いで勇敢に戦った者たちは、今や同様のことをした。彼らに加えて、暴君シモンの兄弟の息子エレアザルもそうした。しかし、ティトゥスは、外国の神殿を救おうとする彼の努力が兵士たちの損害につながり、さらには殺害されることに気づいたので、門に火をつけるよう命令を出した。

2\. その間に、エマオから来たシモンの護衛の中で最も血なまぐさいアナヌスと、マガダトゥスの息子アルケラオスが彼のもとに脱走した。彼らは、ユダヤ人が征服者だった時代にユダヤ人を離れたので、まだ許されるだろうと期待していた。ティトゥスは、彼らの狡猾な策略としてこれに異議を唱えた。また、ユダヤ人に対する彼らの他の蛮行について聞いていたので、急いで二人を殺そうとした。彼は彼らに、彼らが極度の苦難に陥ったために脱走に追い込まれただけで、自らの善意で脱走したのではない、彼ら自身の町はすでに彼らによって火をつけられ、その火の中から彼らは急いで逃げ出したのだから、彼らは救われるに値しない、と言った。しかし、脱走者に約束した安全は彼の憤りを克服し、彼はそれに従って彼らを解雇したが、他の人々に与えたのと同じ特権は彼らに与えなかった。そして兵士たちはすでに門に火をつけており、門の上にあった銀の炎はすぐに門の中の木材に伝わり、そこから突然燃え広がり回廊を焼き尽くした。ユダヤ人たちは周囲にこの火が燃えているのを見て、体とともに意気消沈し、あまりの驚きに、誰一人として身を守ろうとも火を消そうともせず、ただ黙って傍観するだけだった。しかし、彼らは今燃えているものが失われたことを悲しむことはなく、それによって今後のことを考えて賢くなるどころか、聖なる家自体がすでに燃えているかのように、ローマ人に対する怒りをかき立てた。この火はその日も翌日も燃え続けた。兵士たちは周囲の回廊を一度にすべて焼くことはできず、少しずつ焼くしかなかったからである。

3\. しかし、翌日、ティトゥスは軍の一部に火を消し、軍団が楽に進軍できるよう道を作るよう命じ、自らは指揮官たちを集めた。集まったのは、全軍の指揮官ティベリウス・アレクサンダー、第5軍団の指揮官セクストゥス・ケレアリス、第10軍団の指揮官ラルキウス・レピドゥス、第15軍団の指揮官ティトゥス・フリギウスの6人の主要人物であった。また、アレクサンドリアから来た2軍団の指揮官エテルニウス、ユダヤの総督マルクス・アントニウス・ユリアヌスも同席していた。その後、残りの総督と護民官全員が集まった。ティトゥスは彼らに、聖なる家についてどうすべきか助言を求めるよう提案した。彼らのうちのある者は、戦争のルールに従って行動し、それを破壊するのが最善の方法だと考えた。なぜなら、ユダヤ人は、その家が立っている限り、決して反乱をやめないだろうからである。ユダヤ人は皆、その家に集まっていたのである。他の者たちは、ユダヤ人がそこを離れ、誰も武器を置かなければ、彼はそれを救うことができるだろう、しかし、もし彼らがそこに侵入し、さらに戦うなら、彼はそれを焼き払えるだろう、という意見であった。なぜなら、その場合、それは聖なる家ではなく、要塞と見なされることになるからである。そして、それを焼くという不敬な行為は、それを強制した者たちのものであり、彼らには属さないからである。しかし、ティトゥスは、「ユダヤ人がその聖なる家に侵入し、そこから我々と戦うとしても、我々は、人間自身ではなく、無生物に対して復讐すべきではない」と言った。そして、彼は、そのような大規模な建造物を焼き払うことは絶対に賛成しない、なぜなら、それはローマ人自身にとって害になるが、それが存続する限り、彼らの政府にとって飾り物となるからである。そこで、フロント、アレクサンダー、ケレアリスはその宣言に勇気づけられ、ティトゥスの意見に同意した。その後、この集会は解散され、ティトゥスは指揮官たちに、残りの軍は動かないように、しかし、この攻撃で最も勇敢な者を使うようにと命令した。そこで、彼は、部隊から選ばれた選抜された兵士たちに、廃墟を通り抜けて火を消すように命じた。

4\. この日、ユダヤ人たちは疲れ果て、動揺していたため、攻撃を控えたのは事実である。しかし翌日、彼らは全軍を集め、東門から神殿の外庭を守る者たちに大胆に突撃した。これはその日の2時頃のことであった。これらの守備隊は勇敢に攻撃を受け、盾で身を守り、あたかも壁のようにして、部隊を密集させた。しかし、彼らがそこに長く留まることはできず、突撃してくる多数の者たちと彼らの激情に圧倒されるであろうことは明らかであった。しかし、カエサルはアントニアの塔から、この部隊が敗走しそうであるのを見て、彼らを支援するため、選りすぐりの騎兵を派遣した。そこでユダヤ人たちは攻撃に耐えることができず、最前線にいた者たちが虐殺されると、残りの者たちの多くが敗走した。しかし、ローマ軍が撤退すると、ユダヤ人たちは彼らに襲い掛かり、戦いを挑んだ。そして、ローマ軍が再び襲い掛かると、彼らは再び撤退した。そして、その日の午後五時ごろ、彼らは圧倒され、神殿の内庭に閉じこもった。

5\. そこでティトゥスはアントニアの塔に退き、翌日の早朝に全軍を率いて神殿を襲撃し、聖なる家の周囲に陣取ることを決意した。しかしその家については、神は確かにずっと前にそれを焼く運命にしていた。そして今、時代の巡りに従ってその運命の日が来た。それはルウス\[アブ\]の月10日であり、その日、その家は以前バビロン王によって焼かれた。しかし、この炎はユダヤ人自身から生じ、彼らによって引き起こされた。ティトゥスが退くと、反乱軍はしばらく静まり、その後再びローマ軍を攻撃した。そのとき、聖なる家を守る者たちは、神殿の内庭を燃やしている火を消す者たちと戦った。しかし、このローマ軍はユダヤ人を敗走させ、聖なる家そのものまで進軍した。そのとき、兵士の一人が、命令を待つこともなく、また、このような大事業に何の心配も恐れもせず、ある種の神の怒りに駆られて、燃えている材料をいくらかひったくると、別の兵士に持ち上げられて、聖なる家の北側にある周囲の部屋への通路となっている金色の窓に火をつけた。炎が上がると、ユダヤ人たちは、このような強大な災難に必要な大騒ぎをし、それを防ぐために一斉に駆けつけた。そして、今や彼らは、聖なる家が滅びようとしていたので、もはや命を惜しまず、いかなるものにもその力を抑えられなかった。彼らがその家の周りにこれほどの警備をしていたのは、聖なる家のためだった。

6\. さて、ある人物がティトゥスのところに駆け寄って、この火事のことを告げた。ティトゥスは最後の戦いの後、テントで休んでいた。そこで彼は大急ぎで立ち上がり、そのまま聖なる家に駆け寄って火を消した。彼の後には指揮官全員が続き、その後ろには各軍団が大驚いて続いた。こうして、大軍の無秩序な動きに当然のごとく、大騒ぎと騒動が起こった。そこでカエサルは、戦っている兵士たちに大声で呼びかけ、右手で合図して、火を消すように命じた。しかし、カエサルが大声で話したにもかかわらず、彼らは別の方法でより大きな騒音によってすでに耳がかすんでいたため、彼の言うことを聞かなかった。また、カエサルが手で合図しても、彼らのうちのある者は戦いに、またある者は激情に気を取られていたため、注意を払わなかった。しかし、そこに駆けつけた軍団は、いかなる説得も脅迫も彼らの暴力を抑えることができず、この時、各自の激情が指揮を執っていた。彼らが神殿に群がると、彼らの多くは互いに踏みつけられ、多くの者は、まだ熱く煙を上げている回廊の廃墟に倒れ、彼らが征服した者たちと同じように悲惨な形で滅ぼされた。そして、彼らが聖なる家に近づくと、シーザーの反対の命令をまったく聞いていないかのように振る舞い、彼らの前にいる者たちに火をつけるよう促した。反乱者たちは、すでに大きな苦境に陥っていたため、火を消すために協力する余裕がなく、至る所で殺され、至る所で殴打された。民衆の大部分は弱く武器を持たず、捕らえられたところではどこでも喉を切り裂かれた。祭壇の周囲には死体が積み重なっており、祭壇 に上る階段には大量の血が流れ、祭壇の上で殺された死体もそこに落ちた。

7\. さて、カエサルは兵士たちの熱狂的な怒りを抑えることができず、火はますます燃え広がったので、指揮官たちとともに神殿の聖域に入り、そこにある物を見て、外国人の記録に残っている物よりはるかに優れており、我々自身が自慢し信じていた物より劣らないことを知った。しかし、炎はまだ内部にまで達しておらず、聖なる家の周りの部屋をまだ燃やしていたので、ティトゥスは神殿自体はまだ救われるかもしれないと考えて、急いでやって来て兵士たちに火を消すよう説得し、百人隊長リベラリウスと彼の周囲にいる槍兵の一人に、抵抗する兵士たちを杖で叩いて鎮圧するよう命じた。しかし、彼らの情熱は、カエサルに対する尊敬と、彼らを禁じたカエサルに対する恐怖、ユダヤ人に対する憎しみ、そしてユダヤ人と戦うというある種の激しい傾向に対しては、あまりにも激しすぎた。さらに、略奪の希望は、内部のすべての場所がお金でいっぱいであり、その周囲がすべて金でできているという意見を持つように多くの人を駆り立てた。さらに、その場所に入った者の一人が、兵士たちを制止するために急いで駆け出したカエサルを阻止し、暗闇の中で門の蝶番に火を放った。そのため、司令官たちが退却し、カエサルも彼らとともに退却し、誰も外にいる者に火をつけることを禁じなくなったとき、聖なる家自体からすぐに炎が噴き出した。こうして、カエサルの承認なしに聖なる家は焼け落ちた。

8\. さて、このような作品が破壊されたことを嘆くのは当然である。なぜなら、それは、その奇妙な構造と大きさ、それに与えられた莫大な富、そしてその神聖さによる輝かしい評判の両面において、私たちが見聞きしたすべての作品の中で最も素晴らしいものであったからである。しかし、そのような人は、それがそうなるように定めたのは運命であり、生き物についても、作品や場所についても避けられないことである、という考えで自分を慰めることができるかもしれない。しかし、そこに記されているこの期間の正確さには驚かざるを得ない。なぜなら、私が前に述べたように、聖なる家が以前バビロニア人によって焼かれたのと同じ月と日が今観察されたからである。さて、ソロモン王によって築かれた最初の基礎からウェスパシアヌス帝の治世の2年に起こったこの破壊までの年数は、1,130と7ヶ月と15日とされている。キュロス王の治世の二年目にハガイによって二度目の建築が行われてから、ウェスパシアヌス帝によって破壊されるまで、六百三十九年と四十五日が経過した。

### 第5章

> 聖なる家の大火災でユダヤ人が経験した大苦難。偽預言者と、この破壊に先立つ兆候について。

1\. 聖なる家が燃えている間、手近なものはすべて略奪され、捕らえられた一万人が殺された。年齢を問わず同情の念や、厳粛な敬意は見られず、子供、老人、俗人、司祭が皆同じように殺された。そのため、この戦争はあらゆる人々を巻き込み、命乞いをした者も、戦って身を守った者も、皆、破滅に追いやった。炎は遠くまで運ばれ、殺された者のうめき声とともに反響した。この丘は高く、神殿の工事は非常に大規模だったため、街全体が燃えているように思われた。この騒音よりも大きく恐ろしいものは想像できない。なぜなら、一斉に行進していたローマ軍団の叫び声と、今や火と剣に囲まれた反乱軍の悲痛な叫び声が同時に聞こえたからである。上に残った民も敵に打ち負かされ、非常に動揺し、自分たちが受けている災難に悲痛なうめき声をあげた。町にいた群衆も丘の上にいた人々と共にこの叫びに加わった。さらに、飢餓で衰弱し、口がほとんど閉ざされていた多くの人々も、聖なる家の火を見ると、全力を尽くしてうめき声や叫び声をあげた。ペレア 17 も、周囲の山々と同様にその反響を返し、全体の騒音の勢いを増した。しかし、この混乱よりも悲惨さの方がひどかった。というのは、神殿が立っている丘自体が、そのあらゆる部分が火で満たされているように熱く沸騰し、血の量は火よりも多く、殺された者の数は殺した者よりも多かったと思われるからだ。地面はどこにも見えず、そこに死体が横たわっていた。しかし兵士たちは、逃げる者たちに襲いかかりながら、死体の山を踏み越えていった。そして今、ローマ軍によって神殿の内庭から追い出された盗賊の大群は、外庭に入り、そこから町に入るのに苦労し、残りの民衆は外庭の回廊に逃げ込んだ。祭司たちのうちの何人かは、聖なる家から釘を引き抜いた 。 そこには鉛でできた台座のついた聖なる神殿があり、矢の代わりにローマ軍に矢を放った。しかし、そうしても何の得もなかったし、火が彼らの上に燃え上がったので、彼らは幅8キュビトの城壁の方へ退き、そこに留まった。しかし、彼らの中の高位の2人は、ローマ軍に寝返れば助かったかもしれないし、勇気を出して他の者と共に運命を共にしたかもしれないのに、火の中に身を投げ、聖なる神殿と共に焼かれた。彼らの名前はベルガスの子メイラスとダレウスの子ジョセフであった。

2\. そしてローマ人は、聖なる家の周囲をそのままにしておくのは無駄だと判断して、その場所すべてを焼き払い、また、東側と南側の 2 つを除く回廊と門の残骸も焼き払った。しかし、その 2 つは後に焼かれた。彼らはまた、莫大な金額のお金、莫大な数の衣服、その他の貴重な品々が保管されていた宝物庫も焼き払った。簡単に言えば、ユダヤ人の富のすべてがそこに積み上げられ、一方で裕福な人々はそこに部屋を建てていたのである。兵士たちはまた、神殿の外庭にあった回廊の残りにもやって来た。そこには、女性や子供、そして大勢の人々が約 6,000 人ほど逃げていた。しかし、シーザーがこれらの人々について何か決定を下す前、あるいは指揮官に彼らに関する命令を与える前に、兵士たちは激怒し、回廊に火を放った。その結果、彼らのうちの何人かは頭から身を投げて命を落とし、何人かは回廊で焼死した。また、誰一人として命を逃れることができなかった。これらの人々の破滅の原因は、偽預言者19 であった。その預言者は、まさにその日に市内で、神が彼らに神殿に登るよう命じ、そこで救出の奇跡的な兆候を受けるだろうと公に布告したのである。当時、暴君たちに買収された多数の偽預言者が、人々に神の救出を待つべきだと告げ、人々に騙していた。これは、人々が逃亡しないようにするため、また、そのような希望によって恐れや不安から解放されるためであった。さて、逆境にある人は、そのような約束に容易に従うものである。というのは、そのような誘惑者が、患者を苦しめる苦難から解放されると信じ込ませるとき、患者はそのような解放への希望に満ちているからである。

3\. こうして、みじめな民は、これらの詐欺師や神自身を偽る者たちに説得され、非常に明白で、自分たちの将来の破滅をはっきりと予言するしるしに注意を払わず、信じもせず、見る目も考える心もない、夢中になった人々のように、神が彼らになさった告発に耳を傾けなかった。 こうして、剣に似た星20が町の上に立ち、彗星のような姿が 1 年間続いた。 また、ユダヤ人の反乱の前、戦争に先立つ騒動の前にも、人々が大勢で種を入れないパンの祭りに集まったとき、クサンティコスの月21 \[ニサン\] の 8 日、夜の 9 時に、祭壇と聖なる家の周囲に非常に強い光が輝き、明るい昼間のように見えた。それは 30 分間続いた。この光は、無知な者には良い兆しと思われたが、聖なる書記官たちは、その直後に起こる出来事の前兆であると解釈した。同じ祭りのとき、大祭司に連れられて犠牲に捧げられた雌牛が、神殿の真ん中で子羊を産んだ。さらに、内陣の東の門は、神殿の中央にあって、神殿の東の門のすぐ外側に、子羊を産んだ。 神殿の中庭は真鍮でできていて非常に重く、20人の男たちが苦労して閉め、鉄で補強された土台の上にあり、1枚の石でできた堅い床に非常に深くボルトが締められていたが、夜中の6時ごろに門がひとりでに開くのが見られた。そこで神殿の番兵たちが駆けつけて神殿の守衛長に知らせた。守衛長はそこに行き、非常に苦労しながら門を再び閉めることができた。これはまた、神がそれによって彼らの幸福の門を開いたかのような、非常に幸せな奇跡であると一般の人々に思われた。しかし、学識のある人々は、彼らの聖なる家の安全がひとりでに崩れ、門が敵に有利になるように開かれたことを理解した。そこで彼らは、その合図は彼らに迫っている荒廃の前兆であると公に宣言した。これらのほか、その祭りの数日後、アルテミシウス月（ヤール）の21日には、ある驚くべき信じられない現象が起こった。その出来事は、目撃者が語らなかったら、またその後に起こった出来事がそのような警告に値するほど重大なものでなかったら、単なる伝説のように思われただろう。なぜなら、日が沈む前に、戦車と鎧を着た兵士の軍団が雲の中を走り回り、都市を取り囲んでいたからだ。さらに、私たちがペンテコステと呼ぶその祭りでは、祭司たちが慣例通り、夜に神殿の内庭に入り、神聖な奉仕を行っていたとき、まず最初に震えを感じ、大きな音が聞こえ、その後、大勢の人が「ここから立ち去ろう」と言っているような声が聞こえたという。しかし、さらに恐ろしいのは、アナヌスの息子で平民で農夫のイエスが、戦争が始まる4年前、町が非常に平和で繁栄していたときに、神殿で神のために幕屋を建てるのが私たちの習慣である祭りに来たことです。 突然、大声で叫び始めた。「東からの声、西からの声、四方からの声、エルサレムと聖なる家に対する声、花婿と花嫁に対する声、そしてこの民全体に対する声だ！」これが、昼も夜も町のすべての路地を歩き回っているときの彼の叫びだった。しかし、民衆の中で最も著名な何人かは、彼のこの恐ろしい叫びに非常に憤慨し、男を捕らえて何度も厳しいむち打ちを加えた。しかし、男は自分の意見を言うことも、彼を叱責する人たちに特有のことを言うこともせず、以前叫んだのと同じ言葉を言い続けた。そこで、私たちの支配者たちは、これが男の神の怒りの一種であると推測し、彼をローマの総督のところに連れて行き、骨がむき出しになるまで鞭打たれた。しかし、彼は自分のために嘆願することも涙を流すこともせず、鞭が打たれるたびに、できるだけ悲しげな声で「エルサレムに災いあれ！」と答えた。アルビヌス（当時は総督だった）が彼に「あなたは誰ですか？どこから来たのですか？なぜそのような言葉を発したのですか？」と尋ねたとき、彼は自分の言ったことに何の返答もせず、それでも憂鬱な歌を歌い続けたので、アルビヌスは彼を狂人だと思い、彼を解雇した。さて、戦争が始まるまでの間、この男は市民の誰にも近づかず、そう言っているところを市民に見られなかった。しかし、彼は毎日、あたかもそれが彼の計画された誓いであるかのように、「エルサレムに災いあれ！」という悲しげな言葉を発していた。また、毎日彼を殴る者に対して悪口を言うことも、彼に食べ物を与える者に対して良い言葉をかけることもなかった。しかし、これはすべての人々に対する彼の返答であり、実際、これから起こることの悲しげな予兆にほかならなかった。彼のこの叫びは祭りで最も大きく、彼はこの歌を7年5ヶ月間、しわがれたり疲れたりすることなく歌い続けた。そして、我々の包囲戦で彼の予兆が本格的に実現するのを見たとき、歌は止んだ。なぜなら、彼が城壁の周りを回っているとき、彼は最大限の力で叫んだからだ。「悲惨だ、再び町に、人々に、そして聖なる家に！」そして、最後に「悲惨だ、私自身にも！」と付け加えたちょうどその時、機械の1つから石が飛び出し、彼を襲い、すぐに殺した。そして、彼がまさに同じ予兆を口にしているとき、彼は息を引き取った。

4\. さて、これらのことをよく考えてみると、神は人類を守り、あらゆる方法で人類の生存のために何をすべきかを人類に予示しておられるが、人間は狂気と自発的に自ら招いた悲惨さによって滅びることがわかる。というのは、ユダヤ人はアントニアの塔を破壊して神殿を四角形にし、同時に彼らの聖なる預言に「彼らの神殿が四角形になったとき、彼らの町と聖なる家は陥落する」と書いていたからである。しかし、この戦争を遂行するにあたり、彼らを最も奮い立たせたのは、彼らの聖なる書物にも記されていた「そのころ、彼らの国から一人が居住可能な地球の統治者になる」という曖昧な預言であった。ユダヤ人はこの予言を特に自分たちに当てはまるものと受け止め、多くの賢者はそのことでその決意を誤ってしまった。さて、この神託は、ユダヤの皇帝に任命されたウェスパシアヌスの統治を確かに示していました。しかし、人間は運命を事前に知っていても、それを避けることはできません。しかし、これらの人々は、これらの合図のいくつかを自分の好みに従って解釈し、いくつかを完全に軽蔑しました。その結果、彼らの狂気は、彼らの都市の占領と彼ら自身の破滅の両方によって明らかになりました。

### 第6章

> ローマ人が旗を神殿に掲げ、ティトゥスに歓呼の声をあげた様子。ユダヤ人が慈悲を懇願したとき、ティトゥスが彼らに語った言葉。ユダヤ人がそれに対してどのような返答をしたか。そしてその返答がティトゥスの憤りをいかに引き起こしたか。

1\. さて、反乱軍が町に逃げ込み、聖なる神殿とその周囲のすべての建物が焼き払われたとき、ローマ軍は旗を神殿に持ち込み、 24東の門に旗を立てた。そこで彼らは犠牲を捧げ、ティトゥス帝を25大いに歓喜した。そして今や兵士たちは略奪で得た戦利品を大量に手に入れ、シリアでは金一ポンドが以前の半分の値段で売れた。しかし、聖なる神殿の壁の上にじっとしていた祭司たちについて言えば、26 喉が渇いた少年がいた。彼は命の保証としてローマ兵に右手を差し出してほしいと頼み、喉が渇いていると告白した。衛兵たちは彼の年齢と苦境を哀れみ、それに応じて右手を差し出した。そこで彼は自分で降りてきて、水を飲み、彼らのところに来た時に持っていた容器に水を満たし、それから立ち去って自分の友人たちのところへ逃げて行った。衛兵たちは誰も彼に追いつくことができなかったが、それでも彼らは彼の不誠実さを非難した。それに対して彼はこう答えた。「私は約束を破ったのではありません。私が自分に与えた保証は、私があなたたちと一緒にいるためではなく、ただ私が安全に降りてきて水を汲むためだったのです。私はその両方を果たし、それによって約束を忠実に守ったと思っています。」そこで、その子供が騙した人々は彼の狡猾さに感心し、また彼の年齢にも感心した。その後 5 日目に、飢餓で衰弱していた祭司たちが降りてきて、衛兵に連れられてティトゥスのところへ行き、命乞いをした。しかし彼は、彼らに対する赦免の時は過ぎ去っており、彼らだけが正当に救われると期待できるこの聖なる家が破壊されたこと、そして司祭たちが所属する家自体とともに滅びることが彼らの職務にかなうことだ、と答えた。そこで彼は彼らを死刑にするよう命じた。

2\. しかし、暴君たち自身と彼らと共にいた者たちは、四方から包囲され、逃げ場もなく、いわば壁で囲まれていることを知ると、口頭でティトゥスと交渉することを望んだ。そこで、ティトゥスは性格が優しく、町を破壊から守りたいという願いと、盗賊たちが激怒したと考えた友人たちの助言とが相まって、神殿の外庭の西側に陣取った。その側にはクシストゥスの上に門があり、上町と神殿を結ぶ橋があったからである。この橋が暴君たちとカエサルの間にあり、彼らを隔てていた。群衆は両側に立っていた。ユダヤ民族は恩赦を大いに期待してシンランとヨハネの周りに、ローマ人はティトゥスが自分たちの嘆願をどう受け止めるかを大いに期待してカエサルの周りに立っていた。そこでティトゥスは兵士たちに怒りを抑え、矢を放たないように命じ、彼らの間に通訳を置いた。これは彼が征服者であることを示すものであった。そしてまず演説を始め、こう言った。「諸君、諸君は、我が国の惨状にもう飽き飽きしているだろう。諸君は、我々の偉大な力についても、諸君自身の大きな弱さについても、正当な認識を持たず、狂人のように暴力的で無分別なやり方で、諸君の国民、諸君の都市、諸君の聖なる家を破壊しようと企ててきた。諸君は、ポンペイウスが最初に諸君を征服して以来、反乱を止めず、その時以来、ローマ人と公然と戦争をしてきた。諸君は、ローマ軍のごく一部が諸君に十分対抗できるのに、大軍に頼ったのか。同盟者の忠誠心に頼ったのか。そして、我々の支配の境界外に、どんな国があるというのか。ローマ人より先にユダヤ人を助けることを選んだのは誰ですか？あなた方の軍隊は我々の軍隊より強いのですか？いや、あなた方はゲルマン人自身が我々のしもべであることを知っています。あなた方の城壁は我々より強いのですか？頼む、ブリトン人を包囲している大洋の壁よりも大きな障害が他にありますか？それでも、ローマ人の武器を崇拝しています。あなた方は魂の勇気と指揮官の賢明さにおいて我々を上回っていますか？いや、実際、あなた方はカルタゴ人が我々に征服されたことを知らないはずがありません。したがって、あなた方が我々に反抗したのは、我々ローマ人の親切心以外には何もないでしょう。まず第一に、我々はあなた方にこの土地を所有するように与え、次にあなた方の国の王をあなた方に任命し、第三に、あなた方の祖先の法律をあなた方に保持し、あなた方が望むように、あなた方だけで、あるいは他人の間で生きることを許可しました。そして、私たちがあなたに与えたすべての恩恵の中で、神に捧げる貢物を集める許可が私たちの最大の恩恵です27彼に捧げられた他の贈り物とともに、我々はこれらの寄付金を運んだ者たちに責任を問うことも、禁じることもしなかった。ついには、我々の敵であったにもかかわらず、君たちは我々よりも裕福になり、我々の金で我々に対する戦争の準備をしていた。いや、結局のところ、君たちはこれらすべての恩恵を享受していたとき、その莫大な富を、君たちに与えた者たちに向け、無慈悲な蛇のように、君たちに親切にしてくれた者たちに毒を吐いたのだ。だから、君たちはネロの怠惰を軽蔑し、骨折したり脱臼したりした手足のように、その時は静かに横たわり、悪意はあったものの、別の時を待っていたのだろうと思う。そして今、君たちの病気はかつてないほどひどくなり、厚かましく大きな希望が許す限り、君たちの欲望を拡大したのだ。この頃、父がこの国に来たのは、ケスティウスの指揮下であなたがたが行ったことに対する罰を与えるためではなく、あなたがたを戒めるためだった。父があなたがたの国を転覆させるために来たのであれば、あなたがたの源泉に直行し、すぐにこの町を荒廃させたであろう。一方、父はガリラヤとその周辺地域を焼き払い、あなたがたに悔い改める時間を与えた。あなたがたは、この人道的な行為を父の弱さの証拠とみなし、私たちの温和さで厚かましさを養った。ネロがこの世を去った後、あなたがたは最も邪悪な者たちがしたであろうことをし、内紛によって私たちに対して行動するよう自らを鼓舞し、私と父が戦争の準備のためにエジプトへ行ったその時間を悪用した。また、私たちが皇帝になったとき、あなたがたは私たちに対して騒動を起こすことを恥じなかった。それは、私たちが軍の将軍に過ぎなかったとき、私たちがいかに温和であったかをあなたがたが経験していたにもかかわらずである。しかし、政府が我々に移譲され、他のすべての人々がそれに対して沈黙し、外国でさえも使節団を派遣し、我々が政府に加わることを祝福したとき、あなた方ユダヤ人は我々の敵であることを明らかにした。あなた方は、騒乱を起こすのを助けるためにユーフラテス川の向こう側の同胞に使節団を派遣した。あなた方は都市の周囲に新しい壁を築き、暴動が起こり、一人の暴君が他の暴君と争い、あなた方の間で内戦が勃発した。あなた方ほど邪悪な民族にしか起こらないようなことだった。その後、私は父に不本意ながらこの都市にやって来て、父から悲しげな命令を受けた。人々が平和を望んでいると聞いて、わたしはそれを喜んだ。この戦争を始める前に、わたしはあなたたちにこの行為をやめるよう勧めた。あなたたちがわたしと長い間戦っていたときでさえ、わたしはあなたたちを許した。わたしは逃亡者たちに保証として右手を与えた。わたしは約束したことを忠実に守った。彼らがわたしのもとに逃げてきたとき、わたしは捕虜にした多くの人々に同情した。わたしは戦争に熱心な者たちを、彼らを抑えるために拷問した。わたしは不本意ながら、戦争兵器をあなたたちの城壁に持ち込んだ。わたしは、兵士たちがあなたたちを殺戮しようとしたとき、常にあなたたちに対して厳しくするのを禁じた。勝利のたびに、あたかもわたし自身が征服されたかのように、あなたたちを和平に説得した。わたしがあなたたちの神殿に近づいたとき、わたしは再び戦争の法則を離れ、あなたたち自身の聖域を守り、あなたたちの聖なる家をあなたたち自身のために保持するよう勧めた。わたしはあなたたちがそこから静かに退出し、あなたたちの保存のために安全を確保した。いや、もしお前たちがそうしたいのなら、私は他の場所で戦う許可を与えた。それでもお前たちは私の提案を一つ一つ軽蔑し、自らの手でお前たちの聖なる家に火をつけた。そして今、卑劣な奴らよ、口頭で私と交渉したいのか？ かつてはこのような聖なる家だったのに、今は破壊されてしまったのに、何のためにそれを保存しようとするのか？ お前たちの神殿が破壊された今、お前たちは何の保存を望むのか？ お前たちは今もなお、鎧を着てじっと立っているのか？ また、この極限状態にあっても、嘆願者のふりをする気などないのか。ああ、哀れな生き物たち！ お前たちは何を頼りにしているのか？ お前たちの民は死んでしまったのではないか？ お前たちの聖なる家は消えてしまったのではないか？ お前たちの街は私の手中にあるのではないか？ お前たちの命も私の手中にあるのではないか？ お前たちはまだ死ぬことが勇敢なことだと考えているのか？ しかし、私はあなたたちの狂気に倣うつもりはない。もし武器を捨て、私に体を差し出すなら、私はあなたたちの命を許す。そして私は温厚な主人のように振る舞う。治せないものは罰せられ、残りは私自身のために保存されるだろう。」だが、お前たちはまだ私の提案を一つ一つ軽蔑し、自らの手でお前たちの聖なる家に火をつけた。そして今、卑劣な悪党どもよ、口頭で私と交渉したいのか？ かつてはこのような聖なる家だったのに、今は破壊されてしまったのに、何のために救おうとするのか？ 神殿が破壊された今、お前たちは何の保存を望むのか？ だが、お前たちはこの時に鎧を着てじっと立っているのか？ この極限状態にあっても、嘆願者のふりをする気などないのか。 ああ、哀れな生き物たちよ！ お前たちは何を頼りにしているのか？ お前たちの民は死んでいないのか？ お前たちの聖なる家は消え去ったのではないか？ お前たちの街は私の手中にあるのではないか？ お前たちの命も私の手中にあるのではないか？ お前たちはまだ死ぬことが勇敢なことだと考えているのか？ しかし、私はあなたたちの狂気に倣うつもりはない。 お前たちが武器を捨て、死体を私に引き渡すなら、私はあなたたちの命を与えよう。そして私は温厚な一家の主人のように振舞おう。治癒できないものは罰せられ、残りは私自身のために保存されます。」だが、お前たちはまだ私の提案を一つ一つ軽蔑し、自らの手でお前たちの聖なる家に火をつけた。そして今、卑劣な悪党どもよ、口頭で私と交渉したいのか？ かつてはこのような聖なる家だったのに、今は破壊されてしまったのに、何のために救おうとするのか？ 神殿が破壊された今、お前たちは何の保存を望むのか？ だが、お前たちはこの時に鎧を着てじっと立っているのか？ この極限状態にあっても、嘆願者のふりをする気などないのか。 ああ、哀れな生き物たちよ！ お前たちは何を頼りにしているのか？ お前たちの民は死んでいないのか？ お前たちの聖なる家は消え去ったのではないか？ お前たちの街は私の手中にあるのではないか？ お前たちの命も私の手中にあるのではないか？ お前たちはまだ死ぬことが勇敢なことだと考えているのか？ しかし、私はあなたたちの狂気に倣うつもりはない。 お前たちが武器を捨て、死体を私に引き渡すなら、私はあなたたちの命を与えよう。そして私は温厚な一家の主人のように振舞おう。治癒できないものは罰せられ、残りは私自身のために保存されます。」

3\. ティトゥスの申し出に対して、彼らはこう答えた。「決してそうしないと誓ったので、受け入れることはできない。しかし、妻子とともに、自分たちを取り囲む城壁を抜ける許可が欲しい。そうすれば、砂漠に行き、町をティトゥスに任せることができる」。これに対してティトゥスは、彼らがすでに捕虜になっているのに、まるで征服者であるかのように、自分と条件を結ぼうとしていることに憤慨した。そこで彼は、彼らに次のような布告を出すように命じた。「もう脱走兵として出てこないようにし、また、これ以上の安全を期待しないように。今後は誰も容赦せず、全軍で彼らと戦う。できる限り自力で救わなければならない。今後は戦争法に従って彼らを扱う」。そこで彼は兵士たちに、町を焼き払い、略奪するように命令したが、その日は何もしなかった。しかし翌日、彼らは文書保管所、アクラ、評議会の建物、そしてオフラスと呼ばれる場所に火を放った。その時、火はアクラの真ん中にあったヘレナ女王の宮殿にまで燃え広がり、飢餓で破壊された人々の死体でいっぱいの家々とともに、小道も焼け落ちた。

4\. 同じ日に、イザテス王の息子や兄弟たち、そして他の多くの有力な民衆がそこに集まり、自分たちの安全のためにシーザーに右腕を与えてくれるよう懇願した。シーザーは、今残っている者たち全員に非常に怒っていたが、以前の穏健な態度を捨てることはせず、これらの人々を受け入れた。その時、シーザーは確かに彼ら全員を拘留したが、王の息子や親族は拘束し、ローマに連れて行き、彼らの国がローマに忠誠を誓うための人質とした。

### 第7章

> 反乱者たちが多くの悪事を起こし、多くの不幸に見舞われた後、彼らに何が起こったのか。また、カエサルがどのようにして上市都市の支配者になったのか。

1\. すると、反乱軍は、非常に堅固であったため、多くの人が財産を預けていた王宮に突入し、ローマ軍を追い払った。また、王宮に群がっていた約 8,400 人の民衆を皆殺しにし、彼らの所有物を略奪した。さらに、ローマ軍のうち 2 人を生け捕りにした。1 人は騎兵で、もう 1 人は歩兵であった。彼らは歩兵の喉を切り裂き、この一件でローマ軍全体に復讐しようとして、直ちに彼を町中を歩かせた。しかし、騎兵は、ローマ軍の命を救うために何か提案したいことがあると言った。そこで、彼はシモンの前に連れて行かれたが、そこにいたときには何も言うことがなかったので、彼はシモンの指揮官の 1 人であるアルダラスに引き渡され、処罰された。アルダラスは彼の両手を後ろで縛り、両目に帯を巻いた後、首を切ろうとしているかのように、彼をローマ軍の前に連れ出した。しかし、その男は処刑を阻止し、ローマ軍の元へ逃げた。ユダヤ人の死刑執行人が剣を抜いている間に逃げた。敵から逃げ去った後、ティトゥスは彼を殺すことは考えられなかった。しかし、敵に生かされて捕らえられたため、もはやローマ軍の兵士であるに値しないと判断し、武器を取り上げ、所属していた軍団から追放した。これは、恥をかく者にとっては、死刑そのものよりも重い罰であった。

2\. 翌日、ローマ軍は下町から盗賊を追い出し、シロアムに至るまですべてに火を放った。兵士たちは町が破壊されるのを見て本当に喜んだ。しかし、反乱軍が持ち物をすべて持ち去り、上町に退却したため、略奪品は手に入らなかった。彼らはまだ自分たちの犯した悪事を少しも悔い改めておらず、まるでうまくやったかのように横柄だった。町が燃えているのを見て、彼らは陽気な様子で、喜びに満ちた表情を浮かべ、彼らの言うところの、死が彼らの悲惨さを終わらせるだろうと期待していた。したがって、人々は殺され、聖なる家は焼け落ち、町は燃えていたので、敵にはもう何も残っていなかった。しかし、この極限の状況でも、ヨセフスは町の残りを救ってほしいと彼らに懇願するのに疲れることはなかった。彼は彼らの蛮行と不信心について長々と語り、彼らが逃げるための助言を与えたが、それによって彼らに笑われただけで、彼は何も得るものはなかった。彼らは誓いを立てたため投降することを考えられず、四方を囲まれてすでに一種の捕虜になっていたため、広場でローマ軍と戦うだけの力もなかったが、人を殺すことに慣れていたため、それに応じて行動せずにはいられなかった。そこで彼らは都市の前に散り散りになり、ローマ軍に逃亡しようとする者を捕まえるために、その廃墟の中で待ち伏せした。その結果、多くのそのような逃亡者が彼らに捕らえられ、全員殺された。なぜなら、彼らは食糧不足のために逃げるには弱すぎたため、彼らの死体は犬の餌にされたからである。今では、他のあらゆる死は飢餓よりは耐えられると考えられていたので、ユダヤ人は慈悲を得られそうになかったにもかかわらず、ローマ人のもとに逃げ、自ら進んで、殺人的な反乱軍に加わった。また、市内には死体のない場所はなく、飢餓か反乱で殺された死体で完全に覆われていた。そして、あらゆる場所が、その暴動か飢餓で死んだ人々の死体で満ちていた。

3\. それで、暴君たちと彼らといっしょにいた盗賊団を支えていた最後の希望は、地下の洞窟や洞穴にあった。そこに逃げることができたとしても、捜索されることはないと彼らは思っていた。しかし、彼らは、街全体が破壊され、ローマ人が去った後、再び出て彼らから逃げ出そうとしていた。これは彼らの夢に過ぎなかった。なぜなら、彼らは神からもローマ人からも隠れることができなかったからだ。しかし、彼らは地下の隠れ家に頼り、ローマ人自身よりも多くの場所に火を放った。そして、このようにして火をつけられ溝に逃げ込んだ家から逃げた者たちを、彼らは容赦なく殺し、略奪した。そして、もし誰かの食べ物を見つけると、それをつかんで、血とともに飲み込んだ。いや、彼らは今や略奪品をめぐって互いに戦うようになった。そして、もし彼らの破壊がそれを阻止していなかったら、彼らの蛮行は死体そのものの味さえも彼らに感じさせたであろうと私は思わずにはいられない。

### 第8章

> カエサルはどのようにして上市\[シオンの丘\]の周囲に堤防を築き、それが完成すると機械を持ち込むよう命令したのか。そして彼は都市全体を支配した。

1\. さて、カエサルは、上部の都市があまりにも急峻で、堤防を築かなければ陥落できないと悟ると、その工事の各部分を自分の軍隊に分配した。これは、ルース\[アブ\]の月20日のことである。さて、資材の運搬は困難な作業であった。というのも、私がすでに述べたように、都市の周囲100スタルの範囲内にあるすべての木々は、以前の堤防を作るためにすでに枝を切り落とされていたからである。4つの軍団に属する工事は、王宮の向かいの都市の西側に建てられた。しかし、補助軍の全体と、彼らと共にいた残りの群衆は、クシストゥスに\[堤防を築いた\]。そこから彼らは橋と、シモンの塔に至った。シモンは、彼らが互いに戦争をしていたときに、ヨハネに対する要塞としてシモンが建てた塔である。

2\. ちょうどこのとき、イドマヤ人の指揮官たちが密かに集まり、ローマ軍に降伏する案を協議した。そこで彼らはティトゥスに5人の男を送り、自分たちの安全のために右腕を差し出すよう懇願した。ティトゥスは、戦争の大部分がかかっていたイドマヤ人が撤退すれば、暴君たちも屈服するだろうと考え、しぶしぶと遅れた後、彼らの要求に応じ、命の保証を与えて5人を送り返した。しかし、イドマヤ人が出撃の準備をしていると、シモンはそれに気づき、ティトゥスのもとに向かった5人を直ちに殺し、指揮官たちを捕らえて牢に入れた。指揮官たちの中で最も目立っていたのはソサスの子ヤコブであった。しかし、指揮官が奪われて何をすべきか全く分からなくなったイドマヤ人の大群に対しては、彼は監視を命じ、より多数の守備隊で城壁を固めた。しかし、その守備隊は脱走兵に抵抗することができなかった。彼らのうち多数が殺されたが、脱走兵の数はそれよりはるかに多かったからである。彼らは全員ローマ軍に受け入れられたが、それはティトゥス自身が彼らを殺すという以前の命令を怠り、兵士たち自身も彼らを殺すことに飽き、彼らを生かすことでいくらかの金もうけを期待したからである。彼らは民衆だけを残し、残りの大群を妻子もろとも非常に安い値段で売り払った。それは売られた者が多く、買う者が少なかったからである。ティトゥスは、脱走兵は家族を連れて出られるように、一人で来るなと事前に布告していたが、それでも彼はこのような者も受け入れたのである。しかし、彼は彼らの中に罰に値する者がいないか見極めるために、彼らの上に何人かを区別する者を置いた。そして、売られた者の数は実に膨大であったが、民衆のうち四万人以上が救われ、カエサルは彼らをそれぞれ望むところへ放った。

3\. ところが、ちょうどそのとき、祭司のひとりで、テブトゥスの子で、イエスと名乗る者が、カエサルの誓いによって、神殿に保管されていた貴重な品々の一部を渡すという条件で、保護されるという保証を与えられ、神殿から出て、聖なる神殿の壁から、聖なる神殿にあったものと同じ燭台二つ、テーブル、水盤、小瓶をイエスに渡した。すべて純金でできていて、非常に重かった。また、ベール、衣服、宝石、その他、神聖な礼拝に使う貴重な器物も数多くイエスに渡した。神殿の財務官ピネウスも捕らえられ、祭司たちの上着や帯、ヴェールに使うために保管されていた大量の紫や緋色の布、また大量のシナモンやカシア、その他大量の香料を見せた。これらは混ぜて毎日神に香として捧げられていたものだった。 その他にも多くの宝物や神殿の神聖な装飾品が彼に渡された。これらの品々をティトスに渡したことにより、彼はこの男に対して、自ら進んで脱走した者たちに与えたのと同じ赦しを勝ち取った。

4\. そして、ゴルピエウスの月（エルル）の7日、18日後にローマ軍が城壁に兵器を突っ込んだとき、土塁は完成した。反乱軍がいなかったため、ローマ軍の一部は都市を救えないと絶望し、城壁から城塞に退却した。他の一部は地下室に降りたが、それでも大勢のローマ軍が砲台に兵器を突っ込んだ者たちから身を守った。しかし、ローマ軍は数と力で彼らを打ち負かした。そして何よりも重要なのは、ユダヤ人たちがすっかり意気消沈して弱っている間に、喜んで仕事を続けたことである。城壁の一部が破壊され、いくつかの塔が破城槌の衝撃に耐えると、抵抗する者たちは逃げ去り、暴君たちは必要以上に大きな恐怖に襲われた。敵が突破口を越える前に、彼らは完全に驚いて、すぐに逃げ去ろうとした。そして、これまでは邪悪な行いにおいて非常に横柄で傲慢だったこれらの人々が、打ち倒され、震え上がるのを見ることができた。その卑劣な人々の変化を観察することは、心を哀れむほどである。したがって、彼らは、守っている人々を押しのけて、それを突破して逃げるために、自分たちを取り囲むローマの城壁に向かって猛烈に走り回った。しかし、かつて忠実だった者たちが去ったのを見て（実際、彼らは大きな苦難に駆られて逃げたところへ逃げた）、また、他の者たちより先に駆けつけた者たちが西の壁が完全に倒されたと告げたとき、また他の者たちがローマ軍が侵入したと告げたとき、また他の者たちがローマ軍が近くにいて、自分たちを警戒していると告げたときも、それは彼らの視界に浮かんだ恐怖の命令に過ぎなかった。彼らはひれ伏し、自分たちの狂った行為を大いに嘆いた。そして、彼らの神経はひどく緩み、逃げることができなかった。ここで、これらの邪悪な悪党たちに行使された神の力と、ローマ人の幸運について主に考えるべきである。なぜなら、これらの暴君たちは、今や自分たちの力で持っていた安全を完全に奪い、力ずくで、あるいは飢餓以外の方法では決して捕らえられなかった塔から自らの意志で降りてきたからである。そして、ローマ人は、弱い城壁にあれほど苦労したにもかかわらず、幸運によって、彼らの機械では決して得られなかったものを手に入れたのです。なぜなら、これらの塔のうち 3 つは、上で述べたようなあらゆる機械式エンジンでは強固すぎたからです。

5\. そこで彼らは、自らこれらの塔を去り、というよりはむしろ神自身によって塔から追い出され、シロアムの下の谷にすぐに逃げ、そこでしばらくの恐怖から立ち直り、その側にあるローマの城壁のその部分に向かって激しく突進した。しかし、勇気があまりにも落ち込んで十分な力で攻撃することができず、恐怖と苦悩で力が弱まったため、彼らは衛兵に撃退され、互いに離れて散り散りになり、地下の洞窟に降りていった。こうしてローマ軍は城壁の支配者となり、両者とも塔に旗を立て、この戦争の終わりが始まったときよりもずっと楽だったと、勝利を喜びの声をあげた。というのも、最後の城壁にたどり着いたとき、彼らは流血もなく、自分たちが見つけた真実をほとんど信じることができなかったからである。しかし、彼らに対抗する者が誰もいないのを見て、彼らはこのような異常な孤独が何を意味するのか疑問に思った。しかし、彼らは剣を抜いて大勢で街の路地に進み、外で追いついた人々を殺し、ユダヤ人が逃げた家に火を放ち、そこにいたすべての魂を焼き、残りの多くの人々を荒廃させた。そして、略奪するために家々にやって来たとき、彼らは家の中で家族全員が死んでおり、上の部屋は飢餓で死んだ人々の死体でいっぱいだった。彼らはこの光景に恐怖し、何も手を付けずに出て行った。しかし、彼らはこのようにして殺された人々に対して同情したが、まだ生きている人々に対して同じ気持ちはなかった。彼らは出会ったすべての人を襲い、死体で路地をふさいで、街全体を血で染めた。実際、多くの家の火はこれらの人々の血で消されたほどだった。そして実際、殺人者たちは夕方には撤退したが、夜の間に火は激しく燃え盛った。そしてすべてが燃えている中、ゴルピオス（エルル）の月8日がエルサレムに到来した。この包囲戦の間、エルサレムは多くの悲惨な目に遭いがちだった。もしエルサレムが最初の建設以来ずっとこれほど幸福を享受していたなら、間違いなく世界の羨望の的になっていただろう。また、この都市がこのような悲惨な運命をたどったのは、この都市の打倒のきっかけとなったような世代を生み出したからである。

### 第9章

> シーザーが市内に入ったときに出した命令。捕虜の数と包囲中に死んだ者の数。また、地下の洞窟に逃げた者についても。その中には暴君シモンとヨハネもいた。

1\. さて、ティトゥスがこの \[上\] の町に着いたとき、彼はその町のいくつかの強固な場所だけでなく、特に暴君たちが狂気の行為で放棄したあの強固な塔に感心した。なぜなら、その塔の高さ、それぞれの石の大きさ、接合部の正確さ、またその幅の広さ、長さの広さを見て、彼は次のように述べた。「この戦争では確かに神が我々の助けになった。ユダヤ人をこれらの要塞から追い出したのは神に他ならない。人間の手や機械でこれらの塔を倒すなんてできるだろうか。」そのとき、彼は友人たちにそのような話を何度もした。また、暴君たちに縛られて牢獄に残されていた者たちを解放した。結局、彼は都市の残りの部分を完全に破壊し、その壁を倒した後、これらの塔を彼の幸運の記念碑として残しました。それは彼の援軍が功を奏し、他の方法では奪取できなかったものを獲得することを可能にしたのです。

2\. さて、兵士たちはすでに人を殺すことにすっかり疲れていたが、それでもまだ大勢が生き残っているようだったので、カエサルは、武器を持って抵抗する者以外は殺さず、残りは生け捕りにするよう命令した。しかし、殺害命令を受けた者とともに、老人や病弱者も殺した。しかし、栄えある年齢で自分たちに役立ちそうな者たちは、一緒に神殿に追い込み、女たちの庭の壁の中に閉じ込めた。その庭には、カエサルの解放奴隷の一人と、友人の一人であるフロントを置いた。フロントは、それぞれの功績に応じて、各人の運命を決めることになっていた。そこでフロントは、互いに弾劾されていた反逆者や盗賊を皆殺しにしたが、若者の中からは背が高くて美しい者を選び、凱旋式のために残しておいた。残りの十七歳以上の民衆は監禁し、エジプトの鉱山へ送った。31ティトゥスはまた、多くの民衆を贈り物として各州に送り、劇場で剣と野獣で彼らを滅ぼそうとしたが、十七歳以下の者は奴隷として売られた。 さて、フロントがこれらの人々を区別していた日々の間に、一万一千人が食糧不足で死んだ。彼らの中には、衛兵が彼らに抱いた憎しみのために、食物を口にしない者もいたし、また、食物を与えられても受け取ろうとしない者もいた。 民衆は非常に多く、彼らは食料となる穀物さえも欠乏していた。

3\. さて、この戦争中に捕虜となった者の数は、合計で9万7千人であった。包囲戦中に亡くなった者の数は110万人で、その大部分は確かに同じ民族であったが、エルサレム市民ではなかった。彼らは無酵母パンの祭りのために全国からやって来たが、突然軍隊に閉じ込められ、最初は非常に窮地に陥り、疫病による壊滅に見舞われ、その後すぐに飢饉が起こり、さらに急激に壊滅した。この都市にこれほど多くの人々を収容できたことは、ケスティウスの指揮下で捕らえられた者の数からも明らかである。ケスティウスは、この都市の力をネロに知らせたいと考え、そうでなければこの民族を軽蔑する気になっていたネロに、可能であれば、大祭司たちに全群衆の人数を数えてほしいと頼んだ。そこで、これらの大祭司たちは、過越祭と呼ばれる祭りが近づくと、第九時から第十一時まで、犠牲をほふるが、各犠牲につき十人以上の集団が参加することになる（彼らが自分たちだけで祭りをすることは許されていないからである）。そして、私たちの多くは、一つの集団に二十人いるが、犠牲の数は二十五万六千五百人であることに気づいた。これは、一緒に祭りを開いた十人以下を考慮すると、清く聖なる者たちの数は二百七十万二百人になる。なぜなら、らい病や淋病にかかっている者、月経のある女、その他汚れた者たちは、この犠牲にあずかることは許されていないからである。また、礼拝するためにここに来る外国人も同様である。

4\. さて、この膨大な群衆は確かに遠く離れた場所から集められたが、今や全国民は運命によって牢獄のように閉じ込められ、ローマ軍は住民で混雑した都市を包囲した。したがって、そこで死んだ人々の数は、人間や神がこれまでに世界にもたらしたすべての破壊を上回るものであった。公に知られていることだけを言えば、ローマ人は彼らのうちの何人かを殺し、何人かを捕虜にし、他の何人かは地中を捜索し、彼らがどこにいるかを見つけると、地面を掘り起こして出会った者すべてを殺した。また、2000人以上がそこで殺されたのが発見されたが、一部は彼ら自身の手で、一部は互いの手で殺されたが、主に飢饉によって殺された。しかし、死体の悪臭は、そこに立ち寄った者たちにとって非常に不快なものであったため、ある者はすぐに逃げざるを得なかったが、他の者は利益を貪欲に求め、山積みになった死体の間に入ってはそれを踏みつけた。なぜなら、これらの洞窟には大量の財宝が見つかり、利益を期待していたため、それを得るためのあらゆる手段が合法とみなされたからである。また、暴君たちによって牢に入れられていた者たちの多くが今や連れ出された。彼らは最後の最後まで野蛮な残虐行為をやめなかったからである。しかし、神は正義にかなう方法で、彼ら両方に復讐した。ヨハネはというと、この洞窟で兄弟たちとともに食料を欲し、これまで何度も傲慢に拒絶してきたローマ人に、今度は自分の安全のために右手を差し伸べてくれるよう懇願した。しかしシモンは、苦境に立たされながらも必死に抵抗しましたが、後に述べるように、降伏せざるを得ませんでした。そのため、勝利のときまで留置され、その後殺害されることになりました。ヨハネも同様に、永久の投獄を宣告されました。そして今、ローマ軍は都市の端に火を放ち、都市を焼き払い、城壁を完全に破壊しました。

### 第10章

> エルサレムの町はこれまで 5 回占領されたが、今回は 2 度目の荒廃であった。その歴史の簡潔な説明。

1\. こうしてエルサレムはウェスパシアヌス帝の治世の二年目、ゴルペイオスの月\[エルル\]の八日目に陥落した。この都市はそれ以前にも五回陥落していたが、荒廃したのは二度目であった。エジプト王シシャク、その後アンティオコス、その後ポンペイウス、その後ソシウスとヘロデが都市を陥落させたが、それでもなおそれを保持した。しかしこれらすべての前に、バビロン王がこれを征服し、建設後千四百六十八年六ヶ月でこれを荒廃させた。しかし、最初にこれを建設したのはカナン人の間で有力な人物であり、我々の言葉で\[メルキセデク\]、正義の王と呼ばれている。まさにそのような人物であった。そのため彼は\[そこに\]神の最初の祭司であり、最初に神殿を建設し、\[そこに\] かつてサレム と呼ばれていたその都市をエルサレムと名付けた。しかし、ユダヤ人の王ダビデはカナン人を追い出し、そこに自らの民を住まわせた。ダビデの治世後477年6か月で、バビロニア人によって完全に破壊された。そこで統治した最初のユダヤ人であるダビデ王からティトゥスによるこの破壊までは1179年であったが、最初の建設からこの最後の破壊までは2177年であった。しかし、その非常に古い歴史も、その莫大な富も、居住可能な地球全体に広がったその国民の広がりも、宗教上の理由でそこに払われた崇敬の深さも、それを破壊から守るのに十分ではなかった。こうしてエルサレムの包囲は終わった。

(2024.12.4) 脚注省略

## 第七巻

### 第1章

### 第2章

### 第3章

### 第4章

### 第5章

### 第6章

### 第7章

### 第8章

### 第9章

### 第10章

### 第11章
