# トマスの福音書

> **The Gospel of Thomas**
>
> [Early Christian Writings](https://www.earlychristianwritings.com) （初期キリスト教文書）サイトの The Gospel of Thomas （トマスによる福音書）に関してまとめたページ中の [Berlin Working Group for Coptic Gnostic Writings](https://www.earlychristianwritings.com/text/thomas-fifth.html) （コプト語によるグノーシス文書のベルリン作業グループによる英訳）から Google Chrome の翻訳機能で日本語化し、その後多少修正したものです。

これらは、生きているイエスが語った隠された言葉です。\
そして、ディディモス・ユダ・トマスがそれを書き記しました。

\(01\) そして彼は言った。「これらの言葉の意味を知る者は死を味わうことはないだろう。」

\(02\) イエスはこう言っています。\
(1) 「探し求める者は、見つけるまで探し続けることをやめてはならない。\
(2) 見つけたとき、彼は落胆する。\
(3) 落胆したとき、彼は驚く。\
(4) そして、彼は万物の王となる。」

\(03\) イエスはこう言っています。\
(1) 「あなたたちを導く者たちが、『見よ、王国は天にある』と言うなら\
、空の鳥があなたたちより先に行くでしょう。\
(2) 彼らが、『それは海にある』と言うなら、魚があなたたちより先に行くでしょう。\
(3) むしろ、王国はあなたたちの内にもあり、外にもあります。」\
(4) 「あなたたちが自分自身を知れば、あなたたちは知られるようになり、\
あなたたちは生ける父の子供であることを悟るでしょう。\
(5) しかし、あなたたちが自分自身を知らないなら、あなたたちは貧しく、あなたたちは貧しくなっています。」

\(04\) イエスはこう言っています。\
(1) 「年老いた人は、ためらうことなく、生後七日目の幼子に命の場所について尋ね、そして彼は生きる。\
(2) 多くの最初の者が最後となり、(3) 一人の人間となる。」

\(05\) イエスはこう言っています。\
(1) 「あなたの前にあるものを知りなさい。そうすれば、\
あなたから隠されているものは、あなたに対して明らかになります。\
(2) 隠されているもので、明らかにならないものは何もありません。」

(06)\
(1) 弟子たちはイエスに尋ねた。\
「断食をすべきでしょうか。\
また、どのように祈り、施しをすべきでしょうか。\
また、どのような食事を守るべきでしょうか。」\
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--\
(2) イエスはこう言われました。「偽りを言ってはならない。 (3) 憎むことをしてはならない。\
(4) すべては、真理によって明らかにされるからである。\
(5) 隠されたもので、あらわにならないものは一つもない。\
(6) 隠されたもので、あらわにならないものは一つもない。」

\(07\) イエスはこう言っています。\
(1) 「人に食べられ、ライオンが人間になるライオンは幸いです。\
(2) ライオンに食べられ、ライオンが人間になる人は呪われています。」

(08)\
(1) そして彼は言う。「人間は、\
海に網を投げて、海から小さな魚でいっぱいの網を引き上げた賢い漁師のようなものである。\
(2) 賢い漁師は、その中に大きな良い魚を見つけた。\
(3) 彼はすべての小さな魚を海に投げ戻し、大きな魚を楽々と選んだ。\
(4) 聞く耳のある者は聞くべきである。」

\(09\) イエスはこう言われます。\
(1) 「見よ、種まき人が出て行き、手いっぱいに種をまいた。\
(2) ある種は道に落ち、鳥が来てついばんだ。\
(3) ほかの種は岩の上に落ち、土に根を張らず、穂も出なかった。\
(4) ほかの種は茨の中に落ち、茨が種をふさいでしまい、虫がそれを食べた。\
(5) ほかの種は良い土に落ち、良い実を結び、\
一枡に六十、一枡に百二十の実を結んだ。」

\(10\) イエスはこう言っています。「わたしは世界に火を投げ込んだ。そして見よ、わたしはそれが燃え尽きるまで見守っている。」

\(11\) イエスは言いました:\
(1) 「この天は滅び、その上にある天も滅びる。\
(2) 死者は生き返らず、生きている者は死なない。\
(3) あなたがたは死んだものを食べた日に、それを生かした。あなた\
がたが光の中にいるとき、何をするのか。\
(4) あなたがたが一つであったその日に、二つになった。\
しかし二つになったとき、何をするのか。

(12)\
(1) 弟子たちはイエスに言った。「私たちは、あなたが私たちから去って行かれることを知っています。\
では、だれが私たちを治めるのでしょうか。」\
(2) イエスは彼らに言った。「あなたたちはどこから来たのかは関係なく、義人ヤコブのところに行きなさい\
。彼のために天と地が創造されたのです。」

(13)\
(1) イエスは弟子たちに言われた。「私と比べて、私が誰に似ているか教えてください。」\
(2) シモン・ペテロはイエスに言った。「あなたは正しい使者のようです。」\
(3) マタイはイエスに言った。「あなたは（特に）賢い哲学者のようです。」\
(4) トマスはイエスに言った。\
「先生、あなたは誰に似ているか、私にはとても言えません。」\
(5) イエスは言われた。「私はあなたの先生ではありません。あなたは\
私が測り出した湧き出る泉で飲んだのです。」\
(6) そしてイエスはトマスを捕らえ、退いて、彼に三つの言葉を告げた。\
(7) しかしトマスが仲間のところに戻って来ると、彼らは彼に尋ねた。\
「イエスはあなたたちに何と言いましたか。」\
(8) トマスは彼らに言った。「もし私が彼が私に言った言葉の一つでもあなたたちに話せば、\
あなたたちは石を拾い上げて私に投げつけるでしょう\
。すると石から火が出て、あなたたちを焼き尽くすでしょう。」

\(14\) イエスは彼らに言われた。\
(1)「あなたがたが断食すれば、自分自身に罪を生じさせる。\
(2) また、あなたがたが祈れば、罪に定められる。\
(3) また、あなたがたが施しをすれば、自分の霊に害を及ぼす。\
(4) また、あなたがたがどこかの土地に行き、あちこちをさまよい歩くとき、もし人々があなたがたを受け入れたら、\
彼らが出すものを食べなさい。また、彼らの中の病人をいやしなさい。\
(5) あなたがたの口に入るものは、あなたがたを汚さない。\
かえって、あなたがたの口から出るものが、あなたがたを汚す。」

\(15\) イエスは言いました。「女から生まれなかった者を見たら、\
ひれ伏して拝みなさい。その者こそあなたがたの父である。」

\(16\) イエスはこう言われます。\
(1) 「人々は、わたしが地上に平和をもたらすために来たと思っているかもしれません。\
(2) しかし、わたしが地上に争い、火、剣、戦争をもたらすために来たことを彼らは知りません。\
(3) 一つの家に五人いるでしょう。三人が二人に、二人が三人に、\
父が息子に、息子が父に敵対するでしょう。\
(4) そして彼らは孤独な者のように立ちます。」

\(17\) イエスはこう言われます。「わたしは、目が見たことのないもの、耳が聞いたことのないもの、\
手が触れたことのないもの、人の心に思い浮かんだことのないものをあなたに与えます。」

(18)\
(1) 弟子たちはイエスに言った。「私たちの終わりはどうなるのか教えてください。」\
(2) イエスは言った。「あなたは、終わりについて今尋ねていますが、すでに初めを見つけたのですか。\
初めがあるところに終わりもあるからです。\
(3) 初めに立つ人は幸いです。\
その人は終わりを知り、死を味わうことはありません。」

\(19\) イエスは言いました: (1)「存在する前に存在していた者に祝福あれ。\
(2) もしあなたがたがわたしの弟子となり、わたしの言葉に耳を傾けるならば、これらの石はあなたがたの役に立つであろう。\
(3) あなたがたの楽園には、夏も冬も形を変えず、\
葉も落ちない五つの木がある。 (4) それを知る者は死を味わうことはない。」

(20)\
(1) 弟子たちはイエスに言った。「天国はだれに似ているか教えてください。」\
(2) イエスは彼らに言われた。「それはからし種のようなものです。 (3) \<それは\>すべての種の中で最も小さいものです。\
(4) しかし、耕された土に落ちると、大きな枝を出して\
、空の鳥の隠れ家になります。」

(21)\
(1) マリアはイエスに言った。「あなたの弟子たちはだれに似ていますか。」\
(2) イエスは言った。「彼らは、自分のものではない畑を託された召使のようなものです。\
(3) 畑の所有者がやって来て、『畑をください』と言うでしょう。\
(4) (しかし) 所有者は、それを彼らに譲るために\
、そして畑を彼らに与えるために、彼らの前で裸になります。」\
(5) 「だから私は言います。『家の主人は、泥棒が\
来るのが近づいていると知ると、泥棒が来る前に警戒し、泥棒が\
自分の家、自分の領地に押し入って財産を盗み去ることを許さないでしょう。』\
(6) (しかし) あなたは、世に対して警戒しなさい。\
(7) 腰に力強く帯を締めなさい。そうすれば、泥棒はあなたに近づく方法を見つけないでしょう。」\
(8) 「あなたがたが待ち望んでいるものは、必ず見つかるであろう。\
(9) あなたがたの中には、賢い人がいるはずだ。\
(10) 果物が熟したとき、彼は鎌を手に持って急いでやって来て、それを収穫した。\
(11) 聞く耳のある者は、聞くがよい。」

(22)\
(1) イエスは乳飲み子をご覧になった。\
(2) 弟子たちに言われた 。\
「乳飲み子であるこれらの幼子たちは、神の国に入る者たちのようです。」\
(3) 彼らは言った。「では、私たちは幼子として神の国に入るのでしょうか。」\
(4) イエスは彼らに言われた。「二つを一つにし、\
内を外のように、外を内のように\
、上を下のようにする。\
(5) すなわち、男と女を一つにして、\
男が男でなく、女が女でないようにする。\
(6) 目の代わりに目を\
、手の代わりに手を、足の代わりに足を、\
像の代わりに像を造る。 (7) そのとき、あなたたちは神の国に入るのです。」

\(23\) イエスはこう言われます。\
(1)「わたしはあなたたちを千人の中から一人、万人の中から二人を選ぶ。\
(2) そして彼らは一人のようになる。」

(24)\
(1) 弟子たちは言った。「あなたのおられる場所を教えてください。\
私たちはそれを探す必要があります。\
」 (2) イエスは彼らに言われた。「耳のある者は聞きなさい。\
(3) 光のある人の内には光があり、その人は全世界を照らします。\
もし輝かなければ、暗闇があります。」

\(25\) イエスはこう言っています。\
(1)「あなたの兄弟をあなたの命のように愛しなさい！\
(2) 彼をあなたの目のひとみのように守りなさい！」

\(26\) イエスはこう言っています。\
(1)「あなたは兄弟の目にある木片は見える\
が、自分の目にある梁は見えない。\
(2) 自分の目から梁を取り除けば、\
兄弟の目から木片を取り除くことができるようになる。」

(27)\
(1)「もし世を離れなければ、あなたたちは神の国を見つけることはできない。\
(2) もし安息日を安息日としなければ、あなたたちは父を見ることはないだろう。」

\(28\) イエスはこう言っています。\
(1) 「私は世界の中心に立ち、肉体をも​​って彼らに現れた。\
(2) 彼らがみな酔っているのを見つけた。渇いている者は一人もいなかった。\
(3) わたしの心は人類の子らのために痛んだ。\
彼らは心が盲目で、何も見えないからである。\
彼らは空っぽのままでこの世に生まれ、\
空っぽのままでこの世を去ろうとしている。\
(4) しかし、今は酔っている。\
(しかし) 酒を振り払えば、考えが変わるだろう。」

\(29\) イエスはこう言っています。\
(1)「もし肉が霊によって存在するようになったのなら、それは不思議です。\
(2) しかし、もし霊が肉体によって存在するようになったのなら、それは不思議の中の不思議です。\
(3) しかし、この貧しさの中に、どうしてこれほどの富が宿ったのか、私は不思議に思います。」

\(30\) イエスはこう言っています。\
(1)「三人の神がいるところには、彼らは神である。\
(2) 二人か一人の神がいるところには、わたしも共にいる。」

\(31\) イエスはこう言っています。\
(1)「預言者は自分の村では受け入れられない。\
(2) 医者は自分を知っている者を治さない。」

\(32\) イエスはこう言っています。「高い山の上に建てられ、要塞化された町は倒れることも、隠れることもできない。」

\(33\) イエスはこう言われます。\
(1)「あなたがたの耳で聞くことを、屋根の上から告げ知らせなさい。\
(2) だれも、ともしびをともして枡の下に置いたり、隠れた所に置いたりはしない。\
(3) むしろ、出入りするすべての人がその光を見ることができるように、それを燭台の上に置くのだ。」

\(34\) イエスはこう言っています。「盲人が盲人を導くと、二人とも穴に落ちてしまいます。」

\(35\) イエスはこう言っています。\
(1)「だれでも、強い人の家に入って、\
その人の手を縛らない限り、それを力ずくで奪うことはできない。\
(2) そうすれば、その人の家を略奪するだろう。」

\(36\) イエスはこう言っています。「朝から晩まで、夕から朝まで、何を着ようかと心配してはいけません。」

\(37\) \
(1) 弟子たちは言った。「あなたはいつ私たちの前に現れるのですか。私たちはいつあなたに会えるのですか。」\
(2) イエスは言った。「あなたがたが恥ずかしがらずに衣服を脱ぎ、\
幼子のようにそれを足の下に置き、踏みつけるならば、\
(3) そのとき、生ける者の子を見るであろう。そして、恐れることはないであろう。」

\(38\) イエスはこう言っています。\
(1)「あなたたちは、私があなたたちに話しているこれらの言葉を何度も聞きたいと望んだが\
、それを聞く人が他にはいなかった。\
(2) あなたたちが私を探しても、私を見つけられない日が来るだろう。」

\(39\) イエスはこう言っています。\
(1)「パリサイ人や律法学者たちは知識の鍵を受け取っていたが、それを隠してしまった。\
(2) 彼らは入ることができず、また入ることを望む者にも入らせなかった。\
(3) しかし、あなたたちは蛇のように賢く、鳩のように純真であれ！」

\(40\) イエスはこう言っています。\
(1)「ぶどうの木は父の外（ぶどう園）に植えられました。\
(2) 支えがないので、根こそぎ引き抜かれ、枯れてしまいます。」

\(41\) イエスはこう言っています。\
(1)「手に何かを持っている人には、さらに何かが与えられる。\
(2) 何も持っていない人には、持っているわずかなものさえも取り上げられる。」

\(42\) イエスは言いました。「通り過ぎる人になりなさい。」

(43)\
(1) 弟子たちはイエスに言った。「私たちにそんなことを言うあなたは、いったい何者ですか。\
(2) 私があなた方に話していることから、私が誰であるかが分からないのですか。\
(3) しかし、あなた方はユダヤ人のようになってしまいました\
。彼らは木は愛するが\
、その実を憎むのです。あるいは、実は愛するが、木を憎むのです。」

\(44\) イエスはこう言っています。\
(1)「父を冒涜する者は、だれでも許される。\
(2) 子を冒涜する者は、だれでも許される。\
(3) しかし、聖霊を冒涜する者は、地上でも天でも、決して許されない。」

\(45\) イエスはこう言っています。\
(1) 「いばらからはぶどうは収穫されず、あざみからはいちじくは採れません。それらは実を結ばないからです。(2) 善人は自分の宝物から善を出します。(3) 悪人は自分の心にある悪い宝物から悪を出します。そして悪を語ります。(4) 心の豊かさから悪が出てくるのです。」

\(46\) イエスはこう言っています。\
(1) 「アダムから洗礼者ヨハネに至るまで、女から生まれた者の中で、洗礼者ヨハネを超える者は一人もいません。そのため、彼（つまり、ヨハネ）は目を伏せる必要はありません。(2) しかし、私はこうも言っています。『あなたたちのうちで小さくなる者は、神の国を知り、ヨハネを超えるでしょう。』」

\(47\) イエスはこう言っています。\
(1) 「人が二頭の馬に乗り、二本の弓を伸ばすことは不可能である。(2) しもべが二人の主人に仕えることも不可能である。さもなければ、一方を敬い、他方を侮辱するであろう。(3) だれも古いぶどう酒を飲んで、すぐに新しいぶどう酒を飲みたがることはない。(4) 新しいぶどう酒を古い皮袋に入れてはならない。そうすれば、皮袋は破れない。また、古いぶどう酒を新しい皮袋に入れてはならない。そうすれば、皮袋は腐らない。(5) 古い継ぎはぎを新しい服に縫い付けてはならない。そうすれば、破れてしまう。」

\(48\) イエスはこう言っています。「もし二人が同じ家で互いに和平を結ぶなら、\
彼らは山に向かって『立ち去れ』と言えば、山は立ち去るであろう。」

\(49\) イエスはこう言っています。\
(1)「孤独な者、選ばれた者たちは幸いである。あなた方は神の国を見つけるであろう。\
(2) あなた方はそこから来て、またそこに帰るであろう。」

\(50\) イエスは言いました:\
(1) もし彼らがあなた方に「あなたはどこから来たのか」と尋ねたら、こう言いなさい。「私たちは光から来たのです。光はひとりでに生まれ、自らを定め、その姿に現れたのです。」\
(2) もし彼らがあなた方に「それはあなたですか」と尋ねたら、こう言いなさい。「私たちは彼の子供であり、生ける父に選ばれた者です。」\
(3) もし彼らがあなた方に「あなた方の間にある父のしるしは何ですか」と尋ねたら、こう言いなさい。「それは動きと静けさです。」

(51)\
(1) 弟子たちはイエスに言った。「死者の復活はいつ起こるのでしょうか。新しい世界はいつ来るのでしょうか？」\
(2) イエスは彼らに言われた。「あなたがたが待ち望んでいるもの（復活）は（すでに）来たが、あなたがたはそれを認識していない。」

(52)\
(1) 弟子たちはイエスに言った。「イスラエルでは24人の預言者が語っており、皆あなたを通して語ったのです。」\
(2) イエスは弟子たちに言った。「あなたたちは生きている者を自分たちから遠ざけ、死んだ者たちについて語り始めたのです。」

\(53\) \
(1) 弟子たちはイエスに言った。「割礼は有益でしょうか、それとも有害でしょうか。」\
(2) イエスは彼らに言われた。「有益であれば、父親は母親から割礼を受けて子供をもうけるでしょう。\
(3) しかし、真の霊による割礼は、すべてのものに勝っています。」

\(54\) イエスは言いました。「貧しい人々は幸いです。天国はあなた方のものです。」

\(55\) イエスはこう言っています。\
(1)「自分の父と母を憎まない者は、わたしの弟子になることはできません。\
(2) 兄弟、姉妹を憎まず、わたしのように自分の十字架を負わない者は、わたしにふさわしくありません。」

\(56\) イエスは言いました。\
「世を知るようになった者は、死体を見つけたのです。\
そして、（この）死体を見つけた者にとって、世は価値がありません。」

\(57\) イエスはこう言っています。\
(1) 「父の王国は、良い種を蒔いた人のようなものです。\
(2) 彼の敵は夜中にやって来て、良い種の間に毒麦を蒔きました。\
(3) その人は、(召使たちが) 毒麦を引き抜くことを許しませんでした。\
彼は彼らに言いました。『毒麦を引き抜きに行って、小麦も一緒に引き抜かないように。』\
(4) 収穫の日に、毒麦は明らかになり、引き抜かれ、焼かれます。」

\(58\) イエスはこう言っています。「苦労した人は幸いだ。その人は命を見つけたのだ。」

\(59\) イエスは言いました。「生きている間に生ける者を待ち望みなさい。\
そうしないと、死んでから彼を見ようとします。\
しかし、あなたは彼を見ることができないでしょう。」

(60)\
(1) \<イエスは\>、ユダヤへ向かう途中、あるサマリア人が子羊を盗もうとしているのを見た。\
(2) イエスは弟子たちに言った。「あの人は子羊を狙っている。」\
(3) 彼らはイエスに言った。「それを殺して食べるためです。」\
(4) イエスは彼らに言った。「生きている間は食べない。殺して死体になった時だけ。」\
(5) 彼らはイエスに言った。「そうでなければ、それはできない。」\
(6) イエスは彼らに言った。「あなたたちも、死体になって食べられないように、休む場所を探しなさい。」

(61)\
(1) イエスは言った。「二人は一つの寝床に横たわり、一人は死に、もう一人は生きる。」\
(2) サロメは言った。「（それで）あなたは何者ですか？\
あなたは私の寝床に＜よそ者＞として座り、私の食卓から食事をしたのです。」\
(3) イエスは彼女に言った。「私は（常に）同じ方から来た者です。\
私は父のものの一部を与えられました。」\
(4) 「私はあなたの弟子です！」\
(5) 「それゆえ私は言います。もし誰かが＜神＞のようになるなら、彼は光に満ちるでしょう。\
しかしもし彼が（神から）離れた者となるなら、彼は闇に満ちるでしょう。」

\(62\) イエスはこう言っています。\
(1)「私は、私の奥義を、それを知るにふさわしい者に語る。」\
(2)「あなたの右の手が何をしようとも、あなたの左の手はそれを知らないはずである。」

\(63\) イエスはこう言っています。\
(1) 「ある金持ちがいて、たくさんの財産を持っていました。\
(2) 彼は言いました。『私は自分の財産を使って種を蒔き、刈り入れ、植え、\
そして果実で倉を満たし、何一つ欠けることがないようにしよう。』\
(3) 彼は心の中でこのように考えていました。そしてその夜、彼は亡くなりました。\
(4) 耳のある者は聞くがよい。」

\(64\) イエスはこう言っています。

\(1\) 「ある人に客がいた。食事の用意が終わると、\
召使を遣わして客を招かせた。\
(2) 召使は最初の人のところに来て言った。『主人があなたを招いています。』\
(3) 召使は言った。『私は商人たちに請求書を送っています。彼らは今晩私のところに来る予定です。私は行って彼らに指示を出します。食事には参加しません。』\
(4) 召使は別の人のところに来て言った。『主人があなたを招いています。』\
(5) 召使は言った。『私は家を買ったのですが、一日だけ呼び出されました。時間がありません。』\
(6) 召使は別の人のところに行って言った。『主人があなたを招いています。』\
(7) 召使は言った。『友人が結婚することになっており、私は食事の用意をすることになっています。私は行けません。食事には参加しません。』\
(8) 彼は別の人のところへ行き、こう言った。「主人があなたを招待しています。」\
(9) 彼は言った。「私は村を買ったのですが、家賃を取りに行くので行けません。すみません。」\
(10) 召使いは立ち去り、主人に言った。\
「あなたが食事に招待した人たちは、欠席したいと言っています。」\
(11) 主人は召使いに言った。「道に出て行き、\
見つけた人を連れてきて、食事に付き合ってもらいなさい。」\
(12) 商人や商売人は私の父の所に入ることはできません。」

\(65\) 彼は言いました。「ある高利貸しがぶどう園を所有していました。彼はそれを農民に与え、農民に耕作させ、収穫物を受け取らせようとしました。(2) 彼は農民にぶどう園の収穫物を渡すよう、自分の召使いを送りました。(3) 彼らは召使いを捕らえ、殴打し、殺しそうになりました。召使いは戻って主人に告げました。\
(4) 主人は言いました。『彼らは彼を知らなかったのかもしれない。』\
(5) 彼は別の召使いを送りましたが、農民たちはその召使いも殴りました。\
(6) そこで主人は息​​子を送り、こう言いました。『彼らは私の息子に敬意を示すかもしれない。』\
(7) (しかし) 農民たちは、彼がぶどう園の相続人であることを知っていたので、彼を捕らえ、殺しました。\
(8) 耳のある者は聞くがよい。」

\(66\) イエスは言いました。「建築者たちが捨てた石を見せなさい。それが礎石です。」

\(67\) イエスは言いました。「すべてを知っている人が何か一つでも欠けているなら、その人はすでにすべてを欠いているのです。」

\(68\) イエスはこう言っています。\
(1)「彼らがあなた方を憎み、迫害する時、あなた方は幸いです。\
(2) しかし、彼ら自身は、あなた方を迫害した場所に居場所を見つけることはできないでしょう。」

\(69\) イエスはこう言っています。\
(1)「心の中で迫害されてきた人々は幸いである。\
彼らこそ真に父を知るようになった人々である。」\
(2)「望む者の腹が満たされるように飢えに苦しむ人々は幸いである。」

\(70\) イエスはこう言っています。\
(1)「もしあなたがそれを自分の内に生み出すなら、あなたが持っているものがあなたを救うでしょう。\
(2) もしあなたがそれを自分の内に生み出さないなら、あなたの内に持っていないものがあなたを殺すでしょう。」

\(71\) イエスはこう言われました。「わたしはこの家を壊す。そして、だれもそれを建てることはできない。」

\(72\) \
(1) ある人が彼に言った。「私の兄弟たちに、父の財産を私と分け合うように伝えてください。」\
(2) 彼は言った。「人よ、だれが私を分配者にしたのか？」\
(3) 彼は弟子たちのほうを向いて言った。「私は分配者ではないでしょう。」

\(73\) イエスはこう言っています。\
(a)「収穫は豊かだが、働き手が少ない。\
(b) しかし、収穫のために働き手を送ってくださるように主に願いなさい。」

\(74\) 彼は言った。「主よ、井戸の周りにはたくさんの人がいますが、井戸の中には何もありません。」

\(75\) イエスはこう言われました。「戸口には多くの人が立っているが、結婚式場に入るのは孤独な者たちだ。」

\(76\) イエスはこう言っています。\
(1) 「父の王国は、商品を 持っていて真珠を見つけた商人のようなものです。\
(2) その商人は賢明です。彼は商品を売り、自分のために真珠だけを買いました。\
(3) あなたも彼の宝を探しなさい。それは朽ちることなく、蛾も届かず、虫も食い尽くすことのできないところにとどまります。」

\(77\) イエスはこう言っています。\
(1)「私はすべての上にある光です。私はすべてです。\
すべては私から生まれました。そして、すべては私に来ました。」\
(2)「木を割ってみなさい。そこに私がいます。\
(3)石を持ち上げてみなさい。そこに私がいるでしょう。」

\(78\) イエスはこう言われました。\
(1)「なぜ田舎へ出かけたのか。風に揺れる葦を見るため、\
(2) 柔らかい衣を着た人を見るためか。\
(3) 彼らは柔らかい衣を着ており、真実を認識することはできない。」

(79)\
(1) 群衆の中の一人の女がイエスに言った。「あなたを宿した子宮と、あなたを養った乳房に栄光あれ。」\
(2) イエスは言われた。「父の御言葉を聞いて、それを忠実に守った人々に栄光あれ。\
(3) あなた方が『妊娠しなかった子宮と、乳を与えなかった乳房に栄光あれ』と言う日が来るであろう。」

\(80\) イエスはこう言っています。\
(1)「世を知る者は、（死）体を見つけたのです。\
(2) しかし、（死）体を見つけた者には、世はふさわしくありません。」

\(81\) イエスはこう言っています。\
(1)「富んだ者は王になるべきである。\
(2) 権力を持つ者はそれを放棄すべきである。」

\(82\) イエスはこう言っています。\
(1)「わたしに近い者は火に近い。\
(2) わたしから遠い者は神の国から遠い。」

\(83\) イエスは言う。\
(1)「像は人類に見えるが、その中にある光は像の中に隠されている。\
(2) 父の光は現れるが、父の像は光によって隠されている。」

\(84\) イエスはこう言っています。\
(1)「あなた方は、自分の似姿を見ると喜びに満たされる。(2) しかし、あなた方より前に存在していた自分の似姿を見ると、それらは死ぬことも、現れることもないのに、あなた方はどれほどのことを耐えることができるのか。」

\(85\) イエスはこう言っています。\
(1) 「アダムは偉大な力と富を持って生まれました。しかし、彼はあなた方にふさわしくありませんでした。\
(2) もし彼がふさわしかったなら、死を味わうことはなかったでしょう。」

\(86\) イエスはこう言っています。\
(1) 「\[狐には\]穴があり、鳥には巣がある。\
(2) しかし、人の子には頭を置いて休む場所がない。」

\(87\) イエスはこう言っています。\
(1)「肉体に依存する肉体は惨めである。\
(2) そして、この二つに依存する魂も惨めである。」

\(88\) イエスはこう言っています。\
(1) 「使徒と預言者たちがあなた方のもとに来て、あなた方に属するものをあなた方に与える。\
(2) そしてあなた方は、自分の手に持っているものを彼らに与え、心の中で言うのだ。\
『彼らはいつ来て、自分たちのものを取りに行くのだろうか。』」

\(89\) イエスは言いました：\
(1) 「なぜ杯の外側を洗うのですか？\
(2) 内側を作った方が外側も作ったのだということが分からないのですか？」

\(90\) イエスはこう言っています。\
(1) 「わたしのところに来なさい。わたしのくびきは柔らかく、わたしの支配は温和です。\
(2) そうすれば、あなたたちは安らぎを見いだすでしょう。」

\(91\) \
(1) 彼らは言った。「あなたが誰であるかを教えてください。そうすれば私たちはあなたを信じるでしょう。」\
(2) 彼は彼らに言った。「あなた方は天と地の面を調べます\
が、あなた方の前にいる方を認識していません。\
また、この機会をどう試すかを知りません。」

\(92\) イエスはこう言っています。\
(1) 「求めよ、そうすれば見つかるであろう。\
(2) しかし、あなたがたが昔わたしに尋ねたこと、\
また、あの日にわたしがあなたがたに話さなかったことを、\
わたしは今あなたがたに話そうと思っている。しかし、あなたがたはそれを求めないのだ。」

\(93\) \
(1) 「聖なるものを犬に与えてはならない。犬がそれを糞山に投げ捨ててしまうからである。\
(2) 豚に真珠を投げてはならない。豚が真珠を泥に変えてしまうからである。」

\(94\) イエスはこう言われます。\
(1) 「探す者は見つける。\
(2) 門をたたく者には開かれる。」

(95)［イエスはこう言っています：］\
(1) 「もしあなたがお金を持っているなら、それを利子を付けて貸してはいけません。\
(2) むしろ、あなたがそれを取り戻したくない人に与えなさい。」

\(96\) イエスはこう言われました。\
(1) 「父の王国は女のようなものです。\
(2) 彼女は少量のパン種を取り、それを生地の中に隠し、大きなパンを作りました。\
(3) 耳のある者は聞くべきです。」

\(97\) イエスはこう言っています。\
(1) 「\[父の\]王国は、小麦粉の入った\[壺\]を運んでいる女性のようなものです。\
(2) 彼女が道を歩いているとき、家から遠く離れたところで、\
壺の取っ手が壊れ、小麦粉が道に漏れ出しました。\
(3) (しかし) 彼女はそれを知りませんでした。彼女は問題に気付いていませんでした。\
(4) 家に着くと、壺を床に置くと、それが空であることがわかりました。」

\(98\) イエスはこう言っています。\
(1) 「父の王国は権力者を殺そうとした人のようなものです。\
(2) 彼は自分の家で剣を抜き、自分の手が（十分に）強いかどうかを試すために壁に突き刺しました。\
(3) そして権力者を殺しました。」

\(99\) \
(1) 弟子たちはイエスに言った。「あなたの兄弟とあなたの母が外に立っています。」\
(2) イエスは彼らに言われた。「ここにいる、わたしの父の御心を行う人たちが、わたしの兄弟、わたしの母です。\
(3) 彼らこそが、わたしの父の王国に入る者たちです。」

(100)\
(1) 彼らはイエスに金貨を見せて言った。「皇帝の民が私たちに税金を要求しています。」\
(2) イエスは彼らに言った。「皇帝のものは皇帝に与えなさい。\
(3) 神のものは神に与えなさい。\
(4) 私のものは私に与えなさい。」

(101)\
(1) 「わたしのように自分の父と母を憎まない者は、わたしの弟子となることはできない。\
(2) わたしのように自分の父と母を愛さない者は、わたしの弟子となることはできない。\
(3) わたしの母はわたしに命を与えたが、わたしの本当の母はわたしの母である。」

\(102\) イエスはこう言われました。「パリサイ人たちは災いである。彼らは牛の飼い葉桶の中で眠っている犬のようだ。犬は食べず、牛にも食べさせない。」

\(103\) イエスはこう言っています。「強盗が家のどこから侵入してくるかを知っている人は幸いだ。強盗が侵入する前に、立ち上がって自分の領地をまとめ、腰に帯を締めることができるからだ。」

\(104\) \
(1) 彼らはイエスに言った。「さあ、今日は祈りと断食をしましょう！」\
(2) イエスは言った。「私はどんな罪を犯したのですか、あるいは何に打ち負かされたのですか？\
(3) しかし、花婿が結婚式の部屋から出てきたら、（私たちは）断食して祈りましょう。」

\(105\) イエスはこう言っています。「父と母を知る者は、遊女の子と呼ばれるでしょう。」

\(106\) イエスはこう言っています。\
(1) 「あなたたちが二つを一つにすると、あなたたちは人の子となる。\
(2) そして、あなたたちが『山よ、去れ』と言うと、それは去るであろう。」

\(107\) イエスはこう言っています。\
(1) 「王国は百匹の羊を飼っている羊飼いのようなものです。\
(2) 羊飼いは百匹の羊のうち、一番大きな一匹が迷い出ました。そこで九十九匹を残して、一匹を探し求め、ついに見つけました。\
(3) 羊飼いは苦労の末、羊たちに言いました。『私は九十九匹よりもあなたたちを愛している。』」

\(108\) イエスはこう言っています。\
(1) 「わたしの口から飲む者は、わたしのようになる。\
(2) わたし自身がその人のようになる。\
(3) 隠されているものがその人に現れる。」

\(109\) イエスはこう言っています。\
(1) 「王国は、畑に宝を隠しているが、何も知らない人のようなものです。\
(2) そして、彼は死後、それを息子に残しました。(しかし)息子もそれを知りませんでした。\
彼はその畑を引き継いで、それを売りました。\
(3) それを買った人が来て、耕しているときに宝を見つけました。\
彼は望む人に利子を付けて金を貸し始めました。」

\(110\) イエスはこう言っています。「世を見つけて富を得た者は、世を捨てるべきだ。」

\(111\) イエスはこう言っています。\
(1) 「天と地はあなたの前で巻き上がる。\
(2) そして、生ける者から生かされている者は、死を見ることはない。」\
(3) イエスはこう言っていませんか。「自分自身を見つけた者には、世界は値しない。」

\(112\) イエスはこう言っています。\
(1) 「魂に依存する肉は災いである。\
(2) 肉に依存する魂は災いである。」

(113)\
(1) 弟子たちは彼に言った。「王国はいつ来るのでしょうか。\
(2) それは、待ち望んでいるだけでは来ません。\
(3) 彼らは『見よ、ここだ』とか『見よ、あそこだ』とは言いません。\
(4) 父の王国は地上に広がっていますが、人々はそれを見ません。」

(114)\
(1) シモン・ペテロは彼らに言った。「マリアを私たちから遠ざけなさい。女性は生きるに値しないからです。」\
(2) イエスは言った。「見よ、私は彼女を男にするために引き入れます。そうすれば、\
彼女もあなたと同じように、生きた男の霊となるでしょう。」\
(3) (しかし、私はあなた方に言います。)「男になったすべての女性は天国に入るでしょう。」
